return {
corail_pillar_extension_biomesoplenty_jj_biomesoplenty_plank_1=15,
corail_pillar_extension_biomesoplenty_jj_biomesoplenty_log_1=15,
corail_pillar_extension_biomesoplenty_jj_biomesoplenty_log_0=15,
corail_pillar_extension_biomesoplenty_jj_biomesoplenty_plank_0=15,
corail_pillar_extension_biomesoplenty_jj_biomesoplenty_gem_0=15,
corail_pillar_extension_biomesoplenty_jj_biomesoplenty_special_0=15
}