return {
 atlcraft_jj_atlcraft_bayberries={hasPattern=false,label="",tag=""},
 atlcraft_jj_atlcraft_bayberry_juice={hasPattern=true,label="Bayberry Juice",tag=""},
 atlcraft_jj_atlcraft_bayberry_plant={hasPattern=false,label="",tag=""},
 atlcraft_jj_atlcraft_bayberry_seeds={hasPattern=false,label="",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire={hasPattern=true,label="Cobblestone Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_andesite={hasPattern=true,label="Andesite Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_andesitesmooth={hasPattern=true,label="Polished Andesite Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_brick={hasPattern=true,label="Brick Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_castiron={hasPattern=true,label="Cast Iron Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_diamond={hasPattern=true,label="Diamond Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_diorite={hasPattern=true,label="Diorite Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_dioritesmooth={hasPattern=true,label="Polished Diorite Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_emerald={hasPattern=true,label="Emerald Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_endbrick={hasPattern=true,label="End Brick Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_endstone={hasPattern=true,label="End Stone Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_gold={hasPattern=true,label="Gold Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_granite={hasPattern=true,label="Granite Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_granitesmooth={hasPattern=true,label="Polished Granite Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_hardenedclay={hasPattern=true,label="Terracotta Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_hardenedclayblack={hasPattern=true,label="Black Terracotta Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_hardenedclayblue={hasPattern=true,label="Blue Terracotta Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_hardenedclaybrown={hasPattern=true,label="Brown Terracotta Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_hardenedclaycyan={hasPattern=true,label="Cyan Terracotta Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_hardenedclaygray={hasPattern=true,label="Gray Terracotta Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_hardenedclaygreen={hasPattern=true,label="Green Terracotta Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_hardenedclaylightblue={hasPattern=true,label="Light Blue Terracotta Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_hardenedclaylightgray={hasPattern=true,label="Light Gray Terracotta Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_hardenedclaylime={hasPattern=true,label="Lime Terracotta Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_hardenedclaymagenta={hasPattern=true,label="Magenta Terracotta Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_hardenedclayorange={hasPattern=true,label="Orange Terracotta Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_hardenedclaypink={hasPattern=true,label="Pink Terracotta Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_hardenedclaypurple={hasPattern=true,label="Purple Terracotta Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_hardenedclayred={hasPattern=true,label="Red Terracotta Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_hardenedclaywhite={hasPattern=true,label="White Terracotta Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_hardenedclayyellow={hasPattern=true,label="Yellow Terracotta Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_iron={hasPattern=true,label="Iron Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_lapis={hasPattern=true,label="Lapis Lazuli Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_mossstone={hasPattern=true,label="Moss Stone Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_mossstonebrick={hasPattern=true,label="Mossy Stone Brick Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_netherbrick={hasPattern=false,label="",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_netherrack={hasPattern=true,label="Netherrack Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_obsidian={hasPattern=true,label="Obsidian Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_prismarine={hasPattern=true,label="Prismarine Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_prismarinebrick={hasPattern=true,label="Prismarine Brick Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_prismarinedark={hasPattern=true,label="Dark Prismarine Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_purpur={hasPattern=true,label="Purpur Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_quartz={hasPattern=true,label="Quartz Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_quartzchiseled={hasPattern=true,label="Chiseled Quartz Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_rednetherbrick={hasPattern=true,label="Red Nether Brick Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_redsandstone={hasPattern=true,label="Red Sandstone Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_redstone={hasPattern=true,label="Redstone Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_sandstone={hasPattern=true,label="Sandstone Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_stone={hasPattern=true,label="Stone Bonfire",tag=""},
 atlcraft_jj_atlcraft_biglight1_bonfire_stonebrick={hasPattern=true,label="Stone Brick Bonfire",tag=""},
 atlcraft_jj_atlcraft_candle01_stone_black={hasPattern=true,label="Black Candle",tag=""},
 atlcraft_jj_atlcraft_candle01_stone_blue={hasPattern=true,label="Blue Candle",tag=""},
 atlcraft_jj_atlcraft_candle01_stone_brown={hasPattern=true,label="Brown Candle",tag=""},
 atlcraft_jj_atlcraft_candle01_stone_cyan={hasPattern=true,label="Cyan Candle",tag=""},
 atlcraft_jj_atlcraft_candle01_stone_green={hasPattern=true,label="Green Candle",tag=""},
 atlcraft_jj_atlcraft_candle01_stone_grey={hasPattern=true,label="Gray Candle",tag=""},
 atlcraft_jj_atlcraft_candle01_stone_lightblue={hasPattern=true,label="Light Blue Candle",tag=""},
 atlcraft_jj_atlcraft_candle01_stone_lightgrey={hasPattern=true,label="Silver Candle",tag=""},
 atlcraft_jj_atlcraft_candle01_stone_lime={hasPattern=true,label="Lime Candle",tag=""},
 atlcraft_jj_atlcraft_candle01_stone_magenta={hasPattern=true,label="Magenta Candle",tag=""},
 atlcraft_jj_atlcraft_candle01_stone_natural={hasPattern=false,label="",tag=""},
 atlcraft_jj_atlcraft_candle01_stone_orange={hasPattern=true,label="Orange Candle",tag=""},
 atlcraft_jj_atlcraft_candle01_stone_pink={hasPattern=true,label="Pink Candle",tag=""},
 atlcraft_jj_atlcraft_candle01_stone_purple={hasPattern=true,label="Purple Candle",tag=""},
 atlcraft_jj_atlcraft_candle01_stone_red={hasPattern=true,label="Red Candle",tag=""},
 atlcraft_jj_atlcraft_candle01_stone_white={hasPattern=true,label="White Candle",tag=""},
 atlcraft_jj_atlcraft_candle01_stone_yellow={hasPattern=true,label="Yellow Candle",tag=""},
 atlcraft_jj_atlcraft_candle02={hasPattern=true,label="Thin Cast Iron Candle",tag=""},
 atlcraft_jj_atlcraft_candle02_diamond={hasPattern=true,label="Thin Diamond Candle",tag=""},
 atlcraft_jj_atlcraft_candle02_emerald={hasPattern=true,label="Thin Emerald Candle",tag=""},
 atlcraft_jj_atlcraft_candle02_glass={hasPattern=true,label="Thin Glass Candle",tag=""},
 atlcraft_jj_atlcraft_candle02_gold={hasPattern=true,label="Thin Gold Candle",tag=""},
 atlcraft_jj_atlcraft_candle02_iron={hasPattern=true,label="Thin Iron Candle",tag=""},
 atlcraft_jj_atlcraft_candle02_lapis={hasPattern=true,label="Thin Lapis Lazuli Candle",tag=""},
 atlcraft_jj_atlcraft_candle02_redstone={hasPattern=true,label="Thin Redstone Candle",tag=""},
 atlcraft_jj_atlcraft_candle02_stone={hasPattern=true,label="Thin Stone Candle",tag=""},
 atlcraft_jj_atlcraft_candle03={hasPattern=true,label="Rustic Oak Wood Candle",tag=""},
 atlcraft_jj_atlcraft_candle03_acacia={hasPattern=true,label="Rustic Acacia Wood Candle",tag=""},
 atlcraft_jj_atlcraft_candle03_birch={hasPattern=true,label="Rustic Birch Wood Candle",tag=""},
 atlcraft_jj_atlcraft_candle03_darkoak={hasPattern=true,label="Rustic Dark Oak Wood Candle",tag=""},
 atlcraft_jj_atlcraft_candle03_jungle={hasPattern=true,label="Rustic Jungle Wood Candle",tag=""},
 atlcraft_jj_atlcraft_candle03_spruce={hasPattern=true,label="Rustic Spruce Wood Candle",tag=""},
 atlcraft_jj_atlcraft_candle04={hasPattern=true,label="Cast Iron Wrapped Wood Candle",tag=""},
 atlcraft_jj_atlcraft_candle04_iron={hasPattern=true,label="Iron Wrapped Wood Candle",tag=""},
 atlcraft_jj_atlcraft_candle05={hasPattern=true,label="Thick Stone Candle",tag=""},
 atlcraft_jj_atlcraft_candle05_castiron={hasPattern=true,label="Thick Cast Iron Candle",tag=""},
 atlcraft_jj_atlcraft_candle05_gold={hasPattern=true,label="Thick Gold Candle",tag=""},
 atlcraft_jj_atlcraft_candle05_iron={hasPattern=true,label="Thick Iron Candle",tag=""},
 atlcraft_jj_atlcraft_candle06={hasPattern=true,label="Cast Iron Chamber Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle06_gold={hasPattern=true,label="Gold Chamber Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle06_iron={hasPattern=true,label="Iron Chamber Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle07={hasPattern=true,label="Terracotta Bowl Candle",tag=""},
 atlcraft_jj_atlcraft_candle07_black={hasPattern=true,label="Black Terracotta Bowl Candle",tag=""},
 atlcraft_jj_atlcraft_candle07_blue={hasPattern=true,label="Blue Terracotta Bowl Candle",tag=""},
 atlcraft_jj_atlcraft_candle07_brown={hasPattern=true,label="Brown Terracotta Bowl Candle",tag=""},
 atlcraft_jj_atlcraft_candle07_cyan={hasPattern=true,label="Cyan Terracotta Bowl Candle",tag=""},
 atlcraft_jj_atlcraft_candle07_gray={hasPattern=true,label="Gray Terracotta Bowl Candle",tag=""},
 atlcraft_jj_atlcraft_candle07_green={hasPattern=true,label="Green Terracotta Bowl Candle",tag=""},
 atlcraft_jj_atlcraft_candle07_lightblue={hasPattern=true,label="Light Blue Terracotta Bowl Candle",tag=""},
 atlcraft_jj_atlcraft_candle07_lightgray={hasPattern=true,label="Light Gray Terracotta Bowl Candle",tag=""},
 atlcraft_jj_atlcraft_candle07_lime={hasPattern=true,label="Lime Terracotta Bowl Candle",tag=""},
 atlcraft_jj_atlcraft_candle07_magenta={hasPattern=true,label="Magenta Terracotta Bowl Candle",tag=""},
 atlcraft_jj_atlcraft_candle07_orange={hasPattern=true,label="Orange Terracotta Bowl Candle",tag=""},
 atlcraft_jj_atlcraft_candle07_pink={hasPattern=true,label="Pink Terracotta Bowl Candle",tag=""},
 atlcraft_jj_atlcraft_candle07_purple={hasPattern=true,label="Purple Terracotta Bowl Candle",tag=""},
 atlcraft_jj_atlcraft_candle07_red={hasPattern=true,label="Red Terracotta Bowl Candle",tag=""},
 atlcraft_jj_atlcraft_candle07_stone={hasPattern=true,label="Stone Bowl Candle",tag=""},
 atlcraft_jj_atlcraft_candle07_white={hasPattern=true,label="White Terracotta Bowl Candle",tag=""},
 atlcraft_jj_atlcraft_candle07_yellow={hasPattern=true,label="Yellow Terracotta Bowl Candle",tag=""},
 atlcraft_jj_atlcraft_candle08={hasPattern=true,label="Zombie Arm Candle",tag=""},
 atlcraft_jj_atlcraft_candle09={hasPattern=true,label="Thin Cast Iron Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle09_diamond={hasPattern=true,label="Thin Diamond Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle09_emerald={hasPattern=true,label="Thin Emerald Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle09_glass={hasPattern=true,label="Thin Glass Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle09_gold={hasPattern=true,label="Thin Gold Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle09_iron={hasPattern=true,label="Thin Iron Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle09_lapis={hasPattern=true,label="Thin Lapis Lazuli Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle09_redstone={hasPattern=true,label="Thin Redstone Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle10={hasPattern=true,label="Large Cast Iron Candelabra",tag=""},
 atlcraft_jj_atlcraft_candle10_diamond={hasPattern=true,label="Large Diamond Candelabra",tag=""},
 atlcraft_jj_atlcraft_candle10_emerald={hasPattern=true,label="Large Emerald Candelabra",tag=""},
 atlcraft_jj_atlcraft_candle10_glass={hasPattern=true,label="Large Glass Candelabra",tag=""},
 atlcraft_jj_atlcraft_candle10_gold={hasPattern=true,label="Large Gold Candelabra",tag=""},
 atlcraft_jj_atlcraft_candle10_iron={hasPattern=true,label="Large Iron Candelabra",tag=""},
 atlcraft_jj_atlcraft_candle10_lapis={hasPattern=true,label="Large Lapis Lazuli Candelabra",tag=""},
 atlcraft_jj_atlcraft_candle10_redstone={hasPattern=true,label="Large Redstone Candelabra",tag=""},
 atlcraft_jj_atlcraft_candle11={hasPattern=true,label="Cast Iron Framed Candle",tag=""},
 atlcraft_jj_atlcraft_candle11_gold={hasPattern=true,label="Gold Framed Candle",tag=""},
 atlcraft_jj_atlcraft_candle11_iron={hasPattern=true,label="Iron Framed Candle",tag=""},
 atlcraft_jj_atlcraft_candle12={hasPattern=true,label="Cast Iron Barred Candle",tag=""},
 atlcraft_jj_atlcraft_candle12_gold={hasPattern=true,label="Gold Barred Candle",tag=""},
 atlcraft_jj_atlcraft_candle12_iron={hasPattern=true,label="Iron Barred Candle",tag=""},
 atlcraft_jj_atlcraft_candle13={hasPattern=true,label="Short Stone Candle",tag=""},
 atlcraft_jj_atlcraft_candle13_castiron={hasPattern=true,label="Short Cast Iron Candle",tag=""},
 atlcraft_jj_atlcraft_candle13_gold={hasPattern=true,label="Short Gold Candle",tag=""},
 atlcraft_jj_atlcraft_candle13_iron={hasPattern=true,label="Short Iron Candle",tag=""},
 atlcraft_jj_atlcraft_candle14={hasPattern=true,label="Cast Iron Candle Stand",tag=""},
 atlcraft_jj_atlcraft_candle14_diamond={hasPattern=true,label="Diamond Candle Stand",tag=""},
 atlcraft_jj_atlcraft_candle14_emerald={hasPattern=true,label="Emerald Candle Stand",tag=""},
 atlcraft_jj_atlcraft_candle14_glass={hasPattern=true,label="Glass Candle Stand",tag=""},
 atlcraft_jj_atlcraft_candle14_gold={hasPattern=true,label="Gold Candle Stand",tag=""},
 atlcraft_jj_atlcraft_candle14_iron={hasPattern=true,label="Iron Candle Stand",tag=""},
 atlcraft_jj_atlcraft_candle14_lapis={hasPattern=true,label="Lapis Lazuli Candle Stand",tag=""},
 atlcraft_jj_atlcraft_candle14_redstone={hasPattern=true,label="Redstone Candle Stand",tag=""},
 atlcraft_jj_atlcraft_candle15={hasPattern=true,label="Cast Iron Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle15_acacia={hasPattern=true,label="Acacia Wood Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle15_birch={hasPattern=true,label="Birch Wood Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle15_darkoak={hasPattern=true,label="Dark Oak Wood Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle15_diamond={hasPattern=true,label="Diamond Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle15_emerald={hasPattern=true,label="Emerald Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle15_glass={hasPattern=true,label="Glass Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle15_gold={hasPattern=true,label="Gold Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle15_iron={hasPattern=true,label="Iron Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle15_jungle={hasPattern=true,label="Jungle Wood Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle15_lapis={hasPattern=true,label="Lapis Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle15_oak={hasPattern=true,label="Oak Wood Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle15_redstone={hasPattern=true,label="Redstone Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle15_spruce={hasPattern=true,label="Spruce Wood Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle15_stone={hasPattern=true,label="Stone Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle16={hasPattern=true,label="Oak Wood Candle Holder",tag=""},
 atlcraft_jj_atlcraft_candle16_acacia={hasPattern=true,label="Acacia Wood Candle Holder",tag=""},
 atlcraft_jj_atlcraft_candle16_birch={hasPattern=true,label="Birch Wood Candle Holder",tag=""},
 atlcraft_jj_atlcraft_candle16_castiron={hasPattern=true,label="Cast Iron Candle Holder",tag=""},
 atlcraft_jj_atlcraft_candle16_darkoak={hasPattern=true,label="Dark Oak Wood Candle Holder",tag=""},
 atlcraft_jj_atlcraft_candle16_gold={hasPattern=true,label="Gold Candle Holder",tag=""},
 atlcraft_jj_atlcraft_candle16_iron={hasPattern=true,label="Iron Candle Holder",tag=""},
 atlcraft_jj_atlcraft_candle16_jungle={hasPattern=true,label="Jungle Wood Candle Holder",tag=""},
 atlcraft_jj_atlcraft_candle16_spruce={hasPattern=true,label="Spruce Wood Candle Holder",tag=""},
 atlcraft_jj_atlcraft_candle16_stone={hasPattern=true,label="Stone Candle Holder",tag=""},
 atlcraft_jj_atlcraft_candle17={hasPattern=true,label="Cast Iron Candle Lantern",tag=""},
 atlcraft_jj_atlcraft_candle17_acacia={hasPattern=true,label="Acacia Wood Candle Lantern",tag=""},
 atlcraft_jj_atlcraft_candle17_birch={hasPattern=true,label="Birch Wood Candle Lantern",tag=""},
 atlcraft_jj_atlcraft_candle17_darkoak={hasPattern=true,label="Dark Oak Wood Candle Lantern",tag=""},
 atlcraft_jj_atlcraft_candle17_gold={hasPattern=true,label="Gold Candle Lantern",tag=""},
 atlcraft_jj_atlcraft_candle17_iron={hasPattern=true,label="Iron Candle Lantern",tag=""},
 atlcraft_jj_atlcraft_candle17_jungle={hasPattern=true,label="Jungle Wood Candle Lantern",tag=""},
 atlcraft_jj_atlcraft_candle17_oak={hasPattern=true,label="Oak Wood Candle Lantern",tag=""},
 atlcraft_jj_atlcraft_candle17_spruce={hasPattern=true,label="Spruce Wood Candle Lantern",tag=""},
 atlcraft_jj_atlcraft_candle17_stone={hasPattern=true,label="Stone Candle Lantern",tag=""},
 atlcraft_jj_atlcraft_candle18={hasPattern=true,label="Glass Candle Box",tag=""},
 atlcraft_jj_atlcraft_candle18_castiron={hasPattern=true,label="Cast Iron Candle Box",tag=""},
 atlcraft_jj_atlcraft_candle18_diamond={hasPattern=true,label="Diamond Candle Box",tag=""},
 atlcraft_jj_atlcraft_candle18_emerald={hasPattern=true,label="Emerald Candle Box",tag=""},
 atlcraft_jj_atlcraft_candle18_gold={hasPattern=true,label="Gold Candle Box",tag=""},
 atlcraft_jj_atlcraft_candle18_iron={hasPattern=true,label="Iron Candle Box",tag=""},
 atlcraft_jj_atlcraft_candle18_lapis={hasPattern=true,label="Lapis Lazuli Candle Box",tag=""},
 atlcraft_jj_atlcraft_candle18_redstone={hasPattern=true,label="Redstone Candle Box",tag=""},
 atlcraft_jj_atlcraft_candle19={hasPattern=true,label="Glass Round Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle19_castiron={hasPattern=true,label="Cast Iron Round Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle19_diamond={hasPattern=true,label="Diamond Round Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle19_emerald={hasPattern=true,label="Emerald Round Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle19_gold={hasPattern=true,label="Gold Round Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle19_iron={hasPattern=true,label="Iron Round Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle19_lapis={hasPattern=true,label="Lapis Lazuli Round Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle19_redstone={hasPattern=true,label="Redstone Round Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle20={hasPattern=true,label="Glass Square Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle20_castiron={hasPattern=true,label="Cast Iron Square Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle20_diamond={hasPattern=true,label="Diamond Square Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle20_emerald={hasPattern=true,label="Emerald Square Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle20_gold={hasPattern=true,label="Gold Square Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle20_iron={hasPattern=true,label="Iron Square Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle20_lapis={hasPattern=true,label="Lapis Lazuli Square Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle20_redstone={hasPattern=true,label="Redstone Square Candlestick",tag=""},
 atlcraft_jj_atlcraft_candle21_black={hasPattern=true,label="Small Black Stained Glass Lantern",tag=""},
 atlcraft_jj_atlcraft_candle21_blue={hasPattern=true,label="Small Blue Stained Glass Lantern",tag=""},
 atlcraft_jj_atlcraft_candle21_brown={hasPattern=true,label="Small Brown Stained Glass Lantern",tag=""},
 atlcraft_jj_atlcraft_candle21_cyan={hasPattern=true,label="Small Cyan Stained Glass Lantern",tag=""},
 atlcraft_jj_atlcraft_candle21_green={hasPattern=true,label="Small Green Stained Glass Lantern",tag=""},
 atlcraft_jj_atlcraft_candle21_grey={hasPattern=true,label="Small Gray Stained Glass Lantern",tag=""},
 atlcraft_jj_atlcraft_candle21_lightblue={hasPattern=true,label="Small Light Blue Stained Glass Lantern",tag=""},
 atlcraft_jj_atlcraft_candle21_lightgrey={hasPattern=true,label="Small Light Gray Stained Glass Lantern",tag=""},
 atlcraft_jj_atlcraft_candle21_lime={hasPattern=true,label="Small Lime Stained Glass Lantern",tag=""},
 atlcraft_jj_atlcraft_candle21_magenta={hasPattern=true,label="Small Magenta Stained Glass Lantern",tag=""},
 atlcraft_jj_atlcraft_candle21_orange={hasPattern=true,label="Small Orange Stained Glass Lantern",tag=""},
 atlcraft_jj_atlcraft_candle21_pink={hasPattern=true,label="Small Pink Stained Glass Lantern",tag=""},
 atlcraft_jj_atlcraft_candle21_purple={hasPattern=true,label="Small Purple Stained Glass Lantern",tag=""},
 atlcraft_jj_atlcraft_candle21_red={hasPattern=true,label="Small Red Stained Glass Lantern",tag=""},
 atlcraft_jj_atlcraft_candle21_white={hasPattern=true,label="Small White Stained Glass Lantern",tag=""},
 atlcraft_jj_atlcraft_candle21_yellow={hasPattern=true,label="Small Yellow Stained Glass Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22={hasPattern=true,label="Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_black={hasPattern=true,label="Black Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_blue={hasPattern=true,label="Blue Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_brown={hasPattern=true,label="Brown Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_creeper={hasPattern=true,label="Creeper Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_cyan={hasPattern=true,label="Cyan Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_enderman={hasPattern=true,label="Enderman Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_ghast={hasPattern=true,label="Ghast Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_green={hasPattern=true,label="Green Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_grey={hasPattern=true,label="Gray Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_lightblue={hasPattern=true,label="Light Blue Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_lightgrey={hasPattern=true,label="Light Gray Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_lime={hasPattern=true,label="Lime Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_magenta={hasPattern=true,label="Magenta Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_orange={hasPattern=true,label="Orange Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_pink={hasPattern=true,label="Pink Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_pumpkin={hasPattern=true,label="Pumpkin Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_purple={hasPattern=true,label="Purple Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_red={hasPattern=true,label="Red Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_skeleton={hasPattern=true,label="Skeleton Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_slime={hasPattern=true,label="Slime Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_spider={hasPattern=true,label="Spider Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_squid={hasPattern=true,label="Squid Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_white={hasPattern=true,label="White Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_yellow={hasPattern=true,label="Yellow Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle22_zombie={hasPattern=true,label="Zombie Paper Lantern",tag=""},
 atlcraft_jj_atlcraft_candle23_castiron={hasPattern=true,label="Cast Iron Cobweb Candle",tag=""},
 atlcraft_jj_atlcraft_candle23_gold={hasPattern=true,label="Gold Cobweb Candle",tag=""},
 atlcraft_jj_atlcraft_candle23_iron={hasPattern=true,label="Iron Cobweb Candle",tag=""},
 atlcraft_jj_atlcraft_candle24_white={hasPattern=false,label="",tag=""},
 atlcraft_jj_atlcraft_candle25_white={hasPattern=true,label="White Ambient Lantern",tag=""},
 atlcraft_jj_atlcraft_candle_creeper={hasPattern=true,label="Creeper Candle",tag=""},
 atlcraft_jj_atlcraft_candle_creeperhead={hasPattern=true,label="Creeper Head Candle",tag=""},
 atlcraft_jj_atlcraft_candle_creeperhead_black={hasPattern=true,label="Black Creeper Head Candle",tag=""},
 atlcraft_jj_atlcraft_candle_enderman={hasPattern=true,label="Enderman Head Candle",tag=""},
 atlcraft_jj_atlcraft_candle_enderman_purple={hasPattern=true,label="Purple Enderman Head Candle",tag=""},
 atlcraft_jj_atlcraft_candle_skull={hasPattern=true,label="Skull Candle",tag=""},
 atlcraft_jj_atlcraft_candle_skull_red={hasPattern=true,label="Red Skull Candle",tag=""},
 atlcraft_jj_atlcraft_candle_zombiehead={hasPattern=true,label="Zombie Head Candle",tag=""},
 atlcraft_jj_atlcraft_candle_zombiehead_green={hasPattern=true,label="Green Zombie Head Candle",tag=""},
 atlcraft_jj_atlcraft_castiron_block={hasPattern=true,label="Cast Iron Block",tag=""},
 atlcraft_jj_atlcraft_castiron_ingot={hasPattern=true,label="Cast Iron Ingot",tag=""},
 atlcraft_jj_atlcraft_chain1={hasPattern=true,label="Chain",tag=""},
 atlcraft_jj_atlcraft_chain1_gold={hasPattern=true,label="Gold Chain",tag=""},
 atlcraft_jj_atlcraft_chainlong1={hasPattern=true,label="Long Chain",tag=""},
 atlcraft_jj_atlcraft_chainlong1_gold={hasPattern=true,label="Long Gold Chain",tag=""},
 atlcraft_jj_atlcraft_chainlongbottom1={hasPattern=false,label="",tag=""},
 atlcraft_jj_atlcraft_chainlongbottom1_gold={hasPattern=false,label="",tag=""},
 atlcraft_jj_atlcraft_chandelier1={hasPattern=true,label="Large Glass Chandelier",tag=""},
 atlcraft_jj_atlcraft_chandelier1_acacia={hasPattern=true,label="Large Acacia Chandelier",tag=""},
 atlcraft_jj_atlcraft_chandelier1_birch={hasPattern=true,label="Large Birch Chandelier",tag=""},
 atlcraft_jj_atlcraft_chandelier1_castiron={hasPattern=true,label="Large Cast Iron Chandelier",tag=""},
 atlcraft_jj_atlcraft_chandelier1_darkoak={hasPattern=true,label="Large Dark Oak Chandelier",tag=""},
 atlcraft_jj_atlcraft_chandelier1_diamond={hasPattern=true,label="Large Diamond Chandelier",tag=""},
 atlcraft_jj_atlcraft_chandelier1_emerald={hasPattern=true,label="Large Emerald Chandelier",tag=""},
 atlcraft_jj_atlcraft_chandelier1_gold={hasPattern=true,label="Large Gold Chandelier",tag=""},
 atlcraft_jj_atlcraft_chandelier1_iron={hasPattern=true,label="Large Iron Chandelier",tag=""},
 atlcraft_jj_atlcraft_chandelier1_jungle={hasPattern=true,label="Large Jungle Chandelier",tag=""},
 atlcraft_jj_atlcraft_chandelier1_lapis={hasPattern=true,label="Large Lapis Lazuli Chandelier",tag=""},
 atlcraft_jj_atlcraft_chandelier1_oak={hasPattern=true,label="Large Oak Chandelier",tag=""},
 atlcraft_jj_atlcraft_chandelier1_redstone={hasPattern=true,label="Large Redstone Chandelier",tag=""},
 atlcraft_jj_atlcraft_chandelier1_spruce={hasPattern=true,label="Large Spruce Chandelier",tag=""},
 atlcraft_jj_atlcraft_chandelier1_stone={hasPattern=true,label="Large Stone Chandelier",tag=""},
 atlcraft_jj_atlcraft_chandelier2={hasPattern=true,label="Cast Iron Tiered Chandelier",tag=""},
 atlcraft_jj_atlcraft_chandelier2_gold={hasPattern=true,label="Gold Tiered Chandelier",tag=""},
 atlcraft_jj_atlcraft_chandelier2_iron={hasPattern=true,label="Iron Tiered Chandelier",tag=""},
 atlcraft_jj_atlcraft_chandelier3={hasPattern=true,label="Glass Crystal Chandelier",tag=""},
 atlcraft_jj_atlcraft_chandelier3_castiron={hasPattern=true,label="Glass Crystal Cast Iron Chandelier",tag=""},
 atlcraft_jj_atlcraft_chandelier3_gold={hasPattern=true,label="Glass Crystal Gold Chandelier",tag=""},
 atlcraft_jj_atlcraft_chandelier3_iron={hasPattern=true,label="Glass Crystal Iron Chandelier",tag=""},
 atlcraft_jj_atlcraft_climbablevine1={hasPattern=true,label="Vine Rope",tag=""},
 atlcraft_jj_atlcraft_climbablevine1_long={hasPattern=true,label="Vine Rope Coil",tag=""},
 atlcraft_jj_atlcraft_climbablevine1_longbottom={hasPattern=false,label="",tag=""},
 atlcraft_jj_atlcraft_crystalstrand1={hasPattern=true,label="Glass Bead Strand",tag=""},
 atlcraft_jj_atlcraft_crystalstrandcurtain1={hasPattern=true,label="Glass Bead Strand Curtain",tag=""},
 atlcraft_jj_atlcraft_crystalstrandlong1={hasPattern=true,label="Long Glass Bead Strand",tag=""},
 atlcraft_jj_atlcraft_crystalstrandlongbottom1={hasPattern=false,label="",tag=""},
 atlcraft_jj_atlcraft_floorstand3={hasPattern=true,label="Thin Cast Iron Floor Stand",tag=""},
 atlcraft_jj_atlcraft_floorstand3_gold={hasPattern=true,label="Thin Gold Floor Stand",tag=""},
 atlcraft_jj_atlcraft_floorstand3_iron={hasPattern=true,label="Thin Iron Floor Stand",tag=""},
 atlcraft_jj_atlcraft_floorstand3_stone={hasPattern=true,label="Thin Stone Floor Stand",tag=""},
 atlcraft_jj_atlcraft_floorstand4={hasPattern=true,label="Dark Oak Wood Block Pedestal",tag=""},
 atlcraft_jj_atlcraft_floorstand4_acacia={hasPattern=true,label="Acacia Wood Block Pedestal",tag=""},
 atlcraft_jj_atlcraft_floorstand4_birch={hasPattern=true,label="Birch Wood Block Pedestal",tag=""},
 atlcraft_jj_atlcraft_floorstand4_jungle={hasPattern=true,label="Jungle Wood Block Pedestal",tag=""},
 atlcraft_jj_atlcraft_floorstand4_oak={hasPattern=true,label="Oak Wood Block Pedestal",tag=""},
 atlcraft_jj_atlcraft_floorstand4_spruce={hasPattern=true,label="Spruce Wood Block Pedestal",tag=""},
 atlcraft_jj_atlcraft_fried_potatoes={hasPattern=true,label="Fried Potatoes",tag=""},
 atlcraft_jj_atlcraft_furniturecraftingkit={hasPattern=true,label="Deco Crafting Kit",tag=""},
 atlcraft_jj_atlcraft_lamppost01={hasPattern=true,label="Cast Iron Lamp Post Bottom",tag=""},
 atlcraft_jj_atlcraft_lamppost01_acacia={hasPattern=true,label="Acacia Wood Lamp Post Bottom",tag=""},
 atlcraft_jj_atlcraft_lamppost01_acacia_middle={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_acacia_top={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_birch={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_birch_middle={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_birch_top={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_darkoak={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_darkoak_middle={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_darkoak_top={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_acacia={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_acacia_middle={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_acacia_top={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_acacia_top_light1={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_birch={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_birch_middle={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_birch_top={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_birch_top_light1={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_darkoak={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_darkoak_middle={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_darkoak_top={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_darkoak_top_light1={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_gold={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_gold_middle={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_gold_top={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_gold_top_light1={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_iron={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_iron_middle={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_iron_top={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_iron_top_light1={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_jungle={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_jungle_middle={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_jungle_top={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_jungle_top_light1={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_middle={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_oak={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_oak_middle={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_oak_top={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_oak_top_light1={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_spruce={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_spruce_middle={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_spruce_top={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_spruce_top_light1={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_stone={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_stone_middle={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_stone_top={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_stone_top_light1={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_top={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_edge_top_light1={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_gold={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_iron={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_jungle={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_jungle_middle={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_jungle_top={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_middle={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_middle_gold={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_middle_iron={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_middle_stone={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_oak={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_oak_middle={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_oak_top={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_spruce={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_spruce_middle={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_spruce_top={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_stone={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_top={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_top_fancy={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_top_fancy_acacia={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_top_fancy_acaciairon={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_top_fancy_birch={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_top_fancy_birchiron={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_top_fancy_darkoak={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_top_fancy_darkoakiron={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_top_fancy_gold={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_top_fancy_iron={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_top_fancy_jungle={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_top_fancy_jungleiron={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_top_fancy_oak={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_top_fancy_oakiron={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_top_fancy_spruce={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_top_fancy_spruceiron={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_top_fancy_stone={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_top_gold={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_top_iron={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_lamppost01_top_stone={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_rope1={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_ropecoil1={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_ropecoilbottom1={hasPattern=false,label="",tag=""},
 atlcraft_jj_atlcraft_tallow={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_tallow_block={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_wax={hasPattern=true,label="",tag=""},
 atlcraft_jj_atlcraft_wax_block={hasPattern=true,label="",tag=""}
 }