return {
 mysticalagradditions_jj_awakened_draconium_crop={hasPattern=false,label="",tag=""},
 mysticalagradditions_jj_awakened_draconium_essence={hasPattern=false,label="",tag=""},
 mysticalagradditions_jj_awakened_draconium_seeds={hasPattern=true,label="Awakened Draconium Seeds",tag=""},
 mysticalagradditions_jj_charm={hasPattern=true,label="Charm= Mining AOE",tag=""},
 mysticalagradditions_jj_dragon_egg_crop={hasPattern=false,label="",tag=""},
 mysticalagradditions_jj_dragon_egg_essence={hasPattern=false,label="",tag=""},
 mysticalagradditions_jj_dragon_egg_seeds={hasPattern=true,label="Dragon Egg Seeds",tag=""},
 mysticalagradditions_jj_inferium_paxel={hasPattern=true,label="§eInferium Paxel",tag=""},
 mysticalagradditions_jj_insanium={hasPattern=true,label="§5Insanium Essence",tag=""},
 mysticalagradditions_jj_insanium_jj_1={hasPattern=true,label="Tier 6 Crafting Seed",tag=""},
 mysticalagradditions_jj_insanium_jj_2={hasPattern=true,label="§5Insanium Ingot",tag=""},
 mysticalagradditions_jj_insanium_jj_3={hasPattern=true,label="§5Insanium Nugget",tag=""},
 mysticalagradditions_jj_insanium_jj_4={hasPattern=true,label="Tier 6 Mob Chunk",tag=""},
 mysticalagradditions_jj_insanium_jj_5={hasPattern=true,label="§5Insanium Coal",tag=""},
 mysticalagradditions_jj_intermedium_paxel={hasPattern=true,label="§6Intermedium Paxel",tag=""},
 mysticalagradditions_jj_nether_star_crop={hasPattern=false,label="",tag=""},
 mysticalagradditions_jj_nether_star_essence={hasPattern=false,label="",tag=""},
 mysticalagradditions_jj_nether_star_seeds={hasPattern=true,label="Nether Star Seeds",tag=""},
 mysticalagradditions_jj_prudentium_paxel={hasPattern=true,label="§aPrudentium Paxel",tag=""},
 mysticalagradditions_jj_special={hasPattern=true,label="Nether Star Crux",tag=""},
 mysticalagradditions_jj_special_jj_1={hasPattern=true,label="Dragon Egg Crux",tag=""},
 mysticalagradditions_jj_special_jj_4={hasPattern=true,label="Awakened Draconium Crux",tag=""},
 mysticalagradditions_jj_storage={hasPattern=true,label="§5Block of Insanium Essence",tag=""},
 mysticalagradditions_jj_storage_jj_1={hasPattern=true,label="§5Block of Insanium",tag=""},
 mysticalagradditions_jj_storage_jj_2={hasPattern=true,label="§5Block of Insanium Coal",tag=""},
 mysticalagradditions_jj_stuff={hasPattern=false,label="",tag=""},
 mysticalagradditions_jj_stuff_jj_1={hasPattern=false,label="",tag=""},
 mysticalagradditions_jj_stuff_jj_2={hasPattern=false,label="",tag=""},
 mysticalagradditions_jj_stuff_jj_3={hasPattern=false,label="",tag=""},
 mysticalagradditions_jj_stuff_jj_69={hasPattern=false,label="",tag=""},
 mysticalagradditions_jj_superium_paxel={hasPattern=true,label="§bSuperium Paxel",tag=""},
 mysticalagradditions_jj_supremium_paxel={hasPattern=true,label="§cSupremium Paxel",tag=""},
 mysticalagradditions_jj_tier6_inferium_crop={hasPattern=false,label="",tag=""},
 mysticalagradditions_jj_tier6_inferium_seeds={hasPattern=true,label="Inferium Seeds",tag=""},
 mysticalagradditions_jj_tinkering_table={hasPattern=true,label="Tinkering Table",tag=""},
 mysticalagriculture_jj_adamantine_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_adamantine_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_adamantine_seeds={hasPattern=true,label="Adamantine Seeds",tag=""},
 mysticalagriculture_jj_aluminum_brass_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_aluminum_brass_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_aluminum_brass_seeds={hasPattern=true,label="Aluminum Brass Seeds",tag=""},
 mysticalagriculture_jj_aluminum_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_aluminum_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_aluminum_seeds={hasPattern=true,label="Aluminum Seeds",tag=""},
 mysticalagriculture_jj_alumite_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_alumite_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_alumite_seeds={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_amber_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_amber_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_amber_seeds={hasPattern=true,label="Amber Seeds",tag=""},
 mysticalagriculture_jj_apatite_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_apatite_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_apatite_seeds={hasPattern=true,label="Apatite Seeds",tag=""},
 mysticalagriculture_jj_aquamarine_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_aquamarine_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_aquamarine_seeds={hasPattern=true,label="Aquamarine Seeds",tag=""},
 mysticalagriculture_jj_aquarium_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_aquarium_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_aquarium_seeds={hasPattern=true,label="Aquarium Seeds",tag=""},
 mysticalagriculture_jj_ardite_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_ardite_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_ardite_seeds={hasPattern=true,label="Ardite Seeds",tag=""},
 mysticalagriculture_jj_basalt_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_basalt_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_basalt_seeds={hasPattern=true,label="Basalt Seeds",tag=""},
 mysticalagriculture_jj_basalz_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_basalz_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_basalz_seeds={hasPattern=true,label="Basalz Seeds",tag=""},
 mysticalagriculture_jj_black_quartz_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_black_quartz_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_black_quartz_seeds={hasPattern=true,label="Black Quartz Seeds",tag=""},
 mysticalagriculture_jj_blaze_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_blaze_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_blaze_seeds={hasPattern=true,label="Blaze Seeds",tag=""},
 mysticalagriculture_jj_blitz_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_blitz_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_blitz_seeds={hasPattern=true,label="Blitz Seeds",tag=""},
 mysticalagriculture_jj_blizz_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_blizz_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_blizz_seeds={hasPattern=true,label="Blizz Seeds",tag=""},
 mysticalagriculture_jj_boron_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_boron_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_boron_seeds={hasPattern=true,label="Boron Seeds",tag=""},
 mysticalagriculture_jj_brass_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_brass_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_brass_seeds={hasPattern=true,label="Brass Seeds",tag=""},
 mysticalagriculture_jj_bronze_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_bronze_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_bronze_seeds={hasPattern=true,label="Bronze Seeds",tag=""},
 mysticalagriculture_jj_certus_quartz_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_certus_quartz_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_certus_quartz_seeds={hasPattern=true,label="Certus Quartz Seeds",tag=""},
 mysticalagriculture_jj_charm={hasPattern=true,label="Blank Charm",tag=""},
 mysticalagriculture_jj_charm_jj_1={hasPattern=true,label="Charm= Night Vision",tag=""},
 mysticalagriculture_jj_charm_jj_10={hasPattern=true,label="Charm= Jump Boost",tag=""},
 mysticalagriculture_jj_charm_jj_11={hasPattern=true,label="Charm= Miner's Vision",tag=""},
 mysticalagriculture_jj_charm_jj_12={hasPattern=true,label="Charm= Rainbow",tag=""},
 mysticalagriculture_jj_charm_jj_13={hasPattern=true,label="Charm= Quick Draw",tag=""},
 mysticalagriculture_jj_charm_jj_14={hasPattern=true,label="Charm= Triple Shot",tag=""},
 mysticalagriculture_jj_charm_jj_15={hasPattern=true,label="Charm= Mining AOE",tag=""},
 mysticalagriculture_jj_charm_jj_16={hasPattern=true,label="Charm= Attack AOE",tag=""},
 mysticalagriculture_jj_charm_jj_17={hasPattern=true,label="Charm= Tilling AOE",tag=""},
 mysticalagriculture_jj_charm_jj_18={hasPattern=true,label="Charm= Shearing AOE",tag=""},
 mysticalagriculture_jj_charm_jj_19={hasPattern=true,label="Charm= Reaping AOE",tag=""},
 mysticalagriculture_jj_charm_jj_2={hasPattern=true,label="Charm= Absorption",tag=""},
 mysticalagriculture_jj_charm_jj_20={hasPattern=true,label="Charm= Scything AOE",tag=""},
 mysticalagriculture_jj_charm_jj_3={hasPattern=true,label="Charm= Wither Resistance",tag=""},
 mysticalagriculture_jj_charm_jj_4={hasPattern=true,label="Charm= Antivenom",tag=""},
 mysticalagriculture_jj_charm_jj_5={hasPattern=true,label="Charm= Fire Resistance",tag=""},
 mysticalagriculture_jj_charm_jj_6={hasPattern=true,label="Charm= Resistance",tag=""},
 mysticalagriculture_jj_charm_jj_7={hasPattern=true,label="Charm= Strength",tag=""},
 mysticalagriculture_jj_charm_jj_8={hasPattern=true,label="Charm= Strength 2",tag=""},
 mysticalagriculture_jj_charm_jj_9={hasPattern=true,label="Charm= Speed",tag=""},
 mysticalagriculture_jj_chicken_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_chicken_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_chicken_seeds={hasPattern=true,label="Chicken Seeds",tag=""},
 mysticalagriculture_jj_chrome_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_chrome_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_chrome_seeds={hasPattern=true,label="Chrome Seeds",tag=""},
 mysticalagriculture_jj_chunk={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_chunk_jj_1={hasPattern=true,label="Tier 2 Mob Chunk",tag=""},
 mysticalagriculture_jj_chunk_jj_10={hasPattern=true,label="Sheep Chunk",tag=""},
 mysticalagriculture_jj_chunk_jj_11={hasPattern=true,label="Slime Chunk",tag=""},
 mysticalagriculture_jj_chunk_jj_12={hasPattern=true,label="Skeleton Chunk",tag=""},
 mysticalagriculture_jj_chunk_jj_13={hasPattern=true,label="Creeper Chunk",tag=""},
 mysticalagriculture_jj_chunk_jj_14={hasPattern=true,label="Spider Chunk",tag=""},
 mysticalagriculture_jj_chunk_jj_15={hasPattern=true,label="Rabbit Chunk",tag=""},
 mysticalagriculture_jj_chunk_jj_16={hasPattern=true,label="Guardian Chunk",tag=""},
 mysticalagriculture_jj_chunk_jj_17={hasPattern=true,label="Blaze Chunk",tag=""},
 mysticalagriculture_jj_chunk_jj_18={hasPattern=true,label="Ghast Chunk",tag=""},
 mysticalagriculture_jj_chunk_jj_19={hasPattern=true,label="Enderman Chunk",tag=""},
 mysticalagriculture_jj_chunk_jj_2={hasPattern=true,label="Tier 3 Mob Chunk",tag=""},
 mysticalagriculture_jj_chunk_jj_20={hasPattern=true,label="Wither Skeleton Chunk",tag=""},
 mysticalagriculture_jj_chunk_jj_21={hasPattern=true,label="Blizz Chunk",tag=""},
 mysticalagriculture_jj_chunk_jj_22={hasPattern=true,label="Blitz Chunk",tag=""},
 mysticalagriculture_jj_chunk_jj_23={hasPattern=true,label="Basalz Chunk",tag=""},
 mysticalagriculture_jj_chunk_jj_3={hasPattern=true,label="Tier 4 Mob Chunk",tag=""},
 mysticalagriculture_jj_chunk_jj_4={hasPattern=true,label="Tier 5 Mob Chunk",tag=""},
 mysticalagriculture_jj_chunk_jj_5={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_chunk_jj_6={hasPattern=true,label="Zombie Chunk",tag=""},
 mysticalagriculture_jj_chunk_jj_7={hasPattern=true,label="Pig Chunk",tag=""},
 mysticalagriculture_jj_chunk_jj_8={hasPattern=true,label="Chicken Chunk",tag=""},
 mysticalagriculture_jj_chunk_jj_9={hasPattern=true,label="Cow Chunk",tag=""},
 mysticalagriculture_jj_coal={hasPattern=true,label="§eInferium Coal",tag=""},
 mysticalagriculture_jj_coal_block={hasPattern=true,label="§eBlock of Inferium Coal",tag=""},
 mysticalagriculture_jj_coal_block_jj_1={hasPattern=true,label="§aBlock of Prudentium Coal",tag=""},
 mysticalagriculture_jj_coal_block_jj_2={hasPattern=true,label="§6Block of Intermedium Coal",tag=""},
 mysticalagriculture_jj_coal_block_jj_3={hasPattern=true,label="§bBlock of Superium Coal",tag=""},
 mysticalagriculture_jj_coal_block_jj_4={hasPattern=true,label="§cBlock of Supremium Coal",tag=""},
 mysticalagriculture_jj_coal_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_coal_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_coal_jj_1={hasPattern=true,label="§aPrudentium Coal",tag=""},
 mysticalagriculture_jj_coal_jj_2={hasPattern=true,label="§6Intermedium Coal",tag=""},
 mysticalagriculture_jj_coal_jj_3={hasPattern=true,label="§bSuperium Coal",tag=""},
 mysticalagriculture_jj_coal_jj_4={hasPattern=true,label="§cSupremium Coal",tag=""},
 mysticalagriculture_jj_coal_seeds={hasPattern=true,label="Coal Seeds",tag=""},
 mysticalagriculture_jj_cobalt_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_cobalt_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_cobalt_seeds={hasPattern=true,label="Cobalt Seeds",tag=""},
 mysticalagriculture_jj_cobbled_soulstone_slab={hasPattern=true,label="Cobbled Soulstone Slab",tag=""},
 mysticalagriculture_jj_cobbled_soulstone_stairs={hasPattern=true,label="Cobbled Soulstone Stairs",tag=""},
 mysticalagriculture_jj_cobbled_soulstone_wall={hasPattern=true,label="Cobbled Soulstone Wall",tag=""},
 mysticalagriculture_jj_cold_iron_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_cold_iron_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_cold_iron_seeds={hasPattern=true,label="Cold-Iron Seeds",tag=""},
 mysticalagriculture_jj_compressed_iron_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_compressed_iron_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_compressed_iron_seeds={hasPattern=true,label="Compressed Iron Seeds",tag=""},
 mysticalagriculture_jj_conductive_iron_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_conductive_iron_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_conductive_iron_seeds={hasPattern=true,label="Conductive Iron Seeds",tag=""},
 mysticalagriculture_jj_constantan_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_constantan_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_constantan_seeds={hasPattern=true,label="Constantan Seeds",tag=""},
 mysticalagriculture_jj_copper_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_copper_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_copper_seeds={hasPattern=true,label="Copper Seeds",tag=""},
 mysticalagriculture_jj_core_remover={hasPattern=true,label="§cCore Remover",tag=""},
 mysticalagriculture_jj_cow_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_cow_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_cow_seeds={hasPattern=true,label="Cow Seeds",tag=""},
 mysticalagriculture_jj_crafting={hasPattern=true,label="§eInferium Essence",tag=""},
 mysticalagriculture_jj_crafting_jj_1={hasPattern=true,label="§aPrudentium Essence",tag=""},
 mysticalagriculture_jj_crafting_jj_10={hasPattern=true,label="Mystical Flower Cluster",tag=""},
 mysticalagriculture_jj_crafting_jj_14={hasPattern=true,label="Blank Record",tag=""},
 mysticalagriculture_jj_crafting_jj_15={hasPattern=true,label="Blank Skull",tag=""},
 mysticalagriculture_jj_crafting_jj_16={hasPattern=true,label="Base Crafting Seed",tag=""},
 mysticalagriculture_jj_crafting_jj_17={hasPattern=true,label="Tier 1 Crafting Seed",tag=""},
 mysticalagriculture_jj_crafting_jj_18={hasPattern=true,label="Tier 2 Crafting Seed",tag=""},
 mysticalagriculture_jj_crafting_jj_19={hasPattern=true,label="Tier 3 Crafting Seed",tag=""},
 mysticalagriculture_jj_crafting_jj_2={hasPattern=true,label="§6Intermedium Essence",tag=""},
 mysticalagriculture_jj_crafting_jj_20={hasPattern=true,label="Tier 4 Crafting Seed",tag=""},
 mysticalagriculture_jj_crafting_jj_21={hasPattern=true,label="Tier 5 Crafting Seed",tag=""},
 mysticalagriculture_jj_crafting_jj_22={hasPattern=true,label="Mystical Stick",tag=""},
 mysticalagriculture_jj_crafting_jj_23={hasPattern=true,label="Mystical String",tag=""},
 mysticalagriculture_jj_crafting_jj_24={hasPattern=true,label="Mystical Feather",tag=""},
 mysticalagriculture_jj_crafting_jj_28={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_crafting_jj_29={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_crafting_jj_3={hasPattern=true,label="§bSuperium Essence",tag=""},
 mysticalagriculture_jj_crafting_jj_32={hasPattern=true,label="Base Essence Ingot",tag=""},
 mysticalagriculture_jj_crafting_jj_33={hasPattern=true,label="§eInferium Ingot",tag=""},
 mysticalagriculture_jj_crafting_jj_34={hasPattern=true,label="§aPrudentium Ingot",tag=""},
 mysticalagriculture_jj_crafting_jj_35={hasPattern=true,label="§6Intermedium Ingot",tag=""},
 mysticalagriculture_jj_crafting_jj_36={hasPattern=true,label="§bSuperium Ingot",tag=""},
 mysticalagriculture_jj_crafting_jj_37={hasPattern=true,label="§cSupremium Ingot",tag=""},
 mysticalagriculture_jj_crafting_jj_38={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_crafting_jj_39={hasPattern=true,label="Base Essence Nugget",tag=""},
 mysticalagriculture_jj_crafting_jj_4={hasPattern=true,label="§cSupremium Essence",tag=""},
 mysticalagriculture_jj_crafting_jj_40={hasPattern=true,label="§eInferium Nugget",tag=""},
 mysticalagriculture_jj_crafting_jj_41={hasPattern=true,label="§aPrudentium Nugget",tag=""},
 mysticalagriculture_jj_crafting_jj_42={hasPattern=true,label="§6Intermedium Nugget",tag=""},
 mysticalagriculture_jj_crafting_jj_43={hasPattern=true,label="§bSuperium Nugget",tag=""},
 mysticalagriculture_jj_crafting_jj_44={hasPattern=true,label="§cSupremium Nugget",tag=""},
 mysticalagriculture_jj_crafting_jj_45={hasPattern=true,label="§dSoulium Nugget",tag=""},
 mysticalagriculture_jj_crafting_jj_48={hasPattern=true,label="Theoretical Infinite Water Source",tag=""},
 mysticalagriculture_jj_crafting_jj_5={hasPattern=true,label="Prosperity Shard",tag=""},
 mysticalagriculture_jj_crafting_jj_50={hasPattern=true,label="§eInferium Fertilization Core",tag=""},
 mysticalagriculture_jj_crafting_jj_51={hasPattern=true,label="§aPrudentium Fertilization Core",tag=""},
 mysticalagriculture_jj_crafting_jj_52={hasPattern=true,label="§6Intermedium Fertilization Core",tag=""},
 mysticalagriculture_jj_crafting_jj_53={hasPattern=true,label="§bSuperium Fertilization Core",tag=""},
 mysticalagriculture_jj_crafting_jj_54={hasPattern=true,label="§cSupremium Fertilization Core",tag=""},
 mysticalagriculture_jj_crafting_jj_6={hasPattern=true,label="Nature Cluster",tag=""},
 mysticalagriculture_jj_crafting_jj_7={hasPattern=true,label="Dye Cluster",tag=""},
 mysticalagriculture_jj_crafting_jj_8={hasPattern=true,label="Nether Cluster",tag=""},
 mysticalagriculture_jj_crafting_jj_9={hasPattern=true,label="End Cluster",tag=""},
 mysticalagriculture_jj_creeper_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_creeper_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_creeper_seeds={hasPattern=true,label="Creeper Seeds",tag=""},
 mysticalagriculture_jj_dark_steel_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_dark_steel_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_dark_steel_seeds={hasPattern=true,label="Dark Steel Seeds",tag=""},
 mysticalagriculture_jj_diamond_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_diamond_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_diamond_seeds={hasPattern=true,label="Diamond Seeds",tag=""},
 mysticalagriculture_jj_dirt_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_dirt_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_dirt_seeds={hasPattern=true,label="Dirt Seeds",tag=""},
 mysticalagriculture_jj_draconium_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_draconium_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_draconium_seeds={hasPattern=true,label="Draconium Seeds",tag=""},
 mysticalagriculture_jj_dye_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_dye_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_dye_seeds={hasPattern=true,label="Dye Seeds",tag=""},
 mysticalagriculture_jj_electrical_steel_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_electrical_steel_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_electrical_steel_seeds={hasPattern=true,label="Electrical Steel Seeds",tag=""},
 mysticalagriculture_jj_electrum_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_electrum_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_electrum_seeds={hasPattern=true,label="Electrum Seeds",tag=""},
 mysticalagriculture_jj_elementium_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_elementium_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_elementium_seeds={hasPattern=true,label="Elementium Seeds",tag=""},
 mysticalagriculture_jj_emerald_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_emerald_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_emerald_seeds={hasPattern=true,label="Emerald Seeds",tag=""},
 mysticalagriculture_jj_end_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_end_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_end_inferium_ore={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_end_prosperity_ore={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_end_seeds={hasPattern=true,label="End Seeds",tag=""},
 mysticalagriculture_jj_end_steel_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_end_steel_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_end_steel_seeds={hasPattern=true,label="End Steel Seeds",tag=""},
 mysticalagriculture_jj_ender_amethyst_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_ender_amethyst_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_ender_amethyst_seeds={hasPattern=true,label="Ender Amethyst Seeds",tag=""},
 mysticalagriculture_jj_enderium_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_enderium_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_enderium_seeds={hasPattern=true,label="Enderium Seeds",tag=""},
 mysticalagriculture_jj_enderman_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_enderman_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_enderman_seeds={hasPattern=true,label="Enderman Seeds",tag=""},
 mysticalagriculture_jj_energetic_alloy_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_energetic_alloy_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_energetic_alloy_seeds={hasPattern=true,label="Energetic Alloy Seeds",tag=""},
 mysticalagriculture_jj_experience_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_experience_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_experience_seeds={hasPattern=true,label="Experience Seeds",tag=""},
 mysticalagriculture_jj_fertilized_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_fiery_ingot_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_fiery_ingot_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_fiery_ingot_seeds={hasPattern=true,label="Fiery Ingot Seeds",tag=""},
 mysticalagriculture_jj_fire_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_fire_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_fire_seeds={hasPattern=true,label="Fire Seeds",tag=""},
 mysticalagriculture_jj_fluix_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_fluix_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_fluix_seeds={hasPattern=true,label="Fluix Seeds",tag=""},
 mysticalagriculture_jj_fluxed_electrum_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_fluxed_electrum_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_fluxed_electrum_seeds={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_gear={hasPattern=true,label="§eInferium Tool Core",tag=""},
 mysticalagriculture_jj_gear_jj_1={hasPattern=true,label="§aPrudentium Tool Core",tag=""},
 mysticalagriculture_jj_gear_jj_15={hasPattern=true,label="§eInferium Arrow Head",tag=""},
 mysticalagriculture_jj_gear_jj_16={hasPattern=true,label="§aPrudentium Arrow Head",tag=""},
 mysticalagriculture_jj_gear_jj_17={hasPattern=true,label="§6Intermedium Arrow Head",tag=""},
 mysticalagriculture_jj_gear_jj_18={hasPattern=true,label="§bSuperium Arrow Head",tag=""},
 mysticalagriculture_jj_gear_jj_19={hasPattern=true,label="§cSupremium Arrow Head",tag=""},
 mysticalagriculture_jj_gear_jj_2={hasPattern=true,label="§6Intermedium Tool Core",tag=""},
 mysticalagriculture_jj_gear_jj_3={hasPattern=true,label="§bSuperium Tool Core",tag=""},
 mysticalagriculture_jj_gear_jj_4={hasPattern=true,label="§cSupremium Tool Core",tag=""},
 mysticalagriculture_jj_gear_jj_5={hasPattern=true,label="§eInferium Armor Core",tag=""},
 mysticalagriculture_jj_gear_jj_6={hasPattern=true,label="§aPrudentium Armor Core",tag=""},
 mysticalagriculture_jj_gear_jj_7={hasPattern=true,label="§6Intermedium Armor Core",tag=""},
 mysticalagriculture_jj_gear_jj_8={hasPattern=true,label="§bSuperium Armor Core",tag=""},
 mysticalagriculture_jj_gear_jj_9={hasPattern=true,label="§cSupremium Armor Core",tag=""},
 mysticalagriculture_jj_ghast_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_ghast_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_ghast_seeds={hasPattern=true,label="Ghast Seeds",tag=""},
 mysticalagriculture_jj_glowstone_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_glowstone_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_glowstone_ingot_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_glowstone_ingot_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_glowstone_ingot_seeds={hasPattern=true,label="Glowstone Ingot Seeds",tag=""},
 mysticalagriculture_jj_glowstone_lamp={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_glowstone_seeds={hasPattern=true,label="Glowstone Seeds",tag=""},
 mysticalagriculture_jj_gold_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_gold_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_gold_seeds={hasPattern=true,label="Gold Seeds",tag=""},
 mysticalagriculture_jj_grains_of_infinity_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_grains_of_infinity_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_grains_of_infinity_seeds={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_graphite_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_graphite_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_graphite_seeds={hasPattern=true,label="Graphite Seeds",tag=""},
 mysticalagriculture_jj_growth_accelerator={hasPattern=true,label="§eGrowth Accelerator",tag=""},
 mysticalagriculture_jj_guardian_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_guardian_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_guardian_seeds={hasPattern=true,label="Guardian Seeds",tag=""},
 mysticalagriculture_jj_hop_graphite_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_hop_graphite_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_hop_graphite_seeds={hasPattern=true,label="HOP Graphite Seeds",tag=""},
 mysticalagriculture_jj_ice_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_ice_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_ice_seeds={hasPattern=true,label="Ice Seeds",tag=""},
 mysticalagriculture_jj_inferium_apple={hasPattern=true,label="§eInferium Apple",tag=""},
 mysticalagriculture_jj_inferium_arrow={hasPattern=true,label="§eInferium Arrow",tag=""},
 mysticalagriculture_jj_inferium_axe={hasPattern=true,label="§eInferium Axe",tag=""},
 mysticalagriculture_jj_inferium_boots={hasPattern=true,label="§eInferium Boots",tag=""},
 mysticalagriculture_jj_inferium_bow={hasPattern=true,label="§eInferium Bow",tag=""},
 mysticalagriculture_jj_inferium_chestplate={hasPattern=true,label="§eInferium Chestplate",tag=""},
 mysticalagriculture_jj_inferium_fishing_rod={hasPattern=true,label="§eInferium Fishing Rod",tag=""},
 mysticalagriculture_jj_inferium_furnace={hasPattern=true,label="§eInferium Furnace",tag=""},
 mysticalagriculture_jj_inferium_helmet={hasPattern=true,label="§eInferium Helmet",tag=""},
 mysticalagriculture_jj_inferium_hoe={hasPattern=true,label="§eInferium Hoe",tag=""},
 mysticalagriculture_jj_inferium_leggings={hasPattern=true,label="§eInferium Leggings",tag=""},
 mysticalagriculture_jj_inferium_ore={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_inferium_pickaxe={hasPattern=true,label="§eInferium Pickaxe",tag=""},
 mysticalagriculture_jj_inferium_reprocessor={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_inferium_scythe={hasPattern=true,label="§eInferium Scythe",tag=""},
 mysticalagriculture_jj_inferium_shears={hasPattern=true,label="§eInferium Shears",tag=""},
 mysticalagriculture_jj_inferium_shovel={hasPattern=true,label="§eInferium Shovel",tag=""},
 mysticalagriculture_jj_inferium_sickle={hasPattern=true,label="§eInferium Sickle",tag=""},
 mysticalagriculture_jj_inferium_sword={hasPattern=true,label="§eInferium Sword",tag=""},
 mysticalagriculture_jj_infusion_crystal={hasPattern=true,label="Infusion Crystal",tag=""},
 mysticalagriculture_jj_ingot_storage={hasPattern=true,label="Block of Base Essence",tag=""},
 mysticalagriculture_jj_ingot_storage_jj_1={hasPattern=true,label="§eBlock of Inferium",tag=""},
 mysticalagriculture_jj_ingot_storage_jj_2={hasPattern=true,label="§aBlock of Prudentium",tag=""},
 mysticalagriculture_jj_ingot_storage_jj_3={hasPattern=true,label="§6Block of Intermedium",tag=""},
 mysticalagriculture_jj_ingot_storage_jj_4={hasPattern=true,label="§bBlock of Superium",tag=""},
 mysticalagriculture_jj_ingot_storage_jj_5={hasPattern=true,label="§cBlock of Supremium",tag=""},
 mysticalagriculture_jj_ingot_storage_jj_6={hasPattern=true,label="§dBlock of Soulium",tag=""},
 mysticalagriculture_jj_intermedium_apple={hasPattern=true,label="§6Intermedium Apple",tag=""},
 mysticalagriculture_jj_intermedium_arrow={hasPattern=true,label="§6Intermedium Arrow",tag=""},
 mysticalagriculture_jj_intermedium_axe={hasPattern=true,label="§6Intermedium Axe",tag=""},
 mysticalagriculture_jj_intermedium_boots={hasPattern=true,label="§6Intermedium Boots",tag=""},
 mysticalagriculture_jj_intermedium_bow={hasPattern=true,label="§6Intermedium Bow",tag=""},
 mysticalagriculture_jj_intermedium_chestplate={hasPattern=true,label="§6Intermedium Chestplate",tag=""},
 mysticalagriculture_jj_intermedium_fishing_rod={hasPattern=true,label="§6Intermedium Fishing Rod",tag=""},
 mysticalagriculture_jj_intermedium_furnace={hasPattern=true,label="§6Intermedium Furnace",tag=""},
 mysticalagriculture_jj_intermedium_helmet={hasPattern=true,label="§6Intermedium Helmet",tag=""},
 mysticalagriculture_jj_intermedium_hoe={hasPattern=true,label="§6Intermedium Hoe",tag=""},
 mysticalagriculture_jj_intermedium_leggings={hasPattern=true,label="§6Intermedium Leggings",tag=""},
 mysticalagriculture_jj_intermedium_pickaxe={hasPattern=true,label="§6Intermedium Pickaxe",tag=""},
 mysticalagriculture_jj_intermedium_reprocessor={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_intermedium_scythe={hasPattern=true,label="§6Intermedium Scythe",tag=""},
 mysticalagriculture_jj_intermedium_shears={hasPattern=true,label="§6Intermedium Shears",tag=""},
 mysticalagriculture_jj_intermedium_shovel={hasPattern=true,label="§6Intermedium Shovel",tag=""},
 mysticalagriculture_jj_intermedium_sickle={hasPattern=true,label="§6Intermedium Sickle",tag=""},
 mysticalagriculture_jj_intermedium_sword={hasPattern=true,label="§6Intermedium Sword",tag=""},
 mysticalagriculture_jj_invar_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_invar_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_invar_seeds={hasPattern=true,label="Invar Seeds",tag=""},
 mysticalagriculture_jj_iridium_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_iridium_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_iridium_ore_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_iridium_ore_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_iridium_ore_seeds={hasPattern=true,label="Iridium Ore Seeds",tag=""},
 mysticalagriculture_jj_iridium_seeds={hasPattern=true,label="Iridium Seeds",tag=""},
 mysticalagriculture_jj_iron_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_iron_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_iron_seeds={hasPattern=true,label="Iron Seeds",tag=""},
 mysticalagriculture_jj_ironwood_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_ironwood_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_ironwood_seeds={hasPattern=true,label="Ironwood Seeds",tag=""},
 mysticalagriculture_jj_knightmetal_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_knightmetal_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_knightmetal_seeds={hasPattern=true,label="Knightmetal Seeds",tag=""},
 mysticalagriculture_jj_knightslime_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_knightslime_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_knightslime_seeds={hasPattern=true,label="Knightslime Seeds",tag=""},
 mysticalagriculture_jj_lapis_lazuli_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_lapis_lazuli_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_lapis_lazuli_seeds={hasPattern=true,label="Lapis Lazuli Seeds",tag=""},
 mysticalagriculture_jj_lead_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_lead_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_lead_seeds={hasPattern=true,label="Lead Seeds",tag=""},
 mysticalagriculture_jj_limestone_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_limestone_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_limestone_seeds={hasPattern=true,label="Limestone Seeds",tag=""},
 mysticalagriculture_jj_lithium_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_lithium_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_lithium_seeds={hasPattern=true,label="Lithium Seeds",tag=""},
 mysticalagriculture_jj_lumium_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_lumium_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_lumium_seeds={hasPattern=true,label="Lumium Seeds",tag=""},
 mysticalagriculture_jj_magnesium_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_magnesium_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_magnesium_seeds={hasPattern=true,label="Magnesium Seeds",tag=""},
 mysticalagriculture_jj_malachite_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_malachite_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_malachite_seeds={hasPattern=true,label="Malachite Seeds",tag=""},
 mysticalagriculture_jj_manasteel_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_manasteel_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_manasteel_seeds={hasPattern=true,label="Manasteel Seeds",tag=""},
 mysticalagriculture_jj_manyullyn_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_manyullyn_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_manyullyn_seeds={hasPattern=true,label="Manyullyn Seeds",tag=""},
 mysticalagriculture_jj_marble_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_marble_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_marble_seeds={hasPattern=true,label="Marble Seeds",tag=""},
 mysticalagriculture_jj_master_infusion_crystal={hasPattern=true,label="§cMaster Infusion Crystal",tag=""},
 mysticalagriculture_jj_menril_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_menril_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_menril_seeds={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_miners_torch={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_mithril_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_mithril_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_mithril_seeds={hasPattern=true,label="Mithril Seeds",tag=""},
 mysticalagriculture_jj_mystical_fertilizer={hasPattern=true,label="§dMystical Fertilizer",tag=""},
 mysticalagriculture_jj_mystical_flower_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_mystical_flower_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_mystical_flower_seeds={hasPattern=true,label="Mystical Flower Seeds",tag=""},
 mysticalagriculture_jj_mystical_machine_frame={hasPattern=true,label="Mystical Machine Frame",tag=""},
 mysticalagriculture_jj_nature_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_nature_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_nature_seeds={hasPattern=true,label="Nature Seeds",tag=""},
 mysticalagriculture_jj_nether_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_nether_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_nether_inferium_ore={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_nether_prosperity_ore={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_nether_quartz_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_nether_quartz_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_nether_quartz_seeds={hasPattern=true,label="Nether Quartz Seeds",tag=""},
 mysticalagriculture_jj_nether_seeds={hasPattern=true,label="Nether Seeds",tag=""},
 mysticalagriculture_jj_nickel_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_nickel_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_nickel_seeds={hasPattern=true,label="Nickel Seeds",tag=""},
 mysticalagriculture_jj_obsidian_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_obsidian_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_obsidian_seeds={hasPattern=true,label="Obsidian Seeds",tag=""},
 mysticalagriculture_jj_osmium_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_osmium_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_osmium_seeds={hasPattern=true,label="Osmium Seeds",tag=""},
 mysticalagriculture_jj_peridot_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_peridot_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_peridot_seeds={hasPattern=true,label="Peridot Seeds",tag=""},
 mysticalagriculture_jj_pig_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_pig_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_pig_seeds={hasPattern=true,label="Pig Seeds",tag=""},
 mysticalagriculture_jj_platinum_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_platinum_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_platinum_seeds={hasPattern=true,label="Platinum Seeds",tag=""},
 mysticalagriculture_jj_prosperity_ore={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_prudentium_apple={hasPattern=true,label="§aPrudentium Apple",tag=""},
 mysticalagriculture_jj_prudentium_arrow={hasPattern=true,label="§aPrudentium Arrow",tag=""},
 mysticalagriculture_jj_prudentium_axe={hasPattern=true,label="§aPrudentium Axe",tag=""},
 mysticalagriculture_jj_prudentium_boots={hasPattern=true,label="§aPrudentium Boots",tag=""},
 mysticalagriculture_jj_prudentium_bow={hasPattern=true,label="§aPrudentium Bow",tag=""},
 mysticalagriculture_jj_prudentium_chestplate={hasPattern=true,label="§aPrudentium Chestplate",tag=""},
 mysticalagriculture_jj_prudentium_fishing_rod={hasPattern=true,label="§aPrudentium Fishing Rod",tag=""},
 mysticalagriculture_jj_prudentium_furnace={hasPattern=true,label="§aPrudentium Furnace",tag=""},
 mysticalagriculture_jj_prudentium_helmet={hasPattern=true,label="§aPrudentium Helmet",tag=""},
 mysticalagriculture_jj_prudentium_hoe={hasPattern=true,label="§aPrudentium Hoe",tag=""},
 mysticalagriculture_jj_prudentium_leggings={hasPattern=true,label="§aPrudentium Leggings",tag=""},
 mysticalagriculture_jj_prudentium_pickaxe={hasPattern=true,label="§aPrudentium Pickaxe",tag=""},
 mysticalagriculture_jj_prudentium_reprocessor={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_prudentium_scythe={hasPattern=true,label="§aPrudentium Scythe",tag=""},
 mysticalagriculture_jj_prudentium_shears={hasPattern=true,label="§aPrudentium Shears",tag=""},
 mysticalagriculture_jj_prudentium_shovel={hasPattern=true,label="§aPrudentium Shovel",tag=""},
 mysticalagriculture_jj_prudentium_sickle={hasPattern=true,label="§aPrudentium Sickle",tag=""},
 mysticalagriculture_jj_prudentium_sword={hasPattern=true,label="§aPrudentium Sword",tag=""},
 mysticalagriculture_jj_pulsating_iron_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_pulsating_iron_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_pulsating_iron_seeds={hasPattern=true,label="Pulsating Iron Seeds",tag=""},
 mysticalagriculture_jj_quartz_enriched_iron_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_quartz_enriched_iron_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_quartz_enriched_iron_seeds={hasPattern=true,label="Quartz Enriched Iron Seeds",tag=""},
 mysticalagriculture_jj_quicksilver_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_quicksilver_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_quicksilver_seeds={hasPattern=true,label="Quicksilver Seeds",tag=""},
 mysticalagriculture_jj_rabbit_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_rabbit_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_rabbit_seeds={hasPattern=true,label="Rabbit Seeds",tag=""},
 mysticalagriculture_jj_redstone_alloy_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_redstone_alloy_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_redstone_alloy_seeds={hasPattern=true,label="Redstone Alloy Seeds",tag=""},
 mysticalagriculture_jj_redstone_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_redstone_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_redstone_seeds={hasPattern=true,label="Redstone Seeds",tag=""},
 mysticalagriculture_jj_refined_obsidian_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_refined_obsidian_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_refined_obsidian_seeds={hasPattern=true,label="Refined Obsidian Seeds",tag=""},
 mysticalagriculture_jj_rock_crystal_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_rock_crystal_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_rock_crystal_seeds={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_rubber_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_rubber_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_rubber_seeds={hasPattern=true,label="Rubber Seeds",tag=""},
 mysticalagriculture_jj_ruby_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_ruby_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_ruby_seeds={hasPattern=true,label="Ruby Seeds",tag=""},
 mysticalagriculture_jj_saltpeter_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_saltpeter_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_saltpeter_seeds={hasPattern=true,label="Saltpeter Seeds",tag=""},
 mysticalagriculture_jj_sapphire_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_sapphire_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_sapphire_seeds={hasPattern=true,label="Sapphire Seeds",tag=""},
 mysticalagriculture_jj_seed_reprocessor={hasPattern=true,label="Seed Reprocessor",tag=""},
 mysticalagriculture_jj_sheep_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_sheep_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_sheep_seeds={hasPattern=true,label="Sheep Seeds",tag=""},
 mysticalagriculture_jj_signalum_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_signalum_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_signalum_seeds={hasPattern=true,label="Signalum Seeds",tag=""},
 mysticalagriculture_jj_silicon_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_silicon_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_silicon_seeds={hasPattern=true,label="Silicon Seeds",tag=""},
 mysticalagriculture_jj_silver_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_silver_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_silver_seeds={hasPattern=true,label="Silver Seeds",tag=""},
 mysticalagriculture_jj_skeleton_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_skeleton_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_skeleton_seeds={hasPattern=true,label="Skeleton Seeds",tag=""},
 mysticalagriculture_jj_sky_stone_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_sky_stone_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_sky_stone_seeds={hasPattern=true,label="Sky Stone Seeds",tag=""},
 mysticalagriculture_jj_slate_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_slate_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_slate_seeds={hasPattern=true,label="Slate Seeds",tag=""},
 mysticalagriculture_jj_slime_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_slime_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_slime_seeds={hasPattern=true,label="Slime Seeds",tag=""},
 mysticalagriculture_jj_soul_glass={hasPattern=true,label="Soul Glass",tag=""},
 mysticalagriculture_jj_soul_glass_pane={hasPattern=true,label="Soul Glass Pane",tag=""},
 mysticalagriculture_jj_soularium_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_soularium_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_soularium_seeds={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_soulium_dagger={hasPattern=true,label="§dSoulium Dagger",tag=""},
 mysticalagriculture_jj_soulstone={hasPattern=true,label="Soulstone",tag=""},
 mysticalagriculture_jj_soulstone_brick_slab={hasPattern=true,label="Soulstone Brick Slab",tag=""},
 mysticalagriculture_jj_soulstone_brick_stairs={hasPattern=true,label="Soulstone Brick Stairs",tag=""},
 mysticalagriculture_jj_soulstone_brick_wall={hasPattern=true,label="Soulstone Brick Wall",tag=""},
 mysticalagriculture_jj_soulstone_jj_1={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_soulstone_jj_2={hasPattern=true,label="Polished Soulstone",tag=""},
 mysticalagriculture_jj_soulstone_jj_3={hasPattern=true,label="Soulstone Bricks",tag=""},
 mysticalagriculture_jj_soulstone_jj_4={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_soulstone_jj_5={hasPattern=true,label="Chiseled Soulstone",tag=""},
 mysticalagriculture_jj_soulstone_jj_6={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_soulstone_slab={hasPattern=true,label="Soulstone Slab",tag=""},
 mysticalagriculture_jj_spider_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_spider_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_spider_seeds={hasPattern=true,label="Spider Seeds",tag=""},
 mysticalagriculture_jj_star_steel_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_star_steel_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_star_steel_seeds={hasPattern=true,label="Star-Steel Seeds",tag=""},
 mysticalagriculture_jj_starmetal_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_starmetal_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_starmetal_seeds={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_steel_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_steel_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_steel_seeds={hasPattern=true,label="Steel Seeds",tag=""},
 mysticalagriculture_jj_steeleaf_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_steeleaf_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_steeleaf_seeds={hasPattern=true,label="Steeleaf Seeds",tag=""},
 mysticalagriculture_jj_stone_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_stone_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_stone_seeds={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_storage={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_storage_jj_1={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_storage_jj_2={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_storage_jj_3={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_storage_jj_4={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_storage_jj_5={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_sulfur_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_sulfur_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_sulfur_seeds={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_superium_apple={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_superium_arrow={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_superium_axe={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_superium_boots={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_superium_bow={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_superium_chestplate={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_superium_fishing_rod={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_superium_furnace={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_superium_helmet={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_superium_hoe={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_superium_leggings={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_superium_pickaxe={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_superium_reprocessor={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_superium_scythe={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_superium_shears={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_superium_shovel={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_superium_sickle={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_superium_sword={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_supremium_apple={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_supremium_arrow={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_supremium_axe={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_supremium_boots={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_supremium_bow={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_supremium_chestplate={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_supremium_fishing_rod={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_supremium_furnace={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_supremium_helmet={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_supremium_hoe={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_supremium_leggings={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_supremium_pickaxe={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_supremium_reprocessor={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_supremium_scythe={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_supremium_shears={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_supremium_shovel={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_supremium_sickle={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_supremium_sword={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_tanzanite_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_tanzanite_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_tanzanite_seeds={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_terrasteel_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_terrasteel_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_terrasteel_seeds={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_thaumium_crop={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_thaumium_essence={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_thaumium_seeds={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_thorium_crop={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_thorium_essence={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_thorium_seeds={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_tier1_inferium_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_tier1_inferium_seeds={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_tier2_inferium_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_tier2_inferium_seeds={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_tier3_inferium_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_tier3_inferium_seeds={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_tier4_inferium_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_tier4_inferium_seeds={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_tier5_inferium_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_tier5_inferium_seeds={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_tin_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_tin_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_tin_seeds={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_tinkering_table={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_tinkering_table_jj_1={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_tinkering_table_jj_2={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_tinkering_table_jj_3={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_tinkering_table_jj_4={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_titanium_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_titanium_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_titanium_seeds={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_topaz_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_topaz_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_topaz_seeds={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_tungsten_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_tungsten_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_tungsten_seeds={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_ultimate_furnace={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_ultimate_reprocessor={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_uranium_238_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_uranium_238_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_uranium_238_seeds={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_uranium_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_uranium_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_uranium_seeds={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_vibrant_alloy_crop={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_vibrant_alloy_essence={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_vibrant_alloy_seeds={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_void_metal_crop={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_void_metal_essence={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_void_metal_seeds={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_water_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_water_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_water_seeds={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_watering_can={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_watering_can_jj_1={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_watering_can_jj_2={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_watering_can_jj_3={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_watering_can_jj_4={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_wither_skeleton_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_wither_skeleton_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_wither_skeleton_seeds={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_witherproof_block={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_witherproof_glass={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_wood_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_wood_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_wood_seeds={hasPattern=true,label="",tag=""},
 mysticalagriculture_jj_xp_droplet={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_yellorium_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_yellorium_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_yellorium_seeds={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_zinc_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_zinc_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_zinc_seeds={hasPattern=true,label="Zinc Seeds",tag=""},
 mysticalagriculture_jj_zombie_crop={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_zombie_essence={hasPattern=false,label="",tag=""},
 mysticalagriculture_jj_zombie_seeds={hasPattern=true,label="Zombie Seeds",tag=""}
 }