return {
 actuallyadditions_jj_block_atomic_reconstructor={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_battery_box={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_bio_reactor={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_black_lotus={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_breaker={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_canola={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_canola_oil={c1="Industrial Squeezer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_canola_press={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_chiseled_quartz_slab={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_chiseled_quartz_stair={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_chiseled_quartz_wall={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_coal_generator={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_coffee={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_coffee_machine={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_on={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_on_jj_1={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_on_jj_10={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_on_jj_11={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_on_jj_12={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_on_jj_13={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_on_jj_14={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_on_jj_15={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_on_jj_2={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_on_jj_3={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_on_jj_4={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_on_jj_5={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_on_jj_6={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_on_jj_7={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_on_jj_8={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_colored_lamp_on_jj_9={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_compost={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_crystal={c1="Atomarer Umwandler",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_crystal_cluster_coal={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_crystal_cluster_diamond={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_crystal_cluster_emerald={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_crystal_cluster_iron={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_crystal_cluster_lapis={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_crystal_cluster_redstone={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_crystal_empowered={c1="Empowerer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_crystal_empowered_jj_1={c1="Empowerer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_crystal_empowered_jj_2={c1="Empowerer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_crystal_empowered_jj_3={c1="Empowerer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_crystal_empowered_jj_4={c1="Empowerer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_crystal_empowered_jj_5={c1="Empowerer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_crystal_jj_1={c1="Atomarer Umwandler",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_crystal_jj_2={c1="Atomarer Umwandler",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_crystal_jj_3={c1="Atomarer Umwandler",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_crystal_jj_4={c1="Atomarer Umwandler",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_crystal_jj_5={c1="Atomarer Umwandler",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_crystal_oil={c1="Open Crate Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_directional_breaker={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_display_stand={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_dropper={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_empowered_oil={c1="Open Crate Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_empowerer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_energizer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_enervator={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_farmer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_feeder={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_fermenting_barrel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_firework_box={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_fishing_net={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_flax={c1="auto",c2="Agrar Cloche",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_fluid_collector={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_fluid_placer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_furnace_double={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_furnace_solar={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_giant_chest={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_giant_chest_large={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_giant_chest_medium={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_greenhouse_glass={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_grinder={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_grinder_double={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_heat_collector={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_inputter={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_inputter_advanced={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_item_repairer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_item_viewer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_item_viewer_hopping={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_lamp_powerer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_laser_relay={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_laser_relay_advanced={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_laser_relay_extreme={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_laser_relay_fluids={c1="Atomarer Umwandler",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_laser_relay_item={c1="Atomarer Umwandler",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_laser_relay_item_whitelist={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_lava_factory_controller={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_leaf_generator={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_miner={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_misc={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_misc_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_misc_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_misc_jj_3={c1="auto",c2="ET - Erzsteinbruch",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_misc_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_misc_jj_5={c1="Chisel",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_misc_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_misc_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_misc_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_misc_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_oil_generator={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_phantom_booster={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_phantom_breaker={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_phantom_energyface={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_phantom_liquiface={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_phantom_placer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_phantom_redstoneface={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_phantomface={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_pillar_quartz_slab={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_pillar_quartz_stair={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_pillar_quartz_wall={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_placer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_player_interface={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_quartz_slab={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_quartz_stair={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_quartz_wall={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_ranged_collector={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_refined_canola_oil={c1="Fraktionierungsdestille",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_rice={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_shock_suppressor={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_smiley_cloud={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_testifi_bucks_green_fence={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_testifi_bucks_green_slab={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_testifi_bucks_green_stairs={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_testifi_bucks_green_wall={c1="Atomarer Umwandler",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_testifi_bucks_white_fence={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_testifi_bucks_white_slab={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_testifi_bucks_white_stairs={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_testifi_bucks_white_wall={c1="Atomarer Umwandler",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_tiny_torch={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_block_treasure_chest={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_wild={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_block_xp_solidifier={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_diamond_paxel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_emerald_paxel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_gold_paxel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_iron_paxel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_axe_crystal_black={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_axe_crystal_blue={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_axe_crystal_green={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_axe_crystal_light_blue={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_axe_crystal_red={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_axe_crystal_white={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_axe_emerald={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_axe_obsidian={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_axe_quartz={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_bag={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_battery={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Energy: 200000})"},
 actuallyadditions_jj_item_battery_double={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Energy: 350000})"},
 actuallyadditions_jj_item_battery_quadruple={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Energy: 1000000})"},
 actuallyadditions_jj_item_battery_quintuple={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Energy: 2000000})"},
 actuallyadditions_jj_item_battery_triple={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Energy: 600000})"},
 actuallyadditions_jj_item_booklet={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_boots_crystal_black={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_boots_crystal_blue={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_boots_crystal_green={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_boots_crystal_light_blue={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_boots_crystal_red={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_boots_crystal_white={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_boots_emerald={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_boots_obsidian={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_boots_quartz={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_canola_seed={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_chest_crystal_black={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_chest_crystal_blue={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_chest_crystal_green={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_chest_crystal_light_blue={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_chest_crystal_red={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_chest_crystal_white={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_chest_emerald={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_chest_obsidian={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_chest_quartz={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_chest_to_crate_upgrade={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_coffee={c1="manuell",c2="Kaffeemaschine",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_coffee_beans={c1="auto",c2="Agrar Cloche",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_coffee_seed={c1="auto",c2="Agrar Cloche",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_color_lens={c1="Atomarer Umwandler",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_crafter_on_a_stick={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_crate_keeper={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_crystal={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_crystal_empowered={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_crystal_empowered_jj_1={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_crystal_empowered_jj_2={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_crystal_empowered_jj_3={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_crystal_empowered_jj_4={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_crystal_empowered_jj_5={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_crystal_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_crystal_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_crystal_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_crystal_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_crystal_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_crystal_shard={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_crystal_shard_jj_1={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_crystal_shard_jj_2={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_crystal_shard_jj_3={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_crystal_shard_jj_4={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_crystal_shard_jj_5={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_damage_lens={c1="Atomarer Umwandler",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_disenchanting_lens={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_drill={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Energy: 250000})"},
 actuallyadditions_jj_item_drill_jj_1={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Energy: 250000})"},
 actuallyadditions_jj_item_drill_jj_10={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Energy: 250000})"},
 actuallyadditions_jj_item_drill_jj_11={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Energy: 250000})"},
 actuallyadditions_jj_item_drill_jj_12={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Energy: 250000})"},
 actuallyadditions_jj_item_drill_jj_13={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Energy: 250000})"},
 actuallyadditions_jj_item_drill_jj_14={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Energy: 250000})"},
 actuallyadditions_jj_item_drill_jj_15={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Energy: 250000})"},
 actuallyadditions_jj_item_drill_jj_2={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Energy: 250000})"},
 actuallyadditions_jj_item_drill_jj_3={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Energy: 250000})"},
 actuallyadditions_jj_item_drill_jj_4={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Energy: 250000})"},
 actuallyadditions_jj_item_drill_jj_5={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Energy: 250000})"},
 actuallyadditions_jj_item_drill_jj_6={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Energy: 250000})"},
 actuallyadditions_jj_item_drill_jj_7={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Energy: 250000})"},
 actuallyadditions_jj_item_drill_jj_8={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Energy: 250000})"},
 actuallyadditions_jj_item_drill_jj_9={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Energy: 250000})"},
 actuallyadditions_jj_item_drill_upgrade_block_placing={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_drill_upgrade_five_by_five={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_drill_upgrade_fortune={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_drill_upgrade_fortune_ii={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_drill_upgrade_silk_touch={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_drill_upgrade_speed={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_drill_upgrade_speed_ii={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_drill_upgrade_speed_iii={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_drill_upgrade_three_by_three={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_dust={c1="Ore Dict",c2="mekanism_jj_dust",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_dust_jj_1={c1="Ore Dict",c2="mekanism_jj_dust_jj_1",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_dust_jj_2={c1="Ore Dict",c2="mekanism_jj_otherdust",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_dust_jj_3={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_dust_jj_4={c1="Zerstoﬂer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_dust_jj_5={c1="Zerstoﬂer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_dust_jj_6={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_dust_jj_7={c1="auto",c2="Tektonischer Initiator",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_engineer_goggles={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_engineer_goggles_advanced={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_explosion_lens={c1="Atomarer Umwandler",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_fertilizer={c1="Kompost",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_filling_wand={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Energy: 500000})"},
 actuallyadditions_jj_item_filter={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_flax_seed={c1="auto",c2="Agrar Cloche",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_food={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_food_jj_1={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_food_jj_10={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_food_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_food_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_food_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_food_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_food_jj_15={c1="Trivektionskammer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_food_jj_16={c1="auto",c2="Agrar Cloche",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_food_jj_17={c1="Trivektionskammer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_food_jj_18={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_food_jj_19={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_food_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_food_jj_20={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_food_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_food_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_food_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_food_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_food_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_food_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_food_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_growth_ring={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Energy: 1000000})"},
 actuallyadditions_jj_item_hairy_ball={c1="Mob Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_helm_crystal_black={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_helm_crystal_blue={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_helm_crystal_green={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_helm_crystal_light_blue={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_helm_crystal_red={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_helm_crystal_white={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_helm_emerald={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_helm_obsidian={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_helm_quartz={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_hoe_crystal_black={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_hoe_crystal_blue={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_hoe_crystal_green={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_hoe_crystal_light_blue={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_hoe_crystal_red={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_hoe_crystal_white={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_hoe_emerald={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_hoe_obsidian={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_hoe_quartz={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_jam={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_jam_jj_1={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_jam_jj_2={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_jam_jj_3={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_jam_jj_4={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_jam_jj_5={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_jam_jj_6={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_knife={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_laser_upgrade_invisibility={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_laser_upgrade_range={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_laser_wrench={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_leaf_blower={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_leaf_blower_advanced={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_medium_to_large_crate_upgrade={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_mining_lens={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_1={c1="Kompost",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_13={c1="auto",c2="Agrar Cloche",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_15={c1="Chest Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_16={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_17={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_18={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_19={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_20={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_21={c1="Kompost",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_22={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_23={c1="Atomarer Umwandler",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_24={c1="Empowerer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_5={c1="auto",c2="Agrar Cloche / Mekanism Schmelzer",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_misc_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_more_damage_lens={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_pants_crystal_black={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_pants_crystal_blue={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_pants_crystal_green={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_pants_crystal_light_blue={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_pants_crystal_red={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_pants_crystal_white={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_pants_emerald={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_pants_obsidian={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_pants_quartz={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_paxel_crystal_black={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_paxel_crystal_blue={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_paxel_crystal_green={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_paxel_crystal_light_blue={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_paxel_crystal_red={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_paxel_crystal_white={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_phantom_connector={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_pickaxe_crystal_black={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_pickaxe_crystal_blue={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_pickaxe_crystal_green={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_pickaxe_crystal_light_blue={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_pickaxe_crystal_red={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_pickaxe_crystal_white={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_pickaxe_emerald={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_pickaxe_obsidian={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_pickaxe_quartz={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_player_probe={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_potion_ring={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_potion_ring_advanced={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_potion_ring_advanced_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_potion_ring_advanced_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_potion_ring_advanced_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_potion_ring_advanced_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_potion_ring_advanced_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_potion_ring_advanced_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_potion_ring_advanced_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_potion_ring_advanced_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_potion_ring_advanced_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_potion_ring_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_potion_ring_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_potion_ring_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_potion_ring_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_potion_ring_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_potion_ring_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_potion_ring_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_potion_ring_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_potion_ring_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_resonant_rice={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_rice_seed={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_shovel_crystal_black={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_shovel_crystal_blue={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_shovel_crystal_green={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_shovel_crystal_light_blue={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_shovel_crystal_red={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_shovel_crystal_white={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_shovel_emerald={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_shovel_obsidian={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_shovel_quartz={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_small_to_medium_crate_upgrade={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_solidified_experience={c1="auto",c2="Mob Drop / Ore",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_spawner_changer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_suction_ring={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag="({Energy: 0})"},
 actuallyadditions_jj_item_sword_crystal_black={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_sword_crystal_blue={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_sword_crystal_green={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_sword_crystal_light_blue={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_sword_crystal_red={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_sword_crystal_white={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_sword_emerald={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_sword_obsidian={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_sword_quartz={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_tele_staff={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag="({Energy: 0})"},
 actuallyadditions_jj_item_void_bag={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_water_bowl={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_item_water_removal_ring={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag="({Energy: 0})"},
 actuallyadditions_jj_item_wings_of_the_bats={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_item_worm={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 actuallyadditions_jj_obsidian_paxel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_quartz_paxel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_stone_paxel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 actuallyadditions_jj_wooden_paxel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""}
 }