return {
 botany_jj_botanist_bag={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_ceramic={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_1={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_10={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_11={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_12={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_13={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_14={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_15={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_16={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_17={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_18={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_19={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_2={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_20={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_21={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_22={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_23={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_24={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_25={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_26={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_27={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_28={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_29={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_3={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_30={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_31={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_32={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_33={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_34={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_35={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_36={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_37={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_38={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_39={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_4={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_40={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_41={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_42={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_43={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_44={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_45={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_46={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_47={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_48={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_49={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_5={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_50={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_51={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_52={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_53={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_54={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_55={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_56={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_57={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_58={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_59={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_6={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_60={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_61={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_62={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_63={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_64={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_65={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_66={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_67={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_68={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_69={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_7={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_70={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_71={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_72={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_73={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_74={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_75={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_76={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_77={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_78={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_79={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_8={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramic_jj_9={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_ceramicbrick={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag="({id: 0})"},
 botany_jj_ceramicpattern={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_clay={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_16={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_17={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_18={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_19={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_20={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_21={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_22={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_23={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_24={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_25={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_26={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_27={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_28={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_29={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_30={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_31={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_32={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_33={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_34={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_35={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_36={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_37={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_38={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_39={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_40={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_41={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_42={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_43={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_44={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_45={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_46={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_47={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_48={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_49={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_50={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_51={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_52={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_53={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_54={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_55={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_56={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_57={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_58={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_59={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_60={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_61={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_62={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_63={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_64={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_65={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_66={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_67={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_68={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_69={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_70={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_71={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_72={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_73={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_74={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_75={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_76={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_77={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_78={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_79={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_clay_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_database={c1="Schreinerei",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_database_jj_1={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_flowerbed={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_flowerbed_jj_1={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_flowerbed_jj_2={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_flowerbed_jj_3={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_flowerbed_jj_4={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_flowerbed_jj_5={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_flowerbed_jj_6={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_flowerbed_jj_7={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_flowerbed_jj_8={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_flowerbed_no_weed={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_flowerbed_no_weed_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_flowerbed_no_weed_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_flowerbed_no_weed_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_flowerbed_no_weed_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_flowerbed_no_weed_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_flowerbed_no_weed_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_flowerbed_no_weed_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_flowerbed_no_weed_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_insulated_tube={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_insulated_tube_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_insulated_tube_jj_128={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_insulated_tube_jj_129={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_insulated_tube_jj_130={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_insulated_tube_jj_131={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_insulated_tube_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_insulated_tube_jj_256={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_insulated_tube_jj_257={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_insulated_tube_jj_258={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_insulated_tube_jj_259={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_insulated_tube_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_insulated_tube_jj_384={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_insulated_tube_jj_385={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_insulated_tube_jj_386={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_insulated_tube_jj_387={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_insulated_tube_jj_512={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_insulated_tube_jj_513={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_insulated_tube_jj_514={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_insulated_tube_jj_515={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_insulated_tube_jj_640={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_insulated_tube_jj_641={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_insulated_tube_jj_642={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_insulated_tube_jj_643={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_itemflower={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Wilt: 0 as byte, Flowered: 1 as byte, IsAnalyzed: 0 as byte, Genome: {Chromosomes: [{UID1: botany.flowerDandelion, UID0: botany.flowerDandelion, Slot: 0 as byte}, {UID1: botany.colorYellow, UID0: botany.colorYellow, Slot: 1 as byte}, {UID1: botany.colorYellow, UID0: botany.colorYellow, Slot: 2 as byte}, {UID1: forestry.fertilityHigh, UID0: forestry.fertilityHigh, Slot: 3 as byte}, {UID1: forestry.territoryAverage, UID0: forestry.territoryAverage, Slot: 4 as byte}, {UID1: binnie.flowerEffectNone, UID0: binnie.flowerEffectNone, Slot: 5 as byte}, {UID1: forestry.lifespanShortened, UID0: forestry.lifespanShortened, Slot: 6 as byte}, {UID1: forestry.toleranceBoth1, UID0: forestry.toleranceBoth1, Slot: 7 as byte}, {UID1: forestry.toleranceBoth1, UID0: forestry.toleranceBoth1, Slot: 8 as byte}, {UID1: forestry.toleranceBoth1, UID0: forestry.toleranceBoth1, Slot: 9 as byte}, {UID1: forestry.sappinessLower, UID0: forestry.sappinessLower, Slot: 10 as byte}, {UID1: botany.colorGreen, UID0: botany.colorGreen, Slot: 11 as byte}]}, Age: 2})"},
 botany_jj_loam={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_loam_jj_1={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_loam_jj_2={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_loam_jj_3={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_loam_jj_4={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_loam_jj_5={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_loam_jj_6={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_loam_jj_7={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_loam_jj_8={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_loam_no_weed={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_loam_no_weed_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_loam_no_weed_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_loam_no_weed_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_loam_no_weed_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_loam_no_weed_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_loam_no_weed_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_loam_no_weed_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_loam_no_weed_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_machine={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_misc={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_misc_ceramic={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_misc_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_misc_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_misc_jj_3={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_misc_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_misc_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_misc_jj_6={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_misc_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_pigment={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_1={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_10={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_11={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_12={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_13={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_14={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_15={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_16={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_17={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_18={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_19={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_2={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_20={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_21={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_22={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_23={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_24={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_25={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_26={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_27={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_28={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_29={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_3={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_30={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_31={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_32={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_33={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_34={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_35={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_36={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_37={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_38={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_39={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_4={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_40={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_41={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_42={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_43={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_44={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_45={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_46={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_47={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_48={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_49={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_5={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_50={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_51={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_52={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_53={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_54={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_55={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_56={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_57={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_58={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_59={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_6={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_60={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_61={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_62={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_63={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_64={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_65={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_66={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_67={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_68={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_69={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_7={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_70={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_71={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_72={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_73={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_74={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_75={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_76={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_77={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_78={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_79={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_8={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pigment_jj_9={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_plant={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_plant_jj_1={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_plant_jj_2={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_plant_jj_3={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_plant_jj_4={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_pollen={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Wilt: 0 as byte, Flowered: 1 as byte, IsAnalyzed: 0 as byte, Genome: {Chromosomes: [{UID1: botany.flowerDandelion, UID0: botany.flowerDandelion, Slot: 0 as byte}, {UID1: botany.colorYellow, UID0: botany.colorYellow, Slot: 1 as byte}, {UID1: botany.colorYellow, UID0: botany.colorYellow, Slot: 2 as byte}, {UID1: forestry.fertilityHigh, UID0: forestry.fertilityHigh, Slot: 3 as byte}, {UID1: forestry.territoryAverage, UID0: forestry.territoryAverage, Slot: 4 as byte}, {UID1: binnie.flowerEffectNone, UID0: binnie.flowerEffectNone, Slot: 5 as byte}, {UID1: forestry.lifespanShortened, UID0: forestry.lifespanShortened, Slot: 6 as byte}, {UID1: forestry.toleranceBoth1, UID0: forestry.toleranceBoth1, Slot: 7 as byte}, {UID1: forestry.toleranceBoth1, UID0: forestry.toleranceBoth1, Slot: 8 as byte}, {UID1: forestry.toleranceBoth1, UID0: forestry.toleranceBoth1, Slot: 9 as byte}, {UID1: forestry.sappinessLower, UID0: forestry.sappinessLower, Slot: 10 as byte}, {UID1: botany.colorGreen, UID0: botany.colorGreen, Slot: 11 as byte}]}, Age: 0})"},
 botany_jj_seed={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({Wilt: 0 as byte, Flowered: 1 as byte, IsAnalyzed: 0 as byte, Genome: {Chromosomes: [{UID1: botany.flowerDandelion, UID0: botany.flowerDandelion, Slot: 0 as byte}, {UID1: botany.colorYellow, UID0: botany.colorYellow, Slot: 1 as byte}, {UID1: botany.colorYellow, UID0: botany.colorYellow, Slot: 2 as byte}, {UID1: forestry.fertilityHigh, UID0: forestry.fertilityHigh, Slot: 3 as byte}, {UID1: forestry.territoryAverage, UID0: forestry.territoryAverage, Slot: 4 as byte}, {UID1: binnie.flowerEffectNone, UID0: binnie.flowerEffectNone, Slot: 5 as byte}, {UID1: forestry.lifespanShortened, UID0: forestry.lifespanShortened, Slot: 6 as byte}, {UID1: forestry.toleranceBoth1, UID0: forestry.toleranceBoth1, Slot: 7 as byte}, {UID1: forestry.toleranceBoth1, UID0: forestry.toleranceBoth1, Slot: 8 as byte}, {UID1: forestry.toleranceBoth1, UID0: forestry.toleranceBoth1, Slot: 9 as byte}, {UID1: forestry.sappinessLower, UID0: forestry.sappinessLower, Slot: 10 as byte}, {UID1: botany.colorGreen, UID0: botany.colorGreen, Slot: 11 as byte}]}, Age: 0})"},
 botany_jj_soil={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_soil_jj_1={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_soil_jj_2={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_soil_jj_3={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_soil_jj_4={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_soil_jj_5={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_soil_jj_6={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_soil_jj_7={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_soil_jj_8={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 botany_jj_soil_meter={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_soil_no_weed={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_soil_no_weed_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_soil_no_weed_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_soil_no_weed_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_soil_no_weed_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_soil_no_weed_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_soil_no_weed_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_soil_no_weed_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_soil_no_weed_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_stained={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 0})"},
 botany_jj_stained_jj_1={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 1})"},
 botany_jj_stained_jj_10={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 10})"},
 botany_jj_stained_jj_11={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 11})"},
 botany_jj_stained_jj_12={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 12})"},
 botany_jj_stained_jj_13={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 13})"},
 botany_jj_stained_jj_14={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 14})"},
 botany_jj_stained_jj_15={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 15})"},
 botany_jj_stained_jj_16={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 16})"},
 botany_jj_stained_jj_17={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 17})"},
 botany_jj_stained_jj_18={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 18})"},
 botany_jj_stained_jj_19={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 19})"},
 botany_jj_stained_jj_2={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 2})"},
 botany_jj_stained_jj_20={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 20})"},
 botany_jj_stained_jj_21={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 21})"},
 botany_jj_stained_jj_22={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 22})"},
 botany_jj_stained_jj_23={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 23})"},
 botany_jj_stained_jj_24={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 24})"},
 botany_jj_stained_jj_25={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 25})"},
 botany_jj_stained_jj_26={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 26})"},
 botany_jj_stained_jj_27={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 27})"},
 botany_jj_stained_jj_28={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 28})"},
 botany_jj_stained_jj_29={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 29})"},
 botany_jj_stained_jj_3={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 3})"},
 botany_jj_stained_jj_30={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 30})"},
 botany_jj_stained_jj_31={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 31})"},
 botany_jj_stained_jj_32={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 32})"},
 botany_jj_stained_jj_33={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 33})"},
 botany_jj_stained_jj_34={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 34})"},
 botany_jj_stained_jj_35={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 35})"},
 botany_jj_stained_jj_36={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 36})"},
 botany_jj_stained_jj_37={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 37})"},
 botany_jj_stained_jj_38={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 38})"},
 botany_jj_stained_jj_39={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 39})"},
 botany_jj_stained_jj_4={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 4})"},
 botany_jj_stained_jj_40={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 40})"},
 botany_jj_stained_jj_41={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 41})"},
 botany_jj_stained_jj_42={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 42})"},
 botany_jj_stained_jj_43={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 43})"},
 botany_jj_stained_jj_44={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 44})"},
 botany_jj_stained_jj_45={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 45})"},
 botany_jj_stained_jj_46={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 46})"},
 botany_jj_stained_jj_47={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 47})"},
 botany_jj_stained_jj_48={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 48})"},
 botany_jj_stained_jj_49={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 49})"},
 botany_jj_stained_jj_5={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 5})"},
 botany_jj_stained_jj_50={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 50})"},
 botany_jj_stained_jj_51={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 51})"},
 botany_jj_stained_jj_52={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 52})"},
 botany_jj_stained_jj_53={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 53})"},
 botany_jj_stained_jj_54={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 54})"},
 botany_jj_stained_jj_55={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 55})"},
 botany_jj_stained_jj_56={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 56})"},
 botany_jj_stained_jj_57={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 57})"},
 botany_jj_stained_jj_58={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 58})"},
 botany_jj_stained_jj_59={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 59})"},
 botany_jj_stained_jj_6={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 6})"},
 botany_jj_stained_jj_60={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 60})"},
 botany_jj_stained_jj_61={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 61})"},
 botany_jj_stained_jj_62={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 62})"},
 botany_jj_stained_jj_63={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 63})"},
 botany_jj_stained_jj_64={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 64})"},
 botany_jj_stained_jj_65={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 65})"},
 botany_jj_stained_jj_66={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 66})"},
 botany_jj_stained_jj_67={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 67})"},
 botany_jj_stained_jj_68={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 68})"},
 botany_jj_stained_jj_69={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 69})"},
 botany_jj_stained_jj_7={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 7})"},
 botany_jj_stained_jj_70={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 70})"},
 botany_jj_stained_jj_71={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 71})"},
 botany_jj_stained_jj_72={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 72})"},
 botany_jj_stained_jj_73={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 73})"},
 botany_jj_stained_jj_74={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 74})"},
 botany_jj_stained_jj_75={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 75})"},
 botany_jj_stained_jj_76={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 76})"},
 botany_jj_stained_jj_77={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 77})"},
 botany_jj_stained_jj_78={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 78})"},
 botany_jj_stained_jj_79={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 79})"},
 botany_jj_stained_jj_8={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 8})"},
 botany_jj_stained_jj_9={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({meta: 9})"},
 botany_jj_trowel_diamond={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_trowel_gold={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_trowel_iron={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_trowel_stone={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 botany_jj_trowel_wood={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 extrabees_jj_alveary={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 extrabees_jj_alveary_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 extrabees_jj_alveary_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 extrabees_jj_alveary_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 extrabees_jj_alveary_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 extrabees_jj_alveary_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 extrabees_jj_alveary_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 extrabees_jj_dictionary={c1="Schreinerei",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_dictionary_jj_1={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_ectoplasm={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_hive={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_hive_frame_vv_cage={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 extrabees_jj_hive_frame_vv_clay={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 extrabees_jj_hive_frame_vv_cocoa={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 extrabees_jj_hive_frame_vv_debug={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_hive_frame_vv_soul={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 extrabees_jj_hive_jj_1={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_hive_jj_2={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_hive_jj_3={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_1={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_10={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_11={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_12={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_14={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_15={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_16={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_17={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_18={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_19={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_2={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_21={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_22={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_23={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_24={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_25={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_26={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_27={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_28={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_29={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_3={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_30={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_32={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_36={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_37={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_4={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_40={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_41={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_42={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_45={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_46={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_47={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_48={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_49={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_50={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_51={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_52={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_53={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_54={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_56={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_57={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_58={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_59={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_6={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_60={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_61={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_62={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_63={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_64={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_65={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_66={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_67={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_68={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_69={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_7={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_70={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_71={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_72={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_73={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_75={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_76={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_79={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_8={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_81={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_82={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_83={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_84={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_85={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_comb_jj_9={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_crystal={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag="({charge: 8000.0})"},
 extrabees_jj_honey_crystal_jj_26={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 extrabees_jj_honey_drop={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_drop_jj_1={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_drop_jj_13={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_drop_jj_14={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_drop_jj_15={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_drop_jj_16={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_drop_jj_17={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_drop_jj_18={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_drop_jj_19={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_drop_jj_2={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_drop_jj_20={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_drop_jj_21={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_drop_jj_22={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_drop_jj_23={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_drop_jj_24={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_drop_jj_25={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_drop_jj_26={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_drop_jj_27={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_drop_jj_28={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_drop_jj_3={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_drop_jj_5={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_drop_jj_6={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_drop_jj_7={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_honey_drop_jj_8={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc={c1="Schreinerei",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_1={c1="r",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_10={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_11={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_12={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_13={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_14={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_15={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_16={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_17={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_18={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_19={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_2={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_20={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_21={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_22={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_23={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_24={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_25={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_26={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_27={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_28={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_29={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_3={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_4={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_5={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_6={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_7={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_8={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_misc_jj_9={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_propolis={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_propolis_jj_1={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 extrabees_jj_propolis_jj_7={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_apiary_vv_upgrade={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_apiary_vv_upgrade_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_apiary_vv_upgrade_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_apiary_vv_upgrade_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_apiary_vv_upgrade_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_apiary_vv_upgrade_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_apiary_vv_upgrade_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_apiary_vv_upgrade_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_apiary_vv_upgrade_jj_16={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_apiary_vv_upgrade_jj_17={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_apiary_vv_upgrade_jj_18={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_apiary_vv_upgrade_jj_19={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_apiary_vv_upgrade_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_apiary_vv_upgrade_jj_20={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_apiary_vv_upgrade_jj_21={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_apiary_vv_upgrade_jj_22={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_apiary_vv_upgrade_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_apiary_vv_upgrade_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_apiary_vv_upgrade_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_apiary_vv_upgrade_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_apiary_vv_upgrade_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_bee_receptacle={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_climate_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_eject_cover={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_env_processor={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_error_sensor_cover={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_extractor={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_gene_sample={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_gene_sample_blank={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_gene_template={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_genetics_processor={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_hive_spawn_debugger={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_comb_jj_10={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_comb_jj_11={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_comb_jj_12={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_comb_jj_13={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_comb_jj_14={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_comb_jj_15={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_comb_jj_16={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_comb_jj_17={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_comb_jj_18={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_comb_jj_19={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_comb_jj_20={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_comb_jj_21={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_comb_jj_22={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_comb_jj_23={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_comb_jj_24={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_comb_jj_25={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_drop_jj_10={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_drop_jj_11={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_drop_jj_12={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_drop_jj_13={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_drop_jj_14={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_drop_jj_15={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_drop_jj_16={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_drop_jj_17={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_drop_jj_18={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_drop_jj_19={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_drop_jj_20={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_drop_jj_21={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_drop_jj_22={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_drop_jj_23={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_drop_jj_24={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_honey_drop_jj_25={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_import_cover={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_imprinter={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_industrial_apiary={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_industrial_grafter={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_industrial_grafter_jj_1={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({charge: 100000})"},
 gendustry_jj_industrial_scoop={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_industrial_scoop_jj_1={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({charge: 5000})"},
 gendustry_jj_labware={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_liquiddna={c1="Presse",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_liquifier={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_mutagen={c1="Abfüller",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_mutagen_producer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_mutagen_tank={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_mutatron={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_mutatron_advanced={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_pollen_kit={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_power_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_protein={c1="Abfüller",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 gendustry_jj_replicator={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_sampler={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_transposer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_upgrade_frame={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 gendustry_jj_waste={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 genetics_jj_adv_machine={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 genetics_jj_analyst={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 genetics_jj_geneticdatabase={c1="Schreinerei",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 genetics_jj_geneticdatabase_jj_1={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 genetics_jj_lab_machine={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 genetics_jj_lab_machine_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 genetics_jj_lab_machine_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 genetics_jj_lab_machine_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 genetics_jj_lab_machine_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 genetics_jj_machine={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 genetics_jj_machine_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 genetics_jj_machine_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 genetics_jj_machine_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 genetics_jj_master_registry={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 genetics_jj_misc={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 genetics_jj_misc_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 genetics_jj_misc_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 genetics_jj_misc_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 genetics_jj_misc_jj_3={c1="Incubation",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 genetics_jj_misc_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 genetics_jj_misc_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 genetics_jj_misc_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 genetics_jj_misc_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 genetics_jj_misc_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 genetics_jj_misc_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 genetics_jj_punnett_square={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 genetics_jj_registry={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 genetics_jj_sequence_jj_5={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({gene: {allele: forestry.speciesMeadows, root: rootBees, chromo: 0 as byte}, ana: 0 as byte, seq: 0 as byte})"},
 genetics_jj_serum={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({gene: {allele: forestry.speciesSecluded, root: rootBees, chromo: 0 as byte}})"},
 genetics_jj_serum_array={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({genes: [{allele: forestry.speciesForest, root: rootBees, chromo: 0 as byte}, {allele: forestry.speedSlowest, root: rootBees, chromo: 1 as byte}, {allele: forestry.lifespanShorter, root: rootBees, chromo: 2 as byte}, {allele: forestry.fertilityHigh, root: rootBees, chromo: 3 as byte}, {allele: forestry.toleranceNone, root: rootBees, chromo: 4 as byte}, {allele: forestry.boolFalse, root: rootBees, chromo: 5 as byte}, {allele: forestry.toleranceNone, root: rootBees, chromo: 6 as byte}, {allele: forestry.boolFalse, root: rootBees, chromo: 7 as byte}, {allele: forestry.boolFalse, root: rootBees, chromo: 8 as byte}, {allele: forestry.flowersVanilla, root: rootBees, chromo: 9 as byte}, {allele: forestry.floweringSlower, root: rootBees, chromo: 10 as byte}, {allele: forestry.territoryAverage, root: rootBees, chromo: 11 as byte}, {allele: forestry.effectNone, root: rootBees, chromo: 12 as byte}]})"},
 magicbees_jj_beecomb={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_beecomb_jj_1={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_beecomb_jj_2={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_beecomb_jj_3={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_beecomb_jj_4={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_beecomb_jj_5={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_beecomb_jj_6={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_drop={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_drop_jj_1={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_drop_jj_2={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_drop_jj_3={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_drop_jj_4={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_drop_jj_5={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_effectjar={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_enchanted_earth={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_frames_vv_gentle={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_frames_vv_magic={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_frames_vv_metabolic={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_frames_vv_necrotic={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_frames_vv_oblivion={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_frames_vv_resilient={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_frames_vv_temporal={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_hiveblock={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_hiveblock_jj_1={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_hiveblock_jj_2={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_hiveblock_jj_3={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_hiveblock_jj_4={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_hiveblock_jj_5={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_manasteelgrafter={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_manasteelscoop={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_moondial={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_mysteriousmagnet={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_mysteriousmagnet_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_mysteriousmagnet_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_mysteriousmagnet_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_mysteriousmagnet_jj_16={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_mysteriousmagnet_jj_18={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_mysteriousmagnet_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_mysteriousmagnet_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_mysteriousmagnet_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_mysteriousmagnet_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_orepart={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_orepart_jj_1={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_orepart_jj_2={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_orepart_jj_3={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_orepart_jj_4={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_orepart_jj_5={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_pollen={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_pollen_jj_1={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_propolis={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_propolis_jj_1={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_propolis_jj_2={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_propolis_jj_3={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_propolis_jj_4={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_propolis_jj_5={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_propolis_jj_6={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_resource={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_resource_jj_1={c1="Schreinerei",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_resource_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_resource_jj_11={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_resource_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_resource_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_resource_jj_2={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_resource_jj_3={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_resource_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_resource_jj_5={c1="Bee Produce",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_resource_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_resource_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_resource_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_resource_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 magicbees_jj_wax={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_wax_jj_1={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""},
 magicbees_jj_wax_jj_2={c1="auto",c2="Zentrifuge",c3="",hasPattern=false,maxCount=8,tag=""}
 }