return {
 mekanism_jj_anchorupgrade={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_armoredjetpack={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag="({mekData: {}})"},
 mekanism_jj_atomicalloy={c1="Metallurgische Infusionsmaschine",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_atomicdisassembler={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_balloon={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_balloon_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_balloon_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_balloon_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_balloon_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_balloon_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_balloon_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_balloon_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_balloon_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_balloon_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_balloon_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_balloon_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_balloon_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_balloon_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_balloon_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_balloon_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_basicblock={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_basicblock2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_basicblock2_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_basicblock2_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_basicblock2_jj_3={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({tier: 0})"},
 mekanism_jj_basicblock2_jj_4={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({tier: 0})"},
 mekanism_jj_basicblock2_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_basicblock2_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_basicblock2_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_basicblock2_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_basicblock2_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_basicblock_jj_1={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_basicblock_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_basicblock_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_basicblock_jj_12={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_basicblock_jj_13={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_basicblock_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_basicblock_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_basicblock_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_basicblock_jj_3={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_basicblock_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_basicblock_jj_5={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_basicblock_jj_6={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({tier: 0})"},
 mekanism_jj_basicblock_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_basicblock_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_basicblock_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_biofuel={c1="Zerstoﬂer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_boundingblock={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_cardboardbox={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_clump={c1="xx",c2="auto",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_clump_jj_1={c1="xx",c2="auto",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_clump_jj_2={c1="xx",c2="auto",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_clump_jj_3={c1="xx",c2="auto",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_clump_jj_4={c1="xx",c2="auto",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_clump_jj_5={c1="xx",c2="auto",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_clump_jj_6={c1="xx",c2="auto",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_compressedcarbon={c1="Anreicherungskammer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_compresseddiamond={c1="Anreicherungskammer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_compressedobsidian={c1="Anreicherungskammer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_compressedredstone={c1="Anreicherungskammer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_configurationcard={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_configurator={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_controlcircuit={c1="Metallurgische Infusionsmaschine",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_controlcircuit_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_controlcircuit_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_controlcircuit_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_craftingformula={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_crystal={c1="Chemischer Kristallisierer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_crystal_jj_1={c1="Chemischer Kristallisierer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_crystal_jj_2={c1="Chemischer Kristallisierer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_crystal_jj_3={c1="Chemischer Kristallisierer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_crystal_jj_4={c1="Chemischer Kristallisierer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_crystal_jj_5={c1="Chemischer Kristallisierer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_crystal_jj_6={c1="Chemischer Kristallisierer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_dictionary={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_dirtydust={c1="Zerstoﬂer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_dirtydust_jj_1={c1="Zerstoﬂer",c2="auto",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_dirtydust_jj_2={c1="Zerstoﬂer",c2="auto",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_dirtydust_jj_3={c1="Zerstoﬂer",c2="auto",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_dirtydust_jj_4={c1="Zerstoﬂer",c2="auto",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_dirtydust_jj_5={c1="Zerstoﬂer",c2="auto",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_dirtydust_jj_6={c1="Zerstoﬂer",c2="auto",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_dust={c1="Zerstoﬂer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_dust_jj_1={c1="Zerstoﬂer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_dust_jj_2={c1="Zerstoﬂer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_dust_jj_3={c1="Zerstoﬂer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_dust_jj_4={c1="Zerstoﬂer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_dust_jj_5={c1="Zerstoﬂer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_dust_jj_6={c1="Zerstoﬂer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_electricbow={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_electrolyticcore={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_energycube={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({tier: 0})"},
 mekanism_jj_energytablet={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_energyupgrade={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_enrichedalloy={c1="Metallurgische Infusionsmaschine",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_enrichediron={c1="xx",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_filterupgrade={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_flamethrower={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag="({mekData: {}})"},
 mekanism_jj_freerunners={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_gasmask={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_gastank={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({tier: 0})"},
 mekanism_jj_gasupgrade={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_gaugedropper={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag="({mekData: {}})"},
 mekanism_jj_glowpanel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowpanel_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowpanel_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowpanel_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowpanel_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowpanel_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowpanel_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowpanel_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowpanel_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowpanel_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowpanel_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowpanel_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowpanel_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowpanel_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowpanel_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowpanel_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowplasticblock={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowplasticblock_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowplasticblock_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowplasticblock_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowplasticblock_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowplasticblock_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowplasticblock_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowplasticblock_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowplasticblock_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowplasticblock_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowplasticblock_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowplasticblock_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowplasticblock_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowplasticblock_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowplasticblock_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_glowplasticblock_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_ingot={c1="Auto - Agrar Gloche",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_ingot_jj_1={c1="Auto - Agrar Gloche",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_ingot_jj_2={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_ingot_jj_3={c1="Auto - Agrar Gloche",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_ingot_jj_4={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_ingot_jj_5={c1="schmelzsplitting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_ingot_jj_6={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_itemproxy={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_jetpack={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({mekData: {stored: {amount: 24000, gasName: hydrogen}}})"},
 mekanism_jj_machineblock={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_machineblock2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock2_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock2_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock2_jj_11={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({tier: 0})"},
 mekanism_jj_machineblock2_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock2_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock2_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock2_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock2_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock2_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock2_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock2_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock2_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock2_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock2_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock2_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock3_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock3_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock3_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock3_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock3_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock_jj_5={c1="manuell",c2="tierinstaller",c3="",hasPattern=false,maxCount=8,tag="({recipeType: 0})"},
 mekanism_jj_machineblock_jj_6={c1="manuell",c2="tierinstaller",c3="",hasPattern=false,maxCount=8,tag="({recipeType: 0})"},
 mekanism_jj_machineblock_jj_7={c1="manuell",c2="tierinstaller",c3="",hasPattern=false,maxCount=8,tag="({recipeType: 0})"},
 mekanism_jj_machineblock_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_machineblock_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_mufflingupgrade={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_networkreader={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_nugget={c1="xx",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_nugget_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_nugget_jj_2={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_nugget_jj_3={c1="xx",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_nugget_jj_4={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_nugget_jj_5={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_nugget_jj_6={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_obsidiantnt={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_oreblock={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_oreblock_jj_1={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_oreblock_jj_2={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_otherdust={c1="Zerstoﬂer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_otherdust_jj_1={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_otherdust_jj_3={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_otherdust_jj_4={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_otherdust_jj_5={c1="Metallurgische Infusionsmaschine",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_otherdust_jj_6={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_plasticblock={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticblock_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticblock_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticblock_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticblock_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticblock_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticblock_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticblock_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticblock_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticblock_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticblock_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticblock_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticblock_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticblock_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticblock_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticblock_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticfence={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticfence_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticfence_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticfence_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticfence_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticfence_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticfence_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticfence_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticfence_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticfence_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticfence_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticfence_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticfence_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticfence_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticfence_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_plasticfence_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_polyethene={c1="PRC",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_polyethene_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_polyethene_jj_2={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_polyethene_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_portableteleporter={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_reinforcedalloy={c1="Metallurgische Infusionsmaschine",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_reinforcedplasticblock={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_reinforcedplasticblock_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_reinforcedplasticblock_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_reinforcedplasticblock_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_reinforcedplasticblock_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_reinforcedplasticblock_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_reinforcedplasticblock_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_reinforcedplasticblock_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_reinforcedplasticblock_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_reinforcedplasticblock_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_reinforcedplasticblock_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_reinforcedplasticblock_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_reinforcedplasticblock_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_reinforcedplasticblock_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_reinforcedplasticblock_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_reinforcedplasticblock_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_roadplasticblock={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_roadplasticblock_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_roadplasticblock_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_roadplasticblock_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_roadplasticblock_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_roadplasticblock_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_roadplasticblock_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_roadplasticblock_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_roadplasticblock_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_roadplasticblock_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_roadplasticblock_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_roadplasticblock_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_roadplasticblock_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_roadplasticblock_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_roadplasticblock_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_roadplasticblock_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_robit={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_salt={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_saltblock={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_sawdust={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_scubatank={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag="({mekData: {}})"},
 mekanism_jj_seismicreader={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_shard={c1="Chemischer Injektionskammer",c2="auto",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_shard_jj_1={c1="Chemischer Injektionskammer",c2="auto",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_shard_jj_2={c1="Chemischer Injektionskammer",c2="auto",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_shard_jj_3={c1="Chemischer Injektionskammer",c2="auto",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_shard_jj_4={c1="Chemischer Injektionskammer",c2="auto",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_shard_jj_5={c1="Chemischer Injektionskammer",c2="auto",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_shard_jj_6={c1="Chemischer Injektionskammer",c2="auto",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_slickplasticblock={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_slickplasticblock_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_slickplasticblock_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_slickplasticblock_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_slickplasticblock_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_slickplasticblock_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_slickplasticblock_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_slickplasticblock_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_slickplasticblock_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_slickplasticblock_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_slickplasticblock_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_slickplasticblock_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_slickplasticblock_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_slickplasticblock_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_slickplasticblock_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_slickplasticblock_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_speedupgrade={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_substrate={c1="PRC",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_teleportationcore={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_tierinstaller={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanism_jj_tierinstaller_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_tierinstaller_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_tierinstaller_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanism_jj_transmitter={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({tier: 0})"},
 mekanism_jj_transmitter_jj_1={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({tier: 0})"},
 mekanism_jj_transmitter_jj_2={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({tier: 0})"},
 mekanism_jj_transmitter_jj_3={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({tier: 0})"},
 mekanism_jj_transmitter_jj_4={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({tier: 0})"},
 mekanism_jj_transmitter_jj_5={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({tier: 0})"},
 mekanism_jj_transmitter_jj_6={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({tier: 0})"},
 mekanism_jj_walkietalkie={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismgenerators_jj_generator={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismgenerators_jj_generator_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismgenerators_jj_generator_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismgenerators_jj_generator_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismgenerators_jj_generator_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismgenerators_jj_generator_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismgenerators_jj_generator_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismgenerators_jj_generator_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismgenerators_jj_generator_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismgenerators_jj_generator_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismgenerators_jj_generator_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismgenerators_jj_generator_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismgenerators_jj_generator_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismgenerators_jj_hohlraum={c1="manuell",c2="Metallurgische Infusionsmaschine",c3="",hasPattern=false,maxCount=8,tag="({mekData: {}})"},
 mekanismgenerators_jj_reactor={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismgenerators_jj_reactor_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismgenerators_jj_reactor_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismgenerators_jj_reactor_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismgenerators_jj_reactorglass={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismgenerators_jj_reactorglass_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismgenerators_jj_solarpanel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismgenerators_jj_turbineblade={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_bronzeaxe={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanismtools_jj_bronzeboots={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanismtools_jj_bronzechestplate={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanismtools_jj_bronzehelmet={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanismtools_jj_bronzehoe={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanismtools_jj_bronzeleggings={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanismtools_jj_bronzepaxel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_bronzepickaxe={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanismtools_jj_bronzeshovel={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanismtools_jj_bronzesword={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 mekanismtools_jj_diamondpaxel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_glowstoneaxe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_glowstoneboots={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_glowstonechestplate={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_glowstonehelmet={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_glowstonehoe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_glowstoneleggings={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_glowstonepaxel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_glowstonepickaxe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_glowstoneshovel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_glowstonesword={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_goldpaxel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_ironpaxel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_lapislazuliaxe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_lapislazuliboots={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_lapislazulichestplate={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_lapislazulihelmet={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_lapislazulihoe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_lapislazulileggings={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_lapislazulipaxel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_lapislazulipickaxe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_lapislazulishovel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_lapislazulisword={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_obsidianaxe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_obsidianboots={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_obsidianchestplate={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_obsidianhelmet={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_obsidianhoe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_obsidianleggings={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_obsidianpaxel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_obsidianpickaxe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_obsidianshovel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_obsidiansword={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_osmiumaxe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_osmiumboots={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_osmiumchestplate={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_osmiumhelmet={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_osmiumhoe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_osmiumleggings={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_osmiumpaxel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_osmiumpickaxe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_osmiumshovel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_osmiumsword={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_steelaxe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_steelboots={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_steelchestplate={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_steelhelmet={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_steelhoe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_steelleggings={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_steelpaxel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_steelpickaxe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_steelshovel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_steelsword={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_stonepaxel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 mekanismtools_jj_woodpaxel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""}
 }