return {
 minecraft_jj_acacia_boat={c1="",c2="",c3="",hasPattern=true,maxCount=64,tag=""},
 minecraft_jj_acacia_door={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_acacia_fence={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_acacia_fence_gate={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_acacia_stairs={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_activator_rail={c1="",c2="",c3="",hasPattern=true,maxCount=512,tag=""},
 minecraft_jj_air={c1="",c2="",c3="",hasPattern=false,maxCount=1,tag=""},
 minecraft_jj_anvil={c1="",c2="",c3="",hasPattern=true,maxCount=512,tag=""},
 minecraft_jj_anvil_jj_1={c1="",c2="",c3="",hasPattern=false,maxCount=1,tag=""},
 minecraft_jj_anvil_jj_2={c1="",c2="",c3="",hasPattern=false,maxCount=1,tag=""},
 minecraft_jj_apple={c1="Sapling Infuser",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_armor_stand={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_arrow={c1="",c2="",c3="",hasPattern=true,maxCount=512,tag=""},
 minecraft_jj_baked_potato={c1="Trivektionskammer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_banner={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_banner_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_banner_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_banner_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_banner_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_banner_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_banner_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_banner_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_banner_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_banner_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_banner_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_banner_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_banner_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_banner_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_banner_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_banner_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_barrier={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_beacon={c1="",c2="",c3="",hasPattern=true,maxCount=64,tag=""},
 minecraft_jj_bed={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_bed_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_bed_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_bed_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_bed_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_bed_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_bed_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_bed_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_bed_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_bed_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_bed_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_bed_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_bed_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_bed_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_bed_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_bed_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_bedrock={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_beef={c1="Mob Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_beetroot={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_beetroot_seeds={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_beetroot_soup={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_birch_boat={c1="",c2="",c3="",hasPattern=true,maxCount=64,tag=""},
 minecraft_jj_birch_door={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_birch_fence={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_birch_fence_fate={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_birch_fence_gate={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_birch_stairs={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_black_glazed_terracotta={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_black_shulker_box={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_blaze_powder={c1="auto",c2="",c3="",hasPattern=false,maxCount=640,tag=""},
 minecraft_jj_blaze_rod={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_blue_glazed_terracotta={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_blue_shulker_box={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_boat={c1="",c2="",c3="",hasPattern=true,maxCount=64,tag=""},
 minecraft_jj_bone={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_bone_block={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_book={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_bookshelf={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_bow={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_bowl={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_bread={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_brewing_stand={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_brick={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_brick_block={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_brick_stairs={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_brown_glazed_terracotta={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_brown_mushroom={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_brown_mushroom_block={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_brown_shulker_box={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_bucket={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_cactus={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_cake={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_carpet={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_carpet_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_carpet_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_carpet_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_carpet_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_carpet_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_carpet_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_carpet_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_carpet_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_carpet_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_carpet_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_carpet_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_carpet_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_carpet_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_carpet_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_carpet_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_carrot={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_carrot_on_a_stick={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_cauldron={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_chain_command_block={c1="",c2="",c3="",hasPattern=true,maxCount=64,tag=""},
 minecraft_jj_chainmail_boots={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_chainmail_chestplate={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_chainmail_helmet={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_chainmail_leggings={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_chest={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_chest_minecart={c1="",c2="",c3="",hasPattern=true,maxCount=64,tag=""},
 minecraft_jj_chicken={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_chorus_flower={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_chorus_fruit={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_chorus_fruit_popped={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_chorus_plant={c1="Phytogeninsolator",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_clay={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_clay_ball={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_clock={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_clownfish={c1="Water Trap",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_coal={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_coal_block={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_coal_jj_1={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_coal_ore={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_cobblestone={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_cobblestone_wall={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_cobblestone_wall_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_cod={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_command_block={c1="",c2="",c3="",hasPattern=true,maxCount=64,tag=""},
 minecraft_jj_command_block_minecart={c1="",c2="",c3="",hasPattern=true,maxCount=64,tag=""},
 minecraft_jj_comparator={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_compass={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_concrete={c1="Fluidtransposer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_concrete_jj_1={c1="Fluidtransposer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_concrete_jj_10={c1="Fluidtransposer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_concrete_jj_11={c1="Fluidtransposer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_concrete_jj_12={c1="Fluidtransposer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_concrete_jj_13={c1="Fluidtransposer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_concrete_jj_14={c1="Fluidtransposer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_concrete_jj_15={c1="Fluidtransposer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_concrete_jj_2={c1="Fluidtransposer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_concrete_jj_3={c1="Fluidtransposer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_concrete_jj_4={c1="Fluidtransposer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_concrete_jj_5={c1="Fluidtransposer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_concrete_jj_6={c1="Fluidtransposer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_concrete_jj_7={c1="Fluidtransposer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_concrete_jj_8={c1="Fluidtransposer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_concrete_jj_9={c1="Fluidtransposer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_concrete_powder={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_concrete_powder_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_concrete_powder_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_concrete_powder_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_concrete_powder_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_concrete_powder_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_concrete_powder_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_concrete_powder_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_concrete_powder_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_concrete_powder_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_concrete_powder_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_concrete_powder_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_concrete_powder_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_concrete_powder_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_concrete_powder_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_concrete_powder_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_cooked_beef={c1="Trivektionskammer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_cooked_chicken={c1="Trivektionskammer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_cooked_cod={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_cooked_fish={c1="Trivektionskammer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_cooked_fish_jj_1={c1="Trivektionskammer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_cooked_mutton={c1="Trivektionskammer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_cooked_porkchop={c1="Trivektionskammer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_cooked_rabbit={c1="Trivektionskammer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_cooked_salmon={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_cookie={c1="",c2="",c3="",hasPattern=true,maxCount=512,tag=""},
 minecraft_jj_crafting_table={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_cyan_glazed_terracotta={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_cyan_shulker_box={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_dark_oak_boat={c1="",c2="",c3="",hasPattern=true,maxCount=64,tag=""},
 minecraft_jj_dark_oak_door={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_dark_oak_fence={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_dark_oak_fence_gate={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_dark_oak_stairs={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_daylight_detector={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_deadbush={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_detector_rail={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_diamond={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_diamond_axe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_diamond_block={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_diamond_boots={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_diamond_chestplate={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_diamond_helmet={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_diamond_hoe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_diamond_horse_armor={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_diamond_leggings={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_diamond_ore={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_diamond_pickaxe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_diamond_shovel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_diamond_sword={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_dirt={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_dirt_jj_1={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_dirt_jj_2={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_dispenser={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_double_plant={c1="Phytogeninsolator",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_double_plant_jj_1={c1="Phytogeninsolator",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_double_plant_jj_2={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_double_plant_jj_3={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_double_plant_jj_4={c1="Phytogeninsolator",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_double_plant_jj_5={c1="Phytogeninsolator",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_dragon_breath={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_dragon_egg={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_dropper={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_dye={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_dye_jj_1={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_dye_jj_10={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_dye_jj_11={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_dye_jj_12={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_dye_jj_13={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_dye_jj_14={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_dye_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=25600,tag=""},
 minecraft_jj_dye_jj_2={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_dye_jj_3={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_dye_jj_4={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_dye_jj_5={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_dye_jj_6={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_dye_jj_7={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_dye_jj_8={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_dye_jj_9={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_egg={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_elytra={c1="",c2="",c3="",hasPattern=true,maxCount=16,tag=""},
 minecraft_jj_emerald={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_emerald_block={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_emerald_ore={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_enchanting_table={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_end_bricks={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_end_crystal={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_end_portal_frame={c1="",c2="",c3="",hasPattern=true,maxCount=60,tag=""},
 minecraft_jj_end_rod={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_end_stone={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_ender_chest={c1="",c2="",c3="",hasPattern=true,maxCount=64,tag=""},
 minecraft_jj_ender_eye={c1="",c2="",c3="",hasPattern=true,maxCount=512,tag=""},
 minecraft_jj_ender_pearl={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_experience_bottle={c1="Fluidtransposer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_farmland={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_feather={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_fence={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_fence_gate={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_fermented_spider_eye={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_filled_map={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_fire_charge={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_firework_charge={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_fireworks={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_fish={c1="Water Trap",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_fish_jj_1={c1="Water Trap",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_fish_jj_2={c1="Water Trap",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_fish_jj_3={c1="Water Trap",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_fishing_rod={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_flint={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_flint_and_steel={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_flower_pot={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_furnace={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_furnace_minecart={c1="",c2="",c3="",hasPattern=true,maxCount=64,tag=""},
 minecraft_jj_ghast_tear={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_glass={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_glass_bottle={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_glass_pane={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_glowstone={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_glowstone_dust={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_gold_block={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_gold_ingot={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_gold_nugget={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_gold_ore={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_golden_apple={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_golden_apple_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_golden_axe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_golden_boots={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_golden_carrot={c1="",c2="",c3="",hasPattern=true,maxCount=64,tag=""},
 minecraft_jj_golden_chestplate={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_golden_helmet={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_golden_hoe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_golden_horse_armor={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_golden_leggings={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_golden_pickaxe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_golden_rail={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_golden_shovel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_golden_sword={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_grass={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_grass_path={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_gravel={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_gray_glazed_terracotta={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_gray_shulker_box={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_green_glazed_terracotta={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_green_shulker_box={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_gunpowder={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_hardened_clay={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_hay_block={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_heavy_weighted_pressure_plate={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_hopper={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_hopper_minecart={c1="",c2="",c3="",hasPattern=true,maxCount=64,tag=""},
 minecraft_jj_ice={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_iron_axe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_iron_bars={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_iron_block={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_iron_boots={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_iron_chestplate={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_iron_door={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_iron_helmet={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_iron_hoe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_iron_horse_armor={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_iron_ingot={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_iron_leggings={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_iron_nugget={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_iron_ore={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_iron_pickaxe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_iron_shovel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_iron_sword={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_iron_trapdoor={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_item_frame={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_jukebox={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_jungle_boat={c1="",c2="",c3="",hasPattern=true,maxCount=64,tag=""},
 minecraft_jj_jungle_door={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_jungle_fence={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_jungle_fence_gate={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_jungle_stairs={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_knowledge_book={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_ladder={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_lapis_block={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_lapis_ore={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_lava_bucket={c1="auto",c2="Fluidtransposer",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_lead={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_leather={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_leather_boots={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_leather_chestplate={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_leather_helmet={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_leather_leggings={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_leaves={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_leaves2={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_leaves2_jj_1={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_leaves_jj_1={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_leaves_jj_2={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_leaves_jj_3={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_lever={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_light_blue_glazed_terracotta={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_light_blue_shulker_box={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_light_weighted_pressure_plate={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_lime_glazed_terracotta={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_lime_shulker_box={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_lit_pumpkin={c1="",c2="",c3="",hasPattern=true,maxCount=512,tag=""},
 minecraft_jj_log={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_log2={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_log2_jj_1={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_log_jj_1={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_log_jj_2={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_log_jj_3={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_magenta_glazed_terracotta={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_magenta_shulker_box={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_magma={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_magma_cream={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_map={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_melon={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_melon_block={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_melon_seeds={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_milk_bucket={c1="auto",c2="Fluidtransposer",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_minecart={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_mob_spawner={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_monster_egg={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_monster_egg_jj_1={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_monster_egg_jj_2={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_monster_egg_jj_3={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_monster_egg_jj_4={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_monster_egg_jj_5={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_mossy_cobblestone={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_mushroom_stew={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_mutton={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_mycelium={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_name_tag={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_nether_brick={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_nether_brick_fence={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_nether_brick_stairs={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_nether_star={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_nether_wart={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_nether_wart_block={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_netherbrick={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_netherrack={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_noteblock={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_oak_stairs={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_observer={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_obsidian={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_orange_glazed_terracotta={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_orange_shulker_box={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_packed_ice={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_painting={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_paper={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_pink_glazed_terracotta={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_pink_shulker_box={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_piston={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_planks={c1="Sägewerk (Harztrichter)",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_planks_jj_1={c1="Sägewerk (Harztrichter)",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_planks_jj_2={c1="Sägewerk (Harztrichter)",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_planks_jj_3={c1="Sägewerk (Harztrichter)",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_planks_jj_4={c1="Sägewerk (Harztrichter)",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_planks_jj_5={c1="Sägewerk (Harztrichter)",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_poisonous_potato={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_porkchop={c1="Mob Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_potato={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_prismarine={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_prismarine_crystals={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_prismarine_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_prismarine_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_prismarine_shard={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_pufferfish={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_pumpkin={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_pumpkin_pie={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_pumpkin_seeds={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_purple_glazed_terracotta={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_purple_shulker_box={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_purpur_block={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_purpur_pillar={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_purpur_slab={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_purpur_stairs={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_quartz={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_quartz_block={c1="auto",c2="",c3="",hasPattern=false,maxCount=1280,tag=""},
 minecraft_jj_quartz_block_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_quartz_block_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_quartz_ore={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_quartz_stairs={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_rabbit={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_rabbit_foot={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_rabbit_hide={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_rabbit_stew={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_rail={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_record_11={c1="",c2="",c3="",hasPattern=true,maxCount=32,tag=""},
 minecraft_jj_record_13={c1="",c2="",c3="",hasPattern=true,maxCount=32,tag=""},
 minecraft_jj_record_blocks={c1="",c2="",c3="",hasPattern=true,maxCount=32,tag=""},
 minecraft_jj_record_cat={c1="",c2="",c3="",hasPattern=true,maxCount=32,tag=""},
 minecraft_jj_record_chirp={c1="",c2="",c3="",hasPattern=true,maxCount=32,tag=""},
 minecraft_jj_record_far={c1="",c2="",c3="",hasPattern=true,maxCount=32,tag=""},
 minecraft_jj_record_mall={c1="",c2="",c3="",hasPattern=true,maxCount=32,tag=""},
 minecraft_jj_record_mellohi={c1="",c2="",c3="",hasPattern=true,maxCount=32,tag=""},
 minecraft_jj_record_stal={c1="",c2="",c3="",hasPattern=true,maxCount=32,tag=""},
 minecraft_jj_record_strad={c1="",c2="",c3="",hasPattern=true,maxCount=32,tag=""},
 minecraft_jj_record_wait={c1="",c2="",c3="",hasPattern=true,maxCount=32,tag=""},
 minecraft_jj_record_ward={c1="",c2="",c3="",hasPattern=true,maxCount=32,tag=""},
 minecraft_jj_red_flower={c1="Phytogeninsolator",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_red_flower_jj_1={c1="Phytogeninsolator",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_red_flower_jj_2={c1="Phytogeninsolator",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_red_flower_jj_3={c1="Phytogeninsolator",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_red_flower_jj_4={c1="Phytogeninsolator",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_red_flower_jj_5={c1="Phytogeninsolator",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_red_flower_jj_6={c1="Phytogeninsolator",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_red_flower_jj_7={c1="Phytogeninsolator",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_red_flower_jj_8={c1="Phytogeninsolator",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_red_glazed_terracotta={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_red_mushroom={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_red_mushroom_block={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_red_nether_brick={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_red_sandstone={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_red_sandstone_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_red_sandstone_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_red_sandstone_stairs={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_red_shulker_box={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_redstone={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_redstone_block={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_redstone_lamp={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_redstone_ore={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_redstone_torch={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_reeds={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_repeater={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_repeating_command_block={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_rotten_flesh={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_saddle={c1="",c2="",c3="",hasPattern=true,maxCount=64,tag=""},
 minecraft_jj_salmon={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_sand={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_sand_jj_1={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_sandstone={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_sandstone_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_sandstone_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_sandstone_stairs={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_sapling={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_sapling_jj_1={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_sapling_jj_2={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_sapling_jj_3={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_sapling_jj_4={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_sapling_jj_5={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_sea_lantern={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_shears={c1="",c2="",c3="",hasPattern=true,maxCount=64,tag=""},
 minecraft_jj_shield={c1="",c2="",c3="",hasPattern=true,maxCount=64,tag=""},
 minecraft_jj_shulker_shell={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_sign={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_silver_glazed_terracotta={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_silver_shulker_box={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_skull={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_skull_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_skull_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_skull_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_skull_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_skull_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_slime={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_slime_ball={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_snow={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_snow_layer={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_snowball={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_soul_sand={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_speckled_melon={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_spectral_arrow={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_spider_eye={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_sponge={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_sponge_jj_1={c1="Fluidtransposer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_spruce_boat={c1="",c2="",c3="",hasPattern=true,maxCount=64,tag=""},
 minecraft_jj_spruce_door={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_spruce_fence={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_spruce_fence_gate={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_spruce_stairs={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_pane={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_pane_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_pane_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_pane_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_pane_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_pane_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_pane_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_pane_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_pane_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_pane_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_pane_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_pane_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_pane_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_pane_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_pane_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_glass_pane_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_hardened_clay={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_hardened_clay_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_hardened_clay_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_hardened_clay_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_hardened_clay_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_hardened_clay_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_hardened_clay_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_hardened_clay_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_hardened_clay_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_hardened_clay_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_hardened_clay_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_hardened_clay_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_hardened_clay_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_hardened_clay_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_hardened_clay_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stained_hardened_clay_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stick={c1="",c2="",c3="",hasPattern=true,maxCount=2560,tag=""},
 minecraft_jj_sticky_piston={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stone={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_stone_axe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_stone_brick_stairs={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stone_button={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stone_hoe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_stone_jj_1={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_stone_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_stone_jj_3={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_stone_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_stone_jj_5={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_stone_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_stone_pickaxe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_stone_pressure_plate={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_stone_shovel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_stone_slab={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stone_slab2={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stone_slab_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stone_slab_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stone_slab_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stone_slab_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stone_slab_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stone_slab_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stone_stairs={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_stone_sword={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_stonebrick={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_stonebrick_jj_1={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_stonebrick_jj_2={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_stonebrick_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_string={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_structure_block={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_structure_void={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_sugar={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_tallgrass_jj_1={c1="Conjuration Catalyst",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_tallgrass_jj_2={c1="Alchemiekatalysator",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_tnt={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_tnt_minecart={c1="",c2="",c3="",hasPattern=true,maxCount=64,tag=""},
 minecraft_jj_torch={c1="",c2="",c3="",hasPattern=true,maxCount=2560,tag=""},
 minecraft_jj_totem_of_undying={c1="Mob Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_trapdoor={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_trapped_chest={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_tripwire_hook={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_vine={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_water_bucket={c1="auto",c2="Fluidtransposer",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_waterlily={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_web={c1="",c2="",c3="",hasPattern=true,maxCount=1280,tag=""},
 minecraft_jj_wheat={c1="mystical agrar autocrafting",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_wheat_seeds={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_white_glazed_terracotta={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_white_shulker_box={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""},
 minecraft_jj_wooden_axe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_wooden_button={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_wooden_door={c1="",c2="",c3="",hasPattern=true,maxCount=192,tag=""},
 minecraft_jj_wooden_hoe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_wooden_pickaxe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_wooden_pressure_plate={c1="",c2="",c3="",hasPattern=true,maxCount=256,tag=""},
 minecraft_jj_wooden_shovel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_wooden_slab={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_wooden_slab_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_wooden_slab_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_wooden_slab_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_wooden_slab_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_wooden_slab_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_wooden_sword={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_wool={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_wool_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_wool_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_wool_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_wool_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_wool_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_wool_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_wool_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_wool_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_wool_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_wool_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_wool_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_wool_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_wool_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_wool_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_wool_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=640,tag=""},
 minecraft_jj_writable_book={c1="",c2="",c3="",hasPattern=true,maxCount=64,tag=""},
 minecraft_jj_written_book={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 minecraft_jj_yellow_flower={c1="Phytogeninsolator",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_yellow_glazed_terracotta={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 minecraft_jj_yellow_shulker_box={c1="",c2="",c3="",hasPattern=true,maxCount=128,tag=""}
 }