return {
 xreliquary_jj_alkahestry_tome_jj_1001={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag=""},
 xreliquary_jj_altar={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_angelheart_vial={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_angelic_feather={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_apothecary_cauldron={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_apothecary_mortar={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_attraction_potion={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_bullet={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 xreliquary_jj_bullet_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_bullet_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_bullet_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_bullet_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_bullet_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_bullet_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_bullet_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_bullet_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_bullet_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_destruction_catalyst={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_emperor_chalice={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_ender_staff={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_fertile_lilypad={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_fertile_potion={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_fortune_coin={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_glacial_staff={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_glowing_bread={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_glowing_water={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_gun_part={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_gun_part_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_gun_part_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_handgun={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_harvest_rod={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_hero_medallion={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_holy_hand_grenade={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_ice_magus_rod={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_infernal_chalice={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_infernal_claws={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_infernal_tear={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_interdiction_torch={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_kraken_shell={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_lantern_of_paranoia={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_magazine={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_magazine_jj_1={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag=""},
 xreliquary_jj_magazine_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_magazine_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_magazine_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_magazine_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_magazine_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_magazine_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_magazine_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_magazine_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_magicbane={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_mercy_cross={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_midas_touchstone={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_mob_charm={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({type: 0 as byte})"},
 xreliquary_jj_mob_charm_belt={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_mob_charm_fragment={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_mob_charm_fragment_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_mob_charm_fragment_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_mob_charm_fragment_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_mob_charm_fragment_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_mob_charm_fragment_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_mob_charm_fragment_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_mob_charm_fragment_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_mob_charm_fragment_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_mob_charm_fragment_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_mob_charm_fragment_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_mob_charm_fragment_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_mob_charm_fragment_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_mob_charm_fragment_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_mob_ingredient={c1="Mob Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 xreliquary_jj_mob_ingredient_jj_1={c1="Mob Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 xreliquary_jj_mob_ingredient_jj_10={c1="Mob Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 xreliquary_jj_mob_ingredient_jj_11={c1="Mob Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 xreliquary_jj_mob_ingredient_jj_12={c1="Mob Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 xreliquary_jj_mob_ingredient_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_mob_ingredient_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_mob_ingredient_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_mob_ingredient_jj_16={c1="Mob Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 xreliquary_jj_mob_ingredient_jj_2={c1="Mob Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 xreliquary_jj_mob_ingredient_jj_3={c1="Mob Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 xreliquary_jj_mob_ingredient_jj_4={c1="Mob Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 xreliquary_jj_mob_ingredient_jj_5={c1="Mob Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 xreliquary_jj_mob_ingredient_jj_6={c1="Mob Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 xreliquary_jj_mob_ingredient_jj_7={c1="Mob Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 xreliquary_jj_mob_ingredient_jj_8={c1="Mob Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 xreliquary_jj_mob_ingredient_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_passive={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_passive_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_passive_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_passive_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_passive_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_passive_jj_13={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_passive_jj_14={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_passive_jj_15={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_passive_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_passive_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_passive_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_passive_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_passive_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_passive_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_passive_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_pedestal_passive_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_phoenix_down={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_potion={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_potion_essence={c1="manuell",c2="Mortar",c3="",hasPattern=false,maxCount=8,tag="({effects: [{duration: 1500, potency: 0, name: minecraft:absorption}]})"},
 xreliquary_jj_pyromancer_staff={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_rending_gale={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_rod_of_lyssa={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_salamander_eye={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_serpent_staff={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_shears_of_winter={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_sojourner_staff={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_tipped_arrow={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag="({effects: [{duration: 187, potency: 0, name: minecraft:absorption}]})"},
 xreliquary_jj_twilight_cloak={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_void_tear={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_witch_hat={c1="Mob Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 xreliquary_jj_witherless_rose={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 xreliquary_jj_wraith_node={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""}
 }