return {
 rftools_jj_advanced_charged_porter={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_analog_block={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftools_jj_blindness_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_block_protector={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_booster={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_builder={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_button_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_camo_shield_block={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftools_jj_charged_porter={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_clock_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_coalgenerator={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_composer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_computer_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_counter_block={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_counter_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_counterplus_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_crafter1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_crafter2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_crafter3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_creative_screen={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftools_jj_destination_analyzer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_developers_delight={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftools_jj_dialing_device={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_digit_block={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftools_jj_dimensional_shard={c1="auto",c2="User / Miner",c3="",hasPattern=false,maxCount=8,tag=""},
 rftools_jj_dimensional_shard_ore={c1="auto",c2="ET - Erzsteinbruch",c3="",hasPattern=false,maxCount=8,tag=""},
 rftools_jj_dimensional_shard_ore_jj_1={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftools_jj_dimensional_shard_ore_jj_2={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftools_jj_dump_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_elevator={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_elevator_button_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_ender_monitor={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_endergenic={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_energy_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_energyplus_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_environmental_controller={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_featherfalling_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_featherfallingplus_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_filter_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_flight_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_fluid_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_fluidplus_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_generic_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_glowing_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_haste_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_hasteplus_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_infused_diamond={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_infused_enderpearl={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_invchecker_block={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_inventory_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_inventoryplus_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_invisible_shield_block={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftools_jj_item_filter={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_level_emitter={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_liquid_monitor={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_locator={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_logic_block={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftools_jj_luck_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_machine_base={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_machine_frame={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_machine_infuser={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_machineinformation_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_matter_beamer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_matter_booster={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_matter_receiver={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_matter_transmitter={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_modifier_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_modular_storage={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_network_monitor={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftools_jj_nightvision_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_noteleport_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_notick_camo_shield_block={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftools_jj_notick_invisible_shield_block={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftools_jj_notick_solid_shield_block={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftools_jj_oredict_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_orphaning_card={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_peace_essence={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_peaceful_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_pearl_injector={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_poison_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_powercell={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_powercell_advanced={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_powercell_card={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_powercell_creative={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftools_jj_powercell_simple={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_projector={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_redstone_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_redstone_receiver_block={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_redstone_transmitter_block={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_regeneration_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_regenerationplus_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_relay={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_remote_scanner={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_remote_storage={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_rf_monitor={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_rftools_manual={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_rftools_shape_manual={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_saturation_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_saturationplus_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_scanner={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_screen={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_screen_controller={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_security_card={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_security_manager={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_sensor_block={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_sequencer_block={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_shape_card={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_shape_card_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_shape_card_jj_10={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftools_jj_shape_card_jj_2={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftools_jj_shape_card_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_shape_card_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_shape_card_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_shape_card_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_shape_card_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_shape_card_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_shape_card_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_shard_wand={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftools_jj_shield_block1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_shield_block2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_shield_block3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_shield_block4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_shield_template_block={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_shield_template_block_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_shield_template_block_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_shield_template_block_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_simple_dialer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_slowness_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_smartwrench={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_solid_shield_block={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftools_jj_space_chamber={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_space_chamber_card={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_space_chamber_controller={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_spawner={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_speed_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_speedplus_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_storage_control_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_storage_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_storage_module_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_storage_module_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_storage_module_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_storage_module_tablet={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_storage_scanner={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_storage_terminal={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_support_block={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftools_jj_syringe={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftools_jj_teleport_probe={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftools_jj_text_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_timer_block={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_waterbreathing_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_weakness_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftools_jj_wire_block={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolscontrol_jj_advanced_network_card={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolscontrol_jj_card_base={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolscontrol_jj_console_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolscontrol_jj_cpu_core_1000={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolscontrol_jj_cpu_core_2000={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolscontrol_jj_cpu_core_500={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolscontrol_jj_crafting_card={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolscontrol_jj_craftingstation={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolscontrol_jj_graphics_card={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolscontrol_jj_interaction_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolscontrol_jj_network_card={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolscontrol_jj_network_identifier={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolscontrol_jj_node={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolscontrol_jj_processor={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolscontrol_jj_program_card={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolscontrol_jj_programmer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolscontrol_jj_ram_chip={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolscontrol_jj_rftoolscontrol_manual={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolscontrol_jj_tank={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolscontrol_jj_token={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolscontrol_jj_variable_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolscontrol_jj_vectorart_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolscontrol_jj_workbench={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_activity_probe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_biome_absorber={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_dimension_builder={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_dimension_editor={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_dimension_enscriber={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_dimension_module={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_dimension_monitor={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_dimensional_blank_block={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_dimensional_block={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_dimensional_cross2_block={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_dimensional_cross_block={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_dimensional_pattern1_block={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_dimensional_pattern2_block={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_dimensional_small_blocks={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_base={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_control_circuit={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_control_circuit_jj_1={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_control_circuit_jj_2={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_control_circuit_jj_3={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_control_circuit_jj_4={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_control_circuit_jj_5={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_control_circuit_jj_6={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_energy_module={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_energy_module_jj_1={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_energy_module_jj_2={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_memory_unit={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_memory_unit_jj_1={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_memory_unit_jj_2={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_parcel={c1="Chest Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_template={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_type_controller={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_type_controller_jj_1={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_type_controller_jj_10={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_type_controller_jj_11={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_type_controller_jj_12={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_type_controller_jj_13={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_type_controller_jj_14={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_type_controller_jj_2={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_type_controller_jj_3={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_type_controller_jj_4={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_type_controller_jj_5={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_type_controller_jj_6={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_type_controller_jj_7={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_type_controller_jj_8={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_type_controller_jj_9={c1="manuell",c2="Dimlet Workbench",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_dimlet_workbench={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_efficiency_essence={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_empty_dimension_tab={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_energy_extractor={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_fake_gravel={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_fake_sand={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_fake_water={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_feature_absorber={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_known_dimlet_jj_1={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({dkey: minecraft:water@0})"},
 rftoolsdim_jj_known_dimlet_jj_10={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({dkey: None})"},
 rftoolsdim_jj_known_dimlet_jj_12={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({dkey: Default})"},
 rftoolsdim_jj_known_dimlet_jj_13={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({dkey: Default})"},
 rftoolsdim_jj_known_dimlet_jj_2={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({dkey: minecraft:stone@0})"},
 rftoolsdim_jj_known_dimlet_jj_3={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({dkey: Default})"},
 rftoolsdim_jj_known_dimlet_jj_4={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({dkey: normal.day})"},
 rftoolsdim_jj_known_dimlet_jj_5={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({dkey: None})"},
 rftoolsdim_jj_known_dimlet_jj_6={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({dkey: Void})"},
 rftoolsdim_jj_known_dimlet_jj_7={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({dkey: None})"},
 rftoolsdim_jj_known_dimlet_jj_8={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({dkey: Normal})"},
 rftoolsdim_jj_known_dimlet_jj_9={c1="manuell",c2="Matrix",c3="",hasPattern=false,maxCount=8,tag="({dkey: 3})"},
 rftoolsdim_jj_liquid_absorber={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_material_absorber={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_mediocre_efficiency_essence={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_phased_field_generator={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_realized_dimension_tab={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_rftoolsdim_manual={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_structure_essence={c1="Chest Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_structure_essence_jj_1={c1="Chest Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_structure_essence_jj_10={c1="Chest Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_structure_essence_jj_11={c1="Chest Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_structure_essence_jj_2={c1="Chest Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_structure_essence_jj_3={c1="Chest Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_structure_essence_jj_4={c1="Chest Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_structure_essence_jj_5={c1="Chest Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_structure_essence_jj_6={c1="Chest Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_structure_essence_jj_7={c1="Chest Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_structure_essence_jj_8={c1="Chest Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_structure_essence_jj_9={c1="Chest Drop",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 rftoolsdim_jj_terrain_absorber={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 rftoolsdim_jj_time_absorber={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""}
 }