return {
 techreborn_jj_adjustable_su={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_advancedchainsaw={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_advanceddrill={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_alarm={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_alloy_smelter={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_assembly_machine={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_auto_crafting_table={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_bronzeaxe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_bronzeboots={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_bronzechestplate={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_bronzehelmet={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_bronzehoe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_bronzeleggings={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_bronzepickaxe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_bronzespade={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_bronzesword={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_cable={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_cable_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_cable_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_cable_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_cable_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_cable_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_cable_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_cable_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_charge_o_mat={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_chemical_reactor={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_chunk_loader={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_cloakingdevice={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_compressor={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_computer_cube={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_creative_solar_panel={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_debug={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_diamondchainsaw={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_diamonddrill={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_diamondjackhammer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_diesel_generator={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_digital_chest={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_distillation_tower={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_dragon_egg_syphon={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_dust={c1="Industrial Centrifuge",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_1={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_10={c1="Pulverisierer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_11={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_12={c1="Ore Dict",c2="ic2_jj_dust_1",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_13={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_14={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_15={c1="Industrial Blast Furnace",c2="Industrial Centrifuge",c3="Industrial Compressor",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_16={c1="Ore Dict",c2="mekanism_jj_otherdust",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_17={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_18={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_19={c1="Pulverisierer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_2={c1="Industrial Centrifuge",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_20={c1="Grinder",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_21={c1="Industrial Grinder",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_22={c1="Industrial Centrifuge",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_23={c1="Industrial Grinder",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_24={c1="Ore Dict",c2="mekanism_jj_dust_jj_1",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_25={c1="Industrial Centrifuge",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_26={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_27={c1="Ore Dict",c2="mekanism_jj_dust",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_28={c1="Industrial Centrifuge",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_29={c1="Ore Dict ",c2="mekanism_jj_dust_jj_6",c3="REMOVE RSC RECIPE",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_3={c1="Industrial Centrifuge",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_30={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_31={c1="Pulverisierer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_32={c1="Grinder",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_33={c1="Industrial Grinder",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_34={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_35={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_36={c1="Industrial Grinder",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_37={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_38={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_39={c1="auto",c2="Industrial Grinder",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_4={c1="Grinder",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_40={c1="Industrial Centrifuge",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_41={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_43={c1="Industrial Centrifuge",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_44={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_45={c1="Pulverisierer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_46={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_47={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_48={c1="Industrial Grinder",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_49={c1="Industrial Centrifuge",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_5={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_50={c1="Industrial Grinder",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_51={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_52={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_53={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_54={c1="Pulverisierer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_55={c1="Pulverisierer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_56={c1="Industrial Centrifuge",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_58={c1="auto",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_59={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_6={c1="Pulverisierer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_61={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_62={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_63={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_7={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_8={c1="Industrial Centrifuge",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dust_jj_9={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_dynamiccell={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_electric_furnace={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_electrictreetap={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_energycrystal={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_extractor={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_frequencytransmitter={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_fusion_coil={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_fusion_control_computer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_gas_turbine={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_gem={c1="auto",c2="Industrial Grinder",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_gem_jj_1={c1="auto",c2="Industrial Grinder",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_gem_jj_2={c1="auto",c2="Industrial Grinder",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_gem_jj_3={c1="Implosion Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_gem_jj_4={c1="Implosion Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_grinder={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_high_voltage_su={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_hv_transformer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_implosion_compressor={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_industrial_blast_furnace={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_industrial_centrifuge={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_industrial_electrolyzer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_industrial_grinder={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_industrial_sawmill={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_ingot={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ingot_jj_1={c1="auto",c2="Cloche",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ingot_jj_10={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ingot_jj_11={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ingot_jj_12={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ingot_jj_13={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ingot_jj_14={c1="auto",c2="Cloche",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ingot_jj_15={c1="auto",c2="Schmelzsplitting",c3="Cloche",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ingot_jj_16={c1="Industrial Blast Furnace",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ingot_jj_17={c1="Vacuum Freezer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ingot_jj_18={c1="auto",c2="Cloche",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ingot_jj_19={c1="Induktionsschmelzerei",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ingot_jj_2={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ingot_jj_20={c1="Mekanism Schmelzer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ingot_jj_21={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_ingot_jj_22={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_ingot_jj_3={c1="auto",c2="Schmelzsplitting",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ingot_jj_4={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ingot_jj_5={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ingot_jj_6={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ingot_jj_7={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ingot_jj_8={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ingot_jj_9={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_interdimensional_su={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_iron_alloy_furnace={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_iron_furnace={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_ironchainsaw={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_irondrill={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_ironjackhammer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_lamp_incandescent={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_lamp_led={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_lapotroncrystal={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_lapotronic_su={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_lapotronicorb={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_lapotronpack={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_lightning_rod={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_lithiumbatpack={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_lithiumbattery={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_low_voltage_su={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_lsu_storage={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_lv_transformer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_machine_casing={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_machine_casing_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_machine_casing_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_machine_frame={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_machine_frame_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_machine_frame_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_magic_energy_absorber={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_magic_energy_converter={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_matter_fabricator={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_medium_voltage_su={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_missingrecipe={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_mv_transformer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_nanosaber={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag="({isActive: 0 as byte})"},
 techreborn_jj_nuggets={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_nuggets_jj_1={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_nuggets_jj_10={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_nuggets_jj_11={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_nuggets_jj_12={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_nuggets_jj_13={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_nuggets_jj_14={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_nuggets_jj_15={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_nuggets_jj_16={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_nuggets_jj_17={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_nuggets_jj_18={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_nuggets_jj_19={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_nuggets_jj_2={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_nuggets_jj_23={c1="Ore Dict",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_nuggets_jj_24={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_nuggets_jj_3={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_nuggets_jj_4={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_nuggets_jj_5={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_nuggets_jj_6={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_nuggets_jj_7={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_nuggets_jj_8={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_nuggets_jj_9={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_nuke={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_omnitool={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ore={c1="Abbau",c2="auto",c3="Laser",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ore2={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ore2_jj_1={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ore_jj_1={c1="Fusion Control Computer",c2="Abbau",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ore_jj_10={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ore_jj_11={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ore_jj_12={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ore_jj_13={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ore_jj_2={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ore_jj_3={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ore_jj_4={c1="Abbau",c2="auto",c3="Laser",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ore_jj_5={c1="Abbau",c2="auto",c3="Laser",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ore_jj_6={c1="auto",c2="ET - Erzsteinbruch",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ore_jj_7={c1="Abbau",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ore_jj_8={c1="Abbau",c2="auto",c3="ET - Erzsteinbruch",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_ore_jj_9={c1="Abbau",c2="auto",c3="Laser",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_part={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_part_jj_1={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_part_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_part_jj_11={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_part_jj_12={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_part_jj_13={c1="Rolling Machine",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_part_jj_14={c1="Rolling Machine",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_part_jj_15={c1="Rolling Machine",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_part_jj_17={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_part_jj_18={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_part_jj_19={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_part_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_part_jj_20={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_part_jj_21={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_part_jj_22={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_part_jj_23={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_part_jj_24={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_part_jj_25={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_part_jj_26={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_part_jj_27={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_part_jj_28={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_part_jj_29={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_part_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_part_jj_30={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_part_jj_31={c1="Industrial Centrifuge",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_part_jj_32={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_part_jj_33={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_part_jj_34={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_part_jj_35={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_part_jj_36={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_part_jj_37={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_part_jj_38={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_part_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_part_jj_5={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_part_jj_6={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_part_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_part_jj_8={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_part_jj_9={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_peridotaxe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_peridotboots={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_peridotchestplate={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_peridothelmet={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_peridothoe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_peridotleggings={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_peridotpickaxe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_peridotspade={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_peridotsword={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_plasma_generator={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_plates={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_1={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_10={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_11={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_12={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_13={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_14={c1="Kompaktor - Pressen",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_15={c1="Kompaktor - Pressen",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_16={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_17={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_18={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_19={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_2={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_20={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_21={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_22={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_23={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_24={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_25={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_26={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_27={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_28={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_29={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_3={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_30={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_31={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_32={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_33={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_34={c1="Pressurizer",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_35={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_36={c1="Rolling Machine",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_37={c1="Implosion Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_4={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_5={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_6={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_8={c1="Compressor",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_plates_jj_9={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_player_detector={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_player_detector_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_player_detector_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_quantum_chest={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_quantum_tank={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_rebattery={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_recycler={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_refined_iron_fence={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_reinforced_glass={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_rockcutter={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_rolling_machine={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_rubber_leaves={c1="manuell",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_rubber_log={c1="Sapling Infuser",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_rubber_planks={c1="Präzisionssägewerk",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_rubber_sapling={c1="Sapling Infuser",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_rubyaxe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_rubyboots={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_rubychestplate={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_rubyhelmet={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_rubyhoe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_rubyleggings={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_rubypickaxe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_rubyspade={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_rubysword={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_sapphireaxe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_sapphireboots={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_sapphirechestplate={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_sapphirehelmet={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_sapphirehoe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_sapphireleggings={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_sapphirepickaxe={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_sapphirespade={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_sapphiresword={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_scrapbox={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_scrapboxinator={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_semi_fluid_generator={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_smalldust={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_1={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_10={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_11={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_12={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_13={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_14={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_15={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_16={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_17={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_18={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_19={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_2={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_20={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_21={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_22={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_23={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_24={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_25={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_26={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_27={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_28={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_29={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_3={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_30={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_31={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_32={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_33={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_34={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_35={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_36={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_37={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_38={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_39={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_4={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_40={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_41={c1="Industrial Grinder",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_43={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_44={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_45={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_46={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_47={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_48={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_49={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_5={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_50={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_51={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_52={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_53={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_54={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_55={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_56={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_58={c1="Industrial Grinder",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_59={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_6={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_61={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_62={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_63={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_64={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_65={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_7={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_8={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_smalldust_jj_9={c1="Pending",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_solar_panel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_solar_panel_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_solar_panel_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_solar_panel_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_solar_panel_jj_4={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_solid_fuel_generator={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_steeljackhammer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_storage={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_storage2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_storage2_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_storage2_jj_10={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_storage2_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_storage2_jj_3={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_storage2_jj_4={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_storage2_jj_5={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_storage2_jj_6={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_storage2_jj_7={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_storage2_jj_8={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_storage2_jj_9={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_storage_jj_1={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_storage_jj_10={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_storage_jj_11={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_storage_jj_12={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_storage_jj_13={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_storage_jj_14={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_storage_jj_2={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_storage_jj_3={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_storage_jj_4={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_storage_jj_5={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_storage_jj_6={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_storage_jj_7={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_storage_jj_8={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_storage_jj_9={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techmanuel={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_berylium={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_calcium={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_calciumcarbonate={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_carbon={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_carbonfiber={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_chlorite={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_compressedair={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_deuterium={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_diesel={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_electrolyzedwater={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_glyceryl={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_helium={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_helium3={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_heliumplasma={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_hydrogen={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_lithium={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_mercury={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_methane={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_nitrocarbon={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_nitrocoalfuel={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_nitrodiesel={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_nitrofuel={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_nitrogen={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_nitrogendioxide={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_oil={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_potassium={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_silicon={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_sodium={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_sodiumpersulfate={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_sodiumsulfide={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_sulfur={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_sulfuricacid={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_tritium={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_techreborn_techreborn_vv_wolframium={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_thermal_generator={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_treetap={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_upgrades={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_upgrades_jj_1={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_upgrades_jj_2={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_upgrades_jj_3={c1="bb",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_uumatter={c1="x",c2="",c3="",hasPattern=false,maxCount=8,tag=""},
 techreborn_jj_vacuum_freezer={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_water_mill={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_wind_mill={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""},
 techreborn_jj_wrench={c1="",c2="",c3="",hasPattern=true,maxCount=8,tag=""}
 }