{{name="minecraft:acacia_boat"},
{name="minecraft:acacia_door"},
{name="minecraft:acacia_fence"},
{name="minecraft:acacia_fence_gate"},
{name="minecraft:acacia_stairs"},
{name="minecraft:activator_rail"},
{name="minecraft:air"},
{name="minecraft:anvil"},
{name="minecraft:apple"},
{name="minecraft:armor_stand"},
{name="minecraft:arrow"},
{name="minecraft:baked_potato"},
{name="minecraft:banner"},
{name="minecraft:banner", damage=1.0},
{name="minecraft:banner", damage=2.0},
{name="minecraft:banner", damage=3.0},
{name="minecraft:banner", damage=4.0},
{name="minecraft:banner", damage=5.0},
{name="minecraft:banner", damage=6.0},
{name="minecraft:banner", damage=7.0},
{name="minecraft:banner", damage=8.0},
{name="minecraft:banner", damage=9.0},
{name="minecraft:banner", damage=10.0},
{name="minecraft:banner", damage=11.0},
{name="minecraft:banner", damage=12.0},
{name="minecraft:banner", damage=13.0},
{name="minecraft:banner", damage=14.0},
{name="minecraft:banner", damage=15.0},
{name="minecraft:barrier"},
{name="minecraft:beacon"},
{name="minecraft:bed"},
{name="minecraft:bed", damage=1.0},
{name="minecraft:bed", damage=2.0},
{name="minecraft:bed", damage=3.0},
{name="minecraft:bed", damage=4.0},
{name="minecraft:bed", damage=5.0},
{name="minecraft:bed", damage=6.0},
{name="minecraft:bed", damage=7.0},
{name="minecraft:bed", damage=8.0},
{name="minecraft:bed", damage=9.0},
{name="minecraft:bed", damage=10.0},
{name="minecraft:bed", damage=11.0},
{name="minecraft:bed", damage=12.0},
{name="minecraft:bed", damage=13.0},
{name="minecraft:bed", damage=14.0},
{name="minecraft:bed", damage=15.0},
{name="minecraft:bedrock"},
{name="minecraft:beef"},
{name="minecraft:beetroot"},
{name="minecraft:beetroot_seeds"},
{name="minecraft:beetroot_soup"},
{name="minecraft:birch_boat"},
{name="minecraft:birch_door"},
{name="minecraft:birch_fence"},
{name="minecraft:birch_fence_fate"},
{name="minecraft:birch_fence_gate"},
{name="minecraft:birch_stairs"},
{name="minecraft:black_glazed_terracotta"},
{name="minecraft:black_shulker_box"},
{name="minecraft:blaze_powder"},
{name="minecraft:blaze_rod"},
{name="minecraft:blue_glazed_terracotta"},
{name="minecraft:blue_shulker_box"},
{name="minecraft:boat"},
{name="minecraft:bone"},
{name="minecraft:bone_block"},
{name="minecraft:book"},
{name="minecraft:bookshelf"},
{name="minecraft:bow"},
{name="minecraft:bowl"},
{name="minecraft:bread"},
{name="minecraft:brewing_stand"},
{name="minecraft:brick"},
{name="minecraft:brick_block"},
{name="minecraft:brick_stairs"},
{name="minecraft:brown_glazed_terracotta"},
{name="minecraft:brown_mushroom"},
{name="minecraft:brown_mushroom_block"},
{name="minecraft:brown_shulker_box"},
{name="minecraft:bucket"},
{name="minecraft:cactus"},
{name="minecraft:cake"},
{name="minecraft:carpet"},
{name="minecraft:carpet", damage=1.0},
{name="minecraft:carpet", damage=2.0},
{name="minecraft:carpet", damage=3.0},
{name="minecraft:carpet", damage=4.0},
{name="minecraft:carpet", damage=5.0},
{name="minecraft:carpet", damage=6.0},
{name="minecraft:carpet", damage=7.0},
{name="minecraft:carpet", damage=8.0},
{name="minecraft:carpet", damage=9.0},
{name="minecraft:carpet", damage=10.0},
{name="minecraft:carpet", damage=11.0},
{name="minecraft:carpet", damage=12.0},
{name="minecraft:carpet", damage=13.0},
{name="minecraft:carpet", damage=14.0},
{name="minecraft:carpet", damage=15.0},
{name="minecraft:carrot"},
{name="minecraft:carrot_on_a_stick"},
{name="minecraft:cauldron"},
{name="minecraft:chain_command_block"},
{name="minecraft:chainmail_boots"},
{name="minecraft:chainmail_chestplate"},
{name="minecraft:chainmail_helmet"},
{name="minecraft:chainmail_leggings"},
{name="minecraft:chest"},
{name="minecraft:chest_minecart"},
{name="minecraft:chicken"},
{name="minecraft:chorus_flower"},
{name="minecraft:chorus_fruit"},
{name="minecraft:chorus_fruit_popped"},
{name="minecraft:chorus_plant"},
{name="minecraft:clay"},
{name="minecraft:clay_ball"},
{name="minecraft:clock"},
{name="minecraft:clownfish"},
{name="minecraft:coal"},
{name="minecraft:coal", damage=1.0},
{name="minecraft:coal_block"},
{name="minecraft:coal_ore"},
{name="minecraft:cobblestone"},
{name="minecraft:cobblestone_wall"},
{name="minecraft:cobblestone_wall", damage=1.0},
{name="minecraft:cod"},
{name="minecraft:command_block"},
{name="minecraft:command_block_minecart"},
{name="minecraft:comparator"},
{name="minecraft:compass"},
{name="minecraft:concrete"},
{name="minecraft:concrete", damage=1.0},
{name="minecraft:concrete", damage=2.0},
{name="minecraft:concrete", damage=3.0},
{name="minecraft:concrete", damage=4.0},
{name="minecraft:concrete", damage=5.0},
{name="minecraft:concrete", damage=6.0},
{name="minecraft:concrete", damage=7.0},
{name="minecraft:concrete", damage=8.0},
{name="minecraft:concrete", damage=9.0},
{name="minecraft:concrete", damage=10.0},
{name="minecraft:concrete", damage=11.0},
{name="minecraft:concrete", damage=12.0},
{name="minecraft:concrete", damage=13.0},
{name="minecraft:concrete", damage=14.0},
{name="minecraft:concrete", damage=15.0},
{name="minecraft:concrete_powder"},
{name="minecraft:concrete_powder", damage=1.0},
{name="minecraft:concrete_powder", damage=2.0},
{name="minecraft:concrete_powder", damage=3.0},
{name="minecraft:concrete_powder", damage=4.0},
{name="minecraft:concrete_powder", damage=5.0},
{name="minecraft:concrete_powder", damage=6.0},
{name="minecraft:concrete_powder", damage=7.0},
{name="minecraft:concrete_powder", damage=8.0},
{name="minecraft:concrete_powder", damage=9.0},
{name="minecraft:concrete_powder", damage=10.0},
{name="minecraft:concrete_powder", damage=11.0},
{name="minecraft:concrete_powder", damage=12.0},
{name="minecraft:concrete_powder", damage=13.0},
{name="minecraft:concrete_powder", damage=14.0},
{name="minecraft:concrete_powder", damage=15.0},
{name="minecraft:cooked_beef"},
{name="minecraft:cooked_chicken"},
{name="minecraft:cooked_cod"},
{name="minecraft:cooked_fish"},
{name="minecraft:cooked_fish", damage=1.0},
{name="minecraft:cooked_mutton"},
{name="minecraft:cooked_porkchop"},
{name="minecraft:cooked_rabbit"},
{name="minecraft:cooked_salmon"},
{name="minecraft:cookie"},
{name="minecraft:crafting_table"},
{name="minecraft:cyan_glazed_terracotta"},
{name="minecraft:cyan_shulker_box"},
{name="minecraft:dark_oak_boat"},
{name="minecraft:dark_oak_door"},
{name="minecraft:dark_oak_fence"},
{name="minecraft:dark_oak_fence_gate"},
{name="minecraft:dark_oak_stairs"},
{name="minecraft:daylight_detector"},
{name="minecraft:deadbush"},
{name="minecraft:detector_rail"},
{name="minecraft:diamond"},
{name="minecraft:diamond_axe"},
{name="minecraft:diamond_block"},
{name="minecraft:diamond_boots"},
{name="minecraft:diamond_chestplate"},
{name="minecraft:diamond_helmet"},
{name="minecraft:diamond_hoe"},
{name="minecraft:diamond_horse_armor"},
{name="minecraft:diamond_leggings"},
{name="minecraft:diamond_ore"},
{name="minecraft:diamond_pickaxe"},
{name="minecraft:diamond_shovel"},
{name="minecraft:diamond_sword"},
{name="minecraft:dirt"},
{name="minecraft:dirt"},
{name="minecraft:dirt"},
{name="minecraft:dispenser"},
{name="minecraft:double_plant"},
{name="minecraft:double_plant"},
{name="minecraft:double_plant"},
{name="minecraft:double_plant"},
{name="minecraft:double_plant"},
{name="minecraft:double_plant"},
{name="minecraft:dragon_breath"},
{name="minecraft:dragon_egg"},
{name="minecraft:dropper"},
{name="minecraft:dye"},
{name="minecraft:dye", damage=1.0},
{name="minecraft:dye", damage=2.0},
{name="minecraft:dye", damage=3.0},
{name="minecraft:dye", damage=4.0},
{name="minecraft:dye", damage=5.0},
{name="minecraft:dye", damage=6.0},
{name="minecraft:dye", damage=7.0},
{name="minecraft:dye", damage=8.0},
{name="minecraft:dye", damage=9.0},
{name="minecraft:dye", damage=10.0},
{name="minecraft:dye", damage=11.0},
{name="minecraft:dye", damage=12.0},
{name="minecraft:dye", damage=13.0},
{name="minecraft:dye", damage=14.0},
{name="minecraft:dye", damage=15.0},
{name="minecraft:egg"},
{name="minecraft:elytra"},
{name="minecraft:emerald"},
{name="minecraft:emerald_block"},
{name="minecraft:emerald_ore"},
{name="minecraft:enchanting_table"},
{name="minecraft:end_bricks"},
{name="minecraft:end_crystal"},
{name="minecraft:end_portal_frame"},
{name="minecraft:end_rod"},
{name="minecraft:end_stone"},
{name="minecraft:ender_chest"},
{name="minecraft:ender_eye"},
{name="minecraft:ender_pearl"},
{name="minecraft:experience_bottle"},
{name="minecraft:farmland"},
{name="minecraft:feather"},
{name="minecraft:fence"},
{name="minecraft:fence_gate"},
{name="minecraft:fermented_spider_eye"},
{name="minecraft:filled_map"},
{name="minecraft:fire_charge"},
{name="minecraft:firework_charge"},
{name="minecraft:fireworks"},
{name="minecraft:fish"},
{name="minecraft:fish", damage=1.0},
{name="minecraft:fish", damage=2.0},
{name="minecraft:fish", damage=3.0},
{name="minecraft:fishing_rod"},
{name="minecraft:flint"},
{name="minecraft:flint_and_steel"},
{name="minecraft:flower_pot"},
{name="minecraft:furnace"},
{name="minecraft:furnace_minecart"},
{name="minecraft:ghast_tear"},
{name="minecraft:glass"},
{name="minecraft:glass_bottle"},
{name="minecraft:glass_pane"},
{name="minecraft:glowstone"},
{name="minecraft:glowstone_dust"},
{name="minecraft:gold_block"},
{name="minecraft:gold_ingot"},
{name="minecraft:gold_nugget"},
{name="minecraft:gold_ore"},
{name="minecraft:golden_apple"},
{name="minecraft:golden_apple", damage=1.0},
{name="minecraft:golden_axe"},
{name="minecraft:golden_boots"},
{name="minecraft:golden_carrot"},
{name="minecraft:golden_chestplate"},
{name="minecraft:golden_helmet"},
{name="minecraft:golden_hoe"},
{name="minecraft:golden_horse_armor"},
{name="minecraft:golden_leggings"},
{name="minecraft:golden_pickaxe"},
{name="minecraft:golden_rail"},
{name="minecraft:golden_shovel"},
{name="minecraft:golden_sword"},
{name="minecraft:grass"},
{name="minecraft:grass_path"},
{name="minecraft:gravel"},
{name="minecraft:gray_glazed_terracotta"},
{name="minecraft:gray_shulker_box"},
{name="minecraft:green_glazed_terracotta"},
{name="minecraft:green_shulker_box"},
{name="minecraft:gunpowder"},
{name="minecraft:hardened_clay"},
{name="minecraft:hay_block"},
{name="minecraft:heavy_weighted_pressure_plate"},
{name="minecraft:hopper"},
{name="minecraft:hopper_minecart"},
{name="minecraft:ice"},
{name="minecraft:iron_axe"},
{name="minecraft:iron_bars"},
{name="minecraft:iron_block"},
{name="minecraft:iron_boots"},
{name="minecraft:iron_chestplate"},
{name="minecraft:iron_door"},
{name="minecraft:iron_helmet"},
{name="minecraft:iron_hoe"},
{name="minecraft:iron_horse_armor"},
{name="minecraft:iron_ingot"},
{name="minecraft:iron_leggings"},
{name="minecraft:iron_nugget"},
{name="minecraft:iron_ore"},
{name="minecraft:iron_pickaxe"},
{name="minecraft:iron_shovel"},
{name="minecraft:iron_sword"},
{name="minecraft:iron_trapdoor"},
{name="minecraft:item_frame"},
{name="minecraft:jukebox"},
{name="minecraft:jungle_boat"},
{name="minecraft:jungle_door"},
{name="minecraft:jungle_fence"},
{name="minecraft:jungle_fence_gate"},
{name="minecraft:jungle_stairs"},
{name="minecraft:knowledge_book"},
{name="minecraft:ladder"},
{name="minecraft:lapis_block"},
{name="minecraft:lapis_ore"},
{name="minecraft:lava_bucket"},
{name="minecraft:lead"},
{name="minecraft:leather"},
{name="minecraft:leather_boots"},
{name="minecraft:leather_chestplate"},
{name="minecraft:leather_helmet"},
{name="minecraft:leather_leggings"},
{name="minecraft:leaves"},
{name="minecraft:leaves", damage=1.0},
{name="minecraft:leaves", damage=2.0},
{name="minecraft:leaves", damage=3.0},
{name="minecraft:leaves2"},
{name="minecraft:leaves2", damage=1.0},
{name="minecraft:lever"},
{name="minecraft:light_blue_glazed_terracotta"},
{name="minecraft:light_blue_shulker_box"},
{name="minecraft:light_weighted_pressure_plate"},
{name="minecraft:lime_glazed_terracotta"},
{name="minecraft:lime_shulker_box"},
{name="minecraft:lit_pumpkin"},
{name="minecraft:log"},
{name="minecraft:log", damage=1.0},
{name="minecraft:log", damage=2.0},
{name="minecraft:log", damage=3.0},
{name="minecraft:log2"},
{name="minecraft:log2", damage=1.0},
{name="minecraft:magenta_glazed_terracotta"},
{name="minecraft:magenta_shulker_box"},
{name="minecraft:magma"},
{name="minecraft:magma_cream"},
{name="minecraft:map"},
{name="minecraft:melon"},
{name="minecraft:melon_block"},
{name="minecraft:melon_seeds"},
{name="minecraft:milk_bucket"},
{name="minecraft:minecart"},
{name="minecraft:mob_spawner"},
{name="minecraft:monster_egg"},
{name="minecraft:monster_egg", damage=1.0},
{name="minecraft:monster_egg", damage=2.0},
{name="minecraft:monster_egg", damage=3.0},
{name="minecraft:monster_egg", damage=4.0},
{name="minecraft:monster_egg", damage=5.0},
{name="minecraft:mossy_cobblestone"},
{name="minecraft:mushroom_stew"},
{name="minecraft:mutton"},
{name="minecraft:mycelium"},
{name="minecraft:name_tag"},
{name="minecraft:nether_brick"},
{name="minecraft:nether_brick_fence"},
{name="minecraft:nether_brick_stairs"},
{name="minecraft:nether_star"},
{name="minecraft:nether_wart"},
{name="minecraft:nether_wart_block"},
{name="minecraft:netherbrick"},
{name="minecraft:netherrack"},
{name="minecraft:noteblock"},
{name="minecraft:oak_stairs"},
{name="minecraft:observer"},
{name="minecraft:obsidian"},
{name="minecraft:orange_glazed_terracotta"},
{name="minecraft:orange_shulker_box"},
{name="minecraft:packed_ice"},
{name="minecraft:painting"},
{name="minecraft:paper"},
{name="minecraft:pink_glazed_terracotta"},
{name="minecraft:pink_shulker_box"},
{name="minecraft:piston"},
{name="minecraft:planks"},
{name="minecraft:planks", damage=1.0},
{name="minecraft:planks", damage=2.0},
{name="minecraft:planks", damage=3.0},
{name="minecraft:planks", damage=4.0},
{name="minecraft:planks", damage=5.0},
{name="minecraft:poisonous_potato"},
{name="minecraft:porkchop"},
{name="minecraft:potato"},
{name="minecraft:prismarine"},
{name="minecraft:prismarine", damage=1.0},
{name="minecraft:prismarine", damage=2.0},
{name="minecraft:prismarine_crystals"},
{name="minecraft:prismarine_shard"},
{name="minecraft:pufferfish"},
{name="minecraft:pumpkin"},
{name="minecraft:pumpkin_pie"},
{name="minecraft:pumpkin_seeds"},
{name="minecraft:purple_glazed_terracotta"},
{name="minecraft:purple_shulker_box"},
{name="minecraft:purpur_block"},
{name="minecraft:purpur_pillar"},
{name="minecraft:purpur_slab"},
{name="minecraft:purpur_stairs"},
{name="minecraft:quartz"},
{name="minecraft:quartz_block"},
{name="minecraft:quartz_block", damage=1.0},
{name="minecraft:quartz_block", damage=2.0},
{name="minecraft:quartz_ore"},
{name="minecraft:quartz_stairs"},
{name="minecraft:rabbit"},
{name="minecraft:rabbit_foot"},
{name="minecraft:rabbit_hide"},
{name="minecraft:rabbit_stew"},
{name="minecraft:rail"},
{name="minecraft:record_11"},
{name="minecraft:record_13"},
{name="minecraft:record_blocks"},
{name="minecraft:record_cat"},
{name="minecraft:record_chirp"},
{name="minecraft:record_far"},
{name="minecraft:record_mall"},
{name="minecraft:record_mellohi"},
{name="minecraft:record_stal"},
{name="minecraft:record_strad"},
{name="minecraft:record_wait"},
{name="minecraft:record_ward"},
{name="minecraft:red_flower"},
{name="minecraft:red_flower", damage=1.0},
{name="minecraft:red_flower", damage=2.0},
{name="minecraft:red_flower", damage=3.0},
{name="minecraft:red_flower", damage=4.0},
{name="minecraft:red_flower", damage=5.0},
{name="minecraft:red_flower", damage=6.0},
{name="minecraft:red_flower", damage=7.0},
{name="minecraft:red_flower", damage=8.0},
{name="minecraft:red_glazed_terracotta"},
{name="minecraft:red_mushroom"},
{name="minecraft:red_mushroom_block"},
{name="minecraft:red_nether_brick"},
{name="minecraft:red_sandstone"},
{name="minecraft:red_sandstone", damage=1.0},
{name="minecraft:red_sandstone", damage=2.0},
{name="minecraft:red_sandstone_stairs"},
{name="minecraft:red_shulker_box"},
{name="minecraft:redstone"},
{name="minecraft:redstone_block"},
{name="minecraft:redstone_lamp"},
{name="minecraft:redstone_ore"},
{name="minecraft:redstone_torch"},
{name="minecraft:reeds"},
{name="minecraft:repeater"},
{name="minecraft:repeating_command_block"},
{name="minecraft:rotten_flesh"},
{name="minecraft:saddle"},
{name="minecraft:salmon"},
{name="minecraft:sand"},
{name="minecraft:sand", damage=1.0},
{name="minecraft:sandstone"},
{name="minecraft:sandstone", damage=1.0},
{name="minecraft:sandstone", damage=2.0},
{name="minecraft:sandstone_stairs"},
{name="minecraft:sapling"},
{name="minecraft:sapling", damage=1.0},
{name="minecraft:sapling", damage=2.0},
{name="minecraft:sapling", damage=3.0},
{name="minecraft:sapling", damage=4.0},
{name="minecraft:sapling", damage=5.0},
{name="minecraft:sea_lantern"},
{name="minecraft:shears"},
{name="minecraft:shield"},
{name="minecraft:shulker_shell"},
{name="minecraft:sign"},
{name="minecraft:silver_glazed_terracotta"},
{name="minecraft:silver_shulker_box"},
{name="minecraft:skull"},
{name="minecraft:skull", damage=1.0},
{name="minecraft:skull", damage=2.0},
{name="minecraft:skull", damage=3.0},
{name="minecraft:skull", damage=4.0},
{name="minecraft:skull", damage=5.0},
{name="minecraft:slime"},
{name="minecraft:slime_ball"},
{name="minecraft:snow"},
{name="minecraft:snow_layer"},
{name="minecraft:snowball"},
{name="minecraft:soul_sand"},
{name="minecraft:speckled_melon"},
{name="minecraft:spectral_arrow"},
{name="minecraft:spider_eye"},
{name="minecraft:sponge"},
{name="minecraft:sponge", damage=1.0},
{name="minecraft:spruce_boat"},
{name="minecraft:spruce_door"},
{name="minecraft:spruce_fence"},
{name="minecraft:spruce_fence_gate"},
{name="minecraft:spruce_stairs"},
{name="minecraft:stained_glass"},
{name="minecraft:stained_glass", damage=1.0},
{name="minecraft:stained_glass", damage=2.0},
{name="minecraft:stained_glass", damage=3.0},
{name="minecraft:stained_glass", damage=4.0},
{name="minecraft:stained_glass", damage=5.0},
{name="minecraft:stained_glass", damage=6.0},
{name="minecraft:stained_glass", damage=7.0},
{name="minecraft:stained_glass", damage=8.0},
{name="minecraft:stained_glass", damage=9.0},
{name="minecraft:stained_glass", damage=10.0},
{name="minecraft:stained_glass", damage=11.0},
{name="minecraft:stained_glass", damage=12.0},
{name="minecraft:stained_glass", damage=13.0},
{name="minecraft:stained_glass", damage=14.0},
{name="minecraft:stained_glass", damage=15.0},
{name="minecraft:stained_glass_pane"},
{name="minecraft:stained_glass_pane", damage=1.0},
{name="minecraft:stained_glass_pane", damage=2.0},
{name="minecraft:stained_glass_pane", damage=3.0},
{name="minecraft:stained_glass_pane", damage=4.0},
{name="minecraft:stained_glass_pane", damage=5.0},
{name="minecraft:stained_glass_pane", damage=6.0},
{name="minecraft:stained_glass_pane", damage=7.0},
{name="minecraft:stained_glass_pane", damage=8.0},
{name="minecraft:stained_glass_pane", damage=9.0},
{name="minecraft:stained_glass_pane", damage=10.0},
{name="minecraft:stained_glass_pane", damage=11.0},
{name="minecraft:stained_glass_pane", damage=12.0},
{name="minecraft:stained_glass_pane", damage=13.0},
{name="minecraft:stained_glass_pane", damage=14.0},
{name="minecraft:stained_glass_pane", damage=15.0},
{name="minecraft:stained_hardened_clay"},
{name="minecraft:stained_hardened_clay", damage=1.0},
{name="minecraft:stained_hardened_clay", damage=2.0},
{name="minecraft:stained_hardened_clay", damage=3.0},
{name="minecraft:stained_hardened_clay", damage=4.0},
{name="minecraft:stained_hardened_clay", damage=5.0},
{name="minecraft:stained_hardened_clay", damage=6.0},
{name="minecraft:stained_hardened_clay", damage=7.0},
{name="minecraft:stained_hardened_clay", damage=8.0},
{name="minecraft:stained_hardened_clay", damage=9.0},
{name="minecraft:stained_hardened_clay", damage=10.0},
{name="minecraft:stained_hardened_clay", damage=11.0},
{name="minecraft:stained_hardened_clay", damage=12.0},
{name="minecraft:stained_hardened_clay", damage=13.0},
{name="minecraft:stained_hardened_clay", damage=14.0},
{name="minecraft:stained_hardened_clay", damage=15.0},
{name="minecraft:stick"},
{name="minecraft:sticky_piston"},
{name="minecraft:stone"},
{name="minecraft:stone", damage=1.0},
{name="minecraft:stone", damage=2.0},
{name="minecraft:stone", damage=3.0},
{name="minecraft:stone", damage=4.0},
{name="minecraft:stone", damage=5.0},
{name="minecraft:stone", damage=6.0},
{name="minecraft:stone_axe"},
{name="minecraft:stone_brick_stairs"},
{name="minecraft:stone_button"},
{name="minecraft:stone_hoe"},
{name="minecraft:stone_pickaxe"},
{name="minecraft:stone_pressure_plate"},
{name="minecraft:stone_shovel"},
{name="minecraft:stone_slab"},
{name="minecraft:stone_slab", damage=1.0},
{name="minecraft:stone_slab", damage=3.0},
{name="minecraft:stone_slab", damage=4.0},
{name="minecraft:stone_slab", damage=5.0},
{name="minecraft:stone_slab", damage=6.0},
{name="minecraft:stone_slab", damage=7.0},
{name="minecraft:stone_slab2"},
{name="minecraft:stone_stairs"},
{name="minecraft:stone_sword"},
{name="minecraft:stonebrick"},
{name="minecraft:stonebrick", damage=1.0},
{name="minecraft:stonebrick", damage=2.0},
{name="minecraft:stonebrick", damage=3.0},
{name="minecraft:string"},
{name="minecraft:structure_block"},
{name="minecraft:structure_void"},
{name="minecraft:sugar"},
{name="minecraft:tallgrass", damage=1.0},
{name="minecraft:tallgrass", damage=2.0},
{name="minecraft:tnt"},
{name="minecraft:tnt_minecart"},
{name="minecraft:torch"},
{name="minecraft:totem_of_undying"},
{name="minecraft:trapdoor"},
{name="minecraft:trapped_chest"},
{name="minecraft:tripwire_hook"},
{name="minecraft:vine"},
{name="minecraft:water_bucket"},
{name="minecraft:waterlily"},
{name="minecraft:web"},
{name="minecraft:wheat"},
{name="minecraft:wheat_seeds"},
{name="minecraft:white_glazed_terracotta"},
{name="minecraft:white_shulker_box"},
{name="minecraft:wooden_axe"},
{name="minecraft:wooden_button"},
{name="minecraft:wooden_door"},
{name="minecraft:wooden_hoe"},
{name="minecraft:wooden_pickaxe"},
{name="minecraft:wooden_pressure_plate"},
{name="minecraft:wooden_shovel"},
{name="minecraft:wooden_slab"},
{name="minecraft:wooden_slab", damage=1.0},
{name="minecraft:wooden_slab", damage=2.0},
{name="minecraft:wooden_slab", damage=3.0},
{name="minecraft:wooden_slab", damage=4.0},
{name="minecraft:wooden_slab", damage=5.0},
{name="minecraft:wooden_sword"},
{name="minecraft:wool"},
{name="minecraft:wool", damage=1.0},
{name="minecraft:wool", damage=2.0},
{name="minecraft:wool", damage=3.0},
{name="minecraft:wool", damage=4.0},
{name="minecraft:wool", damage=5.0},
{name="minecraft:wool", damage=6.0},
{name="minecraft:wool", damage=7.0},
{name="minecraft:wool", damage=8.0},
{name="minecraft:wool", damage=9.0},
{name="minecraft:wool", damage=10.0},
{name="minecraft:wool", damage=11.0},
{name="minecraft:wool", damage=12.0},
{name="minecraft:wool", damage=13.0},
{name="minecraft:wool", damage=14.0},
{name="minecraft:wool", damage=15.0},
{name="minecraft:writable_book"},
{name="minecraft:written_book"},
{name="minecraft:yellow_flower"},
{name="minecraft:yellow_glazed_terracotta"},
{name="minecraft:yellow_shulker_box"},
{name="minecraft:mob_spawner"}}