return {
    immcraft_jj_bookshelf={maxCount=8, craftCount=1},
    immcraft_jj_bookstand={maxCount=8, craftCount=1},
    immcraft_jj_bundle={maxCount=8, craftCount=1},
    immcraft_jj_chest={maxCount=8, craftCount=1},
    immcraft_jj_chisel={maxCount=8, craftCount=1},
    immcraft_jj_cupboard={maxCount=8, craftCount=1},
    immcraft_jj_dummybook={maxCount=8, craftCount=1},
    immcraft_jj_dummybook_jj_1={maxCount=8, craftCount=1},
    immcraft_jj_dummybook_jj_2={maxCount=8, craftCount=1},
    immcraft_jj_dummybook_jj_3={maxCount=8, craftCount=1},
    immcraft_jj_dummybook_jj_4={maxCount=8, craftCount=1},
    immcraft_jj_dummybook_jj_5={maxCount=8, craftCount=1},
    immcraft_jj_dummybook_jj_6={maxCount=8, craftCount=1},
    immcraft_jj_dummybook_jj_7={maxCount=8, craftCount=1},
    immcraft_jj_furnace={maxCount=8, craftCount=1},
    immcraft_jj_in_world_placer={maxCount=8, craftCount=1},
    immcraft_jj_in_world_vertical_placer={maxCount=8, craftCount=1},
    immcraft_jj_manual={maxCount=8, craftCount=1},
    immcraft_jj_rock={maxCount=8, craftCount=1},
    immcraft_jj_saw={maxCount=8, craftCount=1},
    immcraft_jj_shelf={maxCount=8, craftCount=1},
    immcraft_jj_sticks={maxCount=8, craftCount=1},
    immcraft_jj_workbench={maxCount=8, craftCount=1},
    immcraft_jj_workbench_sec={maxCount=8, craftCount=1},
    immersiveengineering_jj_aluminum_scaffolding_stairs0={maxCount=8, craftCount=1},
    immersiveengineering_jj_aluminum_scaffolding_stairs1={maxCount=8, craftCount=1},
    immersiveengineering_jj_aluminum_scaffolding_stairs2={maxCount=8, craftCount=1},
    immersiveengineering_jj_blueprint={maxCount=8, craftCount=1},--.withTag({blueprint: components})
    immersiveengineering_jj_blueprint={maxCount=8, craftCount=1},--.withTag({blueprint: molds})
    immersiveengineering_jj_blueprint={maxCount=8, craftCount=1},--.withTag({blueprint: bullet})
    immersiveengineering_jj_blueprint={maxCount=8, craftCount=1},--.withTag({blueprint: specialBullet})
    immersiveengineering_jj_blueprint={maxCount=8, craftCount=1},--.withTag({blueprint: electrode})
    immersiveengineering_jj_bullet={maxCount=8, craftCount=1},
    immersiveengineering_jj_bullet_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_bullet_jj_2={maxCount=8, craftCount=1},--.withTag({bullet: casull})
    immersiveengineering_jj_bullet_jj_2={maxCount=8, craftCount=1},--.withTag({bullet: armor_piercing})
    immersiveengineering_jj_bullet_jj_2={maxCount=8, craftCount=1},--.withTag({bullet: buckshot})
    immersiveengineering_jj_bullet_jj_2={maxCount=8, craftCount=1},--.withTag({bullet: he})
    immersiveengineering_jj_bullet_jj_2={maxCount=8, craftCount=1},--.withTag({bullet: silver})
    immersiveengineering_jj_bullet_jj_2={maxCount=8, craftCount=1},--.withTag({bullet: dragonsbreath})
    immersiveengineering_jj_bullet_jj_2={maxCount=8, craftCount=1},--.withTag({bullet: potion})
    immersiveengineering_jj_bullet_jj_2={maxCount=8, craftCount=1},--.withTag({bullet: flare})
    immersiveengineering_jj_bullet_jj_2={maxCount=8, craftCount=1},--.withTag({bullet: terrasteel})
    immersiveengineering_jj_bullet_jj_2={maxCount=8, craftCount=1},--.withTag({bullet: wolfpack})
    immersiveengineering_jj_chemthrower={maxCount=8, craftCount=1},
    immersiveengineering_jj_cloth_device={maxCount=8, craftCount=1},
    immersiveengineering_jj_cloth_device_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_cloth_device_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_connector={maxCount=8, craftCount=1},
    immersiveengineering_jj_connector_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_connector_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_connector_jj_3={maxCount=8, craftCount=1},
    immersiveengineering_jj_connector_jj_4={maxCount=8, craftCount=1},
    immersiveengineering_jj_connector_jj_5={maxCount=8, craftCount=1},
    immersiveengineering_jj_connector_jj_6={maxCount=8, craftCount=1},
    immersiveengineering_jj_connector_jj_7={maxCount=8, craftCount=1},
    immersiveengineering_jj_connector_jj_8={maxCount=8, craftCount=1},
    immersiveengineering_jj_connector_jj_9={maxCount=8, craftCount=1},
    immersiveengineering_jj_connector_jj_10={maxCount=8, craftCount=1},
    immersiveengineering_jj_connector_jj_11={maxCount=8, craftCount=1},
    immersiveengineering_jj_connector_jj_12={maxCount=8, craftCount=1},
    immersiveengineering_jj_connector_jj_13={maxCount=8, craftCount=1},
    immersiveengineering_jj_conveyor={maxCount=8, craftCount=1},--.withTag({conveyorType: immersiveengineering:conveyor})
    immersiveengineering_jj_conveyor={maxCount=8, craftCount=1},--.withTag({conveyorType: immersiveengineering:uncontrolled})
    immersiveengineering_jj_conveyor={maxCount=8, craftCount=1},--.withTag({conveyorType: immersiveengineering:dropper})
    immersiveengineering_jj_conveyor={maxCount=8, craftCount=1},--.withTag({conveyorType: immersiveengineering:vertical})
    immersiveengineering_jj_conveyor={maxCount=8, craftCount=1},--.withTag({conveyorType: immersiveengineering:splitter})
    immersiveengineering_jj_conveyor={maxCount=8, craftCount=1},--.withTag({conveyorType: immersiveengineering:covered})
    immersiveengineering_jj_conveyor={maxCount=8, craftCount=1},--.withTag({conveyorType: immersiveengineering:verticalcovered})
    immersiveengineering_jj_coresample={maxCount=8, craftCount=1},
    immersiveengineering_jj_drill={maxCount=8, craftCount=1},
    immersiveengineering_jj_drillhead={maxCount=8, craftCount=1},
    immersiveengineering_jj_drillhead_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_earmuffs={maxCount=8, craftCount=1},
    immersiveengineering_jj_fake_icon={maxCount=8, craftCount=1},
    immersiveengineering_jj_fake_light={maxCount=8, craftCount=1},
    immersiveengineering_jj_faraday_suit_chest={maxCount=8, craftCount=1},
    immersiveengineering_jj_faraday_suit_feet={maxCount=8, craftCount=1},
    immersiveengineering_jj_faraday_suit_head={maxCount=8, craftCount=1},
    immersiveengineering_jj_faraday_suit_legs={maxCount=8, craftCount=1},
    immersiveengineering_jj_fluidbiodiesel={maxCount=8, craftCount=1},
    immersiveengineering_jj_fluidconcrete={maxCount=8, craftCount=1},
    immersiveengineering_jj_fluidcreosote={maxCount=8, craftCount=1},
    immersiveengineering_jj_fluidethanol={maxCount=8, craftCount=1},
    immersiveengineering_jj_fluidplantoil={maxCount=8, craftCount=1},
    immersiveengineering_jj_fluorescent_tube={maxCount=8, craftCount=1},
    immersiveengineering_jj_graphite_electrode={maxCount=8, craftCount=1},
    immersiveengineering_jj_hemp={maxCount=8, craftCount=1},
    immersiveengineering_jj_jerrycan={maxCount=8, craftCount=1},
    immersiveengineering_jj_material={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_3={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_4={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_5={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_6={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_7={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_8={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_9={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_10={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_11={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_12={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_13={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_14={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_15={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_16={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_17={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_18={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_19={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_20={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_21={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_22={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_23={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_24={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_25={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_26={maxCount=8, craftCount=1},
    immersiveengineering_jj_material_jj_27={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_3={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_4={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_5={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_6={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_7={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_8={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_9={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_10={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_11={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_12={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_13={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_14={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_15={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_16={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_17={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_18={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_19={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_20={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_21={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_22={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_23={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_24={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_25={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_26={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_27={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_28={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_29={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_30={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_31={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_32={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_33={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_34={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_35={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_36={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_37={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_38={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_39={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_jj_40={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration0={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration0_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration0_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration0_jj_3={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration0_jj_4={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration0_jj_5={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration0_jj_6={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration0_jj_7={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration1={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration1_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration1_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration1_jj_3={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration1_jj_4={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration1_jj_5={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration1_jj_6={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration1_jj_7={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration1_slab_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration1_slab_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration1_slab_jj_3={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration1_slab_jj_5={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration1_slab_jj_6={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration1_slab_jj_7={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration2={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration2_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration2_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration2_jj_3={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration2_jj_4={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_decoration2_jj_5={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_device0={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_device0_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_device0_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_device0_jj_3={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_device0_jj_4={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_device0_jj_5={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_device0_jj_6={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_device1={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_device1_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_device1_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_device1_jj_3={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_device1_jj_4={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_device1_jj_5={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_device1_jj_6={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_device1_jj_7={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_device1_jj_8={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_device1_jj_9={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_device1_jj_10={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_device1_jj_11={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_device1_jj_13={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_ladder={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_ladder_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_ladder_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_metal_multiblock={maxCount=8, craftCount=1},
    immersiveengineering_jj_mold={maxCount=8, craftCount=1},
    immersiveengineering_jj_mold_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_mold_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_mold_jj_3={maxCount=8, craftCount=1},
    immersiveengineering_jj_mold_jj_4={maxCount=8, craftCount=1},
    immersiveengineering_jj_mold_jj_5={maxCount=8, craftCount=1},
    immersiveengineering_jj_mold_jj_6={maxCount=8, craftCount=1},
    immersiveengineering_jj_mold_jj_7={maxCount=8, craftCount=1},
    immersiveengineering_jj_molten_constantan={maxCount=8, craftCount=1},
    immersiveengineering_jj_molten_uranium={maxCount=8, craftCount=1},
    immersiveengineering_jj_ore={maxCount=8, craftCount=1},
    immersiveengineering_jj_ore_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_ore_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_ore_jj_3={maxCount=8, craftCount=1},
    immersiveengineering_jj_ore_jj_4={maxCount=8, craftCount=1},
    immersiveengineering_jj_ore_jj_5={maxCount=8, craftCount=1},
    immersiveengineering_jj_powerpack={maxCount=8, craftCount=1},
    immersiveengineering_jj_railgun={maxCount=8, craftCount=1},
    immersiveengineering_jj_revolver={maxCount=8, craftCount=1},
    immersiveengineering_jj_seed={maxCount=8, craftCount=1},
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Rosequartz})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Argo})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Sunstrike})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Locus})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Felix})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Sharkface})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Dragon's Breath})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Hawk})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Eyas})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Magnum})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Fox})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Vault-Tec})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Sponsor})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Mass Fusion})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: StormFlower})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Milö³})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Trident})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Chloris})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Crescent Rose})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Qrow})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Lusus Naturae})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Vanguard})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Regal})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Harrowed})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Taken})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Angel's Thesis})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Sutherland})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Exia})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Crimson Lotus})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Dominator})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Warbird})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Matrix})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Twili})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Usurper})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Ancient})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Glacis})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Phoenix})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Radiant})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Hollow})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Microshark})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: N7})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Normandy})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: OmniTool})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: The Kindled})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Dark Fire})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Erruption})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: WAAAGH!})
    immersiveengineering_jj_shader={maxCount=8, craftCount=1},--.withTag({shader_name: Terra})
    immersiveengineering_jj_shader_bag={maxCount=8, craftCount=1},--.withTag({rarity: COMMON})
    immersiveengineering_jj_shader_bag={maxCount=8, craftCount=1},--.withTag({rarity: UNCOMMON})
    immersiveengineering_jj_shader_bag={maxCount=8, craftCount=1},--.withTag({rarity: RARE})
    immersiveengineering_jj_shader_bag={maxCount=8, craftCount=1},--.withTag({rarity: EPIC})
    immersiveengineering_jj_shader_bag={maxCount=8, craftCount=1},--.withTag({rarity: RELIC})
    immersiveengineering_jj_sheetmetal={maxCount=8, craftCount=1},
    immersiveengineering_jj_sheetmetal_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_sheetmetal_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_sheetmetal_jj_3={maxCount=8, craftCount=1},
    immersiveengineering_jj_sheetmetal_jj_4={maxCount=8, craftCount=1},
    immersiveengineering_jj_sheetmetal_jj_5={maxCount=8, craftCount=1},
    immersiveengineering_jj_sheetmetal_jj_6={maxCount=8, craftCount=1},
    immersiveengineering_jj_sheetmetal_jj_7={maxCount=8, craftCount=1},
    immersiveengineering_jj_sheetmetal_jj_8={maxCount=8, craftCount=1},
    immersiveengineering_jj_sheetmetal_jj_9={maxCount=8, craftCount=1},
    immersiveengineering_jj_sheetmetal_jj_10={maxCount=8, craftCount=1},
    immersiveengineering_jj_sheetmetal_slab={maxCount=8, craftCount=1},
    immersiveengineering_jj_sheetmetal_slab_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_sheetmetal_slab_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_sheetmetal_slab_jj_3={maxCount=8, craftCount=1},
    immersiveengineering_jj_sheetmetal_slab_jj_4={maxCount=8, craftCount=1},
    immersiveengineering_jj_sheetmetal_slab_jj_5={maxCount=8, craftCount=1},
    immersiveengineering_jj_sheetmetal_slab_jj_6={maxCount=8, craftCount=1},
    immersiveengineering_jj_sheetmetal_slab_jj_7={maxCount=8, craftCount=1},
    immersiveengineering_jj_sheetmetal_slab_jj_8={maxCount=8, craftCount=1},
    immersiveengineering_jj_sheetmetal_slab_jj_9={maxCount=8, craftCount=1},
    immersiveengineering_jj_sheetmetal_slab_jj_10={maxCount=8, craftCount=1},
    immersiveengineering_jj_shield={maxCount=8, craftCount=1},
    immersiveengineering_jj_skyhook={maxCount=8, craftCount=1},
    immersiveengineering_jj_speedloader={maxCount=8, craftCount=1},
    immersiveengineering_jj_steel_scaffolding_stairs0={maxCount=8, craftCount=1},
    immersiveengineering_jj_steel_scaffolding_stairs1={maxCount=8, craftCount=1},
    immersiveengineering_jj_steel_scaffolding_stairs2={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_decoration={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_decoration_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_decoration_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_decoration_jj_3={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_decoration_jj_4={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_decoration_jj_5={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_decoration_jj_6={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_decoration_jj_7={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_decoration_jj_8={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_decoration_jj_10={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_decoration_slab={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_decoration_slab_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_decoration_slab_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_decoration_slab_jj_4={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_decoration_slab_jj_5={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_decoration_slab_jj_6={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_decoration_slab_jj_7={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_decoration_slab_jj_10={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_decoration_stairs_concrete={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_decoration_stairs_concrete_leaded={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_decoration_stairs_concrete_tile={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_decoration_stairs_hempcrete={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_device_jj_3={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_device_jj_4={maxCount=8, craftCount=1},
    immersiveengineering_jj_stone_device_jj_5={maxCount=8, craftCount=1},
    immersiveengineering_jj_storage={maxCount=8, craftCount=1},
    immersiveengineering_jj_storage_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_storage_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_storage_jj_3={maxCount=8, craftCount=1},
    immersiveengineering_jj_storage_jj_4={maxCount=8, craftCount=1},
    immersiveengineering_jj_storage_jj_5={maxCount=8, craftCount=1},
    immersiveengineering_jj_storage_jj_6={maxCount=8, craftCount=1},
    immersiveengineering_jj_storage_jj_7={maxCount=8, craftCount=1},
    immersiveengineering_jj_storage_jj_8={maxCount=8, craftCount=1},
    immersiveengineering_jj_storage_slab={maxCount=8, craftCount=1},
    immersiveengineering_jj_storage_slab_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_storage_slab_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_storage_slab_jj_3={maxCount=8, craftCount=1},
    immersiveengineering_jj_storage_slab_jj_4={maxCount=8, craftCount=1},
    immersiveengineering_jj_storage_slab_jj_5={maxCount=8, craftCount=1},
    immersiveengineering_jj_storage_slab_jj_6={maxCount=8, craftCount=1},
    immersiveengineering_jj_storage_slab_jj_7={maxCount=8, craftCount=1},
    immersiveengineering_jj_storage_slab_jj_8={maxCount=8, craftCount=1},
    immersiveengineering_jj_tool={maxCount=8, craftCount=1},
    immersiveengineering_jj_tool_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_tool_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_tool_jj_3={maxCount=8, craftCount=1},
    immersiveengineering_jj_toolbox={maxCount=8, craftCount=1},
    immersiveengineering_jj_toolupgrade={maxCount=8, craftCount=1},
    immersiveengineering_jj_toolupgrade_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_toolupgrade_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_toolupgrade_jj_3={maxCount=8, craftCount=1},
    immersiveengineering_jj_toolupgrade_jj_4={maxCount=8, craftCount=1},
    immersiveengineering_jj_toolupgrade_jj_5={maxCount=8, craftCount=1},
    immersiveengineering_jj_toolupgrade_jj_6={maxCount=8, craftCount=1},
    immersiveengineering_jj_toolupgrade_jj_7={maxCount=8, craftCount=1},
    immersiveengineering_jj_toolupgrade_jj_8={maxCount=8, craftCount=1},
    immersiveengineering_jj_toolupgrade_jj_9={maxCount=8, craftCount=1},
    immersiveengineering_jj_toolupgrade_jj_10={maxCount=8, craftCount=1},
    immersiveengineering_jj_toolupgrade_jj_11={maxCount=8, craftCount=1},
    immersiveengineering_jj_toolupgrade_jj_12={maxCount=8, craftCount=1},
    immersiveengineering_jj_toolupgrade_jj_13={maxCount=8, craftCount=1},
    immersiveengineering_jj_treated_wood={maxCount=8, craftCount=1},
    immersiveengineering_jj_treated_wood_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_treated_wood_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_treated_wood_slab={maxCount=8, craftCount=1},
    immersiveengineering_jj_treated_wood_slab_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_treated_wood_slab_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_treated_wood_stairs0={maxCount=8, craftCount=1},
    immersiveengineering_jj_treated_wood_stairs1={maxCount=8, craftCount=1},
    immersiveengineering_jj_treated_wood_stairs2={maxCount=8, craftCount=1},
    immersiveengineering_jj_wirecoil={maxCount=8, craftCount=1},
    immersiveengineering_jj_wirecoil_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_wirecoil_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_wirecoil_jj_3={maxCount=8, craftCount=1},
    immersiveengineering_jj_wirecoil_jj_4={maxCount=8, craftCount=1},
    immersiveengineering_jj_wirecoil_jj_5={maxCount=8, craftCount=1},
    immersiveengineering_jj_wirecoil_jj_6={maxCount=8, craftCount=1},
    immersiveengineering_jj_wirecoil_jj_7={maxCount=8, craftCount=1},
    immersiveengineering_jj_wooden_decoration={maxCount=8, craftCount=1},
    immersiveengineering_jj_wooden_decoration_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_wooden_device0={maxCount=8, craftCount=1},
    immersiveengineering_jj_wooden_device0_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_wooden_device0_jj_2={maxCount=8, craftCount=1},
    immersiveengineering_jj_wooden_device0_jj_3={maxCount=8, craftCount=1},
    immersiveengineering_jj_wooden_device0_jj_4={maxCount=8, craftCount=1},
    immersiveengineering_jj_wooden_device0_jj_5={maxCount=8, craftCount=1},
    immersiveengineering_jj_wooden_device0_jj_6={maxCount=8, craftCount=1},
    immersiveengineering_jj_wooden_device0_jj_7={maxCount=8, craftCount=1},
    immersiveengineering_jj_wooden_device1={maxCount=8, craftCount=1},
    immersiveengineering_jj_wooden_device1_jj_1={maxCount=8, craftCount=1},
    immersiveengineering_jj_wooden_device1_jj_3={maxCount=8, craftCount=1},
    immersiveengineering_jj_wooden_device1_jj_4={maxCount=8, craftCount=1},
    immersivehempcraft_jj_allmix={maxCount=8, craftCount=1},
    immersivehempcraft_jj_allmix_block={maxCount=8, craftCount=1},
    immersivehempcraft_jj_andesite_dust={maxCount=8, craftCount=1},
    immersivehempcraft_jj_apatite={maxCount=8, craftCount=1},
    immersivehempcraft_jj_bale={maxCount=8, craftCount=1},
    immersivehempcraft_jj_butter={maxCount=8, craftCount=1},
    immersivehempcraft_jj_charcoal_dust={maxCount=8, craftCount=1},
    immersivehempcraft_jj_crop={maxCount=8, craftCount=1},
    immersivehempcraft_jj_diorite_dust={maxCount=8, craftCount=1},
    immersivehempcraft_jj_fabric={maxCount=8, craftCount=1},
    immersivehempcraft_jj_fabric_rf={maxCount=8, craftCount=1},
    immersivehempcraft_jj_fertilizer={maxCount=8, craftCount=1},
    immersivehempcraft_jj_flour={maxCount=8, craftCount=1},
    immersivehempcraft_jj_granite_dust={maxCount=8, craftCount=1},
    immersivehempcraft_jj_hempstone_ball={maxCount=8, craftCount=1},
    immersivehempcraft_jj_hempstone_block={maxCount=8, craftCount=1},
    immersivehempcraft_jj_hempstone_brick={maxCount=8, craftCount=1},
    immersivehempcraft_jj_hempstone_bricks={maxCount=8, craftCount=1},
    immersivehempcraft_jj_hempstone_cobble={maxCount=8, craftCount=1},
    immersivehempcraft_jj_hempstone_hardened={maxCount=8, craftCount=1},
    immersivehempcraft_jj_hempstone_plate={maxCount=8, craftCount=1},
    immersivehempcraft_jj_hempstone_sheet={maxCount=8, craftCount=1},
    immersivehempcraft_jj_icon={maxCount=8, craftCount=1},
    immersivehempcraft_jj_lightmix={maxCount=8, craftCount=1},
    immersivehempcraft_jj_lightmix_block={maxCount=8, craftCount=1},
    immersivehempcraft_jj_oil={maxCount=8, craftCount=1},
    immersivehempcraft_jj_perlite={maxCount=8, craftCount=1},
    immersivehempcraft_jj_phosphate={maxCount=8, craftCount=1},
    immersivehempcraft_jj_seed_base={maxCount=8, craftCount=1},
    immersivehempcraft_jj_soil={maxCount=8, craftCount=1},
    immersivetech_jj_connectors={maxCount=8, craftCount=1},
    immersivetech_jj_material={maxCount=8, craftCount=1},
    immersivetech_jj_metal_multiblock={maxCount=8, craftCount=1},
    immersivetech_jj_stone_decoration={maxCount=8, craftCount=1},
    immersivetech_jj_stone_multiblock={maxCount=8, craftCount=1}
}