return {
 ae2stuff_jj_encoder={hasPattern=true,label="Schablonenkodierer",recipe={appliedenergistics2_jj_material_jj_23={need=1,tag=""},appliedenergistics2_jj_part_jj_160={need=1,tag=""},appliedenergistics2_jj_part_jj_180={need=1,tag=""},minecraft_jj_crafting_table={need=1,tag=""}}},
 ae2stuff_jj_grower={hasPattern=true,label="Kristallwachstumskammer",recipe={appliedenergistics2_jj_part_jj_16={need=1,tag=""},appliedenergistics2_jj_quartz_growth_accelerator={need=6,tag=""},minecraft_jj_chest={need=1,tag=""},minecraft_jj_hopper={need=1,tag=""}}},
 ae2stuff_jj_inscriber={hasPattern=true,label="Erweiterte Gravurmaschine",recipe={appliedenergistics2_jj_inscriber={need=1,tag=""},appliedenergistics2_jj_material_jj_24={need=2,tag=""},minecraft_jj_hopper={need=2,tag=""},minecraft_jj_iron_ingot={need=4,tag=""}}},
 ae2stuff_jj_visualiser={hasPattern=true,label="Network Visualisation Tool",recipe={appliedenergistics2_jj_material_jj_12={need=3,tag=""},appliedenergistics2_jj_material_jj_24={need=2,tag=""},appliedenergistics2_jj_material_jj_41={need=2,tag=""},appliedenergistics2_jj_part_jj_160={need=1,tag=""},appliedenergistics2_jj_part_jj_180={need=1,tag=""}}},
 ae2stuff_jj_wireless={hasPattern=true,label="Wireless Connector",recipe={appliedenergistics2_jj_material_jj_12={need=4,tag=""},appliedenergistics2_jj_material_jj_24={need=2,tag=""},appliedenergistics2_jj_material_jj_41={need=1,tag=""},minecraft_jj_iron_ingot={need=2,tag=""}}},
 ae2stuff_jj_wireless_kit={hasPattern=true,label="Wireless Setup Kit",recipe={appliedenergistics2_jj_material_jj_24={need=1,tag=""},appliedenergistics2_jj_material_jj_41={need=1,tag=""},appliedenergistics2_jj_network_tool={need=1,tag=""}}},
 appliedenergistics2_jj_biometric_card={hasPattern=true,label="Biometriekarte",recipe={appliedenergistics2_jj_material_jj_24={need=1,tag=""},minecraft_jj_gold_ingot={need=2,tag=""},minecraft_jj_iron_ingot={need=2,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 appliedenergistics2_jj_cable_bus={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_cell_workbench={hasPattern=true,label="Speicherzellenwerkbank",recipe={appliedenergistics2_jj_material_jj_23={need=1,tag=""},minecraft_jj_chest={need=1,tag=""},minecraft_jj_iron_ingot={need=5,tag=""},minecraft_jj_wool={need=2,tag=""}}},
 appliedenergistics2_jj_certus_quartz_axe={hasPattern=true,label="Certusquarzaxt",recipe={appliedenergistics2_jj_material={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 appliedenergistics2_jj_certus_quartz_cutting_knife={hasPattern=true,label="Certusquarzmeißel",recipe={appliedenergistics2_jj_material={need=2,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 appliedenergistics2_jj_certus_quartz_hoe={hasPattern=true,label="Certusquarzhacke",recipe={appliedenergistics2_jj_material={need=2,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 appliedenergistics2_jj_certus_quartz_pickaxe={hasPattern=true,label="Certusquarzspitzhacke",recipe={appliedenergistics2_jj_material={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 appliedenergistics2_jj_certus_quartz_spade={hasPattern=true,label="Certusquarzschaufel",recipe={appliedenergistics2_jj_material={need=1,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 appliedenergistics2_jj_certus_quartz_sword={hasPattern=true,label="Certusquarzschwert",recipe={appliedenergistics2_jj_material={need=2,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 appliedenergistics2_jj_certus_quartz_wrench={hasPattern=true,label="Certusquarzschraubenschlüssel",recipe={appliedenergistics2_jj_material={need=5,tag=""}}},
 appliedenergistics2_jj_charged_quartz_ore={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_charged_staff={hasPattern=true,label="Geladener Stab",recipe={appliedenergistics2_jj_material_jj_1={need=1,tag=""},minecraft_jj_iron_ingot={need=2,tag=""}}},
 appliedenergistics2_jj_charger={hasPattern=true,label="Ladegerät",recipe={appliedenergistics2_jj_material_jj_7={need=2,tag=""},minecraft_jj_iron_ingot={need=5,tag=""}}},
 appliedenergistics2_jj_chest={hasPattern=true,label="ME-Truhe",recipe={appliedenergistics2_jj_material_jj_7={need=1,tag=""},appliedenergistics2_jj_part_jj_16={need=2,tag=""},appliedenergistics2_jj_part_jj_380={need=1,tag=""},minecraft_jj_glass={need=2,tag=""},minecraft_jj_iron_ingot={need=2,tag=""}}},
 appliedenergistics2_jj_chiseled_quartz_block={hasPattern=true,label="Gemeißelter Certusquarzblock",recipe={appliedenergistics2_jj_quartz_block={need=2,tag=""}}},
 appliedenergistics2_jj_chiseled_quartz_slab={hasPattern=true,label="Gemeißelte Certusquartzstufe",recipe={appliedenergistics2_jj_chiseled_quartz_block={need=3,tag=""}}},
 appliedenergistics2_jj_chiseled_quartz_stairs={hasPattern=true,label="Chiseled Certus Quartz Stairs",recipe={appliedenergistics2_jj_chiseled_quartz_block={need=6,tag=""}}},
 appliedenergistics2_jj_color_applicator={hasPattern=true,label="Farbapplikator - Leer",recipe={appliedenergistics2_jj_energy_cell={need=1,tag=""},appliedenergistics2_jj_material_jj_36={need=1,tag=""},appliedenergistics2_jj_material_jj_43={need=1,tag=""},minecraft_jj_iron_ingot={need=2,tag=""}}},
 appliedenergistics2_jj_condenser={hasPattern=true,label="Materiekondensator",recipe={appliedenergistics2_jj_material_jj_8={need=1,tag=""},minecraft_jj_glass={need=4,tag=""},minecraft_jj_iron_ingot={need=4,tag=""}}},
 appliedenergistics2_jj_controller={hasPattern=true,label="ME-Controller",recipe={appliedenergistics2_jj_material_jj_12={need=4,tag=""},appliedenergistics2_jj_material_jj_24={need=1,tag=""},appliedenergistics2_jj_smooth_sky_stone_block={need=4,tag=""}}},
 appliedenergistics2_jj_crafting_accelerator={hasPattern=true,label="Fertigungs-Prozessoreinheit",recipe={appliedenergistics2_jj_crafting_unit={need=1,tag=""},appliedenergistics2_jj_material_jj_24={need=1,tag=""}}},
 appliedenergistics2_jj_crafting_monitor={hasPattern=true,label="Fertigungsmonitor",recipe={appliedenergistics2_jj_crafting_unit={need=1,tag=""},appliedenergistics2_jj_part_jj_400={need=1,tag=""}}},
 appliedenergistics2_jj_crafting_storage_16k={hasPattern=true,label="16k-Fertigungsspeicher",recipe={appliedenergistics2_jj_crafting_unit={need=1,tag=""},appliedenergistics2_jj_material_jj_37={need=1,tag=""}}},
 appliedenergistics2_jj_crafting_storage_1k={hasPattern=true,label="1k-Fertigungsspeicher",recipe={appliedenergistics2_jj_crafting_unit={need=1,tag=""},appliedenergistics2_jj_material_jj_35={need=1,tag=""}}},
 appliedenergistics2_jj_crafting_storage_4k={hasPattern=true,label="4k-Fertigungsspeicher",recipe={appliedenergistics2_jj_crafting_unit={need=1,tag=""},appliedenergistics2_jj_material_jj_36={need=1,tag=""}}},
 appliedenergistics2_jj_crafting_storage_64k={hasPattern=true,label="64k-Fertigungsspeicher",recipe={appliedenergistics2_jj_crafting_unit={need=1,tag=""},appliedenergistics2_jj_material_jj_38={need=1,tag=""}}},
 appliedenergistics2_jj_crafting_unit={hasPattern=true,label="Fertigungseinheit",recipe={appliedenergistics2_jj_material_jj_22={need=1,tag=""},appliedenergistics2_jj_material_jj_23={need=2,tag=""},appliedenergistics2_jj_part_jj_16={need=2,tag=""},minecraft_jj_iron_ingot={need=4,tag=""}}},
 appliedenergistics2_jj_crank={hasPattern=true,label="Holzkurbel",recipe={minecraft_jj_stick={need=5,tag=""}}},
 appliedenergistics2_jj_creative_energy_cell={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_creative_storage_cell={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_crystal_seed={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_crystal_seed_jj_1200={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_crystal_seed_jj_600={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_dense_energy_cell={hasPattern=true,label="Dichte Energiezelle",recipe={appliedenergistics2_jj_energy_cell={need=8,tag=""},appliedenergistics2_jj_material_jj_23={need=1,tag=""}}},
 appliedenergistics2_jj_drive={hasPattern=true,label="ME-Laufwerk",recipe={appliedenergistics2_jj_material_jj_24={need=2,tag=""},appliedenergistics2_jj_part_jj_16={need=2,tag=""},minecraft_jj_iron_ingot={need=4,tag=""}}},
 appliedenergistics2_jj_dummy_fluid_item={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_encoded_pattern={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_energy_acceptor={hasPattern=true,label="Energieakzeptor",recipe={appliedenergistics2_jj_material_jj_7={need=1,tag=""},appliedenergistics2_jj_quartz_glass={need=4,tag=""},minecraft_jj_iron_ingot={need=4,tag=""}}},
 appliedenergistics2_jj_energy_cell={hasPattern=true,label="Energiezelle",recipe={appliedenergistics2_jj_material={need=4,tag=""},appliedenergistics2_jj_material_jj_8={need=4,tag=""},appliedenergistics2_jj_quartz_glass={need=1,tag=""}}},
 appliedenergistics2_jj_entropy_manipulator={hasPattern=true,label="Entropiemanipulator",recipe={appliedenergistics2_jj_energy_cell={need=1,tag=""},appliedenergistics2_jj_material_jj_24={need=1,tag=""},appliedenergistics2_jj_material_jj_7={need=1,tag=""},minecraft_jj_iron_ingot={need=2,tag=""}}},
 appliedenergistics2_jj_fluid_interface={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_fluid_storage_cell_16k={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_fluid_storage_cell_1k={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_fluid_storage_cell_4k={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_fluid_storage_cell_64k={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_fluix_block={hasPattern=true,label="Fluixblock",recipe={appliedenergistics2_jj_material_jj_7={need=4,tag=""}}},
 appliedenergistics2_jj_fluix_slab={hasPattern=true,label="Fluixstufe",recipe={appliedenergistics2_jj_fluix_block={need=3,tag=""}}},
 appliedenergistics2_jj_fluix_stairs={hasPattern=true,label="Fluix Stairs",recipe={appliedenergistics2_jj_fluix_block={need=6,tag=""}}},
 appliedenergistics2_jj_grindstone={hasPattern=false,label="",recipe={basemetals_jj_wood_gear={need=1,tag=""},minecraft_jj_cobblestone={need=2,tag=""},minecraft_jj_stone={need=3,tag=""}}},
 appliedenergistics2_jj_inscriber={hasPattern=true,label="Gravurmaschine",recipe={appliedenergistics2_jj_material_jj_7={need=1,tag=""},minecraft_jj_iron_ingot={need=5,tag=""},minecraft_jj_sticky_piston={need=2,tag=""}}},
 appliedenergistics2_jj_interface={hasPattern=true,label="ME-Schnittstelle",recipe={appliedenergistics2_jj_material_jj_43={need=1,tag=""},appliedenergistics2_jj_material_jj_44={need=1,tag=""},appliedenergistics2_jj_part_jj_440={need=1,tag=""},minecraft_jj_glass={need=2,tag=""},minecraft_jj_iron_ingot={need=4,tag=""}}},
 appliedenergistics2_jj_io_port={hasPattern=true,label="ME-IO-Port",recipe={appliedenergistics2_jj_drive={need=2,tag=""},appliedenergistics2_jj_material_jj_22={need=1,tag=""},appliedenergistics2_jj_part_jj_16={need=1,tag=""},minecraft_jj_glass={need=3,tag=""},minecraft_jj_iron_ingot={need=2,tag=""}}},
 appliedenergistics2_jj_light_detector={hasPattern=true,label="Quarzlichtsensor",recipe={minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_quartz={need=1,tag=""}}},
 appliedenergistics2_jj_material={hasPattern=false,label="",recipe={appliedenergistics2_jj_quartz_pillar={need=1,tag=""}}},
 appliedenergistics2_jj_material_jj_1={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_10={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_11={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_12={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_13={hasPattern=true,label="Gravur-Kalkulationsdruck",recipe={appliedenergistics2_jj_material_jj_10={need=1,tag=""},mysticalagriculture_jj_certus_quartz_essence={need=8,tag=""}}},
 appliedenergistics2_jj_material_jj_14={hasPattern=true,label="Gravur-Konstruktionsdruck",recipe={minecraft_jj_diamond={need=1,tag=""},mysticalagriculture_jj_certus_quartz_essence={need=8,tag=""}}},
 appliedenergistics2_jj_material_jj_15={hasPattern=true,label="Gravur-Logikdruck",recipe={minecraft_jj_gold_ingot={need=1,tag=""},mysticalagriculture_jj_certus_quartz_essence={need=8,tag=""}}},
 appliedenergistics2_jj_material_jj_16={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_17={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_18={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_19={hasPattern=true,label="Gravur-Siliziumdruck",recipe={appliedenergistics2_jj_material_jj_5={need=1,tag=""},mysticalagriculture_jj_certus_quartz_essence={need=8,tag=""},nuclearcraft_jj_gem_jj_6={need=1,tag=""}}},
 appliedenergistics2_jj_material_jj_2={hasPattern=false,label="",recipe={appliedenergistics2_jj_quartz_ore={need=1,tag=""},ore_jj_dustPetrotheum={need=1,tag=""}}},
 appliedenergistics2_jj_material_jj_20={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_21={hasPattern=true,label="Schreiber-Namensdruck",recipe={appliedenergistics2_jj_material={need=4,tag=""},appliedenergistics2_jj_material_jj_45={need=1,tag=""},minecraft_jj_iron_ingot={need=4,tag=""}}},
 appliedenergistics2_jj_material_jj_22={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_23={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_24={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_25={hasPattern=true,label="Basiskarte",recipe={appliedenergistics2_jj_material_jj_23={need=1,tag=""},minecraft_jj_gold_ingot={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 appliedenergistics2_jj_material_jj_26={hasPattern=true,label="Redstone-Karte",recipe={appliedenergistics2_jj_material_jj_25={need=1,tag=""},minecraft_jj_redstone_torch={need=1,tag=""}}},
 appliedenergistics2_jj_material_jj_27={hasPattern=true,label="Kapazitätskarte",recipe={appliedenergistics2_jj_material={need=1,tag=""},appliedenergistics2_jj_material_jj_25={need=1,tag=""}}},
 appliedenergistics2_jj_material_jj_28={hasPattern=true,label="Fortgeschrittene Karte",recipe={appliedenergistics2_jj_material_jj_23={need=1,tag=""},minecraft_jj_diamond={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 appliedenergistics2_jj_material_jj_29={hasPattern=true,label="Ungenauigkeitskarte",recipe={appliedenergistics2_jj_material_jj_28={need=1,tag=""},minecraft_jj_wool={need=1,tag=""}}},
 appliedenergistics2_jj_material_jj_3={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_30={hasPattern=true,label="Beschleunigungskarte",recipe={appliedenergistics2_jj_material_jj_28={need=1,tag=""},appliedenergistics2_jj_material_jj_7={need=1,tag=""}}},
 appliedenergistics2_jj_material_jj_31={hasPattern=true,label="Umkehrungskarte",recipe={appliedenergistics2_jj_material_jj_28={need=1,tag=""},minecraft_jj_redstone_torch={need=1,tag=""}}},
 appliedenergistics2_jj_material_jj_32={hasPattern=true,label="2³ Raumkomponente",recipe={appliedenergistics2_jj_material_jj_24={need=1,tag=""},appliedenergistics2_jj_material_jj_9={need=4,tag=""},minecraft_jj_glowstone_dust={need=4,tag=""}}},
 appliedenergistics2_jj_material_jj_33={hasPattern=true,label="16³ Raumkomponente",recipe={appliedenergistics2_jj_material_jj_24={need=1,tag=""},appliedenergistics2_jj_material_jj_32={need=4,tag=""},minecraft_jj_glowstone_dust={need=4,tag=""}}},
 appliedenergistics2_jj_material_jj_34={hasPattern=true,label="128³ Raumkomponente",recipe={appliedenergistics2_jj_material_jj_24={need=1,tag=""},appliedenergistics2_jj_material_jj_33={need=4,tag=""},minecraft_jj_glowstone_dust={need=4,tag=""}}},
 appliedenergistics2_jj_material_jj_35={hasPattern=true,label="1k-ME-Speicherkomponente",recipe={appliedenergistics2_jj_material={need=4,tag=""},appliedenergistics2_jj_material_jj_22={need=1,tag=""},minecraft_jj_redstone={need=4,tag=""}}},
 appliedenergistics2_jj_material_jj_36={hasPattern=true,label="4k-ME-Speicherkomponente",recipe={appliedenergistics2_jj_material_jj_23={need=1,tag=""},appliedenergistics2_jj_material_jj_35={need=3,tag=""},appliedenergistics2_jj_quartz_glass={need=1,tag=""},minecraft_jj_redstone={need=4,tag=""}}},
 appliedenergistics2_jj_material_jj_37={hasPattern=false,label="",recipe={appliedenergistics2_jj_material_jj_24={need=1,tag=""},appliedenergistics2_jj_material_jj_36={need=3,tag=""},appliedenergistics2_jj_quartz_glass={need=1,tag=""},minecraft_jj_glowstone_dust={need=4,tag=""}}},
 appliedenergistics2_jj_material_jj_38={hasPattern=false,label="",recipe={appliedenergistics2_jj_material_jj_24={need=1,tag=""},appliedenergistics2_jj_material_jj_37={need=3,tag=""},appliedenergistics2_jj_quartz_glass={need=1,tag=""},minecraft_jj_glowstone_dust={need=4,tag=""}}},
 appliedenergistics2_jj_material_jj_39={hasPattern=true,label="ME-Speichergehäuse",recipe={appliedenergistics2_jj_quartz_glass={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_redstone={need=3,tag=""}}},
 appliedenergistics2_jj_material_jj_4={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_40={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_41={hasPattern=true,label="Drahtlosempfänger",recipe={appliedenergistics2_jj_material_jj_9={need=1,tag=""},appliedenergistics2_jj_part_jj_140={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 appliedenergistics2_jj_material_jj_42={hasPattern=true,label="Drahtlosverstärker",recipe={appliedenergistics2_jj_material={need=1,tag=""},appliedenergistics2_jj_material_jj_46={need=1,tag=""},appliedenergistics2_jj_material_jj_8={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 appliedenergistics2_jj_material_jj_43={hasPattern=true,label="Formationskern",recipe={appliedenergistics2_jj_material={need=1,tag=""},appliedenergistics2_jj_material_jj_22={need=1,tag=""},appliedenergistics2_jj_material_jj_8={need=1,tag=""}}},
 appliedenergistics2_jj_material_jj_44={hasPattern=true,label="Annihilationskern",recipe={appliedenergistics2_jj_material_jj_22={need=1,tag=""},appliedenergistics2_jj_material_jj_8={need=1,tag=""},minecraft_jj_quartz={need=1,tag=""}}},
 appliedenergistics2_jj_material_jj_45={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_46={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_47={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_48={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_49={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_5={hasPattern=false,label="",recipe={mysticalagriculture_jj_silicon_essence={need=3,tag=""}}},
 appliedenergistics2_jj_material_jj_51={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_52={hasPattern=true,label="Leere Schablone",recipe={appliedenergistics2_jj_material={need=1,tag=""},appliedenergistics2_jj_quartz_glass={need=2,tag=""},minecraft_jj_glowstone_dust={need=3,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 appliedenergistics2_jj_material_jj_53={hasPattern=true,label="Fertigungskarte",recipe={appliedenergistics2_jj_material_jj_25={need=1,tag=""},minecraft_jj_crafting_table={need=1,tag=""}}},
 appliedenergistics2_jj_material_jj_54={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_55={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_56={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_57={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_6={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_7={hasPattern=false,label="",recipe={mysticalagriculture_jj_fluix_essence={need=8,tag=""}}},
 appliedenergistics2_jj_material_jj_8={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_material_jj_9={hasPattern=true,label="Fluixperle",recipe={appliedenergistics2_jj_material_jj_7={need=4,tag=""},appliedenergistics2_jj_material_jj_8={need=4,tag=""},minecraft_jj_ender_pearl={need=1,tag=""}}},
 appliedenergistics2_jj_matrix_frame={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_matter_cannon={hasPattern=true,label="Materiekanone",recipe={appliedenergistics2_jj_energy_cell={need=1,tag=""},appliedenergistics2_jj_material_jj_36={need=1,tag=""},appliedenergistics2_jj_material_jj_43={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 appliedenergistics2_jj_memory_card={hasPattern=true,label="Speicherkarte",recipe={appliedenergistics2_jj_material_jj_23={need=1,tag=""},minecraft_jj_gold_ingot={need=2,tag=""},minecraft_jj_iron_ingot={need=2,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 appliedenergistics2_jj_molecular_assembler={hasPattern=true,label="Molekularassembler",recipe={appliedenergistics2_jj_material_jj_43={need=1,tag=""},appliedenergistics2_jj_material_jj_44={need=1,tag=""},appliedenergistics2_jj_quartz_glass={need=2,tag=""},minecraft_jj_crafting_table={need=1,tag=""},minecraft_jj_iron_ingot={need=4,tag=""}}},
 appliedenergistics2_jj_nether_quartz_axe={hasPattern=true,label="Netherquarzaxt",recipe={minecraft_jj_quartz={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 appliedenergistics2_jj_nether_quartz_cutting_knife={hasPattern=true,label="Netherquarzmeißel",recipe={minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_quartz={need=2,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 appliedenergistics2_jj_nether_quartz_hoe={hasPattern=true,label="Netherquarzhacke",recipe={minecraft_jj_quartz={need=2,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 appliedenergistics2_jj_nether_quartz_pickaxe={hasPattern=true,label="Netherquarzspitzhacke",recipe={minecraft_jj_quartz={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 appliedenergistics2_jj_nether_quartz_spade={hasPattern=true,label="Netherquarzschaufel",recipe={minecraft_jj_quartz={need=1,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 appliedenergistics2_jj_nether_quartz_sword={hasPattern=true,label="Netherquarzschwert",recipe={minecraft_jj_quartz={need=2,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 appliedenergistics2_jj_nether_quartz_wrench={hasPattern=true,label="Netherquarzschraubenschlüssel",recipe={minecraft_jj_quartz={need=5,tag=""}}},
 appliedenergistics2_jj_network_tool={hasPattern=true,label="Netzwerksonde",recipe={appliedenergistics2_jj_certus_quartz_wrench={need=1,tag=""},appliedenergistics2_jj_material_jj_23={need=1,tag=""},appliedenergistics2_jj_nether_quartz_wrench={need=1,tag=""},appliedenergistics2_jj_part_jj_160={need=1,tag=""},appliedenergistics2_jj_part_jj_180={need=1,tag=""},minecraft_jj_chest={need=1,tag=""}}},
 appliedenergistics2_jj_paint={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_paint_ball={hasPattern=true,label="Farbball - Weiß",recipe={appliedenergistics2_jj_material_jj_6={need=8,tag=""},minecraft_jj_dye_jj_15={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_1={hasPattern=true,label="Farbball - Orange",recipe={appliedenergistics2_jj_material_jj_6={need=8,tag=""},minecraft_jj_dye_jj_14={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_10={hasPattern=true,label="Farbball - Violett",recipe={appliedenergistics2_jj_material_jj_6={need=8,tag=""},minecraft_jj_dye_jj_5={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_11={hasPattern=true,label="Farbball - Blau",recipe={appliedenergistics2_jj_material_jj_6={need=8,tag=""},minecraft_jj_dye_jj_4={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_12={hasPattern=true,label="Farbball - Braun",recipe={appliedenergistics2_jj_material_jj_6={need=8,tag=""},minecraft_jj_dye_jj_3={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_13={hasPattern=true,label="Farbball - Grün",recipe={appliedenergistics2_jj_material_jj_6={need=8,tag=""},minecraft_jj_dye_jj_2={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_14={hasPattern=true,label="Farbball - Rot",recipe={appliedenergistics2_jj_material_jj_6={need=8,tag=""},minecraft_jj_dye_jj_1={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_15={hasPattern=true,label="Farbball - Schwarz",recipe={appliedenergistics2_jj_material_jj_6={need=8,tag=""},minecraft_jj_dye={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_2={hasPattern=true,label="Farbball - Magenta",recipe={appliedenergistics2_jj_material_jj_6={need=8,tag=""},minecraft_jj_dye_jj_13={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_20={hasPattern=true,label="Farbball - Lumen Weiß",recipe={appliedenergistics2_jj_paint_ball={need=8,tag=""},minecraft_jj_glowstone_dust={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_21={hasPattern=true,label="Farbball - Lumen Orange",recipe={appliedenergistics2_jj_paint_ball_jj_1={need=8,tag=""},minecraft_jj_glowstone_dust={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_22={hasPattern=true,label="Farbball - Lumen Magenta",recipe={appliedenergistics2_jj_paint_ball_jj_2={need=8,tag=""},minecraft_jj_glowstone_dust={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_23={hasPattern=true,label="Farbball - Lumen Hellblau",recipe={appliedenergistics2_jj_paint_ball_jj_3={need=8,tag=""},minecraft_jj_glowstone_dust={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_24={hasPattern=true,label="Farbball - Lumen Gelb",recipe={appliedenergistics2_jj_paint_ball_jj_4={need=8,tag=""},minecraft_jj_glowstone_dust={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_25={hasPattern=true,label="Farbball - Lumen Hellgrün",recipe={appliedenergistics2_jj_paint_ball_jj_5={need=8,tag=""},minecraft_jj_glowstone_dust={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_26={hasPattern=true,label="Farbball - Lumen Pink",recipe={appliedenergistics2_jj_paint_ball_jj_6={need=8,tag=""},minecraft_jj_glowstone_dust={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_27={hasPattern=true,label="Farbball - Lumen Grau",recipe={appliedenergistics2_jj_paint_ball_jj_7={need=8,tag=""},minecraft_jj_glowstone_dust={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_28={hasPattern=true,label="Farbball - Lumen Hellgrau",recipe={appliedenergistics2_jj_paint_ball_jj_8={need=8,tag=""},minecraft_jj_glowstone_dust={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_29={hasPattern=true,label="Farbball - Lumen Türkis",recipe={appliedenergistics2_jj_paint_ball_jj_9={need=8,tag=""},minecraft_jj_glowstone_dust={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_3={hasPattern=true,label="Farbball - Hellblau",recipe={appliedenergistics2_jj_material_jj_6={need=8,tag=""},minecraft_jj_dye_jj_12={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_30={hasPattern=true,label="Farbball - Lumen Violett",recipe={appliedenergistics2_jj_paint_ball_jj_10={need=8,tag=""},minecraft_jj_glowstone_dust={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_31={hasPattern=true,label="Farbball - Lumen Blau",recipe={appliedenergistics2_jj_paint_ball_jj_11={need=8,tag=""},minecraft_jj_glowstone_dust={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_32={hasPattern=true,label="Farbball - Lumen Braun",recipe={appliedenergistics2_jj_paint_ball_jj_12={need=8,tag=""},minecraft_jj_glowstone_dust={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_33={hasPattern=true,label="Farbball - Lumen Grün",recipe={appliedenergistics2_jj_paint_ball_jj_13={need=8,tag=""},minecraft_jj_glowstone_dust={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_34={hasPattern=true,label="Farbball - Lumen Rot",recipe={appliedenergistics2_jj_paint_ball_jj_14={need=8,tag=""},minecraft_jj_glowstone_dust={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_35={hasPattern=true,label="Farbball - Lumen Schwarz",recipe={appliedenergistics2_jj_paint_ball_jj_15={need=8,tag=""},minecraft_jj_glowstone_dust={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_4={hasPattern=true,label="Farbball - Gelb",recipe={appliedenergistics2_jj_material_jj_6={need=8,tag=""},minecraft_jj_dye_jj_11={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_5={hasPattern=true,label="Farbball - Hellgrün",recipe={appliedenergistics2_jj_material_jj_6={need=8,tag=""},minecraft_jj_dye_jj_10={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_6={hasPattern=true,label="Farbball - Pink",recipe={appliedenergistics2_jj_material_jj_6={need=8,tag=""},minecraft_jj_dye_jj_9={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_7={hasPattern=true,label="Farbball - Grau",recipe={appliedenergistics2_jj_material_jj_6={need=8,tag=""},minecraft_jj_dye_jj_8={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_8={hasPattern=true,label="Farbball - Hellgrau",recipe={appliedenergistics2_jj_material_jj_6={need=8,tag=""},minecraft_jj_dye_jj_7={need=1,tag=""}}},
 appliedenergistics2_jj_paint_ball_jj_9={hasPattern=true,label="Farbball - Türkis",recipe={appliedenergistics2_jj_material_jj_6={need=8,tag=""},minecraft_jj_dye_jj_6={need=1,tag=""}}},
 appliedenergistics2_jj_part={hasPattern=true,label="ME-Glaskabel - Weiß",recipe={appliedenergistics2_jj_part_jj_16={need=8,tag=""},minecraft_jj_dye_jj_15={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_1={hasPattern=true,label="ME-Glaskabel - Orange",recipe={appliedenergistics2_jj_part_jj_16={need=8,tag=""},minecraft_jj_dye_jj_14={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_10={hasPattern=true,label="ME-Glaskabel - Violett",recipe={appliedenergistics2_jj_part_jj_16={need=8,tag=""},minecraft_jj_dye_jj_5={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_100={hasPattern=true,label="Invertierter schaltbarer ME-Bus",recipe={appliedenergistics2_jj_part_jj_80={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_11={hasPattern=true,label="ME-Glaskabel - Blau",recipe={appliedenergistics2_jj_part_jj_16={need=8,tag=""},minecraft_jj_dye_jj_4={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_12={hasPattern=true,label="ME-Glaskabel - Braun",recipe={appliedenergistics2_jj_part_jj_16={need=8,tag=""},minecraft_jj_dye_jj_3={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_120={hasPattern=true,label="Kabelanker",recipe={appliedenergistics2_jj_certus_quartz_cutting_knife={need=1,tag=""},appliedenergistics2_jj_nether_quartz_cutting_knife={need=1,tag=""},ic2_jj_ingot_jj_2={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_13={hasPattern=true,label="ME-Glaskabel - Grün",recipe={appliedenergistics2_jj_part_jj_16={need=8,tag=""},minecraft_jj_dye_jj_2={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_14={hasPattern=true,label="ME-Glaskabel - Rot",recipe={appliedenergistics2_jj_part_jj_16={need=8,tag=""},minecraft_jj_dye_jj_1={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_140={hasPattern=true,label="Quarzfaser",recipe={actuallyadditions_jj_item_dust_jj_5={need=1,tag=""},appliedenergistics2_jj_material_jj_2={need=3,tag=""},minecraft_jj_glass={need=6,tag=""}}},
 appliedenergistics2_jj_part_jj_15={hasPattern=true,label="ME-Glaskabel - Schwarz",recipe={appliedenergistics2_jj_part_jj_16={need=8,tag=""},minecraft_jj_dye={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_16={hasPattern=true,label="ME-Glaskabel - Fluix",recipe={appliedenergistics2_jj_material_jj_7={need=2,tag=""},appliedenergistics2_jj_part_jj_140={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_160={hasPattern=true,label="Helles Leuchtfeld",recipe={appliedenergistics2_jj_part_jj_180={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_180={hasPattern=true,label="Leuchtfeld",recipe={appliedenergistics2_jj_part_jj_200={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_2={hasPattern=true,label="ME-Glaskabel - Magenta",recipe={appliedenergistics2_jj_part_jj_16={need=8,tag=""},minecraft_jj_dye_jj_13={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_20={hasPattern=true,label="Verdecktes ME-Kabel - Weiß",recipe={appliedenergistics2_jj_part_jj_36={need=8,tag=""},minecraft_jj_dye_jj_15={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_200={hasPattern=true,label="Dunkles Leuchtfeld",recipe={appliedenergistics2_jj_part_jj_160={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_21={hasPattern=true,label="Verdecktes ME-Kabel - Orange",recipe={appliedenergistics2_jj_part_jj_36={need=8,tag=""},minecraft_jj_dye_jj_14={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_22={hasPattern=true,label="Verdecktes ME-Kabel - Magenta",recipe={appliedenergistics2_jj_part_jj_36={need=8,tag=""},minecraft_jj_dye_jj_13={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_220={hasPattern=true,label="ME-Speicherbus",recipe={appliedenergistics2_jj_interface={need=1,tag=""},appliedenergistics2_jj_part_jj_440={need=1,tag=""},minecraft_jj_piston={need=1,tag=""},minecraft_jj_sticky_piston={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_221={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_part_jj_23={hasPattern=true,label="Verdecktes ME-Kabel - Hellblau",recipe={appliedenergistics2_jj_part_jj_36={need=8,tag=""},minecraft_jj_dye_jj_12={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_24={hasPattern=true,label="Verdecktes ME-Kabel - Gelb",recipe={appliedenergistics2_jj_part_jj_36={need=8,tag=""},minecraft_jj_dye_jj_11={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_240={hasPattern=true,label="ME-Importbus",recipe={appliedenergistics2_jj_material_jj_44={need=1,tag=""},minecraft_jj_iron_ingot={need=2,tag=""},minecraft_jj_sticky_piston={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_241={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_part_jj_25={hasPattern=true,label="Verdecktes ME-Kabel - Hellgrün",recipe={appliedenergistics2_jj_part_jj_36={need=8,tag=""},minecraft_jj_dye_jj_10={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_26={hasPattern=true,label="Verdecktes ME-Kabel - Pink",recipe={appliedenergistics2_jj_part_jj_36={need=8,tag=""},minecraft_jj_dye_jj_9={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_260={hasPattern=true,label="ME-Exportbus",recipe={appliedenergistics2_jj_material_jj_43={need=1,tag=""},minecraft_jj_iron_ingot={need=2,tag=""},minecraft_jj_piston={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_261={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_part_jj_27={hasPattern=true,label="Verdecktes ME-Kabel - Grau",recipe={appliedenergistics2_jj_part_jj_36={need=8,tag=""},minecraft_jj_dye_jj_8={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_28={hasPattern=true,label="Verdecktes ME-Kabel - Hellgrau",recipe={appliedenergistics2_jj_part_jj_36={need=8,tag=""},minecraft_jj_dye_jj_7={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_280={hasPattern=true,label="ME-Füllstandsemitter",recipe={appliedenergistics2_jj_material_jj_23={need=1,tag=""},minecraft_jj_redstone_torch={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_281={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_part_jj_29={hasPattern=true,label="Verdecktes ME-Kabel - Türkis",recipe={appliedenergistics2_jj_part_jj_36={need=8,tag=""},minecraft_jj_dye_jj_6={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_3={hasPattern=true,label="ME-Glaskabel - Hellblau",recipe={appliedenergistics2_jj_part_jj_16={need=8,tag=""},minecraft_jj_dye_jj_12={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_30={hasPattern=true,label="Verdecktes ME-Kabel - Violett",recipe={appliedenergistics2_jj_part_jj_36={need=8,tag=""},minecraft_jj_dye_jj_5={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_300={hasPattern=true,label="ME-Annihilationsfeld",recipe={appliedenergistics2_jj_material_jj_44={need=1,tag=""},appliedenergistics2_jj_material_jj_7={need=3,tag=""},minecraft_jj_iron_ingot={need=2,tag=""}}},
 appliedenergistics2_jj_part_jj_301={hasPattern=true,label="ME-Identitätsannihilationsfelds",recipe={appliedenergistics2_jj_material_jj_9={need=1,tag=""},appliedenergistics2_jj_part_jj_300={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_302={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_part_jj_31={hasPattern=true,label="Verdecktes ME-Kabel - Blau",recipe={appliedenergistics2_jj_part_jj_36={need=8,tag=""},minecraft_jj_dye_jj_4={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_32={hasPattern=true,label="Verdecktes ME-Kabel - Braun",recipe={appliedenergistics2_jj_part_jj_36={need=8,tag=""},minecraft_jj_dye_jj_3={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_320={hasPattern=true,label="ME-Formationsfeld",recipe={appliedenergistics2_jj_material_jj_43={need=1,tag=""},appliedenergistics2_jj_material_jj_7={need=3,tag=""},minecraft_jj_iron_ingot={need=2,tag=""}}},
 appliedenergistics2_jj_part_jj_321={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_part_jj_33={hasPattern=true,label="Verdecktes ME-Kabel - Grün",recipe={appliedenergistics2_jj_part_jj_36={need=8,tag=""},minecraft_jj_dye_jj_2={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_34={hasPattern=true,label="Verdecktes ME-Kabel - Rot",recipe={appliedenergistics2_jj_part_jj_36={need=8,tag=""},minecraft_jj_dye_jj_1={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_340={hasPattern=true,label="ME-Schablonenkonsole",recipe={appliedenergistics2_jj_material_jj_24={need=1,tag=""},appliedenergistics2_jj_part_jj_360={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_35={hasPattern=true,label="Verdecktes ME-Kabel - Schwarz",recipe={appliedenergistics2_jj_part_jj_36={need=8,tag=""},minecraft_jj_dye={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_36={hasPattern=true,label="Verdecktes ME-Kabel - Fluix",recipe={appliedenergistics2_jj_part_jj_16={need=1,tag=""},appliedenergistics2_jj_part_jj_20={need=1,tag=""},appliedenergistics2_jj_part_jj_21={need=1,tag=""},appliedenergistics2_jj_part_jj_22={need=1,tag=""},appliedenergistics2_jj_part_jj_23={need=1,tag=""},appliedenergistics2_jj_part_jj_24={need=1,tag=""},appliedenergistics2_jj_part_jj_25={need=1,tag=""},appliedenergistics2_jj_part_jj_26={need=1,tag=""},appliedenergistics2_jj_part_jj_27={need=1,tag=""},appliedenergistics2_jj_part_jj_28={need=1,tag=""},appliedenergistics2_jj_part_jj_29={need=1,tag=""},appliedenergistics2_jj_part_jj_30={need=1,tag=""},appliedenergistics2_jj_part_jj_31={need=1,tag=""},appliedenergistics2_jj_part_jj_32={need=1,tag=""},appliedenergistics2_jj_part_jj_33={need=1,tag=""},appliedenergistics2_jj_part_jj_34={need=1,tag=""},appliedenergistics2_jj_part_jj_35={need=1,tag=""},appliedenergistics2_jj_part_jj_36={need=1,tag=""},minecraft_jj_water_bucket={need=1,tag=""},minecraft_jj_wool={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_360={hasPattern=true,label="ME-Fertigungskonsole",recipe={appliedenergistics2_jj_material_jj_23={need=1,tag=""},appliedenergistics2_jj_part_jj_380={need=1,tag=""},minecraft_jj_crafting_table={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_380={hasPattern=true,label="ME-Konsole",recipe={appliedenergistics2_jj_material_jj_22={need=1,tag=""},appliedenergistics2_jj_material_jj_43={need=1,tag=""},appliedenergistics2_jj_material_jj_44={need=1,tag=""},appliedenergistics2_jj_part_jj_160={need=1,tag=""},appliedenergistics2_jj_part_jj_180={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_4={hasPattern=true,label="ME-Glaskabel - Gelb",recipe={appliedenergistics2_jj_part_jj_16={need=8,tag=""},minecraft_jj_dye_jj_11={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_40={hasPattern=true,label="Schlaues ME-Kabel - Weiß",recipe={appliedenergistics2_jj_part_jj_56={need=8,tag=""},minecraft_jj_dye_jj_15={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_400={hasPattern=true,label="ME-Speichermonitor",recipe={appliedenergistics2_jj_part_jj_160={need=1,tag=""},appliedenergistics2_jj_part_jj_180={need=1,tag=""},appliedenergistics2_jj_part_jj_280={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_41={hasPattern=true,label="Schlaues ME-Kabel - Orange",recipe={appliedenergistics2_jj_part_jj_56={need=8,tag=""},minecraft_jj_dye_jj_14={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_42={hasPattern=true,label="Schlaues ME-Kabel - Magenta",recipe={appliedenergistics2_jj_part_jj_56={need=8,tag=""},minecraft_jj_dye_jj_13={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_420={hasPattern=true,label="ME-Konversionsmonitor",recipe={appliedenergistics2_jj_material_jj_43={need=1,tag=""},appliedenergistics2_jj_material_jj_44={need=1,tag=""},appliedenergistics2_jj_part_jj_400={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_43={hasPattern=true,label="Schlaues ME-Kabel - Hellblau",recipe={appliedenergistics2_jj_part_jj_56={need=8,tag=""},minecraft_jj_dye_jj_12={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_44={hasPattern=true,label="Schlaues ME-Kabel - Gelb",recipe={appliedenergistics2_jj_part_jj_56={need=8,tag=""},minecraft_jj_dye_jj_11={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_440={hasPattern=true,label="ME-Schnittstelle",recipe={appliedenergistics2_jj_interface={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_441={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_part_jj_45={hasPattern=true,label="Schlaues ME-Kabel - Hellgrün",recipe={appliedenergistics2_jj_part_jj_56={need=8,tag=""},minecraft_jj_dye_jj_10={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_46={hasPattern=true,label="Schlaues ME-Kabel - Pink",recipe={appliedenergistics2_jj_part_jj_56={need=8,tag=""},minecraft_jj_dye_jj_9={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_460={hasPattern=true,label="P2P-Tunnel - ME",recipe={appliedenergistics2_jj_material_jj_24={need=1,tag=""},appliedenergistics2_jj_material_jj_7={need=3,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 appliedenergistics2_jj_part_jj_461={hasPattern=true,label="P2P-Tunnel - Redstone",recipe={appliedenergistics2_jj_part_jj_460={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""}}},
 appliedenergistics2_jj_part_jj_462={hasPattern=true,label="P2P-Tunnel - Item",recipe={appliedenergistics2_jj_part_jj_460={need=1,tag=""},minecraft_jj_chest={need=2,tag=""}}},
 appliedenergistics2_jj_part_jj_463={hasPattern=true,label="P2P-Tunnel - Flüssigkeiten",recipe={appliedenergistics2_jj_part_jj_460={need=1,tag=""},minecraft_jj_water_bucket={need=2,tag=""}}},
 appliedenergistics2_jj_part_jj_465={hasPattern=true,label="P2P-Tunnel - EU",recipe={appliedenergistics2_jj_part_jj_460={need=1,tag=""},ic2_jj_cable_jj_1={need=2,tag=""}}},
 appliedenergistics2_jj_part_jj_467={hasPattern=true,label="P2P-Tunnel - Licht",recipe={appliedenergistics2_jj_part_jj_460={need=1,tag=""},minecraft_jj_glowstone_dust={need=2,tag=""}}},
 appliedenergistics2_jj_part_jj_469={hasPattern=true,label="P2P-Tunnel - FE",recipe={appliedenergistics2_jj_part_jj_460={need=1,tag=""},immersiveengineering_jj_wirecoil_jj_2={need=2,tag=""}}},
 appliedenergistics2_jj_part_jj_47={hasPattern=true,label="Schlaues ME-Kabel - Grau",recipe={appliedenergistics2_jj_part_jj_56={need=8,tag=""},minecraft_jj_dye_jj_8={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_48={hasPattern=true,label="Schlaues ME-Kabel - Hellgrau",recipe={appliedenergistics2_jj_part_jj_56={need=8,tag=""},minecraft_jj_dye_jj_7={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_480={hasPattern=true,label="ME-Schnittstellenkonsole",recipe={appliedenergistics2_jj_interface={need=1,tag=""},appliedenergistics2_jj_material_jj_24={need=1,tag=""},appliedenergistics2_jj_part_jj_160={need=1,tag=""},appliedenergistics2_jj_part_jj_180={need=1,tag=""},appliedenergistics2_jj_part_jj_440={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_49={hasPattern=true,label="Schlaues ME-Kabel - Türkis",recipe={appliedenergistics2_jj_part_jj_56={need=8,tag=""},minecraft_jj_dye_jj_6={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_5={hasPattern=true,label="ME-Glaskabel - Hellgrün",recipe={appliedenergistics2_jj_part_jj_16={need=8,tag=""},minecraft_jj_dye_jj_10={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_50={hasPattern=true,label="Schlaues ME-Kabel - Violett",recipe={appliedenergistics2_jj_part_jj_56={need=8,tag=""},minecraft_jj_dye_jj_5={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_500={hasPattern=true,label="ME Dense Covered Cable - Weiß",recipe={appliedenergistics2_jj_part_jj_516={need=8,tag=""},minecraft_jj_dye_jj_15={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_501={hasPattern=true,label="ME Dense Covered Cable - Orange",recipe={appliedenergistics2_jj_part_jj_516={need=8,tag=""},minecraft_jj_dye_jj_14={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_502={hasPattern=true,label="ME Dense Covered Cable - Magenta",recipe={appliedenergistics2_jj_part_jj_516={need=8,tag=""},minecraft_jj_dye_jj_13={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_503={hasPattern=true,label="ME Dense Covered Cable - Hellblau",recipe={appliedenergistics2_jj_part_jj_516={need=8,tag=""},minecraft_jj_dye_jj_12={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_504={hasPattern=true,label="ME Dense Covered Cable - Gelb",recipe={appliedenergistics2_jj_part_jj_516={need=8,tag=""},minecraft_jj_dye_jj_11={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_505={hasPattern=true,label="ME Dense Covered Cable - Hellgrün",recipe={appliedenergistics2_jj_part_jj_516={need=8,tag=""},minecraft_jj_dye_jj_10={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_506={hasPattern=true,label="ME Dense Covered Cable - Pink",recipe={appliedenergistics2_jj_part_jj_516={need=8,tag=""},minecraft_jj_dye_jj_9={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_507={hasPattern=true,label="ME Dense Covered Cable - Grau",recipe={appliedenergistics2_jj_part_jj_516={need=8,tag=""},minecraft_jj_dye_jj_8={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_508={hasPattern=true,label="ME Dense Covered Cable - Hellgrau",recipe={appliedenergistics2_jj_part_jj_516={need=8,tag=""},minecraft_jj_dye_jj_7={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_509={hasPattern=true,label="ME Dense Covered Cable - Türkis",recipe={appliedenergistics2_jj_part_jj_516={need=8,tag=""},minecraft_jj_dye_jj_6={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_51={hasPattern=true,label="Schlaues ME-Kabel - Blau",recipe={appliedenergistics2_jj_part_jj_56={need=8,tag=""},minecraft_jj_dye_jj_4={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_510={hasPattern=true,label="ME Dense Covered Cable - Violett",recipe={appliedenergistics2_jj_part_jj_516={need=8,tag=""},minecraft_jj_dye_jj_5={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_511={hasPattern=true,label="ME Dense Covered Cable - Blau",recipe={appliedenergistics2_jj_part_jj_516={need=8,tag=""},minecraft_jj_dye_jj_4={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_512={hasPattern=true,label="ME Dense Covered Cable - Braun",recipe={appliedenergistics2_jj_part_jj_516={need=8,tag=""},minecraft_jj_dye_jj_3={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_513={hasPattern=true,label="ME Dense Covered Cable - Grün",recipe={appliedenergistics2_jj_part_jj_516={need=8,tag=""},minecraft_jj_dye_jj_2={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_514={hasPattern=true,label="ME Dense Covered Cable - Rot",recipe={appliedenergistics2_jj_part_jj_516={need=8,tag=""},minecraft_jj_dye_jj_1={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_515={hasPattern=true,label="ME Dense Covered Cable - Schwarz",recipe={appliedenergistics2_jj_part_jj_516={need=8,tag=""},minecraft_jj_dye={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_516={hasPattern=true,label="ME Dense Covered Cable - Fluix",recipe={appliedenergistics2_jj_part_jj_36={need=4,tag=""},appliedenergistics2_jj_part_jj_500={need=1,tag=""},appliedenergistics2_jj_part_jj_501={need=1,tag=""},appliedenergistics2_jj_part_jj_502={need=1,tag=""},appliedenergistics2_jj_part_jj_503={need=1,tag=""},appliedenergistics2_jj_part_jj_504={need=1,tag=""},appliedenergistics2_jj_part_jj_505={need=1,tag=""},appliedenergistics2_jj_part_jj_506={need=1,tag=""},appliedenergistics2_jj_part_jj_507={need=1,tag=""},appliedenergistics2_jj_part_jj_508={need=1,tag=""},appliedenergistics2_jj_part_jj_509={need=1,tag=""},appliedenergistics2_jj_part_jj_510={need=1,tag=""},appliedenergistics2_jj_part_jj_511={need=1,tag=""},appliedenergistics2_jj_part_jj_512={need=1,tag=""},appliedenergistics2_jj_part_jj_513={need=1,tag=""},appliedenergistics2_jj_part_jj_514={need=1,tag=""},appliedenergistics2_jj_part_jj_515={need=1,tag=""},appliedenergistics2_jj_part_jj_516={need=1,tag=""},minecraft_jj_water_bucket={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_52={hasPattern=true,label="Schlaues ME-Kabel - Braun",recipe={appliedenergistics2_jj_part_jj_56={need=8,tag=""},minecraft_jj_dye_jj_3={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_520={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_part_jj_53={hasPattern=true,label="Schlaues ME-Kabel - Grün",recipe={appliedenergistics2_jj_part_jj_56={need=8,tag=""},minecraft_jj_dye_jj_2={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_54={hasPattern=true,label="Schlaues ME-Kabel - Rot",recipe={appliedenergistics2_jj_part_jj_56={need=8,tag=""},minecraft_jj_dye_jj_1={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_55={hasPattern=true,label="Schlaues ME-Kabel - Schwarz",recipe={appliedenergistics2_jj_part_jj_56={need=8,tag=""},minecraft_jj_dye={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_56={hasPattern=true,label="Schlaues ME-Kabel - Fluix",recipe={appliedenergistics2_jj_part_jj_36={need=1,tag=""},appliedenergistics2_jj_part_jj_40={need=1,tag=""},appliedenergistics2_jj_part_jj_41={need=1,tag=""},appliedenergistics2_jj_part_jj_42={need=1,tag=""},appliedenergistics2_jj_part_jj_43={need=1,tag=""},appliedenergistics2_jj_part_jj_44={need=1,tag=""},appliedenergistics2_jj_part_jj_45={need=1,tag=""},appliedenergistics2_jj_part_jj_46={need=1,tag=""},appliedenergistics2_jj_part_jj_47={need=1,tag=""},appliedenergistics2_jj_part_jj_48={need=1,tag=""},appliedenergistics2_jj_part_jj_49={need=1,tag=""},appliedenergistics2_jj_part_jj_50={need=1,tag=""},appliedenergistics2_jj_part_jj_51={need=1,tag=""},appliedenergistics2_jj_part_jj_52={need=1,tag=""},appliedenergistics2_jj_part_jj_53={need=1,tag=""},appliedenergistics2_jj_part_jj_54={need=1,tag=""},appliedenergistics2_jj_part_jj_55={need=1,tag=""},appliedenergistics2_jj_part_jj_56={need=1,tag=""},minecraft_jj_glowstone_dust={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""},minecraft_jj_water_bucket={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_6={hasPattern=true,label="ME-Glaskabel - Pink",recipe={appliedenergistics2_jj_part_jj_16={need=8,tag=""},minecraft_jj_dye_jj_9={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_60={hasPattern=true,label="Dichtes ME-Kabel - Weiß",recipe={appliedenergistics2_jj_part_jj_76={need=8,tag=""},minecraft_jj_dye_jj_15={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_61={hasPattern=true,label="Dichtes ME-Kabel - Orange",recipe={appliedenergistics2_jj_part_jj_76={need=8,tag=""},minecraft_jj_dye_jj_14={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_62={hasPattern=true,label="Dichtes ME-Kabel - Magenta",recipe={appliedenergistics2_jj_part_jj_76={need=8,tag=""},minecraft_jj_dye_jj_13={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_63={hasPattern=true,label="Dichtes ME-Kabel - Hellblau",recipe={appliedenergistics2_jj_part_jj_76={need=8,tag=""},minecraft_jj_dye_jj_12={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_64={hasPattern=true,label="Dichtes ME-Kabel - Gelb",recipe={appliedenergistics2_jj_part_jj_76={need=8,tag=""},minecraft_jj_dye_jj_11={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_65={hasPattern=true,label="Dichtes ME-Kabel - Hellgrün",recipe={appliedenergistics2_jj_part_jj_76={need=8,tag=""},minecraft_jj_dye_jj_10={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_66={hasPattern=true,label="Dichtes ME-Kabel - Pink",recipe={appliedenergistics2_jj_part_jj_76={need=8,tag=""},minecraft_jj_dye_jj_9={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_67={hasPattern=true,label="Dichtes ME-Kabel - Grau",recipe={appliedenergistics2_jj_part_jj_76={need=8,tag=""},minecraft_jj_dye_jj_8={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_68={hasPattern=true,label="Dichtes ME-Kabel - Hellgrau",recipe={appliedenergistics2_jj_part_jj_76={need=8,tag=""},minecraft_jj_dye_jj_7={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_69={hasPattern=true,label="Dichtes ME-Kabel - Türkis",recipe={appliedenergistics2_jj_part_jj_76={need=8,tag=""},minecraft_jj_dye_jj_6={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_7={hasPattern=true,label="ME-Glaskabel - Grau",recipe={appliedenergistics2_jj_part_jj_16={need=8,tag=""},minecraft_jj_dye_jj_8={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_70={hasPattern=true,label="Dichtes ME-Kabel - Violett",recipe={appliedenergistics2_jj_part_jj_76={need=8,tag=""},minecraft_jj_dye_jj_5={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_71={hasPattern=true,label="Dichtes ME-Kabel - Blau",recipe={appliedenergistics2_jj_part_jj_76={need=8,tag=""},minecraft_jj_dye_jj_4={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_72={hasPattern=true,label="Dichtes ME-Kabel - Braun",recipe={appliedenergistics2_jj_part_jj_76={need=8,tag=""},minecraft_jj_dye_jj_3={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_73={hasPattern=true,label="Dichtes ME-Kabel - Grün",recipe={appliedenergistics2_jj_part_jj_76={need=8,tag=""},minecraft_jj_dye_jj_2={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_74={hasPattern=true,label="Dichtes ME-Kabel - Rot",recipe={appliedenergistics2_jj_part_jj_76={need=8,tag=""},minecraft_jj_dye_jj_1={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_75={hasPattern=true,label="Dichtes ME-Kabel - Schwarz",recipe={appliedenergistics2_jj_part_jj_76={need=8,tag=""},minecraft_jj_dye={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_76={hasPattern=true,label="Dichtes ME-Kabel - Fluix",recipe={appliedenergistics2_jj_part_jj_516={need=1,tag=""},minecraft_jj_glowstone_dust={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_8={hasPattern=true,label="ME-Glaskabel - Hellgrau",recipe={appliedenergistics2_jj_part_jj_16={need=8,tag=""},minecraft_jj_dye_jj_7={need=1,tag=""}}},
 appliedenergistics2_jj_part_jj_80={hasPattern=true,label="Schaltbarer ME-Bus",recipe={appliedenergistics2_jj_part_jj_16={need=2,tag=""},minecraft_jj_lever={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""}}},
 appliedenergistics2_jj_part_jj_9={hasPattern=true,label="ME-Glaskabel - Türkis",recipe={appliedenergistics2_jj_part_jj_16={need=8,tag=""},minecraft_jj_dye_jj_6={need=1,tag=""}}},
 appliedenergistics2_jj_portable_cell={hasPattern=true,label="Tragbare Zelle",recipe={appliedenergistics2_jj_chest={need=1,tag=""},appliedenergistics2_jj_energy_cell={need=1,tag=""},appliedenergistics2_jj_material_jj_35={need=1,tag=""}}},
 appliedenergistics2_jj_quantum_link={hasPattern=true,label="ME-Quantentunnelkammer",recipe={appliedenergistics2_jj_material_jj_9={need=4,tag=""},appliedenergistics2_jj_quartz_glass={need=4,tag=""}}},
 appliedenergistics2_jj_quantum_ring={hasPattern=true,label="ME-Quantentunnelring",recipe={appliedenergistics2_jj_energy_cell={need=1,tag=""},appliedenergistics2_jj_material_jj_22={need=2,tag=""},appliedenergistics2_jj_material_jj_24={need=1,tag=""},appliedenergistics2_jj_part_jj_76={need=1,tag=""},minecraft_jj_iron_ingot={need=4,tag=""}}},
 appliedenergistics2_jj_quartz_block={hasPattern=true,label="Certusquarzblock",recipe={appliedenergistics2_jj_material={need=4,tag=""}}},
 appliedenergistics2_jj_quartz_fixture={hasPattern=true,label="Geladene Quarzleuchte",recipe={appliedenergistics2_jj_material_jj_1={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 appliedenergistics2_jj_quartz_glass={hasPattern=true,label="Quarzglas",recipe={appliedenergistics2_jj_material_jj_2={need=5,tag=""},minecraft_jj_glass={need=4,tag=""}}},
 appliedenergistics2_jj_quartz_growth_accelerator={hasPattern=true,label="Kristallwachstumsbeschleuniger",recipe={appliedenergistics2_jj_fluix_block={need=1,tag=""},appliedenergistics2_jj_part_jj_16={need=2,tag=""},appliedenergistics2_jj_quartz_glass={need=2,tag=""},minecraft_jj_iron_ingot={need=4,tag=""}}},
 appliedenergistics2_jj_quartz_ore={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_quartz_pillar={hasPattern=true,label="Certusquarzsäule",recipe={appliedenergistics2_jj_quartz_block={need=2,tag=""}}},
 appliedenergistics2_jj_quartz_pillar_slab={hasPattern=true,label="Certusquartzsäulenstufe",recipe={appliedenergistics2_jj_quartz_pillar={need=3,tag=""}}},
 appliedenergistics2_jj_quartz_pillar_stairs={hasPattern=true,label="Certus Quartz Pillar Stairs",recipe={appliedenergistics2_jj_quartz_pillar={need=6,tag=""}}},
 appliedenergistics2_jj_quartz_slab={hasPattern=true,label="Certusquartzstufe",recipe={appliedenergistics2_jj_quartz_block={need=3,tag=""}}},
 appliedenergistics2_jj_quartz_stairs={hasPattern=true,label="Certus Quartz Stairs",recipe={appliedenergistics2_jj_quartz_block={need=6,tag=""}}},
 appliedenergistics2_jj_quartz_vibrant_glass={hasPattern=true,label="Polarisiertes Quarzglas",recipe={appliedenergistics2_jj_quartz_glass={need=1,tag=""},minecraft_jj_glowstone_dust={need=2,tag=""}}},
 appliedenergistics2_jj_security_station={hasPattern=true,label="ME-Sicherheitskonsole",recipe={appliedenergistics2_jj_chest={need=1,tag=""},appliedenergistics2_jj_material_jj_24={need=1,tag=""},appliedenergistics2_jj_material_jj_37={need=1,tag=""},appliedenergistics2_jj_part_jj_16={need=2,tag=""},minecraft_jj_iron_ingot={need=4,tag=""}}},
 appliedenergistics2_jj_sky_compass={hasPattern=true,label="Meteoritenkompass",recipe={appliedenergistics2_jj_material_jj_1={need=1,tag=""},minecraft_jj_iron_ingot={need=4,tag=""}}},
 appliedenergistics2_jj_sky_stone_block={hasPattern=false,label="",recipe={mysticalagriculture_jj_sky_stone_essence={need=8,tag=""}}},
 appliedenergistics2_jj_sky_stone_brick={hasPattern=true,label="Himmelssteinziegel",recipe={appliedenergistics2_jj_smooth_sky_stone_block={need=4,tag=""}}},
 appliedenergistics2_jj_sky_stone_brick_slab={hasPattern=true,label="Himmelssteinziegelstufe",recipe={appliedenergistics2_jj_sky_stone_brick={need=3,tag=""}}},
 appliedenergistics2_jj_sky_stone_brick_stairs={hasPattern=true,label="Sky Stone Brick Stairs",recipe={appliedenergistics2_jj_sky_stone_brick={need=6,tag=""}}},
 appliedenergistics2_jj_sky_stone_chest={hasPattern=true,label="Himmelssteintruhe",recipe={appliedenergistics2_jj_sky_stone_block={need=8,tag=""}}},
 appliedenergistics2_jj_sky_stone_slab={hasPattern=true,label="Himmelssteinstufe",recipe={appliedenergistics2_jj_sky_stone_block={need=3,tag=""}}},
 appliedenergistics2_jj_sky_stone_small_brick={hasPattern=true,label="Kleine Himmelssteinziegel",recipe={appliedenergistics2_jj_sky_stone_brick={need=4,tag=""}}},
 appliedenergistics2_jj_sky_stone_small_brick_slab={hasPattern=true,label="Himmelssteinkleinziegelstufe",recipe={appliedenergistics2_jj_sky_stone_small_brick={need=3,tag=""}}},
 appliedenergistics2_jj_sky_stone_small_brick_stairs={hasPattern=true,label="Sky Stone Small Brick Stairs",recipe={appliedenergistics2_jj_sky_stone_small_brick={need=6,tag=""}}},
 appliedenergistics2_jj_sky_stone_stairs={hasPattern=true,label="Sky Stone Stairs",recipe={appliedenergistics2_jj_sky_stone_block={need=6,tag=""}}},
 appliedenergistics2_jj_smooth_sky_stone_block={hasPattern=false,label="",recipe={}},
 appliedenergistics2_jj_smooth_sky_stone_chest={hasPattern=true,label="Himmelssteinblocktruhe",recipe={appliedenergistics2_jj_smooth_sky_stone_block={need=8,tag=""}}},
 appliedenergistics2_jj_smooth_sky_stone_slab={hasPattern=true,label="Himmelssteinblockstufe",recipe={appliedenergistics2_jj_smooth_sky_stone_block={need=3,tag=""}}},
 appliedenergistics2_jj_smooth_sky_stone_stairs={hasPattern=true,label="Sky Stone Block Stairs",recipe={appliedenergistics2_jj_smooth_sky_stone_block={need=6,tag=""}}},
 appliedenergistics2_jj_spatial_io_port={hasPattern=true,label="IO-Raumport",recipe={appliedenergistics2_jj_io_port={need=1,tag=""},appliedenergistics2_jj_material_jj_24={need=1,tag=""},appliedenergistics2_jj_part_jj_16={need=2,tag=""},minecraft_jj_glass={need=3,tag=""},minecraft_jj_iron_ingot={need=2,tag=""}}},
 appliedenergistics2_jj_spatial_pylon={hasPattern=true,label="Raumpylon",recipe={appliedenergistics2_jj_material_jj_7={need=1,tag=""},appliedenergistics2_jj_material_jj_8={need=2,tag=""},appliedenergistics2_jj_part_jj_16={need=2,tag=""},appliedenergistics2_jj_quartz_glass={need=4,tag=""}}},
 appliedenergistics2_jj_spatial_storage_cell_128_cubed={hasPattern=true,label="128³-Raumspeicherzelle",recipe={appliedenergistics2_jj_material_jj_34={need=1,tag=""},appliedenergistics2_jj_material_jj_39={need=1,tag=""},appliedenergistics2_jj_quartz_glass={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_redstone={need=3,tag=""}}},
 appliedenergistics2_jj_spatial_storage_cell_16_cubed={hasPattern=true,label="16³-Raumspeicherzelle",recipe={appliedenergistics2_jj_material_jj_33={need=1,tag=""},appliedenergistics2_jj_material_jj_39={need=1,tag=""}}},
 appliedenergistics2_jj_spatial_storage_cell_2_cubed={hasPattern=true,label="2³-Raumspeicherzelle",recipe={appliedenergistics2_jj_material_jj_32={need=1,tag=""},appliedenergistics2_jj_material_jj_39={need=1,tag=""},appliedenergistics2_jj_quartz_glass={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_redstone={need=3,tag=""}}},
 appliedenergistics2_jj_storage_cell_16k={hasPattern=true,label="16k-ME-Speicherzelle",recipe={appliedenergistics2_jj_material_jj_37={need=1,tag=""},appliedenergistics2_jj_material_jj_39={need=1,tag=""},appliedenergistics2_jj_quartz_glass={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_redstone={need=3,tag=""}}},
 appliedenergistics2_jj_storage_cell_1k={hasPattern=true,label="1k-ME-Speicherzelle",recipe={appliedenergistics2_jj_material_jj_35={need=1,tag=""},appliedenergistics2_jj_material_jj_39={need=1,tag=""},appliedenergistics2_jj_quartz_glass={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_redstone={need=3,tag=""}}},
 appliedenergistics2_jj_storage_cell_4k={hasPattern=true,label="4k-ME-Speicherzelle",recipe={appliedenergistics2_jj_material_jj_36={need=1,tag=""},appliedenergistics2_jj_material_jj_39={need=1,tag=""},appliedenergistics2_jj_quartz_glass={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_redstone={need=3,tag=""}}},
 appliedenergistics2_jj_storage_cell_64k={hasPattern=true,label="64k-ME-Speicherzelle",recipe={appliedenergistics2_jj_material_jj_38={need=1,tag=""},appliedenergistics2_jj_material_jj_39={need=1,tag=""},appliedenergistics2_jj_quartz_glass={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_redstone={need=3,tag=""}}},
 appliedenergistics2_jj_tiny_tnt={hasPattern=true,label="Mini-TNT",recipe={appliedenergistics2_jj_material_jj_2={need=2,tag=""},minecraft_jj_gunpowder={need=2,tag=""}}},
 appliedenergistics2_jj_vibration_chamber={hasPattern=true,label="Vibrationskammer",recipe={appliedenergistics2_jj_energy_acceptor={need=1,tag=""},minecraft_jj_furnace={need=1,tag=""},minecraft_jj_iron_ingot={need=7,tag=""}}},
 appliedenergistics2_jj_view_cell={hasPattern=true,label="Sichtzelle",recipe={appliedenergistics2_jj_material={need=1,tag=""},appliedenergistics2_jj_material_jj_39={need=1,tag=""}}},
 appliedenergistics2_jj_wireless_access_point={hasPattern=true,label="Drahtloser ME-Zugangspunkt",recipe={appliedenergistics2_jj_material_jj_23={need=1,tag=""},appliedenergistics2_jj_material_jj_41={need=1,tag=""},appliedenergistics2_jj_part_jj_16={need=1,tag=""}}},
 appliedenergistics2_jj_wireless_terminal={hasPattern=true,label="Drahtlose Zugangskonsole",recipe={appliedenergistics2_jj_dense_energy_cell={need=1,tag=""},appliedenergistics2_jj_material_jj_41={need=1,tag=""},appliedenergistics2_jj_part_jj_380={need=1,tag=""}}},
 integrateddynamics_jj_block_liquid_chorus={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_block_menril_resin={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_cable={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_coal_generator={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_creative_energy_battery={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_crystalized_chorus_block={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_crystalized_chorus_block_stairs={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_crystalized_chorus_brick={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_crystalized_chorus_brick_stairs={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_crystalized_chorus_chunk={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_crystalized_menril_block={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_crystalized_menril_block_stairs={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_crystalized_menril_brick={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_crystalized_menril_brick_stairs={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_crystalized_menril_chunk={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_delay={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_drying_basin={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_energy_battery={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_facade={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_invisible_light={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_labeller={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_logic_director={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_logic_programmer={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_materializer={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_mechanical_drying_basin={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_mechanical_squeezer={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_menril_berries={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_menril_door={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_menril_leaves={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_menril_log={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_menril_log_filled={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_menril_planks={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_menril_planks_stairs={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_menril_sapling={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_menril_torch={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_menril_torch_stone={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_on_the_dynamics_of_integration={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_part_audio_reader_item={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_part_audio_writer_item={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_part_block_reader_item={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_part_connector_mono_directional_item={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_part_connector_omni_directional_item={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_part_display_panel_item={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_part_dynamic_light_panel_item={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_part_effect_writer_item={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_part_entity_reader_item={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_part_entity_writer_item={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_part_extradimensional_reader_item={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_part_fluid_reader_item={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_part_inventory_reader_item={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_part_inventory_writer_item={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_part_machine_reader_item={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_part_machine_writer_item={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_part_network_reader_item={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_part_redstone_reader_item={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_part_redstone_writer_item={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_part_static_light_panel_item={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_part_world_reader_item={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_portable_logic_programmer={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_proxy={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_squeezer={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_variable={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_variable_transformer={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_variable_transformer_jj_1={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_variablestore={hasPattern=false,label="",recipe={}},
 integrateddynamics_jj_wrench={hasPattern=false,label="",recipe={}},
 integratedtunnels_jj_part_exporter_energy_item={hasPattern=false,label="",recipe={}},
 integratedtunnels_jj_part_exporter_fluid_item={hasPattern=false,label="",recipe={}},
 integratedtunnels_jj_part_exporter_item_item={hasPattern=false,label="",recipe={}},
 integratedtunnels_jj_part_exporter_world_block_item={hasPattern=false,label="",recipe={}},
 integratedtunnels_jj_part_exporter_world_energy_item={hasPattern=false,label="",recipe={}},
 integratedtunnels_jj_part_exporter_world_fluid_item={hasPattern=false,label="",recipe={}},
 integratedtunnels_jj_part_exporter_world_item_item={hasPattern=false,label="",recipe={}},
 integratedtunnels_jj_part_importer_energy_item={hasPattern=false,label="",recipe={}},
 integratedtunnels_jj_part_importer_fluid_item={hasPattern=false,label="",recipe={}},
 integratedtunnels_jj_part_importer_item_item={hasPattern=false,label="",recipe={}},
 integratedtunnels_jj_part_importer_world_block_item={hasPattern=false,label="",recipe={}},
 integratedtunnels_jj_part_importer_world_energy_item={hasPattern=false,label="",recipe={}},
 integratedtunnels_jj_part_importer_world_fluid_item={hasPattern=false,label="",recipe={}},
 integratedtunnels_jj_part_importer_world_item_item={hasPattern=false,label="",recipe={}},
 integratedtunnels_jj_part_interface_energy_item={hasPattern=false,label="",recipe={}},
 integratedtunnels_jj_part_interface_fluid_item={hasPattern=false,label="",recipe={}},
 integratedtunnels_jj_part_interface_item_item={hasPattern=false,label="",recipe={}},
 integratedtunnels_jj_part_player_simulator_item={hasPattern=false,label="",recipe={}}
 }