return {
 binniecore_jj_cylinder={hasPattern=true,label="Empty Cylinder",recipe={minecraft_jj_glass_pane={need=4,tag=""}}},
 binniecore_jj_cylinder_jj_1={hasPattern=false,label="",recipe={}},
 binniecore_jj_field_kit={hasPattern=false,label="",recipe={}},
 binniecore_jj_genesis={hasPattern=false,label="",recipe={}},
 binniecore_jj_glass={hasPattern=true,label="Empty Bottle",recipe={minecraft_jj_glass_bottle={need=1,tag=""}}},
 binniecore_jj_glass_jj_1={hasPattern=false,label="",recipe={}},
 binniecore_jj_storage={hasPattern=true,label="Compartment",recipe={minecraft_jj_book={need=1,tag=""},minecraft_jj_chest={need=4,tag=""},minecraft_jj_stone_button={need=4,tag=""}}},
 binniecore_jj_storage_jj_1={hasPattern=true,label="Copper Compartment",recipe={binniecore_jj_storage={need=1,tag=""},forestry_jj_gear_copper={need=4,tag=""},minecraft_jj_stone_button={need=4,tag=""},thermalfoundation_jj_material_jj_256={need=4,tag=""}}},
 binniecore_jj_storage_jj_2={hasPattern=true,label="Bronze Compartment",recipe={binniecore_jj_storage_jj_1={need=1,tag=""},forestry_jj_gear_bronze={need=4,tag=""},minecraft_jj_gold_nugget={need=4,tag=""},thermalfoundation_jj_material_jj_291={need=4,tag=""}}},
 binniecore_jj_storage_jj_3={hasPattern=true,label="Iron Compartment",recipe={basemetals_jj_iron_gear={need=4,tag=""},binniecore_jj_storage_jj_1={need=1,tag=""},minecraft_jj_gold_nugget={need=4,tag=""},thermalfoundation_jj_material_jj_24={need=4,tag=""}}},
 binniecore_jj_storage_jj_4={hasPattern=true,label="Gold Compartment",recipe={basemetals_jj_gold_gear={need=4,tag=""},binniecore_jj_storage_jj_3={need=1,tag=""},minecraft_jj_emerald={need=4,tag=""},thermalfoundation_jj_material_jj_25={need=4,tag=""}}},
 binniecore_jj_storage_jj_5={hasPattern=true,label="Diamond Compartment",recipe={binniecore_jj_storage_jj_4={need=1,tag=""},minecraft_jj_diamond={need=4,tag=""},minecraft_jj_emerald={need=4,tag=""}}},
 extratrees_jj_binnie_vv_beer_vv_ale={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_beer_vv_corn={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_beer_vv_lager={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_beer_vv_rye={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_beer_vv_stout={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_beer_vv_wheat={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_brandy_vv_apple={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_brandy_vv_apricot={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_brandy_vv_cherry={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_brandy_vv_citrus={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_brandy_vv_elderberry={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_brandy_vv_fruit={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_brandy_vv_grape={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_brandy_vv_pear={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_brandy_vv_plum={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_cider_vv_apple={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_cider_vv_peach={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_ciderpear={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_fermented_vv_potatoes={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_juice={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_juice_vv_apple={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_juice_vv_apricot={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_juice_vv_banana={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_juice_vv_carrot={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_juice_vv_cherry={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_juice_vv_cranberry={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_juice_vv_elderberry={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_juice_vv_grapefruit={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_juice_vv_lemon={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_juice_vv_lime={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_juice_vv_olive={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_juice_vv_orange={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_juice_vv_peach={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_juice_vv_pear={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_juice_vv_pineapple={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_juice_vv_plum={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_juice_vv_red_vv_grape={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_juice_vv_tomato={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_juice_vv_white_vv_grape={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_latex={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_liqueur_vv_almond={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_liqueur_vv_anise={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_liqueur_vv_banana={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_liqueur_vv_blackberry={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_liqueur_vv_blackcurrant={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_liqueur_vv_cherry={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_liqueur_vv_chocolate={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_liqueur_vv_cinnamon={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_liqueur_vv_coffee={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_liqueur_vv_hazelnut={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_liqueur_vv_herbal={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_liqueur_vv_lemon={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_liqueur_vv_melon={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_liqueur_vv_mint={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_liqueur_vv_orange={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_liqueur_vv_peach={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_liqueur_vv_raspberry={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_liquor_vv_apple={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_liquor_vv_apricot={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_liquor_vv_cherry={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_liquor_vv_elderberry={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_liquor_vv_fruit={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_liquor_vv_pear={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_mash_vv_corn={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_mash_vv_grain={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_mash_vv_rye={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_mash_vv_wheat={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_resin={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_rum_vv_dark={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_rum_vv_white={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_sap={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_spirit_vv_gin={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_spirit_vv_neutral={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_spirit_vv_sugarcane={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_tequila={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_turpentine={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_vodka={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_whiskey={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_whiskey_vv_corn={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_whiskey_vv_rye={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_whiskey_vv_wheat={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_wine_vv_agave={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_wine_vv_apricot={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_wine_vv_banana={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_wine_vv_carrot={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_wine_vv_cherry={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_wine_vv_citrus={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_wine_vv_cranberry={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_wine_vv_elderberry={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_wine_vv_fortified={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_wine_vv_pineapple={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_wine_vv_plum={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_wine_vv_red={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_wine_vv_sparkling={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_wine_vv_tomato={hasPattern=false,label="",recipe={}},
 extratrees_jj_binnie_vv_wine_vv_white={hasPattern=false,label="",recipe={}},
 extratrees_jj_carpentry_jj_16387={hasPattern=false,label="",recipe={}},
 extratrees_jj_carpentrypanel={hasPattern=false,label="",recipe={}},
 extratrees_jj_databaselepi={hasPattern=false,label="",recipe={}},
 extratrees_jj_databaselepi_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_databasetree={hasPattern=false,label="",recipe={}},
 extratrees_jj_databasetree_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_doors_vv_alder={hasPattern=true,label="Alderholztür",recipe={extratrees_jj_planks_vv_0_jj_7={need=6,tag=""}}},
 extratrees_jj_doors_vv_apple={hasPattern=true,label="Appleholztür",recipe={extratrees_jj_planks_vv_0={need=6,tag=""}}},
 extratrees_jj_doors_vv_ash={hasPattern=true,label="Ashholztür",recipe={extratrees_jj_planks_vv_0_jj_6={need=6,tag=""}}},
 extratrees_jj_doors_vv_banana={hasPattern=true,label="Bananaholztür",recipe={extratrees_jj_planks_vv_0_jj_10={need=6,tag=""}}},
 extratrees_jj_doors_vv_beech={hasPattern=true,label="Beechholztür",recipe={extratrees_jj_planks_vv_0_jj_8={need=6,tag=""}}},
 extratrees_jj_doors_vv_box={hasPattern=true,label="Boxholztür",recipe={extratrees_jj_planks_vv_2_jj_1={need=6,tag=""}}},
 extratrees_jj_doors_vv_brazilwood={hasPattern=true,label="Brazilwoodholztür",recipe={extratrees_jj_planks_vv_1_jj_10={need=6,tag=""}}},
 extratrees_jj_doors_vv_butternut={hasPattern=true,label="Butternutholztür",recipe={extratrees_jj_planks_vv_0_jj_2={need=6,tag=""}}},
 extratrees_jj_doors_vv_cedar={hasPattern=true,label="Cedarholztür",recipe={extratrees_jj_planks_vv_1_jj_4={need=6,tag=""}}},
 extratrees_jj_doors_vv_cypress={hasPattern=true,label="Cypressholztür",recipe={extratrees_jj_planks_vv_0_jj_12={need=6,tag=""}}},
 extratrees_jj_doors_vv_elder={hasPattern=true,label="Elderholztür",recipe={extratrees_jj_planks_vv_1_jj_1={need=6,tag=""}}},
 extratrees_jj_doors_vv_elm={hasPattern=true,label="Elmholztür",recipe={extratrees_jj_planks_vv_1={need=6,tag=""}}},
 extratrees_jj_doors_vv_eucalyptus={hasPattern=true,label="Eucalyptusholztür",recipe={extratrees_jj_planks_vv_2={need=6,tag=""}}},
 extratrees_jj_doors_vv_fig={hasPattern=true,label="Figholztür",recipe={extratrees_jj_planks_vv_0_jj_1={need=6,tag=""}}},
 extratrees_jj_doors_vv_fir={hasPattern=true,label="Firholztür",recipe={extratrees_jj_planks_vv_0_jj_13={need=6,tag=""}}},
 extratrees_jj_doors_vv_gingko={hasPattern=true,label="Gingkoholztür",recipe={extratrees_jj_planks_vv_1_jj_15={need=6,tag=""}}},
 extratrees_jj_doors_vv_hawthorn={hasPattern=true,label="Hawthornholztür",recipe={extratrees_jj_planks_vv_0_jj_9={need=6,tag=""}}},
 extratrees_jj_doors_vv_hazel={hasPattern=true,label="Hazelholztür",recipe={extratrees_jj_planks_vv_0_jj_14={need=6,tag=""}}},
 extratrees_jj_doors_vv_hemlock={hasPattern=true,label="Hemlockholztür",recipe={extratrees_jj_planks_vv_0_jj_5={need=6,tag=""}}},
 extratrees_jj_doors_vv_hickory={hasPattern=true,label="Hickoryholztür",recipe={extratrees_jj_planks_vv_0_jj_15={need=6,tag=""}}},
 extratrees_jj_doors_vv_holly={hasPattern=true,label="Hollyholztür",recipe={extratrees_jj_planks_vv_1_jj_2={need=6,tag=""}}},
 extratrees_jj_doors_vv_hornbeam={hasPattern=true,label="Hornbeamholztür",recipe={extratrees_jj_planks_vv_1_jj_3={need=6,tag=""}}},
 extratrees_jj_doors_vv_iroko={hasPattern=true,label="Irokoholztür",recipe={extratrees_jj_planks_vv_1_jj_14={need=6,tag=""}}},
 extratrees_jj_doors_vv_locust={hasPattern=true,label="Locustholztür",recipe={extratrees_jj_planks_vv_1_jj_7={need=6,tag=""}}},
 extratrees_jj_doors_vv_logwood={hasPattern=true,label="Logwoodholztür",recipe={extratrees_jj_planks_vv_1_jj_11={need=6,tag=""}}},
 extratrees_jj_doors_vv_maclura={hasPattern=true,label="Macluraholztür",recipe={extratrees_jj_planks_vv_1_jj_9={need=6,tag=""}}},
 extratrees_jj_doors_vv_olive={hasPattern=true,label="Oliveholztür",recipe={extratrees_jj_planks_vv_1_jj_5={need=6,tag=""}}},
 extratrees_jj_doors_vv_pear={hasPattern=true,label="Pearholztür",recipe={extratrees_jj_planks_vv_1_jj_8={need=6,tag=""}}},
 extratrees_jj_doors_vv_pinkivory={hasPattern=true,label="Pink Ivoryholztür",recipe={extratrees_jj_planks_vv_2_jj_3={need=6,tag=""}}},
 extratrees_jj_doors_vv_purpleheart={hasPattern=true,label="Purpleheartholztür",recipe={extratrees_jj_planks_vv_1_jj_13={need=6,tag=""}}},
 extratrees_jj_doors_vv_rosewood={hasPattern=true,label="Rosewoodholztür",recipe={extratrees_jj_planks_vv_1_jj_12={need=6,tag=""}}},
 extratrees_jj_doors_vv_rowan={hasPattern=true,label="Rowanholztür",recipe={extratrees_jj_planks_vv_0_jj_4={need=6,tag=""}}},
 extratrees_jj_doors_vv_sweetgum={hasPattern=true,label="Sweetgumholztür",recipe={extratrees_jj_planks_vv_1_jj_6={need=6,tag=""}}},
 extratrees_jj_doors_vv_syzgium={hasPattern=true,label="Syzgiumholztür",recipe={extratrees_jj_planks_vv_2_jj_2={need=6,tag=""}}},
 extratrees_jj_doors_vv_whitebeam={hasPattern=true,label="Whitebeamholztür",recipe={extratrees_jj_planks_vv_0_jj_3={need=6,tag=""}}},
 extratrees_jj_doors_vv_yew={hasPattern=true,label="Yewholztür",recipe={extratrees_jj_planks_vv_0_jj_11={need=6,tag=""}}},
 extratrees_jj_drink={hasPattern=false,label="",recipe={}},
 extratrees_jj_durable_hammer={hasPattern=true,label="Master Carpentry Hammer",recipe={minecraft_jj_gold_ingot={need=1,tag=""},minecraft_jj_obsidian={need=2,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_alder={hasPattern=true,label="Alderholzzauntor",recipe={extratrees_jj_planks_vv_0_jj_7={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_apple={hasPattern=true,label="Appleholzzauntor",recipe={extratrees_jj_planks_vv_0={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_ash={hasPattern=true,label="Ashholzzauntor",recipe={extratrees_jj_planks_vv_0_jj_6={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_banana={hasPattern=true,label="Bananaholzzauntor",recipe={extratrees_jj_planks_vv_0_jj_10={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_beech={hasPattern=true,label="Beechholzzauntor",recipe={extratrees_jj_planks_vv_0_jj_8={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_box={hasPattern=true,label="Boxholzzauntor",recipe={extratrees_jj_planks_vv_2_jj_1={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_brazilwood={hasPattern=true,label="Brazilwoodholzzauntor",recipe={extratrees_jj_planks_vv_1_jj_10={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_butternut={hasPattern=true,label="Butternutholzzauntor",recipe={extratrees_jj_planks_vv_0_jj_2={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_cedar={hasPattern=true,label="Cedarholzzauntor",recipe={extratrees_jj_planks_vv_1_jj_4={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_cypress={hasPattern=true,label="Cypressholzzauntor",recipe={extratrees_jj_planks_vv_0_jj_12={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_elder={hasPattern=true,label="Elderholzzauntor",recipe={extratrees_jj_planks_vv_1_jj_1={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_elm={hasPattern=true,label="Elmholzzauntor",recipe={extratrees_jj_planks_vv_1={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_eucalyptus={hasPattern=true,label="Eucalyptusholzzauntor",recipe={extratrees_jj_planks_vv_2={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fig={hasPattern=true,label="Figholzzauntor",recipe={extratrees_jj_planks_vv_0_jj_1={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fir={hasPattern=true,label="Firholzzauntor",recipe={extratrees_jj_planks_vv_0_jj_13={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_alder={hasPattern=true,label="Alderholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_7={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_apple={hasPattern=true,label="Appleholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_ash={hasPattern=true,label="Ashholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_6={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_banana={hasPattern=true,label="Bananaholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_10={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_beech={hasPattern=true,label="Beechholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_8={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_box={hasPattern=true,label="Boxholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_2_jj_1={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_brazilwood={hasPattern=true,label="Brazilwoodholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_10={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_butternut={hasPattern=true,label="Butternutholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_2={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_cedar={hasPattern=true,label="Cedarholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_4={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_cypress={hasPattern=true,label="Cypressholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_12={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_elder={hasPattern=true,label="Elderholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_1={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_elm={hasPattern=true,label="Elmholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_eucalyptus={hasPattern=true,label="Eucalyptusholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_2={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_fig={hasPattern=true,label="Figholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_1={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_fir={hasPattern=true,label="Firholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_13={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_gingko={hasPattern=true,label="Gingkoholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_15={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_hawthorn={hasPattern=true,label="Hawthornholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_9={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_hazel={hasPattern=true,label="Hazelholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_14={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_hemlock={hasPattern=true,label="Hemlockholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_5={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_hickory={hasPattern=true,label="Hickoryholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_15={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_holly={hasPattern=true,label="Hollyholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_2={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_hornbeam={hasPattern=true,label="Hornbeamholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_3={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_iroko={hasPattern=true,label="Irokoholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_14={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_locust={hasPattern=true,label="Locustholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_7={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_logwood={hasPattern=true,label="Logwoodholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_11={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_maclura={hasPattern=true,label="Macluraholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_9={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_olive={hasPattern=true,label="Oliveholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_5={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_pear={hasPattern=true,label="Pearholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_8={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_pinkivory={hasPattern=true,label="Pink Ivoryholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_2_jj_3={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_purpleheart={hasPattern=true,label="Purpleheartholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_13={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_rosewood={hasPattern=true,label="Rosewoodholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_12={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_rowan={hasPattern=true,label="Rowanholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_4={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_sweetgum={hasPattern=true,label="Sweetgumholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_6={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_syzgium={hasPattern=true,label="Syzgiumholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_2_jj_2={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_whitebeam={hasPattern=true,label="Whitebeamholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_3={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_fireproof_vv_yew={hasPattern=true,label="Yewholzzauntor (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_11={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_gingko={hasPattern=true,label="Gingkoholzzauntor",recipe={extratrees_jj_planks_vv_1_jj_15={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_hawthorn={hasPattern=true,label="Hawthornholzzauntor",recipe={extratrees_jj_planks_vv_0_jj_9={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_hazel={hasPattern=true,label="Hazelholzzauntor",recipe={extratrees_jj_planks_vv_0_jj_14={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_hemlock={hasPattern=true,label="Hemlockholzzauntor",recipe={extratrees_jj_planks_vv_0_jj_5={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_hickory={hasPattern=true,label="Hickoryholzzauntor",recipe={extratrees_jj_planks_vv_0_jj_15={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_holly={hasPattern=true,label="Hollyholzzauntor",recipe={extratrees_jj_planks_vv_1_jj_2={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_hornbeam={hasPattern=true,label="Hornbeamholzzauntor",recipe={extratrees_jj_planks_vv_1_jj_3={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_iroko={hasPattern=true,label="Irokoholzzauntor",recipe={extratrees_jj_planks_vv_1_jj_14={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_locust={hasPattern=true,label="Locustholzzauntor",recipe={extratrees_jj_planks_vv_1_jj_7={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_logwood={hasPattern=true,label="Logwoodholzzauntor",recipe={extratrees_jj_planks_vv_1_jj_11={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_maclura={hasPattern=true,label="Macluraholzzauntor",recipe={extratrees_jj_planks_vv_1_jj_9={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_olive={hasPattern=true,label="Oliveholzzauntor",recipe={extratrees_jj_planks_vv_1_jj_5={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_pear={hasPattern=true,label="Pearholzzauntor",recipe={extratrees_jj_planks_vv_1_jj_8={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_pinkivory={hasPattern=true,label="Pink Ivoryholzzauntor",recipe={extratrees_jj_planks_vv_2_jj_3={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_purpleheart={hasPattern=true,label="Purpleheartholzzauntor",recipe={extratrees_jj_planks_vv_1_jj_13={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_rosewood={hasPattern=true,label="Rosewoodholzzauntor",recipe={extratrees_jj_planks_vv_1_jj_12={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_rowan={hasPattern=true,label="Rowanholzzauntor",recipe={extratrees_jj_planks_vv_0_jj_4={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_sweetgum={hasPattern=true,label="Sweetgumholzzauntor",recipe={extratrees_jj_planks_vv_1_jj_6={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_syzgium={hasPattern=true,label="Syzgiumholzzauntor",recipe={extratrees_jj_planks_vv_2_jj_2={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_whitebeam={hasPattern=true,label="Whitebeamholzzauntor",recipe={extratrees_jj_planks_vv_0_jj_3={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fence_vv_gates_vv_yew={hasPattern=true,label="Yewholzzauntor",recipe={extratrees_jj_planks_vv_0_jj_11={need=2,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_fences_vv_0={hasPattern=true,label="Appleholzzaun",recipe={extratrees_jj_planks_vv_0={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_0_jj_1={hasPattern=true,label="Figholzzaun",recipe={extratrees_jj_planks_vv_0_jj_1={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_0_jj_10={hasPattern=true,label="Bananaholzzaun",recipe={extratrees_jj_planks_vv_0_jj_10={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_0_jj_11={hasPattern=true,label="Yewholzzaun",recipe={extratrees_jj_planks_vv_0_jj_11={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_0_jj_12={hasPattern=true,label="Cypressholzzaun",recipe={extratrees_jj_planks_vv_0_jj_12={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_0_jj_13={hasPattern=true,label="Firholzzaun",recipe={extratrees_jj_planks_vv_0_jj_13={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_0_jj_14={hasPattern=true,label="Hazelholzzaun",recipe={extratrees_jj_planks_vv_0_jj_14={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_0_jj_15={hasPattern=true,label="Hickoryholzzaun",recipe={extratrees_jj_planks_vv_0_jj_15={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_0_jj_2={hasPattern=true,label="Butternutholzzaun",recipe={extratrees_jj_planks_vv_0_jj_2={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_0_jj_3={hasPattern=true,label="Whitebeamholzzaun",recipe={extratrees_jj_planks_vv_0_jj_3={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_0_jj_4={hasPattern=true,label="Rowanholzzaun",recipe={extratrees_jj_planks_vv_0_jj_4={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_0_jj_5={hasPattern=true,label="Hemlockholzzaun",recipe={extratrees_jj_planks_vv_0_jj_5={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_0_jj_6={hasPattern=true,label="Ashholzzaun",recipe={extratrees_jj_planks_vv_0_jj_6={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_0_jj_7={hasPattern=true,label="Alderholzzaun",recipe={extratrees_jj_planks_vv_0_jj_7={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_0_jj_8={hasPattern=true,label="Beechholzzaun",recipe={extratrees_jj_planks_vv_0_jj_8={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_0_jj_9={hasPattern=true,label="Hawthornholzzaun",recipe={extratrees_jj_planks_vv_0_jj_9={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_1={hasPattern=true,label="Elmholzzaun",recipe={extratrees_jj_planks_vv_1={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_1_jj_1={hasPattern=true,label="Elderholzzaun",recipe={extratrees_jj_planks_vv_1_jj_1={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_1_jj_10={hasPattern=true,label="Brazilwoodholzzaun",recipe={extratrees_jj_planks_vv_1_jj_10={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_1_jj_11={hasPattern=true,label="Logwoodholzzaun",recipe={extratrees_jj_planks_vv_1_jj_11={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_1_jj_12={hasPattern=true,label="Rosewoodholzzaun",recipe={extratrees_jj_planks_vv_1_jj_12={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_1_jj_13={hasPattern=true,label="Purpleheartholzzaun",recipe={extratrees_jj_planks_vv_1_jj_13={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_1_jj_14={hasPattern=true,label="Irokoholzzaun",recipe={extratrees_jj_planks_vv_1_jj_14={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_1_jj_15={hasPattern=true,label="Gingkoholzzaun",recipe={extratrees_jj_planks_vv_1_jj_15={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_1_jj_2={hasPattern=true,label="Hollyholzzaun",recipe={extratrees_jj_planks_vv_1_jj_2={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_1_jj_3={hasPattern=true,label="Hornbeamholzzaun",recipe={extratrees_jj_planks_vv_1_jj_3={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_1_jj_4={hasPattern=true,label="Cedarholzzaun",recipe={extratrees_jj_planks_vv_1_jj_4={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_1_jj_5={hasPattern=true,label="Oliveholzzaun",recipe={extratrees_jj_planks_vv_1_jj_5={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_1_jj_6={hasPattern=true,label="Sweetgumholzzaun",recipe={extratrees_jj_planks_vv_1_jj_6={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_1_jj_7={hasPattern=true,label="Locustholzzaun",recipe={extratrees_jj_planks_vv_1_jj_7={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_1_jj_8={hasPattern=true,label="Pearholzzaun",recipe={extratrees_jj_planks_vv_1_jj_8={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_1_jj_9={hasPattern=true,label="Macluraholzzaun",recipe={extratrees_jj_planks_vv_1_jj_9={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_2={hasPattern=true,label="Eucalyptusholzzaun",recipe={extratrees_jj_planks_vv_2={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_2_jj_1={hasPattern=true,label="Boxholzzaun",recipe={extratrees_jj_planks_vv_2_jj_1={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_2_jj_2={hasPattern=true,label="Syzgiumholzzaun",recipe={extratrees_jj_planks_vv_2_jj_2={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_2_jj_3={hasPattern=true,label="Pink Ivoryholzzaun",recipe={extratrees_jj_planks_vv_2_jj_3={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_0={hasPattern=true,label="Appleholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_0_jj_1={hasPattern=true,label="Figholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_1={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_0_jj_10={hasPattern=true,label="Bananaholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_10={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_0_jj_11={hasPattern=true,label="Yewholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_11={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_0_jj_12={hasPattern=true,label="Cypressholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_12={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_0_jj_13={hasPattern=true,label="Firholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_13={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_0_jj_14={hasPattern=true,label="Hazelholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_14={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_0_jj_15={hasPattern=true,label="Hickoryholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_15={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_0_jj_2={hasPattern=true,label="Butternutholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_2={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_0_jj_3={hasPattern=true,label="Whitebeamholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_3={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_0_jj_4={hasPattern=true,label="Rowanholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_4={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_0_jj_5={hasPattern=true,label="Hemlockholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_5={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_0_jj_6={hasPattern=true,label="Ashholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_6={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_0_jj_7={hasPattern=true,label="Alderholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_7={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_0_jj_8={hasPattern=true,label="Beechholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_8={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_0_jj_9={hasPattern=true,label="Hawthornholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_9={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_1={hasPattern=true,label="Elmholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_1_jj_1={hasPattern=true,label="Elderholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_1={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_1_jj_10={hasPattern=true,label="Brazilwoodholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_10={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_1_jj_11={hasPattern=true,label="Logwoodholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_11={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_1_jj_12={hasPattern=true,label="Rosewoodholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_12={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_1_jj_13={hasPattern=true,label="Purpleheartholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_13={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_1_jj_14={hasPattern=true,label="Irokoholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_14={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_1_jj_15={hasPattern=true,label="Gingkoholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_15={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_1_jj_2={hasPattern=true,label="Hollyholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_2={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_1_jj_3={hasPattern=true,label="Hornbeamholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_3={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_1_jj_4={hasPattern=true,label="Cedarholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_4={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_1_jj_5={hasPattern=true,label="Oliveholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_5={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_1_jj_6={hasPattern=true,label="Sweetgumholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_6={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_1_jj_7={hasPattern=true,label="Locustholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_7={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_1_jj_8={hasPattern=true,label="Pearholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_8={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_1_jj_9={hasPattern=true,label="Macluraholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_9={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_2={hasPattern=true,label="Eucalyptusholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_2={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_2_jj_1={hasPattern=true,label="Boxholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_2_jj_1={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_2_jj_2={hasPattern=true,label="Syzgiumholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_2_jj_2={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_fences_vv_fireproof_vv_2_jj_3={hasPattern=true,label="Pink Ivoryholzzaun (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_2_jj_3={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_food={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_10={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_11={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_12={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_13={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_14={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_15={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_16={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_17={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_18={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_19={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_20={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_21={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_22={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_23={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_24={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_25={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_26={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_27={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_28={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_29={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_30={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_31={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_32={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_33={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_34={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_35={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_36={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_37={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_38={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_39={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_4={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_40={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_41={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_42={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_43={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_44={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_45={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_46={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_47={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_48={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_49={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_5={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_50={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_51={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_52={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_53={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_54={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_55={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_56={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_57={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_58={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_59={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_6={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_7={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_8={hasPattern=false,label="",recipe={}},
 extratrees_jj_food_jj_9={hasPattern=false,label="",recipe={}},
 extratrees_jj_hammer={hasPattern=true,label="Carpentry Hammer",recipe={minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_planks={need=2,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 extratrees_jj_hops={hasPattern=true,label="Hops",recipe={conquest_jj_hops={need=1,tag=""}}},
 extratrees_jj_leaves_vv_decorative_vv_0={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_0_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_0_jj_10={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_0_jj_11={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_0_jj_12={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_0_jj_13={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_0_jj_14={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_0_jj_15={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_0_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_0_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_0_jj_4={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_0_jj_5={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_0_jj_6={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_0_jj_7={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_0_jj_8={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_0_jj_9={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_1_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_1_jj_10={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_1_jj_11={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_1_jj_12={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_1_jj_13={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_1_jj_14={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_1_jj_15={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_1_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_1_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_1_jj_4={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_1_jj_5={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_1_jj_6={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_1_jj_7={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_1_jj_8={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_1_jj_9={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_2_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_2_jj_10={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_2_jj_11={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_2_jj_12={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_2_jj_13={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_2_jj_14={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_2_jj_15={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_2_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_2_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_2_jj_4={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_2_jj_5={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_2_jj_6={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_2_jj_7={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_2_jj_8={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_2_jj_9={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_3_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_3_jj_10={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_3_jj_11={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_3_jj_12={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_3_jj_13={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_3_jj_14={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_3_jj_15={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_3_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_3_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_3_jj_4={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_3_jj_5={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_3_jj_6={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_3_jj_7={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_3_jj_8={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_3_jj_9={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_4={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_4_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_4_jj_10={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_4_jj_11={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_4_jj_12={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_4_jj_13={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_4_jj_14={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_4_jj_15={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_4_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_4_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_4_jj_4={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_4_jj_5={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_4_jj_6={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_4_jj_7={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_4_jj_8={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_4_jj_9={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_5={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_5_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_5_jj_10={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_5_jj_11={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_5_jj_12={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_5_jj_13={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_5_jj_14={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_5_jj_15={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_5_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_5_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_5_jj_4={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_5_jj_5={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_5_jj_6={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_5_jj_7={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_5_jj_8={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_5_jj_9={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_decorative_vv_6={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_0={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_10={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_11={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_12={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_13={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_14={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_15={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_16={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_17={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_18={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_19={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_20={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_21={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_22={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_23={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_24={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_4={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_5={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_6={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_7={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_8={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_9={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_fruit_vv_0={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_fruit_vv_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_fruit_vv_10={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_fruit_vv_11={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_fruit_vv_12={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_fruit_vv_13={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_fruit_vv_14={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_fruit_vv_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_fruit_vv_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_fruit_vv_4={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_fruit_vv_5={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_fruit_vv_6={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_fruit_vv_7={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_fruit_vv_8={hasPattern=false,label="",recipe={}},
 extratrees_jj_leaves_vv_default_vv_fruit_vv_9={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_0={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_0_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_0_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_0_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_1_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_1_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_1_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_2_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_2_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_2_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_3_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_3_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_3_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_4={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_4_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_4_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_4_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_5={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_5_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_5_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_5_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_6={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_6_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_6_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_6_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_7={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_7_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_7_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_7_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_8={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_8_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_8_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_8_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_9={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_9_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_9_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_9_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_0={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_0_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_0_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_0_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_1_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_1_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_1_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_2_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_2_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_2_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_3_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_3_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_3_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_4={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_4_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_4_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_4_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_5={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_5_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_5_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_5_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_6={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_6_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_6_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_6_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_7={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_7_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_7_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_7_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_8={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_8_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_8_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_8_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_9={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_9_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_9_jj_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_logs_vv_fireproof_vv_9_jj_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_machine={hasPattern=false,label="",recipe={extratrees_jj_misc_jj_3={need=4,tag=""},forestry_jj_gear_bronze={need=1,tag=""},forestry_jj_sturdy_machine={need=1,tag=""},minecraft_jj_glass={need=2,tag=""},minecraft_jj_iron_axe={need=1,tag=""}}},
 extratrees_jj_machine_jj_1={hasPattern=false,label="",recipe={extratrees_jj_misc_jj_3={need=3,tag=""},forestry_jj_impregnated_casing={need=1,tag=""},minecraft_jj_glass={need=3,tag=""},minecraft_jj_planks={need=2,tag=""}}},
 extratrees_jj_machine_jj_2={hasPattern=false,label="",recipe={extratrees_jj_misc_jj_3={need=3,tag=""},forestry_jj_impregnated_casing={need=1,tag=""},minecraft_jj_glass={need=3,tag=""},minecraft_jj_wooden_slab={need=2,tag=""}}},
 extratrees_jj_machine_jj_4={hasPattern=true,label="Fruit Press",recipe={forestry_jj_gear_bronze={need=1,tag=""},forestry_jj_ingot_tin={need=4,tag=""},forestry_jj_sturdy_machine={need=1,tag=""},ic2_jj_ingot_jj_6={need=4,tag=""},minecraft_jj_glass={need=1,tag=""},minecraft_jj_iron_ingot={need=2,tag=""},thermalfoundation_jj_material_jj_291={need=1,tag=""}}},
 extratrees_jj_machine_jj_5={hasPattern=true,label="Brewery",recipe={forestry_jj_gear_bronze={need=5,tag=""},forestry_jj_sturdy_machine={need=1,tag=""},minecraft_jj_glass={need=1,tag=""},minecraft_jj_iron_ingot={need=2,tag=""},thermalfoundation_jj_material_jj_291={need=5,tag=""}}},
 extratrees_jj_machine_jj_6={hasPattern=false,label="",recipe={forestry_jj_gear_bronze={need=1,tag=""},forestry_jj_sturdy_machine={need=1,tag=""},minecraft_jj_glass={need=1,tag=""},minecraft_jj_iron_ingot={need=2,tag=""},minecraft_jj_redstone={need=4,tag=""}}},
 extratrees_jj_machine_jj_7={hasPattern=false,label="",recipe={extratrees_jj_misc_jj_3={need=3,tag=""},forestry_jj_impregnated_casing={need=1,tag=""},minecraft_jj_glass={need=5,tag=""}}},
 extratrees_jj_misc={hasPattern=false,label="",recipe={}},
 extratrees_jj_misc_jj_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_misc_jj_10={hasPattern=false,label="",recipe={extratrees_jj_misc_jj_7={need=3,tag=""}}},
 extratrees_jj_misc_jj_11={hasPattern=true,label="Glass Fittings",recipe={minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 extratrees_jj_misc_jj_2={hasPattern=true,label="Proven Gear",recipe={forestry_jj_oak_stick={need=4,tag=""}}},
 extratrees_jj_misc_jj_3={hasPattern=false,label="",recipe={forestry_jj_oak_stick={need=4,tag=""}}},
 extratrees_jj_misc_jj_4={hasPattern=true,label="Yeast",recipe={minecraft_jj_bread={need=1,tag=""},minecraft_jj_brown_mushroom={need=3,tag=""}}},
 extratrees_jj_misc_jj_5={hasPattern=true,label="Lager LagerYeast",recipe={minecraft_jj_bread={need=1,tag=""},minecraft_jj_brown_mushroom={need=3,tag=""}}},
 extratrees_jj_misc_jj_6={hasPattern=true,label="Wheat Grain",recipe={minecraft_jj_bread={need=1,tag=""},minecraft_jj_brown_mushroom={need=3,tag=""},minecraft_jj_wheat_seeds={need=5,tag=""}}},
 extratrees_jj_misc_jj_7={hasPattern=false,label="",recipe={minecraft_jj_wheat_seeds={need=5,tag=""}}},
 extratrees_jj_misc_jj_8={hasPattern=false,label="",recipe={extratrees_jj_misc_jj_7={need=3,tag=""}}},
 extratrees_jj_misc_jj_9={hasPattern=false,label="",recipe={extratrees_jj_misc_jj_7={need=3,tag=""}}},
 extratrees_jj_multifence_jj_16387={hasPattern=false,label="",recipe={}},
 extratrees_jj_planks_vv_0={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_0={need=1,tag=""}}},
 extratrees_jj_planks_vv_0_jj_1={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_0_jj_1={need=1,tag=""}}},
 extratrees_jj_planks_vv_0_jj_10={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_2_jj_2={need=1,tag=""}}},
 extratrees_jj_planks_vv_0_jj_11={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_2_jj_3={need=1,tag=""}}},
 extratrees_jj_planks_vv_0_jj_12={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_3={need=1,tag=""}}},
 extratrees_jj_planks_vv_0_jj_13={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_3_jj_1={need=1,tag=""}}},
 extratrees_jj_planks_vv_0_jj_14={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_3_jj_2={need=1,tag=""}}},
 extratrees_jj_planks_vv_0_jj_15={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_3_jj_3={need=1,tag=""}}},
 extratrees_jj_planks_vv_0_jj_2={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_0_jj_2={need=1,tag=""}}},
 extratrees_jj_planks_vv_0_jj_3={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_0_jj_3={need=1,tag=""}}},
 extratrees_jj_planks_vv_0_jj_4={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_1={need=1,tag=""}}},
 extratrees_jj_planks_vv_0_jj_5={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_1_jj_1={need=1,tag=""}}},
 extratrees_jj_planks_vv_0_jj_6={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_1_jj_2={need=1,tag=""}}},
 extratrees_jj_planks_vv_0_jj_7={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_1_jj_3={need=1,tag=""}}},
 extratrees_jj_planks_vv_0_jj_8={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_2={need=1,tag=""}}},
 extratrees_jj_planks_vv_0_jj_9={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_2_jj_1={need=1,tag=""}}},
 extratrees_jj_planks_vv_1={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_4={need=1,tag=""}}},
 extratrees_jj_planks_vv_1_jj_1={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_4_jj_1={need=1,tag=""}}},
 extratrees_jj_planks_vv_1_jj_10={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_6_jj_2={need=1,tag=""}}},
 extratrees_jj_planks_vv_1_jj_11={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_6_jj_3={need=1,tag=""}}},
 extratrees_jj_planks_vv_1_jj_12={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_7={need=1,tag=""}}},
 extratrees_jj_planks_vv_1_jj_13={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_7_jj_1={need=1,tag=""}}},
 extratrees_jj_planks_vv_1_jj_14={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_7_jj_2={need=1,tag=""}}},
 extratrees_jj_planks_vv_1_jj_15={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_7_jj_3={need=1,tag=""}}},
 extratrees_jj_planks_vv_1_jj_2={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_4_jj_2={need=1,tag=""}}},
 extratrees_jj_planks_vv_1_jj_3={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_4_jj_3={need=1,tag=""}}},
 extratrees_jj_planks_vv_1_jj_4={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_5={need=1,tag=""}}},
 extratrees_jj_planks_vv_1_jj_5={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_5_jj_1={need=1,tag=""}}},
 extratrees_jj_planks_vv_1_jj_6={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_5_jj_2={need=1,tag=""}}},
 extratrees_jj_planks_vv_1_jj_7={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_5_jj_3={need=1,tag=""}}},
 extratrees_jj_planks_vv_1_jj_8={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_6={need=1,tag=""}}},
 extratrees_jj_planks_vv_1_jj_9={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_6_jj_1={need=1,tag=""}}},
 extratrees_jj_planks_vv_2={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_9_jj_1={need=1,tag=""}}},
 extratrees_jj_planks_vv_2_jj_1={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_8_jj_1={need=1,tag=""}}},
 extratrees_jj_planks_vv_2_jj_2={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_8_jj_2={need=1,tag=""}}},
 extratrees_jj_planks_vv_2_jj_3={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_8_jj_3={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_0={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_0={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_0_jj_1={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_0_jj_1={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_0_jj_10={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_2_jj_2={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_0_jj_11={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_2_jj_3={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_0_jj_12={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_3={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_0_jj_13={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_3_jj_1={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_0_jj_14={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_3_jj_2={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_0_jj_15={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_3_jj_3={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_0_jj_2={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_0_jj_2={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_0_jj_3={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_0_jj_3={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_0_jj_4={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_1={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_0_jj_5={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_1_jj_1={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_0_jj_6={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_1_jj_2={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_0_jj_7={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_1_jj_3={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_0_jj_8={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_2={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_0_jj_9={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_2_jj_1={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_1={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_4={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_1_jj_1={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_4_jj_1={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_1_jj_10={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_6_jj_2={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_1_jj_11={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_6_jj_3={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_1_jj_12={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_7={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_1_jj_13={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_7_jj_1={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_1_jj_14={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_7_jj_2={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_1_jj_15={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_7_jj_3={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_1_jj_2={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_4_jj_2={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_1_jj_3={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_4_jj_3={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_1_jj_4={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_5={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_1_jj_5={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_5_jj_1={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_1_jj_6={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_5_jj_2={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_1_jj_7={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_5_jj_3={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_1_jj_8={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_6={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_1_jj_9={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_6_jj_1={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_2={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_9_jj_1={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_2_jj_1={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_8_jj_1={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_2_jj_2={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_8_jj_2={need=1,tag=""}}},
 extratrees_jj_planks_vv_fireproof_vv_2_jj_3={hasPattern=false,label="",recipe={extratrees_jj_logs_vv_fireproof_vv_8_jj_3={need=1,tag=""}}},
 extratrees_jj_shrub_log={hasPattern=false,label="",recipe={}},
 extratrees_jj_slabs_vv_0={hasPattern=true,label="Appleholzstufe",recipe={extratrees_jj_planks_vv_0={need=3,tag=""}}},
 extratrees_jj_slabs_vv_0_jj_1={hasPattern=true,label="Figholzstufe",recipe={extratrees_jj_planks_vv_0_jj_1={need=3,tag=""}}},
 extratrees_jj_slabs_vv_0_jj_2={hasPattern=true,label="Butternutholzstufe",recipe={extratrees_jj_planks_vv_0_jj_2={need=3,tag=""}}},
 extratrees_jj_slabs_vv_0_jj_3={hasPattern=true,label="Whitebeamholzstufe",recipe={extratrees_jj_planks_vv_0_jj_3={need=3,tag=""}}},
 extratrees_jj_slabs_vv_0_jj_4={hasPattern=true,label="Rowanholzstufe",recipe={extratrees_jj_planks_vv_0_jj_4={need=3,tag=""}}},
 extratrees_jj_slabs_vv_0_jj_5={hasPattern=true,label="Hemlockholzstufe",recipe={extratrees_jj_planks_vv_0_jj_5={need=3,tag=""}}},
 extratrees_jj_slabs_vv_0_jj_6={hasPattern=true,label="Ashholzstufe",recipe={extratrees_jj_planks_vv_0_jj_6={need=3,tag=""}}},
 extratrees_jj_slabs_vv_0_jj_7={hasPattern=true,label="Alderholzstufe",recipe={extratrees_jj_planks_vv_0_jj_7={need=3,tag=""}}},
 extratrees_jj_slabs_vv_1={hasPattern=true,label="Beechholzstufe",recipe={extratrees_jj_planks_vv_0_jj_8={need=3,tag=""}}},
 extratrees_jj_slabs_vv_1_jj_1={hasPattern=true,label="Hawthornholzstufe",recipe={extratrees_jj_planks_vv_0_jj_9={need=3,tag=""}}},
 extratrees_jj_slabs_vv_1_jj_2={hasPattern=true,label="Bananaholzstufe",recipe={extratrees_jj_planks_vv_0_jj_10={need=3,tag=""}}},
 extratrees_jj_slabs_vv_1_jj_3={hasPattern=true,label="Yewholzstufe",recipe={extratrees_jj_planks_vv_0_jj_11={need=3,tag=""}}},
 extratrees_jj_slabs_vv_1_jj_4={hasPattern=true,label="Cypressholzstufe",recipe={extratrees_jj_planks_vv_0_jj_12={need=3,tag=""}}},
 extratrees_jj_slabs_vv_1_jj_5={hasPattern=true,label="Firholzstufe",recipe={extratrees_jj_planks_vv_0_jj_13={need=3,tag=""}}},
 extratrees_jj_slabs_vv_1_jj_6={hasPattern=true,label="Hazelholzstufe",recipe={extratrees_jj_planks_vv_0_jj_14={need=3,tag=""}}},
 extratrees_jj_slabs_vv_1_jj_7={hasPattern=true,label="Hickoryholzstufe",recipe={extratrees_jj_planks_vv_0_jj_15={need=3,tag=""}}},
 extratrees_jj_slabs_vv_2={hasPattern=true,label="Elmholzstufe",recipe={extratrees_jj_planks_vv_1={need=3,tag=""}}},
 extratrees_jj_slabs_vv_2_jj_1={hasPattern=true,label="Elderholzstufe",recipe={extratrees_jj_planks_vv_1_jj_1={need=3,tag=""}}},
 extratrees_jj_slabs_vv_2_jj_2={hasPattern=true,label="Hollyholzstufe",recipe={extratrees_jj_planks_vv_1_jj_2={need=3,tag=""}}},
 extratrees_jj_slabs_vv_2_jj_3={hasPattern=true,label="Hornbeamholzstufe",recipe={extratrees_jj_planks_vv_1_jj_3={need=3,tag=""}}},
 extratrees_jj_slabs_vv_2_jj_4={hasPattern=true,label="Cedarholzstufe",recipe={extratrees_jj_planks_vv_1_jj_4={need=3,tag=""}}},
 extratrees_jj_slabs_vv_2_jj_5={hasPattern=true,label="Oliveholzstufe",recipe={extratrees_jj_planks_vv_1_jj_5={need=3,tag=""}}},
 extratrees_jj_slabs_vv_2_jj_6={hasPattern=true,label="Sweetgumholzstufe",recipe={extratrees_jj_planks_vv_1_jj_6={need=3,tag=""}}},
 extratrees_jj_slabs_vv_2_jj_7={hasPattern=true,label="Locustholzstufe",recipe={extratrees_jj_planks_vv_1_jj_7={need=3,tag=""}}},
 extratrees_jj_slabs_vv_3={hasPattern=true,label="Pearholzstufe",recipe={extratrees_jj_planks_vv_1_jj_8={need=3,tag=""}}},
 extratrees_jj_slabs_vv_3_jj_1={hasPattern=true,label="Macluraholzstufe",recipe={extratrees_jj_planks_vv_1_jj_9={need=3,tag=""}}},
 extratrees_jj_slabs_vv_3_jj_2={hasPattern=true,label="Brazilwoodholzstufe",recipe={extratrees_jj_planks_vv_1_jj_10={need=3,tag=""}}},
 extratrees_jj_slabs_vv_3_jj_3={hasPattern=true,label="Logwoodholzstufe",recipe={extratrees_jj_planks_vv_1_jj_11={need=3,tag=""}}},
 extratrees_jj_slabs_vv_3_jj_4={hasPattern=true,label="Rosewoodholzstufe",recipe={extratrees_jj_planks_vv_1_jj_12={need=3,tag=""}}},
 extratrees_jj_slabs_vv_3_jj_5={hasPattern=true,label="Purpleheartholzstufe",recipe={extratrees_jj_planks_vv_1_jj_13={need=3,tag=""}}},
 extratrees_jj_slabs_vv_3_jj_6={hasPattern=true,label="Irokoholzstufe",recipe={extratrees_jj_planks_vv_1_jj_14={need=3,tag=""}}},
 extratrees_jj_slabs_vv_3_jj_7={hasPattern=true,label="Gingkoholzstufe",recipe={extratrees_jj_planks_vv_1_jj_15={need=3,tag=""}}},
 extratrees_jj_slabs_vv_4={hasPattern=true,label="Eucalyptusholzstufe",recipe={extratrees_jj_planks_vv_2={need=3,tag=""}}},
 extratrees_jj_slabs_vv_4_jj_1={hasPattern=true,label="Boxholzstufe",recipe={extratrees_jj_planks_vv_2_jj_1={need=3,tag=""}}},
 extratrees_jj_slabs_vv_4_jj_2={hasPattern=true,label="Syzgiumholzstufe",recipe={extratrees_jj_planks_vv_2_jj_2={need=3,tag=""}}},
 extratrees_jj_slabs_vv_4_jj_3={hasPattern=true,label="Pink Ivoryholzstufe",recipe={extratrees_jj_planks_vv_2_jj_3={need=3,tag=""}}},
 extratrees_jj_slabs_vv_double_vv_0={hasPattern=false,label="",recipe={}},
 extratrees_jj_slabs_vv_double_vv_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_slabs_vv_double_vv_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_slabs_vv_double_vv_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_slabs_vv_double_vv_4={hasPattern=false,label="",recipe={}},
 extratrees_jj_slabs_vv_fireproof_vv_0={hasPattern=true,label="Appleholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_0_jj_1={hasPattern=true,label="Figholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_1={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_0_jj_2={hasPattern=true,label="Butternutholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_2={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_0_jj_3={hasPattern=true,label="Whitebeamholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_3={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_0_jj_4={hasPattern=true,label="Rowanholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_4={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_0_jj_5={hasPattern=true,label="Hemlockholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_5={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_0_jj_6={hasPattern=true,label="Ashholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_6={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_0_jj_7={hasPattern=true,label="Alderholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_7={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_1={hasPattern=true,label="Beechholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_8={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_1_jj_1={hasPattern=true,label="Hawthornholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_9={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_1_jj_2={hasPattern=true,label="Bananaholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_10={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_1_jj_3={hasPattern=true,label="Yewholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_11={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_1_jj_4={hasPattern=true,label="Cypressholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_12={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_1_jj_5={hasPattern=true,label="Firholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_13={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_1_jj_6={hasPattern=true,label="Hazelholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_14={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_1_jj_7={hasPattern=true,label="Hickoryholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_15={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_2={hasPattern=true,label="Elmholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_2_jj_1={hasPattern=true,label="Elderholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_1={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_2_jj_2={hasPattern=true,label="Hollyholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_2={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_2_jj_3={hasPattern=true,label="Hornbeamholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_3={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_2_jj_4={hasPattern=true,label="Cedarholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_4={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_2_jj_5={hasPattern=true,label="Oliveholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_5={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_2_jj_6={hasPattern=true,label="Sweetgumholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_6={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_2_jj_7={hasPattern=true,label="Locustholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_7={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_3={hasPattern=true,label="Pearholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_8={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_3_jj_1={hasPattern=true,label="Macluraholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_9={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_3_jj_2={hasPattern=true,label="Brazilwoodholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_10={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_3_jj_3={hasPattern=true,label="Logwoodholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_11={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_3_jj_4={hasPattern=true,label="Rosewoodholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_12={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_3_jj_5={hasPattern=true,label="Purpleheartholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_13={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_3_jj_6={hasPattern=true,label="Irokoholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_14={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_3_jj_7={hasPattern=true,label="Gingkoholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_15={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_4={hasPattern=true,label="Eucalyptusholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_2={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_4_jj_1={hasPattern=true,label="Boxholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_2_jj_1={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_4_jj_2={hasPattern=true,label="Syzgiumholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_2_jj_2={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_4_jj_3={hasPattern=true,label="Pink Ivoryholzstufe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_2_jj_3={need=3,tag=""}}},
 extratrees_jj_slabs_vv_fireproof_vv_double_vv_0={hasPattern=false,label="",recipe={}},
 extratrees_jj_slabs_vv_fireproof_vv_double_vv_1={hasPattern=false,label="",recipe={}},
 extratrees_jj_slabs_vv_fireproof_vv_double_vv_2={hasPattern=false,label="",recipe={}},
 extratrees_jj_slabs_vv_fireproof_vv_double_vv_3={hasPattern=false,label="",recipe={}},
 extratrees_jj_slabs_vv_fireproof_vv_double_vv_4={hasPattern=false,label="",recipe={}},
 extratrees_jj_stainedglass={hasPattern=false,label="",recipe={}},
 extratrees_jj_stairs_vv_alder={hasPattern=true,label="Alderholztreppe",recipe={extratrees_jj_planks_vv_0_jj_7={need=6,tag=""}}},
 extratrees_jj_stairs_vv_apple={hasPattern=true,label="Appleholztreppe",recipe={extratrees_jj_planks_vv_0={need=6,tag=""}}},
 extratrees_jj_stairs_vv_ash={hasPattern=true,label="Ashholztreppe",recipe={extratrees_jj_planks_vv_0_jj_6={need=6,tag=""}}},
 extratrees_jj_stairs_vv_banana={hasPattern=true,label="Bananaholztreppe",recipe={extratrees_jj_planks_vv_0_jj_10={need=6,tag=""}}},
 extratrees_jj_stairs_vv_beech={hasPattern=true,label="Beechholztreppe",recipe={extratrees_jj_planks_vv_0_jj_8={need=6,tag=""}}},
 extratrees_jj_stairs_vv_box={hasPattern=true,label="Boxholztreppe",recipe={extratrees_jj_planks_vv_2_jj_1={need=6,tag=""}}},
 extratrees_jj_stairs_vv_brazilwood={hasPattern=true,label="Brazilwoodholztreppe",recipe={extratrees_jj_planks_vv_1_jj_10={need=6,tag=""}}},
 extratrees_jj_stairs_vv_butternut={hasPattern=true,label="Butternutholztreppe",recipe={extratrees_jj_planks_vv_0_jj_2={need=6,tag=""}}},
 extratrees_jj_stairs_vv_cedar={hasPattern=true,label="Cedarholztreppe",recipe={extratrees_jj_planks_vv_1_jj_4={need=6,tag=""}}},
 extratrees_jj_stairs_vv_cypress={hasPattern=true,label="Cypressholztreppe",recipe={extratrees_jj_planks_vv_0_jj_12={need=6,tag=""}}},
 extratrees_jj_stairs_vv_elder={hasPattern=true,label="Elderholztreppe",recipe={extratrees_jj_planks_vv_1_jj_1={need=6,tag=""}}},
 extratrees_jj_stairs_vv_elm={hasPattern=true,label="Elmholztreppe",recipe={extratrees_jj_planks_vv_1={need=6,tag=""}}},
 extratrees_jj_stairs_vv_eucalyptus={hasPattern=true,label="Eucalyptusholztreppe",recipe={extratrees_jj_planks_vv_2={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fig={hasPattern=true,label="Figholztreppe",recipe={extratrees_jj_planks_vv_0_jj_1={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fir={hasPattern=true,label="Firholztreppe",recipe={extratrees_jj_planks_vv_0_jj_13={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_alder={hasPattern=true,label="Alderholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_7={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_apple={hasPattern=true,label="Appleholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_ash={hasPattern=true,label="Ashholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_6={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_banana={hasPattern=true,label="Bananaholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_10={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_beech={hasPattern=true,label="Beechholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_8={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_box={hasPattern=true,label="Boxholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_2_jj_1={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_brazilwood={hasPattern=true,label="Brazilwoodholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_10={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_butternut={hasPattern=true,label="Butternutholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_2={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_cedar={hasPattern=true,label="Cedarholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_4={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_cypress={hasPattern=true,label="Cypressholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_12={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_elder={hasPattern=true,label="Elderholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_1={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_elm={hasPattern=true,label="Elmholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_eucalyptus={hasPattern=true,label="Eucalyptusholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_2={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_fig={hasPattern=true,label="Figholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_1={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_fir={hasPattern=true,label="Firholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_13={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_gingko={hasPattern=true,label="Gingkoholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_15={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_hawthorn={hasPattern=true,label="Hawthornholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_9={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_hazel={hasPattern=true,label="Hazelholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_14={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_hemlock={hasPattern=true,label="Hemlockholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_5={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_hickory={hasPattern=true,label="Hickoryholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_15={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_holly={hasPattern=true,label="Hollyholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_2={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_hornbeam={hasPattern=true,label="Hornbeamholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_3={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_iroko={hasPattern=true,label="Irokoholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_14={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_locust={hasPattern=true,label="Locustholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_7={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_logwood={hasPattern=true,label="Logwoodholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_11={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_maclura={hasPattern=true,label="Macluraholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_9={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_olive={hasPattern=true,label="Oliveholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_5={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_pear={hasPattern=true,label="Pearholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_8={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_pinkivory={hasPattern=true,label="Pink Ivoryholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_2_jj_3={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_purpleheart={hasPattern=true,label="Purpleheartholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_13={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_rosewood={hasPattern=true,label="Rosewoodholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_12={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_rowan={hasPattern=true,label="Rowanholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_4={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_sweetgum={hasPattern=true,label="Sweetgumholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_1_jj_6={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_syzgium={hasPattern=true,label="Syzgiumholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_2_jj_2={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_whitebeam={hasPattern=true,label="Whitebeamholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_3={need=6,tag=""}}},
 extratrees_jj_stairs_vv_fireproof_vv_yew={hasPattern=true,label="Yewholztreppe (Feuerfest)",recipe={extratrees_jj_planks_vv_fireproof_vv_0_jj_11={need=6,tag=""}}},
 extratrees_jj_stairs_vv_gingko={hasPattern=true,label="Gingkoholztreppe",recipe={extratrees_jj_planks_vv_1_jj_15={need=6,tag=""}}},
 extratrees_jj_stairs_vv_hawthorn={hasPattern=true,label="Hawthornholztreppe",recipe={extratrees_jj_planks_vv_0_jj_9={need=6,tag=""}}},
 extratrees_jj_stairs_vv_hazel={hasPattern=true,label="Hazelholztreppe",recipe={extratrees_jj_planks_vv_0_jj_14={need=6,tag=""}}},
 extratrees_jj_stairs_vv_hemlock={hasPattern=true,label="Hemlockholztreppe",recipe={extratrees_jj_planks_vv_0_jj_5={need=6,tag=""}}},
 extratrees_jj_stairs_vv_hickory={hasPattern=true,label="Hickoryholztreppe",recipe={extratrees_jj_planks_vv_0_jj_15={need=6,tag=""}}},
 extratrees_jj_stairs_vv_holly={hasPattern=true,label="Hollyholztreppe",recipe={extratrees_jj_planks_vv_1_jj_2={need=6,tag=""}}},
 extratrees_jj_stairs_vv_hornbeam={hasPattern=true,label="Hornbeamholztreppe",recipe={extratrees_jj_planks_vv_1_jj_3={need=6,tag=""}}},
 extratrees_jj_stairs_vv_iroko={hasPattern=true,label="Irokoholztreppe",recipe={extratrees_jj_planks_vv_1_jj_14={need=6,tag=""}}},
 extratrees_jj_stairs_vv_locust={hasPattern=true,label="Locustholztreppe",recipe={extratrees_jj_planks_vv_1_jj_7={need=6,tag=""}}},
 extratrees_jj_stairs_vv_logwood={hasPattern=true,label="Logwoodholztreppe",recipe={extratrees_jj_planks_vv_1_jj_11={need=6,tag=""}}},
 extratrees_jj_stairs_vv_maclura={hasPattern=true,label="Macluraholztreppe",recipe={extratrees_jj_planks_vv_1_jj_9={need=6,tag=""}}},
 extratrees_jj_stairs_vv_olive={hasPattern=true,label="Oliveholztreppe",recipe={extratrees_jj_planks_vv_1_jj_5={need=6,tag=""}}},
 extratrees_jj_stairs_vv_pear={hasPattern=true,label="Pearholztreppe",recipe={extratrees_jj_planks_vv_1_jj_8={need=6,tag=""}}},
 extratrees_jj_stairs_vv_pinkivory={hasPattern=true,label="Pink Ivoryholztreppe",recipe={extratrees_jj_planks_vv_2_jj_3={need=6,tag=""}}},
 extratrees_jj_stairs_vv_purpleheart={hasPattern=true,label="Purpleheartholztreppe",recipe={extratrees_jj_planks_vv_1_jj_13={need=6,tag=""}}},
 extratrees_jj_stairs_vv_rosewood={hasPattern=true,label="Rosewoodholztreppe",recipe={extratrees_jj_planks_vv_1_jj_12={need=6,tag=""}}},
 extratrees_jj_stairs_vv_rowan={hasPattern=true,label="Rowanholztreppe",recipe={extratrees_jj_planks_vv_0_jj_4={need=6,tag=""}}},
 extratrees_jj_stairs_vv_sweetgum={hasPattern=true,label="Sweetgumholztreppe",recipe={extratrees_jj_planks_vv_1_jj_6={need=6,tag=""}}},
 extratrees_jj_stairs_vv_syzgium={hasPattern=true,label="Syzgiumholztreppe",recipe={extratrees_jj_planks_vv_2_jj_2={need=6,tag=""}}},
 extratrees_jj_stairs_vv_whitebeam={hasPattern=true,label="Whitebeamholztreppe",recipe={extratrees_jj_planks_vv_0_jj_3={need=6,tag=""}}},
 extratrees_jj_stairs_vv_yew={hasPattern=true,label="Yewholztreppe",recipe={extratrees_jj_planks_vv_0_jj_11={need=6,tag=""}}}
 }