return {
 ceramics_jj_channel={hasPattern=false,label="",recipe={ceramics_jj_unfired_clay_jj_5={need=5,tag=""}}},
 ceramics_jj_clay_barrel={hasPattern=false,label="",recipe={}},
 ceramics_jj_clay_barrel_jj_1={hasPattern=false,label="",recipe={}},
 ceramics_jj_clay_barrel_stained={hasPattern=true,label="White Clay Barrel",recipe={ceramics_jj_clay_barrel={need=8,tag=""},ceramics_jj_clay_barrel_stained={need=1,tag=""},minecraft_jj_dye_jj_15={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_extension={hasPattern=true,label="White Clay Barrel Extension",recipe={ceramics_jj_clay_barrel_jj_1={need=8,tag=""},ceramics_jj_clay_barrel_stained_extension={need=8,tag=""},minecraft_jj_dye_jj_15={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_extension_jj_1={hasPattern=true,label="Orange Clay Barrel Extension",recipe={ceramics_jj_clay_barrel_jj_1={need=8,tag=""},ceramics_jj_clay_barrel_stained_extension={need=1,tag=""},minecraft_jj_dye_jj_14={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_extension_jj_10={hasPattern=true,label="Purple Clay Barrel Extension",recipe={ceramics_jj_clay_barrel_jj_1={need=8,tag=""},ceramics_jj_clay_barrel_stained_extension={need=8,tag=""},minecraft_jj_dye_jj_5={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_extension_jj_11={hasPattern=true,label="Blue Clay Barrel Extension",recipe={ceramics_jj_clay_barrel_jj_1={need=8,tag=""},ceramics_jj_clay_barrel_stained_extension={need=8,tag=""},minecraft_jj_dye_jj_4={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_extension_jj_12={hasPattern=true,label="Brown Clay Barrel Extension",recipe={ceramics_jj_clay_barrel_jj_1={need=8,tag=""},ceramics_jj_clay_barrel_stained_extension={need=1,tag=""},minecraft_jj_dye_jj_3={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_extension_jj_13={hasPattern=true,label="Green Clay Barrel Extension",recipe={ceramics_jj_clay_barrel_jj_1={need=8,tag=""},ceramics_jj_clay_barrel_stained_extension={need=8,tag=""},minecraft_jj_dye_jj_2={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_extension_jj_14={hasPattern=true,label="Red Clay Barrel Extension",recipe={ceramics_jj_clay_barrel_jj_1={need=8,tag=""},ceramics_jj_clay_barrel_stained_extension={need=8,tag=""},minecraft_jj_dye_jj_1={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_extension_jj_15={hasPattern=true,label="Black Clay Barrel Extension",recipe={ceramics_jj_clay_barrel_jj_1={need=8,tag=""},ceramics_jj_clay_barrel_stained_extension={need=1,tag=""},minecraft_jj_dye={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_extension_jj_2={hasPattern=true,label="Magenta Clay Barrel Extension",recipe={ceramics_jj_clay_barrel_jj_1={need=8,tag=""},ceramics_jj_clay_barrel_stained_extension={need=1,tag=""},minecraft_jj_dye_jj_13={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_extension_jj_3={hasPattern=true,label="Light Blue Clay Barrel Extension",recipe={ceramics_jj_clay_barrel_jj_1={need=8,tag=""},ceramics_jj_clay_barrel_stained_extension={need=8,tag=""},minecraft_jj_dye_jj_12={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_extension_jj_4={hasPattern=true,label="Yellow Clay Barrel Extension",recipe={ceramics_jj_clay_barrel_jj_1={need=8,tag=""},ceramics_jj_clay_barrel_stained_extension={need=1,tag=""},minecraft_jj_dye_jj_11={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_extension_jj_5={hasPattern=true,label="Lime Clay Barrel Extension",recipe={ceramics_jj_clay_barrel_jj_1={need=8,tag=""},ceramics_jj_clay_barrel_stained_extension={need=1,tag=""},minecraft_jj_dye_jj_10={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_extension_jj_6={hasPattern=true,label="Pink Clay Barrel Extension",recipe={ceramics_jj_clay_barrel_jj_1={need=8,tag=""},ceramics_jj_clay_barrel_stained_extension={need=8,tag=""},minecraft_jj_dye_jj_9={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_extension_jj_7={hasPattern=true,label="Gray Clay Barrel Extension",recipe={ceramics_jj_clay_barrel_jj_1={need=8,tag=""},ceramics_jj_clay_barrel_stained_extension={need=8,tag=""},minecraft_jj_dye_jj_8={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_extension_jj_8={hasPattern=true,label="Light Gray Clay Barrel Extension",recipe={ceramics_jj_clay_barrel_jj_1={need=8,tag=""},ceramics_jj_clay_barrel_stained_extension={need=1,tag=""},minecraft_jj_dye_jj_7={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_extension_jj_9={hasPattern=true,label="Cyan Clay Barrel Extension",recipe={ceramics_jj_clay_barrel_jj_1={need=8,tag=""},ceramics_jj_clay_barrel_stained_extension={need=1,tag=""},minecraft_jj_dye_jj_6={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_jj_1={hasPattern=true,label="Orange Clay Barrel",recipe={ceramics_jj_clay_barrel={need=8,tag=""},ceramics_jj_clay_barrel_stained={need=1,tag=""},minecraft_jj_dye_jj_14={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_jj_10={hasPattern=true,label="Purple Clay Barrel",recipe={ceramics_jj_clay_barrel={need=8,tag=""},ceramics_jj_clay_barrel_stained={need=8,tag=""},minecraft_jj_dye_jj_5={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_jj_11={hasPattern=true,label="Blue Clay Barrel",recipe={ceramics_jj_clay_barrel={need=8,tag=""},ceramics_jj_clay_barrel_stained={need=1,tag=""},minecraft_jj_dye_jj_4={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_jj_12={hasPattern=true,label="Brown Clay Barrel",recipe={ceramics_jj_clay_barrel={need=8,tag=""},ceramics_jj_clay_barrel_stained={need=8,tag=""},minecraft_jj_dye_jj_3={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_jj_13={hasPattern=true,label="Green Clay Barrel",recipe={ceramics_jj_clay_barrel={need=8,tag=""},ceramics_jj_clay_barrel_stained={need=8,tag=""},minecraft_jj_dye_jj_2={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_jj_14={hasPattern=true,label="Red Clay Barrel",recipe={ceramics_jj_clay_barrel={need=8,tag=""},ceramics_jj_clay_barrel_stained={need=8,tag=""},minecraft_jj_dye_jj_1={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_jj_15={hasPattern=true,label="Black Clay Barrel",recipe={ceramics_jj_clay_barrel={need=8,tag=""},ceramics_jj_clay_barrel_stained={need=8,tag=""},minecraft_jj_dye={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_jj_2={hasPattern=true,label="Magenta Clay Barrel",recipe={ceramics_jj_clay_barrel={need=8,tag=""},ceramics_jj_clay_barrel_stained={need=1,tag=""},minecraft_jj_dye_jj_13={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_jj_3={hasPattern=true,label="Light Blue Clay Barrel",recipe={ceramics_jj_clay_barrel={need=8,tag=""},ceramics_jj_clay_barrel_stained={need=8,tag=""},minecraft_jj_dye_jj_12={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_jj_4={hasPattern=true,label="Yellow Clay Barrel",recipe={ceramics_jj_clay_barrel={need=8,tag=""},ceramics_jj_clay_barrel_stained={need=1,tag=""},minecraft_jj_dye_jj_11={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_jj_5={hasPattern=true,label="Lime Clay Barrel",recipe={ceramics_jj_clay_barrel={need=8,tag=""},ceramics_jj_clay_barrel_stained={need=8,tag=""},minecraft_jj_dye_jj_10={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_jj_6={hasPattern=true,label="Pink Clay Barrel",recipe={ceramics_jj_clay_barrel={need=8,tag=""},ceramics_jj_clay_barrel_stained={need=8,tag=""},minecraft_jj_dye_jj_9={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_jj_7={hasPattern=true,label="Gray Clay Barrel",recipe={ceramics_jj_clay_barrel={need=8,tag=""},ceramics_jj_clay_barrel_stained={need=8,tag=""},minecraft_jj_dye_jj_8={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_jj_8={hasPattern=true,label="Light Gray Clay Barrel",recipe={ceramics_jj_clay_barrel={need=8,tag=""},ceramics_jj_clay_barrel_stained={need=1,tag=""},minecraft_jj_dye_jj_7={need=1,tag=""}}},
 ceramics_jj_clay_barrel_stained_jj_9={hasPattern=true,label="Cyan Clay Barrel",recipe={ceramics_jj_clay_barrel={need=8,tag=""},ceramics_jj_clay_barrel_stained={need=1,tag=""},minecraft_jj_dye_jj_6={need=1,tag=""}}},
 ceramics_jj_clay_barrel_unfired={hasPattern=false,label="",recipe={minecraft_jj_clay_ball={need=6,tag=""}}},
 ceramics_jj_clay_barrel_unfired_jj_1={hasPattern=true,label="Unfired Clay Barrel Extension",recipe={minecraft_jj_clay_ball={need=6,tag=""}}},
 ceramics_jj_clay_barrel_unfired_jj_2={hasPattern=false,label="",recipe={ceramics_jj_unfired_clay_jj_4={need=6,tag=""}}},
 ceramics_jj_clay_barrel_unfired_jj_3={hasPattern=true,label="Unfired Porcelain Barrel Extension",recipe={ceramics_jj_unfired_clay_jj_4={need=6,tag=""}}},
 ceramics_jj_clay_boots={hasPattern=true,label="Clay Boots",recipe={ceramics_jj_unfired_clay_jj_9={need=4,tag=""}}},
 ceramics_jj_clay_boots_raw={hasPattern=false,label="",recipe={minecraft_jj_clay_ball={need=4,tag=""}}},
 ceramics_jj_clay_bucket={hasPattern=false,label="",recipe={}},
 ceramics_jj_clay_bucket_block={hasPattern=false,label="",recipe={}},
 ceramics_jj_clay_bucket_jj_1={hasPattern=false,label="",recipe={}},
 ceramics_jj_clay_chestplate={hasPattern=true,label="Clay Chestplate",recipe={ceramics_jj_unfired_clay_jj_9={need=8,tag=""}}},
 ceramics_jj_clay_chestplate_raw={hasPattern=false,label="",recipe={minecraft_jj_clay_ball={need=8,tag=""}}},
 ceramics_jj_clay_hard={hasPattern=true,label="Porcelain Bricks",recipe={ceramics_jj_unfired_clay_jj_5={need=4,tag=""}}},
 ceramics_jj_clay_hard_jj_1={hasPattern=false,label="",recipe={minecraft_jj_brick={need=8,tag=""},minecraft_jj_dye={need=1,tag=""}}},
 ceramics_jj_clay_hard_jj_2={hasPattern=true,label="Marine Bricks",recipe={ceramics_jj_unfired_clay_jj_5={need=8,tag=""},minecraft_jj_dye_jj_4={need=1,tag=""}}},
 ceramics_jj_clay_hard_jj_3={hasPattern=true,label="Golden Bricks",recipe={ceramics_jj_clay_hard={need=8,tag=""},minecraft_jj_gold_nugget={need=1,tag=""}}},
 ceramics_jj_clay_hard_jj_4={hasPattern=true,label="Dragon Bricks",recipe={minecraft_jj_brick_block={need=8,tag=""},minecraft_jj_dragon_breath={need=1,tag=""}}},
 ceramics_jj_clay_hard_jj_5={hasPattern=false,label="",recipe={minecraft_jj_brick_block={need=8,tag=""}}},
 ceramics_jj_clay_hard_jj_6={hasPattern=true,label="Rainbow Bricks",recipe={ceramics_jj_clay_hard={need=6,tag=""},minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_dye_jj_4={need=1,tag=""}}},
 ceramics_jj_clay_hard_jj_7={hasPattern=false,label="",recipe={}},
 ceramics_jj_clay_helmet={hasPattern=true,label="Clay Helmet",recipe={ceramics_jj_unfired_clay_jj_9={need=5,tag=""}}},
 ceramics_jj_clay_helmet_raw={hasPattern=false,label="",recipe={minecraft_jj_clay_ball={need=5,tag=""}}},
 ceramics_jj_clay_leggings={hasPattern=true,label="Clay Leggings",recipe={ceramics_jj_unfired_clay_jj_9={need=7,tag=""}}},
 ceramics_jj_clay_leggings_raw={hasPattern=false,label="",recipe={minecraft_jj_clay_ball={need=7,tag=""}}},
 ceramics_jj_clay_shears={hasPattern=false,label="",recipe={}},
 ceramics_jj_clay_slab={hasPattern=true,label="Porcelain Bricks Slab",recipe={ceramics_jj_clay_hard={need=3,tag=""}}},
 ceramics_jj_clay_slab_jj_1={hasPattern=true,label="Dark Bricks Slab",recipe={ceramics_jj_clay_hard_jj_1={need=3,tag=""}}},
 ceramics_jj_clay_slab_jj_2={hasPattern=true,label="Marine Bricks Slab",recipe={ceramics_jj_clay_hard_jj_2={need=3,tag=""}}},
 ceramics_jj_clay_slab_jj_3={hasPattern=true,label="Golden Bricks Slab",recipe={ceramics_jj_clay_hard_jj_3={need=3,tag=""}}},
 ceramics_jj_clay_slab_jj_4={hasPattern=true,label="Dragon Bricks Slab",recipe={ceramics_jj_clay_hard_jj_4={need=3,tag=""}}},
 ceramics_jj_clay_slab_jj_5={hasPattern=true,label="Lava Bricks Slab",recipe={ceramics_jj_clay_hard_jj_5={need=3,tag=""}}},
 ceramics_jj_clay_slab_jj_6={hasPattern=true,label="Rainbow Bricks Slab",recipe={ceramics_jj_clay_hard_jj_6={need=3,tag=""}}},
 ceramics_jj_clay_slab_jj_7={hasPattern=false,label="",recipe={}},
 ceramics_jj_clay_soft={hasPattern=true,label="Unfired Porcelain",recipe={ceramics_jj_unfired_clay_jj_4={need=4,tag=""}}},
 ceramics_jj_clay_wall={hasPattern=true,label="Bricks Wall",recipe={minecraft_jj_brick_block={need=6,tag=""}}},
 ceramics_jj_clay_wall_jj_1={hasPattern=true,label="Porcelain Bricks Wall",recipe={ceramics_jj_clay_hard={need=6,tag=""}}},
 ceramics_jj_clay_wall_jj_2={hasPattern=true,label="Dark Bricks Wall",recipe={ceramics_jj_clay_hard_jj_1={need=6,tag=""}}},
 ceramics_jj_clay_wall_jj_3={hasPattern=true,label="Marine Bricks Wall",recipe={ceramics_jj_clay_hard_jj_2={need=6,tag=""}}},
 ceramics_jj_clay_wall_jj_4={hasPattern=true,label="Golden Bricks Wall",recipe={ceramics_jj_clay_hard_jj_3={need=6,tag=""}}},
 ceramics_jj_clay_wall_jj_5={hasPattern=true,label="Dragon Bricks Wall",recipe={ceramics_jj_clay_hard_jj_4={need=6,tag=""}}},
 ceramics_jj_clay_wall_jj_6={hasPattern=true,label="Lava Bricks Wall",recipe={ceramics_jj_clay_hard_jj_5={need=6,tag=""}}},
 ceramics_jj_clay_wall_jj_7={hasPattern=true,label="Rainbow Bricks Wall",recipe={ceramics_jj_clay_hard_jj_6={need=6,tag=""}}},
 ceramics_jj_clay_wall_jj_8={hasPattern=false,label="",recipe={}},
 ceramics_jj_dark_bricks_stairs={hasPattern=true,label="Dark Bricks Stairs",recipe={ceramics_jj_clay_hard_jj_1={need=6,tag=""}}},
 ceramics_jj_dragon_bricks_stairs={hasPattern=true,label="Dragon Bricks Stairs",recipe={ceramics_jj_clay_hard_jj_4={need=6,tag=""}}},
 ceramics_jj_faucet={hasPattern=false,label="",recipe={ceramics_jj_unfired_clay_jj_5={need=3,tag=""}}},
 ceramics_jj_golden_bricks_stairs={hasPattern=true,label="Golden Bricks Stairs",recipe={ceramics_jj_clay_hard_jj_3={need=6,tag=""}}},
 ceramics_jj_lava_bricks_stairs={hasPattern=true,label="Lava Bricks Stairs",recipe={ceramics_jj_clay_hard_jj_5={need=6,tag=""}}},
 ceramics_jj_marine_bricks_stairs={hasPattern=true,label="Marine Bricks Stairs",recipe={ceramics_jj_clay_hard_jj_2={need=6,tag=""}}},
 ceramics_jj_monochrome_bricks_stairs={hasPattern=false,label="",recipe={}},
 ceramics_jj_porcelain={hasPattern=true,label="White Porcelain",recipe={ceramics_jj_porcelain={need=8,tag=""},minecraft_jj_dye_jj_15={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel={hasPattern=true,label="White Porcelain Barrel",recipe={ceramics_jj_porcelain_barrel={need=8,tag=""},minecraft_jj_dye_jj_15={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_extension={hasPattern=true,label="White Porcelain Barrel Extension",recipe={ceramics_jj_porcelain_barrel_extension={need=8,tag=""},minecraft_jj_dye_jj_15={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_extension_jj_1={hasPattern=true,label="Orange Porcelain Barrel Extension",recipe={ceramics_jj_porcelain_barrel_extension={need=8,tag=""},minecraft_jj_dye_jj_14={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_extension_jj_10={hasPattern=true,label="Purple Porcelain Barrel Extension",recipe={ceramics_jj_porcelain_barrel_extension={need=8,tag=""},minecraft_jj_dye_jj_5={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_extension_jj_11={hasPattern=true,label="Blue Porcelain Barrel Extension",recipe={ceramics_jj_porcelain_barrel_extension={need=8,tag=""},minecraft_jj_dye_jj_4={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_extension_jj_12={hasPattern=true,label="Brown Porcelain Barrel Extension",recipe={ceramics_jj_porcelain_barrel_extension={need=8,tag=""},minecraft_jj_dye_jj_3={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_extension_jj_13={hasPattern=true,label="Green Porcelain Barrel Extension",recipe={ceramics_jj_porcelain_barrel_extension={need=8,tag=""},minecraft_jj_dye_jj_2={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_extension_jj_14={hasPattern=true,label="Red Porcelain Barrel Extension",recipe={ceramics_jj_porcelain_barrel_extension={need=8,tag=""},minecraft_jj_dye_jj_1={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_extension_jj_15={hasPattern=true,label="Black Porcelain Barrel Extension",recipe={ceramics_jj_porcelain_barrel_extension={need=8,tag=""},minecraft_jj_dye={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_extension_jj_2={hasPattern=true,label="Magenta Porcelain Barrel Extension",recipe={ceramics_jj_porcelain_barrel_extension={need=8,tag=""},minecraft_jj_dye_jj_13={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_extension_jj_3={hasPattern=true,label="Light Blue Porcelain Barrel Extension",recipe={ceramics_jj_porcelain_barrel_extension={need=8,tag=""},minecraft_jj_dye_jj_12={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_extension_jj_4={hasPattern=true,label="Yellow Porcelain Barrel Extension",recipe={ceramics_jj_porcelain_barrel_extension={need=8,tag=""},minecraft_jj_dye_jj_11={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_extension_jj_5={hasPattern=true,label="Lime Porcelain Barrel Extension",recipe={ceramics_jj_porcelain_barrel_extension={need=8,tag=""},minecraft_jj_dye_jj_10={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_extension_jj_6={hasPattern=true,label="Pink Porcelain Barrel Extension",recipe={ceramics_jj_porcelain_barrel_extension={need=8,tag=""},minecraft_jj_dye_jj_9={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_extension_jj_7={hasPattern=true,label="Gray Porcelain Barrel Extension",recipe={ceramics_jj_porcelain_barrel_extension={need=8,tag=""},minecraft_jj_dye_jj_8={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_extension_jj_8={hasPattern=true,label="Light Gray Porcelain Barrel Extension",recipe={ceramics_jj_porcelain_barrel_extension={need=8,tag=""},minecraft_jj_dye_jj_7={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_extension_jj_9={hasPattern=true,label="Cyan Porcelain Barrel Extension",recipe={ceramics_jj_porcelain_barrel_extension={need=8,tag=""},minecraft_jj_dye_jj_6={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_jj_1={hasPattern=true,label="Orange Porcelain Barrel",recipe={ceramics_jj_porcelain_barrel={need=8,tag=""},minecraft_jj_dye_jj_14={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_jj_10={hasPattern=true,label="Purple Porcelain Barrel",recipe={ceramics_jj_porcelain_barrel={need=8,tag=""},minecraft_jj_dye_jj_5={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_jj_11={hasPattern=true,label="Blue Porcelain Barrel",recipe={ceramics_jj_porcelain_barrel={need=8,tag=""},minecraft_jj_dye_jj_4={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_jj_12={hasPattern=true,label="Brown Porcelain Barrel",recipe={ceramics_jj_porcelain_barrel={need=8,tag=""},minecraft_jj_dye_jj_3={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_jj_13={hasPattern=true,label="Green Porcelain Barrel",recipe={ceramics_jj_porcelain_barrel={need=8,tag=""},minecraft_jj_dye_jj_2={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_jj_14={hasPattern=true,label="Red Porcelain Barrel",recipe={ceramics_jj_porcelain_barrel={need=8,tag=""},minecraft_jj_dye_jj_1={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_jj_15={hasPattern=true,label="Black Porcelain Barrel",recipe={ceramics_jj_porcelain_barrel={need=8,tag=""},minecraft_jj_dye={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_jj_2={hasPattern=true,label="Magenta Porcelain Barrel",recipe={ceramics_jj_porcelain_barrel={need=8,tag=""},minecraft_jj_dye_jj_13={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_jj_3={hasPattern=true,label="Light Blue Porcelain Barrel",recipe={ceramics_jj_porcelain_barrel={need=8,tag=""},minecraft_jj_dye_jj_12={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_jj_4={hasPattern=true,label="Yellow Porcelain Barrel",recipe={ceramics_jj_porcelain_barrel={need=8,tag=""},minecraft_jj_dye_jj_11={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_jj_5={hasPattern=true,label="Lime Porcelain Barrel",recipe={ceramics_jj_porcelain_barrel={need=8,tag=""},minecraft_jj_dye_jj_10={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_jj_6={hasPattern=true,label="Pink Porcelain Barrel",recipe={ceramics_jj_porcelain_barrel={need=8,tag=""},minecraft_jj_dye_jj_9={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_jj_7={hasPattern=true,label="Gray Porcelain Barrel",recipe={ceramics_jj_porcelain_barrel={need=8,tag=""},minecraft_jj_dye_jj_8={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_jj_8={hasPattern=true,label="Light Gray Porcelain Barrel",recipe={ceramics_jj_porcelain_barrel={need=8,tag=""},minecraft_jj_dye_jj_7={need=1,tag=""}}},
 ceramics_jj_porcelain_barrel_jj_9={hasPattern=true,label="Cyan Porcelain Barrel",recipe={ceramics_jj_porcelain_barrel={need=8,tag=""},minecraft_jj_dye_jj_6={need=1,tag=""}}},
 ceramics_jj_porcelain_bricks_stairs={hasPattern=true,label="Porcelain Bricks Stairs",recipe={ceramics_jj_clay_hard={need=6,tag=""}}},
 ceramics_jj_porcelain_jj_1={hasPattern=true,label="Orange Porcelain",recipe={ceramics_jj_porcelain={need=8,tag=""},minecraft_jj_dye_jj_14={need=1,tag=""}}},
 ceramics_jj_porcelain_jj_10={hasPattern=true,label="Purple Porcelain",recipe={ceramics_jj_porcelain={need=8,tag=""},minecraft_jj_dye_jj_5={need=1,tag=""}}},
 ceramics_jj_porcelain_jj_11={hasPattern=true,label="Blue Porcelain",recipe={ceramics_jj_porcelain={need=8,tag=""},minecraft_jj_dye_jj_4={need=1,tag=""}}},
 ceramics_jj_porcelain_jj_12={hasPattern=true,label="Brown Porcelain",recipe={ceramics_jj_porcelain={need=8,tag=""},minecraft_jj_dye_jj_3={need=1,tag=""}}},
 ceramics_jj_porcelain_jj_13={hasPattern=true,label="Green Porcelain",recipe={ceramics_jj_porcelain={need=8,tag=""},minecraft_jj_dye_jj_2={need=1,tag=""}}},
 ceramics_jj_porcelain_jj_14={hasPattern=true,label="Red Porcelain",recipe={ceramics_jj_porcelain={need=8,tag=""},minecraft_jj_dye_jj_1={need=1,tag=""}}},
 ceramics_jj_porcelain_jj_15={hasPattern=true,label="Black Porcelain",recipe={ceramics_jj_porcelain={need=8,tag=""},minecraft_jj_dye={need=1,tag=""}}},
 ceramics_jj_porcelain_jj_2={hasPattern=true,label="Magenta Porcelain",recipe={ceramics_jj_porcelain={need=8,tag=""},minecraft_jj_dye_jj_13={need=1,tag=""}}},
 ceramics_jj_porcelain_jj_3={hasPattern=true,label="Light Blue Porcelain",recipe={ceramics_jj_porcelain={need=8,tag=""},minecraft_jj_dye_jj_12={need=1,tag=""}}},
 ceramics_jj_porcelain_jj_4={hasPattern=true,label="Yellow Porcelain",recipe={ceramics_jj_porcelain={need=8,tag=""},minecraft_jj_dye_jj_11={need=1,tag=""}}},
 ceramics_jj_porcelain_jj_5={hasPattern=true,label="Lime Porcelain",recipe={ceramics_jj_porcelain={need=8,tag=""},minecraft_jj_dye_jj_10={need=1,tag=""}}},
 ceramics_jj_porcelain_jj_6={hasPattern=true,label="Pink Porcelain",recipe={ceramics_jj_porcelain={need=8,tag=""},minecraft_jj_dye_jj_9={need=1,tag=""}}},
 ceramics_jj_porcelain_jj_7={hasPattern=true,label="Gray Porcelain",recipe={ceramics_jj_porcelain={need=8,tag=""},minecraft_jj_dye_jj_8={need=1,tag=""}}},
 ceramics_jj_porcelain_jj_8={hasPattern=true,label="Light Gray Porcelain",recipe={ceramics_jj_porcelain={need=8,tag=""},minecraft_jj_dye_jj_7={need=1,tag=""}}},
 ceramics_jj_porcelain_jj_9={hasPattern=true,label="Cyan Porcelain",recipe={ceramics_jj_porcelain={need=8,tag=""},minecraft_jj_dye_jj_6={need=1,tag=""}}},
 ceramics_jj_rainbow_bricks_stairs={hasPattern=true,label="Rainbow Bricks Stairs",recipe={ceramics_jj_clay_hard_jj_6={need=6,tag=""}}},
 ceramics_jj_rainbow_clay={hasPattern=true,label="Rainbow Porcelain",recipe={ceramics_jj_porcelain={need=6,tag=""},ceramics_jj_rainbow_clay_jj_7={need=1,tag=""},minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_dye_jj_4={need=1,tag=""}}},
 ceramics_jj_rainbow_clay_jj_1={hasPattern=false,label="",recipe={ceramics_jj_rainbow_clay={need=1,tag=""}}},
 ceramics_jj_rainbow_clay_jj_2={hasPattern=false,label="",recipe={ceramics_jj_rainbow_clay_jj_1={need=1,tag=""}}},
 ceramics_jj_rainbow_clay_jj_3={hasPattern=false,label="",recipe={ceramics_jj_rainbow_clay_jj_2={need=1,tag=""}}},
 ceramics_jj_rainbow_clay_jj_4={hasPattern=false,label="",recipe={ceramics_jj_rainbow_clay_jj_3={need=1,tag=""}}},
 ceramics_jj_rainbow_clay_jj_5={hasPattern=false,label="",recipe={ceramics_jj_rainbow_clay_jj_4={need=1,tag=""}}},
 ceramics_jj_rainbow_clay_jj_6={hasPattern=false,label="",recipe={ceramics_jj_rainbow_clay_jj_5={need=1,tag=""}}},
 ceramics_jj_rainbow_clay_jj_7={hasPattern=false,label="",recipe={ceramics_jj_rainbow_clay_jj_6={need=1,tag=""}}},
 ceramics_jj_unfired_clay={hasPattern=true,label="Unfired Clay Bucket",recipe={minecraft_jj_clay_ball={need=3,tag=""}}},
 ceramics_jj_unfired_clay_jj_1={hasPattern=true,label="Unfired Clay Shears",recipe={minecraft_jj_clay_ball={need=2,tag=""}}},
 ceramics_jj_unfired_clay_jj_4={hasPattern=true,label="Unfired Porcelain",recipe={ceramics_jj_clay_soft={need=1,tag=""},minecraft_jj_clay_ball={need=2,tag=""},minecraft_jj_quartz={need=1,tag=""}}},
 ceramics_jj_unfired_clay_jj_5={hasPattern=false,label="",recipe={}},
 ceramics_jj_unfired_clay_jj_6={hasPattern=false,label="",recipe={}},
 ceramics_jj_unfired_clay_jj_7={hasPattern=false,label="",recipe={}},
 ceramics_jj_unfired_clay_jj_8={hasPattern=true,label="Unfired Clay Plate",recipe={minecraft_jj_clay_ball={need=2,tag=""}}},
 ceramics_jj_unfired_clay_jj_9={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_advanced_air_compressor={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_advanced_liquid_compressor={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_advanced_pcb={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_advanced_pressure_tube={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_aerial_interface={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_air_canister={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_air_canister_jj_30000={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_air_cannon={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_air_compressor={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_air_grate_module={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_amadron_tablet={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_amadron_tablet_jj_30000={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_aphorism_tile={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_armor_upgrade={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_assembly_controller={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_assembly_drill={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_assembly_io_unit={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_assembly_laser={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_assembly_platform={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_assembly_program={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_assembly_program_jj_1={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_assembly_program_jj_2={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_block_tracker_upgrade={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_camo_applicator={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_camo_applicator_jj_30000={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_cannon_barrel={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_capacitor={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_charging_module={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_charging_station={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_charging_upgrade={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_compressed_iron_block={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_compressed_iron_gear={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_coordinate_tracker_upgrade={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_creative_compressor={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_creative_upgrade={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_crop_support={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_dispenser_upgrade={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_drone={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_drone_interface={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_electric_compressor={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_electrostatic_compressor={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_elevator_base={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_elevator_caller={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_elevator_frame={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_empty_pcb={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_empty_pcb_jj_100={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_entity_tracker_upgrade={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_failed_pcb={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_fake_ice={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_flow_detector_module={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_fluid_vv_etchacid={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_fluid_vv_fuel={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_fluid_vv_kerosene={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_fluid_vv_lpg={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_fluid_vv_plastic={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_flux_compressor={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_gas_lift={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_gps_area_tool={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_gps_tool={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_gun_ammo={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_gun_ammo_ap={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_gun_ammo_explosive={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_gun_ammo_freezing={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_gun_ammo_incendiary={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_gun_ammo_weighted={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_harvesting_drone={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_heat_frame={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_heat_sink={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_ingot_iron_compressed={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_item_life_upgrade={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_jet_boots_upgrade={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_kerosene_lamp={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_liquid_compressor={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_liquid_hopper={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_logistic_drone={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_logistic_frame_active_provider={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_logistic_frame_default_storage={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_logistic_frame_passive_provider={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_logistic_frame_requester={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_logistic_frame_storage={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_logistics_configurator={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_logistics_configurator_jj_30000={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_logistics_module={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_magnet_upgrade={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_manometer={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_manometer_jj_30000={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_micromissiles={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_minigun={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_minigun_jj_30000={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_network_component={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_network_component_jj_1={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_network_component_jj_2={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_network_component_jj_3={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_network_component_jj_4={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_network_component_jj_5={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_night_vision_upgrade={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_nuke_virus={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_omnidirectional_hopper={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_pcb_blueprint={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_plastic={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_plastic_jj_1={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_plastic_jj_10={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_plastic_jj_11={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_plastic_jj_12={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_plastic_jj_13={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_plastic_jj_14={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_plastic_jj_15={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_plastic_jj_2={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_plastic_jj_3={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_plastic_jj_4={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_plastic_jj_5={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_plastic_jj_6={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_plastic_jj_7={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_plastic_jj_8={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_plastic_jj_9={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_plastic_mixer={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_pneumatic_boots={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_pneumatic_chestplate={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_pneumatic_cylinder={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_pneumatic_door={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_pneumatic_door_base={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_pneumatic_dynamo={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_pneumatic_generator={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_pneumatic_helmet={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_pneumatic_leggings={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_pneumatic_wrench={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_pneumatic_wrench_jj_30000={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_pressure_chamber_glass={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_pressure_chamber_interface={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_pressure_chamber_valve={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_pressure_chamber_wall={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_pressure_gauge={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_pressure_gauge_module={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_pressure_tube={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_printed_circuit_board={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_programmable_controller={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_programmer={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_programming_puzzle_jj_1={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_programming_puzzle_jj_10={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_programming_puzzle_jj_11={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_programming_puzzle_jj_12={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_programming_puzzle_jj_14={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_programming_puzzle_jj_15={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_programming_puzzle_jj_2={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_programming_puzzle_jj_3={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_programming_puzzle_jj_4={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_programming_puzzle_jj_5={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_programming_puzzle_jj_6={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_programming_puzzle_jj_8={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_programming_puzzle_jj_9={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_range_upgrade={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_refinery={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_regulator_tube_module={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_remote={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_safety_tube_module={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_scuba_upgrade={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_search_upgrade={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_security_station={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_security_upgrade={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_seismic_sensor={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_sentry_turret={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_spawner_agitator={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_speed_upgrade={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_stone_base={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_stop_worm={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_thaumcraft_upgrade={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_thermopneumatic_processing_plant={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_transfer_gadget={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_transistor={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_turbine_blade={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_turbine_rotor={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_unassembled_pcb={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_universal_sensor={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_uv_light_box={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_vacuum_pump={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_volume_upgrade={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_vortex_cannon={hasPattern=true,label="",recipe={}},
 pneumaticcraft_jj_vortex_cannon_jj_30000={hasPattern=false,label="",recipe={}},
 pneumaticcraft_jj_vortex_tube={hasPattern=false,label="",recipe={}}
 }