return {
 minewatch_jj_ana_boots={hasPattern=true,label="Ana Stiefel",recipe={minecraft_jj_iron_boots={need=1,tag=""},minewatch_jj_ana_token={need=1,tag=""}}},
 minewatch_jj_ana_chestplate={hasPattern=true,label="Ana Brustpanzer",recipe={minecraft_jj_iron_chestplate={need=1,tag=""},minewatch_jj_ana_token={need=1,tag=""}}},
 minewatch_jj_ana_helmet={hasPattern=true,label="Ana Helm",recipe={minecraft_jj_iron_helmet={need=1,tag=""},minewatch_jj_ana_token={need=1,tag=""}}},
 minewatch_jj_ana_leggings={hasPattern=true,label="Ana Beinschutz",recipe={minecraft_jj_iron_leggings={need=1,tag=""},minewatch_jj_ana_token={need=1,tag=""}}},
 minewatch_jj_ana_token={hasPattern=false,label="",recipe={}},
 minewatch_jj_ana_weapon={hasPattern=true,label="Ana's Biotisches Gewehr",recipe={minewatch_jj_ana_token={need=1,tag=""}}},
 minewatch_jj_bastion_boots={hasPattern=true,label="Bastion Stiefel",recipe={minecraft_jj_iron_boots={need=1,tag=""},minewatch_jj_bastion_token={need=1,tag=""}}},
 minewatch_jj_bastion_chestplate={hasPattern=true,label="Bastion Brustpanzer",recipe={minecraft_jj_iron_chestplate={need=1,tag=""},minewatch_jj_bastion_token={need=1,tag=""}}},
 minewatch_jj_bastion_helmet={hasPattern=true,label="Bastion Helm",recipe={minecraft_jj_iron_helmet={need=1,tag=""},minewatch_jj_bastion_token={need=1,tag=""}}},
 minewatch_jj_bastion_leggings={hasPattern=true,label="Bastion Beinschutz",recipe={minecraft_jj_iron_leggings={need=1,tag=""},minewatch_jj_bastion_token={need=1,tag=""}}},
 minewatch_jj_bastion_token={hasPattern=false,label="",recipe={}},
 minewatch_jj_bastion_weapon={hasPattern=true,label="Bastion's Maschinengewehr",recipe={minewatch_jj_bastion_token={need=1,tag=""}}},
 minewatch_jj_death_block={hasPattern=false,label="",recipe={}},
 minewatch_jj_doomfist_boots={hasPattern=true,label="Doomfist Stiefel",recipe={minecraft_jj_iron_boots={need=1,tag=""},minewatch_jj_doomfist_token={need=1,tag=""}}},
 minewatch_jj_doomfist_chestplate={hasPattern=true,label="Doomfist Brustpanzer",recipe={minecraft_jj_iron_chestplate={need=1,tag=""},minewatch_jj_doomfist_token={need=1,tag=""}}},
 minewatch_jj_doomfist_helmet={hasPattern=true,label="Doomfist Helm",recipe={minecraft_jj_iron_helmet={need=1,tag=""},minewatch_jj_doomfist_token={need=1,tag=""}}},
 minewatch_jj_doomfist_leggings={hasPattern=true,label="Doomfist Beinschutz",recipe={minecraft_jj_iron_leggings={need=1,tag=""},minewatch_jj_doomfist_token={need=1,tag=""}}},
 minewatch_jj_doomfist_token={hasPattern=false,label="",recipe={}},
 minewatch_jj_doomfist_weapon={hasPattern=true,label="Doomfist's Handschuh",recipe={minewatch_jj_doomfist_token={need=1,tag=""}}},
 minewatch_jj_genji_boots={hasPattern=true,label="Genji Stiefel",recipe={minecraft_jj_iron_boots={need=1,tag=""},minewatch_jj_genji_token={need=1,tag=""}}},
 minewatch_jj_genji_chestplate={hasPattern=true,label="Genji Brustpanzer",recipe={minecraft_jj_iron_chestplate={need=1,tag=""},minewatch_jj_genji_token={need=1,tag=""}}},
 minewatch_jj_genji_helmet={hasPattern=true,label="Genji Helm",recipe={minecraft_jj_iron_helmet={need=1,tag=""},minewatch_jj_genji_token={need=1,tag=""}}},
 minewatch_jj_genji_leggings={hasPattern=true,label="Genji Beinschutz",recipe={minecraft_jj_iron_leggings={need=1,tag=""},minewatch_jj_genji_token={need=1,tag=""}}},
 minewatch_jj_genji_shuriken_single={hasPattern=false,label="",recipe={}},
 minewatch_jj_genji_token={hasPattern=false,label="",recipe={}},
 minewatch_jj_genji_weapon={hasPattern=true,label="Genji's Shuriken",recipe={minewatch_jj_genji_token={need=1,tag=""}}},
 minewatch_jj_hanzo_boots={hasPattern=true,label="Hanzo Stiefel",recipe={minecraft_jj_iron_boots={need=1,tag=""},minewatch_jj_hanzo_token={need=1,tag=""}}},
 minewatch_jj_hanzo_chestplate={hasPattern=true,label="Hanzo Brustpanzer",recipe={minecraft_jj_iron_chestplate={need=1,tag=""},minewatch_jj_hanzo_token={need=1,tag=""}}},
 minewatch_jj_hanzo_helmet={hasPattern=true,label="Hanzo Helm",recipe={minecraft_jj_iron_helmet={need=1,tag=""},minewatch_jj_hanzo_token={need=1,tag=""}}},
 minewatch_jj_hanzo_leggings={hasPattern=true,label="Hanzo Beinschutz",recipe={minecraft_jj_iron_leggings={need=1,tag=""},minewatch_jj_hanzo_token={need=1,tag=""}}},
 minewatch_jj_hanzo_token={hasPattern=false,label="",recipe={}},
 minewatch_jj_hanzo_weapon={hasPattern=true,label="Hanzo's Sturmbogen",recipe={minewatch_jj_hanzo_token={need=1,tag=""}}},
 minewatch_jj_health_pack_large={hasPattern=true,label="großes Heilungspaket",recipe={immersiveengineering_jj_metal_jj_39={need=3,tag=""},minecraft_jj_cake={need=1,tag=""},minecraft_jj_light_weighted_pressure_plate={need=1,tag=""}}},
 minewatch_jj_health_pack_small={hasPattern=true,label="kleines Heilungspaket",recipe={immersiveengineering_jj_metal_jj_39={need=3,tag=""},minecraft_jj_carrot={need=1,tag=""},minecraft_jj_light_weighted_pressure_plate={need=1,tag=""}}},
 minewatch_jj_junkrat_boots={hasPattern=true,label="Junkrat Stiefel",recipe={minecraft_jj_iron_boots={need=1,tag=""},minewatch_jj_junkrat_token={need=1,tag=""}}},
 minewatch_jj_junkrat_chestplate={hasPattern=true,label="Junkrat Brustpanzer",recipe={minecraft_jj_iron_chestplate={need=1,tag=""},minewatch_jj_junkrat_token={need=1,tag=""}}},
 minewatch_jj_junkrat_helmet={hasPattern=true,label="Junkrat Helm",recipe={minecraft_jj_iron_helmet={need=1,tag=""},minewatch_jj_junkrat_token={need=1,tag=""}}},
 minewatch_jj_junkrat_leggings={hasPattern=true,label="Junkrat Beinschutz",recipe={minecraft_jj_iron_leggings={need=1,tag=""},minewatch_jj_junkrat_token={need=1,tag=""}}},
 minewatch_jj_junkrat_token={hasPattern=false,label="",recipe={}},
 minewatch_jj_junkrat_trigger={hasPattern=false,label="",recipe={}},
 minewatch_jj_junkrat_weapon={hasPattern=true,label="Junkrat's Granatwerfer",recipe={minewatch_jj_junkrat_token={need=1,tag=""}}},
 minewatch_jj_lucio_boots={hasPattern=true,label="Lucio Stiefel",recipe={minecraft_jj_iron_boots={need=1,tag=""},minewatch_jj_lucio_token={need=1,tag=""}}},
 minewatch_jj_lucio_chestplate={hasPattern=true,label="Lucio Brustpanzer",recipe={minecraft_jj_iron_chestplate={need=1,tag=""},minewatch_jj_lucio_token={need=1,tag=""}}},
 minewatch_jj_lucio_helmet={hasPattern=true,label="Lucio Helm",recipe={minecraft_jj_iron_helmet={need=1,tag=""},minewatch_jj_lucio_token={need=1,tag=""}}},
 minewatch_jj_lucio_leggings={hasPattern=true,label="Lucio Beinschutz",recipe={minecraft_jj_iron_leggings={need=1,tag=""},minewatch_jj_lucio_token={need=1,tag=""}}},
 minewatch_jj_lucio_token={hasPattern=false,label="",recipe={}},
 minewatch_jj_lucio_weapon={hasPattern=true,label="Lucio's Schallverstärker",recipe={minewatch_jj_lucio_token={need=1,tag=""}}},
 minewatch_jj_mccree_boots={hasPattern=true,label="McCree Stiefel",recipe={minecraft_jj_iron_boots={need=1,tag=""},minewatch_jj_mccree_token={need=1,tag=""}}},
 minewatch_jj_mccree_chestplate={hasPattern=true,label="McCree Brustpanzer",recipe={minecraft_jj_iron_chestplate={need=1,tag=""},minewatch_jj_mccree_token={need=1,tag=""}}},
 minewatch_jj_mccree_helmet={hasPattern=true,label="McCree Helm",recipe={minecraft_jj_iron_helmet={need=1,tag=""},minewatch_jj_mccree_token={need=1,tag=""}}},
 minewatch_jj_mccree_leggings={hasPattern=true,label="McCree Beinschutz",recipe={minecraft_jj_iron_leggings={need=1,tag=""},minewatch_jj_mccree_token={need=1,tag=""}}},
 minewatch_jj_mccree_token={hasPattern=false,label="",recipe={}},
 minewatch_jj_mccree_weapon={hasPattern=true,label="McCree's Friedensstifter",recipe={minewatch_jj_mccree_token={need=1,tag=""}}},
 minewatch_jj_mei_boots={hasPattern=true,label="Mei Stiefel",recipe={minecraft_jj_iron_boots={need=1,tag=""},minewatch_jj_mei_token={need=1,tag=""}}},
 minewatch_jj_mei_chestplate={hasPattern=true,label="Mei Brustpanzer",recipe={minecraft_jj_iron_chestplate={need=1,tag=""},minewatch_jj_mei_token={need=1,tag=""}}},
 minewatch_jj_mei_helmet={hasPattern=true,label="Mei Helm",recipe={minecraft_jj_iron_helmet={need=1,tag=""},minewatch_jj_mei_token={need=1,tag=""}}},
 minewatch_jj_mei_leggings={hasPattern=true,label="Mei Beinschutz",recipe={minecraft_jj_iron_leggings={need=1,tag=""},minewatch_jj_mei_token={need=1,tag=""}}},
 minewatch_jj_mei_token={hasPattern=false,label="",recipe={}},
 minewatch_jj_mei_weapon={hasPattern=true,label="Mei's Endothermischer Strahler",recipe={minewatch_jj_mei_token={need=1,tag=""}}},
 minewatch_jj_mercy_boots={hasPattern=true,label="Mercy Stiefel",recipe={minecraft_jj_iron_boots={need=1,tag=""},minewatch_jj_mercy_token={need=1,tag=""}}},
 minewatch_jj_mercy_chestplate={hasPattern=true,label="Mercy Brustpanzer",recipe={minecraft_jj_iron_chestplate={need=1,tag=""},minewatch_jj_mercy_token={need=1,tag=""}}},
 minewatch_jj_mercy_helmet={hasPattern=true,label="Mercy Helm",recipe={minecraft_jj_iron_helmet={need=1,tag=""},minewatch_jj_mercy_token={need=1,tag=""}}},
 minewatch_jj_mercy_leggings={hasPattern=true,label="Mercy Beinschutz",recipe={minecraft_jj_iron_leggings={need=1,tag=""},minewatch_jj_mercy_token={need=1,tag=""}}},
 minewatch_jj_mercy_token={hasPattern=false,label="",recipe={}},
 minewatch_jj_mercy_weapon={hasPattern=true,label="Caduceus Staff",recipe={minewatch_jj_mercy_token={need=1,tag=""}}},
 minewatch_jj_moira_boots={hasPattern=true,label="Moira Stiefel",recipe={minecraft_jj_iron_boots={need=1,tag=""},minewatch_jj_moira_token={need=1,tag=""}}},
 minewatch_jj_moira_chestplate={hasPattern=true,label="Moira Brustpanzer",recipe={minecraft_jj_iron_chestplate={need=1,tag=""},minewatch_jj_moira_token={need=1,tag=""}}},
 minewatch_jj_moira_helmet={hasPattern=true,label="Moira Helm",recipe={minecraft_jj_iron_helmet={need=1,tag=""},minewatch_jj_moira_token={need=1,tag=""}}},
 minewatch_jj_moira_leggings={hasPattern=true,label="Moira Beinschutz",recipe={minecraft_jj_iron_leggings={need=1,tag=""},minewatch_jj_moira_token={need=1,tag=""}}},
 minewatch_jj_moira_token={hasPattern=false,label="",recipe={}},
 minewatch_jj_moira_weapon={hasPattern=true,label="Moira's Biotische Hand",recipe={minewatch_jj_moira_token={need=1,tag=""}}},
 minewatch_jj_pharah_boots={hasPattern=true,label="Pharah Stiefel",recipe={minecraft_jj_iron_boots={need=1,tag=""},minewatch_jj_pharah_token={need=1,tag=""}}},
 minewatch_jj_pharah_chestplate={hasPattern=true,label="Pharah Brustpanzer",recipe={minecraft_jj_iron_chestplate={need=1,tag=""},minewatch_jj_pharah_token={need=1,tag=""}}},
 minewatch_jj_pharah_helmet={hasPattern=true,label="Pharah Helm",recipe={minecraft_jj_iron_helmet={need=1,tag=""},minewatch_jj_pharah_token={need=1,tag=""}}},
 minewatch_jj_pharah_leggings={hasPattern=true,label="Pharah Beinschutz",recipe={minecraft_jj_iron_leggings={need=1,tag=""},minewatch_jj_pharah_token={need=1,tag=""}}},
 minewatch_jj_pharah_token={hasPattern=false,label="",recipe={}},
 minewatch_jj_pharah_weapon={hasPattern=true,label="Pharah's Raketenwerfer",recipe={minewatch_jj_pharah_token={need=1,tag=""}}},
 minewatch_jj_push_block={hasPattern=true,label="Schiebeblock",recipe={darkutils_jj_trap_move={need=1,tag=""},minecraft_jj_glass={need=1,tag=""}}},
 minewatch_jj_reaper_boots={hasPattern=true,label="Reaper Stiefel",recipe={minecraft_jj_iron_boots={need=1,tag=""},minewatch_jj_reaper_token={need=1,tag=""}}},
 minewatch_jj_reaper_chestplate={hasPattern=true,label="Reaper Brustpanzer",recipe={minecraft_jj_iron_chestplate={need=1,tag=""},minewatch_jj_reaper_token={need=1,tag=""}}},
 minewatch_jj_reaper_helmet={hasPattern=true,label="Reaper Helm",recipe={minecraft_jj_iron_helmet={need=1,tag=""},minewatch_jj_reaper_token={need=1,tag=""}}},
 minewatch_jj_reaper_leggings={hasPattern=true,label="Reaper Beinschutz",recipe={minecraft_jj_iron_leggings={need=1,tag=""},minewatch_jj_reaper_token={need=1,tag=""}}},
 minewatch_jj_reaper_token={hasPattern=false,label="",recipe={}},
 minewatch_jj_reaper_weapon={hasPattern=true,label="Reaper's Infernoschrotflinten",recipe={minewatch_jj_reaper_token={need=1,tag=""}}},
 minewatch_jj_reinhardt_boots={hasPattern=true,label="Reinhardt Stiefel",recipe={minecraft_jj_iron_boots={need=1,tag=""},minewatch_jj_reinhardt_token={need=1,tag=""}}},
 minewatch_jj_reinhardt_chestplate={hasPattern=true,label="Reinhardt Brustpanzer",recipe={minecraft_jj_iron_chestplate={need=1,tag=""},minewatch_jj_reinhardt_token={need=1,tag=""}}},
 minewatch_jj_reinhardt_helmet={hasPattern=true,label="Reinhardt Helm",recipe={minecraft_jj_iron_helmet={need=1,tag=""},minewatch_jj_reinhardt_token={need=1,tag=""}}},
 minewatch_jj_reinhardt_leggings={hasPattern=true,label="Reinhardt Beinschutz",recipe={minecraft_jj_iron_leggings={need=1,tag=""},minewatch_jj_reinhardt_token={need=1,tag=""}}},
 minewatch_jj_reinhardt_token={hasPattern=false,label="",recipe={}},
 minewatch_jj_reinhardt_weapon={hasPattern=true,label="Reinhardt's Rakentenhammer",recipe={minewatch_jj_reinhardt_token={need=1,tag=""}}},
 minewatch_jj_roadhog_boots={hasPattern=true,label="Roadhog Stiefel",recipe={minecraft_jj_iron_boots={need=1,tag=""},minewatch_jj_roadhog_token={need=1,tag=""}}},
 minewatch_jj_roadhog_chestplate={hasPattern=true,label="Roadhog Brustpanzer",recipe={minecraft_jj_iron_chestplate={need=1,tag=""},minewatch_jj_roadhog_token={need=1,tag=""}}},
 minewatch_jj_roadhog_health={hasPattern=true,label="Roadhog's Lebenskanister",recipe={minewatch_jj_health_pack_small={need=1,tag=""},minewatch_jj_roadhog_token={need=1,tag=""}}},
 minewatch_jj_roadhog_helmet={hasPattern=true,label="Roadhog Helm",recipe={minecraft_jj_iron_helmet={need=1,tag=""},minewatch_jj_roadhog_token={need=1,tag=""}}},
 minewatch_jj_roadhog_leggings={hasPattern=true,label="Roadhog Beinschutz",recipe={minecraft_jj_iron_leggings={need=1,tag=""},minewatch_jj_roadhog_token={need=1,tag=""}}},
 minewatch_jj_roadhog_token={hasPattern=false,label="",recipe={}},
 minewatch_jj_roadhog_weapon={hasPattern=true,label="Roadhog's Schrottflinte",recipe={minewatch_jj_roadhog_token={need=1,tag=""}}},
 minewatch_jj_soldier76_boots={hasPattern=true,label="Soldier 76 Stiefel",recipe={minecraft_jj_iron_boots={need=1,tag=""},minewatch_jj_soldier76_token={need=1,tag=""}}},
 minewatch_jj_soldier76_chestplate={hasPattern=true,label="Soldier 76 Brustpanzer",recipe={minecraft_jj_iron_chestplate={need=1,tag=""},minewatch_jj_soldier76_token={need=1,tag=""}}},
 minewatch_jj_soldier76_helmet={hasPattern=true,label="Soldier 76 Helm",recipe={minecraft_jj_iron_helmet={need=1,tag=""},minewatch_jj_soldier76_token={need=1,tag=""}}},
 minewatch_jj_soldier76_leggings={hasPattern=true,label="Soldier 76 Beinschutz",recipe={minecraft_jj_iron_leggings={need=1,tag=""},minewatch_jj_soldier76_token={need=1,tag=""}}},
 minewatch_jj_soldier76_token={hasPattern=false,label="",recipe={}},
 minewatch_jj_soldier76_weapon={hasPattern=true,label="Soldier 76's Impulsgewehr",recipe={minewatch_jj_soldier76_token={need=1,tag=""}}},
 minewatch_jj_sombra_boots={hasPattern=true,label="Sombra Stiefel",recipe={minecraft_jj_iron_boots={need=1,tag=""},minewatch_jj_sombra_token={need=1,tag=""}}},
 minewatch_jj_sombra_chestplate={hasPattern=true,label="Sombra Brustpanzer",recipe={minecraft_jj_iron_chestplate={need=1,tag=""},minewatch_jj_sombra_token={need=1,tag=""}}},
 minewatch_jj_sombra_hack={hasPattern=false,label="",recipe={}},
 minewatch_jj_sombra_helmet={hasPattern=true,label="Sombra Helm",recipe={minecraft_jj_iron_helmet={need=1,tag=""},minewatch_jj_sombra_token={need=1,tag=""}}},
 minewatch_jj_sombra_leggings={hasPattern=true,label="Sombra Beinschutz",recipe={minecraft_jj_iron_leggings={need=1,tag=""},minewatch_jj_sombra_token={need=1,tag=""}}},
 minewatch_jj_sombra_token={hasPattern=false,label="",recipe={}},
 minewatch_jj_sombra_weapon={hasPattern=true,label="Sombra's Maschinenpistole",recipe={minewatch_jj_sombra_token={need=1,tag=""}}},
 minewatch_jj_team_spawn={hasPattern=true,label="Teamspawn",recipe={minewatch_jj_team_stick={need=1,tag=""}}},
 minewatch_jj_team_stick={hasPattern=true,label="Team Helfer",recipe={minecraft_jj_stick={need=2,tag=""},minewatch_jj_ana_token={need=1,tag=""},minewatch_jj_genji_token={need=1,tag=""},minewatch_jj_hanzo_token={need=1,tag=""},minewatch_jj_mccree_token={need=1,tag=""},minewatch_jj_reaper_token={need=1,tag=""},minewatch_jj_reinhardt_token={need=1,tag=""},minewatch_jj_soldier76_token={need=1,tag=""}}},
 minewatch_jj_tracer_boots={hasPattern=true,label="Tracer Stiefel",recipe={minecraft_jj_iron_boots={need=1,tag=""},minewatch_jj_tracer_token={need=1,tag=""}}},
 minewatch_jj_tracer_chestplate={hasPattern=true,label="Tracer Brustpanzer",recipe={minecraft_jj_iron_chestplate={need=1,tag=""},minewatch_jj_tracer_token={need=1,tag=""}}},
 minewatch_jj_tracer_helmet={hasPattern=true,label="Tracer Helm",recipe={minecraft_jj_iron_helmet={need=1,tag=""},minewatch_jj_tracer_token={need=1,tag=""}}},
 minewatch_jj_tracer_leggings={hasPattern=true,label="Tracer Beinschutz",recipe={minecraft_jj_iron_leggings={need=1,tag=""},minewatch_jj_tracer_token={need=1,tag=""}}},
 minewatch_jj_tracer_token={hasPattern=false,label="",recipe={}},
 minewatch_jj_tracer_weapon={hasPattern=true,label="Tracer's Impulspistolen",recipe={minewatch_jj_tracer_token={need=1,tag=""}}},
 minewatch_jj_widowmaker_boots={hasPattern=true,label="Widowmaker Stiefel",recipe={minecraft_jj_iron_boots={need=1,tag=""},minewatch_jj_widowmaker_token={need=1,tag=""}}},
 minewatch_jj_widowmaker_chestplate={hasPattern=true,label="Widowmaker Brustpanzer",recipe={minecraft_jj_iron_chestplate={need=1,tag=""},minewatch_jj_widowmaker_token={need=1,tag=""}}},
 minewatch_jj_widowmaker_helmet={hasPattern=true,label="Widowmaker Helm",recipe={minecraft_jj_iron_helmet={need=1,tag=""},minewatch_jj_widowmaker_token={need=1,tag=""}}},
 minewatch_jj_widowmaker_leggings={hasPattern=true,label="Widowmaker Beinschutz",recipe={minecraft_jj_iron_leggings={need=1,tag=""},minewatch_jj_widowmaker_token={need=1,tag=""}}},
 minewatch_jj_widowmaker_token={hasPattern=false,label="",recipe={}},
 minewatch_jj_widowmaker_weapon={hasPattern=true,label="Witwenkuss",recipe={minewatch_jj_widowmaker_token={need=1,tag=""}}},
 minewatch_jj_wild_card_token={hasPattern=false,label="",recipe={}},
 minewatch_jj_zenyatta_boots={hasPattern=true,label="Zenyatta Stiefel",recipe={minecraft_jj_iron_boots={need=1,tag=""},minewatch_jj_zenyatta_token={need=1,tag=""}}},
 minewatch_jj_zenyatta_chestplate={hasPattern=true,label="Zenyatta Brustpanzer",recipe={minecraft_jj_iron_chestplate={need=1,tag=""},minewatch_jj_zenyatta_token={need=1,tag=""}}},
 minewatch_jj_zenyatta_helmet={hasPattern=true,label="Zenyatta Helm",recipe={minecraft_jj_iron_helmet={need=1,tag=""},minewatch_jj_zenyatta_token={need=1,tag=""}}},
 minewatch_jj_zenyatta_leggings={hasPattern=true,label="Zenyatta Beinschutz",recipe={minecraft_jj_iron_leggings={need=1,tag=""},minewatch_jj_zenyatta_token={need=1,tag=""}}},
 minewatch_jj_zenyatta_token={hasPattern=false,label="",recipe={}},
 minewatch_jj_zenyatta_weapon={hasPattern=true,label="Zenyatta's Sphäre der Zerstörung",recipe={minewatch_jj_zenyatta_token={need=1,tag=""}}},
 mores_jj_aikar_axe={hasPattern=false,label="",recipe={}},
 mores_jj_aikar_dust={hasPattern=true,label="Aikar Dust",recipe={mores_jj_aurine_dust={need=1,tag=""},mores_jj_draxate_dust={need=1,tag=""},mores_jj_phantom_shard={need=1,tag=""}}},
 mores_jj_aikar_ingot={hasPattern=false,label="",recipe={}},
 mores_jj_aikar_pickaxe={hasPattern=true,label="Aikar Pickaxe",recipe={minecraft_jj_stick={need=2,tag=""},mores_jj_aikar_ingot={need=3,tag=""}}},
 mores_jj_aikar_shovel={hasPattern=true,label="Aikar Shovel",recipe={minecraft_jj_stick={need=2,tag=""},mores_jj_aikar_ingot={need=1,tag=""}}},
 mores_jj_aikar_sword={hasPattern=false,label="",recipe={}},
 mores_jj_aoci_axe={hasPattern=false,label="",recipe={}},
 mores_jj_aoci_dust={hasPattern=true,label="Aoci Dust",recipe={mores_jj_ayzanite_dust={need=1,tag=""},mores_jj_draxate_dust={need=1,tag=""},mores_jj_phantom_shard={need=1,tag=""}}},
 mores_jj_aoci_ingot={hasPattern=false,label="",recipe={}},
 mores_jj_aoci_pickaxe={hasPattern=true,label="Aoci Pickaxe",recipe={minecraft_jj_stick={need=2,tag=""},mores_jj_aoci_ingot={need=3,tag=""}}},
 mores_jj_aoci_shovel={hasPattern=true,label="Aoci Shovel",recipe={minecraft_jj_stick={need=2,tag=""},mores_jj_aoci_ingot={need=1,tag=""}}},
 mores_jj_aoci_sword={hasPattern=false,label="",recipe={}},
 mores_jj_aryxi_axe={hasPattern=false,label="",recipe={}},
 mores_jj_aryxi_dust={hasPattern=true,label="Aryxi Dust",recipe={mores_jj_eukavoynt_dust={need=1,tag=""},mores_jj_iturite_dust={need=1,tag=""},mores_jj_phantom_shard={need=1,tag=""}}},
 mores_jj_aryxi_ingot={hasPattern=false,label="",recipe={}},
 mores_jj_aryxi_pickaxe={hasPattern=false,label="",recipe={}},
 mores_jj_aryxi_shovel={hasPattern=true,label="Aryxi Shovel",recipe={minecraft_jj_stick={need=2,tag=""},mores_jj_aryxi_ingot={need=1,tag=""}}},
 mores_jj_aryxi_sword={hasPattern=true,label="Aryxi Sword",recipe={minecraft_jj_stick={need=1,tag=""},mores_jj_aryxi_ingot={need=2,tag=""}}},
 mores_jj_ataru_dust={hasPattern=false,label="",recipe={}},
 mores_jj_ataru_ingot={hasPattern=false,label="",recipe={}},
 mores_jj_audu_axe={hasPattern=false,label="",recipe={}},
 mores_jj_audu_dust={hasPattern=true,label="Audu Dust",recipe={mores_jj_draxate_dust={need=1,tag=""},mores_jj_iturite_dust={need=1,tag=""},mores_jj_phantom_shard={need=1,tag=""}}},
 mores_jj_audu_ingot={hasPattern=false,label="",recipe={}},
 mores_jj_audu_pickaxe={hasPattern=true,label="Audu Pickaxe",recipe={minecraft_jj_stick={need=2,tag=""},mores_jj_audu_ingot={need=3,tag=""}}},
 mores_jj_audu_shovel={hasPattern=true,label="Audu Shovel",recipe={minecraft_jj_stick={need=2,tag=""},mores_jj_audu_ingot={need=1,tag=""}}},
 mores_jj_audu_sword={hasPattern=false,label="",recipe={}},
 mores_jj_aurine_dust={hasPattern=false,label="",recipe={immersiveengineering_jj_tool={need=1,tag=""},mores_jj_aurine_ore={need=1,tag=""}}},
 mores_jj_aurine_ore={hasPattern=false,label="",recipe={}},
 mores_jj_ayzanite_dust={hasPattern=false,label="",recipe={immersiveengineering_jj_tool={need=1,tag=""},mores_jj_ayzanite_ore={need=1,tag=""}}},
 mores_jj_ayzanite_ore={hasPattern=false,label="",recipe={}},
 mores_jj_bydoom_axe={hasPattern=true,label="Bydoom Axe",recipe={minecraft_jj_stick={need=2,tag=""},mores_jj_bydoom_ingot={need=3,tag=""}}},
 mores_jj_bydoom_dust={hasPattern=true,label="Bydoom Dust",recipe={mores_jj_aurine_dust={need=1,tag=""},mores_jj_nodemite_dust={need=1,tag=""},mores_jj_phantom_shard={need=1,tag=""}}},
 mores_jj_bydoom_ingot={hasPattern=false,label="",recipe={}},
 mores_jj_bydoom_pickaxe={hasPattern=true,label="Bydoom Pickaxe",recipe={minecraft_jj_stick={need=2,tag=""},mores_jj_bydoom_ingot={need=3,tag=""}}},
 mores_jj_bydoom_shovel={hasPattern=true,label="Bydoom Shovel",recipe={minecraft_jj_stick={need=2,tag=""},mores_jj_bydoom_ingot={need=1,tag=""}}},
 mores_jj_bydoom_sword={hasPattern=true,label="Bydoom Sword",recipe={minecraft_jj_stick={need=1,tag=""},mores_jj_bydoom_ingot={need=2,tag=""}}},
 mores_jj_draxate_dust={hasPattern=false,label="",recipe={immersiveengineering_jj_tool={need=1,tag=""},mores_jj_draxate_ore={need=1,tag=""}}},
 mores_jj_draxate_ore={hasPattern=false,label="",recipe={}},
 mores_jj_duxirete_axe={hasPattern=false,label="",recipe={}},
 mores_jj_duxirete_dust={hasPattern=true,label="Duxirete Dust",recipe={mores_jj_draxate_dust={need=1,tag=""},mores_jj_nodemite_dust={need=1,tag=""},mores_jj_phantom_shard={need=1,tag=""}}},
 mores_jj_duxirete_ingot={hasPattern=false,label="",recipe={}},
 mores_jj_duxirete_pickaxe={hasPattern=true,label="Duxirete Pickaxe",recipe={minecraft_jj_stick={need=2,tag=""},mores_jj_duxirete_ingot={need=3,tag=""}}},
 mores_jj_duxirete_shovel={hasPattern=true,label="Duxirete Shovel",recipe={minecraft_jj_stick={need=2,tag=""},mores_jj_duxirete_ingot={need=1,tag=""}}},
 mores_jj_duxirete_sword={hasPattern=false,label="",recipe={}},
 mores_jj_eukavoynt_dust={hasPattern=false,label="",recipe={mores_jj_eukavoynt_ore={need=1,tag=""},ore_jj_dustPetrotheum={need=1,tag=""}}},
 mores_jj_eukavoynt_ore={hasPattern=false,label="",recipe={}},
 mores_jj_irine_axe={hasPattern=false,label="",recipe={}},
 mores_jj_irine_dust={hasPattern=true,label="Irine Dust",recipe={mores_jj_aurine_dust={need=1,tag=""},mores_jj_iturite_dust={need=1,tag=""},mores_jj_phantom_shard={need=1,tag=""}}},
 mores_jj_irine_ingot={hasPattern=false,label="",recipe={}},
 mores_jj_irine_pickaxe={hasPattern=false,label="",recipe={}},
 mores_jj_irine_shovel={hasPattern=false,label="",recipe={}},
 mores_jj_irine_sword={hasPattern=false,label="",recipe={}},
 mores_jj_iturite_dust={hasPattern=false,label="",recipe={immersiveengineering_jj_tool={need=1,tag=""},mores_jj_iturite_ore={need=1,tag=""}}},
 mores_jj_iturite_ore={hasPattern=false,label="",recipe={}},
 mores_jj_josawriline_axe={hasPattern=false,label="",recipe={}},
 mores_jj_josawriline_dust={hasPattern=true,label="Josawriline Dust",recipe={mores_jj_aurine_dust={need=1,tag=""},mores_jj_eukavoynt_dust={need=1,tag=""},mores_jj_phantom_shard={need=1,tag=""}}},
 mores_jj_josawriline_ingot={hasPattern=false,label="",recipe={}},
 mores_jj_josawriline_pickaxe={hasPattern=false,label="",recipe={}},
 mores_jj_josawriline_shovel={hasPattern=false,label="",recipe={}},
 mores_jj_josawriline_sword={hasPattern=true,label="Josawriline Sword",recipe={minecraft_jj_stick={need=1,tag=""},mores_jj_josawriline_ingot={need=2,tag=""}}},
 mores_jj_murol_axe={hasPattern=true,label="Murol Axe",recipe={minecraft_jj_stick={need=2,tag=""},mores_jj_murol_ingot={need=3,tag=""}}},
 mores_jj_murol_dust={hasPattern=true,label="Murol Dust",recipe={mores_jj_ayzanite_dust={need=1,tag=""},mores_jj_nodemite_dust={need=1,tag=""},mores_jj_phantom_shard={need=1,tag=""}}},
 mores_jj_murol_ingot={hasPattern=false,label="",recipe={}},
 mores_jj_murol_pickaxe={hasPattern=true,label="Murol Pickaxe",recipe={minecraft_jj_stick={need=2,tag=""},mores_jj_murol_ingot={need=3,tag=""}}},
 mores_jj_murol_shovel={hasPattern=true,label="Murol Shovel",recipe={minecraft_jj_stick={need=2,tag=""},mores_jj_murol_ingot={need=1,tag=""}}},
 mores_jj_murol_sword={hasPattern=true,label="Murol Sword",recipe={minecraft_jj_stick={need=1,tag=""},mores_jj_murol_ingot={need=2,tag=""}}},
 mores_jj_nether_aurine_ore={hasPattern=false,label="",recipe={}},
 mores_jj_nether_ayzanite_ore={hasPattern=false,label="",recipe={}},
 mores_jj_nether_draxate_ore={hasPattern=false,label="",recipe={}},
 mores_jj_nether_eukavoynt_ore={hasPattern=false,label="",recipe={}},
 mores_jj_nether_iturite_ore={hasPattern=false,label="",recipe={}},
 mores_jj_nether_nodemite_ore={hasPattern=false,label="",recipe={}},
 mores_jj_nether_phantom_ore={hasPattern=false,label="",recipe={minecraft_jj_netherrack={need=1,tag=""},mores_jj_phantom_shard={need=4,tag=""}}},
 mores_jj_nether_sivenium_ore={hasPattern=false,label="",recipe={}},
 mores_jj_nodemite_dust={hasPattern=false,label="",recipe={immersiveengineering_jj_tool={need=1,tag=""},mores_jj_nodemite_ore={need=1,tag=""}}},
 mores_jj_nodemite_ore={hasPattern=false,label="",recipe={}},
 mores_jj_odeznum_axe={hasPattern=true,label="Odeznum Axe",recipe={minecraft_jj_stick={need=2,tag=""},mores_jj_odeznum_ingot={need=3,tag=""}}},
 mores_jj_odeznum_dust={hasPattern=true,label="Odeznum Dust",recipe={mores_jj_nodemite_dust={need=1,tag=""},mores_jj_phantom_shard={need=1,tag=""},mores_jj_sivenium_dust={need=1,tag=""}}},
 mores_jj_odeznum_ingot={hasPattern=false,label="",recipe={}},
 mores_jj_odeznum_pickaxe={hasPattern=true,label="Odeznum Pickaxe",recipe={minecraft_jj_stick={need=2,tag=""},mores_jj_odeznum_ingot={need=3,tag=""}}},
 mores_jj_odeznum_shovel={hasPattern=true,label="Odeznum Shovel",recipe={minecraft_jj_stick={need=2,tag=""},mores_jj_odeznum_ingot={need=1,tag=""}}},
 mores_jj_odeznum_sword={hasPattern=true,label="Odeznum Sword",recipe={minecraft_jj_stick={need=1,tag=""},mores_jj_odeznum_ingot={need=2,tag=""}}},
 mores_jj_oivi_axe={hasPattern=true,label="Oivi Axe",recipe={minecraft_jj_stick={need=2,tag=""},mores_jj_oivi_ingot={need=3,tag=""}}},
 mores_jj_oivi_dust={hasPattern=true,label="Oivi Dust",recipe={mores_jj_iturite_dust={need=1,tag=""},mores_jj_nodemite_dust={need=1,tag=""},mores_jj_phantom_shard={need=1,tag=""}}},
 mores_jj_oivi_ingot={hasPattern=false,label="",recipe={}},
 mores_jj_oivi_pickaxe={hasPattern=true,label="Oivi Pickaxe",recipe={minecraft_jj_stick={need=2,tag=""},mores_jj_oivi_ingot={need=3,tag=""}}},
 mores_jj_oivi_shovel={hasPattern=true,label="Oivi Shovel",recipe={minecraft_jj_stick={need=2,tag=""},mores_jj_oivi_ingot={need=1,tag=""}}},
 mores_jj_oivi_sword={hasPattern=true,label="Oivi Sword",recipe={minecraft_jj_stick={need=1,tag=""},mores_jj_oivi_ingot={need=2,tag=""}}},
 mores_jj_oivywon_axe={hasPattern=false,label="",recipe={}},
 mores_jj_oivywon_dust={hasPattern=true,label="Oivywon Dust",recipe={mores_jj_draxate_dust={need=1,tag=""},mores_jj_eukavoynt_dust={need=1,tag=""},mores_jj_phantom_shard={need=1,tag=""}}},
 mores_jj_oivywon_ingot={hasPattern=false,label="",recipe={}},
 mores_jj_oivywon_pickaxe={hasPattern=false,label="",recipe={}},
 mores_jj_oivywon_shovel={hasPattern=false,label="",recipe={}},
 mores_jj_oivywon_sword={hasPattern=false,label="",recipe={}},
 mores_jj_oxaxagite_ore={hasPattern=false,label="",recipe={}},
 mores_jj_petuxo_axe={hasPattern=false,label="",recipe={}},
 mores_jj_petuxo_dust={hasPattern=true,label="Petuxo Dust",recipe={mores_jj_eukavoynt_dust={need=1,tag=""},mores_jj_nodemite_dust={need=1,tag=""},mores_jj_phantom_shard={need=1,tag=""}}},
 mores_jj_petuxo_ingot={hasPattern=false,label="",recipe={}},
 mores_jj_petuxo_pickaxe={hasPattern=false,label="",recipe={}},
 mores_jj_petuxo_shovel={hasPattern=false,label="",recipe={}},
 mores_jj_petuxo_sword={hasPattern=true,label="Petuxo Sword",recipe={minecraft_jj_stick={need=1,tag=""},mores_jj_petuxo_ingot={need=2,tag=""}}},
 mores_jj_phantom_ore={hasPattern=false,label="",recipe={mores_jj_phantom_shard={need=4,tag=""}}},
 mores_jj_phantom_shard={hasPattern=false,label="",recipe={}},
 mores_jj_ro_axe={hasPattern=false,label="",recipe={}},
 mores_jj_ro_dust={hasPattern=true,label="Ro Dust",recipe={mores_jj_ayzanite_dust={need=1,tag=""},mores_jj_eukavoynt_dust={need=1,tag=""},mores_jj_phantom_shard={need=1,tag=""}}},
 mores_jj_ro_ingot={hasPattern=false,label="",recipe={}},
 mores_jj_ro_pickaxe={hasPattern=false,label="",recipe={}},
 mores_jj_ro_shovel={hasPattern=false,label="",recipe={}},
 mores_jj_ro_sword={hasPattern=true,label="Ro Sword",recipe={minecraft_jj_stick={need=1,tag=""},mores_jj_ro_ingot={need=2,tag=""}}},
 mores_jj_sivenium_dust={hasPattern=false,label="",recipe={mores_jj_sivenium_ore={need=1,tag=""},ore_jj_dustPetrotheum={need=1,tag=""}}},
 mores_jj_sivenium_ore={hasPattern=false,label="",recipe={}},
 mores_jj_susimen_axe={hasPattern=false,label="",recipe={}},
 mores_jj_susimen_dust={hasPattern=true,label="Susimen Dust",recipe={mores_jj_draxate_dust={need=1,tag=""},mores_jj_phantom_shard={need=1,tag=""},mores_jj_sivenium_dust={need=1,tag=""}}},
 mores_jj_susimen_ingot={hasPattern=false,label="",recipe={}},
 mores_jj_susimen_pickaxe={hasPattern=true,label="Susimen Pickaxe",recipe={minecraft_jj_stick={need=2,tag=""},mores_jj_susimen_ingot={need=3,tag=""}}},
 mores_jj_susimen_shovel={hasPattern=true,label="Susimen Shovel",recipe={minecraft_jj_stick={need=2,tag=""},mores_jj_susimen_ingot={need=1,tag=""}}},
 mores_jj_susimen_sword={hasPattern=false,label="",recipe={}},
 mores_jj_uamaf_axe={hasPattern=false,label="",recipe={}},
 mores_jj_uamaf_dust={hasPattern=true,label="Uamaf Dust",recipe={mores_jj_eukavoynt_dust={need=1,tag=""},mores_jj_phantom_shard={need=1,tag=""},mores_jj_sivenium_dust={need=1,tag=""}}},
 mores_jj_uamaf_ingot={hasPattern=false,label="",recipe={}},
 mores_jj_uamaf_pickaxe={hasPattern=false,label="",recipe={}},
 mores_jj_uamaf_shovel={hasPattern=false,label="",recipe={}},
 mores_jj_uamaf_sword={hasPattern=true,label="Uamaf Sword",recipe={minecraft_jj_stick={need=1,tag=""},mores_jj_uamaf_ingot={need=2,tag=""}}},
 mores_jj_uokuwixasi_axe={hasPattern=false,label="",recipe={}},
 mores_jj_uokuwixasi_dust={hasPattern=true,label="Uokuwixasi Dust",recipe={mores_jj_ayzanite_dust={need=1,tag=""},mores_jj_phantom_shard={need=1,tag=""},mores_jj_sivenium_dust={need=1,tag=""}}},
 mores_jj_uokuwixasi_ingot={hasPattern=false,label="",recipe={}},
 mores_jj_uokuwixasi_pickaxe={hasPattern=false,label="",recipe={}},
 mores_jj_uokuwixasi_shovel={hasPattern=false,label="",recipe={}},
 mores_jj_uokuwixasi_sword={hasPattern=true,label="Uokuwixasi Sword",recipe={minecraft_jj_stick={need=1,tag=""},mores_jj_uokuwixasi_ingot={need=2,tag=""}}},
 mores_jj_vodricite_axe={hasPattern=false,label="",recipe={}},
 mores_jj_vodricite_dust={hasPattern=true,label="Vodricite Dust",recipe={mores_jj_iturite_dust={need=1,tag=""},mores_jj_phantom_shard={need=1,tag=""},mores_jj_sivenium_dust={need=1,tag=""}}},
 mores_jj_vodricite_ingot={hasPattern=false,label="",recipe={}},
 mores_jj_vodricite_pickaxe={hasPattern=false,label="",recipe={}},
 mores_jj_vodricite_shovel={hasPattern=false,label="",recipe={}},
 mores_jj_vodricite_sword={hasPattern=false,label="",recipe={}},
 mores_jj_vukanite_axe={hasPattern=false,label="",recipe={}},
 mores_jj_vukanite_dust={hasPattern=true,label="Vukanite Dust",recipe={mores_jj_ayzanite_dust={need=1,tag=""},mores_jj_iturite_dust={need=1,tag=""},mores_jj_phantom_shard={need=1,tag=""}}},
 mores_jj_vukanite_ingot={hasPattern=false,label="",recipe={}},
 mores_jj_vukanite_pickaxe={hasPattern=false,label="",recipe={}},
 mores_jj_vukanite_shovel={hasPattern=false,label="",recipe={}},
 mores_jj_vukanite_sword={hasPattern=false,label="",recipe={}},
 mores_jj_zanine_axe={hasPattern=false,label="",recipe={}},
 mores_jj_zanine_dust={hasPattern=true,label="Zanine Dust",recipe={mores_jj_aurine_dust={need=1,tag=""},mores_jj_ayzanite_dust={need=1,tag=""},mores_jj_phantom_shard={need=1,tag=""}}},
 mores_jj_zanine_ingot={hasPattern=false,label="",recipe={}},
 mores_jj_zanine_pickaxe={hasPattern=false,label="",recipe={}},
 mores_jj_zanine_shovel={hasPattern=false,label="",recipe={}},
 mores_jj_zanine_sword={hasPattern=false,label="",recipe={}},
 mores_jj_zawium_axe={hasPattern=false,label="",recipe={}},
 mores_jj_zawium_dust={hasPattern=true,label="Zawium Dust",recipe={mores_jj_aurine_dust={need=1,tag=""},mores_jj_phantom_shard={need=1,tag=""},mores_jj_sivenium_dust={need=1,tag=""}}},
 mores_jj_zawium_ingot={hasPattern=false,label="",recipe={}},
 mores_jj_zawium_pickaxe={hasPattern=false,label="",recipe={}},
 mores_jj_zawium_shovel={hasPattern=false,label="",recipe={}},
 mores_jj_zawium_sword={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_ammo_belt={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_ammo_box_jj_1={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_ammo_fire={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_ammo_furnace={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_ammo_jj_1={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_ammo_jj_11={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_ammo_jj_13={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_ammo_jj_14={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_ammo_jj_4={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_ammo_jj_6={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_ammo_jj_7={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_ammo_jj_8={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_ammo_medigun={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_ammo_minigun={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_ammo_pistol={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_ammo_smg={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_ammo_syringe={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_australium_block={hasPattern=false,label="",recipe={rafradek_tf2_weapons_jj_itemtf2_jj_2={need=9,tag=""}}},
 rafradek_tf2_weapons_jj_australium_ore={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_backpack={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_bonk={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_boss_spawner={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_boss_spawner_jj_1={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_boss_spawner_jj_2={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_building_box_jj_18={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_building_box_jj_19={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_building_box_jj_20={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_building_box_jj_21={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_building_box_jj_22={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_building_box_jj_23={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_bullet={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_chocolate={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_cleaver={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_cloak={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_copper_ore={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_cosmetic={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_crate={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_disguise_kit={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_door_controller={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_door_controller_jj_1={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_door_controller_jj_2={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_door_controller_jj_3={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_eventmaker={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_eventmaker_jj_1={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_eventmaker_jj_2={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_eventmaker_jj_3={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_eventmaker_jj_4={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_flamethrower={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_gunboats={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_horn={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_itemtf2={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_itemtf2_jj_1={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_itemtf2_jj_11={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_itemtf2_jj_2={hasPattern=false,label="",recipe={ore_jj_dustPyrotheum={need=1,tag=""},ore_jj_oreAustralium={need=1,tag=""}}},
 rafradek_tf2_weapons_jj_itemtf2_jj_3={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_itemtf2_jj_4={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_itemtf2_jj_5={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_itemtf2_jj_6={hasPattern=false,label="",recipe={ore_jj_ingotAustralium={need=1,tag=""}}},
 rafradek_tf2_weapons_jj_itemtf2_jj_7={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_jar={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakfabricator={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_1024={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_1026={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_1030={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_1036={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_1040={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_1048={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_1058={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_12={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_16={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_2={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_24={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_34={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_512={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_514={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_518={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_524={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_528={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_536={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_546={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_6={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakkit={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakkit_jj_1024={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakkit_jj_1026={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakkit_jj_1030={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakkit_jj_1036={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakkit_jj_1040={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakkit_jj_1048={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakkit_jj_1058={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakkit_jj_12={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakkit_jj_16={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakkit_jj_2={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakkit_jj_24={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakkit_jj_34={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakkit_jj_512={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakkit_jj_514={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakkit_jj_518={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakkit_jj_524={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakkit_jj_528={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakkit_jj_536={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakkit_jj_546={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_killstreakkit_jj_6={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_knife={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_lead_ore={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_mantreads={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_medigun={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_melee={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_minigun={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_overhead_door={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_parachute={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_1={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_10={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_11={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_12={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_13={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_14={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_15={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_16={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_17={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_2={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_26={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_27={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_28={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_29={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_3={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_30={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_36={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_37={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_38={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_39={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_4={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_40={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_41={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_42={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_43={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_44={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_5={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_6={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_7={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_8={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_placer_jj_9={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_projectile={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_robotpart={hasPattern=true,label="",recipe={}},
 rafradek_tf2_weapons_jj_robotpart_jj_1={hasPattern=true,label="",recipe={}},
 rafradek_tf2_weapons_jj_robotpart_jj_2={hasPattern=true,label="",recipe={}},
 rafradek_tf2_weapons_jj_robotpart_jj_3={hasPattern=true,label="",recipe={}},
 rafradek_tf2_weapons_jj_robotpart_jj_4={hasPattern=true,label="",recipe={}},
 rafradek_tf2_weapons_jj_robotpart_jj_5={hasPattern=true,label="",recipe={}},
 rafradek_tf2_weapons_jj_robotpart_jj_6={hasPattern=true,label="",recipe={}},
 rafradek_tf2_weapons_jj_sandvich={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_sapper={hasPattern=true,label="",recipe={}},
 rafradek_tf2_weapons_jj_scout_shoes={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_shield={hasPattern=true,label="",recipe={}},
 rafradek_tf2_weapons_jj_sniperrifle={hasPattern=true,label="",recipe={}},
 rafradek_tf2_weapons_jj_statue={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_stickybomb={hasPattern=true,label="",recipe={}},
 rafradek_tf2_weapons_jj_strangifier={hasPattern=true,label="",recipe={}},
 rafradek_tf2_weapons_jj_target={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_tf2workbench={hasPattern=false,label="",recipe={minecraft_jj_iron_block={need=1,tag=""},ore_jj_workbench={need=1,tag=""},rafradek_tf2_weapons_jj_itemtf2_jj_3={need=4,tag=""}}},
 rafradek_tf2_weapons_jj_token={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_token_jj_1={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_token_jj_2={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_token_jj_3={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_token_jj_4={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_token_jj_5={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_token_jj_6={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_token_jj_7={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_token_jj_8={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_upgrade_station_jj_8={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_wrangler={hasPattern=false,label="",recipe={}},
 rafradek_tf2_weapons_jj_wrench={hasPattern=false,label="",recipe={}}
 }