return {
 bigreactors_jj_blockblutonium={hasPattern=true,label="Blutonium Block",recipe={bigreactors_jj_ingotblutonium={need=9,tag=""}}},
 bigreactors_jj_blockcyanite={hasPattern=true,label="Cyanite Block",recipe={bigreactors_jj_ingotcyanite={need=9,tag=""}}},
 bigreactors_jj_blockgraphite={hasPattern=true,label="Graphite Block",recipe={bigreactors_jj_ingotgraphite={need=9,tag=""}}},
 bigreactors_jj_blockludicrite={hasPattern=false,label="",recipe={bigreactors_jj_ingotblutonium={need=4,tag=""},minecraft_jj_blaze_rod={need=2,tag=""},thermalfoundation_jj_storage_alloy_jj_7={need=2,tag=""}}},
 bigreactors_jj_blocksteel={hasPattern=true,label="Steel Block",recipe={bigreactors_jj_ingotsteel={need=9,tag=""}}},
 bigreactors_jj_blockyellorium={hasPattern=true,label="Yellorium Block",recipe={bigreactors_jj_ingotyellorium={need=9,tag=""}}},
 bigreactors_jj_dustblutonium={hasPattern=false,label="",recipe={bigreactors_jj_ingotblutonium={need=1,tag=""}}},
 bigreactors_jj_dustcyanite={hasPattern=false,label="",recipe={bigreactors_jj_ingotcyanite={need=1,tag=""}}},
 bigreactors_jj_dustgraphite={hasPattern=false,label="",recipe={bigreactors_jj_ingotgraphite={need=1,tag=""}}},
 bigreactors_jj_dustludicrite={hasPattern=false,label="",recipe={bigreactors_jj_ingotludicrite={need=1,tag=""}}},
 bigreactors_jj_duststeel={hasPattern=false,label="",recipe={mekanism_jj_otherdust_jj_1={need=1,tag=""}}},
 bigreactors_jj_dustyellorium={hasPattern=false,label="",recipe={bigreactors_jj_ingotyellorium={need=1,tag=""}}},
 bigreactors_jj_ingotblutonium={hasPattern=false,label="",recipe={modernmetals_jj_plutonium_ingot={need=1,tag=""}}},
 bigreactors_jj_ingotcyanite={hasPattern=true,label="Cyanite Ingot",recipe={bigreactors_jj_ingotyellorium={need=1,tag=""},minecraft_jj_sand={need=1,tag=""}}},
 bigreactors_jj_ingotgraphite={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot_jj_8={need=1,tag=""}}},
 bigreactors_jj_ingotludicrite={hasPattern=true,label="Ludicrite Ingot",recipe={bigreactors_jj_blockludicrite={need=1,tag=""}}},
 bigreactors_jj_ingotsteel={hasPattern=false,label="",recipe={ic2_jj_ingot_jj_5={need=1,tag=""}}},
 bigreactors_jj_ingotyellorium={hasPattern=false,label="",recipe={}},
 bigreactors_jj_mineralanglesite={hasPattern=false,label="",recipe={}},
 bigreactors_jj_mineralbenitoite={hasPattern=false,label="",recipe={}},
 bigreactors_jj_oreanglesite={hasPattern=false,label="",recipe={}},
 bigreactors_jj_orebenitoite={hasPattern=false,label="",recipe={}},
 bigreactors_jj_oreyellorite={hasPattern=false,label="",recipe={}},
 bigreactors_jj_reactoraccessport={hasPattern=true,label="Reactor Access Port (Legacy)",recipe={bigreactors_jj_reactorcasing={need=4,tag=""},minecraft_jj_chest={need=1,tag=""},minecraft_jj_hopper={need=1,tag=""},minecraft_jj_iron_ingot={need=2,tag=""},minecraft_jj_piston={need=1,tag=""}}},
 bigreactors_jj_reactorcasing={hasPattern=true,label="Reactor Casing (Legacy)",recipe={bigreactors_jj_ingotgraphite={need=4,tag=""},bigreactors_jj_reactorcasingcores={need=1,tag=""},minecraft_jj_iron_ingot={need=4,tag=""}}},
 bigreactors_jj_reactorcasingcores={hasPattern=true,label="Reactor Casing Core (Legacy)",recipe={bigreactors_jj_ingotgraphite={need=2,tag=""},minecraft_jj_gold_ingot={need=2,tag=""},minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 bigreactors_jj_reactorcomputerport={hasPattern=true,label="Reactor Computer Port (Legacy)",recipe={bigreactors_jj_reactorcasing={need=4,tag=""},minecraft_jj_gold_ingot={need=2,tag=""},minecraft_jj_redstone={need=2,tag=""},minecraft_jj_repeater={need=1,tag=""},opencomputers_jj_card_jj_6={need=1,tag=""},opencomputers_jj_component={need=1,tag=""},opencomputers_jj_component_jj_3={need=1,tag=""}}},
 bigreactors_jj_reactorcontroller={hasPattern=true,label="Reactor Controller (Legacy)",recipe={bigreactors_jj_ingotyellorium={need=2,tag=""},bigreactors_jj_reactorcasing={need=4,tag=""},minecraft_jj_comparator={need=1,tag=""},minecraft_jj_diamond={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 bigreactors_jj_reactorcontrolrod={hasPattern=true,label="Reactor Control Rod (Legacy)",recipe={bigreactors_jj_ingotgraphite={need=2,tag=""},bigreactors_jj_ingotyellorium={need=1,tag=""},bigreactors_jj_reactorcasing={need=4,tag=""},ic2_jj_ingot_jj_8={need=1,tag=""},minecraft_jj_piston={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 bigreactors_jj_reactorcoolantport={hasPattern=true,label="Reactor Coolant Port (Legacy)",recipe={bigreactors_jj_reactorcasing={need=4,tag=""},minecraft_jj_bucket={need=1,tag=""},minecraft_jj_hopper={need=1,tag=""},minecraft_jj_iron_ingot={need=2,tag=""},minecraft_jj_piston={need=1,tag=""}}},
 bigreactors_jj_reactorcreativecoolantport={hasPattern=false,label="",recipe={}},
 bigreactors_jj_reactorfuelrod={hasPattern=true,label="Reactor Fuel Rod (Legacy)",recipe={bigreactors_jj_ingotgraphite={need=2,tag=""},bigreactors_jj_ingotyellorium={need=1,tag=""},ic2_jj_ingot_jj_8={need=1,tag=""},minecraft_jj_glass={need=2,tag=""},minecraft_jj_iron_ingot={need=4,tag=""}}},
 bigreactors_jj_reactorglass={hasPattern=true,label="Reactor Glass (Legacy)",recipe={bigreactors_jj_reactorcasing={need=1,tag=""},minecraft_jj_glass={need=2,tag=""}}},
 bigreactors_jj_reactorpowertaprf={hasPattern=true,label="Reactor Redstone Flux Power Tap (Legacy)",recipe={bigreactors_jj_reactorcasing={need=4,tag=""},minecraft_jj_redstone={need=4,tag=""},minecraft_jj_redstone_block={need=1,tag=""}}},
 bigreactors_jj_reactorpowertaptesla={hasPattern=true,label="Reactor Tesla Power Tap (Legacy)",recipe={bigreactors_jj_reactorcasing={need=4,tag=""},minecraft_jj_dye_jj_4={need=4,tag=""},minecraft_jj_lapis_block={need=1,tag=""}}},
 bigreactors_jj_reactorrednetport={hasPattern=false,label="",recipe={}},
 bigreactors_jj_reactorredstoneport={hasPattern=true,label="Reactor Redstone Port (Legacy)",recipe={bigreactors_jj_reactorcasing={need=4,tag=""},minecraft_jj_gold_ingot={need=1,tag=""},minecraft_jj_redstone={need=4,tag=""}}},
 bigreactors_jj_turbinebearing={hasPattern=true,label="Turbine Rotor Bearing (Legacy)",recipe={bigreactors_jj_turbinehousing={need=4,tag=""},bigreactors_jj_turbinerotorshaft={need=2,tag=""},minecraft_jj_diamond={need=3,tag=""}}},
 bigreactors_jj_turbinecomputerport={hasPattern=true,label="Turbine Computer Port (Legacy)",recipe={bigreactors_jj_turbinehousing={need=4,tag=""},minecraft_jj_gold_ingot={need=2,tag=""},minecraft_jj_redstone={need=2,tag=""},minecraft_jj_repeater={need=1,tag=""},opencomputers_jj_card_jj_6={need=1,tag=""},opencomputers_jj_component={need=1,tag=""},opencomputers_jj_component_jj_3={need=1,tag=""}}},
 bigreactors_jj_turbinecontroller={hasPattern=true,label="Turbine Controller (Legacy)",recipe={bigreactors_jj_ingotblutonium={need=2,tag=""},bigreactors_jj_turbinehousing={need=4,tag=""},minecraft_jj_comparator={need=1,tag=""},minecraft_jj_diamond={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 bigreactors_jj_turbinecreativesteamgenerator={hasPattern=false,label="",recipe={}},
 bigreactors_jj_turbinefluidport={hasPattern=true,label="Turbine Fluid Port (Legacy)",recipe={bigreactors_jj_turbinehousing={need=4,tag=""},minecraft_jj_bucket={need=1,tag=""},minecraft_jj_hopper={need=1,tag=""},minecraft_jj_iron_ingot={need=2,tag=""},minecraft_jj_piston={need=1,tag=""}}},
 bigreactors_jj_turbineglass={hasPattern=true,label="Turbine Glass (Legacy)",recipe={bigreactors_jj_turbinehousing={need=1,tag=""},minecraft_jj_glass={need=2,tag=""}}},
 bigreactors_jj_turbinehousing={hasPattern=true,label="Turbine Housing (Legacy)",recipe={bigreactors_jj_ingotgraphite={need=4,tag=""},bigreactors_jj_turbinehousingcores={need=1,tag=""},minecraft_jj_iron_ingot={need=4,tag=""}}},
 bigreactors_jj_turbinehousingcores={hasPattern=true,label="Turbine Housing Core (Legacy)",recipe={bigreactors_jj_ingotgraphite={need=2,tag=""},minecraft_jj_comparator={need=1,tag=""},minecraft_jj_gold_ingot={need=2,tag=""},minecraft_jj_iron_ingot={need=4,tag=""}}},
 bigreactors_jj_turbinepowertaprf={hasPattern=true,label="Turbine Redstone Flux Power Tap (Legacy)",recipe={bigreactors_jj_turbinehousing={need=4,tag=""},minecraft_jj_redstone={need=4,tag=""},minecraft_jj_redstone_block={need=1,tag=""}}},
 bigreactors_jj_turbinepowertaptesla={hasPattern=true,label="Turbine Tesla Power Tap (Legacy)",recipe={bigreactors_jj_turbinehousing={need=4,tag=""},minecraft_jj_dye_jj_4={need=4,tag=""},minecraft_jj_lapis_block={need=1,tag=""}}},
 bigreactors_jj_turbinerotorblade={hasPattern=true,label="Turbine Rotor Blade (Legacy)",recipe={bigreactors_jj_ingotcyanite={need=1,tag=""},minecraft_jj_iron_ingot={need=2,tag=""}}},
 bigreactors_jj_turbinerotorshaft={hasPattern=true,label="Turbine Rotor Shaft (Legacy)",recipe={bigreactors_jj_ingotcyanite={need=1,tag=""},minecraft_jj_iron_ingot={need=4,tag=""}}},
 bigreactors_jj_wrench={hasPattern=true,label="Extreme Wrench",recipe={minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_wool_jj_5={need=2,tag=""}}},
 nuclearcraft_jj_accelerator_electromagnet_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_accelerator_electromagnet_idle={hasPattern=true,label="Supraleitender Elektromagnet",recipe={nuclearcraft_jj_part_jj_3={need=4,tag=""},nuclearcraft_jj_part_jj_5={need=4,tag=""}}},
 nuclearcraft_jj_active_cooler={hasPattern=true,label="Aktiver Flüssigkeitskühler",recipe={ic2_jj_ingot_jj_2={need=2,tag=""},ic2_jj_ingot_jj_6={need=2,tag=""},minecraft_jj_cauldron={need=1,tag=""},nuclearcraft_jj_ingot={need=2,tag=""},nuclearcraft_jj_ingot_jj_1={need=2,tag=""},nuclearcraft_jj_part={need=4,tag=""}}},
 nuclearcraft_jj_alloy={hasPattern=false,label="",recipe={ic2_jj_ingot_jj_1={need=1,tag=""}}},
 nuclearcraft_jj_alloy_furnace_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_alloy_furnace_idle={hasPattern=true,label="Legierungsofen",recipe={minecraft_jj_brick={need=2,tag=""},minecraft_jj_furnace={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""},nuclearcraft_jj_part={need=4,tag=""},nuclearcraft_jj_part_jj_4={need=1,tag=""}}},
 nuclearcraft_jj_alloy_jj_1={hasPattern=false,label="",recipe={nuclearcraft_jj_alloy_jj_6={need=1,tag=""},nuclearcraft_jj_ingot_jj_6={need=1,tag=""}}},
 nuclearcraft_jj_alloy_jj_10={hasPattern=false,label="",recipe={nuclearcraft_jj_alloy_jj_1={need=1,tag=""},nuclearcraft_jj_alloy_jj_2={need=1,tag=""}}},
 nuclearcraft_jj_alloy_jj_11={hasPattern=false,label="",recipe={nuclearcraft_jj_alloy_jj_10={need=1,tag=""},nuclearcraft_jj_gem_jj_5={need=1,tag=""}}},
 nuclearcraft_jj_alloy_jj_12={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot_jj_1={need=1,tag=""},nuclearcraft_jj_ingot_jj_10={need=7,tag=""}}},
 nuclearcraft_jj_alloy_jj_13={hasPattern=false,label="",recipe={nuclearcraft_jj_gem_jj_6={need=1,tag=""},nuclearcraft_jj_ingot_jj_8={need=1,tag=""}}},
 nuclearcraft_jj_alloy_jj_14={hasPattern=true,label="SiC-SiC Ceramic Matrix Composite",recipe={nuclearcraft_jj_alloy_jj_12={need=1,tag=""},nuclearcraft_jj_alloy_jj_13={need=1,tag=""}}},
 nuclearcraft_jj_alloy_jj_15={hasPattern=false,label="",recipe={minecraft_jj_iron_ingot={need=15,tag=""},nuclearcraft_jj_compound_jj_9={need=1,tag=""}}},
 nuclearcraft_jj_alloy_jj_2={hasPattern=false,label="",recipe={minecraft_jj_diamond={need=1,tag=""},nuclearcraft_jj_ingot_jj_8={need=2,tag=""}}},
 nuclearcraft_jj_alloy_jj_3={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot_jj_5={need=2,tag=""},nuclearcraft_jj_ingot_jj_7={need=1,tag=""}}},
 nuclearcraft_jj_alloy_jj_4={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot_jj_6={need=1,tag=""},nuclearcraft_jj_ingot_oxide_jj_3={need=1,tag=""}}},
 nuclearcraft_jj_alloy_jj_5={hasPattern=false,label="",recipe={ic2_jj_ingot_jj_5={need=1,tag=""}}},
 nuclearcraft_jj_alloy_jj_6={hasPattern=false,label="",recipe={nuclearcraft_jj_alloy_jj_5={need=1,tag=""},nuclearcraft_jj_ingot_jj_5={need=1,tag=""}}},
 nuclearcraft_jj_alloy_jj_7={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot={need=3,tag=""},nuclearcraft_jj_ingot_jj_13={need=1,tag=""}}},
 nuclearcraft_jj_alloy_jj_8={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot_jj_1={need=3,tag=""},nuclearcraft_jj_ingot_jj_13={need=1,tag=""}}},
 nuclearcraft_jj_alloy_jj_9={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot_jj_2={need=3,tag=""},thermalfoundation_jj_material_jj_134={need=1,tag=""}}},
 nuclearcraft_jj_americium={hasPattern=false,label="",recipe={ore_jj_nuggetAmericium241={need=9,tag=""}}},
 nuclearcraft_jj_americium_jj_1={hasPattern=false,label="",recipe={ore_jj_nuggetAmericium241Oxide={need=9,tag=""}}},
 nuclearcraft_jj_americium_jj_10={hasPattern=false,label="",recipe={ore_jj_ingotAmericium243Base={need=1,tag=""}}},
 nuclearcraft_jj_americium_jj_11={hasPattern=false,label="",recipe={ore_jj_ingotAmericium243Oxide={need=1,tag=""}}},
 nuclearcraft_jj_americium_jj_2={hasPattern=false,label="",recipe={ore_jj_ingotAmericium241Base={need=1,tag=""}}},
 nuclearcraft_jj_americium_jj_3={hasPattern=false,label="",recipe={ore_jj_ingotAmericium241Oxide={need=1,tag=""}}},
 nuclearcraft_jj_americium_jj_4={hasPattern=false,label="",recipe={ore_jj_nuggetAmericium242={need=9,tag=""}}},
 nuclearcraft_jj_americium_jj_5={hasPattern=false,label="",recipe={ore_jj_nuggetAmericium242Oxide={need=9,tag=""}}},
 nuclearcraft_jj_americium_jj_6={hasPattern=false,label="",recipe={ore_jj_ingotAmericium242Base={need=1,tag=""}}},
 nuclearcraft_jj_americium_jj_7={hasPattern=false,label="",recipe={nuclearcraft_jj_americium_jj_5={need=1,tag=""}}},
 nuclearcraft_jj_americium_jj_8={hasPattern=false,label="",recipe={ore_jj_blockDepletedAmericium={need=1,tag=""}}},
 nuclearcraft_jj_americium_jj_9={hasPattern=false,label="",recipe={ore_jj_nuggetAmericium243Oxide={need=9,tag=""}}},
 nuclearcraft_jj_axe_boron={hasPattern=true,label="Boraxt",recipe={minecraft_jj_stick={need=2,tag=""},nuclearcraft_jj_ingot_jj_5={need=3,tag=""}}},
 nuclearcraft_jj_axe_boron_nitride={hasPattern=true,label="Bornitridaxt",recipe={minecraft_jj_stick={need=2,tag=""},nuclearcraft_jj_gem_jj_1={need=3,tag=""}}},
 nuclearcraft_jj_axe_hard_carbon={hasPattern=true,label="Harte Kohlenstoffaxt",recipe={minecraft_jj_stick={need=2,tag=""},nuclearcraft_jj_alloy_jj_2={need=3,tag=""}}},
 nuclearcraft_jj_axe_tough={hasPattern=true,label="Harte Legierungsaxt",recipe={minecraft_jj_stick={need=2,tag=""},nuclearcraft_jj_alloy_jj_1={need=3,tag=""}}},
 nuclearcraft_jj_berkelium={hasPattern=false,label="",recipe={ore_jj_blockDepletedBerkelium={need=1,tag=""}}},
 nuclearcraft_jj_berkelium_jj_1={hasPattern=false,label="",recipe={ore_jj_nuggetBerkelium247Oxide={need=9,tag=""}}},
 nuclearcraft_jj_berkelium_jj_2={hasPattern=false,label="",recipe={ore_jj_ingotBerkelium247Base={need=1,tag=""}}},
 nuclearcraft_jj_berkelium_jj_3={hasPattern=false,label="",recipe={ore_jj_ingotBerkelium247Oxide={need=1,tag=""}}},
 nuclearcraft_jj_berkelium_jj_4={hasPattern=false,label="",recipe={ore_jj_nuggetBerkelium248={need=9,tag=""}}},
 nuclearcraft_jj_berkelium_jj_5={hasPattern=false,label="",recipe={ore_jj_nuggetBerkelium248Oxide={need=9,tag=""}}},
 nuclearcraft_jj_berkelium_jj_6={hasPattern=false,label="",recipe={ore_jj_ingotBerkelium248Base={need=1,tag=""}}},
 nuclearcraft_jj_berkelium_jj_7={hasPattern=false,label="",recipe={nuclearcraft_jj_berkelium_jj_5={need=1,tag=""}}},
 nuclearcraft_jj_bin={hasPattern=true,label="Universaler Mistkübel",recipe={nuclearcraft_jj_ingot_jj_10={need=4,tag=""},nuclearcraft_jj_part={need=4,tag=""}}},
 nuclearcraft_jj_block_depleted_americium={hasPattern=true,label="Erschöpfter Americiumblock",recipe={nuclearcraft_jj_americium_jj_8={need=9,tag=""}}},
 nuclearcraft_jj_block_depleted_berkelium={hasPattern=true,label="Erschöpfter Berkeliumblock",recipe={nuclearcraft_jj_berkelium={need=9,tag=""}}},
 nuclearcraft_jj_block_depleted_californium={hasPattern=true,label="Erschöpfter Californiumblock",recipe={nuclearcraft_jj_californium_jj_12={need=9,tag=""}}},
 nuclearcraft_jj_block_depleted_curium={hasPattern=true,label="Erschöpfter Curiumblock",recipe={nuclearcraft_jj_curium_jj_8={need=9,tag=""}}},
 nuclearcraft_jj_block_depleted_neptunium={hasPattern=true,label="Erschöpfter Neptuniumblock",recipe={nuclearcraft_jj_neptunium_jj_4={need=9,tag=""}}},
 nuclearcraft_jj_block_depleted_plutonium={hasPattern=true,label="Erschöpfter Plutoniumblock",recipe={nuclearcraft_jj_plutonium_jj_12={need=9,tag=""}}},
 nuclearcraft_jj_block_depleted_thorium={hasPattern=true,label="Erschöpfter Thoriumblock",recipe={nuclearcraft_jj_thorium={need=9,tag=""}}},
 nuclearcraft_jj_block_depleted_uranium={hasPattern=true,label="Erschöpfter Uranblock",recipe={nuclearcraft_jj_uranium_jj_8={need=9,tag=""}}},
 nuclearcraft_jj_block_ice={hasPattern=false,label="",recipe={minecraft_jj_ice={need=1,tag=""}}},
 nuclearcraft_jj_boots_boron={hasPattern=true,label="Borstiefel",recipe={nuclearcraft_jj_ingot_jj_5={need=4,tag=""}}},
 nuclearcraft_jj_boots_boron_nitride={hasPattern=true,label="Bornitridstiefel",recipe={nuclearcraft_jj_gem_jj_1={need=4,tag=""}}},
 nuclearcraft_jj_boots_hard_carbon={hasPattern=true,label="Harte Kohlenstoffstiefel",recipe={nuclearcraft_jj_alloy_jj_2={need=4,tag=""}}},
 nuclearcraft_jj_boots_hazmat={hasPattern=true,label="Hazmat Suit Boots",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_leather_boots={need=1,tag=""},nuclearcraft_jj_part_jj_6={need=2,tag=""},nuclearcraft_jj_rad_shielding_jj_2={need=2,tag=""}}},
 nuclearcraft_jj_boots_tough={hasPattern=true,label="Harte Legierungsstiefel",recipe={nuclearcraft_jj_alloy_jj_1={need=4,tag=""}}},
 nuclearcraft_jj_boron={hasPattern=false,label="",recipe={ore_jj_nuggetBoron10={need=9,tag=""}}},
 nuclearcraft_jj_boron_jj_1={hasPattern=false,label="",recipe={ore_jj_ingotBoron10={need=1,tag=""}}},
 nuclearcraft_jj_boron_jj_2={hasPattern=false,label="",recipe={ore_jj_nuggetBoron11={need=9,tag=""}}},
 nuclearcraft_jj_boron_jj_3={hasPattern=false,label="",recipe={ore_jj_ingotBoron11={need=1,tag=""}}},
 nuclearcraft_jj_buffer={hasPattern=true,label="Zwischenspeicher",recipe={minecraft_jj_bucket={need=2,tag=""},minecraft_jj_hopper={need=1,tag=""},nuclearcraft_jj_part={need=4,tag=""},nuclearcraft_jj_part_jj_4={need=2,tag=""}}},
 nuclearcraft_jj_californium={hasPattern=false,label="",recipe={ore_jj_nuggetCalifornium249={need=9,tag=""}}},
 nuclearcraft_jj_californium_jj_1={hasPattern=false,label="",recipe={ore_jj_nuggetCalifornium249Oxide={need=9,tag=""}}},
 nuclearcraft_jj_californium_jj_10={hasPattern=false,label="",recipe={ore_jj_ingotCalifornium251Base={need=1,tag=""}}},
 nuclearcraft_jj_californium_jj_11={hasPattern=false,label="",recipe={nuclearcraft_jj_californium_jj_9={need=1,tag=""}}},
 nuclearcraft_jj_californium_jj_12={hasPattern=false,label="",recipe={ore_jj_blockDepletedCalifornium={need=1,tag=""}}},
 nuclearcraft_jj_californium_jj_13={hasPattern=false,label="",recipe={ore_jj_nuggetCalifornium252Oxide={need=9,tag=""}}},
 nuclearcraft_jj_californium_jj_14={hasPattern=false,label="",recipe={ore_jj_ingotCalifornium252Base={need=1,tag=""}}},
 nuclearcraft_jj_californium_jj_15={hasPattern=false,label="",recipe={ore_jj_ingotCalifornium252Oxide={need=1,tag=""}}},
 nuclearcraft_jj_californium_jj_2={hasPattern=false,label="",recipe={ore_jj_ingotCalifornium249Base={need=1,tag=""}}},
 nuclearcraft_jj_californium_jj_3={hasPattern=false,label="",recipe={nuclearcraft_jj_californium_jj_1={need=1,tag=""}}},
 nuclearcraft_jj_californium_jj_4={hasPattern=false,label="",recipe={ore_jj_nuggetCalifornium250={need=9,tag=""}}},
 nuclearcraft_jj_californium_jj_5={hasPattern=false,label="",recipe={ore_jj_nuggetCalifornium250Oxide={need=9,tag=""}}},
 nuclearcraft_jj_californium_jj_6={hasPattern=false,label="",recipe={ore_jj_ingotCalifornium250Base={need=1,tag=""}}},
 nuclearcraft_jj_californium_jj_7={hasPattern=false,label="",recipe={ore_jj_ingotCalifornium250Oxide={need=1,tag=""}}},
 nuclearcraft_jj_californium_jj_8={hasPattern=false,label="",recipe={ore_jj_nuggetCalifornium251={need=9,tag=""}}},
 nuclearcraft_jj_californium_jj_9={hasPattern=false,label="",recipe={ore_jj_nuggetCalifornium251Oxide={need=9,tag=""}}},
 nuclearcraft_jj_cell_block={hasPattern=true,label="Reaktorzelle",recipe={minecraft_jj_glass={need=4,tag=""},nuclearcraft_jj_alloy_jj_1={need=4,tag=""}}},
 nuclearcraft_jj_centrifuge_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_centrifuge_idle={hasPattern=true,label="Zentrifuge",recipe={nuclearcraft_jj_alloy_jj_6={need=1,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""},nuclearcraft_jj_part_jj_10={need=1,tag=""},nuclearcraft_jj_part_jj_7={need=1,tag=""},nuclearcraft_jj_part_jj_8={need=2,tag=""}}},
 nuclearcraft_jj_chemical_reactor_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_chemical_reactor_idle={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot_jj_10={need=4,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""},nuclearcraft_jj_salt_mixer_idle={need=1,tag=""}}},
 nuclearcraft_jj_chest_boron={hasPattern=true,label="Borbrustpanzer",recipe={nuclearcraft_jj_ingot_jj_5={need=8,tag=""}}},
 nuclearcraft_jj_chest_boron_nitride={hasPattern=true,label="Bornitridbrustpanzer",recipe={nuclearcraft_jj_gem_jj_1={need=8,tag=""}}},
 nuclearcraft_jj_chest_hard_carbon={hasPattern=true,label="Harter Kohlenstoffbrustpanzer",recipe={nuclearcraft_jj_alloy_jj_2={need=8,tag=""}}},
 nuclearcraft_jj_chest_hazmat={hasPattern=true,label="Hazmat Suit Chestpiece",recipe={minecraft_jj_dye_jj_11={need=2,tag=""},minecraft_jj_leather_chestplate={need=1,tag=""},minecraft_jj_wool={need=3,tag=""},nuclearcraft_jj_rad_shielding_jj_2={need=3,tag=""}}},
 nuclearcraft_jj_chest_tough={hasPattern=true,label="Harter Legierungsbrustpanzer",recipe={nuclearcraft_jj_alloy_jj_1={need=8,tag=""}}},
 nuclearcraft_jj_cobblestone_generator={hasPattern=true,label="Bruchsteingenerator",recipe={ic2_jj_ingot_jj_6={need=2,tag=""},minecraft_jj_lava_bucket={need=1,tag=""},minecraft_jj_water_bucket={need=1,tag=""},nuclearcraft_jj_ingot_jj_1={need=2,tag=""},nuclearcraft_jj_part={need=4,tag=""}}},
 nuclearcraft_jj_cobblestone_generator_compact={hasPattern=true,label="Kompakter Bruchsteingenerator",recipe={ic2_jj_ingot_jj_1={need=1,tag=""},nuclearcraft_jj_alloy={need=1,tag=""},nuclearcraft_jj_cobblestone_generator={need=8,tag=""}}},
 nuclearcraft_jj_cobblestone_generator_dense={hasPattern=true,label="Dichter Bruchsteingenerator",recipe={minecraft_jj_gold_ingot={need=1,tag=""},nuclearcraft_jj_cobblestone_generator_compact={need=8,tag=""}}},
 nuclearcraft_jj_cocoa_butter={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_cocoa_solids={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_compound={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_compound_jj_1={hasPattern=true,label="Kristallbinder",recipe={ic2_jj_dust_jj_12={need=8,tag=""},nuclearcraft_jj_compound={need=1,tag=""},nuclearcraft_jj_dust_jj_7={need=1,tag=""},nuclearcraft_jj_gem_dust_jj_1={need=1,tag=""},nuclearcraft_jj_gem_dust_jj_3={need=1,tag=""},techreborn_jj_dust_jj_30={need=1,tag=""}}},
 nuclearcraft_jj_compound_jj_10={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_compound_jj_2={hasPattern=true,label="Energische Mischung",recipe={minecraft_jj_glowstone_dust={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 nuclearcraft_jj_compound_jj_3={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_compound_jj_4={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_compound_jj_5={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_compound_jj_6={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_compound_jj_7={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_compound_jj_8={hasPattern=true,label="Dimensional Blend",recipe={nuclearcraft_jj_gem_dust_jj_11={need=1,tag=""},nuclearcraft_jj_gem_dust_jj_3={need=4,tag=""}}},
 nuclearcraft_jj_compound_jj_9={hasPattern=true,label="Carbon-Manganese Blend",recipe={nuclearcraft_jj_dust_jj_11={need=1,tag=""},nuclearcraft_jj_dust_jj_8={need=1,tag=""}}},
 nuclearcraft_jj_cooler={hasPattern=true,label="Leerer Kühler",recipe={ic2_jj_ingot_jj_5={need=4,tag=""},nuclearcraft_jj_alloy_jj_1={need=4,tag=""},nuclearcraft_jj_alloy_jj_5={need=4,tag=""}}},
 nuclearcraft_jj_cooler_jj_1={hasPattern=true,label="Wasserkühler",recipe={minecraft_jj_water_bucket={need=1,tag=""},nuclearcraft_jj_cooler={need=1,tag=""}}},
 nuclearcraft_jj_cooler_jj_10={hasPattern=true,label="Kryotheumkühler",recipe={nuclearcraft_jj_cooler={need=1,tag=""},thermalfoundation_jj_material_jj_1025={need=8,tag=""}}},
 nuclearcraft_jj_cooler_jj_11={hasPattern=true,label="Eisenkühler",recipe={minecraft_jj_iron_ingot={need=8,tag=""},nuclearcraft_jj_cooler={need=1,tag=""}}},
 nuclearcraft_jj_cooler_jj_12={hasPattern=true,label="Smaragdkühler",recipe={minecraft_jj_emerald={need=6,tag=""},nuclearcraft_jj_cooler={need=1,tag=""}}},
 nuclearcraft_jj_cooler_jj_13={hasPattern=true,label="Kupferkühler",recipe={ic2_jj_ingot_jj_2={need=8,tag=""},nuclearcraft_jj_cooler={need=1,tag=""},nuclearcraft_jj_ingot={need=8,tag=""}}},
 nuclearcraft_jj_cooler_jj_14={hasPattern=true,label="Zinnkühler",recipe={ic2_jj_ingot_jj_6={need=8,tag=""},nuclearcraft_jj_cooler={need=1,tag=""},nuclearcraft_jj_ingot_jj_1={need=8,tag=""}}},
 nuclearcraft_jj_cooler_jj_15={hasPattern=true,label="Magnesiumkühler",recipe={nuclearcraft_jj_cooler={need=1,tag=""},nuclearcraft_jj_ingot_jj_7={need=8,tag=""}}},
 nuclearcraft_jj_cooler_jj_2={hasPattern=true,label="Redstone Cooler",recipe={minecraft_jj_redstone={need=2,tag=""},minecraft_jj_redstone_block={need=2,tag=""},nuclearcraft_jj_cooler={need=1,tag=""}}},
 nuclearcraft_jj_cooler_jj_3={hasPattern=true,label="Quarzkühler",recipe={minecraft_jj_quartz_block={need=2,tag=""},nuclearcraft_jj_cooler={need=1,tag=""},nuclearcraft_jj_gem_dust_jj_2={need=6,tag=""}}},
 nuclearcraft_jj_cooler_jj_4={hasPattern=true,label="Goldkühler",recipe={minecraft_jj_gold_ingot={need=8,tag=""},nuclearcraft_jj_cooler={need=1,tag=""}}},
 nuclearcraft_jj_cooler_jj_5={hasPattern=true,label="Glowstonekühler",recipe={minecraft_jj_glowstone={need=2,tag=""},minecraft_jj_glowstone_dust={need=6,tag=""},nuclearcraft_jj_cooler={need=1,tag=""}}},
 nuclearcraft_jj_cooler_jj_6={hasPattern=true,label="Lapislazulikühler",recipe={minecraft_jj_lapis_block={need=2,tag=""},nuclearcraft_jj_cooler={need=1,tag=""}}},
 nuclearcraft_jj_cooler_jj_7={hasPattern=true,label="Diamantkühler",recipe={minecraft_jj_diamond={need=8,tag=""},nuclearcraft_jj_cooler={need=1,tag=""}}},
 nuclearcraft_jj_cooler_jj_8={hasPattern=true,label="Flüssigheliumkühler",recipe={forge_jj_bucketfilled={need=1,tag=""},nuclearcraft_jj_cooler={need=1,tag=""}}},
 nuclearcraft_jj_cooler_jj_9={hasPattern=true,label="Enderiumkühler",recipe={nuclearcraft_jj_cooler={need=1,tag=""},thermalfoundation_jj_material_jj_167={need=8,tag=""}}},
 nuclearcraft_jj_crystallizer_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_crystallizer_idle={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot_former_idle={need=1,tag=""},nuclearcraft_jj_ingot_jj_9={need=4,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""}}},
 nuclearcraft_jj_curium={hasPattern=false,label="",recipe={ore_jj_nuggetCurium243={need=9,tag=""}}},
 nuclearcraft_jj_curium_jj_1={hasPattern=false,label="",recipe={ore_jj_nuggetCurium243Oxide={need=9,tag=""}}},
 nuclearcraft_jj_curium_jj_10={hasPattern=false,label="",recipe={ore_jj_ingotCurium246Base={need=1,tag=""}}},
 nuclearcraft_jj_curium_jj_11={hasPattern=false,label="",recipe={ore_jj_ingotCurium246Oxide={need=1,tag=""}}},
 nuclearcraft_jj_curium_jj_12={hasPattern=false,label="",recipe={ore_jj_nuggetCurium247={need=9,tag=""}}},
 nuclearcraft_jj_curium_jj_13={hasPattern=false,label="",recipe={ore_jj_nuggetCurium247Oxide={need=9,tag=""}}},
 nuclearcraft_jj_curium_jj_14={hasPattern=false,label="",recipe={ore_jj_ingotCurium247Base={need=1,tag=""}}},
 nuclearcraft_jj_curium_jj_15={hasPattern=false,label="",recipe={nuclearcraft_jj_curium_jj_13={need=1,tag=""}}},
 nuclearcraft_jj_curium_jj_2={hasPattern=false,label="",recipe={ore_jj_ingotCurium243Base={need=1,tag=""}}},
 nuclearcraft_jj_curium_jj_3={hasPattern=false,label="",recipe={nuclearcraft_jj_curium_jj_1={need=1,tag=""}}},
 nuclearcraft_jj_curium_jj_4={hasPattern=false,label="",recipe={ore_jj_nuggetCurium245={need=9,tag=""}}},
 nuclearcraft_jj_curium_jj_5={hasPattern=false,label="",recipe={ore_jj_nuggetCurium245Oxide={need=9,tag=""}}},
 nuclearcraft_jj_curium_jj_6={hasPattern=false,label="",recipe={ore_jj_ingotCurium245Base={need=1,tag=""}}},
 nuclearcraft_jj_curium_jj_7={hasPattern=false,label="",recipe={nuclearcraft_jj_curium_jj_5={need=1,tag=""}}},
 nuclearcraft_jj_curium_jj_8={hasPattern=false,label="",recipe={ore_jj_blockDepletedCurium={need=1,tag=""}}},
 nuclearcraft_jj_curium_jj_9={hasPattern=false,label="",recipe={ore_jj_nuggetCurium246Oxide={need=9,tag=""}}},
 nuclearcraft_jj_dark_chocolate={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_decay_generator={hasPattern=true,label="Zerfallsgenerator",recipe={ic2_jj_ingot_jj_3={need=4,tag=""},minecraft_jj_cobblestone={need=4,tag=""},minecraft_jj_redstone={need=1,tag=""},nuclearcraft_jj_ingot_jj_2={need=4,tag=""}}},
 nuclearcraft_jj_decay_hastener_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_decay_hastener_idle={hasPattern=false,label="",recipe={nuclearcraft_jj_alloy_furnace_idle={need=1,tag=""},nuclearcraft_jj_ingot_jj_7={need=4,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""}}},
 nuclearcraft_jj_depleted_fuel_americium={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_americium_jj_1={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_americium_jj_2={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_americium_jj_3={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_berkelium={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_berkelium_jj_1={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_berkelium_jj_2={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_berkelium_jj_3={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_californium={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_californium_jj_1={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_californium_jj_2={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_californium_jj_3={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_californium_jj_4={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_californium_jj_5={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_californium_jj_6={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_californium_jj_7={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_curium={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_curium_jj_1={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_curium_jj_10={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_curium_jj_11={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_curium_jj_2={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_curium_jj_3={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_curium_jj_4={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_curium_jj_5={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_curium_jj_6={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_curium_jj_7={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_curium_jj_8={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_curium_jj_9={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_ic2={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_ic2_jj_1={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_mixed_oxide={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_mixed_oxide_jj_1={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_neptunium={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_neptunium_jj_1={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_neptunium_jj_2={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_neptunium_jj_3={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_plutonium={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_plutonium_jj_1={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_plutonium_jj_2={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_plutonium_jj_3={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_plutonium_jj_4={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_plutonium_jj_5={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_plutonium_jj_6={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_plutonium_jj_7={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_thorium={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_thorium_jj_1={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_uranium={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_uranium_jj_1={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_uranium_jj_2={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_uranium_jj_3={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_uranium_jj_4={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_uranium_jj_5={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_uranium_jj_6={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_depleted_fuel_uranium_jj_7={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_dissolver_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_dissolver_idle={hasPattern=false,label="",recipe={nuclearcraft_jj_gem_dust_jj_3={need=4,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""},nuclearcraft_jj_salt_mixer_idle={need=1,tag=""}}},
 nuclearcraft_jj_dominos={hasPattern=true,label="Domino's Special",recipe={minecraft_jj_bread={need=3,tag=""},minecraft_jj_brown_mushroom={need=2,tag=""},minecraft_jj_cooked_beef={need=1,tag=""},minecraft_jj_cooked_chicken={need=1,tag=""},minecraft_jj_cooked_mutton={need=1,tag=""},minecraft_jj_cooked_porkchop={need=1,tag=""}}},
 nuclearcraft_jj_dry_earth={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_dust={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_dust_jj_1={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_dust_jj_10={hasPattern=false,label="",recipe={ore_jj_dustPetrotheum={need=1,tag=""},ore_jj_oreZirconium={need=1,tag=""}}},
 nuclearcraft_jj_dust_jj_11={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_dust_jj_12={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_dust_jj_13={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_dust_jj_2={hasPattern=false,label="",recipe={ore_jj_tinyDustLead={need=9,tag=""}}},
 nuclearcraft_jj_dust_jj_3={hasPattern=false,label="",recipe={immersiveengineering_jj_tool={need=1,tag=""},ore_jj_oreThorium={need=1,tag=""}}},
 nuclearcraft_jj_dust_jj_4={hasPattern=false,label="",recipe={ore_jj_dustPetrotheum={need=1,tag=""},ore_jj_oreUranium={need=1,tag=""}}},
 nuclearcraft_jj_dust_jj_5={hasPattern=false,label="",recipe={immersiveengineering_jj_tool={need=1,tag=""},ore_jj_oreBoron={need=1,tag=""}}},
 nuclearcraft_jj_dust_jj_6={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_dust_jj_7={hasPattern=false,label="",recipe={immersiveengineering_jj_tool={need=1,tag=""},nuclearcraft_jj_ore_jj_7={need=1,tag=""}}},
 nuclearcraft_jj_dust_jj_8={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_dust_jj_9={hasPattern=false,label="",recipe={modernmetals_jj_beryllium_ore={need=1,tag=""},ore_jj_dustPetrotheum={need=1,tag=""}}},
 nuclearcraft_jj_dust_oxide={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_dust_oxide_jj_1={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_dust_oxide_jj_2={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_dust_oxide_jj_3={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_electrolyser_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_electrolyser_idle={hasPattern=true,label="Elektrolysegerät",recipe={minecraft_jj_redstone={need=4,tag=""},nuclearcraft_jj_ingot_jj_8={need=1,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""},nuclearcraft_jj_part_jj_10={need=1,tag=""},nuclearcraft_jj_part_jj_4={need=2,tag=""},nuclearcraft_jj_part_jj_8={need=1,tag=""},nuclearcraft_jj_salt_mixer_idle={need=1,tag=""}}},
 nuclearcraft_jj_electromagnet_supercooler_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_electromagnet_supercooler_idle={hasPattern=true,label="Supraleitender Superkühler",recipe={ic2_jj_ingot_jj_6={need=4,tag=""},nuclearcraft_jj_accelerator_electromagnet_idle={need=1,tag=""},nuclearcraft_jj_block_ice={need=4,tag=""},nuclearcraft_jj_ingot_jj_1={need=4,tag=""}}},
 nuclearcraft_jj_extractor_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_extractor_idle={hasPattern=true,label="Flüssigkeitenextraktor",recipe={minecraft_jj_bucket={need=2,tag=""},nuclearcraft_jj_alloy_furnace_idle={need=1,tag=""},nuclearcraft_jj_alloy_jj_4={need=4,tag=""},nuclearcraft_jj_ingot_jj_7={need=1,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""},nuclearcraft_jj_part_jj_10={need=1,tag=""},nuclearcraft_jj_part_jj_7={need=1,tag=""}}},
 nuclearcraft_jj_fission_block={hasPattern=true,label="Reaktorgehäuse",recipe={nuclearcraft_jj_alloy_jj_1={need=1,tag=""},nuclearcraft_jj_part={need=4,tag=""},nuclearcraft_jj_reactor_casing_transparent={need=1,tag=""}}},
 nuclearcraft_jj_fission_block_jj_1={hasPattern=true,label="Explosionssicherer Block",recipe={minecraft_jj_obsidian={need=1,tag=""},nuclearcraft_jj_part={need=4,tag=""}}},
 nuclearcraft_jj_fission_controller_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fission_controller_idle={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fission_controller_new_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fission_controller_new_fixed={hasPattern=true,label="Spaltungsregeler",recipe={nuclearcraft_jj_nuclear_furnace_idle={need=2,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""},nuclearcraft_jj_part_jj_10={need=1,tag=""},nuclearcraft_jj_part_jj_5={need=2,tag=""}}},
 nuclearcraft_jj_fission_controller_new_idle={hasPattern=false,label="",recipe={nuclearcraft_jj_nuclear_furnace_idle={need=1,tag=""},nuclearcraft_jj_part_jj_2={need=4,tag=""},nuclearcraft_jj_part_jj_5={need=4,tag=""}}},
 nuclearcraft_jj_fission_port={hasPattern=true,label="Reaktoröffnung",recipe={minecraft_jj_hopper={need=1,tag=""},nuclearcraft_jj_fission_block={need=2,tag=""},nuclearcraft_jj_part_jj_4={need=2,tag=""}}},
 nuclearcraft_jj_flour={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_alugentum={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_alumina={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_aluminum={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_ammonia={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_arsenic={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_bas={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_bef2={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_beryllium={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_borax_solution={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_boric_acid={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_boron={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_boron10={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_boron11={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_boron_nitride_solution={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_calcium_sulfate_solution={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_carbon_dioxide={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_carbon_monoxide={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_chocolate_liquor={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_cocoa_butter={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_condensate_water={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_corium={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_dark_chocolate={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_deuterium={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_diborane={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_ethanol={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_ethene={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_exhaust_steam={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_ferroboron={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_flibe={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_fluorine={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_fluorite_water={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_fluoromethane={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_gelatin={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_hard_carbon={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_helium={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_helium3={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_high_pressure_steam={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_hydrated_gelatin={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_hydrofluoric_acid={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_hydrogen={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_koh={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_lif={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_liquidhelium={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_lithium={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_lithium6={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_lithium7={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_low_pressure_steam={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_low_quality_steam={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_manganese={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_manganese_dioxide={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_marshmallow={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_methanol={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_milk={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_milk_chocolate={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_nak={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_nak_hot={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_naoh={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_neutron={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_nitrogen={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_oxygen={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_oxygen_difluoride={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_plasma={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_potassium={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_potassium_fluoride_solution={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_potassium_hydroxide_solution={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_preheated_water={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_radaway={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_sic_vapor={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_silver={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_sodium={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_sodium_fluoride_solution={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_sodium_hydroxide_solution={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_sugar={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_sulfur={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_sulfur_dioxide={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_sulfur_trioxide={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_sulfuric_acid={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_tough={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_tritium={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fluid_unsweetened_chocolate={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_foursmore={hasPattern=true,label="FourS'more QuadS'mingot",recipe={nuclearcraft_jj_marshmallow={need=1,tag=""},nuclearcraft_jj_milk_chocolate={need=1,tag=""},nuclearcraft_jj_moresmore={need=2,tag=""}}},
 nuclearcraft_jj_fuel_americium={hasPattern=true,label="LEA-242 Kernbrennstoff",recipe={nuclearcraft_jj_americium_jj_4={need=1,tag=""},nuclearcraft_jj_americium_jj_8={need=8,tag=""}}},
 nuclearcraft_jj_fuel_americium_jj_1={hasPattern=true,label="LEA-242 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_americium_jj_5={need=1,tag=""},nuclearcraft_jj_americium_jj_8={need=8,tag=""}}},
 nuclearcraft_jj_fuel_americium_jj_2={hasPattern=true,label="HEA-242 Kernbrennstoff",recipe={nuclearcraft_jj_americium_jj_4={need=4,tag=""},nuclearcraft_jj_americium_jj_8={need=5,tag=""}}},
 nuclearcraft_jj_fuel_americium_jj_3={hasPattern=true,label="HEA-242 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_americium_jj_5={need=4,tag=""},nuclearcraft_jj_americium_jj_8={need=5,tag=""}}},
 nuclearcraft_jj_fuel_berkelium={hasPattern=true,label="LEB-248 Kernbrennstoff",recipe={nuclearcraft_jj_berkelium={need=8,tag=""},nuclearcraft_jj_berkelium_jj_4={need=1,tag=""}}},
 nuclearcraft_jj_fuel_berkelium_jj_1={hasPattern=true,label="LEB-248 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_berkelium={need=8,tag=""},nuclearcraft_jj_berkelium_jj_5={need=1,tag=""}}},
 nuclearcraft_jj_fuel_berkelium_jj_2={hasPattern=true,label="HEB-248 Kernbrennstoff",recipe={nuclearcraft_jj_berkelium={need=5,tag=""},nuclearcraft_jj_berkelium_jj_4={need=4,tag=""}}},
 nuclearcraft_jj_fuel_berkelium_jj_3={hasPattern=true,label="HEB-248 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_berkelium={need=5,tag=""},nuclearcraft_jj_berkelium_jj_5={need=4,tag=""}}},
 nuclearcraft_jj_fuel_californium={hasPattern=true,label="LECf-249 Kernbrennstoff",recipe={nuclearcraft_jj_californium={need=1,tag=""},nuclearcraft_jj_californium_jj_12={need=8,tag=""}}},
 nuclearcraft_jj_fuel_californium_jj_1={hasPattern=true,label="LECf-249 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_californium_jj_1={need=1,tag=""},nuclearcraft_jj_californium_jj_12={need=8,tag=""}}},
 nuclearcraft_jj_fuel_californium_jj_2={hasPattern=true,label="HECf-249 Kernbrennstoff",recipe={nuclearcraft_jj_californium={need=4,tag=""},nuclearcraft_jj_californium_jj_12={need=5,tag=""}}},
 nuclearcraft_jj_fuel_californium_jj_3={hasPattern=true,label="HECf-249 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_californium_jj_1={need=4,tag=""},nuclearcraft_jj_californium_jj_12={need=5,tag=""}}},
 nuclearcraft_jj_fuel_californium_jj_4={hasPattern=true,label="LECf-251 Kernbrennstoff",recipe={nuclearcraft_jj_californium_jj_12={need=8,tag=""},nuclearcraft_jj_californium_jj_8={need=1,tag=""}}},
 nuclearcraft_jj_fuel_californium_jj_5={hasPattern=true,label="LECf-251 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_californium_jj_12={need=8,tag=""},nuclearcraft_jj_californium_jj_9={need=1,tag=""}}},
 nuclearcraft_jj_fuel_californium_jj_6={hasPattern=true,label="HECf-251 Kernbrennstoff",recipe={nuclearcraft_jj_californium_jj_12={need=5,tag=""},nuclearcraft_jj_californium_jj_8={need=4,tag=""}}},
 nuclearcraft_jj_fuel_californium_jj_7={hasPattern=true,label="HECf-251 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_californium_jj_12={need=5,tag=""},nuclearcraft_jj_californium_jj_9={need=4,tag=""}}},
 nuclearcraft_jj_fuel_curium={hasPattern=true,label="LECm-243 Kernbrennstoff",recipe={nuclearcraft_jj_curium={need=1,tag=""},nuclearcraft_jj_curium_jj_8={need=8,tag=""}}},
 nuclearcraft_jj_fuel_curium_jj_1={hasPattern=true,label="LECm-243 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_curium_jj_1={need=1,tag=""},nuclearcraft_jj_curium_jj_8={need=8,tag=""}}},
 nuclearcraft_jj_fuel_curium_jj_10={hasPattern=true,label="HECm-247 Kernbrennstoff",recipe={nuclearcraft_jj_curium_jj_12={need=4,tag=""},nuclearcraft_jj_curium_jj_8={need=5,tag=""}}},
 nuclearcraft_jj_fuel_curium_jj_11={hasPattern=true,label="HECm-247 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_curium_jj_13={need=4,tag=""},nuclearcraft_jj_curium_jj_8={need=5,tag=""}}},
 nuclearcraft_jj_fuel_curium_jj_2={hasPattern=true,label="HECm-243 Kernbrennstoff",recipe={nuclearcraft_jj_curium={need=4,tag=""},nuclearcraft_jj_curium_jj_8={need=5,tag=""}}},
 nuclearcraft_jj_fuel_curium_jj_3={hasPattern=true,label="HECm-243 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_curium_jj_1={need=4,tag=""},nuclearcraft_jj_curium_jj_8={need=5,tag=""}}},
 nuclearcraft_jj_fuel_curium_jj_4={hasPattern=true,label="LECm-245 Kernbrennstoff",recipe={nuclearcraft_jj_curium_jj_4={need=1,tag=""},nuclearcraft_jj_curium_jj_8={need=8,tag=""}}},
 nuclearcraft_jj_fuel_curium_jj_5={hasPattern=true,label="LECm-245 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_curium_jj_5={need=1,tag=""},nuclearcraft_jj_curium_jj_8={need=8,tag=""}}},
 nuclearcraft_jj_fuel_curium_jj_6={hasPattern=true,label="HECm-245 Kernbrennstoff",recipe={nuclearcraft_jj_curium_jj_4={need=4,tag=""},nuclearcraft_jj_curium_jj_8={need=5,tag=""}}},
 nuclearcraft_jj_fuel_curium_jj_7={hasPattern=true,label="HECm-245 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_curium_jj_5={need=4,tag=""},nuclearcraft_jj_curium_jj_8={need=5,tag=""}}},
 nuclearcraft_jj_fuel_curium_jj_8={hasPattern=true,label="LECm-247 Kernbrennstoff",recipe={nuclearcraft_jj_curium_jj_12={need=1,tag=""},nuclearcraft_jj_curium_jj_8={need=8,tag=""}}},
 nuclearcraft_jj_fuel_curium_jj_9={hasPattern=true,label="LECm-247 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_curium_jj_13={need=1,tag=""},nuclearcraft_jj_curium_jj_8={need=8,tag=""}}},
 nuclearcraft_jj_fuel_mixed_oxide={hasPattern=true,label="MOX-239 Kernbrennstoff",recipe={nuclearcraft_jj_plutonium_jj_5={need=1,tag=""},nuclearcraft_jj_uranium_jj_8={need=8,tag=""}}},
 nuclearcraft_jj_fuel_mixed_oxide_jj_1={hasPattern=true,label="MOX-241 Kernbrennstoff",recipe={nuclearcraft_jj_plutonium_jj_9={need=1,tag=""},nuclearcraft_jj_uranium_jj_8={need=8,tag=""}}},
 nuclearcraft_jj_fuel_neptunium={hasPattern=true,label="LEN-236 Kernbrennstoff",recipe={nuclearcraft_jj_neptunium={need=1,tag=""},nuclearcraft_jj_neptunium_jj_4={need=8,tag=""}}},
 nuclearcraft_jj_fuel_neptunium_jj_1={hasPattern=true,label="LEN-236 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_neptunium_jj_1={need=1,tag=""},nuclearcraft_jj_neptunium_jj_4={need=8,tag=""}}},
 nuclearcraft_jj_fuel_neptunium_jj_2={hasPattern=true,label="HEN-236 Kernbrennstoff",recipe={nuclearcraft_jj_neptunium={need=4,tag=""},nuclearcraft_jj_neptunium_jj_4={need=5,tag=""}}},
 nuclearcraft_jj_fuel_neptunium_jj_3={hasPattern=true,label="HEN-236 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_neptunium_jj_1={need=4,tag=""},nuclearcraft_jj_neptunium_jj_4={need=5,tag=""}}},
 nuclearcraft_jj_fuel_plutonium={hasPattern=true,label="LEP-239 Kernbrennstoff",recipe={nuclearcraft_jj_plutonium_jj_12={need=8,tag=""},nuclearcraft_jj_plutonium_jj_4={need=1,tag=""}}},
 nuclearcraft_jj_fuel_plutonium_jj_1={hasPattern=true,label="LEP-239 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_plutonium_jj_12={need=8,tag=""},nuclearcraft_jj_plutonium_jj_5={need=1,tag=""}}},
 nuclearcraft_jj_fuel_plutonium_jj_2={hasPattern=true,label="HEP-239 Kernbrennstoff",recipe={nuclearcraft_jj_plutonium_jj_12={need=5,tag=""},nuclearcraft_jj_plutonium_jj_4={need=4,tag=""}}},
 nuclearcraft_jj_fuel_plutonium_jj_3={hasPattern=true,label="HEP-239 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_plutonium_jj_12={need=5,tag=""},nuclearcraft_jj_plutonium_jj_5={need=4,tag=""}}},
 nuclearcraft_jj_fuel_plutonium_jj_4={hasPattern=true,label="LEP-241 Kernbrennstoff",recipe={nuclearcraft_jj_plutonium_jj_12={need=8,tag=""},nuclearcraft_jj_plutonium_jj_8={need=1,tag=""}}},
 nuclearcraft_jj_fuel_plutonium_jj_5={hasPattern=true,label="LEP-241 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_plutonium_jj_12={need=8,tag=""},nuclearcraft_jj_plutonium_jj_9={need=1,tag=""}}},
 nuclearcraft_jj_fuel_plutonium_jj_6={hasPattern=true,label="HEP-241 Kernbrennstoff",recipe={nuclearcraft_jj_plutonium_jj_12={need=5,tag=""},nuclearcraft_jj_plutonium_jj_8={need=4,tag=""}}},
 nuclearcraft_jj_fuel_plutonium_jj_7={hasPattern=true,label="HEP-241 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_plutonium_jj_12={need=5,tag=""},nuclearcraft_jj_plutonium_jj_9={need=4,tag=""}}},
 nuclearcraft_jj_fuel_reprocessor_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fuel_reprocessor_idle={hasPattern=false,label="",recipe={nuclearcraft_jj_alloy={need=4,tag=""},nuclearcraft_jj_alloy_furnace_idle={need=1,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""}}},
 nuclearcraft_jj_fuel_rod={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fuel_thorium={hasPattern=true,label="TBU Kernbrennstoff",recipe={nuclearcraft_jj_thorium_jj_4={need=9,tag=""}}},
 nuclearcraft_jj_fuel_thorium_jj_1={hasPattern=true,label="TBU Oxid Kernbrennstoff",recipe={nuclearcraft_jj_thorium_jj_5={need=9,tag=""}}},
 nuclearcraft_jj_fuel_uranium={hasPattern=true,label="LEU-233 Kernbrennstoff",recipe={nuclearcraft_jj_uranium={need=1,tag=""},nuclearcraft_jj_uranium_jj_8={need=8,tag=""}}},
 nuclearcraft_jj_fuel_uranium_jj_1={hasPattern=true,label="LEU-233 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_uranium_jj_1={need=1,tag=""},nuclearcraft_jj_uranium_jj_8={need=8,tag=""}}},
 nuclearcraft_jj_fuel_uranium_jj_2={hasPattern=true,label="HEU-233 Kernbrennstoff",recipe={nuclearcraft_jj_uranium={need=4,tag=""},nuclearcraft_jj_uranium_jj_8={need=5,tag=""}}},
 nuclearcraft_jj_fuel_uranium_jj_3={hasPattern=true,label="HEU-233 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_uranium_jj_1={need=4,tag=""},nuclearcraft_jj_uranium_jj_8={need=5,tag=""}}},
 nuclearcraft_jj_fuel_uranium_jj_4={hasPattern=true,label="LEU-235 Kernbrennstoff",recipe={nuclearcraft_jj_uranium_jj_4={need=1,tag=""},nuclearcraft_jj_uranium_jj_8={need=8,tag=""}}},
 nuclearcraft_jj_fuel_uranium_jj_5={hasPattern=true,label="LEU-235 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_uranium_jj_5={need=1,tag=""},nuclearcraft_jj_uranium_jj_8={need=8,tag=""}}},
 nuclearcraft_jj_fuel_uranium_jj_6={hasPattern=true,label="HEU-235 Kernbrennstoff",recipe={nuclearcraft_jj_uranium_jj_4={need=4,tag=""},nuclearcraft_jj_uranium_jj_8={need=5,tag=""}}},
 nuclearcraft_jj_fuel_uranium_jj_7={hasPattern=true,label="HEU-235 Oxid Kernbrennstoff",recipe={nuclearcraft_jj_uranium_jj_5={need=4,tag=""},nuclearcraft_jj_uranium_jj_8={need=5,tag=""}}},
 nuclearcraft_jj_fusion_connector={hasPattern=true,label="Fusionskonnektor",recipe={ic2_jj_ingot_jj_2={need=1,tag=""},nuclearcraft_jj_alloy_jj_1={need=4,tag=""},nuclearcraft_jj_ingot={need=1,tag=""},nuclearcraft_jj_part={need=4,tag=""}}},
 nuclearcraft_jj_fusion_core={hasPattern=false,label="",recipe={nuclearcraft_jj_chemical_reactor_idle={need=1,tag=""},nuclearcraft_jj_part_jj_3={need=4,tag=""},nuclearcraft_jj_part_jj_5={need=4,tag=""}}},
 nuclearcraft_jj_fusion_dummy_side={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fusion_dummy_top={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fusion_electromagnet_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fusion_electromagnet_idle={hasPattern=true,label="Fusionselektromagnet",recipe={nuclearcraft_jj_part_jj_1={need=4,tag=""},nuclearcraft_jj_part_jj_4={need=4,tag=""}}},
 nuclearcraft_jj_fusion_electromagnet_transparent_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_fusion_electromagnet_transparent_idle={hasPattern=true,label="Transparenter Fusionselektromagnet",recipe={minecraft_jj_glass={need=1,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""},nuclearcraft_jj_part_jj_4={need=4,tag=""}}},
 nuclearcraft_jj_geiger_block={hasPattern=true,label="Geiger Counter Block",recipe={nuclearcraft_jj_geiger_counter={need=1,tag=""},nuclearcraft_jj_part={need=4,tag=""}}},
 nuclearcraft_jj_geiger_counter={hasPattern=true,label="Geiger Counter",recipe={minecraft_jj_redstone={need=2,tag=""},nuclearcraft_jj_alloy_jj_5={need=1,tag=""},nuclearcraft_jj_alloy_jj_6={need=4,tag=""},nuclearcraft_jj_ingot={need=1,tag=""},nuclearcraft_jj_part_jj_6={need=1,tag=""}}},
 nuclearcraft_jj_gelatin={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_gem={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_gem_dust={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_gem_dust_jj_1={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_gem_dust_jj_10={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_gem_dust_jj_11={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_gem_dust_jj_2={hasPattern=false,label="",recipe={ore_jj_dustPetrotheum={need=1,tag=""},ore_jj_oreQuartz={need=1,tag=""}}},
 nuclearcraft_jj_gem_dust_jj_3={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_gem_dust_jj_4={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_gem_dust_jj_5={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_gem_dust_jj_6={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_gem_dust_jj_7={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_gem_dust_jj_8={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_gem_dust_jj_9={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_gem_jj_1={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_gem_jj_2={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_gem_jj_3={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_gem_jj_4={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_gem_jj_5={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_gem_jj_6={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_glowing_mushroom={hasPattern=true,label="Strahlender Pilz",recipe={minecraft_jj_brown_mushroom={need=1,tag=""},minecraft_jj_glowstone_dust={need=1,tag=""}}},
 nuclearcraft_jj_graham_cracker={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_ground_cocoa_nibs={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_heat_exchanger_computer_port={hasPattern=true,label="Heat Exchanger Computer Port",recipe={nuclearcraft_jj_heat_exchanger_wall={need=1,tag=""},opencomputers_jj_cable_jj_11250603={need=2,tag=""},opencomputers_jj_material_jj_4={need=1,tag=""},opencomputers_jj_material_jj_7={need=1,tag=""}}},
 nuclearcraft_jj_heat_exchanger_controller={hasPattern=true,label="Heat Exchanger Controller",recipe={nuclearcraft_jj_alloy_jj_11={need=2,tag=""},nuclearcraft_jj_alloy_jj_5={need=2,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""},nuclearcraft_jj_part_jj_12={need=1,tag=""}}},
 nuclearcraft_jj_heat_exchanger_frame={hasPattern=true,label="Heat Exchanger Frame",recipe={nuclearcraft_jj_alloy_jj_5={need=4,tag=""},nuclearcraft_jj_heat_exchanger_wall={need=5,tag=""}}},
 nuclearcraft_jj_heat_exchanger_glass={hasPattern=true,label="Transparent Heat Exchanger Shell",recipe={minecraft_jj_glass={need=1,tag=""},nuclearcraft_jj_heat_exchanger_wall={need=1,tag=""}}},
 nuclearcraft_jj_heat_exchanger_tube_copper={hasPattern=true,label="Copper Heat Exchanger Tube",recipe={nuclearcraft_jj_ingot={need=3,tag=""},nuclearcraft_jj_part={need=4,tag=""},nuclearcraft_jj_part_jj_12={need=1,tag=""},nuclearcraft_jj_part_jj_7={need=1,tag=""}}},
 nuclearcraft_jj_heat_exchanger_tube_hard_carbon={hasPattern=true,label="Hard Carbon Heat Exchanger Tube",recipe={nuclearcraft_jj_alloy_jj_2={need=3,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""},nuclearcraft_jj_part_jj_12={need=1,tag=""},nuclearcraft_jj_part_jj_7={need=1,tag=""}}},
 nuclearcraft_jj_heat_exchanger_tube_thermoconducting={hasPattern=true,label="Thermoconducting Alloy Heat Exchanger Tube",recipe={nuclearcraft_jj_alloy_jj_11={need=3,tag=""},nuclearcraft_jj_part_jj_12={need=1,tag=""},nuclearcraft_jj_part_jj_3={need=4,tag=""},nuclearcraft_jj_part_jj_7={need=1,tag=""}}},
 nuclearcraft_jj_heat_exchanger_vent={hasPattern=true,label="Heat Exchanger Vent",recipe={minecraft_jj_stone={need=2,tag=""},nuclearcraft_jj_alloy_jj_5={need=4,tag=""},nuclearcraft_jj_part_jj_12={need=1,tag=""},nuclearcraft_jj_part_jj_7={need=2,tag=""}}},
 nuclearcraft_jj_heat_exchanger_wall={hasPattern=true,label="Heat Exchanger Shell",recipe={minecraft_jj_stone={need=4,tag=""},nuclearcraft_jj_alloy_jj_5={need=4,tag=""},nuclearcraft_jj_part_jj_12={need=1,tag=""}}},
 nuclearcraft_jj_helium_collector={hasPattern=true,label="Heliumsammler",recipe={nuclearcraft_jj_block_depleted_thorium={need=1,tag=""},nuclearcraft_jj_ingot_jj_1={need=4,tag=""},nuclearcraft_jj_ingot_jj_10={need=4,tag=""},nuclearcraft_jj_part={need=4,tag=""}}},
 nuclearcraft_jj_helium_collector_compact={hasPattern=true,label="Kompakter Heliumsammler",recipe={ic2_jj_ingot_jj_1={need=1,tag=""},nuclearcraft_jj_alloy={need=1,tag=""},nuclearcraft_jj_helium_collector={need=8,tag=""}}},
 nuclearcraft_jj_helium_collector_dense={hasPattern=true,label="Dichter Heliumsammler",recipe={minecraft_jj_gold_ingot={need=1,tag=""},nuclearcraft_jj_helium_collector_compact={need=8,tag=""}}},
 nuclearcraft_jj_helm_boron={hasPattern=true,label="Borhelm",recipe={nuclearcraft_jj_ingot_jj_5={need=5,tag=""}}},
 nuclearcraft_jj_helm_boron_nitride={hasPattern=true,label="Bornitridhelm",recipe={nuclearcraft_jj_gem_jj_1={need=5,tag=""}}},
 nuclearcraft_jj_helm_hard_carbon={hasPattern=true,label="Harter Kohlenstoffhelm",recipe={nuclearcraft_jj_alloy_jj_2={need=5,tag=""}}},
 nuclearcraft_jj_helm_hazmat={hasPattern=true,label="Hazmat Suit Headwear",recipe={minecraft_jj_dye_jj_11={need=2,tag=""},minecraft_jj_leather_helmet={need=1,tag=""},minecraft_jj_wool={need=1,tag=""},nuclearcraft_jj_alloy_jj_5={need=1,tag=""},nuclearcraft_jj_part_jj_6={need=2,tag=""},nuclearcraft_jj_rad_shielding_jj_2={need=2,tag=""}}},
 nuclearcraft_jj_helm_tough={hasPattern=true,label="Harter Legierungshelm",recipe={nuclearcraft_jj_alloy_jj_1={need=5,tag=""}}},
 nuclearcraft_jj_hoe_boron={hasPattern=true,label="Borhacke",recipe={minecraft_jj_stick={need=2,tag=""},nuclearcraft_jj_ingot_jj_5={need=2,tag=""}}},
 nuclearcraft_jj_hoe_boron_nitride={hasPattern=true,label="Bornitridhacke",recipe={minecraft_jj_stick={need=2,tag=""},nuclearcraft_jj_gem_jj_1={need=2,tag=""}}},
 nuclearcraft_jj_hoe_hard_carbon={hasPattern=true,label="Harte Kohlenstoffhacke",recipe={minecraft_jj_stick={need=2,tag=""},nuclearcraft_jj_alloy_jj_2={need=2,tag=""}}},
 nuclearcraft_jj_hoe_tough={hasPattern=true,label="Harte Legierungshacke",recipe={minecraft_jj_stick={need=2,tag=""},nuclearcraft_jj_alloy_jj_1={need=2,tag=""}}},
 nuclearcraft_jj_infuser_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_infuser_idle={hasPattern=false,label="",recipe={nuclearcraft_jj_alloy_furnace_idle={need=1,tag=""},nuclearcraft_jj_ingot_jj_1={need=4,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""}}},
 nuclearcraft_jj_ingot={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot_block={need=1,tag=""}}},
 nuclearcraft_jj_ingot_block={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot={need=9,tag=""}}},
 nuclearcraft_jj_ingot_block_jj_1={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot_jj_1={need=9,tag=""}}},
 nuclearcraft_jj_ingot_block_jj_10={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot_jj_10={need=9,tag=""}}},
 nuclearcraft_jj_ingot_block_jj_11={hasPattern=true,label="Manganese Block",recipe={nuclearcraft_jj_ingot_jj_11={need=9,tag=""}}},
 nuclearcraft_jj_ingot_block_jj_12={hasPattern=true,label="Aluminum Block",recipe={nuclearcraft_jj_ingot_jj_12={need=9,tag=""}}},
 nuclearcraft_jj_ingot_block_jj_13={hasPattern=true,label="Silver Block",recipe={nuclearcraft_jj_ingot_jj_13={need=9,tag=""}}},
 nuclearcraft_jj_ingot_block_jj_2={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot_jj_2={need=9,tag=""}}},
 nuclearcraft_jj_ingot_block_jj_3={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot_jj_3={need=9,tag=""}}},
 nuclearcraft_jj_ingot_block_jj_4={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot_jj_4={need=9,tag=""}}},
 nuclearcraft_jj_ingot_block_jj_5={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot_jj_5={need=9,tag=""}}},
 nuclearcraft_jj_ingot_block_jj_6={hasPattern=true,label="Lithiumblock",recipe={nuclearcraft_jj_ingot_jj_6={need=9,tag=""}}},
 nuclearcraft_jj_ingot_block_jj_7={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot_jj_7={need=9,tag=""}}},
 nuclearcraft_jj_ingot_block_jj_8={hasPattern=true,label="Graphitblock",recipe={nuclearcraft_jj_ingot_jj_8={need=9,tag=""}}},
 nuclearcraft_jj_ingot_block_jj_9={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot_jj_9={need=9,tag=""}}},
 nuclearcraft_jj_ingot_former_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_ingot_former_idle={hasPattern=true,label="Barrenformer",recipe={minecraft_jj_hopper={need=1,tag=""},nuclearcraft_jj_alloy_jj_1={need=1,tag=""},nuclearcraft_jj_alloy_jj_6={need=2,tag=""},nuclearcraft_jj_ingot_jj_5={need=4,tag=""},nuclearcraft_jj_manufactory_idle={need=1,tag=""},nuclearcraft_jj_part={need=4,tag=""},nuclearcraft_jj_part_jj_10={need=1,tag=""}}},
 nuclearcraft_jj_ingot_jj_1={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot_block_jj_1={need=1,tag=""}}},
 nuclearcraft_jj_ingot_jj_10={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot_block_jj_10={need=1,tag=""}}},
 nuclearcraft_jj_ingot_jj_11={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_ingot_jj_12={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_ingot_jj_13={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_ingot_jj_2={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot_block_jj_2={need=1,tag=""}}},
 nuclearcraft_jj_ingot_jj_3={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot_block_jj_3={need=1,tag=""}}},
 nuclearcraft_jj_ingot_jj_4={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot_block_jj_4={need=1,tag=""}}},
 nuclearcraft_jj_ingot_jj_5={hasPattern=false,label="",recipe={ore_jj_dustBoron={need=1,tag=""},ore_jj_dustPyrotheum={need=1,tag=""}}},
 nuclearcraft_jj_ingot_jj_6={hasPattern=false,label="",recipe={ore_jj_dustPetrotheum={need=1,tag=""},ore_jj_dustPyrotheum={need=1,tag=""},ore_jj_oreLithium={need=1,tag=""}}},
 nuclearcraft_jj_ingot_jj_7={hasPattern=false,label="",recipe={nuclearcraft_jj_ore_jj_7={need=1,tag=""},ore_jj_dustPetrotheum={need=1,tag=""},ore_jj_dustPyrotheum={need=1,tag=""}}},
 nuclearcraft_jj_ingot_jj_8={hasPattern=false,label="",recipe={nuclearcraft_jj_ingot_block_jj_8={need=1,tag=""}}},
 nuclearcraft_jj_ingot_jj_9={hasPattern=false,label="",recipe={modernmetals_jj_beryllium_ore={need=1,tag=""},ore_jj_dustPetrotheum={need=1,tag=""},ore_jj_dustPyrotheum={need=1,tag=""}}},
 nuclearcraft_jj_ingot_oxide={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_ingot_oxide_jj_1={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_ingot_oxide_jj_2={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_ingot_oxide_jj_3={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_irradiator_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_irradiator_idle={hasPattern=true,label="Neutronenirritierer",recipe={minecraft_jj_ender_pearl={need=1,tag=""},minecraft_jj_gold_ingot={need=4,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""},nuclearcraft_jj_part_jj_10={need=1,tag=""},nuclearcraft_jj_part_jj_4={need=2,tag=""},nuclearcraft_jj_part_jj_7={need=1,tag=""},nuclearcraft_jj_salt_mixer_idle={need=1,tag=""}}},
 nuclearcraft_jj_isotope_separator_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_isotope_separator_idle={hasPattern=true,label="Isotopenseparator",recipe={minecraft_jj_redstone={need=2,tag=""},nuclearcraft_jj_alloy_furnace_idle={need=1,tag=""},nuclearcraft_jj_alloy_jj_6={need=4,tag=""},nuclearcraft_jj_part={need=4,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""},nuclearcraft_jj_part_jj_10={need=1,tag=""},nuclearcraft_jj_part_jj_8={need=2,tag=""}}},
 nuclearcraft_jj_legs_boron={hasPattern=true,label="Borhosen",recipe={nuclearcraft_jj_ingot_jj_5={need=7,tag=""}}},
 nuclearcraft_jj_legs_boron_nitride={hasPattern=true,label="Bornitridhosen",recipe={nuclearcraft_jj_gem_jj_1={need=7,tag=""}}},
 nuclearcraft_jj_legs_hard_carbon={hasPattern=true,label="Harte Kohlenstoffhosen",recipe={nuclearcraft_jj_alloy_jj_2={need=7,tag=""}}},
 nuclearcraft_jj_legs_hazmat={hasPattern=true,label="Hazmat Suit Leggings",recipe={minecraft_jj_dye_jj_11={need=2,tag=""},minecraft_jj_leather_leggings={need=1,tag=""},minecraft_jj_wool={need=2,tag=""},nuclearcraft_jj_part_jj_6={need=1,tag=""},nuclearcraft_jj_rad_shielding_jj_2={need=2,tag=""}}},
 nuclearcraft_jj_legs_tough={hasPattern=true,label="Harte Legierungshosen",recipe={nuclearcraft_jj_alloy_jj_1={need=7,tag=""}}},
 nuclearcraft_jj_lithium={hasPattern=false,label="",recipe={ore_jj_nuggetLithium6={need=9,tag=""}}},
 nuclearcraft_jj_lithium_ion_battery_basic={hasPattern=true,label="Einfache Lithium Ionen Batterie",recipe={nuclearcraft_jj_lithium_ion_cell={need=4,tag=""},nuclearcraft_jj_part_jj_3={need=4,tag=""},nuclearcraft_jj_part_jj_5={need=1,tag=""}}},
 nuclearcraft_jj_lithium_jj_1={hasPattern=false,label="",recipe={ore_jj_ingotLithium6={need=1,tag=""}}},
 nuclearcraft_jj_lithium_jj_2={hasPattern=false,label="",recipe={ore_jj_nuggetLithium7={need=9,tag=""}}},
 nuclearcraft_jj_lithium_jj_3={hasPattern=false,label="",recipe={ore_jj_ingotLithium7={need=1,tag=""}}},
 nuclearcraft_jj_machine_interface={hasPattern=true,label="Maschineninterface",recipe={nuclearcraft_jj_buffer={need=1,tag=""},nuclearcraft_jj_part={need=4,tag=""},nuclearcraft_jj_part_jj_10={need=1,tag=""},nuclearcraft_jj_part_jj_7={need=1,tag=""},nuclearcraft_jj_part_jj_8={need=2,tag=""},nuclearcraft_jj_part_jj_9={need=1,tag=""}}},
 nuclearcraft_jj_manufactory_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_manufactory_idle={hasPattern=true,label="Manufaktur",recipe={minecraft_jj_flint={need=2,tag=""},minecraft_jj_piston={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""},nuclearcraft_jj_ingot_jj_2={need=4,tag=""},nuclearcraft_jj_part_jj_4={need=1,tag=""}}},
 nuclearcraft_jj_marshmallow={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_melter_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_melter_idle={hasPattern=true,label="Schmelzer",recipe={minecraft_jj_netherbrick={need=3,tag=""},nuclearcraft_jj_alloy_furnace_idle={need=1,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""},nuclearcraft_jj_part_jj_10={need=1,tag=""},nuclearcraft_jj_part_jj_7={need=1,tag=""}}},
 nuclearcraft_jj_milk_chocolate={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_moresmore={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_neptunium={hasPattern=false,label="",recipe={ore_jj_nuggetNeptunium236={need=9,tag=""}}},
 nuclearcraft_jj_neptunium_jj_1={hasPattern=false,label="",recipe={ore_jj_nuggetNeptunium236Oxide={need=9,tag=""}}},
 nuclearcraft_jj_neptunium_jj_2={hasPattern=false,label="",recipe={ore_jj_ingotNeptunium236Base={need=1,tag=""}}},
 nuclearcraft_jj_neptunium_jj_3={hasPattern=false,label="",recipe={nuclearcraft_jj_neptunium_jj_1={need=1,tag=""}}},
 nuclearcraft_jj_neptunium_jj_4={hasPattern=false,label="",recipe={ore_jj_nuggetNeptunium237={need=9,tag=""}}},
 nuclearcraft_jj_neptunium_jj_5={hasPattern=false,label="",recipe={ore_jj_nuggetNeptunium237Oxide={need=9,tag=""}}},
 nuclearcraft_jj_neptunium_jj_6={hasPattern=false,label="",recipe={ore_jj_ingotNeptunium237Base={need=1,tag=""}}},
 nuclearcraft_jj_neptunium_jj_7={hasPattern=false,label="",recipe={ore_jj_ingotNeptunium237Oxide={need=1,tag=""}}},
 nuclearcraft_jj_nitrogen_collector={hasPattern=true,label="Stickstoffsammler",recipe={minecraft_jj_bucket={need=2,tag=""},nuclearcraft_jj_ingot_jj_9={need=2,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""}}},
 nuclearcraft_jj_nitrogen_collector_compact={hasPattern=true,label="Kompakter Stickstoffsammler",recipe={ic2_jj_ingot_jj_1={need=1,tag=""},nuclearcraft_jj_alloy={need=1,tag=""},nuclearcraft_jj_nitrogen_collector={need=8,tag=""}}},
 nuclearcraft_jj_nitrogen_collector_dense={hasPattern=true,label="Dichter Stickstoffsammler",recipe={minecraft_jj_gold_ingot={need=1,tag=""},nuclearcraft_jj_nitrogen_collector_compact={need=8,tag=""}}},
 nuclearcraft_jj_nuclear_furnace_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_nuclear_furnace_idle={hasPattern=true,label="Atomofen",recipe={minecraft_jj_furnace={need=1,tag=""},nuclearcraft_jj_alloy_jj_1={need=4,tag=""},nuclearcraft_jj_part={need=4,tag=""}}},
 nuclearcraft_jj_ore={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_ore_jj_1={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_ore_jj_2={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_ore_jj_3={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_ore_jj_4={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_ore_jj_5={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_ore_jj_6={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_ore_jj_7={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_part={hasPattern=true,label="Einfache Platte",recipe={ic2_jj_ingot_jj_3={need=2,tag=""},nuclearcraft_jj_dust_jj_8={need=2,tag=""},nuclearcraft_jj_ingot_jj_2={need=2,tag=""}}},
 nuclearcraft_jj_part_jj_1={hasPattern=true,label="Fortgeschrittene Platte",recipe={minecraft_jj_redstone={need=4,tag=""},nuclearcraft_jj_alloy_jj_1={need=4,tag=""},nuclearcraft_jj_part={need=1,tag=""}}},
 nuclearcraft_jj_part_jj_10={hasPattern=true,label="Maschinengehäuse",recipe={nuclearcraft_jj_alloy_jj_1={need=1,tag=""},nuclearcraft_jj_alloy_jj_5={need=4,tag=""},nuclearcraft_jj_ingot_jj_2={need=4,tag=""}}},
 nuclearcraft_jj_part_jj_11={hasPattern=true,label="Leerer Rahmen",recipe={minecraft_jj_iron_ingot={need=2,tag=""},nuclearcraft_jj_ingot_jj_1={need=2,tag=""},nuclearcraft_jj_part={need=4,tag=""}}},
 nuclearcraft_jj_part_jj_12={hasPattern=true,label="Steel Frame",recipe={nuclearcraft_jj_alloy={need=1,tag=""},nuclearcraft_jj_alloy_jj_1={need=4,tag=""},nuclearcraft_jj_alloy_jj_5={need=4,tag=""}}},
 nuclearcraft_jj_part_jj_13={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_part_jj_2={hasPattern=true,label="DU Platte",recipe={ic2_jj_dust_jj_16={need=4,tag=""},nuclearcraft_jj_gem_dust_jj_6={need=4,tag=""},nuclearcraft_jj_part_jj_1={need=1,tag=""},nuclearcraft_jj_uranium_jj_8={need=4,tag=""}}},
 nuclearcraft_jj_part_jj_3={hasPattern=true,label="Eliteplatte",recipe={nuclearcraft_jj_compound_jj_1={need=4,tag=""},nuclearcraft_jj_ingot_jj_5={need=4,tag=""},nuclearcraft_jj_part_jj_2={need=1,tag=""}}},
 nuclearcraft_jj_part_jj_4={hasPattern=true,label="Kupfersolenoid",recipe={ic2_jj_ingot_jj_2={need=4,tag=""},minecraft_jj_iron_ingot={need=2,tag=""},nuclearcraft_jj_ingot={need=4,tag=""}}},
 nuclearcraft_jj_part_jj_5={hasPattern=true,label="Magnesiumdiboridsolenoid",recipe={nuclearcraft_jj_alloy_jj_1={need=2,tag=""},nuclearcraft_jj_alloy_jj_3={need=4,tag=""}}},
 nuclearcraft_jj_part_jj_6={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_part_jj_7={hasPattern=true,label="Servomechanismus",recipe={minecraft_jj_redstone={need=2,tag=""},nuclearcraft_jj_alloy_jj_5={need=3,tag=""},nuclearcraft_jj_alloy_jj_6={need=2,tag=""},nuclearcraft_jj_ingot={need=1,tag=""}}},
 nuclearcraft_jj_part_jj_8={hasPattern=true,label="Elektromotor",recipe={minecraft_jj_gold_nugget={need=2,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},nuclearcraft_jj_alloy_jj_5={need=4,tag=""},nuclearcraft_jj_part_jj_4={need=2,tag=""}}},
 nuclearcraft_jj_part_jj_9={hasPattern=true,label="Linearer Auslöser",recipe={minecraft_jj_piston={need=1,tag=""},nuclearcraft_jj_alloy_jj_5={need=1,tag=""},nuclearcraft_jj_alloy_jj_6={need=2,tag=""},nuclearcraft_jj_ingot={need=1,tag=""}}},
 nuclearcraft_jj_pickaxe_boron={hasPattern=true,label="Borspitzhacke",recipe={minecraft_jj_stick={need=2,tag=""},nuclearcraft_jj_ingot_jj_5={need=3,tag=""}}},
 nuclearcraft_jj_pickaxe_boron_nitride={hasPattern=true,label="Bornitridspitzhacke",recipe={minecraft_jj_stick={need=2,tag=""},nuclearcraft_jj_gem_jj_1={need=3,tag=""}}},
 nuclearcraft_jj_pickaxe_hard_carbon={hasPattern=true,label="Harte Kohlenstoffspitzhacke",recipe={minecraft_jj_stick={need=2,tag=""},nuclearcraft_jj_alloy_jj_2={need=3,tag=""}}},
 nuclearcraft_jj_pickaxe_tough={hasPattern=true,label="Harte Legierungsspitzhacke",recipe={minecraft_jj_stick={need=2,tag=""},nuclearcraft_jj_alloy_jj_1={need=3,tag=""}}},
 nuclearcraft_jj_plutonium={hasPattern=false,label="",recipe={ore_jj_nuggetPlutonium238={need=9,tag=""}}},
 nuclearcraft_jj_plutonium_jj_1={hasPattern=false,label="",recipe={ore_jj_nuggetPlutonium238Oxide={need=9,tag=""}}},
 nuclearcraft_jj_plutonium_jj_10={hasPattern=false,label="",recipe={ore_jj_ingotPlutonium241Base={need=1,tag=""}}},
 nuclearcraft_jj_plutonium_jj_11={hasPattern=false,label="",recipe={nuclearcraft_jj_plutonium_jj_9={need=1,tag=""}}},
 nuclearcraft_jj_plutonium_jj_12={hasPattern=false,label="",recipe={ore_jj_blockDepletedPlutonium={need=1,tag=""}}},
 nuclearcraft_jj_plutonium_jj_13={hasPattern=false,label="",recipe={ore_jj_nuggetPlutonium242Oxide={need=9,tag=""}}},
 nuclearcraft_jj_plutonium_jj_14={hasPattern=false,label="",recipe={ore_jj_ingotPlutonium242Base={need=1,tag=""}}},
 nuclearcraft_jj_plutonium_jj_15={hasPattern=false,label="",recipe={ore_jj_ingotPlutonium242Oxide={need=1,tag=""}}},
 nuclearcraft_jj_plutonium_jj_2={hasPattern=false,label="",recipe={ore_jj_ingotPlutonium238Base={need=1,tag=""}}},
 nuclearcraft_jj_plutonium_jj_3={hasPattern=false,label="",recipe={ore_jj_ingotPlutonium238Oxide={need=1,tag=""}}},
 nuclearcraft_jj_plutonium_jj_4={hasPattern=false,label="",recipe={ore_jj_nuggetPlutonium239={need=9,tag=""}}},
 nuclearcraft_jj_plutonium_jj_5={hasPattern=false,label="",recipe={ore_jj_nuggetPlutonium239Oxide={need=9,tag=""}}},
 nuclearcraft_jj_plutonium_jj_6={hasPattern=false,label="",recipe={ore_jj_ingotPlutonium239Base={need=1,tag=""}}},
 nuclearcraft_jj_plutonium_jj_7={hasPattern=false,label="",recipe={nuclearcraft_jj_plutonium_jj_5={need=1,tag=""}}},
 nuclearcraft_jj_plutonium_jj_8={hasPattern=false,label="",recipe={ore_jj_nuggetPlutonium241={need=9,tag=""}}},
 nuclearcraft_jj_plutonium_jj_9={hasPattern=false,label="",recipe={ore_jj_nuggetPlutonium241Oxide={need=9,tag=""}}},
 nuclearcraft_jj_portable_ender_chest={hasPattern=true,label="Portable Endertruhe",recipe={minecraft_jj_ender_chest={need=1,tag=""},minecraft_jj_string={need=1,tag=""},minecraft_jj_wool_jj_10={need=3,tag=""},nuclearcraft_jj_alloy_jj_1={need=2,tag=""}}},
 nuclearcraft_jj_pressurizer_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_pressurizer_idle={hasPattern=true,label="Komprimierer",recipe={minecraft_jj_piston={need=4,tag=""},nuclearcraft_jj_alloy_furnace_idle={need=1,tag=""},nuclearcraft_jj_alloy_jj_1={need=2,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""},nuclearcraft_jj_part_jj_10={need=1,tag=""},nuclearcraft_jj_part_jj_9={need=2,tag=""}}},
 nuclearcraft_jj_rad_shielding={hasPattern=true,label="Light Radiation Shielding",recipe={minecraft_jj_coal={need=3,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},nuclearcraft_jj_ingot_jj_2={need=3,tag=""}}},
 nuclearcraft_jj_rad_shielding_jj_1={hasPattern=true,label="Medium Radiation Shielding",recipe={nuclearcraft_jj_alloy_jj_6={need=1,tag=""},nuclearcraft_jj_part={need=3,tag=""},nuclearcraft_jj_part_jj_6={need=3,tag=""},nuclearcraft_jj_rad_shielding={need=2,tag=""}}},
 nuclearcraft_jj_rad_shielding_jj_2={hasPattern=true,label="Heavy Radiation Shielding",recipe={nuclearcraft_jj_alloy_jj_2={need=1,tag=""},nuclearcraft_jj_ingot_jj_9={need=3,tag=""},nuclearcraft_jj_part_jj_2={need=3,tag=""},nuclearcraft_jj_rad_shielding_jj_1={need=2,tag=""}}},
 nuclearcraft_jj_rad_x={hasPattern=true,label="Rad-X",recipe={minecraft_jj_blaze_powder={need=1,tag=""},nuclearcraft_jj_compound_jj_2={need=2,tag=""},nuclearcraft_jj_part_jj_6={need=5,tag=""},nuclearcraft_jj_radaway={need=1,tag=""}}},
 nuclearcraft_jj_radaway={hasPattern=true,label="RadAway",recipe={nuclearcraft_jj_part_jj_6={need=2,tag=""}}},
 nuclearcraft_jj_radiation_badge={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_radiation_scrubber={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_reactor_casing_transparent={hasPattern=true,label="Transparentes Reaktorgehäuse",recipe={minecraft_jj_glass={need=4,tag=""},nuclearcraft_jj_alloy_jj_1={need=1,tag=""},nuclearcraft_jj_fission_block={need=1,tag=""},nuclearcraft_jj_part={need=4,tag=""}}},
 nuclearcraft_jj_reactor_door={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_reactor_door_item={hasPattern=true,label="Reaktortür",recipe={nuclearcraft_jj_fission_block={need=6,tag=""}}},
 nuclearcraft_jj_reactor_trapdoor={hasPattern=true,label="Reaktorfalltür",recipe={nuclearcraft_jj_fission_block={need=6,tag=""}}},
 nuclearcraft_jj_record_end_of_the_world={hasPattern=true,label="Music Disc",recipe={minecraft_jj_record_13={need=1,tag=""},nuclearcraft_jj_ingot_jj_4={need=1,tag=""},nuclearcraft_jj_record_wanderer={need=1,tag=""},nuclearcraft_jj_uranium_jj_4={need=1,tag=""}}},
 nuclearcraft_jj_record_hyperspace={hasPattern=true,label="Music Disc",recipe={minecraft_jj_record_13={need=1,tag=""},nuclearcraft_jj_compound_jj_8={need=1,tag=""}}},
 nuclearcraft_jj_record_money_for_nothing={hasPattern=true,label="Schallplatte",recipe={minecraft_jj_record_13={need=1,tag=""},nuclearcraft_jj_alloy={need=1,tag=""},nuclearcraft_jj_ingot_jj_13={need=1,tag=""},nuclearcraft_jj_record_wanderer={need=1,tag=""}}},
 nuclearcraft_jj_record_wanderer={hasPattern=true,label="Schallplatte",recipe={minecraft_jj_record_13={need=1,tag=""},nuclearcraft_jj_alloy_jj_1={need=1,tag=""},nuclearcraft_jj_record_wanderer={need=1,tag=""}}},
 nuclearcraft_jj_roasted_cocoa_beans={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_rock_crusher_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_rock_crusher_idle={hasPattern=true,label="Gesteinsbrecher",recipe={nuclearcraft_jj_alloy_jj_1={need=1,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""},nuclearcraft_jj_part_jj_10={need=1,tag=""},nuclearcraft_jj_part_jj_8={need=1,tag=""},nuclearcraft_jj_part_jj_9={need=2,tag=""}}},
 nuclearcraft_jj_rtg_americium={hasPattern=true,label="Americium RTG",recipe={nuclearcraft_jj_americium={need=1,tag=""},nuclearcraft_jj_ingot_jj_8={need=4,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""}}},
 nuclearcraft_jj_rtg_californium={hasPattern=true,label="Californium RTG",recipe={nuclearcraft_jj_californium_jj_4={need=1,tag=""},nuclearcraft_jj_ingot_jj_8={need=4,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""}}},
 nuclearcraft_jj_rtg_plutonium={hasPattern=true,label="Plutonium RTG",recipe={nuclearcraft_jj_ingot_jj_8={need=4,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""},nuclearcraft_jj_plutonium={need=1,tag=""}}},
 nuclearcraft_jj_rtg_uranium={hasPattern=true,label="Uran RTG",recipe={nuclearcraft_jj_block_depleted_uranium={need=1,tag=""},nuclearcraft_jj_ingot_jj_8={need=4,tag=""},nuclearcraft_jj_part={need=4,tag=""}}},
 nuclearcraft_jj_salt_fission_beam={hasPattern=true,label="Flüssigsalzreaktorverstärkung",recipe={nuclearcraft_jj_salt_fission_wall={need=2,tag=""}}},
 nuclearcraft_jj_salt_fission_computer_port={hasPattern=true,label="Molten Salt Reactor Computer Port",recipe={nuclearcraft_jj_salt_fission_wall={need=1,tag=""},opencomputers_jj_cable_jj_11250603={need=2,tag=""},opencomputers_jj_material_jj_4={need=1,tag=""},opencomputers_jj_material_jj_7={need=1,tag=""}}},
 nuclearcraft_jj_salt_fission_controller={hasPattern=true,label="Flüssigsalz Spaltungsregeler",recipe={nuclearcraft_jj_alloy_jj_10={need=2,tag=""},nuclearcraft_jj_alloy_jj_2={need=2,tag=""},nuclearcraft_jj_part_jj_12={need=1,tag=""},nuclearcraft_jj_part_jj_3={need=4,tag=""}}},
 nuclearcraft_jj_salt_fission_distributor={hasPattern=true,label="Molten Salt Fuel Distributor",recipe={minecraft_jj_ender_eye={need=2,tag=""},nuclearcraft_jj_alloy_jj_10={need=2,tag=""},nuclearcraft_jj_part_jj_3={need=4,tag=""},nuclearcraft_jj_salt_fission_vent={need=1,tag=""}}},
 nuclearcraft_jj_salt_fission_frame={hasPattern=true,label="Flüssigsalzreaktorrahmen",recipe={nuclearcraft_jj_alloy_jj_5={need=4,tag=""},nuclearcraft_jj_salt_fission_wall={need=5,tag=""}}},
 nuclearcraft_jj_salt_fission_glass={hasPattern=true,label="Transparentes Flüssigsalzreaktorgehäuse",recipe={minecraft_jj_glass={need=1,tag=""},nuclearcraft_jj_salt_fission_wall={need=1,tag=""}}},
 nuclearcraft_jj_salt_fission_heater={hasPattern=true,label="Flüssigsalzkühlmittelerhitzer",recipe={nuclearcraft_jj_alloy_jj_10={need=1,tag=""},nuclearcraft_jj_alloy_jj_11={need=2,tag=""},nuclearcraft_jj_part_jj_12={need=1,tag=""},nuclearcraft_jj_part_jj_3={need=4,tag=""},nuclearcraft_jj_part_jj_7={need=1,tag=""}}},
 nuclearcraft_jj_salt_fission_moderator={hasPattern=true,label="Flüssigsalzreaktormoderatorgehäuse",recipe={nuclearcraft_jj_alloy_jj_5={need=4,tag=""},nuclearcraft_jj_ingot_block_jj_8={need=1,tag=""},nuclearcraft_jj_part_jj_3={need=4,tag=""}}},
 nuclearcraft_jj_salt_fission_redstone_port={hasPattern=true,label="Molten Salt Reactor Redstone Port",recipe={minecraft_jj_comparator={need=2,tag=""},minecraft_jj_repeater={need=2,tag=""},nuclearcraft_jj_alloy_jj_5={need=4,tag=""},nuclearcraft_jj_part_jj_12={need=1,tag=""}}},
 nuclearcraft_jj_salt_fission_retriever={hasPattern=true,label="Molten Salt Depleted Fuel Retriever",recipe={minecraft_jj_ender_eye={need=2,tag=""},nuclearcraft_jj_alloy_jj_1={need=2,tag=""},nuclearcraft_jj_part_jj_3={need=4,tag=""},nuclearcraft_jj_salt_fission_vent={need=1,tag=""}}},
 nuclearcraft_jj_salt_fission_vent={hasPattern=true,label="Flüssigsalzreaktorlüftungsschacht",recipe={nuclearcraft_jj_alloy_jj_1={need=2,tag=""},nuclearcraft_jj_alloy_jj_5={need=4,tag=""},nuclearcraft_jj_part_jj_12={need=1,tag=""},nuclearcraft_jj_part_jj_7={need=2,tag=""}}},
 nuclearcraft_jj_salt_fission_vessel={hasPattern=true,label="Flüssigsalzfissionsbehälter",recipe={nuclearcraft_jj_alloy_jj_1={need=1,tag=""},nuclearcraft_jj_alloy_jj_12={need=2,tag=""},nuclearcraft_jj_part_jj_12={need=1,tag=""},nuclearcraft_jj_part_jj_3={need=4,tag=""},nuclearcraft_jj_part_jj_7={need=1,tag=""}}},
 nuclearcraft_jj_salt_fission_wall={hasPattern=true,label="Flüssigsalzreaktorgehäuse",recipe={nuclearcraft_jj_alloy_jj_1={need=4,tag=""},nuclearcraft_jj_alloy_jj_5={need=4,tag=""},nuclearcraft_jj_part_jj_12={need=1,tag=""}}},
 nuclearcraft_jj_salt_mixer_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_salt_mixer_idle={hasPattern=true,label="Salzmixer",recipe={minecraft_jj_bucket={need=2,tag=""},minecraft_jj_glass={need=4,tag=""},nuclearcraft_jj_alloy_jj_5={need=1,tag=""},nuclearcraft_jj_manufactory_idle={need=1,tag=""},nuclearcraft_jj_part={need=4,tag=""},nuclearcraft_jj_part_jj_10={need=1,tag=""},nuclearcraft_jj_part_jj_8={need=1,tag=""}}},
 nuclearcraft_jj_shovel_boron={hasPattern=true,label="Borschaufel",recipe={minecraft_jj_stick={need=2,tag=""},nuclearcraft_jj_ingot_jj_5={need=1,tag=""}}},
 nuclearcraft_jj_shovel_boron_nitride={hasPattern=true,label="Bornitridschaufel",recipe={minecraft_jj_stick={need=2,tag=""},nuclearcraft_jj_gem_jj_1={need=1,tag=""}}},
 nuclearcraft_jj_shovel_hard_carbon={hasPattern=true,label="Harte Kohlenstoffschaufel",recipe={minecraft_jj_stick={need=2,tag=""},nuclearcraft_jj_alloy_jj_2={need=1,tag=""}}},
 nuclearcraft_jj_shovel_tough={hasPattern=true,label="Harte Legierungsschaufel",recipe={minecraft_jj_stick={need=2,tag=""},nuclearcraft_jj_alloy_jj_1={need=1,tag=""}}},
 nuclearcraft_jj_smore={hasPattern=true,label="S'more S'mingot",recipe={nuclearcraft_jj_graham_cracker={need=2,tag=""},nuclearcraft_jj_marshmallow={need=1,tag=""},nuclearcraft_jj_milk_chocolate={need=1,tag=""}}},
 nuclearcraft_jj_solar_panel_advanced={hasPattern=true,label="Fortgeschrittenes Solarpanel",recipe={nuclearcraft_jj_dust_jj_8={need=1,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""},nuclearcraft_jj_part_jj_4={need=1,tag=""},nuclearcraft_jj_solar_panel_basic={need=3,tag=""}}},
 nuclearcraft_jj_solar_panel_basic={hasPattern=true,label="Einfaches Solarpanel",recipe={minecraft_jj_dye_jj_4={need=1,tag=""},minecraft_jj_heavy_weighted_pressure_plate={need=3,tag=""},nuclearcraft_jj_dust_jj_8={need=2,tag=""},nuclearcraft_jj_gem_dust_jj_2={need=1,tag=""},nuclearcraft_jj_part_jj_4={need=2,tag=""}}},
 nuclearcraft_jj_solar_panel_du={hasPattern=true,label="DU Solarpanel",recipe={nuclearcraft_jj_dust_jj_8={need=1,tag=""},nuclearcraft_jj_part_jj_2={need=4,tag=""},nuclearcraft_jj_part_jj_5={need=1,tag=""},nuclearcraft_jj_solar_panel_advanced={need=3,tag=""}}},
 nuclearcraft_jj_solar_panel_elite={hasPattern=true,label="Elite Solarpanel",recipe={nuclearcraft_jj_gem_jj_5={need=1,tag=""},nuclearcraft_jj_part_jj_3={need=4,tag=""},nuclearcraft_jj_part_jj_5={need=1,tag=""},nuclearcraft_jj_solar_panel_du={need=3,tag=""}}},
 nuclearcraft_jj_spaxelhoe_boron={hasPattern=true,label="Borspatelhacke",recipe={minecraft_jj_iron_ingot={need=2,tag=""},nuclearcraft_jj_axe_boron={need=1,tag=""},nuclearcraft_jj_hoe_boron={need=1,tag=""},nuclearcraft_jj_pickaxe_boron={need=1,tag=""},nuclearcraft_jj_shovel_boron={need=1,tag=""},nuclearcraft_jj_sword_boron={need=1,tag=""}}},
 nuclearcraft_jj_spaxelhoe_boron_nitride={hasPattern=true,label="Bornitridspatelhacke",recipe={minecraft_jj_iron_ingot={need=2,tag=""},nuclearcraft_jj_axe_boron_nitride={need=1,tag=""},nuclearcraft_jj_hoe_boron_nitride={need=1,tag=""},nuclearcraft_jj_pickaxe_boron_nitride={need=1,tag=""},nuclearcraft_jj_shovel_boron_nitride={need=1,tag=""},nuclearcraft_jj_sword_boron_nitride={need=1,tag=""}}},
 nuclearcraft_jj_spaxelhoe_hard_carbon={hasPattern=true,label="Harte Kohlenstoffspatelhacke",recipe={minecraft_jj_iron_ingot={need=2,tag=""},nuclearcraft_jj_axe_hard_carbon={need=1,tag=""},nuclearcraft_jj_hoe_hard_carbon={need=1,tag=""},nuclearcraft_jj_pickaxe_hard_carbon={need=1,tag=""},nuclearcraft_jj_shovel_hard_carbon={need=1,tag=""},nuclearcraft_jj_sword_hard_carbon={need=1,tag=""}}},
 nuclearcraft_jj_spaxelhoe_tough={hasPattern=true,label="Harte Legierungsspatelhacke",recipe={minecraft_jj_iron_ingot={need=2,tag=""},nuclearcraft_jj_axe_tough={need=1,tag=""},nuclearcraft_jj_hoe_tough={need=1,tag=""},nuclearcraft_jj_pickaxe_tough={need=1,tag=""},nuclearcraft_jj_shovel_tough={need=1,tag=""},nuclearcraft_jj_sword_tough={need=1,tag=""}}},
 nuclearcraft_jj_supercooler_active={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_supercooler_idle={hasPattern=true,label="Superkühler",recipe={minecraft_jj_glowstone_dust={need=4,tag=""},nuclearcraft_jj_alloy_jj_2={need=2,tag=""},nuclearcraft_jj_alloy_jj_3={need=1,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""},nuclearcraft_jj_part_jj_10={need=1,tag=""},nuclearcraft_jj_part_jj_7={need=1,tag=""},nuclearcraft_jj_salt_mixer_idle={need=1,tag=""}}},
 nuclearcraft_jj_sword_boron={hasPattern=true,label="Borschwert",recipe={minecraft_jj_stick={need=1,tag=""},nuclearcraft_jj_ingot_jj_5={need=2,tag=""}}},
 nuclearcraft_jj_sword_boron_nitride={hasPattern=true,label="Bornitridschwert",recipe={minecraft_jj_stick={need=1,tag=""},nuclearcraft_jj_gem_jj_1={need=2,tag=""}}},
 nuclearcraft_jj_sword_hard_carbon={hasPattern=true,label="Hartes Kohlenstoffschwert",recipe={minecraft_jj_stick={need=1,tag=""},nuclearcraft_jj_alloy_jj_2={need=2,tag=""}}},
 nuclearcraft_jj_sword_tough={hasPattern=true,label="Harte Legierungsschwert",recipe={minecraft_jj_stick={need=1,tag=""},nuclearcraft_jj_alloy_jj_1={need=2,tag=""}}},
 nuclearcraft_jj_thorium={hasPattern=false,label="",recipe={ore_jj_nuggetThorium230={need=9,tag=""}}},
 nuclearcraft_jj_thorium_jj_1={hasPattern=false,label="",recipe={ore_jj_nuggetThorium230Oxide={need=9,tag=""}}},
 nuclearcraft_jj_thorium_jj_2={hasPattern=false,label="",recipe={ore_jj_ingotThorium230Base={need=1,tag=""}}},
 nuclearcraft_jj_thorium_jj_3={hasPattern=false,label="",recipe={ore_jj_ingotThorium230Oxide={need=1,tag=""}}},
 nuclearcraft_jj_thorium_jj_4={hasPattern=false,label="",recipe={ore_jj_nuggetThorium232={need=9,tag=""}}},
 nuclearcraft_jj_thorium_jj_5={hasPattern=false,label="",recipe={ore_jj_nuggetThorium232Oxide={need=9,tag=""}}},
 nuclearcraft_jj_thorium_jj_6={hasPattern=false,label="",recipe={ore_jj_ingotThorium232Base={need=1,tag=""}}},
 nuclearcraft_jj_thorium_jj_7={hasPattern=false,label="",recipe={nuclearcraft_jj_thorium_jj_5={need=1,tag=""}}},
 nuclearcraft_jj_tiny_dust_lead={hasPattern=false,label="",recipe={ore_jj_dustLead={need=1,tag=""}}},
 nuclearcraft_jj_turbine_computer_port={hasPattern=true,label="Turbine Computer Port",recipe={nuclearcraft_jj_turbine_wall={need=1,tag=""},opencomputers_jj_cable_jj_11250603={need=2,tag=""},opencomputers_jj_material_jj_4={need=1,tag=""},opencomputers_jj_material_jj_7={need=1,tag=""}}},
 nuclearcraft_jj_turbine_controller={hasPattern=true,label="Turbine Controller",recipe={nuclearcraft_jj_alloy_jj_15={need=4,tag=""},nuclearcraft_jj_part_jj_1={need=4,tag=""},nuclearcraft_jj_part_jj_12={need=1,tag=""}}},
 nuclearcraft_jj_turbine_dynamo_coil={hasPattern=true,label="Magnesium Turbine Dynamo Coil",recipe={nuclearcraft_jj_alloy_jj_1={need=1,tag=""},nuclearcraft_jj_alloy_jj_15={need=2,tag=""},nuclearcraft_jj_ingot_jj_7={need=6,tag=""}}},
 nuclearcraft_jj_turbine_dynamo_coil_jj_1={hasPattern=true,label="Beryllium Turbine Dynamo Coil",recipe={nuclearcraft_jj_alloy_jj_1={need=1,tag=""},nuclearcraft_jj_alloy_jj_15={need=2,tag=""},nuclearcraft_jj_ingot_jj_9={need=6,tag=""}}},
 nuclearcraft_jj_turbine_dynamo_coil_jj_2={hasPattern=true,label="Aluminum Turbine Dynamo Coil",recipe={nuclearcraft_jj_alloy_jj_1={need=1,tag=""},nuclearcraft_jj_alloy_jj_15={need=2,tag=""},nuclearcraft_jj_ingot_jj_12={need=6,tag=""}}},
 nuclearcraft_jj_turbine_dynamo_coil_jj_3={hasPattern=true,label="Gold Turbine Dynamo Coil",recipe={minecraft_jj_gold_ingot={need=6,tag=""},nuclearcraft_jj_alloy_jj_1={need=1,tag=""},nuclearcraft_jj_alloy_jj_15={need=2,tag=""}}},
 nuclearcraft_jj_turbine_dynamo_coil_jj_4={hasPattern=true,label="Copper Turbine Dynamo Coil",recipe={nuclearcraft_jj_alloy_jj_1={need=1,tag=""},nuclearcraft_jj_alloy_jj_15={need=2,tag=""},nuclearcraft_jj_ingot={need=6,tag=""}}},
 nuclearcraft_jj_turbine_dynamo_coil_jj_5={hasPattern=true,label="Silver Turbine Dynamo Coil",recipe={nuclearcraft_jj_alloy_jj_1={need=1,tag=""},nuclearcraft_jj_alloy_jj_15={need=2,tag=""},nuclearcraft_jj_ingot_jj_13={need=6,tag=""}}},
 nuclearcraft_jj_turbine_frame={hasPattern=true,label="Turbine Frame",recipe={nuclearcraft_jj_alloy_jj_15={need=4,tag=""},nuclearcraft_jj_turbine_wall={need=5,tag=""}}},
 nuclearcraft_jj_turbine_glass={hasPattern=true,label="Transparent Turbine Wall",recipe={minecraft_jj_glass={need=1,tag=""},nuclearcraft_jj_turbine_wall={need=1,tag=""}}},
 nuclearcraft_jj_turbine_inlet={hasPattern=true,label="Turbine Fluid Inlet",recipe={nuclearcraft_jj_alloy_jj_1={need=2,tag=""},nuclearcraft_jj_alloy_jj_15={need=5,tag=""},nuclearcraft_jj_part_jj_12={need=1,tag=""},nuclearcraft_jj_part_jj_7={need=1,tag=""}}},
 nuclearcraft_jj_turbine_outlet={hasPattern=true,label="Turbine Fluid Outlet",recipe={nuclearcraft_jj_alloy_jj_15={need=6,tag=""},nuclearcraft_jj_part_jj_12={need=1,tag=""},nuclearcraft_jj_part_jj_7={need=2,tag=""}}},
 nuclearcraft_jj_turbine_rotor_bearing={hasPattern=true,label="Turbine Rotor Bearing",recipe={minecraft_jj_gold_nugget={need=4,tag=""},nuclearcraft_jj_alloy_jj_15={need=4,tag=""},nuclearcraft_jj_part_jj_12={need=1,tag=""}}},
 nuclearcraft_jj_turbine_rotor_blade_extreme={hasPattern=true,label="Extreme Alloy Turbine Rotor Blade",recipe={nuclearcraft_jj_alloy_jj_10={need=6,tag=""},nuclearcraft_jj_alloy_jj_15={need=3,tag=""}}},
 nuclearcraft_jj_turbine_rotor_blade_sic_sic_cmc={hasPattern=true,label="SiC-SiC CMC Turbine Rotor Blade",recipe={nuclearcraft_jj_alloy_jj_14={need=6,tag=""},nuclearcraft_jj_alloy_jj_15={need=3,tag=""}}},
 nuclearcraft_jj_turbine_rotor_blade_steel={hasPattern=true,label="Steel Turbine Rotor Blade",recipe={nuclearcraft_jj_alloy_jj_15={need=3,tag=""},nuclearcraft_jj_alloy_jj_5={need=6,tag=""}}},
 nuclearcraft_jj_turbine_rotor_shaft={hasPattern=true,label="Turbine Rotor Shaft",recipe={nuclearcraft_jj_alloy_jj_1={need=3,tag=""},nuclearcraft_jj_alloy_jj_15={need=6,tag=""}}},
 nuclearcraft_jj_turbine_rotor_stator={hasPattern=true,label="Turbine Rotor Stator",recipe={nuclearcraft_jj_alloy_jj_15={need=6,tag=""}}},
 nuclearcraft_jj_turbine_wall={hasPattern=true,label="Turbine Wall",recipe={nuclearcraft_jj_alloy_jj_15={need=8,tag=""},nuclearcraft_jj_part_jj_12={need=1,tag=""}}},
 nuclearcraft_jj_unsweetened_chocolate={hasPattern=false,label="",recipe={}},
 nuclearcraft_jj_upgrade={hasPattern=true,label="Geschwindigkeitsupgrade",recipe={minecraft_jj_dye_jj_4={need=4,tag=""},minecraft_jj_heavy_weighted_pressure_plate={need=1,tag=""},minecraft_jj_redstone={need=4,tag=""}}},
 nuclearcraft_jj_upgrade_jj_1={hasPattern=true,label="Energy Upgrade",recipe={minecraft_jj_light_weighted_pressure_plate={need=1,tag=""},nuclearcraft_jj_gem_dust_jj_2={need=4,tag=""},nuclearcraft_jj_gem_dust_jj_3={need=4,tag=""}}},
 nuclearcraft_jj_uranium={hasPattern=false,label="",recipe={ore_jj_nuggetUranium233={need=9,tag=""}}},
 nuclearcraft_jj_uranium_jj_1={hasPattern=false,label="",recipe={ore_jj_nuggetUranium233Oxide={need=9,tag=""}}},
 nuclearcraft_jj_uranium_jj_10={hasPattern=false,label="",recipe={ore_jj_ingotUranium238Base={need=1,tag=""}}},
 nuclearcraft_jj_uranium_jj_11={hasPattern=false,label="",recipe={ore_jj_ingotUranium238Oxide={need=1,tag=""}}},
 nuclearcraft_jj_uranium_jj_2={hasPattern=false,label="",recipe={ore_jj_ingotUranium233Base={need=1,tag=""}}},
 nuclearcraft_jj_uranium_jj_3={hasPattern=false,label="",recipe={nuclearcraft_jj_uranium_jj_1={need=1,tag=""}}},
 nuclearcraft_jj_uranium_jj_4={hasPattern=false,label="",recipe={ore_jj_nuggetUranium235={need=9,tag=""}}},
 nuclearcraft_jj_uranium_jj_5={hasPattern=false,label="",recipe={ore_jj_nuggetUranium235Oxide={need=9,tag=""}}},
 nuclearcraft_jj_uranium_jj_6={hasPattern=false,label="",recipe={ore_jj_ingotUranium235Base={need=1,tag=""}}},
 nuclearcraft_jj_uranium_jj_7={hasPattern=false,label="",recipe={nuclearcraft_jj_uranium_jj_5={need=1,tag=""}}},
 nuclearcraft_jj_uranium_jj_8={hasPattern=false,label="",recipe={nuclearcraft_jj_block_depleted_uranium={need=1,tag=""}}},
 nuclearcraft_jj_uranium_jj_9={hasPattern=false,label="",recipe={ore_jj_nuggetUranium238Oxide={need=9,tag=""}}},
 nuclearcraft_jj_voltaic_pile_basic={hasPattern=true,label="Einfache voltaische Säule",recipe={nuclearcraft_jj_ingot_block_jj_7={need=1,tag=""},nuclearcraft_jj_part={need=4,tag=""},nuclearcraft_jj_part_jj_4={need=4,tag=""}}},
 nuclearcraft_jj_water_source={hasPattern=true,label="Unendliche Wasserquelle",recipe={ic2_jj_ingot_jj_6={need=2,tag=""},minecraft_jj_water_bucket={need=2,tag=""},nuclearcraft_jj_ingot_jj_1={need=2,tag=""},nuclearcraft_jj_part={need=4,tag=""}}},
 nuclearcraft_jj_water_source_compact={hasPattern=true,label="Kompakte unendliche Wasserquelle",recipe={ic2_jj_ingot_jj_1={need=1,tag=""},nuclearcraft_jj_alloy={need=1,tag=""},nuclearcraft_jj_water_source={need=8,tag=""}}},
 nuclearcraft_jj_water_source_dense={hasPattern=true,label="Dichte unendliche Wasserquelle",recipe={minecraft_jj_gold_ingot={need=1,tag=""},nuclearcraft_jj_water_source_compact={need=8,tag=""}}}
 }