return {
 aether_legacy_jj_aechor_petal={hasPattern=false,label="",tag={}},
 aether_legacy_jj_aercloud={hasPattern=false,label="",tag={}},
 aether_legacy_jj_aercloud_jj_1={hasPattern=false,label="",tag={}},
 aether_legacy_jj_aercloud_jj_2={hasPattern=false,label="",tag={}},
 aether_legacy_jj_aercloud_jj_3={hasPattern=false,label="",tag={}},
 aether_legacy_jj_aerogel={hasPattern=false,label="",tag={}},
 aether_legacy_jj_aerogel_double_slab={hasPattern=false,label="",tag={}},
 aether_legacy_jj_aerogel_slab={hasPattern=true,label="Unknown Block",tag={}},
 aether_legacy_jj_aerogel_stairs={hasPattern=true,label="Luftgel Treppe",tag={}},
 aether_legacy_jj_aerogel_wall={hasPattern=true,label="Luftgel Wand",tag={}},
 aether_legacy_jj_aether_dirt={hasPattern=false,label="",tag={}},
 aether_legacy_jj_aether_grass={hasPattern=false,label="",tag={}},
 aether_legacy_jj_aether_leaves={hasPattern=false,label="",tag={}},
 aether_legacy_jj_aether_leaves_jj_1={hasPattern=false,label="",tag={}},
 aether_legacy_jj_aether_lever={hasPattern=false,label="",tag={}},
 aether_legacy_jj_aether_log={hasPattern=false,label="",tag={}},
 aether_legacy_jj_aether_log_jj_1={hasPattern=false,label="",tag={}},
 aether_legacy_jj_aether_portal={hasPattern=false,label="",tag={}},
 aether_legacy_jj_aether_tune={hasPattern=false,label="",tag={}},
 aether_legacy_jj_aetherion_chest={hasPattern=false,label="",tag={}},
 aether_legacy_jj_aetherium_core={hasPattern=false,label="",tag={}},
 aether_legacy_jj_agility_cape={hasPattern=false,label="",tag={}},
 aether_legacy_jj_ambrosium_block={hasPattern=false,label="",tag={}},
 aether_legacy_jj_ambrosium_ore={hasPattern=false,label="",tag={}},
 aether_legacy_jj_ambrosium_shard={hasPattern=false,label="",tag={}},
 aether_legacy_jj_ambrosium_torch={hasPattern=true,label="Ambrosium Fackel",tag={}},
 aether_legacy_jj_angelic_double_slab={hasPattern=false,label="",tag={}},
 aether_legacy_jj_angelic_slab={hasPattern=true,label="Unknown Block",tag={}},
 aether_legacy_jj_angelic_stairs={hasPattern=true,label="Angelic Treppe",tag={}},
 aether_legacy_jj_angelic_wall={hasPattern=true,label="Angelic Mauer",tag={}},
 aether_legacy_jj_ascending_dawn={hasPattern=false,label="",tag={}},
 aether_legacy_jj_berry_bush={hasPattern=false,label="",tag={}},
 aether_legacy_jj_berry_bush_stem={hasPattern=false,label="",tag={}},
 aether_legacy_jj_blue_berry={hasPattern=false,label="",tag={}},
 aether_legacy_jj_blue_cape={hasPattern=true,label="Blauer Umhang",tag={}},
 aether_legacy_jj_burnt_cockatrice={hasPattern=false,label="",tag={}},
 aether_legacy_jj_candy_cane={hasPattern=false,label="",tag={}},
 aether_legacy_jj_candy_cane_sword={hasPattern=false,label="",tag={}},
 aether_legacy_jj_carved_double_slab={hasPattern=false,label="",tag={}},
 aether_legacy_jj_carved_slab={hasPattern=true,label="Unknown Block",tag={}},
 aether_legacy_jj_carved_stairs={hasPattern=true,label="Geschnitzte Treppe",tag={}},
 aether_legacy_jj_carved_wall={hasPattern=true,label="Geschnitze Mauer",tag={}},
 aether_legacy_jj_chain_gloves={hasPattern=false,label="",tag={}},
 aether_legacy_jj_chest_mimic={hasPattern=false,label="",tag={}},
 aether_legacy_jj_cloud_staff={hasPattern=false,label="",tag={}},
 aether_legacy_jj_cockatrice={hasPattern=false,label="",tag={}},
 aether_legacy_jj_cold_parachute={hasPattern=true,label="Kalter Fallschirm",tag={}},
 aether_legacy_jj_cooked_enchanted_cockatrice={hasPattern=false,label="",tag={}},
 aether_legacy_jj_crystal_leaves={hasPattern=false,label="",tag={}},
 aether_legacy_jj_crystal_leaves_jj_1={hasPattern=false,label="",tag={}},
 aether_legacy_jj_dart={hasPattern=true,label="Goldener Pfeil",tag={}},
 aether_legacy_jj_dart_jj_1={hasPattern=true,label="Giftiger Pfeil",tag={}},
 aether_legacy_jj_dart_jj_2={hasPattern=false,label="",tag={}},
 aether_legacy_jj_dart_shooter={hasPattern=false,label="",tag={}},
 aether_legacy_jj_dart_shooter_jj_1={hasPattern=false,label="",tag={}},
 aether_legacy_jj_dart_shooter_jj_2={hasPattern=false,label="",tag={}},
 aether_legacy_jj_developer_stick={hasPattern=false,label="",tag={}},
 aether_legacy_jj_diamond_gloves={hasPattern=true,label="Diamand Handschuhe",tag={}},
 aether_legacy_jj_dungeon_block={hasPattern=false,label="",tag={}},
 aether_legacy_jj_dungeon_block_jj_1={hasPattern=false,label="",tag={}},
 aether_legacy_jj_dungeon_block_jj_2={hasPattern=false,label="",tag={}},
 aether_legacy_jj_dungeon_block_jj_3={hasPattern=false,label="",tag={}},
 aether_legacy_jj_dungeon_block_jj_4={hasPattern=false,label="",tag={}},
 aether_legacy_jj_dungeon_block_jj_5={hasPattern=false,label="",tag={}},
 aether_legacy_jj_dungeon_key={hasPattern=false,label="",tag={}},
 aether_legacy_jj_dungeon_trap={hasPattern=false,label="",tag={}},
 aether_legacy_jj_enchanted_aether_grass={hasPattern=false,label="",tag={}},
 aether_legacy_jj_enchanted_blueberry={hasPattern=false,label="",tag={}},
 aether_legacy_jj_enchanted_cockatrice={hasPattern=false,label="",tag={}},
 aether_legacy_jj_enchanted_gravitite={hasPattern=false,label="",tag={}},
 aether_legacy_jj_enchanter={hasPattern=true,label="Altar",tag={}},
 aether_legacy_jj_flaming_sword={hasPattern=false,label="",tag={}},
 aether_legacy_jj_freezer={hasPattern=true,label="Freezer",tag={}},
 aether_legacy_jj_ginger_bread_man={hasPattern=false,label="",tag={}},
 aether_legacy_jj_golden_amber={hasPattern=false,label="",tag={}},
 aether_legacy_jj_golden_feather={hasPattern=false,label="",tag={}},
 aether_legacy_jj_golden_gloves={hasPattern=true,label="Goldene Handschuhe",tag={}},
 aether_legacy_jj_golden_oak_sapling={hasPattern=false,label="",tag={}},
 aether_legacy_jj_golden_parachute={hasPattern=true,label="Goldener Fallschirm",tag={}},
 aether_legacy_jj_golden_pendant={hasPattern=true,label="Goldener Anhänger",tag={}},
 aether_legacy_jj_golden_ring={hasPattern=true,label="Gold Ring",tag={}},
 aether_legacy_jj_gravitite_axe={hasPattern=true,label="Gravitite Axt",tag={}},
 aether_legacy_jj_gravitite_boots={hasPattern=true,label="Gravitite Schuhe",tag={}},
 aether_legacy_jj_gravitite_chestplate={hasPattern=true,label="Gravtiite Brustplatte",tag={}},
 aether_legacy_jj_gravitite_gloves={hasPattern=true,label="Gravitite Handschuhe",tag={}},
 aether_legacy_jj_gravitite_helmet={hasPattern=true,label="Gravitite Helm",tag={}},
 aether_legacy_jj_gravitite_leggings={hasPattern=true,label="Gravitite Hose",tag={}},
 aether_legacy_jj_gravitite_ore={hasPattern=false,label="",tag={}},
 aether_legacy_jj_gravitite_pickaxe={hasPattern=true,label="Gravitite Spitzhacke",tag={}},
 aether_legacy_jj_gravitite_shovel={hasPattern=true,label="Gravitite Schaufel",tag={}},
 aether_legacy_jj_gravitite_sword={hasPattern=true,label="Gravitite Schwert",tag={}},
 aether_legacy_jj_gummy_swet={hasPattern=false,label="",tag={}},
 aether_legacy_jj_healing_stone={hasPattern=false,label="",tag={}},
 aether_legacy_jj_hellfire_double_slab={hasPattern=false,label="",tag={}},
 aether_legacy_jj_hellfire_slab={hasPattern=true,label="Unknown Block",tag={}},
 aether_legacy_jj_hellfire_stairs={hasPattern=true,label="Höllenfeuer Treppe",tag={}},
 aether_legacy_jj_hellfire_wall={hasPattern=true,label="Höllenfeuer Mauer",tag={}},
 aether_legacy_jj_holiday_leaves={hasPattern=false,label="",tag={}},
 aether_legacy_jj_holiday_leaves_jj_1={hasPattern=false,label="",tag={}},
 aether_legacy_jj_holy_sword={hasPattern=false,label="",tag={}},
 aether_legacy_jj_holystone={hasPattern=false,label="",tag={}},
 aether_legacy_jj_holystone_axe={hasPattern=true,label="Heiligstein Axt",tag={}},
 aether_legacy_jj_holystone_brick={hasPattern=true,label="Heiligstein Ziegel",tag={}},
 aether_legacy_jj_holystone_brick_double_slab={hasPattern=false,label="",tag={}},
 aether_legacy_jj_holystone_brick_slab={hasPattern=true,label="Unknown Block",tag={}},
 aether_legacy_jj_holystone_brick_stairs={hasPattern=true,label="Heiligstein Ziegel Treppe",tag={}},
 aether_legacy_jj_holystone_brick_wall={hasPattern=true,label="Heiligstein Ziegel Wand",tag={}},
 aether_legacy_jj_holystone_button={hasPattern=false,label="",tag={}},
 aether_legacy_jj_holystone_double_slab={hasPattern=false,label="",tag={}},
 aether_legacy_jj_holystone_pickaxe={hasPattern=true,label="Heiligstein Spitzhacke",tag={}},
 aether_legacy_jj_holystone_pressure_plate={hasPattern=false,label="",tag={}},
 aether_legacy_jj_holystone_shovel={hasPattern=true,label="Heiligstein Schaufel",tag={}},
 aether_legacy_jj_holystone_slab={hasPattern=false,label="",tag={}},
 aether_legacy_jj_holystone_stairs={hasPattern=false,label="",tag={}},
 aether_legacy_jj_holystone_sword={hasPattern=true,label="Heiligstein Schwert",tag={}},
 aether_legacy_jj_holystone_wall={hasPattern=false,label="",tag={}},
 aether_legacy_jj_ice_pendant={hasPattern=false,label="",tag={}},
 aether_legacy_jj_ice_ring={hasPattern=false,label="",tag={}},
 aether_legacy_jj_icestone={hasPattern=false,label="",tag={}},
 aether_legacy_jj_incubator={hasPattern=true,label="Inkubator",tag={}},
 aether_legacy_jj_invisibility_cape={hasPattern=false,label="",tag={}},
 aether_legacy_jj_iron_bubble={hasPattern=false,label="",tag={}},
 aether_legacy_jj_iron_gloves={hasPattern=true,label="Eisen Handschuhe",tag={}},
 aether_legacy_jj_iron_pendant={hasPattern=true,label="Eisen Anhänger",tag={}},
 aether_legacy_jj_iron_ring={hasPattern=true,label="Eisen Ring",tag={}},
 aether_legacy_jj_leather_gloves={hasPattern=true,label="Leder Handschuhe",tag={}},
 aether_legacy_jj_legacy={hasPattern=false,label="",tag={}},
 aether_legacy_jj_life_shard={hasPattern=false,label="",tag={}},
 aether_legacy_jj_lightning_knife={hasPattern=false,label="",tag={}},
 aether_legacy_jj_lightning_sword={hasPattern=false,label="",tag={}},
 aether_legacy_jj_locked_dungeon_block={hasPattern=false,label="",tag={}},
 aether_legacy_jj_lore_book={hasPattern=true,label="Buch der Überlieferung",tag={}},
 aether_legacy_jj_moa_egg={hasPattern=false,label="",tag={typeId=0}},
 aether_legacy_jj_moa_egg_b_1={hasPattern=false,label="",tag={typeId=1}},
 aether_legacy_jj_moa_egg_b_2={hasPattern=false,label="",tag={typeId=2}},
 aether_legacy_jj_moa_egg_b_3={hasPattern=false,label="",tag={typeId=3}},
 aether_legacy_jj_moa_egg_b_4={hasPattern=false,label="",tag={typeId=4}},
 aether_legacy_jj_mossy_holystone={hasPattern=false,label="",tag={}},
 aether_legacy_jj_mossy_holystone_double_slab={hasPattern=false,label="",tag={}},
 aether_legacy_jj_mossy_holystone_slab={hasPattern=false,label="",tag={}},
 aether_legacy_jj_mossy_holystone_stairs={hasPattern=false,label="",tag={}},
 aether_legacy_jj_mossy_holystone_wall={hasPattern=false,label="",tag={}},
 aether_legacy_jj_nature_staff={hasPattern=true,label="Naturstab",tag={}},
 aether_legacy_jj_neptune_boots={hasPattern=false,label="",tag={}},
 aether_legacy_jj_neptune_chestplate={hasPattern=false,label="",tag={}},
 aether_legacy_jj_neptune_gloves={hasPattern=false,label="",tag={}},
 aether_legacy_jj_neptune_helmet={hasPattern=false,label="",tag={}},
 aether_legacy_jj_neptune_leggings={hasPattern=false,label="",tag={}},
 aether_legacy_jj_notch_hammer={hasPattern=false,label="",tag={}},
 aether_legacy_jj_obsidian_boots={hasPattern=false,label="",tag={}},
 aether_legacy_jj_obsidian_chestplate={hasPattern=false,label="",tag={}},
 aether_legacy_jj_obsidian_gloves={hasPattern=false,label="",tag={}},
 aether_legacy_jj_obsidian_helmet={hasPattern=false,label="",tag={}},
 aether_legacy_jj_obsidian_leggings={hasPattern=false,label="",tag={}},
 aether_legacy_jj_phoenix_boots={hasPattern=false,label="",tag={}},
 aether_legacy_jj_phoenix_bow={hasPattern=false,label="",tag={}},
 aether_legacy_jj_phoenix_chestplate={hasPattern=false,label="",tag={}},
 aether_legacy_jj_phoenix_gloves={hasPattern=false,label="",tag={}},
 aether_legacy_jj_phoenix_helmet={hasPattern=false,label="",tag={}},
 aether_legacy_jj_phoenix_leggings={hasPattern=false,label="",tag={}},
 aether_legacy_jj_pig_slayer={hasPattern=false,label="",tag={}},
 aether_legacy_jj_pillar={hasPattern=false,label="",tag={}},
 aether_legacy_jj_pillar_top={hasPattern=false,label="",tag={}},
 aether_legacy_jj_present={hasPattern=false,label="",tag={}},
 aether_legacy_jj_purple_flower={hasPattern=false,label="",tag={}},
 aether_legacy_jj_quicksoil={hasPattern=false,label="",tag={}},
 aether_legacy_jj_quicksoil_glass={hasPattern=false,label="",tag={}},
 aether_legacy_jj_quicksoil_glass_pane={hasPattern=false,label="",tag={}},
 aether_legacy_jj_red_cape={hasPattern=true,label="Roter Umhang",tag={}},
 aether_legacy_jj_regeneration_stone={hasPattern=false,label="",tag={}},
 aether_legacy_jj_repulsion_shield={hasPattern=false,label="",tag={}},
 aether_legacy_jj_sentry_boots={hasPattern=false,label="",tag={}},
 aether_legacy_jj_skyroot_axe={hasPattern=true,label="Himmelswurzel Axt",tag={}},
 aether_legacy_jj_skyroot_bed={hasPattern=false,label="",tag={}},
 aether_legacy_jj_skyroot_bookshelf={hasPattern=false,label="",tag={}},
 aether_legacy_jj_skyroot_bucket={hasPattern=true,label="Himmelswurzel Eimer",tag={}},
 aether_legacy_jj_skyroot_bucket_jj_1={hasPattern=false,label="",tag={}},
 aether_legacy_jj_skyroot_bucket_jj_2={hasPattern=false,label="",tag={}},
 aether_legacy_jj_skyroot_bucket_jj_3={hasPattern=false,label="",tag={}},
 aether_legacy_jj_skyroot_bucket_jj_4={hasPattern=false,label="",tag={}},
 aether_legacy_jj_skyroot_button={hasPattern=false,label="",tag={}},
 aether_legacy_jj_skyroot_chest={hasPattern=false,label="",tag={}},
 aether_legacy_jj_skyroot_crafting_table={hasPattern=false,label="",tag={}},
 aether_legacy_jj_skyroot_door={hasPattern=false,label="",tag={}},
 aether_legacy_jj_skyroot_double_slab={hasPattern=false,label="",tag={}},
 aether_legacy_jj_skyroot_fence={hasPattern=true,label="Himmelswurzel Zaun",tag={}},
 aether_legacy_jj_skyroot_fence_gate={hasPattern=true,label="Himmelswurzel Zauntor",tag={}},
 aether_legacy_jj_skyroot_ladder={hasPattern=false,label="",tag={}},
 aether_legacy_jj_skyroot_pickaxe={hasPattern=true,label="Skyroot Pickaxe",tag={}},
 aether_legacy_jj_skyroot_plank={hasPattern=false,label="",tag={}},
 aether_legacy_jj_skyroot_pressure_plate={hasPattern=false,label="",tag={}},
 aether_legacy_jj_skyroot_sapling={hasPattern=false,label="",tag={}},
 aether_legacy_jj_skyroot_shovel={hasPattern=true,label="Himmelswurzel Schaufel",tag={}},
 aether_legacy_jj_skyroot_sign={hasPattern=false,label="",tag={}},
 aether_legacy_jj_skyroot_slab={hasPattern=true,label="Unknown Block",tag={}},
 aether_legacy_jj_skyroot_stairs={hasPattern=true,label="Himmelswurzel Treppe",tag={}},
 aether_legacy_jj_skyroot_stick={hasPattern=true,label="Himmelswurzel Stab",tag={}},
 aether_legacy_jj_skyroot_sword={hasPattern=true,label="Himmelswurzel Schwert",tag={}},
 aether_legacy_jj_skyroot_trapdoor={hasPattern=false,label="",tag={}},
 aether_legacy_jj_sun_altar={hasPattern=false,label="",tag={}},
 aether_legacy_jj_swet_cape={hasPattern=false,label="",tag={}},
 aether_legacy_jj_swetty_ball={hasPattern=false,label="",tag={}},
 aether_legacy_jj_treasure_chest={hasPattern=false,label="",tag={}},
 aether_legacy_jj_valkyrie_axe={hasPattern=false,label="",tag={}},
 aether_legacy_jj_valkyrie_boots={hasPattern=false,label="",tag={}},
 aether_legacy_jj_valkyrie_cape={hasPattern=false,label="",tag={}},
 aether_legacy_jj_valkyrie_chestplate={hasPattern=false,label="",tag={}},
 aether_legacy_jj_valkyrie_gloves={hasPattern=false,label="",tag={}},
 aether_legacy_jj_valkyrie_helmet={hasPattern=false,label="",tag={}},
 aether_legacy_jj_valkyrie_lance={hasPattern=false,label="",tag={}},
 aether_legacy_jj_valkyrie_leggings={hasPattern=false,label="",tag={}},
 aether_legacy_jj_valkyrie_pickaxe={hasPattern=false,label="",tag={}},
 aether_legacy_jj_valkyrie_shovel={hasPattern=false,label="",tag={}},
 aether_legacy_jj_vampire_blade={hasPattern=false,label="",tag={}},
 aether_legacy_jj_victory_medal={hasPattern=false,label="",tag={}},
 aether_legacy_jj_welcoming_skies={hasPattern=false,label="",tag={}},
 aether_legacy_jj_white_apple={hasPattern=false,label="",tag={}},
 aether_legacy_jj_white_cape={hasPattern=true,label="Wheißer Umhang",tag={}},
 aether_legacy_jj_white_flower={hasPattern=false,label="",tag={}},
 aether_legacy_jj_yellow_cape={hasPattern=true,label="Gelber Umhang",tag={}},
 aether_legacy_jj_zanite_axe={hasPattern=true,label="Zanite Axt",tag={}},
 aether_legacy_jj_zanite_bars={hasPattern=false,label="",tag={}},
 aether_legacy_jj_zanite_block={hasPattern=true,label="Zanite Block",tag={}},
 aether_legacy_jj_zanite_boots={hasPattern=true,label="Zanite Schuhe",tag={}},
 aether_legacy_jj_zanite_chestplate={hasPattern=true,label="Zanite Brustplatte",tag={}},
 aether_legacy_jj_zanite_door={hasPattern=false,label="",tag={}},
 aether_legacy_jj_zanite_gemstone={hasPattern=true,label="Zanite Edelstein",tag={}},
 aether_legacy_jj_zanite_gloves={hasPattern=true,label="Zanite Handschuhe",tag={}},
 aether_legacy_jj_zanite_helmet={hasPattern=true,label="Zanite Helm",tag={}},
 aether_legacy_jj_zanite_leggings={hasPattern=true,label="Zanite Hose",tag={}},
 aether_legacy_jj_zanite_ore={hasPattern=false,label="",tag={}},
 aether_legacy_jj_zanite_pendant={hasPattern=true,label="Zanite Anhänger",tag={}},
 aether_legacy_jj_zanite_pickaxe={hasPattern=true,label="Zanite Spitzhacke",tag={}},
 aether_legacy_jj_zanite_pressure_plate={hasPattern=false,label="",tag={}},
 aether_legacy_jj_zanite_ring={hasPattern=true,label="Zanite Ring",tag={}},
 aether_legacy_jj_zanite_shovel={hasPattern=true,label="Zanite Schaufel",tag={}},
 aether_legacy_jj_zanite_sword={hasPattern=true,label="Zanite Schwert",tag={}},
 aether_legacy_jj_zanite_trapdoor={hasPattern=false,label="",tag={}},
 animania_jj_animania_manual={hasPattern=false,label="",tag={}},
 animania_jj_bacon_omelette={hasPattern=true,label="Omelette mit Speck",tag={}},
 animania_jj_bee_hive={hasPattern=false,label="",tag={}},
 animania_jj_block_hamster_wheel={hasPattern=true,label="Hamster Wheel",tag={}},
 animania_jj_block_mud={hasPattern=true,label="Schlamm",tag={}},
 animania_jj_block_nest={hasPattern=true,label="Nest",tag={}},
 animania_jj_block_straw={hasPattern=true,label="Straw",tag={}},
 animania_jj_block_trough={hasPattern=true,label="Trog",tag={}},
 animania_jj_blue_peacock_feather={hasPattern=false,label="",tag={}},
 animania_jj_brown_egg={hasPattern=false,label="",tag={}},
 animania_jj_carving_knife={hasPattern=true,label="Tranchiermesser",tag={}},
 animania_jj_charcoal_peacock_feather={hasPattern=false,label="",tag={}},
 animania_jj_cheese_mold={hasPattern=true,label="Cheese Mold",tag={}},
 animania_jj_cheese_omelette={hasPattern=true,label="Käseomelette",tag={}},
 animania_jj_chocolate_truffle={hasPattern=true,label="Schokoladentrüffel",tag={}},
 animania_jj_cooked_chevon={hasPattern=false,label="",tag={}},
 animania_jj_cooked_frog_legs={hasPattern=false,label="",tag={}},
 animania_jj_cooked_horse={hasPattern=false,label="",tag={}},
 animania_jj_cooked_peacock={hasPattern=false,label="",tag={}},
 animania_jj_cooked_prime_bacon={hasPattern=false,label="",tag={}},
 animania_jj_cooked_prime_beef={hasPattern=false,label="",tag={}},
 animania_jj_cooked_prime_chevon={hasPattern=false,label="",tag={}},
 animania_jj_cooked_prime_chicken={hasPattern=false,label="",tag={}},
 animania_jj_cooked_prime_mutton={hasPattern=false,label="",tag={}},
 animania_jj_cooked_prime_peacock={hasPattern=false,label="",tag={}},
 animania_jj_cooked_prime_pork={hasPattern=false,label="",tag={}},
 animania_jj_cooked_prime_rabbit={hasPattern=false,label="",tag={}},
 animania_jj_cooked_prime_steak={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_buck_alpine={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_buck_angora={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_buck_chinchilla={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_buck_cottontail={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_buck_dutch={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_buck_fainting={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_buck_havana={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_buck_jack={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_buck_kiko={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_buck_kinder={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_buck_lop={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_buck_new_zealand={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_buck_nigerian_dwarf={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_buck_pygmy={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_buck_rex={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_bull_angus={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_bull_friesian={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_bull_hereford={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_bull_highland={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_bull_holstein={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_bull_jersey={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_bull_longhorn={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_bull_mooshroom={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_calf_angus={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_calf_friesian={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_calf_hereford={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_calf_highland={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_calf_holstein={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_calf_jersey={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_calf_longhorn={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_calf_mooshroom={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_chick_leghorn={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_chick_orpington={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_chick_plymouth_rock={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_chick_rhode_island_red={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_chick_wyandotte={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_chicken_random={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_cow_angus={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_cow_friesian={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_cow_hereford={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_cow_highland={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_cow_holstein={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_cow_jersey={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_cow_longhorn={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_cow_mooshroom={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_cow_random={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_dart_frog={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_doe_alpine={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_doe_angora={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_doe_chinchilla={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_doe_cottontail={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_doe_dutch={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_doe_fainting={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_doe_havana={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_doe_jack={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_doe_kiko={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_doe_kinder={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_doe_lop={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_doe_new_zealand={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_doe_nigerian_dwarf={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_doe_pygmy={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_doe_rex={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_ewe_dorper={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_ewe_dorset={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_ewe_friesian={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_ewe_jacob={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_ewe_merino={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_ewe_suffolk={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_ferret_grey={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_ferret_white={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_foal_draft={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_frog={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_goat_random={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_hamster={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_hedgehog={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_hedgehog_albino={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_hen_leghorn={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_hen_orpington={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_hen_plymouth_rock={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_hen_rhode_island_red={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_hen_wyandotte={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_hog_duroc={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_hog_hampshire={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_hog_large_black={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_hog_large_white={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_hog_old_spot={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_hog_yorkshire={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_kid_alpine={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_kid_angora={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_kid_fainting={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_kid_kiko={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_kid_kinder={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_kid_nigerian_dwarf={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_kid_pygmy={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_kit_chinchilla={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_kit_cottontail={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_kit_dutch={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_kit_havana={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_kit_jack={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_kit_lop={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_kit_new_zealand={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_kit_rex={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_lamb_dorper={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_lamb_dorset={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_lamb_friesian={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_lamb_jacob={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_lamb_merino={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_lamb_suffolk={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_mare_draft={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_peachick_blue={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_peachick_charcoal={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_peachick_opal={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_peachick_peach={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_peachick_purple={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_peachick_taupe={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_peachick_white={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_peacock_blue={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_peacock_charcoal={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_peacock_opal={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_peacock_peach={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_peacock_purple={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_peacock_random={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_peacock_taupe={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_peacock_white={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_peahen_blue={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_peahen_charcoal={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_peahen_opal={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_peahen_peach={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_peahen_purple={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_peahen_taupe={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_peahen_white={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_pig_random={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_piglet_duroc={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_piglet_hampshire={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_piglet_large_black={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_piglet_large_white={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_piglet_old_spot={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_piglet_yorkshire={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_rabbit_random={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_ram_dorper={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_ram_dorset={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_ram_friesian={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_ram_jacob={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_ram_merino={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_ram_suffolk={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_random={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_rooster_leghorn={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_rooster_orpington={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_rooster_plymouth_rock={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_rooster_rhode_island_red={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_rooster_wyandotte={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_sheep_random={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_sow_duroc={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_sow_hampshire={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_sow_large_black={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_sow_large_white={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_sow_old_spot={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_sow_yorkshire={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_stallion_draft={hasPattern=false,label="",tag={}},
 animania_jj_entity_egg_toad={hasPattern=false,label="",tag={}},
 animania_jj_friesian_cheese_wedge={hasPattern=false,label="",tag={}},
 animania_jj_friesian_cheese_wheel={hasPattern=false,label="",tag={}},
 animania_jj_goat_cheese_wedge={hasPattern=false,label="",tag={}},
 animania_jj_goat_cheese_wheel={hasPattern=false,label="",tag={}},
 animania_jj_hamster_ball_clear={hasPattern=true,label="Clear Hamster Ball",tag={}},
 animania_jj_hamster_ball_colored={hasPattern=true,label="Black Hamster Ball",tag={}},
 animania_jj_hamster_food={hasPattern=true,label="Hamster Futter",tag={}},
 animania_jj_holstein_cheese_wedge={hasPattern=false,label="",tag={}},
 animania_jj_holstein_cheese_wheel={hasPattern=false,label="",tag={}},
 animania_jj_honey_bottle={hasPattern=false,label="",tag={Fluid={Amount=1000,FluidName="animania_honey"}}},
 animania_jj_item_cart={hasPattern=true,label="Horse Cart",tag={}},
 animania_jj_item_tiller={hasPattern=false,label="",tag={}},
 animania_jj_item_wagon={hasPattern=true,label="Covered Wagon",tag={}},
 animania_jj_jersey_cheese_wedge={hasPattern=false,label="",tag={}},
 animania_jj_jersey_cheese_wheel={hasPattern=false,label="",tag={}},
 animania_jj_milk_bottle={hasPattern=true,label="Bottle of Milk",tag={}},
 animania_jj_opal_peacock_feather={hasPattern=false,label="",tag={}},
 animania_jj_peach_peacock_feather={hasPattern=false,label="",tag={}},
 animania_jj_peacock_egg_blue={hasPattern=false,label="",tag={}},
 animania_jj_peacock_egg_white={hasPattern=false,label="",tag={}},
 animania_jj_plain_omelette={hasPattern=false,label="",tag={}},
 animania_jj_purple_peacock_feather={hasPattern=false,label="",tag={}},
 animania_jj_raw_chevon={hasPattern=false,label="",tag={}},
 animania_jj_raw_frog_legs={hasPattern=false,label="",tag={}},
 animania_jj_raw_horse={hasPattern=false,label="",tag={}},
 animania_jj_raw_peacock={hasPattern=false,label="",tag={}},
 animania_jj_raw_prime_bacon={hasPattern=false,label="",tag={}},
 animania_jj_raw_prime_beef={hasPattern=false,label="",tag={}},
 animania_jj_raw_prime_chevon={hasPattern=false,label="",tag={}},
 animania_jj_raw_prime_chicken={hasPattern=false,label="",tag={}},
 animania_jj_raw_prime_mutton={hasPattern=false,label="",tag={}},
 animania_jj_raw_prime_peacock={hasPattern=false,label="",tag={}},
 animania_jj_raw_prime_pork={hasPattern=false,label="",tag={}},
 animania_jj_raw_prime_rabbit={hasPattern=false,label="",tag={}},
 animania_jj_raw_prime_steak={hasPattern=false,label="",tag={}},
 animania_jj_riding_crop={hasPattern=true,label="Riding Crop",tag={}},
 animania_jj_salt={hasPattern=false,label="",tag={}},
 animania_jj_salt_lick={hasPattern=true,label="Salt Lick",tag={}},
 animania_jj_sheep_cheese_wedge={hasPattern=false,label="",tag={}},
 animania_jj_sheep_cheese_wheel={hasPattern=false,label="",tag={}},
 animania_jj_super_omelette={hasPattern=true,label="Superomelette",tag={}},
 animania_jj_taupe_peacock_feather={hasPattern=false,label="",tag={}},
 animania_jj_truffle={hasPattern=false,label="",tag={}},
 animania_jj_truffle_omelette={hasPattern=true,label="Trüffelomelette",tag={}},
 animania_jj_truffle_soup={hasPattern=true,label="Trüffelsuppe",tag={}},
 animania_jj_wheel={hasPattern=true,label="Wheel",tag={}},
 animania_jj_white_peacock_feather={hasPattern=false,label="",tag={}},
 animania_jj_wild_hive={hasPattern=false,label="",tag={}},
 animania_jj_wool={hasPattern=false,label="",tag={}},
 animania_jj_wool_jj_1={hasPattern=false,label="",tag={}},
 animania_jj_wool_jj_2={hasPattern=false,label="",tag={}},
 animania_jj_wool_jj_3={hasPattern=false,label="",tag={}},
 animania_jj_wool_jj_4={hasPattern=false,label="",tag={}},
 animania_jj_wool_jj_5={hasPattern=false,label="",tag={}},
 animania_jj_wool_jj_6={hasPattern=false,label="",tag={}},
 lost_aether_jj_agility_boots={hasPattern=false,label="",tag={}},
 lost_aether_jj_crystal_sapling={hasPattern=false,label="",tag={}},
 lost_aether_jj_gale_double_slab={hasPattern=false,label="",tag={}},
 lost_aether_jj_gale_slab={hasPattern=false,label="",tag={}},
 lost_aether_jj_gale_stairs={hasPattern=false,label="",tag={}},
 lost_aether_jj_gale_stone={hasPattern=false,label="",tag={}},
 lost_aether_jj_gale_wall={hasPattern=false,label="",tag={}},
 lost_aether_jj_gravitite_shield={hasPattern=false,label="",tag={}},
 lost_aether_jj_invisibility_gem={hasPattern=false,label="",tag={}},
 lost_aether_jj_jeb_shield={hasPattern=false,label="",tag={}},
 lost_aether_jj_light_gale_stone={hasPattern=false,label="",tag={}},
 lost_aether_jj_locked_gale_stone={hasPattern=false,label="",tag={}},
 lost_aether_jj_locked_light_gale_stone={hasPattern=false,label="",tag={}},
 lost_aether_jj_phoenix_axe={hasPattern=false,label="",tag={}},
 lost_aether_jj_phoenix_cape={hasPattern=false,label="",tag={}},
 lost_aether_jj_phoenix_pickaxe={hasPattern=false,label="",tag={}},
 lost_aether_jj_phoenix_shovel={hasPattern=false,label="",tag={}},
 lost_aether_jj_phoenix_sword={hasPattern=false,label="",tag={}},
 lost_aether_jj_platinum_key={hasPattern=false,label="",tag={}},
 lost_aether_jj_power_gloves={hasPattern=false,label="",tag={}},
 lost_aether_jj_sentry_shield={hasPattern=false,label="",tag={}},
 lost_aether_jj_songstone={hasPattern=false,label="",tag={}},
 lost_aether_jj_swetty_mask={hasPattern=false,label="",tag={}},
 lost_aether_jj_zanite_shield={hasPattern=false,label="",tag={}},
 minecolonies_jj_ancienttome={hasPattern=false,label="",tag={}},
 minecolonies_jj_barrel_block={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockbarrackstowersubstitution={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockconstructiontape={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutarchery={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutbaker={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutbarracks={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutbarrackstower={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutblacksmith={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutbuilder={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutchickenherder={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutcitizen={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutcombatacademy={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutcomposter={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutcook={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutcowboy={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutcrusher={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutdeliveryman={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutenchanter={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutfarmer={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutfield={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutfisherman={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutflorist={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutguardtower={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutlibrary={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutlumberjack={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutminer={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutsawmill={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutshepherd={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutsifter={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutsmeltery={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutstonemason={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutstonesmeltery={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutswineherder={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhuttownhall={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockhutwarehouse={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockinfoposter={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockminecoloniesrack={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockpostbox={hasPattern=false,label="",tag={}},
 minecolonies_jj_blockwaypoint={hasPattern=false,label="",tag={}},
 minecolonies_jj_caliper={hasPattern=false,label="",tag={}},
 minecolonies_jj_chiefsword={hasPattern=false,label="",tag={}},
 minecolonies_jj_clipboard={hasPattern=false,label="",tag={}},
 minecolonies_jj_compost={hasPattern=false,label="",tag={}},
 minecolonies_jj_composted_dirt={hasPattern=false,label="",tag={}},
 minecolonies_jj_decorationcontroller={hasPattern=false,label="",tag={}},
 minecolonies_jj_iron_scimitar={hasPattern=false,label="",tag={}},
 minecolonies_jj_pirate_boots={hasPattern=false,label="",tag={}},
 minecolonies_jj_pirate_cap={hasPattern=false,label="",tag={}},
 minecolonies_jj_pirate_chest={hasPattern=false,label="",tag={}},
 minecolonies_jj_pirate_hat={hasPattern=false,label="",tag={}},
 minecolonies_jj_pirate_leggins={hasPattern=false,label="",tag={}},
 minecolonies_jj_pirate_legs={hasPattern=false,label="",tag={}},
 minecolonies_jj_pirate_shoes={hasPattern=false,label="",tag={}},
 minecolonies_jj_pirate_top={hasPattern=false,label="",tag={}},
 minecolonies_jj_resourcescroll={hasPattern=false,label="",tag={}},
 minecolonies_jj_santa_hat={hasPattern=false,label="",tag={}},
 minecolonies_jj_scepterguard={hasPattern=false,label="",tag={}},
 minecolonies_jj_scepterlumberjack={hasPattern=false,label="",tag={}},
 minecolonies_jj_scepterpermission={hasPattern=false,label="",tag={}},
 minecolonies_jj_sizecity={hasPattern=false,label="",tag={}},
 minecolonies_jj_sizemetropolis={hasPattern=false,label="",tag={}},
 minecolonies_jj_sizesettlement={hasPattern=false,label="",tag={}},
 minecolonies_jj_sizetown={hasPattern=false,label="",tag={}},
 minecolonies_jj_supplycampdeployer={hasPattern=false,label="",tag={}},
 minecolonies_jj_supplychestdeployer={hasPattern=false,label="",tag={}},
 structurize_jj_blockcactusfence={hasPattern=false,label="",tag={}},
 structurize_jj_blockcactusfencegate={hasPattern=false,label="",tag={}},
 structurize_jj_blockcactusplank={hasPattern=false,label="",tag={}},
 structurize_jj_blockcactusslab_half={hasPattern=false,label="",tag={}},
 structurize_jj_blockcactusstair={hasPattern=false,label="",tag={}},
 structurize_jj_blockcactustrapdoor={hasPattern=false,label="",tag={}},
 structurize_jj_blockpaperwall={hasPattern=false,label="",tag={}},
 structurize_jj_blockpaperwall_jj_1={hasPattern=false,label="",tag={}},
 structurize_jj_blockpaperwall_jj_2={hasPattern=false,label="",tag={}},
 structurize_jj_blockpaperwall_jj_3={hasPattern=false,label="",tag={}},
 structurize_jj_blockshingle_acacia={hasPattern=false,label="",tag={}},
 structurize_jj_blockshingle_birch={hasPattern=false,label="",tag={}},
 structurize_jj_blockshingle_dark_oak={hasPattern=false,label="",tag={}},
 structurize_jj_blockshingle_jungle={hasPattern=false,label="",tag={}},
 structurize_jj_blockshingle_oak={hasPattern=false,label="",tag={}},
 structurize_jj_blockshingle_spruce={hasPattern=false,label="",tag={}},
 structurize_jj_blockshingleslab={hasPattern=false,label="",tag={}},
 structurize_jj_blocksolidsubstitution={hasPattern=false,label="",tag={}},
 structurize_jj_blocksubstitution={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_acacia_doublecrossed={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_acacia_downgated={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_acacia_framed={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_acacia_gateframed={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_acacia_horizontalnocap={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_acacia_horizontalplain={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_acacia_onecrossedlr={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_acacia_onecrossedrl={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_acacia_plain={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_acacia_sideframed={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_birch_doublecrossed={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_birch_downgated={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_birch_framed={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_birch_gateframed={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_birch_horizontalnocap={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_birch_horizontalplain={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_birch_onecrossedlr={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_birch_onecrossedrl={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_birch_plain={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_birch_sideframed={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_dark_oak_doublecrossed={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_dark_oak_downgated={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_dark_oak_framed={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_dark_oak_gateframed={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_dark_oak_horizontalnocap={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_dark_oak_horizontalplain={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_dark_oak_onecrossedlr={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_dark_oak_onecrossedrl={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_dark_oak_plain={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_dark_oak_sideframed={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_jungle_doublecrossed={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_jungle_downgated={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_jungle_framed={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_jungle_gateframed={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_jungle_horizontalnocap={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_jungle_horizontalplain={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_jungle_onecrossedlr={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_jungle_onecrossedrl={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_jungle_plain={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_jungle_sideframed={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_oak_doublecrossed={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_oak_downgated={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_oak_framed={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_oak_gateframed={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_oak_horizontalnocap={hasPattern=false,label="",tag={}},
 structurize_jj_blocktimberframe_oak_horizontalplain={hasPattern=true,label="",tag={}},
 structurize_jj_blocktimberframe_oak_onecrossedlr={hasPattern=true,label="",tag={}},
 structurize_jj_blocktimberframe_oak_onecrossedrl={hasPattern=true,label="",tag={}},
 structurize_jj_blocktimberframe_oak_plain={hasPattern=true,label="",tag={}},
 structurize_jj_blocktimberframe_oak_sideframed={hasPattern=true,label="",tag={}},
 structurize_jj_blocktimberframe_spruce_doublecrossed={hasPattern=true,label="",tag={}},
 structurize_jj_blocktimberframe_spruce_downgated={hasPattern=true,label="",tag={}},
 structurize_jj_blocktimberframe_spruce_framed={hasPattern=true,label="",tag={}},
 structurize_jj_blocktimberframe_spruce_gateframed={hasPattern=true,label="",tag={}},
 structurize_jj_blocktimberframe_spruce_horizontalnocap={hasPattern=true,label="",tag={}},
 structurize_jj_blocktimberframe_spruce_horizontalplain={hasPattern=true,label="",tag={}},
 structurize_jj_blocktimberframe_spruce_onecrossedlr={hasPattern=true,label="",tag={}},
 structurize_jj_blocktimberframe_spruce_onecrossedrl={hasPattern=true,label="",tag={}},
 structurize_jj_blocktimberframe_spruce_plain={hasPattern=true,label="",tag={}},
 structurize_jj_blocktimberframe_spruce_sideframed={hasPattern=true,label="",tag={}},
 structurize_jj_cactusdoor={hasPattern=true,label="",tag={}},
 structurize_jj_caliper={hasPattern=false,label="",tag={}},
 structurize_jj_multiblock={hasPattern=true,label="",tag={}},
 structurize_jj_sceptergold={hasPattern=true,label="",tag={}},
 structurize_jj_sceptersteel={hasPattern=true,label="",tag={}},
 structurize_jj_shapetool={hasPattern=true,label="",tag={}}
 }