return {
 ae2stuff_jj_encoder={hasPattern=true,label="Schablonenkodierer",tag={}},
 ae2stuff_jj_grower={hasPattern=true,label="Kristallwachstumskammer",tag={}},
 ae2stuff_jj_inscriber={hasPattern=true,label="Erweiterte Gravurmaschine",tag={}},
 ae2stuff_jj_visualiser={hasPattern=true,label="Network Visualisation Tool",tag={}},
 ae2stuff_jj_wireless={hasPattern=true,label="Wireless Connector",tag={}},
 ae2stuff_jj_wireless_kit={hasPattern=true,label="Wireless Setup Kit",tag={}},
 appliedenergistics2_jj_biometric_card={hasPattern=true,label="Biometriekarte",tag={}},
 appliedenergistics2_jj_cable_bus={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_cell_workbench={hasPattern=true,label="Speicherzellenwerkbank",tag={}},
 appliedenergistics2_jj_certus_quartz_axe={hasPattern=true,label="Certusquarzaxt",tag={}},
 appliedenergistics2_jj_certus_quartz_cutting_knife={hasPattern=true,label="Certusquarzmeißel",tag={}},
 appliedenergistics2_jj_certus_quartz_hoe={hasPattern=true,label="Certusquarzhacke",tag={}},
 appliedenergistics2_jj_certus_quartz_pickaxe={hasPattern=true,label="Certusquarzspitzhacke",tag={}},
 appliedenergistics2_jj_certus_quartz_spade={hasPattern=true,label="Certusquarzschaufel",tag={}},
 appliedenergistics2_jj_certus_quartz_sword={hasPattern=true,label="Certusquarzschwert",tag={}},
 appliedenergistics2_jj_certus_quartz_wrench={hasPattern=true,label="Certusquarzschraubenschlüssel",tag={}},
 appliedenergistics2_jj_charged_quartz_ore={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_charged_staff={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_charged_staff_b_1={hasPattern=true,label="Geladener Stab",tag={}},
 appliedenergistics2_jj_charger={hasPattern=true,label="Ladegerät",tag={}},
 appliedenergistics2_jj_chest={hasPattern=true,label="ME-Truhe",tag={}},
 appliedenergistics2_jj_chiseled_quartz_block={hasPattern=true,label="Gemeißelter Certusquarzblock",tag={}},
 appliedenergistics2_jj_chiseled_quartz_slab={hasPattern=true,label="Gemeißelte Certusquartzstufe",tag={}},
 appliedenergistics2_jj_chiseled_quartz_stairs={hasPattern=true,label="Chiseled Certus Quartz Stairs",tag={}},
 appliedenergistics2_jj_color_applicator={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_color_applicator_b_1={hasPattern=true,label="Farbapplikator - Leer",tag={}},
 appliedenergistics2_jj_condenser={hasPattern=true,label="Materiekondensator",tag={}},
 appliedenergistics2_jj_controller={hasPattern=true,label="ME-Controller",tag={}},
 appliedenergistics2_jj_crafting_accelerator={hasPattern=true,label="Fertigungs-Prozessoreinheit",tag={}},
 appliedenergistics2_jj_crafting_monitor={hasPattern=true,label="Fertigungsmonitor",tag={}},
 appliedenergistics2_jj_crafting_storage_16k={hasPattern=true,label="16k-Fertigungsspeicher",tag={}},
 appliedenergistics2_jj_crafting_storage_1k={hasPattern=true,label="1k-Fertigungsspeicher",tag={}},
 appliedenergistics2_jj_crafting_storage_4k={hasPattern=true,label="4k-Fertigungsspeicher",tag={}},
 appliedenergistics2_jj_crafting_storage_64k={hasPattern=true,label="64k-Fertigungsspeicher",tag={}},
 appliedenergistics2_jj_crafting_unit={hasPattern=true,label="Fertigungseinheit",tag={}},
 appliedenergistics2_jj_crank={hasPattern=true,label="Holzkurbel",tag={}},
 appliedenergistics2_jj_creative_energy_cell={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_creative_storage_cell={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_crystal_seed={hasPattern=false,label="",tag={progress=0}},
 appliedenergistics2_jj_crystal_seed_b_1={hasPattern=false,label="",tag={progress=200}},
 appliedenergistics2_jj_crystal_seed_b_2={hasPattern=false,label="",tag={progress=400}},
 appliedenergistics2_jj_crystal_seed_jj_1200={hasPattern=false,label="",tag={progress=1200}},
 appliedenergistics2_jj_crystal_seed_jj_1200_b_1={hasPattern=false,label="",tag={progress=1400}},
 appliedenergistics2_jj_crystal_seed_jj_1200_b_2={hasPattern=false,label="",tag={progress=1600}},
 appliedenergistics2_jj_crystal_seed_jj_600={hasPattern=false,label="",tag={progress=600}},
 appliedenergistics2_jj_crystal_seed_jj_600_b_1={hasPattern=false,label="",tag={progress=800}},
 appliedenergistics2_jj_crystal_seed_jj_600_b_2={hasPattern=false,label="",tag={progress=1000}},
 appliedenergistics2_jj_dense_energy_cell={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_dense_energy_cell_b_1={hasPattern=true,label="Dichte Energiezelle",tag={}},
 appliedenergistics2_jj_drive={hasPattern=true,label="ME-Laufwerk",tag={}},
 appliedenergistics2_jj_dummy_fluid_item={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_encoded_pattern={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_energy_acceptor={hasPattern=true,label="Energieakzeptor",tag={}},
 appliedenergistics2_jj_energy_cell={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_energy_cell_b_1={hasPattern=true,label="Energiezelle",tag={}},
 appliedenergistics2_jj_entropy_manipulator={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_entropy_manipulator_b_1={hasPattern=true,label="Entropiemanipulator",tag={}},
 appliedenergistics2_jj_fluid_interface={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_fluid_storage_cell_16k={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_fluid_storage_cell_1k={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_fluid_storage_cell_4k={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_fluid_storage_cell_64k={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_fluix_block={hasPattern=true,label="Fluixblock",tag={}},
 appliedenergistics2_jj_fluix_slab={hasPattern=true,label="Fluixstufe",tag={}},
 appliedenergistics2_jj_fluix_stairs={hasPattern=true,label="Fluix Stairs",tag={}},
 appliedenergistics2_jj_grindstone={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_inscriber={hasPattern=true,label="Gravurmaschine",tag={}},
 appliedenergistics2_jj_interface={hasPattern=true,label="ME-Schnittstelle",tag={}},
 appliedenergistics2_jj_io_port={hasPattern=true,label="ME-IO-Port",tag={}},
 appliedenergistics2_jj_light_detector={hasPattern=true,label="Quarzlichtsensor",tag={}},
 appliedenergistics2_jj_material={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_1={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_10={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_11={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_12={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_13={hasPattern=true,label="Gravur-Kalkulationsdruck",tag={}},
 appliedenergistics2_jj_material_jj_14={hasPattern=true,label="Gravur-Konstruktionsdruck",tag={}},
 appliedenergistics2_jj_material_jj_15={hasPattern=true,label="Gravur-Logikdruck",tag={}},
 appliedenergistics2_jj_material_jj_16={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_17={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_18={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_19={hasPattern=true,label="Gravur-Siliziumdruck",tag={}},
 appliedenergistics2_jj_material_jj_2={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_20={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_21={hasPattern=true,label="Schreiber-Namensdruck",tag={}},
 appliedenergistics2_jj_material_jj_22={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_23={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_24={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_25={hasPattern=true,label="Basiskarte",tag={}},
 appliedenergistics2_jj_material_jj_26={hasPattern=true,label="Redstone-Karte",tag={}},
 appliedenergistics2_jj_material_jj_27={hasPattern=true,label="Kapazitätskarte",tag={}},
 appliedenergistics2_jj_material_jj_28={hasPattern=true,label="Fortgeschrittene Karte",tag={}},
 appliedenergistics2_jj_material_jj_29={hasPattern=true,label="Ungenauigkeitskarte",tag={}},
 appliedenergistics2_jj_material_jj_3={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_30={hasPattern=true,label="Beschleunigungskarte",tag={}},
 appliedenergistics2_jj_material_jj_31={hasPattern=true,label="Umkehrungskarte",tag={}},
 appliedenergistics2_jj_material_jj_32={hasPattern=true,label="2³ Raumkomponente",tag={}},
 appliedenergistics2_jj_material_jj_33={hasPattern=true,label="16³ Raumkomponente",tag={}},
 appliedenergistics2_jj_material_jj_34={hasPattern=true,label="128³ Raumkomponente",tag={}},
 appliedenergistics2_jj_material_jj_35={hasPattern=true,label="1k-ME-Speicherkomponente",tag={}},
 appliedenergistics2_jj_material_jj_36={hasPattern=true,label="4k-ME-Speicherkomponente",tag={}},
 appliedenergistics2_jj_material_jj_37={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_38={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_39={hasPattern=true,label="ME-Speichergehäuse",tag={}},
 appliedenergistics2_jj_material_jj_4={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_40={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_41={hasPattern=true,label="Drahtlosempfänger",tag={}},
 appliedenergistics2_jj_material_jj_42={hasPattern=true,label="Drahtlosverstärker",tag={}},
 appliedenergistics2_jj_material_jj_43={hasPattern=true,label="Formationskern",tag={}},
 appliedenergistics2_jj_material_jj_44={hasPattern=true,label="Annihilationskern",tag={}},
 appliedenergistics2_jj_material_jj_45={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_46={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_47={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_48={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_49={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_5={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_51={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_52={hasPattern=true,label="Leere Schablone",tag={}},
 appliedenergistics2_jj_material_jj_53={hasPattern=true,label="Fertigungskarte",tag={}},
 appliedenergistics2_jj_material_jj_54={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_55={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_56={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_57={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_6={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_7={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_8={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_material_jj_9={hasPattern=true,label="Fluixperle",tag={}},
 appliedenergistics2_jj_matrix_frame={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_matter_cannon={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_matter_cannon_b_1={hasPattern=true,label="Materiekanone",tag={}},
 appliedenergistics2_jj_memory_card={hasPattern=true,label="Speicherkarte",tag={}},
 appliedenergistics2_jj_molecular_assembler={hasPattern=true,label="Molekularassembler",tag={}},
 appliedenergistics2_jj_nether_quartz_axe={hasPattern=true,label="Netherquarzaxt",tag={}},
 appliedenergistics2_jj_nether_quartz_cutting_knife={hasPattern=true,label="Netherquarzmeißel",tag={}},
 appliedenergistics2_jj_nether_quartz_hoe={hasPattern=true,label="Netherquarzhacke",tag={}},
 appliedenergistics2_jj_nether_quartz_pickaxe={hasPattern=true,label="Netherquarzspitzhacke",tag={}},
 appliedenergistics2_jj_nether_quartz_spade={hasPattern=true,label="Netherquarzschaufel",tag={}},
 appliedenergistics2_jj_nether_quartz_sword={hasPattern=true,label="Netherquarzschwert",tag={}},
 appliedenergistics2_jj_nether_quartz_wrench={hasPattern=true,label="Netherquarzschraubenschlüssel",tag={}},
 appliedenergistics2_jj_network_tool={hasPattern=true,label="Netzwerksonde",tag={}},
 appliedenergistics2_jj_paint={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_paint_ball={hasPattern=true,label="Farbball - Weiß",tag={}},
 appliedenergistics2_jj_paint_ball_jj_1={hasPattern=true,label="Farbball - Orange",tag={}},
 appliedenergistics2_jj_paint_ball_jj_10={hasPattern=true,label="Farbball - Violett",tag={}},
 appliedenergistics2_jj_paint_ball_jj_11={hasPattern=true,label="Farbball - Blau",tag={}},
 appliedenergistics2_jj_paint_ball_jj_12={hasPattern=true,label="Farbball - Braun",tag={}},
 appliedenergistics2_jj_paint_ball_jj_13={hasPattern=true,label="Farbball - Grün",tag={}},
 appliedenergistics2_jj_paint_ball_jj_14={hasPattern=true,label="Farbball - Rot",tag={}},
 appliedenergistics2_jj_paint_ball_jj_15={hasPattern=true,label="Farbball - Schwarz",tag={}},
 appliedenergistics2_jj_paint_ball_jj_2={hasPattern=true,label="Farbball - Magenta",tag={}},
 appliedenergistics2_jj_paint_ball_jj_20={hasPattern=true,label="Farbball - Lumen Weiß",tag={}},
 appliedenergistics2_jj_paint_ball_jj_21={hasPattern=true,label="Farbball - Lumen Orange",tag={}},
 appliedenergistics2_jj_paint_ball_jj_22={hasPattern=true,label="Farbball - Lumen Magenta",tag={}},
 appliedenergistics2_jj_paint_ball_jj_23={hasPattern=true,label="Farbball - Lumen Hellblau",tag={}},
 appliedenergistics2_jj_paint_ball_jj_24={hasPattern=true,label="Farbball - Lumen Gelb",tag={}},
 appliedenergistics2_jj_paint_ball_jj_25={hasPattern=true,label="Farbball - Lumen Hellgrün",tag={}},
 appliedenergistics2_jj_paint_ball_jj_26={hasPattern=true,label="Farbball - Lumen Pink",tag={}},
 appliedenergistics2_jj_paint_ball_jj_27={hasPattern=true,label="Farbball - Lumen Grau",tag={}},
 appliedenergistics2_jj_paint_ball_jj_28={hasPattern=true,label="Farbball - Lumen Hellgrau",tag={}},
 appliedenergistics2_jj_paint_ball_jj_29={hasPattern=true,label="Farbball - Lumen Türkis",tag={}},
 appliedenergistics2_jj_paint_ball_jj_3={hasPattern=true,label="Farbball - Hellblau",tag={}},
 appliedenergistics2_jj_paint_ball_jj_30={hasPattern=true,label="Farbball - Lumen Violett",tag={}},
 appliedenergistics2_jj_paint_ball_jj_31={hasPattern=true,label="Farbball - Lumen Blau",tag={}},
 appliedenergistics2_jj_paint_ball_jj_32={hasPattern=true,label="Farbball - Lumen Braun",tag={}},
 appliedenergistics2_jj_paint_ball_jj_33={hasPattern=true,label="Farbball - Lumen Grün",tag={}},
 appliedenergistics2_jj_paint_ball_jj_34={hasPattern=true,label="Farbball - Lumen Rot",tag={}},
 appliedenergistics2_jj_paint_ball_jj_35={hasPattern=true,label="Farbball - Lumen Schwarz",tag={}},
 appliedenergistics2_jj_paint_ball_jj_4={hasPattern=true,label="Farbball - Gelb",tag={}},
 appliedenergistics2_jj_paint_ball_jj_5={hasPattern=true,label="Farbball - Hellgrün",tag={}},
 appliedenergistics2_jj_paint_ball_jj_6={hasPattern=true,label="Farbball - Pink",tag={}},
 appliedenergistics2_jj_paint_ball_jj_7={hasPattern=true,label="Farbball - Grau",tag={}},
 appliedenergistics2_jj_paint_ball_jj_8={hasPattern=true,label="Farbball - Hellgrau",tag={}},
 appliedenergistics2_jj_paint_ball_jj_9={hasPattern=true,label="Farbball - Türkis",tag={}},
 appliedenergistics2_jj_part={hasPattern=true,label="ME-Glaskabel - Weiß",tag={}},
 appliedenergistics2_jj_part_jj_1={hasPattern=true,label="ME-Glaskabel - Orange",tag={}},
 appliedenergistics2_jj_part_jj_10={hasPattern=true,label="ME-Glaskabel - Violett",tag={}},
 appliedenergistics2_jj_part_jj_100={hasPattern=true,label="Invertierter schaltbarer ME-Bus",tag={}},
 appliedenergistics2_jj_part_jj_11={hasPattern=true,label="ME-Glaskabel - Blau",tag={}},
 appliedenergistics2_jj_part_jj_12={hasPattern=true,label="ME-Glaskabel - Braun",tag={}},
 appliedenergistics2_jj_part_jj_120={hasPattern=true,label="Kabelanker",tag={}},
 appliedenergistics2_jj_part_jj_13={hasPattern=true,label="ME-Glaskabel - Grün",tag={}},
 appliedenergistics2_jj_part_jj_14={hasPattern=true,label="ME-Glaskabel - Rot",tag={}},
 appliedenergistics2_jj_part_jj_140={hasPattern=true,label="Quarzfaser",tag={}},
 appliedenergistics2_jj_part_jj_15={hasPattern=true,label="ME-Glaskabel - Schwarz",tag={}},
 appliedenergistics2_jj_part_jj_16={hasPattern=true,label="ME-Glaskabel - Fluix",tag={}},
 appliedenergistics2_jj_part_jj_160={hasPattern=true,label="Helles Leuchtfeld",tag={}},
 appliedenergistics2_jj_part_jj_180={hasPattern=true,label="Leuchtfeld",tag={}},
 appliedenergistics2_jj_part_jj_2={hasPattern=true,label="ME-Glaskabel - Magenta",tag={}},
 appliedenergistics2_jj_part_jj_20={hasPattern=true,label="Verdecktes ME-Kabel - Weiß",tag={}},
 appliedenergistics2_jj_part_jj_200={hasPattern=true,label="Dunkles Leuchtfeld",tag={}},
 appliedenergistics2_jj_part_jj_21={hasPattern=true,label="Verdecktes ME-Kabel - Orange",tag={}},
 appliedenergistics2_jj_part_jj_22={hasPattern=true,label="Verdecktes ME-Kabel - Magenta",tag={}},
 appliedenergistics2_jj_part_jj_220={hasPattern=true,label="ME-Speicherbus",tag={}},
 appliedenergistics2_jj_part_jj_221={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_part_jj_23={hasPattern=true,label="Verdecktes ME-Kabel - Hellblau",tag={}},
 appliedenergistics2_jj_part_jj_24={hasPattern=true,label="Verdecktes ME-Kabel - Gelb",tag={}},
 appliedenergistics2_jj_part_jj_240={hasPattern=true,label="ME-Importbus",tag={}},
 appliedenergistics2_jj_part_jj_241={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_part_jj_25={hasPattern=true,label="Verdecktes ME-Kabel - Hellgrün",tag={}},
 appliedenergistics2_jj_part_jj_26={hasPattern=true,label="Verdecktes ME-Kabel - Pink",tag={}},
 appliedenergistics2_jj_part_jj_260={hasPattern=true,label="ME-Exportbus",tag={}},
 appliedenergistics2_jj_part_jj_261={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_part_jj_27={hasPattern=true,label="Verdecktes ME-Kabel - Grau",tag={}},
 appliedenergistics2_jj_part_jj_28={hasPattern=true,label="Verdecktes ME-Kabel - Hellgrau",tag={}},
 appliedenergistics2_jj_part_jj_280={hasPattern=true,label="ME-Füllstandsemitter",tag={}},
 appliedenergistics2_jj_part_jj_281={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_part_jj_29={hasPattern=true,label="Verdecktes ME-Kabel - Türkis",tag={}},
 appliedenergistics2_jj_part_jj_3={hasPattern=true,label="ME-Glaskabel - Hellblau",tag={}},
 appliedenergistics2_jj_part_jj_30={hasPattern=true,label="Verdecktes ME-Kabel - Violett",tag={}},
 appliedenergistics2_jj_part_jj_300={hasPattern=true,label="ME-Annihilationsfeld",tag={}},
 appliedenergistics2_jj_part_jj_301={hasPattern=true,label="ME-Identitätsannihilationsfelds",tag={}},
 appliedenergistics2_jj_part_jj_302={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_part_jj_31={hasPattern=true,label="Verdecktes ME-Kabel - Blau",tag={}},
 appliedenergistics2_jj_part_jj_32={hasPattern=true,label="Verdecktes ME-Kabel - Braun",tag={}},
 appliedenergistics2_jj_part_jj_320={hasPattern=true,label="ME-Formationsfeld",tag={}},
 appliedenergistics2_jj_part_jj_321={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_part_jj_33={hasPattern=true,label="Verdecktes ME-Kabel - Grün",tag={}},
 appliedenergistics2_jj_part_jj_34={hasPattern=true,label="Verdecktes ME-Kabel - Rot",tag={}},
 appliedenergistics2_jj_part_jj_340={hasPattern=true,label="ME-Schablonenkonsole",tag={}},
 appliedenergistics2_jj_part_jj_35={hasPattern=true,label="Verdecktes ME-Kabel - Schwarz",tag={}},
 appliedenergistics2_jj_part_jj_36={hasPattern=true,label="Verdecktes ME-Kabel - Fluix",tag={}},
 appliedenergistics2_jj_part_jj_360={hasPattern=true,label="ME-Fertigungskonsole",tag={}},
 appliedenergistics2_jj_part_jj_380={hasPattern=true,label="ME-Konsole",tag={}},
 appliedenergistics2_jj_part_jj_4={hasPattern=true,label="ME-Glaskabel - Gelb",tag={}},
 appliedenergistics2_jj_part_jj_40={hasPattern=true,label="Schlaues ME-Kabel - Weiß",tag={}},
 appliedenergistics2_jj_part_jj_400={hasPattern=true,label="ME-Speichermonitor",tag={}},
 appliedenergistics2_jj_part_jj_41={hasPattern=true,label="Schlaues ME-Kabel - Orange",tag={}},
 appliedenergistics2_jj_part_jj_42={hasPattern=true,label="Schlaues ME-Kabel - Magenta",tag={}},
 appliedenergistics2_jj_part_jj_420={hasPattern=true,label="ME-Konversionsmonitor",tag={}},
 appliedenergistics2_jj_part_jj_43={hasPattern=true,label="Schlaues ME-Kabel - Hellblau",tag={}},
 appliedenergistics2_jj_part_jj_44={hasPattern=true,label="Schlaues ME-Kabel - Gelb",tag={}},
 appliedenergistics2_jj_part_jj_440={hasPattern=true,label="ME-Schnittstelle",tag={}},
 appliedenergistics2_jj_part_jj_441={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_part_jj_45={hasPattern=true,label="Schlaues ME-Kabel - Hellgrün",tag={}},
 appliedenergistics2_jj_part_jj_46={hasPattern=true,label="Schlaues ME-Kabel - Pink",tag={}},
 appliedenergistics2_jj_part_jj_460={hasPattern=true,label="P2P-Tunnel - ME",tag={}},
 appliedenergistics2_jj_part_jj_461={hasPattern=true,label="P2P-Tunnel - Redstone",tag={}},
 appliedenergistics2_jj_part_jj_462={hasPattern=true,label="P2P-Tunnel - Item",tag={}},
 appliedenergistics2_jj_part_jj_463={hasPattern=true,label="P2P-Tunnel - Flüssigkeiten",tag={}},
 appliedenergistics2_jj_part_jj_465={hasPattern=true,label="P2P-Tunnel - EU",tag={}},
 appliedenergistics2_jj_part_jj_467={hasPattern=true,label="P2P-Tunnel - Licht",tag={}},
 appliedenergistics2_jj_part_jj_469={hasPattern=true,label="P2P-Tunnel - FE",tag={}},
 appliedenergistics2_jj_part_jj_47={hasPattern=true,label="Schlaues ME-Kabel - Grau",tag={}},
 appliedenergistics2_jj_part_jj_48={hasPattern=true,label="Schlaues ME-Kabel - Hellgrau",tag={}},
 appliedenergistics2_jj_part_jj_480={hasPattern=true,label="ME-Schnittstellenkonsole",tag={}},
 appliedenergistics2_jj_part_jj_49={hasPattern=true,label="Schlaues ME-Kabel - Türkis",tag={}},
 appliedenergistics2_jj_part_jj_5={hasPattern=true,label="ME-Glaskabel - Hellgrün",tag={}},
 appliedenergistics2_jj_part_jj_50={hasPattern=true,label="Schlaues ME-Kabel - Violett",tag={}},
 appliedenergistics2_jj_part_jj_500={hasPattern=true,label="ME Dense Covered Cable - Weiß",tag={}},
 appliedenergistics2_jj_part_jj_501={hasPattern=true,label="ME Dense Covered Cable - Orange",tag={}},
 appliedenergistics2_jj_part_jj_502={hasPattern=true,label="ME Dense Covered Cable - Magenta",tag={}},
 appliedenergistics2_jj_part_jj_503={hasPattern=true,label="ME Dense Covered Cable - Hellblau",tag={}},
 appliedenergistics2_jj_part_jj_504={hasPattern=true,label="ME Dense Covered Cable - Gelb",tag={}},
 appliedenergistics2_jj_part_jj_505={hasPattern=true,label="ME Dense Covered Cable - Hellgrün",tag={}},
 appliedenergistics2_jj_part_jj_506={hasPattern=true,label="ME Dense Covered Cable - Pink",tag={}},
 appliedenergistics2_jj_part_jj_507={hasPattern=true,label="ME Dense Covered Cable - Grau",tag={}},
 appliedenergistics2_jj_part_jj_508={hasPattern=true,label="ME Dense Covered Cable - Hellgrau",tag={}},
 appliedenergistics2_jj_part_jj_509={hasPattern=true,label="ME Dense Covered Cable - Türkis",tag={}},
 appliedenergistics2_jj_part_jj_51={hasPattern=true,label="Schlaues ME-Kabel - Blau",tag={}},
 appliedenergistics2_jj_part_jj_510={hasPattern=true,label="ME Dense Covered Cable - Violett",tag={}},
 appliedenergistics2_jj_part_jj_511={hasPattern=true,label="ME Dense Covered Cable - Blau",tag={}},
 appliedenergistics2_jj_part_jj_512={hasPattern=true,label="ME Dense Covered Cable - Braun",tag={}},
 appliedenergistics2_jj_part_jj_513={hasPattern=true,label="ME Dense Covered Cable - Grün",tag={}},
 appliedenergistics2_jj_part_jj_514={hasPattern=true,label="ME Dense Covered Cable - Rot",tag={}},
 appliedenergistics2_jj_part_jj_515={hasPattern=true,label="ME Dense Covered Cable - Schwarz",tag={}},
 appliedenergistics2_jj_part_jj_516={hasPattern=true,label="ME Dense Covered Cable - Fluix",tag={}},
 appliedenergistics2_jj_part_jj_52={hasPattern=true,label="Schlaues ME-Kabel - Braun",tag={}},
 appliedenergistics2_jj_part_jj_520={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_part_jj_53={hasPattern=true,label="Schlaues ME-Kabel - Grün",tag={}},
 appliedenergistics2_jj_part_jj_54={hasPattern=true,label="Schlaues ME-Kabel - Rot",tag={}},
 appliedenergistics2_jj_part_jj_55={hasPattern=true,label="Schlaues ME-Kabel - Schwarz",tag={}},
 appliedenergistics2_jj_part_jj_56={hasPattern=true,label="Schlaues ME-Kabel - Fluix",tag={}},
 appliedenergistics2_jj_part_jj_6={hasPattern=true,label="ME-Glaskabel - Pink",tag={}},
 appliedenergistics2_jj_part_jj_60={hasPattern=true,label="Dichtes ME-Kabel - Weiß",tag={}},
 appliedenergistics2_jj_part_jj_61={hasPattern=true,label="Dichtes ME-Kabel - Orange",tag={}},
 appliedenergistics2_jj_part_jj_62={hasPattern=true,label="Dichtes ME-Kabel - Magenta",tag={}},
 appliedenergistics2_jj_part_jj_63={hasPattern=true,label="Dichtes ME-Kabel - Hellblau",tag={}},
 appliedenergistics2_jj_part_jj_64={hasPattern=true,label="Dichtes ME-Kabel - Gelb",tag={}},
 appliedenergistics2_jj_part_jj_65={hasPattern=true,label="Dichtes ME-Kabel - Hellgrün",tag={}},
 appliedenergistics2_jj_part_jj_66={hasPattern=true,label="Dichtes ME-Kabel - Pink",tag={}},
 appliedenergistics2_jj_part_jj_67={hasPattern=true,label="Dichtes ME-Kabel - Grau",tag={}},
 appliedenergistics2_jj_part_jj_68={hasPattern=true,label="Dichtes ME-Kabel - Hellgrau",tag={}},
 appliedenergistics2_jj_part_jj_69={hasPattern=true,label="Dichtes ME-Kabel - Türkis",tag={}},
 appliedenergistics2_jj_part_jj_7={hasPattern=true,label="ME-Glaskabel - Grau",tag={}},
 appliedenergistics2_jj_part_jj_70={hasPattern=true,label="Dichtes ME-Kabel - Violett",tag={}},
 appliedenergistics2_jj_part_jj_71={hasPattern=true,label="Dichtes ME-Kabel - Blau",tag={}},
 appliedenergistics2_jj_part_jj_72={hasPattern=true,label="Dichtes ME-Kabel - Braun",tag={}},
 appliedenergistics2_jj_part_jj_73={hasPattern=true,label="Dichtes ME-Kabel - Grün",tag={}},
 appliedenergistics2_jj_part_jj_74={hasPattern=true,label="Dichtes ME-Kabel - Rot",tag={}},
 appliedenergistics2_jj_part_jj_75={hasPattern=true,label="Dichtes ME-Kabel - Schwarz",tag={}},
 appliedenergistics2_jj_part_jj_76={hasPattern=true,label="Dichtes ME-Kabel - Fluix",tag={}},
 appliedenergistics2_jj_part_jj_8={hasPattern=true,label="ME-Glaskabel - Hellgrau",tag={}},
 appliedenergistics2_jj_part_jj_80={hasPattern=true,label="Schaltbarer ME-Bus",tag={}},
 appliedenergistics2_jj_part_jj_9={hasPattern=true,label="ME-Glaskabel - Türkis",tag={}},
 appliedenergistics2_jj_portable_cell={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_portable_cell_b_1={hasPattern=true,label="Tragbare Zelle",tag={}},
 appliedenergistics2_jj_quantum_link={hasPattern=true,label="ME-Quantentunnelkammer",tag={}},
 appliedenergistics2_jj_quantum_ring={hasPattern=true,label="ME-Quantentunnelring",tag={}},
 appliedenergistics2_jj_quartz_block={hasPattern=true,label="Certusquarzblock",tag={}},
 appliedenergistics2_jj_quartz_fixture={hasPattern=true,label="Geladene Quarzleuchte",tag={}},
 appliedenergistics2_jj_quartz_glass={hasPattern=true,label="Quarzglas",tag={}},
 appliedenergistics2_jj_quartz_growth_accelerator={hasPattern=true,label="Kristallwachstumsbeschleuniger",tag={}},
 appliedenergistics2_jj_quartz_ore={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_quartz_pillar={hasPattern=true,label="Certusquarzsäule",tag={}},
 appliedenergistics2_jj_quartz_pillar_slab={hasPattern=true,label="Certusquartzsäulenstufe",tag={}},
 appliedenergistics2_jj_quartz_pillar_stairs={hasPattern=true,label="Certus Quartz Pillar Stairs",tag={}},
 appliedenergistics2_jj_quartz_slab={hasPattern=true,label="Certusquartzstufe",tag={}},
 appliedenergistics2_jj_quartz_stairs={hasPattern=true,label="Certus Quartz Stairs",tag={}},
 appliedenergistics2_jj_quartz_vibrant_glass={hasPattern=true,label="Polarisiertes Quarzglas",tag={}},
 appliedenergistics2_jj_security_station={hasPattern=true,label="ME-Sicherheitskonsole",tag={}},
 appliedenergistics2_jj_sky_compass={hasPattern=true,label="Meteoritenkompass",tag={}},
 appliedenergistics2_jj_sky_stone_block={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_sky_stone_brick={hasPattern=true,label="Himmelssteinziegel",tag={}},
 appliedenergistics2_jj_sky_stone_brick_slab={hasPattern=true,label="Himmelssteinziegelstufe",tag={}},
 appliedenergistics2_jj_sky_stone_brick_stairs={hasPattern=true,label="Sky Stone Brick Stairs",tag={}},
 appliedenergistics2_jj_sky_stone_chest={hasPattern=true,label="Himmelssteintruhe",tag={}},
 appliedenergistics2_jj_sky_stone_slab={hasPattern=true,label="Himmelssteinstufe",tag={}},
 appliedenergistics2_jj_sky_stone_small_brick={hasPattern=true,label="Kleine Himmelssteinziegel",tag={}},
 appliedenergistics2_jj_sky_stone_small_brick_slab={hasPattern=true,label="Himmelssteinkleinziegelstufe",tag={}},
 appliedenergistics2_jj_sky_stone_small_brick_stairs={hasPattern=true,label="Sky Stone Small Brick Stairs",tag={}},
 appliedenergistics2_jj_sky_stone_stairs={hasPattern=true,label="Sky Stone Stairs",tag={}},
 appliedenergistics2_jj_smooth_sky_stone_block={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_smooth_sky_stone_chest={hasPattern=true,label="Himmelssteinblocktruhe",tag={}},
 appliedenergistics2_jj_smooth_sky_stone_slab={hasPattern=true,label="Himmelssteinblockstufe",tag={}},
 appliedenergistics2_jj_smooth_sky_stone_stairs={hasPattern=true,label="Sky Stone Block Stairs",tag={}},
 appliedenergistics2_jj_spatial_io_port={hasPattern=true,label="IO-Raumport",tag={}},
 appliedenergistics2_jj_spatial_pylon={hasPattern=true,label="Raumpylon",tag={}},
 appliedenergistics2_jj_spatial_storage_cell_128_cubed={hasPattern=true,label="128³-Raumspeicherzelle",tag={}},
 appliedenergistics2_jj_spatial_storage_cell_16_cubed={hasPattern=true,label="16³-Raumspeicherzelle",tag={}},
 appliedenergistics2_jj_spatial_storage_cell_2_cubed={hasPattern=true,label="2³-Raumspeicherzelle",tag={}},
 appliedenergistics2_jj_storage_cell_16k={hasPattern=true,label="16k-ME-Speicherzelle",tag={}},
 appliedenergistics2_jj_storage_cell_1k={hasPattern=true,label="1k-ME-Speicherzelle",tag={}},
 appliedenergistics2_jj_storage_cell_4k={hasPattern=true,label="4k-ME-Speicherzelle",tag={}},
 appliedenergistics2_jj_storage_cell_64k={hasPattern=true,label="64k-ME-Speicherzelle",tag={}},
 appliedenergistics2_jj_tiny_tnt={hasPattern=true,label="Mini-TNT",tag={}},
 appliedenergistics2_jj_vibration_chamber={hasPattern=true,label="Vibrationskammer",tag={}},
 appliedenergistics2_jj_view_cell={hasPattern=true,label="Sichtzelle",tag={}},
 appliedenergistics2_jj_wireless_access_point={hasPattern=true,label="Drahtloser ME-Zugangspunkt",tag={}},
 appliedenergistics2_jj_wireless_terminal={hasPattern=false,label="",tag={}},
 appliedenergistics2_jj_wireless_terminal_b_1={hasPattern=true,label="Drahtlose Zugangskonsole",tag={}},
 integrateddynamics_jj_block_liquid_chorus={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_block_menril_resin={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_cable={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_coal_generator={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_creative_energy_battery={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_crystalized_chorus_block={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_crystalized_chorus_block_stairs={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_crystalized_chorus_brick={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_crystalized_chorus_brick_stairs={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_crystalized_chorus_chunk={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_crystalized_menril_block={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_crystalized_menril_block_stairs={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_crystalized_menril_brick={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_crystalized_menril_brick_stairs={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_crystalized_menril_chunk={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_delay={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_drying_basin={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_energy_battery={hasPattern=false,label="",tag={energy=0}},
 integrateddynamics_jj_energy_battery_b_1={hasPattern=false,label="",tag={energy=1000000}},
 integrateddynamics_jj_energy_battery_b_2={hasPattern=false,label="",tag={capacity=4000000,energy=0}},
 integrateddynamics_jj_energy_battery_b_3={hasPattern=false,label="",tag={capacity=4000000,energy=4000000}},
 integrateddynamics_jj_energy_battery_b_4={hasPattern=false,label="",tag={capacity=16000000,energy=0}},
 integrateddynamics_jj_energy_battery_b_5={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_facade={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_invisible_light={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_labeller={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_logic_director={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_logic_programmer={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_materializer={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_mechanical_drying_basin={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_mechanical_squeezer={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_menril_berries={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_menril_door={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_menril_leaves={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_menril_log={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_menril_log_filled={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_menril_planks={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_menril_planks_stairs={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_menril_sapling={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_menril_torch={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_menril_torch_stone={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_on_the_dynamics_of_integration={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_part_audio_reader_item={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_part_audio_writer_item={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_part_block_reader_item={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_part_connector_mono_directional_item={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_part_connector_omni_directional_item={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_part_display_panel_item={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_part_dynamic_light_panel_item={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_part_effect_writer_item={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_part_entity_reader_item={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_part_entity_writer_item={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_part_extradimensional_reader_item={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_part_fluid_reader_item={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_part_inventory_reader_item={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_part_inventory_writer_item={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_part_machine_reader_item={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_part_machine_writer_item={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_part_network_reader_item={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_part_redstone_reader_item={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_part_redstone_writer_item={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_part_static_light_panel_item={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_part_world_reader_item={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_portable_logic_programmer={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_proxy={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_squeezer={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_variable={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_variable_transformer={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_variable_transformer_jj_1={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_variablestore={hasPattern=false,label="",tag={}},
 integrateddynamics_jj_wrench={hasPattern=false,label="",tag={}},
 integratedtunnels_jj_part_exporter_energy_item={hasPattern=false,label="",tag={}},
 integratedtunnels_jj_part_exporter_fluid_item={hasPattern=false,label="",tag={}},
 integratedtunnels_jj_part_exporter_item_item={hasPattern=false,label="",tag={}},
 integratedtunnels_jj_part_exporter_world_block_item={hasPattern=false,label="",tag={}},
 integratedtunnels_jj_part_exporter_world_energy_item={hasPattern=false,label="",tag={}},
 integratedtunnels_jj_part_exporter_world_fluid_item={hasPattern=false,label="",tag={}},
 integratedtunnels_jj_part_exporter_world_item_item={hasPattern=false,label="",tag={}},
 integratedtunnels_jj_part_importer_energy_item={hasPattern=false,label="",tag={}},
 integratedtunnels_jj_part_importer_fluid_item={hasPattern=false,label="",tag={}},
 integratedtunnels_jj_part_importer_item_item={hasPattern=false,label="",tag={}},
 integratedtunnels_jj_part_importer_world_block_item={hasPattern=false,label="",tag={}},
 integratedtunnels_jj_part_importer_world_energy_item={hasPattern=false,label="",tag={}},
 integratedtunnels_jj_part_importer_world_fluid_item={hasPattern=false,label="",tag={}},
 integratedtunnels_jj_part_importer_world_item_item={hasPattern=false,label="",tag={}},
 integratedtunnels_jj_part_interface_energy_item={hasPattern=false,label="",tag={}},
 integratedtunnels_jj_part_interface_fluid_item={hasPattern=false,label="",tag={}},
 integratedtunnels_jj_part_interface_item_item={hasPattern=false,label="",tag={}},
 integratedtunnels_jj_part_player_simulator_item={hasPattern=false,label="",tag={}}
 }