return {
 bibliocraft_jj_armorstand={hasPattern=true,label="Eichenholz-Rüstungsständer",tag=""},
 bibliocraft_jj_armorstand_jj_1={hasPattern=true,label="Fichtenholz-Rüstungsständer",tag=""},
 bibliocraft_jj_armorstand_jj_2={hasPattern=true,label="Birkenholz-Rüstungsständer",tag=""},
 bibliocraft_jj_armorstand_jj_3={hasPattern=true,label="Tropenholz-Rüstungsständer",tag=""},
 bibliocraft_jj_armorstand_jj_4={hasPattern=true,label="Akazienholz-Rüstungsständer",tag=""},
 bibliocraft_jj_armorstand_jj_5={hasPattern=true,label="Schwarzeichenholz-Rüstungsständer",tag=""},
 bibliocraft_jj_armorstand_jj_6={hasPattern=true,label="Eingerahmter Rüstungsständer",tag=""},
 bibliocraft_jj_atlasbook={hasPattern=true,label="Atlas",tag=""},
 bibliocraft_jj_atlasplate={hasPattern=false,label="",tag=""},
 bibliocraft_jj_bell={hasPattern=true,label="Schreibtischglocke",tag=""},
 bibliocraft_jj_bibliochase={hasPattern=true,label="Drucksatzrahmen",tag=""},
 bibliocraft_jj_biblioclipboard={hasPattern=true,label="Klemmbrett",tag=""},
 bibliocraft_jj_bibliocreativelock={hasPattern=false,label="",tag=""},
 bibliocraft_jj_bibliodrill={hasPattern=true,label="Schraubendreher",tag=""},
 bibliocraft_jj_biblioglasses={hasPattern=true,label="Lesebrille",tag=""},
 bibliocraft_jj_biblioredbook={hasPattern=false,label="",tag=""},
 bibliocraft_jj_bigbook={hasPattern=true,label="Dickes Schreibbuch",tag=""},
 bibliocraft_jj_bookcase={hasPattern=true,label="Eichenholz-Bücherschrank",tag=""},
 bibliocraft_jj_bookcase_jj_1={hasPattern=true,label="Fichtenholz-Bücherschrank",tag=""},
 bibliocraft_jj_bookcase_jj_2={hasPattern=true,label="Birkenholz-Bücherschrank",tag=""},
 bibliocraft_jj_bookcase_jj_3={hasPattern=true,label="Tropenholz-Bücherschrank",tag=""},
 bibliocraft_jj_bookcase_jj_4={hasPattern=true,label="Akazienholz-Bücherschrank",tag=""},
 bibliocraft_jj_bookcase_jj_5={hasPattern=true,label="Schwarzeichenholz-Bücherschrank",tag=""},
 bibliocraft_jj_bookcase_jj_6={hasPattern=true,label="Eingerahmter Bücherschrank",tag=""},
 bibliocraft_jj_bookcasecreative={hasPattern=false,label="",tag=""},
 bibliocraft_jj_bookcasecreative_jj_1={hasPattern=false,label="",tag=""},
 bibliocraft_jj_bookcasecreative_jj_2={hasPattern=false,label="",tag=""},
 bibliocraft_jj_bookcasecreative_jj_3={hasPattern=false,label="",tag=""},
 bibliocraft_jj_bookcasecreative_jj_4={hasPattern=false,label="",tag=""},
 bibliocraft_jj_bookcasecreative_jj_5={hasPattern=false,label="",tag=""},
 bibliocraft_jj_bookcasecreative_jj_6={hasPattern=false,label="",tag=""},
 bibliocraft_jj_case={hasPattern=true,label="Eichenholz-Schaukasten",tag=""},
 bibliocraft_jj_case_jj_1={hasPattern=true,label="Fichtenholz-Schaukasten",tag=""},
 bibliocraft_jj_case_jj_2={hasPattern=true,label="Birkenholz-Schaukasten",tag=""},
 bibliocraft_jj_case_jj_3={hasPattern=true,label="Tropenholz-Schaukasten",tag=""},
 bibliocraft_jj_case_jj_4={hasPattern=true,label="Akazienholz-Schaukasten",tag=""},
 bibliocraft_jj_case_jj_5={hasPattern=true,label="Schwarzeichenholz-Schaukasten",tag=""},
 bibliocraft_jj_case_jj_6={hasPattern=true,label="Eingerahmter Schaukasten",tag=""},
 bibliocraft_jj_clipboard={hasPattern=false,label="",tag=""},
 bibliocraft_jj_clock={hasPattern=true,label="Eichenholzuhr",tag=""},
 bibliocraft_jj_clock_jj_1={hasPattern=true,label="Fichtenholzuhr",tag=""},
 bibliocraft_jj_clock_jj_2={hasPattern=true,label="Birkenholzuhr",tag=""},
 bibliocraft_jj_clock_jj_3={hasPattern=true,label="Tropenholzuhr",tag=""},
 bibliocraft_jj_clock_jj_4={hasPattern=true,label="Akazienholzuhr",tag=""},
 bibliocraft_jj_clock_jj_5={hasPattern=true,label="Schwarzeichenholzuhr",tag=""},
 bibliocraft_jj_clock_jj_6={hasPattern=true,label="Eingerahmte Uhr",tag=""},
 bibliocraft_jj_compass={hasPattern=true,label="Kompass",tag=""},
 bibliocraft_jj_cookiejar={hasPattern=true,label="Keksglas",tag=""},
 bibliocraft_jj_deathcompass={hasPattern=false,label="",tag=""},
 bibliocraft_jj_desk={hasPattern=true,label="Eichenholzschreibtisch",tag=""},
 bibliocraft_jj_desk_jj_1={hasPattern=true,label="Fichtenholzschreibtisch",tag=""},
 bibliocraft_jj_desk_jj_2={hasPattern=true,label="Birkenholzschreibtisch",tag=""},
 bibliocraft_jj_desk_jj_3={hasPattern=true,label="Tropenholzschreibtisch",tag=""},
 bibliocraft_jj_desk_jj_4={hasPattern=true,label="Akazienholzschreibtisch",tag=""},
 bibliocraft_jj_desk_jj_5={hasPattern=true,label="Schwarzeichenholzschreibtisch",tag=""},
 bibliocraft_jj_desk_jj_6={hasPattern=true,label="Eingerahmter Schreibtisch",tag=""},
 bibliocraft_jj_dinnerplate={hasPattern=true,label="Teller",tag=""},
 bibliocraft_jj_discrack={hasPattern=false,label="",tag=""},
 bibliocraft_jj_enchantedplate={hasPattern=false,label="",tag=""},
 bibliocraft_jj_fancysign={hasPattern=true,label="Schickes Eichenholzschild",tag=""},
 bibliocraft_jj_fancysign_jj_1={hasPattern=true,label="Schickes Fichtenholzschild",tag=""},
 bibliocraft_jj_fancysign_jj_2={hasPattern=true,label="Schickes Birkenholzschild",tag=""},
 bibliocraft_jj_fancysign_jj_3={hasPattern=true,label="Schickes Tropenholzschild",tag=""},
 bibliocraft_jj_fancysign_jj_4={hasPattern=true,label="Schickes Akazienholzschild",tag=""},
 bibliocraft_jj_fancysign_jj_5={hasPattern=true,label="Schickes Schwarzeichenholzschild",tag=""},
 bibliocraft_jj_fancysign_jj_6={hasPattern=true,label="Eingerahmtes Schickes Schild",tag=""},
 bibliocraft_jj_fancyworkbench={hasPattern=true,label="Schicke Eichenholzwerkbank",tag=""},
 bibliocraft_jj_fancyworkbench_jj_1={hasPattern=true,label="Schicke Fichtenholzwerkbank",tag=""},
 bibliocraft_jj_fancyworkbench_jj_2={hasPattern=true,label="Schicke Birkenholzwerkbank",tag=""},
 bibliocraft_jj_fancyworkbench_jj_3={hasPattern=true,label="Schicke Tropenholzwerkbank",tag=""},
 bibliocraft_jj_fancyworkbench_jj_4={hasPattern=true,label="Schicke Akazienholzwerkbank",tag=""},
 bibliocraft_jj_fancyworkbench_jj_5={hasPattern=true,label="Schwarzeichenholzwerkbank",tag=""},
 bibliocraft_jj_fancyworkbench_jj_6={hasPattern=true,label="Eingerahmte Schicke Werkbank",tag=""},
 bibliocraft_jj_framedchest={hasPattern=true,label="Eingerahmte Eichenholztruhe",tag=""},
 bibliocraft_jj_framedchest_jj_1={hasPattern=true,label="Eingerahmte Fichtenholztruhe",tag=""},
 bibliocraft_jj_framedchest_jj_2={hasPattern=true,label="Eingerahmte Birkenholztruhe",tag=""},
 bibliocraft_jj_framedchest_jj_3={hasPattern=true,label="Eingerahmte Tropenholztruhe",tag=""},
 bibliocraft_jj_framedchest_jj_4={hasPattern=true,label="Eingerahmte Akazienholztruhe",tag=""},
 bibliocraft_jj_framedchest_jj_5={hasPattern=true,label="Eingerahmte Schwarzeichenholztruhe",tag=""},
 bibliocraft_jj_framedchest_jj_6={hasPattern=true,label="Eingerahmte Eingerahmte Eichenholztruhe",tag=""},
 bibliocraft_jj_framingboard={hasPattern=true,label="Rahmenbrett",tag=""},
 bibliocraft_jj_framingsaw={hasPattern=true,label="Einrahmsäge",tag=""},
 bibliocraft_jj_framingsheet={hasPattern=true,label="Rahmenplatte",tag=""},
 bibliocraft_jj_furniturepaneler={hasPattern=true,label="Eichenholz-Möbeleinrahmer",tag=""},
 bibliocraft_jj_furniturepaneler_jj_1={hasPattern=true,label="Fichtenholz-Möbeleinrahmer",tag=""},
 bibliocraft_jj_furniturepaneler_jj_2={hasPattern=true,label="Birkenholz-Möbeleinrahmer",tag=""},
 bibliocraft_jj_furniturepaneler_jj_3={hasPattern=true,label="Tropenholz-Möbeleinrahmer",tag=""},
 bibliocraft_jj_furniturepaneler_jj_4={hasPattern=true,label="Akazienholz-Möbeleinrahmer",tag=""},
 bibliocraft_jj_furniturepaneler_jj_5={hasPattern=true,label="Schwarzeichenholz-Möbeleinrahmer",tag=""},
 bibliocraft_jj_furniturepaneler_jj_6={hasPattern=true,label="Eingerahmter Möbeleinrahmer",tag=""},
 bibliocraft_jj_handdrill={hasPattern=true,label="Handbohrer",tag=""},
 bibliocraft_jj_label={hasPattern=true,label="Eichenholzschildchen",tag=""},
 bibliocraft_jj_label_jj_1={hasPattern=true,label="Fichtenholzschildchen",tag=""},
 bibliocraft_jj_label_jj_2={hasPattern=true,label="Birkenholzschildchen",tag=""},
 bibliocraft_jj_label_jj_3={hasPattern=true,label="Tropenholzschildchen",tag=""},
 bibliocraft_jj_label_jj_4={hasPattern=true,label="Akazienholzschildchen",tag=""},
 bibliocraft_jj_label_jj_5={hasPattern=true,label="Schwarzeichenholzschildchen",tag=""},
 bibliocraft_jj_label_jj_6={hasPattern=true,label="Eingerahmtes Schildchen",tag=""},
 bibliocraft_jj_lampgold={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampgold_jj_1={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampgold_jj_10={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampgold_jj_11={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampgold_jj_12={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampgold_jj_13={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampgold_jj_14={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampgold_jj_15={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampgold_jj_2={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampgold_jj_3={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampgold_jj_4={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampgold_jj_5={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampgold_jj_6={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampgold_jj_7={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampgold_jj_8={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampgold_jj_9={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampiron={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampiron_jj_1={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampiron_jj_10={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampiron_jj_11={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampiron_jj_12={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampiron_jj_13={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampiron_jj_14={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampiron_jj_15={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampiron_jj_2={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampiron_jj_3={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampiron_jj_4={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampiron_jj_5={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampiron_jj_6={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampiron_jj_7={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampiron_jj_8={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lampiron_jj_9={hasPattern=true,label="Schicke Lampe",tag=""},
 bibliocraft_jj_lanterngold={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterngold_jj_1={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterngold_jj_10={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterngold_jj_11={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterngold_jj_12={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterngold_jj_13={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterngold_jj_14={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterngold_jj_15={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterngold_jj_2={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterngold_jj_3={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterngold_jj_4={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterngold_jj_5={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterngold_jj_6={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterngold_jj_7={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterngold_jj_8={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterngold_jj_9={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterniron={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterniron_jj_1={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterniron_jj_10={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterniron_jj_11={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterniron_jj_12={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterniron_jj_13={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterniron_jj_14={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterniron_jj_15={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterniron_jj_2={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterniron_jj_3={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterniron_jj_4={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterniron_jj_5={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterniron_jj_6={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterniron_jj_7={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterniron_jj_8={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_lanterniron_jj_9={hasPattern=true,label="Schicke Laterne",tag=""},
 bibliocraft_jj_mapframe={hasPattern=true,label="Eichenholz-Kartenrahmen",tag=""},
 bibliocraft_jj_mapframe_jj_1={hasPattern=true,label="Fichtenholz-Kartenrahmen",tag=""},
 bibliocraft_jj_mapframe_jj_2={hasPattern=true,label="Birkenholz-Kartenrahmen",tag=""},
 bibliocraft_jj_mapframe_jj_3={hasPattern=true,label="Tropenholz-Kartenrahmen",tag=""},
 bibliocraft_jj_mapframe_jj_4={hasPattern=true,label="Akazienholz-Kartenrahmen",tag=""},
 bibliocraft_jj_mapframe_jj_5={hasPattern=true,label="Schwarzeichenholz-Kartenrahmen",tag=""},
 bibliocraft_jj_mapframe_jj_6={hasPattern=true,label="Eingerahmter Kartenrahmen",tag=""},
 bibliocraft_jj_maptool={hasPattern=true,label="Stechzirkel",tag=""},
 bibliocraft_jj_markerpole={hasPattern=false,label="",tag=""},
 bibliocraft_jj_paintingcanvas={hasPattern=true,label="Gemäldeleinwand",tag=""},
 bibliocraft_jj_paintingframeborderless={hasPattern=true,label="Eichenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframeborderless_jj_1={hasPattern=true,label="Fichtenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframeborderless_jj_2={hasPattern=true,label="Birkenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframeborderless_jj_3={hasPattern=true,label="Tropenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframeborderless_jj_4={hasPattern=true,label="Akazienholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframeborderless_jj_5={hasPattern=true,label="Schwarzeichenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframeborderless_jj_6={hasPattern=true,label="Eingerahmter Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframefancy={hasPattern=true,label="Eichenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframefancy_jj_1={hasPattern=true,label="Fichtenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframefancy_jj_2={hasPattern=true,label="Birkenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframefancy_jj_3={hasPattern=true,label="Tropenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframefancy_jj_4={hasPattern=true,label="Akazienholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframefancy_jj_5={hasPattern=true,label="Schwarzeichenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframefancy_jj_6={hasPattern=true,label="Eingerahmter Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframeflat={hasPattern=true,label="Eichenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframeflat_jj_1={hasPattern=true,label="Fichtenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframeflat_jj_2={hasPattern=true,label="Birkenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframeflat_jj_3={hasPattern=true,label="Tropenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframeflat_jj_4={hasPattern=true,label="Akazienholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframeflat_jj_5={hasPattern=true,label="Schwarzeichenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframeflat_jj_6={hasPattern=true,label="Eingerahmter Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframemiddle={hasPattern=true,label="Eichenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframemiddle_jj_1={hasPattern=true,label="Fichtenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframemiddle_jj_2={hasPattern=true,label="Birkenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframemiddle_jj_3={hasPattern=true,label="Tropenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframemiddle_jj_4={hasPattern=true,label="Akazienholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframemiddle_jj_5={hasPattern=true,label="Schwarzeichenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframemiddle_jj_6={hasPattern=true,label="Eingerahmter Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframesimple={hasPattern=true,label="Eichenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframesimple_jj_1={hasPattern=true,label="Fichtenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframesimple_jj_2={hasPattern=true,label="Birkenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframesimple_jj_3={hasPattern=true,label="Tropenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframesimple_jj_4={hasPattern=true,label="Akazienholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframesimple_jj_5={hasPattern=true,label="Schwarzeichenholz-Gemälderahmen",tag=""},
 bibliocraft_jj_paintingframesimple_jj_6={hasPattern=true,label="Eingerahmter Gemälderahmen",tag=""},
 bibliocraft_jj_paintingpress={hasPattern=true,label="Gemäldepresse",tag=""},
 bibliocraft_jj_plumbline={hasPattern=true,label="Lot",tag=""},
 bibliocraft_jj_potionshelf={hasPattern=true,label="Eichenholz-Trankregal",tag=""},
 bibliocraft_jj_potionshelf_jj_1={hasPattern=true,label="Fichtenholz-Trankregal",tag=""},
 bibliocraft_jj_potionshelf_jj_2={hasPattern=true,label="Birkenholz-Trankregal",tag=""},
 bibliocraft_jj_potionshelf_jj_3={hasPattern=true,label="Tropenholz-Trankregal",tag=""},
 bibliocraft_jj_potionshelf_jj_4={hasPattern=true,label="Akazienholz-Trankregal",tag=""},
 bibliocraft_jj_potionshelf_jj_5={hasPattern=true,label="Schwarzeichenholz-Trankregal",tag=""},
 bibliocraft_jj_potionshelf_jj_6={hasPattern=true,label="Eingerahmtes Trankregal",tag=""},
 bibliocraft_jj_printingpress={hasPattern=true,label="Druckpresse",tag=""},
 bibliocraft_jj_printplate={hasPattern=false,label="",tag=""},
 bibliocraft_jj_recipebook={hasPattern=false,label="",tag=""},
 bibliocraft_jj_seat={hasPattern=true,label="Eichenholzsitz",tag=""},
 bibliocraft_jj_seat_jj_1={hasPattern=true,label="Fichtenholzsitz",tag=""},
 bibliocraft_jj_seat_jj_2={hasPattern=true,label="Birkenholzsitz",tag=""},
 bibliocraft_jj_seat_jj_3={hasPattern=true,label="Tropenholzsitz",tag=""},
 bibliocraft_jj_seat_jj_4={hasPattern=true,label="Akazienholzsitz",tag=""},
 bibliocraft_jj_seat_jj_5={hasPattern=true,label="Schwarzeichenholzsitz",tag=""},
 bibliocraft_jj_seat_jj_6={hasPattern=true,label="Eingerahmter Sitz",tag=""},
 bibliocraft_jj_seatback1={hasPattern=true,label="Eichenholzsitzlehne",tag=""},
 bibliocraft_jj_seatback2={hasPattern=true,label="Eichenholzsitzlehne",tag=""},
 bibliocraft_jj_seatback3={hasPattern=true,label="Eichenholzsitzlehne",tag=""},
 bibliocraft_jj_seatback4={hasPattern=true,label="Eichenholzsitzlehne",tag=""},
 bibliocraft_jj_seatback5={hasPattern=true,label="Eichenholzsitzlehne",tag=""},
 bibliocraft_jj_shelf={hasPattern=true,label="Eichenholzregal",tag=""},
 bibliocraft_jj_shelf_jj_1={hasPattern=true,label="Fichtenholzregal",tag=""},
 bibliocraft_jj_shelf_jj_2={hasPattern=true,label="Birkenholzregal",tag=""},
 bibliocraft_jj_shelf_jj_3={hasPattern=true,label="Tropenholzregal",tag=""},
 bibliocraft_jj_shelf_jj_4={hasPattern=true,label="Akazienholzregal",tag=""},
 bibliocraft_jj_shelf_jj_5={hasPattern=true,label="Schwarzeichenholzregal",tag=""},
 bibliocraft_jj_shelf_jj_6={hasPattern=true,label="Eingerahmtes Regal",tag=""},
 bibliocraft_jj_slottedbook={hasPattern=false,label="",tag=""},
 bibliocraft_jj_stockroomcatalog={hasPattern=true,label="Lagerkatalog",tag=""},
 bibliocraft_jj_swordpedestal={hasPattern=true,label="Schwertsockel",tag=""},
 bibliocraft_jj_swordpedestal_jj_1={hasPattern=true,label="Schwertsockel",tag=""},
 bibliocraft_jj_swordpedestal_jj_10={hasPattern=true,label="Schwertsockel",tag=""},
 bibliocraft_jj_swordpedestal_jj_11={hasPattern=true,label="Schwertsockel",tag=""},
 bibliocraft_jj_swordpedestal_jj_12={hasPattern=true,label="Schwertsockel",tag=""},
 bibliocraft_jj_swordpedestal_jj_13={hasPattern=true,label="Schwertsockel",tag=""},
 bibliocraft_jj_swordpedestal_jj_14={hasPattern=true,label="Schwertsockel",tag=""},
 bibliocraft_jj_swordpedestal_jj_15={hasPattern=true,label="Schwertsockel",tag=""},
 bibliocraft_jj_swordpedestal_jj_2={hasPattern=true,label="Schwertsockel",tag=""},
 bibliocraft_jj_swordpedestal_jj_3={hasPattern=true,label="Schwertsockel",tag=""},
 bibliocraft_jj_swordpedestal_jj_4={hasPattern=true,label="Schwertsockel",tag=""},
 bibliocraft_jj_swordpedestal_jj_5={hasPattern=true,label="Schwertsockel",tag=""},
 bibliocraft_jj_swordpedestal_jj_6={hasPattern=true,label="Schwertsockel",tag=""},
 bibliocraft_jj_swordpedestal_jj_7={hasPattern=true,label="Schwertsockel",tag=""},
 bibliocraft_jj_swordpedestal_jj_8={hasPattern=true,label="Schwertsockel",tag=""},
 bibliocraft_jj_swordpedestal_jj_9={hasPattern=true,label="Schwertsockel",tag=""},
 bibliocraft_jj_table={hasPattern=true,label="Eichenholztisch",tag=""},
 bibliocraft_jj_table_jj_1={hasPattern=true,label="Fichtenholztisch",tag=""},
 bibliocraft_jj_table_jj_2={hasPattern=true,label="Birkenholztisch",tag=""},
 bibliocraft_jj_table_jj_3={hasPattern=true,label="Tropenholztisch",tag=""},
 bibliocraft_jj_table_jj_4={hasPattern=true,label="Akazienholztisch",tag=""},
 bibliocraft_jj_table_jj_5={hasPattern=true,label="Schwarzeichenholztisch",tag=""},
 bibliocraft_jj_table_jj_6={hasPattern=true,label="Eingerahmter Tisch",tag=""},
 bibliocraft_jj_tape={hasPattern=true,label="Maßbandrolle",tag=""},
 bibliocraft_jj_tapemeasure={hasPattern=true,label="Maßband",tag=""},
 bibliocraft_jj_testeritem={hasPattern=false,label="",tag=""},
 bibliocraft_jj_toolrack={hasPattern=true,label="Eichenholz-Werkzeugregal",tag=""},
 bibliocraft_jj_toolrack_jj_1={hasPattern=true,label="Fichtenholz-Werkzeugregal",tag=""},
 bibliocraft_jj_toolrack_jj_2={hasPattern=true,label="Birkenholz-Werkzeugregal",tag=""},
 bibliocraft_jj_toolrack_jj_3={hasPattern=true,label="Tropenholz-Werkzeugregal",tag=""},
 bibliocraft_jj_toolrack_jj_4={hasPattern=true,label="Akazienholz-Werkzeugregal",tag=""},
 bibliocraft_jj_toolrack_jj_5={hasPattern=true,label="Schwarzeichenholz-Werkzeugregal",tag=""},
 bibliocraft_jj_toolrack_jj_6={hasPattern=true,label="Eingerahmtes Werkzeugregal",tag=""},
 bibliocraft_jj_typesettingtable={hasPattern=true,label="Drucksetzer",tag=""},
 bibliocraft_jj_typewriter={hasPattern=true,label="Weiße Schreibmaschine",tag=""},
 bibliocraft_jj_typewriter_jj_1={hasPattern=true,label="Hellgraue Schreibmaschine",tag=""},
 bibliocraft_jj_typewriter_jj_10={hasPattern=true,label="Hellblaue Schreibmaschine",tag=""},
 bibliocraft_jj_typewriter_jj_11={hasPattern=true,label="Blaue Schreibmaschine",tag=""},
 bibliocraft_jj_typewriter_jj_12={hasPattern=true,label="Violette Schreibmaschine",tag=""},
 bibliocraft_jj_typewriter_jj_13={hasPattern=true,label="Magentafarbene Schreibmaschine",tag=""},
 bibliocraft_jj_typewriter_jj_14={hasPattern=true,label="Pinke Schreibmaschine",tag=""},
 bibliocraft_jj_typewriter_jj_15={hasPattern=true,label="Braune Schreibmaschine",tag=""},
 bibliocraft_jj_typewriter_jj_2={hasPattern=true,label="Graue Schreibmaschine",tag=""},
 bibliocraft_jj_typewriter_jj_3={hasPattern=true,label="Schwarze Schreibmaschine",tag=""},
 bibliocraft_jj_typewriter_jj_4={hasPattern=true,label="Rote Schreibmaschine",tag=""},
 bibliocraft_jj_typewriter_jj_5={hasPattern=true,label="Orange Schreibmaschine",tag=""},
 bibliocraft_jj_typewriter_jj_6={hasPattern=true,label="Gelbe Schreibmaschine",tag=""},
 bibliocraft_jj_typewriter_jj_7={hasPattern=true,label="Hellgrüne Schreibmaschine",tag=""},
 bibliocraft_jj_typewriter_jj_8={hasPattern=true,label="Grüne Schreibmaschine",tag=""},
 bibliocraft_jj_typewriter_jj_9={hasPattern=true,label="Türkise",tag=""},
 thaumcomp_jj_sealconnector={hasPattern=false,label="",tag=""},
 thaumcraft_jj_activator_rail={hasPattern=false,label="",tag=""},
 thaumcraft_jj_alembic={hasPattern=false,label="",tag=""},
 thaumcraft_jj_alumentum={hasPattern=false,label="",tag=""},
 thaumcraft_jj_amber={hasPattern=false,label="",tag=""},
 thaumcraft_jj_amber_block={hasPattern=false,label="",tag=""},
 thaumcraft_jj_amber_brick={hasPattern=false,label="",tag=""},
 thaumcraft_jj_amulet_vis={hasPattern=false,label="",tag=""},
 thaumcraft_jj_amulet_vis_jj_1={hasPattern=false,label="",tag=""},
 thaumcraft_jj_arcane_ear={hasPattern=false,label="",tag=""},
 thaumcraft_jj_arcane_ear_toggle={hasPattern=false,label="",tag=""},
 thaumcraft_jj_arcane_workbench={hasPattern=false,label="",tag=""},
 thaumcraft_jj_arcane_workbench_charger={hasPattern=false,label="",tag=""},
 thaumcraft_jj_banner_black={hasPattern=false,label="",tag=""},
 thaumcraft_jj_banner_blue={hasPattern=false,label="",tag=""},
 thaumcraft_jj_banner_brown={hasPattern=false,label="",tag=""},
 thaumcraft_jj_banner_crimson_cult={hasPattern=false,label="",tag=""},
 thaumcraft_jj_banner_cyan={hasPattern=false,label="",tag=""},
 thaumcraft_jj_banner_gray={hasPattern=false,label="",tag=""},
 thaumcraft_jj_banner_green={hasPattern=false,label="",tag=""},
 thaumcraft_jj_banner_lightblue={hasPattern=false,label="",tag=""},
 thaumcraft_jj_banner_lime={hasPattern=false,label="",tag=""},
 thaumcraft_jj_banner_magenta={hasPattern=false,label="",tag=""},
 thaumcraft_jj_banner_orange={hasPattern=false,label="",tag=""},
 thaumcraft_jj_banner_pink={hasPattern=false,label="",tag=""},
 thaumcraft_jj_banner_purple={hasPattern=false,label="",tag=""},
 thaumcraft_jj_banner_red={hasPattern=false,label="",tag=""},
 thaumcraft_jj_banner_silver={hasPattern=false,label="",tag=""},
 thaumcraft_jj_banner_white={hasPattern=false,label="",tag=""},
 thaumcraft_jj_banner_yellow={hasPattern=false,label="",tag=""},
 thaumcraft_jj_barrier={hasPattern=false,label="",tag=""},
 thaumcraft_jj_bath_salts={hasPattern=false,label="",tag=""},
 thaumcraft_jj_baubles={hasPattern=false,label="",tag=""},
 thaumcraft_jj_baubles_jj_1={hasPattern=false,label="",tag=""},
 thaumcraft_jj_baubles_jj_2={hasPattern=false,label="",tag=""},
 thaumcraft_jj_baubles_jj_3={hasPattern=false,label="",tag=""},
 thaumcraft_jj_baubles_jj_4={hasPattern=false,label="",tag=""},
 thaumcraft_jj_baubles_jj_5={hasPattern=false,label="",tag=""},
 thaumcraft_jj_baubles_jj_6={hasPattern=false,label="",tag=""},
 thaumcraft_jj_bellows={hasPattern=false,label="",tag=""},
 thaumcraft_jj_bottle_taint={hasPattern=false,label="",tag=""},
 thaumcraft_jj_brain={hasPattern=false,label="",tag=""},
 thaumcraft_jj_brain_box={hasPattern=false,label="",tag=""},
 thaumcraft_jj_candle_black={hasPattern=false,label="",tag=""},
 thaumcraft_jj_candle_blue={hasPattern=false,label="",tag=""},
 thaumcraft_jj_candle_brown={hasPattern=false,label="",tag=""},
 thaumcraft_jj_candle_cyan={hasPattern=false,label="",tag=""},
 thaumcraft_jj_candle_gray={hasPattern=false,label="",tag=""},
 thaumcraft_jj_candle_green={hasPattern=false,label="",tag=""},
 thaumcraft_jj_candle_lightblue={hasPattern=false,label="",tag=""},
 thaumcraft_jj_candle_lime={hasPattern=false,label="",tag=""},
 thaumcraft_jj_candle_magenta={hasPattern=false,label="",tag=""},
 thaumcraft_jj_candle_orange={hasPattern=false,label="",tag=""},
 thaumcraft_jj_candle_pink={hasPattern=false,label="",tag=""},
 thaumcraft_jj_candle_purple={hasPattern=false,label="",tag=""},
 thaumcraft_jj_candle_red={hasPattern=false,label="",tag=""},
 thaumcraft_jj_candle_silver={hasPattern=false,label="",tag=""},
 thaumcraft_jj_candle_white={hasPattern=false,label="",tag=""},
 thaumcraft_jj_candle_yellow={hasPattern=false,label="",tag=""},
 thaumcraft_jj_caster_basic={hasPattern=false,label="",tag=""},
 thaumcraft_jj_causality_collapser={hasPattern=false,label="",tag=""},
 thaumcraft_jj_celestial_notes={hasPattern=false,label="",tag=""},
 thaumcraft_jj_celestial_notes_jj_1={hasPattern=false,label="",tag=""},
 thaumcraft_jj_celestial_notes_jj_10={hasPattern=false,label="",tag=""},
 thaumcraft_jj_celestial_notes_jj_11={hasPattern=false,label="",tag=""},
 thaumcraft_jj_celestial_notes_jj_12={hasPattern=false,label="",tag=""},
 thaumcraft_jj_celestial_notes_jj_2={hasPattern=false,label="",tag=""},
 thaumcraft_jj_celestial_notes_jj_3={hasPattern=false,label="",tag=""},
 thaumcraft_jj_celestial_notes_jj_4={hasPattern=false,label="",tag=""},
 thaumcraft_jj_celestial_notes_jj_5={hasPattern=false,label="",tag=""},
 thaumcraft_jj_celestial_notes_jj_6={hasPattern=false,label="",tag=""},
 thaumcraft_jj_celestial_notes_jj_7={hasPattern=false,label="",tag=""},
 thaumcraft_jj_celestial_notes_jj_8={hasPattern=false,label="",tag=""},
 thaumcraft_jj_celestial_notes_jj_9={hasPattern=false,label="",tag=""},
 thaumcraft_jj_centrifuge={hasPattern=false,label="",tag=""},
 thaumcraft_jj_charm_undying={hasPattern=false,label="",tag=""},
 thaumcraft_jj_chunk={hasPattern=false,label="",tag=""},
 thaumcraft_jj_chunk_jj_1={hasPattern=false,label="",tag=""},
 thaumcraft_jj_chunk_jj_2={hasPattern=false,label="",tag=""},
 thaumcraft_jj_chunk_jj_3={hasPattern=false,label="",tag=""},
 thaumcraft_jj_chunk_jj_4={hasPattern=false,label="",tag=""},
 thaumcraft_jj_chunk_jj_5={hasPattern=false,label="",tag=""},
 thaumcraft_jj_cinderpearl={hasPattern=false,label="",tag=""},
 thaumcraft_jj_cloth_boots={hasPattern=false,label="",tag=""},
 thaumcraft_jj_cloth_chest={hasPattern=false,label="",tag=""},
 thaumcraft_jj_cloth_legs={hasPattern=false,label="",tag=""},
 thaumcraft_jj_cloud_ring={hasPattern=false,label="",tag=""},
 thaumcraft_jj_cluster={hasPattern=false,label="",tag=""},
 thaumcraft_jj_cluster_jj_1={hasPattern=false,label="",tag=""},
 thaumcraft_jj_cluster_jj_2={hasPattern=false,label="",tag=""},
 thaumcraft_jj_cluster_jj_3={hasPattern=false,label="",tag=""},
 thaumcraft_jj_cluster_jj_4={hasPattern=false,label="",tag=""},
 thaumcraft_jj_cluster_jj_5={hasPattern=false,label="",tag=""},
 thaumcraft_jj_cluster_jj_6={hasPattern=false,label="",tag=""},
 thaumcraft_jj_cluster_jj_7={hasPattern=false,label="",tag=""},
 thaumcraft_jj_condenser={hasPattern=false,label="",tag=""},
 thaumcraft_jj_condenser_lattice={hasPattern=false,label="",tag=""},
 thaumcraft_jj_condenser_lattice_dirty={hasPattern=false,label="",tag=""},
 thaumcraft_jj_creative_flux_sponge={hasPattern=false,label="",tag=""},
 thaumcraft_jj_crimson_blade={hasPattern=false,label="",tag=""},
 thaumcraft_jj_crimson_boots={hasPattern=false,label="",tag=""},
 thaumcraft_jj_crimson_plate_chest={hasPattern=false,label="",tag=""},
 thaumcraft_jj_crimson_plate_helm={hasPattern=false,label="",tag=""},
 thaumcraft_jj_crimson_plate_legs={hasPattern=false,label="",tag=""},
 thaumcraft_jj_crimson_praetor_chest={hasPattern=false,label="",tag=""},
 thaumcraft_jj_crimson_praetor_helm={hasPattern=false,label="",tag=""},
 thaumcraft_jj_crimson_praetor_legs={hasPattern=false,label="",tag=""},
 thaumcraft_jj_crimson_robe_chest={hasPattern=false,label="",tag=""},
 thaumcraft_jj_crimson_robe_helm={hasPattern=false,label="",tag=""},
 thaumcraft_jj_crimson_robe_legs={hasPattern=false,label="",tag=""},
 thaumcraft_jj_crucible={hasPattern=false,label="",tag=""},
 thaumcraft_jj_crystal_aer={hasPattern=false,label="",tag=""},
 thaumcraft_jj_crystal_aqua={hasPattern=false,label="",tag=""},
 thaumcraft_jj_crystal_essence_b_37={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= aer}]})"},
 thaumcraft_jj_crystal_essence_b_38={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= alienis}]})"},
 thaumcraft_jj_crystal_essence_b_39={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= alkimia}]})"},
 thaumcraft_jj_crystal_essence_b_40={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= aqua}]})"},
 thaumcraft_jj_crystal_essence_b_41={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= auram}]})"},
 thaumcraft_jj_crystal_essence_b_42={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= aversio}]})"},
 thaumcraft_jj_crystal_essence_b_43={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= bestia}]})"},
 thaumcraft_jj_crystal_essence_b_44={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= cognitio}]})"},
 thaumcraft_jj_crystal_essence_b_45={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= desiderium}]})"},
 thaumcraft_jj_crystal_essence_b_46={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= exanimis}]})"},
 thaumcraft_jj_crystal_essence_b_47={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= fabrico}]})"},
 thaumcraft_jj_crystal_essence_b_48={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= gelum}]})"},
 thaumcraft_jj_crystal_essence_b_49={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= herba}]})"},
 thaumcraft_jj_crystal_essence_b_50={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= humanus}]})"},
 thaumcraft_jj_crystal_essence_b_51={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= ignis}]})"},
 thaumcraft_jj_crystal_essence_b_52={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= instrumentum}]})"},
 thaumcraft_jj_crystal_essence_b_53={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= lux}]})"},
 thaumcraft_jj_crystal_essence_b_54={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= machina}]})"},
 thaumcraft_jj_crystal_essence_b_55={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= metallum}]})"},
 thaumcraft_jj_crystal_essence_b_56={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= mortuus}]})"},
 thaumcraft_jj_crystal_essence_b_57={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= motus}]})"},
 thaumcraft_jj_crystal_essence_b_58={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= ordo}]})"},
 thaumcraft_jj_crystal_essence_b_59={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= perditio}]})"},
 thaumcraft_jj_crystal_essence_b_60={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= permutatio}]})"},
 thaumcraft_jj_crystal_essence_b_61={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= potentia}]})"},
 thaumcraft_jj_crystal_essence_b_62={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= praecantatio}]})"},
 thaumcraft_jj_crystal_essence_b_63={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= praemunio}]})"},
 thaumcraft_jj_crystal_essence_b_64={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= sensus}]})"},
 thaumcraft_jj_crystal_essence_b_65={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= spiritus}]})"},
 thaumcraft_jj_crystal_essence_b_66={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= tenebrae}]})"},
 thaumcraft_jj_crystal_essence_b_67={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= terra}]})"},
 thaumcraft_jj_crystal_essence_b_68={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= vacuos}]})"},
 thaumcraft_jj_crystal_essence_b_69={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= victus}]})"},
 thaumcraft_jj_crystal_essence_b_70={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= vinculum}]})"},
 thaumcraft_jj_crystal_essence_b_71={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= vitium}]})"},
 thaumcraft_jj_crystal_essence_b_72={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= vitreus}]})"},
 thaumcraft_jj_crystal_essence_b_73={hasPattern=false,label="",tag="({Aspects= [{amount= 1, key= volatus}]})"},
 thaumcraft_jj_crystal_ignis={hasPattern=false,label="",tag=""},
 thaumcraft_jj_crystal_ordo={hasPattern=false,label="",tag=""},
 thaumcraft_jj_crystal_perditio={hasPattern=false,label="",tag=""},
 thaumcraft_jj_crystal_terra={hasPattern=false,label="",tag=""},
 thaumcraft_jj_crystal_vitium={hasPattern=false,label="",tag=""},
 thaumcraft_jj_curio={hasPattern=false,label="",tag=""},
 thaumcraft_jj_curio_jj_1={hasPattern=false,label="",tag=""},
 thaumcraft_jj_curio_jj_2={hasPattern=false,label="",tag=""},
 thaumcraft_jj_curio_jj_3={hasPattern=false,label="",tag=""},
 thaumcraft_jj_curio_jj_4={hasPattern=false,label="",tag=""},
 thaumcraft_jj_curio_jj_5={hasPattern=false,label="",tag=""},
 thaumcraft_jj_curio_jj_6={hasPattern=false,label="",tag=""},
 thaumcraft_jj_curiosity_band={hasPattern=false,label="",tag=""},
 thaumcraft_jj_dioptra={hasPattern=false,label="",tag=""},
 thaumcraft_jj_effect_glimmer={hasPattern=false,label="",tag=""},
 thaumcraft_jj_effect_sap={hasPattern=false,label="",tag=""},
 thaumcraft_jj_effect_shock={hasPattern=false,label="",tag=""},
 thaumcraft_jj_elemental_axe_b_1={hasPattern=false,label="",tag="({infench= [{lvl= 1 as short, id= 2 as short}, {lvl= 1 as short, id= 0 as short}]})"},
 thaumcraft_jj_elemental_hoe={hasPattern=false,label="",tag=""},
 thaumcraft_jj_elemental_pick_b_1={hasPattern=false,label="",tag="({infench= [{lvl= 1 as short, id= 4 as short}, {lvl= 2 as short, id= 3 as short}]})"},
 thaumcraft_jj_elemental_shovel_b_1={hasPattern=false,label="",tag="({infench= [{lvl= 1 as short, id= 1 as short}]})"},
 thaumcraft_jj_elemental_sword_b_1={hasPattern=false,label="",tag="({infench= [{lvl= 2 as short, id= 5 as short}]})"},
 thaumcraft_jj_empty={hasPattern=false,label="",tag=""},
 thaumcraft_jj_enchanted_placeholder={hasPattern=false,label="",tag=""},
 thaumcraft_jj_essentia_input={hasPattern=false,label="",tag=""},
 thaumcraft_jj_essentia_output={hasPattern=false,label="",tag=""},
 thaumcraft_jj_everfull_urn={hasPattern=false,label="",tag=""},
 thaumcraft_jj_fabric={hasPattern=false,label="",tag=""},
 thaumcraft_jj_filter={hasPattern=false,label="",tag=""},
 thaumcraft_jj_flesh_block={hasPattern=false,label="",tag=""},
 thaumcraft_jj_focus_1={hasPattern=false,label="",tag=""},
 thaumcraft_jj_focus_2={hasPattern=false,label="",tag=""},
 thaumcraft_jj_focus_3={hasPattern=false,label="",tag=""},
 thaumcraft_jj_focus_pouch={hasPattern=false,label="",tag=""},
 thaumcraft_jj_fortress_chest={hasPattern=false,label="",tag=""},
 thaumcraft_jj_fortress_helm={hasPattern=false,label="",tag=""},
 thaumcraft_jj_fortress_legs={hasPattern=false,label="",tag=""},
 thaumcraft_jj_goggles={hasPattern=false,label="",tag=""},
 thaumcraft_jj_golem_b_4={hasPattern=false,label="",tag="({props= 0 as long})"},
 thaumcraft_jj_golem_b_5={hasPattern=false,label="",tag="({props= 282574488338432 as long})"},
 thaumcraft_jj_golem_b_6={hasPattern=false,label="",tag="({props= 288515149663305728 as long})"},
 thaumcraft_jj_golem_b_7={hasPattern=false,label="",tag="({props= 72341268037894144 as long})"},
 thaumcraft_jj_golem_bell={hasPattern=false,label="",tag=""},
 thaumcraft_jj_golem_builder={hasPattern=false,label="",tag=""},
 thaumcraft_jj_grapple_gun={hasPattern=false,label="",tag=""},
 thaumcraft_jj_grapple_gun_spool={hasPattern=false,label="",tag=""},
 thaumcraft_jj_grapple_gun_tip={hasPattern=false,label="",tag=""},
 thaumcraft_jj_grass_ambient={hasPattern=false,label="",tag=""},
 thaumcraft_jj_hand_mirror={hasPattern=false,label="",tag=""},
 thaumcraft_jj_hole={hasPattern=false,label="",tag=""},
 thaumcraft_jj_hungry_chest={hasPattern=false,label="",tag=""},
 thaumcraft_jj_infernal_furnace={hasPattern=false,label="",tag=""},
 thaumcraft_jj_infusion_matrix={hasPattern=false,label="",tag=""},
 thaumcraft_jj_ingot={hasPattern=false,label="",tag=""},
 thaumcraft_jj_ingot_jj_1={hasPattern=false,label="",tag=""},
 thaumcraft_jj_ingot_jj_2={hasPattern=false,label="",tag=""},
 thaumcraft_jj_inlay={hasPattern=false,label="",tag=""},
 thaumcraft_jj_jar_brace={hasPattern=false,label="",tag=""},
 thaumcraft_jj_jar_brain={hasPattern=false,label="",tag=""},
 thaumcraft_jj_jar_normal={hasPattern=false,label="",tag=""},
 thaumcraft_jj_jar_void={hasPattern=false,label="",tag=""},
 thaumcraft_jj_label={hasPattern=false,label="",tag=""},
 thaumcraft_jj_lamp_arcane={hasPattern=false,label="",tag=""},
 thaumcraft_jj_lamp_fertility={hasPattern=false,label="",tag=""},
 thaumcraft_jj_lamp_growth={hasPattern=false,label="",tag=""},
 thaumcraft_jj_leaves_greatwood={hasPattern=false,label="",tag=""},
 thaumcraft_jj_leaves_silverwood={hasPattern=false,label="",tag=""},
 thaumcraft_jj_levitator={hasPattern=false,label="",tag=""},
 thaumcraft_jj_log_greatwood={hasPattern=false,label="",tag=""},
 thaumcraft_jj_log_silverwood={hasPattern=false,label="",tag=""},
 thaumcraft_jj_loot_bag={hasPattern=false,label="",tag=""},
 thaumcraft_jj_loot_bag_jj_1={hasPattern=false,label="",tag=""},
 thaumcraft_jj_loot_bag_jj_2={hasPattern=false,label="",tag=""},
 thaumcraft_jj_loot_crate_common={hasPattern=false,label="",tag=""},
 thaumcraft_jj_loot_crate_rare={hasPattern=false,label="",tag=""},
 thaumcraft_jj_loot_crate_uncommon={hasPattern=false,label="",tag=""},
 thaumcraft_jj_loot_urn_common={hasPattern=false,label="",tag=""},
 thaumcraft_jj_loot_urn_rare={hasPattern=false,label="",tag=""},
 thaumcraft_jj_loot_urn_uncommon={hasPattern=false,label="",tag=""},
 thaumcraft_jj_matrix_cost={hasPattern=false,label="",tag=""},
 thaumcraft_jj_matrix_speed={hasPattern=false,label="",tag=""},
 thaumcraft_jj_mechanism_complex={hasPattern=false,label="",tag=""},
 thaumcraft_jj_mechanism_simple={hasPattern=false,label="",tag=""},
 thaumcraft_jj_metal_alchemical={hasPattern=false,label="",tag=""},
 thaumcraft_jj_metal_alchemical_advanced={hasPattern=false,label="",tag=""},
 thaumcraft_jj_metal_brass={hasPattern=false,label="",tag=""},
 thaumcraft_jj_metal_thaumium={hasPattern=false,label="",tag=""},
 thaumcraft_jj_metal_void={hasPattern=false,label="",tag=""},
 thaumcraft_jj_mind={hasPattern=false,label="",tag=""},
 thaumcraft_jj_mind_jj_1={hasPattern=false,label="",tag=""},
 thaumcraft_jj_mirror={hasPattern=false,label="",tag=""},
 thaumcraft_jj_mirror_essentia={hasPattern=false,label="",tag=""},
 thaumcraft_jj_mirrored_glass={hasPattern=false,label="",tag=""},
 thaumcraft_jj_module={hasPattern=false,label="",tag=""},
 thaumcraft_jj_module_jj_1={hasPattern=false,label="",tag=""},
 thaumcraft_jj_morphic_resonator={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nitor_black={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nitor_blue={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nitor_brown={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nitor_cyan={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nitor_gray={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nitor_green={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nitor_lightblue={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nitor_lime={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nitor_magenta={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nitor_orange={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nitor_pink={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nitor_purple={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nitor_red={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nitor_silver={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nitor_white={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nitor_yellow={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nugget={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nugget_jj_1={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nugget_jj_10={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nugget_jj_2={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nugget_jj_3={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nugget_jj_4={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nugget_jj_5={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nugget_jj_6={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nugget_jj_7={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nugget_jj_8={hasPattern=false,label="",tag=""},
 thaumcraft_jj_nugget_jj_9={hasPattern=false,label="",tag=""},
 thaumcraft_jj_ore_amber={hasPattern=false,label="",tag=""},
 thaumcraft_jj_ore_cinnabar={hasPattern=false,label="",tag=""},
 thaumcraft_jj_ore_quartz={hasPattern=false,label="",tag=""},
 thaumcraft_jj_pattern_crafter={hasPattern=false,label="",tag=""},
 thaumcraft_jj_paving_stone_barrier={hasPattern=false,label="",tag=""},
 thaumcraft_jj_paving_stone_travel={hasPattern=false,label="",tag=""},
 thaumcraft_jj_pech_wand={hasPattern=false,label="",tag=""},
 thaumcraft_jj_pedestal_ancient={hasPattern=false,label="",tag=""},
 thaumcraft_jj_pedestal_arcane={hasPattern=false,label="",tag=""},
 thaumcraft_jj_pedestal_eldritch={hasPattern=false,label="",tag=""},
 thaumcraft_jj_phial={hasPattern=false,label="",tag=""},
 thaumcraft_jj_phial_jj_1_b_37={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= aer}]})"},
 thaumcraft_jj_phial_jj_1_b_38={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= alienis}]})"},
 thaumcraft_jj_phial_jj_1_b_39={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= alkimia}]})"},
 thaumcraft_jj_phial_jj_1_b_40={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= aqua}]})"},
 thaumcraft_jj_phial_jj_1_b_41={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= auram}]})"},
 thaumcraft_jj_phial_jj_1_b_42={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= aversio}]})"},
 thaumcraft_jj_phial_jj_1_b_43={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= bestia}]})"},
 thaumcraft_jj_phial_jj_1_b_44={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= cognitio}]})"},
 thaumcraft_jj_phial_jj_1_b_45={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= desiderium}]})"},
 thaumcraft_jj_phial_jj_1_b_46={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= exanimis}]})"},
 thaumcraft_jj_phial_jj_1_b_47={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= fabrico}]})"},
 thaumcraft_jj_phial_jj_1_b_48={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= gelum}]})"},
 thaumcraft_jj_phial_jj_1_b_49={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= herba}]})"},
 thaumcraft_jj_phial_jj_1_b_50={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= humanus}]})"},
 thaumcraft_jj_phial_jj_1_b_51={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= ignis}]})"},
 thaumcraft_jj_phial_jj_1_b_52={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= instrumentum}]})"},
 thaumcraft_jj_phial_jj_1_b_53={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= lux}]})"},
 thaumcraft_jj_phial_jj_1_b_54={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= machina}]})"},
 thaumcraft_jj_phial_jj_1_b_55={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= metallum}]})"},
 thaumcraft_jj_phial_jj_1_b_56={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= mortuus}]})"},
 thaumcraft_jj_phial_jj_1_b_57={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= motus}]})"},
 thaumcraft_jj_phial_jj_1_b_58={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= ordo}]})"},
 thaumcraft_jj_phial_jj_1_b_59={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= perditio}]})"},
 thaumcraft_jj_phial_jj_1_b_60={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= permutatio}]})"},
 thaumcraft_jj_phial_jj_1_b_61={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= potentia}]})"},
 thaumcraft_jj_phial_jj_1_b_62={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= praecantatio}]})"},
 thaumcraft_jj_phial_jj_1_b_63={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= praemunio}]})"},
 thaumcraft_jj_phial_jj_1_b_64={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= sensus}]})"},
 thaumcraft_jj_phial_jj_1_b_65={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= spiritus}]})"},
 thaumcraft_jj_phial_jj_1_b_66={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= tenebrae}]})"},
 thaumcraft_jj_phial_jj_1_b_67={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= terra}]})"},
 thaumcraft_jj_phial_jj_1_b_68={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= vacuos}]})"},
 thaumcraft_jj_phial_jj_1_b_69={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= victus}]})"},
 thaumcraft_jj_phial_jj_1_b_70={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= vinculum}]})"},
 thaumcraft_jj_phial_jj_1_b_71={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= vitium}]})"},
 thaumcraft_jj_phial_jj_1_b_72={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= vitreus}]})"},
 thaumcraft_jj_phial_jj_1_b_73={hasPattern=false,label="",tag="({Aspects= [{amount= 10, key= volatus}]})"},
 thaumcraft_jj_pillar_ancient={hasPattern=false,label="",tag=""},
 thaumcraft_jj_pillar_arcane={hasPattern=false,label="",tag=""},
 thaumcraft_jj_pillar_eldritch={hasPattern=false,label="",tag=""},
 thaumcraft_jj_placeholder_anvil={hasPattern=false,label="",tag=""},
 thaumcraft_jj_placeholder_bars={hasPattern=false,label="",tag=""},
 thaumcraft_jj_placeholder_brick={hasPattern=false,label="",tag=""},
 thaumcraft_jj_placeholder_cauldron={hasPattern=false,label="",tag=""},
 thaumcraft_jj_placeholder_obsidian={hasPattern=false,label="",tag=""},
 thaumcraft_jj_placeholder_table={hasPattern=false,label="",tag=""},
 thaumcraft_jj_plank_greatwood={hasPattern=false,label="",tag=""},
 thaumcraft_jj_plank_silverwood={hasPattern=false,label="",tag=""},
 thaumcraft_jj_plate={hasPattern=false,label="",tag=""},
 thaumcraft_jj_plate_jj_1={hasPattern=false,label="",tag=""},
 thaumcraft_jj_plate_jj_2={hasPattern=false,label="",tag=""},
 thaumcraft_jj_plate_jj_3={hasPattern=false,label="",tag=""},
 thaumcraft_jj_potion_sprayer={hasPattern=false,label="",tag=""},
 thaumcraft_jj_primal_crusher_b_1={hasPattern=false,label="",tag="({infench= [{lvl= 1 as short, id= 1 as short}, {lvl= 1 as short, id= 4 as short}]})"},
 thaumcraft_jj_primordial_pearl={hasPattern=false,label="",tag=""},
 thaumcraft_jj_quicksilver={hasPattern=false,label="",tag=""},
 thaumcraft_jj_recharge_pedestal={hasPattern=false,label="",tag=""},
 thaumcraft_jj_redstone_relay={hasPattern=false,label="",tag=""},
 thaumcraft_jj_research_table={hasPattern=false,label="",tag=""},
 thaumcraft_jj_resonator={hasPattern=false,label="",tag=""},
 thaumcraft_jj_salis_mundus={hasPattern=false,label="",tag=""},
 thaumcraft_jj_sanity_checker={hasPattern=false,label="",tag=""},
 thaumcraft_jj_sanity_soap={hasPattern=false,label="",tag=""},
 thaumcraft_jj_sapling_greatwood={hasPattern=false,label="",tag=""},
 thaumcraft_jj_sapling_silverwood={hasPattern=false,label="",tag=""},
 thaumcraft_jj_scribing_tools={hasPattern=false,label="",tag=""},
 thaumcraft_jj_seal={hasPattern=false,label="",tag=""},
 thaumcraft_jj_seal_jj_1={hasPattern=false,label="",tag=""},
 thaumcraft_jj_seal_jj_10={hasPattern=false,label="",tag=""},
 thaumcraft_jj_seal_jj_11={hasPattern=false,label="",tag=""},
 thaumcraft_jj_seal_jj_12={hasPattern=false,label="",tag=""},
 thaumcraft_jj_seal_jj_13={hasPattern=false,label="",tag=""},
 thaumcraft_jj_seal_jj_14={hasPattern=false,label="",tag=""},
 thaumcraft_jj_seal_jj_15={hasPattern=false,label="",tag=""},
 thaumcraft_jj_seal_jj_16={hasPattern=false,label="",tag=""},
 thaumcraft_jj_seal_jj_2={hasPattern=false,label="",tag=""},
 thaumcraft_jj_seal_jj_3={hasPattern=false,label="",tag=""},
 thaumcraft_jj_seal_jj_4={hasPattern=false,label="",tag=""},
 thaumcraft_jj_seal_jj_5={hasPattern=false,label="",tag=""},
 thaumcraft_jj_seal_jj_6={hasPattern=false,label="",tag=""},
 thaumcraft_jj_seal_jj_7={hasPattern=false,label="",tag=""},
 thaumcraft_jj_seal_jj_8={hasPattern=false,label="",tag=""},
 thaumcraft_jj_seal_jj_9={hasPattern=false,label="",tag=""},
 thaumcraft_jj_shimmerleaf={hasPattern=false,label="",tag=""},
 thaumcraft_jj_slab_ancient={hasPattern=false,label="",tag=""},
 thaumcraft_jj_slab_arcane_brick={hasPattern=false,label="",tag=""},
 thaumcraft_jj_slab_arcane_stone={hasPattern=false,label="",tag=""},
 thaumcraft_jj_slab_eldritch={hasPattern=false,label="",tag=""},
 thaumcraft_jj_slab_greatwood={hasPattern=false,label="",tag=""},
 thaumcraft_jj_slab_silverwood={hasPattern=false,label="",tag=""},
 thaumcraft_jj_smelter_aux={hasPattern=false,label="",tag=""},
 thaumcraft_jj_smelter_basic={hasPattern=false,label="",tag=""},
 thaumcraft_jj_smelter_thaumium={hasPattern=false,label="",tag=""},
 thaumcraft_jj_smelter_vent={hasPattern=false,label="",tag=""},
 thaumcraft_jj_smelter_void={hasPattern=false,label="",tag=""},
 thaumcraft_jj_spa={hasPattern=false,label="",tag=""},
 thaumcraft_jj_stabilizer={hasPattern=false,label="",tag=""},
 thaumcraft_jj_stairs_ancient={hasPattern=false,label="",tag=""},
 thaumcraft_jj_stairs_arcane={hasPattern=false,label="",tag=""},
 thaumcraft_jj_stairs_arcane_brick={hasPattern=false,label="",tag=""},
 thaumcraft_jj_stairs_greatwood={hasPattern=false,label="",tag=""},
 thaumcraft_jj_stairs_silverwood={hasPattern=false,label="",tag=""},
 thaumcraft_jj_stone_ancient={hasPattern=false,label="",tag=""},
 thaumcraft_jj_stone_ancient_doorway={hasPattern=false,label="",tag=""},
 thaumcraft_jj_stone_ancient_glyphed={hasPattern=false,label="",tag=""},
 thaumcraft_jj_stone_ancient_rock={hasPattern=false,label="",tag=""},
 thaumcraft_jj_stone_ancient_tile={hasPattern=false,label="",tag=""},
 thaumcraft_jj_stone_arcane={hasPattern=false,label="",tag=""},
 thaumcraft_jj_stone_arcane_brick={hasPattern=false,label="",tag=""},
 thaumcraft_jj_stone_eldritch_tile={hasPattern=false,label="",tag=""},
 thaumcraft_jj_stone_porous={hasPattern=false,label="",tag=""},
 thaumcraft_jj_table_stone={hasPattern=false,label="",tag=""},
 thaumcraft_jj_table_wood={hasPattern=false,label="",tag=""},
 thaumcraft_jj_taint_crust={hasPattern=false,label="",tag=""},
 thaumcraft_jj_taint_feature={hasPattern=false,label="",tag=""},
 thaumcraft_jj_taint_fibre={hasPattern=false,label="",tag=""},
 thaumcraft_jj_taint_geyser={hasPattern=false,label="",tag=""},
 thaumcraft_jj_taint_log={hasPattern=false,label="",tag=""},
 thaumcraft_jj_taint_rock={hasPattern=false,label="",tag=""},
 thaumcraft_jj_taint_soil={hasPattern=false,label="",tag=""},
 thaumcraft_jj_tallow={hasPattern=false,label="",tag=""},
 thaumcraft_jj_thaumatorium={hasPattern=false,label="",tag=""},
 thaumcraft_jj_thaumatorium_top={hasPattern=false,label="",tag=""},
 thaumcraft_jj_thaumium_axe={hasPattern=false,label="",tag=""},
 thaumcraft_jj_thaumium_boots={hasPattern=false,label="",tag=""},
 thaumcraft_jj_thaumium_chest={hasPattern=false,label="",tag=""},
 thaumcraft_jj_thaumium_helm={hasPattern=false,label="",tag=""},
 thaumcraft_jj_thaumium_hoe={hasPattern=false,label="",tag=""},
 thaumcraft_jj_thaumium_legs={hasPattern=false,label="",tag=""},
 thaumcraft_jj_thaumium_pick={hasPattern=false,label="",tag=""},
 thaumcraft_jj_thaumium_shovel={hasPattern=false,label="",tag=""},
 thaumcraft_jj_thaumium_sword={hasPattern=false,label="",tag=""},
 thaumcraft_jj_thaumometer={hasPattern=false,label="",tag=""},
 thaumcraft_jj_thaumonomicon={hasPattern=false,label="",tag=""},
 thaumcraft_jj_traveller_boots={hasPattern=false,label="",tag=""},
 thaumcraft_jj_triple_meat_treat={hasPattern=false,label="",tag=""},
 thaumcraft_jj_tube={hasPattern=false,label="",tag=""},
 thaumcraft_jj_tube_buffer={hasPattern=false,label="",tag=""},
 thaumcraft_jj_tube_filter={hasPattern=false,label="",tag=""},
 thaumcraft_jj_tube_oneway={hasPattern=false,label="",tag=""},
 thaumcraft_jj_tube_restrict={hasPattern=false,label="",tag=""},
 thaumcraft_jj_tube_valve={hasPattern=false,label="",tag=""},
 thaumcraft_jj_turret={hasPattern=false,label="",tag=""},
 thaumcraft_jj_turret_jj_1={hasPattern=false,label="",tag=""},
 thaumcraft_jj_turret_jj_2={hasPattern=false,label="",tag=""},
 thaumcraft_jj_verdant_charm={hasPattern=false,label="",tag=""},
 thaumcraft_jj_verdant_charm_b_3={hasPattern=false,label="",tag="({type= 1 as byte})"},
 thaumcraft_jj_verdant_charm_b_4={hasPattern=false,label="",tag="({type= 2 as byte})"},
 thaumcraft_jj_vis_battery={hasPattern=false,label="",tag=""},
 thaumcraft_jj_vis_generator={hasPattern=false,label="",tag=""},
 thaumcraft_jj_vis_resonator={hasPattern=false,label="",tag=""},
 thaumcraft_jj_vishroom={hasPattern=false,label="",tag=""},
 thaumcraft_jj_void_axe={hasPattern=false,label="",tag=""},
 thaumcraft_jj_void_boots={hasPattern=false,label="",tag=""},
 thaumcraft_jj_void_chest={hasPattern=false,label="",tag=""},
 thaumcraft_jj_void_helm={hasPattern=false,label="",tag=""},
 thaumcraft_jj_void_hoe={hasPattern=false,label="",tag=""},
 thaumcraft_jj_void_legs={hasPattern=false,label="",tag=""},
 thaumcraft_jj_void_pick={hasPattern=false,label="",tag=""},
 thaumcraft_jj_void_robe_chest={hasPattern=false,label="",tag=""},
 thaumcraft_jj_void_robe_helm={hasPattern=false,label="",tag=""},
 thaumcraft_jj_void_robe_legs={hasPattern=false,label="",tag=""},
 thaumcraft_jj_void_seed={hasPattern=false,label="",tag=""},
 thaumcraft_jj_void_shovel={hasPattern=false,label="",tag=""},
 thaumcraft_jj_void_siphon={hasPattern=false,label="",tag=""},
 thaumcraft_jj_void_sword={hasPattern=false,label="",tag=""},
 thaumcraft_jj_voidseer_charm={hasPattern=false,label="",tag=""},
 thaumcraft_jj_wand_workbench={hasPattern=false,label="",tag=""}
 }