return {
 botania_jj_alchemycatalyst={hasPattern=true,label="Alchemiekatalysator",tag={}},
 botania_jj_alfheimportal={hasPattern=true,label="Weltenbaumextrakt",tag={}},
 botania_jj_altar={hasPattern=true,label="Petal Apothecary",tag={}},
 botania_jj_altar_jj_1={hasPattern=true,label="Forest Petal Apothecary",tag={}},
 botania_jj_altar_jj_2={hasPattern=true,label="Plains Petal Apothecary",tag={}},
 botania_jj_altar_jj_3={hasPattern=true,label="Mountain Petal Apothecary",tag={}},
 botania_jj_altar_jj_4={hasPattern=true,label="Fungal Petal Apothecary",tag={}},
 botania_jj_altar_jj_5={hasPattern=true,label="Swamp Petal Apothecary",tag={}},
 botania_jj_altar_jj_6={hasPattern=true,label="Desert Petal Apothecary",tag={}},
 botania_jj_altar_jj_7={hasPattern=true,label="Taiga Petal Apothecary",tag={}},
 botania_jj_altar_jj_8={hasPattern=true,label="Mesa Petal Apothecary",tag={}},
 botania_jj_altgrass={hasPattern=false,label="",tag={}},
 botania_jj_altgrass_jj_1={hasPattern=false,label="",tag={}},
 botania_jj_altgrass_jj_2={hasPattern=false,label="",tag={}},
 botania_jj_altgrass_jj_3={hasPattern=false,label="",tag={}},
 botania_jj_altgrass_jj_4={hasPattern=false,label="",tag={}},
 botania_jj_altgrass_jj_5={hasPattern=false,label="",tag={}},
 botania_jj_ancientwill={hasPattern=false,label="",tag={}},
 botania_jj_ancientwill_jj_1={hasPattern=false,label="",tag={}},
 botania_jj_ancientwill_jj_2={hasPattern=false,label="",tag={}},
 botania_jj_ancientwill_jj_3={hasPattern=false,label="",tag={}},
 botania_jj_ancientwill_jj_4={hasPattern=false,label="",tag={}},
 botania_jj_ancientwill_jj_5={hasPattern=false,label="",tag={}},
 botania_jj_animatedtorch={hasPattern=true,label="Animated Torch",tag={}},
 botania_jj_astrolabe={hasPattern=true,label="Worldshaper's Astrolabe",tag={}},
 botania_jj_auraring={hasPattern=true,label="Auraband",tag={}},
 botania_jj_auraringgreater={hasPattern=true,label="Besseres Auraband",tag={}},
 botania_jj_autocraftinghalo={hasPattern=true,label="Manufactory Halo",tag={}},
 botania_jj_avatar={hasPattern=true,label="Livingwood Avatar",tag={}},
 botania_jj_balancecloak={hasPattern=true,label="Cloak of Balance",tag={}},
 botania_jj_baublebox={hasPattern=true,label="Bauble Case",tag={}},
 botania_jj_bellows={hasPattern=true,label="Manatide Bellows",tag={}},
 botania_jj_bifrost={hasPattern=false,label="",tag={}},
 botania_jj_bifrostperm={hasPattern=true,label="Bifrost Block",tag={}},
 botania_jj_bifrostpermpane={hasPattern=true,label="Bifrost Pane",tag={}},
 botania_jj_biomestonea={hasPattern=false,label="",tag={}},
 botania_jj_biomestonea0slab={hasPattern=true,label="Metamorphic Forest Stone Slab",tag={}},
 botania_jj_biomestonea0stairs={hasPattern=true,label="Metamorphic Forest Stone Stairs",tag={}},
 botania_jj_biomestonea0wall={hasPattern=true,label="Metamorphic Forest Cobblestone Wall",tag={}},
 botania_jj_biomestonea0wall_jj_1={hasPattern=true,label="Metamorphic Plains Cobblestone Wall",tag={}},
 botania_jj_biomestonea0wall_jj_2={hasPattern=true,label="Metamorphic Mountain Cobblestone Wall",tag={}},
 botania_jj_biomestonea0wall_jj_3={hasPattern=true,label="Metamorphic Fungal Cobblestone Wall",tag={}},
 botania_jj_biomestonea0wall_jj_4={hasPattern=true,label="Metamorphic Swamp Cobblestone Wall",tag={}},
 botania_jj_biomestonea0wall_jj_5={hasPattern=true,label="Metamorphic Desert Cobblestone Wall",tag={}},
 botania_jj_biomestonea0wall_jj_6={hasPattern=true,label="Metamorphic Taiga Cobblestone Wall",tag={}},
 botania_jj_biomestonea0wall_jj_7={hasPattern=true,label="Metamorphic Mesa Cobblestone Wall",tag={}},
 botania_jj_biomestonea10slab={hasPattern=true,label="Metamorphic Mountain Cobblestone Slab",tag={}},
 botania_jj_biomestonea10stairs={hasPattern=true,label="Metamorphic Mountain Cobblestone Stairs",tag={}},
 botania_jj_biomestonea11slab={hasPattern=true,label="Metamorphic Fungal Cobblestone Slab",tag={}},
 botania_jj_biomestonea11stairs={hasPattern=true,label="Metamorphic Fungal Cobblestone Stairs",tag={}},
 botania_jj_biomestonea12slab={hasPattern=true,label="Metamorphic Swamp Cobblestone Slab",tag={}},
 botania_jj_biomestonea12stairs={hasPattern=true,label="Metamorphic Swamp Cobblestone Stairs",tag={}},
 botania_jj_biomestonea13slab={hasPattern=true,label="Metamorphic Desert Cobblestone Slab",tag={}},
 botania_jj_biomestonea13stairs={hasPattern=true,label="Metamorphic Desert Cobblestone Stairs",tag={}},
 botania_jj_biomestonea14slab={hasPattern=true,label="Metamorphic Taiga Cobblestone Slab",tag={}},
 botania_jj_biomestonea14stairs={hasPattern=true,label="Metamorphic Taiga Cobblestone Stairs",tag={}},
 botania_jj_biomestonea15slab={hasPattern=true,label="Metamorphic Mesa Cobblestone Slab",tag={}},
 botania_jj_biomestonea15stairs={hasPattern=true,label="Metamorphic Mesa Cobblestone Stairs",tag={}},
 botania_jj_biomestonea1slab={hasPattern=true,label="Metamorphic Plains Stone Slab",tag={}},
 botania_jj_biomestonea1stairs={hasPattern=true,label="Metamorphic Plains Stone Stairs",tag={}},
 botania_jj_biomestonea2slab={hasPattern=true,label="Metamorphic Mountain Stone Slab",tag={}},
 botania_jj_biomestonea2stairs={hasPattern=true,label="Metamorphic Mountain Stone Stairs",tag={}},
 botania_jj_biomestonea3slab={hasPattern=true,label="Metamorphic Fungal Stone Slab",tag={}},
 botania_jj_biomestonea3stairs={hasPattern=true,label="Metamorphic Fungal Stone Stairs",tag={}},
 botania_jj_biomestonea4slab={hasPattern=true,label="Metamorphic Swamp Stone Slab",tag={}},
 botania_jj_biomestonea4stairs={hasPattern=true,label="Metamorphic Swamp Stone Stairs",tag={}},
 botania_jj_biomestonea5slab={hasPattern=true,label="Metamorphic Desert Stone Slab",tag={}},
 botania_jj_biomestonea5stairs={hasPattern=true,label="Metamorphic Desert Stone Stairs",tag={}},
 botania_jj_biomestonea6slab={hasPattern=true,label="Metamorphic Taiga Stone Slab",tag={}},
 botania_jj_biomestonea6stairs={hasPattern=true,label="Metamorphic Taiga Stone Stairs",tag={}},
 botania_jj_biomestonea7slab={hasPattern=true,label="Metamorphic Mesa Stone Slab",tag={}},
 botania_jj_biomestonea7stairs={hasPattern=true,label="Metamorphic Mesa Stone Stairs",tag={}},
 botania_jj_biomestonea8slab={hasPattern=true,label="Metamorphic Forest Cobblestone Slab",tag={}},
 botania_jj_biomestonea8stairs={hasPattern=true,label="Metamorphic Forest Cobblestone Stairs",tag={}},
 botania_jj_biomestonea9slab={hasPattern=true,label="Metamorphic Plains Cobblestone Slab",tag={}},
 botania_jj_biomestonea9stairs={hasPattern=true,label="Metamorphic Plains Cobblestone Stairs",tag={}},
 botania_jj_biomestonea_jj_1={hasPattern=false,label="",tag={}},
 botania_jj_biomestonea_jj_10={hasPattern=false,label="",tag={}},
 botania_jj_biomestonea_jj_11={hasPattern=false,label="",tag={}},
 botania_jj_biomestonea_jj_12={hasPattern=false,label="",tag={}},
 botania_jj_biomestonea_jj_13={hasPattern=false,label="",tag={}},
 botania_jj_biomestonea_jj_14={hasPattern=false,label="",tag={}},
 botania_jj_biomestonea_jj_15={hasPattern=false,label="",tag={}},
 botania_jj_biomestonea_jj_2={hasPattern=false,label="",tag={}},
 botania_jj_biomestonea_jj_3={hasPattern=false,label="",tag={}},
 botania_jj_biomestonea_jj_4={hasPattern=false,label="",tag={}},
 botania_jj_biomestonea_jj_5={hasPattern=false,label="",tag={}},
 botania_jj_biomestonea_jj_6={hasPattern=false,label="",tag={}},
 botania_jj_biomestonea_jj_7={hasPattern=false,label="",tag={}},
 botania_jj_biomestonea_jj_8={hasPattern=false,label="",tag={}},
 botania_jj_biomestonea_jj_9={hasPattern=false,label="",tag={}},
 botania_jj_biomestoneb={hasPattern=true,label="Metamorphic Forest Stone Bricks",tag={}},
 botania_jj_biomestoneb0slab={hasPattern=true,label="Metamorphic Forest Stone Brick Slab",tag={}},
 botania_jj_biomestoneb0stairs={hasPattern=true,label="Metamorphic Forest Stone Brick Stairs",tag={}},
 botania_jj_biomestoneb1slab={hasPattern=true,label="Metamorphic Plains Stone Brick Slab",tag={}},
 botania_jj_biomestoneb1stairs={hasPattern=true,label="Metamorphic Plains Stone Brick Stairs",tag={}},
 botania_jj_biomestoneb2slab={hasPattern=true,label="Metamorphic Mountain Stone Brick Slab",tag={}},
 botania_jj_biomestoneb2stairs={hasPattern=true,label="Metamorphic Mountain Stone Brick Stairs",tag={}},
 botania_jj_biomestoneb3slab={hasPattern=true,label="Metamorphic Fungal Stone Brick Slab",tag={}},
 botania_jj_biomestoneb3stairs={hasPattern=true,label="Metamorphic Fungal Stone Brick Stairs",tag={}},
 botania_jj_biomestoneb4slab={hasPattern=true,label="Metamorphic Swamp Stone Brick Slab",tag={}},
 botania_jj_biomestoneb4stairs={hasPattern=true,label="Metamorphic Swamp Stone Brick Stairs",tag={}},
 botania_jj_biomestoneb5slab={hasPattern=true,label="Metamorphic Desert Stone Brick Slab",tag={}},
 botania_jj_biomestoneb5stairs={hasPattern=true,label="Metamorphic Desert Stone Brick Stairs",tag={}},
 botania_jj_biomestoneb6slab={hasPattern=true,label="Metamorphic Taiga Stone Brick Slab",tag={}},
 botania_jj_biomestoneb6stairs={hasPattern=true,label="Metamorphic Taiga Stone Brick Stairs",tag={}},
 botania_jj_biomestoneb7slab={hasPattern=true,label="Metamorphic Mesa Stone Bricks Slab",tag={}},
 botania_jj_biomestoneb7stairs={hasPattern=true,label="Metamorphic Mesa Stone Bricks Stairs",tag={}},
 botania_jj_biomestoneb_jj_1={hasPattern=true,label="Metamorphic Plains Stone Bricks",tag={}},
 botania_jj_biomestoneb_jj_10={hasPattern=true,label="Chiseled Metamorphic Mountain Stone Brick",tag={}},
 botania_jj_biomestoneb_jj_11={hasPattern=true,label="Chiseled Metamorphic Fungal Stone Brick",tag={}},
 botania_jj_biomestoneb_jj_12={hasPattern=true,label="Chiseled Metamorphic Swamp Stone Brick",tag={}},
 botania_jj_biomestoneb_jj_13={hasPattern=true,label="Chiseled Metamorphic Desert Stone Brick",tag={}},
 botania_jj_biomestoneb_jj_14={hasPattern=true,label="Chiseled Metamorphic Taiga Stone Brick",tag={}},
 botania_jj_biomestoneb_jj_15={hasPattern=true,label="Chiseled Metamorphic Mesa Stone Brick",tag={}},
 botania_jj_biomestoneb_jj_2={hasPattern=true,label="Metamorphic Mountain Stone Bricks",tag={}},
 botania_jj_biomestoneb_jj_3={hasPattern=true,label="Metamorphic Fungal Stone Bricks",tag={}},
 botania_jj_biomestoneb_jj_4={hasPattern=true,label="Metamorphic Swamp Stone Bricks",tag={}},
 botania_jj_biomestoneb_jj_5={hasPattern=true,label="Metamorphic Desert Stone Bricks",tag={}},
 botania_jj_biomestoneb_jj_6={hasPattern=true,label="Metamorphic Taiga Stone Bricks",tag={}},
 botania_jj_biomestoneb_jj_7={hasPattern=true,label="Metamorphic Mesa Stone Bricks",tag={}},
 botania_jj_biomestoneb_jj_8={hasPattern=true,label="Chiseled Metamorphic Forest Stone Brick",tag={}},
 botania_jj_biomestoneb_jj_9={hasPattern=true,label="Chiseled Metamorphic Plains Stone Brick",tag={}},
 botania_jj_blackholetalisman={hasPattern=true,label="Black Hole Talisman",tag={}},
 botania_jj_blacklotus={hasPattern=false,label="",tag={}},
 botania_jj_blacklotus_jj_1={hasPattern=false,label="",tag={}},
 botania_jj_blazeblock={hasPattern=true,label="Blaze Mesh",tag={}},
 botania_jj_bloodpendant={hasPattern=false,label="",tag={}},
 botania_jj_bloodpendant_b_1={hasPattern=false,label="",tag={brewKey="speed"}},
 botania_jj_bloodpendant_b_10={hasPattern=false,label="",tag={brewKey="nightVision"}},
 botania_jj_bloodpendant_b_11={hasPattern=false,label="",tag={brewKey="soulCross"}},
 botania_jj_bloodpendant_b_12={hasPattern=false,label="",tag={brewKey="featherFeet"}},
 botania_jj_bloodpendant_b_13={hasPattern=false,label="",tag={brewKey="emptiness"}},
 botania_jj_bloodpendant_b_14={hasPattern=false,label="",tag={brewKey="bloodthirst"}},
 botania_jj_bloodpendant_b_15={hasPattern=true,label="Tainted Blood Pendant",tag={}},
 botania_jj_bloodpendant_b_2={hasPattern=false,label="",tag={brewKey="strength"}},
 botania_jj_bloodpendant_b_3={hasPattern=false,label="",tag={brewKey="haste"}},
 botania_jj_bloodpendant_b_4={hasPattern=false,label="",tag={brewKey="jumpBoost"}},
 botania_jj_bloodpendant_b_5={hasPattern=false,label="",tag={brewKey="regen"}},
 botania_jj_bloodpendant_b_6={hasPattern=false,label="",tag={brewKey="regenWeak"}},
 botania_jj_bloodpendant_b_7={hasPattern=false,label="",tag={brewKey="resistance"}},
 botania_jj_bloodpendant_b_8={hasPattern=false,label="",tag={brewKey="fireResistance"}},
 botania_jj_bloodpendant_b_9={hasPattern=false,label="",tag={brewKey="waterBreathing"}},
 botania_jj_brewery={hasPattern=true,label="Botanical Brewery",tag={}},
 botania_jj_brewflask={hasPattern=false,label="",tag={brewKey="speed"}},
 botania_jj_brewflask_b_1={hasPattern=false,label="",tag={brewKey="strength"}},
 botania_jj_brewflask_b_10={hasPattern=false,label="",tag={brewKey="invisibility"}},
 botania_jj_brewflask_b_11={hasPattern=false,label="",tag={brewKey="nightVision"}},
 botania_jj_brewflask_b_12={hasPattern=false,label="",tag={brewKey="absorption"}},
 botania_jj_brewflask_b_13={hasPattern=false,label="",tag={brewKey="overload"}},
 botania_jj_brewflask_b_14={hasPattern=false,label="",tag={brewKey="soulCross"}},
 botania_jj_brewflask_b_15={hasPattern=false,label="",tag={brewKey="featherFeet"}},
 botania_jj_brewflask_b_16={hasPattern=false,label="",tag={brewKey="emptiness"}},
 botania_jj_brewflask_b_17={hasPattern=false,label="",tag={brewKey="bloodthirst"}},
 botania_jj_brewflask_b_18={hasPattern=false,label="",tag={brewKey="allure"}},
 botania_jj_brewflask_b_19={hasPattern=false,label="",tag={brewKey="clear"}},
 botania_jj_brewflask_b_2={hasPattern=false,label="",tag={brewKey="haste"}},
 botania_jj_brewflask_b_20={hasPattern=false,label="",tag={brewKey="warpWard"}},
 botania_jj_brewflask_b_3={hasPattern=false,label="",tag={brewKey="healing"}},
 botania_jj_brewflask_b_4={hasPattern=false,label="",tag={brewKey="jumpBoost"}},
 botania_jj_brewflask_b_5={hasPattern=false,label="",tag={brewKey="regen"}},
 botania_jj_brewflask_b_6={hasPattern=false,label="",tag={brewKey="regenWeak"}},
 botania_jj_brewflask_b_7={hasPattern=false,label="",tag={brewKey="resistance"}},
 botania_jj_brewflask_b_8={hasPattern=false,label="",tag={brewKey="fireResistance"}},
 botania_jj_brewflask_b_9={hasPattern=false,label="",tag={brewKey="waterBreathing"}},
 botania_jj_brewvial={hasPattern=false,label="",tag={brewKey="speed"}},
 botania_jj_brewvial_b_1={hasPattern=false,label="",tag={brewKey="strength"}},
 botania_jj_brewvial_b_10={hasPattern=false,label="",tag={brewKey="invisibility"}},
 botania_jj_brewvial_b_11={hasPattern=false,label="",tag={brewKey="nightVision"}},
 botania_jj_brewvial_b_12={hasPattern=false,label="",tag={brewKey="absorption"}},
 botania_jj_brewvial_b_13={hasPattern=false,label="",tag={brewKey="overload"}},
 botania_jj_brewvial_b_14={hasPattern=false,label="",tag={brewKey="soulCross"}},
 botania_jj_brewvial_b_15={hasPattern=false,label="",tag={brewKey="featherFeet"}},
 botania_jj_brewvial_b_16={hasPattern=false,label="",tag={brewKey="emptiness"}},
 botania_jj_brewvial_b_17={hasPattern=false,label="",tag={brewKey="bloodthirst"}},
 botania_jj_brewvial_b_18={hasPattern=false,label="",tag={brewKey="allure"}},
 botania_jj_brewvial_b_19={hasPattern=false,label="",tag={brewKey="clear"}},
 botania_jj_brewvial_b_2={hasPattern=false,label="",tag={brewKey="haste"}},
 botania_jj_brewvial_b_20={hasPattern=false,label="",tag={brewKey="warpWard"}},
 botania_jj_brewvial_b_3={hasPattern=false,label="",tag={brewKey="healing"}},
 botania_jj_brewvial_b_4={hasPattern=false,label="",tag={brewKey="jumpBoost"}},
 botania_jj_brewvial_b_5={hasPattern=false,label="",tag={brewKey="regen"}},
 botania_jj_brewvial_b_6={hasPattern=false,label="",tag={brewKey="regenWeak"}},
 botania_jj_brewvial_b_7={hasPattern=false,label="",tag={brewKey="resistance"}},
 botania_jj_brewvial_b_8={hasPattern=false,label="",tag={brewKey="fireResistance"}},
 botania_jj_brewvial_b_9={hasPattern=false,label="",tag={brewKey="waterBreathing"}},
 botania_jj_cacophonium={hasPattern=true,label="Cacophonium",tag={}},
 botania_jj_cacophoniumblock={hasPattern=false,label="",tag={}},
 botania_jj_cellblock={hasPattern=true,label="Cellular Block",tag={}},
 botania_jj_clip={hasPattern=true,label="Lens Clip",tag={}},
 botania_jj_cloudpendant={hasPattern=true,label="Cirrus Amulet",tag={}},
 botania_jj_cobblerod={hasPattern=true,label="Rod of the Depths",tag={}},
 botania_jj_cocoon={hasPattern=true,label="Cocoon of Caprice",tag={}},
 botania_jj_conjurationcatalyst={hasPattern=true,label="Conjuration Catalyst",tag={}},
 botania_jj_corporeacrystalcube={hasPattern=true,label="Corporea Crystal Cube",tag={}},
 botania_jj_corporeafunnel={hasPattern=true,label="Corporea Funnel",tag={}},
 botania_jj_corporeaindex={hasPattern=true,label="Corporea Index",tag={}},
 botania_jj_corporeainterceptor={hasPattern=true,label="Corporea Interceptor",tag={}},
 botania_jj_corporearetainer={hasPattern=true,label="Corporea Retainer",tag={}},
 botania_jj_corporeaspark={hasPattern=true,label="Corporea Spark",tag={}},
 botania_jj_corporeaspark_jj_1={hasPattern=true,label="Master Corporea Spark",tag={}},
 botania_jj_cosmetic={hasPattern=true,label="Black Bowtie",tag={}},
 botania_jj_cosmetic_jj_1={hasPattern=true,label="Black Tie",tag={}},
 botania_jj_cosmetic_jj_10={hasPattern=true,label="Blue Butterfly",tag={}},
 botania_jj_cosmetic_jj_11={hasPattern=true,label="Cat Ears",tag={}},
 botania_jj_cosmetic_jj_12={hasPattern=true,label="Witch Pin",tag={}},
 botania_jj_cosmetic_jj_13={hasPattern=true,label="Devil Tail",tag={}},
 botania_jj_cosmetic_jj_14={hasPattern=true,label="Kamui Eye",tag={}},
 botania_jj_cosmetic_jj_15={hasPattern=true,label="Googly Eyes",tag={}},
 botania_jj_cosmetic_jj_16={hasPattern=true,label="Four-Leafed Clover",tag={}},
 botania_jj_cosmetic_jj_17={hasPattern=true,label="Clock Eye",tag={}},
 botania_jj_cosmetic_jj_18={hasPattern=true,label="Unicorn Horn",tag={}},
 botania_jj_cosmetic_jj_19={hasPattern=true,label="Devil Horns",tag={}},
 botania_jj_cosmetic_jj_2={hasPattern=true,label="Red Glasses",tag={}},
 botania_jj_cosmetic_jj_20={hasPattern=true,label="Hyper Plus",tag={}},
 botania_jj_cosmetic_jj_21={hasPattern=true,label="Botanist Emblem",tag={}},
 botania_jj_cosmetic_jj_22={hasPattern=true,label="Ancient Mask",tag={}},
 botania_jj_cosmetic_jj_23={hasPattern=true,label="Eerie Mask",tag={}},
 botania_jj_cosmetic_jj_24={hasPattern=true,label="Alien Antenna",tag={}},
 botania_jj_cosmetic_jj_25={hasPattern=true,label="Anaglyph Glasses",tag={}},
 botania_jj_cosmetic_jj_26={hasPattern=true,label="Orange Shades",tag={}},
 botania_jj_cosmetic_jj_27={hasPattern=true,label="Groucho Glasses",tag={}},
 botania_jj_cosmetic_jj_28={hasPattern=true,label="Thick Eyebrows",tag={}},
 botania_jj_cosmetic_jj_29={hasPattern=true,label="Lusitanic Shield",tag={}},
 botania_jj_cosmetic_jj_3={hasPattern=true,label="Puffy Scarf",tag={}},
 botania_jj_cosmetic_jj_30={hasPattern=true,label="Tiny Potato Mask",tag={}},
 botania_jj_cosmetic_jj_31={hasPattern=true,label="Questgiver Mark",tag={}},
 botania_jj_cosmetic_jj_32={hasPattern=false,label="",tag={}},
 botania_jj_cosmetic_jj_4={hasPattern=true,label="Engineer Goggles",tag={}},
 botania_jj_cosmetic_jj_5={hasPattern=true,label="Eyepatch",tag={}},
 botania_jj_cosmetic_jj_6={hasPattern=true,label="Wicked Eyepatch",tag={}},
 botania_jj_cosmetic_jj_7={hasPattern=true,label="Red Ribbons",tag={}},
 botania_jj_cosmetic_jj_8={hasPattern=true,label="Pink Flower Bud",tag={}},
 botania_jj_cosmetic_jj_9={hasPattern=true,label="Polka-Dotted Bows",tag={}},
 botania_jj_craftinghalo={hasPattern=true,label="Assembly Halo",tag={}},
 botania_jj_craftpattern={hasPattern=true,label="Crafting Pattern #1: 1x1",tag={}},
 botania_jj_craftpattern_jj_1={hasPattern=true,label="Crafting Pattern #2: 2x2",tag={}},
 botania_jj_craftpattern_jj_2={hasPattern=true,label="Crafting Pattern #3: 1x2",tag={}},
 botania_jj_craftpattern_jj_3={hasPattern=true,label="Crafting Pattern #4: 2x1",tag={}},
 botania_jj_craftpattern_jj_4={hasPattern=true,label="Crafting Pattern #5: 1x3",tag={}},
 botania_jj_craftpattern_jj_5={hasPattern=true,label="Crafting Pattern #6: 3x1",tag={}},
 botania_jj_craftpattern_jj_6={hasPattern=true,label="Crafting Pattern #7: 2x3",tag={}},
 botania_jj_craftpattern_jj_7={hasPattern=true,label="Crafting Pattern #8: 3x2",tag={}},
 botania_jj_craftpattern_jj_8={hasPattern=true,label="Crafting Pattern #9: Donut",tag={}},
 botania_jj_crystalbow={hasPattern=true,label="Crystal Bow",tag={}},
 botania_jj_custombrick={hasPattern=true,label="Azulejo",tag={}},
 botania_jj_custombrick_jj_1={hasPattern=true,label="Azulejo",tag={}},
 botania_jj_custombrick_jj_10={hasPattern=true,label="Azulejo",tag={}},
 botania_jj_custombrick_jj_11={hasPattern=true,label="Azulejo",tag={}},
 botania_jj_custombrick_jj_12={hasPattern=true,label="Azulejo",tag={}},
 botania_jj_custombrick_jj_13={hasPattern=true,label="Azulejo",tag={}},
 botania_jj_custombrick_jj_14={hasPattern=true,label="Azulejo",tag={}},
 botania_jj_custombrick_jj_15={hasPattern=true,label="Azulejo",tag={}},
 botania_jj_custombrick_jj_2={hasPattern=true,label="Azulejo",tag={}},
 botania_jj_custombrick_jj_3={hasPattern=true,label="Azulejo",tag={}},
 botania_jj_custombrick_jj_4={hasPattern=true,label="Azulejo",tag={}},
 botania_jj_custombrick_jj_5={hasPattern=true,label="Azulejo",tag={}},
 botania_jj_custombrick_jj_6={hasPattern=true,label="Azulejo",tag={}},
 botania_jj_custombrick_jj_7={hasPattern=true,label="Azulejo",tag={}},
 botania_jj_custombrick_jj_8={hasPattern=true,label="Azulejo",tag={}},
 botania_jj_custombrick_jj_9={hasPattern=true,label="Azulejo",tag={}},
 botania_jj_dice={hasPattern=false,label="",tag={}},
 botania_jj_dirtrod={hasPattern=true,label="Stab der Böden",tag={}},
 botania_jj_distributor={hasPattern=true,label="Manaverteiler",tag={}},
 botania_jj_divacharm={hasPattern=true,label="Talisman der Diva",tag={}},
 botania_jj_diviningrod={hasPattern=true,label="Rod of the Plentiful Mantle",tag={}},
 botania_jj_dodgering={hasPattern=true,label="Ring of Dexterous Motion",tag={}},
 botania_jj_doubleflower1={hasPattern=false,label="",tag={}},
 botania_jj_doubleflower1_jj_1={hasPattern=false,label="",tag={}},
 botania_jj_doubleflower1_jj_2={hasPattern=false,label="",tag={}},
 botania_jj_doubleflower1_jj_3={hasPattern=false,label="",tag={}},
 botania_jj_doubleflower1_jj_4={hasPattern=false,label="",tag={}},
 botania_jj_doubleflower1_jj_5={hasPattern=false,label="",tag={}},
 botania_jj_doubleflower1_jj_6={hasPattern=false,label="",tag={}},
 botania_jj_doubleflower1_jj_7={hasPattern=false,label="",tag={}},
 botania_jj_doubleflower2={hasPattern=false,label="",tag={}},
 botania_jj_doubleflower2_jj_1={hasPattern=false,label="",tag={}},
 botania_jj_doubleflower2_jj_2={hasPattern=false,label="",tag={}},
 botania_jj_doubleflower2_jj_3={hasPattern=false,label="",tag={}},
 botania_jj_doubleflower2_jj_4={hasPattern=false,label="",tag={}},
 botania_jj_doubleflower2_jj_5={hasPattern=false,label="",tag={}},
 botania_jj_doubleflower2_jj_6={hasPattern=false,label="",tag={}},
 botania_jj_doubleflower2_jj_7={hasPattern=false,label="",tag={}},
 botania_jj_dreamwood={hasPattern=true,label="Dreamwood",tag={}},
 botania_jj_dreamwood0slab={hasPattern=true,label="Dreamwood Slab",tag={}},
 botania_jj_dreamwood0stairs={hasPattern=true,label="Dreamwood Stairs",tag={}},
 botania_jj_dreamwood0wall={hasPattern=true,label="Dreamwood Wall",tag={}},
 botania_jj_dreamwood1slab={hasPattern=true,label="Dreamwood Plank Slab",tag={}},
 botania_jj_dreamwood1stairs={hasPattern=true,label="Dreamwood Plank Stairs",tag={}},
 botania_jj_dreamwood_jj_1={hasPattern=true,label="Dreamwood Planks",tag={}},
 botania_jj_dreamwood_jj_2={hasPattern=true,label="Mossy Dreamwood Planks",tag={}},
 botania_jj_dreamwood_jj_3={hasPattern=true,label="Framed Dreamwood",tag={}},
 botania_jj_dreamwood_jj_4={hasPattern=true,label="Pattern Framed Dreamwood",tag={}},
 botania_jj_dreamwood_jj_5={hasPattern=true,label="Glimmering Dreamwood",tag={}},
 botania_jj_dye={hasPattern=true,label="Weißes Blumenpulver",tag={}},
 botania_jj_dye_jj_1={hasPattern=true,label="Oranges Blumenpulver",tag={}},
 botania_jj_dye_jj_10={hasPattern=true,label="Violettes Blumenpulver",tag={}},
 botania_jj_dye_jj_11={hasPattern=true,label="Blaues Blumenpulver",tag={}},
 botania_jj_dye_jj_12={hasPattern=true,label="Braunes Blumenpulver",tag={}},
 botania_jj_dye_jj_13={hasPattern=true,label="Grünes Blumenpulver",tag={}},
 botania_jj_dye_jj_14={hasPattern=true,label="Rotes Blumenpulver",tag={}},
 botania_jj_dye_jj_15={hasPattern=true,label="Schwarzes Blumenpulver",tag={}},
 botania_jj_dye_jj_2={hasPattern=true,label="Magentafarbenes Blumenpulver",tag={}},
 botania_jj_dye_jj_3={hasPattern=true,label="Hellblaues Blumenpulver",tag={}},
 botania_jj_dye_jj_4={hasPattern=true,label="Gelbes Blumenpulver",tag={}},
 botania_jj_dye_jj_5={hasPattern=true,label="Hellgrünes Blumenpulver",tag={}},
 botania_jj_dye_jj_6={hasPattern=true,label="Pinkes Blumenpulver",tag={}},
 botania_jj_dye_jj_7={hasPattern=true,label="Graues Blumenpulver",tag={}},
 botania_jj_dye_jj_8={hasPattern=true,label="Hellgraues Blumenpulver",tag={}},
 botania_jj_dye_jj_9={hasPattern=true,label="Türkises Blumenpulver",tag={}},
 botania_jj_elementiumaxe={hasPattern=true,label="Elementium Axe",tag={}},
 botania_jj_elementiumboots={hasPattern=true,label="Elementium Boots",tag={}},
 botania_jj_elementiumchest={hasPattern=true,label="Elementium Chestplate",tag={}},
 botania_jj_elementiumhelm={hasPattern=true,label="Elementium Helmet",tag={}},
 botania_jj_elementiumhelmreveal={hasPattern=false,label="",tag={}},
 botania_jj_elementiumlegs={hasPattern=true,label="Elementium Leggings",tag={}},
 botania_jj_elementiumpick={hasPattern=true,label="Elementium Pickaxe",tag={}},
 botania_jj_elementiumshears={hasPattern=true,label="Elementium Shears",tag={}},
 botania_jj_elementiumshovel={hasPattern=true,label="Elementium Shovel",tag={}},
 botania_jj_elementiumsword={hasPattern=true,label="Elementium Sword",tag={}},
 botania_jj_elfglass={hasPattern=false,label="",tag={}},
 botania_jj_elfglasspane={hasPattern=true,label="Alfglass Pane",tag={}},
 botania_jj_enchantedsoil={hasPattern=false,label="",tag={}},
 botania_jj_enchanter={hasPattern=false,label="",tag={}},
 botania_jj_enderdagger={hasPattern=true,label="Soulscribe",tag={}},
 botania_jj_endereyeblock={hasPattern=true,label="Ender Overseer",tag={}},
 botania_jj_enderhand={hasPattern=true,label="Hand of Ender",tag={}},
 botania_jj_exchangerod={hasPattern=true,label="Rod of the Shifting Crust",tag={}},
 botania_jj_felpumpkin={hasPattern=true,label="Fel Pumpkin",tag={}},
 botania_jj_fertilizer={hasPattern=true,label="Blumendünger",tag={}},
 botania_jj_firerod={hasPattern=true,label="Rod of the Hells",tag={}},
 botania_jj_flighttiara={hasPattern=true,label="Flügel-Tiara",tag={}},
 botania_jj_flighttiara_jj_1={hasPattern=false,label="",tag={}},
 botania_jj_flighttiara_jj_2={hasPattern=false,label="",tag={}},
 botania_jj_flighttiara_jj_3={hasPattern=false,label="",tag={}},
 botania_jj_flighttiara_jj_4={hasPattern=false,label="",tag={}},
 botania_jj_flighttiara_jj_5={hasPattern=false,label="",tag={}},
 botania_jj_flighttiara_jj_6={hasPattern=false,label="",tag={}},
 botania_jj_flighttiara_jj_7={hasPattern=false,label="",tag={}},
 botania_jj_flighttiara_jj_8={hasPattern=false,label="",tag={}},
 botania_jj_floatingspecialflower={hasPattern=false,label="",tag={type="puredaisy"}},
 botania_jj_floatingspecialflower_b_1={hasPattern=false,label="",tag={type="manastar"}},
 botania_jj_floatingspecialflower_b_10={hasPattern=false,label="",tag={type="narslimmus"}},
 botania_jj_floatingspecialflower_b_11={hasPattern=false,label="",tag={type="spectrolus"}},
 botania_jj_floatingspecialflower_b_12={hasPattern=false,label="",tag={type="rafflowsia"}},
 botania_jj_floatingspecialflower_b_13={hasPattern=false,label="",tag={type="shulk_me_not"}},
 botania_jj_floatingspecialflower_b_14={hasPattern=false,label="",tag={type="dandelifeon"}},
 botania_jj_floatingspecialflower_b_15={hasPattern=false,label="",tag={type="jadedAmaranthus"}},
 botania_jj_floatingspecialflower_b_16={hasPattern=false,label="",tag={type="bellethorn"}},
 botania_jj_floatingspecialflower_b_17={hasPattern=false,label="",tag={type="bellethornChibi"}},
 botania_jj_floatingspecialflower_b_18={hasPattern=false,label="",tag={type="dreadthorn"}},
 botania_jj_floatingspecialflower_b_19={hasPattern=false,label="",tag={type="heiseiDream"}},
 botania_jj_floatingspecialflower_b_2={hasPattern=false,label="",tag={type="endoflame"}},
 botania_jj_floatingspecialflower_b_20={hasPattern=false,label="",tag={type="tigerseye"}},
 botania_jj_floatingspecialflower_b_21={hasPattern=false,label="",tag={type="marimorphosis"}},
 botania_jj_floatingspecialflower_b_22={hasPattern=false,label="",tag={type="marimorphosisChibi"}},
 botania_jj_floatingspecialflower_b_23={hasPattern=false,label="",tag={type="orechid"}},
 botania_jj_floatingspecialflower_b_24={hasPattern=false,label="",tag={type="orechidIgnem"}},
 botania_jj_floatingspecialflower_b_25={hasPattern=false,label="",tag={type="fallenKanade"}},
 botania_jj_floatingspecialflower_b_26={hasPattern=false,label="",tag={type="exoflame"}},
 botania_jj_floatingspecialflower_b_27={hasPattern=false,label="",tag={type="agricarnation"}},
 botania_jj_floatingspecialflower_b_28={hasPattern=false,label="",tag={type="agricarnationChibi"}},
 botania_jj_floatingspecialflower_b_29={hasPattern=false,label="",tag={type="hopperhock"}},
 botania_jj_floatingspecialflower_b_3={hasPattern=false,label="",tag={type="hydroangeas"}},
 botania_jj_floatingspecialflower_b_30={hasPattern=false,label="",tag={type="hopperhockChibi"}},
 botania_jj_floatingspecialflower_b_31={hasPattern=false,label="",tag={type="rannuncarpus"}},
 botania_jj_floatingspecialflower_b_32={hasPattern=false,label="",tag={type="rannuncarpusChibi"}},
 botania_jj_floatingspecialflower_b_33={hasPattern=false,label="",tag={type="tangleberrie"}},
 botania_jj_floatingspecialflower_b_34={hasPattern=false,label="",tag={type="jiyuulia"}},
 botania_jj_floatingspecialflower_b_35={hasPattern=false,label="",tag={type="hyacidus"}},
 botania_jj_floatingspecialflower_b_36={hasPattern=false,label="",tag={type="medumone"}},
 botania_jj_floatingspecialflower_b_37={hasPattern=false,label="",tag={type="pollidisiac"}},
 botania_jj_floatingspecialflower_b_38={hasPattern=false,label="",tag={type="clayconia"}},
 botania_jj_floatingspecialflower_b_39={hasPattern=false,label="",tag={type="clayconiaChibi"}},
 botania_jj_floatingspecialflower_b_4={hasPattern=false,label="",tag={type="thermalily"}},
 botania_jj_floatingspecialflower_b_40={hasPattern=false,label="",tag={type="loonium"}},
 botania_jj_floatingspecialflower_b_41={hasPattern=false,label="",tag={type="daffomill"}},
 botania_jj_floatingspecialflower_b_42={hasPattern=false,label="",tag={type="vinculotus"}},
 botania_jj_floatingspecialflower_b_43={hasPattern=false,label="",tag={type="spectranthemum"}},
 botania_jj_floatingspecialflower_b_44={hasPattern=false,label="",tag={type="bubbell"}},
 botania_jj_floatingspecialflower_b_45={hasPattern=false,label="",tag={type="bubbellChibi"}},
 botania_jj_floatingspecialflower_b_46={hasPattern=false,label="",tag={type="solegnolia"}},
 botania_jj_floatingspecialflower_b_47={hasPattern=false,label="",tag={type="solegnoliaChibi"}},
 botania_jj_floatingspecialflower_b_48={hasPattern=false,label="",tag={type="bergamute"}},
 botania_jj_floatingspecialflower_b_49={hasPattern=false,label="",tag={type="beegonia"}},
 botania_jj_floatingspecialflower_b_5={hasPattern=false,label="",tag={type="arcanerose"}},
 botania_jj_floatingspecialflower_b_50={hasPattern=false,label="",tag={type="hiveacynth"}},
 botania_jj_floatingspecialflower_b_51={hasPattern=false,label="",tag={type="hibeescus"}},
 botania_jj_floatingspecialflower_b_52={hasPattern=false,label="",tag={type="ba_rain_flower"}},
 botania_jj_floatingspecialflower_b_53={hasPattern=false,label="",tag={type="ba_lightning_flower"}},
 botania_jj_floatingspecialflower_b_54={hasPattern=false,label="",tag={type="ba_snow_flower"}},
 botania_jj_floatingspecialflower_b_55={hasPattern=false,label="",tag={type="ba_wither_flower"}},
 botania_jj_floatingspecialflower_b_6={hasPattern=false,label="",tag={type="munchdew"}},
 botania_jj_floatingspecialflower_b_7={hasPattern=false,label="",tag={type="entropinnyum"}},
 botania_jj_floatingspecialflower_b_8={hasPattern=false,label="",tag={type="kekimurus"}},
 botania_jj_floatingspecialflower_b_9={hasPattern=false,label="",tag={type="gourmaryllis"}},
 botania_jj_flower={hasPattern=false,label="",tag={}},
 botania_jj_flower_jj_1={hasPattern=false,label="",tag={}},
 botania_jj_flower_jj_10={hasPattern=false,label="",tag={}},
 botania_jj_flower_jj_11={hasPattern=false,label="",tag={}},
 botania_jj_flower_jj_12={hasPattern=false,label="",tag={}},
 botania_jj_flower_jj_13={hasPattern=false,label="",tag={}},
 botania_jj_flower_jj_14={hasPattern=false,label="",tag={}},
 botania_jj_flower_jj_15={hasPattern=false,label="",tag={}},
 botania_jj_flower_jj_2={hasPattern=false,label="",tag={}},
 botania_jj_flower_jj_3={hasPattern=false,label="",tag={}},
 botania_jj_flower_jj_4={hasPattern=false,label="",tag={}},
 botania_jj_flower_jj_5={hasPattern=false,label="",tag={}},
 botania_jj_flower_jj_6={hasPattern=false,label="",tag={}},
 botania_jj_flower_jj_7={hasPattern=false,label="",tag={}},
 botania_jj_flower_jj_8={hasPattern=false,label="",tag={}},
 botania_jj_flower_jj_9={hasPattern=false,label="",tag={}},
 botania_jj_flowerbag={hasPattern=true,label="Flower Pouch",tag={}},
 botania_jj_flugeleye={hasPattern=false,label="",tag={}},
 botania_jj_forestdrum={hasPattern=true,label="Drum of the Wild",tag={}},
 botania_jj_forestdrum_jj_1={hasPattern=true,label="Drum of the Gathering",tag={}},
 botania_jj_forestdrum_jj_2={hasPattern=true,label="Drum of the Canopy",tag={}},
 botania_jj_foresteye={hasPattern=true,label="Auge der Ältesten",tag={}},
 botania_jj_gaiahead={hasPattern=false,label="",tag={}},
 botania_jj_ghostrail={hasPattern=true,label="Spectral Rail",tag={}},
 botania_jj_glasspick={hasPattern=true,label="Vitreous Pickaxe",tag={}},
 botania_jj_goddesscharm={hasPattern=true,label="Benevolent Goddess' Charm",tag={}},
 botania_jj_grasshorn={hasPattern=true,label="Horn of the Wild",tag={}},
 botania_jj_grasshorn_jj_1={hasPattern=true,label="Horn of the Canopy",tag={}},
 botania_jj_grasshorn_jj_2={hasPattern=true,label="Horn of the Covering",tag={}},
 botania_jj_grassseeds={hasPattern=false,label="",tag={}},
 botania_jj_grassseeds_jj_1={hasPattern=false,label="",tag={}},
 botania_jj_grassseeds_jj_2={hasPattern=false,label="",tag={}},
 botania_jj_grassseeds_jj_3={hasPattern=true,label="Dry Pasture Seeds",tag={}},
 botania_jj_grassseeds_jj_4={hasPattern=true,label="Golden Pasture Seeds",tag={}},
 botania_jj_grassseeds_jj_5={hasPattern=true,label="Vivid Pasture Seeds",tag={}},
 botania_jj_grassseeds_jj_6={hasPattern=true,label="Scorched Pasture Seeds",tag={}},
 botania_jj_grassseeds_jj_7={hasPattern=true,label="Infused Pasture Seeds",tag={}},
 botania_jj_grassseeds_jj_8={hasPattern=true,label="Mutated Pasture Seeds",tag={}},
 botania_jj_gravityrod={hasPattern=true,label="Rod of the Shaded Mesa",tag={}},
 botania_jj_holycloak={hasPattern=true,label="Cloak of Virtue",tag={}},
 botania_jj_hourglass={hasPattern=true,label="Hovering Hourglass",tag={}},
 botania_jj_icependant={hasPattern=true,label="Schneeflockanhänger",tag={}},
 botania_jj_incenseplate={hasPattern=true,label="Incense Plate",tag={}},
 botania_jj_incensestick={hasPattern=false,label="",tag={}},
 botania_jj_incensestick_b_1={hasPattern=false,label="",tag={brewKey="speed"}},
 botania_jj_incensestick_b_10={hasPattern=false,label="",tag={brewKey="invisibility"}},
 botania_jj_incensestick_b_11={hasPattern=false,label="",tag={brewKey="nightVision"}},
 botania_jj_incensestick_b_12={hasPattern=false,label="",tag={brewKey="soulCross"}},
 botania_jj_incensestick_b_13={hasPattern=false,label="",tag={brewKey="featherFeet"}},
 botania_jj_incensestick_b_14={hasPattern=false,label="",tag={brewKey="emptiness"}},
 botania_jj_incensestick_b_15={hasPattern=false,label="",tag={brewKey="bloodthirst"}},
 botania_jj_incensestick_b_16={hasPattern=false,label="",tag={brewKey="allure"}},
 botania_jj_incensestick_b_17={hasPattern=true,label="Incense Stick",tag={}},
 botania_jj_incensestick_b_2={hasPattern=false,label="",tag={brewKey="strength"}},
 botania_jj_incensestick_b_3={hasPattern=false,label="",tag={brewKey="haste"}},
 botania_jj_incensestick_b_4={hasPattern=false,label="",tag={brewKey="jumpBoost"}},
 botania_jj_incensestick_b_5={hasPattern=false,label="",tag={brewKey="regen"}},
 botania_jj_incensestick_b_6={hasPattern=false,label="",tag={brewKey="regenWeak"}},
 botania_jj_incensestick_b_7={hasPattern=false,label="",tag={brewKey="resistance"}},
 botania_jj_incensestick_b_8={hasPattern=false,label="",tag={brewKey="fireResistance"}},
 botania_jj_incensestick_b_9={hasPattern=false,label="",tag={brewKey="waterBreathing"}},
 botania_jj_infinitefruit={hasPattern=false,label="",tag={}},
 botania_jj_invisibilitycloak={hasPattern=true,label="Invisibility Cloak",tag={}},
 botania_jj_itemfinder={hasPattern=true,label="The Spectator",tag={}},
 botania_jj_keepivy={hasPattern=true,label="Resolute Ivy",tag={}},
 botania_jj_kingkey={hasPattern=false,label="",tag={}},
 botania_jj_knockbackbelt={hasPattern=true,label="Tektonikgürtel",tag={}},
 botania_jj_laputashard={hasPattern=true,label="Shard of Laputa",tag={}},
 botania_jj_laputashard_jj_14={hasPattern=true,label="Shard of Laputa",tag={}},
 botania_jj_laputashard_jj_19={hasPattern=true,label="Shard of Laputa",tag={}},
 botania_jj_laputashard_jj_4={hasPattern=true,label="Shard of Laputa",tag={}},
 botania_jj_laputashard_jj_9={hasPattern=true,label="Shard of Laputa",tag={}},
 botania_jj_lavapendant={hasPattern=true,label="Pyroklastanhänger",tag={}},
 botania_jj_lens={hasPattern=true,label="Manalinse",tag={}},
 botania_jj_lens_jj_1={hasPattern=true,label="Manalinse: Geschwindigkeit",tag={}},
 botania_jj_lens_jj_10={hasPattern=true,label="Manalinse: Magnetisierung",tag={}},
 botania_jj_lens_jj_11={hasPattern=true,label="Manalinse: Chaos",tag={}},
 botania_jj_lens_jj_12={hasPattern=true,label="Mana Lens: Influence",tag={}},
 botania_jj_lens_jj_13={hasPattern=true,label="Mana Lens: Weight",tag={}},
 botania_jj_lens_jj_14={hasPattern=true,label="Mana Lens: Paintslinger",tag={}},
 botania_jj_lens_jj_15={hasPattern=true,label="Mana Lens: Kindle",tag={}},
 botania_jj_lens_jj_16={hasPattern=true,label="Mana Lens: Force",tag={}},
 botania_jj_lens_jj_17={hasPattern=true,label="Mana Lens: Flash",tag={}},
 botania_jj_lens_jj_18={hasPattern=true,label="Mana Lens: Warp",tag={}},
 botania_jj_lens_jj_19={hasPattern=true,label="Mana Lens: Redirective",tag={}},
 botania_jj_lens_jj_2={hasPattern=true,label="Manalinse: Macht",tag={}},
 botania_jj_lens_jj_20={hasPattern=true,label="Mana Lens: Celebratory",tag={}},
 botania_jj_lens_jj_21={hasPattern=true,label="Mana Lens: Flare",tag={}},
 botania_jj_lens_jj_22={hasPattern=true,label="Mana Lens: Messenger",tag={}},
 botania_jj_lens_jj_23={hasPattern=true,label="Mana Lens: Tripwire",tag={}},
 botania_jj_lens_jj_3={hasPattern=true,label="Manalinse: Resistenz",tag={}},
 botania_jj_lens_jj_4={hasPattern=true,label="Manalinse: Effizienz",tag={}},
 botania_jj_lens_jj_5={hasPattern=true,label="Manalinse: Abprall",tag={}},
 botania_jj_lens_jj_6={hasPattern=true,label="Manalinse: Schwerkraft",tag={}},
 botania_jj_lens_jj_7={hasPattern=true,label="Manalinse: Bohren",tag={}},
 botania_jj_lens_jj_8={hasPattern=true,label="Manalinse: Schädigung",tag={}},
 botania_jj_lens_jj_9={hasPattern=true,label="Manalinse: Phantom",tag={}},
 botania_jj_lexicon={hasPattern=false,label="",tag={}},
 botania_jj_lexicon_b_1={hasPattern=true,label="Lexica Botania",tag={}},
 botania_jj_lightlauncher={hasPattern=true,label="Luminizer Launcher",tag={}},
 botania_jj_lightrelay={hasPattern=true,label="Luminizer",tag={}},
 botania_jj_lightrelay_jj_1={hasPattern=true,label="Detector Luminizer",tag={}},
 botania_jj_lightrelay_jj_2={hasPattern=true,label="Fork Luminizer",tag={}},
 botania_jj_lightrelay_jj_3={hasPattern=true,label="Toggle Luminizer",tag={}},
 botania_jj_livingrock={hasPattern=false,label="",tag={}},
 botania_jj_livingrock0slab={hasPattern=true,label="Livingrock Slab",tag={}},
 botania_jj_livingrock0stairs={hasPattern=true,label="Livingrock Stairs",tag={}},
 botania_jj_livingrock0wall={hasPattern=true,label="Livingrock Wall",tag={}},
 botania_jj_livingrock1slab={hasPattern=true,label="Livingrock Brick Slab",tag={}},
 botania_jj_livingrock1stairs={hasPattern=true,label="Livingrock Brick Stairs",tag={}},
 botania_jj_livingrock_jj_1={hasPattern=true,label="Lebesteinziegel",tag={}},
 botania_jj_livingrock_jj_2={hasPattern=true,label="Bemooste Lebesteinziegel",tag={}},
 botania_jj_livingrock_jj_3={hasPattern=true,label="Brüchige Lebesteinziegel",tag={}},
 botania_jj_livingrock_jj_4={hasPattern=true,label="Gerahmte Lebesteinziegel",tag={}},
 botania_jj_livingwood={hasPattern=false,label="",tag={}},
 botania_jj_livingwood0slab={hasPattern=true,label="Livingwood Slab",tag={}},
 botania_jj_livingwood0stairs={hasPattern=true,label="Livingwood Stairs",tag={}},
 botania_jj_livingwood0wall={hasPattern=true,label="Livingwood Wall",tag={}},
 botania_jj_livingwood1slab={hasPattern=true,label="Livingwood Plank Slab",tag={}},
 botania_jj_livingwood1stairs={hasPattern=true,label="Livingwood Plank Stairs",tag={}},
 botania_jj_livingwood_jj_1={hasPattern=true,label="Lebeholzbretter",tag={}},
 botania_jj_livingwood_jj_2={hasPattern=true,label="Bemooste Lebeholzbretter",tag={}},
 botania_jj_livingwood_jj_3={hasPattern=true,label="Gerahmtes Lebeholz",tag={}},
 botania_jj_livingwood_jj_4={hasPattern=true,label="Schnittgerahmtes Lebeholz",tag={}},
 botania_jj_livingwood_jj_5={hasPattern=true,label="Schimmerndes Lebeholz",tag={}},
 botania_jj_livingwoodbow={hasPattern=true,label="Livingwood Bow",tag={}},
 botania_jj_lokiring={hasPattern=false,label="",tag={}},
 botania_jj_magnetring={hasPattern=true,label="Ring des Magnetismus",tag={}},
 botania_jj_magnetringgreater={hasPattern=true,label="Greater Ring of Magnetization",tag={}},
 botania_jj_manabomb={hasPattern=true,label="Manastorm Charge",tag={}},
 botania_jj_manabottle={hasPattern=false,label="",tag={}},
 botania_jj_manacookie={hasPattern=false,label="",tag={}},
 botania_jj_manadetector={hasPattern=true,label="Mandetektor",tag={}},
 botania_jj_managlass={hasPattern=false,label="",tag={}},
 botania_jj_managlasspane={hasPattern=true,label="Managlass Pane",tag={}},
 botania_jj_managun={hasPattern=true,label="Mana-Blaster",tag={}},
 botania_jj_manainkwell={hasPattern=false,label="",tag={mana=7500}},
 botania_jj_manainkwell_jj_150={hasPattern=false,label="",tag={}},
 botania_jj_manamirror={hasPattern=true,label="Manaspiegel",tag={}},
 botania_jj_manaresource={hasPattern=false,label="",tag={}},
 botania_jj_manaresource_jj_1={hasPattern=false,label="",tag={}},
 botania_jj_manaresource_jj_11={hasPattern=true,label="Crafting Placeholder",tag={}},
 botania_jj_manaresource_jj_12={hasPattern=true,label="Red String",tag={}},
 botania_jj_manaresource_jj_13={hasPattern=true,label="Dreamwood Twig",tag={}},
 botania_jj_manaresource_jj_14={hasPattern=true,label="Gaia Spirit Ingot",tag={}},
 botania_jj_manaresource_jj_15={hasPattern=false,label="",tag={}},
 botania_jj_manaresource_jj_16={hasPattern=false,label="",tag={}},
 botania_jj_manaresource_jj_17={hasPattern=true,label="Manasteel Nugget",tag={}},
 botania_jj_manaresource_jj_18={hasPattern=true,label="Terrasteel Nugget",tag={}},
 botania_jj_manaresource_jj_19={hasPattern=true,label="Elementium Nugget",tag={}},
 botania_jj_manaresource_jj_2={hasPattern=false,label="",tag={}},
 botania_jj_manaresource_jj_22={hasPattern=true,label="Manaweave Cloth",tag={}},
 botania_jj_manaresource_jj_23={hasPattern=false,label="",tag={}},
 botania_jj_manaresource_jj_3={hasPattern=true,label="Lebeholzzweig",tag={}},
 botania_jj_manaresource_jj_4={hasPattern=false,label="",tag={}},
 botania_jj_manaresource_jj_5={hasPattern=false,label="",tag={}},
 botania_jj_manaresource_jj_6={hasPattern=true,label="Redstone-Wurzel",tag={}},
 botania_jj_manaresource_jj_7={hasPattern=false,label="",tag={}},
 botania_jj_manaresource_jj_8={hasPattern=false,label="",tag={}},
 botania_jj_manaresource_jj_9={hasPattern=false,label="",tag={}},
 botania_jj_manaring={hasPattern=false,label="",tag={}},
 botania_jj_manaring_b_1={hasPattern=false,label="",tag={}},
 botania_jj_manaringgreater={hasPattern=false,label="",tag={}},
 botania_jj_manaringgreater_b_1={hasPattern=false,label="",tag={}},
 botania_jj_manasteelaxe={hasPattern=true,label="Manastahlaxt",tag={}},
 botania_jj_manasteelboots={hasPattern=true,label="Manastahlstiefel",tag={}},
 botania_jj_manasteelchest={hasPattern=true,label="Manastahlbrustpanzer",tag={}},
 botania_jj_manasteelhelm={hasPattern=true,label="Manastahlhelm",tag={}},
 botania_jj_manasteelhelmreveal={hasPattern=false,label="",tag={}},
 botania_jj_manasteellegs={hasPattern=true,label="Manastahlbeinschutz",tag={}},
 botania_jj_manasteelpick={hasPattern=true,label="Manastahlspitzhacke",tag={}},
 botania_jj_manasteelshears={hasPattern=true,label="Manastahlschere",tag={}},
 botania_jj_manasteelshovel={hasPattern=true,label="Manastahlschaufel",tag={}},
 botania_jj_manasteelsword={hasPattern=true,label="Manastahlschwert",tag={}},
 botania_jj_manatablet={hasPattern=false,label="",tag={}},
 botania_jj_manatablet_b_1={hasPattern=false,label="",tag={mana=500000}},
 botania_jj_manatablet_b_2={hasPattern=true,label="Manatablett",tag={}},
 botania_jj_manavoid={hasPattern=true,label="Manaleere",tag={}},
 botania_jj_manaweaveboots={hasPattern=true,label="Manaweave Boots",tag={}},
 botania_jj_manaweavechest={hasPattern=true,label="Manaweave Robe Top",tag={}},
 botania_jj_manaweavehelm={hasPattern=true,label="Manaweave Cowl",tag={}},
 botania_jj_manaweavelegs={hasPattern=true,label="Manaweave Robe Bottom",tag={}},
 botania_jj_miniisland={hasPattern=true,label="Floating White Flower",tag={}},
 botania_jj_miniisland_jj_1={hasPattern=true,label="Floating Orange Flower",tag={}},
 botania_jj_miniisland_jj_10={hasPattern=true,label="Floating Purple Flower",tag={}},
 botania_jj_miniisland_jj_11={hasPattern=true,label="Floating Blue Flower",tag={}},
 botania_jj_miniisland_jj_12={hasPattern=true,label="Floating Brown Flower",tag={}},
 botania_jj_miniisland_jj_13={hasPattern=true,label="Floating Green Flower",tag={}},
 botania_jj_miniisland_jj_14={hasPattern=true,label="Floating Red Flower",tag={}},
 botania_jj_miniisland_jj_15={hasPattern=true,label="Floating Black Flower",tag={}},
 botania_jj_miniisland_jj_2={hasPattern=true,label="Floating Magenta Flower",tag={}},
 botania_jj_miniisland_jj_3={hasPattern=true,label="Floating Light Blue Flower",tag={}},
 botania_jj_miniisland_jj_4={hasPattern=true,label="Floating Yellow Flower",tag={}},
 botania_jj_miniisland_jj_5={hasPattern=true,label="Floating Lime Flower",tag={}},
 botania_jj_miniisland_jj_6={hasPattern=true,label="Floating Pink Flower",tag={}},
 botania_jj_miniisland_jj_7={hasPattern=true,label="Floating Gray Flower",tag={}},
 botania_jj_miniisland_jj_8={hasPattern=true,label="Floating Light Gray Flower",tag={}},
 botania_jj_miniisland_jj_9={hasPattern=true,label="Floating Cyan Flower",tag={}},
 botania_jj_miningring={hasPattern=true,label="Ring des Erdmantels",tag={}},
 botania_jj_missilerod={hasPattern=true,label="Rod of the Unstable Reservoir",tag={}},
 botania_jj_monocle={hasPattern=true,label="Manaseer Monocle",tag={}},
 botania_jj_mushroom={hasPattern=true,label="White Shimmering Mushroom",tag={}},
 botania_jj_mushroom_jj_1={hasPattern=true,label="Orange Shimmering Mushroom",tag={}},
 botania_jj_mushroom_jj_10={hasPattern=true,label="Purple Shimmering Mushroom",tag={}},
 botania_jj_mushroom_jj_11={hasPattern=true,label="Blue Shimmering Mushroom",tag={}},
 botania_jj_mushroom_jj_12={hasPattern=true,label="Brown Shimmering Mushroom",tag={}},
 botania_jj_mushroom_jj_13={hasPattern=true,label="Green Shimmering Mushroom",tag={}},
 botania_jj_mushroom_jj_14={hasPattern=true,label="Red Shimmering Mushroom",tag={}},
 botania_jj_mushroom_jj_15={hasPattern=true,label="Black Shimmering Mushroom",tag={}},
 botania_jj_mushroom_jj_2={hasPattern=true,label="Magenta Shimmering Mushroom",tag={}},
 botania_jj_mushroom_jj_3={hasPattern=true,label="Light Blue Shimmering Mushroom",tag={}},
 botania_jj_mushroom_jj_4={hasPattern=true,label="Yellow Shimmering Mushroom",tag={}},
 botania_jj_mushroom_jj_5={hasPattern=true,label="Lime Shimmering Mushroom",tag={}},
 botania_jj_mushroom_jj_6={hasPattern=true,label="Pink Shimmering Mushroom",tag={}},
 botania_jj_mushroom_jj_7={hasPattern=true,label="Gray Shimmering Mushroom",tag={}},
 botania_jj_mushroom_jj_8={hasPattern=true,label="Light Gray Shimmering Mushroom",tag={}},
 botania_jj_mushroom_jj_9={hasPattern=true,label="Cyan Shimmering Mushroom",tag={}},
 botania_jj_obediencestick={hasPattern=true,label="Floral Obedience Stick",tag={}},
 botania_jj_odinring={hasPattern=false,label="",tag={}},
 botania_jj_openbucket={hasPattern=true,label="Extrapolated Bucket",tag={}},
 botania_jj_opencrate={hasPattern=true,label="Open Crate",tag={}},
 botania_jj_opencrate_jj_1={hasPattern=true,label="Crafty Crate",tag={}},
 botania_jj_overgrowthseed={hasPattern=false,label="",tag={}},
 botania_jj_pavement={hasPattern=true,label="White Portuguese Pavement",tag={}},
 botania_jj_pavement0slab={hasPattern=true,label="White Portuguese Pavement Slab",tag={}},
 botania_jj_pavement0stairs={hasPattern=true,label="White Portuguese Pavement Stairs",tag={}},
 botania_jj_pavement1slab={hasPattern=true,label="Black Portuguese Pavement Slab",tag={}},
 botania_jj_pavement1stairs={hasPattern=true,label="Black Portuguese Pavement Stairs",tag={}},
 botania_jj_pavement2slab={hasPattern=true,label="Blue Portuguese Pavement Slab",tag={}},
 botania_jj_pavement2stairs={hasPattern=true,label="Blue Portuguese Pavement Stairs",tag={}},
 botania_jj_pavement3slab={hasPattern=true,label="Red Portuguese Pavement Slab",tag={}},
 botania_jj_pavement3stairs={hasPattern=true,label="Red Portuguese Pavement Stairs",tag={}},
 botania_jj_pavement4slab={hasPattern=true,label="Yellow Portuguese Pavement Slab",tag={}},
 botania_jj_pavement4stairs={hasPattern=true,label="Yellow Portuguese Pavement Stairs",tag={}},
 botania_jj_pavement5slab={hasPattern=true,label="Green Portuguese Pavement Slab",tag={}},
 botania_jj_pavement5stairs={hasPattern=true,label="Green Portuguese Pavement Stairs",tag={}},
 botania_jj_pavement_jj_1={hasPattern=true,label="Black Portuguese Pavement",tag={}},
 botania_jj_pavement_jj_2={hasPattern=true,label="Blue Portuguese Pavement",tag={}},
 botania_jj_pavement_jj_3={hasPattern=true,label="Red Portuguese Pavement",tag={}},
 botania_jj_pavement_jj_4={hasPattern=true,label="Yellow Portuguese Pavement",tag={}},
 botania_jj_pavement_jj_5={hasPattern=true,label="Green Portuguese Pavement",tag={}},
 botania_jj_pestleandmortar={hasPattern=true,label="Stößel und Mörser",tag={}},
 botania_jj_petal={hasPattern=true,label="Mystisches Weißes Blütenblatt",tag={}},
 botania_jj_petal_jj_1={hasPattern=true,label="Mystisches Oranges Blütenblatt",tag={}},
 botania_jj_petal_jj_10={hasPattern=true,label="Mystisches Violettes Blütenblatt",tag={}},
 botania_jj_petal_jj_11={hasPattern=true,label="Mystisches Blaues Blütenblatt",tag={}},
 botania_jj_petal_jj_12={hasPattern=true,label="Mystisches Braunes Blütenblatt",tag={}},
 botania_jj_petal_jj_13={hasPattern=true,label="Mystisches Grünes Blütenblatt",tag={}},
 botania_jj_petal_jj_14={hasPattern=true,label="Mystisches Red Blütenblatt",tag={}},
 botania_jj_petal_jj_15={hasPattern=true,label="Mystisches Black Blütenblatt",tag={}},
 botania_jj_petal_jj_2={hasPattern=true,label="Mystisches Magentafarbenes Blütenblatt",tag={}},
 botania_jj_petal_jj_3={hasPattern=true,label="Mystisches Hellblaues Blütenblatt",tag={}},
 botania_jj_petal_jj_4={hasPattern=true,label="Mystisches Gelbes Blütenblatt",tag={}},
 botania_jj_petal_jj_5={hasPattern=true,label="Mystisches Hellgrünes Blütenblatt",tag={}},
 botania_jj_petal_jj_6={hasPattern=true,label="Mystisches Pinkes Blütenblatt",tag={}},
 botania_jj_petal_jj_7={hasPattern=true,label="Mystisches Graues Blütenblatt",tag={}},
 botania_jj_petal_jj_8={hasPattern=true,label="Mystisches Hellgraues Blütenblatt",tag={}},
 botania_jj_petal_jj_9={hasPattern=true,label="Mystisches Türkises Blütenblatt",tag={}},
 botania_jj_petalblock={hasPattern=true,label="White Petal Block",tag={}},
 botania_jj_petalblock_jj_1={hasPattern=true,label="Orange Petal Block",tag={}},
 botania_jj_petalblock_jj_10={hasPattern=true,label="Purple Petal Block",tag={}},
 botania_jj_petalblock_jj_11={hasPattern=true,label="Blue Petal Block",tag={}},
 botania_jj_petalblock_jj_12={hasPattern=true,label="Brown Petal Block",tag={}},
 botania_jj_petalblock_jj_13={hasPattern=true,label="Green Petal Block",tag={}},
 botania_jj_petalblock_jj_14={hasPattern=true,label="Red Petal Block",tag={}},
 botania_jj_petalblock_jj_15={hasPattern=true,label="Black Petal Block",tag={}},
 botania_jj_petalblock_jj_2={hasPattern=true,label="Magenta Petal Block",tag={}},
 botania_jj_petalblock_jj_3={hasPattern=true,label="Light Blue Petal Block",tag={}},
 botania_jj_petalblock_jj_4={hasPattern=true,label="Yellow Petal Block",tag={}},
 botania_jj_petalblock_jj_5={hasPattern=true,label="Lime Petal Block",tag={}},
 botania_jj_petalblock_jj_6={hasPattern=true,label="Pink Petal Block",tag={}},
 botania_jj_petalblock_jj_7={hasPattern=true,label="Gray Petal Block",tag={}},
 botania_jj_petalblock_jj_8={hasPattern=true,label="Light Gray Petal Block",tag={}},
 botania_jj_petalblock_jj_9={hasPattern=true,label="Cyan Petal Block",tag={}},
 botania_jj_phantomink={hasPattern=true,label="Phantom Ink",tag={}},
 botania_jj_pinkinator={hasPattern=false,label="",tag={}},
 botania_jj_pistonrelay={hasPattern=false,label="",tag={}},
 botania_jj_pixiering={hasPattern=true,label="Great Fairy Ring",tag={}},
 botania_jj_platform={hasPattern=true,label="Abstruse Platform",tag={}},
 botania_jj_platform_jj_1={hasPattern=true,label="Spectral Platform",tag={}},
 botania_jj_platform_jj_2={hasPattern=false,label="",tag={}},
 botania_jj_pool={hasPattern=true,label="Manabecken",tag={}},
 botania_jj_pool_jj_1={hasPattern=false,label="",tag={}},
 botania_jj_pool_jj_2={hasPattern=true,label="Diluted Mana Pool",tag={}},
 botania_jj_pool_jj_3={hasPattern=true,label="Fabulous Mana Pool",tag={}},
 botania_jj_poolminecart={hasPattern=true,label="Minecart with Mana Pool",tag={}},
 botania_jj_prism={hasPattern=true,label="Mana Prism",tag={}},
 botania_jj_pump={hasPattern=true,label="Mana Pump",tag={}},
 botania_jj_pylon={hasPattern=true,label="Mana Pylon",tag={}},
 botania_jj_pylon_jj_1={hasPattern=true,label="Natura Pylon",tag={}},
 botania_jj_pylon_jj_2={hasPattern=true,label="Gaia Pylon",tag={}},
 botania_jj_quartz={hasPattern=true,label="Smokey Quartz",tag={}},
 botania_jj_quartz_jj_1={hasPattern=false,label="",tag={}},
 botania_jj_quartz_jj_2={hasPattern=true,label="Blaze Quartz",tag={}},
 botania_jj_quartz_jj_3={hasPattern=true,label="Lavender Quartz",tag={}},
 botania_jj_quartz_jj_4={hasPattern=true,label="Redquartz",tag={}},
 botania_jj_quartz_jj_5={hasPattern=false,label="",tag={}},
 botania_jj_quartz_jj_6={hasPattern=true,label="Sunny Quartz",tag={}},
 botania_jj_quartzslabblazehalf={hasPattern=true,label="Blaze Quartz Slab",tag={}},
 botania_jj_quartzslabdarkhalf={hasPattern=true,label="Smokey Quartz Slab",tag={}},
 botania_jj_quartzslabelfhalf={hasPattern=true,label="Elven Quartz Slab",tag={}},
 botania_jj_quartzslablavenderhalf={hasPattern=true,label="Lavender Quartz Slab",tag={}},
 botania_jj_quartzslabmanahalf={hasPattern=true,label="Mana Quartz Slab",tag={}},
 botania_jj_quartzslabredhalf={hasPattern=true,label="Redquartz Slab",tag={}},
 botania_jj_quartzslabsunnyhalf={hasPattern=true,label="Sunny Quartz Slab",tag={}},
 botania_jj_quartzstairsblaze={hasPattern=true,label="Blaze Quartz Stairs",tag={}},
 botania_jj_quartzstairsdark={hasPattern=true,label="Smokey Quartz Stairs",tag={}},
 botania_jj_quartzstairself={hasPattern=true,label="Elven Quartz Stairs",tag={}},
 botania_jj_quartzstairslavender={hasPattern=true,label="Lavender Quartz Stairs",tag={}},
 botania_jj_quartzstairsmana={hasPattern=true,label="Mana Quartz Stairs",tag={}},
 botania_jj_quartzstairsred={hasPattern=true,label="Redquartz Stairs",tag={}},
 botania_jj_quartzstairssunny={hasPattern=true,label="Sunny Quartz Stairs",tag={}},
 botania_jj_quartztypeblaze={hasPattern=true,label="Block of Blaze Quartz",tag={}},
 botania_jj_quartztypeblaze_jj_1={hasPattern=true,label="Chiseled Blaze Quartz Block",tag={}},
 botania_jj_quartztypeblaze_jj_2={hasPattern=true,label="Pillar Blaze Quartz Block",tag={}},
 botania_jj_quartztypedark={hasPattern=true,label="Block of Smokey Quartz",tag={}},
 botania_jj_quartztypedark_jj_1={hasPattern=true,label="Chiseled Smokey Quartz Block",tag={}},
 botania_jj_quartztypedark_jj_2={hasPattern=true,label="Pillar Smokey Quartz Block",tag={}},
 botania_jj_quartztypeelf={hasPattern=true,label="Block of Elven Quartz",tag={}},
 botania_jj_quartztypeelf_jj_1={hasPattern=true,label="Chiseled Elven Quartz Block",tag={}},
 botania_jj_quartztypeelf_jj_2={hasPattern=true,label="Pillar Elven Quartz Block",tag={}},
 botania_jj_quartztypelavender={hasPattern=true,label="Block of Lavender Quartz",tag={}},
 botania_jj_quartztypelavender_jj_1={hasPattern=true,label="Chiseled Lavender Quartz Block",tag={}},
 botania_jj_quartztypelavender_jj_2={hasPattern=true,label="Pillar Lavender Quartz Block",tag={}},
 botania_jj_quartztypemana={hasPattern=true,label="Block of Mana Quartz",tag={}},
 botania_jj_quartztypemana_jj_1={hasPattern=true,label="Chiseled Mana Quartz Block",tag={}},
 botania_jj_quartztypemana_jj_2={hasPattern=true,label="Pillar Mana Quartz Block",tag={}},
 botania_jj_quartztypered={hasPattern=true,label="Block of Redquartz",tag={}},
 botania_jj_quartztypered_jj_1={hasPattern=true,label="Chiseled Redquartz Block",tag={}},
 botania_jj_quartztypered_jj_2={hasPattern=true,label="Pillar Redquartz Block",tag={}},
 botania_jj_quartztypesunny={hasPattern=true,label="Block of Sunny Quartz",tag={}},
 botania_jj_quartztypesunny_jj_1={hasPattern=true,label="Chiseled Sunny Quartz Block",tag={}},
 botania_jj_quartztypesunny_jj_2={hasPattern=true,label="Pillar Sunny Quartz Block",tag={}},
 botania_jj_rainbowrod={hasPattern=true,label="Rod of the Bifrost",tag={}},
 botania_jj_reachring={hasPattern=true,label="Ring of Far Reach",tag={}},
 botania_jj_recordgaia1={hasPattern=true,label="Scathed Music Disc",tag={}},
 botania_jj_recordgaia2={hasPattern=true,label="Scathed Music Disc",tag={}},
 botania_jj_redstringcomparator={hasPattern=true,label="Red Stringed Comparator",tag={}},
 botania_jj_redstringcontainer={hasPattern=true,label="Red Stringed Container",tag={}},
 botania_jj_redstringdispenser={hasPattern=true,label="Red Stringed Dispenser",tag={}},
 botania_jj_redstringfertilizer={hasPattern=true,label="Red Stringed Nutrifier",tag={}},
 botania_jj_redstringinterceptor={hasPattern=true,label="Red Stringed Interceptor",tag={}},
 botania_jj_redstringrelay={hasPattern=true,label="Red Stringed Spoofer",tag={}},
 botania_jj_rfgenerator={hasPattern=true,label="Mana Fluxfield",tag={}},
 botania_jj_root={hasPattern=true,label="Living Root",tag={}},
 botania_jj_rune={hasPattern=false,label="",tag={}},
 botania_jj_rune_jj_1={hasPattern=false,label="",tag={}},
 botania_jj_rune_jj_10={hasPattern=false,label="",tag={}},
 botania_jj_rune_jj_11={hasPattern=false,label="",tag={}},
 botania_jj_rune_jj_12={hasPattern=false,label="",tag={}},
 botania_jj_rune_jj_13={hasPattern=false,label="",tag={}},
 botania_jj_rune_jj_14={hasPattern=false,label="",tag={}},
 botania_jj_rune_jj_15={hasPattern=false,label="",tag={}},
 botania_jj_rune_jj_2={hasPattern=false,label="",tag={}},
 botania_jj_rune_jj_3={hasPattern=false,label="",tag={}},
 botania_jj_rune_jj_4={hasPattern=false,label="",tag={}},
 botania_jj_rune_jj_5={hasPattern=false,label="",tag={}},
 botania_jj_rune_jj_6={hasPattern=false,label="",tag={}},
 botania_jj_rune_jj_7={hasPattern=false,label="",tag={}},
 botania_jj_rune_jj_8={hasPattern=false,label="",tag={}},
 botania_jj_rune_jj_9={hasPattern=false,label="",tag={}},
 botania_jj_runealtar={hasPattern=true,label="Runenaltar",tag={}},
 botania_jj_sextant={hasPattern=true,label="Worldshaper's Sextant",tag={}},
 botania_jj_shimmerrock={hasPattern=true,label="Shimmerrock",tag={}},
 botania_jj_shimmerrock0slab={hasPattern=true,label="Shimmerrock Slab",tag={}},
 botania_jj_shimmerrock0stairs={hasPattern=true,label="Shimmerrock Stairs",tag={}},
 botania_jj_shimmerwoodplanks={hasPattern=true,label="Shimmerwood Planks",tag={}},
 botania_jj_shimmerwoodplanks0slab={hasPattern=true,label="Shimmerwood Plank Slab",tag={}},
 botania_jj_shimmerwoodplanks0stairs={hasPattern=true,label="Shimmerwood Plank Stairs",tag={}},
 botania_jj_shinyflower={hasPattern=true,label="Schimmernde Weiße Blume",tag={}},
 botania_jj_shinyflower_jj_1={hasPattern=true,label="Schimmernde Orange Blume",tag={}},
 botania_jj_shinyflower_jj_10={hasPattern=true,label="",tag={}},
 botania_jj_shinyflower_jj_11={hasPattern=true,label="",tag={}},
 botania_jj_shinyflower_jj_12={hasPattern=true,label="",tag={}},
 botania_jj_shinyflower_jj_13={hasPattern=true,label="",tag={}},
 botania_jj_shinyflower_jj_14={hasPattern=true,label="",tag={}},
 botania_jj_shinyflower_jj_15={hasPattern=true,label="",tag={}},
 botania_jj_shinyflower_jj_2={hasPattern=true,label="",tag={}},
 botania_jj_shinyflower_jj_3={hasPattern=true,label="",tag={}},
 botania_jj_shinyflower_jj_4={hasPattern=true,label="",tag={}},
 botania_jj_shinyflower_jj_5={hasPattern=true,label="",tag={}},
 botania_jj_shinyflower_jj_6={hasPattern=true,label="",tag={}},
 botania_jj_shinyflower_jj_7={hasPattern=true,label="",tag={}},
 botania_jj_shinyflower_jj_8={hasPattern=true,label="",tag={}},
 botania_jj_shinyflower_jj_9={hasPattern=true,label="",tag={}},
 botania_jj_skydirtrod={hasPattern=true,label="",tag={}},
 botania_jj_slimebottle={hasPattern=true,label="",tag={}},
 botania_jj_slingshot={hasPattern=true,label="",tag={}},
 botania_jj_smeltrod={hasPattern=true,label="",tag={}},
 botania_jj_spark={hasPattern=true,label="",tag={}},
 botania_jj_sparkchanger={hasPattern=true,label="",tag={}},
 botania_jj_sparkupgrade={hasPattern=true,label="",tag={}},
 botania_jj_sparkupgrade_jj_1={hasPattern=true,label="",tag={}},
 botania_jj_sparkupgrade_jj_2={hasPattern=true,label="",tag={}},
 botania_jj_sparkupgrade_jj_3={hasPattern=true,label="",tag={}},
 botania_jj_spawnerclaw={hasPattern=true,label="",tag={}},
 botania_jj_spawnermover={hasPattern=true,label="",tag={}},
 botania_jj_specialflower={hasPattern=true,label="",tag={type="puredaisy"}},
 botania_jj_specialflower_b_1={hasPattern=true,label="",tag={type="manastar"}},
 botania_jj_specialflower_b_10={hasPattern=true,label="",tag={type="narslimmus"}},
 botania_jj_specialflower_b_11={hasPattern=true,label="",tag={type="spectrolus"}},
 botania_jj_specialflower_b_12={hasPattern=true,label="",tag={type="rafflowsia"}},
 botania_jj_specialflower_b_13={hasPattern=true,label="",tag={type="shulk_me_not"}},
 botania_jj_specialflower_b_14={hasPattern=true,label="",tag={type="dandelifeon"}},
 botania_jj_specialflower_b_15={hasPattern=true,label="",tag={type="jadedAmaranthus"}},
 botania_jj_specialflower_b_16={hasPattern=true,label="",tag={type="bellethorn"}},
 botania_jj_specialflower_b_17={hasPattern=true,label="",tag={type="bellethornChibi"}},
 botania_jj_specialflower_b_18={hasPattern=true,label="",tag={type="dreadthorn"}},
 botania_jj_specialflower_b_19={hasPattern=true,label="",tag={type="heiseiDream"}},
 botania_jj_specialflower_b_2={hasPattern=true,label="",tag={type="endoflame"}},
 botania_jj_specialflower_b_20={hasPattern=true,label="",tag={type="tigerseye"}},
 botania_jj_specialflower_b_21={hasPattern=true,label="",tag={type="marimorphosis"}},
 botania_jj_specialflower_b_22={hasPattern=true,label="",tag={type="marimorphosisChibi"}},
 botania_jj_specialflower_b_23={hasPattern=true,label="",tag={type="orechid"}},
 botania_jj_specialflower_b_24={hasPattern=true,label="",tag={type="orechidIgnem"}},
 botania_jj_specialflower_b_25={hasPattern=true,label="",tag={type="fallenKanade"}},
 botania_jj_specialflower_b_26={hasPattern=true,label="",tag={type="exoflame"}},
 botania_jj_specialflower_b_27={hasPattern=true,label="",tag={type="agricarnation"}},
 botania_jj_specialflower_b_28={hasPattern=true,label="",tag={type="agricarnationChibi"}},
 botania_jj_specialflower_b_29={hasPattern=true,label="",tag={type="hopperhock"}},
 botania_jj_specialflower_b_3={hasPattern=true,label="",tag={type="hydroangeas"}},
 botania_jj_specialflower_b_30={hasPattern=true,label="",tag={type="hopperhockChibi"}},
 botania_jj_specialflower_b_31={hasPattern=true,label="",tag={type="rannuncarpus"}},
 botania_jj_specialflower_b_32={hasPattern=true,label="",tag={type="rannuncarpusChibi"}},
 botania_jj_specialflower_b_33={hasPattern=true,label="",tag={type="tangleberrie"}},
 botania_jj_specialflower_b_34={hasPattern=true,label="",tag={type="jiyuulia"}},
 botania_jj_specialflower_b_35={hasPattern=true,label="",tag={type="hyacidus"}},
 botania_jj_specialflower_b_36={hasPattern=true,label="",tag={type="medumone"}},
 botania_jj_specialflower_b_37={hasPattern=true,label="",tag={type="pollidisiac"}},
 botania_jj_specialflower_b_38={hasPattern=true,label="",tag={type="clayconia"}},
 botania_jj_specialflower_b_39={hasPattern=true,label="",tag={type="clayconiaChibi"}},
 botania_jj_specialflower_b_4={hasPattern=true,label="",tag={type="thermalily"}},
 botania_jj_specialflower_b_40={hasPattern=true,label="",tag={type="loonium"}},
 botania_jj_specialflower_b_41={hasPattern=true,label="",tag={type="daffomill"}},
 botania_jj_specialflower_b_42={hasPattern=true,label="",tag={type="vinculotus"}},
 botania_jj_specialflower_b_43={hasPattern=true,label="",tag={type="spectranthemum"}},
 botania_jj_specialflower_b_44={hasPattern=true,label="",tag={type="bubbell"}},
 botania_jj_specialflower_b_45={hasPattern=true,label="",tag={type="bubbellChibi"}},
 botania_jj_specialflower_b_46={hasPattern=true,label="",tag={type="solegnolia"}},
 botania_jj_specialflower_b_47={hasPattern=true,label="",tag={type="solegnoliaChibi"}},
 botania_jj_specialflower_b_48={hasPattern=true,label="",tag={type="bergamute"}},
 botania_jj_specialflower_b_49={hasPattern=true,label="",tag={type="beegonia"}},
 botania_jj_specialflower_b_5={hasPattern=true,label="",tag={type="arcanerose"}},
 botania_jj_specialflower_b_50={hasPattern=true,label="",tag={type="hiveacynth"}},
 botania_jj_specialflower_b_51={hasPattern=true,label="",tag={type="hibeescus"}},
 botania_jj_specialflower_b_52={hasPattern=false,label="",tag={type="ba_rain_flower"}},
 botania_jj_specialflower_b_53={hasPattern=false,label="",tag={type="ba_lightning_flower"}},
 botania_jj_specialflower_b_54={hasPattern=false,label="",tag={type="ba_snow_flower"}},
 botania_jj_specialflower_b_55={hasPattern=false,label="",tag={type="ba_wither_flower"}},
 botania_jj_specialflower_b_6={hasPattern=true,label="",tag={type="munchdew"}},
 botania_jj_specialflower_b_7={hasPattern=true,label="",tag={type="entropinnyum"}},
 botania_jj_specialflower_b_8={hasPattern=true,label="",tag={type="kekimurus"}},
 botania_jj_specialflower_b_9={hasPattern=true,label="",tag={type="gourmaryllis"}},
 botania_jj_speedupbelt={hasPattern=true,label="",tag={}},
 botania_jj_spellcloth={hasPattern=true,label="",tag={}},
 botania_jj_spreader={hasPattern=true,label="",tag={}},
 botania_jj_spreader_jj_1={hasPattern=true,label="",tag={}},
 botania_jj_spreader_jj_2={hasPattern=true,label="",tag={}},
 botania_jj_spreader_jj_3={hasPattern=true,label="",tag={}},
 botania_jj_starfield={hasPattern=true,label="",tag={}},
 botania_jj_starsword={hasPattern=true,label="",tag={}},
 botania_jj_storage={hasPattern=true,label="",tag={}},
 botania_jj_storage_jj_1={hasPattern=true,label="",tag={}},
 botania_jj_storage_jj_2={hasPattern=true,label="",tag={}},
 botania_jj_storage_jj_3={hasPattern=true,label="",tag={}},
 botania_jj_storage_jj_4={hasPattern=true,label="",tag={}},
 botania_jj_supercloudpendant={hasPattern=true,label="",tag={}},
 botania_jj_superlavapendant={hasPattern=true,label="",tag={}},
 botania_jj_supertravelbelt={hasPattern=true,label="",tag={}},
 botania_jj_swapring={hasPattern=true,label="",tag={}},
 botania_jj_temperancestone={hasPattern=true,label="",tag={}},
 botania_jj_terraaxe={hasPattern=true,label="",tag={}},
 botania_jj_terraformrod={hasPattern=true,label="",tag={}},
 botania_jj_terrapick={hasPattern=true,label="",tag={mana=9999}},
 botania_jj_terrapick_b_1={hasPattern=true,label="",tag={mana=999999}},
 botania_jj_terrapick_b_2={hasPattern=true,label="",tag={mana=9999999}},
 botania_jj_terrapick_b_3={hasPattern=true,label="",tag={mana=99999999}},
 botania_jj_terrapick_b_4={hasPattern=true,label="",tag={mana=999999999}},
 botania_jj_terrapick_b_5={hasPattern=true,label="",tag={mana=2147483646}},
 botania_jj_terraplate={hasPattern=true,label="",tag={}},
 botania_jj_terrasteelboots={hasPattern=true,label="",tag={}},
 botania_jj_terrasteelchest={hasPattern=true,label="",tag={}},
 botania_jj_terrasteelhelm={hasPattern=true,label="",tag={}},
 botania_jj_terrasteelhelmreveal={hasPattern=true,label="",tag={}},
 botania_jj_terrasteellegs={hasPattern=true,label="",tag={}},
 botania_jj_terrasword={hasPattern=true,label="",tag={}},
 botania_jj_teruterubozu={hasPattern=true,label="",tag={}},
 botania_jj_thirdeye={hasPattern=true,label="",tag={}},
 botania_jj_thornchakram={hasPattern=true,label="",tag={}},
 botania_jj_thornchakram_jj_1={hasPattern=true,label="",tag={}},
 botania_jj_thorring={hasPattern=false,label="",tag={}},
 botania_jj_thundersword={hasPattern=true,label="",tag={}},
 botania_jj_tinyplanet={hasPattern=true,label="",tag={}},
 botania_jj_tinyplanetblock={hasPattern=true,label="",tag={}},
 botania_jj_tinypotato={hasPattern=false,label="",tag={}},
 botania_jj_tornadorod={hasPattern=true,label="",tag={}},
 botania_jj_travelbelt={hasPattern=true,label="",tag={}},
 botania_jj_turntable={hasPattern=true,label="",tag={}},
 botania_jj_twigwand={hasPattern=true,label="",tag={color1=0,color2=0}},
 botania_jj_twigwand_b_1={hasPattern=true,label="",tag={color1=1,color2=1}},
 botania_jj_twigwand_b_10={hasPattern=true,label="",tag={color1=10,color2=10}},
 botania_jj_twigwand_b_11={hasPattern=true,label="",tag={color1=11,color2=11}},
 botania_jj_twigwand_b_12={hasPattern=true,label="",tag={color1=12,color2=12}},
 botania_jj_twigwand_b_13={hasPattern=true,label="",tag={color1=13,color2=13}},
 botania_jj_twigwand_b_14={hasPattern=true,label="",tag={color1=14,color2=14}},
 botania_jj_twigwand_b_15={hasPattern=true,label="",tag={color1=15,color2=15}},
 botania_jj_twigwand_b_2={hasPattern=true,label="",tag={color1=2,color2=2}},
 botania_jj_twigwand_b_3={hasPattern=true,label="",tag={color1=3,color2=3}},
 botania_jj_twigwand_b_4={hasPattern=true,label="",tag={color1=4,color2=4}},
 botania_jj_twigwand_b_5={hasPattern=true,label="",tag={color1=5,color2=5}},
 botania_jj_twigwand_b_6={hasPattern=true,label="",tag={color1=6,color2=6}},
 botania_jj_twigwand_b_7={hasPattern=true,label="",tag={color1=7,color2=7}},
 botania_jj_twigwand_b_8={hasPattern=true,label="",tag={color1=8,color2=8}},
 botania_jj_twigwand_b_9={hasPattern=true,label="",tag={color1=9,color2=9}},
 botania_jj_unholycloak={hasPattern=true,label="",tag={}},
 botania_jj_vial={hasPattern=true,label="",tag={}},
 botania_jj_vial_jj_1={hasPattern=true,label="",tag={}},
 botania_jj_vineball={hasPattern=true,label="",tag={}},
 botania_jj_virus={hasPattern=true,label="",tag={}},
 botania_jj_virus_jj_1={hasPattern=true,label="",tag={}},
 botania_jj_waterbowl={hasPattern=true,label="",tag={Fluid={Amount=1000,FluidName="water"}}},
 botania_jj_waterring={hasPattern=true,label="",tag={}},
 botania_jj_waterrod={hasPattern=true,label="",tag={}},
 botania_jj_worldseed={hasPattern=true,label="",tag={}},
 botanicadds_jj_dreamrock={hasPattern=false,label="",tag={}},
 botanicadds_jj_elven_altar={hasPattern=false,label="",tag={}},
 botanicadds_jj_elven_lapis={hasPattern=false,label="",tag={}},
 botanicadds_jj_elven_lapis_block={hasPattern=false,label="",tag={}},
 botanicadds_jj_elvenwood_log={hasPattern=false,label="",tag={}},
 botanicadds_jj_gaia_plate={hasPattern=false,label="",tag={}},
 botanicadds_jj_gaia_shard={hasPattern=false,label="",tag={}},
 botanicadds_jj_gaiasteel_ingot={hasPattern=false,label="",tag={}},
 botanicadds_jj_mana_lapis={hasPattern=false,label="",tag={}},
 botanicadds_jj_mana_lapis_block={hasPattern=false,label="",tag={}},
 botanicadds_jj_mana_stealer_sword={hasPattern=false,label="",tag={}},
 botanicadds_jj_mana_tesseract={hasPattern=false,label="",tag={}},
 botanicadds_jj_pool_dreaming={hasPattern=false,label="",tag={}},
 botanicadds_jj_ring_aura_gaia={hasPattern=false,label="",tag={}},
 botanicadds_jj_rune_energy={hasPattern=false,label="",tag={}},
 botanicadds_jj_rune_tp={hasPattern=false,label="",tag={}},
 botanicadds_jj_terra_catalyst={hasPattern=false,label="",tag={}},
 botanicadds_jj_terra_protector={hasPattern=false,label="",tag={}}
 }