return {
 arcticmobs_jj_arcticspawn_b_10={hasPattern=true,label="",tag="({EntityTag: {id: arcticmobs:wendigo}})"},
 arcticmobs_jj_arcticspawn_b_11={hasPattern=true,label="",tag="({EntityTag: {id: arcticmobs:yeti}})"},
 arcticmobs_jj_arcticspawn_b_6={hasPattern=true,label="",tag="({EntityTag: {id: arcticmobs:arix}})"},
 arcticmobs_jj_arcticspawn_b_7={hasPattern=true,label="",tag="({EntityTag: {id: arcticmobs:frostweaver}})"},
 arcticmobs_jj_arcticspawn_b_8={hasPattern=true,label="",tag="({EntityTag: {id: arcticmobs:maug}})"},
 arcticmobs_jj_arcticspawn_b_9={hasPattern=true,label="",tag="({EntityTag: {id: arcticmobs:serpix}})"},
 arcticmobs_jj_arixtreat={hasPattern=true,label="",tag=""},
 arcticmobs_jj_blizzardcharge={hasPattern=false,label="",tag=""},
 arcticmobs_jj_blizzardscepter={hasPattern=true,label="",tag=""},
 arcticmobs_jj_bucketooze={hasPattern=false,label="",tag=""},
 arcticmobs_jj_frostcloud={hasPattern=false,label="",tag=""},
 arcticmobs_jj_frostfire={hasPattern=false,label="",tag=""},
 arcticmobs_jj_frostweb={hasPattern=false,label="",tag=""},
 arcticmobs_jj_frostwebcharge={hasPattern=false,label="",tag=""},
 arcticmobs_jj_frostwebscepter={hasPattern=true,label="",tag=""},
 arcticmobs_jj_frostyfur={hasPattern=false,label="",tag=""},
 arcticmobs_jj_icefire={hasPattern=false,label="",tag=""},
 arcticmobs_jj_icefirecharge={hasPattern=false,label="",tag=""},
 arcticmobs_jj_icefirescepter={hasPattern=true,label="",tag=""},
 arcticmobs_jj_maugtreat={hasPattern=true,label="",tag=""},
 arcticmobs_jj_ooze={hasPattern=false,label="",tag=""},
 arcticmobs_jj_palesoup={hasPattern=true,label="",tag=""},
 arcticmobs_jj_serpixtreat={hasPattern=true,label="",tag=""},
 arcticmobs_jj_tundracharge={hasPattern=false,label="",tag=""},
 arcticmobs_jj_tundrascepter={hasPattern=true,label="",tag=""},
 arcticmobs_jj_yetimeatcooked={hasPattern=true,label="",tag=""},
 arcticmobs_jj_yetimeatraw={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_amber={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_apple={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_apple_emerald={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_apple_lapis={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_auto_crafter={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_auto_packager={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_battery={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_battery_infinite={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_beacon_potion={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_beacon_redstone={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_biomass={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_block_anvil={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_block_anvil_magma={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_block_disenchanter={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_block_enchanter={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_block_fishing={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_block_forester={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_block_fragile={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_block_fragile_auto={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_block_fragile_weak={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_block_hydrator={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_block_library={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_block_library_ctrl={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_block_miner={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_block_miner_smart={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_block_screen={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_block_shears={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_block_soundproofing={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_block_storeempty={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_block_user={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_block_vacuum={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_block_workbench={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_book_ender={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_boomerang={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_builder_block={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_builder_pattern={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_bundled_pipe={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_button_large={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_cable_wireless={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_cable_wireless_energy={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_cable_wireless_fluid={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_carbon_paper={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_card_location={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_charm_air={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_charm_antidote={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_charm_boat={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_charm_fire={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_charm_speed={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_charm_void={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_charm_water={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_charm_wing={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_chest_sack={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_chest_sack_empty={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_clock={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_corrupted_chorus={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_crafting_food={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_crystal={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_crystal_axe={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_crystal_hoe={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_crystal_pickaxe={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_crystal_spade={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_crystal_sword={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_crystallized_amber={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_crystallized_obsidian={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_cyclic_wand_build={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_dehydrator={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_dice={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_doorbell_simple={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_dropper_exact={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_dropper_minecart={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_dynamite_mining={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_dynamite_safe={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_emerald_axe={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_emerald_boots={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_emerald_chestplate={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_emerald_helmet={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_emerald_hoe={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_emerald_leggings={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_emerald_pickaxe={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_emerald_spade={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_emerald_sword={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_end_coal_ore={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_end_diamond_ore={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_end_emerald_ore={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_end_gold_ore={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_end_iron_ore={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_end_lapis_ore={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_end_redstone_ore={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_ender_blaze={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_ender_dungeon={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_ender_eye_orb={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_ender_lightning={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_ender_pearl_mounted={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_ender_pearl_reuse={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_ender_snow={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_ender_tnt_1={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_ender_tnt_2={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_ender_tnt_3={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_ender_tnt_4={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_ender_tnt_5={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_ender_tnt_6={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_ender_torch={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_ender_water={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_ender_wool={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_energy_pipe={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_energy_pump={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_entity_detector={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_evoker_fang={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_exp_pylon={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_fan={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_fire_dark={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_fire_dark_anim={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_fire_frost={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_fire_killer={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_fire_starter={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_fluid_drain={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_fluid_pipe={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_fluid_placer={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_fluid_pump={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_food_step={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_glass_strong={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_glove_climb={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_glowing_chorus={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_glowing_helmet={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_gold_furnace_minecart={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_gold_minecart={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_harvester_block={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_heart_food={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_heart_toxic={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_horse_upgrade_health={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_horse_upgrade_jump={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_horse_upgrade_speed={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_horse_upgrade_type={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_horse_upgrade_variant={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_imbuer={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_inventory_food={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_item_pipe={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_item_pipe_sort={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_item_pump={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_laser={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_laser_cannon={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_magic_net={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_magnet_anti_block={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_magnet_block={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_mattock={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_melter={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_milk={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_moon_sensor={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_nether_coal_ore={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_nether_diamond_ore={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_nether_emerald_ore={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_nether_gold_ore={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_nether_iron_ore={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_nether_lapis_ore={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_nether_redstone_ore={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_netherbrick_axe={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_netherbrick_hoe={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_netherbrick_pickaxe={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_netherbrick_spade={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_password_block={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_password_remote={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_peat_baked={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_peat_biomass={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_peat_farm={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_peat_fuel={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_peat_fuel_enriched={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_peat_generator={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_peat_unbaked={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_placer_block={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_plate_launch_extra={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_plate_launch_large={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_plate_launch_med={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_plate_launch_small={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_plate_push={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_plate_push_corner={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_plate_push_fast={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_plate_push_fast_angle={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_plate_push_fast_corner={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_plate_push_med_angle={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_plate_push_slow={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_plate_push_slow_angle={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_plate_push_slow_corner={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_plate_push_slowest={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_plate_push_slowest_angle={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_plate_push_slowest_corner={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_plate_vector={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_poison={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_purple_boots={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_purple_chestplate={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_purple_helmet={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_purple_leggings={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_robot_spawner={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_sack_ender={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_sandstone_axe={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_sandstone_hoe={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_sandstone_pickaxe={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_sandstone_spade={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_sandstone_sword={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_screen_target={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_shears_obsidian={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_sign_editor={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_sleeping_mat={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_slingshot_weapon={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_solidifier={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_soulstone={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_sound_player={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_spikes_diamond={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_spikes_iron={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_sprinkler={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_sprout={hasPattern=false,label="",tag=""},
 cyclicmagic_jj_sprout_seed={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_stone_minecart={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_stone_pebble={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_storage_bag={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_sword_ender={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_sword_slowness={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_sword_weakness={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_target={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_tool_auto_torch={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_tool_elevate={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_tool_harvest_crops={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_tool_harvest_leaves={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_tool_harvest_weeds={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_tool_launcher={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_tool_mount={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_tool_mount_inverse={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_tool_prospector={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_tool_push={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_tool_randomize={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_tool_rotate={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_tool_spawn_inspect={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_tool_spelunker={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_tool_swap={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_tool_swap_match={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_tool_torch_launcher={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_tool_trade={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_tool_warp_home={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_tool_warp_spawn={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_trash={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_turret_minecart={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_uncrafting_block={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_void_anvil={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_wand_hypno={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_wand_missile={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_water_candle={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_water_freezer={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_water_spreader={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_wireless_receiver={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_wireless_transmitter={hasPattern=true,label="",tag=""},
 cyclicmagic_jj_xpjuice={hasPattern=false,label="",tag=""},
 demonmobs_jj_cacodemontreat={hasPattern=true,label="",tag=""},
 demonmobs_jj_demoncrystal={hasPattern=true,label="",tag=""},
 demonmobs_jj_demoniclightningcharge={hasPattern=false,label="",tag=""},
 demonmobs_jj_demoniclightningscepter={hasPattern=true,label="",tag=""},
 demonmobs_jj_demonspawn_b_10={hasPattern=true,label="",tag="({EntityTag: {id: demonmobs:behemoth}})"},
 demonmobs_jj_demonspawn_b_11={hasPattern=true,label="",tag="({EntityTag: {id: demonmobs:belph}})"},
 demonmobs_jj_demonspawn_b_12={hasPattern=true,label="",tag="({EntityTag: {id: demonmobs:cacodemon}})"},
 demonmobs_jj_demonspawn_b_13={hasPattern=true,label="",tag="({EntityTag: {id: demonmobs:pinky}})"},
 demonmobs_jj_demonspawn_b_14={hasPattern=true,label="",tag="({EntityTag: {id: demonmobs:rahovart}})"},
 demonmobs_jj_demonspawn_b_15={hasPattern=true,label="",tag="({EntityTag: {id: demonmobs:trite}})"},
 demonmobs_jj_demonspawn_b_8={hasPattern=true,label="",tag="({EntityTag: {id: demonmobs:asmodeus}})"},
 demonmobs_jj_demonspawn_b_9={hasPattern=true,label="",tag="({EntityTag: {id: demonmobs:astaroth}})"},
 demonmobs_jj_demonstone={hasPattern=true,label="",tag=""},
 demonmobs_jj_demonstone_slab={hasPattern=true,label="",tag=""},
 demonmobs_jj_demonstone_slab_double={hasPattern=false,label="",tag=""},
 demonmobs_jj_demonstone_stairs={hasPattern=true,label="",tag=""},
 demonmobs_jj_demonstonebrick={hasPattern=true,label="",tag=""},
 demonmobs_jj_demonstonebrick_fence={hasPattern=true,label="",tag=""},
 demonmobs_jj_demonstonebrick_slab={hasPattern=true,label="",tag=""},
 demonmobs_jj_demonstonebrick_stairs={hasPattern=true,label="",tag=""},
 demonmobs_jj_demonstonebrick_wall={hasPattern=true,label="",tag=""},
 demonmobs_jj_demonstonechiseled={hasPattern=true,label="",tag=""},
 demonmobs_jj_demonstonepillar={hasPattern=true,label="",tag=""},
 demonmobs_jj_demonstonepolished={hasPattern=true,label="",tag=""},
 demonmobs_jj_demonstonetile={hasPattern=true,label="",tag=""},
 demonmobs_jj_demonstonetile_slab={hasPattern=true,label="",tag=""},
 demonmobs_jj_demonstonetile_stairs={hasPattern=true,label="",tag=""},
 demonmobs_jj_devillasagna={hasPattern=true,label="",tag=""},
 demonmobs_jj_devilstarcharge={hasPattern=false,label="",tag=""},
 demonmobs_jj_devilstarscepter={hasPattern=true,label="",tag=""},
 demonmobs_jj_doomfire={hasPattern=false,label="",tag=""},
 demonmobs_jj_doomfirecharge={hasPattern=false,label="",tag=""},
 demonmobs_jj_doomfirescepter={hasPattern=true,label="",tag=""},
 demonmobs_jj_hellfire={hasPattern=false,label="",tag=""},
 demonmobs_jj_hellfirecharge={hasPattern=false,label="",tag=""},
 demonmobs_jj_hellfirescepter={hasPattern=true,label="",tag=""},
 demonmobs_jj_pinkymeatcooked={hasPattern=false,label="",tag=""},
 demonmobs_jj_pinkymeatraw={hasPattern=false,label="",tag=""},
 demonmobs_jj_pinkytreat={hasPattern=true,label="",tag=""},
 demonmobs_jj_soulcubedemonic={hasPattern=true,label="",tag=""},
 demonmobs_jj_soulstonedemonic={hasPattern=false,label="",tag=""},
 desertmobs_jj_ambercake={hasPattern=true,label="",tag=""},
 desertmobs_jj_crusktreat={hasPattern=true,label="",tag=""},
 desertmobs_jj_desertspawn_b_10={hasPattern=true,label="",tag="({EntityTag: {id: desertmobs:crusk}})"},
 desertmobs_jj_desertspawn_b_11={hasPattern=true,label="",tag="({EntityTag: {id: desertmobs:cryptzombie}})"},
 desertmobs_jj_desertspawn_b_12={hasPattern=true,label="",tag="({EntityTag: {id: desertmobs:erepede}})"},
 desertmobs_jj_desertspawn_b_13={hasPattern=true,label="",tag="({EntityTag: {id: desertmobs:gorgomite}})"},
 desertmobs_jj_desertspawn_b_14={hasPattern=true,label="",tag="({EntityTag: {id: desertmobs:joust}})"},
 desertmobs_jj_desertspawn_b_15={hasPattern=true,label="",tag="({EntityTag: {id: desertmobs:joustalpha}})"},
 desertmobs_jj_desertspawn_b_16={hasPattern=true,label="",tag="({EntityTag: {id: desertmobs:manticore}})"},
 desertmobs_jj_desertspawn_b_17={hasPattern=true,label="",tag="({EntityTag: {id: desertmobs:sutiramu}})"},
 desertmobs_jj_desertspawn_b_9={hasPattern=true,label="",tag="({EntityTag: {id: desertmobs:clink}})"},
 desertmobs_jj_erepedetreat={hasPattern=true,label="",tag=""},
 desertmobs_jj_joustmeatcooked={hasPattern=true,label="",tag=""},
 desertmobs_jj_joustmeatraw={hasPattern=false,label="",tag=""},
 desertmobs_jj_mudshotcharge={hasPattern=false,label="",tag=""},
 desertmobs_jj_mudshotscepter={hasPattern=true,label="",tag=""},
 desertmobs_jj_scythescepter={hasPattern=true,label="",tag=""},
 desertmobs_jj_throwingscythe={hasPattern=true,label="",tag=""},
 elementalmobs_jj_acidsplashcharge={hasPattern=false,label="",tag=""},
 elementalmobs_jj_aetherwavecharge={hasPattern=false,label="",tag=""},
 elementalmobs_jj_aquapulsecharge={hasPattern=false,label="",tag=""},
 elementalmobs_jj_aquapulsescepter={hasPattern=true,label="",tag=""},
 elementalmobs_jj_azurecinderfallsword={hasPattern=true,label="",tag=""},
 elementalmobs_jj_chaosorbcharge={hasPattern=false,label="",tag=""},
 elementalmobs_jj_cinderblade_b_1={hasPattern=true,label="",tag="({equipmentLevel: 1})"},
 elementalmobs_jj_cinderblade_b_2={hasPattern=true,label="",tag="({equipmentLevel: 2})"},
 elementalmobs_jj_cinderblade_b_3={hasPattern=true,label="",tag="({equipmentLevel: 3})"},
 elementalmobs_jj_cinderfallsword={hasPattern=true,label="",tag=""},
 elementalmobs_jj_crystalshard={hasPattern=false,label="",tag=""},
 elementalmobs_jj_elementalspawn_b_21={hasPattern=true,label="",tag="({EntityTag: {id: elementalmobs:aegis}})"},
 elementalmobs_jj_elementalspawn_b_22={hasPattern=true,label="",tag="({EntityTag: {id: elementalmobs:argus}})"},
 elementalmobs_jj_elementalspawn_b_23={hasPattern=true,label="",tag="({EntityTag: {id: elementalmobs:banshee}})"},
 elementalmobs_jj_elementalspawn_b_24={hasPattern=true,label="",tag="({EntityTag: {id: elementalmobs:cinder}})"},
 elementalmobs_jj_elementalspawn_b_25={hasPattern=true,label="",tag="({EntityTag: {id: elementalmobs:djinn}})"},
 elementalmobs_jj_elementalspawn_b_26={hasPattern=true,label="",tag="({EntityTag: {id: elementalmobs:eechetik}})"},
 elementalmobs_jj_elementalspawn_b_27={hasPattern=true,label="",tag="({EntityTag: {id: elementalmobs:geonach}})"},
 elementalmobs_jj_elementalspawn_b_28={hasPattern=true,label="",tag="({EntityTag: {id: elementalmobs:grue}})"},
 elementalmobs_jj_elementalspawn_b_29={hasPattern=true,label="",tag="({EntityTag: {id: elementalmobs:jengu}})"},
 elementalmobs_jj_elementalspawn_b_30={hasPattern=true,label="",tag="({EntityTag: {id: elementalmobs:nymph}})"},
 elementalmobs_jj_elementalspawn_b_31={hasPattern=true,label="",tag="({EntityTag: {id: elementalmobs:reiver}})"},
 elementalmobs_jj_elementalspawn_b_32={hasPattern=true,label="",tag="({EntityTag: {id: elementalmobs:spectre}})"},
 elementalmobs_jj_elementalspawn_b_33={hasPattern=true,label="",tag="({EntityTag: {id: elementalmobs:spriggan}})"},
 elementalmobs_jj_elementalspawn_b_34={hasPattern=true,label="",tag="({EntityTag: {id: elementalmobs:sylph}})"},
 elementalmobs_jj_elementalspawn_b_35={hasPattern=true,label="",tag="({EntityTag: {id: elementalmobs:tremor}})"},
 elementalmobs_jj_elementalspawn_b_36={hasPattern=true,label="",tag="({EntityTag: {id: elementalmobs:vapula}})"},
 elementalmobs_jj_elementalspawn_b_37={hasPattern=true,label="",tag="({EntityTag: {id: elementalmobs:volcan}})"},
 elementalmobs_jj_elementalspawn_b_38={hasPattern=true,label="",tag="({EntityTag: {id: elementalmobs:wisp}})"},
 elementalmobs_jj_elementalspawn_b_39={hasPattern=true,label="",tag="({EntityTag: {id: elementalmobs:wraith}})"},
 elementalmobs_jj_elementalspawn_b_40={hasPattern=true,label="",tag="({EntityTag: {id: elementalmobs:xaphan}})"},
 elementalmobs_jj_elementalspawn_b_41={hasPattern=true,label="",tag="({EntityTag: {id: elementalmobs:zephyr}})"},
 elementalmobs_jj_embercharge={hasPattern=true,label="",tag=""},
 elementalmobs_jj_emberscepter={hasPattern=true,label="",tag=""},
 elementalmobs_jj_faeboltcharge={hasPattern=false,label="",tag=""},
 elementalmobs_jj_frostboltcharge={hasPattern=false,label="",tag=""},
 elementalmobs_jj_frostboltscepter={hasPattern=true,label="",tag=""},
 elementalmobs_jj_geonachfist_b_1={hasPattern=true,label="",tag="({equipmentLevel: 1})"},
 elementalmobs_jj_geonachfist_b_2={hasPattern=true,label="",tag="({equipmentLevel: 2})"},
 elementalmobs_jj_geonachfist_b_3={hasPattern=true,label="",tag="({equipmentLevel: 3})"},
 elementalmobs_jj_lifedraincharge={hasPattern=false,label="",tag=""},
 elementalmobs_jj_lifedrainscepter={hasPattern=true,label="",tag=""},
 elementalmobs_jj_lightball={hasPattern=false,label="",tag=""},
 elementalmobs_jj_vapulacrystal={hasPattern=true,label="",tag="({equipmentLevel: 1})"},
 elementalmobs_jj_vapulacrystal_b_1={hasPattern=true,label="",tag="({equipmentLevel: 2})"},
 elementalmobs_jj_vapulacrystal_b_2={hasPattern=true,label="",tag="({equipmentLevel: 3})"},
 elementalmobs_jj_verdantcinderfallsword={hasPattern=true,label="",tag=""},
 elementalmobs_jj_whirlwindcharge={hasPattern=false,label="",tag=""},
 elementalmobs_jj_wraithsigil={hasPattern=false,label="",tag=""},
 elementalmobs_jj_xaphanspine={hasPattern=true,label="",tag="({equipmentLevel: 1})"},
 elementalmobs_jj_xaphanspine_b_1={hasPattern=true,label="",tag="({equipmentLevel: 2})"},
 elementalmobs_jj_xaphanspine_b_2={hasPattern=true,label="",tag="({equipmentLevel: 3})"},
 elementalmobs_jj_zephyrblade={hasPattern=true,label="",tag="({equipmentLevel: 1})"},
 elementalmobs_jj_zephyrblade_b_1={hasPattern=true,label="",tag="({equipmentLevel: 2})"},
 elementalmobs_jj_zephyrblade_b_2={hasPattern=true,label="",tag="({equipmentLevel: 3})"},
 forestmobs_jj_arisaurmeatcooked={hasPattern=false,label="",tag=""},
 forestmobs_jj_arisaurmeatraw={hasPattern=false,label="",tag=""},
 forestmobs_jj_entarm_b_1={hasPattern=true,label="",tag="({equipmentLevel: 1})"},
 forestmobs_jj_entarm_b_2={hasPattern=true,label="",tag="({equipmentLevel: 2})"},
 forestmobs_jj_entarm_b_3={hasPattern=true,label="",tag="({equipmentLevel: 3})"},
 forestmobs_jj_forestspawn_b_10={hasPattern=true,label="",tag="({EntityTag: {id: forestmobs:treant}})"},
 forestmobs_jj_forestspawn_b_11={hasPattern=true,label="",tag="({EntityTag: {id: forestmobs:warg}})"},
 forestmobs_jj_forestspawn_b_6={hasPattern=true,label="",tag="({EntityTag: {id: forestmobs:arisaur}})"},
 forestmobs_jj_forestspawn_b_7={hasPattern=true,label="",tag="({EntityTag: {id: forestmobs:calpod}})"},
 forestmobs_jj_forestspawn_b_8={hasPattern=true,label="",tag="({EntityTag: {id: forestmobs:ent}})"},
 forestmobs_jj_forestspawn_b_9={hasPattern=true,label="",tag="({EntityTag: {id: forestmobs:shambler}})"},
 forestmobs_jj_paleosalad={hasPattern=true,label="",tag=""},
 forestmobs_jj_shamblertreat={hasPattern=true,label="",tag=""},
 forestmobs_jj_wargtreat={hasPattern=true,label="",tag=""},
 freshwatermobs_jj_freshwaterspawn_b_5={hasPattern=true,label="",tag="({EntityTag: {id: freshwatermobs:abaia}})"},
 freshwatermobs_jj_freshwaterspawn_b_6={hasPattern=true,label="",tag="({EntityTag: {id: freshwatermobs:ioray}})"},
 freshwatermobs_jj_freshwaterspawn_b_7={hasPattern=true,label="",tag="({EntityTag: {id: freshwatermobs:silex}})"},
 freshwatermobs_jj_freshwaterspawn_b_8={hasPattern=true,label="",tag="({EntityTag: {id: freshwatermobs:strider}})"},
 freshwatermobs_jj_freshwaterspawn_b_9={hasPattern=true,label="",tag="({EntityTag: {id: freshwatermobs:thresher}})"},
 freshwatermobs_jj_ioraytreat={hasPattern=true,label="",tag=""},
 freshwatermobs_jj_lapisfishandchips={hasPattern=true,label="",tag=""},
 freshwatermobs_jj_silexmeatcooked={hasPattern=false,label="",tag=""},
 freshwatermobs_jj_silexmeatraw={hasPattern=false,label="",tag=""},
 freshwatermobs_jj_soulstonefreshwater={hasPattern=false,label="",tag=""},
 freshwatermobs_jj_stridertreat={hasPattern=true,label="",tag=""},
 freshwatermobs_jj_threshertreat={hasPattern=true,label="",tag=""},
 freshwatermobs_jj_waterjetcharge={hasPattern=false,label="",tag=""},
 freshwatermobs_jj_waterjetscepter={hasPattern=true,label="",tag=""},
 infernomobs_jj_afrittreat={hasPattern=true,label="",tag=""},
 infernomobs_jj_bucketpurelava={hasPattern=true,label="",tag=""},
 infernomobs_jj_cephignismeatcooked={hasPattern=false,label="",tag=""},
 infernomobs_jj_gorgertreat={hasPattern=true,label="",tag=""},
 infernomobs_jj_ignibustreat={hasPattern=false,label="",tag=""},
 infernomobs_jj_infernospawn_b_10={hasPattern=true,label="",tag="({EntityTag: {id: infernomobs:ignibus}})"},
 infernomobs_jj_infernospawn_b_11={hasPattern=true,label="",tag="({EntityTag: {id: infernomobs:khalk}})"},
 infernomobs_jj_infernospawn_b_12={hasPattern=true,label="",tag="({EntityTag: {id: infernomobs:lobber}})"},
 infernomobs_jj_infernospawn_b_13={hasPattern=true,label="",tag="({EntityTag: {id: infernomobs:salamander}})"},
 infernomobs_jj_infernospawn_b_7={hasPattern=true,label="",tag="({EntityTag: {id: infernomobs:afrit}})"},
 infernomobs_jj_infernospawn_b_8={hasPattern=true,label="",tag="({EntityTag: {id: infernomobs:cephignis}})"},
 infernomobs_jj_infernospawn_b_9={hasPattern=true,label="",tag="({EntityTag: {id: infernomobs:gorger}})"},
 infernomobs_jj_magmacharge={hasPattern=false,label="",tag=""},
 infernomobs_jj_magmascepter={hasPattern=true,label="",tag=""},
 infernomobs_jj_purelava={hasPattern=false,label="",tag=""},
 infernomobs_jj_salamandertreat={hasPattern=true,label="",tag=""},
 infernomobs_jj_scorchfire={hasPattern=false,label="",tag=""},
 infernomobs_jj_scorchfirecharge={hasPattern=false,label="",tag=""},
 infernomobs_jj_scorchfirescepter={hasPattern=true,label="",tag=""},
 infernomobs_jj_searingtaco={hasPattern=true,label="",tag=""},
 infernomobs_jj_soulstoneinferno={hasPattern=false,label="",tag=""},
 junglemobs_jj_cockatricetreat={hasPattern=true,label="",tag=""},
 junglemobs_jj_concapedemeatcooked={hasPattern=false,label="",tag=""},
 junglemobs_jj_concapedemeatraw={hasPattern=false,label="",tag=""},
 junglemobs_jj_dawontreat={hasPattern=true,label="",tag=""},
 junglemobs_jj_junglespawn_b_10={hasPattern=true,label="",tag="({EntityTag: {id: junglemobs:conba}})"},
 junglemobs_jj_junglespawn_b_11={hasPattern=true,label="",tag="({EntityTag: {id: junglemobs:concapede}})"},
 junglemobs_jj_junglespawn_b_12={hasPattern=true,label="",tag="({EntityTag: {id: junglemobs:concapedesegment}})"},
 junglemobs_jj_junglespawn_b_13={hasPattern=true,label="",tag="({EntityTag: {id: junglemobs:dawon}})"},
 junglemobs_jj_junglespawn_b_14={hasPattern=true,label="",tag="({EntityTag: {id: junglemobs:geken}})"},
 junglemobs_jj_junglespawn_b_15={hasPattern=true,label="",tag="({EntityTag: {id: junglemobs:tarantula}})"},
 junglemobs_jj_junglespawn_b_16={hasPattern=true,label="",tag="({EntityTag: {id: junglemobs:uvaraptor}})"},
 junglemobs_jj_junglespawn_b_17={hasPattern=true,label="",tag="({EntityTag: {id: junglemobs:vespid}})"},
 junglemobs_jj_junglespawn_b_18={hasPattern=true,label="",tag="({EntityTag: {id: junglemobs:vespidqueen}})"},
 junglemobs_jj_junglespawn_b_9={hasPattern=true,label="",tag="({EntityTag: {id: junglemobs:cockatrice}})"},
 junglemobs_jj_poopcharge={hasPattern=false,label="",tag=""},
 junglemobs_jj_poopcloud={hasPattern=false,label="",tag=""},
 junglemobs_jj_poopscepter={hasPattern=true,label="",tag=""},
 junglemobs_jj_propolis={hasPattern=true,label="",tag=""},
 junglemobs_jj_quickweb={hasPattern=false,label="",tag=""},
 junglemobs_jj_tropicalcurry={hasPattern=true,label="",tag=""},
 junglemobs_jj_uvaraptortreat={hasPattern=true,label="",tag=""},
 junglemobs_jj_veswax={hasPattern=true,label="",tag=""},
 lycanitesmobs_jj_battleburrito={hasPattern=true,label="",tag=""},
 lycanitesmobs_jj_bloodsummoningstaff={hasPattern=true,label="",tag=""},
 lycanitesmobs_jj_cleansingcrystal={hasPattern=true,label="",tag=""},
 lycanitesmobs_jj_equipment={hasPattern=false,label="",tag=""},
 lycanitesmobs_jj_equipmentforge_iron={hasPattern=false,label="",tag=""},
 lycanitesmobs_jj_equipmentforge_stone={hasPattern=false,label="",tag=""},
 lycanitesmobs_jj_equipmentforge_wood={hasPattern=false,label="",tag=""},
 lycanitesmobs_jj_explorersrisotto={hasPattern=true,label="",tag=""},
 lycanitesmobs_jj_halloweentreat={hasPattern=false,label="",tag=""},
 lycanitesmobs_jj_immunizer={hasPattern=true,label="",tag=""},
 lycanitesmobs_jj_mobtoken={hasPattern=false,label="",tag=""},
 lycanitesmobs_jj_savagesummoningstaff={hasPattern=true,label="",tag=""},
 lycanitesmobs_jj_soulgazer={hasPattern=true,label="",tag=""},
 lycanitesmobs_jj_soulkey={hasPattern=true,label="",tag=""},
 lycanitesmobs_jj_soulkeydiamond={hasPattern=true,label="",tag=""},
 lycanitesmobs_jj_soulkeyemerald={hasPattern=true,label="",tag=""},
 lycanitesmobs_jj_soulstone={hasPattern=true,label="",tag=""},
 lycanitesmobs_jj_stablesummoningstaff={hasPattern=true,label="",tag=""},
 lycanitesmobs_jj_sturdysummoningstaff={hasPattern=true,label="",tag=""},
 lycanitesmobs_jj_summoningpedestal={hasPattern=true,label="",tag=""},
 lycanitesmobs_jj_summoningstaff={hasPattern=true,label="",tag=""},
 lycanitesmobs_jj_wintergift={hasPattern=false,label="",tag=""},
 lycanitesmobs_jj_wintergiftlarge={hasPattern=false,label="",tag=""},
 lycanitesmobs_jj_woodenhilt={hasPattern=true,label="",tag="({equipmentLevel: 1})"},
 lycanitesmobs_jj_woodenpaxel={hasPattern=true,label="",tag="({equipmentLevel: 1})"},
 lycanitesmobs_jj_woodenrod={hasPattern=true,label="",tag="({equipmentLevel: 1})"},
 mountainmobs_jj_arcanelaserstormcharge={hasPattern=false,label="",tag=""},
 mountainmobs_jj_arcanelaserstormscepter={hasPattern=true,label="",tag=""},
 mountainmobs_jj_barghesttreat={hasPattern=true,label="",tag=""},
 mountainmobs_jj_beholdertreat={hasPattern=true,label="",tag=""},
 mountainmobs_jj_boulderblastcharge={hasPattern=false,label="",tag=""},
 mountainmobs_jj_boulderblastscepter={hasPattern=true,label="",tag=""},
 mountainmobs_jj_mountainspawn_b_10={hasPattern=true,label="",tag="({EntityTag: {id: mountainmobs:wildkin}})"},
 mountainmobs_jj_mountainspawn_b_11={hasPattern=true,label="",tag="({EntityTag: {id: mountainmobs:yale}})"},
 mountainmobs_jj_mountainspawn_b_6={hasPattern=true,label="",tag="({EntityTag: {id: mountainmobs:barghest}})"},
 mountainmobs_jj_mountainspawn_b_7={hasPattern=true,label="",tag="({EntityTag: {id: mountainmobs:beholder}})"},
 mountainmobs_jj_mountainspawn_b_8={hasPattern=true,label="",tag="({EntityTag: {id: mountainmobs:jabberwock}})"},
 mountainmobs_jj_mountainspawn_b_9={hasPattern=true,label="",tag="({EntityTag: {id: mountainmobs:troll}})"},
 mountainmobs_jj_peakskebab={hasPattern=true,label="",tag=""},
 mountainmobs_jj_soulstonemountain={hasPattern=false,label="",tag=""},
 mountainmobs_jj_wildkintreat={hasPattern=true,label="",tag=""},
 mountainmobs_jj_yalemeatcooked={hasPattern=false,label="",tag=""},
 mountainmobs_jj_yalemeatraw={hasPattern=false,label="",tag=""},
 plainsmobs_jj_bulwarkburger={hasPattern=true,label="",tag=""},
 plainsmobs_jj_feradontreat={hasPattern=true,label="",tag=""},
 plainsmobs_jj_makameatcooked={hasPattern=true,label="",tag=""},
 plainsmobs_jj_makameatraw={hasPattern=false,label="",tag=""},
 plainsmobs_jj_morocktreat={hasPattern=true,label="",tag=""},
 plainsmobs_jj_plainsspawn_b_10={hasPattern=true,label="",tag="({EntityTag: {id: plainsmobs:kobold}})"},
 plainsmobs_jj_plainsspawn_b_11={hasPattern=true,label="",tag="({EntityTag: {id: plainsmobs:maka}})"},
 plainsmobs_jj_plainsspawn_b_12={hasPattern=true,label="",tag="({EntityTag: {id: plainsmobs:makaalpha}})"},
 plainsmobs_jj_plainsspawn_b_13={hasPattern=true,label="",tag="({EntityTag: {id: plainsmobs:morock}})"},
 plainsmobs_jj_plainsspawn_b_14={hasPattern=true,label="",tag="({EntityTag: {id: plainsmobs:quillbeast}})"},
 plainsmobs_jj_plainsspawn_b_15={hasPattern=true,label="",tag="({EntityTag: {id: plainsmobs:roc}})"},
 plainsmobs_jj_plainsspawn_b_16={hasPattern=true,label="",tag="({EntityTag: {id: plainsmobs:ventoraptor}})"},
 plainsmobs_jj_plainsspawn_b_17={hasPattern=true,label="",tag="({EntityTag: {id: plainsmobs:zoataur}})"},
 plainsmobs_jj_plainsspawn_b_9={hasPattern=true,label="",tag="({EntityTag: {id: plainsmobs:feradon}})"},
 plainsmobs_jj_quill={hasPattern=false,label="",tag=""},
 plainsmobs_jj_quillbeasttreat={hasPattern=true,label="",tag=""},
 plainsmobs_jj_quillscepter={hasPattern=true,label="",tag=""},
 plainsmobs_jj_roctreat={hasPattern=true,label="",tag=""},
 plainsmobs_jj_ventoraptorskull={hasPattern=true,label="",tag="({equipmentLevel: 1})"},
 plainsmobs_jj_ventoraptorskull_b_1={hasPattern=true,label="",tag="({equipmentLevel: 2})"},
 plainsmobs_jj_ventoraptorskull_b_2={hasPattern=true,label="",tag="({equipmentLevel: 3})"},
 plainsmobs_jj_ventoraptortreat={hasPattern=true,label="",tag=""},
 saltwatermobs_jj_hermatreat={hasPattern=true,label="",tag=""},
 saltwatermobs_jj_ikameatcooked={hasPattern=false,label="",tag=""},
 saltwatermobs_jj_ikameatraw={hasPattern=false,label="",tag=""},
 saltwatermobs_jj_quetzodracltreat={hasPattern=true,label="",tag=""},
 saltwatermobs_jj_raikotreat={hasPattern=true,label="",tag=""},
 saltwatermobs_jj_roatreat={hasPattern=true,label="",tag=""},
 saltwatermobs_jj_saltwaterspawn_b_10={hasPattern=true,label="",tag="({EntityTag: {id: saltwatermobs:ika}})"},
 saltwatermobs_jj_saltwaterspawn_b_11={hasPattern=true,label="",tag="({EntityTag: {id: saltwatermobs:lacedon}})"},
 saltwatermobs_jj_saltwaterspawn_b_12={hasPattern=true,label="",tag="({EntityTag: {id: saltwatermobs:quetzodracl}})"},
 saltwatermobs_jj_saltwaterspawn_b_13={hasPattern=true,label="",tag="({EntityTag: {id: saltwatermobs:raiko}})"},
 saltwatermobs_jj_saltwaterspawn_b_14={hasPattern=true,label="",tag="({EntityTag: {id: saltwatermobs:roa}})"},
 saltwatermobs_jj_saltwaterspawn_b_15={hasPattern=true,label="",tag="({EntityTag: {id: saltwatermobs:skylus}})"},
 saltwatermobs_jj_saltwaterspawn_b_8={hasPattern=true,label="",tag="({EntityTag: {id: saltwatermobs:abtu}})"},
 saltwatermobs_jj_saltwaterspawn_b_9={hasPattern=true,label="",tag="({EntityTag: {id: saltwatermobs:herma}})"},
 saltwatermobs_jj_seashellmaki={hasPattern=true,label="",tag=""},
 shadowmobs_jj_bloodchili={hasPattern=true,label="",tag=""},
 shadowmobs_jj_bloodleechcharge={hasPattern=false,label="",tag=""},
 shadowmobs_jj_bloodleechscepter={hasPattern=true,label="",tag=""},
 shadowmobs_jj_chupacabrameatcooked={hasPattern=false,label="",tag=""},
 shadowmobs_jj_chupacabrameatraw={hasPattern=false,label="",tag=""},
 shadowmobs_jj_chupacabratreat={hasPattern=true,label="",tag=""},
 shadowmobs_jj_darklingskull_b_1={hasPattern=true,label="",tag="({equipmentLevel: 1})"},
 shadowmobs_jj_darklingskull_b_2={hasPattern=true,label="",tag="({equipmentLevel: 2})"},
 shadowmobs_jj_darklingskull_b_3={hasPattern=true,label="",tag="({equipmentLevel: 3})"},
 shadowmobs_jj_geistliver={hasPattern=false,label="",tag=""},
 shadowmobs_jj_shadetreat={hasPattern=true,label="",tag=""},
 shadowmobs_jj_shadowcrystal={hasPattern=true,label="",tag=""},
 shadowmobs_jj_shadowfire={hasPattern=false,label="",tag=""},
 shadowmobs_jj_shadowspawn_b_10={hasPattern=true,label="",tag="({EntityTag: {id: shadowmobs:geist}})"},
 shadowmobs_jj_shadowspawn_b_11={hasPattern=true,label="",tag="({EntityTag: {id: shadowmobs:phantom}})"},
 shadowmobs_jj_shadowspawn_b_12={hasPattern=true,label="",tag="({EntityTag: {id: shadowmobs:shade}})"},
 shadowmobs_jj_shadowspawn_b_13={hasPattern=true,label="",tag="({EntityTag: {id: shadowmobs:wraamon}})"},
 shadowmobs_jj_shadowspawn_b_7={hasPattern=true,label="",tag="({EntityTag: {id: shadowmobs:chupacabra}})"},
 shadowmobs_jj_shadowspawn_b_8={hasPattern=true,label="",tag="({EntityTag: {id: shadowmobs:darkling}})"},
 shadowmobs_jj_shadowspawn_b_9={hasPattern=true,label="",tag="({EntityTag: {id: shadowmobs:epion}})"},
 shadowmobs_jj_shadowstone={hasPattern=true,label="",tag=""},
 shadowmobs_jj_shadowstone_slab={hasPattern=true,label="",tag=""},
 shadowmobs_jj_shadowstone_slab_double={hasPattern=false,label="",tag=""},
 shadowmobs_jj_shadowstone_stairs={hasPattern=true,label="",tag=""},
 shadowmobs_jj_shadowstonebrick={hasPattern=true,label="",tag=""},
 shadowmobs_jj_shadowstonebrick_fence={hasPattern=true,label="",tag=""},
 shadowmobs_jj_shadowstonebrick_slab={hasPattern=true,label="",tag=""},
 shadowmobs_jj_shadowstonebrick_stairs={hasPattern=true,label="",tag=""},
 shadowmobs_jj_shadowstonebrick_wall={hasPattern=true,label="",tag=""},
 shadowmobs_jj_shadowstonechiseled={hasPattern=true,label="",tag=""},
 shadowmobs_jj_shadowstonepillar={hasPattern=true,label="",tag=""},
 shadowmobs_jj_shadowstonepolished={hasPattern=true,label="",tag=""},
 shadowmobs_jj_shadowstonetile={hasPattern=true,label="",tag=""},
 shadowmobs_jj_shadowstonetile_slab={hasPattern=true,label="",tag=""},
 shadowmobs_jj_shadowstonetile_stairs={hasPattern=true,label="",tag=""},
 shadowmobs_jj_soulstoneshadow={hasPattern=false,label="",tag=""},
 shadowmobs_jj_spectralboltcharge={hasPattern=false,label="",tag=""},
 shadowmobs_jj_spectralboltscepter={hasPattern=true,label="",tag=""},
 swampmobs_jj_aspidmeatcooked={hasPattern=false,label="",tag=""},
 swampmobs_jj_aspidmeatraw={hasPattern=false,label="",tag=""},
 swampmobs_jj_eyewigtreat={hasPattern=true,label="",tag=""},
 swampmobs_jj_goldenvenomaxeblade={hasPattern=true,label="",tag=""},
 swampmobs_jj_lurkertreat={hasPattern=true,label="",tag=""},
 swampmobs_jj_mosspie={hasPattern=true,label="",tag=""},
 swampmobs_jj_poisoncloud={hasPattern=false,label="",tag=""},
 swampmobs_jj_poisongland={hasPattern=false,label="",tag=""},
 swampmobs_jj_poisonrayscepter={hasPattern=true,label="",tag=""},
 swampmobs_jj_swampspawn_b_10={hasPattern=true,label="",tag="({EntityTag: {id: swampmobs:aspid}})"},
 swampmobs_jj_swampspawn_b_11={hasPattern=true,label="",tag="({EntityTag: {id: swampmobs:dweller}})"},
 swampmobs_jj_swampspawn_b_12={hasPattern=true,label="",tag="({EntityTag: {id: swampmobs:ettin}})"},
 swampmobs_jj_swampspawn_b_13={hasPattern=true,label="",tag="({EntityTag: {id: swampmobs:eyewig}})"},
 swampmobs_jj_swampspawn_b_14={hasPattern=true,label="",tag="({EntityTag: {id: swampmobs:ghoulzombie}})"},
 swampmobs_jj_swampspawn_b_15={hasPattern=true,label="",tag="({EntityTag: {id: swampmobs:lurker}})"},
 swampmobs_jj_swampspawn_b_16={hasPattern=true,label="",tag="({EntityTag: {id: swampmobs:remobra}})"},
 swampmobs_jj_swampspawn_b_17={hasPattern=true,label="",tag="({EntityTag: {id: swampmobs:triffid}})"},
 swampmobs_jj_swampspawn_b_9={hasPattern=true,label="",tag="({EntityTag: {id: swampmobs:aglebemu}})"},
 swampmobs_jj_venomaxeblade={hasPattern=true,label="",tag=""},
 swampmobs_jj_venomshotscepter={hasPattern=true,label="",tag=""},
 swampmobs_jj_verdantvenomaxeblade={hasPattern=true,label="",tag=""}
 }