return {
 alchemistry_jj_argon_light={hasPattern=false,label="",tag={}},
 alchemistry_jj_atomizer={hasPattern=false,label="",tag={}},
 alchemistry_jj_chemical_combiner={hasPattern=false,label="",tag={}},
 alchemistry_jj_chemical_dissolver={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_1={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_10={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_11={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_12={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_13={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_14={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_15={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_16={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_17={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_18={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_19={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_2={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_20={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_21={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_22={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_23={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_24={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_25={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_26={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_27={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_28={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_29={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_3={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_30={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_31={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_32={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_33={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_34={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_35={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_36={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_37={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_38={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_39={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_4={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_40={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_41={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_42={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_43={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_44={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_45={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_46={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_47={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_48={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_49={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_5={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_50={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_51={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_52={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_53={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_54={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_55={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_56={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_57={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_58={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_59={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_6={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_60={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_7={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_8={hasPattern=false,label="",tag={}},
 alchemistry_jj_compound_jj_9={hasPattern=false,label="",tag={}},
 alchemistry_jj_condensed_milk={hasPattern=false,label="",tag={}},
 alchemistry_jj_electrolyzer={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_1={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_10={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_100={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_101={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_102={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_103={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_104={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_105={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_106={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_107={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_108={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_109={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_11={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_110={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_111={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_112={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_113={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_114={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_115={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_116={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_117={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_118={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_12={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_13={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_14={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_15={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_16={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_17={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_18={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_19={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_2={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_20={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_21={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_22={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_23={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_24={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_25={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_26={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_27={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_28={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_29={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_3={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_30={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_31={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_32={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_33={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_34={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_35={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_36={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_37={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_38={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_39={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_4={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_40={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_41={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_42={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_43={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_44={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_45={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_46={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_47={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_48={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_49={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_5={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_50={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_51={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_52={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_53={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_54={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_55={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_56={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_57={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_58={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_59={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_6={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_60={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_61={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_62={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_63={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_64={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_65={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_66={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_67={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_68={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_69={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_7={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_70={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_71={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_72={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_73={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_74={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_75={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_76={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_77={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_78={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_79={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_8={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_80={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_81={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_82={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_83={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_84={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_85={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_86={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_87={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_88={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_89={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_9={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_90={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_91={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_92={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_93={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_94={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_95={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_96={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_97={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_98={hasPattern=false,label="",tag={}},
 alchemistry_jj_element_jj_99={hasPattern=false,label="",tag={}},
 alchemistry_jj_evaporator={hasPattern=false,label="",tag={}},
 alchemistry_jj_fertilizer={hasPattern=false,label="",tag={}},
 alchemistry_jj_fission_casing={hasPattern=false,label="",tag={}},
 alchemistry_jj_fission_controller={hasPattern=false,label="",tag={}},
 alchemistry_jj_fission_core={hasPattern=false,label="",tag={}},
 alchemistry_jj_fusion_casing={hasPattern=false,label="",tag={}},
 alchemistry_jj_fusion_controller={hasPattern=false,label="",tag={}},
 alchemistry_jj_fusion_core={hasPattern=false,label="",tag={}},
 alchemistry_jj_helium_light={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_100={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_101={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_102={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_103={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_104={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_105={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_106={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_107={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_108={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_109={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_11={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_110={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_111={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_112={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_113={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_114={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_115={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_116={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_117={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_118={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_12={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_13={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_14={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_19={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_20={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_21={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_22={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_23={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_24={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_25={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_27={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_28={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_29={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_3={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_30={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_31={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_32={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_33={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_34={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_37={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_38={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_39={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_4={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_40={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_41={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_42={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_43={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_44={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_45={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_46={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_47={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_48={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_49={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_5={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_50={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_51={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_52={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_55={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_56={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_57={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_58={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_59={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_60={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_61={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_62={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_63={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_64={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_65={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_66={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_67={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_68={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_69={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_70={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_71={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_72={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_73={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_74={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_75={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_76={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_77={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_78={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_81={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_82={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_83={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_84={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_85={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_87={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_88={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_89={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_90={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_91={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_92={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_93={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_94={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_95={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_96={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_97={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_98={hasPattern=false,label="",tag={}},
 alchemistry_jj_ingot_jj_99={hasPattern=false,label="",tag={}},
 alchemistry_jj_krypton_light={hasPattern=false,label="",tag={}},
 alchemistry_jj_liquifier={hasPattern=false,label="",tag={}},
 alchemistry_jj_milk={hasPattern=false,label="",tag={}},
 alchemistry_jj_mineral_salt={hasPattern=false,label="",tag={}},
 alchemistry_jj_neon_light={hasPattern=false,label="",tag={}},
 alchemistry_jj_obsidian_breaker={hasPattern=false,label="",tag={}},
 alchemistry_jj_periodic_diagram={hasPattern=false,label="",tag={}},
 alchemistry_jj_slot_filler={hasPattern=false,label="",tag={}},
 alchemistry_jj_wet_sand={hasPattern=false,label="",tag={}},
 alchemistry_jj_xenon_light={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_amber={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_apple={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_apple_emerald={hasPattern=true,label="Emerald Apple",tag={}},
 cyclicmagic_jj_apple_lapis={hasPattern=true,label="Lapis Apple",tag={}},
 cyclicmagic_jj_auto_crafter={hasPattern=true,label="Auto Crafter",tag={}},
 cyclicmagic_jj_auto_packager={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_battery={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_battery_infinite={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_beacon_potion={hasPattern=true,label="Pharos Beacon",tag={}},
 cyclicmagic_jj_beacon_redstone={hasPattern=true,label="Empty Beacon",tag={}},
 cyclicmagic_jj_biomass={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_block_anvil={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_block_anvil_magma={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_block_disenchanter={hasPattern=true,label="Unchant Pylon",tag={}},
 cyclicmagic_jj_block_enchanter={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_block_fishing={hasPattern=true,label="Automatic Fishing Net",tag={}},
 cyclicmagic_jj_block_forester={hasPattern=true,label="Forester",tag={}},
 cyclicmagic_jj_block_fragile={hasPattern=true,label="Fragile Scaffolding",tag={}},
 cyclicmagic_jj_block_fragile_auto={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_block_fragile_weak={hasPattern=true,label="Replaceable Scaffolding",tag={}},
 cyclicmagic_jj_block_hydrator={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_block_library={hasPattern=true,label="Ender Bookshelf",tag={}},
 cyclicmagic_jj_block_library_ctrl={hasPattern=true,label="Ender Library",tag={}},
 cyclicmagic_jj_block_miner={hasPattern=true,label="Block Miner",tag={}},
 cyclicmagic_jj_block_miner_smart={hasPattern=true,label="Controlled Miner",tag={}},
 cyclicmagic_jj_block_screen={hasPattern=true,label="Text Projector",tag={}},
 cyclicmagic_jj_block_shears={hasPattern=true,label="Shearing Block",tag={}},
 cyclicmagic_jj_block_soundproofing={hasPattern=true,label="Soundproofing",tag={}},
 cyclicmagic_jj_block_storeempty={hasPattern=true,label="Fluid Storage Tank",tag={}},
 cyclicmagic_jj_block_user={hasPattern=true,label="Automated User",tag={}},
 cyclicmagic_jj_block_vacuum={hasPattern=true,label="Item Collector",tag={}},
 cyclicmagic_jj_block_workbench={hasPattern=true,label="Workbench",tag={}},
 cyclicmagic_jj_book_ender={hasPattern=true,label="Ender Book",tag={}},
 cyclicmagic_jj_boomerang={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_builder_block={hasPattern=true,label="Structure Builder",tag={}},
 cyclicmagic_jj_builder_pattern={hasPattern=true,label="Pattern Replicator",tag={}},
 cyclicmagic_jj_bundled_pipe={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_button_large={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_cable_wireless={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_cable_wireless_energy={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_cable_wireless_fluid={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_carbon_paper={hasPattern=true,label="Carbon Paper",tag={}},
 cyclicmagic_jj_card_location={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_charm_air={hasPattern=true,label="Air Charm",tag={}},
 cyclicmagic_jj_charm_antidote={hasPattern=true,label="Antidote Charm",tag={}},
 cyclicmagic_jj_charm_boat={hasPattern=true,label="Sailor Charm",tag={}},
 cyclicmagic_jj_charm_fire={hasPattern=true,label="Fire Charm",tag={}},
 cyclicmagic_jj_charm_speed={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_charm_void={hasPattern=true,label="Void Charm",tag={}},
 cyclicmagic_jj_charm_water={hasPattern=true,label="Water Charm",tag={}},
 cyclicmagic_jj_charm_wing={hasPattern=true,label="Wing Charm",tag={}},
 cyclicmagic_jj_chest_sack={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_chest_sack_empty={hasPattern=true,label="Empty Sack of Holding",tag={}},
 cyclicmagic_jj_clock={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_corrupted_chorus={hasPattern=true,label="Corrupted Chorus Fruit",tag={}},
 cyclicmagic_jj_crafting_food={hasPattern=true,label="Inventory Crafting Table",tag={}},
 cyclicmagic_jj_crystal={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_crystal_axe={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_crystal_hoe={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_crystal_pickaxe={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_crystal_spade={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_crystal_sword={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_crystallized_amber={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_crystallized_obsidian={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_cyclic_wand_build={hasPattern=true,label="Cyclic Building Scepter",tag={}},
 cyclicmagic_jj_dehydrator={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_dice={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_doorbell_simple={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_dropper_exact={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_dropper_minecart={hasPattern=true,label="Dropper Minecart",tag={}},
 cyclicmagic_jj_dynamite_mining={hasPattern=true,label="Mining Dynamite",tag={}},
 cyclicmagic_jj_dynamite_safe={hasPattern=true,label="Combat Dynamite",tag={}},
 cyclicmagic_jj_emerald_axe={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_emerald_boots={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_emerald_chestplate={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_emerald_helmet={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_emerald_hoe={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_emerald_leggings={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_emerald_pickaxe={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_emerald_spade={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_emerald_sword={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_end_coal_ore={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_end_diamond_ore={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_end_emerald_ore={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_end_gold_ore={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_end_iron_ore={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_end_lapis_ore={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_end_redstone_ore={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_ender_blaze={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_ender_dungeon={hasPattern=true,label="Spawner Seeker",tag={}},
 cyclicmagic_jj_ender_eye_orb={hasPattern=true,label="Solid Ender Eye",tag={}},
 cyclicmagic_jj_ender_lightning={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_ender_pearl_mounted={hasPattern=true,label="Ender Orb Translocator",tag={}},
 cyclicmagic_jj_ender_pearl_reuse={hasPattern=true,label="Ender Orb",tag={}},
 cyclicmagic_jj_ender_snow={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_ender_tnt_1={hasPattern=true,label="Dynamite I",tag={}},
 cyclicmagic_jj_ender_tnt_2={hasPattern=true,label="Dynamite II",tag={}},
 cyclicmagic_jj_ender_tnt_3={hasPattern=true,label="Dynamite III",tag={}},
 cyclicmagic_jj_ender_tnt_4={hasPattern=true,label="Dynamite IV",tag={}},
 cyclicmagic_jj_ender_tnt_5={hasPattern=true,label="Dynamite V",tag={}},
 cyclicmagic_jj_ender_tnt_6={hasPattern=true,label="Dynamite VI",tag={}},
 cyclicmagic_jj_ender_torch={hasPattern=true,label="Throwing Torch",tag={}},
 cyclicmagic_jj_ender_water={hasPattern=true,label="Antimatter Evaporator",tag={}},
 cyclicmagic_jj_ender_wool={hasPattern=true,label="Enhanced Shears",tag={}},
 cyclicmagic_jj_energy_pipe={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_energy_pump={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_entity_detector={hasPattern=true,label="Entity Detector",tag={}},
 cyclicmagic_jj_evoker_fang={hasPattern=true,label="Evoker Fang",tag={}},
 cyclicmagic_jj_exp_pylon={hasPattern=true,label="Experience Pylon",tag={}},
 cyclicmagic_jj_fan={hasPattern=true,label="Fan",tag={}},
 cyclicmagic_jj_fire_dark={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_fire_dark_anim={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_fire_frost={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_fire_killer={hasPattern=true,label="Fire Slayer",tag={}},
 cyclicmagic_jj_fire_starter={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_fluid_drain={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_fluid_pipe={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_fluid_placer={hasPattern=true,label="Fluid Placer",tag={}},
 cyclicmagic_jj_fluid_pump={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_food_step={hasPattern=true,label="Apple of Lofty Stature",tag={}},
 cyclicmagic_jj_glass_strong={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_glove_climb={hasPattern=true,label="Climbing Gloves",tag={}},
 cyclicmagic_jj_glowing_chorus={hasPattern=true,label="Glowing Chorus Fruit",tag={}},
 cyclicmagic_jj_glowing_helmet={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_gold_furnace_minecart={hasPattern=true,label="Gold Furnace Minecart",tag={}},
 cyclicmagic_jj_gold_minecart={hasPattern=true,label="Gold Minecart",tag={}},
 cyclicmagic_jj_harvester_block={hasPattern=true,label="Harvester",tag={}},
 cyclicmagic_jj_heart_food={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_heart_toxic={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_horse_upgrade_health={hasPattern=true,label="Diamond Carrot",tag={}},
 cyclicmagic_jj_horse_upgrade_jump={hasPattern=true,label="Ender Carrot",tag={}},
 cyclicmagic_jj_horse_upgrade_speed={hasPattern=true,label="Redstone Carrot",tag={}},
 cyclicmagic_jj_horse_upgrade_type={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_horse_upgrade_variant={hasPattern=true,label="Lapis Carrot",tag={}},
 cyclicmagic_jj_imbuer={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_inventory_food={hasPattern=true,label="Inventory Upgrade",tag={}},
 cyclicmagic_jj_item_pipe={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_item_pipe_sort={hasPattern=true,label="Item Sorter",tag={}},
 cyclicmagic_jj_item_pump={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_laser={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_laser_cannon={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_magic_net={hasPattern=true,label="Monster Ball",tag={}},
 cyclicmagic_jj_magnet_anti_block={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_magnet_block={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_mattock={hasPattern=true,label="Mattock",tag={}},
 cyclicmagic_jj_melter={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_milk={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_moon_sensor={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_nether_coal_ore={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_nether_diamond_ore={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_nether_emerald_ore={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_nether_gold_ore={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_nether_iron_ore={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_nether_lapis_ore={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_nether_redstone_ore={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_netherbrick_axe={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_netherbrick_hoe={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_netherbrick_pickaxe={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_netherbrick_spade={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_password_block={hasPattern=true,label="Password Trigger",tag={}},
 cyclicmagic_jj_password_remote={hasPattern=true,label="Remote Lever",tag={}},
 cyclicmagic_jj_peat_baked={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_peat_biomass={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_peat_farm={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_peat_fuel={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_peat_fuel_enriched={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_peat_generator={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_peat_unbaked={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_placer_block={hasPattern=true,label="Block Placer",tag={}},
 cyclicmagic_jj_plate_launch_extra={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_plate_launch_large={hasPattern=true,label="Hardened Slime Plate",tag={}},
 cyclicmagic_jj_plate_launch_med={hasPattern=true,label="Slime Plate",tag={}},
 cyclicmagic_jj_plate_launch_small={hasPattern=true,label="Soft Slime Plate",tag={}},
 cyclicmagic_jj_plate_push={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_plate_push_corner={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_plate_push_fast={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_plate_push_fast_angle={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_plate_push_fast_corner={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_plate_push_med_angle={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_plate_push_slow={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_plate_push_slow_angle={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_plate_push_slow_corner={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_plate_push_slowest={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_plate_push_slowest_angle={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_plate_push_slowest_corner={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_plate_vector={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_poison={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_purple_boots={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_purple_chestplate={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_purple_helmet={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_purple_leggings={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_robot_spawner={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_sack_ender={hasPattern=true,label="Ender Sack",tag={}},
 cyclicmagic_jj_sandstone_axe={hasPattern=true,label="Sandstone Axe",tag={}},
 cyclicmagic_jj_sandstone_hoe={hasPattern=true,label="Sandstone Hoe",tag={}},
 cyclicmagic_jj_sandstone_pickaxe={hasPattern=true,label="Sandstone Pickaxe",tag={}},
 cyclicmagic_jj_sandstone_spade={hasPattern=true,label="Sandstone Shovel",tag={}},
 cyclicmagic_jj_sandstone_sword={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_screen_target={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_shears_obsidian={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_sign_editor={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_sleeping_mat={hasPattern=true,label="Sleeping Mat",tag={}},
 cyclicmagic_jj_slingshot_weapon={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_solidifier={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_soulstone={hasPattern=true,label="Soulstone",tag={}},
 cyclicmagic_jj_sound_player={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_spikes_diamond={hasPattern=true,label="Diamond Spikes",tag={}},
 cyclicmagic_jj_spikes_iron={hasPattern=true,label="Iron Spikes",tag={}},
 cyclicmagic_jj_sprinkler={hasPattern=true,label="Sprinkler",tag={}},
 cyclicmagic_jj_sprout={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_sprout_seed={hasPattern=true,label="Magic Bean",tag={}},
 cyclicmagic_jj_stone_minecart={hasPattern=true,label="Stone Minecart",tag={}},
 cyclicmagic_jj_stone_pebble={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_storage_bag={hasPattern=true,label="Storage Bag",tag={}},
 cyclicmagic_jj_sword_ender={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_sword_slowness={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_sword_weakness={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_target={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_tool_auto_torch={hasPattern=true,label="Automatic Torch",tag={}},
 cyclicmagic_jj_tool_elevate={hasPattern=true,label="Rod of Elevation",tag={}},
 cyclicmagic_jj_tool_harvest_crops={hasPattern=true,label="Garden Scythe",tag={}},
 cyclicmagic_jj_tool_harvest_leaves={hasPattern=true,label="Tree Scythe",tag={}},
 cyclicmagic_jj_tool_harvest_weeds={hasPattern=true,label="Brush Scythe",tag={}},
 cyclicmagic_jj_tool_launcher={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_tool_mount={hasPattern=true,label="Stirrups",tag={}},
 cyclicmagic_jj_tool_mount_inverse={hasPattern=true,label="Inverted Stirrups",tag={}},
 cyclicmagic_jj_tool_prospector={hasPattern=true,label="Prospector",tag={}},
 cyclicmagic_jj_tool_push={hasPattern=true,label="Piston Scepter",tag={}},
 cyclicmagic_jj_tool_randomize={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_tool_rotate={hasPattern=true,label="Wooden Wrench",tag={}},
 cyclicmagic_jj_tool_spawn_inspect={hasPattern=true,label="Spawn Detector",tag={}},
 cyclicmagic_jj_tool_spelunker={hasPattern=true,label="Cavefinder",tag={}},
 cyclicmagic_jj_tool_swap={hasPattern=true,label="Standard Exchange Scepter",tag={}},
 cyclicmagic_jj_tool_swap_match={hasPattern=true,label="Gentle Exchange Scepter",tag={}},
 cyclicmagic_jj_tool_torch_launcher={hasPattern=true,label="Torch launcher",tag={}},
 cyclicmagic_jj_tool_trade={hasPattern=true,label="Merchant Almanac",tag={}},
 cyclicmagic_jj_tool_warp_home={hasPattern=true,label="Ender Wing Prime",tag={}},
 cyclicmagic_jj_tool_warp_spawn={hasPattern=true,label="Ender Wing",tag={}},
 cyclicmagic_jj_trash={hasPattern=true,label="Trash Void",tag={}},
 cyclicmagic_jj_turret_minecart={hasPattern=true,label="Turret Minecart",tag={}},
 cyclicmagic_jj_uncrafting_block={hasPattern=true,label="Uncrafting Grinder",tag={}},
 cyclicmagic_jj_void_anvil={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_wand_hypno={hasPattern=true,label="Chaos Reaper",tag={}},
 cyclicmagic_jj_wand_missile={hasPattern=true,label="Spirit Seeker",tag={}},
 cyclicmagic_jj_water_candle={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_water_freezer={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_water_spreader={hasPattern=false,label="",tag={}},
 cyclicmagic_jj_wireless_receiver={hasPattern=true,label="Wireless Receiver",tag={}},
 cyclicmagic_jj_wireless_transmitter={hasPattern=true,label="Wireless Transmitter",tag={}},
 cyclicmagic_jj_xpjuice={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_aberrationspawn={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="beholder"}}},
 lycanitesmobs_jj_aberrationspawn_b_1={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="trite"}}},
 lycanitesmobs_jj_aberrationspawn_b_2={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="shade"}}},
 lycanitesmobs_jj_aberrationspawn_b_3={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="asmodeus"}}},
 lycanitesmobs_jj_aberrationspawn_b_4={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="astaroth"}}},
 lycanitesmobs_jj_aberrationspawn_b_5={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="krake"}}},
 lycanitesmobs_jj_aberrationtreat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_acidsplashcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_aetherwavecharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_amber_cake={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_angelspawn={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_angeltreat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_aquapulsecharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_aquapulsescepter={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_aquaticspawn={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="lacedon"}}},
 lycanitesmobs_jj_aquaticspawn_b_1={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="roa"}}},
 lycanitesmobs_jj_aquaticspawn_b_10={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="ika"}}},
 lycanitesmobs_jj_aquaticspawn_b_11={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="dweller"}}},
 lycanitesmobs_jj_aquaticspawn_b_12={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="ioray"}}},
 lycanitesmobs_jj_aquaticspawn_b_2={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="silex"}}},
 lycanitesmobs_jj_aquaticspawn_b_3={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="abtu"}}},
 lycanitesmobs_jj_aquaticspawn_b_4={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="strider"}}},
 lycanitesmobs_jj_aquaticspawn_b_5={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="skylus"}}},
 lycanitesmobs_jj_aquaticspawn_b_6={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="thresher"}}},
 lycanitesmobs_jj_aquaticspawn_b_7={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="aglebemu"}}},
 lycanitesmobs_jj_aquaticspawn_b_8={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="cephignis"}}},
 lycanitesmobs_jj_aquaticspawn_b_9={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="abaia"}}},
 lycanitesmobs_jj_aquatictreat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_arcanelaserstormcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_arcanelaserstormscepter={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_argustail={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_argustail_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_argustail_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_arthropodspawn={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="herma"}}},
 lycanitesmobs_jj_arthropodspawn_b_1={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="sutiramu"}}},
 lycanitesmobs_jj_arthropodspawn_b_10={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="eyewig"}}},
 lycanitesmobs_jj_arthropodspawn_b_11={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="concapede"}}},
 lycanitesmobs_jj_arthropodspawn_b_12={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="joust"}}},
 lycanitesmobs_jj_arthropodspawn_b_13={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="gorgomite"}}},
 lycanitesmobs_jj_arthropodspawn_b_14={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="darkling"}}},
 lycanitesmobs_jj_arthropodspawn_b_15={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="lurker"}}},
 lycanitesmobs_jj_arthropodspawn_b_2={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="vespidqueen"}}},
 lycanitesmobs_jj_arthropodspawn_b_3={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="vespid"}}},
 lycanitesmobs_jj_arthropodspawn_b_4={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="joustalpha"}}},
 lycanitesmobs_jj_arthropodspawn_b_5={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="tarantula"}}},
 lycanitesmobs_jj_arthropodspawn_b_6={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="calpod"}}},
 lycanitesmobs_jj_arthropodspawn_b_7={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="erepede"}}},
 lycanitesmobs_jj_arthropodspawn_b_8={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="concapedesegment"}}},
 lycanitesmobs_jj_arthropodspawn_b_9={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="frostweaver"}}},
 lycanitesmobs_jj_arthropodtreat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_astarothclaw={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_astarothclaw_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_astarothclaw_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_avianspawn={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="uvaraptor"}}},
 lycanitesmobs_jj_avianspawn_b_1={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="roc"}}},
 lycanitesmobs_jj_avianspawn_b_2={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="raiko"}}},
 lycanitesmobs_jj_avianspawn_b_3={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="ventoraptor"}}},
 lycanitesmobs_jj_aviantreat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_bansheeeye={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_bansheeeye_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_bansheeeye_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_battle_burrito={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_beastspawn={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="jabberwock"}}},
 lycanitesmobs_jj_beastspawn_b_1={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="arisaur"}}},
 lycanitesmobs_jj_beastspawn_b_10={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="chupacabra"}}},
 lycanitesmobs_jj_beastspawn_b_11={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="geken"}}},
 lycanitesmobs_jj_beastspawn_b_12={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="maug"}}},
 lycanitesmobs_jj_beastspawn_b_13={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="aspid"}}},
 lycanitesmobs_jj_beastspawn_b_14={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="dawon"}}},
 lycanitesmobs_jj_beastspawn_b_15={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="khalk"}}},
 lycanitesmobs_jj_beastspawn_b_16={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="quillbeast"}}},
 lycanitesmobs_jj_beastspawn_b_17={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="yale"}}},
 lycanitesmobs_jj_beastspawn_b_18={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="yeti"}}},
 lycanitesmobs_jj_beastspawn_b_19={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="maka"}}},
 lycanitesmobs_jj_beastspawn_b_2={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="wraamon"}}},
 lycanitesmobs_jj_beastspawn_b_20={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="feradon"}}},
 lycanitesmobs_jj_beastspawn_b_21={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="epion"}}},
 lycanitesmobs_jj_beastspawn_b_3={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="manticore"}}},
 lycanitesmobs_jj_beastspawn_b_4={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="barghest"}}},
 lycanitesmobs_jj_beastspawn_b_5={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="conba"}}},
 lycanitesmobs_jj_beastspawn_b_6={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="warg"}}},
 lycanitesmobs_jj_beastspawn_b_7={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="kobold"}}},
 lycanitesmobs_jj_beastspawn_b_8={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="makaalpha"}}},
 lycanitesmobs_jj_beastspawn_b_9={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="salamander"}}},
 lycanitesmobs_jj_beasttreat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_blizzardcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_blizzardscepter={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_blood_chili={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_bloodleechcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_bloodleechscepter={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_bloodsummoningstaff={hasPattern=true,label="Blood Summoning Staff",tag={}},
 lycanitesmobs_jj_boulderblastcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_boulderblastscepter={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_brutespawn={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="lobber"}}},
 lycanitesmobs_jj_brutespawn_b_1={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="wildkin"}}},
 lycanitesmobs_jj_brutespawn_b_2={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="troll"}}},
 lycanitesmobs_jj_brutespawn_b_3={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="ettin"}}},
 lycanitesmobs_jj_brutetreat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_bucketooze={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_bucketpurelava={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_bulwark_burger={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_caecilian_ramen={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_chaosorbcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_cinderblade={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_cinderblade_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_cinderblade_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_cleansingcrystal={hasPattern=true,label="Cleansing Crystal",tag={}},
 lycanitesmobs_jj_clinkscythe={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_clinkscythe_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_clinkscythe_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_cooked_arisaur_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_cooked_aspid_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_cooked_cephignis_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_cooked_chupacabra_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_cooked_concapede_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_cooked_ika_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_cooked_joust_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_cooked_krake_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_cooked_maka_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_cooked_pinky_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_cooked_silex_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_cooked_yale_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_cooked_yeti_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_crystalshardcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_darklingskull={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_darklingskull_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_darklingskull_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_demoncrystal={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_demonicblastcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_demoniclightningscepter={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_demonspawn={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="behemoth"}}},
 lycanitesmobs_jj_demonspawn_b_1={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="belph"}}},
 lycanitesmobs_jj_demonspawn_b_2={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="pinky"}}},
 lycanitesmobs_jj_demonspawn_b_3={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="cacodemon"}}},
 lycanitesmobs_jj_demonspawn_b_4={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="rahovart"}}},
 lycanitesmobs_jj_demonstone={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_demonstone_slab={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_demonstone_slab_double={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_demonstone_stairs={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_demonstonebrick={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_demonstonebrick_fence={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_demonstonebrick_slab={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_demonstonebrick_stairs={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_demonstonebrick_wall={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_demonstonechiseled={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_demonstonepillar={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_demonstonepolished={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_demonstonetile={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_demonstonetile_slab={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_demonstonetile_stairs={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_demontreat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_desertcrystal={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_desertstone={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_desertstone_slab={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_desertstone_slab_double={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_desertstone_stairs={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_desertstonebrick={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_desertstonebrick_fence={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_desertstonebrick_slab={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_desertstonebrick_stairs={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_desertstonebrick_wall={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_desertstonechiseled={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_desertstonepillar={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_desertstonepolished={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_desertstonetile={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_desertstonetile_slab={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_desertstonetile_stairs={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_devil_lasagna={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_devilstarcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_djinncloud={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_djinncloud_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_djinncloud_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_doomfire={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_doomfireballcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_doomfirescepter={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_dragonspawn={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="quetzodracl"}}},
 lycanitesmobs_jj_dragonspawn_b_1={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="cockatrice"}}},
 lycanitesmobs_jj_dragonspawn_b_2={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="morock"}}},
 lycanitesmobs_jj_dragonspawn_b_3={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="ignibus"}}},
 lycanitesmobs_jj_dragonspawn_b_4={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="zoataur"}}},
 lycanitesmobs_jj_dragonspawn_b_5={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="remobra"}}},
 lycanitesmobs_jj_dragontreat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_eechetikarm={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_eechetikarm_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_eechetikarm_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_elementalspawn={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="spriggan"}}},
 lycanitesmobs_jj_elementalspawn_b_1={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="tremor"}}},
 lycanitesmobs_jj_elementalspawn_b_10={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="aegis"}}},
 lycanitesmobs_jj_elementalspawn_b_11={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="zephyr"}}},
 lycanitesmobs_jj_elementalspawn_b_12={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="djinn"}}},
 lycanitesmobs_jj_elementalspawn_b_13={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="eechetik"}}},
 lycanitesmobs_jj_elementalspawn_b_14={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="wraith"}}},
 lycanitesmobs_jj_elementalspawn_b_15={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="sylph"}}},
 lycanitesmobs_jj_elementalspawn_b_16={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="volcan"}}},
 lycanitesmobs_jj_elementalspawn_b_17={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="wisp"}}},
 lycanitesmobs_jj_elementalspawn_b_18={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="argus"}}},
 lycanitesmobs_jj_elementalspawn_b_19={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="nymph"}}},
 lycanitesmobs_jj_elementalspawn_b_2={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="vapula"}}},
 lycanitesmobs_jj_elementalspawn_b_20={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="xaphan"}}},
 lycanitesmobs_jj_elementalspawn_b_3={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="geonach"}}},
 lycanitesmobs_jj_elementalspawn_b_4={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="cinder"}}},
 lycanitesmobs_jj_elementalspawn_b_5={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="reiver"}}},
 lycanitesmobs_jj_elementalspawn_b_6={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="jengu"}}},
 lycanitesmobs_jj_elementalspawn_b_7={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="spectre"}}},
 lycanitesmobs_jj_elementalspawn_b_8={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="banshee"}}},
 lycanitesmobs_jj_elementalspawn_b_9={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="grue"}}},
 lycanitesmobs_jj_elementaltreat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_embercharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_entarm={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_entarm_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_entarm_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_equipment={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_equipment_infuser={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_equipmentforge_greater={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_equipmentforge_lesser={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_equipmentforge_master={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_explorers_risotto={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_faeboltcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_frostboltcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_frostboltscepter={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_frostcloud={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_frostfire={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_frostweb={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_frostwebcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_frostwebscepter={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_frostyfur={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_gammasphere={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_gammasphere_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_gammasphere_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_geistliver={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_geonachfist={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_geonachfist_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_geonachfist_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_geonachspear={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_geonachspear_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_geonachspear_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_goldscepterhead={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_grueclaw={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_grueclaw_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_grueclaw_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_halloweentreat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_hellfire={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_hellfireballcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_hellfirescepter={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_icefire={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_icefireballcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_icefirescepter={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_immunizer={hasPattern=true,label="Immunizer",tag={}},
 lycanitesmobs_jj_impspawn={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="gnekk"}}},
 lycanitesmobs_jj_impspawn_b_1={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="pixen"}}},
 lycanitesmobs_jj_impspawn_b_2={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="clink"}}},
 lycanitesmobs_jj_impspawn_b_3={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="arix"}}},
 lycanitesmobs_jj_impspawn_b_4={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="afrit"}}},
 lycanitesmobs_jj_imptreat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_ironaxehead={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_ironhilt={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_ironpaxel={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_ironpikejoint={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_ironrod={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_lapis_fish_and_chips={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_lifedraincharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_lifedrainscepter={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_lightballcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_lobdarklingscharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_lushcrystal={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_lushstone={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_lushstone_slab={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_lushstone_slab_double={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_lushstone_stairs={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_lushstonebrick={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_lushstonebrick_fence={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_lushstonebrick_slab={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_lushstonebrick_stairs={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_lushstonebrick_wall={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_lushstonechiseled={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_lushstonepillar={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_lushstonepolished={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_lushstonetile={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_lushstonetile_slab={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_lushstonetile_stairs={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_magmacharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_magmascepter={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_mobtoken={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_moss_pie={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_mudshotcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_mudshotscepter={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_ooze={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_pale_soup={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_paleo_salad={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_peaks_kebab={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_plantspawn={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="triffid"}}},
 lycanitesmobs_jj_plantspawn_b_1={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="treant"}}},
 lycanitesmobs_jj_plantspawn_b_2={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="ent"}}},
 lycanitesmobs_jj_plantspawn_b_3={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="shambler"}}},
 lycanitesmobs_jj_planttreat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_poisoncloud={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_poisongland={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_poisonraycharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_poisonrayscepter={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_poopcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_poopcloud={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_poopscepter={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_propolis={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_purelava={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_quickweb={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_quillcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_quillscepter={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_raw_arisaur_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_raw_aspid_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_raw_chupacabra_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_raw_concapede_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_raw_ika_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_raw_joust_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_raw_krake_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_raw_maka_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_raw_pinky_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_raw_silex_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_raw_yale_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_raw_yeti_meat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_reiverhorns={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_reiverhorns_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_reiverhorns_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_remobrawing={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_remobrawing_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_remobrawing_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_savagesummoningstaff={hasPattern=true,label="Savage Summoning Staff",tag={}},
 lycanitesmobs_jj_scorchfire={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_scorchfireballcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_scorchfirescepter={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_searing_taco={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_seashell_maki={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_shadowcrystal={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_shadowfire={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_shadowstone={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_shadowstone_slab={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_shadowstone_slab_double={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_shadowstone_stairs={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_shadowstonebrick={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_shadowstonebrick_fence={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_shadowstonebrick_slab={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_shadowstonebrick_stairs={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_shadowstonebrick_wall={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_shadowstonechiseled={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_shadowstonepillar={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_shadowstonepolished={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_shadowstonetile={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_shadowstonetile_slab={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_shadowstonetile_stairs={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_soulcubedemonic={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_soulcubeundead={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_soulgazer={hasPattern=true,label="Soulgazer",tag={}},
 lycanitesmobs_jj_soulkey={hasPattern=true,label="Soulkey",tag={}},
 lycanitesmobs_jj_soulkeydiamond={hasPattern=true,label="Diamond Soulkey",tag={}},
 lycanitesmobs_jj_soulkeyemerald={hasPattern=true,label="Emerald Soulkey",tag={}},
 lycanitesmobs_jj_soulstone={hasPattern=true,label="Soulstone",tag={}},
 lycanitesmobs_jj_soulstonedemonic={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_soulstonefreshwater={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_soulstoneinferno={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_soulstonemountain={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_soulstoneshadow={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_spectralboltcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_spectralboltscepter={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_spectretendril={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_spectretendril_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_spectretendril_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_sprigganheart={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_sprigganheart_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_sprigganheart_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_sprigganroot={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_sprigganroot_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_sprigganroot_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_stablesummoningstaff={hasPattern=true,label="Stable Summoning Staff",tag={}},
 lycanitesmobs_jj_sturdysummoningstaff={hasPattern=true,label="Sturdy Summoning Staff",tag={}},
 lycanitesmobs_jj_summoningpedestal={hasPattern=true,label="Summoning Pedestal",tag={}},
 lycanitesmobs_jj_summoningstaff={hasPattern=true,label="Summoning Staff",tag={}},
 lycanitesmobs_jj_sutiramustinger={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_sutiramustinger_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_sutiramustinger_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_sylphwing={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_sylphwing_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_sylphwing_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_throwingscythecharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_tricksterflarecharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_tropical_curry={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_tundracharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_tundrascepter={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_undeadspawn={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="wendigo"}}},
 lycanitesmobs_jj_undeadspawn_b_1={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="amalgalich"}}},
 lycanitesmobs_jj_undeadspawn_b_2={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="geist"}}},
 lycanitesmobs_jj_undeadspawn_b_3={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="ghoul"}}},
 lycanitesmobs_jj_undeadspawn_b_4={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="cryptkeeper"}}},
 lycanitesmobs_jj_undeadspawn_b_5={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="reaper"}}},
 lycanitesmobs_jj_undeadtreat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_uvaraptorskull={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_uvaraptorskull_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_uvaraptorskull_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_vapulacrystal={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_vapulacrystal_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_vapulacrystal_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_venomshotcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_ventoraptorskull={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_ventoraptorskull_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_ventoraptorskull_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_vespidstinger={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_vespidstinger_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_vespidstinger_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_veswax={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_wargskull={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_wargskull_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_wargskull_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_waterjetcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_waterjetscepter={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_wendigoantler={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_wendigoantler_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_wendigoantler_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_whirlwindcharge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_wintergift={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_wintergiftlarge={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_woodenhilt={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_woodenpaxel={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_woodenrod={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_wormspawn={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="crusk"}}},
 lycanitesmobs_jj_wormspawn_b_1={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="serpix"}}},
 lycanitesmobs_jj_wormspawn_b_2={hasPattern=false,label="",tag={CreatureInfoSpawnEgg={creaturename="gorger"}}},
 lycanitesmobs_jj_wormtreat={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_wraithsigil={hasPattern=false,label="",tag={}},
 lycanitesmobs_jj_wraithskull={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_wraithskull_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_wraithskull_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_xaphanspine={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_xaphanspine_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_xaphanspine_b_2={hasPattern=false,label="",tag={equipmentLevel=3}},
 lycanitesmobs_jj_zephyrblade={hasPattern=false,label="",tag={equipmentLevel=1}},
 lycanitesmobs_jj_zephyrblade_b_1={hasPattern=false,label="",tag={equipmentLevel=2}},
 lycanitesmobs_jj_zephyrblade_b_2={hasPattern=false,label="",tag={equipmentLevel=3}}
 }