return {
 farmory_jj_blowgun={hasPattern=true,label="Blowgun",tag=""},
 farmory_jj_crossbow={hasPattern=true,label="Crossbow",tag=""},
 farmory_jj_enderiumboots={hasPattern=true,label="Enderium Boots",tag=""},
 farmory_jj_enderiumchestplate={hasPattern=true,label="Enderium ChestPlate",tag=""},
 farmory_jj_enderiumhelmet={hasPattern=true,label="Enderium Helmet",tag=""},
 farmory_jj_enderiumleggings={hasPattern=true,label="Enderium Leggings",tag=""},
 farmory_jj_enderiumsword={hasPattern=true,label="§dEnderium Sword",tag=""},
 farmory_jj_longbow={hasPattern=true,label="Long Bow",tag=""},
 farmory_jj_reddiamondboots={hasPattern=true,label="Red Diamond Boots",tag=""},
 farmory_jj_reddiamondchestplate={hasPattern=true,label="Red Diamond ChestPlate",tag=""},
 farmory_jj_reddiamondhelmet={hasPattern=true,label="Red Diamond Helmet",tag=""},
 farmory_jj_reddiamondleggings={hasPattern=true,label="Red Diamond Leggings",tag=""},
 farmory_jj_reddiamondsword={hasPattern=true,label="§4Red Diamond Sword",tag=""},
 farmory_jj_terilliumaxe={hasPattern=false,label="",tag=""},
 farmory_jj_terilliumboots={hasPattern=false,label="",tag=""},
 farmory_jj_terilliumchestplate={hasPattern=false,label="",tag=""},
 farmory_jj_terilliumhelmet={hasPattern=false,label="",tag=""},
 farmory_jj_terilliumhoe={hasPattern=false,label="",tag=""},
 farmory_jj_terilliumleggings={hasPattern=false,label="",tag=""},
 farmory_jj_terilliumpickaxe={hasPattern=false,label="",tag=""},
 farmory_jj_terilliumshovel={hasPattern=false,label="",tag=""},
 farmory_jj_terilliumsword={hasPattern=false,label="",tag=""},
 fcl_jj_blueprinttable={hasPattern=true,label="Blueprint Table",tag=""},
 fcl_jj_workbench={hasPattern=true,label="Workbench",tag=""},
 fdecostuff_jj_andesite_slab_double={hasPattern=false,label="",tag=""},
 fdecostuff_jj_andesite_slab_half={hasPattern=true,label="Andesite Brick Slab",tag=""},
 fdecostuff_jj_andesitebrick={hasPattern=true,label="Andesite Brick",tag=""},
 fdecostuff_jj_andesitebrickcarved={hasPattern=true,label="Andesite Brick Carved",tag=""},
 fdecostuff_jj_andesitebrickcracked={hasPattern=false,label="",tag=""},
 fdecostuff_jj_andesitebrickmossy={hasPattern=true,label="Andesite Brick Mossy",tag=""},
 fdecostuff_jj_christmas_tree={hasPattern=true,label="Christmas Tree",tag=""},
 fdecostuff_jj_diorite_slab_double={hasPattern=false,label="",tag=""},
 fdecostuff_jj_diorite_slab_half={hasPattern=true,label="Diorite Brick Slab",tag=""},
 fdecostuff_jj_dioritebrick={hasPattern=true,label="Diorite Brick",tag=""},
 fdecostuff_jj_dioritebrickcarved={hasPattern=true,label="Diorite Brick Carved",tag=""},
 fdecostuff_jj_dioritebrickcracked={hasPattern=false,label="",tag=""},
 fdecostuff_jj_dioritebrickmossy={hasPattern=true,label="Diorite Brick Mossy",tag=""},
 fdecostuff_jj_endstone_slab_double={hasPattern=false,label="",tag=""},
 fdecostuff_jj_endstone_slab_half={hasPattern=true,label="End Stone Brick Slab",tag=""},
 fdecostuff_jj_endstonebrickcarved={hasPattern=true,label="End Stone Brick Carved",tag=""},
 fdecostuff_jj_endstonebrickcracked={hasPattern=false,label="",tag=""},
 fdecostuff_jj_endstonebrickmossy={hasPattern=true,label="End Stone Brick Mossy",tag=""},
 fdecostuff_jj_granite_slab_double={hasPattern=false,label="",tag=""},
 fdecostuff_jj_granite_slab_half={hasPattern=true,label="Granite Brick Slab",tag=""},
 fdecostuff_jj_granitebrick={hasPattern=true,label="Granite Brick",tag=""},
 fdecostuff_jj_granitebrickcarved={hasPattern=true,label="Granite Brick Carved",tag=""},
 fdecostuff_jj_granitebrickcracked={hasPattern=false,label="",tag=""},
 fdecostuff_jj_granitebrickmossy={hasPattern=true,label="Granite Brick Mossy",tag=""},
 ffactory_jj_barrel={hasPattern=true,label="Barrel",tag=""},
 ffactory_jj_ironfurnace={hasPattern=true,label="Iron Furnace",tag=""},
 ffactory_jj_lit_ironfurnace={hasPattern=false,label="",tag=""},
 ffactory_jj_lit_steampunkfurnace={hasPattern=false,label="",tag=""},
 ffactory_jj_steampunkfurnace={hasPattern=true,label="Steampunk Furnace",tag=""},
 ffoods_jj_applejam={hasPattern=true,label="Apple Jam",tag=""},
 ffoods_jj_applejamjar={hasPattern=true,label="Jar of Apple Jam",tag=""},
 ffoods_jj_appletoast={hasPattern=true,label="Toast with Apple Jam",tag=""},
 ffoods_jj_barley={hasPattern=false,label="",tag=""},
 ffoods_jj_barley_seeds={hasPattern=false,label="",tag=""},
 ffoods_jj_beer={hasPattern=false,label="",tag=""},
 ffoods_jj_beermug={hasPattern=true,label="Beer Mug",tag=""},
 ffoods_jj_cereals={hasPattern=true,label="Cereals",tag=""},
 ffoods_jj_cerealsbowl={hasPattern=true,label="Cereals Bowl",tag=""},
 ffoods_jj_chocolatecereals={hasPattern=true,label="Chocolate Cereals",tag=""},
 ffoods_jj_chocolatecerealsbowl={hasPattern=true,label="Chocolate Cereals Bowl",tag=""},
 ffoods_jj_flour={hasPattern=true,label="Flour",tag=""},
 ffoods_jj_kitchenknife={hasPattern=true,label="Kitchen Kinfe",tag=""},
 ffoods_jj_toast={hasPattern=true,label="Toast",tag=""},
 fmagic_jj_wfragment={hasPattern=true,label="§bWither Fragment",tag=""},
 fmagic_jj_wseed={hasPattern=true,label="Wither Seed",tag=""},
 fresource_jj_blazecoal={hasPattern=true,label="Blaze Coal",tag=""},
 fresource_jj_blazecoalblock={hasPattern=true,label="Blaze Coal Block",tag=""},
 fresource_jj_blazecoalore={hasPattern=false,label="",tag=""},
 fresource_jj_bronzeingot={hasPattern=true,label="Bronze Ingot",tag=""},
 fresource_jj_copperingot={hasPattern=false,label="",tag=""},
 fresource_jj_copperore={hasPattern=false,label="",tag=""},
 fresource_jj_enderiumblock={hasPattern=true,label="Enderium Block",tag=""},
 fresource_jj_enderiumingot={hasPattern=false,label="",tag=""},
 fresource_jj_enderiumore={hasPattern=false,label="",tag=""},
 fresource_jj_rawterillium={hasPattern=false,label="",tag=""},
 fresource_jj_reddiamond={hasPattern=false,label="",tag=""},
 fresource_jj_reddiamondblock={hasPattern=true,label="Red Diamond Block",tag=""},
 fresource_jj_reddiamondore={hasPattern=false,label="",tag=""},
 fresource_jj_terillium={hasPattern=true,label="§aTerillium",tag=""},
 fresource_jj_terilliumblock={hasPattern=true,label="Terillium Block",tag=""},
 fresource_jj_terilliumore={hasPattern=false,label="",tag=""},
 fresource_jj_tiningot={hasPattern=false,label="",tag=""},
 fresource_jj_tinore={hasPattern=false,label="",tag=""},
 frsm_jj_asphalt={hasPattern=true,label="Asphalt",tag=""},
 frsm_jj_asphalt2={hasPattern=true,label="Asphalt",tag=""},
 frsm_jj_asphalt2slab={hasPattern=true,label="Asphalt Slab",tag=""},
 frsm_jj_asphaltfull={hasPattern=true,label="Full Asphalt Block",tag=""},
 frsm_jj_asphaltslab={hasPattern=true,label="Asphalt Slab",tag=""},
 frsm_jj_bacon={hasPattern=false,label="",tag=""},
 frsm_jj_baconraw={hasPattern=true,label="Raw Bacon",tag=""},
 frsm_jj_bench1={hasPattern=true,label="Bench",tag=""},
 frsm_jj_bench1_1={hasPattern=true,label="Bench",tag=""},
 frsm_jj_bench1_2={hasPattern=true,label="Bench",tag=""},
 frsm_jj_bench1_3={hasPattern=true,label="Bench",tag=""},
 frsm_jj_brush={hasPattern=true,label="Brush",tag=""},
 frsm_jj_busstation={hasPattern=true,label="Bus Station",tag=""},
 frsm_jj_busstop={hasPattern=true,label="Bus Stop Sign",tag=""},
 frsm_jj_car1d={hasPattern=true,label="Deco Model Car",tag=""},
 frsm_jj_cheese={hasPattern=false,label="",tag=""},
 frsm_jj_cheesepie={hasPattern=true,label="Cheese Pie",tag=""},
 frsm_jj_cheesewhite={hasPattern=true,label="White Cheese",tag=""},
 frsm_jj_chimney={hasPattern=false,label="",tag=""},
 frsm_jj_chimney_jj_1={hasPattern=false,label="",tag=""},
 frsm_jj_chimney_jj_2={hasPattern=false,label="",tag=""},
 frsm_jj_chimney_jj_3={hasPattern=false,label="",tag=""},
 frsm_jj_chimney_jj_4={hasPattern=false,label="",tag=""},
 frsm_jj_chocolatebar={hasPattern=true,label="Chocolate Bar",tag=""},
 frsm_jj_chocolatebarwhite={hasPattern=true,label="White Chocolate Bar",tag=""},
 frsm_jj_chocolatecookie={hasPattern=true,label="Chocolate Cookie",tag=""},
 frsm_jj_chocolatemilk={hasPattern=true,label="Chocolate Milk",tag=""},
 frsm_jj_clock1={hasPattern=true,label="Clock (1)",tag=""},
 frsm_jj_clock1c={hasPattern=true,label="Clock (1c)",tag=""},
 frsm_jj_clock1w={hasPattern=true,label="Clock (1w)",tag=""},
 frsm_jj_clock2={hasPattern=false,label="",tag=""},
 frsm_jj_clock2c={hasPattern=false,label="",tag=""},
 frsm_jj_clock2w={hasPattern=false,label="",tag=""},
 frsm_jj_cobble1={hasPattern=true,label="Cobblestone",tag=""},
 frsm_jj_cobble10={hasPattern=true,label="Cobblestone",tag=""},
 frsm_jj_cobble10b={hasPattern=true,label="Cobblestone",tag=""},
 frsm_jj_cobble2={hasPattern=true,label="Cobblestone",tag=""},
 frsm_jj_cobble3={hasPattern=true,label="Cobblestone",tag=""},
 frsm_jj_cobble4={hasPattern=true,label="Cobblestone",tag=""},
 frsm_jj_cobble5={hasPattern=true,label="Cobblestone",tag=""},
 frsm_jj_cobble5b={hasPattern=true,label="CobbleStone",tag=""},
 frsm_jj_cobble6={hasPattern=true,label="CobbleStone",tag=""},
 frsm_jj_cobble6b={hasPattern=true,label="CobbleStone",tag=""},
 frsm_jj_cobble7={hasPattern=true,label="CobbleStone",tag=""},
 frsm_jj_cobble7b={hasPattern=true,label="CobbleStone",tag=""},
 frsm_jj_cobble8={hasPattern=true,label="CobbleStone",tag=""},
 frsm_jj_cobble8b={hasPattern=true,label="CobbleStone",tag=""},
 frsm_jj_cobble9={hasPattern=true,label="CobbleStone",tag=""},
 frsm_jj_cobble9b={hasPattern=true,label="CobbleStone",tag=""},
 frsm_jj_cookedegg={hasPattern=false,label="",tag=""},
 frsm_jj_crate={hasPattern=true,label="Crate",tag=""},
 frsm_jj_cup={hasPattern=true,label="Cup",tag=""},
 frsm_jj_cupwithcacao={hasPattern=true,label="Cacao Drink",tag=""},
 frsm_jj_decoblock1={hasPattern=true,label="tile.frsm:decoblock1.white.name",tag=""},
 frsm_jj_decoblock2={hasPattern=true,label="Deco Block (2)",tag=""},
 frsm_jj_donut={hasPattern=true,label="Donut",tag=""},
 frsm_jj_electric_pizza_oven={hasPattern=true,label="Electric Pizza Oven",tag=""},
 frsm_jj_fence1={hasPattern=true,label="Iron Fence",tag=""},
 frsm_jj_framedglowstone={hasPattern=true,label="Framed Glowstone",tag=""},
 frsm_jj_framedglowstone_jj_1={hasPattern=true,label="Framed Glowstone",tag=""},
 frsm_jj_framedglowstone_jj_2={hasPattern=true,label="Framed Glowstone",tag=""},
 frsm_jj_framedglowstone_jj_3={hasPattern=true,label="Framed Glowstone",tag=""},
 frsm_jj_framedglowstone_jj_4={hasPattern=true,label="Framed Glowstone",tag=""},
 frsm_jj_framedglowstone_jj_5={hasPattern=true,label="Framed Glowstone",tag=""},
 frsm_jj_fridge={hasPattern=true,label="Fridge",tag=""},
 frsm_jj_furnace1={hasPattern=false,label="",tag=""},
 frsm_jj_furnace1b={hasPattern=false,label="",tag=""},
 frsm_jj_hamburger={hasPattern=true,label="Hamburger",tag=""},
 frsm_jj_iron_barrel={hasPattern=false,label="",tag=""},
 frsm_jj_ironsaw={hasPattern=true,label="Iron Saw",tag=""},
 frsm_jj_jar={hasPattern=true,label="Glass Jar",tag=""},
 frsm_jj_kd1={hasPattern=true,label="Kitchen Deco (1)",tag=""},
 frsm_jj_kd2={hasPattern=true,label="Kitchen Deco (2)",tag=""},
 frsm_jj_key={hasPattern=false,label="",tag=""},
 frsm_jj_keyboard={hasPattern=true,label="Keyboard",tag=""},
 frsm_jj_lamp={hasPattern=true,label="Lamp",tag=""},
 frsm_jj_lamp_jj_1={hasPattern=true,label="Lamp",tag=""},
 frsm_jj_lamp_jj_10={hasPattern=true,label="Lamp",tag=""},
 frsm_jj_lamp_jj_11={hasPattern=true,label="Lamp",tag=""},
 frsm_jj_lamp_jj_12={hasPattern=true,label="Lamp",tag=""},
 frsm_jj_lamp_jj_13={hasPattern=true,label="Lamp",tag=""},
 frsm_jj_lamp_jj_14={hasPattern=true,label="Lamp",tag=""},
 frsm_jj_lamp_jj_15={hasPattern=true,label="Lamp",tag=""},
 frsm_jj_lamp_jj_2={hasPattern=false,label="",tag=""},
 frsm_jj_lamp_jj_3={hasPattern=false,label="",tag=""},
 frsm_jj_lamp_jj_4={hasPattern=false,label="",tag=""},
 frsm_jj_lamp_jj_5={hasPattern=false,label="",tag=""},
 frsm_jj_lamp_jj_6={hasPattern=false,label="",tag=""},
 frsm_jj_lamp_jj_7={hasPattern=false,label="",tag=""},
 frsm_jj_lamp_jj_8={hasPattern=false,label="",tag=""},
 frsm_jj_lamp_jj_9={hasPattern=false,label="",tag=""},
 frsm_jj_lampoff={hasPattern=false,label="",tag=""},
 frsm_jj_lampoff_jj_1={hasPattern=false,label="",tag=""},
 frsm_jj_lampoff_jj_10={hasPattern=false,label="",tag=""},
 frsm_jj_lampoff_jj_11={hasPattern=false,label="",tag=""},
 frsm_jj_lampoff_jj_12={hasPattern=false,label="",tag=""},
 frsm_jj_lampoff_jj_13={hasPattern=false,label="",tag=""},
 frsm_jj_lampoff_jj_14={hasPattern=false,label="",tag=""},
 frsm_jj_lampoff_jj_15={hasPattern=false,label="",tag=""},
 frsm_jj_lampoff_jj_2={hasPattern=false,label="",tag=""},
 frsm_jj_lampoff_jj_3={hasPattern=false,label="",tag=""},
 frsm_jj_lampoff_jj_4={hasPattern=false,label="",tag=""},
 frsm_jj_lampoff_jj_5={hasPattern=false,label="",tag=""},
 frsm_jj_lampoff_jj_6={hasPattern=false,label="",tag=""},
 frsm_jj_lampoff_jj_7={hasPattern=false,label="",tag=""},
 frsm_jj_lampoff_jj_8={hasPattern=false,label="",tag=""},
 frsm_jj_lampoff_jj_9={hasPattern=false,label="",tag=""},
 frsm_jj_laptop={hasPattern=true,label="Laptop",tag=""},
 frsm_jj_laptop_black={hasPattern=true,label="Black Laptop",tag=""},
 frsm_jj_laptop_blue={hasPattern=true,label="Blue Laptop",tag=""},
 frsm_jj_laptop_green={hasPattern=true,label="Green Laptop",tag=""},
 frsm_jj_laptop_red={hasPattern=true,label="Red Laptop",tag=""},
 frsm_jj_laptop_white={hasPattern=true,label="White Laptop",tag=""},
 frsm_jj_laptopmainboard={hasPattern=true,label="Laptop Mainboard",tag=""},
 frsm_jj_model_rail={hasPattern=true,label="Model Rail",tag=""},
 frsm_jj_model_railturn={hasPattern=true,label="Model Rail Turn",tag=""},
 frsm_jj_model_station={hasPattern=true,label="Model Station (1)",tag=""},
 frsm_jj_model_station2={hasPattern=true,label="Model Station (2)",tag=""},
 frsm_jj_model_station3={hasPattern=true,label="Model Station (3)",tag=""},
 frsm_jj_nesr={hasPattern=true,label="NESR - Not Existing Stuff Replace",tag=""},
 frsm_jj_officechair={hasPattern=true,label="Officechair",tag=""},
 frsm_jj_paintbucket={hasPattern=true,label="Paint Bucket",tag=""},
 frsm_jj_paintbucket_jj_1={hasPattern=true,label="Paint Bucket",tag=""},
 frsm_jj_paintbucket_jj_10={hasPattern=true,label="Paint Bucket",tag=""},
 frsm_jj_paintbucket_jj_11={hasPattern=true,label="Paint Bucket",tag=""},
 frsm_jj_paintbucket_jj_12={hasPattern=true,label="Paint Bucket",tag=""},
 frsm_jj_paintbucket_jj_13={hasPattern=true,label="Paint Bucket",tag=""},
 frsm_jj_paintbucket_jj_14={hasPattern=true,label="Paint Bucket",tag=""},
 frsm_jj_paintbucket_jj_15={hasPattern=true,label="Paint Bucket",tag=""},
 frsm_jj_paintbucket_jj_2={hasPattern=true,label="Paint Bucket",tag=""},
 frsm_jj_paintbucket_jj_3={hasPattern=true,label="Paint Bucket",tag=""},
 frsm_jj_paintbucket_jj_4={hasPattern=true,label="Paint Bucket",tag=""},
 frsm_jj_paintbucket_jj_5={hasPattern=true,label="Paint Bucket",tag=""},
 frsm_jj_paintbucket_jj_6={hasPattern=true,label="Paint Bucket",tag=""},
 frsm_jj_paintbucket_jj_7={hasPattern=true,label="Paint Bucket",tag=""},
 frsm_jj_paintbucket_jj_8={hasPattern=true,label="Paint Bucket",tag=""},
 frsm_jj_paintbucket_jj_9={hasPattern=true,label="Paint Bucket",tag=""},
 frsm_jj_paintset0={hasPattern=true,label="White Paint Set",tag=""},
 frsm_jj_paintset1={hasPattern=true,label="Orange Paint Set",tag=""},
 frsm_jj_paintset10={hasPattern=true,label="Purple Paint Set",tag=""},
 frsm_jj_paintset11={hasPattern=true,label="Blue Paint Set",tag=""},
 frsm_jj_paintset12={hasPattern=true,label="Brown Paint Set",tag=""},
 frsm_jj_paintset13={hasPattern=true,label="Green Paint Set",tag=""},
 frsm_jj_paintset14={hasPattern=true,label="Red Paint Set",tag=""},
 frsm_jj_paintset15={hasPattern=true,label="Black Paint Set",tag=""},
 frsm_jj_paintset16={hasPattern=true,label="Customisable Paint Set",tag=""},
 frsm_jj_paintset2={hasPattern=true,label="Magenta Paint Set",tag=""},
 frsm_jj_paintset3={hasPattern=true,label="Light Blue Paint Set",tag=""},
 frsm_jj_paintset4={hasPattern=true,label="Yellow Paint Set",tag=""},
 frsm_jj_paintset5={hasPattern=true,label="Lime Paint Set",tag=""},
 frsm_jj_paintset6={hasPattern=true,label="Pink Paint Set",tag=""},
 frsm_jj_paintset7={hasPattern=true,label="Gray Paint Set",tag=""},
 frsm_jj_paintset8={hasPattern=true,label="Light Gray Paint Set",tag=""},
 frsm_jj_paintset9={hasPattern=true,label="Cyan Paint Set",tag=""},
 frsm_jj_palet1x1={hasPattern=false,label="",tag=""},
 frsm_jj_palet1x1_1={hasPattern=false,label="",tag=""},
 frsm_jj_palet1x1_2={hasPattern=false,label="",tag=""},
 frsm_jj_pchardware1={hasPattern=true,label="Desktop Computer Hardware",tag=""},
 frsm_jj_pchardware2={hasPattern=true,label="Monitor, Keyboard and Mouse",tag=""},
 frsm_jj_pcmainboard={hasPattern=true,label="Desktop Computer Mainboard",tag=""},
 frsm_jj_pillar1={hasPattern=true,label="Quartz Pillar",tag=""},
 frsm_jj_pillar1_bottom={hasPattern=true,label="Quartz Pillar Bottom",tag=""},
 frsm_jj_pillar1_top={hasPattern=true,label="Quartz Pillar Top",tag=""},
 frsm_jj_pizza={hasPattern=true,label="Pizza",tag=""},
 frsm_jj_placeholder={hasPattern=false,label="",tag=""},
 frsm_jj_planks_oak={hasPattern=false,label="",tag=""},
 frsm_jj_potatochipsbag={hasPattern=true,label="Potato Chips Bag",tag=""},
 frsm_jj_potatochipscheese={hasPattern=true,label="Potato Chips with Cheese",tag=""},
 frsm_jj_potatochipstomato={hasPattern=true,label="item.frsm:potatochipstomato.name",tag=""},
 frsm_jj_printer={hasPattern=true,label="Printer",tag=""},
 frsm_jj_prozessor={hasPattern=true,label="Single-Core Processor",tag=""},
 frsm_jj_prozessor2={hasPattern=true,label="Dual-Core Processor",tag=""},
 frsm_jj_prozessor4={hasPattern=true,label="Quad-Core Processor",tag=""},
 frsm_jj_radio1={hasPattern=true,label="Radio (1)",tag=""},
 frsm_jj_radio2={hasPattern=true,label="Radio (2)",tag=""},
 frsm_jj_redstoneinput={hasPattern=true,label="Redstone Input",tag=""},
 frsm_jj_roadsign1={hasPattern=false,label="",tag=""},
 frsm_jj_roadsign2={hasPattern=false,label="",tag=""},
 frsm_jj_roadsign3={hasPattern=false,label="",tag=""},
 frsm_jj_roadsign4={hasPattern=false,label="",tag=""},
 frsm_jj_roadsign5={hasPattern=false,label="",tag=""},
 frsm_jj_roadsign6={hasPattern=false,label="",tag=""},
 frsm_jj_salami={hasPattern=true,label="Ham",tag=""},
 frsm_jj_shelf1={hasPattern=true,label="Shelf (1)",tag=""},
 frsm_jj_status={hasPattern=false,label="",tag=""},
 frsm_jj_stonelightbox={hasPattern=true,label="Stone Light Box",tag=""},
 frsm_jj_stonemug={hasPattern=true,label="Stone Mug",tag=""},
 frsm_jj_stonemugwithbeer={hasPattern=true,label="Stone Mug with Beer",tag=""},
 frsm_jj_stoneslabpillar={hasPattern=true,label="Stone Slab Pillar",tag=""},
 frsm_jj_stove={hasPattern=true,label="Stove",tag=""},
 frsm_jj_stove_pipe={hasPattern=true,label="Stove Pipe",tag=""},
 frsm_jj_streetlamp_base={hasPattern=true,label="Street Lamp Base",tag=""},
 frsm_jj_streetlamp_lamp={hasPattern=true,label="Street Lamp",tag=""},
 frsm_jj_streetlamp_post={hasPattern=true,label="Street Lamp Post",tag=""},
 frsm_jj_tbm={hasPattern=true,label="TBM - Test Block Model (1)",tag=""},
 frsm_jj_tbm2={hasPattern=true,label="Test Block Model (2)",tag=""},
 frsm_jj_tbm3={hasPattern=true,label="Test Block Model (3)",tag=""},
 frsm_jj_tiles={hasPattern=false,label="",tag=""},
 frsm_jj_tiles2={hasPattern=false,label="",tag=""},
 frsm_jj_tiles3={hasPattern=false,label="",tag=""},
 frsm_jj_tiles4={hasPattern=false,label="",tag=""},
 frsm_jj_tilesempty={hasPattern=false,label="",tag=""},
 frsm_jj_toaster={hasPattern=true,label="Toaster",tag=""},
 frsm_jj_tomato={hasPattern=true,label="Tomato",tag=""},
 frsm_jj_tomatojar={hasPattern=true,label="Tomato Jar",tag=""},
 frsm_jj_tomatoplant={hasPattern=false,label="",tag=""},
 frsm_jj_tomatoseeds={hasPattern=true,label="Tomato Seeds",tag=""},
 frsm_jj_tomatosoup={hasPattern=true,label="Tomato Soup",tag=""},
 frsm_jj_trashcan={hasPattern=true,label="Trashcan",tag=""},
 frsm_jj_tree_pot={hasPattern=false,label="",tag=""},
 frsm_jj_tree_pot_jj_1={hasPattern=false,label="",tag=""},
 frsm_jj_tree_pot_jj_10={hasPattern=false,label="",tag=""},
 frsm_jj_tree_pot_jj_11={hasPattern=false,label="",tag=""},
 frsm_jj_tree_pot_jj_12={hasPattern=false,label="",tag=""},
 frsm_jj_tree_pot_jj_13={hasPattern=false,label="",tag=""},
 frsm_jj_tree_pot_jj_14={hasPattern=false,label="",tag=""},
 frsm_jj_tree_pot_jj_15={hasPattern=false,label="",tag=""},
 frsm_jj_tree_pot_jj_2={hasPattern=false,label="",tag=""},
 frsm_jj_tree_pot_jj_3={hasPattern=false,label="",tag=""},
 frsm_jj_tree_pot_jj_4={hasPattern=false,label="",tag=""},
 frsm_jj_tree_pot_jj_5={hasPattern=false,label="",tag=""},
 frsm_jj_tree_pot_jj_6={hasPattern=false,label="",tag=""},
 frsm_jj_tree_pot_jj_7={hasPattern=false,label="",tag=""},
 frsm_jj_tree_pot_jj_8={hasPattern=false,label="",tag=""},
 frsm_jj_tree_pot_jj_9={hasPattern=false,label="",tag=""},
 frsm_jj_tvcontroller={hasPattern=true,label="TV Controller",tag=""},
 frsm_jj_tvl={hasPattern=true,label="TV Large",tag=""},
 frsm_jj_tvl_1={hasPattern=true,label="TV Large (alt)",tag=""},
 frsm_jj_tvm={hasPattern=true,label="TV Medium",tag=""},
 frsm_jj_tvs={hasPattern=true,label="TV Small (1)",tag=""},
 frsm_jj_tvs2={hasPattern=false,label="",tag=""},
 frsm_jj_tvscreenlarge={hasPattern=false,label="",tag=""},
 frsm_jj_tvscreenmedium={hasPattern=true,label="TV Screen Medium",tag=""},
 frsm_jj_tvscreensmall={hasPattern=true,label="TV Screen Small",tag=""},
 frsm_jj_upgradekit={hasPattern=true,label="UpGrade Kit",tag=""},
 frsm_jj_vendingmashine={hasPattern=true,label="Vending Mashine",tag=""},
 frsm_jj_washingmashine={hasPattern=true,label="Washing Mashine",tag=""},
 frsm_jj_window1={hasPattern=true,label="Window (1)",tag=""},
 frsm_jj_woodenlightbox={hasPattern=true,label="Wooden Light Box",tag=""},
 fvtm_jj_adj_sign={hasPattern=false,label="",tag=""},
 fvtm_jj_constructor_center={hasPattern=false,label="",tag=""},
 fvtm_jj_constructor_controller={hasPattern=true,label="Constructor Controller",tag=""},
 fvtm_jj_constructor_remote={hasPattern=true,label="Constructor Remote Controller",tag=""},
 fvtm_jj_consumable={hasPattern=false,label="",tag=""},
 fvtm_jj_container={hasPattern=false,label="",tag="({FVTM=Container= generic=container_large, fvtm_container= {SelectedTexture= 0}})"},
 fvtm_jj_container_b_1={hasPattern=false,label="",tag="({FVTM=Container= generic=container_large, fvtm_container= {SelectedTexture= 1}})"},
 fvtm_jj_container_b_2={hasPattern=false,label="",tag="({FVTM=Container= generic=container_large, fvtm_container= {SelectedTexture= 2}})"},
 fvtm_jj_container_b_3={hasPattern=false,label="",tag="({FVTM=Container= generic=container_medium, fvtm_container= {SelectedTexture= 0}})"},
 fvtm_jj_container_b_4={hasPattern=false,label="",tag="({FVTM=Container= generic=container_medium, fvtm_container= {SelectedTexture= 1}})"},
 fvtm_jj_container_b_5={hasPattern=false,label="",tag="({FVTM=Container= generic=container_medium, fvtm_container= {SelectedTexture= 2}})"},
 fvtm_jj_container_b_6={hasPattern=false,label="",tag="({FVTM=Container= hcp=medium, fvtm_container= {SelectedTexture= 0}})"},
 fvtm_jj_container_b_7={hasPattern=false,label="",tag="({FVTM=Container= hcp=medium_fluid, fvtm_container= {SelectedTexture= 0}})"},
 fvtm_jj_container_b_8={hasPattern=false,label="",tag="({FVTM=Container= hcp=medium_refrigerator, fvtm_container= {SelectedTexture= 0}})"},
 fvtm_jj_container_block={hasPattern=false,label="",tag=""},
 fvtm_jj_cyl_sign={hasPattern=false,label="",tag=""},
 fvtm_jj_display_block={hasPattern=false,label="",tag=""},
 fvtm_jj_fluid_pipe={hasPattern=true,label="Generic FVTM Fluid Pipe",tag=""},
 fvtm_jj_fluid_pipe_jj_1={hasPattern=true,label="Generic FVTM Fluid Pipe",tag=""},
 fvtm_jj_fluid_pipe_jj_10={hasPattern=true,label="Generic FVTM Fluid Pipe",tag=""},
 fvtm_jj_fluid_pipe_jj_11={hasPattern=true,label="Generic FVTM Fluid Pipe",tag=""},
 fvtm_jj_fluid_pipe_jj_12={hasPattern=true,label="Generic FVTM Fluid Pipe",tag=""},
 fvtm_jj_fluid_pipe_jj_13={hasPattern=true,label="Generic FVTM Fluid Pipe",tag=""},
 fvtm_jj_fluid_pipe_jj_14={hasPattern=true,label="Generic FVTM Fluid Pipe",tag=""},
 fvtm_jj_fluid_pipe_jj_15={hasPattern=true,label="Generic FVTM Fluid Pipe",tag=""},
 fvtm_jj_fluid_pipe_jj_2={hasPattern=true,label="Generic FVTM Fluid Pipe",tag=""},
 fvtm_jj_fluid_pipe_jj_3={hasPattern=true,label="Generic FVTM Fluid Pipe",tag=""},
 fvtm_jj_fluid_pipe_jj_4={hasPattern=true,label="Generic FVTM Fluid Pipe",tag=""},
 fvtm_jj_fluid_pipe_jj_5={hasPattern=true,label="Generic FVTM Fluid Pipe",tag=""},
 fvtm_jj_fluid_pipe_jj_6={hasPattern=true,label="Generic FVTM Fluid Pipe",tag=""},
 fvtm_jj_fluid_pipe_jj_7={hasPattern=true,label="Generic FVTM Fluid Pipe",tag=""},
 fvtm_jj_fluid_pipe_jj_8={hasPattern=true,label="Generic FVTM Fluid Pipe",tag=""},
 fvtm_jj_fluid_pipe_jj_9={hasPattern=true,label="Generic FVTM Fluid Pipe",tag=""},
 fvtm_jj_material={hasPattern=false,label="",tag="({FVTM=Material= generic=canister})"},
 fvtm_jj_material_b_1={hasPattern=false,label="",tag="({FVTM=Material= generic=diesel_canister, FuelContent= 0.0})"},
 fvtm_jj_material_b_2={hasPattern=false,label="",tag="({FVTM=Material= generic=diesel_canister, FuelContent= 256.0})"},
 fvtm_jj_material_b_3={hasPattern=false,label="",tag="({FVTM=Material= generic=petroleum_canister, FuelContent= 0.0})"},
 fvtm_jj_material_b_4={hasPattern=false,label="",tag="({FVTM=Material= generic=petroleum_canister, FuelContent= 250.0})"},
 fvtm_jj_material_b_5={hasPattern=false,label="",tag="({FVTM=Material= generic=rubber})"},
 fvtm_jj_material_b_6={hasPattern=false,label="",tag="({FVTM=Material= generic=steel_ingot})"},
 fvtm_jj_material_b_7={hasPattern=false,label="",tag="({FVTM=Material= generic=steel_plate})"},
 fvtm_jj_material_b_8={hasPattern=false,label="",tag="({VehicleKeyCreator= 00000000-0000-0000-0000-000000000000, FVTM=Material= generic=goldkey, VehicleKeyType= 0 as byte, VehicleKeyCode= 958facdc})"},
 fvtm_jj_material_b_9={hasPattern=false,label="",tag="({VehicleKeyCreator= 00000000-0000-0000-0000-000000000000, FVTM=Material= generic=key, VehicleKeyType= 0 as byte, VehicleKeyCode= 0bfe6fed})"},
 fvtm_jj_part={hasPattern=false,label="",tag="({FVTM=Part= fvp=ab1_doors})"},
 fvtm_jj_part_b_1={hasPattern=false,label="",tag="({FVTM=Part= fvp=ab1_driver_seat})"},
 fvtm_jj_part_b_10={hasPattern=false,label="",tag="({FVTM=Part= fvp=c1r1_steering_wheel})"},
 fvtm_jj_part_b_11={hasPattern=false,label="",tag="({FVTM=Part= fvp=c1r1t1_wheel})"},
 fvtm_jj_part_b_12={hasPattern=false,label="",tag="({FVTM=Part= fvp=c1r1t2_wheel})"},
 fvtm_jj_part_b_13={hasPattern=false,label="",tag="({FVTM=Part= fvp=c2_interior})"},
 fvtm_jj_part_b_14={hasPattern=false,label="",tag="({FVTM=Part= fvp=c2_steering_wheel})"},
 fvtm_jj_part_b_15={hasPattern=false,label="",tag="({FVTM=Part= fvp=c2r2t1_wheel})"},
 fvtm_jj_part_b_16={hasPattern=false,label="",tag="({FVTM=Part= fvp=c4z1_cargospace})"},
 fvtm_jj_part_b_17={hasPattern=false,label="",tag="({FVTM=Part= fvp=c4z1_interior})"},
 fvtm_jj_part_b_18={hasPattern=false,label="",tag="({FVTM=Part= fvp=c4z1_seats})"},
 fvtm_jj_part_b_19={hasPattern=false,label="",tag="({FVTM=Part= fvp=c4z1_steering_wheel})"},
 fvtm_jj_part_b_2={hasPattern=false,label="",tag="({FVTM=Part= fvp=ab1_engine})"},
 fvtm_jj_part_b_20={hasPattern=false,label="",tag="({FVTM=Part= fvp=c4z1_wheel})"},
 fvtm_jj_part_b_21={hasPattern=false,label="",tag="({FVTM=Part= fvp=c5_back_lights})"},
 fvtm_jj_part_b_22={hasPattern=false,label="",tag="({FVTM=Part= fvp=c5_front_lights})"},
 fvtm_jj_part_b_23={hasPattern=false,label="",tag="({FVTM=Part= fvp=c5_interior})"},
 fvtm_jj_part_b_24={hasPattern=false,label="",tag="({FVTM=Part= fvp=c5_seats})"},
 fvtm_jj_part_b_25={hasPattern=false,label="",tag="({FVTM=Part= fvp=c5_steering_wheel})"},
 fvtm_jj_part_b_26={hasPattern=false,label="",tag="({FVTM=Part= fvp=c5_wheel})"},
 fvtm_jj_part_b_27={hasPattern=false,label="",tag="({FVTM=Part= fvp=c7_doors})"},
 fvtm_jj_part_b_28={hasPattern=false,label="",tag="({FVTM=Part= fvp=c7_fuel_tank})"},
 fvtm_jj_part_b_29={hasPattern=false,label="",tag="({FVTM=Part= fvp=c7_hood})"},
 fvtm_jj_part_b_3={hasPattern=false,label="",tag="({FVTM=Part= fvp=ab1_lights})"},
 fvtm_jj_part_b_30={hasPattern=false,label="",tag="({FVTM=Part= fvp=c7_interior})"},
 fvtm_jj_part_b_31={hasPattern=false,label="",tag="({FVTM=Part= fvp=c7_seats})"},
 fvtm_jj_part_b_32={hasPattern=false,label="",tag="({FVTM=Part= fvp=c7_steering_wheel})"},
 fvtm_jj_part_b_33={hasPattern=false,label="",tag="({FVTM=Part= fvp=c7_wheel})"},
 fvtm_jj_part_b_34={hasPattern=false,label="",tag="({FVTM=Part= fvp=c8_doors})"},
 fvtm_jj_part_b_35={hasPattern=false,label="",tag="({FVTM=Part= fvp=c8_interior})"},
 fvtm_jj_part_b_36={hasPattern=false,label="",tag="({FVTM=Part= fvp=c8_lights})"},
 fvtm_jj_part_b_37={hasPattern=false,label="",tag="({FVTM=Part= fvp=c8_phwheel})"},
 fvtm_jj_part_b_38={hasPattern=false,label="",tag="({FVTM=Part= fvp=c8_seats})"},
 fvtm_jj_part_b_39={hasPattern=false,label="",tag="({FVTM=Part= fvp=c8_steering_wheel})"},
 fvtm_jj_part_b_4={hasPattern=false,label="",tag="({FVTM=Part= fvp=ab1_passenger_seats})"},
 fvtm_jj_part_b_40={hasPattern=false,label="",tag="({FVTM=Part= fvp=engine_c4z1i4})"},
 fvtm_jj_part_b_41={hasPattern=false,label="",tag="({FVTM=Part= fvp=engine_c7i4})"},
 fvtm_jj_part_b_42={hasPattern=false,label="",tag="({FVTM=Part= fvp=ot1_back_wheel})"},
 fvtm_jj_part_b_43={hasPattern=false,label="",tag="({FVTM=Part= fvp=ot1_front_seats})"},
 fvtm_jj_part_b_44={hasPattern=false,label="",tag="({FVTM=Part= fvp=ot1_front_wheel})"},
 fvtm_jj_part_b_45={hasPattern=false,label="",tag="({FVTM=Part= fvp=ot1_logtransport})"},
 fvtm_jj_part_b_46={hasPattern=false,label="",tag="({FVTM=Part= fvp=ot1_steering_wheel})"},
 fvtm_jj_part_b_47={hasPattern=false,label="",tag="({FVTM=Part= fvp=ot1_type2})"},
 fvtm_jj_part_b_48={hasPattern=false,label="",tag="({FVTM=Part= fvp=ot1_type3})"},
 fvtm_jj_part_b_49={hasPattern=false,label="",tag="({FVTM=Part= fvp=t1_back_wheel})"},
 fvtm_jj_part_b_5={hasPattern=false,label="",tag="({FVTM=Part= fvp=ab1_steering_wheel})"},
 fvtm_jj_part_b_50={hasPattern=false,label="",tag="({FVTM=Part= fvp=t1_deflector})"},
 fvtm_jj_part_b_51={hasPattern=false,label="",tag="({FVTM=Part= fvp=t1_driver_seat})"},
 fvtm_jj_part_b_52={hasPattern=false,label="",tag="({FVTM=Part= fvp=t1_front_seats})"},
 fvtm_jj_part_b_53={hasPattern=false,label="",tag="({FVTM=Part= fvp=t1_front_wheel})"},
 fvtm_jj_part_b_54={hasPattern=false,label="",tag="({FVTM=Part= fvp=t1_front_window})"},
 fvtm_jj_part_b_55={hasPattern=false,label="",tag="({FVTM=Part= fvp=t1_fuelgauge})"},
 fvtm_jj_part_b_56={hasPattern=false,label="",tag="({FVTM=Part= fvp=t1_snowplow})"},
 fvtm_jj_part_b_57={hasPattern=false,label="",tag="({FVTM=Part= fvp=t1_steering_wheel})"},
 fvtm_jj_part_b_58={hasPattern=false,label="",tag="({FVTM=Part= fvp=t1_trailer_connector})"},
 fvtm_jj_part_b_59={hasPattern=false,label="",tag="({FVTM=Part= fvp=t1_type1_cargoupgrade})"},
 fvtm_jj_part_b_6={hasPattern=false,label="",tag="({FVTM=Part= fvp=c1r1_back_seats})"},
 fvtm_jj_part_b_60={hasPattern=false,label="",tag="({FVTM=Part= fvp=t1_type2_cargoupgrade})"},
 fvtm_jj_part_b_61={hasPattern=false,label="",tag="({FVTM=Part= fvp=t1_type4_cargoupgrade})"},
 fvtm_jj_part_b_62={hasPattern=false,label="",tag="({FVTM=Part= fvp=t1_type5_cargoupgrade})"},
 fvtm_jj_part_b_63={hasPattern=false,label="",tag="({FVTM=Part= fvp=t2r1t1_wheel})"},
 fvtm_jj_part_b_64={hasPattern=false,label="",tag="({FVTM=Part= generic=engine})"},
 fvtm_jj_part_b_65={hasPattern=false,label="",tag="({FVTM=Part= generic=engine2})"},
 fvtm_jj_part_b_66={hasPattern=false,label="",tag="({FVTM=Part= generic=fuel_tank})"},
 fvtm_jj_part_b_7={hasPattern=false,label="",tag="({FVTM=Part= fvp=c1r1_front_seats})"},
 fvtm_jj_part_b_8={hasPattern=false,label="",tag="({FVTM=Part= fvp=c1r1_interior})"},
 fvtm_jj_part_b_9={hasPattern=false,label="",tag="({FVTM=Part= fvp=c1r1_lights})"},
 fvtm_jj_smeltery={hasPattern=false,label="",tag=""},
 fvtm_jj_vehicles={hasPattern=false,label="",tag="({FVTM=Vehicle= fvp=ab1})"},
 fvtm_jj_vehicles_b_1={hasPattern=false,label="",tag="({FVTM=Vehicle= fvp=c1r1})"},
 fvtm_jj_vehicles_b_10={hasPattern=false,label="",tag="({PresetKey= fvtm=fvp/c1r1_green, PresetCreatorUUID= 01e4af9b-2a30-471e-addf-f6338ffce04b, fvtm_vehicle= {SpawnedKeys= 0, SelectedTexture= 0, SecondaryRed= 66, DoorsOpen= 0b, CustomTexture= minecraft=, LightsState= 0, SecondaryBlue= 66, PrimaryGreen= 45, Locked= 0b, IsTextureExternal= 0b, Parts= [{UsedAs= back_seats, FVTM=Part= fvp=c1r1_back_seats, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= engine, FVTM=Part= generic=engine2, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft=, EngineOn= 0b}}, {UsedAs= front_seats, FVTM=Part= fvp=c1r1_front_seats, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= fuel_tank, FVTM=Part= generic=fuel_tank, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, FuelTankContent= 0.0d, CustomTexture= minecraft={}}, {UsedAs= interior, FVTM=Part= fvp=c1r1_interior, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= left_back_wheel, FVTM=Part= fvp=c1r1t1_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= left_front_wheel, FVTM=Part= fvp=c1r1t1_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= lights, FVTM=Part= fvp=c1r1_lights, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= right_back_wheel, FVTM=Part= fvp=c1r1t1_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= right_front_wheel, FVTM=Part= fvp=c1r1t1_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= steering_wheel, FVTM=Part= fvp=c1r1_steering_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}], PrimaryBlue= 38, PrimaryRed= 25, SecondaryGreen= 66}, PresetCreator= FEX___96, PresetCreated= 1520339357834, FVTM=Vehicle= fvp=c1r1})"},
 fvtm_jj_vehicles_b_11={hasPattern=false,label="",tag="({PresetKey= fvtm=fvp/c1r1_red, PresetCreatorUUID= 01e4af9b-2a30-471e-addf-f6338ffce04b, fvtm_vehicle= {SpawnedKeys= 0, SelectedTexture= 0, SecondaryRed= 66, DoorsOpen= 0b, CustomTexture= minecraft=, LightsState= 0, SecondaryBlue= 66, PrimaryGreen= 16, Locked= 0b, IsTextureExternal= 0b, Parts= [{UsedAs= back_seats, FVTM=Part= fvp=c1r1_back_seats, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= front_seats, FVTM=Part= fvp=c1r1_front_seats, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= fuel_tank, FVTM=Part= generic=fuel_tank, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, FuelTankContent= 0.0d, CustomTexture= minecraft={}}, {UsedAs= interior, FVTM=Part= fvp=c1r1_interior, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= left_back_wheel, FVTM=Part= fvp=c1r1t1_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= left_front_wheel, FVTM=Part= fvp=c1r1t1_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= lights, FVTM=Part= fvp=c1r1_lights, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= right_back_wheel, FVTM=Part= fvp=c1r1t1_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= right_front_wheel, FVTM=Part= fvp=c1r1t1_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= steering_wheel, FVTM=Part= fvp=c1r1_steering_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}], PrimaryBlue= -4, PrimaryRed= 60, SecondaryGreen= 66}, PresetCreator= FEX___96, PresetCreated= 1520339365931, FVTM=Vehicle= fvp=c1r1})"},
 fvtm_jj_vehicles_b_12={hasPattern=false,label="",tag="({PresetKey= fvtm=fvp/c2_orange, PresetCreatorUUID= 01e4af9b-2a30-471e-addf-f6338ffce04b, fvtm_vehicle= {SpawnedKeys= 0, SelectedTexture= 0, SecondaryRed= 66, DoorsOpen= 0b, CustomTexture= minecraft=, SecondaryBlue= 66, PrimaryGreen= 17, Locked= 0b, IsTextureExternal= 0b, Parts= [{UsedAs= engine, FVTM=Part= generic=engine, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft=, EngineOn= 0b}}, {UsedAs= fuel_tank, FVTM=Part= fvp=c7_fuel_tank, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, FuelTankContent= 0.0d, CustomTexture= minecraft={}}, {UsedAs= interior, FVTM=Part= fvp=c2_interior, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= left_back_wheel, FVTM=Part= fvp=c2r2t1_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= left_front_wheel, FVTM=Part= fvp=c2r2t1_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= right_back_wheel, FVTM=Part= fvp=c2r2t1_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= right_front_wheel, FVTM=Part= fvp=c2r2t1_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= steering_wheel, FVTM=Part= fvp=c2_steering_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}], PrimaryBlue= -64, PrimaryRed= 109, SecondaryGreen= 66}, PresetCreator= FEX___96, PresetCreated= 1513093037501, FVTM=Vehicle= fvp=c2})"},
 fvtm_jj_vehicles_b_13={hasPattern=false,label="",tag="({PresetKey= fvtm=fvp/c5_blue, PresetCreatorUUID= 01e4af9b-2a30-471e-addf-f6338ffce04b, fvtm_vehicle= {SpawnedKeys= 0, SelectedTexture= 0, SecondaryRed= 66, DoorsOpen= 0b, CustomTexture= minecraft=, SecondaryBlue= 66, PrimaryGreen= 40, Locked= 0b, IsTextureExternal= 0b, Parts= [{UsedAs= back_lights, FVTM=Part= fvp=c5_back_lights, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= engine, FVTM=Part= generic=engine2, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft=, EngineOn= 0b}}, {UsedAs= front_lights, FVTM=Part= fvp=c5_front_lights, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= fuel_tank, FVTM=Part= fvp=c7_fuel_tank, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, FuelTankContent= 0.0d, CustomTexture= minecraft={}}, {UsedAs= interior, FVTM=Part= fvp=c5_interior, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= left_back_wheel, FVTM=Part= fvp=c5_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= left_front_wheel, FVTM=Part= fvp=c5_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= right_back_wheel, FVTM=Part= fvp=c5_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= right_front_wheel, FVTM=Part= fvp=c5_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= seats, FVTM=Part= fvp=c5_seats, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= steering_wheel, FVTM=Part= fvp=c5_steering_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}], PrimaryBlue= 58, PrimaryRed= 23, SecondaryGreen= 66}, PresetCreator= FEX___96, PresetCreated= 1515932746741, FVTM=Vehicle= fvp=c5})"},
 fvtm_jj_vehicles_b_14={hasPattern=false,label="",tag="({PresetKey= fvtm=fvp/c7_default_light_red, FVTM=Vehicle= fvp=c7, fvtm_landvehicle= {MultiDoor-FrontRight= 0b, SpawnedKeys= 0, SelectedTexture= 0, SecondaryRed= 66, DoorsOpen= 0b, CustomTexture= minecraft=, MultiDoor-Trunk= 0b, SecondaryBlue= 66, PrimaryGreen= 45, MultiDoor-Hood= 0b, Locked= 0b, IsTextureExternal= 0b, MultiDoor-FrontLeft= 0b, Parts= [{UsedAs= doors, FVTM=Part= fvp=c7_doors, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= engine, FVTM=Part= fvp=engine_c7i4, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft=, EngineOn= 0b}}, {UsedAs= exchange_wheel, FVTM=Part= fvp=c7_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= fuel_gauge, FVTM=Part= fvp=t1_fuelgauge, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= fuel_tank, FVTM=Part= fvp=c7_fuel_tank, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, FuelTankContent= 0.0d, CustomTexture= minecraft={}}, {UsedAs= hood, FVTM=Part= fvp=c7_hood, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= interior, FVTM=Part= fvp=c7_interior, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= left_back_wheel, FVTM=Part= fvp=c7_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= left_front_wheel, FVTM=Part= fvp=c7_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= right_back_wheel, FVTM=Part= fvp=c7_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= right_front_wheel, FVTM=Part= fvp=c7_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= seats, FVTM=Part= fvp=c7_seats, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= steering_wheel, FVTM=Part= fvp=c7_steering_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}], PrimaryBlue= 45, MultiDoor-BackLeft= 0b, MultiDoor-BackRight= 0b, PrimaryRed= 86, SecondaryGreen= 66}})"},
 fvtm_jj_vehicles_b_15={hasPattern=false,label="",tag="({PresetKey= fvtm=fvp/c8_blue, PresetCreatorUUID= 01e4af9b-2a30-471e-addf-f6338ffce04b, fvtm_vehicle= {MultiDoor-FrontRight= 0b, SpawnedKeys= 0, SelectedTexture= 0, SecondaryRed= 66, DoorsOpen= 0b, CustomTexture= minecraft=, LightsState= 0, MultiDoor-Trunk= 0b, SecondaryBlue= 66, PrimaryGreen= 40, MultiDoor-Hood= 0b, Locked= 0b, IsTextureExternal= 0b, MultiDoor-FrontLeft= 0b, Parts= [{UsedAs= doors, FVTM=Part= fvp=c8_doors, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= engine, FVTM=Part= generic=engine2, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft=, EngineOn= 0b}}, {UsedAs= fuel_tank, FVTM=Part= fvp=c7_fuel_tank, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, FuelTankContent= 0.0d, CustomTexture= minecraft={}}, {UsedAs= interior, FVTM=Part= fvp=c8_interior, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= left_back_wheel, FVTM=Part= fvp=c2r2t1_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= left_front_wheel, FVTM=Part= fvp=c2r2t1_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= lights, FVTM=Part= fvp=c8_lights, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= right_back_wheel, FVTM=Part= fvp=c2r2t1_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= right_front_wheel, FVTM=Part= fvp=c2r2t1_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= seats, FVTM=Part= fvp=c8_seats, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= steering_wheel, FVTM=Part= fvp=c8_steering_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}], PrimaryBlue= 44, MultiDoor-BackLeft= 0b, MultiDoor-BackRight= 0b, PrimaryRed= 16, SecondaryGreen= 66}, PresetCreator= FEX___96, PresetCreated= 1520376874344, FVTM=Vehicle= fvp=c8})"},
 fvtm_jj_vehicles_b_16={hasPattern=false,label="",tag="({PresetKey= fvtm=fvp/c8_green, PresetCreatorUUID= 01e4af9b-2a30-471e-addf-f6338ffce04b, fvtm_vehicle= {MultiDoor-FrontRight= 0b, SpawnedKeys= 0, SelectedTexture= 0, SecondaryRed= 66, DoorsOpen= 0b, CustomTexture= minecraft=, LightsState= 0, MultiDoor-Trunk= 0b, SecondaryBlue= 66, PrimaryGreen= 67, MultiDoor-Hood= 0b, Locked= 0b, IsTextureExternal= 0b, MultiDoor-FrontLeft= 0b, Parts= [{UsedAs= doors, FVTM=Part= fvp=c8_doors, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= engine, FVTM=Part= generic=engine2, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft=, EngineOn= 0b}}, {UsedAs= fuel_tank, FVTM=Part= generic=fuel_tank, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, FuelTankContent= 0.0d, CustomTexture= minecraft={}}, {UsedAs= interior, FVTM=Part= fvp=c8_interior, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= left_back_wheel, FVTM=Part= fvp=c8_phwheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= left_front_wheel, FVTM=Part= fvp=c8_phwheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= lights, FVTM=Part= fvp=c8_lights, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= right_back_wheel, FVTM=Part= fvp=c8_phwheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= right_front_wheel, FVTM=Part= fvp=c8_phwheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= seats, FVTM=Part= fvp=c8_seats, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= steering_wheel, FVTM=Part= fvp=c8_steering_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}], PrimaryBlue= 50, MultiDoor-BackLeft= 0b, MultiDoor-BackRight= 0b, PrimaryRed= 52, SecondaryGreen= 66}, PresetCreator= FEX___96, PresetCreated= 1520376402585, FVTM=Vehicle= fvp=c8})"},
 fvtm_jj_vehicles_b_17={hasPattern=false,label="",tag="({PresetKey= fvtm=fvp/ot1_example_type3, PresetCreatorUUID= 01e4af9b-2a30-471e-addf-f6338ffce04b, fvtm_vehicle= {SpawnedKeys= 0, SelectedTexture= 0, SecondaryRed= 66, DoorsOpen= 0b, CustomTexture= minecraft=, SecondaryBlue= 66, PrimaryGreen= 23, Locked= 0b, IsTextureExternal= 0b, Parts= [{UsedAs= engine, FVTM=Part= generic=engine, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft=, EngineOn= 0b}}, {UsedAs= fuel_tank, FVTM=Part= fvp=c7_fuel_tank, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, FuelTankContent= 0.0d, CustomTexture= minecraft={}}, {UsedAs= cargo, FVTM=Part= fvp=ot1_type3, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= front_seats, FVTM=Part= fvp=ot1_front_seats, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= left_back_wheel, FVTM=Part= fvp=ot1_back_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= left_front_wheel, FVTM=Part= fvp=ot1_front_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= right_back_wheel, FVTM=Part= fvp=ot1_back_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= right_front_wheel, FVTM=Part= fvp=ot1_front_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= steering_wheel, FVTM=Part= fvp=ot1_steering_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}], PrimaryBlue= 35, PrimaryRed= -14, SecondaryGreen= 66}, PresetCreator= FEX___96, PresetCreated= 1513094193090, FVTM=Vehicle= fvp=ot1})"},
 fvtm_jj_vehicles_b_18={hasPattern=false,label="",tag="({PresetKey= fvtm=fvp/ot1_logtransport, PresetCreatorUUID= 01e4af9b-2a30-471e-addf-f6338ffce04b, fvtm_vehicle= {SpawnedKeys= 0, SelectedTexture= 0, SecondaryRed= 66, DoorsOpen= 0b, CustomTexture= minecraft=, SecondaryBlue= 66, PrimaryGreen= 40, Locked= 0b, IsTextureExternal= 0b, Parts= [{UsedAs= engine, FVTM=Part= generic=engine, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft=, EngineOn= 0b}}, {UsedAs= fuel_tank, FVTM=Part= fvp=c7_fuel_tank, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, FuelTankContent= 0.0d, CustomTexture= minecraft={}}, {UsedAs= cargo, FVTM=Part= fvp=ot1_logtransport, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft=, inventory= {Items= []}}}, {UsedAs= front_seats, FVTM=Part= fvp=ot1_front_seats, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= left_back_wheel, FVTM=Part= fvp=ot1_back_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= left_front_wheel, FVTM=Part= fvp=ot1_front_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= right_back_wheel, FVTM=Part= fvp=ot1_back_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= right_front_wheel, FVTM=Part= fvp=ot1_front_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= steering_wheel, FVTM=Part= fvp=ot1_steering_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}], PrimaryBlue= 40, PrimaryRed= 40, SecondaryGreen= 66}, PresetCreator= FEX___96, PresetCreated= 1513093659890, FVTM=Vehicle= fvp=ot1})"},
 fvtm_jj_vehicles_b_19={hasPattern=false,label="",tag="({PresetKey= fvtm=fvp/t1_example_tanker, FVTM=Vehicle= fvp=t1, fvtm_landvehicle= {SpawnedKeys= 0, SelectedTexture= 0, SecondaryRed= 32, DoorsOpen= 0b, CustomTexture= minecraft=, SecondaryBlue= 66, PrimaryGreen= 0, Locked= 0b, IsTextureExternal= 0b, Parts= [{UsedAs= cargo, FVTM=Part= fvp=t1_type4_cargoupgrade, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 1, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft=, inventory= {Items= []}}}, {UsedAs= driver_seat, FVTM=Part= fvp=t1_driver_seat, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= engine, FVTM=Part= generic=engine, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft=, EngineOn= 0b}}, {UsedAs= fuel_tank, FVTM=Part= generic=fuel_tank, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, FuelTankContent= 0.0d, CustomTexture= minecraft={}}, {UsedAs= left_back_wheel, FVTM=Part= fvp=t1_back_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= left_front_wheel, FVTM=Part= fvp=t1_front_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= passenger_seats, FVTM=Part= fvp=t1_front_seats, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= rear_connector, FVTM=Part= fvp=t1_trailer_connector, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= right_back_wheel, FVTM=Part= fvp=t1_back_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= right_front_wheel, FVTM=Part= fvp=t1_front_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= steering_wheel, FVTM=Part= fvp=t1_steering_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}], PrimaryBlue= 116, PrimaryRed= 52, SecondaryGreen= 51}})"},
 fvtm_jj_vehicles_b_2={hasPattern=false,label="",tag="({FVTM=Vehicle= fvp=c2})"},
 fvtm_jj_vehicles_b_3={hasPattern=false,label="",tag="({FVTM=Vehicle= fvp=c4z1})"},
 fvtm_jj_vehicles_b_4={hasPattern=false,label="",tag="({FVTM=Vehicle= fvp=c5})"},
 fvtm_jj_vehicles_b_5={hasPattern=false,label="",tag="({FVTM=Vehicle= fvp=c7})"},
 fvtm_jj_vehicles_b_6={hasPattern=false,label="",tag="({FVTM=Vehicle= fvp=c8})"},
 fvtm_jj_vehicles_b_7={hasPattern=false,label="",tag="({FVTM=Vehicle= fvp=ot1})"},
 fvtm_jj_vehicles_b_8={hasPattern=false,label="",tag="({FVTM=Vehicle= fvp=t1})"},
 fvtm_jj_vehicles_b_9={hasPattern=false,label="",tag="({PresetKey= fvtm=fvp/ab1b_example, PresetCreatorUUID= 01e4af9b-2a30-471e-addf-f6338ffce04b, fvtm_vehicle= {SpawnedKeys= 0, SelectedTexture= 0, SecondaryRed= 127, DoorsOpen= 0b, CustomTexture= minecraft=, SecondaryBlue= 127, PrimaryGreen= 80, Locked= 0b, IsTextureExternal= 0b, Parts= [{UsedAs= doors, FVTM=Part= fvp=ab1_doors, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= driver_seat, FVTM=Part= fvp=ab1_driver_seat, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= engine, FVTM=Part= fvp=ab1_engine, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft=, EngineOn= 0b}}, {UsedAs= fuel_tank, FVTM=Part= fvp=c7_fuel_tank, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, FuelTankContent= 0.0d, CustomTexture= minecraft={}}, {UsedAs= inner, FVTM=Part= fvp=ab1_passenger_seats, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= left_back_wheel, FVTM=Part= fvp=t2r1t1_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= left_front_wheel, FVTM=Part= fvp=t2r1t1_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= lights, FVTM=Part= fvp=ab1_lights, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= right_back_wheel, FVTM=Part= fvp=t2r1t1_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= right_front_wheel, FVTM=Part= fvp=t2r1t1_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}, {UsedAs= secondary_fuel_tank, FVTM=Part= generic=fuel_tank, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, FuelTankContent= 0.0d, CustomTexture= minecraft={}}, {UsedAs= steering_wheel, FVTM=Part= fvp=ab1_steering_wheel, fvtm_part= {IsTextureExternal= 0b, Offset_z= 0.0f, SelectedTexture= 0, Offset_x= 0.0f, Offset_y= 0.0f, CustomTexture= minecraft={}}], PrimaryBlue= 64, PrimaryRed= -24, SecondaryGreen= 127}, PresetCreator= FEX___96, PresetCreated= 1514139727750, FVTM=Vehicle= fvp=ab1})"},
 industrialforegoing_jj_adult_filter={hasPattern=true,label="Adult Filter",tag=""},
 industrialforegoing_jj_animal_byproduct_recolector={hasPattern=true,label="Animal Sewer",tag=""},
 industrialforegoing_jj_animal_growth_increaser={hasPattern=true,label="Animal Grower",tag=""},
 industrialforegoing_jj_animal_independence_selector={hasPattern=true,label="Animal Baby Separator",tag=""},
 industrialforegoing_jj_animal_resource_harvester={hasPattern=true,label="Animal Rancher",tag=""},
 industrialforegoing_jj_animal_stock_increaser={hasPattern=true,label="Animal Feeder",tag=""},
 industrialforegoing_jj_artificial_dye={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_artificial_dye_jj_1={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_artificial_dye_jj_10={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_artificial_dye_jj_11={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_artificial_dye_jj_12={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_artificial_dye_jj_13={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_artificial_dye_jj_14={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_artificial_dye_jj_15={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_artificial_dye_jj_2={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_artificial_dye_jj_3={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_artificial_dye_jj_4={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_artificial_dye_jj_5={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_artificial_dye_jj_6={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_artificial_dye_jj_7={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_artificial_dye_jj_8={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_artificial_dye_jj_9={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_biofuel_generator={hasPattern=true,label="Biofuel Generator",tag=""},
 industrialforegoing_jj_bioreactor={hasPattern=true,label="Bioreactor",tag=""},
 industrialforegoing_jj_black_hole_controller={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_black_hole_controller_reworked={hasPattern=true,label="Black Hole Controller v2.0",tag=""},
 industrialforegoing_jj_black_hole_label={hasPattern=true,label="Black Hole Label",tag=""},
 industrialforegoing_jj_black_hole_tank={hasPattern=true,label="Black Hole Tank",tag=""},
 industrialforegoing_jj_black_hole_unit={hasPattern=true,label="Black Hole Unit",tag=""},
 industrialforegoing_jj_block_destroyer={hasPattern=true,label="Block Breaker",tag=""},
 industrialforegoing_jj_block_placer={hasPattern=true,label="Block Placer",tag=""},
 industrialforegoing_jj_book_manual={hasPattern=true,label="Industrial Foregoing's Manual",tag=""},
 industrialforegoing_jj_conveyor={hasPattern=true,label="Weiß§r Conveyor Belt",tag=""},
 industrialforegoing_jj_conveyor_jj_1={hasPattern=true,label="Orange§r Conveyor Belt",tag=""},
 industrialforegoing_jj_conveyor_jj_10={hasPattern=true,label="Violett§r Conveyor Belt",tag=""},
 industrialforegoing_jj_conveyor_jj_11={hasPattern=true,label="Blau§r Conveyor Belt",tag=""},
 industrialforegoing_jj_conveyor_jj_12={hasPattern=true,label="Braun§r Conveyor Belt",tag=""},
 industrialforegoing_jj_conveyor_jj_13={hasPattern=true,label="Grün§r Conveyor Belt",tag=""},
 industrialforegoing_jj_conveyor_jj_14={hasPattern=true,label="Rot§r Conveyor Belt",tag=""},
 industrialforegoing_jj_conveyor_jj_15={hasPattern=true,label="Schwarz§r Conveyor Belt",tag=""},
 industrialforegoing_jj_conveyor_jj_2={hasPattern=true,label="Magenta§r Conveyor Belt",tag=""},
 industrialforegoing_jj_conveyor_jj_3={hasPattern=true,label="Hellblau§r Conveyor Belt",tag=""},
 industrialforegoing_jj_conveyor_jj_4={hasPattern=true,label="Gelb§r Conveyor Belt",tag=""},
 industrialforegoing_jj_conveyor_jj_5={hasPattern=true,label="Hellgrün§r Conveyor Belt",tag=""},
 industrialforegoing_jj_conveyor_jj_6={hasPattern=true,label="Rosa§r Conveyor Belt",tag=""},
 industrialforegoing_jj_conveyor_jj_7={hasPattern=true,label="Grau§r Conveyor Belt",tag=""},
 industrialforegoing_jj_conveyor_jj_8={hasPattern=true,label="Hellgrau§r Conveyor Belt",tag=""},
 industrialforegoing_jj_conveyor_jj_9={hasPattern=true,label="Türkis§r Conveyor Belt",tag=""},
 industrialforegoing_jj_conveyor_upgrade={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_conveyor_upgrade_jj_1={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_conveyor_upgrade_jj_2={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_conveyor_upgrade_jj_3={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_conveyor_upgrade_jj_4={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_conveyor_upgrade_jj_5={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_conveyor_upgrade_jj_6={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_crop_enrich_material_injector={hasPattern=true,label="Plant Fertilizer",tag=""},
 industrialforegoing_jj_crop_recolector={hasPattern=true,label="Plant Gatherer",tag=""},
 industrialforegoing_jj_crop_sower={hasPattern=true,label="Plant Sower",tag=""},
 industrialforegoing_jj_dryrubber={hasPattern=true,label="Dry Rubber",tag=""},
 industrialforegoing_jj_dye_mixer={hasPattern=true,label="Dye Mixer",tag=""},
 industrialforegoing_jj_enchantment_aplicator={hasPattern=true,label="Enchantment Applicator",tag=""},
 industrialforegoing_jj_enchantment_extractor={hasPattern=true,label="Enchantment Extractor",tag=""},
 industrialforegoing_jj_enchantment_invoker={hasPattern=true,label="Enchantment Factory",tag=""},
 industrialforegoing_jj_enchantment_refiner={hasPattern=true,label="Enchantment Sorter",tag=""},
 industrialforegoing_jj_energy_field_addon={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_energy_field_provider={hasPattern=true,label="Energy Field Provider",tag=""},
 industrialforegoing_jj_fertilizer={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_fluid_crafter={hasPattern=true,label="Fluid Crafter",tag=""},
 industrialforegoing_jj_fluid_pump={hasPattern=true,label="Fluid Pump",tag=""},
 industrialforegoing_jj_fluid_transfer_addon_pull={hasPattern=true,label="Fluid Transfer Addon (Pull/Down)",tag=""},
 industrialforegoing_jj_fluid_transfer_addon_push={hasPattern=true,label="Fluid Transfer Addon (Push/Down)",tag=""},
 industrialforegoing_jj_fluiddictionary_converter={hasPattern=true,label="Fluid Dictionary Converter",tag=""},
 industrialforegoing_jj_fortune_addon={hasPattern=true,label="Fortune Addon",tag=""},
 industrialforegoing_jj_froster={hasPattern=true,label="Froster",tag=""},
 industrialforegoing_jj_hydrator={hasPattern=true,label="Hydrator",tag=""},
 industrialforegoing_jj_infinity_drill_b_10={hasPattern=false,label="",tag="({Energy= 3360000000 as long, Fluid= {FluidName= biofuel, Amount= 0}, Special= 0 as byte, Selected= LEGENDARY})"},
 industrialforegoing_jj_infinity_drill_b_11={hasPattern=false,label="",tag="({Energy= 4000000 as long, Fluid= {FluidName= biofuel, Amount= 0}, Special= 0 as byte, Selected= COMMON})"},
 industrialforegoing_jj_infinity_drill_b_12={hasPattern=false,label="",tag="({Energy= 480000000 as long, Fluid= {FluidName= biofuel, Amount= 0}, Special= 0 as byte, Selected= EPIC})"},
 industrialforegoing_jj_infinity_drill_b_13={hasPattern=false,label="",tag="({Energy= 80000000 as long, Fluid= {FluidName= biofuel, Amount= 0}, Special= 0 as byte, Selected= RARE})"},
 industrialforegoing_jj_infinity_drill_b_14={hasPattern=false,label="",tag="({Energy= 9223372036854775807 as long, Fluid= {FluidName= biofuel, Amount= 0}, Special= 0 as byte, Selected= ARTIFACT})"},
 industrialforegoing_jj_infinity_drill_b_15={hasPattern=false,label="",tag="({Energy= 9223372036854775807 as long, Fluid= {FluidName= biofuel, Amount= 1000000}, Special= 1 as byte, Selected= ARTIFACT})"},
 industrialforegoing_jj_infinity_drill_b_8={hasPattern=false,label="",tag="({Energy= 0 as long, Fluid= {FluidName= biofuel, Amount= 0}, Special= 0 as byte, Selected= POOR})"},
 industrialforegoing_jj_infinity_drill_b_9={hasPattern=false,label="",tag="({Energy= 16000000 as long, Fluid= {FluidName= biofuel, Amount= 0}, Special= 0 as byte, Selected= UNCOMMON})"},
 industrialforegoing_jj_item_splitter={hasPattern=true,label="Item Splitter",tag=""},
 industrialforegoing_jj_itemstack_transfer_addon_pull={hasPattern=true,label="Itemstack Transfer Addon (Pull/Down)",tag=""},
 industrialforegoing_jj_itemstack_transfer_addon_push={hasPattern=true,label="Itemstack Transfer Addon (Push/Down)",tag=""},
 industrialforegoing_jj_laser_base={hasPattern=true,label="Laser Base",tag=""},
 industrialforegoing_jj_laser_drill={hasPattern=true,label="Laser Drill",tag=""},
 industrialforegoing_jj_laser_lens={hasPattern=true,label="Weiß§r Laser Lens",tag=""},
 industrialforegoing_jj_laser_lens_inverted={hasPattern=true,label="Weiß§r Laser Lens (Inverted)",tag=""},
 industrialforegoing_jj_laser_lens_inverted_jj_1={hasPattern=true,label="Orange§r Laser Lens (Inverted)",tag=""},
 industrialforegoing_jj_laser_lens_inverted_jj_10={hasPattern=true,label="Violett§r Laser Lens (Inverted)",tag=""},
 industrialforegoing_jj_laser_lens_inverted_jj_11={hasPattern=true,label="Blau§r Laser Lens (Inverted)",tag=""},
 industrialforegoing_jj_laser_lens_inverted_jj_12={hasPattern=true,label="Braun§r Laser Lens (Inverted)",tag=""},
 industrialforegoing_jj_laser_lens_inverted_jj_13={hasPattern=true,label="Grün§r Laser Lens (Inverted)",tag=""},
 industrialforegoing_jj_laser_lens_inverted_jj_14={hasPattern=true,label="Rot§r Laser Lens (Inverted)",tag=""},
 industrialforegoing_jj_laser_lens_inverted_jj_15={hasPattern=true,label="Schwarz§r Laser Lens (Inverted)",tag=""},
 industrialforegoing_jj_laser_lens_inverted_jj_2={hasPattern=true,label="Magenta§r Laser Lens (Inverted)",tag=""},
 industrialforegoing_jj_laser_lens_inverted_jj_3={hasPattern=true,label="Hellblau§r Laser Lens (Inverted)",tag=""},
 industrialforegoing_jj_laser_lens_inverted_jj_4={hasPattern=true,label="Gelb§r Laser Lens (Inverted)",tag=""},
 industrialforegoing_jj_laser_lens_inverted_jj_5={hasPattern=true,label="Hellgrün§r Laser Lens (Inverted)",tag=""},
 industrialforegoing_jj_laser_lens_inverted_jj_6={hasPattern=true,label="Rosa§r Laser Lens (Inverted)",tag=""},
 industrialforegoing_jj_laser_lens_inverted_jj_7={hasPattern=true,label="Grau§r Laser Lens (Inverted)",tag=""},
 industrialforegoing_jj_laser_lens_inverted_jj_8={hasPattern=true,label="Hellgrau§r Laser Lens (Inverted)",tag=""},
 industrialforegoing_jj_laser_lens_inverted_jj_9={hasPattern=true,label="Türkis§r Laser Lens (Inverted)",tag=""},
 industrialforegoing_jj_laser_lens_jj_1={hasPattern=true,label="Orange§r Laser Lens",tag=""},
 industrialforegoing_jj_laser_lens_jj_10={hasPattern=true,label="Violett§r Laser Lens",tag=""},
 industrialforegoing_jj_laser_lens_jj_11={hasPattern=true,label="Blau§r Laser Lens",tag=""},
 industrialforegoing_jj_laser_lens_jj_12={hasPattern=true,label="Braun§r Laser Lens",tag=""},
 industrialforegoing_jj_laser_lens_jj_13={hasPattern=true,label="Grün§r Laser Lens",tag=""},
 industrialforegoing_jj_laser_lens_jj_14={hasPattern=true,label="Rot§r Laser Lens",tag=""},
 industrialforegoing_jj_laser_lens_jj_15={hasPattern=true,label="Schwarz§r Laser Lens",tag=""},
 industrialforegoing_jj_laser_lens_jj_2={hasPattern=true,label="Magenta§r Laser Lens",tag=""},
 industrialforegoing_jj_laser_lens_jj_3={hasPattern=true,label="Hellblau§r Laser Lens",tag=""},
 industrialforegoing_jj_laser_lens_jj_4={hasPattern=true,label="Gelb§r Laser Lens",tag=""},
 industrialforegoing_jj_laser_lens_jj_5={hasPattern=true,label="Hellgrün§r Laser Lens",tag=""},
 industrialforegoing_jj_laser_lens_jj_6={hasPattern=true,label="Rosa§r Laser Lens",tag=""},
 industrialforegoing_jj_laser_lens_jj_7={hasPattern=true,label="Grau§r Laser Lens",tag=""},
 industrialforegoing_jj_laser_lens_jj_8={hasPattern=true,label="Hellgrau§r Laser Lens",tag=""},
 industrialforegoing_jj_laser_lens_jj_9={hasPattern=true,label="Türkis§r Laser Lens",tag=""},
 industrialforegoing_jj_latex_processing_unit={hasPattern=true,label="Latex Processing Unit",tag=""},
 industrialforegoing_jj_lava_fabricator={hasPattern=true,label="Lava Fabricator",tag=""},
 industrialforegoing_jj_leaf_shearing={hasPattern=true,label="Leaf Shearing Addon",tag=""},
 industrialforegoing_jj_material_stonework_factory={hasPattern=true,label="Material StoneWork Factory",tag=""},
 industrialforegoing_jj_meat_feeder={hasPattern=true,label="Meat Feeder",tag=""},
 industrialforegoing_jj_mob_detector={hasPattern=true,label="Mob Detector",tag=""},
 industrialforegoing_jj_mob_duplicator={hasPattern=true,label="Mob Duplicator",tag=""},
 industrialforegoing_jj_mob_imprisonment_tool={hasPattern=true,label="Mob Imprisonment Tool",tag=""},
 industrialforegoing_jj_mob_relocator={hasPattern=true,label="Mob Crusher",tag=""},
 industrialforegoing_jj_mob_slaughter_factory={hasPattern=true,label="Mob Slaughter Factory",tag=""},
 industrialforegoing_jj_ore_fermenter={hasPattern=true,label="Fermentation Station",tag=""},
 industrialforegoing_jj_ore_processor={hasPattern=true,label="Ore Processor",tag=""},
 industrialforegoing_jj_ore_sieve={hasPattern=true,label="Fluid Sieving Machine",tag=""},
 industrialforegoing_jj_ore_washer={hasPattern=true,label="Washing Factory",tag=""},
 industrialforegoing_jj_oredictionary_converter={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_petrified_fuel_generator={hasPattern=true,label="Petrified Fuel Generator",tag=""},
 industrialforegoing_jj_pink_slime={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_pink_slime_ingot={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_pitiful_fuel_generator={hasPattern=true,label="Pitiful Fuel Generator",tag=""},
 industrialforegoing_jj_plant_interactor={hasPattern=true,label="Plant Interactor",tag=""},
 industrialforegoing_jj_plastic={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_potion_enervator={hasPattern=true,label="Potion Brewer",tag=""},
 industrialforegoing_jj_protein_generator={hasPattern=true,label="Protein Generator",tag=""},
 industrialforegoing_jj_protein_reactor={hasPattern=true,label="Protein Reactor",tag=""},
 industrialforegoing_jj_range_addon={hasPattern=true,label="Range Addon",tag=""},
 industrialforegoing_jj_range_addon_jj_1={hasPattern=true,label="Range Addon",tag=""},
 industrialforegoing_jj_range_addon_jj_10={hasPattern=true,label="Range Addon",tag=""},
 industrialforegoing_jj_range_addon_jj_11={hasPattern=true,label="Range Addon",tag=""},
 industrialforegoing_jj_range_addon_jj_2={hasPattern=true,label="Range Addon",tag=""},
 industrialforegoing_jj_range_addon_jj_3={hasPattern=true,label="Range Addon",tag=""},
 industrialforegoing_jj_range_addon_jj_4={hasPattern=true,label="Range Addon",tag=""},
 industrialforegoing_jj_range_addon_jj_5={hasPattern=true,label="Range Addon",tag=""},
 industrialforegoing_jj_range_addon_jj_6={hasPattern=true,label="Range Addon",tag=""},
 industrialforegoing_jj_range_addon_jj_7={hasPattern=true,label="Range Addon",tag=""},
 industrialforegoing_jj_range_addon_jj_8={hasPattern=true,label="Range Addon",tag=""},
 industrialforegoing_jj_range_addon_jj_9={hasPattern=true,label="Range Addon",tag=""},
 industrialforegoing_jj_resourceful_furnace={hasPattern=true,label="Resourceful Furnace",tag=""},
 industrialforegoing_jj_sewage_composter_solidifier={hasPattern=true,label="Sewage Composter",tag=""},
 industrialforegoing_jj_sludge_refiner={hasPattern=true,label="Sludge Refiner",tag=""},
 industrialforegoing_jj_spores_recreator={hasPattern=true,label="Spores Recreator",tag=""},
 industrialforegoing_jj_straw={hasPattern=true,label="Straw",tag=""},
 industrialforegoing_jj_tinydryrubber={hasPattern=false,label="",tag=""},
 industrialforegoing_jj_tree_fluid_extractor={hasPattern=true,label="Tree Fluid Extractor",tag=""},
 industrialforegoing_jj_villager_trade_exchanger={hasPattern=true,label="Villager Trade Exchanger",tag=""},
 industrialforegoing_jj_water_condensator={hasPattern=true,label="Water Condensator",tag=""},
 industrialforegoing_jj_water_resources_collector={hasPattern=true,label="Resources Fisher",tag=""},
 industrialforegoing_jj_wither_builder={hasPattern=true,label="Wither Builder",tag=""},
 infinitycraft_jj_aluminum_bar={hasPattern=false,label="",tag=""},
 infinitycraft_jj_aluminum_block={hasPattern=true,label="Aluminum Block",tag=""},
 infinitycraft_jj_aluminum_brick={hasPattern=true,label="Aluminum Brick",tag=""},
 infinitycraft_jj_aluminum_can={hasPattern=true,label="Aluminum Can",tag=""},
 infinitycraft_jj_aluminum_light={hasPattern=true,label="Aluminum Light",tag=""},
 infinitycraft_jj_aluminum_ore={hasPattern=false,label="",tag=""},
 infinitycraft_jj_amethyst={hasPattern=false,label="",tag=""},
 infinitycraft_jj_amethyst_axe={hasPattern=true,label="Amethyst Axe",tag=""},
 infinitycraft_jj_amethyst_block={hasPattern=true,label="Amethyst Block",tag=""},
 infinitycraft_jj_amethyst_brick={hasPattern=true,label="Amethyst Brick",tag=""},
 infinitycraft_jj_amethyst_hoe={hasPattern=true,label="Amethyst Hoe",tag=""},
 infinitycraft_jj_amethyst_light={hasPattern=true,label="Amethyst Light",tag=""},
 infinitycraft_jj_amethyst_ore={hasPattern=false,label="",tag=""},
 infinitycraft_jj_amethyst_pickaxe={hasPattern=true,label="Amethyst Pickaxe",tag=""},
 infinitycraft_jj_amethyst_shovel={hasPattern=true,label="Amethyst Shovel",tag=""},
 infinitycraft_jj_amethyst_sword={hasPattern=true,label="Amethyst Sword",tag=""},
 infinitycraft_jj_apple_juice={hasPattern=true,label="Apple juice",tag=""},
 infinitycraft_jj_block_compressor={hasPattern=true,label="Compressor",tag=""},
 infinitycraft_jj_bronze_axe={hasPattern=true,label="Bronze Axe",tag=""},
 infinitycraft_jj_bronze_bar={hasPattern=true,label="Bronze Bar",tag=""},
 infinitycraft_jj_bronze_hoe={hasPattern=true,label="Bronze Hoe",tag=""},
 infinitycraft_jj_bronze_pickaxe={hasPattern=true,label="Bronze Pickaxe",tag=""},
 infinitycraft_jj_bronze_shovel={hasPattern=true,label="Bronze Shovel",tag=""},
 infinitycraft_jj_bronze_sword={hasPattern=true,label="Bronze Sword",tag=""},
 infinitycraft_jj_canned_beef={hasPattern=true,label="Canned Beef",tag=""},
 infinitycraft_jj_canned_fish={hasPattern=true,label="Canned Fish",tag=""},
 infinitycraft_jj_canned_pork={hasPattern=true,label="Canned Pork",tag=""},
 infinitycraft_jj_chainsaw={hasPattern=true,label="Chainsaw",tag=""},
 infinitycraft_jj_chocolate_apple={hasPattern=true,label="Chocolate Apple",tag=""},
 infinitycraft_jj_copper_bar={hasPattern=false,label="",tag=""},
 infinitycraft_jj_copper_coil={hasPattern=true,label="Copper Coil",tag=""},
 infinitycraft_jj_copper_ore={hasPattern=false,label="",tag=""},
 infinitycraft_jj_dia_drill={hasPattern=true,label="Diamond Drill",tag=""},
 infinitycraft_jj_diamond_chainsaw={hasPattern=true,label="Diamond Chainsaw",tag=""},
 infinitycraft_jj_donut={hasPattern=true,label="Donut",tag=""},
 infinitycraft_jj_drill={hasPattern=true,label="Drill",tag=""},
 infinitycraft_jj_energy_crystal={hasPattern=false,label="",tag=""},
 infinitycraft_jj_energy_crystal_mesh={hasPattern=true,label="Energy Crystal Mesh",tag=""},
 infinitycraft_jj_exp_ore={hasPattern=false,label="",tag=""},
 infinitycraft_jj_khalzit_axe={hasPattern=true,label="Khalzit Axe",tag=""},
 infinitycraft_jj_khalzit_bar={hasPattern=false,label="",tag=""},
 infinitycraft_jj_khalzit_block={hasPattern=true,label="Khalzit Block",tag=""},
 infinitycraft_jj_khalzit_brick={hasPattern=true,label="Khalzit Brick",tag=""},
 infinitycraft_jj_khalzit_dust={hasPattern=false,label="",tag=""},
 infinitycraft_jj_khalzit_hoe={hasPattern=true,label="Khalzit Hoe",tag=""},
 infinitycraft_jj_khalzit_light={hasPattern=true,label="Khalzit Light",tag=""},
 infinitycraft_jj_khalzit_ore={hasPattern=false,label="",tag=""},
 infinitycraft_jj_khalzit_pickaxe={hasPattern=true,label="Khalzit Pickaxe",tag=""},
 infinitycraft_jj_khalzit_shovel={hasPattern=true,label="Khalzit Shovel",tag=""},
 infinitycraft_jj_khalzit_sword={hasPattern=true,label="Khalzit Sword",tag=""},
 infinitycraft_jj_motor={hasPattern=true,label="Motor",tag=""},
 infinitycraft_jj_nether_axe={hasPattern=true,label="Nether Axe",tag=""},
 infinitycraft_jj_nether_boots={hasPattern=true,label="Nether Boots",tag=""},
 infinitycraft_jj_nether_chestplate={hasPattern=true,label="Nether Chestplate",tag=""},
 infinitycraft_jj_nether_diamond={hasPattern=false,label="",tag=""},
 infinitycraft_jj_nether_dust={hasPattern=false,label="",tag=""},
 infinitycraft_jj_nether_dust_ore={hasPattern=false,label="",tag=""},
 infinitycraft_jj_nether_helmet={hasPattern=true,label="Nether Helmet",tag=""},
 infinitycraft_jj_nether_hoe={hasPattern=true,label="Nether Hoe",tag=""},
 infinitycraft_jj_nether_leggings={hasPattern=true,label="Nether Leggings",tag=""},
 infinitycraft_jj_nether_pickaxe={hasPattern=true,label="Nether Pickaxe",tag=""},
 infinitycraft_jj_nether_shovel={hasPattern=true,label="Nether Shovel",tag=""},
 infinitycraft_jj_nether_sword={hasPattern=true,label="Nether Sword",tag=""},
 infinitycraft_jj_ocean_boots={hasPattern=true,label="Ocean Boots",tag=""},
 infinitycraft_jj_ocean_chestplate={hasPattern=true,label="Ocean Chestplate",tag=""},
 infinitycraft_jj_ocean_chunk={hasPattern=false,label="",tag=""},
 infinitycraft_jj_ocean_diamond={hasPattern=false,label="",tag=""},
 infinitycraft_jj_ocean_helmet={hasPattern=true,label="Ocean Helmet",tag=""},
 infinitycraft_jj_ocean_leggings={hasPattern=true,label="Ocean Leggings",tag=""},
 infinitycraft_jj_ocean_ore={hasPattern=false,label="",tag=""},
 infinitycraft_jj_oily_stone={hasPattern=false,label="",tag=""},
 infinitycraft_jj_onyx_axe={hasPattern=true,label="Onyx Axe",tag=""},
 infinitycraft_jj_onyx_bar={hasPattern=false,label="",tag=""},
 infinitycraft_jj_onyx_block={hasPattern=true,label="Onyx Block",tag=""},
 infinitycraft_jj_onyx_boots={hasPattern=true,label="Onyx Boots",tag=""},
 infinitycraft_jj_onyx_brick={hasPattern=true,label="Onyx Brick",tag=""},
 infinitycraft_jj_onyx_chestplate={hasPattern=true,label="Onyx Chestplate",tag=""},
 infinitycraft_jj_onyx_helmet={hasPattern=true,label="Onyx Helmet",tag=""},
 infinitycraft_jj_onyx_hoe={hasPattern=true,label="Onyx Hoe",tag=""},
 infinitycraft_jj_onyx_leggings={hasPattern=true,label="Onyx Leggings",tag=""},
 infinitycraft_jj_onyx_light={hasPattern=true,label="Onyx Light",tag=""},
 infinitycraft_jj_onyx_ore={hasPattern=false,label="",tag=""},
 infinitycraft_jj_onyx_pickaxe={hasPattern=true,label="Onyx Pickaxe",tag=""},
 infinitycraft_jj_onyx_shovel={hasPattern=true,label="Onyx Shovel",tag=""},
 infinitycraft_jj_onyx_sword={hasPattern=true,label="Onyx Sword",tag=""},
 infinitycraft_jj_pancake={hasPattern=false,label="",tag=""},
 infinitycraft_jj_pancake_batter={hasPattern=true,label="Pancake Batter",tag=""},
 infinitycraft_jj_pudding_bread={hasPattern=true,label="Pudding Bread",tag=""},
 infinitycraft_jj_rubber_boots={hasPattern=true,label="Rubber Boots",tag=""},
 infinitycraft_jj_rubber_chestplate={hasPattern=true,label="Rubber Chestplate",tag=""},
 infinitycraft_jj_rubber_helmet={hasPattern=true,label="Rubber Helmet",tag=""},
 infinitycraft_jj_rubber_leggings={hasPattern=true,label="Rubber Leggings",tag=""},
 infinitycraft_jj_rubbery_ball={hasPattern=false,label="",tag=""},
 infinitycraft_jj_sphalzite_axe={hasPattern=true,label="Sphalzite Axe",tag=""},
 infinitycraft_jj_sphalzite_bar={hasPattern=false,label="",tag=""},
 infinitycraft_jj_sphalzite_block={hasPattern=true,label="Sphalzite Block",tag=""},
 infinitycraft_jj_sphalzite_brick={hasPattern=true,label="Sphalzite Brick",tag=""},
 infinitycraft_jj_sphalzite_chunk={hasPattern=false,label="",tag=""},
 infinitycraft_jj_sphalzite_hoe={hasPattern=true,label="Sphalzite Hoe",tag=""},
 infinitycraft_jj_sphalzite_light={hasPattern=true,label="Sphalzite Light",tag=""},
 infinitycraft_jj_sphalzite_ore={hasPattern=false,label="",tag=""},
 infinitycraft_jj_sphalzite_pickaxe={hasPattern=true,label="Sphalzite Pickaxe",tag=""},
 infinitycraft_jj_sphalzite_shovel={hasPattern=true,label="Sphalzite Shovel",tag=""},
 infinitycraft_jj_sphalzite_sword={hasPattern=true,label="Sphalzite Sword",tag=""},
 infinitycraft_jj_sugar_bread={hasPattern=true,label="Sugar Bread",tag=""},
 infinitycraft_jj_tin_bar={hasPattern=false,label="",tag=""},
 infinitycraft_jj_tin_ore={hasPattern=false,label="",tag=""},
 infinitycraft_jj_uranium={hasPattern=false,label="",tag=""},
 infinitycraft_jj_uranium_ore={hasPattern=false,label="",tag=""},
 infinitycraft_jj_zeux_axe={hasPattern=true,label="Zeux Axe",tag=""},
 infinitycraft_jj_zeux_bar={hasPattern=false,label="",tag=""},
 infinitycraft_jj_zeux_block={hasPattern=true,label="Zeux Block",tag=""},
 infinitycraft_jj_zeux_brick={hasPattern=true,label="Zeux Brick",tag=""},
 infinitycraft_jj_zeux_dust={hasPattern=false,label="",tag=""},
 infinitycraft_jj_zeux_hoe={hasPattern=true,label="Zeux Hoe",tag=""},
 infinitycraft_jj_zeux_light={hasPattern=true,label="Zeux Light",tag=""},
 infinitycraft_jj_zeux_ore={hasPattern=false,label="",tag=""},
 infinitycraft_jj_zeux_pickaxe={hasPattern=true,label="Zeux Pickaxe",tag=""},
 infinitycraft_jj_zeux_shovel={hasPattern=true,label="Zeux Shovel",tag=""},
 infinitycraft_jj_zeux_sword={hasPattern=true,label="Zeux Sword",tag=""}
 }