return {
 mekanism_jj_anchorupgrade={hasPattern=true,label="Anchor Upgrade",tag={}},
 mekanism_jj_armoredjetpack={hasPattern=false,label="",tag={}},
 mekanism_jj_armoredjetpack_b_1={hasPattern=true,label="Panzer-Jetpack",tag={mekData={}}},
 mekanism_jj_atomicalloy={hasPattern=true,label="Atomlegierung",tag={}},
 mekanism_jj_atomicdisassembler={hasPattern=false,label="",tag={}},
 mekanism_jj_atomicdisassembler_b_1={hasPattern=true,label="Atomar-Disassembler",tag={}},
 mekanism_jj_balloon={hasPattern=true,label="§8Schwarz Ballon",tag={}},
 mekanism_jj_balloon_jj_1={hasPattern=true,label="§cRot Ballon",tag={}},
 mekanism_jj_balloon_jj_10={hasPattern=true,label="§aHellgrün Ballon",tag={}},
 mekanism_jj_balloon_jj_11={hasPattern=true,label="§eGelb Ballon",tag={}},
 mekanism_jj_balloon_jj_12={hasPattern=true,label="§9Hellblau Ballon",tag={}},
 mekanism_jj_balloon_jj_13={hasPattern=true,label="§dMagentafarben Ballon",tag={}},
 mekanism_jj_balloon_jj_14={hasPattern=true,label="§6Orange Ballon",tag={}},
 mekanism_jj_balloon_jj_15={hasPattern=true,label="§fWeiß Ballon",tag={}},
 mekanism_jj_balloon_jj_2={hasPattern=true,label="§2Grün Ballon",tag={}},
 mekanism_jj_balloon_jj_3={hasPattern=true,label="§6Braun Ballon",tag={}},
 mekanism_jj_balloon_jj_4={hasPattern=true,label="§1Blau Ballon",tag={}},
 mekanism_jj_balloon_jj_5={hasPattern=true,label="§5Violett Ballon",tag={}},
 mekanism_jj_balloon_jj_6={hasPattern=true,label="§3Türkis Ballon",tag={}},
 mekanism_jj_balloon_jj_7={hasPattern=true,label="§7Hellgrau Ballon",tag={}},
 mekanism_jj_balloon_jj_8={hasPattern=true,label="§8Grau Ballon",tag={}},
 mekanism_jj_balloon_jj_9={hasPattern=true,label="§dPink Ballon",tag={}},
 mekanism_jj_basicblock={hasPattern=true,label="Osmiumblock",tag={}},
 mekanism_jj_basicblock2={hasPattern=true,label="Thermalverdampfungsblock",tag={}},
 mekanism_jj_basicblock2_jj_1={hasPattern=true,label="Induktionshülle",tag={}},
 mekanism_jj_basicblock2_jj_2={hasPattern=true,label="Induktionsport",tag={}},
 mekanism_jj_basicblock2_jj_3={hasPattern=false,label="",tag={tier=0}},
 mekanism_jj_basicblock2_jj_3_b_1={hasPattern=false,label="",tag={tier=1}},
 mekanism_jj_basicblock2_jj_3_b_2={hasPattern=false,label="",tag={tier=2}},
 mekanism_jj_basicblock2_jj_3_b_3={hasPattern=false,label="",tag={tier=3}},
 mekanism_jj_basicblock2_jj_4={hasPattern=false,label="",tag={tier=0}},
 mekanism_jj_basicblock2_jj_4_b_1={hasPattern=false,label="",tag={tier=1}},
 mekanism_jj_basicblock2_jj_4_b_2={hasPattern=false,label="",tag={tier=2}},
 mekanism_jj_basicblock2_jj_4_b_3={hasPattern=false,label="",tag={tier=3}},
 mekanism_jj_basicblock2_jj_5={hasPattern=true,label="Überhitzungselement",tag={}},
 mekanism_jj_basicblock2_jj_6={hasPattern=true,label="Druckventil",tag={}},
 mekanism_jj_basicblock2_jj_7={hasPattern=true,label="Dampfkesselhülle",tag={}},
 mekanism_jj_basicblock2_jj_8={hasPattern=true,label="Dampfkesselventil",tag={}},
 mekanism_jj_basicblock2_jj_9={hasPattern=true,label="Sicherungstisch",tag={}},
 mekanism_jj_basicblock_jj_1={hasPattern=true,label="Bronzeblock",tag={}},
 mekanism_jj_basicblock_jj_10={hasPattern=true,label="Strukturglas",tag={}},
 mekanism_jj_basicblock_jj_11={hasPattern=true,label="Dynamisches Ventil",tag={}},
 mekanism_jj_basicblock_jj_12={hasPattern=true,label="Kupferblock",tag={}},
 mekanism_jj_basicblock_jj_13={hasPattern=true,label="Zinnblock",tag={}},
 mekanism_jj_basicblock_jj_14={hasPattern=true,label="Thermalverdampfungs-Controller",tag={}},
 mekanism_jj_basicblock_jj_15={hasPattern=true,label="Thermalverdampfungsventil",tag={}},
 mekanism_jj_basicblock_jj_2={hasPattern=true,label="Raffiniertes Obsidian",tag={}},
 mekanism_jj_basicblock_jj_3={hasPattern=false,label="",tag={}},
 mekanism_jj_basicblock_jj_4={hasPattern=true,label="Raffiniertes Glowstone",tag={}},
 mekanism_jj_basicblock_jj_5={hasPattern=true,label="Stahlblock",tag={}},
 mekanism_jj_basicblock_jj_6={hasPattern=false,label="",tag={tier=0}},
 mekanism_jj_basicblock_jj_6_b_1={hasPattern=false,label="",tag={tier=1}},
 mekanism_jj_basicblock_jj_6_b_2={hasPattern=false,label="",tag={tier=2}},
 mekanism_jj_basicblock_jj_6_b_3={hasPattern=false,label="",tag={tier=3}},
 mekanism_jj_basicblock_jj_6_b_4={hasPattern=false,label="",tag={tier=4}},
 mekanism_jj_basicblock_jj_7={hasPattern=true,label="Teleporter-Rahmen",tag={}},
 mekanism_jj_basicblock_jj_8={hasPattern=true,label="Stahlhülle",tag={}},
 mekanism_jj_basicblock_jj_9={hasPattern=true,label="Dynamischer Tank",tag={}},
 mekanism_jj_biofuel={hasPattern=false,label="",tag={}},
 mekanism_jj_boundingblock={hasPattern=false,label="",tag={}},
 mekanism_jj_cardboardbox={hasPattern=true,label="Pappkarton",tag={}},
 mekanism_jj_clump={hasPattern=false,label="",tag={}},
 mekanism_jj_clump_jj_1={hasPattern=false,label="",tag={}},
 mekanism_jj_clump_jj_2={hasPattern=false,label="",tag={}},
 mekanism_jj_clump_jj_3={hasPattern=false,label="",tag={}},
 mekanism_jj_clump_jj_4={hasPattern=false,label="",tag={}},
 mekanism_jj_clump_jj_5={hasPattern=false,label="",tag={}},
 mekanism_jj_clump_jj_6={hasPattern=false,label="",tag={}},
 mekanism_jj_compressedcarbon={hasPattern=true,label="Komprimierter Kohlenstoff",tag={}},
 mekanism_jj_compresseddiamond={hasPattern=true,label="Komprimierter Diamant",tag={}},
 mekanism_jj_compressedobsidian={hasPattern=true,label="Komprimiertes Obsidian",tag={}},
 mekanism_jj_compressedredstone={hasPattern=true,label="Komprimiertes Redstone",tag={}},
 mekanism_jj_configurationcard={hasPattern=true,label="Konfigurationskarte",tag={}},
 mekanism_jj_configurator={hasPattern=false,label="",tag={}},
 mekanism_jj_configurator_b_1={hasPattern=true,label="Konfigurator",tag={}},
 mekanism_jj_controlcircuit={hasPattern=true,label="Basis-Kontrollschaltkreis",tag={}},
 mekanism_jj_controlcircuit_jj_1={hasPattern=true,label="Fortgeschr. Kontrollschaltkreis",tag={}},
 mekanism_jj_controlcircuit_jj_2={hasPattern=true,label="Elite-Kontrollschaltkreis",tag={}},
 mekanism_jj_controlcircuit_jj_3={hasPattern=true,label="Ultimativer Kontrollschaltkreis",tag={}},
 mekanism_jj_craftingformula={hasPattern=true,label="Fertigungsformel",tag={}},
 mekanism_jj_crystal={hasPattern=false,label="",tag={}},
 mekanism_jj_crystal_jj_1={hasPattern=false,label="",tag={}},
 mekanism_jj_crystal_jj_2={hasPattern=false,label="",tag={}},
 mekanism_jj_crystal_jj_3={hasPattern=false,label="",tag={}},
 mekanism_jj_crystal_jj_4={hasPattern=false,label="",tag={}},
 mekanism_jj_crystal_jj_5={hasPattern=false,label="",tag={}},
 mekanism_jj_crystal_jj_6={hasPattern=false,label="",tag={}},
 mekanism_jj_dictionary={hasPattern=true,label="Lexikon",tag={}},
 mekanism_jj_dirtydust={hasPattern=false,label="",tag={}},
 mekanism_jj_dirtydust_jj_1={hasPattern=false,label="",tag={}},
 mekanism_jj_dirtydust_jj_2={hasPattern=false,label="",tag={}},
 mekanism_jj_dirtydust_jj_3={hasPattern=false,label="",tag={}},
 mekanism_jj_dirtydust_jj_4={hasPattern=false,label="",tag={}},
 mekanism_jj_dirtydust_jj_5={hasPattern=false,label="",tag={}},
 mekanism_jj_dirtydust_jj_6={hasPattern=false,label="",tag={}},
 mekanism_jj_dust={hasPattern=true,label="Eisenstaub",tag={}},
 mekanism_jj_dust_jj_1={hasPattern=true,label="Goldstaub",tag={}},
 mekanism_jj_dust_jj_2={hasPattern=true,label="Osmiumstaub",tag={}},
 mekanism_jj_dust_jj_3={hasPattern=true,label="Kupferstaub",tag={}},
 mekanism_jj_dust_jj_4={hasPattern=true,label="Zinnstaub",tag={}},
 mekanism_jj_dust_jj_5={hasPattern=true,label="Silberstaub",tag={}},
 mekanism_jj_dust_jj_6={hasPattern=true,label="Bleistaub",tag={}},
 mekanism_jj_electricbow={hasPattern=false,label="",tag={}},
 mekanism_jj_electricbow_b_1={hasPattern=true,label="Elektrischer Bogen",tag={}},
 mekanism_jj_electrolyticcore={hasPattern=true,label="Elektrolysekern",tag={}},
 mekanism_jj_energycube={hasPattern=false,label="",tag={tier=0}},
 mekanism_jj_energycube_b_1={hasPattern=false,label="",tag={mekData={energyStored=2000000},tier=0}},
 mekanism_jj_energycube_b_2={hasPattern=false,label="",tag={tier=1}},
 mekanism_jj_energycube_b_3={hasPattern=false,label="",tag={mekData={energyStored=8000000},tier=1}},
 mekanism_jj_energycube_b_4={hasPattern=false,label="",tag={tier=2}},
 mekanism_jj_energycube_b_5={hasPattern=false,label="",tag={mekData={energyStored=32000000},tier=2}},
 mekanism_jj_energycube_b_6={hasPattern=false,label="",tag={tier=3}},
 mekanism_jj_energycube_b_7={hasPattern=false,label="",tag={mekData={energyStored=128000000},tier=3}},
 mekanism_jj_energycube_b_8={hasPattern=false,label="",tag={tier=4}},
 mekanism_jj_energycube_b_9={hasPattern=false,label="",tag={mekData={energyStored=1.7976931348623e+308},tier=4}},
 mekanism_jj_energytablet={hasPattern=false,label="",tag={}},
 mekanism_jj_energytablet_b_1={hasPattern=true,label="Energietablett",tag={}},
 mekanism_jj_energyupgrade={hasPattern=true,label="Energieupgrade",tag={}},
 mekanism_jj_enrichedalloy={hasPattern=true,label="Angereicherte Legierung",tag={}},
 mekanism_jj_enrichediron={hasPattern=false,label="",tag={}},
 mekanism_jj_filterupgrade={hasPattern=true,label="Filter-Upgrade",tag={}},
 mekanism_jj_flamethrower={hasPattern=false,label="",tag={}},
 mekanism_jj_flamethrower_b_1={hasPattern=true,label="Flammenwerfer",tag={mekData={}}},
 mekanism_jj_freerunners={hasPattern=false,label="",tag={}},
 mekanism_jj_freerunners_b_1={hasPattern=true,label="Freiläufer",tag={}},
 mekanism_jj_gasmask={hasPattern=true,label="Gasmaske",tag={}},
 mekanism_jj_gastank={hasPattern=false,label="",tag={tier=0}},
 mekanism_jj_gastank_b_1={hasPattern=false,label="",tag={tier=1}},
 mekanism_jj_gastank_b_10={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="sulfurtrioxide"}},tier=4}},
 mekanism_jj_gastank_b_11={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="sulfuricacid"}},tier=4}},
 mekanism_jj_gastank_b_12={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="hydrogenchloride"}},tier=4}},
 mekanism_jj_gastank_b_13={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="ethene"}},tier=4}},
 mekanism_jj_gastank_b_14={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="sodium"}},tier=4}},
 mekanism_jj_gastank_b_15={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="brine"}},tier=4}},
 mekanism_jj_gastank_b_16={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="deuterium"}},tier=4}},
 mekanism_jj_gastank_b_17={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="tritium"}},tier=4}},
 mekanism_jj_gastank_b_18={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="fusionfuel"}},tier=4}},
 mekanism_jj_gastank_b_19={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="lithium"}},tier=4}},
 mekanism_jj_gastank_b_2={hasPattern=false,label="",tag={tier=2}},
 mekanism_jj_gastank_b_20={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="adamantine"}},tier=4}},
 mekanism_jj_gastank_b_21={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleanadamantine"}},tier=4}},
 mekanism_jj_gastank_b_22={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="antimony"}},tier=4}},
 mekanism_jj_gastank_b_23={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleanantimony"}},tier=4}},
 mekanism_jj_gastank_b_24={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="bismuth"}},tier=4}},
 mekanism_jj_gastank_b_25={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleanbismuth"}},tier=4}},
 mekanism_jj_gastank_b_26={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="coldiron"}},tier=4}},
 mekanism_jj_gastank_b_27={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleancoldiron"}},tier=4}},
 mekanism_jj_gastank_b_28={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="platinum"}},tier=4}},
 mekanism_jj_gastank_b_29={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleanplatinum"}},tier=4}},
 mekanism_jj_gastank_b_3={hasPattern=false,label="",tag={tier=3}},
 mekanism_jj_gastank_b_30={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="nickel"}},tier=4}},
 mekanism_jj_gastank_b_31={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleannickel"}},tier=4}},
 mekanism_jj_gastank_b_32={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="starsteel"}},tier=4}},
 mekanism_jj_gastank_b_33={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleanstarsteel"}},tier=4}},
 mekanism_jj_gastank_b_34={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="zinc"}},tier=4}},
 mekanism_jj_gastank_b_35={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleanzinc"}},tier=4}},
 mekanism_jj_gastank_b_36={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="aluminum"}},tier=4}},
 mekanism_jj_gastank_b_37={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleanaluminum"}},tier=4}},
 mekanism_jj_gastank_b_38={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="beryllium"}},tier=4}},
 mekanism_jj_gastank_b_39={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleanberyllium"}},tier=4}},
 mekanism_jj_gastank_b_4={hasPattern=false,label="",tag={tier=4}},
 mekanism_jj_gastank_b_40={hasPattern=false,label="",tag={tier=4}},
 mekanism_jj_gastank_b_41={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleanboron"}},tier=4}},
 mekanism_jj_gastank_b_42={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cadmium"}},tier=4}},
 mekanism_jj_gastank_b_43={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleancadmium"}},tier=4}},
 mekanism_jj_gastank_b_44={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="chromium"}},tier=4}},
 mekanism_jj_gastank_b_45={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleanchromium"}},tier=4}},
 mekanism_jj_gastank_b_46={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="iridium"}},tier=4}},
 mekanism_jj_gastank_b_47={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleaniridium"}},tier=4}},
 mekanism_jj_gastank_b_48={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="magnesium"}},tier=4}},
 mekanism_jj_gastank_b_49={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleanmagnesium"}},tier=4}},
 mekanism_jj_gastank_b_5={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="hydrogen"}},tier=4}},
 mekanism_jj_gastank_b_50={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="manganese"}},tier=4}},
 mekanism_jj_gastank_b_51={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleanmanganese"}},tier=4}},
 mekanism_jj_gastank_b_52={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="plutonium"}},tier=4}},
 mekanism_jj_gastank_b_53={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleanplutonium"}},tier=4}},
 mekanism_jj_gastank_b_54={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="rutile"}},tier=4}},
 mekanism_jj_gastank_b_55={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleanrutile"}},tier=4}},
 mekanism_jj_gastank_b_56={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="tantalum"}},tier=4}},
 mekanism_jj_gastank_b_57={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleantantalum"}},tier=4}},
 mekanism_jj_gastank_b_58={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="thorium"}},tier=4}},
 mekanism_jj_gastank_b_59={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleanthorium"}},tier=4}},
 mekanism_jj_gastank_b_6={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="oxygen"}},tier=4}},
 mekanism_jj_gastank_b_60={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="titanium"}},tier=4}},
 mekanism_jj_gastank_b_61={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleantitanium"}},tier=4}},
 mekanism_jj_gastank_b_62={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="tungsten"}},tier=4}},
 mekanism_jj_gastank_b_63={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleantungsten"}},tier=4}},
 mekanism_jj_gastank_b_64={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="uranium"}},tier=4}},
 mekanism_jj_gastank_b_65={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleanuranium"}},tier=4}},
 mekanism_jj_gastank_b_66={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="zirconium"}},tier=4}},
 mekanism_jj_gastank_b_67={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="cleanzirconium"}},tier=4}},
 mekanism_jj_gastank_b_7={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="water"}},tier=4}},
 mekanism_jj_gastank_b_8={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="chlorine"}},tier=4}},
 mekanism_jj_gastank_b_9={hasPattern=false,label="",tag={mekData={stored={amount=2147483647,gasName="sulfurdioxide"}},tier=4}},
 mekanism_jj_gasupgrade={hasPattern=true,label="Gas-Upgrade",tag={}},
 mekanism_jj_gaugedropper={hasPattern=false,label="",tag={}},
 mekanism_jj_glowpanel={hasPattern=true,label="§8Schwarz Glow Panel",tag={}},
 mekanism_jj_glowpanel_jj_1={hasPattern=true,label="§cRot Glow Panel",tag={}},
 mekanism_jj_glowpanel_jj_10={hasPattern=true,label="§aHellgrün Glow Panel",tag={}},
 mekanism_jj_glowpanel_jj_11={hasPattern=true,label="§eGelb Glow Panel",tag={}},
 mekanism_jj_glowpanel_jj_12={hasPattern=true,label="§9Hellblau Glow Panel",tag={}},
 mekanism_jj_glowpanel_jj_13={hasPattern=true,label="§dMagentafarben Glow Panel",tag={}},
 mekanism_jj_glowpanel_jj_14={hasPattern=true,label="§6Orange Glow Panel",tag={}},
 mekanism_jj_glowpanel_jj_15={hasPattern=true,label="§fWeiß Glow Panel",tag={}},
 mekanism_jj_glowpanel_jj_2={hasPattern=true,label="§2Grün Glow Panel",tag={}},
 mekanism_jj_glowpanel_jj_3={hasPattern=true,label="§6Braun Glow Panel",tag={}},
 mekanism_jj_glowpanel_jj_4={hasPattern=true,label="§1Blau Glow Panel",tag={}},
 mekanism_jj_glowpanel_jj_5={hasPattern=true,label="§5Violett Glow Panel",tag={}},
 mekanism_jj_glowpanel_jj_6={hasPattern=true,label="§3Türkis Glow Panel",tag={}},
 mekanism_jj_glowpanel_jj_7={hasPattern=true,label="§7Hellgrau Glow Panel",tag={}},
 mekanism_jj_glowpanel_jj_8={hasPattern=true,label="§8Grau Glow Panel",tag={}},
 mekanism_jj_glowpanel_jj_9={hasPattern=true,label="§dPink Glow Panel",tag={}},
 mekanism_jj_glowplasticblock={hasPattern=true,label="§8Schwarz Schimmernder Plastikblock",tag={}},
 mekanism_jj_glowplasticblock_jj_1={hasPattern=true,label="§cRot Schimmernder Plastikblock",tag={}},
 mekanism_jj_glowplasticblock_jj_10={hasPattern=true,label="§aHellgrün Schimmernder Plastikblock",tag={}},
 mekanism_jj_glowplasticblock_jj_11={hasPattern=true,label="§eGelb Schimmernder Plastikblock",tag={}},
 mekanism_jj_glowplasticblock_jj_12={hasPattern=true,label="§9Hellblau Schimmernder Plastikblock",tag={}},
 mekanism_jj_glowplasticblock_jj_13={hasPattern=true,label="§dMagentafarben Schimmernder Plastikblock",tag={}},
 mekanism_jj_glowplasticblock_jj_14={hasPattern=true,label="§6Orange Schimmernder Plastikblock",tag={}},
 mekanism_jj_glowplasticblock_jj_15={hasPattern=true,label="§fWeiß Schimmernder Plastikblock",tag={}},
 mekanism_jj_glowplasticblock_jj_2={hasPattern=true,label="§2Grün Schimmernder Plastikblock",tag={}},
 mekanism_jj_glowplasticblock_jj_3={hasPattern=true,label="§6Braun Schimmernder Plastikblock",tag={}},
 mekanism_jj_glowplasticblock_jj_4={hasPattern=true,label="§1Blau Schimmernder Plastikblock",tag={}},
 mekanism_jj_glowplasticblock_jj_5={hasPattern=true,label="§5Violett Schimmernder Plastikblock",tag={}},
 mekanism_jj_glowplasticblock_jj_6={hasPattern=true,label="§3Türkis Schimmernder Plastikblock",tag={}},
 mekanism_jj_glowplasticblock_jj_7={hasPattern=true,label="§7Hellgrau Schimmernder Plastikblock",tag={}},
 mekanism_jj_glowplasticblock_jj_8={hasPattern=true,label="§8Grau Schimmernder Plastikblock",tag={}},
 mekanism_jj_glowplasticblock_jj_9={hasPattern=true,label="§dPink Schimmernder Plastikblock",tag={}},
 mekanism_jj_ingot={hasPattern=false,label="",tag={}},
 mekanism_jj_ingot_jj_1={hasPattern=false,label="",tag={}},
 mekanism_jj_ingot_jj_2={hasPattern=true,label="Bronzebarren",tag={}},
 mekanism_jj_ingot_jj_3={hasPattern=false,label="",tag={}},
 mekanism_jj_ingot_jj_4={hasPattern=true,label="Stahlbarren",tag={}},
 mekanism_jj_ingot_jj_5={hasPattern=false,label="",tag={}},
 mekanism_jj_ingot_jj_6={hasPattern=false,label="",tag={}},
 mekanism_jj_itemproxy={hasPattern=false,label="",tag={}},
 mekanism_jj_jetpack={hasPattern=false,label="",tag={}},
 mekanism_jj_jetpack_b_1={hasPattern=true,label="Jetpack",tag={mekData={stored={amount=24000,gasName="hydrogen"}}}},
 mekanism_jj_machineblock={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock2={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock2_jj_1={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock2_jj_10={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock2_jj_11={hasPattern=false,label="",tag={tier=0}},
 mekanism_jj_machineblock2_jj_11_b_1={hasPattern=false,label="",tag={tier=1}},
 mekanism_jj_machineblock2_jj_11_b_2={hasPattern=false,label="",tag={tier=2}},
 mekanism_jj_machineblock2_jj_11_b_3={hasPattern=false,label="",tag={tier=3}},
 mekanism_jj_machineblock2_jj_11_b_4={hasPattern=false,label="",tag={tier=4}},
 mekanism_jj_machineblock2_jj_12={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock2_jj_13={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock2_jj_14={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock2_jj_15={hasPattern=true,label="Laser-Traktorstrahl",tag={}},
 mekanism_jj_machineblock2_jj_2={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock2_jj_3={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock2_jj_4={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock2_jj_5={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock2_jj_6={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock2_jj_7={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock2_jj_8={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock2_jj_9={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock3={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock3_jj_1={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock3_jj_3={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock3_jj_4={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock3_jj_5={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock3_jj_6={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock_jj_1={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock_jj_10={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock_jj_11={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock_jj_12={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock_jj_13={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock_jj_14={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock_jj_15={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock_jj_2={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock_jj_3={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock_jj_4={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock_jj_5={hasPattern=false,label="",tag={recipeType=0}},
 mekanism_jj_machineblock_jj_5_b_1={hasPattern=false,label="",tag={recipeType=1}},
 mekanism_jj_machineblock_jj_5_b_2={hasPattern=false,label="",tag={recipeType=2}},
 mekanism_jj_machineblock_jj_5_b_3={hasPattern=false,label="",tag={recipeType=3}},
 mekanism_jj_machineblock_jj_5_b_4={hasPattern=false,label="",tag={recipeType=4}},
 mekanism_jj_machineblock_jj_5_b_5={hasPattern=false,label="",tag={recipeType=5}},
 mekanism_jj_machineblock_jj_5_b_6={hasPattern=false,label="",tag={recipeType=6}},
 mekanism_jj_machineblock_jj_5_b_7={hasPattern=false,label="",tag={recipeType=7}},
 mekanism_jj_machineblock_jj_5_b_8={hasPattern=false,label="",tag={recipeType=8}},
 mekanism_jj_machineblock_jj_6={hasPattern=false,label="",tag={recipeType=0}},
 mekanism_jj_machineblock_jj_6_b_1={hasPattern=false,label="",tag={recipeType=1}},
 mekanism_jj_machineblock_jj_6_b_2={hasPattern=false,label="",tag={recipeType=2}},
 mekanism_jj_machineblock_jj_6_b_3={hasPattern=false,label="",tag={recipeType=3}},
 mekanism_jj_machineblock_jj_6_b_4={hasPattern=false,label="",tag={recipeType=4}},
 mekanism_jj_machineblock_jj_6_b_5={hasPattern=false,label="",tag={recipeType=5}},
 mekanism_jj_machineblock_jj_6_b_6={hasPattern=false,label="",tag={recipeType=6}},
 mekanism_jj_machineblock_jj_6_b_7={hasPattern=false,label="",tag={recipeType=7}},
 mekanism_jj_machineblock_jj_6_b_8={hasPattern=false,label="",tag={recipeType=8}},
 mekanism_jj_machineblock_jj_7={hasPattern=false,label="",tag={recipeType=0}},
 mekanism_jj_machineblock_jj_7_b_1={hasPattern=false,label="",tag={recipeType=1}},
 mekanism_jj_machineblock_jj_7_b_2={hasPattern=false,label="",tag={recipeType=2}},
 mekanism_jj_machineblock_jj_7_b_3={hasPattern=false,label="",tag={recipeType=3}},
 mekanism_jj_machineblock_jj_7_b_4={hasPattern=false,label="",tag={recipeType=4}},
 mekanism_jj_machineblock_jj_7_b_5={hasPattern=false,label="",tag={recipeType=5}},
 mekanism_jj_machineblock_jj_7_b_6={hasPattern=false,label="",tag={recipeType=6}},
 mekanism_jj_machineblock_jj_7_b_7={hasPattern=false,label="",tag={recipeType=7}},
 mekanism_jj_machineblock_jj_7_b_8={hasPattern=false,label="",tag={recipeType=8}},
 mekanism_jj_machineblock_jj_8={hasPattern=false,label="",tag={}},
 mekanism_jj_machineblock_jj_9={hasPattern=false,label="",tag={}},
 mekanism_jj_mufflingupgrade={hasPattern=true,label="Schalldämpfer-Upgrade",tag={}},
 mekanism_jj_networkreader={hasPattern=false,label="",tag={}},
 mekanism_jj_networkreader_b_1={hasPattern=true,label="Netzwerklesegerät",tag={}},
 mekanism_jj_nugget={hasPattern=true,label="Refined Obsidian Nugget",tag={}},
 mekanism_jj_nugget_jj_1={hasPattern=true,label="Osmium Nugget",tag={}},
 mekanism_jj_nugget_jj_2={hasPattern=true,label="Bronze Nugget",tag={}},
 mekanism_jj_nugget_jj_3={hasPattern=true,label="Glowstone Nugget",tag={}},
 mekanism_jj_nugget_jj_4={hasPattern=true,label="Steel Nugget",tag={}},
 mekanism_jj_nugget_jj_5={hasPattern=true,label="Copper Nugget",tag={}},
 mekanism_jj_nugget_jj_6={hasPattern=true,label="Tin Nugget",tag={}},
 mekanism_jj_obsidiantnt={hasPattern=true,label="Obsidian-TNT",tag={}},
 mekanism_jj_oreblock={hasPattern=false,label="",tag={}},
 mekanism_jj_oreblock_jj_1={hasPattern=false,label="",tag={}},
 mekanism_jj_oreblock_jj_2={hasPattern=false,label="",tag={}},
 mekanism_jj_otherdust={hasPattern=true,label="Diamantstaub",tag={}},
 mekanism_jj_otherdust_jj_1={hasPattern=true,label="Stahlstaub",tag={}},
 mekanism_jj_otherdust_jj_3={hasPattern=true,label="Schwefelstaub",tag={}},
 mekanism_jj_otherdust_jj_4={hasPattern=true,label="Lithiumstaub",tag={}},
 mekanism_jj_otherdust_jj_5={hasPattern=true,label="Raffinierter Obsidianstaub",tag={}},
 mekanism_jj_otherdust_jj_6={hasPattern=true,label="Obsidianstaub",tag={}},
 mekanism_jj_plasticblock={hasPattern=true,label="§8Schwarz Plastikblock",tag={}},
 mekanism_jj_plasticblock_jj_1={hasPattern=true,label="§cRot Plastikblock",tag={}},
 mekanism_jj_plasticblock_jj_10={hasPattern=true,label="§aHellgrün Plastikblock",tag={}},
 mekanism_jj_plasticblock_jj_11={hasPattern=true,label="§eGelb Plastikblock",tag={}},
 mekanism_jj_plasticblock_jj_12={hasPattern=true,label="§9Hellblau Plastikblock",tag={}},
 mekanism_jj_plasticblock_jj_13={hasPattern=true,label="§dMagentafarben Plastikblock",tag={}},
 mekanism_jj_plasticblock_jj_14={hasPattern=true,label="§6Orange Plastikblock",tag={}},
 mekanism_jj_plasticblock_jj_15={hasPattern=true,label="§fWeiß Plastikblock",tag={}},
 mekanism_jj_plasticblock_jj_2={hasPattern=true,label="§2Grün Plastikblock",tag={}},
 mekanism_jj_plasticblock_jj_3={hasPattern=true,label="§6Braun Plastikblock",tag={}},
 mekanism_jj_plasticblock_jj_4={hasPattern=true,label="§1Blau Plastikblock",tag={}},
 mekanism_jj_plasticblock_jj_5={hasPattern=true,label="§5Violett Plastikblock",tag={}},
 mekanism_jj_plasticblock_jj_6={hasPattern=true,label="§3Türkis Plastikblock",tag={}},
 mekanism_jj_plasticblock_jj_7={hasPattern=true,label="§7Hellgrau Plastikblock",tag={}},
 mekanism_jj_plasticblock_jj_8={hasPattern=true,label="§8Grau Plastikblock",tag={}},
 mekanism_jj_plasticblock_jj_9={hasPattern=true,label="§dPink Plastikblock",tag={}},
 mekanism_jj_plasticfence={hasPattern=true,label="§8Schwarz Plastikbarriere",tag={}},
 mekanism_jj_plasticfence_jj_1={hasPattern=true,label="§cRot Plastikbarriere",tag={}},
 mekanism_jj_plasticfence_jj_10={hasPattern=true,label="§aHellgrün Plastikbarriere",tag={}},
 mekanism_jj_plasticfence_jj_11={hasPattern=true,label="§eGelb Plastikbarriere",tag={}},
 mekanism_jj_plasticfence_jj_12={hasPattern=true,label="§9Hellblau Plastikbarriere",tag={}},
 mekanism_jj_plasticfence_jj_13={hasPattern=true,label="§dMagentafarben Plastikbarriere",tag={}},
 mekanism_jj_plasticfence_jj_14={hasPattern=true,label="§6Orange Plastikbarriere",tag={}},
 mekanism_jj_plasticfence_jj_15={hasPattern=true,label="§fWeiß Plastikbarriere",tag={}},
 mekanism_jj_plasticfence_jj_2={hasPattern=true,label="§2Grün Plastikbarriere",tag={}},
 mekanism_jj_plasticfence_jj_3={hasPattern=true,label="§6Braun Plastikbarriere",tag={}},
 mekanism_jj_plasticfence_jj_4={hasPattern=true,label="§1Blau Plastikbarriere",tag={}},
 mekanism_jj_plasticfence_jj_5={hasPattern=true,label="§5Violett Plastikbarriere",tag={}},
 mekanism_jj_plasticfence_jj_6={hasPattern=true,label="§3Türkis Plastikbarriere",tag={}},
 mekanism_jj_plasticfence_jj_7={hasPattern=true,label="§7Hellgrau Plastikbarriere",tag={}},
 mekanism_jj_plasticfence_jj_8={hasPattern=true,label="§8Grau Plastikbarriere",tag={}},
 mekanism_jj_plasticfence_jj_9={hasPattern=true,label="§dPink Plastikbarriere",tag={}},
 mekanism_jj_polyethene={hasPattern=false,label="",tag={}},
 mekanism_jj_polyethene_jj_1={hasPattern=true,label="HDPE-Stange",tag={}},
 mekanism_jj_polyethene_jj_2={hasPattern=false,label="HDPE-Bogen",tag={}},
 mekanism_jj_polyethene_jj_3={hasPattern=true,label="PlaStick",tag={}},
 mekanism_jj_portableteleporter={hasPattern=false,label="",tag={}},
 mekanism_jj_portableteleporter_b_1={hasPattern=true,label="Tragbarer Teleporter",tag={}},
 mekanism_jj_reinforcedalloy={hasPattern=true,label="Verstärkte Legierung",tag={}},
 mekanism_jj_reinforcedplasticblock={hasPattern=true,label="§8Schwarz Verstärkter Plastikblock",tag={}},
 mekanism_jj_reinforcedplasticblock_jj_1={hasPattern=true,label="§cRot Verstärkter Plastikblock",tag={}},
 mekanism_jj_reinforcedplasticblock_jj_10={hasPattern=true,label="§aHellgrün Verstärkter Plastikblock",tag={}},
 mekanism_jj_reinforcedplasticblock_jj_11={hasPattern=true,label="§eGelb Verstärkter Plastikblock",tag={}},
 mekanism_jj_reinforcedplasticblock_jj_12={hasPattern=true,label="§9Hellblau Verstärkter Plastikblock",tag={}},
 mekanism_jj_reinforcedplasticblock_jj_13={hasPattern=true,label="§dMagentafarben Verstärkter Plastikblock",tag={}},
 mekanism_jj_reinforcedplasticblock_jj_14={hasPattern=true,label="§6Orange Verstärkter Plastikblock",tag={}},
 mekanism_jj_reinforcedplasticblock_jj_15={hasPattern=true,label="§fWeiß Verstärkter Plastikblock",tag={}},
 mekanism_jj_reinforcedplasticblock_jj_2={hasPattern=true,label="§2Grün Verstärkter Plastikblock",tag={}},
 mekanism_jj_reinforcedplasticblock_jj_3={hasPattern=true,label="§6Braun Verstärkter Plastikblock",tag={}},
 mekanism_jj_reinforcedplasticblock_jj_4={hasPattern=true,label="§1Blau Verstärkter Plastikblock",tag={}},
 mekanism_jj_reinforcedplasticblock_jj_5={hasPattern=true,label="§5Violett Verstärkter Plastikblock",tag={}},
 mekanism_jj_reinforcedplasticblock_jj_6={hasPattern=true,label="§3Türkis Verstärkter Plastikblock",tag={}},
 mekanism_jj_reinforcedplasticblock_jj_7={hasPattern=true,label="§7Hellgrau Verstärkter Plastikblock",tag={}},
 mekanism_jj_reinforcedplasticblock_jj_8={hasPattern=true,label="§8Grau Verstärkter Plastikblock",tag={}},
 mekanism_jj_reinforcedplasticblock_jj_9={hasPattern=true,label="§dPink Verstärkter Plastikblock",tag={}},
 mekanism_jj_roadplasticblock={hasPattern=true,label="§8Schwarz Plastikstraße",tag={}},
 mekanism_jj_roadplasticblock_jj_1={hasPattern=true,label="§cRot Plastikstraße",tag={}},
 mekanism_jj_roadplasticblock_jj_10={hasPattern=true,label="§aHellgrün Plastikstraße",tag={}},
 mekanism_jj_roadplasticblock_jj_11={hasPattern=true,label="§eGelb Plastikstraße",tag={}},
 mekanism_jj_roadplasticblock_jj_12={hasPattern=true,label="§9Hellblau Plastikstraße",tag={}},
 mekanism_jj_roadplasticblock_jj_13={hasPattern=true,label="§dMagentafarben Plastikstraße",tag={}},
 mekanism_jj_roadplasticblock_jj_14={hasPattern=true,label="§6Orange Plastikstraße",tag={}},
 mekanism_jj_roadplasticblock_jj_15={hasPattern=true,label="§fWeiß Plastikstraße",tag={}},
 mekanism_jj_roadplasticblock_jj_2={hasPattern=true,label="§2Grün Plastikstraße",tag={}},
 mekanism_jj_roadplasticblock_jj_3={hasPattern=true,label="§6Braun Plastikstraße",tag={}},
 mekanism_jj_roadplasticblock_jj_4={hasPattern=true,label="§1Blau Plastikstraße",tag={}},
 mekanism_jj_roadplasticblock_jj_5={hasPattern=true,label="§5Violett Plastikstraße",tag={}},
 mekanism_jj_roadplasticblock_jj_6={hasPattern=true,label="§3Türkis Plastikstraße",tag={}},
 mekanism_jj_roadplasticblock_jj_7={hasPattern=true,label="§7Hellgrau Plastikstraße",tag={}},
 mekanism_jj_roadplasticblock_jj_8={hasPattern=true,label="§8Grau Plastikstraße",tag={}},
 mekanism_jj_roadplasticblock_jj_9={hasPattern=true,label="§dPink Plastikstraße",tag={}},
 mekanism_jj_robit={hasPattern=false,label="",tag={}},
 mekanism_jj_robit_b_1={hasPattern=true,label="Robit",tag={}},
 mekanism_jj_salt={hasPattern=true,label="Salz",tag={}},
 mekanism_jj_saltblock={hasPattern=true,label="Salzblock",tag={}},
 mekanism_jj_sawdust={hasPattern=true,label="Sägemehl",tag={}},
 mekanism_jj_scubatank={hasPattern=false,label="",tag={}},
 mekanism_jj_scubatank_b_1={hasPattern=true,label="Taucherflasche",tag={mekData={}}},
 mekanism_jj_seismicreader={hasPattern=false,label="",tag={}},
 mekanism_jj_seismicreader_b_1={hasPattern=true,label="Seismisches Lesegerät",tag={}},
 mekanism_jj_shard={hasPattern=false,label="",tag={}},
 mekanism_jj_shard_jj_1={hasPattern=false,label="",tag={}},
 mekanism_jj_shard_jj_2={hasPattern=false,label="",tag={}},
 mekanism_jj_shard_jj_3={hasPattern=false,label="",tag={}},
 mekanism_jj_shard_jj_4={hasPattern=false,label="",tag={}},
 mekanism_jj_shard_jj_5={hasPattern=false,label="",tag={}},
 mekanism_jj_shard_jj_6={hasPattern=false,label="",tag={}},
 mekanism_jj_slickplasticblock={hasPattern=true,label="§8Schwarz Glatter Plastikblock",tag={}},
 mekanism_jj_slickplasticblock_jj_1={hasPattern=true,label="§cRot Glatter Plastikblock",tag={}},
 mekanism_jj_slickplasticblock_jj_10={hasPattern=true,label="§aHellgrün Glatter Plastikblock",tag={}},
 mekanism_jj_slickplasticblock_jj_11={hasPattern=true,label="§eGelb Glatter Plastikblock",tag={}},
 mekanism_jj_slickplasticblock_jj_12={hasPattern=true,label="§9Hellblau Glatter Plastikblock",tag={}},
 mekanism_jj_slickplasticblock_jj_13={hasPattern=true,label="§dMagentafarben Glatter Plastikblock",tag={}},
 mekanism_jj_slickplasticblock_jj_14={hasPattern=true,label="§6Orange Glatter Plastikblock",tag={}},
 mekanism_jj_slickplasticblock_jj_15={hasPattern=true,label="§fWeiß Glatter Plastikblock",tag={}},
 mekanism_jj_slickplasticblock_jj_2={hasPattern=true,label="§2Grün Glatter Plastikblock",tag={}},
 mekanism_jj_slickplasticblock_jj_3={hasPattern=true,label="§6Braun Glatter Plastikblock",tag={}},
 mekanism_jj_slickplasticblock_jj_4={hasPattern=true,label="§1Blau Glatter Plastikblock",tag={}},
 mekanism_jj_slickplasticblock_jj_5={hasPattern=true,label="§5Violett Glatter Plastikblock",tag={}},
 mekanism_jj_slickplasticblock_jj_6={hasPattern=true,label="§3Türkis Glatter Plastikblock",tag={}},
 mekanism_jj_slickplasticblock_jj_7={hasPattern=true,label="§7Hellgrau Glatter Plastikblock",tag={}},
 mekanism_jj_slickplasticblock_jj_8={hasPattern=true,label="§8Grau Glatter Plastikblock",tag={}},
 mekanism_jj_slickplasticblock_jj_9={hasPattern=true,label="§dPink Glatter Plastikblock",tag={}},
 mekanism_jj_speedupgrade={hasPattern=true,label="Geschwindigkeitsupgrade",tag={}},
 mekanism_jj_substrate={hasPattern=false,label="",tag={}},
 mekanism_jj_teleportationcore={hasPattern=true,label="Teleportationskern",tag={}},
 mekanism_jj_tierinstaller={hasPattern=true,label="Gewöhnlich Stufe Einbauwerkzeug",tag={}},
 mekanism_jj_tierinstaller_jj_1={hasPattern=true,label="Fortgeschritten Stufe Einbauwerkzeug",tag={}},
 mekanism_jj_tierinstaller_jj_2={hasPattern=true,label="Elite Stufe Einbauwerkzeug",tag={}},
 mekanism_jj_tierinstaller_jj_3={hasPattern=true,label="Ultimativ Stufe Einbauwerkzeug",tag={}},
 mekanism_jj_transmitter={hasPattern=false,label="",tag={tier=0}},
 mekanism_jj_transmitter_b_1={hasPattern=false,label="",tag={tier=1}},
 mekanism_jj_transmitter_b_2={hasPattern=false,label="",tag={tier=2}},
 mekanism_jj_transmitter_b_3={hasPattern=false,label="",tag={tier=3}},
 mekanism_jj_transmitter_jj_1={hasPattern=false,label="",tag={tier=0}},
 mekanism_jj_transmitter_jj_1_b_1={hasPattern=false,label="",tag={tier=1}},
 mekanism_jj_transmitter_jj_1_b_2={hasPattern=false,label="",tag={tier=2}},
 mekanism_jj_transmitter_jj_1_b_3={hasPattern=false,label="",tag={tier=3}},
 mekanism_jj_transmitter_jj_2={hasPattern=false,label="",tag={tier=0}},
 mekanism_jj_transmitter_jj_2_b_1={hasPattern=false,label="",tag={tier=1}},
 mekanism_jj_transmitter_jj_2_b_2={hasPattern=false,label="",tag={tier=2}},
 mekanism_jj_transmitter_jj_2_b_3={hasPattern=false,label="",tag={tier=3}},
 mekanism_jj_transmitter_jj_3={hasPattern=false,label="",tag={tier=0}},
 mekanism_jj_transmitter_jj_3_b_1={hasPattern=false,label="",tag={tier=1}},
 mekanism_jj_transmitter_jj_3_b_2={hasPattern=false,label="",tag={tier=2}},
 mekanism_jj_transmitter_jj_3_b_3={hasPattern=false,label="",tag={tier=3}},
 mekanism_jj_transmitter_jj_4={hasPattern=false,label="",tag={tier=0}},
 mekanism_jj_transmitter_jj_5={hasPattern=false,label="",tag={tier=0}},
 mekanism_jj_transmitter_jj_6={hasPattern=false,label="",tag={tier=0}},
 mekanism_jj_transmitter_jj_6_b_1={hasPattern=false,label="",tag={tier=1}},
 mekanism_jj_transmitter_jj_6_b_2={hasPattern=false,label="",tag={tier=2}},
 mekanism_jj_transmitter_jj_6_b_3={hasPattern=false,label="",tag={tier=3}},
 mekanism_jj_walkietalkie={hasPattern=false,label="",tag={}},
 mekanismgenerators_jj_generator={hasPattern=true,label="Hitzegenerator",tag={}},
 mekanismgenerators_jj_generator_jj_1={hasPattern=true,label="Solargenerator",tag={}},
 mekanismgenerators_jj_generator_jj_10={hasPattern=true,label="Turbinengehäuse",tag={}},
 mekanismgenerators_jj_generator_jj_11={hasPattern=false,label="",tag={}},
 mekanismgenerators_jj_generator_jj_12={hasPattern=true,label="Turbinenabzug",tag={}},
 mekanismgenerators_jj_generator_jj_13={hasPattern=true,label="Saturating Condenser",tag={}},
 mekanismgenerators_jj_generator_jj_3={hasPattern=true,label="Gasverbrennender Generator",tag={}},
 mekanismgenerators_jj_generator_jj_4={hasPattern=true,label="Bio-Generator",tag={}},
 mekanismgenerators_jj_generator_jj_5={hasPattern=false,label="",tag={}},
 mekanismgenerators_jj_generator_jj_6={hasPattern=true,label="Windgenerator",tag={}},
 mekanismgenerators_jj_generator_jj_7={hasPattern=true,label="Turbinenrotor",tag={}},
 mekanismgenerators_jj_generator_jj_8={hasPattern=true,label="Rotationskomplex",tag={}},
 mekanismgenerators_jj_generator_jj_9={hasPattern=true,label="Elektromagnetische Spule",tag={}},
 mekanismgenerators_jj_hohlraum={hasPattern=false,label="",tag={}},
 mekanismgenerators_jj_hohlraum_b_1={hasPattern=true,label="Hohlraum",tag={mekData={}}},
 mekanismgenerators_jj_reactor={hasPattern=true,label="Reaktor-Controller",tag={}},
 mekanismgenerators_jj_reactor_jj_1={hasPattern=true,label="Reaktorrahmen",tag={}},
 mekanismgenerators_jj_reactor_jj_2={hasPattern=true,label="Reaktorport",tag={}},
 mekanismgenerators_jj_reactor_jj_3={hasPattern=true,label="Reaktor-Logikadapter",tag={}},
 mekanismgenerators_jj_reactorglass={hasPattern=true,label="Reaktorglas",tag={}},
 mekanismgenerators_jj_reactorglass_jj_1={hasPattern=true,label="Laser-Fokusmatrix",tag={}},
 mekanismgenerators_jj_solarpanel={hasPattern=true,label="Solarmodul",tag={}},
 mekanismgenerators_jj_turbineblade={hasPattern=true,label="Rotorblatt",tag={}},
 mekanismtools_jj_bronzeaxe={hasPattern=true,label="Bronzeaxt",tag={}},
 mekanismtools_jj_bronzeboots={hasPattern=true,label="Bronzestiefel",tag={}},
 mekanismtools_jj_bronzechestplate={hasPattern=true,label="Bronzebrustpanzer",tag={}},
 mekanismtools_jj_bronzehelmet={hasPattern=true,label="Bronzehelm",tag={}},
 mekanismtools_jj_bronzehoe={hasPattern=true,label="Bronzehacke",tag={}},
 mekanismtools_jj_bronzeleggings={hasPattern=true,label="Bronzebeinschutz",tag={}},
 mekanismtools_jj_bronzepaxel={hasPattern=true,label="Bronze-Paxel",tag={}},
 mekanismtools_jj_bronzepickaxe={hasPattern=true,label="Bronzespitzhacke",tag={}},
 mekanismtools_jj_bronzeshovel={hasPattern=true,label="Bronzeschaufel",tag={}},
 mekanismtools_jj_bronzesword={hasPattern=true,label="Bronzeschwert",tag={}},
 mekanismtools_jj_diamondpaxel={hasPattern=true,label="Diamant-Paxel",tag={}},
 mekanismtools_jj_glowstoneaxe={hasPattern=true,label="Glowstone-Axt",tag={}},
 mekanismtools_jj_glowstoneboots={hasPattern=true,label="Glowstone-Stiefel",tag={}},
 mekanismtools_jj_glowstonechestplate={hasPattern=true,label="Glowstone-Brustpanzer",tag={}},
 mekanismtools_jj_glowstonehelmet={hasPattern=true,label="Glowstone-Helm",tag={}},
 mekanismtools_jj_glowstonehoe={hasPattern=true,label="Glowstone-Hacke",tag={}},
 mekanismtools_jj_glowstoneleggings={hasPattern=true,label="Glowstone-Beinschutz",tag={}},
 mekanismtools_jj_glowstonepaxel={hasPattern=true,label="Glowstone-Paxel",tag={}},
 mekanismtools_jj_glowstonepickaxe={hasPattern=true,label="Glowstone-Spitzhacke",tag={}},
 mekanismtools_jj_glowstoneshovel={hasPattern=true,label="Glowstone-Schaufel",tag={}},
 mekanismtools_jj_glowstonesword={hasPattern=true,label="Glowstone-Schwert",tag={}},
 mekanismtools_jj_goldpaxel={hasPattern=true,label="Gold-Paxel",tag={}},
 mekanismtools_jj_ironpaxel={hasPattern=true,label="Eisen-Paxel",tag={}},
 mekanismtools_jj_lapislazuliaxe={hasPattern=true,label="Lapis Lazuli Axe",tag={}},
 mekanismtools_jj_lapislazuliboots={hasPattern=true,label="Lapis Lazuli Boots",tag={}},
 mekanismtools_jj_lapislazulichestplate={hasPattern=true,label="Lapis Lazuli Chestplate",tag={}},
 mekanismtools_jj_lapislazulihelmet={hasPattern=true,label="Lapis Lazuli Helmet",tag={}},
 mekanismtools_jj_lapislazulihoe={hasPattern=true,label="Lapis Lazuli Hoe",tag={}},
 mekanismtools_jj_lapislazulileggings={hasPattern=true,label="Lapis Lazuli Leggings",tag={}},
 mekanismtools_jj_lapislazulipaxel={hasPattern=true,label="Lapis Lazuli Paxel",tag={}},
 mekanismtools_jj_lapislazulipickaxe={hasPattern=true,label="Lapis Lazuli Pickaxe",tag={}},
 mekanismtools_jj_lapislazulishovel={hasPattern=true,label="Lapis Lazuli Shovel",tag={}},
 mekanismtools_jj_lapislazulisword={hasPattern=true,label="Lapis Lazuli Sword",tag={}},
 mekanismtools_jj_obsidianaxe={hasPattern=true,label="Obsidianaxt",tag={}},
 mekanismtools_jj_obsidianboots={hasPattern=true,label="Obsidianstiefel",tag={}},
 mekanismtools_jj_obsidianchestplate={hasPattern=true,label="Obsidianbrustpanzer",tag={}},
 mekanismtools_jj_obsidianhelmet={hasPattern=true,label="Obsidianhelm",tag={}},
 mekanismtools_jj_obsidianhoe={hasPattern=true,label="Obsidianhacke",tag={}},
 mekanismtools_jj_obsidianleggings={hasPattern=true,label="Obsidianbeinschutz",tag={}},
 mekanismtools_jj_obsidianpaxel={hasPattern=true,label="Obsidian-Paxel",tag={}},
 mekanismtools_jj_obsidianpickaxe={hasPattern=true,label="Obsidianspitzhacke",tag={}},
 mekanismtools_jj_obsidianshovel={hasPattern=true,label="Obsidianschaufel",tag={}},
 mekanismtools_jj_obsidiansword={hasPattern=true,label="Obsidianschwert",tag={}},
 mekanismtools_jj_osmiumaxe={hasPattern=true,label="Osmiumaxt",tag={}},
 mekanismtools_jj_osmiumboots={hasPattern=true,label="Osmiumstiefel",tag={}},
 mekanismtools_jj_osmiumchestplate={hasPattern=true,label="Osmiumbrustpanzer",tag={}},
 mekanismtools_jj_osmiumhelmet={hasPattern=true,label="Osmiumhelm",tag={}},
 mekanismtools_jj_osmiumhoe={hasPattern=true,label="Osmiumhacke",tag={}},
 mekanismtools_jj_osmiumleggings={hasPattern=true,label="Osmiumbeinschutz",tag={}},
 mekanismtools_jj_osmiumpaxel={hasPattern=true,label="Osmium-Paxel",tag={}},
 mekanismtools_jj_osmiumpickaxe={hasPattern=true,label="Osmiumspitzhacke",tag={}},
 mekanismtools_jj_osmiumshovel={hasPattern=true,label="Osmiumschaufel",tag={}},
 mekanismtools_jj_osmiumsword={hasPattern=true,label="Osmiumschwert",tag={}},
 mekanismtools_jj_steelaxe={hasPattern=true,label="Stahlaxt",tag={}},
 mekanismtools_jj_steelboots={hasPattern=true,label="Stahlstiefel",tag={}},
 mekanismtools_jj_steelchestplate={hasPattern=true,label="Stahlbrustpanzer",tag={}},
 mekanismtools_jj_steelhelmet={hasPattern=true,label="Stahlhelm",tag={}},
 mekanismtools_jj_steelhoe={hasPattern=true,label="Stahlhacke",tag={}},
 mekanismtools_jj_steelleggings={hasPattern=true,label="Stahlbeinschutz",tag={}},
 mekanismtools_jj_steelpaxel={hasPattern=true,label="Stahl-Paxel",tag={}},
 mekanismtools_jj_steelpickaxe={hasPattern=true,label="Stahlspitzhacke",tag={}},
 mekanismtools_jj_steelshovel={hasPattern=true,label="Stahlschaufel",tag={}},
 mekanismtools_jj_steelsword={hasPattern=true,label="Stahlschwert",tag={}},
 mekanismtools_jj_stonepaxel={hasPattern=true,label="Stein-Paxel",tag={}},
 mekanismtools_jj_woodpaxel={hasPattern=true,label="Holz-Paxel",tag={}}
 }