return {
 minewatch_jj_ana_boots={hasPattern=true,label="Ana Stiefel",tag=""},
 minewatch_jj_ana_chestplate={hasPattern=true,label="Ana Brustpanzer",tag=""},
 minewatch_jj_ana_helmet={hasPattern=true,label="Ana Helm",tag=""},
 minewatch_jj_ana_leggings={hasPattern=true,label="Ana Beinschutz",tag=""},
 minewatch_jj_ana_token={hasPattern=false,label="",tag=""},
 minewatch_jj_ana_weapon={hasPattern=true,label="Ana's Biotisches Gewehr",tag=""},
 minewatch_jj_bastion_boots={hasPattern=true,label="Bastion Stiefel",tag=""},
 minewatch_jj_bastion_chestplate={hasPattern=true,label="Bastion Brustpanzer",tag=""},
 minewatch_jj_bastion_helmet={hasPattern=true,label="Bastion Helm",tag=""},
 minewatch_jj_bastion_leggings={hasPattern=true,label="Bastion Beinschutz",tag=""},
 minewatch_jj_bastion_token={hasPattern=false,label="",tag=""},
 minewatch_jj_bastion_weapon={hasPattern=true,label="Bastion's Maschinengewehr",tag=""},
 minewatch_jj_death_block={hasPattern=false,label="",tag=""},
 minewatch_jj_doomfist_boots={hasPattern=true,label="Doomfist Stiefel",tag=""},
 minewatch_jj_doomfist_chestplate={hasPattern=true,label="Doomfist Brustpanzer",tag=""},
 minewatch_jj_doomfist_helmet={hasPattern=true,label="Doomfist Helm",tag=""},
 minewatch_jj_doomfist_leggings={hasPattern=true,label="Doomfist Beinschutz",tag=""},
 minewatch_jj_doomfist_token={hasPattern=false,label="",tag=""},
 minewatch_jj_doomfist_weapon={hasPattern=true,label="Doomfist's Handschuh",tag=""},
 minewatch_jj_genji_boots={hasPattern=true,label="Genji Stiefel",tag=""},
 minewatch_jj_genji_chestplate={hasPattern=true,label="Genji Brustpanzer",tag=""},
 minewatch_jj_genji_helmet={hasPattern=true,label="Genji Helm",tag=""},
 minewatch_jj_genji_leggings={hasPattern=true,label="Genji Beinschutz",tag=""},
 minewatch_jj_genji_shuriken_single={hasPattern=false,label="",tag=""},
 minewatch_jj_genji_token={hasPattern=false,label="",tag=""},
 minewatch_jj_genji_weapon={hasPattern=true,label="Genji's Shuriken",tag=""},
 minewatch_jj_hanzo_boots={hasPattern=true,label="Hanzo Stiefel",tag=""},
 minewatch_jj_hanzo_chestplate={hasPattern=true,label="Hanzo Brustpanzer",tag=""},
 minewatch_jj_hanzo_helmet={hasPattern=true,label="Hanzo Helm",tag=""},
 minewatch_jj_hanzo_leggings={hasPattern=true,label="Hanzo Beinschutz",tag=""},
 minewatch_jj_hanzo_token={hasPattern=false,label="",tag=""},
 minewatch_jj_hanzo_weapon={hasPattern=true,label="Hanzo's Sturmbogen",tag=""},
 minewatch_jj_health_pack_large={hasPattern=true,label="großes Heilungspaket",tag=""},
 minewatch_jj_health_pack_small={hasPattern=true,label="kleines Heilungspaket",tag=""},
 minewatch_jj_junkrat_boots={hasPattern=true,label="Junkrat Stiefel",tag=""},
 minewatch_jj_junkrat_chestplate={hasPattern=true,label="Junkrat Brustpanzer",tag=""},
 minewatch_jj_junkrat_helmet={hasPattern=true,label="Junkrat Helm",tag=""},
 minewatch_jj_junkrat_leggings={hasPattern=true,label="Junkrat Beinschutz",tag=""},
 minewatch_jj_junkrat_token={hasPattern=false,label="",tag=""},
 minewatch_jj_junkrat_trigger={hasPattern=false,label="",tag=""},
 minewatch_jj_junkrat_weapon={hasPattern=true,label="Junkrat's Granatwerfer",tag=""},
 minewatch_jj_lucio_boots={hasPattern=true,label="Lucio Stiefel",tag=""},
 minewatch_jj_lucio_chestplate={hasPattern=true,label="Lucio Brustpanzer",tag=""},
 minewatch_jj_lucio_helmet={hasPattern=true,label="Lucio Helm",tag=""},
 minewatch_jj_lucio_leggings={hasPattern=true,label="Lucio Beinschutz",tag=""},
 minewatch_jj_lucio_token={hasPattern=false,label="",tag=""},
 minewatch_jj_lucio_weapon={hasPattern=true,label="Lucio's Schallverstärker",tag=""},
 minewatch_jj_mccree_boots={hasPattern=true,label="McCree Stiefel",tag=""},
 minewatch_jj_mccree_chestplate={hasPattern=true,label="McCree Brustpanzer",tag=""},
 minewatch_jj_mccree_helmet={hasPattern=true,label="McCree Helm",tag=""},
 minewatch_jj_mccree_leggings={hasPattern=true,label="McCree Beinschutz",tag=""},
 minewatch_jj_mccree_token={hasPattern=false,label="",tag=""},
 minewatch_jj_mccree_weapon={hasPattern=true,label="McCree's Friedensstifter",tag=""},
 minewatch_jj_mei_boots={hasPattern=true,label="Mei Stiefel",tag=""},
 minewatch_jj_mei_chestplate={hasPattern=true,label="Mei Brustpanzer",tag=""},
 minewatch_jj_mei_helmet={hasPattern=true,label="Mei Helm",tag=""},
 minewatch_jj_mei_leggings={hasPattern=true,label="Mei Beinschutz",tag=""},
 minewatch_jj_mei_token={hasPattern=false,label="",tag=""},
 minewatch_jj_mei_weapon={hasPattern=true,label="Mei's Endothermischer Strahler",tag=""},
 minewatch_jj_mercy_boots={hasPattern=true,label="Mercy Stiefel",tag=""},
 minewatch_jj_mercy_chestplate={hasPattern=true,label="Mercy Brustpanzer",tag=""},
 minewatch_jj_mercy_helmet={hasPattern=true,label="Mercy Helm",tag=""},
 minewatch_jj_mercy_leggings={hasPattern=true,label="Mercy Beinschutz",tag=""},
 minewatch_jj_mercy_token={hasPattern=false,label="",tag=""},
 minewatch_jj_mercy_weapon={hasPattern=true,label="Caduceus Staff",tag=""},
 minewatch_jj_moira_boots={hasPattern=true,label="Moira Stiefel",tag=""},
 minewatch_jj_moira_chestplate={hasPattern=true,label="Moira Brustpanzer",tag=""},
 minewatch_jj_moira_helmet={hasPattern=true,label="Moira Helm",tag=""},
 minewatch_jj_moira_leggings={hasPattern=true,label="Moira Beinschutz",tag=""},
 minewatch_jj_moira_token={hasPattern=false,label="",tag=""},
 minewatch_jj_moira_weapon={hasPattern=true,label="Moira's Biotische Hand",tag=""},
 minewatch_jj_pharah_boots={hasPattern=true,label="Pharah Stiefel",tag=""},
 minewatch_jj_pharah_chestplate={hasPattern=true,label="Pharah Brustpanzer",tag=""},
 minewatch_jj_pharah_helmet={hasPattern=true,label="Pharah Helm",tag=""},
 minewatch_jj_pharah_leggings={hasPattern=true,label="Pharah Beinschutz",tag=""},
 minewatch_jj_pharah_token={hasPattern=false,label="",tag=""},
 minewatch_jj_pharah_weapon={hasPattern=true,label="Pharah's Raketenwerfer",tag=""},
 minewatch_jj_push_block={hasPattern=true,label="Schiebeblock",tag=""},
 minewatch_jj_reaper_boots={hasPattern=true,label="Reaper Stiefel",tag=""},
 minewatch_jj_reaper_chestplate={hasPattern=true,label="Reaper Brustpanzer",tag=""},
 minewatch_jj_reaper_helmet={hasPattern=true,label="Reaper Helm",tag=""},
 minewatch_jj_reaper_leggings={hasPattern=true,label="Reaper Beinschutz",tag=""},
 minewatch_jj_reaper_token={hasPattern=false,label="",tag=""},
 minewatch_jj_reaper_weapon={hasPattern=true,label="Reaper's Infernoschrotflinten",tag=""},
 minewatch_jj_reinhardt_boots={hasPattern=true,label="Reinhardt Stiefel",tag=""},
 minewatch_jj_reinhardt_chestplate={hasPattern=true,label="Reinhardt Brustpanzer",tag=""},
 minewatch_jj_reinhardt_helmet={hasPattern=true,label="Reinhardt Helm",tag=""},
 minewatch_jj_reinhardt_leggings={hasPattern=true,label="Reinhardt Beinschutz",tag=""},
 minewatch_jj_reinhardt_token={hasPattern=false,label="",tag=""},
 minewatch_jj_reinhardt_weapon={hasPattern=true,label="Reinhardt's Rakentenhammer",tag=""},
 minewatch_jj_roadhog_boots={hasPattern=true,label="Roadhog Stiefel",tag=""},
 minewatch_jj_roadhog_chestplate={hasPattern=true,label="Roadhog Brustpanzer",tag=""},
 minewatch_jj_roadhog_health={hasPattern=true,label="Roadhog's Lebenskanister",tag=""},
 minewatch_jj_roadhog_helmet={hasPattern=true,label="Roadhog Helm",tag=""},
 minewatch_jj_roadhog_leggings={hasPattern=true,label="Roadhog Beinschutz",tag=""},
 minewatch_jj_roadhog_token={hasPattern=false,label="",tag=""},
 minewatch_jj_roadhog_weapon={hasPattern=true,label="Roadhog's Schrottflinte",tag=""},
 minewatch_jj_soldier76_boots={hasPattern=true,label="Soldier 76 Stiefel",tag=""},
 minewatch_jj_soldier76_chestplate={hasPattern=true,label="Soldier 76 Brustpanzer",tag=""},
 minewatch_jj_soldier76_helmet={hasPattern=true,label="Soldier 76 Helm",tag=""},
 minewatch_jj_soldier76_leggings={hasPattern=true,label="Soldier 76 Beinschutz",tag=""},
 minewatch_jj_soldier76_token={hasPattern=false,label="",tag=""},
 minewatch_jj_soldier76_weapon={hasPattern=true,label="Soldier 76's Impulsgewehr",tag=""},
 minewatch_jj_sombra_boots={hasPattern=true,label="Sombra Stiefel",tag=""},
 minewatch_jj_sombra_chestplate={hasPattern=true,label="Sombra Brustpanzer",tag=""},
 minewatch_jj_sombra_hack={hasPattern=false,label="",tag=""},
 minewatch_jj_sombra_helmet={hasPattern=true,label="Sombra Helm",tag=""},
 minewatch_jj_sombra_leggings={hasPattern=true,label="Sombra Beinschutz",tag=""},
 minewatch_jj_sombra_token={hasPattern=false,label="",tag=""},
 minewatch_jj_sombra_weapon={hasPattern=true,label="Sombra's Maschinenpistole",tag=""},
 minewatch_jj_team_spawn={hasPattern=true,label="Teamspawn",tag=""},
 minewatch_jj_team_stick={hasPattern=true,label="Team Helfer",tag=""},
 minewatch_jj_tracer_boots={hasPattern=true,label="Tracer Stiefel",tag=""},
 minewatch_jj_tracer_chestplate={hasPattern=true,label="Tracer Brustpanzer",tag=""},
 minewatch_jj_tracer_helmet={hasPattern=true,label="Tracer Helm",tag=""},
 minewatch_jj_tracer_leggings={hasPattern=true,label="Tracer Beinschutz",tag=""},
 minewatch_jj_tracer_token={hasPattern=false,label="",tag=""},
 minewatch_jj_tracer_weapon={hasPattern=true,label="Tracer's Impulspistolen",tag=""},
 minewatch_jj_widowmaker_boots={hasPattern=true,label="Widowmaker Stiefel",tag=""},
 minewatch_jj_widowmaker_chestplate={hasPattern=true,label="Widowmaker Brustpanzer",tag=""},
 minewatch_jj_widowmaker_helmet={hasPattern=true,label="Widowmaker Helm",tag=""},
 minewatch_jj_widowmaker_leggings={hasPattern=true,label="Widowmaker Beinschutz",tag=""},
 minewatch_jj_widowmaker_token={hasPattern=false,label="",tag=""},
 minewatch_jj_widowmaker_weapon={hasPattern=true,label="Witwenkuss",tag=""},
 minewatch_jj_wild_card_token={hasPattern=false,label="",tag=""},
 minewatch_jj_zenyatta_boots={hasPattern=true,label="Zenyatta Stiefel",tag=""},
 minewatch_jj_zenyatta_chestplate={hasPattern=true,label="Zenyatta Brustpanzer",tag=""},
 minewatch_jj_zenyatta_helmet={hasPattern=true,label="Zenyatta Helm",tag=""},
 minewatch_jj_zenyatta_leggings={hasPattern=true,label="Zenyatta Beinschutz",tag=""},
 minewatch_jj_zenyatta_token={hasPattern=false,label="",tag=""},
 minewatch_jj_zenyatta_weapon={hasPattern=true,label="Zenyatta's Sphäre der Zerstörung",tag=""},
 mores_jj_aikar_axe={hasPattern=false,label="",tag=""},
 mores_jj_aikar_dust={hasPattern=true,label="Aikar Dust",tag=""},
 mores_jj_aikar_ingot={hasPattern=false,label="",tag=""},
 mores_jj_aikar_pickaxe={hasPattern=true,label="Aikar Pickaxe",tag=""},
 mores_jj_aikar_shovel={hasPattern=true,label="Aikar Shovel",tag=""},
 mores_jj_aikar_sword={hasPattern=false,label="",tag=""},
 mores_jj_aoci_axe={hasPattern=false,label="",tag=""},
 mores_jj_aoci_dust={hasPattern=true,label="Aoci Dust",tag=""},
 mores_jj_aoci_ingot={hasPattern=false,label="",tag=""},
 mores_jj_aoci_pickaxe={hasPattern=true,label="Aoci Pickaxe",tag=""},
 mores_jj_aoci_shovel={hasPattern=true,label="Aoci Shovel",tag=""},
 mores_jj_aoci_sword={hasPattern=false,label="",tag=""},
 mores_jj_aryxi_axe={hasPattern=false,label="",tag=""},
 mores_jj_aryxi_dust={hasPattern=true,label="Aryxi Dust",tag=""},
 mores_jj_aryxi_ingot={hasPattern=false,label="",tag=""},
 mores_jj_aryxi_pickaxe={hasPattern=false,label="",tag=""},
 mores_jj_aryxi_shovel={hasPattern=true,label="Aryxi Shovel",tag=""},
 mores_jj_aryxi_sword={hasPattern=true,label="Aryxi Sword",tag=""},
 mores_jj_ataru_dust={hasPattern=false,label="",tag=""},
 mores_jj_ataru_ingot={hasPattern=false,label="",tag=""},
 mores_jj_audu_axe={hasPattern=false,label="",tag=""},
 mores_jj_audu_dust={hasPattern=true,label="Audu Dust",tag=""},
 mores_jj_audu_ingot={hasPattern=false,label="",tag=""},
 mores_jj_audu_pickaxe={hasPattern=true,label="Audu Pickaxe",tag=""},
 mores_jj_audu_shovel={hasPattern=true,label="Audu Shovel",tag=""},
 mores_jj_audu_sword={hasPattern=false,label="",tag=""},
 mores_jj_aurine_dust={hasPattern=false,label="",tag=""},
 mores_jj_aurine_ore={hasPattern=false,label="",tag=""},
 mores_jj_ayzanite_dust={hasPattern=false,label="",tag=""},
 mores_jj_ayzanite_ore={hasPattern=false,label="",tag=""},
 mores_jj_bydoom_axe={hasPattern=true,label="Bydoom Axe",tag=""},
 mores_jj_bydoom_dust={hasPattern=true,label="Bydoom Dust",tag=""},
 mores_jj_bydoom_ingot={hasPattern=false,label="",tag=""},
 mores_jj_bydoom_pickaxe={hasPattern=true,label="Bydoom Pickaxe",tag=""},
 mores_jj_bydoom_shovel={hasPattern=true,label="Bydoom Shovel",tag=""},
 mores_jj_bydoom_sword={hasPattern=true,label="Bydoom Sword",tag=""},
 mores_jj_draxate_dust={hasPattern=false,label="",tag=""},
 mores_jj_draxate_ore={hasPattern=false,label="",tag=""},
 mores_jj_duxirete_axe={hasPattern=false,label="",tag=""},
 mores_jj_duxirete_dust={hasPattern=true,label="Duxirete Dust",tag=""},
 mores_jj_duxirete_ingot={hasPattern=false,label="",tag=""},
 mores_jj_duxirete_pickaxe={hasPattern=true,label="Duxirete Pickaxe",tag=""},
 mores_jj_duxirete_shovel={hasPattern=true,label="Duxirete Shovel",tag=""},
 mores_jj_duxirete_sword={hasPattern=false,label="",tag=""},
 mores_jj_eukavoynt_dust={hasPattern=false,label="",tag=""},
 mores_jj_eukavoynt_ore={hasPattern=false,label="",tag=""},
 mores_jj_irine_axe={hasPattern=false,label="",tag=""},
 mores_jj_irine_dust={hasPattern=true,label="Irine Dust",tag=""},
 mores_jj_irine_ingot={hasPattern=false,label="",tag=""},
 mores_jj_irine_pickaxe={hasPattern=false,label="",tag=""},
 mores_jj_irine_shovel={hasPattern=false,label="",tag=""},
 mores_jj_irine_sword={hasPattern=false,label="",tag=""},
 mores_jj_iturite_dust={hasPattern=false,label="",tag=""},
 mores_jj_iturite_ore={hasPattern=false,label="",tag=""},
 mores_jj_josawriline_axe={hasPattern=false,label="",tag=""},
 mores_jj_josawriline_dust={hasPattern=true,label="Josawriline Dust",tag=""},
 mores_jj_josawriline_ingot={hasPattern=false,label="",tag=""},
 mores_jj_josawriline_pickaxe={hasPattern=false,label="",tag=""},
 mores_jj_josawriline_shovel={hasPattern=false,label="",tag=""},
 mores_jj_josawriline_sword={hasPattern=true,label="Josawriline Sword",tag=""},
 mores_jj_murol_axe={hasPattern=true,label="Murol Axe",tag=""},
 mores_jj_murol_dust={hasPattern=true,label="Murol Dust",tag=""},
 mores_jj_murol_ingot={hasPattern=false,label="",tag=""},
 mores_jj_murol_pickaxe={hasPattern=true,label="Murol Pickaxe",tag=""},
 mores_jj_murol_shovel={hasPattern=true,label="Murol Shovel",tag=""},
 mores_jj_murol_sword={hasPattern=true,label="Murol Sword",tag=""},
 mores_jj_nether_aurine_ore={hasPattern=false,label="",tag=""},
 mores_jj_nether_ayzanite_ore={hasPattern=false,label="",tag=""},
 mores_jj_nether_draxate_ore={hasPattern=false,label="",tag=""},
 mores_jj_nether_eukavoynt_ore={hasPattern=false,label="",tag=""},
 mores_jj_nether_iturite_ore={hasPattern=false,label="",tag=""},
 mores_jj_nether_nodemite_ore={hasPattern=false,label="",tag=""},
 mores_jj_nether_phantom_ore={hasPattern=false,label="",tag=""},
 mores_jj_nether_sivenium_ore={hasPattern=false,label="",tag=""},
 mores_jj_nodemite_dust={hasPattern=false,label="",tag=""},
 mores_jj_nodemite_ore={hasPattern=false,label="",tag=""},
 mores_jj_odeznum_axe={hasPattern=true,label="Odeznum Axe",tag=""},
 mores_jj_odeznum_dust={hasPattern=true,label="Odeznum Dust",tag=""},
 mores_jj_odeznum_ingot={hasPattern=false,label="",tag=""},
 mores_jj_odeznum_pickaxe={hasPattern=true,label="Odeznum Pickaxe",tag=""},
 mores_jj_odeznum_shovel={hasPattern=true,label="Odeznum Shovel",tag=""},
 mores_jj_odeznum_sword={hasPattern=true,label="Odeznum Sword",tag=""},
 mores_jj_oivi_axe={hasPattern=true,label="Oivi Axe",tag=""},
 mores_jj_oivi_dust={hasPattern=true,label="Oivi Dust",tag=""},
 mores_jj_oivi_ingot={hasPattern=false,label="",tag=""},
 mores_jj_oivi_pickaxe={hasPattern=true,label="Oivi Pickaxe",tag=""},
 mores_jj_oivi_shovel={hasPattern=true,label="Oivi Shovel",tag=""},
 mores_jj_oivi_sword={hasPattern=true,label="Oivi Sword",tag=""},
 mores_jj_oivywon_axe={hasPattern=false,label="",tag=""},
 mores_jj_oivywon_dust={hasPattern=true,label="Oivywon Dust",tag=""},
 mores_jj_oivywon_ingot={hasPattern=false,label="",tag=""},
 mores_jj_oivywon_pickaxe={hasPattern=false,label="",tag=""},
 mores_jj_oivywon_shovel={hasPattern=false,label="",tag=""},
 mores_jj_oivywon_sword={hasPattern=false,label="",tag=""},
 mores_jj_oxaxagite_ore={hasPattern=false,label="",tag=""},
 mores_jj_petuxo_axe={hasPattern=false,label="",tag=""},
 mores_jj_petuxo_dust={hasPattern=true,label="Petuxo Dust",tag=""},
 mores_jj_petuxo_ingot={hasPattern=false,label="",tag=""},
 mores_jj_petuxo_pickaxe={hasPattern=false,label="",tag=""},
 mores_jj_petuxo_shovel={hasPattern=false,label="",tag=""},
 mores_jj_petuxo_sword={hasPattern=true,label="Petuxo Sword",tag=""},
 mores_jj_phantom_ore={hasPattern=false,label="",tag=""},
 mores_jj_phantom_shard={hasPattern=false,label="",tag=""},
 mores_jj_ro_axe={hasPattern=false,label="",tag=""},
 mores_jj_ro_dust={hasPattern=true,label="Ro Dust",tag=""},
 mores_jj_ro_ingot={hasPattern=false,label="",tag=""},
 mores_jj_ro_pickaxe={hasPattern=false,label="",tag=""},
 mores_jj_ro_shovel={hasPattern=false,label="",tag=""},
 mores_jj_ro_sword={hasPattern=true,label="Ro Sword",tag=""},
 mores_jj_sivenium_dust={hasPattern=false,label="",tag=""},
 mores_jj_sivenium_ore={hasPattern=false,label="",tag=""},
 mores_jj_susimen_axe={hasPattern=false,label="",tag=""},
 mores_jj_susimen_dust={hasPattern=true,label="Susimen Dust",tag=""},
 mores_jj_susimen_ingot={hasPattern=false,label="",tag=""},
 mores_jj_susimen_pickaxe={hasPattern=true,label="Susimen Pickaxe",tag=""},
 mores_jj_susimen_shovel={hasPattern=true,label="Susimen Shovel",tag=""},
 mores_jj_susimen_sword={hasPattern=false,label="",tag=""},
 mores_jj_uamaf_axe={hasPattern=false,label="",tag=""},
 mores_jj_uamaf_dust={hasPattern=true,label="Uamaf Dust",tag=""},
 mores_jj_uamaf_ingot={hasPattern=false,label="",tag=""},
 mores_jj_uamaf_pickaxe={hasPattern=false,label="",tag=""},
 mores_jj_uamaf_shovel={hasPattern=false,label="",tag=""},
 mores_jj_uamaf_sword={hasPattern=true,label="Uamaf Sword",tag=""},
 mores_jj_uokuwixasi_axe={hasPattern=false,label="",tag=""},
 mores_jj_uokuwixasi_dust={hasPattern=true,label="Uokuwixasi Dust",tag=""},
 mores_jj_uokuwixasi_ingot={hasPattern=false,label="",tag=""},
 mores_jj_uokuwixasi_pickaxe={hasPattern=false,label="",tag=""},
 mores_jj_uokuwixasi_shovel={hasPattern=false,label="",tag=""},
 mores_jj_uokuwixasi_sword={hasPattern=true,label="Uokuwixasi Sword",tag=""},
 mores_jj_vodricite_axe={hasPattern=false,label="",tag=""},
 mores_jj_vodricite_dust={hasPattern=true,label="Vodricite Dust",tag=""},
 mores_jj_vodricite_ingot={hasPattern=false,label="",tag=""},
 mores_jj_vodricite_pickaxe={hasPattern=false,label="",tag=""},
 mores_jj_vodricite_shovel={hasPattern=false,label="",tag=""},
 mores_jj_vodricite_sword={hasPattern=false,label="",tag=""},
 mores_jj_vukanite_axe={hasPattern=false,label="",tag=""},
 mores_jj_vukanite_dust={hasPattern=true,label="Vukanite Dust",tag=""},
 mores_jj_vukanite_ingot={hasPattern=false,label="",tag=""},
 mores_jj_vukanite_pickaxe={hasPattern=false,label="",tag=""},
 mores_jj_vukanite_shovel={hasPattern=false,label="",tag=""},
 mores_jj_vukanite_sword={hasPattern=false,label="",tag=""},
 mores_jj_zanine_axe={hasPattern=false,label="",tag=""},
 mores_jj_zanine_dust={hasPattern=true,label="Zanine Dust",tag=""},
 mores_jj_zanine_ingot={hasPattern=false,label="",tag=""},
 mores_jj_zanine_pickaxe={hasPattern=false,label="",tag=""},
 mores_jj_zanine_shovel={hasPattern=false,label="",tag=""},
 mores_jj_zanine_sword={hasPattern=false,label="",tag=""},
 mores_jj_zawium_axe={hasPattern=false,label="",tag=""},
 mores_jj_zawium_dust={hasPattern=true,label="Zawium Dust",tag=""},
 mores_jj_zawium_ingot={hasPattern=false,label="",tag=""},
 mores_jj_zawium_pickaxe={hasPattern=false,label="",tag=""},
 mores_jj_zawium_shovel={hasPattern=false,label="",tag=""},
 mores_jj_zawium_sword={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_airblast_b_1={hasPattern=false,label="",tag="({Type= dragonsfury, Attributes= {}})"},
 rafradek_tf2_weapons_jj_ammo_belt={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_ammo_box_jj_1={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_ammo_fire={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_ammo_furnace={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_ammo_jj_1={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_ammo_jj_11={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_ammo_jj_13={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_ammo_jj_14={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_ammo_jj_4={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_ammo_jj_6={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_ammo_jj_7={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_ammo_jj_8={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_ammo_medigun={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_ammo_minigun={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_ammo_pistol={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_ammo_smg={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_ammo_syringe={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_australium_block={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_australium_ore={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_backpack={hasPattern=false,label="",tag="({Type= battalionbackup, Attributes= {}})"},
 rafradek_tf2_weapons_jj_backpack_b_1={hasPattern=false,label="",tag="({Type= buffbanner, Attributes= {}})"},
 rafradek_tf2_weapons_jj_backpack_b_2={hasPattern=false,label="",tag="({Type= concheror, Attributes= {}})"},
 rafradek_tf2_weapons_jj_backpackgeneric_b_2={hasPattern=false,label="",tag="({Type= dangershield, Attributes= {}})"},
 rafradek_tf2_weapons_jj_backpackgeneric_b_3={hasPattern=false,label="",tag="({Type= razorback, Attributes= {}})"},
 rafradek_tf2_weapons_jj_bonk={hasPattern=false,label="",tag="({Type= bonk, Attributes= {}})"},
 rafradek_tf2_weapons_jj_bonk_b_1={hasPattern=false,label="",tag="({Type= critcola, Attributes= {}})"},
 rafradek_tf2_weapons_jj_boss_spawner={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_boss_spawner_jj_1={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_boss_spawner_jj_2={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_building_box_jj_18={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_building_box_jj_19={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_building_box_jj_20={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_building_box_jj_21={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_building_box_jj_22={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_building_box_jj_23={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_bullet={hasPattern=false,label="",tag="({Type= ambassador, Attributes= {}})"},
 rafradek_tf2_weapons_jj_bullet_b_1={hasPattern=false,label="",tag="({Type= forcenature, Attributes= {}})"},
 rafradek_tf2_weapons_jj_bullet_b_18={hasPattern=false,label="",tag="({Type= smg, Attributes= {}})"},
 rafradek_tf2_weapons_jj_bullet_b_19={hasPattern=false,label="",tag="({Type= widowmaker, Attributes= {}})"},
 rafradek_tf2_weapons_jj_bullet_b_2={hasPattern=false,label="",tag="({Type= panicattack, Attributes= {}})"},
 rafradek_tf2_weapons_jj_bullet_b_3={hasPattern=false,label="",tag="({Type= pistol, Attributes= {}})"},
 rafradek_tf2_weapons_jj_bullet_b_4={hasPattern=false,label="",tag="({Type= revolver, Attributes= {}})"},
 rafradek_tf2_weapons_jj_bullet_b_5={hasPattern=false,label="",tag="({Type= scattergun, Attributes= {}})"},
 rafradek_tf2_weapons_jj_bullet_b_6={hasPattern=false,label="",tag="({Type= shortstop, Attributes= {}})"},
 rafradek_tf2_weapons_jj_bullet_b_7={hasPattern=false,label="",tag="({Type= shotgun, Attributes= {}})"},
 rafradek_tf2_weapons_jj_chocolate={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_cleaver={hasPattern=false,label="",tag="({Type= cleaver, Attributes= {}})"},
 rafradek_tf2_weapons_jj_cloak={hasPattern=false,label="",tag="({Type= cloak, Attributes= {}})"},
 rafradek_tf2_weapons_jj_cloak_b_1={hasPattern=false,label="",tag="({Type= deadringer, Attributes= {}})"},
 rafradek_tf2_weapons_jj_copper_ore={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_cosmetic={hasPattern=false,label="",tag="({Type= allfather, Attributes= {}})"},
 rafradek_tf2_weapons_jj_cosmetic_b_1={hasPattern=false,label="",tag="({Type= billhat, Attributes= {}})"},
 rafradek_tf2_weapons_jj_cosmetic_b_15={hasPattern=false,label="",tag="({Type= texashat, Attributes= {}})"},
 rafradek_tf2_weapons_jj_cosmetic_b_2={hasPattern=false,label="",tag="({Type= bombinomicon, Attributes= {}})"},
 rafradek_tf2_weapons_jj_cosmetic_b_3={hasPattern=false,label="",tag="({Type= head_prize, Attributes= {}})"},
 rafradek_tf2_weapons_jj_cosmetic_b_4={hasPattern=false,label="",tag="({Type= merasmushat, Attributes= {}})"},
 rafradek_tf2_weapons_jj_cosmetic_b_5={hasPattern=false,label="",tag="({Type= monoculus, Attributes= {}})"},
 rafradek_tf2_weapons_jj_cosmetic_b_6={hasPattern=false,label="",tag="({Type= teamcaptain, Attributes= {}})"},
 rafradek_tf2_weapons_jj_crate={hasPattern=false,label="",tag="({Type= crate1, Attributes= {}})"},
 rafradek_tf2_weapons_jj_crate_b_1={hasPattern=false,label="",tag="({Type= crate2, Attributes= {}})"},
 rafradek_tf2_weapons_jj_crate_b_16={hasPattern=false,label="",tag="({Type= crate8, Attributes= {}})"},
 rafradek_tf2_weapons_jj_crate_b_17={hasPattern=false,label="",tag="({Type= crate9, Attributes= {}})"},
 rafradek_tf2_weapons_jj_crate_b_2={hasPattern=false,label="",tag="({Type= crate3, Attributes= {}})"},
 rafradek_tf2_weapons_jj_crate_b_3={hasPattern=false,label="",tag="({Type= crate4, Attributes= {}})"},
 rafradek_tf2_weapons_jj_crate_b_4={hasPattern=false,label="",tag="({Type= crate5, Attributes= {}})"},
 rafradek_tf2_weapons_jj_crate_b_5={hasPattern=false,label="",tag="({Type= crate6, Attributes= {}})"},
 rafradek_tf2_weapons_jj_crate_b_6={hasPattern=false,label="",tag="({Type= crate7, Attributes= {}})"},
 rafradek_tf2_weapons_jj_disguise_kit={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_door_controller={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_door_controller_jj_1={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_door_controller_jj_2={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_door_controller_jj_3={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_eventmaker={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_eventmaker_jj_1={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_eventmaker_jj_2={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_eventmaker_jj_3={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_eventmaker_jj_4={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_flamethrower={hasPattern=false,label="",tag="({Type= flamethrower, Attributes= {}})"},
 rafradek_tf2_weapons_jj_flamethrower_b_1={hasPattern=false,label="",tag="({Type= phlog, Attributes= {}})"},
 rafradek_tf2_weapons_jj_gunboats={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_horn={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_huntsman_b_1={hasPattern=false,label="",tag="({Type= huntsman, Attributes= {}})"},
 rafradek_tf2_weapons_jj_itemtf2={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_itemtf2_jj_1={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_itemtf2_jj_11={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_itemtf2_jj_2={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_itemtf2_jj_3={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_itemtf2_jj_4={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_itemtf2_jj_5={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_itemtf2_jj_6={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_itemtf2_jj_7={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_jar={hasPattern=false,label="",tag="({Type= jarate, Attributes= {}})"},
 rafradek_tf2_weapons_jj_jar_b_1={hasPattern=false,label="",tag="({Type= madmilk, Attributes= {}})"},
 rafradek_tf2_weapons_jj_jetpack_b_1={hasPattern=false,label="",tag="({Type= thermalthruster, Attributes= {}})"},
 rafradek_tf2_weapons_jj_jetpacktrigger_b_1={hasPattern=false,label="",tag="({Type= trigger, Attributes= {}})"},
 rafradek_tf2_weapons_jj_killstreakfabricator={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_1024={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_1026={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_1030={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_1036={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_1040={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_1048={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_1058={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_12={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_16={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_2={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_24={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_34={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_512={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_514={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_518={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_524={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_528={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_536={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_546={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakfabricator_jj_6={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakkit={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakkit_jj_1024={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakkit_jj_1026={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakkit_jj_1030={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakkit_jj_1036={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakkit_jj_1040={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakkit_jj_1048={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakkit_jj_1058={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakkit_jj_12={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakkit_jj_16={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakkit_jj_2={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakkit_jj_24={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakkit_jj_34={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakkit_jj_512={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakkit_jj_514={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakkit_jj_518={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakkit_jj_524={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakkit_jj_528={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakkit_jj_536={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakkit_jj_546={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_killstreakkit_jj_6={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_knife={hasPattern=false,label="",tag="({Type= butterflyknife, Attributes= {}})"},
 rafradek_tf2_weapons_jj_knife_b_3={hasPattern=false,label="",tag="({Type= eternalreward, Attributes= {}})"},
 rafradek_tf2_weapons_jj_lead_ore={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_mantreads={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_medigun={hasPattern=false,label="",tag="({Type= kritzkrieg, Attributes= {}})"},
 rafradek_tf2_weapons_jj_medigun_b_1={hasPattern=false,label="",tag="({Type= medigun, Attributes= {}})"},
 rafradek_tf2_weapons_jj_melee={hasPattern=false,label="",tag="({Type= axtinguisher, Attributes= {}})"},
 rafradek_tf2_weapons_jj_melee_b_1={hasPattern=false,label="",tag="({Type= bottle, Attributes= {}})"},
 rafradek_tf2_weapons_jj_melee_b_10={hasPattern=false,label="",tag="({Type= marketgarden, Attributes= {}})"},
 rafradek_tf2_weapons_jj_melee_b_11={hasPattern=false,label="",tag="({Type= sandman, Attributes= {}})"},
 rafradek_tf2_weapons_jj_melee_b_12={hasPattern=false,label="",tag="({Type= ubersaw, Attributes= {}})"},
 rafradek_tf2_weapons_jj_melee_b_2={hasPattern=false,label="",tag="({Type= bushwacka, Attributes= {}})"},
 rafradek_tf2_weapons_jj_melee_b_3={hasPattern=false,label="",tag="({Type= disciplinary, Attributes= {}})"},
 rafradek_tf2_weapons_jj_melee_b_4={hasPattern=false,label="",tag="({Type= eyelander, Attributes= {}})"},
 rafradek_tf2_weapons_jj_melee_b_5={hasPattern=false,label="",tag="({Type= fistofsteel, Attributes= {}})"},
 rafradek_tf2_weapons_jj_melee_b_6={hasPattern=false,label="",tag="({Type= fryingpan, Attributes= {}})"},
 rafradek_tf2_weapons_jj_melee_b_7={hasPattern=false,label="",tag="({Type= gru, Attributes= {}})"},
 rafradek_tf2_weapons_jj_melee_b_8={hasPattern=false,label="",tag="({Type= headtaker, Attributes= {}})"},
 rafradek_tf2_weapons_jj_melee_b_9={hasPattern=false,label="",tag="({Type= kgb, Attributes= {}})"},
 rafradek_tf2_weapons_jj_minigun={hasPattern=false,label="",tag="({Type= heater, Attributes= {}})"},
 rafradek_tf2_weapons_jj_minigun_b_1={hasPattern=false,label="",tag="({Type= minigun, Attributes= {}})"},
 rafradek_tf2_weapons_jj_minigun_b_2={hasPattern=false,label="",tag="({Type= tomislav, Attributes= {}})"},
 rafradek_tf2_weapons_jj_overhead_door={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_parachute={hasPattern=false,label="",tag="({Type= basejumper, Attributes= {}})"},
 rafradek_tf2_weapons_jj_pda_b_1={hasPattern=false,label="",tag="({Type= pda, Attributes= {}})"},
 rafradek_tf2_weapons_jj_placer={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_1={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_10={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_11={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_12={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_13={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_14={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_15={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_16={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_17={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_2={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_26={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_27={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_28={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_29={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_3={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_30={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_36={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_37={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_38={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_39={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_4={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_40={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_41={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_42={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_43={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_44={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_5={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_6={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_7={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_8={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_placer_jj_9={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_projectile={hasPattern=false,label="",tag="({Type= airstrike, Attributes= {}})"},
 rafradek_tf2_weapons_jj_projectile_b_1={hasPattern=true,label="",tag="({Type= crossbow, Attributes= {}})"},
 rafradek_tf2_weapons_jj_projectile_b_2={hasPattern=true,label="",tag="({Type= detonator, Attributes= {}})"},
 rafradek_tf2_weapons_jj_projectile_b_22={hasPattern=true,label="",tag="({Type= rocketlauncher, Attributes= {}})"},
 rafradek_tf2_weapons_jj_projectile_b_23={hasPattern=true,label="",tag="({Type= syringegun, Attributes= {}})"},
 rafradek_tf2_weapons_jj_projectile_b_3={hasPattern=true,label="",tag="({Type= directhit, Attributes= {}})"},
 rafradek_tf2_weapons_jj_projectile_b_4={hasPattern=true,label="",tag="({Type= flaregun, Attributes= {}})"},
 rafradek_tf2_weapons_jj_projectile_b_5={hasPattern=true,label="",tag="({Type= grenadelauncher, Attributes= {}})"},
 rafradek_tf2_weapons_jj_projectile_b_6={hasPattern=true,label="",tag="({Type= loosecannon, Attributes= {}})"},
 rafradek_tf2_weapons_jj_projectile_b_7={hasPattern=true,label="",tag="({Type= rescueranger, Attributes= {}})"},
 rafradek_tf2_weapons_jj_projectile_b_8={hasPattern=true,label="",tag="({Type= righterousbison, Attributes= {}})"},
 rafradek_tf2_weapons_jj_projectile_b_9={hasPattern=true,label="",tag="({Type= rocketjumper, Attributes= {}})"},
 rafradek_tf2_weapons_jj_robotpart={hasPattern=true,label="",tag=""},
 rafradek_tf2_weapons_jj_robotpart_jj_1={hasPattern=true,label="",tag=""},
 rafradek_tf2_weapons_jj_robotpart_jj_2={hasPattern=true,label="",tag=""},
 rafradek_tf2_weapons_jj_robotpart_jj_3={hasPattern=true,label="",tag=""},
 rafradek_tf2_weapons_jj_robotpart_jj_4={hasPattern=true,label="",tag=""},
 rafradek_tf2_weapons_jj_robotpart_jj_5={hasPattern=true,label="",tag=""},
 rafradek_tf2_weapons_jj_robotpart_jj_6={hasPattern=true,label="",tag=""},
 rafradek_tf2_weapons_jj_sandvich={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_sapper={hasPattern=true,label="",tag="({Type= sapper, Attributes= {}})"},
 rafradek_tf2_weapons_jj_scout_shoes={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_shield={hasPattern=true,label="",tag="({Type= chargintarge, Attributes= {}})"},
 rafradek_tf2_weapons_jj_sniperrifle={hasPattern=true,label="",tag="({Type= machina, Attributes= {}})"},
 rafradek_tf2_weapons_jj_sniperrifle_b_1={hasPattern=true,label="",tag="({Type= sniperrifle, Attributes= {}})"},
 rafradek_tf2_weapons_jj_sniperrifle_b_5={hasPattern=true,label="",tag="({Type= sydneysleeper, Attributes= {}})"},
 rafradek_tf2_weapons_jj_statue={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_stickybomb={hasPattern=true,label="",tag="({Type= scottishresistance, Attributes= {}})"},
 rafradek_tf2_weapons_jj_stickybomb_b_1={hasPattern=true,label="",tag="({Type= stickybomblauncher, Attributes= {}})"},
 rafradek_tf2_weapons_jj_stickybomb_b_2={hasPattern=true,label="",tag="({Type= stickyjumper, Attributes= {}})"},
 rafradek_tf2_weapons_jj_strangifier={hasPattern=true,label="",tag=""},
 rafradek_tf2_weapons_jj_target={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_tf2workbench={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_token={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_token_jj_1={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_token_jj_2={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_token_jj_3={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_token_jj_4={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_token_jj_5={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_token_jj_6={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_token_jj_7={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_token_jj_8={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_upgrade_station_jj_8={hasPattern=false,label="",tag=""},
 rafradek_tf2_weapons_jj_wrangler={hasPattern=false,label="",tag="({Type= wrangler, Attributes= {}})"},
 rafradek_tf2_weapons_jj_wrench={hasPattern=false,label="",tag="({Type= eurekaeffect, Attributes= {}})"},
 rafradek_tf2_weapons_jj_wrench_b_1={hasPattern=false,label="",tag="({Type= gunsligner, Attributes= {}})"},
 rafradek_tf2_weapons_jj_wrench_b_2={hasPattern=false,label="",tag="({Type= startwrench, Attributes= {}})"},
 rafradek_tf2_weapons_jj_wrench_b_7={hasPattern=false,label="",tag="({Type= wrench, Attributes= {}})"}
 }