return {
 gravestone_qq_extended_jj_bone_boots={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_bone_chestplate={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_bone_helmet={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_bone_leggings={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_bone_shovel={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_bone_shovel_diamond={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_bone_shovel_golden={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_bone_shovel_iron={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_cemetery_key={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_cemetery_key_jj_1={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_frozen_lava={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_bat_wing={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_bone_axe={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_bone_axe_diamond={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_bone_axe_golden={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_bone_axe_iron={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_bone_hoe={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_bone_hoe_diamond={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_bone_hoe_golden={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_bone_hoe_iron={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_bone_pickaxe={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_bone_pickaxe_diamond={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_bone_pickaxe_golden={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_bone_pickaxe_iron={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_bone_shield={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_bone_sword={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_bone_sword_diamond={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_bone_sword_golden={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_bone_sword_iron={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_catacombs_portal={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_diving_boots={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_diving_chestplate={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_diving_helmet={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_diving_leggings={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_enchanted_skull={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 10 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_1={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 14 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_10={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 45 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_11={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 46 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_12={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 47 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_13={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 50 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_14={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 51 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_15={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 52 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_16={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 54 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_17={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 58 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_18={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 6 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_19={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 60 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_2={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 15 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_20={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 67 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_21={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 69 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_22={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 70 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_23={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 71 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_24={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 72 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_25={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 73 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_26={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 74 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_27={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 76 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_28={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 77 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_29={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 78 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_3={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 25 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_30={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 80 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_31={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 81 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_32={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 83 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_33={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 84 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_34={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 85 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_35={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 87 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_36={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 88 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_37={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 2 as short, id: 19 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_38={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 2 as short, id: 20 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_39={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 2 as short, id: 43 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_4={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 26 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_40={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 2 as short, id: 44 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_41={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 2 as short, id: 49 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_42={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 2 as short, id: 57 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_43={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 2 as short, id: 63 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_44={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 2 as short, id: 65 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_45={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 2 as short, id: 75 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_46={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 2 as short, id: 9 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_47={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 11 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_48={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 21 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_49={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 22 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_5={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 31 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_50={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 24 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_51={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 28 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_52={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 34 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_53={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 35 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_54={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 36 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_55={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 39 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_56={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 42 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_57={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 5 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_58={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 53 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_59={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 56 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_6={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 33 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_60={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 61 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_61={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 62 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_62={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 66 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_63={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 68 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_64={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 7 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_65={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 79 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_66={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 8 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_67={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 86 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_68={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 4 as short, id: 0 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_69={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 4 as short, id: 1 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_7={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 37 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_70={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 4 as short, id: 12 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_71={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 4 as short, id: 2 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_72={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 4 as short, id: 27 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_73={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 4 as short, id: 29 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_74={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 4 as short, id: 3 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_75={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 4 as short, id: 30 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_76={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 4 as short, id: 4 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_77={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 4 as short, id: 59 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_78={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 4 as short, id: 82 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_79={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 5 as short, id: 13 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_8={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 38 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_80={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 5 as short, id: 16 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_81={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 5 as short, id: 17 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_82={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 5 as short, id: 18 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_83={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 5 as short, id: 23 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_84={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 5 as short, id: 32 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_85={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 5 as short, id: 41 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_86={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 5 as short, id: 48 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_87={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 5 as short, id: 55 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_88={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 5 as short, id: 64 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_b_9={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 40 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 10 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_1={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 14 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_10={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 45 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_11={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 46 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_12={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 47 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_13={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 50 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_14={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 51 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_15={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 52 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_16={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 54 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_17={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 58 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_18={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 6 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_19={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 60 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_2={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 15 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_20={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 67 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_21={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 69 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_22={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 70 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_23={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 71 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_24={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 72 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_25={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 73 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_26={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 74 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_27={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 76 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_28={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 77 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_29={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 78 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_3={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 25 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_30={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 80 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_31={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 81 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_32={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 83 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_33={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 84 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_34={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 85 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_35={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 87 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_36={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 88 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_37={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 2 as short, id: 19 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_38={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 2 as short, id: 20 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_39={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 2 as short, id: 43 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_4={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 26 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_40={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 2 as short, id: 44 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_41={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 2 as short, id: 49 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_42={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 2 as short, id: 57 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_43={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 2 as short, id: 63 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_44={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 2 as short, id: 65 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_45={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 2 as short, id: 75 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_46={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 2 as short, id: 9 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_47={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 11 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_48={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 21 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_49={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 22 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_5={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 31 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_50={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 24 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_51={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 28 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_52={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 34 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_53={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 35 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_54={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 36 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_55={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 39 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_56={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 42 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_57={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 5 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_58={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 53 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_59={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 56 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_6={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 33 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_60={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 61 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_61={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 62 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_62={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 66 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_63={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 68 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_64={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 7 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_65={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 79 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_66={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 8 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_67={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 3 as short, id: 86 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_68={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 4 as short, id: 0 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_69={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 4 as short, id: 1 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_7={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 37 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_70={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 4 as short, id: 12 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_71={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 4 as short, id: 2 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_72={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 4 as short, id: 27 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_73={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 4 as short, id: 29 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_74={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 4 as short, id: 3 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_75={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 4 as short, id: 30 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_76={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 4 as short, id: 4 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_77={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 4 as short, id: 59 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_78={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 4 as short, id: 82 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_79={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 5 as short, id: 13 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_8={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 38 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_80={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 5 as short, id: 16 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_81={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 5 as short, id: 17 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_82={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 5 as short, id: 18 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_83={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 5 as short, id: 23 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_84={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 5 as short, id: 32 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_85={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 5 as short, id: 41 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_86={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 5 as short, id: 48 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_87={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 5 as short, id: 55 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_88={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 5 as short, id: 64 as short}]})"},
 gravestone_qq_extended_jj_gs_enchanted_skull_jj_1_b_9={hasPattern=true,label="",tag="({StoredEnchantments: [{lvl: 1 as short, id: 40 as short}]})"},
 gravestone_qq_extended_jj_gs_ender_skull={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_frozen_mirror={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_imp_skull={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_mummy_boots={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_mummy_chestplate={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_mummy_helmet={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_mummy_leggings={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_ooze={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_piece_of_diving_suit={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_piece_of_mummy_cloth={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_raven_claws={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_raven_feather={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_slime_chunk={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_swamp_thing_boots={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_swamp_thing_chestplate={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_swamp_thing_helmet={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_swamp_thing_leggings={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_toxic_slime={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_undertaker_backpack={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_undertaker_backpack_woven={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_withered_glass={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gs_withered_glass_pane={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsaltar={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsboneblock={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsboneblock_jj_1={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsboneblock_jj_2={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsboneblock_jj_3={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsboneslab={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsbonestairs={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gscandle={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gschisel={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gscorpse={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gscorpse_b_1={hasPattern=true,label="",tag="({Owner: {Id: 1f61746c-849d-3494-a3b3-46c6f1639dca, Name: bufu16}})"},
 gravestone_qq_extended_jj_gscorpse_jj_1={hasPattern=true,label="",tag="({Profession: 0, CareerLevel: 1, Career: 1})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_1={hasPattern=true,label="",tag="({Profession: 0, CareerLevel: 1, Career: 2})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_10={hasPattern=true,label="",tag="({Profession: 13, CareerLevel: 1, Career: 0})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_11={hasPattern=true,label="",tag="({Profession: 2, CareerLevel: 1, Career: 0})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_12={hasPattern=true,label="",tag="({Profession: 2, CareerLevel: 1, Career: 1})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_13={hasPattern=true,label="",tag="({Profession: 3, CareerLevel: 1, Career: 1})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_14={hasPattern=true,label="",tag="({Profession: 3, CareerLevel: 1, Career: 2})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_15={hasPattern=true,label="",tag="({Profession: 3, CareerLevel: 1, Career: 3})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_16={hasPattern=true,label="",tag="({Profession: 4, CareerLevel: 1, Career: 0})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_17={hasPattern=true,label="",tag="({Profession: 4, CareerLevel: 1, Career: 1})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_18={hasPattern=true,label="",tag="({Profession: 4, CareerLevel: 1, Career: 2})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_19={hasPattern=true,label="",tag="({Profession: 5, CareerLevel: 1, Career: 0})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_2={hasPattern=true,label="",tag="({Profession: 0, CareerLevel: 1, Career: 3})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_20={hasPattern=true,label="",tag="({Profession: 5, CareerLevel: 1, Career: 1})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_21={hasPattern=true,label="",tag="({Profession: 6, CareerLevel: 1, Career: 0})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_22={hasPattern=true,label="",tag="({Profession: 7, CareerLevel: 1, Career: 0})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_23={hasPattern=true,label="",tag="({Profession: 8, CareerLevel: 1, Career: 0})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_24={hasPattern=true,label="",tag="({Profession: 9, CareerLevel: 1, Career: 0})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_3={hasPattern=true,label="",tag="({Profession: 0, CareerLevel: 1, Career: 4})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_4={hasPattern=true,label="",tag="({Profession: 1, CareerLevel: 1, Career: 0})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_5={hasPattern=true,label="",tag="({Profession: 1, CareerLevel: 1, Career: 1})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_6={hasPattern=true,label="",tag="({Profession: 1, CareerLevel: 1, Career: 2})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_7={hasPattern=true,label="",tag="({Profession: 10, CareerLevel: 1, Career: 0})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_8={hasPattern=true,label="",tag="({Profession: 11, CareerLevel: 1, Career: 1})"},
 gravestone_qq_extended_jj_gscorpse_jj_1_b_9={hasPattern=true,label="",tag="({Profession: 12, CareerLevel: 1, Career: 0})"},
 gravestone_qq_extended_jj_gscorpse_jj_2={hasPattern=true,label="",tag="({MobType: 0 as byte, Collar: 14 as byte})"},
 gravestone_qq_extended_jj_gscorpse_jj_2_b_1={hasPattern=true,label="",tag="({MobType: 1 as byte, Collar: 14 as byte})"},
 gravestone_qq_extended_jj_gscorpse_jj_2_b_2={hasPattern=true,label="",tag="({MobType: 2 as byte, Collar: 14 as byte})"},
 gravestone_qq_extended_jj_gscorpse_jj_2_b_3={hasPattern=true,label="",tag="({MobType: 4 as byte, Collar: 14 as byte})"},
 gravestone_qq_extended_jj_gscorpse_jj_3={hasPattern=true,label="",tag="({CatType: 0 as byte, MobType: 0 as byte})"},
 gravestone_qq_extended_jj_gscorpse_jj_3_b_1={hasPattern=true,label="",tag="({CatType: 0 as byte, MobType: 1 as byte})"},
 gravestone_qq_extended_jj_gscorpse_jj_3_b_10={hasPattern=true,label="",tag="({CatType: 3 as byte, MobType: 0 as byte})"},
 gravestone_qq_extended_jj_gscorpse_jj_3_b_11={hasPattern=true,label="",tag="({CatType: 3 as byte, MobType: 1 as byte})"},
 gravestone_qq_extended_jj_gscorpse_jj_3_b_12={hasPattern=true,label="",tag="({CatType: 3 as byte, MobType: 4 as byte})"},
 gravestone_qq_extended_jj_gscorpse_jj_3_b_2={hasPattern=true,label="",tag="({CatType: 0 as byte, MobType: 2 as byte})"},
 gravestone_qq_extended_jj_gscorpse_jj_3_b_3={hasPattern=true,label="",tag="({CatType: 0 as byte, MobType: 4 as byte})"},
 gravestone_qq_extended_jj_gscorpse_jj_3_b_4={hasPattern=true,label="",tag="({CatType: 1 as byte, MobType: 0 as byte})"},
 gravestone_qq_extended_jj_gscorpse_jj_3_b_5={hasPattern=true,label="",tag="({CatType: 1 as byte, MobType: 1 as byte})"},
 gravestone_qq_extended_jj_gscorpse_jj_3_b_6={hasPattern=true,label="",tag="({CatType: 1 as byte, MobType: 4 as byte})"},
 gravestone_qq_extended_jj_gscorpse_jj_3_b_7={hasPattern=true,label="",tag="({CatType: 2 as byte, MobType: 0 as byte})"},
 gravestone_qq_extended_jj_gscorpse_jj_3_b_8={hasPattern=true,label="",tag="({CatType: 2 as byte, MobType: 1 as byte})"},
 gravestone_qq_extended_jj_gscorpse_jj_3_b_9={hasPattern=true,label="",tag="({CatType: 2 as byte, MobType: 4 as byte})"},
 gravestone_qq_extended_jj_gscorpse_jj_4={hasPattern=true,label="",tag="({Variant: 0, Movement Speed: 0.3, HorseType: 0, Max Health: 25.0, Jump Strength: 0.7})"},
 gravestone_qq_extended_jj_gscorpse_jj_4_b_1={hasPattern=true,label="",tag="({Variant: 0, Movement Speed: 0.3, HorseType: 1, Max Health: 25.0, Jump Strength: 0.7})"},
 gravestone_qq_extended_jj_gscorpse_jj_4_b_2={hasPattern=true,label="",tag="({Variant: 0, Movement Speed: 0.3, HorseType: 2, Max Health: 25.0, Jump Strength: 0.7})"},
 gravestone_qq_extended_jj_gscorpse_jj_4_b_3={hasPattern=true,label="",tag="({Variant: 0, Movement Speed: 0.3, HorseType: 3, Max Health: 25.0, Jump Strength: 0.7})"},
 gravestone_qq_extended_jj_gscorpse_jj_4_b_4={hasPattern=true,label="",tag="({Variant: 0, Movement Speed: 0.3, HorseType: 4, Max Health: 25.0, Jump Strength: 0.7})"},
 gravestone_qq_extended_jj_gscorpse_jj_5={hasPattern=true,label="",tag="({MobType: 1 as byte})"},
 gravestone_qq_extended_jj_gscorpse_jj_5_b_1={hasPattern=true,label="",tag="({MobType: 4 as byte})"},
 gravestone_qq_extended_jj_gscorpse_jj_5_b_2={hasPattern=true,label="",tag="({MobType: 7 as byte})"},
 gravestone_qq_extended_jj_gscorpse_jj_6={hasPattern=true,label="",tag="({Profession: 0, MobType: 1 as byte, Career: 1})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_1={hasPattern=true,label="",tag="({Profession: 0, MobType: 1 as byte, Career: 2})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_10={hasPattern=true,label="",tag="({Profession: 13, MobType: 1 as byte, Career: 0})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_11={hasPattern=true,label="",tag="({Profession: 2, MobType: 1 as byte, Career: 0})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_12={hasPattern=true,label="",tag="({Profession: 2, MobType: 1 as byte, Career: 1})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_13={hasPattern=true,label="",tag="({Profession: 3, MobType: 1 as byte, Career: 0})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_14={hasPattern=true,label="",tag="({Profession: 3, MobType: 1 as byte, Career: 1})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_15={hasPattern=true,label="",tag="({Profession: 3, MobType: 1 as byte, Career: 2})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_16={hasPattern=true,label="",tag="({Profession: 3, MobType: 1 as byte, Career: 3})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_17={hasPattern=true,label="",tag="({Profession: 4, MobType: 1 as byte, Career: 0})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_18={hasPattern=true,label="",tag="({Profession: 4, MobType: 1 as byte, Career: 1})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_19={hasPattern=true,label="",tag="({Profession: 4, MobType: 1 as byte, Career: 2})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_2={hasPattern=true,label="",tag="({Profession: 0, MobType: 1 as byte, Career: 3})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_20={hasPattern=true,label="",tag="({Profession: 5, MobType: 1 as byte, Career: 0})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_21={hasPattern=true,label="",tag="({Profession: 5, MobType: 1 as byte, Career: 1})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_22={hasPattern=true,label="",tag="({Profession: 6, MobType: 1 as byte, Career: 1})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_23={hasPattern=true,label="",tag="({Profession: 7, MobType: 1 as byte, Career: 0})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_24={hasPattern=true,label="",tag="({Profession: 8, MobType: 1 as byte, Career: 0})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_25={hasPattern=true,label="",tag="({Profession: 9, MobType: 1 as byte, Career: 0})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_3={hasPattern=true,label="",tag="({Profession: 0, MobType: 1 as byte, Career: 4})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_4={hasPattern=true,label="",tag="({Profession: 1, MobType: 1 as byte, Career: 0})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_5={hasPattern=true,label="",tag="({Profession: 1, MobType: 1 as byte, Career: 1})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_6={hasPattern=true,label="",tag="({Profession: 1, MobType: 1 as byte, Career: 2})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_7={hasPattern=true,label="",tag="({Profession: 10, MobType: 1 as byte, Career: 0})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_8={hasPattern=true,label="",tag="({Profession: 11, MobType: 1 as byte, Career: 1})"},
 gravestone_qq_extended_jj_gscorpse_jj_6_b_9={hasPattern=true,label="",tag="({Profession: 12, MobType: 1 as byte, Career: 0})"},
 gravestone_qq_extended_jj_gscorpse_jj_7={hasPattern=true,label="",tag="({MobType: 2 as byte})"},
 gravestone_qq_extended_jj_gscorpse_jj_7_b_1={hasPattern=true,label="",tag="({MobType: 5 as byte})"},
 gravestone_qq_extended_jj_gscorpse_jj_7_b_2={hasPattern=true,label="",tag="({MobType: 6 as byte})"},
 gravestone_qq_extended_jj_gscorpse_jj_8={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsexecution={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsexecution_jj_1={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsexecution_jj_2={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsexecution_jj_3={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gshauntedchest={hasPattern=true,label="",tag="({ChestType: 0})"},
 gravestone_qq_extended_jj_gshauntedchest_b_1={hasPattern=true,label="",tag="({ChestType: 1})"},
 gravestone_qq_extended_jj_gsmemorial={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_1={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_10={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_100={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_101={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_102={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_103={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_104={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_105={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_106={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_107={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_108={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_109={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_11={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_110={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_111={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_112={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_113={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_114={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_115={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_116={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_117={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_118={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_119={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_12={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_120={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_121={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_122={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_123={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_124={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_125={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_126={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_127={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_128={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_129={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_13={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_130={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_131={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_132={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_133={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_134={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_135={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_136={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_137={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_138={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_139={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_14={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_140={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_141={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_142={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_143={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_144={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_145={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_146={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_147={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_148={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_149={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_15={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_150={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_151={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_152={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_16={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_17={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_18={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_19={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_2={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_20={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_21={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_22={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_23={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_24={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_25={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_26={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_27={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_28={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_29={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_3={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_30={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_31={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_32={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_33={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_34={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_35={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_36={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_37={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_38={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_39={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_4={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_40={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_41={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_42={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_43={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_44={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_45={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_46={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_47={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_48={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_49={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_5={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_50={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_51={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_52={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_53={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_54={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_55={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_56={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_57={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_58={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_59={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_6={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_60={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_61={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_62={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_63={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_64={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_65={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_66={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_67={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_68={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_69={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_7={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_70={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_71={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_72={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_73={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_74={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_75={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_76={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_77={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_78={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_79={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_8={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_80={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_81={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_82={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_83={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_84={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_85={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_86={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_87={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_88={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_89={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_9={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_90={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_91={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_92={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_93={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_94={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_95={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_96={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_97={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_98={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsmemorial_jj_99={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gspileofbones={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gspileofbones_jj_4={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gspileofbones_jj_8={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsskullcandle={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_1={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_10={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_11={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_12={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_13={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_14={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_15={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_16={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_17={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_18={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_19={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_2={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_20={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_21={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_22={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_23={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_24={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_3={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_4={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_5={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_6={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_7={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_8={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawnegg_jj_9={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawner={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawner_jj_1={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawner_jj_2={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gsspawner_jj_3={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gstrap={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_gstrap_jj_1={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_skull_candle_wither={hasPattern=true,label="",tag=""},
 gravestone_qq_extended_jj_skull_candle_zombie={hasPattern=true,label="",tag=""}
 }