return {
 advancedrocketry_jj_advrocketmotor={hasPattern=true,label="Verbesserter Flüssigtreibstoff",tag={}},
 advancedrocketry_jj_airlock_door={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_alienleaves={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_aliensapling={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_alienwood={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_altitudecontroller={hasPattern=true,label="Flughöhensteuerung",tag={}},
 advancedrocketry_jj_arcfurnace={hasPattern=true,label="Elektrischer Hochofen",tag={}},
 advancedrocketry_jj_asteroidchip={hasPattern=true,label="Asteroiden Chip",tag={}},
 advancedrocketry_jj_astrobed={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_atmanalyser={hasPattern=true,label="Atmospherenanalysierer",tag={}},
 advancedrocketry_jj_basalt={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_basiclasergun={hasPattern=true,label="Einfache Laserpistole",tag={}},
 advancedrocketry_jj_beacon={hasPattern=true,label="Leuchtfeuer",tag={}},
 advancedrocketry_jj_beaconfinder={hasPattern=true,label="Leuchtfeuerfinder",tag={}},
 advancedrocketry_jj_biomechanger={hasPattern=true,label="Biomenmanipulator Bedinung",tag={}},
 advancedrocketry_jj_biomescanner={hasPattern=true,label="Biomenscanner",tag={}},
 advancedrocketry_jj_blackholegenerator={hasPattern=true,label="Black Hole Generator",tag={}},
 advancedrocketry_jj_blastbrick={hasPattern=true,label="Hitzebeständiger Ziegel",tag={}},
 advancedrocketry_jj_blocklens={hasPattern=true,label="Linse",tag={}},
 advancedrocketry_jj_blockpump={hasPattern=true,label="Fluid Pump",tag={}},
 advancedrocketry_jj_bucketenrichedlava={hasPattern=false,label="",tag={Fluid={Amount=1000,FluidName="enrichedlava"}}},
 advancedrocketry_jj_buckethydrogen={hasPattern=false,label="",tag={Fluid={Amount=1000,FluidName="hydrogen"}}},
 advancedrocketry_jj_bucketnitrogen={hasPattern=false,label="",tag={Fluid={Amount=1000,FluidName="nitrogen"}}},
 advancedrocketry_jj_bucketoxygen={hasPattern=false,label="",tag={Fluid={Amount=1000,FluidName="oxygen"}}},
 advancedrocketry_jj_bucketrocketfuel={hasPattern=false,label="",tag={Fluid={Amount=1000,FluidName="rocketfuel"}}},
 advancedrocketry_jj_carbonscrubbercartridge={hasPattern=true,label="Carbonsammlungskassete",tag={}},
 advancedrocketry_jj_centrifuge={hasPattern=true,label="Essentia Zentrifuge",tag={}},
 advancedrocketry_jj_charcoallog={hasPattern=true,label="Holzkohlenholzscheit",tag={}},
 advancedrocketry_jj_chemicalreactor={hasPattern=true,label="Chemischer Reaktor",tag={}},
 advancedrocketry_jj_circlelight={hasPattern=true,label="Raumstationsbeleuchtung",tag={}},
 advancedrocketry_jj_concrete={hasPattern=true,label="Asphalttile.lathe.name=Drechselbank",tag={}},
 advancedrocketry_jj_crystal={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_crystal_jj_1={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_crystal_jj_2={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_crystal_jj_3={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_crystal_jj_4={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_crystal_jj_5={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_crystallizer={hasPattern=true,label="Kristallisierer",tag={}},
 advancedrocketry_jj_cuttingmachine={hasPattern=true,label="Schneidemaschine",tag={}},
 advancedrocketry_jj_dataunit={hasPattern=true,label="Datenspeicherungseinheit",tag={}},
 advancedrocketry_jj_deployablerocketbuilder={hasPattern=true,label="Unbemannte Raketen Monteur",tag={}},
 advancedrocketry_jj_drill={hasPattern=true,label="Bohrer",tag={}},
 advancedrocketry_jj_electricmushroom={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_electrolyser={hasPattern=true,label="Elektrolyseur",tag={}},
 advancedrocketry_jj_elevatorchip={hasPattern=true,label="Raumfahrstuhl Chip",tag={}},
 advancedrocketry_jj_enrichedlavafluid={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_forcefield={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_forcefieldprojector={hasPattern=true,label="Kraftfeldgenerator",tag={}},
 advancedrocketry_jj_fuelingstation={hasPattern=true,label="Befüllungstation",tag={}},
 advancedrocketry_jj_fueltank={hasPattern=true,label="Treibstofftank",tag={}},
 advancedrocketry_jj_geode={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_gravitycontroller={hasPattern=true,label="Gravitationssteuerung",tag={}},
 advancedrocketry_jj_gravitymachine={hasPattern=true,label="Gravitationsveränderer",tag={}},
 advancedrocketry_jj_guidancecomputer={hasPattern=true,label="Raketenflugcomputer",tag={}},
 advancedrocketry_jj_hotturf={hasPattern=true,label="Oxidierter Eisensand",tag={}},
 advancedrocketry_jj_hovercraft={hasPattern=true,label="HoverCraft",tag={}},
 advancedrocketry_jj_hydrogenfluid={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_ic={hasPattern=true,label="Einfacher Schaltkreis",tag={}},
 advancedrocketry_jj_ic_jj_1={hasPattern=true,label="Verfolgungsschaltkreis",tag={}},
 advancedrocketry_jj_ic_jj_2={hasPattern=true,label="Fortgeschrittene Schaltkreis",tag={}},
 advancedrocketry_jj_ic_jj_3={hasPattern=true,label="Steuerungsschaltkreisplatte",tag={}},
 advancedrocketry_jj_ic_jj_4={hasPattern=true,label="Item IO Schaltkreisplatte",tag={}},
 advancedrocketry_jj_ic_jj_5={hasPattern=true,label="Flüssigkeiten IO Schaltkreisplatte",tag={}},
 advancedrocketry_jj_intake={hasPattern=true,label="Gas Einlass",tag={}},
 advancedrocketry_jj_iquartzcrucible={hasPattern=true,label="Quartz Crucible",tag={}},
 advancedrocketry_jj_itemcircuitplate={hasPattern=true,label="Einfache Schaltkreisplatte",tag={}},
 advancedrocketry_jj_itemcircuitplate_jj_1={hasPattern=true,label="Fortgeschrittene Schaltkreisplatte",tag={}},
 advancedrocketry_jj_itemupgrade={hasPattern=true,label="Schwebeverbesserung",tag={}},
 advancedrocketry_jj_itemupgrade_jj_1={hasPattern=true,label="Fluggeschwindigkeitssteuerung",tag={}},
 advancedrocketry_jj_itemupgrade_jj_2={hasPattern=true,label="Bionische Hose Verbesserung",tag={}},
 advancedrocketry_jj_itemupgrade_jj_3={hasPattern=true,label="Gepolsterte Landeschuhe",tag={}},
 advancedrocketry_jj_itemupgrade_jj_4={hasPattern=true,label="Nebelsichtgeräht",tag={}},
 advancedrocketry_jj_jackhammer={hasPattern=true,label="Presslufthammer",tag={}},
 advancedrocketry_jj_jetpack={hasPattern=true,label="Raketenrucksack",tag={}},
 advancedrocketry_jj_landingfloat={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_landingpad={hasPattern=true,label="Landerampe",tag={}},
 advancedrocketry_jj_lathe={hasPattern=true,label="Lathe",tag={}},
 advancedrocketry_jj_launchpad={hasPattern=true,label="Launch Pad",tag={}},
 advancedrocketry_jj_lens={hasPattern=true,label="Einfache Linse",tag={}},
 advancedrocketry_jj_lightsource={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_liquidtank={hasPattern=true,label="Drucktank",tag={}},
 advancedrocketry_jj_loader={hasPattern=true,label="Datenübertragungskabel",tag={}},
 advancedrocketry_jj_loader_jj_1={hasPattern=true,label="Satellitenkapsel",tag={}},
 advancedrocketry_jj_loader_jj_2={hasPattern=true,label="Raketen Entlader",tag={}},
 advancedrocketry_jj_loader_jj_3={hasPattern=true,label="Raketen Belader",tag={}},
 advancedrocketry_jj_loader_jj_4={hasPattern=true,label="Flüssigkeits Entlader",tag={}},
 advancedrocketry_jj_loader_jj_5={hasPattern=true,label="Flüssigkeits Belader",tag={}},
 advancedrocketry_jj_loader_jj_6={hasPattern=true,label="Guidance Computer Access Hatch",tag={}},
 advancedrocketry_jj_metal0={hasPattern=true,label="Titanaluminide Block",tag={}},
 advancedrocketry_jj_metal0_jj_1={hasPattern=true,label="Titanium Iridium Legierung Block",tag={}},
 advancedrocketry_jj_microwavereciever={hasPattern=true,label="Mikrowellenstrahlungs Fänger",tag={}},
 advancedrocketry_jj_misc={hasPattern=true,label="Nutzer Interface",tag={}},
 advancedrocketry_jj_misc_jj_1={hasPattern=true,label="Carbonziegel",tag={}},
 advancedrocketry_jj_monitoringstation={hasPattern=true,label="Raketenbeobachtungsmonitor",tag={}},
 advancedrocketry_jj_moonturf={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_moonturf_dark={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_nitrogenfluid={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_observatory={hasPattern=true,label="Observatorium",tag={}},
 advancedrocketry_jj_orescanner={hasPattern=true,label="Erzscanner",tag={}},
 advancedrocketry_jj_orientationcontroller={hasPattern=true,label="Richtungssteuerung",tag={}},
 advancedrocketry_jj_oxygencharger={hasPattern=true,label="Gasaufladeplatte",tag={}},
 advancedrocketry_jj_oxygendetection={hasPattern=true,label="Atmospherendetektor",tag={}},
 advancedrocketry_jj_oxygenfluid={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_oxygenscrubber={hasPattern=true,label="CO2 Reiniger",tag={}},
 advancedrocketry_jj_oxygenvent={hasPattern=true,label="Sauerstofflüftung",tag={}},
 advancedrocketry_jj_pipesealer={hasPattern=true,label="Rohrdichtung",tag={}},
 advancedrocketry_jj_planetanalyser={hasPattern=true,label="Planetenbeobachter",tag={}},
 advancedrocketry_jj_planetholoselector={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_planetidchip={hasPattern=true,label="Planeten Id Chip",tag={}},
 advancedrocketry_jj_planetselector={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_planks={hasPattern=true,label="Lichteichenbretter",tag={}},
 advancedrocketry_jj_platepress={hasPattern=true,label="Kleine Plattenpresse",tag={}},
 advancedrocketry_jj_precisionassemblingmachine={hasPattern=true,label="Präzisionsmonteur",tag={}},
 advancedrocketry_jj_pressuretank={hasPattern=true,label="Niedrigdrucktank",tag={}},
 advancedrocketry_jj_pressuretank_jj_1={hasPattern=true,label="Drucktank",tag={}},
 advancedrocketry_jj_pressuretank_jj_2={hasPattern=true,label="Hochdrucktank",tag={}},
 advancedrocketry_jj_pressuretank_jj_3={hasPattern=true,label="Extremer Hochdrucktank",tag={}},
 advancedrocketry_jj_productboule={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_productdust={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_productdust_jj_1={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_productfan={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_productgear={hasPattern=true,label="Titanaluminide Gear",tag={}},
 advancedrocketry_jj_productgear_jj_1={hasPattern=true,label="Titanium Iridium Legierung Gear",tag={}},
 advancedrocketry_jj_productgem={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_productingot={hasPattern=true,label="Titanaluminide Ingot",tag={}},
 advancedrocketry_jj_productingot_jj_1={hasPattern=true,label="Titanium Iridium Legierung Ingot",tag={}},
 advancedrocketry_jj_productnugget={hasPattern=true,label="Titanaluminide Nugget",tag={}},
 advancedrocketry_jj_productnugget_jj_1={hasPattern=true,label="Titanium Iridium Legierung Nugget",tag={}},
 advancedrocketry_jj_productplate={hasPattern=true,label="Titanaluminide Plate",tag={}},
 advancedrocketry_jj_productplate_jj_1={hasPattern=true,label="Titanium Iridium Legierung Plate",tag={}},
 advancedrocketry_jj_productrod={hasPattern=true,label="Titanaluminide Rod",tag={}},
 advancedrocketry_jj_productrod_jj_1={hasPattern=true,label="Titanium Iridium Legierung Rod",tag={}},
 advancedrocketry_jj_productsheet={hasPattern=true,label="Titanaluminide Sheet",tag={}},
 advancedrocketry_jj_productsheet_jj_1={hasPattern=true,label="Titanium Iridium Legierung Sheet",tag={}},
 advancedrocketry_jj_railgun={hasPattern=true,label="Schienenkanone",tag={}},
 advancedrocketry_jj_rocketbuilder={hasPattern=true,label="Raketenmonteur",tag={}},
 advancedrocketry_jj_rocketfuel={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_rocketmotor={hasPattern=true,label="Flüssigtreibstoff Triebwerk",tag={}},
 advancedrocketry_jj_rollingmachine={hasPattern=true,label="Walzenmaschine",tag={}},
 advancedrocketry_jj_satellite={hasPattern=true,label="Satellit",tag={}},
 advancedrocketry_jj_satellitebuilder={hasPattern=true,label="Satellitenkonstrukteur",tag={}},
 advancedrocketry_jj_satellitecontrolcenter={hasPattern=true,label="Satellitenterminal",tag={}},
 advancedrocketry_jj_satelliteidchip={hasPattern=true,label="Satelliten ID Chip",tag={}},
 advancedrocketry_jj_satellitepowersource={hasPattern=true,label="Einfache Solarpanelen",tag={}},
 advancedrocketry_jj_satellitepowersource_jj_1={hasPattern=true,label="Große Solarpanelen",tag={}},
 advancedrocketry_jj_satelliteprimaryfunction={hasPattern=true,label="Optischer Sensor",tag={}},
 advancedrocketry_jj_satelliteprimaryfunction_jj_1={hasPattern=true,label="Zusamensetzungs Sensor",tag={}},
 advancedrocketry_jj_satelliteprimaryfunction_jj_2={hasPattern=true,label="Massendetektor",tag={}},
 advancedrocketry_jj_satelliteprimaryfunction_jj_3={hasPattern=true,label="Mikrowellenstrahlungs Sender",tag={}},
 advancedrocketry_jj_satelliteprimaryfunction_jj_4={hasPattern=true,label="Erzkarograph",tag={}},
 advancedrocketry_jj_satelliteprimaryfunction_jj_5={hasPattern=true,label="Biomenmanipulator",tag={}},
 advancedrocketry_jj_sawblade={hasPattern=true,label="Sägeblatt",tag={}},
 advancedrocketry_jj_sawbladeiron={hasPattern=true,label="Eisensägeblatt",tag={}},
 advancedrocketry_jj_sealdetector={hasPattern=true,label="Dichtungsdetektor",tag={}},
 advancedrocketry_jj_seat={hasPattern=true,label="Seat",tag={}},
 advancedrocketry_jj_smallairlockdoor={hasPattern=true,label="Kleine Luftschleuse",tag={}},
 advancedrocketry_jj_solargenerator={hasPattern=true,label="Solar Generator",tag={}},
 advancedrocketry_jj_solarpanel={hasPattern=true,label="Solarpanele",tag={}},
 advancedrocketry_jj_spaceboots={hasPattern=true,label="Raumanzugsschuhe",tag={}},
 advancedrocketry_jj_spacechestplate={hasPattern=true,label="Raumanzugsbrustplatte",tag={}},
 advancedrocketry_jj_spaceelevatorcontroller={hasPattern=true,label="Raumfahrstuhl",tag={}},
 advancedrocketry_jj_spacehelmet={hasPattern=true,label="Raumanzugshelm",tag={}},
 advancedrocketry_jj_spacelaser={hasPattern=true,label="Weltraum Laserbohrer",tag={}},
 advancedrocketry_jj_spaceleggings={hasPattern=true,label="Raumanzugshose",tag={}},
 advancedrocketry_jj_spacestation={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_spacestationchip={hasPattern=true,label="Raumstations ID Chip",tag={}},
 advancedrocketry_jj_stationbuilder={hasPattern=true,label="Raumstationsmonteur",tag={}},
 advancedrocketry_jj_stationmarker={hasPattern=true,label="Raumstation Andockstelle",tag={}},
 advancedrocketry_jj_structuretower={hasPattern=true,label="Structure Tower",tag={}},
 advancedrocketry_jj_suitworkstation={hasPattern=true,label="Raumanzugs Werkbank",tag={}},
 advancedrocketry_jj_terraformer={hasPattern=true,label="Atmospherenmanipulator",tag={}},
 advancedrocketry_jj_thermite={hasPattern=true,label="Thermit",tag={}},
 advancedrocketry_jj_thermitetorch={hasPattern=true,label="Thermitfackel",tag={}},
 advancedrocketry_jj_unlittorch={hasPattern=false,label="",tag={}},
 advancedrocketry_jj_vitrifiedsand={hasPattern=true,label="Verglaster Sand",tag={}},
 advancedrocketry_jj_wafer={hasPattern=true,label="Sillicon Wafer",tag={}},
 advancedrocketry_jj_warpcore={hasPattern=true,label="Warpkern",tag={}},
 advancedrocketry_jj_warpmonitor={hasPattern=true,label="Warpsteuerung",tag={}},
 advancedrocketry_jj_wirelesstransciever={hasPattern=true,label="Wireless Transciever",tag={}},
 buildcraftbuilders_jj_architect={hasPattern=true,label="Architekturtisch",tag={}},
 buildcraftbuilders_jj_builder={hasPattern=true,label="Konstrukteursblock",tag={}},
 buildcraftbuilders_jj_filler={hasPattern=true,label="Füller",tag={}},
 buildcraftbuilders_jj_filler_planner={hasPattern=false,label="",tag={}},
 buildcraftbuilders_jj_frame={hasPattern=true,label="Rahmen",tag={}},
 buildcraftbuilders_jj_library={hasPattern=true,label="Elektronische Bibliothek",tag={}},
 buildcraftbuilders_jj_quarry={hasPattern=true,label="Quarry",tag={}},
 buildcraftbuilders_jj_replacer={hasPattern=true,label="tile.replacerBlock.name",tag={}},
 buildcraftbuilders_jj_schematic_single={hasPattern=false,label="",tag={}},
 buildcraftbuilders_jj_snapshot={hasPattern=true,label="Schablone",tag={}},
 buildcraftbuilders_jj_snapshot_jj_2={hasPattern=true,label="Erweiterter Bauplan",tag={}},
 buildcraftcompat_jj_pipe_item_propolis={hasPattern=true,label="Bienenrohr",tag={}},
 buildcraftcore_jj_decorated={hasPattern=false,label="",tag={}},
 buildcraftcore_jj_decorated_jj_1={hasPattern=false,label="",tag={}},
 buildcraftcore_jj_decorated_jj_2={hasPattern=false,label="",tag={}},
 buildcraftcore_jj_decorated_jj_3={hasPattern=false,label="",tag={}},
 buildcraftcore_jj_decorated_jj_4={hasPattern=false,label="",tag={}},
 buildcraftcore_jj_decorated_jj_5={hasPattern=true,label="Laser (Decoration)",tag={}},
 buildcraftcore_jj_engine={hasPattern=true,label="Redstone-Motor",tag={}},
 buildcraftcore_jj_engine_jj_1={hasPattern=true,label="Stirlingmotor",tag={}},
 buildcraftcore_jj_engine_jj_2={hasPattern=true,label="Verbrennungsmotor",tag={}},
 buildcraftcore_jj_engine_jj_3={hasPattern=false,label="",tag={}},
 buildcraftcore_jj_fragile_fluid_shard={hasPattern=false,label="",tag={}},
 buildcraftcore_jj_gear_diamond={hasPattern=true,label="Diamantzahnrad",tag={}},
 buildcraftcore_jj_gear_gold={hasPattern=true,label="Goldzahnrad",tag={}},
 buildcraftcore_jj_gear_iron={hasPattern=true,label="Eisenzahnrad",tag={}},
 buildcraftcore_jj_gear_stone={hasPattern=true,label="Steinzahnrad",tag={}},
 buildcraftcore_jj_gear_wood={hasPattern=false,label="",tag={}},
 buildcraftcore_jj_list={hasPattern=true,label="Liste",tag={}},
 buildcraftcore_jj_map_location={hasPattern=false,label="",tag={}},
 buildcraftcore_jj_marker_connector={hasPattern=true,label="Marker Connector",tag={}},
 buildcraftcore_jj_marker_path={hasPattern=true,label="Wegmarkierung",tag={}},
 buildcraftcore_jj_marker_volume={hasPattern=true,label="Platzmarker",tag={}},
 buildcraftcore_jj_paintbrush={hasPattern=true,label="Pinsel",tag={}},
 buildcraftcore_jj_paintbrush_jj_1={hasPattern=true,label="§z§0§fWeiß§r Pinsel",tag={}},
 buildcraftcore_jj_paintbrush_jj_10={hasPattern=true,label="§z§0§fWeiß§r Pinsel",tag={}},
 buildcraftcore_jj_paintbrush_jj_11={hasPattern=true,label="§z§0§fWeiß§r Pinsel",tag={}},
 buildcraftcore_jj_paintbrush_jj_12={hasPattern=true,label="§z§0§fWeiß§r Pinsel",tag={}},
 buildcraftcore_jj_paintbrush_jj_13={hasPattern=true,label="§z§0§fWeiß§r Pinsel",tag={}},
 buildcraftcore_jj_paintbrush_jj_14={hasPattern=true,label="§z§0§fWeiß§r Pinsel",tag={}},
 buildcraftcore_jj_paintbrush_jj_15={hasPattern=true,label="§z§0§fWeiß§r Pinsel",tag={}},
 buildcraftcore_jj_paintbrush_jj_16={hasPattern=true,label="§z§0§fWeiß§r Pinsel",tag={}},
 buildcraftcore_jj_paintbrush_jj_2={hasPattern=true,label="§z§0§fWeiß§r Pinsel",tag={}},
 buildcraftcore_jj_paintbrush_jj_3={hasPattern=true,label="§z§0§fWeiß§r Pinsel",tag={}},
 buildcraftcore_jj_paintbrush_jj_4={hasPattern=true,label="§z§0§fWeiß§r Pinsel",tag={}},
 buildcraftcore_jj_paintbrush_jj_5={hasPattern=true,label="§z§0§fWeiß§r Pinsel",tag={}},
 buildcraftcore_jj_paintbrush_jj_6={hasPattern=true,label="§z§0§fWeiß§r Pinsel",tag={}},
 buildcraftcore_jj_paintbrush_jj_7={hasPattern=true,label="§z§0§fWeiß§r Pinsel",tag={}},
 buildcraftcore_jj_paintbrush_jj_8={hasPattern=true,label="§z§0§fWeiß§r Pinsel",tag={}},
 buildcraftcore_jj_paintbrush_jj_9={hasPattern=true,label="§z§0§fWeiß§r Pinsel",tag={}},
 buildcraftcore_jj_spring={hasPattern=false,label="",tag={}},
 buildcraftcore_jj_spring_jj_1={hasPattern=false,label="",tag={}},
 buildcraftcore_jj_volume_box={hasPattern=false,label="",tag={}},
 buildcraftcore_jj_wrench={hasPattern=true,label="Schraubenschlüssel",tag={}},
 buildcraftenergy_jj_glob_of_oil={hasPattern=false,label="",tag={}},
 buildcraftfactory_jj_autoworkbench_item={hasPattern=true,label="Automatische Werkbank",tag={}},
 buildcraftfactory_jj_chute={hasPattern=true,label="Chute",tag={}},
 buildcraftfactory_jj_distiller={hasPattern=true,label="Distiller",tag={}},
 buildcraftfactory_jj_flood_gate={hasPattern=true,label="Auslass",tag={}},
 buildcraftfactory_jj_gel={hasPattern=false,label="",tag={}},
 buildcraftfactory_jj_heat_exchange={hasPattern=true,label="Heat Exchanger",tag={}},
 buildcraftfactory_jj_mining_well={hasPattern=true,label="Minenbohrer",tag={}},
 buildcraftfactory_jj_pump={hasPattern=true,label="Pumpe",tag={}},
 buildcraftfactory_jj_tank={hasPattern=true,label="Tank",tag={}},
 buildcraftfactory_jj_water_gel_spawn={hasPattern=true,label="Water Gelifier",tag={}},
 buildcraftlib_jj_debugger={hasPattern=false,label="",tag={}},
 buildcraftlib_jj_guide={hasPattern=true,label="BuildCraft Guide Book§r",tag={}},
 buildcraftlib_jj_guide_note={hasPattern=false,label="",tag={}},
 buildcraftrobotics_jj_zone_planner={hasPattern=false,label="",tag={}},
 buildcraftsilicon_jj_advanced_crafting_table={hasPattern=true,label="Montagewerkbank",tag={}},
 buildcraftsilicon_jj_assembly_table={hasPattern=true,label="Montagebank",tag={}},
 buildcraftsilicon_jj_integration_table={hasPattern=true,label="Integrationstisch",tag={}},
 buildcraftsilicon_jj_laser={hasPattern=true,label="Laser",tag={}},
 buildcraftsilicon_jj_plug_gate={hasPattern=false,label="",tag={}},
 buildcraftsilicon_jj_plug_gate_b_1={hasPattern=false,label="",tag={gate={logic=0,material=1,modifier=0}}},
 buildcraftsilicon_jj_plug_gate_b_10={hasPattern=false,label="",tag={gate={logic=0,material=2,modifier=1}}},
 buildcraftsilicon_jj_plug_gate_b_11={hasPattern=false,label="",tag={gate={logic=0,material=2,modifier=2}}},
 buildcraftsilicon_jj_plug_gate_b_12={hasPattern=false,label="",tag={gate={logic=0,material=2,modifier=3}}},
 buildcraftsilicon_jj_plug_gate_b_13={hasPattern=false,label="",tag={gate={logic=1,material=2,modifier=0}}},
 buildcraftsilicon_jj_plug_gate_b_14={hasPattern=false,label="",tag={gate={logic=1,material=2,modifier=1}}},
 buildcraftsilicon_jj_plug_gate_b_15={hasPattern=false,label="",tag={gate={logic=1,material=2,modifier=2}}},
 buildcraftsilicon_jj_plug_gate_b_16={hasPattern=false,label="",tag={gate={logic=1,material=2,modifier=3}}},
 buildcraftsilicon_jj_plug_gate_b_17={hasPattern=false,label="",tag={gate={logic=0,material=3,modifier=0}}},
 buildcraftsilicon_jj_plug_gate_b_18={hasPattern=false,label="",tag={gate={logic=0,material=3,modifier=1}}},
 buildcraftsilicon_jj_plug_gate_b_19={hasPattern=false,label="",tag={gate={logic=0,material=3,modifier=2}}},
 buildcraftsilicon_jj_plug_gate_b_2={hasPattern=false,label="",tag={gate={logic=0,material=1,modifier=1}}},
 buildcraftsilicon_jj_plug_gate_b_20={hasPattern=false,label="",tag={gate={logic=0,material=3,modifier=3}}},
 buildcraftsilicon_jj_plug_gate_b_21={hasPattern=false,label="",tag={gate={logic=1,material=3,modifier=0}}},
 buildcraftsilicon_jj_plug_gate_b_22={hasPattern=false,label="",tag={gate={logic=1,material=3,modifier=1}}},
 buildcraftsilicon_jj_plug_gate_b_23={hasPattern=false,label="",tag={gate={logic=1,material=3,modifier=2}}},
 buildcraftsilicon_jj_plug_gate_b_24={hasPattern=false,label="",tag={}},
 buildcraftsilicon_jj_plug_gate_b_3={hasPattern=false,label="",tag={gate={logic=0,material=1,modifier=2}}},
 buildcraftsilicon_jj_plug_gate_b_4={hasPattern=false,label="",tag={gate={logic=0,material=1,modifier=3}}},
 buildcraftsilicon_jj_plug_gate_b_5={hasPattern=false,label="",tag={gate={logic=1,material=1,modifier=0}}},
 buildcraftsilicon_jj_plug_gate_b_6={hasPattern=false,label="",tag={gate={logic=1,material=1,modifier=1}}},
 buildcraftsilicon_jj_plug_gate_b_7={hasPattern=false,label="",tag={gate={logic=1,material=1,modifier=2}}},
 buildcraftsilicon_jj_plug_gate_b_8={hasPattern=false,label="",tag={gate={logic=1,material=1,modifier=3}}},
 buildcraftsilicon_jj_plug_gate_b_9={hasPattern=false,label="",tag={gate={logic=0,material=2,modifier=0}}},
 buildcraftsilicon_jj_plug_lens={hasPattern=true,label="§0§7Schwarz§r Linse",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_1={hasPattern=true,label="§z§e§cRot§r Linse",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_10={hasPattern=true,label="§z§5§aHellgrün§r Linse",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_11={hasPattern=true,label="§z§4§eGelb§r Linse",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_12={hasPattern=true,label="§z§3§bHellblau§r Linse",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_13={hasPattern=true,label="§z§2§dMagenta§r Linse",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_14={hasPattern=true,label="§z§1§6Orange§r Linse",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_15={hasPattern=true,label="§z§0§fWeiß§r Linse",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_16={hasPattern=true,label="§0§7Schwarz§r Filter",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_17={hasPattern=true,label="§z§e§cRot§r Filter",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_18={hasPattern=true,label="§z§d§aGrün§r Filter",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_19={hasPattern=true,label="§z§c§6Braun§r Filter",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_2={hasPattern=true,label="§z§d§aGrün§r Linse",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_20={hasPattern=true,label="§9§9Blau§r Filter",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_21={hasPattern=true,label="§z§a§dViolett§r Filter",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_22={hasPattern=true,label="§z§9§3Türkis§r Filter",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_23={hasPattern=true,label="§z§8§7Hellgrau§r Filter",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_24={hasPattern=true,label="§z§7§7Grau§r Filter",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_25={hasPattern=true,label="§z§6§dRosa§r Filter",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_26={hasPattern=true,label="§z§5§aHellgrün§r Filter",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_27={hasPattern=true,label="§z§4§eGelb§r Filter",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_28={hasPattern=true,label="§z§3§bHellblau§r Filter",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_29={hasPattern=true,label="§z§2§dMagenta§r Filter",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_3={hasPattern=true,label="§z§c§6Braun§r Linse",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_30={hasPattern=true,label="§z§1§6Orange§r Filter",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_31={hasPattern=true,label="§z§0§fWeiß§r Filter",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_32={hasPattern=true,label="Klar Linse",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_33={hasPattern=true,label="Klar Filter",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_4={hasPattern=true,label="§9§9Blau§r Linse",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_5={hasPattern=true,label="§z§a§dViolett§r Linse",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_6={hasPattern=true,label="§z§9§3Türkis§r Linse",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_7={hasPattern=true,label="§z§8§7Hellgrau§r Linse",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_8={hasPattern=true,label="§z§7§7Grau§r Linse",tag={}},
 buildcraftsilicon_jj_plug_lens_jj_9={hasPattern=true,label="§z§6§dRosa§r Linse",tag={}},
 buildcraftsilicon_jj_plug_light_sensor={hasPattern=true,label="Light Sensor",tag={}},
 buildcraftsilicon_jj_plug_pulsar={hasPattern=true,label="Pipe Pulsar",tag={}},
 buildcraftsilicon_jj_redstone_chipset={hasPattern=true,label="Redstone-Schaltkreis",tag={}},
 buildcraftsilicon_jj_redstone_chipset_jj_1={hasPattern=true,label="Eiserner Schaltkreis",tag={}},
 buildcraftsilicon_jj_redstone_chipset_jj_2={hasPattern=true,label="Goldener Schaltkreis",tag={}},
 buildcraftsilicon_jj_redstone_chipset_jj_3={hasPattern=true,label="Quarz-Schaltkreis",tag={}},
 buildcraftsilicon_jj_redstone_chipset_jj_4={hasPattern=true,label="Diamantener Schaltkreis",tag={}},
 buildcrafttransport_jj_filtered_buffer={hasPattern=true,label="Gefilterter Puffer",tag={}},
 buildcrafttransport_jj_pipe_clay_fluid={hasPattern=true,label="Lehmiges Flüssigkeitsrohr",tag={}},
 buildcrafttransport_jj_pipe_clay_item={hasPattern=true,label="Lehmiges Transportrohr",tag={}},
 buildcrafttransport_jj_pipe_cobble_fluid={hasPattern=true,label="Pflastersteinernes Flüssigkeitsrohr",tag={}},
 buildcrafttransport_jj_pipe_cobble_item={hasPattern=true,label="Pflasterstein-Transportrohr",tag={}},
 buildcrafttransport_jj_pipe_cobble_power={hasPattern=true,label="Pflasterstein-Energieleitung",tag={}},
 buildcrafttransport_jj_pipe_daizuli_item={hasPattern=true,label="Daizuli-Transportrohr",tag={}},
 buildcrafttransport_jj_pipe_diamond_fluid={hasPattern=true,label="Diamantenes Flüssigkeitsrohr",tag={}},
 buildcrafttransport_jj_pipe_diamond_item={hasPattern=true,label="Diamantenes Transportrohr",tag={}},
 buildcrafttransport_jj_pipe_diamond_wood_fluid={hasPattern=true,label="Wooden Diamond Fluid Pipe",tag={}},
 buildcrafttransport_jj_pipe_diamond_wood_item={hasPattern=true,label="Wooden Diamond Transport Pipe",tag={}},
 buildcrafttransport_jj_pipe_emzuli_item={hasPattern=true,label="Emzuli-Transportrohr",tag={}},
 buildcrafttransport_jj_pipe_gold_fluid={hasPattern=true,label="Goldenes Flüssigkeitsrohr",tag={}},
 buildcrafttransport_jj_pipe_gold_item={hasPattern=true,label="Goldenes Transportrohr",tag={}},
 buildcrafttransport_jj_pipe_gold_power={hasPattern=true,label="Goldene Energieleitung",tag={}},
 buildcrafttransport_jj_pipe_iron_fluid={hasPattern=true,label="Eisernes Flüssigkeitsrohr",tag={}},
 buildcrafttransport_jj_pipe_iron_item={hasPattern=true,label="Eisernes Transportrohr",tag={}},
 buildcrafttransport_jj_pipe_lapis_item={hasPattern=true,label="Lazuli-Transportrohr",tag={}},
 buildcrafttransport_jj_pipe_obsidian_item={hasPattern=true,label="Obsidian-Transportrohr",tag={}},
 buildcrafttransport_jj_pipe_quartz_fluid={hasPattern=true,label="Quarz-Flüssigkeitsrohr",tag={}},
 buildcrafttransport_jj_pipe_quartz_item={hasPattern=true,label="Quarz-Transportrohr",tag={}},
 buildcrafttransport_jj_pipe_quartz_power={hasPattern=true,label="Quarz-Energieleitung",tag={}},
 buildcrafttransport_jj_pipe_sandstone_fluid={hasPattern=true,label="Sandstein-Flüssigkeitsrohr",tag={}},
 buildcrafttransport_jj_pipe_sandstone_item={hasPattern=true,label="Sandstein-Transportrohr",tag={}},
 buildcrafttransport_jj_pipe_sandstone_power={hasPattern=true,label="Sandstein-Energieleitung",tag={}},
 buildcrafttransport_jj_pipe_stone_fluid={hasPattern=true,label="Steineres Flüssigkeitsrohr",tag={}},
 buildcrafttransport_jj_pipe_stone_item={hasPattern=true,label="Steineres Transportrohr",tag={}},
 buildcrafttransport_jj_pipe_stone_power={hasPattern=true,label="Steinerne Energieleitung",tag={}},
 buildcrafttransport_jj_pipe_stripes_item={hasPattern=true,label="Gestreiftes Transportrohr",tag={}},
 buildcrafttransport_jj_pipe_structure={hasPattern=true,label="Strukturrohr",tag={}},
 buildcrafttransport_jj_pipe_void_fluid={hasPattern=true,label="Löschendes Flüssigkeitsrohr",tag={}},
 buildcrafttransport_jj_pipe_void_item={hasPattern=true,label="Löschendes Transportrohr",tag={}},
 buildcrafttransport_jj_pipe_wood_fluid={hasPattern=true,label="Hölzernes Flüssigkeitsrohr",tag={}},
 buildcrafttransport_jj_pipe_wood_item={hasPattern=true,label="Hölzernes Transportrohr",tag={}},
 buildcrafttransport_jj_pipe_wood_power={hasPattern=true,label="Hölzerne Energieleitung",tag={}},
 buildcrafttransport_jj_plug_blocker={hasPattern=true,label="Rohrstöpsel",tag={}},
 buildcrafttransport_jj_plug_power_adaptor={hasPattern=true,label="Energieadapter",tag={}},
 buildcrafttransport_jj_waterproof={hasPattern=true,label="Dichtung",tag={}},
 buildcrafttransport_jj_wire={hasPattern=true,label="§z§0§fWeiß§r Pipe Wire",tag={}},
 buildcrafttransport_jj_wire_jj_1={hasPattern=true,label="§z§1§6Orange§r Pipe Wire",tag={}},
 buildcrafttransport_jj_wire_jj_10={hasPattern=true,label="§z§a§dViolett§r Pipe Wire",tag={}},
 buildcrafttransport_jj_wire_jj_11={hasPattern=true,label="§9§9Blau§r Pipe Wire",tag={}},
 buildcrafttransport_jj_wire_jj_12={hasPattern=true,label="§z§c§6Braun§r Pipe Wire",tag={}},
 buildcrafttransport_jj_wire_jj_13={hasPattern=true,label="§z§d§aGrün§r Pipe Wire",tag={}},
 buildcrafttransport_jj_wire_jj_14={hasPattern=true,label="§z§e§cRot§r Pipe Wire",tag={}},
 buildcrafttransport_jj_wire_jj_15={hasPattern=true,label="§0§7Schwarz§r Pipe Wire",tag={}},
 buildcrafttransport_jj_wire_jj_2={hasPattern=true,label="§z§2§dMagenta§r Pipe Wire",tag={}},
 buildcrafttransport_jj_wire_jj_3={hasPattern=true,label="§z§3§bHellblau§r Pipe Wire",tag={}},
 buildcrafttransport_jj_wire_jj_4={hasPattern=true,label="§z§4§eGelb§r Pipe Wire",tag={}},
 buildcrafttransport_jj_wire_jj_5={hasPattern=true,label="§z§5§aHellgrün§r Pipe Wire",tag={}},
 buildcrafttransport_jj_wire_jj_6={hasPattern=true,label="§z§6§dRosa§r Pipe Wire",tag={}},
 buildcrafttransport_jj_wire_jj_7={hasPattern=true,label="§z§7§7Grau§r Pipe Wire",tag={}},
 buildcrafttransport_jj_wire_jj_8={hasPattern=true,label="§z§8§7Hellgrau§r Pipe Wire",tag={}},
 buildcrafttransport_jj_wire_jj_9={hasPattern=true,label="§z§9§3Türkis§r Pipe Wire",tag={}},
 libvulpes_jj_advancedmotor={hasPattern=true,label="Advanced Motor",tag={}},
 libvulpes_jj_advstructuremachine={hasPattern=true,label="Advanced Machine Structure",tag={}},
 libvulpes_jj_battery={hasPattern=true,label="Kleine Batterie",tag={}},
 libvulpes_jj_battery_jj_1={hasPattern=true,label="2x Kleine Batterie",tag={}},
 libvulpes_jj_blockphantom={hasPattern=false,label="",tag={}},
 libvulpes_jj_coalgenerator={hasPattern=true,label="Coal Generator",tag={}},
 libvulpes_jj_coil0_jj_10={hasPattern=true,label="Iridium Coil",tag={}},
 libvulpes_jj_coil0_jj_2={hasPattern=true,label="Gold Coil",tag={}},
 libvulpes_jj_coil0_jj_4={hasPattern=true,label="Copper Coil",tag={}},
 libvulpes_jj_coil0_jj_7={hasPattern=true,label="Titanium Coil",tag={}},
 libvulpes_jj_coil0_jj_9={hasPattern=true,label="Aluminum Coil",tag={}},
 libvulpes_jj_creativepowerbattery={hasPattern=false,label="",tag={}},
 libvulpes_jj_elitemotor={hasPattern=true,label="Elite Motor",tag={}},
 libvulpes_jj_enhancedmotor={hasPattern=true,label="Enhanced Motor",tag={}},
 libvulpes_jj_forgepowerinput={hasPattern=true,label="Power Input Plug",tag={}},
 libvulpes_jj_forgepoweroutput={hasPattern=true,label="Power Output Plug",tag={}},
 libvulpes_jj_hatch={hasPattern=true,label="Input Hatch",tag={}},
 libvulpes_jj_hatch_jj_1={hasPattern=true,label="Output Hatch",tag={}},
 libvulpes_jj_hatch_jj_2={hasPattern=true,label="Fluid Input Hatch",tag={}},
 libvulpes_jj_hatch_jj_3={hasPattern=true,label="Fluid Output Hatch",tag={}},
 libvulpes_jj_holoprojector={hasPattern=true,label="Holo-Projector",tag={}},
 libvulpes_jj_ic2plug={hasPattern=true,label="IC2 Plug(EU)",tag={}},
 libvulpes_jj_linker={hasPattern=true,label="Linker",tag={}},
 libvulpes_jj_metal0_jj_10={hasPattern=true,label="Iridium Block",tag={}},
 libvulpes_jj_metal0_jj_4={hasPattern=true,label="Copper Block",tag={}},
 libvulpes_jj_metal0_jj_5={hasPattern=true,label="Tin Block",tag={}},
 libvulpes_jj_metal0_jj_6={hasPattern=true,label="Steel Block",tag={}},
 libvulpes_jj_metal0_jj_7={hasPattern=true,label="Titanium Block",tag={}},
 libvulpes_jj_metal0_jj_9={hasPattern=true,label="Aluminum Block",tag={}},
 libvulpes_jj_motor={hasPattern=true,label="Motor",tag={}},
 libvulpes_jj_ore0={hasPattern=false,label="",tag={}},
 libvulpes_jj_ore0_jj_10={hasPattern=false,label="",tag={}},
 libvulpes_jj_ore0_jj_4={hasPattern=false,label="",tag={}},
 libvulpes_jj_ore0_jj_5={hasPattern=false,label="",tag={}},
 libvulpes_jj_ore0_jj_8={hasPattern=false,label="",tag={}},
 libvulpes_jj_ore0_jj_9={hasPattern=false,label="",tag={}},
 libvulpes_jj_placeholder={hasPattern=false,label="",tag={}},
 libvulpes_jj_productboule_jj_3={hasPattern=true,label="Silicon Boule",tag={}},
 libvulpes_jj_productdust={hasPattern=true,label="Dilizium Dust",tag={}},
 libvulpes_jj_productdust_jj_1={hasPattern=true,label="Iron Dust",tag={}},
 libvulpes_jj_productdust_jj_10={hasPattern=true,label="Iridium Dust",tag={}},
 libvulpes_jj_productdust_jj_2={hasPattern=true,label="Gold Dust",tag={}},
 libvulpes_jj_productdust_jj_3={hasPattern=true,label="Silicon Dust",tag={}},
 libvulpes_jj_productdust_jj_4={hasPattern=true,label="Copper Dust",tag={}},
 libvulpes_jj_productdust_jj_5={hasPattern=true,label="Tin Dust",tag={}},
 libvulpes_jj_productdust_jj_6={hasPattern=true,label="Steel Dust",tag={}},
 libvulpes_jj_productdust_jj_7={hasPattern=true,label="Titanium Dust",tag={}},
 libvulpes_jj_productdust_jj_9={hasPattern=true,label="Aluminum Dust",tag={}},
 libvulpes_jj_productfan_jj_6={hasPattern=true,label="Steel Fan",tag={}},
 libvulpes_jj_productgear_jj_6={hasPattern=true,label="Steel Gear",tag={}},
 libvulpes_jj_productgear_jj_7={hasPattern=true,label="Titanium Gear",tag={}},
 libvulpes_jj_productgem={hasPattern=false,label="",tag={}},
 libvulpes_jj_productingot_jj_10={hasPattern=true,label="Iridium Ingot",tag={}},
 libvulpes_jj_productingot_jj_3={hasPattern=true,label="Silicon Ingot",tag={}},
 libvulpes_jj_productingot_jj_4={hasPattern=true,label="Copper Ingot",tag={}},
 libvulpes_jj_productingot_jj_5={hasPattern=true,label="Tin Ingot",tag={}},
 libvulpes_jj_productingot_jj_6={hasPattern=true,label="Steel Ingot",tag={}},
 libvulpes_jj_productingot_jj_7={hasPattern=true,label="Titanium Ingot",tag={}},
 libvulpes_jj_productingot_jj_9={hasPattern=true,label="Aluminum Ingot",tag={}},
 libvulpes_jj_productnugget_jj_10={hasPattern=true,label="Iridium Nugget",tag={}},
 libvulpes_jj_productnugget_jj_3={hasPattern=true,label="Silicon Nugget",tag={}},
 libvulpes_jj_productnugget_jj_4={hasPattern=true,label="Copper Nugget",tag={}},
 libvulpes_jj_productnugget_jj_5={hasPattern=true,label="Tin Nugget",tag={}},
 libvulpes_jj_productnugget_jj_6={hasPattern=true,label="Steel Nugget",tag={}},
 libvulpes_jj_productnugget_jj_7={hasPattern=true,label="Titanium Nugget",tag={}},
 libvulpes_jj_productnugget_jj_9={hasPattern=true,label="Aluminum Nugget",tag={}},
 libvulpes_jj_productplate_jj_1={hasPattern=true,label="Iron Plate",tag={}},
 libvulpes_jj_productplate_jj_10={hasPattern=true,label="Iridium Plate",tag={}},
 libvulpes_jj_productplate_jj_2={hasPattern=true,label="Gold Plate",tag={}},
 libvulpes_jj_productplate_jj_3={hasPattern=true,label="Silicon Plate",tag={}},
 libvulpes_jj_productplate_jj_4={hasPattern=true,label="Copper Plate",tag={}},
 libvulpes_jj_productplate_jj_5={hasPattern=true,label="Tin Plate",tag={}},
 libvulpes_jj_productplate_jj_6={hasPattern=true,label="Steel Plate",tag={}},
 libvulpes_jj_productplate_jj_7={hasPattern=true,label="Titanium Plate",tag={}},
 libvulpes_jj_productplate_jj_9={hasPattern=true,label="Aluminum Plate",tag={}},
 libvulpes_jj_productrod_jj_1={hasPattern=true,label="Iron Rod",tag={}},
 libvulpes_jj_productrod_jj_10={hasPattern=true,label="Iridium Rod",tag={}},
 libvulpes_jj_productrod_jj_4={hasPattern=true,label="Copper Rod",tag={}},
 libvulpes_jj_productrod_jj_6={hasPattern=true,label="Steel Rod",tag={}},
 libvulpes_jj_productrod_jj_7={hasPattern=true,label="Titanium Rod",tag={}},
 libvulpes_jj_productsheet_jj_1={hasPattern=true,label="Iron Sheet",tag={}},
 libvulpes_jj_productsheet_jj_4={hasPattern=true,label="Copper Sheet",tag={}},
 libvulpes_jj_productsheet_jj_6={hasPattern=true,label="Steel Sheet",tag={}},
 libvulpes_jj_productsheet_jj_7={hasPattern=true,label="Titanium Sheet",tag={}},
 libvulpes_jj_productsheet_jj_9={hasPattern=true,label="Aluminum Sheet",tag={}},
 libvulpes_jj_structuremachine={hasPattern=true,label="Machine Structure",tag={}}
 }