return {
 darkutils_jj_anti_slime={hasPattern=true,label="",tag=""},
 darkutils_jj_charm_agression={hasPattern=true,label="",tag=""},
 darkutils_jj_charm_gluttony={hasPattern=true,label="",tag=""},
 darkutils_jj_charm_null={hasPattern=true,label="",tag=""},
 darkutils_jj_charm_portal={hasPattern=true,label="",tag=""},
 darkutils_jj_charm_sleep={hasPattern=true,label="",tag=""},
 darkutils_jj_ender_hopper={hasPattern=true,label="",tag=""},
 darkutils_jj_ender_pearl_hopper={hasPattern=true,label="",tag=""},
 darkutils_jj_ender_tether={hasPattern=true,label="",tag=""},
 darkutils_jj_fake_tnt={hasPattern=true,label="",tag=""},
 darkutils_jj_filter={hasPattern=true,label="",tag=""},
 darkutils_jj_filter_inverted={hasPattern=true,label="",tag=""},
 darkutils_jj_filter_inverted_jj_1={hasPattern=true,label="",tag=""},
 darkutils_jj_filter_inverted_jj_10={hasPattern=true,label="",tag=""},
 darkutils_jj_filter_inverted_jj_2={hasPattern=true,label="",tag=""},
 darkutils_jj_filter_inverted_jj_3={hasPattern=true,label="",tag=""},
 darkutils_jj_filter_inverted_jj_4={hasPattern=true,label="",tag=""},
 darkutils_jj_filter_inverted_jj_5={hasPattern=true,label="",tag=""},
 darkutils_jj_filter_inverted_jj_6={hasPattern=true,label="",tag=""},
 darkutils_jj_filter_inverted_jj_7={hasPattern=true,label="",tag=""},
 darkutils_jj_filter_inverted_jj_8={hasPattern=true,label="",tag=""},
 darkutils_jj_filter_inverted_jj_9={hasPattern=true,label="",tag=""},
 darkutils_jj_filter_jj_1={hasPattern=true,label="",tag=""},
 darkutils_jj_filter_jj_10={hasPattern=true,label="",tag=""},
 darkutils_jj_filter_jj_2={hasPattern=true,label="",tag=""},
 darkutils_jj_filter_jj_3={hasPattern=true,label="",tag=""},
 darkutils_jj_filter_jj_4={hasPattern=true,label="",tag=""},
 darkutils_jj_filter_jj_5={hasPattern=true,label="",tag=""},
 darkutils_jj_filter_jj_6={hasPattern=true,label="",tag=""},
 darkutils_jj_filter_jj_7={hasPattern=true,label="",tag=""},
 darkutils_jj_filter_jj_8={hasPattern=true,label="",tag=""},
 darkutils_jj_filter_jj_9={hasPattern=true,label="",tag=""},
 darkutils_jj_focus_sash={hasPattern=true,label="",tag=""},
 darkutils_jj_grate={hasPattern=true,label="",tag=""},
 darkutils_jj_lore_tag={hasPattern=true,label="",tag=""},
 darkutils_jj_lore_tag_jj_1={hasPattern=true,label="",tag=""},
 darkutils_jj_lore_tag_jj_10={hasPattern=true,label="",tag=""},
 darkutils_jj_lore_tag_jj_11={hasPattern=true,label="",tag=""},
 darkutils_jj_lore_tag_jj_12={hasPattern=true,label="",tag=""},
 darkutils_jj_lore_tag_jj_13={hasPattern=true,label="",tag=""},
 darkutils_jj_lore_tag_jj_14={hasPattern=true,label="",tag=""},
 darkutils_jj_lore_tag_jj_15={hasPattern=true,label="",tag=""},
 darkutils_jj_lore_tag_jj_2={hasPattern=true,label="",tag=""},
 darkutils_jj_lore_tag_jj_3={hasPattern=true,label="",tag=""},
 darkutils_jj_lore_tag_jj_4={hasPattern=true,label="",tag=""},
 darkutils_jj_lore_tag_jj_5={hasPattern=true,label="",tag=""},
 darkutils_jj_lore_tag_jj_6={hasPattern=true,label="",tag=""},
 darkutils_jj_lore_tag_jj_7={hasPattern=true,label="",tag=""},
 darkutils_jj_lore_tag_jj_8={hasPattern=true,label="",tag=""},
 darkutils_jj_lore_tag_jj_9={hasPattern=true,label="",tag=""},
 darkutils_jj_material={hasPattern=true,label="",tag=""},
 darkutils_jj_material_jj_1={hasPattern=true,label="",tag=""},
 darkutils_jj_material_jj_2={hasPattern=true,label="",tag=""},
 darkutils_jj_material_jj_3={hasPattern=true,label="",tag=""},
 darkutils_jj_monolith={hasPattern=true,label="",tag=""},
 darkutils_jj_monolith_jj_1={hasPattern=true,label="",tag=""},
 darkutils_jj_pearl_block={hasPattern=true,label="",tag=""},
 darkutils_jj_pearl_block_jj_1={hasPattern=true,label="",tag=""},
 darkutils_jj_pearl_block_jj_2={hasPattern=true,label="",tag=""},
 darkutils_jj_pearl_block_jj_3={hasPattern=true,label="",tag=""},
 darkutils_jj_shulker_pearl={hasPattern=true,label="",tag=""},
 darkutils_jj_slime_dyed={hasPattern=true,label="",tag=""},
 darkutils_jj_slime_dyed_jj_1={hasPattern=true,label="",tag=""},
 darkutils_jj_slime_dyed_jj_10={hasPattern=true,label="",tag=""},
 darkutils_jj_slime_dyed_jj_11={hasPattern=true,label="",tag=""},
 darkutils_jj_slime_dyed_jj_12={hasPattern=true,label="",tag=""},
 darkutils_jj_slime_dyed_jj_13={hasPattern=true,label="",tag=""},
 darkutils_jj_slime_dyed_jj_14={hasPattern=true,label="",tag=""},
 darkutils_jj_slime_dyed_jj_15={hasPattern=true,label="",tag=""},
 darkutils_jj_slime_dyed_jj_2={hasPattern=true,label="",tag=""},
 darkutils_jj_slime_dyed_jj_3={hasPattern=true,label="",tag=""},
 darkutils_jj_slime_dyed_jj_4={hasPattern=true,label="",tag=""},
 darkutils_jj_slime_dyed_jj_5={hasPattern=true,label="",tag=""},
 darkutils_jj_slime_dyed_jj_6={hasPattern=true,label="",tag=""},
 darkutils_jj_slime_dyed_jj_7={hasPattern=true,label="",tag=""},
 darkutils_jj_slime_dyed_jj_8={hasPattern=true,label="",tag=""},
 darkutils_jj_slime_dyed_jj_9={hasPattern=true,label="",tag=""},
 darkutils_jj_sneaky={hasPattern=true,label="",tag=""},
 darkutils_jj_sneaky_bedrock={hasPattern=true,label="",tag=""},
 darkutils_jj_sneaky_button={hasPattern=true,label="",tag=""},
 darkutils_jj_sneaky_ghost={hasPattern=true,label="",tag=""},
 darkutils_jj_sneaky_lever={hasPattern=true,label="",tag=""},
 darkutils_jj_sneaky_obsidian={hasPattern=true,label="",tag=""},
 darkutils_jj_sneaky_plate={hasPattern=true,label="",tag=""},
 darkutils_jj_sneaky_torch={hasPattern=true,label="",tag=""},
 darkutils_jj_timer={hasPattern=true,label="",tag=""},
 darkutils_jj_trap_anchor={hasPattern=true,label="",tag=""},
 darkutils_jj_trap_move={hasPattern=true,label="",tag=""},
 darkutils_jj_trap_move_fast={hasPattern=true,label="",tag=""},
 darkutils_jj_trap_move_hyper={hasPattern=true,label="",tag=""},
 darkutils_jj_trap_tile={hasPattern=true,label="",tag=""},
 darkutils_jj_trap_tile_jj_1={hasPattern=true,label="",tag=""},
 darkutils_jj_trap_tile_jj_2={hasPattern=true,label="",tag=""},
 darkutils_jj_trap_tile_jj_3={hasPattern=true,label="",tag=""},
 darkutils_jj_trap_tile_jj_4={hasPattern=true,label="",tag=""},
 darkutils_jj_trap_tile_jj_5={hasPattern=true,label="",tag=""},
 darkutils_jj_trap_tile_jj_6={hasPattern=true,label="",tag=""},
 darkutils_jj_trap_tile_jj_7={hasPattern=true,label="",tag=""},
 darkutils_jj_update_detector={hasPattern=true,label="",tag=""},
 darkutils_jj_wither_block={hasPattern=true,label="",tag=""},
 darkutils_jj_wither_block_jj_1={hasPattern=true,label="",tag=""},
 darkutils_jj_wither_block_jj_2={hasPattern=true,label="",tag=""},
 darkutils_jj_wither_block_jj_3={hasPattern=true,label="",tag=""},
 darkutils_jj_wither_block_jj_4={hasPattern=true,label="",tag=""},
 darkutils_jj_wither_block_jj_5={hasPattern=true,label="",tag=""},
 defiledlands_jj_black_heart={hasPattern=true,label="",tag=""},
 defiledlands_jj_blastem_fruit={hasPattern=true,label="",tag=""},
 defiledlands_jj_blastem_fruit_blazing={hasPattern=true,label="",tag=""},
 defiledlands_jj_blastem_seed={hasPattern=true,label="",tag=""},
 defiledlands_jj_book_wyrm_analyzer={hasPattern=true,label="",tag=""},
 defiledlands_jj_book_wyrm_cooked={hasPattern=true,label="",tag=""},
 defiledlands_jj_book_wyrm_raw={hasPattern=false,label="",tag=""},
 defiledlands_jj_book_wyrm_scale={hasPattern=false,label="",tag=""},
 defiledlands_jj_book_wyrm_scale_golden={hasPattern=true,label="",tag=""},
 defiledlands_jj_calling_stone={hasPattern=true,label="",tag=""},
 defiledlands_jj_concussion_smasher={hasPattern=true,label="",tag=""},
 defiledlands_jj_conjuring_altar={hasPattern=true,label="",tag=""},
 defiledlands_jj_defilement_powder={hasPattern=true,label="",tag=""},
 defiledlands_jj_dirt_defiled={hasPattern=false,label="",tag=""},
 defiledlands_jj_essence_destroyer={hasPattern=false,label="",tag=""},
 defiledlands_jj_essence_mourner={hasPattern=true,label="",tag=""},
 defiledlands_jj_foul_candy={hasPattern=true,label="",tag=""},
 defiledlands_jj_foul_slime={hasPattern=false,label="",tag=""},
 defiledlands_jj_glass_obscure={hasPattern=true,label="",tag=""},
 defiledlands_jj_grass_defiled={hasPattern=false,label="",tag=""},
 defiledlands_jj_gravel_defiled={hasPattern=false,label="",tag=""},
 defiledlands_jj_healing_pad={hasPattern=true,label="",tag=""},
 defiledlands_jj_hephaestite={hasPattern=true,label="",tag=""},
 defiledlands_jj_hephaestite_block={hasPattern=true,label="",tag=""},
 defiledlands_jj_hephaestite_ore={hasPattern=true,label="",tag=""},
 defiledlands_jj_idol_sorrow={hasPattern=true,label="",tag=""},
 defiledlands_jj_molten_umbrium={hasPattern=true,label="",tag=""},
 defiledlands_jj_pellet_ravaging={hasPattern=true,label="",tag=""},
 defiledlands_jj_pellet_spiked={hasPattern=true,label="",tag=""},
 defiledlands_jj_pellet_umbrium={hasPattern=true,label="",tag=""},
 defiledlands_jj_phytoprostasia_amulet={hasPattern=true,label="",tag=""},
 defiledlands_jj_ravaging_axe={hasPattern=true,label="",tag=""},
 defiledlands_jj_ravaging_decoration={hasPattern=true,label="",tag=""},
 defiledlands_jj_ravaging_decoration_jj_1={hasPattern=true,label="",tag=""},
 defiledlands_jj_ravaging_ingot={hasPattern=true,label="",tag=""},
 defiledlands_jj_ravaging_pickaxe={hasPattern=true,label="",tag=""},
 defiledlands_jj_ravaging_shovel={hasPattern=true,label="",tag=""},
 defiledlands_jj_remorseful_gem={hasPattern=true,label="",tag=""},
 defiledlands_jj_sand_defiled={hasPattern=false,label="",tag=""},
 defiledlands_jj_sandstone_defiled={hasPattern=true,label="",tag=""},
 defiledlands_jj_sandstone_defiled_stairs={hasPattern=true,label="",tag=""},
 defiledlands_jj_scale_boots={hasPattern=true,label="",tag=""},
 defiledlands_jj_scale_chestplate={hasPattern=true,label="",tag=""},
 defiledlands_jj_scale_golden_boots={hasPattern=true,label="",tag=""},
 defiledlands_jj_scale_golden_chestplate={hasPattern=true,label="",tag=""},
 defiledlands_jj_scale_golden_helmet={hasPattern=true,label="",tag=""},
 defiledlands_jj_scale_golden_leggings={hasPattern=true,label="",tag=""},
 defiledlands_jj_scale_helmet={hasPattern=true,label="",tag=""},
 defiledlands_jj_scale_leggings={hasPattern=true,label="",tag=""},
 defiledlands_jj_scarlite={hasPattern=true,label="",tag=""},
 defiledlands_jj_scarlite_block={hasPattern=true,label="",tag=""},
 defiledlands_jj_scarlite_ore={hasPattern=true,label="",tag=""},
 defiledlands_jj_scarlite_razor={hasPattern=true,label="",tag=""},
 defiledlands_jj_scarlite_reaver={hasPattern=true,label="",tag=""},
 defiledlands_jj_scarlite_ring={hasPattern=true,label="",tag=""},
 defiledlands_jj_scuronotte={hasPattern=true,label="",tag=""},
 defiledlands_jj_scuttler_eye={hasPattern=true,label="",tag=""},
 defiledlands_jj_stone_defiled={hasPattern=false,label="",tag=""},
 defiledlands_jj_stone_defiled_bricks_stairs={hasPattern=true,label="",tag=""},
 defiledlands_jj_stone_defiled_decoration={hasPattern=true,label="",tag=""},
 defiledlands_jj_stone_defiled_decoration_jj_1={hasPattern=true,label="",tag=""},
 defiledlands_jj_stone_defiled_decoration_jj_2={hasPattern=true,label="",tag=""},
 defiledlands_jj_stone_defiled_decoration_jj_3={hasPattern=true,label="",tag=""},
 defiledlands_jj_stone_defiled_slab={hasPattern=true,label="",tag=""},
 defiledlands_jj_stone_defiled_slab_jj_1={hasPattern=true,label="",tag=""},
 defiledlands_jj_stone_defiled_slab_jj_2={hasPattern=true,label="",tag=""},
 defiledlands_jj_stone_defiled_stairs={hasPattern=true,label="",tag=""},
 defiledlands_jj_tears_flame={hasPattern=true,label="",tag=""},
 defiledlands_jj_tears_shulker={hasPattern=true,label="",tag=""},
 defiledlands_jj_tenebra_door={hasPattern=true,label="",tag=""},
 defiledlands_jj_tenebra_leaves={hasPattern=true,label="",tag=""},
 defiledlands_jj_tenebra_log={hasPattern=true,label="",tag=""},
 defiledlands_jj_tenebra_planks={hasPattern=true,label="",tag=""},
 defiledlands_jj_tenebra_sapling={hasPattern=true,label="",tag=""},
 defiledlands_jj_tenebra_stairs={hasPattern=true,label="",tag=""},
 defiledlands_jj_the_ravager={hasPattern=true,label="",tag=""},
 defiledlands_jj_umbra_blaster={hasPattern=true,label="",tag=""},
 defiledlands_jj_umbrium_axe={hasPattern=true,label="",tag=""},
 defiledlands_jj_umbrium_block={hasPattern=true,label="",tag=""},
 defiledlands_jj_umbrium_boots={hasPattern=true,label="",tag=""},
 defiledlands_jj_umbrium_chestplate={hasPattern=true,label="",tag=""},
 defiledlands_jj_umbrium_helmet={hasPattern=true,label="",tag=""},
 defiledlands_jj_umbrium_hoe={hasPattern=true,label="",tag=""},
 defiledlands_jj_umbrium_ingot={hasPattern=true,label="",tag=""},
 defiledlands_jj_umbrium_leggings={hasPattern=true,label="",tag=""},
 defiledlands_jj_umbrium_nugget={hasPattern=true,label="",tag=""},
 defiledlands_jj_umbrium_ore={hasPattern=true,label="",tag=""},
 defiledlands_jj_umbrium_pickaxe={hasPattern=true,label="",tag=""},
 defiledlands_jj_umbrium_shovel={hasPattern=true,label="",tag=""},
 defiledlands_jj_umbrium_sword={hasPattern=true,label="",tag=""},
 defiledlands_jj_vilespine={hasPattern=true,label="",tag=""},
 defiledlands_jj_wood_defiled_slab={hasPattern=true,label="",tag=""},
 extrautils2_jj_analogcrafter={hasPattern=true,label="",tag=""},
 extrautils2_jj_angelblock={hasPattern=true,label="",tag=""},
 extrautils2_jj_angelring={hasPattern=true,label="",tag=""},
 extrautils2_jj_angelring_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_angelring_jj_2={hasPattern=true,label="",tag=""},
 extrautils2_jj_angelring_jj_3={hasPattern=true,label="",tag=""},
 extrautils2_jj_angelring_jj_4={hasPattern=true,label="",tag=""},
 extrautils2_jj_angelring_jj_5={hasPattern=true,label="",tag=""},
 extrautils2_jj_bagofholding={hasPattern=true,label="",tag=""},
 extrautils2_jj_biomemarker={hasPattern=true,label="",tag=""},
 extrautils2_jj_biomemarker_b_202={hasPattern=true,label="",tag="({Biome: advancedrocketry:alien forest})"},
 extrautils2_jj_biomemarker_b_203={hasPattern=true,label="",tag="({Biome: advancedrocketry:crystalchasms})"},
 extrautils2_jj_biomemarker_b_204={hasPattern=true,label="",tag="({Biome: advancedrocketry:deepswamp})"},
 extrautils2_jj_biomemarker_b_205={hasPattern=true,label="",tag="({Biome: advancedrocketry:hotdryrock})"},
 extrautils2_jj_biomemarker_b_206={hasPattern=true,label="",tag="({Biome: advancedrocketry:marsh})"},
 extrautils2_jj_biomemarker_b_207={hasPattern=true,label="",tag="({Biome: advancedrocketry:moon})"},
 extrautils2_jj_biomemarker_b_208={hasPattern=true,label="",tag="({Biome: advancedrocketry:moondark})"},
 extrautils2_jj_biomemarker_b_209={hasPattern=true,label="",tag="({Biome: advancedrocketry:oceanspires})"},
 extrautils2_jj_biomemarker_b_210={hasPattern=true,label="",tag="({Biome: advancedrocketry:space})"},
 extrautils2_jj_biomemarker_b_211={hasPattern=true,label="",tag="({Biome: advancedrocketry:stormland})"},
 extrautils2_jj_biomemarker_b_212={hasPattern=true,label="",tag="({Biome: aether_legacy:aether_highlands})"},
 extrautils2_jj_biomemarker_b_213={hasPattern=true,label="",tag="({Biome: appliedenergistics2:storage_biome})"},
 extrautils2_jj_biomemarker_b_214={hasPattern=true,label="",tag="({Biome: biomesoplenty:alps})"},
 extrautils2_jj_biomemarker_b_215={hasPattern=true,label="",tag="({Biome: biomesoplenty:alps_foothills})"},
 extrautils2_jj_biomemarker_b_216={hasPattern=true,label="",tag="({Biome: biomesoplenty:bamboo_forest})"},
 extrautils2_jj_biomemarker_b_217={hasPattern=true,label="",tag="({Biome: biomesoplenty:bayou})"},
 extrautils2_jj_biomemarker_b_218={hasPattern=true,label="",tag="({Biome: biomesoplenty:bog})"},
 extrautils2_jj_biomemarker_b_219={hasPattern=true,label="",tag="({Biome: biomesoplenty:boreal_forest})"},
 extrautils2_jj_biomemarker_b_220={hasPattern=true,label="",tag="({Biome: biomesoplenty:brushland})"},
 extrautils2_jj_biomemarker_b_221={hasPattern=true,label="",tag="({Biome: biomesoplenty:chaparral})"},
 extrautils2_jj_biomemarker_b_222={hasPattern=true,label="",tag="({Biome: biomesoplenty:cherry_blossom_grove})"},
 extrautils2_jj_biomemarker_b_223={hasPattern=true,label="",tag="({Biome: biomesoplenty:cold_desert})"},
 extrautils2_jj_biomemarker_b_224={hasPattern=true,label="",tag="({Biome: biomesoplenty:coniferous_forest})"},
 extrautils2_jj_biomemarker_b_225={hasPattern=true,label="",tag="({Biome: biomesoplenty:coral_reef})"},
 extrautils2_jj_biomemarker_b_226={hasPattern=true,label="",tag="({Biome: biomesoplenty:corrupted_sands})"},
 extrautils2_jj_biomemarker_b_227={hasPattern=true,label="",tag="({Biome: biomesoplenty:crag})"},
 extrautils2_jj_biomemarker_b_228={hasPattern=true,label="",tag="({Biome: biomesoplenty:dead_forest})"},
 extrautils2_jj_biomemarker_b_229={hasPattern=true,label="",tag="({Biome: biomesoplenty:dead_swamp})"},
 extrautils2_jj_biomemarker_b_230={hasPattern=true,label="",tag="({Biome: biomesoplenty:eucalyptus_forest})"},
 extrautils2_jj_biomemarker_b_231={hasPattern=true,label="",tag="({Biome: biomesoplenty:fen})"},
 extrautils2_jj_biomemarker_b_232={hasPattern=true,label="",tag="({Biome: biomesoplenty:flower_field})"},
 extrautils2_jj_biomemarker_b_233={hasPattern=true,label="",tag="({Biome: biomesoplenty:flower_island})"},
 extrautils2_jj_biomemarker_b_234={hasPattern=true,label="",tag="({Biome: biomesoplenty:fungi_forest})"},
 extrautils2_jj_biomemarker_b_235={hasPattern=true,label="",tag="({Biome: biomesoplenty:glacier})"},
 extrautils2_jj_biomemarker_b_236={hasPattern=true,label="",tag="({Biome: biomesoplenty:grassland})"},
 extrautils2_jj_biomemarker_b_237={hasPattern=true,label="",tag="({Biome: biomesoplenty:gravel_beach})"},
 extrautils2_jj_biomemarker_b_238={hasPattern=true,label="",tag="({Biome: biomesoplenty:grove})"},
 extrautils2_jj_biomemarker_b_239={hasPattern=true,label="",tag="({Biome: biomesoplenty:highland})"},
 extrautils2_jj_biomemarker_b_240={hasPattern=true,label="",tag="({Biome: biomesoplenty:kelp_forest})"},
 extrautils2_jj_biomemarker_b_241={hasPattern=true,label="",tag="({Biome: biomesoplenty:land_of_lakes})"},
 extrautils2_jj_biomemarker_b_242={hasPattern=true,label="",tag="({Biome: biomesoplenty:lavender_fields})"},
 extrautils2_jj_biomemarker_b_243={hasPattern=true,label="",tag="({Biome: biomesoplenty:lush_desert})"},
 extrautils2_jj_biomemarker_b_244={hasPattern=true,label="",tag="({Biome: biomesoplenty:lush_swamp})"},
 extrautils2_jj_biomemarker_b_245={hasPattern=true,label="",tag="({Biome: biomesoplenty:mangrove})"},
 extrautils2_jj_biomemarker_b_246={hasPattern=true,label="",tag="({Biome: biomesoplenty:maple_woods})"},
 extrautils2_jj_biomemarker_b_247={hasPattern=true,label="",tag="({Biome: biomesoplenty:marsh})"},
 extrautils2_jj_biomemarker_b_248={hasPattern=true,label="",tag="({Biome: biomesoplenty:meadow})"},
 extrautils2_jj_biomemarker_b_249={hasPattern=true,label="",tag="({Biome: biomesoplenty:moor})"},
 extrautils2_jj_biomemarker_b_250={hasPattern=true,label="",tag="({Biome: biomesoplenty:mountain})"},
 extrautils2_jj_biomemarker_b_251={hasPattern=true,label="",tag="({Biome: biomesoplenty:mountain_foothills})"},
 extrautils2_jj_biomemarker_b_252={hasPattern=true,label="",tag="({Biome: biomesoplenty:mystic_grove})"},
 extrautils2_jj_biomemarker_b_253={hasPattern=true,label="",tag="({Biome: biomesoplenty:oasis})"},
 extrautils2_jj_biomemarker_b_254={hasPattern=true,label="",tag="({Biome: biomesoplenty:ominous_woods})"},
 extrautils2_jj_biomemarker_b_255={hasPattern=true,label="",tag="({Biome: biomesoplenty:orchard})"},
 extrautils2_jj_biomemarker_b_256={hasPattern=true,label="",tag="({Biome: biomesoplenty:origin_beach})"},
 extrautils2_jj_biomemarker_b_257={hasPattern=true,label="",tag="({Biome: biomesoplenty:origin_island})"},
 extrautils2_jj_biomemarker_b_258={hasPattern=true,label="",tag="({Biome: biomesoplenty:outback})"},
 extrautils2_jj_biomemarker_b_259={hasPattern=true,label="",tag="({Biome: biomesoplenty:overgrown_cliffs})"},
 extrautils2_jj_biomemarker_b_260={hasPattern=true,label="",tag="({Biome: biomesoplenty:pasture})"},
 extrautils2_jj_biomemarker_b_261={hasPattern=true,label="",tag="({Biome: biomesoplenty:phantasmagoric_inferno})"},
 extrautils2_jj_biomemarker_b_262={hasPattern=true,label="",tag="({Biome: biomesoplenty:prairie})"},
 extrautils2_jj_biomemarker_b_263={hasPattern=true,label="",tag="({Biome: biomesoplenty:quagmire})"},
 extrautils2_jj_biomemarker_b_264={hasPattern=true,label="",tag="({Biome: biomesoplenty:rainforest})"},
 extrautils2_jj_biomemarker_b_265={hasPattern=true,label="",tag="({Biome: biomesoplenty:redwood_forest})"},
 extrautils2_jj_biomemarker_b_266={hasPattern=true,label="",tag="({Biome: biomesoplenty:redwood_forest_edge})"},
 extrautils2_jj_biomemarker_b_267={hasPattern=true,label="",tag="({Biome: biomesoplenty:sacred_springs})"},
 extrautils2_jj_biomemarker_b_268={hasPattern=true,label="",tag="({Biome: biomesoplenty:seasonal_forest})"},
 extrautils2_jj_biomemarker_b_269={hasPattern=true,label="",tag="({Biome: biomesoplenty:shield})"},
 extrautils2_jj_biomemarker_b_270={hasPattern=true,label="",tag="({Biome: biomesoplenty:shrubland})"},
 extrautils2_jj_biomemarker_b_271={hasPattern=true,label="",tag="({Biome: biomesoplenty:snowy_coniferous_forest})"},
 extrautils2_jj_biomemarker_b_272={hasPattern=true,label="",tag="({Biome: biomesoplenty:snowy_forest})"},
 extrautils2_jj_biomemarker_b_273={hasPattern=true,label="",tag="({Biome: biomesoplenty:snowy_tundra})"},
 extrautils2_jj_biomemarker_b_274={hasPattern=true,label="",tag="({Biome: biomesoplenty:steppe})"},
 extrautils2_jj_biomemarker_b_275={hasPattern=true,label="",tag="({Biome: biomesoplenty:temperate_rainforest})"},
 extrautils2_jj_biomemarker_b_276={hasPattern=true,label="",tag="({Biome: biomesoplenty:tropical_island})"},
 extrautils2_jj_biomemarker_b_277={hasPattern=true,label="",tag="({Biome: biomesoplenty:tropical_rainforest})"},
 extrautils2_jj_biomemarker_b_278={hasPattern=true,label="",tag="({Biome: biomesoplenty:tundra})"},
 extrautils2_jj_biomemarker_b_279={hasPattern=true,label="",tag="({Biome: biomesoplenty:undergarden})"},
 extrautils2_jj_biomemarker_b_280={hasPattern=true,label="",tag="({Biome: biomesoplenty:visceral_heap})"},
 extrautils2_jj_biomemarker_b_281={hasPattern=true,label="",tag="({Biome: biomesoplenty:volcanic_island})"},
 extrautils2_jj_biomemarker_b_282={hasPattern=true,label="",tag="({Biome: biomesoplenty:wasteland})"},
 extrautils2_jj_biomemarker_b_283={hasPattern=true,label="",tag="({Biome: biomesoplenty:wetland})"},
 extrautils2_jj_biomemarker_b_284={hasPattern=true,label="",tag="({Biome: biomesoplenty:white_beach})"},
 extrautils2_jj_biomemarker_b_285={hasPattern=true,label="",tag="({Biome: biomesoplenty:woodland})"},
 extrautils2_jj_biomemarker_b_286={hasPattern=true,label="",tag="({Biome: biomesoplenty:xeric_shrubland})"},
 extrautils2_jj_biomemarker_b_287={hasPattern=true,label="",tag="({Biome: buildcraftenergy:oil_desert})"},
 extrautils2_jj_biomemarker_b_288={hasPattern=true,label="",tag="({Biome: buildcraftenergy:oil_ocean})"},
 extrautils2_jj_biomemarker_b_289={hasPattern=true,label="",tag="({Biome: conquest:alder_swamp})"},
 extrautils2_jj_biomemarker_b_290={hasPattern=true,label="",tag="({Biome: conquest:bamboo_forest})"},
 extrautils2_jj_biomemarker_b_291={hasPattern=true,label="",tag="({Biome: conquest:beach_mod})"},
 extrautils2_jj_biomemarker_b_292={hasPattern=true,label="",tag="({Biome: conquest:birch_forest})"},
 extrautils2_jj_biomemarker_b_293={hasPattern=true,label="",tag="({Biome: conquest:bog})"},
 extrautils2_jj_biomemarker_b_294={hasPattern=true,label="",tag="({Biome: conquest:boreal_forest})"},
 extrautils2_jj_biomemarker_b_295={hasPattern=true,label="",tag="({Biome: conquest:cold_beach_mod})"},
 extrautils2_jj_biomemarker_b_296={hasPattern=true,label="",tag="({Biome: conquest:deciduous_forest})"},
 extrautils2_jj_biomemarker_b_297={hasPattern=true,label="",tag="({Biome: conquest:desert_mod})"},
 extrautils2_jj_biomemarker_b_298={hasPattern=true,label="",tag="({Biome: conquest:forest_flower_plain})"},
 extrautils2_jj_biomemarker_b_299={hasPattern=true,label="",tag="({Biome: conquest:japanese_forest})"},
 extrautils2_jj_biomemarker_b_300={hasPattern=true,label="",tag="({Biome: conquest:jungle_mod})"},
 extrautils2_jj_biomemarker_b_301={hasPattern=true,label="",tag="({Biome: conquest:lorein_forest})"},
 extrautils2_jj_biomemarker_b_302={hasPattern=true,label="",tag="({Biome: conquest:marsh})"},
 extrautils2_jj_biomemarker_b_303={hasPattern=true,label="",tag="({Biome: conquest:mediterranean})"},
 extrautils2_jj_biomemarker_b_304={hasPattern=true,label="",tag="({Biome: conquest:mega_boreal_forest})"},
 extrautils2_jj_biomemarker_b_305={hasPattern=true,label="",tag="({Biome: conquest:mesa_extreme_mod})"},
 extrautils2_jj_biomemarker_b_306={hasPattern=true,label="",tag="({Biome: conquest:moorland})"},
 extrautils2_jj_biomemarker_b_307={hasPattern=true,label="",tag="({Biome: conquest:mountains})"},
 extrautils2_jj_biomemarker_b_308={hasPattern=true,label="",tag="({Biome: conquest:ocean})"},
 extrautils2_jj_biomemarker_b_309={hasPattern=true,label="",tag="({Biome: conquest:oldgrowth_forest})"},
 extrautils2_jj_biomemarker_b_310={hasPattern=true,label="",tag="({Biome: conquest:red_desert})"},
 extrautils2_jj_biomemarker_b_311={hasPattern=true,label="",tag="({Biome: conquest:river})"},
 extrautils2_jj_biomemarker_b_312={hasPattern=true,label="",tag="({Biome: conquest:tundra})"},
 extrautils2_jj_biomemarker_b_313={hasPattern=true,label="",tag="({Biome: conquest:tundra_marsh})"},
 extrautils2_jj_biomemarker_b_314={hasPattern=true,label="",tag="({Biome: defiledlands:desert_defiled})"},
 extrautils2_jj_biomemarker_b_315={hasPattern=true,label="",tag="({Biome: defiledlands:forest_tenebra})"},
 extrautils2_jj_biomemarker_b_316={hasPattern=true,label="",tag="({Biome: defiledlands:forest_vilespine})"},
 extrautils2_jj_biomemarker_b_317={hasPattern=true,label="",tag="({Biome: defiledlands:hills_defiled})"},
 extrautils2_jj_biomemarker_b_318={hasPattern=true,label="",tag="({Biome: defiledlands:ice_plains_defiled})"},
 extrautils2_jj_biomemarker_b_319={hasPattern=true,label="",tag="({Biome: defiledlands:plains_defiled})"},
 extrautils2_jj_biomemarker_b_320={hasPattern=true,label="",tag="({Biome: defiledlands:swamp_defiled})"},
 extrautils2_jj_biomemarker_b_321={hasPattern=true,label="",tag="({Biome: floricraft:rose land})"},
 extrautils2_jj_biomemarker_b_322={hasPattern=true,label="",tag="({Biome: floricraft:tulip land})"},
 extrautils2_jj_biomemarker_b_323={hasPattern=true,label="",tag="({Biome: fp:envia})"},
 extrautils2_jj_biomemarker_b_324={hasPattern=true,label="",tag="({Biome: fp:menelaus})"},
 extrautils2_jj_biomemarker_b_325={hasPattern=true,label="",tag="({Biome: fp:menelaus_flat})"},
 extrautils2_jj_biomemarker_b_326={hasPattern=true,label="",tag="({Biome: fp:menelaus_sea})"},
 extrautils2_jj_biomemarker_b_327={hasPattern=true,label="",tag="({Biome: fp:tyros})"},
 extrautils2_jj_biomemarker_b_328={hasPattern=true,label="",tag="({Biome: fp:tyros_mountain})"},
 extrautils2_jj_biomemarker_b_329={hasPattern=true,label="",tag="({Biome: fp:tyros_rockdesert})"},
 extrautils2_jj_biomemarker_b_330={hasPattern=true,label="",tag="({Biome: fp:tyros_rockdesertflat})"},
 extrautils2_jj_biomemarker_b_331={hasPattern=true,label="",tag="({Biome: fp:tyros_swamp})"},
 extrautils2_jj_biomemarker_b_332={hasPattern=true,label="",tag="({Biome: minecraft:beaches})"},
 extrautils2_jj_biomemarker_b_333={hasPattern=true,label="",tag="({Biome: minecraft:birch_forest})"},
 extrautils2_jj_biomemarker_b_334={hasPattern=true,label="",tag="({Biome: minecraft:birch_forest_hills})"},
 extrautils2_jj_biomemarker_b_335={hasPattern=true,label="",tag="({Biome: minecraft:cold_beach})"},
 extrautils2_jj_biomemarker_b_336={hasPattern=true,label="",tag="({Biome: minecraft:deep_ocean})"},
 extrautils2_jj_biomemarker_b_337={hasPattern=true,label="",tag="({Biome: minecraft:desert})"},
 extrautils2_jj_biomemarker_b_338={hasPattern=true,label="",tag="({Biome: minecraft:desert_hills})"},
 extrautils2_jj_biomemarker_b_339={hasPattern=true,label="",tag="({Biome: minecraft:extreme_hills})"},
 extrautils2_jj_biomemarker_b_340={hasPattern=true,label="",tag="({Biome: minecraft:extreme_hills_with_trees})"},
 extrautils2_jj_biomemarker_b_341={hasPattern=true,label="",tag="({Biome: minecraft:forest})"},
 extrautils2_jj_biomemarker_b_342={hasPattern=true,label="",tag="({Biome: minecraft:forest_hills})"},
 extrautils2_jj_biomemarker_b_343={hasPattern=true,label="",tag="({Biome: minecraft:frozen_ocean})"},
 extrautils2_jj_biomemarker_b_344={hasPattern=true,label="",tag="({Biome: minecraft:frozen_river})"},
 extrautils2_jj_biomemarker_b_345={hasPattern=true,label="",tag="({Biome: minecraft:hell})"},
 extrautils2_jj_biomemarker_b_346={hasPattern=true,label="",tag="({Biome: minecraft:ice_flats})"},
 extrautils2_jj_biomemarker_b_347={hasPattern=true,label="",tag="({Biome: minecraft:ice_mountains})"},
 extrautils2_jj_biomemarker_b_348={hasPattern=true,label="",tag="({Biome: minecraft:jungle})"},
 extrautils2_jj_biomemarker_b_349={hasPattern=true,label="",tag="({Biome: minecraft:jungle_edge})"},
 extrautils2_jj_biomemarker_b_350={hasPattern=true,label="",tag="({Biome: minecraft:jungle_hills})"},
 extrautils2_jj_biomemarker_b_351={hasPattern=true,label="",tag="({Biome: minecraft:mesa})"},
 extrautils2_jj_biomemarker_b_352={hasPattern=true,label="",tag="({Biome: minecraft:mesa_clear_rock})"},
 extrautils2_jj_biomemarker_b_353={hasPattern=true,label="",tag="({Biome: minecraft:mesa_rock})"},
 extrautils2_jj_biomemarker_b_354={hasPattern=true,label="",tag="({Biome: minecraft:mushroom_island})"},
 extrautils2_jj_biomemarker_b_355={hasPattern=true,label="",tag="({Biome: minecraft:mushroom_island_shore})"},
 extrautils2_jj_biomemarker_b_356={hasPattern=true,label="",tag="({Biome: minecraft:mutated_birch_forest})"},
 extrautils2_jj_biomemarker_b_357={hasPattern=true,label="",tag="({Biome: minecraft:mutated_birch_forest_hills})"},
 extrautils2_jj_biomemarker_b_358={hasPattern=true,label="",tag="({Biome: minecraft:mutated_desert})"},
 extrautils2_jj_biomemarker_b_359={hasPattern=true,label="",tag="({Biome: minecraft:mutated_extreme_hills})"},
 extrautils2_jj_biomemarker_b_360={hasPattern=true,label="",tag="({Biome: minecraft:mutated_extreme_hills_with_trees})"},
 extrautils2_jj_biomemarker_b_361={hasPattern=true,label="",tag="({Biome: minecraft:mutated_forest})"},
 extrautils2_jj_biomemarker_b_362={hasPattern=true,label="",tag="({Biome: minecraft:mutated_ice_flats})"},
 extrautils2_jj_biomemarker_b_363={hasPattern=true,label="",tag="({Biome: minecraft:mutated_jungle})"},
 extrautils2_jj_biomemarker_b_364={hasPattern=true,label="",tag="({Biome: minecraft:mutated_jungle_edge})"},
 extrautils2_jj_biomemarker_b_365={hasPattern=true,label="",tag="({Biome: minecraft:mutated_mesa})"},
 extrautils2_jj_biomemarker_b_366={hasPattern=true,label="",tag="({Biome: minecraft:mutated_mesa_clear_rock})"},
 extrautils2_jj_biomemarker_b_367={hasPattern=true,label="",tag="({Biome: minecraft:mutated_mesa_rock})"},
 extrautils2_jj_biomemarker_b_368={hasPattern=true,label="",tag="({Biome: minecraft:mutated_redwood_taiga})"},
 extrautils2_jj_biomemarker_b_369={hasPattern=true,label="",tag="({Biome: minecraft:mutated_redwood_taiga_hills})"},
 extrautils2_jj_biomemarker_b_370={hasPattern=true,label="",tag="({Biome: minecraft:mutated_roofed_forest})"},
 extrautils2_jj_biomemarker_b_371={hasPattern=true,label="",tag="({Biome: minecraft:mutated_savanna})"},
 extrautils2_jj_biomemarker_b_372={hasPattern=true,label="",tag="({Biome: minecraft:mutated_savanna_rock})"},
 extrautils2_jj_biomemarker_b_373={hasPattern=true,label="",tag="({Biome: minecraft:mutated_swampland})"},
 extrautils2_jj_biomemarker_b_374={hasPattern=true,label="",tag="({Biome: minecraft:mutated_taiga})"},
 extrautils2_jj_biomemarker_b_375={hasPattern=true,label="",tag="({Biome: minecraft:mutated_taiga_cold})"},
 extrautils2_jj_biomemarker_b_376={hasPattern=true,label="",tag="({Biome: minecraft:ocean})"},
 extrautils2_jj_biomemarker_b_377={hasPattern=true,label="",tag="({Biome: minecraft:plains})"},
 extrautils2_jj_biomemarker_b_378={hasPattern=true,label="",tag="({Biome: minecraft:redwood_taiga})"},
 extrautils2_jj_biomemarker_b_379={hasPattern=true,label="",tag="({Biome: minecraft:redwood_taiga_hills})"},
 extrautils2_jj_biomemarker_b_380={hasPattern=true,label="",tag="({Biome: minecraft:river})"},
 extrautils2_jj_biomemarker_b_381={hasPattern=true,label="",tag="({Biome: minecraft:roofed_forest})"},
 extrautils2_jj_biomemarker_b_382={hasPattern=true,label="",tag="({Biome: minecraft:savanna})"},
 extrautils2_jj_biomemarker_b_383={hasPattern=true,label="",tag="({Biome: minecraft:savanna_rock})"},
 extrautils2_jj_biomemarker_b_384={hasPattern=true,label="",tag="({Biome: minecraft:sky})"},
 extrautils2_jj_biomemarker_b_385={hasPattern=true,label="",tag="({Biome: minecraft:smaller_extreme_hills})"},
 extrautils2_jj_biomemarker_b_386={hasPattern=true,label="",tag="({Biome: minecraft:stone_beach})"},
 extrautils2_jj_biomemarker_b_387={hasPattern=true,label="",tag="({Biome: minecraft:swampland})"},
 extrautils2_jj_biomemarker_b_388={hasPattern=true,label="",tag="({Biome: minecraft:taiga})"},
 extrautils2_jj_biomemarker_b_389={hasPattern=true,label="",tag="({Biome: minecraft:taiga_cold})"},
 extrautils2_jj_biomemarker_b_390={hasPattern=true,label="",tag="({Biome: minecraft:taiga_cold_hills})"},
 extrautils2_jj_biomemarker_b_391={hasPattern=true,label="",tag="({Biome: minecraft:taiga_hills})"},
 extrautils2_jj_biomemarker_b_392={hasPattern=true,label="",tag="({Biome: minecraft:void})"},
 extrautils2_jj_biomemarker_b_393={hasPattern=true,label="",tag="({Biome: nuclearcraft:nuclear_wasteland})"},
 extrautils2_jj_biomemarker_b_394={hasPattern=true,label="",tag="({Biome: plants2:crystal_forest})"},
 extrautils2_jj_biomemarker_b_395={hasPattern=true,label="",tag="({Biome: steamworld:blazing withers})"},
 extrautils2_jj_biomemarker_b_396={hasPattern=true,label="",tag="({Biome: steamworld:floating wetlands})"},
 extrautils2_jj_biomemarker_b_397={hasPattern=true,label="",tag="({Biome: steamworld:forest island})"},
 extrautils2_jj_biomemarker_b_398={hasPattern=true,label="",tag="({Biome: steamworld:forgotten sky})"},
 extrautils2_jj_biomemarker_b_399={hasPattern=true,label="",tag="({Biome: steamworld:highland island})"},
 extrautils2_jj_biomemarker_b_400={hasPattern=true,label="",tag="({Biome: steamworld:nature island})"},
 extrautils2_jj_biomemarker_b_401={hasPattern=true,label="",tag="({Biome: steamworld:snow highland island})"},
 extrautils2_jj_biomemarker_b_402={hasPattern=true,label="",tag="({Biome: thaumcraft:eerie})"},
 extrautils2_jj_biomemarker_b_403={hasPattern=true,label="",tag="({Biome: thaumcraft:eldritch})"},
 extrautils2_jj_biomemarker_b_404={hasPattern=true,label="",tag="({Biome: thaumcraft:magical_forest})"},
 extrautils2_jj_biomemarker_b_405={hasPattern=true,label="",tag="({Biome: twilightforest:dark_forest})"},
 extrautils2_jj_biomemarker_b_406={hasPattern=true,label="",tag="({Biome: twilightforest:dark_forest_center})"},
 extrautils2_jj_biomemarker_b_407={hasPattern=true,label="",tag="({Biome: twilightforest:deep_mushroom_forest})"},
 extrautils2_jj_biomemarker_b_408={hasPattern=true,label="",tag="({Biome: twilightforest:dense_twilight_forest})"},
 extrautils2_jj_biomemarker_b_409={hasPattern=true,label="",tag="({Biome: twilightforest:enchanted_forest})"},
 extrautils2_jj_biomemarker_b_410={hasPattern=true,label="",tag="({Biome: twilightforest:fire_swamp})"},
 extrautils2_jj_biomemarker_b_411={hasPattern=true,label="",tag="({Biome: twilightforest:firefly_forest})"},
 extrautils2_jj_biomemarker_b_412={hasPattern=true,label="",tag="({Biome: twilightforest:highlands_center})"},
 extrautils2_jj_biomemarker_b_413={hasPattern=true,label="",tag="({Biome: twilightforest:mushroom_forest})"},
 extrautils2_jj_biomemarker_b_414={hasPattern=true,label="",tag="({Biome: twilightforest:oak_savannah})"},
 extrautils2_jj_biomemarker_b_415={hasPattern=true,label="",tag="({Biome: twilightforest:snowy_forest})"},
 extrautils2_jj_biomemarker_b_416={hasPattern=true,label="",tag="({Biome: twilightforest:thornlands})"},
 extrautils2_jj_biomemarker_b_417={hasPattern=true,label="",tag="({Biome: twilightforest:twilight_clearing})"},
 extrautils2_jj_biomemarker_b_418={hasPattern=true,label="",tag="({Biome: twilightforest:twilight_forest})"},
 extrautils2_jj_biomemarker_b_419={hasPattern=true,label="",tag="({Biome: twilightforest:twilight_glacier})"},
 extrautils2_jj_biomemarker_b_420={hasPattern=true,label="",tag="({Biome: twilightforest:twilight_highlands})"},
 extrautils2_jj_biomemarker_b_421={hasPattern=true,label="",tag="({Biome: twilightforest:twilight_lake})"},
 extrautils2_jj_biomemarker_b_422={hasPattern=true,label="",tag="({Biome: twilightforest:twilight_stream})"},
 extrautils2_jj_biomemarker_b_423={hasPattern=true,label="",tag="({Biome: twilightforest:twilight_swamp})"},
 extrautils2_jj_book={hasPattern=true,label="",tag=""},
 extrautils2_jj_boomerang={hasPattern=true,label="",tag=""},
 extrautils2_jj_chickenring={hasPattern=true,label="",tag=""},
 extrautils2_jj_chickenring_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_chunkloader={hasPattern=true,label="",tag=""},
 extrautils2_jj_compoundbow={hasPattern=true,label="",tag=""},
 extrautils2_jj_compressedcobblestone={hasPattern=true,label="",tag=""},
 extrautils2_jj_compressedcobblestone_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_compressedcobblestone_jj_2={hasPattern=true,label="",tag=""},
 extrautils2_jj_compressedcobblestone_jj_3={hasPattern=true,label="",tag=""},
 extrautils2_jj_compressedcobblestone_jj_4={hasPattern=true,label="",tag=""},
 extrautils2_jj_compressedcobblestone_jj_5={hasPattern=true,label="",tag=""},
 extrautils2_jj_compressedcobblestone_jj_6={hasPattern=true,label="",tag=""},
 extrautils2_jj_compressedcobblestone_jj_7={hasPattern=true,label="",tag=""},
 extrautils2_jj_compresseddirt={hasPattern=true,label="",tag=""},
 extrautils2_jj_compresseddirt_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_compresseddirt_jj_2={hasPattern=true,label="",tag=""},
 extrautils2_jj_compresseddirt_jj_3={hasPattern=true,label="",tag=""},
 extrautils2_jj_compressedgravel={hasPattern=true,label="",tag=""},
 extrautils2_jj_compressedgravel_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_compressednetherrack={hasPattern=true,label="",tag=""},
 extrautils2_jj_compressednetherrack_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_compressednetherrack_jj_2={hasPattern=true,label="",tag=""},
 extrautils2_jj_compressednetherrack_jj_3={hasPattern=true,label="",tag=""},
 extrautils2_jj_compressednetherrack_jj_4={hasPattern=true,label="",tag=""},
 extrautils2_jj_compressednetherrack_jj_5={hasPattern=true,label="",tag=""},
 extrautils2_jj_compressedsand={hasPattern=true,label="",tag=""},
 extrautils2_jj_compressedsand_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_contract={hasPattern=true,label="",tag=""},
 extrautils2_jj_crafter={hasPattern=true,label="",tag=""},
 extrautils2_jj_creativechest={hasPattern=false,label="",tag=""},
 extrautils2_jj_creativeenergy={hasPattern=false,label="",tag=""},
 extrautils2_jj_creativeharvest={hasPattern=false,label="",tag=""},
 extrautils2_jj_cursedearth={hasPattern=false,label="",tag=""},
 extrautils2_jj_decorativebedrock={hasPattern=false,label="",tag=""},
 extrautils2_jj_decorativebedrock_jj_1={hasPattern=false,label="",tag=""},
 extrautils2_jj_decorativebedrock_jj_2={hasPattern=false,label="",tag=""},
 extrautils2_jj_decorativeglass={hasPattern=true,label="",tag=""},
 extrautils2_jj_decorativeglass_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_decorativeglass_jj_2={hasPattern=true,label="",tag=""},
 extrautils2_jj_decorativeglass_jj_3={hasPattern=true,label="",tag=""},
 extrautils2_jj_decorativeglass_jj_4={hasPattern=true,label="",tag=""},
 extrautils2_jj_decorativeglass_jj_5={hasPattern=true,label="",tag=""},
 extrautils2_jj_decorativesolid={hasPattern=true,label="",tag=""},
 extrautils2_jj_decorativesolid_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_decorativesolid_jj_2={hasPattern=true,label="",tag=""},
 extrautils2_jj_decorativesolid_jj_3={hasPattern=true,label="",tag=""},
 extrautils2_jj_decorativesolid_jj_4={hasPattern=true,label="",tag=""},
 extrautils2_jj_decorativesolid_jj_5={hasPattern=true,label="",tag=""},
 extrautils2_jj_decorativesolid_jj_6={hasPattern=true,label="",tag=""},
 extrautils2_jj_decorativesolid_jj_7={hasPattern=true,label="",tag=""},
 extrautils2_jj_decorativesolid_jj_8={hasPattern=true,label="",tag=""},
 extrautils2_jj_decorativesolidwood={hasPattern=true,label="",tag=""},
 extrautils2_jj_decorativesolidwood_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_decorativesolidwood_jj_2={hasPattern=true,label="",tag=""},
 extrautils2_jj_drum={hasPattern=true,label="",tag=""},
 extrautils2_jj_drum_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_drum_jj_2={hasPattern=true,label="",tag=""},
 extrautils2_jj_drum_jj_3={hasPattern=true,label="",tag=""},
 extrautils2_jj_drum_jj_4={hasPattern=false,label="",tag=""},
 extrautils2_jj_enderlilly={hasPattern=false,label="",tag=""},
 extrautils2_jj_endershard={hasPattern=true,label="",tag=""},
 extrautils2_jj_fakecopy={hasPattern=false,label="",tag=""},
 extrautils2_jj_filter={hasPattern=true,label="",tag=""},
 extrautils2_jj_filterfluids={hasPattern=true,label="",tag=""},
 extrautils2_jj_fireaxe={hasPattern=true,label="",tag=""},
 extrautils2_jj_flattransfernode={hasPattern=true,label="",tag=""},
 extrautils2_jj_flattransfernode_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_glasscutter={hasPattern=true,label="",tag=""},
 extrautils2_jj_goldenlasso={hasPattern=false,label="",tag=""},
 extrautils2_jj_goldenlasso_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_grocket={hasPattern=true,label="",tag=""},
 extrautils2_jj_grocket_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_grocket_jj_2={hasPattern=true,label="",tag=""},
 extrautils2_jj_grocket_jj_3={hasPattern=true,label="",tag=""},
 extrautils2_jj_grocket_jj_4={hasPattern=true,label="",tag=""},
 extrautils2_jj_grocket_jj_5={hasPattern=true,label="",tag=""},
 extrautils2_jj_grocket_jj_6={hasPattern=true,label="",tag=""},
 extrautils2_jj_indexer={hasPattern=true,label="",tag=""},
 extrautils2_jj_indexerremote={hasPattern=true,label="",tag=""},
 extrautils2_jj_ineffableglass={hasPattern=true,label="",tag=""},
 extrautils2_jj_ineffableglass_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_ineffableglass_jj_2={hasPattern=true,label="",tag=""},
 extrautils2_jj_ineffableglass_jj_3={hasPattern=true,label="",tag=""},
 extrautils2_jj_ingredients={hasPattern=true,label="",tag=""},
 extrautils2_jj_ingredients_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_ingredients_jj_10={hasPattern=false,label="",tag=""},
 extrautils2_jj_ingredients_jj_11={hasPattern=true,label="",tag=""},
 extrautils2_jj_ingredients_jj_12={hasPattern=true,label="",tag=""},
 extrautils2_jj_ingredients_jj_13={hasPattern=true,label="",tag=""},
 extrautils2_jj_ingredients_jj_14={hasPattern=false,label="",tag=""},
 extrautils2_jj_ingredients_jj_15={hasPattern=true,label="",tag=""},
 extrautils2_jj_ingredients_jj_16={hasPattern=true,label="",tag=""},
 extrautils2_jj_ingredients_jj_17={hasPattern=true,label="",tag=""},
 extrautils2_jj_ingredients_jj_2={hasPattern=true,label="",tag=""},
 extrautils2_jj_ingredients_jj_3={hasPattern=true,label="",tag=""},
 extrautils2_jj_ingredients_jj_4={hasPattern=true,label="",tag=""},
 extrautils2_jj_ingredients_jj_5={hasPattern=true,label="",tag=""},
 extrautils2_jj_ingredients_jj_6={hasPattern=true,label="",tag=""},
 extrautils2_jj_ingredients_jj_7={hasPattern=true,label="",tag=""},
 extrautils2_jj_ingredients_jj_8={hasPattern=true,label="",tag=""},
 extrautils2_jj_ingredients_jj_9={hasPattern=true,label="",tag=""},
 extrautils2_jj_interactionproxy={hasPattern=true,label="",tag=""},
 extrautils2_jj_ironwood_leaves={hasPattern=true,label="",tag=""},
 extrautils2_jj_ironwood_leaves_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_ironwood_log={hasPattern=true,label="",tag=""},
 extrautils2_jj_ironwood_log_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_ironwood_planks={hasPattern=true,label="",tag=""},
 extrautils2_jj_ironwood_planks_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_ironwood_sapling={hasPattern=true,label="",tag=""},
 extrautils2_jj_ironwood_sapling_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_itembuilderswand={hasPattern=true,label="",tag=""},
 extrautils2_jj_itemcreativebuilderswand={hasPattern=false,label="",tag=""},
 extrautils2_jj_itemcreativedestructionwand={hasPattern=false,label="",tag=""},
 extrautils2_jj_itemdestructionwand={hasPattern=true,label="",tag=""},
 extrautils2_jj_klein={hasPattern=true,label="",tag=""},
 extrautils2_jj_largishchest={hasPattern=true,label="",tag=""},
 extrautils2_jj_lawsword={hasPattern=true,label="",tag=""},
 extrautils2_jj_luxsaber={hasPattern=true,label="",tag=""},
 extrautils2_jj_luxsaber_b_1={hasPattern=true,label="",tag="({Energy: 40000})"},
 extrautils2_jj_luxsaber_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_luxsaber_jj_1_b_1={hasPattern=true,label="",tag="({Energy: 40000})"},
 extrautils2_jj_luxsaber_jj_2={hasPattern=true,label="",tag=""},
 extrautils2_jj_luxsaber_jj_2_b_1={hasPattern=true,label="",tag="({Energy: 40000})"},
 extrautils2_jj_luxsaber_jj_3={hasPattern=true,label="",tag=""},
 extrautils2_jj_luxsaber_jj_3_b_1={hasPattern=true,label="",tag="({Energy: 40000})"},
 extrautils2_jj_luxsaber_jj_4={hasPattern=true,label="",tag=""},
 extrautils2_jj_luxsaber_jj_4_b_1={hasPattern=true,label="",tag="({Energy: 40000})"},
 extrautils2_jj_luxsaber_jj_5={hasPattern=true,label="",tag=""},
 extrautils2_jj_luxsaber_jj_5_b_1={hasPattern=true,label="",tag="({Energy: 40000})"},
 extrautils2_jj_luxsaber_jj_6={hasPattern=true,label="",tag=""},
 extrautils2_jj_luxsaber_jj_6_b_1={hasPattern=true,label="",tag="({Energy: 40000})"},
 extrautils2_jj_luxsaber_jj_7={hasPattern=true,label="",tag=""},
 extrautils2_jj_luxsaber_jj_7_b_1={hasPattern=true,label="",tag="({Energy: 40000})"},
 extrautils2_jj_machine={hasPattern=true,label="",tag=""},
 extrautils2_jj_machine_b_20={hasPattern=true,label="",tag="({Type: extrautils2:crusher})"},
 extrautils2_jj_machine_b_21={hasPattern=true,label="",tag="({Type: extrautils2:enchanter})"},
 extrautils2_jj_machine_b_22={hasPattern=true,label="",tag="({Type: extrautils2:furnace})"},
 extrautils2_jj_machine_b_23={hasPattern=true,label="",tag="({Type: extrautils2:generator})"},
 extrautils2_jj_machine_b_24={hasPattern=true,label="",tag="({Type: extrautils2:generator_culinary})"},
 extrautils2_jj_machine_b_25={hasPattern=true,label="",tag="({Type: extrautils2:generator_death})"},
 extrautils2_jj_machine_b_26={hasPattern=true,label="",tag="({Type: extrautils2:generator_dragonsbreath})"},
 extrautils2_jj_machine_b_27={hasPattern=true,label="",tag="({Type: extrautils2:generator_enchant})"},
 extrautils2_jj_machine_b_28={hasPattern=true,label="",tag="({Type: extrautils2:generator_ender})"},
 extrautils2_jj_machine_b_29={hasPattern=true,label="",tag="({Type: extrautils2:generator_ice})"},
 extrautils2_jj_machine_b_30={hasPattern=true,label="",tag="({Type: extrautils2:generator_lava})"},
 extrautils2_jj_machine_b_31={hasPattern=true,label="",tag="({Type: extrautils2:generator_netherstar})"},
 extrautils2_jj_machine_b_32={hasPattern=true,label="",tag="({Type: extrautils2:generator_overclock})"},
 extrautils2_jj_machine_b_33={hasPattern=true,label="",tag="({Type: extrautils2:generator_pink})"},
 extrautils2_jj_machine_b_34={hasPattern=true,label="",tag="({Type: extrautils2:generator_potion})"},
 extrautils2_jj_machine_b_35={hasPattern=true,label="",tag="({Type: extrautils2:generator_redstone})"},
 extrautils2_jj_machine_b_36={hasPattern=true,label="",tag="({Type: extrautils2:generator_slime})"},
 extrautils2_jj_machine_b_37={hasPattern=true,label="",tag="({Type: extrautils2:generator_survival})"},
 extrautils2_jj_machine_b_38={hasPattern=true,label="",tag="({Type: extrautils2:generator_tnt})"},
 extrautils2_jj_magicapple={hasPattern=true,label="",tag=""},
 extrautils2_jj_miner={hasPattern=true,label="",tag=""},
 extrautils2_jj_minichest={hasPattern=true,label="",tag=""},
 extrautils2_jj_opinium={hasPattern=true,label="",tag=""},
 extrautils2_jj_opinium_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_opinium_jj_2={hasPattern=true,label="",tag=""},
 extrautils2_jj_opinium_jj_3={hasPattern=true,label="",tag=""},
 extrautils2_jj_opinium_jj_4={hasPattern=true,label="",tag=""},
 extrautils2_jj_opinium_jj_5={hasPattern=true,label="",tag=""},
 extrautils2_jj_opinium_jj_6={hasPattern=true,label="",tag=""},
 extrautils2_jj_opinium_jj_7={hasPattern=true,label="",tag=""},
 extrautils2_jj_opinium_jj_8={hasPattern=true,label="",tag=""},
 extrautils2_jj_passivegenerator={hasPattern=true,label="",tag=""},
 extrautils2_jj_passivegenerator_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_passivegenerator_jj_2={hasPattern=true,label="",tag=""},
 extrautils2_jj_passivegenerator_jj_3={hasPattern=true,label="",tag=""},
 extrautils2_jj_passivegenerator_jj_4={hasPattern=true,label="",tag=""},
 extrautils2_jj_passivegenerator_jj_5={hasPattern=true,label="",tag=""},
 extrautils2_jj_passivegenerator_jj_6={hasPattern=false,label="",tag=""},
 extrautils2_jj_passivegenerator_jj_7={hasPattern=true,label="",tag=""},
 extrautils2_jj_passivegenerator_jj_8={hasPattern=true,label="",tag=""},
 extrautils2_jj_pipe={hasPattern=true,label="",tag=""},
 extrautils2_jj_playerchest={hasPattern=true,label="",tag=""},
 extrautils2_jj_powerbattery={hasPattern=true,label="",tag=""},
 extrautils2_jj_powermanager={hasPattern=true,label="",tag=""},
 extrautils2_jj_poweroverload={hasPattern=true,label="",tag=""},
 extrautils2_jj_powertransmitter={hasPattern=true,label="",tag=""},
 extrautils2_jj_quarry={hasPattern=true,label="",tag=""},
 extrautils2_jj_quarryproxy={hasPattern=true,label="",tag=""},
 extrautils2_jj_rainbowgenerator={hasPattern=true,label="",tag=""},
 extrautils2_jj_rainbowgenerator_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_rainbowgenerator_jj_2={hasPattern=true,label="",tag=""},
 extrautils2_jj_redorchid={hasPattern=false,label="",tag=""},
 extrautils2_jj_redstoneclock={hasPattern=true,label="",tag=""},
 extrautils2_jj_redstonelantern={hasPattern=true,label="",tag=""},
 extrautils2_jj_resonator={hasPattern=true,label="",tag=""},
 extrautils2_jj_scanner={hasPattern=true,label="",tag=""},
 extrautils2_jj_screen={hasPattern=true,label="",tag=""},
 extrautils2_jj_sickle_diamond={hasPattern=true,label="",tag=""},
 extrautils2_jj_sickle_gold={hasPattern=true,label="",tag=""},
 extrautils2_jj_sickle_iron={hasPattern=true,label="",tag=""},
 extrautils2_jj_sickle_stone={hasPattern=true,label="",tag=""},
 extrautils2_jj_sickle_wood={hasPattern=true,label="",tag=""},
 extrautils2_jj_simpledecorative={hasPattern=true,label="",tag=""},
 extrautils2_jj_simpledecorative_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_simpledecorative_jj_2={hasPattern=true,label="",tag=""},
 extrautils2_jj_snowglobe={hasPattern=true,label="",tag=""},
 extrautils2_jj_snowglobe_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_soundmuffler={hasPattern=true,label="",tag=""},
 extrautils2_jj_spike_creative={hasPattern=false,label="",tag=""},
 extrautils2_jj_spike_diamond={hasPattern=true,label="",tag=""},
 extrautils2_jj_spike_gold={hasPattern=true,label="",tag=""},
 extrautils2_jj_spike_iron={hasPattern=true,label="",tag=""},
 extrautils2_jj_spike_stone={hasPattern=true,label="",tag=""},
 extrautils2_jj_spike_wood={hasPattern=true,label="",tag=""},
 extrautils2_jj_spotlight={hasPattern=false,label="",tag=""},
 extrautils2_jj_suncrystal={hasPattern=false,label="",tag=""},
 extrautils2_jj_suncrystal_jj_250={hasPattern=true,label="",tag=""},
 extrautils2_jj_supermobspawner={hasPattern=false,label="",tag=""},
 extrautils2_jj_teleporter={hasPattern=false,label="",tag=""},
 extrautils2_jj_teleporter_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_terraformer={hasPattern=true,label="",tag=""},
 extrautils2_jj_terraformer_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_terraformer_jj_2={hasPattern=true,label="",tag=""},
 extrautils2_jj_terraformer_jj_3={hasPattern=true,label="",tag=""},
 extrautils2_jj_terraformer_jj_4={hasPattern=true,label="",tag=""},
 extrautils2_jj_terraformer_jj_5={hasPattern=true,label="",tag=""},
 extrautils2_jj_terraformer_jj_6={hasPattern=true,label="",tag=""},
 extrautils2_jj_terraformer_jj_7={hasPattern=true,label="",tag=""},
 extrautils2_jj_terraformer_jj_8={hasPattern=true,label="",tag=""},
 extrautils2_jj_terraformer_jj_9={hasPattern=true,label="",tag=""},
 extrautils2_jj_trashcan={hasPattern=true,label="",tag=""},
 extrautils2_jj_trashcanenergy={hasPattern=true,label="",tag=""},
 extrautils2_jj_trashcanfluid={hasPattern=true,label="",tag=""},
 extrautils2_jj_trashchest={hasPattern=true,label="",tag=""},
 extrautils2_jj_trowel={hasPattern=true,label="",tag=""},
 extrautils2_jj_unstableingots={hasPattern=false,label="",tag=""},
 extrautils2_jj_unstableingots_jj_1={hasPattern=true,label="",tag=""},
 extrautils2_jj_unstableingots_jj_2={hasPattern=true,label="",tag=""},
 extrautils2_jj_user={hasPattern=true,label="",tag=""},
 extrautils2_jj_wateringcan={hasPattern=false,label="",tag=""},
 extrautils2_jj_wateringcan_jj_1000={hasPattern=true,label="",tag=""},
 extrautils2_jj_wrench={hasPattern=true,label="",tag=""}
 }