return {
actuallyadditions_jj_item_food=20,
actuallyadditions_jj_item_crystal=5,
actuallyadditions_jj_item_drill=15,
actuallyadditions_jj_item_crystal_shard=5,
actuallyadditions_jj_block_colored_lamp_on=15,
actuallyadditions_jj_block_crystal_empowered=5,
actuallyadditions_jj_item_dust=7,
actuallyadditions_jj_block_misc=9,
actuallyadditions_jj_block_colored_lamp=15,
actuallyadditions_jj_block_crystal=5,
actuallyadditions_jj_item_potion_ring_advanced=9,
actuallyadditions_jj_item_jam=6,
actuallyadditions_jj_item_misc=24,
actuallyadditions_jj_item_potion_ring=9,
actuallyadditions_jj_item_crystal_empowered=5
}