return {
advancedrocketry_jj_ic=5,
advancedrocketry_jj_crystal=5,
advancedrocketry_jj_loader=6,
advancedrocketry_jj_itemupgrade=4,
advancedrocketry_jj_pressuretank=3,
advancedrocketry_jj_satelliteprimaryfunction=5
}