local filesystem = require("filesystem")
if filesystem.exists("/home/Crafter/") == false then filesystem.makeDirectory("/home/Crafter/") end
if filesystem.exists("/home/Crafter/ItemsAll") == false then filesystem.makeDirectory("/home/Crafter/ItemsAll") end
if filesystem.exists("/mnt/58e/home/Crafter/") == false then filesystem.makeDirectory("/mnt/58e/home/Crafter/") end
if filesystem.exists("/mnt/58e/home/Crafter/ItemsAll") == false then filesystem.makeDirectory("/mnt/58e/home/Crafter/ItemsAll") end
if filesystem.exists("/mnt/caa/home/Crafter/") == false then filesystem.makeDirectory("/mnt/caa/home/Crafter/") end
if filesystem.exists("/mnt/caa/home/Crafter/ItemsAll") == false then filesystem.makeDirectory("/mnt/caa/home/Crafter/ItemsAll") end


os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/minecraft.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/minecraft.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/draconic.lua" .. "?" .. math.random() .. " /mnt/58e/home/Crafter/ItemsAll/draconic.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/conquest.lua" .. "?" .. math.random() .. " /mnt/caa/home/Crafter/ItemsAll/conquest.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/mekanism.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/mekanism.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/utilities.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/utilities.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/environ.lua" .. "?" .. math.random() .. " /mnt/58e/home/Crafter/ItemsAll/environ.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/storage.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/storage.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/nuclear.lua" .. "?" .. math.random() .. " /mnt/58e/home/Crafter/ItemsAll/nuclear.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/forestry.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/forestry.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/food.lua" .. "?" .. math.random() .. " /mnt/58e/home/Crafter/ItemsAll/food.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/immersive.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/immersive.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/railroading.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/railroading.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/others.lua" .. "?" .. math.random() .. " /mnt/58e/home/Crafter/ItemsAll/others.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/fiifex.lua" .. "?" .. math.random() .. " /mnt/58e/home/Crafter/ItemsAll/fiifex.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/thermal.lua" .. "?" .. math.random() .. " /mnt/58e/home/Crafter/ItemsAll/thermal.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/industrial.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/industrial.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/treborn.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/treborn.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/rftools.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/rftools.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/metals.lua" .. "?" .. math.random() .. " /mnt/58e/home/Crafter/ItemsAll/metals.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/modern.lua" .. "?" .. math.random() .. " /mnt/58e/home/Crafter/ItemsAll/modern.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/actadd.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/actadd.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/rocketry.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/rocketry.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/biomes.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/biomes.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/botania.lua" .. "?" .. math.random() .. " /mnt/58e/home/Crafter/ItemsAll/botania.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/mystical.lua" .. "?" .. math.random() .. " /mnt/58e/home/Crafter/ItemsAll/mystical.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/biblio.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/biblio.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/fairy.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/fairy.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/reliq.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/reliq.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/terra.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/terra.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/appen.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/appen.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/btrees.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/btrees.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/binnie.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/binnie.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/aether.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/aether.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/plants.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/plants.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/cyclic.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/cyclic.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/tinkers.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/tinkers.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/ceramics.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/ceramics.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/atl.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/atl.lua")
--os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/deco.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/deco.lua")
--os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/chisel.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/chisel.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/bits.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/bits.lua")
--os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/flat.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/flat.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/more.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/more.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/pillar.lua" .. "?" .. math.random() .. " /mnt/caa/home/Crafter/ItemsAll/pillar.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/chimneys.lua" .. "?" .. math.random() .. " /mnt/caa/home/Crafter/ItemsAll/chimneys.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/minewatch.lua" .. "?" .. math.random() .. " /home/Crafter/ItemsAll/minewatch.lua")
os.execute("wget -f https://raw.githubusercontent.com/bufu1337/OC-Scripts/master/Crafter/ItemsFullAll/future.lua" .. "?" .. math.random() .. " /mnt/58e/home/Crafter/ItemsAll/future.lua")