return {
thermalfoundation_jj_material=2053,
thermalfoundation_jj_ore_fluid=4,
thermalfoundation_jj_glass_alloy=7,
thermalfoundation_jj_storage=8,
thermalfoundation_jj_coin=103,
thermalfoundation_jj_ore=8,
thermalfoundation_jj_storage_alloy=7,
thermalfoundation_jj_rockwool=15,
thermalfoundation_jj_glass=8,
thermalfoundation_jj_fertilizer=2,
thermalfoundation_jj_bait=2,
thermalfoundation_jj_upgrade=256
}