return {
 aether_legacy_jj_aechor_petal={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_aercloud={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_aercloud_jj_1={hasPattern=true,label="Blaue Aerwolke",recipe={aether_legacy_jj_aercloud={need=1,tag=""},aether_legacy_jj_icestone={need=1,tag=""}}},
 aether_legacy_jj_aercloud_jj_2={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_aercloud_jj_3={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_aerogel={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_aerogel_double_slab={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_aerogel_slab={hasPattern=true,label="Unknown Block",recipe={aether_legacy_jj_aerogel={need=3,tag=""}}},
 aether_legacy_jj_aerogel_stairs={hasPattern=true,label="Luftgel Treppe",recipe={aether_legacy_jj_aerogel={need=6,tag=""}}},
 aether_legacy_jj_aerogel_wall={hasPattern=true,label="Luftgel Wand",recipe={aether_legacy_jj_aerogel={need=6,tag=""}}},
 aether_legacy_jj_aether_dirt={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_aether_grass={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_aether_leaves={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_aether_leaves_jj_1={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_aether_lever={hasPattern=true,label="Holystone Lever",recipe={aether_legacy_jj_holystone={need=1,tag=""},aether_legacy_jj_skyroot_stick={need=1,tag=""}}},
 aether_legacy_jj_aether_log={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_aether_log_jj_1={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_aether_portal={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_aether_tune={hasPattern=true,label="Aether Melodie",recipe={aether_legacy_jj_ambrosium_shard={need=1,tag=""},minecraft_jj_record_13={need=1,tag=""}}},
 aether_legacy_jj_aetherion_chest={hasPattern=true,label="Aetherion Chest",recipe={aether_legacy_jj_aetherium_core={need=1,tag=""},minecraft_jj_packed_ice={need=8,tag=""}}},
 aether_legacy_jj_aetherium_core={hasPattern=true,label="Aetherium Core",recipe={aether_legacy_jj_golden_amber={need=1,tag=""},aether_legacy_jj_swetty_ball={need=1,tag=""},aether_legacy_jj_zanite_gemstone={need=1,tag=""}}},
 aether_legacy_jj_agility_cape={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_ambrosium_block={hasPattern=true,label="Block of Ambrosium",recipe={aether_legacy_jj_ambrosium_shard={need=9,tag=""}}},
 aether_legacy_jj_ambrosium_ore={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_ambrosium_shard={hasPattern=true,label="Ambrosium Scherbe",recipe={aether_legacy_jj_ambrosium_ore={need=1,tag=""}}},
 aether_legacy_jj_ambrosium_torch={hasPattern=true,label="Ambrosium Fackel",recipe={aether_legacy_jj_ambrosium_shard={need=1,tag=""},aether_legacy_jj_skyroot_stick={need=1,tag=""}}},
 aether_legacy_jj_angelic_double_slab={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_angelic_slab={hasPattern=true,label="Unknown Block",recipe={aether_legacy_jj_dungeon_block_jj_2={need=3,tag=""}}},
 aether_legacy_jj_angelic_stairs={hasPattern=true,label="Angelic Treppe",recipe={aether_legacy_jj_dungeon_block_jj_2={need=6,tag=""}}},
 aether_legacy_jj_angelic_wall={hasPattern=true,label="Angelic Mauer",recipe={aether_legacy_jj_dungeon_block_jj_2={need=6,tag=""}}},
 aether_legacy_jj_ascending_dawn={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_berry_bush={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_berry_bush_stem={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_blue_berry={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_blue_cape={hasPattern=true,label="Blauer Umhang",recipe={minecraft_jj_wool_jj_11={need=6,tag=""}}},
 aether_legacy_jj_burnt_cockatrice={hasPattern=true,label="Burnt Cockatrice",recipe={aether_legacy_jj_cockatrice={need=1,tag=""}}},
 aether_legacy_jj_candy_cane={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_candy_cane_sword={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_carved_double_slab={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_carved_slab={hasPattern=true,label="Unknown Block",recipe={aether_legacy_jj_dungeon_block={need=3,tag=""}}},
 aether_legacy_jj_carved_stairs={hasPattern=true,label="Geschnitzte Treppe",recipe={aether_legacy_jj_dungeon_block={need=6,tag=""}}},
 aether_legacy_jj_carved_wall={hasPattern=true,label="Geschnitze Mauer",recipe={aether_legacy_jj_dungeon_block={need=6,tag=""}}},
 aether_legacy_jj_chain_gloves={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_chest_mimic={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_cloud_staff={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_cockatrice={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_cold_parachute={hasPattern=true,label="Kalter Fallschirm",recipe={aether_legacy_jj_aercloud={need=4,tag=""}}},
 aether_legacy_jj_cooked_enchanted_cockatrice={hasPattern=true,label="Cooked Enchanted Cockatrice",recipe={aether_legacy_jj_enchanted_cockatrice={need=1,tag=""}}},
 aether_legacy_jj_crystal_leaves={hasPattern=true,label="Kristall Blätter",recipe={aether_legacy_jj_aether_leaves={need=1,tag=""},aether_legacy_jj_icestone={need=1,tag=""}}},
 aether_legacy_jj_crystal_leaves_jj_1={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_dart={hasPattern=true,label="Goldener Pfeil",recipe={aether_legacy_jj_golden_amber={need=1,tag=""},aether_legacy_jj_skyroot_stick={need=1,tag=""},minecraft_jj_feather={need=1,tag=""}}},
 aether_legacy_jj_dart_jj_1={hasPattern=true,label="Giftiger Pfeil",recipe={aether_legacy_jj_dart={need=8,tag=""},aether_legacy_jj_skyroot_bucket_jj_2={need=1,tag=""}}},
 aether_legacy_jj_dart_jj_2={hasPattern=true,label="Verzauberter Pfeil",recipe={aether_legacy_jj_ambrosium_shard={need=1,tag=""},aether_legacy_jj_dart={need=1,tag=""}}},
 aether_legacy_jj_dart_shooter={hasPattern=true,label="Goldene Pfeil Pistole",recipe={aether_legacy_jj_golden_amber={need=1,tag=""},aether_legacy_jj_skyroot_plank={need=2,tag=""}}},
 aether_legacy_jj_dart_shooter_jj_1={hasPattern=true,label="Giftige Pfeil Pistole",recipe={aether_legacy_jj_dart_shooter={need=1,tag=""},aether_legacy_jj_skyroot_bucket_jj_2={need=1,tag=""}}},
 aether_legacy_jj_dart_shooter_jj_2={hasPattern=true,label="Verzauberte Pfeil Pistole",recipe={aether_legacy_jj_ambrosium_shard={need=1,tag=""},aether_legacy_jj_dart_shooter={need=1,tag=""}}},
 aether_legacy_jj_developer_stick={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_diamond_gloves={hasPattern=true,label="Diamand Handschuhe",recipe={minecraft_jj_diamond={need=2,tag=""}}},
 aether_legacy_jj_dungeon_block={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_dungeon_block_jj_1={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_dungeon_block_jj_2={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_dungeon_block_jj_3={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_dungeon_block_jj_4={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_dungeon_block_jj_5={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_dungeon_key={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_dungeon_trap={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_enchanted_aether_grass={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_enchanted_blueberry={hasPattern=true,label="Verzauberte Beere",recipe={aether_legacy_jj_ambrosium_shard={need=1,tag=""},aether_legacy_jj_blue_berry={need=1,tag=""}}},
 aether_legacy_jj_enchanted_cockatrice={hasPattern=true,label="Enchanted Cockatrice",recipe={aether_legacy_jj_ambrosium_shard={need=1,tag=""},aether_legacy_jj_cockatrice={need=1,tag=""}}},
 aether_legacy_jj_enchanted_gravitite={hasPattern=true,label="Verzaubertes Gravitite",recipe={aether_legacy_jj_ambrosium_shard={need=1,tag=""},aether_legacy_jj_gravitite_ore={need=1,tag=""}}},
 aether_legacy_jj_enchanter={hasPattern=true,label="Altar",recipe={aether_legacy_jj_holystone={need=8,tag=""},aether_legacy_jj_zanite_gemstone={need=1,tag=""}}},
 aether_legacy_jj_flaming_sword={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_freezer={hasPattern=true,label="Freezer",recipe={aether_legacy_jj_holystone={need=5,tag=""},aether_legacy_jj_icestone={need=1,tag=""},aether_legacy_jj_skyroot_plank={need=3,tag=""}}},
 aether_legacy_jj_ginger_bread_man={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_golden_amber={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_golden_feather={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_golden_gloves={hasPattern=true,label="Goldene Handschuhe",recipe={minecraft_jj_gold_ingot={need=2,tag=""}}},
 aether_legacy_jj_golden_oak_sapling={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_golden_parachute={hasPattern=true,label="Goldener Fallschirm",recipe={aether_legacy_jj_aercloud_jj_2={need=4,tag=""}}},
 aether_legacy_jj_golden_pendant={hasPattern=true,label="Goldener Anhänger",recipe={minecraft_jj_gold_ingot={need=1,tag=""},minecraft_jj_string={need=5,tag=""}}},
 aether_legacy_jj_golden_ring={hasPattern=true,label="Gold Ring",recipe={minecraft_jj_gold_ingot={need=4,tag=""}}},
 aether_legacy_jj_gravitite_axe={hasPattern=true,label="Gravitite Axt",recipe={aether_legacy_jj_enchanted_gravitite={need=3,tag=""},aether_legacy_jj_skyroot_stick={need=2,tag=""}}},
 aether_legacy_jj_gravitite_boots={hasPattern=true,label="Gravitite Schuhe",recipe={aether_legacy_jj_enchanted_gravitite={need=4,tag=""}}},
 aether_legacy_jj_gravitite_chestplate={hasPattern=true,label="Gravtiite Brustplatte",recipe={aether_legacy_jj_enchanted_gravitite={need=8,tag=""}}},
 aether_legacy_jj_gravitite_gloves={hasPattern=true,label="Gravitite Handschuhe",recipe={aether_legacy_jj_enchanted_gravitite={need=2,tag=""}}},
 aether_legacy_jj_gravitite_helmet={hasPattern=true,label="Gravitite Helm",recipe={aether_legacy_jj_enchanted_gravitite={need=5,tag=""}}},
 aether_legacy_jj_gravitite_leggings={hasPattern=true,label="Gravitite Hose",recipe={aether_legacy_jj_enchanted_gravitite={need=7,tag=""}}},
 aether_legacy_jj_gravitite_ore={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_gravitite_pickaxe={hasPattern=true,label="Gravitite Spitzhacke",recipe={aether_legacy_jj_enchanted_gravitite={need=3,tag=""},aether_legacy_jj_skyroot_stick={need=2,tag=""}}},
 aether_legacy_jj_gravitite_shovel={hasPattern=true,label="Gravitite Schaufel",recipe={aether_legacy_jj_enchanted_gravitite={need=1,tag=""},aether_legacy_jj_skyroot_stick={need=2,tag=""}}},
 aether_legacy_jj_gravitite_sword={hasPattern=true,label="Gravitite Schwert",recipe={aether_legacy_jj_enchanted_gravitite={need=2,tag=""},aether_legacy_jj_skyroot_stick={need=1,tag=""}}},
 aether_legacy_jj_gummy_swet={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_healing_stone={hasPattern=true,label="Heilender Stein",recipe={aether_legacy_jj_ambrosium_shard={need=1,tag=""},aether_legacy_jj_holystone={need=1,tag=""}}},
 aether_legacy_jj_hellfire_double_slab={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_hellfire_slab={hasPattern=true,label="Unknown Block",recipe={aether_legacy_jj_dungeon_block_jj_4={need=3,tag=""}}},
 aether_legacy_jj_hellfire_stairs={hasPattern=true,label="Höllenfeuer Treppe",recipe={aether_legacy_jj_dungeon_block_jj_4={need=6,tag=""}}},
 aether_legacy_jj_hellfire_wall={hasPattern=true,label="Höllenfeuer Mauer",recipe={aether_legacy_jj_dungeon_block_jj_4={need=6,tag=""}}},
 aether_legacy_jj_holiday_leaves={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_holiday_leaves_jj_1={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_holy_sword={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_holystone={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_holystone_axe={hasPattern=true,label="Heiligstein Axt",recipe={aether_legacy_jj_holystone={need=3,tag=""},aether_legacy_jj_skyroot_stick={need=2,tag=""}}},
 aether_legacy_jj_holystone_brick={hasPattern=true,label="Heiligstein Ziegel",recipe={aether_legacy_jj_holystone={need=4,tag=""}}},
 aether_legacy_jj_holystone_brick_double_slab={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_holystone_brick_slab={hasPattern=true,label="Unknown Block",recipe={aether_legacy_jj_holystone_brick={need=3,tag=""}}},
 aether_legacy_jj_holystone_brick_stairs={hasPattern=true,label="Heiligstein Ziegel Treppe",recipe={aether_legacy_jj_holystone_brick={need=6,tag=""}}},
 aether_legacy_jj_holystone_brick_wall={hasPattern=true,label="Heiligstein Ziegel Wand",recipe={aether_legacy_jj_holystone_brick={need=6,tag=""}}},
 aether_legacy_jj_holystone_button={hasPattern=true,label="Holystone Button",recipe={aether_legacy_jj_holystone={need=1,tag=""}}},
 aether_legacy_jj_holystone_double_slab={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_holystone_pickaxe={hasPattern=true,label="Heiligstein Spitzhacke",recipe={aether_legacy_jj_holystone={need=3,tag=""},aether_legacy_jj_skyroot_stick={need=2,tag=""}}},
 aether_legacy_jj_holystone_pressure_plate={hasPattern=true,label="Holystone Pressure Plate",recipe={aether_legacy_jj_holystone={need=2,tag=""}}},
 aether_legacy_jj_holystone_shovel={hasPattern=true,label="Heiligstein Schaufel",recipe={aether_legacy_jj_holystone={need=1,tag=""},aether_legacy_jj_skyroot_stick={need=2,tag=""}}},
 aether_legacy_jj_holystone_slab={hasPattern=true,label="Unknown Block",recipe={aether_legacy_jj_holystone={need=3,tag=""}}},
 aether_legacy_jj_holystone_stairs={hasPattern=true,label="Heiligstein Treppen",recipe={aether_legacy_jj_holystone={need=6,tag=""}}},
 aether_legacy_jj_holystone_sword={hasPattern=true,label="Heiligstein Schwert",recipe={aether_legacy_jj_holystone={need=2,tag=""},aether_legacy_jj_skyroot_stick={need=1,tag=""}}},
 aether_legacy_jj_holystone_wall={hasPattern=true,label="Heiligstein Mauer",recipe={aether_legacy_jj_holystone={need=6,tag=""}}},
 aether_legacy_jj_ice_pendant={hasPattern=true,label="Eis Anhänger",recipe={aether_legacy_jj_icestone={need=1,tag=""},aether_legacy_jj_iron_pendant={need=1,tag=""}}},
 aether_legacy_jj_ice_ring={hasPattern=true,label="Eis Ring",recipe={aether_legacy_jj_icestone={need=1,tag=""},aether_legacy_jj_iron_ring={need=1,tag=""}}},
 aether_legacy_jj_icestone={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_incubator={hasPattern=true,label="Inkubator",recipe={aether_legacy_jj_ambrosium_torch={need=1,tag=""},aether_legacy_jj_holystone={need=8,tag=""}}},
 aether_legacy_jj_invisibility_cape={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_iron_bubble={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_iron_gloves={hasPattern=true,label="Eisen Handschuhe",recipe={minecraft_jj_iron_ingot={need=2,tag=""}}},
 aether_legacy_jj_iron_pendant={hasPattern=true,label="Eisen Anhänger",recipe={minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_string={need=5,tag=""}}},
 aether_legacy_jj_iron_ring={hasPattern=true,label="Eisen Ring",recipe={minecraft_jj_iron_ingot={need=4,tag=""}}},
 aether_legacy_jj_leather_gloves={hasPattern=true,label="Leder Handschuhe",recipe={minecraft_jj_leather={need=2,tag=""}}},
 aether_legacy_jj_legacy={hasPattern=true,label="Legacy",recipe={aether_legacy_jj_ambrosium_shard={need=1,tag=""},minecraft_jj_record_cat={need=1,tag=""}}},
 aether_legacy_jj_life_shard={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_lightning_knife={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_lightning_sword={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_locked_dungeon_block={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_lore_book={hasPattern=true,label="Buch der Überlieferung",recipe={aether_legacy_jj_ambrosium_shard={need=1,tag=""},minecraft_jj_book={need=1,tag=""}}},
 aether_legacy_jj_moa_egg={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_mossy_holystone={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_mossy_holystone_double_slab={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_mossy_holystone_slab={hasPattern=true,label="Unknown Block",recipe={aether_legacy_jj_mossy_holystone={need=3,tag=""}}},
 aether_legacy_jj_mossy_holystone_stairs={hasPattern=true,label="Moosige Heiligstein Treppe",recipe={aether_legacy_jj_mossy_holystone={need=6,tag=""}}},
 aether_legacy_jj_mossy_holystone_wall={hasPattern=true,label="Moosige Heiligstein Wand",recipe={aether_legacy_jj_mossy_holystone={need=6,tag=""}}},
 aether_legacy_jj_nature_staff={hasPattern=true,label="Naturstab",recipe={aether_legacy_jj_skyroot_stick={need=1,tag=""},aether_legacy_jj_zanite_gemstone={need=1,tag=""}}},
 aether_legacy_jj_neptune_boots={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_neptune_chestplate={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_neptune_gloves={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_neptune_helmet={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_neptune_leggings={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_notch_hammer={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_obsidian_boots={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_obsidian_chestplate={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_obsidian_gloves={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_obsidian_helmet={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_obsidian_leggings={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_phoenix_boots={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_phoenix_bow={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_phoenix_chestplate={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_phoenix_gloves={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_phoenix_helmet={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_phoenix_leggings={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_pig_slayer={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_pillar={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_pillar_top={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_present={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_purple_flower={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_quicksoil={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_quicksoil_glass={hasPattern=true,label="Schnellboden Glas",recipe={aether_legacy_jj_ambrosium_shard={need=1,tag=""},aether_legacy_jj_quicksoil={need=1,tag=""}}},
 aether_legacy_jj_quicksoil_glass_pane={hasPattern=true,label="Quicksoil Glass Pane",recipe={aether_legacy_jj_quicksoil_glass={need=6,tag=""}}},
 aether_legacy_jj_red_cape={hasPattern=true,label="Roter Umhang",recipe={minecraft_jj_wool_jj_14={need=6,tag=""}}},
 aether_legacy_jj_regeneration_stone={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_repulsion_shield={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_sentry_boots={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_skyroot_axe={hasPattern=true,label="Himmelswurzel Axt",recipe={aether_legacy_jj_skyroot_plank={need=3,tag=""},aether_legacy_jj_skyroot_stick={need=2,tag=""}}},
 aether_legacy_jj_skyroot_bed={hasPattern=true,label="White Skyroot Bed",recipe={aether_legacy_jj_skyroot_plank={need=3,tag=""},minecraft_jj_wool={need=3,tag=""}}},
 aether_legacy_jj_skyroot_bookshelf={hasPattern=true,label="Skyroot Bookshelf",recipe={aether_legacy_jj_skyroot_plank={need=6,tag=""},minecraft_jj_book={need=3,tag=""}}},
 aether_legacy_jj_skyroot_bucket={hasPattern=true,label="Himmelswurzel Eimer",recipe={aether_legacy_jj_skyroot_plank={need=3,tag=""}}},
 aether_legacy_jj_skyroot_bucket_jj_1={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_skyroot_bucket_jj_2={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_skyroot_bucket_jj_3={hasPattern=true,label="Himmelswurzel Abhilfe Eimer",recipe={aether_legacy_jj_ambrosium_shard={need=1,tag=""},aether_legacy_jj_skyroot_bucket_jj_2={need=1,tag=""}}},
 aether_legacy_jj_skyroot_bucket_jj_4={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_skyroot_button={hasPattern=true,label="Skyroot Button",recipe={aether_legacy_jj_skyroot_plank={need=1,tag=""}}},
 aether_legacy_jj_skyroot_chest={hasPattern=true,label="Skyroot Chest",recipe={aether_legacy_jj_skyroot_plank={need=8,tag=""}}},
 aether_legacy_jj_skyroot_crafting_table={hasPattern=true,label="Skyroot Crafting Table",recipe={aether_legacy_jj_skyroot_plank={need=4,tag=""}}},
 aether_legacy_jj_skyroot_door={hasPattern=true,label="Skyroot Door",recipe={aether_legacy_jj_skyroot_plank={need=6,tag=""}}},
 aether_legacy_jj_skyroot_double_slab={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_skyroot_fence={hasPattern=true,label="Himmelswurzel Zaun",recipe={aether_legacy_jj_skyroot_plank={need=4,tag=""},aether_legacy_jj_skyroot_stick={need=2,tag=""}}},
 aether_legacy_jj_skyroot_fence_gate={hasPattern=true,label="Himmelswurzel Zauntor",recipe={aether_legacy_jj_skyroot_plank={need=2,tag=""},aether_legacy_jj_skyroot_stick={need=4,tag=""}}},
 aether_legacy_jj_skyroot_ladder={hasPattern=true,label="Skyroot Ladder",recipe={aether_legacy_jj_skyroot_stick={need=7,tag=""}}},
 aether_legacy_jj_skyroot_pickaxe={hasPattern=true,label="Skyroot Pickaxe",recipe={aether_legacy_jj_skyroot_plank={need=3,tag=""},aether_legacy_jj_skyroot_stick={need=2,tag=""}}},
 aether_legacy_jj_skyroot_plank={hasPattern=true,label="Himmelswurzel Bretter",recipe={aether_legacy_jj_aether_log={need=1,tag=""}}},
 aether_legacy_jj_skyroot_pressure_plate={hasPattern=true,label="Skyroot Pressure Plate",recipe={aether_legacy_jj_skyroot_plank={need=2,tag=""}}},
 aether_legacy_jj_skyroot_sapling={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_skyroot_shovel={hasPattern=true,label="Himmelswurzel Schaufel",recipe={aether_legacy_jj_skyroot_plank={need=1,tag=""},aether_legacy_jj_skyroot_stick={need=2,tag=""}}},
 aether_legacy_jj_skyroot_sign={hasPattern=true,label="Skyroot Sign",recipe={aether_legacy_jj_skyroot_plank={need=6,tag=""},aether_legacy_jj_skyroot_stick={need=1,tag=""}}},
 aether_legacy_jj_skyroot_slab={hasPattern=true,label="Unknown Block",recipe={aether_legacy_jj_skyroot_plank={need=3,tag=""}}},
 aether_legacy_jj_skyroot_stairs={hasPattern=true,label="Himmelswurzel Treppe",recipe={aether_legacy_jj_skyroot_plank={need=6,tag=""}}},
 aether_legacy_jj_skyroot_stick={hasPattern=true,label="Himmelswurzel Stab",recipe={aether_legacy_jj_skyroot_plank={need=2,tag=""}}},
 aether_legacy_jj_skyroot_sword={hasPattern=true,label="Himmelswurzel Schwert",recipe={aether_legacy_jj_skyroot_plank={need=2,tag=""},aether_legacy_jj_skyroot_stick={need=1,tag=""}}},
 aether_legacy_jj_skyroot_trapdoor={hasPattern=true,label="Skyroot Trapdoor",recipe={aether_legacy_jj_skyroot_plank={need=6,tag=""}}},
 aether_legacy_jj_sun_altar={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_swet_cape={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_swetty_ball={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_treasure_chest={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_valkyrie_axe={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_valkyrie_boots={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_valkyrie_cape={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_valkyrie_chestplate={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_valkyrie_gloves={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_valkyrie_helmet={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_valkyrie_lance={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_valkyrie_leggings={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_valkyrie_pickaxe={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_valkyrie_shovel={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_vampire_blade={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_victory_medal={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_welcoming_skies={hasPattern=true,label="Einladender Himmel",recipe={aether_legacy_jj_ascending_dawn={need=1,tag=""},aether_legacy_jj_icestone={need=1,tag=""}}},
 aether_legacy_jj_white_apple={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_white_cape={hasPattern=true,label="Wheißer Umhang",recipe={minecraft_jj_wool={need=6,tag=""}}},
 aether_legacy_jj_white_flower={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_yellow_cape={hasPattern=true,label="Gelber Umhang",recipe={minecraft_jj_wool_jj_4={need=6,tag=""}}},
 aether_legacy_jj_zanite_axe={hasPattern=true,label="Zanite Axt",recipe={aether_legacy_jj_skyroot_stick={need=2,tag=""},aether_legacy_jj_zanite_gemstone={need=3,tag=""}}},
 aether_legacy_jj_zanite_bars={hasPattern=true,label="Zanite Bars",recipe={aether_legacy_jj_zanite_gemstone={need=6,tag=""}}},
 aether_legacy_jj_zanite_block={hasPattern=true,label="Zanite Block",recipe={aether_legacy_jj_zanite_gemstone={need=9,tag=""}}},
 aether_legacy_jj_zanite_boots={hasPattern=true,label="Zanite Schuhe",recipe={aether_legacy_jj_zanite_gemstone={need=4,tag=""}}},
 aether_legacy_jj_zanite_chestplate={hasPattern=true,label="Zanite Brustplatte",recipe={aether_legacy_jj_zanite_gemstone={need=8,tag=""}}},
 aether_legacy_jj_zanite_door={hasPattern=true,label="Zanite Door",recipe={aether_legacy_jj_zanite_gemstone={need=6,tag=""}}},
 aether_legacy_jj_zanite_gemstone={hasPattern=true,label="Zanite Edelstein",recipe={aether_legacy_jj_zanite_ore={need=1,tag=""}}},
 aether_legacy_jj_zanite_gloves={hasPattern=true,label="Zanite Handschuhe",recipe={aether_legacy_jj_zanite_gemstone={need=2,tag=""}}},
 aether_legacy_jj_zanite_helmet={hasPattern=true,label="Zanite Helm",recipe={aether_legacy_jj_zanite_gemstone={need=5,tag=""}}},
 aether_legacy_jj_zanite_leggings={hasPattern=true,label="Zanite Hose",recipe={aether_legacy_jj_zanite_gemstone={need=7,tag=""}}},
 aether_legacy_jj_zanite_ore={hasPattern=false,label="",recipe={}},
 aether_legacy_jj_zanite_pendant={hasPattern=true,label="Zanite Anhänger",recipe={aether_legacy_jj_zanite_gemstone={need=1,tag=""},minecraft_jj_string={need=5,tag=""}}},
 aether_legacy_jj_zanite_pickaxe={hasPattern=true,label="Zanite Spitzhacke",recipe={aether_legacy_jj_skyroot_stick={need=2,tag=""},aether_legacy_jj_zanite_gemstone={need=3,tag=""}}},
 aether_legacy_jj_zanite_pressure_plate={hasPattern=true,label="Zanite Pressure Plate",recipe={aether_legacy_jj_zanite_gemstone={need=2,tag=""}}},
 aether_legacy_jj_zanite_ring={hasPattern=true,label="Zanite Ring",recipe={aether_legacy_jj_zanite_gemstone={need=4,tag=""}}},
 aether_legacy_jj_zanite_shovel={hasPattern=true,label="Zanite Schaufel",recipe={aether_legacy_jj_skyroot_stick={need=2,tag=""},aether_legacy_jj_zanite_gemstone={need=1,tag=""}}},
 aether_legacy_jj_zanite_sword={hasPattern=true,label="Zanite Schwert",recipe={aether_legacy_jj_skyroot_stick={need=1,tag=""},aether_legacy_jj_zanite_gemstone={need=2,tag=""}}},
 aether_legacy_jj_zanite_trapdoor={hasPattern=true,label="Zanite Trapdoor",recipe={aether_legacy_jj_zanite_gemstone={need=4,tag=""}}},
 animania_jj_animania_manual={hasPattern=true,label="Animania Manual",recipe={animania_jj_block_straw={need=1,tag=""},minecraft_jj_book={need=1,tag=""},minecraft_jj_wheat_seeds={need=1,tag=""}}},
 animania_jj_bacon_omelette={hasPattern=true,label="Omelette mit Speck",recipe={animania_jj_cooked_prime_bacon={need=1,tag=""},animania_jj_plain_omelette={need=1,tag=""}}},
 animania_jj_bee_hive={hasPattern=true,label="Bee Hive",recipe={animania_jj_wild_hive={need=1,tag=""},minecraft_jj_planks={need=8,tag=""}}},
 animania_jj_block_hamster_wheel={hasPattern=true,label="Hamster Wheel",recipe={minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_stone_slab={need=2,tag=""}}},
 animania_jj_block_mud={hasPattern=true,label="Schlamm",recipe={minecraft_jj_dirt={need=2,tag=""},minecraft_jj_water_bucket={need=2,tag=""}}},
 animania_jj_block_nest={hasPattern=true,label="Nest",recipe={minecraft_jj_leaves={need=1,tag=""},minecraft_jj_stick={need=1,tag=""},minecraft_jj_wool={need=1,tag=""}}},
 animania_jj_block_straw={hasPattern=true,label="Straw",recipe={animania_jj_carving_knife={need=1,tag=""},minecraft_jj_wheat={need=1,tag=""}}},
 animania_jj_block_trough={hasPattern=true,label="Trog",recipe={minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_planks={need=4,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 animania_jj_blue_peacock_feather={hasPattern=false,label="",recipe={}},
 animania_jj_brown_egg={hasPattern=false,label="",recipe={}},
 animania_jj_carving_knife={hasPattern=true,label="Tranchiermesser",recipe={minecraft_jj_iron_ingot={need=2,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 animania_jj_charcoal_peacock_feather={hasPattern=false,label="",recipe={}},
 animania_jj_cheese_mold={hasPattern=true,label="Cheese Mold",recipe={minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_planks={need=3,tag=""}}},
 animania_jj_cheese_omelette={hasPattern=true,label="Käseomelette",recipe={animania_jj_friesian_cheese_wedge={need=1,tag=""},animania_jj_plain_omelette={need=1,tag=""}}},
 animania_jj_chocolate_truffle={hasPattern=true,label="Schokoladentrüffel",recipe={animania_jj_truffle={need=1,tag=""},minecraft_jj_dye_jj_3={need=1,tag=""},minecraft_jj_sugar={need=1,tag=""}}},
 animania_jj_cooked_chevon={hasPattern=true,label="Roast Chevon",recipe={animania_jj_raw_chevon={need=1,tag=""}}},
 animania_jj_cooked_frog_legs={hasPattern=true,label="Cooked Frog Legs",recipe={animania_jj_raw_frog_legs={need=1,tag=""}}},
 animania_jj_cooked_horse={hasPattern=true,label="Cooked Horse",recipe={animania_jj_raw_horse={need=1,tag=""}}},
 animania_jj_cooked_peacock={hasPattern=true,label="Roast Peacock",recipe={animania_jj_raw_peacock={need=1,tag=""}}},
 animania_jj_cooked_prime_bacon={hasPattern=true,label="Roast Prime Bacon",recipe={animania_jj_raw_prime_bacon={need=1,tag=""}}},
 animania_jj_cooked_prime_beef={hasPattern=true,label="Roast Prime Beef",recipe={animania_jj_raw_prime_beef={need=1,tag=""}}},
 animania_jj_cooked_prime_chevon={hasPattern=true,label="Roast Prime Chevon",recipe={animania_jj_raw_prime_chevon={need=1,tag=""}}},
 animania_jj_cooked_prime_chicken={hasPattern=true,label="Roast Prime Chicken",recipe={animania_jj_raw_prime_chicken={need=1,tag=""}}},
 animania_jj_cooked_prime_mutton={hasPattern=true,label="Roast Prime Mutton",recipe={animania_jj_raw_prime_mutton={need=1,tag=""}}},
 animania_jj_cooked_prime_peacock={hasPattern=true,label="Roast Prime Peacock",recipe={animania_jj_raw_prime_peacock={need=1,tag=""}}},
 animania_jj_cooked_prime_pork={hasPattern=true,label="Roast Prime Pork",recipe={animania_jj_raw_prime_pork={need=1,tag=""}}},
 animania_jj_cooked_prime_rabbit={hasPattern=true,label="Roast Prime Rabbit",recipe={animania_jj_raw_prime_rabbit={need=1,tag=""}}},
 animania_jj_cooked_prime_steak={hasPattern=true,label="Roast Prime Steak",recipe={animania_jj_raw_prime_steak={need=1,tag=""}}},
 animania_jj_entity_egg_buck_alpine={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_buck_angora={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_buck_chinchilla={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_buck_cottontail={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_buck_dutch={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_buck_fainting={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_buck_havana={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_buck_jack={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_buck_kiko={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_buck_kinder={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_buck_lop={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_buck_new_zealand={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_buck_nigerian_dwarf={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_buck_pygmy={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_buck_rex={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_bull_angus={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_bull_friesian={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_bull_hereford={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_bull_highland={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_bull_holstein={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_bull_jersey={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_bull_longhorn={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_bull_mooshroom={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_calf_angus={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_calf_friesian={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_calf_hereford={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_calf_highland={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_calf_holstein={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_calf_jersey={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_calf_longhorn={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_calf_mooshroom={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_chick_leghorn={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_chick_orpington={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_chick_plymouth_rock={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_chick_rhode_island_red={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_chick_wyandotte={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_chicken_random={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_cow_angus={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_cow_friesian={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_cow_hereford={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_cow_highland={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_cow_holstein={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_cow_jersey={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_cow_longhorn={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_cow_mooshroom={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_cow_random={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_dart_frog={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_doe_alpine={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_doe_angora={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_doe_chinchilla={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_doe_cottontail={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_doe_dutch={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_doe_fainting={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_doe_havana={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_doe_jack={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_doe_kiko={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_doe_kinder={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_doe_lop={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_doe_new_zealand={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_doe_nigerian_dwarf={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_doe_pygmy={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_doe_rex={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_ewe_dorper={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_ewe_dorset={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_ewe_friesian={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_ewe_jacob={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_ewe_merino={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_ewe_suffolk={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_ferret_grey={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_ferret_white={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_foal_draft={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_frog={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_goat_random={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_hamster={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_hedgehog={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_hedgehog_albino={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_hen_leghorn={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_hen_orpington={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_hen_plymouth_rock={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_hen_rhode_island_red={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_hen_wyandotte={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_hog_duroc={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_hog_hampshire={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_hog_large_black={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_hog_large_white={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_hog_old_spot={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_hog_yorkshire={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_kid_alpine={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_kid_angora={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_kid_fainting={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_kid_kiko={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_kid_kinder={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_kid_nigerian_dwarf={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_kid_pygmy={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_kit_chinchilla={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_kit_cottontail={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_kit_dutch={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_kit_havana={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_kit_jack={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_kit_lop={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_kit_new_zealand={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_kit_rex={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_lamb_dorper={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_lamb_dorset={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_lamb_friesian={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_lamb_jacob={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_lamb_merino={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_lamb_suffolk={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_mare_draft={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_peachick_blue={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_peachick_charcoal={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_peachick_opal={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_peachick_peach={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_peachick_purple={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_peachick_taupe={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_peachick_white={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_peacock_blue={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_peacock_charcoal={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_peacock_opal={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_peacock_peach={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_peacock_purple={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_peacock_random={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_peacock_taupe={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_peacock_white={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_peahen_blue={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_peahen_charcoal={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_peahen_opal={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_peahen_peach={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_peahen_purple={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_peahen_taupe={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_peahen_white={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_pig_random={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_piglet_duroc={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_piglet_hampshire={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_piglet_large_black={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_piglet_large_white={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_piglet_old_spot={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_piglet_yorkshire={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_rabbit_random={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_ram_dorper={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_ram_dorset={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_ram_friesian={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_ram_jacob={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_ram_merino={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_ram_suffolk={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_random={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_rooster_leghorn={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_rooster_orpington={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_rooster_plymouth_rock={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_rooster_rhode_island_red={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_rooster_wyandotte={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_sheep_random={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_sow_duroc={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_sow_hampshire={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_sow_large_black={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_sow_large_white={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_sow_old_spot={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_sow_yorkshire={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_stallion_draft={hasPattern=false,label="",recipe={}},
 animania_jj_entity_egg_toad={hasPattern=false,label="",recipe={}},
 animania_jj_friesian_cheese_wedge={hasPattern=false,label="",recipe={}},
 animania_jj_friesian_cheese_wheel={hasPattern=false,label="",recipe={}},
 animania_jj_goat_cheese_wedge={hasPattern=false,label="",recipe={}},
 animania_jj_goat_cheese_wheel={hasPattern=false,label="",recipe={}},
 animania_jj_hamster_ball_clear={hasPattern=true,label="Clear Hamster Ball",recipe={minecraft_jj_glass_pane={need=8,tag=""}}},
 animania_jj_hamster_ball_colored={hasPattern=true,label="Black Hamster Ball",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_glass_pane={need=8,tag=""}}},
 animania_jj_hamster_food={hasPattern=true,label="Hamster Futter",recipe={minecraft_jj_melon_seeds={need=1,tag=""},minecraft_jj_pumpkin_seeds={need=1,tag=""},minecraft_jj_wheat_seeds={need=1,tag=""}}},
 animania_jj_holstein_cheese_wedge={hasPattern=false,label="",recipe={}},
 animania_jj_holstein_cheese_wheel={hasPattern=false,label="",recipe={}},
 animania_jj_honey_bottle={hasPattern=false,label="",recipe={}},
 animania_jj_item_cart={hasPattern=true,label="Horse Cart",recipe={animania_jj_wheel={need=2,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_planks={need=4,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 animania_jj_item_tiller={hasPattern=true,label="Tiller",recipe={animania_jj_wheel={need=2,tag=""},minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_planks={need=2,tag=""}}},
 animania_jj_item_wagon={hasPattern=true,label="Covered Wagon",recipe={animania_jj_item_cart={need=1,tag=""},animania_jj_wheel={need=2,tag=""},minecraft_jj_bed={need=1,tag=""},minecraft_jj_chest={need=1,tag=""},minecraft_jj_planks={need=2,tag=""},minecraft_jj_wool={need=2,tag=""}}},
 animania_jj_jersey_cheese_wedge={hasPattern=false,label="",recipe={}},
 animania_jj_jersey_cheese_wheel={hasPattern=false,label="",recipe={}},
 animania_jj_milk_bottle={hasPattern=true,label="Bottle of Milk",recipe={forge_jj_bucketfilled={need=1,tag=""},minecraft_jj_glass_bottle={need=4,tag=""}}},
 animania_jj_opal_peacock_feather={hasPattern=false,label="",recipe={}},
 animania_jj_peach_peacock_feather={hasPattern=false,label="",recipe={}},
 animania_jj_peacock_egg_blue={hasPattern=false,label="",recipe={}},
 animania_jj_peacock_egg_white={hasPattern=false,label="",recipe={}},
 animania_jj_plain_omelette={hasPattern=true,label="Omelette",recipe={minecraft_jj_egg={need=1,tag=""}}},
 animania_jj_purple_peacock_feather={hasPattern=false,label="",recipe={}},
 animania_jj_raw_chevon={hasPattern=false,label="",recipe={}},
 animania_jj_raw_frog_legs={hasPattern=false,label="",recipe={}},
 animania_jj_raw_horse={hasPattern=false,label="",recipe={}},
 animania_jj_raw_peacock={hasPattern=false,label="",recipe={}},
 animania_jj_raw_prime_bacon={hasPattern=false,label="",recipe={}},
 animania_jj_raw_prime_beef={hasPattern=false,label="",recipe={}},
 animania_jj_raw_prime_chevon={hasPattern=false,label="",recipe={}},
 animania_jj_raw_prime_chicken={hasPattern=false,label="",recipe={}},
 animania_jj_raw_prime_mutton={hasPattern=false,label="",recipe={}},
 animania_jj_raw_prime_peacock={hasPattern=false,label="",recipe={}},
 animania_jj_raw_prime_pork={hasPattern=false,label="",recipe={}},
 animania_jj_raw_prime_rabbit={hasPattern=false,label="",recipe={}},
 animania_jj_raw_prime_steak={hasPattern=false,label="",recipe={}},
 animania_jj_riding_crop={hasPattern=true,label="Riding Crop",recipe={minecraft_jj_leather={need=2,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 animania_jj_salt={hasPattern=true,label="Salt",recipe={harvestcraft_jj_saltitem={need=1,tag=""}}},
 animania_jj_salt_lick={hasPattern=true,label="Salt Lick",recipe={animania_jj_salt={need=8,tag=""},minecraft_jj_water_bucket={need=1,tag=""}}},
 animania_jj_sheep_cheese_wedge={hasPattern=false,label="",recipe={}},
 animania_jj_sheep_cheese_wheel={hasPattern=false,label="",recipe={}},
 animania_jj_super_omelette={hasPattern=true,label="Superomelette",recipe={animania_jj_cooked_prime_bacon={need=1,tag=""},animania_jj_friesian_cheese_wedge={need=1,tag=""},animania_jj_plain_omelette={need=1,tag=""},animania_jj_truffle={need=1,tag=""}}},
 animania_jj_taupe_peacock_feather={hasPattern=false,label="",recipe={}},
 animania_jj_truffle={hasPattern=false,label="",recipe={}},
 animania_jj_truffle_omelette={hasPattern=true,label="Trüffelomelette",recipe={animania_jj_plain_omelette={need=1,tag=""},animania_jj_truffle={need=1,tag=""}}},
 animania_jj_truffle_soup={hasPattern=true,label="Trüffelsuppe",recipe={animania_jj_truffle={need=2,tag=""},minecraft_jj_bowl={need=1,tag=""}}},
 animania_jj_wheel={hasPattern=true,label="Wheel",recipe={minecraft_jj_iron_nugget={need=1,tag=""},minecraft_jj_stick={need=4,tag=""}}},
 animania_jj_white_peacock_feather={hasPattern=false,label="",recipe={}},
 animania_jj_wild_hive={hasPattern=false,label="",recipe={}},
 animania_jj_wool={hasPattern=false,label="",recipe={}},
 animania_jj_wool_jj_1={hasPattern=false,label="",recipe={}},
 animania_jj_wool_jj_2={hasPattern=false,label="",recipe={}},
 animania_jj_wool_jj_3={hasPattern=false,label="",recipe={}},
 animania_jj_wool_jj_4={hasPattern=false,label="",recipe={}},
 animania_jj_wool_jj_5={hasPattern=false,label="",recipe={}},
 animania_jj_wool_jj_6={hasPattern=false,label="",recipe={}},
 lost_aether_jj_agility_boots={hasPattern=false,label="",recipe={}},
 lost_aether_jj_crystal_sapling={hasPattern=false,label="",recipe={}},
 lost_aether_jj_gale_double_slab={hasPattern=false,label="",recipe={}},
 lost_aether_jj_gale_slab={hasPattern=true,label="Unknown Block",recipe={lost_aether_jj_gale_stone={need=3,tag=""}}},
 lost_aether_jj_gale_stairs={hasPattern=true,label="Sturmtreppe",recipe={lost_aether_jj_gale_stone={need=6,tag=""}}},
 lost_aether_jj_gale_stone={hasPattern=false,label="",recipe={}},
 lost_aether_jj_gale_wall={hasPattern=true,label="Sturmwand",recipe={lost_aether_jj_gale_stone={need=6,tag=""}}},
 lost_aether_jj_gravitite_shield={hasPattern=true,label="Gravitite Schild",recipe={aether_legacy_jj_enchanted_gravitite={need=6,tag=""},aether_legacy_jj_skyroot_stick={need=1,tag=""}}},
 lost_aether_jj_invisibility_gem={hasPattern=false,label="",recipe={}},
 lost_aether_jj_jeb_shield={hasPattern=false,label="",recipe={}},
 lost_aether_jj_light_gale_stone={hasPattern=false,label="",recipe={}},
 lost_aether_jj_locked_gale_stone={hasPattern=false,label="",recipe={}},
 lost_aether_jj_locked_light_gale_stone={hasPattern=false,label="",recipe={}},
 lost_aether_jj_phoenix_axe={hasPattern=false,label="",recipe={}},
 lost_aether_jj_phoenix_cape={hasPattern=false,label="",recipe={}},
 lost_aether_jj_phoenix_pickaxe={hasPattern=false,label="",recipe={}},
 lost_aether_jj_phoenix_shovel={hasPattern=false,label="",recipe={}},
 lost_aether_jj_phoenix_sword={hasPattern=false,label="",recipe={}},
 lost_aether_jj_platinum_key={hasPattern=false,label="",recipe={}},
 lost_aether_jj_power_gloves={hasPattern=false,label="",recipe={}},
 lost_aether_jj_sentry_shield={hasPattern=false,label="",recipe={}},
 lost_aether_jj_songstone={hasPattern=false,label="",recipe={}},
 lost_aether_jj_swetty_mask={hasPattern=false,label="",recipe={}},
 lost_aether_jj_zanite_shield={hasPattern=true,label="Zanite Schild",recipe={aether_legacy_jj_skyroot_stick={need=1,tag=""},aether_legacy_jj_zanite_gemstone={need=6,tag=""}}},
 minecolonies_jj_ancienttome={hasPattern=false,label="",recipe={}},
 minecolonies_jj_barrel_block={hasPattern=true,label="Fass",recipe={minecraft_jj_dirt={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_planks={need=6,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockbarrackstowersubstitution={hasPattern=false,label="",recipe={}},
 minecolonies_jj_blockconstructiontape={hasPattern=true,label="Baustellenabsperrung",recipe={minecraft_jj_stick={need=6,tag=""},minecraft_jj_wool_jj_4={need=1,tag=""}}},
 minecolonies_jj_blockhutarchery={hasPattern=true,label="Schießstand",recipe={minecraft_jj_bow={need=3,tag=""},minecraft_jj_planks={need=5,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutbaker={hasPattern=true,label="Bäckerei",recipe={minecraft_jj_planks={need=7,tag=""},minecraft_jj_wheat={need=1,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutbarracks={hasPattern=true,label="Kaserne",recipe={minecraft_jj_iron_block={need=1,tag=""},minecraft_jj_planks={need=7,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutbarrackstower={hasPattern=false,label="",recipe={}},
 minecolonies_jj_blockhutblacksmith={hasPattern=true,label="Schmiede",recipe={minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_planks={need=5,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutbuilder={hasPattern=true,label="Bauhütte",recipe={minecraft_jj_planks={need=7,tag=""},minecraft_jj_wooden_door={need=1,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutchickenherder={hasPattern=true,label="Hühnerhof",recipe={minecraft_jj_egg={need=1,tag=""},minecraft_jj_planks={need=7,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutcitizen={hasPattern=true,label="Wohnhaus",recipe={minecraft_jj_planks={need=7,tag=""},minecraft_jj_torch={need=1,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutcombatacademy={hasPattern=true,label="Kampfschule",recipe={minecraft_jj_iron_sword={need=3,tag=""},minecraft_jj_planks={need=5,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutcomposter={hasPattern=true,label="Kompostieranlage",recipe={minecolonies_jj_barrel_block={need=1,tag=""},minecraft_jj_planks={need=7,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutcook={hasPattern=true,label="Restaurant",recipe={minecraft_jj_apple={need=1,tag=""},minecraft_jj_planks={need=7,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutcowboy={hasPattern=true,label="Kuhhof",recipe={minecraft_jj_beef={need=1,tag=""},minecraft_jj_planks={need=7,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutcrusher={hasPattern=true,label="Brecher",recipe={minecraft_jj_cobblestone={need=2,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_planks={need=5,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutdeliveryman={hasPattern=true,label="Lastenträger",recipe={minecraft_jj_iron_boots={need=1,tag=""},minecraft_jj_planks={need=7,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutenchanter={hasPattern=true,label="Enchanter",recipe={minecraft_jj_enchanting_table={need=1,tag=""},minecraft_jj_planks={need=7,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutfarmer={hasPattern=true,label="Bauernhof",recipe={minecraft_jj_planks={need=7,tag=""},minecraft_jj_stone_hoe={need=1,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutfield={hasPattern=true,label="Feld",recipe={minecraft_jj_hay_block={need=1,tag=""},minecraft_jj_leather={need=1,tag=""},minecraft_jj_stick={need=3,tag=""}}},
 minecolonies_jj_blockhutfisherman={hasPattern=true,label="Fischerhütte",recipe={minecraft_jj_fishing_rod={need=1,tag=""},minecraft_jj_planks={need=7,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutflorist={hasPattern=true,label="Flower Shop",recipe={minecraft_jj_planks={need=7,tag=""},minecraft_jj_red_flower={need=1,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutguardtower={hasPattern=true,label="Wachturm",recipe={minecraft_jj_bow={need=1,tag=""},minecraft_jj_planks={need=7,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutlibrary={hasPattern=true,label="Bücherei",recipe={minecraft_jj_book={need=1,tag=""},minecraft_jj_planks={need=7,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutlumberjack={hasPattern=true,label="Holzfällerhütte",recipe={minecraft_jj_planks={need=7,tag=""},minecraft_jj_stone_axe={need=1,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutminer={hasPattern=true,label="Bergwerk",recipe={minecraft_jj_planks={need=7,tag=""},minecraft_jj_stone_pickaxe={need=1,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutsawmill={hasPattern=true,label="Sägewerk",recipe={minecraft_jj_planks={need=5,tag=""},minecraft_jj_wooden_axe={need=3,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutshepherd={hasPattern=true,label="Schäferhütte",recipe={minecraft_jj_planks={need=7,tag=""},minecraft_jj_shears={need=1,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutsifter={hasPattern=true,label="Sieber",recipe={minecraft_jj_planks={need=5,tag=""},minecraft_jj_string={need=3,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutsmeltery={hasPattern=true,label="Eisenhütte",recipe={minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_planks={need=7,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutstonemason={hasPattern=true,label="Steinmetz",recipe={minecraft_jj_planks={need=5,tag=""},minecraft_jj_stonebrick={need=3,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutstonesmeltery={hasPattern=true,label="Steinschmelze",recipe={minecraft_jj_furnace={need=1,tag=""},minecraft_jj_planks={need=5,tag=""},minecraft_jj_stonebrick={need=2,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhutswineherder={hasPattern=true,label="Schweinehof",recipe={minecraft_jj_planks={need=7,tag=""},minecraft_jj_porkchop={need=1,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockhuttownhall={hasPattern=false,label="",recipe={}},
 minecolonies_jj_blockhutwarehouse={hasPattern=true,label="Lagerhaus",recipe={minecraft_jj_chest={need=1,tag=""},minecraft_jj_planks={need=7,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockinfoposter={hasPattern=false,label="",recipe={}},
 minecolonies_jj_blockminecoloniesrack={hasPattern=true,label="Regal",recipe={minecraft_jj_iron_bars={need=1,tag=""},minecraft_jj_planks={need=8,tag=""}}},
 minecolonies_jj_blockpostbox={hasPattern=true,label="Briefkasten",recipe={minecraft_jj_chest={need=3,tag=""},minecraft_jj_planks={need=5,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_blockwaypoint={hasPattern=true,label="Wegpunkt Platzhalter",recipe={minecraft_jj_planks={need=8,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_caliper={hasPattern=false,label="",recipe={}},
 minecolonies_jj_chiefsword={hasPattern=false,label="",recipe={}},
 minecolonies_jj_clipboard={hasPattern=true,label="Klemmbrett",recipe={minecraft_jj_leather={need=1,tag=""},minecraft_jj_stick={need=7,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 minecolonies_jj_compost={hasPattern=false,label="",recipe={}},
 minecolonies_jj_composted_dirt={hasPattern=true,label="Composted Dirt",recipe={minecolonies_jj_compost={need=1,tag=""},minecraft_jj_dirt={need=8,tag=""}}},
 minecolonies_jj_decorationcontroller={hasPattern=false,label="",recipe={}},
 minecolonies_jj_iron_scimitar={hasPattern=false,label="",recipe={}},
 minecolonies_jj_pirate_boots={hasPattern=false,label="",recipe={}},
 minecolonies_jj_pirate_cap={hasPattern=false,label="",recipe={}},
 minecolonies_jj_pirate_chest={hasPattern=false,label="",recipe={}},
 minecolonies_jj_pirate_hat={hasPattern=false,label="",recipe={}},
 minecolonies_jj_pirate_leggins={hasPattern=false,label="",recipe={}},
 minecolonies_jj_pirate_legs={hasPattern=false,label="",recipe={}},
 minecolonies_jj_pirate_shoes={hasPattern=false,label="",recipe={}},
 minecolonies_jj_pirate_top={hasPattern=false,label="",recipe={}},
 minecolonies_jj_resourcescroll={hasPattern=true,label="Werkstoff-Liste",recipe={minecraft_jj_leather={need=2,tag={}},minecraft_jj_stick={need=6,tag={}},structurize_jj_sceptergold={need=1,tag={}}}},
 minecolonies_jj_santa_hat={hasPattern=false,label="",recipe={}},
 minecolonies_jj_scepterguard={hasPattern=false,label="",recipe={}},
 minecolonies_jj_scepterlumberjack={hasPattern=false,label="",recipe={}},
 minecolonies_jj_scepterpermission={hasPattern=false,label="",recipe={}},
 minecolonies_jj_sizecity={hasPattern=false,label="",recipe={}},
 minecolonies_jj_sizemetropolis={hasPattern=false,label="",recipe={}},
 minecolonies_jj_sizesettlement={hasPattern=false,label="",recipe={}},
 minecolonies_jj_sizetown={hasPattern=false,label="",recipe={}},
 minecolonies_jj_supplycampdeployer={hasPattern=true,label="Versorgungscamp-Kiste",recipe={minecraft_jj_chest={need=5,tag=""}}},
 minecolonies_jj_supplychestdeployer={hasPattern=true,label="Versorgungsboot-Kiste",recipe={minecraft_jj_boat={need=5,tag=""}}},
 structurize_jj_blockcactusfence={hasPattern=true,label="Cactus Fence",recipe={minecraft_jj_stick={need=2,tag=""},structurize_jj_blockcactusplank={need=4,tag=""}}},
 structurize_jj_blockcactusfencegate={hasPattern=true,label="Cactus Fence Gate",recipe={minecraft_jj_stick={need=4,tag=""},structurize_jj_blockcactusplank={need=2,tag=""}}},
 structurize_jj_blockcactusplank={hasPattern=true,label="Cactus Plank",recipe={minecraft_jj_cactus={need=1,tag=""}}},
 structurize_jj_blockcactusslab_half={hasPattern=true,label="Cactus Slab",recipe={structurize_jj_blockcactusplank={need=3,tag=""}}},
 structurize_jj_blockcactusstair={hasPattern=true,label="tile.structurize.blockcactusstair.name",recipe={structurize_jj_blockcactusplank={need=6,tag=""}}},
 structurize_jj_blockcactustrapdoor={hasPattern=true,label="Cactus Trapdoor",recipe={structurize_jj_blockcactusplank={need=6,tag=""}}},
 structurize_jj_blockpaperwall={hasPattern=true,label="Paper wall",recipe={minecraft_jj_paper={need=3,tag=""},minecraft_jj_planks={need=6,tag=""}}},
 structurize_jj_blockpaperwall_jj_1={hasPattern=true,label="Paper wall",recipe={minecraft_jj_paper={need=3,tag=""},minecraft_jj_planks_jj_1={need=6,tag=""}}},
 structurize_jj_blockpaperwall_jj_2={hasPattern=true,label="Paper wall",recipe={minecraft_jj_paper={need=3,tag=""},minecraft_jj_planks_jj_2={need=6,tag=""}}},
 structurize_jj_blockpaperwall_jj_3={hasPattern=true,label="Paper wall",recipe={minecraft_jj_paper={need=3,tag=""},minecraft_jj_planks_jj_3={need=6,tag=""}}},
 structurize_jj_blockshingle_acacia={hasPattern=true,label="Acacia Shingle",recipe={minecraft_jj_brick={need=3,tag=""},minecraft_jj_planks_jj_4={need=1,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 structurize_jj_blockshingle_birch={hasPattern=true,label="Birch Shingle",recipe={minecraft_jj_brick={need=3,tag=""},minecraft_jj_planks_jj_2={need=1,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 structurize_jj_blockshingle_dark_oak={hasPattern=true,label="Dark Oak Shingle",recipe={minecraft_jj_brick={need=3,tag=""},minecraft_jj_planks_jj_5={need=1,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 structurize_jj_blockshingle_jungle={hasPattern=true,label="Jungle Shingle",recipe={minecraft_jj_brick={need=3,tag=""},minecraft_jj_planks_jj_3={need=1,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 structurize_jj_blockshingle_oak={hasPattern=true,label="Oak Shingle",recipe={minecraft_jj_brick={need=3,tag=""},minecraft_jj_planks={need=1,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 structurize_jj_blockshingle_spruce={hasPattern=true,label="Spruce Shingle",recipe={minecraft_jj_brick={need=3,tag=""},minecraft_jj_planks_jj_1={need=1,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 structurize_jj_blockshingleslab={hasPattern=true,label="Shingle slab",recipe={minecraft_jj_brick={need=3,tag=""},minecraft_jj_stick={need=3,tag=""}}},
 structurize_jj_blocksolidsubstitution={hasPattern=true,label="tile.structurize.blockSolidSubstitution.name",recipe={minecraft_jj_log={need=8,tag=""},structurize_jj_sceptersteel={need=1,tag=""}}},
 structurize_jj_blocksubstitution={hasPattern=true,label="Placeholderblock",recipe={minecraft_jj_planks={need=8,tag=""},structurize_jj_sceptersteel={need=1,tag=""}}},
 structurize_jj_blocktimberframe_acacia_doublecrossed={hasPattern=true,label="Acacia Crossed Timber Frame",recipe={structurize_jj_blocktimberframe_acacia_plain={need=1,tag=""}}},
 structurize_jj_blocktimberframe_acacia_downgated={hasPattern=true,label="Acacia Framed Timber Frame",recipe={structurize_jj_blocktimberframe_acacia_onecrossedrl={need=1,tag=""}}},
 structurize_jj_blocktimberframe_acacia_framed={hasPattern=true,label="Acacia Framed Timber Frame",recipe={structurize_jj_blocktimberframe_acacia_doublecrossed={need=1,tag=""}}},
 structurize_jj_blocktimberframe_acacia_gateframed={hasPattern=true,label="Acacia Framed Timber Frame",recipe={structurize_jj_blocktimberframe_acacia_sideframed={need=1,tag=""}}},
 structurize_jj_blocktimberframe_acacia_horizontalnocap={hasPattern=true,label="Acacia Horizontal Timber Frame",recipe={structurize_jj_blocktimberframe_acacia_horizontalplain={need=1,tag=""}}},
 structurize_jj_blocktimberframe_acacia_horizontalplain={hasPattern=true,label="Acacia Horizontal Timber Frame",recipe={structurize_jj_blocktimberframe_acacia_downgated={need=1,tag=""}}},
 structurize_jj_blocktimberframe_acacia_onecrossedlr={hasPattern=true,label="Acacia Right-Left Diagonal Timber Frame",recipe={structurize_jj_blocktimberframe_acacia_gateframed={need=1,tag=""}}},
 structurize_jj_blocktimberframe_acacia_onecrossedrl={hasPattern=true,label="Acacia Left-Right Diagonal Timber Frame",recipe={structurize_jj_blocktimberframe_acacia_onecrossedlr={need=1,tag=""}}},
 structurize_jj_blocktimberframe_acacia_plain={hasPattern=true,label="Acacia Plain Timber Frame",recipe={minecraft_jj_planks_jj_4={need=2,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 structurize_jj_blocktimberframe_acacia_sideframed={hasPattern=true,label="Acacia Framed Timber Frame",recipe={structurize_jj_blocktimberframe_acacia_framed={need=1,tag=""}}},
 structurize_jj_blocktimberframe_birch_doublecrossed={hasPattern=true,label="Birch Crossed Timber Frame",recipe={structurize_jj_blocktimberframe_birch_plain={need=1,tag=""}}},
 structurize_jj_blocktimberframe_birch_downgated={hasPattern=true,label="Birch Framed Timber Frame",recipe={structurize_jj_blocktimberframe_birch_onecrossedrl={need=1,tag=""}}},
 structurize_jj_blocktimberframe_birch_framed={hasPattern=true,label="Birch Framed Timber Frame",recipe={structurize_jj_blocktimberframe_birch_doublecrossed={need=1,tag=""}}},
 structurize_jj_blocktimberframe_birch_gateframed={hasPattern=true,label="Birch Framed Timber Frame",recipe={structurize_jj_blocktimberframe_birch_sideframed={need=1,tag=""}}},
 structurize_jj_blocktimberframe_birch_horizontalnocap={hasPattern=true,label="Birch Horizontal Timber Frame",recipe={structurize_jj_blocktimberframe_birch_horizontalplain={need=1,tag=""}}},
 structurize_jj_blocktimberframe_birch_horizontalplain={hasPattern=true,label="Birch Horizontal Timber Frame",recipe={structurize_jj_blocktimberframe_birch_downgated={need=1,tag=""}}},
 structurize_jj_blocktimberframe_birch_onecrossedlr={hasPattern=true,label="Birch Right-Left Diagonal Timber Frame",recipe={structurize_jj_blocktimberframe_birch_gateframed={need=1,tag=""}}},
 structurize_jj_blocktimberframe_birch_onecrossedrl={hasPattern=true,label="Birch Left-Right Diagonal Timber Frame",recipe={structurize_jj_blocktimberframe_birch_onecrossedlr={need=1,tag=""}}},
 structurize_jj_blocktimberframe_birch_plain={hasPattern=true,label="Birch Plain Timber Frame",recipe={minecraft_jj_planks_jj_2={need=2,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 structurize_jj_blocktimberframe_birch_sideframed={hasPattern=true,label="Birch Framed Timber Frame",recipe={structurize_jj_blocktimberframe_birch_framed={need=1,tag=""}}},
 structurize_jj_blocktimberframe_dark_oak_doublecrossed={hasPattern=true,label="Dark Oak Crossed Timber Frame",recipe={structurize_jj_blocktimberframe_dark_oak_plain={need=1,tag=""}}},
 structurize_jj_blocktimberframe_dark_oak_downgated={hasPattern=true,label="Dark Oak Framed Timber Frame",recipe={structurize_jj_blocktimberframe_dark_oak_onecrossedrl={need=1,tag=""}}},
 structurize_jj_blocktimberframe_dark_oak_framed={hasPattern=true,label="Dark Oak Framed Timber Frame",recipe={structurize_jj_blocktimberframe_dark_oak_doublecrossed={need=1,tag=""}}},
 structurize_jj_blocktimberframe_dark_oak_gateframed={hasPattern=true,label="Dark Oak Framed Timber Frame",recipe={structurize_jj_blocktimberframe_dark_oak_sideframed={need=1,tag=""}}},
 structurize_jj_blocktimberframe_dark_oak_horizontalnocap={hasPattern=true,label="Dark Oak Horizontal Timber Frame",recipe={structurize_jj_blocktimberframe_dark_oak_horizontalplain={need=1,tag=""}}},
 structurize_jj_blocktimberframe_dark_oak_horizontalplain={hasPattern=true,label="Dark Oak Horizontal Timber Frame",recipe={structurize_jj_blocktimberframe_dark_oak_downgated={need=1,tag=""}}},
 structurize_jj_blocktimberframe_dark_oak_onecrossedlr={hasPattern=true,label="Dark Oak Right-Left Diagonal Timber Frame",recipe={structurize_jj_blocktimberframe_dark_oak_gateframed={need=1,tag=""}}},
 structurize_jj_blocktimberframe_dark_oak_onecrossedrl={hasPattern=true,label="Dark Oak Left-Right Diagonal Timber Frame",recipe={structurize_jj_blocktimberframe_dark_oak_onecrossedlr={need=1,tag=""}}},
 structurize_jj_blocktimberframe_dark_oak_plain={hasPattern=true,label="Dark Oak Plain Timber Frame",recipe={minecraft_jj_planks_jj_5={need=2,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 structurize_jj_blocktimberframe_dark_oak_sideframed={hasPattern=true,label="Dark Oak Framed Timber Frame",recipe={structurize_jj_blocktimberframe_dark_oak_framed={need=1,tag=""}}},
 structurize_jj_blocktimberframe_jungle_doublecrossed={hasPattern=true,label="Jungle Crossed Timber Frame",recipe={structurize_jj_blocktimberframe_jungle_plain={need=1,tag=""}}},
 structurize_jj_blocktimberframe_jungle_downgated={hasPattern=true,label="Jungle Framed Timber Frame",recipe={structurize_jj_blocktimberframe_jungle_onecrossedrl={need=1,tag=""}}},
 structurize_jj_blocktimberframe_jungle_framed={hasPattern=true,label="Jungle Framed Timber Frame",recipe={structurize_jj_blocktimberframe_jungle_doublecrossed={need=1,tag=""}}},
 structurize_jj_blocktimberframe_jungle_gateframed={hasPattern=true,label="Jungle Framed Timber Frame",recipe={structurize_jj_blocktimberframe_jungle_sideframed={need=1,tag=""}}},
 structurize_jj_blocktimberframe_jungle_horizontalnocap={hasPattern=true,label="Jungle Horizontal Timber Frame",recipe={structurize_jj_blocktimberframe_jungle_horizontalplain={need=1,tag=""}}},
 structurize_jj_blocktimberframe_jungle_horizontalplain={hasPattern=true,label="Jungle Horizontal Timber Frame",recipe={structurize_jj_blocktimberframe_jungle_downgated={need=1,tag=""}}},
 structurize_jj_blocktimberframe_jungle_onecrossedlr={hasPattern=true,label="Jungle Right-Left Diagonal Timber Frame",recipe={structurize_jj_blocktimberframe_jungle_gateframed={need=1,tag=""}}},
 structurize_jj_blocktimberframe_jungle_onecrossedrl={hasPattern=true,label="Jungle Left-Right Diagonal Timber Frame",recipe={structurize_jj_blocktimberframe_jungle_onecrossedlr={need=1,tag=""}}},
 structurize_jj_blocktimberframe_jungle_plain={hasPattern=true,label="Jungle Plain Timber Frame",recipe={minecraft_jj_planks_jj_3={need=2,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 structurize_jj_blocktimberframe_jungle_sideframed={hasPattern=true,label="Jungle Framed Timber Frame",recipe={structurize_jj_blocktimberframe_jungle_framed={need=1,tag=""}}},
 structurize_jj_blocktimberframe_oak_doublecrossed={hasPattern=true,label="Oak Crossed Timber Frame",recipe={structurize_jj_blocktimberframe_oak_plain={need=1,tag=""}}},
 structurize_jj_blocktimberframe_oak_downgated={hasPattern=true,label="Oak Framed Timber Frame",recipe={structurize_jj_blocktimberframe_oak_onecrossedrl={need=1,tag=""}}},
 structurize_jj_blocktimberframe_oak_framed={hasPattern=true,label="Oak Framed Timber Frame",recipe={structurize_jj_blocktimberframe_oak_doublecrossed={need=1,tag=""}}},
 structurize_jj_blocktimberframe_oak_gateframed={hasPattern=true,label="Oak Framed Timber Frame",recipe={structurize_jj_blocktimberframe_oak_sideframed={need=1,tag=""}}},
 structurize_jj_blocktimberframe_oak_horizontalnocap={hasPattern=true,label="Oak Horizontal Timber Frame",recipe={structurize_jj_blocktimberframe_oak_horizontalplain={need=1,tag=""}}},
 structurize_jj_blocktimberframe_oak_horizontalplain={hasPattern=true,label="Oak Horizontal Timber Frame",recipe={structurize_jj_blocktimberframe_oak_downgated={need=1,tag=""}}},
 structurize_jj_blocktimberframe_oak_onecrossedlr={hasPattern=true,label="Oak Left-Right Diagonal Timber Frame",recipe={structurize_jj_blocktimberframe_oak_gateframed={need=1,tag=""}}},
 structurize_jj_blocktimberframe_oak_onecrossedrl={hasPattern=true,label="Oak Right-Left Diagonal Timber Frame",recipe={structurize_jj_blocktimberframe_oak_onecrossedlr={need=1,tag=""}}},
 structurize_jj_blocktimberframe_oak_plain={hasPattern=true,label="Oak Plain Timber Frame",recipe={minecraft_jj_planks={need=2,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 structurize_jj_blocktimberframe_oak_sideframed={hasPattern=true,label="Oak Framed Timber Frame",recipe={structurize_jj_blocktimberframe_oak_framed={need=1,tag=""}}},
 structurize_jj_blocktimberframe_spruce_doublecrossed={hasPattern=true,label="Spruce Crossed Timber Frame",recipe={structurize_jj_blocktimberframe_spruce_plain={need=1,tag=""}}},
 structurize_jj_blocktimberframe_spruce_downgated={hasPattern=true,label="Spruce Framed Timber Frame",recipe={structurize_jj_blocktimberframe_spruce_onecrossedrl={need=1,tag=""}}},
 structurize_jj_blocktimberframe_spruce_framed={hasPattern=true,label="Spruce Framed Timber Frame",recipe={structurize_jj_blocktimberframe_spruce_doublecrossed={need=1,tag=""}}},
 structurize_jj_blocktimberframe_spruce_gateframed={hasPattern=true,label="Spruce Framed Timber Frame",recipe={structurize_jj_blocktimberframe_spruce_sideframed={need=1,tag=""}}},
 structurize_jj_blocktimberframe_spruce_horizontalnocap={hasPattern=true,label="Spruce Horizontal Timber Frame",recipe={structurize_jj_blocktimberframe_spruce_horizontalplain={need=1,tag=""}}},
 structurize_jj_blocktimberframe_spruce_horizontalplain={hasPattern=true,label="Spruce Horizontal Timber Frame",recipe={structurize_jj_blocktimberframe_spruce_downgated={need=1,tag=""}}},
 structurize_jj_blocktimberframe_spruce_onecrossedlr={hasPattern=true,label="Spruce Right-Left Diagonal Timber Frame",recipe={structurize_jj_blocktimberframe_spruce_gateframed={need=1,tag=""}}},
 structurize_jj_blocktimberframe_spruce_onecrossedrl={hasPattern=true,label="Spruce Left-Right Diagonal Timber Frame",recipe={structurize_jj_blocktimberframe_spruce_onecrossedlr={need=1,tag=""}}},
 structurize_jj_blocktimberframe_spruce_plain={hasPattern=true,label="Spruce Plain Timber Frame",recipe={minecraft_jj_planks_jj_1={need=2,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 structurize_jj_blocktimberframe_spruce_sideframed={hasPattern=true,label="Spruce Framed Timber Frame",recipe={structurize_jj_blocktimberframe_spruce_framed={need=1,tag=""}}},
 structurize_jj_cactusdoor={hasPattern=true,label="Cactus Door",recipe={structurize_jj_blockcactusplank={need=6,tag=""}}},
 structurize_jj_caliper={hasPattern=false,label="",recipe={}},
 structurize_jj_multiblock={hasPattern=true,label="MultiBlock",recipe={minecraft_jj_piston={need=3,tag=""},minecraft_jj_redstone_block={need=2,tag=""},minecraft_jj_stone={need=3,tag=""},structurize_jj_sceptergold={need=1,tag=""}}},
 structurize_jj_sceptergold={hasPattern=true,label="Building Tool",recipe={minecraft_jj_cobblestone={need=1,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 structurize_jj_sceptersteel={hasPattern=true,label="Scan Tool",recipe={minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 structurize_jj_shapetool={hasPattern=false,label="",recipe={}}
 }