return {
 fairylights_jj_garland={hasPattern=true,label="Rebengirlande",recipe={minecraft_jj_iron_ingot={need=2,tag=""},minecraft_jj_vine={need=1,tag=""}}},
 fairylights_jj_hanging_lights={hasPattern=false,label="",recipe={}},
 fairylights_jj_ladder={hasPattern=true,label="Leiter",recipe={minecraft_jj_ladder={need=3,tag=""},minecraft_jj_stick={need=3,tag=""}}},
 fairylights_jj_letter_bunting={hasPattern=false,label="",recipe={}},
 fairylights_jj_light={hasPattern=true,label="Schwarz Feenlicht",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_1={hasPattern=true,label="Rot Feenlicht",recipe={minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_10={hasPattern=true,label="Hellgrün Feenlicht",recipe={minecraft_jj_dye_jj_10={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_11={hasPattern=true,label="Gelb Feenlicht",recipe={minecraft_jj_dye_jj_11={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_112={hasPattern=true,label="Schwarz Kürbislaterne",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_pumpkin={need=1,tag=""},minecraft_jj_torch={need=2,tag=""},minecraft_jj_wooden_slab={need=2,tag=""}}},
 fairylights_jj_light_jj_113={hasPattern=true,label="Rot Kürbislaterne",recipe={minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_pumpkin={need=1,tag=""},minecraft_jj_torch={need=2,tag=""},minecraft_jj_wooden_slab={need=2,tag=""}}},
 fairylights_jj_light_jj_114={hasPattern=true,label="Grün Kürbislaterne",recipe={minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_pumpkin={need=1,tag=""},minecraft_jj_torch={need=2,tag=""},minecraft_jj_wooden_slab={need=2,tag=""}}},
 fairylights_jj_light_jj_115={hasPattern=true,label="Braun Kürbislaterne",recipe={minecraft_jj_dye_jj_3={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_pumpkin={need=1,tag=""},minecraft_jj_torch={need=2,tag=""},minecraft_jj_wooden_slab={need=2,tag=""}}},
 fairylights_jj_light_jj_116={hasPattern=true,label="Blau Kürbislaterne",recipe={minecraft_jj_dye_jj_4={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_pumpkin={need=1,tag=""},minecraft_jj_torch={need=2,tag=""},minecraft_jj_wooden_slab={need=2,tag=""}}},
 fairylights_jj_light_jj_117={hasPattern=true,label="Lila Kürbislaterne",recipe={minecraft_jj_dye_jj_5={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_pumpkin={need=1,tag=""},minecraft_jj_torch={need=2,tag=""},minecraft_jj_wooden_slab={need=2,tag=""}}},
 fairylights_jj_light_jj_118={hasPattern=true,label="Zyan Kürbislaterne",recipe={minecraft_jj_dye_jj_6={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_pumpkin={need=1,tag=""},minecraft_jj_torch={need=2,tag=""},minecraft_jj_wooden_slab={need=2,tag=""}}},
 fairylights_jj_light_jj_119={hasPattern=true,label="Hellgrau Kürbislaterne",recipe={minecraft_jj_dye_jj_7={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_pumpkin={need=1,tag=""},minecraft_jj_torch={need=2,tag=""},minecraft_jj_wooden_slab={need=2,tag=""}}},
 fairylights_jj_light_jj_12={hasPattern=true,label="Hellblau Feenlicht",recipe={minecraft_jj_dye_jj_12={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_120={hasPattern=true,label="Grau Kürbislaterne",recipe={minecraft_jj_dye_jj_8={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_pumpkin={need=1,tag=""},minecraft_jj_torch={need=2,tag=""},minecraft_jj_wooden_slab={need=2,tag=""}}},
 fairylights_jj_light_jj_121={hasPattern=true,label="Rosa Kürbislaterne",recipe={minecraft_jj_dye_jj_9={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_pumpkin={need=1,tag=""},minecraft_jj_torch={need=2,tag=""},minecraft_jj_wooden_slab={need=2,tag=""}}},
 fairylights_jj_light_jj_122={hasPattern=true,label="Hellgrün Kürbislaterne",recipe={minecraft_jj_dye_jj_10={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_pumpkin={need=1,tag=""},minecraft_jj_torch={need=2,tag=""},minecraft_jj_wooden_slab={need=2,tag=""}}},
 fairylights_jj_light_jj_123={hasPattern=true,label="Gelb Kürbislaterne",recipe={minecraft_jj_dye_jj_11={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_pumpkin={need=1,tag=""},minecraft_jj_torch={need=2,tag=""},minecraft_jj_wooden_slab={need=2,tag=""}}},
 fairylights_jj_light_jj_124={hasPattern=true,label="Hellblau Kürbislaterne",recipe={minecraft_jj_dye_jj_12={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_pumpkin={need=1,tag=""},minecraft_jj_torch={need=2,tag=""},minecraft_jj_wooden_slab={need=2,tag=""}}},
 fairylights_jj_light_jj_125={hasPattern=true,label="Purpur Kürbislaterne",recipe={minecraft_jj_dye_jj_13={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_pumpkin={need=1,tag=""},minecraft_jj_torch={need=2,tag=""},minecraft_jj_wooden_slab={need=2,tag=""}}},
 fairylights_jj_light_jj_126={hasPattern=true,label="Orange Kürbislaterne",recipe={minecraft_jj_dye_jj_14={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_pumpkin={need=1,tag=""},minecraft_jj_torch={need=2,tag=""},minecraft_jj_wooden_slab={need=2,tag=""}}},
 fairylights_jj_light_jj_127={hasPattern=true,label="Weiß Kürbislaterne",recipe={minecraft_jj_dye_jj_15={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_pumpkin={need=1,tag=""},minecraft_jj_torch={need=2,tag=""},minecraft_jj_wooden_slab={need=2,tag=""}}},
 fairylights_jj_light_jj_128={hasPattern=true,label="Schwarz Schädellicht",recipe={minecraft_jj_bone={need=1,tag=""},minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_129={hasPattern=true,label="Rot Schädellicht",recipe={minecraft_jj_bone={need=1,tag=""},minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_13={hasPattern=true,label="Purpur Feenlicht",recipe={minecraft_jj_dye_jj_13={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_130={hasPattern=true,label="Grün Schädellicht",recipe={minecraft_jj_bone={need=1,tag=""},minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_131={hasPattern=true,label="Braun Schädellicht",recipe={minecraft_jj_bone={need=1,tag=""},minecraft_jj_dye_jj_3={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_132={hasPattern=true,label="Blau Schädellicht",recipe={minecraft_jj_bone={need=1,tag=""},minecraft_jj_dye_jj_4={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_133={hasPattern=true,label="Lila Schädellicht",recipe={minecraft_jj_bone={need=1,tag=""},minecraft_jj_dye_jj_5={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_134={hasPattern=true,label="Zyan Schädellicht",recipe={minecraft_jj_bone={need=1,tag=""},minecraft_jj_dye_jj_6={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_135={hasPattern=true,label="Hellgrau Schädellicht",recipe={minecraft_jj_bone={need=1,tag=""},minecraft_jj_dye_jj_7={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_136={hasPattern=true,label="Grau Schädellicht",recipe={minecraft_jj_bone={need=1,tag=""},minecraft_jj_dye_jj_8={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_137={hasPattern=true,label="Rosa Schädellicht",recipe={minecraft_jj_bone={need=1,tag=""},minecraft_jj_dye_jj_9={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_138={hasPattern=true,label="Hellgrün Schädellicht",recipe={minecraft_jj_bone={need=1,tag=""},minecraft_jj_dye_jj_10={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_139={hasPattern=true,label="Gelb Schädellicht",recipe={minecraft_jj_bone={need=1,tag=""},minecraft_jj_dye_jj_11={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_14={hasPattern=true,label="Orange Feenlicht",recipe={minecraft_jj_dye_jj_14={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_140={hasPattern=true,label="Hellblau Schädellicht",recipe={minecraft_jj_bone={need=1,tag=""},minecraft_jj_dye_jj_12={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_141={hasPattern=true,label="Purpur Schädellicht",recipe={minecraft_jj_bone={need=1,tag=""},minecraft_jj_dye_jj_13={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_142={hasPattern=true,label="Orange Schädellicht",recipe={minecraft_jj_bone={need=1,tag=""},minecraft_jj_dye_jj_14={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_143={hasPattern=true,label="Weiß Schädellicht",recipe={minecraft_jj_bone={need=1,tag=""},minecraft_jj_dye_jj_15={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_144={hasPattern=true,label="Schwarz Geisterlicht",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_145={hasPattern=true,label="Rot Geisterlicht",recipe={minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_146={hasPattern=true,label="Grün Geisterlicht",recipe={minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_147={hasPattern=true,label="Braun Geisterlicht",recipe={minecraft_jj_dye_jj_3={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_148={hasPattern=true,label="Blau Geisterlicht",recipe={minecraft_jj_dye_jj_4={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_149={hasPattern=true,label="Lila Geisterlicht",recipe={minecraft_jj_dye_jj_5={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_15={hasPattern=true,label="Weiß Feenlicht",recipe={minecraft_jj_dye_jj_15={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_150={hasPattern=true,label="Zyan Geisterlicht",recipe={minecraft_jj_dye_jj_6={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_151={hasPattern=true,label="Hellgrau Geisterlicht",recipe={minecraft_jj_dye_jj_7={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_152={hasPattern=true,label="Grau Geisterlicht",recipe={minecraft_jj_dye_jj_8={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_153={hasPattern=true,label="Rosa Geisterlicht",recipe={minecraft_jj_dye_jj_9={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_154={hasPattern=true,label="Hellgrün Geisterlicht",recipe={minecraft_jj_dye_jj_10={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_155={hasPattern=true,label="Gelb Geisterlicht",recipe={minecraft_jj_dye_jj_11={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_156={hasPattern=true,label="Hellblau Geisterlicht",recipe={minecraft_jj_dye_jj_12={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_157={hasPattern=true,label="Purpur Geisterlicht",recipe={minecraft_jj_dye_jj_13={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_158={hasPattern=true,label="Orange Geisterlicht",recipe={minecraft_jj_dye_jj_14={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_159={hasPattern=true,label="Weiß Geisterlicht",recipe={minecraft_jj_dye_jj_15={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_16={hasPattern=true,label="Schwarz Papierlaterne",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_paper={need=5,tag=""}}},
 fairylights_jj_light_jj_160={hasPattern=true,label="Schwarz Spinnenlicht",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_spider_eye={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_web={need=2,tag=""}}},
 fairylights_jj_light_jj_161={hasPattern=true,label="Rot Spinnenlicht",recipe={minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_spider_eye={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_web={need=2,tag=""}}},
 fairylights_jj_light_jj_162={hasPattern=true,label="Grün Spinnenlicht",recipe={minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_spider_eye={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_web={need=2,tag=""}}},
 fairylights_jj_light_jj_163={hasPattern=true,label="Braun Spinnenlicht",recipe={minecraft_jj_dye_jj_3={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_spider_eye={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_web={need=2,tag=""}}},
 fairylights_jj_light_jj_164={hasPattern=true,label="Blau Spinnenlicht",recipe={minecraft_jj_dye_jj_4={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_spider_eye={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_web={need=2,tag=""}}},
 fairylights_jj_light_jj_165={hasPattern=true,label="Lila Spinnenlicht",recipe={minecraft_jj_dye_jj_5={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_spider_eye={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_web={need=2,tag=""}}},
 fairylights_jj_light_jj_166={hasPattern=true,label="Zyan Spinnenlicht",recipe={minecraft_jj_dye_jj_6={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_spider_eye={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_web={need=2,tag=""}}},
 fairylights_jj_light_jj_167={hasPattern=true,label="Hellgrau Spinnenlicht",recipe={minecraft_jj_dye_jj_7={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_spider_eye={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_web={need=2,tag=""}}},
 fairylights_jj_light_jj_168={hasPattern=true,label="Grau Spinnenlicht",recipe={minecraft_jj_dye_jj_8={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_spider_eye={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_web={need=2,tag=""}}},
 fairylights_jj_light_jj_169={hasPattern=true,label="Rosa Spinnenlicht",recipe={minecraft_jj_dye_jj_9={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_spider_eye={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_web={need=2,tag=""}}},
 fairylights_jj_light_jj_17={hasPattern=true,label="Rot Papierlaterne",recipe={minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_paper={need=5,tag=""}}},
 fairylights_jj_light_jj_170={hasPattern=true,label="Hellgrün Spinnenlicht",recipe={minecraft_jj_dye_jj_10={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_spider_eye={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_web={need=2,tag=""}}},
 fairylights_jj_light_jj_171={hasPattern=true,label="Gelb Spinnenlicht",recipe={minecraft_jj_dye_jj_11={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_spider_eye={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_web={need=2,tag=""}}},
 fairylights_jj_light_jj_172={hasPattern=true,label="Hellblau Spinnenlicht",recipe={minecraft_jj_dye_jj_12={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_spider_eye={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_web={need=2,tag=""}}},
 fairylights_jj_light_jj_173={hasPattern=true,label="Purpur Spinnenlicht",recipe={minecraft_jj_dye_jj_13={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_spider_eye={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_web={need=2,tag=""}}},
 fairylights_jj_light_jj_174={hasPattern=true,label="Orange Spinnenlicht",recipe={minecraft_jj_dye_jj_14={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_spider_eye={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_web={need=2,tag=""}}},
 fairylights_jj_light_jj_175={hasPattern=true,label="Weiß Spinnenlicht",recipe={minecraft_jj_dye_jj_15={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_spider_eye={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_web={need=2,tag=""}}},
 fairylights_jj_light_jj_176={hasPattern=true,label="Schwarz Hexenlicht",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_glass_bottle={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_stick={need=1,tag=""},minecraft_jj_wheat={need=1,tag=""}}},
 fairylights_jj_light_jj_177={hasPattern=true,label="Rot Hexenlicht",recipe={minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_glass_bottle={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_stick={need=1,tag=""},minecraft_jj_wheat={need=1,tag=""}}},
 fairylights_jj_light_jj_178={hasPattern=true,label="Grün Hexenlicht",recipe={minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_glass_bottle={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_stick={need=1,tag=""},minecraft_jj_wheat={need=1,tag=""}}},
 fairylights_jj_light_jj_179={hasPattern=true,label="Braun Hexenlicht",recipe={minecraft_jj_dye_jj_3={need=1,tag=""},minecraft_jj_glass_bottle={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_stick={need=1,tag=""},minecraft_jj_wheat={need=1,tag=""}}},
 fairylights_jj_light_jj_18={hasPattern=true,label="Grün Papierlaterne",recipe={minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_paper={need=5,tag=""}}},
 fairylights_jj_light_jj_180={hasPattern=true,label="Blau Hexenlicht",recipe={minecraft_jj_dye_jj_4={need=1,tag=""},minecraft_jj_glass_bottle={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_stick={need=1,tag=""},minecraft_jj_wheat={need=1,tag=""}}},
 fairylights_jj_light_jj_181={hasPattern=true,label="Lila Hexenlicht",recipe={minecraft_jj_dye_jj_5={need=1,tag=""},minecraft_jj_glass_bottle={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_stick={need=1,tag=""},minecraft_jj_wheat={need=1,tag=""}}},
 fairylights_jj_light_jj_182={hasPattern=true,label="Zyan Hexenlicht",recipe={minecraft_jj_dye_jj_6={need=1,tag=""},minecraft_jj_glass_bottle={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_stick={need=1,tag=""},minecraft_jj_wheat={need=1,tag=""}}},
 fairylights_jj_light_jj_183={hasPattern=true,label="Hellgrau Hexenlicht",recipe={minecraft_jj_dye_jj_7={need=1,tag=""},minecraft_jj_glass_bottle={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_stick={need=1,tag=""},minecraft_jj_wheat={need=1,tag=""}}},
 fairylights_jj_light_jj_184={hasPattern=true,label="Grau Hexenlicht",recipe={minecraft_jj_dye_jj_8={need=1,tag=""},minecraft_jj_glass_bottle={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_stick={need=1,tag=""},minecraft_jj_wheat={need=1,tag=""}}},
 fairylights_jj_light_jj_185={hasPattern=true,label="Rosa Hexenlicht",recipe={minecraft_jj_dye_jj_9={need=1,tag=""},minecraft_jj_glass_bottle={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_stick={need=1,tag=""},minecraft_jj_wheat={need=1,tag=""}}},
 fairylights_jj_light_jj_186={hasPattern=true,label="Hellgrün Hexenlicht",recipe={minecraft_jj_dye_jj_10={need=1,tag=""},minecraft_jj_glass_bottle={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_stick={need=1,tag=""},minecraft_jj_wheat={need=1,tag=""}}},
 fairylights_jj_light_jj_187={hasPattern=true,label="Gelb Hexenlicht",recipe={minecraft_jj_dye_jj_11={need=1,tag=""},minecraft_jj_glass_bottle={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_stick={need=1,tag=""},minecraft_jj_wheat={need=1,tag=""}}},
 fairylights_jj_light_jj_188={hasPattern=true,label="Hellblau Hexenlicht",recipe={minecraft_jj_dye_jj_12={need=1,tag=""},minecraft_jj_glass_bottle={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_stick={need=1,tag=""},minecraft_jj_wheat={need=1,tag=""}}},
 fairylights_jj_light_jj_189={hasPattern=true,label="Purpur Hexenlicht",recipe={minecraft_jj_dye_jj_13={need=1,tag=""},minecraft_jj_glass_bottle={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_stick={need=1,tag=""},minecraft_jj_wheat={need=1,tag=""}}},
 fairylights_jj_light_jj_19={hasPattern=true,label="Braun Papierlaterne",recipe={minecraft_jj_dye_jj_3={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_paper={need=5,tag=""}}},
 fairylights_jj_light_jj_190={hasPattern=true,label="Orange Hexenlicht",recipe={minecraft_jj_dye_jj_14={need=1,tag=""},minecraft_jj_glass_bottle={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_stick={need=1,tag=""},minecraft_jj_wheat={need=1,tag=""}}},
 fairylights_jj_light_jj_191={hasPattern=true,label="Weiß Hexenlicht",recipe={minecraft_jj_dye_jj_15={need=1,tag=""},minecraft_jj_glass_bottle={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_stick={need=1,tag=""},minecraft_jj_wheat={need=1,tag=""}}},
 fairylights_jj_light_jj_192={hasPattern=true,label="Schwarz Schneeflockenlicht",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_snowball={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_193={hasPattern=true,label="Rot Schneeflockenlicht",recipe={minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_snowball={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_194={hasPattern=true,label="Grün Schneeflockenlicht",recipe={minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_snowball={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_195={hasPattern=true,label="Braun Schneeflockenlicht",recipe={minecraft_jj_dye_jj_3={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_snowball={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_196={hasPattern=true,label="Blau Schneeflockenlicht",recipe={minecraft_jj_dye_jj_4={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_snowball={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_197={hasPattern=true,label="Lila Schneeflockenlicht",recipe={minecraft_jj_dye_jj_5={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_snowball={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_198={hasPattern=true,label="Zyan Schneeflockenlicht",recipe={minecraft_jj_dye_jj_6={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_snowball={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_199={hasPattern=true,label="Hellgrau Schneeflockenlicht",recipe={minecraft_jj_dye_jj_7={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_snowball={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_2={hasPattern=true,label="Grün Feenlicht",recipe={minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_20={hasPattern=true,label="Blau Papierlaterne",recipe={minecraft_jj_dye_jj_4={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_paper={need=5,tag=""}}},
 fairylights_jj_light_jj_200={hasPattern=true,label="Grau Schneeflockenlicht",recipe={minecraft_jj_dye_jj_8={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_snowball={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_201={hasPattern=true,label="Rosa Schneeflockenlicht",recipe={minecraft_jj_dye_jj_9={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_snowball={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_202={hasPattern=true,label="Hellgrün Schneeflockenlicht",recipe={minecraft_jj_dye_jj_10={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_snowball={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_203={hasPattern=true,label="Gelb Schneeflockenlicht",recipe={minecraft_jj_dye_jj_11={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_snowball={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_204={hasPattern=true,label="Hellblau Schneeflockenlicht",recipe={minecraft_jj_dye_jj_12={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_snowball={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_205={hasPattern=true,label="Purpur Schneeflockenlicht",recipe={minecraft_jj_dye_jj_13={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_snowball={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_206={hasPattern=true,label="Orange Schneeflockenlicht",recipe={minecraft_jj_dye_jj_14={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_snowball={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_207={hasPattern=true,label="Weiß Schneeflockenlicht",recipe={minecraft_jj_dye_jj_15={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_snowball={need=2,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 fairylights_jj_light_jj_208={hasPattern=true,label="Schwarz Eiswürfellicht",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_glass_pane={need=2,tag=""},minecraft_jj_ice={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 fairylights_jj_light_jj_209={hasPattern=true,label="Rot Eiswürfellicht",recipe={minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_glass_pane={need=2,tag=""},minecraft_jj_ice={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 fairylights_jj_light_jj_21={hasPattern=true,label="Lila Papierlaterne",recipe={minecraft_jj_dye_jj_5={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_paper={need=5,tag=""}}},
 fairylights_jj_light_jj_210={hasPattern=true,label="Grün Eiswürfellicht",recipe={minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_glass_pane={need=2,tag=""},minecraft_jj_ice={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 fairylights_jj_light_jj_211={hasPattern=true,label="Braun Eiswürfellicht",recipe={minecraft_jj_dye_jj_3={need=1,tag=""},minecraft_jj_glass_pane={need=2,tag=""},minecraft_jj_ice={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 fairylights_jj_light_jj_212={hasPattern=true,label="Blau Eiswürfellicht",recipe={minecraft_jj_dye_jj_4={need=1,tag=""},minecraft_jj_glass_pane={need=2,tag=""},minecraft_jj_ice={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 fairylights_jj_light_jj_213={hasPattern=true,label="Lila Eiswürfellicht",recipe={minecraft_jj_dye_jj_5={need=1,tag=""},minecraft_jj_glass_pane={need=2,tag=""},minecraft_jj_ice={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 fairylights_jj_light_jj_214={hasPattern=true,label="Zyan Eiswürfellicht",recipe={minecraft_jj_dye_jj_6={need=1,tag=""},minecraft_jj_glass_pane={need=2,tag=""},minecraft_jj_ice={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 fairylights_jj_light_jj_215={hasPattern=true,label="Hellgrau Eiswürfellicht",recipe={minecraft_jj_dye_jj_7={need=1,tag=""},minecraft_jj_glass_pane={need=2,tag=""},minecraft_jj_ice={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 fairylights_jj_light_jj_216={hasPattern=true,label="Grau Eiswürfellicht",recipe={minecraft_jj_dye_jj_8={need=1,tag=""},minecraft_jj_glass_pane={need=2,tag=""},minecraft_jj_ice={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 fairylights_jj_light_jj_217={hasPattern=true,label="Rosa Eiswürfellicht",recipe={minecraft_jj_dye_jj_9={need=1,tag=""},minecraft_jj_glass_pane={need=2,tag=""},minecraft_jj_ice={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 fairylights_jj_light_jj_218={hasPattern=true,label="Hellgrün Eiswürfellicht",recipe={minecraft_jj_dye_jj_10={need=1,tag=""},minecraft_jj_glass_pane={need=2,tag=""},minecraft_jj_ice={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 fairylights_jj_light_jj_219={hasPattern=true,label="Gelb Eiswürfellicht",recipe={minecraft_jj_dye_jj_11={need=1,tag=""},minecraft_jj_glass_pane={need=2,tag=""},minecraft_jj_ice={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 fairylights_jj_light_jj_22={hasPattern=true,label="Zyan Papierlaterne",recipe={minecraft_jj_dye_jj_6={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_paper={need=5,tag=""}}},
 fairylights_jj_light_jj_220={hasPattern=true,label="Hellblau Eiswürfellicht",recipe={minecraft_jj_dye_jj_12={need=1,tag=""},minecraft_jj_glass_pane={need=2,tag=""},minecraft_jj_ice={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 fairylights_jj_light_jj_221={hasPattern=true,label="Purpur Eiswürfellicht",recipe={minecraft_jj_dye_jj_13={need=1,tag=""},minecraft_jj_glass_pane={need=2,tag=""},minecraft_jj_ice={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 fairylights_jj_light_jj_222={hasPattern=true,label="Orange Eiswürfellicht",recipe={minecraft_jj_dye_jj_14={need=1,tag=""},minecraft_jj_glass_pane={need=2,tag=""},minecraft_jj_ice={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 fairylights_jj_light_jj_223={hasPattern=true,label="Weiß Eiswürfellicht",recipe={minecraft_jj_dye_jj_15={need=1,tag=""},minecraft_jj_glass_pane={need=2,tag=""},minecraft_jj_ice={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 fairylights_jj_light_jj_224={hasPattern=true,label="Schwarz Meteorlicht",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_glowstone_dust={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=1,tag=""}}},
 fairylights_jj_light_jj_225={hasPattern=true,label="Rot Meteorlicht",recipe={minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_glowstone_dust={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=1,tag=""}}},
 fairylights_jj_light_jj_226={hasPattern=true,label="Grün Meteorlicht",recipe={minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_glowstone_dust={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=1,tag=""}}},
 fairylights_jj_light_jj_227={hasPattern=true,label="Braun Meteorlicht",recipe={minecraft_jj_dye_jj_3={need=1,tag=""},minecraft_jj_glowstone_dust={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=1,tag=""}}},
 fairylights_jj_light_jj_228={hasPattern=true,label="Blau Meteorlicht",recipe={minecraft_jj_dye_jj_4={need=1,tag=""},minecraft_jj_glowstone_dust={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=1,tag=""}}},
 fairylights_jj_light_jj_229={hasPattern=true,label="Lila Meteorlicht",recipe={minecraft_jj_dye_jj_5={need=1,tag=""},minecraft_jj_glowstone_dust={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=1,tag=""}}},
 fairylights_jj_light_jj_23={hasPattern=true,label="Hellgrau Papierlaterne",recipe={minecraft_jj_dye_jj_7={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_paper={need=5,tag=""}}},
 fairylights_jj_light_jj_230={hasPattern=true,label="Zyan Meteorlicht",recipe={minecraft_jj_dye_jj_6={need=1,tag=""},minecraft_jj_glowstone_dust={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=1,tag=""}}},
 fairylights_jj_light_jj_231={hasPattern=true,label="Hellgrau Meteorlicht",recipe={minecraft_jj_dye_jj_7={need=1,tag=""},minecraft_jj_glowstone_dust={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=1,tag=""}}},
 fairylights_jj_light_jj_232={hasPattern=true,label="Grau Meteorlicht",recipe={minecraft_jj_dye_jj_8={need=1,tag=""},minecraft_jj_glowstone_dust={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=1,tag=""}}},
 fairylights_jj_light_jj_233={hasPattern=true,label="Rosa Meteorlicht",recipe={minecraft_jj_dye_jj_9={need=1,tag=""},minecraft_jj_glowstone_dust={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=1,tag=""}}},
 fairylights_jj_light_jj_234={hasPattern=true,label="Hellgrün Meteorlicht",recipe={minecraft_jj_dye_jj_10={need=1,tag=""},minecraft_jj_glowstone_dust={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=1,tag=""}}},
 fairylights_jj_light_jj_235={hasPattern=true,label="Gelb Meteorlicht",recipe={minecraft_jj_dye_jj_11={need=1,tag=""},minecraft_jj_glowstone_dust={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=1,tag=""}}},
 fairylights_jj_light_jj_236={hasPattern=true,label="Hellblau Meteorlicht",recipe={minecraft_jj_dye_jj_12={need=1,tag=""},minecraft_jj_glowstone_dust={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=1,tag=""}}},
 fairylights_jj_light_jj_237={hasPattern=true,label="Purpur Meteorlicht",recipe={minecraft_jj_dye_jj_13={need=1,tag=""},minecraft_jj_glowstone_dust={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=1,tag=""}}},
 fairylights_jj_light_jj_238={hasPattern=true,label="Orange Meteorlicht",recipe={minecraft_jj_dye_jj_14={need=1,tag=""},minecraft_jj_glowstone_dust={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=1,tag=""}}},
 fairylights_jj_light_jj_239={hasPattern=true,label="Weiß Meteorlicht",recipe={minecraft_jj_dye_jj_15={need=1,tag=""},minecraft_jj_glowstone_dust={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=1,tag=""}}},
 fairylights_jj_light_jj_24={hasPattern=true,label="Grau Papierlaterne",recipe={minecraft_jj_dye_jj_8={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_paper={need=5,tag=""}}},
 fairylights_jj_light_jj_25={hasPattern=true,label="Rosa Papierlaterne",recipe={minecraft_jj_dye_jj_9={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_paper={need=5,tag=""}}},
 fairylights_jj_light_jj_26={hasPattern=true,label="Hellgrün Papierlaterne",recipe={minecraft_jj_dye_jj_10={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_paper={need=5,tag=""}}},
 fairylights_jj_light_jj_27={hasPattern=true,label="Gelb Papierlaterne",recipe={minecraft_jj_dye_jj_11={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_paper={need=5,tag=""}}},
 fairylights_jj_light_jj_28={hasPattern=true,label="Hellblau Papierlaterne",recipe={minecraft_jj_dye_jj_12={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_paper={need=5,tag=""}}},
 fairylights_jj_light_jj_29={hasPattern=true,label="Purpur Papierlaterne",recipe={minecraft_jj_dye_jj_13={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_paper={need=5,tag=""}}},
 fairylights_jj_light_jj_3={hasPattern=true,label="Braun Feenlicht",recipe={minecraft_jj_dye_jj_3={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_30={hasPattern=true,label="Orange Papierlaterne",recipe={minecraft_jj_dye_jj_14={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_paper={need=5,tag=""}}},
 fairylights_jj_light_jj_31={hasPattern=true,label="Weiß Papierlaterne",recipe={minecraft_jj_dye_jj_15={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_paper={need=5,tag=""}}},
 fairylights_jj_light_jj_32={hasPattern=true,label="Schwarz Ballonlaterne",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_wool={need=1,tag=""}}},
 fairylights_jj_light_jj_33={hasPattern=true,label="Rot Ballonlaterne",recipe={minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_wool={need=1,tag=""}}},
 fairylights_jj_light_jj_34={hasPattern=true,label="Grün Ballonlaterne",recipe={minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_wool={need=1,tag=""}}},
 fairylights_jj_light_jj_35={hasPattern=true,label="Braun Ballonlaterne",recipe={minecraft_jj_dye_jj_3={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_wool={need=1,tag=""}}},
 fairylights_jj_light_jj_36={hasPattern=true,label="Blau Ballonlaterne",recipe={minecraft_jj_dye_jj_4={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_wool={need=1,tag=""}}},
 fairylights_jj_light_jj_37={hasPattern=true,label="Lila Ballonlaterne",recipe={minecraft_jj_dye_jj_5={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_wool={need=1,tag=""}}},
 fairylights_jj_light_jj_38={hasPattern=true,label="Zyan Ballonlaterne",recipe={minecraft_jj_dye_jj_6={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_wool={need=1,tag=""}}},
 fairylights_jj_light_jj_39={hasPattern=true,label="Hellgrau Ballonlaterne",recipe={minecraft_jj_dye_jj_7={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_wool={need=1,tag=""}}},
 fairylights_jj_light_jj_4={hasPattern=true,label="Blau Feenlicht",recipe={minecraft_jj_dye_jj_4={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_40={hasPattern=true,label="Grau Ballonlaterne",recipe={minecraft_jj_dye_jj_8={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_wool={need=1,tag=""}}},
 fairylights_jj_light_jj_41={hasPattern=true,label="Rosa Ballonlaterne",recipe={minecraft_jj_dye_jj_9={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_wool={need=1,tag=""}}},
 fairylights_jj_light_jj_42={hasPattern=true,label="Hellgrün Ballonlaterne",recipe={minecraft_jj_dye_jj_10={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_wool={need=1,tag=""}}},
 fairylights_jj_light_jj_43={hasPattern=true,label="Gelb Ballonlaterne",recipe={minecraft_jj_dye_jj_11={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_wool={need=1,tag=""}}},
 fairylights_jj_light_jj_44={hasPattern=true,label="Hellblau Ballonlaterne",recipe={minecraft_jj_dye_jj_12={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_wool={need=1,tag=""}}},
 fairylights_jj_light_jj_45={hasPattern=true,label="Purpur Ballonlaterne",recipe={minecraft_jj_dye_jj_13={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_wool={need=1,tag=""}}},
 fairylights_jj_light_jj_46={hasPattern=true,label="Orange Ballonlaterne",recipe={minecraft_jj_dye_jj_14={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_wool={need=1,tag=""}}},
 fairylights_jj_light_jj_47={hasPattern=true,label="Weiß Ballonlaterne",recipe={minecraft_jj_dye_jj_15={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_string={need=2,tag=""},minecraft_jj_wool={need=1,tag=""}}},
 fairylights_jj_light_jj_48={hasPattern=true,label="Schwarz Blumenlicht",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_red_flower={need=1,tag=""},minecraft_jj_red_flower_jj_1={need=1,tag=""},minecraft_jj_yellow_flower={need=1,tag=""}}},
 fairylights_jj_light_jj_49={hasPattern=true,label="Rot Blumenlicht",recipe={minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_red_flower={need=1,tag=""},minecraft_jj_red_flower_jj_1={need=1,tag=""},minecraft_jj_yellow_flower={need=1,tag=""}}},
 fairylights_jj_light_jj_5={hasPattern=true,label="Lila Feenlicht",recipe={minecraft_jj_dye_jj_5={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_50={hasPattern=true,label="Grün Blumenlicht",recipe={minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_red_flower={need=1,tag=""},minecraft_jj_red_flower_jj_1={need=1,tag=""},minecraft_jj_yellow_flower={need=1,tag=""}}},
 fairylights_jj_light_jj_51={hasPattern=true,label="Braun Blumenlicht",recipe={minecraft_jj_dye_jj_3={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_red_flower={need=1,tag=""},minecraft_jj_red_flower_jj_1={need=1,tag=""},minecraft_jj_yellow_flower={need=1,tag=""}}},
 fairylights_jj_light_jj_52={hasPattern=true,label="Blau Blumenlicht",recipe={minecraft_jj_dye_jj_4={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_red_flower={need=1,tag=""},minecraft_jj_red_flower_jj_1={need=1,tag=""},minecraft_jj_yellow_flower={need=1,tag=""}}},
 fairylights_jj_light_jj_53={hasPattern=true,label="Lila Blumenlicht",recipe={minecraft_jj_dye_jj_5={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_red_flower={need=1,tag=""},minecraft_jj_red_flower_jj_1={need=1,tag=""},minecraft_jj_yellow_flower={need=1,tag=""}}},
 fairylights_jj_light_jj_54={hasPattern=true,label="Zyan Blumenlicht",recipe={minecraft_jj_dye_jj_6={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_red_flower={need=1,tag=""},minecraft_jj_red_flower_jj_1={need=1,tag=""},minecraft_jj_yellow_flower={need=1,tag=""}}},
 fairylights_jj_light_jj_55={hasPattern=true,label="Hellgrau Blumenlicht",recipe={minecraft_jj_dye_jj_7={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_red_flower={need=1,tag=""},minecraft_jj_red_flower_jj_1={need=1,tag=""},minecraft_jj_yellow_flower={need=1,tag=""}}},
 fairylights_jj_light_jj_56={hasPattern=true,label="Grau Blumenlicht",recipe={minecraft_jj_dye_jj_8={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_red_flower={need=1,tag=""},minecraft_jj_red_flower_jj_1={need=1,tag=""},minecraft_jj_yellow_flower={need=1,tag=""}}},
 fairylights_jj_light_jj_57={hasPattern=true,label="Rosa Blumenlicht",recipe={minecraft_jj_dye_jj_9={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_red_flower={need=1,tag=""},minecraft_jj_red_flower_jj_1={need=1,tag=""},minecraft_jj_yellow_flower={need=1,tag=""}}},
 fairylights_jj_light_jj_58={hasPattern=true,label="Hellgrün Blumenlicht",recipe={minecraft_jj_dye_jj_10={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_red_flower={need=1,tag=""},minecraft_jj_red_flower_jj_1={need=1,tag=""},minecraft_jj_yellow_flower={need=1,tag=""}}},
 fairylights_jj_light_jj_59={hasPattern=true,label="Gelb Blumenlicht",recipe={minecraft_jj_dye_jj_11={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_red_flower={need=1,tag=""},minecraft_jj_red_flower_jj_1={need=1,tag=""},minecraft_jj_yellow_flower={need=1,tag=""}}},
 fairylights_jj_light_jj_6={hasPattern=true,label="Zyan Feenlicht",recipe={minecraft_jj_dye_jj_6={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_60={hasPattern=true,label="Hellblau Blumenlicht",recipe={minecraft_jj_dye_jj_12={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_red_flower={need=1,tag=""},minecraft_jj_red_flower_jj_1={need=1,tag=""},minecraft_jj_yellow_flower={need=1,tag=""}}},
 fairylights_jj_light_jj_61={hasPattern=true,label="Purpur Blumenlicht",recipe={minecraft_jj_dye_jj_13={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_red_flower={need=1,tag=""},minecraft_jj_red_flower_jj_1={need=1,tag=""},minecraft_jj_yellow_flower={need=1,tag=""}}},
 fairylights_jj_light_jj_62={hasPattern=true,label="Orange Blumenlicht",recipe={minecraft_jj_dye_jj_14={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_red_flower={need=1,tag=""},minecraft_jj_red_flower_jj_1={need=1,tag=""},minecraft_jj_yellow_flower={need=1,tag=""}}},
 fairylights_jj_light_jj_63={hasPattern=true,label="Weiß Blumenlicht",recipe={minecraft_jj_dye_jj_15={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_red_flower={need=1,tag=""},minecraft_jj_red_flower_jj_1={need=1,tag=""},minecraft_jj_yellow_flower={need=1,tag=""}}},
 fairylights_jj_light_jj_64={hasPattern=true,label="Schwarz Ornamentlaterne",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_gold_nugget={need=3,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_65={hasPattern=true,label="Rot Ornamentlaterne",recipe={minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_gold_nugget={need=3,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_66={hasPattern=true,label="Grün Ornamentlaterne",recipe={minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_gold_nugget={need=3,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_67={hasPattern=true,label="Braun Ornamentlaterne",recipe={minecraft_jj_dye_jj_3={need=1,tag=""},minecraft_jj_gold_nugget={need=3,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_68={hasPattern=true,label="Blau Ornamentlaterne",recipe={minecraft_jj_dye_jj_4={need=1,tag=""},minecraft_jj_gold_nugget={need=3,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_69={hasPattern=true,label="Lila Ornamentlaterne",recipe={minecraft_jj_dye_jj_5={need=1,tag=""},minecraft_jj_gold_nugget={need=3,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_7={hasPattern=true,label="Hellgrau Feenlicht",recipe={minecraft_jj_dye_jj_7={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_70={hasPattern=true,label="Zyan Ornamentlaterne",recipe={minecraft_jj_dye_jj_6={need=1,tag=""},minecraft_jj_gold_nugget={need=3,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_71={hasPattern=true,label="Hellgrau Ornamentlaterne",recipe={minecraft_jj_dye_jj_7={need=1,tag=""},minecraft_jj_gold_nugget={need=3,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_72={hasPattern=true,label="Grau Ornamentlaterne",recipe={minecraft_jj_dye_jj_8={need=1,tag=""},minecraft_jj_gold_nugget={need=3,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_73={hasPattern=true,label="Rosa Ornamentlaterne",recipe={minecraft_jj_dye_jj_9={need=1,tag=""},minecraft_jj_gold_nugget={need=3,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_74={hasPattern=true,label="Hellgrün Ornamentlaterne",recipe={minecraft_jj_dye_jj_10={need=1,tag=""},minecraft_jj_gold_nugget={need=3,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_75={hasPattern=true,label="Gelb Ornamentlaterne",recipe={minecraft_jj_dye_jj_11={need=1,tag=""},minecraft_jj_gold_nugget={need=3,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_76={hasPattern=true,label="Hellblau Ornamentlaterne",recipe={minecraft_jj_dye_jj_12={need=1,tag=""},minecraft_jj_gold_nugget={need=3,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_77={hasPattern=true,label="Purpur Ornamentlaterne",recipe={minecraft_jj_dye_jj_13={need=1,tag=""},minecraft_jj_gold_nugget={need=3,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_78={hasPattern=true,label="Orange Ornamentlaterne",recipe={minecraft_jj_dye_jj_14={need=1,tag=""},minecraft_jj_gold_nugget={need=3,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_79={hasPattern=true,label="Weiß Ornamentlaterne",recipe={minecraft_jj_dye_jj_15={need=1,tag=""},minecraft_jj_gold_nugget={need=3,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_8={hasPattern=true,label="Grau Feenlicht",recipe={minecraft_jj_dye_jj_8={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_80={hasPattern=true,label="Schwarz Öllaterne",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 fairylights_jj_light_jj_81={hasPattern=true,label="Rot Öllaterne",recipe={minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 fairylights_jj_light_jj_82={hasPattern=true,label="Grün Öllaterne",recipe={minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 fairylights_jj_light_jj_83={hasPattern=true,label="Braun Öllaterne",recipe={minecraft_jj_dye_jj_3={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 fairylights_jj_light_jj_84={hasPattern=true,label="Blau Öllaterne",recipe={minecraft_jj_dye_jj_4={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 fairylights_jj_light_jj_85={hasPattern=true,label="Lila Öllaterne",recipe={minecraft_jj_dye_jj_5={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 fairylights_jj_light_jj_86={hasPattern=true,label="Zyan Öllaterne",recipe={minecraft_jj_dye_jj_6={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 fairylights_jj_light_jj_87={hasPattern=true,label="Hellgrau Öllaterne",recipe={minecraft_jj_dye_jj_7={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 fairylights_jj_light_jj_88={hasPattern=true,label="Grau Öllaterne",recipe={minecraft_jj_dye_jj_8={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 fairylights_jj_light_jj_89={hasPattern=true,label="Rosa Öllaterne",recipe={minecraft_jj_dye_jj_9={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 fairylights_jj_light_jj_9={hasPattern=true,label="Rosa Feenlicht",recipe={minecraft_jj_dye_jj_9={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 fairylights_jj_light_jj_90={hasPattern=true,label="Hellgrün Öllaterne",recipe={minecraft_jj_dye_jj_10={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 fairylights_jj_light_jj_91={hasPattern=true,label="Gelb Öllaterne",recipe={minecraft_jj_dye_jj_11={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 fairylights_jj_light_jj_92={hasPattern=true,label="Hellblau Öllaterne",recipe={minecraft_jj_dye_jj_12={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 fairylights_jj_light_jj_93={hasPattern=true,label="Purpur Öllaterne",recipe={minecraft_jj_dye_jj_13={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 fairylights_jj_light_jj_94={hasPattern=true,label="Orange Öllaterne",recipe={minecraft_jj_dye_jj_14={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 fairylights_jj_light_jj_95={hasPattern=true,label="Weiß Öllaterne",recipe={minecraft_jj_dye_jj_15={need=1,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 fairylights_jj_pennant={hasPattern=true,label="Schwarz Wimpel",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_paper={need=3,tag=""},minecraft_jj_string={need=2,tag=""}}},
 fairylights_jj_pennant_bunting={hasPattern=false,label="",recipe={}},
 fairylights_jj_pennant_jj_1={hasPattern=true,label="Rot Wimpel",recipe={minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_paper={need=3,tag=""},minecraft_jj_string={need=2,tag=""}}},
 fairylights_jj_pennant_jj_10={hasPattern=true,label="Hellgrün Wimpel",recipe={minecraft_jj_dye_jj_10={need=1,tag=""},minecraft_jj_paper={need=3,tag=""},minecraft_jj_string={need=2,tag=""}}},
 fairylights_jj_pennant_jj_11={hasPattern=true,label="Gelb Wimpel",recipe={minecraft_jj_dye_jj_11={need=1,tag=""},minecraft_jj_paper={need=3,tag=""},minecraft_jj_string={need=2,tag=""}}},
 fairylights_jj_pennant_jj_12={hasPattern=true,label="Hellblau Wimpel",recipe={minecraft_jj_dye_jj_12={need=1,tag=""},minecraft_jj_paper={need=3,tag=""},minecraft_jj_string={need=2,tag=""}}},
 fairylights_jj_pennant_jj_13={hasPattern=true,label="Purpur Wimpel",recipe={minecraft_jj_dye_jj_13={need=1,tag=""},minecraft_jj_paper={need=3,tag=""},minecraft_jj_string={need=2,tag=""}}},
 fairylights_jj_pennant_jj_14={hasPattern=true,label="Orange Wimpel",recipe={minecraft_jj_dye_jj_14={need=1,tag=""},minecraft_jj_paper={need=3,tag=""},minecraft_jj_string={need=2,tag=""}}},
 fairylights_jj_pennant_jj_15={hasPattern=true,label="Weiß Wimpel",recipe={minecraft_jj_dye_jj_15={need=1,tag=""},minecraft_jj_paper={need=3,tag=""},minecraft_jj_string={need=2,tag=""}}},
 fairylights_jj_pennant_jj_2={hasPattern=true,label="Grün Wimpel",recipe={minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_paper={need=3,tag=""},minecraft_jj_string={need=2,tag=""}}},
 fairylights_jj_pennant_jj_3={hasPattern=true,label="Braun Wimpel",recipe={minecraft_jj_dye_jj_3={need=1,tag=""},minecraft_jj_paper={need=3,tag=""},minecraft_jj_string={need=2,tag=""}}},
 fairylights_jj_pennant_jj_4={hasPattern=true,label="Blau Wimpel",recipe={minecraft_jj_dye_jj_4={need=1,tag=""},minecraft_jj_paper={need=3,tag=""},minecraft_jj_string={need=2,tag=""}}},
 fairylights_jj_pennant_jj_5={hasPattern=true,label="Lila Wimpel",recipe={minecraft_jj_dye_jj_5={need=1,tag=""},minecraft_jj_paper={need=3,tag=""},minecraft_jj_string={need=2,tag=""}}},
 fairylights_jj_pennant_jj_6={hasPattern=true,label="Zyan Wimpel",recipe={minecraft_jj_dye_jj_6={need=1,tag=""},minecraft_jj_paper={need=3,tag=""},minecraft_jj_string={need=2,tag=""}}},
 fairylights_jj_pennant_jj_7={hasPattern=true,label="Hellgrau Wimpel",recipe={minecraft_jj_dye_jj_7={need=1,tag=""},minecraft_jj_paper={need=3,tag=""},minecraft_jj_string={need=2,tag=""}}},
 fairylights_jj_pennant_jj_8={hasPattern=true,label="Grau Wimpel",recipe={minecraft_jj_dye_jj_8={need=1,tag=""},minecraft_jj_paper={need=3,tag=""},minecraft_jj_string={need=2,tag=""}}},
 fairylights_jj_pennant_jj_9={hasPattern=true,label="Rosa Wimpel",recipe={minecraft_jj_dye_jj_9={need=1,tag=""},minecraft_jj_paper={need=3,tag=""},minecraft_jj_string={need=2,tag=""}}},
 fairylights_jj_tinsel={hasPattern=false,label="",recipe={}},
 floricraft_jj_amulet_sachet_anti_creeper={hasPattern=false,label="",recipe={}},
 floricraft_jj_amulet_sachet_anti_enderman={hasPattern=false,label="",recipe={}},
 floricraft_jj_amulet_sachet_anti_skeleton={hasPattern=false,label="",recipe={}},
 floricraft_jj_amulet_sachet_anti_spider={hasPattern=false,label="",recipe={}},
 floricraft_jj_amulet_sachet_anti_zombie={hasPattern=false,label="",recipe={}},
 floricraft_jj_amulet_sachet_flower={hasPattern=false,label="",recipe={}},
 floricraft_jj_amulet_sachet_temptation={hasPattern=false,label="",recipe={}},
 floricraft_jj_apron_chestplate={hasPattern=true,label="Schürze",recipe={floricraft_jj_hemp_cloth={need=2,tag=""},floricraft_jj_hemp_twine={need=6,tag=""}}},
 floricraft_jj_ballon={hasPattern=true,label="Black Balloon",recipe={floricraft_jj_hemp_cloth={need=1,tag=""},floricraft_jj_hemp_twine={need=1,tag=""}}},
 floricraft_jj_basket_flower={hasPattern=true,label="Blumenkorb",recipe={floricraft_jj_hemp_cloth={need=4,tag=""},floricraft_jj_hemp_twine={need=4,tag=""},minecraft_jj_red_flower={need=1,tag=""}}},
 floricraft_jj_basket_lunch={hasPattern=true,label="Picknickkorb",recipe={floricraft_jj_hemp_cloth={need=4,tag=""},floricraft_jj_hemp_twine={need=4,tag=""},minecraft_jj_bread={need=1,tag=""}}},
 floricraft_jj_block_salt={hasPattern=true,label="Salzblock",recipe={floricraft_jj_dust_salt={need=9,tag=""}}},
 floricraft_jj_bottle_brown_empty={hasPattern=false,label="",recipe={}},
 floricraft_jj_bottle_brown_flower={hasPattern=false,label="",recipe={}},
 floricraft_jj_bottle_brown_water={hasPattern=false,label="",recipe={}},
 floricraft_jj_cloth_boots={hasPattern=true,label="Thaumaturgenstiefel",recipe={floricraft_jj_hemp_cloth={need=2,tag=""},floricraft_jj_hemp_twine={need=2,tag=""}}},
 floricraft_jj_cloth_chestplate={hasPattern=true,label="Stoffbrustplatte",recipe={floricraft_jj_hemp_cloth={need=6,tag=""},floricraft_jj_hemp_twine={need=2,tag=""}}},
 floricraft_jj_cloth_helmet={hasPattern=true,label="Stoffhelm",recipe={floricraft_jj_hemp_cloth={need=3,tag=""},floricraft_jj_hemp_twine={need=2,tag=""}}},
 floricraft_jj_cloth_leggings={hasPattern=true,label="Stoffbeinschutz",recipe={floricraft_jj_hemp_cloth={need=4,tag=""},floricraft_jj_hemp_twine={need=3,tag=""}}},
 floricraft_jj_confection_event={hasPattern=true,label="Lebkuchenmann",recipe={harvestcraft_jj_batteritem={need=1,tag=""},minecraft_jj_sugar={need=4,tag=""}}},
 floricraft_jj_doll_iron_sit={hasPattern=true,label="Eisengolem-Puppe",recipe={minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_pumpkin={need=1,tag=""}}},
 floricraft_jj_doll_player={hasPattern=false,label="",recipe={}},
 floricraft_jj_dust_salt={hasPattern=false,label="",recipe={}},
 floricraft_jj_floric_torch_allium={hasPattern=true,label="Florische Fackel (Sternlauch)",recipe={floricraft_jj_petals_raw_jj_3={need=1,tag=""},minecraft_jj_coal={need=1,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 floricraft_jj_floric_torch_azure_bluet={hasPattern=true,label="Florische Fackel (Porzellansternchen)",recipe={floricraft_jj_petals_raw_jj_4={need=1,tag=""},minecraft_jj_coal={need=1,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 floricraft_jj_floric_torch_blue_orchid={hasPattern=true,label="Florische Fackel (Blaue Orchidee)",recipe={floricraft_jj_petals_raw_jj_2={need=1,tag=""},minecraft_jj_coal={need=1,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 floricraft_jj_floric_torch_dandelion={hasPattern=true,label="Florische Fackel (Löwenzahn)",recipe={floricraft_jj_petals_raw={need=1,tag=""},minecraft_jj_coal={need=1,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 floricraft_jj_floric_torch_lilac={hasPattern=true,label="Florische Fackel (Flieder)",recipe={floricraft_jj_petals_raw_jj_11={need=1,tag=""},minecraft_jj_coal={need=1,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 floricraft_jj_floric_torch_orange_tulip={hasPattern=true,label="Florische Fackel (Orange Tulpe)",recipe={floricraft_jj_petals_raw_jj_6={need=1,tag=""},minecraft_jj_coal={need=1,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 floricraft_jj_floric_torch_oxeye_daisy={hasPattern=true,label="Florische Fackel (Margerite)",recipe={floricraft_jj_petals_raw_jj_9={need=1,tag=""},minecraft_jj_coal={need=1,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 floricraft_jj_floric_torch_peony={hasPattern=true,label="Florische Fackel (Pfingstrose)",recipe={floricraft_jj_petals_raw_jj_13={need=1,tag=""},minecraft_jj_coal={need=1,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 floricraft_jj_floric_torch_pink_tulip={hasPattern=true,label="Florische Fackel (Rosa Tulpe)",recipe={floricraft_jj_petals_raw_jj_8={need=1,tag=""},minecraft_jj_coal={need=1,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 floricraft_jj_floric_torch_poppy={hasPattern=true,label="Florische Fackel (Mohn)",recipe={floricraft_jj_petals_raw_jj_1={need=1,tag=""},minecraft_jj_coal={need=1,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 floricraft_jj_floric_torch_red_tulip={hasPattern=true,label="Florische Fackel (Rote Tulpe)",recipe={floricraft_jj_petals_raw_jj_5={need=1,tag=""},minecraft_jj_coal={need=1,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 floricraft_jj_floric_torch_rose={hasPattern=true,label="Florische Fackel (Rose)",recipe={floricraft_jj_petals_raw_jj_12={need=1,tag=""},minecraft_jj_coal={need=1,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 floricraft_jj_floric_torch_sakura={hasPattern=true,label="Florische Fackel (Sakura)",recipe={floricraft_jj_petals_raw_jj_14={need=1,tag=""},minecraft_jj_coal={need=1,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 floricraft_jj_floric_torch_sunflower={hasPattern=true,label="Florische Fackel (Sonnenblume)",recipe={floricraft_jj_petals_raw_jj_10={need=1,tag=""},minecraft_jj_coal={need=1,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 floricraft_jj_floric_torch_white_tulip={hasPattern=true,label="Florische Fackel (Weiße Tulpe)",recipe={floricraft_jj_petals_raw_jj_7={need=1,tag=""},minecraft_jj_coal={need=1,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 floricraft_jj_flower_bed={hasPattern=true,label="Better Flower Bed",recipe={minecraft_jj_brick={need=8,tag=""},minecraft_jj_grass={need=1,tag=""}}},
 floricraft_jj_flower_cut={hasPattern=true,label="Geschnittener Löwenzahn",recipe={floricraft_jj_purner={need=1,tag=""},minecraft_jj_yellow_flower={need=1,tag=""}}},
 floricraft_jj_flower_cut_jj_1={hasPattern=true,label="",recipe={floricraft_jj_purner={need=1,tag=""},minecraft_jj_red_flower={need=1,tag=""}}},
 floricraft_jj_flower_cut_jj_10={hasPattern=true,label="",recipe={floricraft_jj_purner={need=1,tag=""},minecraft_jj_double_plant={need=1,tag=""}}},
 floricraft_jj_flower_cut_jj_11={hasPattern=true,label="",recipe={floricraft_jj_purner={need=1,tag=""},minecraft_jj_double_plant_jj_1={need=1,tag=""}}},
 floricraft_jj_flower_cut_jj_12={hasPattern=true,label="",recipe={floricraft_jj_purner={need=1,tag=""},minecraft_jj_double_plant4={need=1,tag=""}}},
 floricraft_jj_flower_cut_jj_13={hasPattern=true,label="",recipe={floricraft_jj_purner={need=1,tag=""},minecraft_jj_double_plant5={need=1,tag=""}}},
 floricraft_jj_flower_cut_jj_14={hasPattern=true,label="",recipe={floricraft_jj_leaves_floric_type0={need=1,tag=""},floricraft_jj_purner={need=1,tag=""}}},
 floricraft_jj_flower_cut_jj_2={hasPattern=true,label="",recipe={floricraft_jj_purner={need=1,tag=""},minecraft_jj_red_flower_jj_1={need=1,tag=""}}},
 floricraft_jj_flower_cut_jj_3={hasPattern=true,label="",recipe={floricraft_jj_purner={need=1,tag=""},minecraft_jj_red_flower_jj_2={need=1,tag=""}}},
 floricraft_jj_flower_cut_jj_4={hasPattern=true,label="",recipe={floricraft_jj_purner={need=1,tag=""},minecraft_jj_red_flower_jj_3={need=1,tag=""}}},
 floricraft_jj_flower_cut_jj_5={hasPattern=true,label="",recipe={floricraft_jj_purner={need=1,tag=""},minecraft_jj_red_flower_jj_4={need=1,tag=""}}},
 floricraft_jj_flower_cut_jj_6={hasPattern=true,label="",recipe={floricraft_jj_purner={need=1,tag=""},minecraft_jj_red_flower_jj_5={need=1,tag=""}}},
 floricraft_jj_flower_cut_jj_7={hasPattern=true,label="",recipe={floricraft_jj_purner={need=1,tag=""},minecraft_jj_red_flower_jj_6={need=1,tag=""}}},
 floricraft_jj_flower_cut_jj_8={hasPattern=true,label="",recipe={floricraft_jj_purner={need=1,tag=""},minecraft_jj_red_flower_jj_7={need=1,tag=""}}},
 floricraft_jj_flower_cut_jj_9={hasPattern=true,label="",recipe={floricraft_jj_purner={need=1,tag=""},minecraft_jj_red_flower_jj_8={need=1,tag=""}}},
 floricraft_jj_flower_pot={hasPattern=true,label="Besserer Blumentopf",recipe={minecraft_jj_flower_pot={need=1,tag=""}}},
 floricraft_jj_hemp_cloth={hasPattern=true,label="Hanfstoff",recipe={floricraft_jj_hemp_yarn={need=6,tag=""}}},
 floricraft_jj_hemp_twine={hasPattern=true,label="Hanffaden",recipe={floricraft_jj_hemp_yarn={need=2,tag=""}}},
 floricraft_jj_hemp_yarn={hasPattern=false,label="",recipe={}},
 floricraft_jj_leaves_christmas={hasPattern=false,label="",recipe={}},
 floricraft_jj_leaves_christmas_dynamic={hasPattern=false,label="",recipe={}},
 floricraft_jj_leaves_christmas_dynamic_unlit={hasPattern=false,label="",recipe={}},
 floricraft_jj_leaves_christmas_jj_1={hasPattern=false,label="",recipe={}},
 floricraft_jj_leaves_christmas_jj_2={hasPattern=false,label="",recipe={}},
 floricraft_jj_leaves_christmas_jj_3={hasPattern=false,label="",recipe={}},
 floricraft_jj_leaves_christmas_unlit={hasPattern=false,label="",recipe={}},
 floricraft_jj_leaves_floric_type0={hasPattern=false,label="",recipe={}},
 floricraft_jj_leaves_floric_type0_jj_1={hasPattern=false,label="",recipe={}},
 floricraft_jj_leaves_floric_type0_jj_2={hasPattern=false,label="",recipe={}},
 floricraft_jj_leaves_floric_type0_jj_3={hasPattern=false,label="",recipe={}},
 floricraft_jj_lycoris={hasPattern=false,label="",recipe={}},
 floricraft_jj_ore_salt={hasPattern=false,label="",recipe={}},
 floricraft_jj_ornament_christmas={hasPattern=true,label="Weihnachtskranz",recipe={floricraft_jj_leaves_christmas={need=8,tag=""}}},
 floricraft_jj_ornament_christmas_jj_1={hasPattern=true,label="Weihnachtssocke",recipe={floricraft_jj_hemp_cloth={need=3,tag=""},floricraft_jj_hemp_twine={need=1,tag=""},minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_dye_jj_15={need=1,tag=""}}},
 floricraft_jj_ornament_christmas_jj_2={hasPattern=true,label="Weihnachtsflaggen-Girlande",recipe={floricraft_jj_hemp_twine={need=3,tag=""},minecraft_jj_dye_jj_1={need=2,tag=""},minecraft_jj_dye_jj_2={need=1,tag=""}}},
 floricraft_jj_ornament_christmas_jj_3={hasPattern=true,label="Bunte Fahnen-Girlande",recipe={floricraft_jj_hemp_twine={need=3,tag=""},minecraft_jj_dye={need=3,tag=""}}},
 floricraft_jj_petal_dry={hasPattern=true,label="",recipe={floricraft_jj_stack_dandelion_jj_3={need=1,tag=""}}},
 floricraft_jj_petal_dry_jj_1={hasPattern=true,label="",recipe={floricraft_jj_stack_poppy_jj_3={need=1,tag=""}}},
 floricraft_jj_petal_dry_jj_10={hasPattern=true,label="",recipe={floricraft_jj_stack_sunflower_jj_3={need=1,tag=""}}},
 floricraft_jj_petal_dry_jj_11={hasPattern=true,label="",recipe={floricraft_jj_stack_lilac_jj_3={need=1,tag=""}}},
 floricraft_jj_petal_dry_jj_12={hasPattern=true,label="",recipe={floricraft_jj_stack_rose_jj_3={need=1,tag=""}}},
 floricraft_jj_petal_dry_jj_13={hasPattern=true,label="",recipe={floricraft_jj_stack_peony_jj_3={need=1,tag=""}}},
 floricraft_jj_petal_dry_jj_14={hasPattern=true,label="",recipe={floricraft_jj_stack_sakura_jj_3={need=1,tag=""}}},
 floricraft_jj_petal_dry_jj_2={hasPattern=true,label="",recipe={floricraft_jj_stack_blue_orchid_jj_3={need=1,tag=""}}},
 floricraft_jj_petal_dry_jj_3={hasPattern=true,label="",recipe={floricraft_jj_stack_allium_jj_3={need=1,tag=""}}},
 floricraft_jj_petal_dry_jj_4={hasPattern=true,label="",recipe={floricraft_jj_stack_azure_bluet_jj_3={need=1,tag=""}}},
 floricraft_jj_petal_dry_jj_5={hasPattern=true,label="",recipe={floricraft_jj_stack_red_tulip_jj_3={need=1,tag=""}}},
 floricraft_jj_petal_dry_jj_6={hasPattern=true,label="",recipe={floricraft_jj_stack_orange_tulip_jj_3={need=1,tag=""}}},
 floricraft_jj_petal_dry_jj_7={hasPattern=true,label="",recipe={floricraft_jj_stack_white_tulip_jj_3={need=1,tag=""}}},
 floricraft_jj_petal_dry_jj_8={hasPattern=true,label="",recipe={floricraft_jj_stack_pink_tulip_jj_3={need=1,tag=""}}},
 floricraft_jj_petal_dry_jj_9={hasPattern=true,label="",recipe={floricraft_jj_stack_oxeye_daisy_jj_3={need=1,tag=""}}},
 floricraft_jj_petal_raw={hasPattern=true,label="",recipe={floricraft_jj_flower_cut={need=1,tag=""}}},
 floricraft_jj_petal_raw_jj_1={hasPattern=true,label="",recipe={floricraft_jj_flower_cut_jj_1={need=1,tag=""}}},
 floricraft_jj_petal_raw_jj_10={hasPattern=true,label="",recipe={floricraft_jj_flower_cut_jj_10={need=1,tag=""}}},
 floricraft_jj_petal_raw_jj_11={hasPattern=true,label="",recipe={floricraft_jj_flower_cut_jj_11={need=1,tag=""}}},
 floricraft_jj_petal_raw_jj_12={hasPattern=true,label="",recipe={floricraft_jj_flower_cut_jj_12={need=1,tag=""}}},
 floricraft_jj_petal_raw_jj_13={hasPattern=true,label="",recipe={floricraft_jj_flower_cut_jj_13={need=1,tag=""}}},
 floricraft_jj_petal_raw_jj_14={hasPattern=true,label="",recipe={floricraft_jj_flower_cut_jj_14={need=1,tag=""}}},
 floricraft_jj_petal_raw_jj_2={hasPattern=true,label="",recipe={floricraft_jj_flower_cut_jj_2={need=1,tag=""}}},
 floricraft_jj_petal_raw_jj_3={hasPattern=true,label="",recipe={floricraft_jj_flower_cut_jj_3={need=1,tag=""}}},
 floricraft_jj_petal_raw_jj_4={hasPattern=true,label="",recipe={floricraft_jj_flower_cut_jj_4={need=1,tag=""}}},
 floricraft_jj_petal_raw_jj_5={hasPattern=true,label="",recipe={floricraft_jj_flower_cut_jj_5={need=1,tag=""}}},
 floricraft_jj_petal_raw_jj_6={hasPattern=true,label="",recipe={floricraft_jj_flower_cut_jj_6={need=1,tag=""}}},
 floricraft_jj_petal_raw_jj_7={hasPattern=true,label="",recipe={floricraft_jj_flower_cut_jj_7={need=1,tag=""}}},
 floricraft_jj_petal_raw_jj_8={hasPattern=true,label="",recipe={floricraft_jj_flower_cut_jj_8={need=1,tag=""}}},
 floricraft_jj_petal_raw_jj_9={hasPattern=true,label="",recipe={floricraft_jj_flower_cut_jj_9={need=1,tag=""}}},
 floricraft_jj_petal_salty={hasPattern=true,label="",recipe={floricraft_jj_dust_salt={need=2,tag=""},floricraft_jj_petal_raw={need=1,tag=""}}},
 floricraft_jj_petal_salty_jj_1={hasPattern=true,label="",recipe={floricraft_jj_dust_salt={need=2,tag=""},floricraft_jj_petal_raw_jj_1={need=1,tag=""}}},
 floricraft_jj_petal_salty_jj_10={hasPattern=true,label="",recipe={floricraft_jj_dust_salt={need=2,tag=""},floricraft_jj_petal_raw_jj_10={need=1,tag=""}}},
 floricraft_jj_petal_salty_jj_11={hasPattern=true,label="",recipe={floricraft_jj_dust_salt={need=2,tag=""},floricraft_jj_petal_raw_jj_11={need=1,tag=""}}},
 floricraft_jj_petal_salty_jj_12={hasPattern=true,label="",recipe={floricraft_jj_dust_salt={need=2,tag=""},floricraft_jj_petal_raw_jj_12={need=1,tag=""}}},
 floricraft_jj_petal_salty_jj_13={hasPattern=true,label="",recipe={floricraft_jj_dust_salt={need=2,tag=""},floricraft_jj_petal_raw_jj_13={need=1,tag=""}}},
 floricraft_jj_petal_salty_jj_14={hasPattern=true,label="",recipe={floricraft_jj_dust_salt={need=2,tag=""},floricraft_jj_petal_raw_jj_14={need=1,tag=""}}},
 floricraft_jj_petal_salty_jj_2={hasPattern=true,label="",recipe={floricraft_jj_dust_salt={need=2,tag=""},floricraft_jj_petal_raw_jj_2={need=1,tag=""}}},
 floricraft_jj_petal_salty_jj_3={hasPattern=true,label="",recipe={floricraft_jj_dust_salt={need=2,tag=""},floricraft_jj_petal_raw_jj_3={need=1,tag=""}}},
 floricraft_jj_petal_salty_jj_4={hasPattern=true,label="",recipe={floricraft_jj_dust_salt={need=2,tag=""},floricraft_jj_petal_raw_jj_4={need=1,tag=""}}},
 floricraft_jj_petal_salty_jj_5={hasPattern=true,label="",recipe={floricraft_jj_dust_salt={need=2,tag=""},floricraft_jj_petal_raw_jj_5={need=1,tag=""}}},
 floricraft_jj_petal_salty_jj_6={hasPattern=true,label="",recipe={floricraft_jj_dust_salt={need=2,tag=""},floricraft_jj_petal_raw_jj_6={need=1,tag=""}}},
 floricraft_jj_petal_salty_jj_7={hasPattern=true,label="",recipe={floricraft_jj_dust_salt={need=2,tag=""},floricraft_jj_petal_raw_jj_7={need=1,tag=""}}},
 floricraft_jj_petal_salty_jj_8={hasPattern=true,label="",recipe={floricraft_jj_dust_salt={need=2,tag=""},floricraft_jj_petal_raw_jj_8={need=1,tag=""}}},
 floricraft_jj_petal_salty_jj_9={hasPattern=true,label="",recipe={floricraft_jj_dust_salt={need=2,tag=""},floricraft_jj_petal_raw_jj_9={need=1,tag=""}}},
 floricraft_jj_petal_sugared={hasPattern=true,label="",recipe={floricraft_jj_petal_raw={need=1,tag=""},minecraft_jj_sugar={need=2,tag=""}}},
 floricraft_jj_petal_sugared_jj_1={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_1={need=1,tag=""},minecraft_jj_sugar={need=2,tag=""}}},
 floricraft_jj_petal_sugared_jj_10={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_10={need=1,tag=""},minecraft_jj_sugar={need=2,tag=""}}},
 floricraft_jj_petal_sugared_jj_11={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_11={need=1,tag=""},minecraft_jj_sugar={need=2,tag=""}}},
 floricraft_jj_petal_sugared_jj_12={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_12={need=1,tag=""},minecraft_jj_sugar={need=2,tag=""}}},
 floricraft_jj_petal_sugared_jj_13={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_13={need=1,tag=""},minecraft_jj_sugar={need=2,tag=""}}},
 floricraft_jj_petal_sugared_jj_14={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_14={need=1,tag=""},minecraft_jj_sugar={need=2,tag=""}}},
 floricraft_jj_petal_sugared_jj_2={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_2={need=1,tag=""},minecraft_jj_sugar={need=2,tag=""}}},
 floricraft_jj_petal_sugared_jj_3={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_3={need=1,tag=""},minecraft_jj_sugar={need=2,tag=""}}},
 floricraft_jj_petal_sugared_jj_4={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_4={need=1,tag=""},minecraft_jj_sugar={need=2,tag=""}}},
 floricraft_jj_petal_sugared_jj_5={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_5={need=1,tag=""},minecraft_jj_sugar={need=2,tag=""}}},
 floricraft_jj_petal_sugared_jj_6={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_6={need=1,tag=""},minecraft_jj_sugar={need=2,tag=""}}},
 floricraft_jj_petal_sugared_jj_7={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_7={need=1,tag=""},minecraft_jj_sugar={need=2,tag=""}}},
 floricraft_jj_petal_sugared_jj_8={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_8={need=1,tag=""},minecraft_jj_sugar={need=2,tag=""}}},
 floricraft_jj_petal_sugared_jj_9={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_9={need=1,tag=""},minecraft_jj_sugar={need=2,tag=""}}},
 floricraft_jj_petals_dry={hasPattern=true,label="",recipe={floricraft_jj_petal_dry={need=9,tag=""}}},
 floricraft_jj_petals_dry_jj_1={hasPattern=true,label="",recipe={floricraft_jj_petal_dry_jj_1={need=9,tag=""}}},
 floricraft_jj_petals_dry_jj_10={hasPattern=true,label="",recipe={floricraft_jj_petal_dry_jj_10={need=9,tag=""}}},
 floricraft_jj_petals_dry_jj_11={hasPattern=true,label="",recipe={floricraft_jj_petal_dry_jj_11={need=9,tag=""}}},
 floricraft_jj_petals_dry_jj_12={hasPattern=true,label="",recipe={floricraft_jj_petal_dry_jj_12={need=9,tag=""}}},
 floricraft_jj_petals_dry_jj_13={hasPattern=true,label="",recipe={floricraft_jj_petal_dry_jj_13={need=9,tag=""}}},
 floricraft_jj_petals_dry_jj_14={hasPattern=true,label="",recipe={floricraft_jj_petal_dry_jj_14={need=9,tag=""}}},
 floricraft_jj_petals_dry_jj_2={hasPattern=true,label="",recipe={floricraft_jj_petal_dry_jj_2={need=9,tag=""}}},
 floricraft_jj_petals_dry_jj_3={hasPattern=true,label="",recipe={floricraft_jj_petal_dry_jj_3={need=9,tag=""}}},
 floricraft_jj_petals_dry_jj_4={hasPattern=true,label="",recipe={floricraft_jj_petal_dry_jj_4={need=9,tag=""}}},
 floricraft_jj_petals_dry_jj_5={hasPattern=true,label="",recipe={floricraft_jj_petal_dry_jj_5={need=9,tag=""}}},
 floricraft_jj_petals_dry_jj_6={hasPattern=true,label="",recipe={floricraft_jj_petal_dry_jj_6={need=9,tag=""}}},
 floricraft_jj_petals_dry_jj_7={hasPattern=true,label="",recipe={floricraft_jj_petal_dry_jj_7={need=9,tag=""}}},
 floricraft_jj_petals_dry_jj_8={hasPattern=true,label="",recipe={floricraft_jj_petal_dry_jj_8={need=9,tag=""}}},
 floricraft_jj_petals_dry_jj_9={hasPattern=true,label="",recipe={floricraft_jj_petal_dry_jj_9={need=9,tag=""}}},
 floricraft_jj_petals_raw={hasPattern=true,label="",recipe={floricraft_jj_petal_raw={need=9,tag=""}}},
 floricraft_jj_petals_raw_jj_1={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_1={need=9,tag=""}}},
 floricraft_jj_petals_raw_jj_10={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_10={need=9,tag=""}}},
 floricraft_jj_petals_raw_jj_11={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_11={need=9,tag=""}}},
 floricraft_jj_petals_raw_jj_12={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_12={need=9,tag=""}}},
 floricraft_jj_petals_raw_jj_13={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_13={need=9,tag=""}}},
 floricraft_jj_petals_raw_jj_14={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_14={need=9,tag=""}}},
 floricraft_jj_petals_raw_jj_2={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_2={need=9,tag=""}}},
 floricraft_jj_petals_raw_jj_3={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_3={need=9,tag=""}}},
 floricraft_jj_petals_raw_jj_4={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_4={need=9,tag=""}}},
 floricraft_jj_petals_raw_jj_5={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_5={need=9,tag=""}}},
 floricraft_jj_petals_raw_jj_6={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_6={need=9,tag=""}}},
 floricraft_jj_petals_raw_jj_7={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_7={need=9,tag=""}}},
 floricraft_jj_petals_raw_jj_8={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_8={need=9,tag=""}}},
 floricraft_jj_petals_raw_jj_9={hasPattern=true,label="",recipe={floricraft_jj_petal_raw_jj_9={need=9,tag=""}}},
 floricraft_jj_petals_salty={hasPattern=true,label="",recipe={floricraft_jj_petal_salty={need=9,tag=""}}},
 floricraft_jj_petals_salty_jj_1={hasPattern=true,label="",recipe={floricraft_jj_petal_salty_jj_1={need=9,tag=""}}},
 floricraft_jj_petals_salty_jj_10={hasPattern=true,label="",recipe={floricraft_jj_petal_salty_jj_10={need=9,tag=""}}},
 floricraft_jj_petals_salty_jj_11={hasPattern=true,label="",recipe={floricraft_jj_petal_salty_jj_11={need=9,tag=""}}},
 floricraft_jj_petals_salty_jj_12={hasPattern=true,label="",recipe={floricraft_jj_petal_salty_jj_12={need=9,tag=""}}},
 floricraft_jj_petals_salty_jj_13={hasPattern=true,label="",recipe={floricraft_jj_petal_salty_jj_13={need=9,tag=""}}},
 floricraft_jj_petals_salty_jj_14={hasPattern=true,label="",recipe={floricraft_jj_petal_salty_jj_14={need=9,tag=""}}},
 floricraft_jj_petals_salty_jj_2={hasPattern=true,label="",recipe={floricraft_jj_petal_salty_jj_2={need=9,tag=""}}},
 floricraft_jj_petals_salty_jj_3={hasPattern=true,label="",recipe={floricraft_jj_petal_salty_jj_3={need=9,tag=""}}},
 floricraft_jj_petals_salty_jj_4={hasPattern=true,label="",recipe={floricraft_jj_petal_salty_jj_4={need=9,tag=""}}},
 floricraft_jj_petals_salty_jj_5={hasPattern=true,label="",recipe={floricraft_jj_petal_salty_jj_5={need=9,tag=""}}},
 floricraft_jj_petals_salty_jj_6={hasPattern=true,label="",recipe={floricraft_jj_petal_salty_jj_6={need=9,tag=""}}},
 floricraft_jj_petals_salty_jj_7={hasPattern=true,label="",recipe={floricraft_jj_petal_salty_jj_7={need=9,tag=""}}},
 floricraft_jj_petals_salty_jj_8={hasPattern=true,label="",recipe={floricraft_jj_petal_salty_jj_8={need=9,tag=""}}},
 floricraft_jj_petals_salty_jj_9={hasPattern=true,label="",recipe={floricraft_jj_petal_salty_jj_9={need=9,tag=""}}},
 floricraft_jj_petals_sugared={hasPattern=true,label="",recipe={floricraft_jj_petal_sugared={need=9,tag=""}}},
 floricraft_jj_petals_sugared_jj_1={hasPattern=true,label="",recipe={floricraft_jj_petal_sugared_jj_1={need=9,tag=""}}},
 floricraft_jj_petals_sugared_jj_10={hasPattern=true,label="",recipe={floricraft_jj_petal_sugared_jj_10={need=9,tag=""}}},
 floricraft_jj_petals_sugared_jj_11={hasPattern=true,label="",recipe={floricraft_jj_petal_sugared_jj_11={need=9,tag=""}}},
 floricraft_jj_petals_sugared_jj_12={hasPattern=true,label="",recipe={floricraft_jj_petal_sugared_jj_12={need=9,tag=""}}},
 floricraft_jj_petals_sugared_jj_13={hasPattern=true,label="",recipe={floricraft_jj_petal_sugared_jj_13={need=9,tag=""}}},
 floricraft_jj_petals_sugared_jj_14={hasPattern=true,label="",recipe={floricraft_jj_petal_sugared_jj_14={need=9,tag=""}}},
 floricraft_jj_petals_sugared_jj_2={hasPattern=true,label="",recipe={floricraft_jj_petal_sugared_jj_2={need=9,tag=""}}},
 floricraft_jj_petals_sugared_jj_3={hasPattern=true,label="",recipe={floricraft_jj_petal_sugared_jj_3={need=9,tag=""}}},
 floricraft_jj_petals_sugared_jj_4={hasPattern=true,label="",recipe={floricraft_jj_petal_sugared_jj_4={need=9,tag=""}}},
 floricraft_jj_petals_sugared_jj_5={hasPattern=true,label="",recipe={floricraft_jj_petal_sugared_jj_5={need=9,tag=""}}},
 floricraft_jj_petals_sugared_jj_6={hasPattern=true,label="",recipe={floricraft_jj_petal_sugared_jj_6={need=9,tag=""}}},
 floricraft_jj_petals_sugared_jj_7={hasPattern=true,label="",recipe={floricraft_jj_petal_sugared_jj_7={need=9,tag=""}}},
 floricraft_jj_petals_sugared_jj_8={hasPattern=true,label="",recipe={floricraft_jj_petal_sugared_jj_8={need=9,tag=""}}},
 floricraft_jj_petals_sugared_jj_9={hasPattern=true,label="",recipe={floricraft_jj_petal_sugared_jj_9={need=9,tag=""}}},
 floricraft_jj_potpourri={hasPattern=true,label="Potpourri",recipe={floricraft_jj_dust_salt={need=1,tag=""},minecraft_jj_glass={need=5,tag=""},minecraft_jj_glass_pane={need=3,tag=""}}},
 floricraft_jj_purner={hasPattern=true,label="Gartenschere",recipe={minecraft_jj_iron_ingot={need=3,tag=""}}},
 floricraft_jj_round_bale_hay={hasPattern=true,label="Runder Ballen",recipe={floricraft_jj_hemp_twine={need=4,tag=""},minecraft_jj_hay_block={need=1,tag=""},minecraft_jj_paper={need=4,tag=""}}},
 floricraft_jj_round_bale_silage={hasPattern=false,label="",recipe={}},
 floricraft_jj_round_bale_silage_jj_1={hasPattern=false,label="",recipe={}},
 floricraft_jj_round_bale_silage_jj_2={hasPattern=false,label="",recipe={}},
 floricraft_jj_round_bale_silage_jj_3={hasPattern=false,label="",recipe={}},
 floricraft_jj_sachet={hasPattern=true,label="Beutelsack",recipe={floricraft_jj_hemp_cloth={need=3,tag=""},floricraft_jj_hemp_twine={need=3,tag=""}}},
 floricraft_jj_sachet_anti_creeper={hasPattern=true,label="Anti-Creeper-Beutel",recipe={floricraft_jj_sachet_flower={need=1,tag=""},minecraft_jj_gunpowder={need=8,tag=""}}},
 floricraft_jj_sachet_anti_enderman={hasPattern=true,label="Anti-Enderman-Beutel",recipe={floricraft_jj_sachet_flower={need=1,tag=""},minecraft_jj_ender_pearl={need=8,tag=""}}},
 floricraft_jj_sachet_anti_skeleton={hasPattern=true,label="Anti-Skelett-Beutel",recipe={floricraft_jj_sachet_flower={need=1,tag=""},minecraft_jj_bone={need=8,tag=""}}},
 floricraft_jj_sachet_anti_spider={hasPattern=true,label="Anti-Spinnen-Beutel",recipe={floricraft_jj_sachet_flower={need=1,tag=""},minecraft_jj_spider_eye={need=8,tag=""}}},
 floricraft_jj_sachet_anti_zombie={hasPattern=true,label="Anti-Zombie-Beutel",recipe={floricraft_jj_sachet_flower={need=1,tag=""},minecraft_jj_rotten_flesh={need=8,tag=""}}},
 floricraft_jj_sachet_flower={hasPattern=true,label="Blumenbeutel",recipe={floricraft_jj_hemp_yarn={need=1,tag=""},floricraft_jj_sachet={need=1,tag=""}}},
 floricraft_jj_sachet_holder={hasPattern=true,label="Beutelhalter",recipe={floricraft_jj_hemp_twine={need=5,tag=""},floricraft_jj_sachet={need=3,tag=""}}},
 floricraft_jj_sachet_temptation={hasPattern=true,label="Versuchungsbeutel",recipe={floricraft_jj_petals_raw_jj_13={need=8,tag=""},floricraft_jj_sachet_flower={need=1,tag=""}}},
 floricraft_jj_sapling_christmas={hasPattern=true,label="Weihnachtsbaumsetzling",recipe={minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_sapling_jj_1={need=1,tag=""},minecraft_jj_torch={need=3,tag=""}}},
 floricraft_jj_sapling_christmas_jj_1={hasPattern=true,label="Funkelnder Weihnachtsbaumsetzling",recipe={minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_redstone_torch={need=3,tag=""},minecraft_jj_sapling_jj_1={need=1,tag=""}}},
 floricraft_jj_sapling_christmas_jj_2={hasPattern=true,label="Dynamischer Weihnachtsbaumsetzling",recipe={floricraft_jj_sapling_christmas_jj_1={need=1,tag=""}}},
 floricraft_jj_sapling_christmas_jj_3={hasPattern=false,label="",recipe={}},
 floricraft_jj_sapling_floric_type0={hasPattern=true,label="Sakurasetzling",recipe={minecraft_jj_dye_jj_13={need=1,tag=""},minecraft_jj_sapling={need=1,tag=""}}},
 floricraft_jj_sapling_floric_type0_jj_1={hasPattern=true,label="Hartriegelsetzling",recipe={minecraft_jj_dye_jj_9={need=1,tag=""},minecraft_jj_sapling={need=1,tag=""}}},
 floricraft_jj_sapling_floric_type0_jj_2={hasPattern=true,label="Kerriensetzling",recipe={minecraft_jj_dye_jj_11={need=1,tag=""},minecraft_jj_sapling={need=1,tag=""}}},
 floricraft_jj_sapling_floric_type0_jj_3={hasPattern=true,label="Rhododendronsetzling",recipe={minecraft_jj_dye_jj_5={need=1,tag=""},minecraft_jj_sapling={need=1,tag=""}}},
 floricraft_jj_seed_hemp={hasPattern=false,label="",recipe={}},
 floricraft_jj_stack_allium={hasPattern=true,label="Roher Sternlauchhaufen",recipe={floricraft_jj_flower_cut_jj_3={need=7,tag=""},floricraft_jj_hemp_twine={need=2,tag=""}}},
 floricraft_jj_stack_allium_jj_3={hasPattern=false,label="",recipe={}},
 floricraft_jj_stack_azure_bluet={hasPattern=true,label="Roher Porzellansternchenhaufen",recipe={floricraft_jj_flower_cut_jj_4={need=7,tag=""},floricraft_jj_hemp_twine={need=2,tag=""}}},
 floricraft_jj_stack_azure_bluet_jj_3={hasPattern=false,label="",recipe={}},
 floricraft_jj_stack_blue_orchid={hasPattern=true,label="Roher Blaue Orchideen-Haufen",recipe={floricraft_jj_flower_cut_jj_2={need=7,tag=""},floricraft_jj_hemp_twine={need=2,tag=""}}},
 floricraft_jj_stack_blue_orchid_jj_3={hasPattern=false,label="",recipe={}},
 floricraft_jj_stack_dandelion={hasPattern=true,label="Roher Löwenzahnhaufen",recipe={floricraft_jj_flower_cut={need=7,tag=""},floricraft_jj_hemp_twine={need=2,tag=""}}},
 floricraft_jj_stack_dandelion_jj_3={hasPattern=false,label="",recipe={}},
 floricraft_jj_stack_dead={hasPattern=false,label="",recipe={}},
 floricraft_jj_stack_lilac={hasPattern=true,label="Roher Fliederhaufen",recipe={floricraft_jj_flower_cut_jj_11={need=7,tag=""},floricraft_jj_hemp_twine={need=2,tag=""}}},
 floricraft_jj_stack_lilac_jj_3={hasPattern=false,label="",recipe={}},
 floricraft_jj_stack_orange_tulip={hasPattern=true,label="Roher Orange Tulpen-Haufen",recipe={floricraft_jj_flower_cut_jj_6={need=7,tag=""},floricraft_jj_hemp_twine={need=2,tag=""}}},
 floricraft_jj_stack_orange_tulip_jj_3={hasPattern=false,label="",recipe={}},
 floricraft_jj_stack_oxeye_daisy={hasPattern=true,label="Roher Margeritenhaufen",recipe={floricraft_jj_flower_cut_jj_9={need=7,tag=""},floricraft_jj_hemp_twine={need=2,tag=""}}},
 floricraft_jj_stack_oxeye_daisy_jj_3={hasPattern=false,label="",recipe={}},
 floricraft_jj_stack_peony={hasPattern=true,label="Roher Pfingstrosenhaufen",recipe={floricraft_jj_flower_cut_jj_13={need=7,tag=""},floricraft_jj_hemp_twine={need=2,tag=""}}},
 floricraft_jj_stack_peony_jj_3={hasPattern=false,label="",recipe={}},
 floricraft_jj_stack_pink_tulip={hasPattern=true,label="Roher Rosa Tulpen-Haufen",recipe={floricraft_jj_flower_cut_jj_8={need=7,tag=""},floricraft_jj_hemp_twine={need=2,tag=""}}},
 floricraft_jj_stack_pink_tulip_jj_3={hasPattern=false,label="",recipe={}},
 floricraft_jj_stack_poppy={hasPattern=true,label="Roher Mohnhaufen",recipe={floricraft_jj_flower_cut_jj_1={need=7,tag=""},floricraft_jj_hemp_twine={need=2,tag=""}}},
 floricraft_jj_stack_poppy_jj_3={hasPattern=false,label="",recipe={}},
 floricraft_jj_stack_red_tulip={hasPattern=true,label="Roher Rote Tulpen-Haufen",recipe={floricraft_jj_flower_cut_jj_5={need=7,tag=""},floricraft_jj_hemp_twine={need=2,tag=""}}},
 floricraft_jj_stack_red_tulip_jj_3={hasPattern=false,label="",recipe={}},
 floricraft_jj_stack_rose={hasPattern=true,label="Roher Rosenhaufen",recipe={floricraft_jj_flower_cut_jj_12={need=7,tag=""},floricraft_jj_hemp_twine={need=2,tag=""}}},
 floricraft_jj_stack_rose_jj_3={hasPattern=false,label="",recipe={}},
 floricraft_jj_stack_sakura={hasPattern=true,label="Roher Sakurahaufen",recipe={floricraft_jj_flower_cut_jj_14={need=7,tag=""},floricraft_jj_hemp_twine={need=2,tag=""}}},
 floricraft_jj_stack_sakura_jj_3={hasPattern=false,label="",recipe={}},
 floricraft_jj_stack_sunflower={hasPattern=true,label="Roher Sonnenblumenhaufen",recipe={floricraft_jj_flower_cut_jj_10={need=7,tag=""},floricraft_jj_hemp_twine={need=2,tag=""}}},
 floricraft_jj_stack_sunflower_jj_3={hasPattern=false,label="",recipe={}},
 floricraft_jj_stack_white_tulip={hasPattern=true,label="Roher Weiße Tulpen-Haufen",recipe={floricraft_jj_flower_cut_jj_7={need=7,tag=""},floricraft_jj_hemp_twine={need=2,tag=""}}},
 floricraft_jj_stack_white_tulip_jj_3={hasPattern=false,label="",recipe={}},
 floricraft_jj_weather_cock={hasPattern=true,label="Wetterhahn",recipe={minecraft_jj_arrow={need=1,tag=""},minecraft_jj_iron_ingot={need=4,tag=""}}},
 floricraft_jj_weather_cock_jj_1={hasPattern=true,label="Wetterhund",recipe={floricraft_jj_weather_cock={need=1,tag=""}}}
 }