return {
 farmory_jj_blowgun={hasPattern=true,label="Blowgun",recipe={minecraft_jj_leather={need=1,tag=""},minecraft_jj_stick={need=3,tag=""},minecraft_jj_string={need=1,tag=""}}},
 farmory_jj_crossbow={hasPattern=true,label="Crossbow",recipe={minecraft_jj_bow={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_stick={need=4,tag=""},minecraft_jj_string={need=3,tag=""}}},
 farmory_jj_enderiumboots={hasPattern=true,label="Enderium Boots",recipe={fresource_jj_enderiumingot={need=4,tag=""}}},
 farmory_jj_enderiumchestplate={hasPattern=true,label="Enderium ChestPlate",recipe={fresource_jj_enderiumingot={need=8,tag=""}}},
 farmory_jj_enderiumhelmet={hasPattern=true,label="Enderium Helmet",recipe={fresource_jj_enderiumingot={need=5,tag=""}}},
 farmory_jj_enderiumleggings={hasPattern=true,label="Enderium Leggings",recipe={fresource_jj_enderiumingot={need=7,tag=""}}},
 farmory_jj_enderiumsword={hasPattern=true,label="§dEnderium Sword",recipe={fresource_jj_enderiumingot={need=2,tag=""},minecraft_jj_diamond={need=2,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 farmory_jj_longbow={hasPattern=true,label="Long Bow",recipe={minecraft_jj_bow={need=1,tag=""},minecraft_jj_stick={need=2,tag=""},minecraft_jj_string={need=3,tag=""}}},
 farmory_jj_reddiamondboots={hasPattern=true,label="Red Diamond Boots",recipe={fresource_jj_reddiamond={need=4,tag=""}}},
 farmory_jj_reddiamondchestplate={hasPattern=true,label="Red Diamond ChestPlate",recipe={fresource_jj_reddiamond={need=8,tag=""}}},
 farmory_jj_reddiamondhelmet={hasPattern=true,label="Red Diamond Helmet",recipe={fresource_jj_reddiamond={need=5,tag=""}}},
 farmory_jj_reddiamondleggings={hasPattern=true,label="Red Diamond Leggings",recipe={fresource_jj_reddiamond={need=7,tag=""}}},
 farmory_jj_reddiamondsword={hasPattern=true,label="§4Red Diamond Sword",recipe={fresource_jj_reddiamond={need=2,tag=""},minecraft_jj_diamond={need=2,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 farmory_jj_terilliumaxe={hasPattern=true,label="Terillium Axe",recipe={fresource_jj_terillium={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 farmory_jj_terilliumboots={hasPattern=true,label="Terillium Boots",recipe={fresource_jj_terillium={need=4,tag=""}}},
 farmory_jj_terilliumchestplate={hasPattern=true,label="Terillium ChestPlate",recipe={fresource_jj_terillium={need=8,tag=""}}},
 farmory_jj_terilliumhelmet={hasPattern=true,label="Terillium Helmet",recipe={fresource_jj_terillium={need=5,tag=""}}},
 farmory_jj_terilliumhoe={hasPattern=true,label="Terillium Hoe",recipe={fresource_jj_terillium={need=2,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 farmory_jj_terilliumleggings={hasPattern=true,label="Terillium Leggings",recipe={fresource_jj_terillium={need=7,tag=""}}},
 farmory_jj_terilliumpickaxe={hasPattern=true,label="Terillium Pickaxe",recipe={fresource_jj_terillium={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 farmory_jj_terilliumshovel={hasPattern=true,label="Terillium Shovel",recipe={fresource_jj_terillium={need=1,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 farmory_jj_terilliumsword={hasPattern=true,label="§aTerillium Sword",recipe={fresource_jj_terillium={need=2,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 fcl_jj_blueprinttable={hasPattern=true,label="tile.fcl:blueprinttable.name",recipe={minecraft_jj_crafting_table={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_log={need=2,tag=""}}},
 fcl_jj_workbench={hasPattern=true,label="tile.fcl:workbench.name",recipe={frsm_jj_ironsaw={need=1,tag=""},minecraft_jj_crafting_table={need=1,tag=""}}},
 fdecostuff_jj_andesite_slab_double={hasPattern=false,label="",recipe={}},
 fdecostuff_jj_andesite_slab_half={hasPattern=true,label="Andesite Brick Slab",recipe={fdecostuff_jj_andesitebrick={need=3,tag=""}}},
 fdecostuff_jj_andesitebrick={hasPattern=true,label="Andesite Brick",recipe={minecraft_jj_stone_jj_6={need=4,tag=""}}},
 fdecostuff_jj_andesitebrickcarved={hasPattern=true,label="Andesite Brick Carved",recipe={fdecostuff_jj_andesite_slab_half={need=2,tag=""}}},
 fdecostuff_jj_andesitebrickcracked={hasPattern=true,label="Andesite Brick Cracked",recipe={fdecostuff_jj_andesitebrick={need=1,tag=""}}},
 fdecostuff_jj_andesitebrickmossy={hasPattern=true,label="Andesite Brick Mossy",recipe={fdecostuff_jj_andesitebrick={need=1,tag=""},minecraft_jj_vine={need=1,tag=""}}},
 fdecostuff_jj_christmas_tree={hasPattern=true,label="Christmas Tree",recipe={minecraft_jj_leaves_jj_1={need=4,tag=""},minecraft_jj_log_jj_1={need=1,tag=""}}},
 fdecostuff_jj_diorite_slab_double={hasPattern=false,label="",recipe={}},
 fdecostuff_jj_diorite_slab_half={hasPattern=true,label="Diorite Brick Slab",recipe={fdecostuff_jj_dioritebrick={need=3,tag=""}}},
 fdecostuff_jj_dioritebrick={hasPattern=true,label="Diorite Brick",recipe={minecraft_jj_stone_jj_4={need=4,tag=""}}},
 fdecostuff_jj_dioritebrickcarved={hasPattern=true,label="Diorite Brick Carved",recipe={fdecostuff_jj_diorite_slab_half={need=2,tag=""}}},
 fdecostuff_jj_dioritebrickcracked={hasPattern=true,label="Diorite Brick Cracked",recipe={fdecostuff_jj_dioritebrick={need=1,tag=""}}},
 fdecostuff_jj_dioritebrickmossy={hasPattern=true,label="Diorite Brick Mossy",recipe={fdecostuff_jj_dioritebrick={need=1,tag=""},minecraft_jj_vine={need=1,tag=""}}},
 fdecostuff_jj_endstone_slab_double={hasPattern=false,label="",recipe={}},
 fdecostuff_jj_endstone_slab_half={hasPattern=true,label="End Stone Brick Slab",recipe={minecraft_jj_end_bricks={need=3,tag=""}}},
 fdecostuff_jj_endstonebrickcarved={hasPattern=true,label="End Stone Brick Carved",recipe={fdecostuff_jj_endstone_slab_half={need=2,tag=""}}},
 fdecostuff_jj_endstonebrickcracked={hasPattern=true,label="End Stone Brick Cracked",recipe={minecraft_jj_end_bricks={need=1,tag=""}}},
 fdecostuff_jj_endstonebrickmossy={hasPattern=true,label="End Stone Brick Mossy",recipe={minecraft_jj_end_bricks={need=1,tag=""},minecraft_jj_vine={need=1,tag=""}}},
 fdecostuff_jj_granite_slab_double={hasPattern=false,label="",recipe={}},
 fdecostuff_jj_granite_slab_half={hasPattern=true,label="Granite Brick Slab",recipe={fdecostuff_jj_granitebrick={need=3,tag=""}}},
 fdecostuff_jj_granitebrick={hasPattern=true,label="Granite Brick",recipe={minecraft_jj_stone_jj_2={need=4,tag=""}}},
 fdecostuff_jj_granitebrickcarved={hasPattern=true,label="Granite Brick Carved",recipe={fdecostuff_jj_granite_slab_half={need=2,tag=""}}},
 fdecostuff_jj_granitebrickcracked={hasPattern=true,label="Granite Brick Cracked",recipe={fdecostuff_jj_granitebrick={need=1,tag=""}}},
 fdecostuff_jj_granitebrickmossy={hasPattern=true,label="Granite Brick Mossy",recipe={fdecostuff_jj_granitebrick={need=1,tag=""},minecraft_jj_vine={need=1,tag=""}}},
 ffactory_jj_barrel={hasPattern=true,label="Barrel",recipe={minecraft_jj_log={need=6,tag=""},minecraft_jj_water_bucket={need=1,tag=""},minecraft_jj_wooden_slab={need=2,tag=""}}},
 ffactory_jj_ironfurnace={hasPattern=true,label="Iron Furnace",recipe={minecraft_jj_furnace={need=1,tag=""},minecraft_jj_iron_ingot={need=6,tag=""}}},
 ffactory_jj_lit_ironfurnace={hasPattern=false,label="",recipe={}},
 ffactory_jj_lit_steampunkfurnace={hasPattern=false,label="",recipe={}},
 ffactory_jj_steampunkfurnace={hasPattern=true,label="Steampunk Furnace",recipe={fresource_jj_bronzeingot={need=8,tag=""},minecraft_jj_furnace={need=1,tag=""}}},
 ffoods_jj_applejam={hasPattern=true,label="Apple Jam",recipe={minecraft_jj_apple={need=1,tag=""},minecraft_jj_glass_bottle={need=1,tag=""},minecraft_jj_sugar={need=1,tag=""}}},
 ffoods_jj_applejamjar={hasPattern=true,label="Jar of Apple Jam",recipe={ffoods_jj_applejam={need=8,tag=""},minecraft_jj_glass={need=1,tag=""}}},
 ffoods_jj_appletoast={hasPattern=true,label="Toast with Apple Jam",recipe={ffoods_jj_applejam={need=1,tag=""},ffoods_jj_toast={need=1,tag=""}}},
 ffoods_jj_barley={hasPattern=false,label="",recipe={}},
 ffoods_jj_barley_seeds={hasPattern=false,label="",recipe={}},
 ffoods_jj_beer={hasPattern=true,label="Beer",recipe={ffoods_jj_barley={need=1,tag=""},ffoods_jj_beermug={need=1,tag=""},minecraft_jj_sugar={need=1,tag=""}}},
 ffoods_jj_beermug={hasPattern=true,label="Beer Mug",recipe={minecraft_jj_glass={need=4,tag=""}}},
 ffoods_jj_cereals={hasPattern=true,label="Cereals",recipe={ffoods_jj_flour={need=1,tag=""},minecraft_jj_sugar={need=1,tag=""}}},
 ffoods_jj_cerealsbowl={hasPattern=true,label="Cereals Bowl",recipe={ffoods_jj_cereals={need=1,tag=""},minecraft_jj_bowl={need=1,tag=""},minecraft_jj_milk_bucket={need=1,tag=""}}},
 ffoods_jj_chocolatecereals={hasPattern=true,label="Chocolate Cereals",recipe={ffoods_jj_flour={need=1,tag=""},minecraft_jj_dye_jj_3={need=1,tag=""},minecraft_jj_sugar={need=1,tag=""}}},
 ffoods_jj_chocolatecerealsbowl={hasPattern=true,label="Chocolate Cereals Bowl",recipe={ffoods_jj_chocolatecereals={need=1,tag=""},minecraft_jj_bowl={need=1,tag=""},minecraft_jj_milk_bucket={need=1,tag=""}}},
 ffoods_jj_flour={hasPattern=true,label="Flour",recipe={minecraft_jj_stick={need=1,tag=""},minecraft_jj_wheat={need=1,tag=""}}},
 ffoods_jj_kitchenknife={hasPattern=true,label="Kitchen Kinfe",recipe={actuallyadditions_jj_item_knife={need=1,tag=""}}},
 ffoods_jj_toast={hasPattern=true,label="Toast",recipe={ffoods_jj_kitchenknife={need=1,tag=""},minecraft_jj_bread={need=1,tag=""}}},
 fmagic_jj_wfragment={hasPattern=true,label="§bWither Fragment",recipe={fmagic_jj_wseed={need=1,tag=""}}},
 fmagic_jj_wseed={hasPattern=true,label="Wither Seed",recipe={fresource_jj_terillium={need=4,tag=""},minecraft_jj_glowstone_dust={need=4,tag=""},minecraft_jj_skull_jj_1={need=1,tag=""}}},
 fresource_jj_blazecoal={hasPattern=false,label="Blaze Coal",recipe={}},
 fresource_jj_blazecoalblock={hasPattern=true,label="Blaze Coal Block",recipe={fresource_jj_blazecoal={need=9,tag=""}}},
 fresource_jj_blazecoalore={hasPattern=false,label="",recipe={}},
 fresource_jj_bronzeingot={hasPattern=true,label="Bronze Ingot",recipe={ic2_jj_ingot_jj_1={need=1,tag=""}}},
 fresource_jj_copperingot={hasPattern=true,label="Copper Ingot",recipe={mekanism_jj_ingot_jj_5={need=1,tag=""}}},
 fresource_jj_copperore={hasPattern=false,label="",recipe={}},
 fresource_jj_enderiumblock={hasPattern=true,label="Enderium Block",recipe={fresource_jj_enderiumingot={need=9,tag=""}}},
 fresource_jj_enderiumingot={hasPattern=true,label="§dEnderium Ingot",recipe={thermalfoundation_jj_material_jj_167={need=1,tag=""}}},
 fresource_jj_enderiumore={hasPattern=false,label="",recipe={}},
 fresource_jj_rawterillium={hasPattern=false,label="",recipe={}},
 fresource_jj_reddiamond={hasPattern=false,label="",recipe={}},
 fresource_jj_reddiamondblock={hasPattern=true,label="Red Diamond Block",recipe={fresource_jj_reddiamond={need=9,tag=""}}},
 fresource_jj_reddiamondore={hasPattern=false,label="",recipe={}},
 fresource_jj_terillium={hasPattern=true,label="§aTerillium",recipe={fresource_jj_rawterillium={need=1,tag=""},minecraft_jj_glowstone_dust={need=2,tag=""},minecraft_jj_redstone={need=2,tag=""}}},
 fresource_jj_terilliumblock={hasPattern=true,label="Terillium Block",recipe={fresource_jj_terillium={need=9,tag=""}}},
 fresource_jj_terilliumore={hasPattern=false,label="",recipe={}},
 fresource_jj_tiningot={hasPattern=true,label="Tin Ingot",recipe={mekanism_jj_ingot_jj_6={need=1,tag=""}}},
 fresource_jj_tinore={hasPattern=false,label="",recipe={}},
 frsm_jj_asphalt={hasPattern=true,label="Asphalt",recipe={car_jj_tar={need=1,tag=""}}},
 frsm_jj_asphalt2={hasPattern=true,label="Asphalt",recipe={frsm_jj_asphalt={need=1,tag=""}}},
 frsm_jj_asphalt2slab={hasPattern=true,label="Asphalt Slab",recipe={frsm_jj_asphalt2={need=3,tag=""}}},
 frsm_jj_asphaltfull={hasPattern=true,label="Full Asphalt Block",recipe={frsm_jj_asphalt2={need=1,tag=""}}},
 frsm_jj_asphaltslab={hasPattern=true,label="Asphalt Slab",recipe={frsm_jj_asphaltfull={need=3,tag=""}}},
 frsm_jj_bacon={hasPattern=true,label="Bacon",recipe={frsm_jj_baconraw={need=1,tag=""}}},
 frsm_jj_baconraw={hasPattern=true,label="Raw Bacon",recipe={minecraft_jj_porkchop={need=1,tag=""}}},
 frsm_jj_bench1={hasPattern=true,label="Bench",recipe={frsm_jj_planks_oak={need=6,tag=""}}},
 frsm_jj_bench1_1={hasPattern=true,label="Bench",recipe={frsm_jj_planks_oak={need=6,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 frsm_jj_bench1_2={hasPattern=true,label="Bench",recipe={frsm_jj_planks_oak={need=6,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 frsm_jj_bench1_3={hasPattern=true,label="Bench",recipe={frsm_jj_planks_oak={need=6,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 frsm_jj_brush={hasPattern=true,label="Brush",recipe={minecraft_jj_stick={need=2,tag=""},minecraft_jj_wool={need=1,tag=""}}},
 frsm_jj_busstation={hasPattern=true,label="Bus Station",recipe={frsm_jj_bench1={need=1,tag=""},frsm_jj_bench1_1={need=1,tag=""},frsm_jj_bench1_2={need=1,tag=""},immersiveengineering_jj_metal_jj_39={need=1,tag=""},minecraft_jj_glass_pane={need=3,tag=""},mmdlib_jj_iron_rod={need=2,tag=""}}},
 frsm_jj_busstop={hasPattern=true,label="Bus Stop Sign",recipe={immersiveengineering_jj_metal_jj_39={need=1,tag=""},minecraft_jj_dye_jj_4={need=2,tag=""},mmdlib_jj_iron_rod={need=2,tag=""}}},
 frsm_jj_car1d={hasPattern=true,label="Deco Model Car",recipe={minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_planks={need=1,tag=""}}},
 frsm_jj_cheese={hasPattern=true,label="Cheese",recipe={minecraft_jj_milk_bucket={need=1,tag=""}}},
 frsm_jj_cheesepie={hasPattern=true,label="Cheese Pie",recipe={frsm_jj_cheesewhite={need=1,tag=""},minecraft_jj_egg={need=1,tag=""},minecraft_jj_sugar={need=1,tag=""}}},
 frsm_jj_cheesewhite={hasPattern=true,label="White Cheese",recipe={frsm_jj_cheese={need=4,tag=""},minecraft_jj_milk_bucket={need=1,tag=""}}},
 frsm_jj_chimney={hasPattern=false,label="",recipe={}},
 frsm_jj_chimney_jj_1={hasPattern=false,label="",recipe={}},
 frsm_jj_chimney_jj_2={hasPattern=false,label="",recipe={}},
 frsm_jj_chimney_jj_3={hasPattern=false,label="",recipe={}},
 frsm_jj_chimney_jj_4={hasPattern=false,label="",recipe={}},
 frsm_jj_chocolatebar={hasPattern=true,label="Chocolate Bar",recipe={frsm_jj_chocolatemilk={need=1,tag=""},minecraft_jj_sugar={need=1,tag=""}}},
 frsm_jj_chocolatebarwhite={hasPattern=true,label="White Chocolate Bar",recipe={minecraft_jj_milk_bucket={need=1,tag=""},minecraft_jj_sugar={need=1,tag=""}}},
 frsm_jj_chocolatecookie={hasPattern=true,label="Chocolate Cookie",recipe={frsm_jj_chocolatemilk={need=1,tag=""},minecraft_jj_wheat={need=1,tag=""}}},
 frsm_jj_chocolatemilk={hasPattern=true,label="Chocolate Milk",recipe={minecraft_jj_dye_jj_3={need=1,tag=""},minecraft_jj_milk_bucket={need=1,tag=""}}},
 frsm_jj_clock1={hasPattern=true,label="Clock (1)",recipe={conquest_jj_needle={need=3,tag=""},immersiveengineering_jj_metal_jj_39={need=1,tag=""},minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 frsm_jj_clock1c={hasPattern=true,label="Clock (1c)",recipe={frsm_jj_clock1={need=1,tag=""}}},
 frsm_jj_clock1w={hasPattern=true,label="Clock (1w)",recipe={frsm_jj_clock1c={need=1,tag=""}}},
 frsm_jj_clock2={hasPattern=false,label="",recipe={}},
 frsm_jj_clock2c={hasPattern=false,label="",recipe={}},
 frsm_jj_clock2w={hasPattern=false,label="",recipe={}},
 frsm_jj_cobble1={hasPattern=true,label="Cobblestone",recipe={frsm_jj_nesr={need=1,tag=""}}},
 frsm_jj_cobble10={hasPattern=true,label="Cobblestone",recipe={frsm_jj_cobble1={need=1,tag=""}}},
 frsm_jj_cobble10b={hasPattern=true,label="Cobblestone",recipe={frsm_jj_cobble10={need=1,tag=""}}},
 frsm_jj_cobble2={hasPattern=true,label="Cobblestone",recipe={frsm_jj_cobble10b={need=1,tag=""}}},
 frsm_jj_cobble3={hasPattern=true,label="Cobblestone",recipe={frsm_jj_cobble2={need=1,tag=""}}},
 frsm_jj_cobble4={hasPattern=true,label="Cobblestone",recipe={frsm_jj_cobble3={need=1,tag=""}}},
 frsm_jj_cobble5={hasPattern=true,label="Cobblestone",recipe={frsm_jj_cobble4={need=1,tag=""}}},
 frsm_jj_cobble5b={hasPattern=true,label="CobbleStone",recipe={frsm_jj_cobble5={need=1,tag=""}}},
 frsm_jj_cobble6={hasPattern=true,label="CobbleStone",recipe={frsm_jj_cobble5b={need=1,tag=""}}},
 frsm_jj_cobble6b={hasPattern=true,label="CobbleStone",recipe={frsm_jj_cobble6={need=1,tag=""}}},
 frsm_jj_cobble7={hasPattern=true,label="CobbleStone",recipe={frsm_jj_cobble6b={need=1,tag=""}}},
 frsm_jj_cobble7b={hasPattern=true,label="CobbleStone",recipe={frsm_jj_cobble7={need=1,tag=""}}},
 frsm_jj_cobble8={hasPattern=true,label="CobbleStone",recipe={frsm_jj_cobble7b={need=1,tag=""}}},
 frsm_jj_cobble8b={hasPattern=true,label="CobbleStone",recipe={frsm_jj_cobble8={need=1,tag=""}}},
 frsm_jj_cobble9={hasPattern=true,label="CobbleStone",recipe={frsm_jj_cobble8b={need=1,tag=""}}},
 frsm_jj_cobble9b={hasPattern=true,label="CobbleStone",recipe={frsm_jj_cobble9={need=1,tag=""}}},
 frsm_jj_cookedegg={hasPattern=true,label="Omelet",recipe={minecraft_jj_egg={need=1,tag=""}}},
 frsm_jj_crate={hasPattern=true,label="Crate",recipe={frsm_jj_ironsaw={need=1,tag=""},minecraft_jj_chest={need=1,tag=""}}},
 frsm_jj_cup={hasPattern=true,label="Cup",recipe={minecraft_jj_clay_ball={need=1,tag=""}}},
 frsm_jj_cupwithcacao={hasPattern=true,label="Cacao Drink",recipe={frsm_jj_cup={need=1,tag=""},minecraft_jj_dye_jj_3={need=1,tag=""}}},
 frsm_jj_decoblock1={hasPattern=true,label="tile.frsm:decoblock1.white.name",recipe={minecraft_jj_log={need=5,tag=""},minecraft_jj_wool={need=4,tag=""}}},
 frsm_jj_decoblock2={hasPattern=true,label="Deco Block (2)",recipe={minecraft_jj_log={need=3,tag=""},minecraft_jj_wool={need=6,tag=""}}},
 frsm_jj_donut={hasPattern=true,label="Donut",recipe={frsm_jj_chocolatemilk={need=1,tag=""},minecraft_jj_sugar={need=1,tag=""},minecraft_jj_wheat={need=1,tag=""}}},
 frsm_jj_electric_pizza_oven={hasPattern=true,label="Electric Pizza Oven",recipe={frsm_jj_nesr={need=1,tag=""},minecraft_jj_furnace={need=1,tag=""}}},
 frsm_jj_fence1={hasPattern=true,label="Iron Fence",recipe={minecraft_jj_iron_bars={need=3,tag=""},minecraft_jj_iron_ingot={need=2,tag=""},minecraft_jj_stone={need=3,tag=""}}},
 frsm_jj_framedglowstone={hasPattern=true,label="Framed Glowstone",recipe={minecraft_jj_glowstone={need=1,tag=""},minecraft_jj_planks={need=4,tag=""}}},
 frsm_jj_framedglowstone_jj_1={hasPattern=true,label="Framed Glowstone",recipe={minecraft_jj_glowstone={need=1,tag=""},minecraft_jj_planks_jj_1={need=4,tag=""}}},
 frsm_jj_framedglowstone_jj_2={hasPattern=true,label="Framed Glowstone",recipe={minecraft_jj_glowstone={need=1,tag=""},minecraft_jj_planks_jj_2={need=4,tag=""}}},
 frsm_jj_framedglowstone_jj_3={hasPattern=true,label="Framed Glowstone",recipe={minecraft_jj_glowstone={need=1,tag=""},minecraft_jj_planks_jj_3={need=4,tag=""}}},
 frsm_jj_framedglowstone_jj_4={hasPattern=true,label="Framed Glowstone",recipe={minecraft_jj_glowstone={need=1,tag=""},minecraft_jj_planks_jj_4={need=4,tag=""}}},
 frsm_jj_framedglowstone_jj_5={hasPattern=true,label="Framed Glowstone",recipe={minecraft_jj_glowstone={need=1,tag=""},minecraft_jj_planks_jj_5={need=4,tag=""}}},
 frsm_jj_fridge={hasPattern=true,label="Fridge",recipe={cookingforblockheads_jj_fridge={need=1,tag=""},frsm_jj_nesr={need=1,tag=""}}},
 frsm_jj_furnace1={hasPattern=false,label="",recipe={}},
 frsm_jj_furnace1b={hasPattern=false,label="",recipe={}},
 frsm_jj_hamburger={hasPattern=true,label="Hamburger",recipe={minecraft_jj_bread={need=2,tag=""},minecraft_jj_cooked_beef={need=1,tag=""}}},
 frsm_jj_iron_barrel={hasPattern=false,label="",recipe={}},
 frsm_jj_ironsaw={hasPattern=true,label="Iron Saw",recipe={minecraft_jj_iron_ingot={need=2,tag=""},minecraft_jj_planks={need=1,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 frsm_jj_jar={hasPattern=true,label="Glass Jar",recipe={frsm_jj_nesr={need=1,tag=""},minecraft_jj_glass={need=1,tag=""}}},
 frsm_jj_kd1={hasPattern=true,label="Kitchen Deco (1)",recipe={frsm_jj_cup={need=1,tag=""},frsm_jj_jar={need=2,tag=""},frsm_jj_tomatojar={need=1,tag=""}}},
 frsm_jj_kd2={hasPattern=true,label="Kitchen Deco (2)",recipe={frsm_jj_stonemugwithbeer={need=2,tag=""},minecraft_jj_clay_ball={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 frsm_jj_key={hasPattern=false,label="",recipe={}},
 frsm_jj_keyboard={hasPattern=true,label="Keyboard",recipe={frsm_jj_nesr={need=1,tag=""},minecraft_jj_iron_ingot={need=2,tag=""},minecraft_jj_stone_button={need=6,tag=""}}},
 frsm_jj_lamp={hasPattern=false,label="Lamp",recipe={}},
 frsm_jj_lamp_jj_1={hasPattern=false,label="Lamp",recipe={}},
 frsm_jj_lamp_jj_10={hasPattern=false,label="Lamp",recipe={}},
 frsm_jj_lamp_jj_11={hasPattern=false,label="Lamp",recipe={}},
 frsm_jj_lamp_jj_12={hasPattern=false,label="Lamp",recipe={}},
 frsm_jj_lamp_jj_13={hasPattern=false,label="Lamp",recipe={}},
 frsm_jj_lamp_jj_14={hasPattern=false,label="Lamp",recipe={}},
 frsm_jj_lamp_jj_15={hasPattern=true,label="Lamp",recipe={minecraft_jj_glowstone={need=1,tag=""},minecraft_jj_wool_jj_15={need=5,tag=""}}},
 frsm_jj_lamp_jj_2={hasPattern=false,label="",recipe={}},
 frsm_jj_lamp_jj_3={hasPattern=false,label="",recipe={}},
 frsm_jj_lamp_jj_4={hasPattern=false,label="",recipe={}},
 frsm_jj_lamp_jj_5={hasPattern=false,label="",recipe={}},
 frsm_jj_lamp_jj_6={hasPattern=false,label="",recipe={}},
 frsm_jj_lamp_jj_7={hasPattern=false,label="",recipe={}},
 frsm_jj_lamp_jj_8={hasPattern=false,label="",recipe={}},
 frsm_jj_lamp_jj_9={hasPattern=false,label="",recipe={}},
 frsm_jj_lampoff={hasPattern=false,label="",recipe={}},
 frsm_jj_lampoff_jj_1={hasPattern=false,label="",recipe={}},
 frsm_jj_lampoff_jj_10={hasPattern=false,label="",recipe={}},
 frsm_jj_lampoff_jj_11={hasPattern=false,label="",recipe={}},
 frsm_jj_lampoff_jj_12={hasPattern=false,label="",recipe={}},
 frsm_jj_lampoff_jj_13={hasPattern=false,label="",recipe={}},
 frsm_jj_lampoff_jj_14={hasPattern=false,label="",recipe={}},
 frsm_jj_lampoff_jj_15={hasPattern=false,label="",recipe={}},
 frsm_jj_lampoff_jj_2={hasPattern=false,label="",recipe={}},
 frsm_jj_lampoff_jj_3={hasPattern=false,label="",recipe={}},
 frsm_jj_lampoff_jj_4={hasPattern=false,label="",recipe={}},
 frsm_jj_lampoff_jj_5={hasPattern=false,label="",recipe={}},
 frsm_jj_lampoff_jj_6={hasPattern=false,label="",recipe={}},
 frsm_jj_lampoff_jj_7={hasPattern=false,label="",recipe={}},
 frsm_jj_lampoff_jj_8={hasPattern=false,label="",recipe={}},
 frsm_jj_lampoff_jj_9={hasPattern=false,label="",recipe={}},
 frsm_jj_laptop={hasPattern=true,label="Laptop",recipe={frsm_jj_keyboard={need=1,tag=""},frsm_jj_laptopmainboard={need=1,tag=""},frsm_jj_nesr={need=1,tag=""},frsm_jj_redstoneinput={need=1,tag=""},frsm_jj_tvscreensmall={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 frsm_jj_laptop_black={hasPattern=true,label="Black Laptop",recipe={frsm_jj_keyboard={need=1,tag=""},frsm_jj_laptopmainboard={need=1,tag=""},frsm_jj_nesr={need=1,tag=""},frsm_jj_redstoneinput={need=1,tag=""},frsm_jj_tvscreensmall={need=1,tag=""},minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 frsm_jj_laptop_blue={hasPattern=true,label="Blue Laptop",recipe={frsm_jj_keyboard={need=1,tag=""},frsm_jj_laptopmainboard={need=1,tag=""},frsm_jj_nesr={need=1,tag=""},frsm_jj_redstoneinput={need=1,tag=""},frsm_jj_tvscreensmall={need=1,tag=""},minecraft_jj_dye_jj_4={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 frsm_jj_laptop_green={hasPattern=true,label="Green Laptop",recipe={frsm_jj_keyboard={need=1,tag=""},frsm_jj_laptopmainboard={need=1,tag=""},frsm_jj_nesr={need=1,tag=""},frsm_jj_redstoneinput={need=1,tag=""},frsm_jj_tvscreensmall={need=1,tag=""},minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 frsm_jj_laptop_red={hasPattern=true,label="Red Laptop",recipe={frsm_jj_keyboard={need=1,tag=""},frsm_jj_laptopmainboard={need=1,tag=""},frsm_jj_nesr={need=1,tag=""},frsm_jj_redstoneinput={need=1,tag=""},frsm_jj_tvscreensmall={need=1,tag=""},minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 frsm_jj_laptop_white={hasPattern=true,label="White Laptop",recipe={frsm_jj_keyboard={need=1,tag=""},frsm_jj_laptopmainboard={need=1,tag=""},frsm_jj_nesr={need=1,tag=""},frsm_jj_redstoneinput={need=1,tag=""},frsm_jj_tvscreensmall={need=1,tag=""},minecraft_jj_dye_jj_15={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 frsm_jj_laptopmainboard={hasPattern=true,label="Laptop Mainboard",recipe={frsm_jj_prozessor2={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""},minecraft_jj_slime_ball={need=1,tag=""}}},
 frsm_jj_model_rail={hasPattern=true,label="Model Rail",recipe={minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_stick={need=6,tag=""}}},
 frsm_jj_model_railturn={hasPattern=true,label="Model Rail Turn",recipe={frsm_jj_model_rail={need=1,tag=""}}},
 frsm_jj_model_station={hasPattern=true,label="Model Station (1)",recipe={frsm_jj_model_rail={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 frsm_jj_model_station2={hasPattern=true,label="Model Station (2)",recipe={frsm_jj_model_rail={need=1,tag=""},minecraft_jj_iron_ingot={need=2,tag=""}}},
 frsm_jj_model_station3={hasPattern=true,label="Model Station (3)",recipe={frsm_jj_model_station2={need=1,tag=""},minecraft_jj_glowstone_dust={need=1,tag=""}}},
 frsm_jj_nesr={hasPattern=true,label="NESR - Not Existing Stuff Replace",recipe={minecraft_jj_cobblestone={need=1,tag=""},minecraft_jj_dirt={need=1,tag=""}}},
 frsm_jj_officechair={hasPattern=true,label="Officechair",recipe={minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_wool={need=3,tag=""}}},
 frsm_jj_paintbucket={hasPattern=true,label="Paint Bucket",recipe={minecraft_jj_bucket={need=1,tag=""},minecraft_jj_dye_jj_15={need=4,tag=""}}},
 frsm_jj_paintset0={hasPattern=true,label="White Paint Set",recipe={frsm_jj_brush={need=1,tag=""},frsm_jj_paintbucket={need=1,tag=""}}},
 frsm_jj_paintset1={hasPattern=true,label="Orange Paint Set",recipe={frsm_jj_brush={need=1,tag=""},frsm_jj_paintbucket_jj_1={need=1,tag=""}}},
 frsm_jj_paintset10={hasPattern=true,label="Purple Paint Set",recipe={frsm_jj_brush={need=1,tag=""},frsm_jj_paintbucket_jj_10={need=1,tag=""}}},
 frsm_jj_paintset11={hasPattern=true,label="Blue Paint Set",recipe={frsm_jj_brush={need=1,tag=""},frsm_jj_paintbucket_jj_11={need=1,tag=""}}},
 frsm_jj_paintset12={hasPattern=true,label="Brown Paint Set",recipe={frsm_jj_brush={need=1,tag=""},frsm_jj_paintbucket_jj_12={need=1,tag=""}}},
 frsm_jj_paintset13={hasPattern=true,label="Green Paint Set",recipe={frsm_jj_brush={need=1,tag=""},frsm_jj_paintbucket_jj_13={need=1,tag=""}}},
 frsm_jj_paintset14={hasPattern=true,label="Red Paint Set",recipe={frsm_jj_brush={need=1,tag=""},frsm_jj_paintbucket_jj_14={need=1,tag=""}}},
 frsm_jj_paintset15={hasPattern=true,label="Black Paint Set",recipe={frsm_jj_brush={need=1,tag=""},frsm_jj_paintbucket_jj_15={need=1,tag=""}}},
 frsm_jj_paintset16={hasPattern=true,label="Customisable Paint Set",recipe={frsm_jj_brush={need=1,tag=""},frsm_jj_paintbucket_jj_15={need=1,tag=""},minecraft_jj_dye={need=1,tag=""}}},
 frsm_jj_paintset2={hasPattern=true,label="Magenta Paint Set",recipe={frsm_jj_brush={need=1,tag=""},frsm_jj_paintbucket_jj_2={need=1,tag=""}}},
 frsm_jj_paintset3={hasPattern=true,label="Light Blue Paint Set",recipe={frsm_jj_brush={need=1,tag=""},frsm_jj_paintbucket_jj_3={need=1,tag=""}}},
 frsm_jj_paintset4={hasPattern=true,label="Yellow Paint Set",recipe={frsm_jj_brush={need=1,tag=""},frsm_jj_paintbucket_jj_4={need=1,tag=""}}},
 frsm_jj_paintset5={hasPattern=true,label="Lime Paint Set",recipe={frsm_jj_brush={need=1,tag=""},frsm_jj_paintbucket_jj_5={need=1,tag=""}}},
 frsm_jj_paintset6={hasPattern=true,label="Pink Paint Set",recipe={frsm_jj_brush={need=1,tag=""},frsm_jj_paintbucket_jj_6={need=1,tag=""}}},
 frsm_jj_paintset7={hasPattern=true,label="Gray Paint Set",recipe={frsm_jj_brush={need=1,tag=""},frsm_jj_paintbucket_jj_7={need=1,tag=""}}},
 frsm_jj_paintset8={hasPattern=true,label="Light Gray Paint Set",recipe={frsm_jj_brush={need=1,tag=""},frsm_jj_paintbucket_jj_8={need=1,tag=""}}},
 frsm_jj_paintset9={hasPattern=true,label="Cyan Paint Set",recipe={frsm_jj_brush={need=1,tag=""},frsm_jj_paintbucket_jj_9={need=1,tag=""}}},
 frsm_jj_palet1x1={hasPattern=false,label="",recipe={}},
 frsm_jj_palet1x1_1={hasPattern=false,label="",recipe={}},
 frsm_jj_palet1x1_2={hasPattern=false,label="",recipe={}},
 frsm_jj_pchardware1={hasPattern=true,label="Desktop Computer Hardware",recipe={frsm_jj_nesr={need=1,tag=""},frsm_jj_pcmainboard={need=1,tag=""},frsm_jj_redstoneinput={need=1,tag=""},minecraft_jj_iron_ingot={need=6,tag=""}}},
 frsm_jj_pchardware2={hasPattern=true,label="Monitor, Keyboard and Mouse",recipe={frsm_jj_keyboard={need=1,tag=""},frsm_jj_nesr={need=1,tag=""},frsm_jj_redstoneinput={need=1,tag=""},frsm_jj_tvscreensmall={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 frsm_jj_pcmainboard={hasPattern=true,label="Desktop Computer Mainboard",recipe={frsm_jj_nesr={need=1,tag=""},frsm_jj_prozessor4={need=1,tag=""},minecraft_jj_dye_jj_4={need=1,tag=""},minecraft_jj_iron_ingot={need=2,tag=""},minecraft_jj_slime_ball={need=1,tag=""}}},
 frsm_jj_pillar1={hasPattern=true,label="Quartz Pillar",recipe={minecraft_jj_quartz_block_jj_2={need=1,tag=""}}},
 frsm_jj_pillar1_bottom={hasPattern=true,label="Quartz Pillar Bottom",recipe={frsm_jj_pillar1={need=1,tag=""}}},
 frsm_jj_pillar1_top={hasPattern=true,label="Quartz Pillar Top",recipe={frsm_jj_pillar1_bottom={need=1,tag=""}}},
 frsm_jj_pizza={hasPattern=true,label="Pizza",recipe={frsm_jj_cheese={need=2,tag=""},frsm_jj_salami={need=3,tag=""},frsm_jj_tomatojar={need=1,tag=""},minecraft_jj_wheat={need=3,tag=""}}},
 frsm_jj_placeholder={hasPattern=false,label="",recipe={}},
 frsm_jj_planks_oak={hasPattern=false,label="",recipe={}},
 frsm_jj_potatochipsbag={hasPattern=true,label="Potato Chips Bag",recipe={minecraft_jj_baked_potato={need=3,tag=""},minecraft_jj_paper={need=6,tag=""}}},
 frsm_jj_potatochipscheese={hasPattern=true,label="Potato Chips with Cheese",recipe={frsm_jj_cheese={need=1,tag=""},minecraft_jj_baked_potato={need=2,tag=""},minecraft_jj_paper={need=6,tag=""}}},
 frsm_jj_potatochipstomato={hasPattern=true,label="item.frsm:potatochipstomato.name",recipe={frsm_jj_tomato={need=1,tag=""},minecraft_jj_baked_potato={need=2,tag=""},minecraft_jj_paper={need=6,tag=""}}},
 frsm_jj_printer={hasPattern=true,label="Printer",recipe={frsm_jj_nesr={need=1,tag=""},minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_paper={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 frsm_jj_prozessor={hasPattern=true,label="Single-Core Processor",recipe={minecraft_jj_dye_jj_4={need=6,tag=""},minecraft_jj_gold_nugget={need=1,tag=""},minecraft_jj_iron_ingot={need=2,tag=""}}},
 frsm_jj_prozessor2={hasPattern=true,label="Dual-Core Processor",recipe={frsm_jj_prozessor={need=2,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 frsm_jj_prozessor4={hasPattern=true,label="Quad-Core Processor",recipe={frsm_jj_prozessor={need=4,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 frsm_jj_radio1={hasPattern=true,label="Radio (1)",recipe={frsm_jj_nesr={need=1,tag=""},frsm_jj_prozessor={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 frsm_jj_radio2={hasPattern=true,label="Radio (2)",recipe={frsm_jj_nesr={need=1,tag=""},minecraft_jj_log={need=1,tag=""}}},
 frsm_jj_redstoneinput={hasPattern=true,label="Redstone Input",recipe={minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""},minecraft_jj_slime_ball={need=1,tag=""}}},
 frsm_jj_roadsign1={hasPattern=false,label="",recipe={}},
 frsm_jj_roadsign2={hasPattern=false,label="",recipe={}},
 frsm_jj_roadsign3={hasPattern=false,label="",recipe={}},
 frsm_jj_roadsign4={hasPattern=false,label="",recipe={}},
 frsm_jj_roadsign5={hasPattern=false,label="",recipe={}},
 frsm_jj_roadsign6={hasPattern=false,label="",recipe={}},
 frsm_jj_salami={hasPattern=true,label="Ham",recipe={minecraft_jj_cooked_porkchop={need=1,tag=""}}},
 frsm_jj_shelf1={hasPattern=true,label="Shelf (1)",recipe={frsm_jj_planks_oak={need=4,tag=""},minecraft_jj_planks={need=1,tag=""},minecraft_jj_stone_button={need=2,tag=""},minecraft_jj_wool={need=2,tag=""}}},
 frsm_jj_status={hasPattern=false,label="",recipe={}},
 frsm_jj_stonelightbox={hasPattern=true,label="Stone Light Box",recipe={minecraft_jj_cobblestone={need=8,tag=""},minecraft_jj_glowstone_dust={need=1,tag=""}}},
 frsm_jj_stonemug={hasPattern=true,label="Stone Mug",recipe={minecraft_jj_glass={need=1,tag=""},minecraft_jj_stone={need=1,tag=""}}},
 frsm_jj_stonemugwithbeer={hasPattern=true,label="Stone Mug with Beer",recipe={frsm_jj_stonemug={need=1,tag=""},minecraft_jj_water_bucket={need=1,tag=""},minecraft_jj_wheat={need=1,tag=""}}},
 frsm_jj_stoneslabpillar={hasPattern=true,label="Stone Slab Pillar",recipe={minecraft_jj_stone_slab={need=6,tag=""}}},
 frsm_jj_stove={hasPattern=true,label="Stove",recipe={frsm_jj_nesr={need=1,tag=""},frsm_jj_redstoneinput={need=1,tag=""},minecraft_jj_furnace={need=1,tag=""},minecraft_jj_iron_ingot={need=6,tag=""}}},
 frsm_jj_stove_pipe={hasPattern=true,label="Stove Pipe",recipe={minecraft_jj_coal={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 frsm_jj_streetlamp_base={hasPattern=true,label="Street Lamp Base",recipe={minecraft_jj_concrete_jj_8={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 frsm_jj_streetlamp_lamp={hasPattern=true,label="Street Lamp",recipe={frsm_jj_lamp={need=1,tag=""},minecraft_jj_concrete_jj_8={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 frsm_jj_streetlamp_post={hasPattern=true,label="Street Lamp Post",recipe={minecraft_jj_concrete_jj_8={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 frsm_jj_tbm={hasPattern=true,label="TBM - Test Block Model (1)",recipe={minecraft_jj_log={need=2,tag=""},minecraft_jj_planks={need=3,tag=""}}},
 frsm_jj_tbm2={hasPattern=true,label="Test Block Model (2)",recipe={frsm_jj_tbm={need=1,tag=""}}},
 frsm_jj_tbm3={hasPattern=true,label="Test Block Model (3)",recipe={frsm_jj_tbm2={need=1,tag=""}}},
 frsm_jj_tiles={hasPattern=false,label="",recipe={}},
 frsm_jj_tiles2={hasPattern=false,label="",recipe={}},
 frsm_jj_tiles3={hasPattern=false,label="",recipe={}},
 frsm_jj_tiles4={hasPattern=false,label="",recipe={}},
 frsm_jj_tilesempty={hasPattern=false,label="",recipe={}},
 frsm_jj_toaster={hasPattern=true,label="Toaster",recipe={frsm_jj_nesr={need=1,tag=""},frsm_jj_redstoneinput={need=1,tag=""},minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 frsm_jj_tomato={hasPattern=true,label="Tomato",recipe={harvestcraft_jj_tomatoitem={need=1,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 frsm_jj_tomatojar={hasPattern=true,label="Tomato Jar",recipe={frsm_jj_jar={need=2,tag=""},frsm_jj_tomato={need=1,tag=""}}},
 frsm_jj_tomatoplant={hasPattern=false,label="",recipe={}},
 frsm_jj_tomatoseeds={hasPattern=true,label="Tomato Seeds",recipe={frsm_jj_tomato={need=1,tag=""}}},
 frsm_jj_tomatosoup={hasPattern=true,label="Tomato Soup",recipe={frsm_jj_tomatojar={need=1,tag=""},minecraft_jj_bowl={need=1,tag=""}}},
 frsm_jj_trashcan={hasPattern=true,label="Trashcan",recipe={minecraft_jj_iron_ingot={need=7,tag=""},minecraft_jj_lava_bucket={need=1,tag=""}}},
 frsm_jj_tree_pot={hasPattern=false,label="",recipe={}},
 frsm_jj_tree_pot_jj_1={hasPattern=false,label="",recipe={}},
 frsm_jj_tree_pot_jj_10={hasPattern=false,label="",recipe={}},
 frsm_jj_tree_pot_jj_11={hasPattern=false,label="",recipe={}},
 frsm_jj_tree_pot_jj_12={hasPattern=false,label="",recipe={}},
 frsm_jj_tree_pot_jj_13={hasPattern=false,label="",recipe={}},
 frsm_jj_tree_pot_jj_14={hasPattern=false,label="",recipe={}},
 frsm_jj_tree_pot_jj_15={hasPattern=false,label="",recipe={}},
 frsm_jj_tree_pot_jj_2={hasPattern=false,label="",recipe={}},
 frsm_jj_tree_pot_jj_3={hasPattern=false,label="",recipe={}},
 frsm_jj_tree_pot_jj_4={hasPattern=false,label="",recipe={}},
 frsm_jj_tree_pot_jj_5={hasPattern=false,label="",recipe={}},
 frsm_jj_tree_pot_jj_6={hasPattern=false,label="",recipe={}},
 frsm_jj_tree_pot_jj_7={hasPattern=false,label="",recipe={}},
 frsm_jj_tree_pot_jj_8={hasPattern=false,label="",recipe={}},
 frsm_jj_tree_pot_jj_9={hasPattern=false,label="",recipe={}},
 frsm_jj_tvcontroller={hasPattern=true,label="TV Controller",recipe={minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""},minecraft_jj_stone_button={need=7,tag=""}}},
 frsm_jj_tvl={hasPattern=true,label="TV Large",recipe={frsm_jj_nesr={need=1,tag=""},frsm_jj_prozessor2={need=1,tag=""},frsm_jj_redstoneinput={need=1,tag=""},frsm_jj_tvcontroller={need=1,tag=""},frsm_jj_tvscreenlarge={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 frsm_jj_tvl_1={hasPattern=true,label="TV Large (alt)",recipe={frsm_jj_tvl={need=1,tag=""}}},
 frsm_jj_tvm={hasPattern=true,label="TV Medium",recipe={frsm_jj_nesr={need=1,tag=""},frsm_jj_prozessor={need=1,tag=""},frsm_jj_redstoneinput={need=1,tag=""},frsm_jj_tvcontroller={need=1,tag=""},frsm_jj_tvscreenmedium={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 frsm_jj_tvs={hasPattern=true,label="TV Small (1)",recipe={frsm_jj_prozessor={need=1,tag=""},frsm_jj_redstoneinput={need=1,tag=""},frsm_jj_tvscreensmall={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 frsm_jj_tvs2={hasPattern=false,label="",recipe={}},
 frsm_jj_tvscreenlarge={hasPattern=false,label="",recipe={}},
 frsm_jj_tvscreenmedium={hasPattern=true,label="TV Screen Medium",recipe={frsm_jj_tvscreensmall={need=2,tag=""}}},
 frsm_jj_tvscreensmall={hasPattern=true,label="TV Screen Small",recipe={minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_dye_jj_12={need=1,tag=""},minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_glass={need=6,tag=""}}},
 frsm_jj_upgradekit={hasPattern=true,label="UpGrade Kit",recipe={frsm_jj_prozessor={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 frsm_jj_vendingmashine={hasPattern=true,label="Vending Mashine",recipe={frsm_jj_nesr={need=3,tag=""},frsm_jj_prozessor={need=1,tag=""},minecraft_jj_iron_block={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 frsm_jj_washingmashine={hasPattern=true,label="Washing Mashine",recipe={frsm_jj_nesr={need=1,tag=""},frsm_jj_prozessor={need=1,tag=""},frsm_jj_redstoneinput={need=1,tag=""},minecraft_jj_iron_ingot={need=6,tag=""}}},
 frsm_jj_window1={hasPattern=true,label="Window (1)",recipe={minecraft_jj_glass={need=1,tag=""},minecraft_jj_log={need=6,tag=""},minecraft_jj_planks={need=2,tag=""}}},
 frsm_jj_woodenlightbox={hasPattern=true,label="Wooden Light Box",recipe={minecraft_jj_glowstone_dust={need=1,tag=""},minecraft_jj_planks={need=8,tag=""}}},
 fvp_jj_ab1={hasPattern=false,label="",recipe={}},
 fvp_jj_ab1_doors={hasPattern=false,label="",recipe={}},
 fvp_jj_ab1_driver_seat={hasPattern=false,label="",recipe={}},
 fvp_jj_ab1_engine={hasPattern=false,label="",recipe={}},
 fvp_jj_ab1_lights={hasPattern=false,label="",recipe={}},
 fvp_jj_ab1_passenger_seats={hasPattern=false,label="",recipe={}},
 fvp_jj_ab1_steering_wheel={hasPattern=false,label="",recipe={}},
 fvp_jj_bogie_st1={hasPattern=false,label="",recipe={}},
 fvp_jj_c10={hasPattern=false,label="",recipe={}},
 fvp_jj_c10_doors={hasPattern=false,label="",recipe={}},
 fvp_jj_c10_hood={hasPattern=false,label="",recipe={}},
 fvp_jj_c10_interior={hasPattern=false,label="",recipe={}},
 fvp_jj_c10_license_plates={hasPattern=false,label="",recipe={}},
 fvp_jj_c10_lights={hasPattern=false,label="",recipe={}},
 fvp_jj_c10_seats={hasPattern=false,label="",recipe={}},
 fvp_jj_c10_steering_wheel={hasPattern=false,label="",recipe={}},
 fvp_jj_c10_trailer_hitch={hasPattern=false,label="",recipe={}},
 fvp_jj_c10_trunk={hasPattern=false,label="",recipe={}},
 fvp_jj_c11={hasPattern=false,label="",recipe={}},
 fvp_jj_c11_doors={hasPattern=false,label="",recipe={}},
 fvp_jj_c11_hood={hasPattern=false,label="",recipe={}},
 fvp_jj_c11_interior={hasPattern=false,label="",recipe={}},
 fvp_jj_c11_lights={hasPattern=false,label="",recipe={}},
 fvp_jj_c11_roof={hasPattern=false,label="",recipe={}},
 fvp_jj_c11_seats={hasPattern=false,label="",recipe={}},
 fvp_jj_c11_steering_wheel={hasPattern=false,label="",recipe={}},
 fvp_jj_c11_trunk={hasPattern=false,label="",recipe={}},
 fvp_jj_c1r1={hasPattern=false,label="",recipe={}},
 fvp_jj_c1r1_back_seats={hasPattern=false,label="",recipe={}},
 fvp_jj_c1r1_doors={hasPattern=false,label="",recipe={}},
 fvp_jj_c1r1_front_seats={hasPattern=false,label="",recipe={}},
 fvp_jj_c1r1_interior={hasPattern=false,label="",recipe={}},
 fvp_jj_c1r1_lights={hasPattern=false,label="",recipe={}},
 fvp_jj_c1r1_steering_wheel={hasPattern=false,label="",recipe={}},
 fvp_jj_c1r1t1_wheel={hasPattern=false,label="",recipe={}},
 fvp_jj_c1r1t2_wheel={hasPattern=false,label="",recipe={}},
 fvp_jj_c2={hasPattern=false,label="",recipe={}},
 fvp_jj_c2_doors={hasPattern=false,label="",recipe={}},
 fvp_jj_c2_interior={hasPattern=false,label="",recipe={}},
 fvp_jj_c2_lights={hasPattern=false,label="",recipe={}},
 fvp_jj_c2_steering_wheel={hasPattern=false,label="",recipe={}},
 fvp_jj_c2r2t1_wheel={hasPattern=false,label="",recipe={}},
 fvp_jj_c4={hasPattern=false,label="",recipe={}},
 fvp_jj_c4_front_seats={hasPattern=false,label="",recipe={}},
 fvp_jj_c4_interior={hasPattern=false,label="",recipe={}},
 fvp_jj_c4_lights={hasPattern=false,label="",recipe={}},
 fvp_jj_c4_steering_wheel={hasPattern=false,label="",recipe={}},
 fvp_jj_c4r1_wheel={hasPattern=false,label="",recipe={}},
 fvp_jj_c5={hasPattern=false,label="",recipe={}},
 fvp_jj_c5_interior={hasPattern=false,label="",recipe={}},
 fvp_jj_c5_lights={hasPattern=false,label="",recipe={}},
 fvp_jj_c5_seats={hasPattern=false,label="",recipe={}},
 fvp_jj_c5_steering_wheel={hasPattern=false,label="",recipe={}},
 fvp_jj_c8={hasPattern=false,label="",recipe={}},
 fvp_jj_c8_bumpers={hasPattern=false,label="",recipe={}},
 fvp_jj_c8_doors={hasPattern=false,label="",recipe={}},
 fvp_jj_c8_interior={hasPattern=false,label="",recipe={}},
 fvp_jj_c8_lights={hasPattern=false,label="",recipe={}},
 fvp_jj_c8_seats={hasPattern=false,label="",recipe={}},
 fvp_jj_c8_steering_wheel={hasPattern=false,label="",recipe={}},
 fvp_jj_c9_bumper={hasPattern=false,label="",recipe={}},
 fvp_jj_c9_doors={hasPattern=false,label="",recipe={}},
 fvp_jj_c9_hood={hasPattern=false,label="",recipe={}},
 fvp_jj_c9_interior={hasPattern=false,label="",recipe={}},
 fvp_jj_c9_lights={hasPattern=false,label="",recipe={}},
 fvp_jj_c9_seats={hasPattern=false,label="",recipe={}},
 fvp_jj_c9_steering_wheel={hasPattern=false,label="",recipe={}},
 fvp_jj_c9_trunk={hasPattern=false,label="",recipe={}},
 fvp_jj_sentinel={hasPattern=false,label="",recipe={}},
 fvp_jj_t1_back_wheel={hasPattern=false,label="",recipe={}},
 fvp_jj_t1_deflector={hasPattern=false,label="",recipe={}},
 fvp_jj_t1_front_seats={hasPattern=false,label="",recipe={}},
 fvp_jj_t1_front_wheel={hasPattern=false,label="",recipe={}},
 fvp_jj_t1_lights={hasPattern=false,label="",recipe={}},
 fvp_jj_t1_snowplow={hasPattern=false,label="",recipe={}},
 fvp_jj_t1_steering_wheel={hasPattern=false,label="",recipe={}},
 fvp_jj_t1_trailer_connector={hasPattern=false,label="",recipe={}},
 fvp_jj_t1_type1_cargoupgrade={hasPattern=false,label="",recipe={}},
 fvp_jj_t1_type2_cargoupgrade={hasPattern=false,label="",recipe={}},
 fvp_jj_t1_type4_cargoupgrade={hasPattern=false,label="",recipe={}},
 fvp_jj_t1_type5_cargoupgrade={hasPattern=false,label="",recipe={}},
 fvp_jj_t1p={hasPattern=false,label="",recipe={}},
 fvp_jj_t2={hasPattern=false,label="",recipe={}},
 fvp_jj_t2_doors={hasPattern=false,label="",recipe={}},
 fvp_jj_t2_interior={hasPattern=false,label="",recipe={}},
 fvp_jj_t2_lights={hasPattern=false,label="",recipe={}},
 fvp_jj_t2_rear_fender={hasPattern=false,label="",recipe={}},
 fvp_jj_t2_side_skirts={hasPattern=false,label="",recipe={}},
 fvp_jj_t2_steering_wheel={hasPattern=false,label="",recipe={}},
 fvp_jj_t2_trailer_connector={hasPattern=false,label="",recipe={}},
 fvp_jj_t2r1t1_wheel={hasPattern=false,label="",recipe={}},
 fvp_jj_tr1={hasPattern=false,label="",recipe={}},
 fvp_jj_tr1_container_holder={hasPattern=false,label="",recipe={}},
 fvp_jj_tr1_fenders={hasPattern=false,label="",recipe={}},
 fvp_jj_tr1_license_plate={hasPattern=false,label="",recipe={}},
 fvp_jj_tr1_lights={hasPattern=false,label="",recipe={}},
 fvp_jj_tr1_type1={hasPattern=false,label="",recipe={}},
 fvtm_jj_asphalt={hasPattern=false,label="",recipe={}},
 fvtm_jj_asphalt_jj_1={hasPattern=false,label="",recipe={}},
 fvtm_jj_asphalt_jj_12={hasPattern=false,label="",recipe={}},
 fvtm_jj_asphalt_jj_2={hasPattern=false,label="",recipe={}},
 fvtm_jj_asphalt_jj_4={hasPattern=false,label="",recipe={}},
 fvtm_jj_asphalt_jj_8={hasPattern=false,label="",recipe={}},
 fvtm_jj_constructor={hasPattern=false,label="",recipe={}},
 fvtm_jj_constructor_lift={hasPattern=false,label="",recipe={}},
 fvtm_jj_container_block={hasPattern=false,label="",recipe={}},
 fvtm_jj_display_block={hasPattern=false,label="",recipe={}},
 fvtm_jj_junction_tool={hasPattern=false,label="",recipe={}},
 fvtm_jj_road_tool={hasPattern=false,label="",recipe={}},
 fvtm_jj_roadsign={hasPattern=false,label="",recipe={}},
 fvtm_jj_roadsystem_tool={hasPattern=false,label="",recipe={}},
 fvtm_jj_simple_signal={hasPattern=false,label="",recipe={}},
 fvtm_jj_standard={hasPattern=false,label="",recipe={}},
 fvtm_jj_standard_vv_16_straight={hasPattern=false,label="",recipe={}},
 fvtm_jj_standard_vv_16_straight_slope_down={hasPattern=false,label="",recipe={}},
 fvtm_jj_standard_vv_16_straight_slope_up={hasPattern=false,label="",recipe={}},
 fvtm_jj_standard_vv_32_straight={hasPattern=false,label="",recipe={}},
 fvtm_jj_standard_vv_4_straight={hasPattern=false,label="",recipe={}},
 fvtm_jj_standard_vv_8_straight={hasPattern=false,label="",recipe={}},
 fvtm_jj_streetpost={hasPattern=false,label="",recipe={}},
 fvtm_jj_streetsign={hasPattern=false,label="",recipe={}},
 gep_jj_cola={hasPattern=false,label="",recipe={}},
 gep_jj_diesel_canister={hasPattern=false,label="",recipe={}},
 gep_jj_engine_diesel={hasPattern=false,label="",recipe={}},
 gep_jj_engine_petrol={hasPattern=false,label="",recipe={}},
 gep_jj_fuel_tank={hasPattern=false,label="",recipe={}},
 gep_jj_glue={hasPattern=false,label="",recipe={}},
 gep_jj_key={hasPattern=false,label="",recipe={}},
 gep_jj_petrol_canister={hasPattern=false,label="",recipe={}},
 gep_jj_pizza_oven={hasPattern=false,label="",recipe={}},
 gep_jj_pizza_oven2={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_adult_filter={hasPattern=true,label="Adult Filter",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_egg={need=1,tag=""},minecraft_jj_gold_nugget={need=6,tag=""}}},
 industrialforegoing_jj_animal_byproduct_recolector={hasPattern=true,label="Animal Sewer",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_brick={need=4,tag=""},minecraft_jj_bucket={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""}}},
 industrialforegoing_jj_animal_growth_increaser={hasPattern=true,label="Animal Grower",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_dye_jj_5={need=2,tag=""},minecraft_jj_wheat={need=3,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=1,tag=""}}},
 industrialforegoing_jj_animal_independence_selector={hasPattern=true,label="Animal Baby Separator",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_dye_jj_5={need=2,tag=""},minecraft_jj_emerald={need=3,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=1,tag=""}}},
 industrialforegoing_jj_animal_resource_harvester={hasPattern=true,label="Animal Rancher",recipe={industrialforegoing_jj_plastic={need=3,tag=""},minecraft_jj_bucket={need=1,tag=""},minecraft_jj_shears={need=2,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=2,tag=""}}},
 industrialforegoing_jj_animal_stock_increaser={hasPattern=true,label="Animal Feeder",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_dye_jj_5={need=2,tag=""},minecraft_jj_golden_apple={need=1,tag=""},minecraft_jj_golden_carrot={need=2,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=1,tag=""}}},
 industrialforegoing_jj_artificial_dye={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_artificial_dye_jj_1={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_artificial_dye_jj_10={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_artificial_dye_jj_11={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_artificial_dye_jj_12={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_artificial_dye_jj_13={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_artificial_dye_jj_14={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_artificial_dye_jj_15={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_artificial_dye_jj_2={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_artificial_dye_jj_3={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_artificial_dye_jj_4={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_artificial_dye_jj_5={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_artificial_dye_jj_6={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_artificial_dye_jj_7={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_artificial_dye_jj_8={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_artificial_dye_jj_9={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_biofuel_generator={hasPattern=true,label="Biofuel Generator",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_blaze_rod={need=2,tag=""},minecraft_jj_furnace={need=1,tag=""},minecraft_jj_piston={need=3,tag=""},thermalexpansion_jj_frame={need=1,tag=""}}},
 industrialforegoing_jj_bioreactor={hasPattern=true,label="Bioreactor",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_brick={need=2,tag=""},minecraft_jj_fermented_spider_eye={need=1,tag=""},minecraft_jj_slime_ball={need=2,tag=""},minecraft_jj_sugar={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""}}},
 industrialforegoing_jj_black_hole_controller={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_black_hole_controller_reworked={hasPattern=true,label="Black Hole Controller v2.0",recipe={industrialforegoing_jj_pink_slime_ingot={need=2,tag=""},industrialforegoing_jj_plastic={need=4,tag=""},minecraft_jj_diamond_block={need=1,tag=""},minecraft_jj_ender_chest={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""}}},
 industrialforegoing_jj_black_hole_label={hasPattern=true,label="Black Hole Label",recipe={industrialforegoing_jj_plastic={need=6,tag=""},minecraft_jj_paper={need=2,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 industrialforegoing_jj_black_hole_tank={hasPattern=true,label="Black Hole Tank",recipe={industrialforegoing_jj_plastic={need=3,tag=""},minecraft_jj_bucket={need=2,tag=""},minecraft_jj_ender_eye={need=2,tag=""},minecraft_jj_ender_pearl={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""}}},
 industrialforegoing_jj_black_hole_unit={hasPattern=true,label="Black Hole Unit",recipe={industrialforegoing_jj_plastic={need=3,tag=""},minecraft_jj_chest={need=2,tag=""},minecraft_jj_ender_eye={need=2,tag=""},minecraft_jj_ender_pearl={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""}}},
 industrialforegoing_jj_block_destroyer={hasPattern=true,label="Block Breaker",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_iron_pickaxe={need=1,tag=""},minecraft_jj_iron_shovel={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=2,tag=""},thermalfoundation_jj_material_jj_25={need=1,tag=""}}},
 industrialforegoing_jj_block_placer={hasPattern=true,label="Block Placer",recipe={industrialforegoing_jj_plastic={need=4,tag=""},minecraft_jj_dropper={need=3,tag=""},minecraft_jj_redstone={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""}}},
 industrialforegoing_jj_book_manual={hasPattern=true,label="Industrial Foregoing's Manual",recipe={minecraft_jj_log={need=1,tag=""},minecraft_jj_paper={need=1,tag=""}}},
 industrialforegoing_jj_conveyor={hasPattern=true,label="Weiß§r Conveyor Belt",recipe={industrialforegoing_jj_plastic={need=6,tag=""},minecraft_jj_iron_ingot={need=2,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 industrialforegoing_jj_conveyor_jj_1={hasPattern=true,label="Orange§r Conveyor Belt",recipe={industrialforegoing_jj_conveyor={need=8,tag=""},minecraft_jj_dye_jj_14={need=1,tag=""}}},
 industrialforegoing_jj_conveyor_jj_10={hasPattern=true,label="Violett§r Conveyor Belt",recipe={industrialforegoing_jj_conveyor={need=8,tag=""},minecraft_jj_dye_jj_5={need=1,tag=""}}},
 industrialforegoing_jj_conveyor_jj_11={hasPattern=true,label="Blau§r Conveyor Belt",recipe={industrialforegoing_jj_conveyor={need=8,tag=""},minecraft_jj_dye_jj_4={need=1,tag=""}}},
 industrialforegoing_jj_conveyor_jj_12={hasPattern=true,label="Braun§r Conveyor Belt",recipe={industrialforegoing_jj_conveyor={need=8,tag=""},minecraft_jj_dye_jj_3={need=1,tag=""}}},
 industrialforegoing_jj_conveyor_jj_13={hasPattern=true,label="Grün§r Conveyor Belt",recipe={industrialforegoing_jj_conveyor={need=8,tag=""},minecraft_jj_dye_jj_2={need=1,tag=""}}},
 industrialforegoing_jj_conveyor_jj_14={hasPattern=true,label="Rot§r Conveyor Belt",recipe={industrialforegoing_jj_conveyor={need=8,tag=""},minecraft_jj_dye_jj_1={need=1,tag=""}}},
 industrialforegoing_jj_conveyor_jj_15={hasPattern=true,label="Schwarz§r Conveyor Belt",recipe={industrialforegoing_jj_conveyor={need=8,tag=""},minecraft_jj_dye={need=1,tag=""}}},
 industrialforegoing_jj_conveyor_jj_2={hasPattern=true,label="Magenta§r Conveyor Belt",recipe={industrialforegoing_jj_conveyor={need=8,tag=""},minecraft_jj_dye_jj_13={need=1,tag=""}}},
 industrialforegoing_jj_conveyor_jj_3={hasPattern=true,label="Hellblau§r Conveyor Belt",recipe={industrialforegoing_jj_conveyor={need=8,tag=""},minecraft_jj_dye_jj_12={need=1,tag=""}}},
 industrialforegoing_jj_conveyor_jj_4={hasPattern=true,label="Gelb§r Conveyor Belt",recipe={industrialforegoing_jj_conveyor={need=8,tag=""},minecraft_jj_dye_jj_11={need=1,tag=""}}},
 industrialforegoing_jj_conveyor_jj_5={hasPattern=true,label="Hellgrün§r Conveyor Belt",recipe={industrialforegoing_jj_conveyor={need=8,tag=""},minecraft_jj_dye_jj_10={need=1,tag=""}}},
 industrialforegoing_jj_conveyor_jj_6={hasPattern=true,label="Rosa§r Conveyor Belt",recipe={industrialforegoing_jj_conveyor={need=8,tag=""},minecraft_jj_dye_jj_9={need=1,tag=""}}},
 industrialforegoing_jj_conveyor_jj_7={hasPattern=true,label="Grau§r Conveyor Belt",recipe={industrialforegoing_jj_conveyor={need=8,tag=""},minecraft_jj_dye_jj_8={need=1,tag=""}}},
 industrialforegoing_jj_conveyor_jj_8={hasPattern=true,label="Hellgrau§r Conveyor Belt",recipe={industrialforegoing_jj_conveyor={need=8,tag=""},minecraft_jj_dye_jj_7={need=1,tag=""}}},
 industrialforegoing_jj_conveyor_jj_9={hasPattern=true,label="Türkis§r Conveyor Belt",recipe={industrialforegoing_jj_conveyor={need=8,tag=""},minecraft_jj_dye_jj_6={need=1,tag=""}}},
 industrialforegoing_jj_conveyor_upgrade={hasPattern=true,label="Extraction Conveyor Upgrade",recipe={industrialforegoing_jj_conveyor={need=1,tag=""},industrialforegoing_jj_plastic={need=1,tag=""},minecraft_jj_dispenser={need=1,tag=""},minecraft_jj_iron_ingot={need=6,tag=""}}},
 industrialforegoing_jj_conveyor_upgrade_jj_1={hasPattern=true,label="Insertion Conveyor Upgrade",recipe={industrialforegoing_jj_conveyor={need=1,tag=""},industrialforegoing_jj_plastic={need=1,tag=""},minecraft_jj_hopper={need=1,tag=""},minecraft_jj_iron_ingot={need=6,tag=""}}},
 industrialforegoing_jj_conveyor_upgrade_jj_2={hasPattern=true,label="Detection Conveyor Upgrade",recipe={industrialforegoing_jj_conveyor={need=1,tag=""},minecraft_jj_comparator={need=1,tag=""},minecraft_jj_iron_ingot={need=6,tag=""},minecraft_jj_stone_pressure_plate={need=1,tag=""}}},
 industrialforegoing_jj_conveyor_upgrade_jj_3={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_conveyor_upgrade_jj_4={hasPattern=true,label="Dropping Conveyor Upgrade",recipe={industrialforegoing_jj_conveyor={need=1,tag=""},minecraft_jj_dropper={need=1,tag=""},minecraft_jj_iron_bars={need=1,tag=""},minecraft_jj_iron_ingot={need=6,tag=""}}},
 industrialforegoing_jj_conveyor_upgrade_jj_5={hasPattern=true,label="Blinking Conveyor Upgrade",recipe={industrialforegoing_jj_conveyor={need=1,tag=""},minecraft_jj_chorus_fruit={need=1,tag=""},minecraft_jj_iron_ingot={need=6,tag=""},minecraft_jj_piston={need=1,tag=""}}},
 industrialforegoing_jj_conveyor_upgrade_jj_6={hasPattern=true,label="Splitting Conveyor Upgrade",recipe={industrialforegoing_jj_conveyor={need=2,tag=""},minecraft_jj_hopper={need=1,tag=""},minecraft_jj_iron_ingot={need=6,tag=""}}},
 industrialforegoing_jj_crop_enrich_material_injector={hasPattern=true,label="Plant Fertilizer",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_glass_bottle={need=1,tag=""},minecraft_jj_leather={need=2,tag=""},minecraft_jj_redstone={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=2,tag=""}}},
 industrialforegoing_jj_crop_recolector={hasPattern=true,label="Plant Gatherer",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_iron_axe={need=2,tag=""},minecraft_jj_iron_hoe={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=2,tag=""}}},
 industrialforegoing_jj_crop_sower={hasPattern=true,label="Plant Sower",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_flower_pot={need=1,tag=""},minecraft_jj_piston={need=2,tag=""},minecraft_jj_redstone={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=2,tag=""}}},
 industrialforegoing_jj_dryrubber={hasPattern=true,label="Dry Rubber",recipe={industrialforegoing_jj_tinydryrubber={need=9,tag=""}}},
 industrialforegoing_jj_dye_mixer={hasPattern=true,label="Dye Mixer",recipe={industrialforegoing_jj_plastic={need=4,tag=""},minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_dye_jj_4={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=1,tag=""}}},
 industrialforegoing_jj_enchantment_aplicator={hasPattern=true,label="Enchantment Applicator",recipe={industrialforegoing_jj_plastic={need=3,tag=""},minecraft_jj_anvil={need=3,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=2,tag=""}}},
 industrialforegoing_jj_enchantment_extractor={hasPattern=true,label="Enchantment Extractor",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_book={need=2,tag=""},minecraft_jj_diamond={need=2,tag=""},minecraft_jj_nether_brick={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=1,tag=""}}},
 industrialforegoing_jj_enchantment_invoker={hasPattern=true,label="Enchantment Factory",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_book={need=1,tag=""},minecraft_jj_diamond={need=2,tag=""},minecraft_jj_obsidian={need=3,tag=""},thermalexpansion_jj_frame={need=1,tag=""}}},
 industrialforegoing_jj_enchantment_refiner={hasPattern=true,label="Enchantment Sorter",recipe={industrialforegoing_jj_plastic={need=4,tag=""},minecraft_jj_book={need=1,tag=""},minecraft_jj_enchanted_book={need=1,tag=""},minecraft_jj_ender_pearl={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_26={need=1,tag=""}}},
 industrialforegoing_jj_energy_field_addon={hasPattern=true,label="Energy Field Addon",recipe={industrialforegoing_jj_pink_slime_ingot={need=4,tag=""},industrialforegoing_jj_range_addon_jj_9={need=1,tag=""},minecraft_jj_redstone={need=4,tag=""}}},
 industrialforegoing_jj_energy_field_provider={hasPattern=true,label="Energy Field Provider",recipe={industrialforegoing_jj_energy_field_addon={need=1,tag=""},minecraft_jj_gold_ingot={need=4,tag=""},minecraft_jj_repeater={need=2,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_26={need=1,tag=""}}},
 industrialforegoing_jj_fertilizer={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_fluid_crafter={hasPattern=true,label="Fluid Crafter",recipe={industrialforegoing_jj_plastic={need=4,tag=""},minecraft_jj_bucket={need=2,tag=""},minecraft_jj_crafting_table={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=1,tag=""}}},
 industrialforegoing_jj_fluid_pump={hasPattern=true,label="Fluid Pump",recipe={industrialforegoing_jj_plastic={need=4,tag=""},minecraft_jj_bucket={need=1,tag=""},minecraft_jj_lava_bucket={need=1,tag=""},minecraft_jj_water_bucket={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=1,tag=""}}},
 industrialforegoing_jj_fluid_transfer_addon_pull={hasPattern=true,label="Fluid Transfer Addon (Pull/Down)",recipe={industrialforegoing_jj_plastic={need=4,tag=""},minecraft_jj_bucket={need=2,tag=""},minecraft_jj_dye_jj_12={need=2,tag=""},minecraft_jj_sticky_piston={need=1,tag=""}}},
 industrialforegoing_jj_fluid_transfer_addon_push={hasPattern=true,label="Fluid Transfer Addon (Push/Down)",recipe={industrialforegoing_jj_plastic={need=4,tag=""},minecraft_jj_bucket={need=2,tag=""},minecraft_jj_dye_jj_12={need=2,tag=""},minecraft_jj_piston={need=1,tag=""}}},
 industrialforegoing_jj_fluiddictionary_converter={hasPattern=true,label="Fluid Dictionary Converter",recipe={industrialforegoing_jj_plastic={need=3,tag=""},minecraft_jj_bucket={need=2,tag=""},minecraft_jj_glass={need=2,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=1,tag=""}}},
 industrialforegoing_jj_fortune_addon={hasPattern=true,label="Fortune Addon",recipe={industrialforegoing_jj_pink_slime_ingot={need=1,tag=""},industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_emerald={need=6,tag=""}}},
 industrialforegoing_jj_froster={hasPattern=true,label="Froster",recipe={industrialforegoing_jj_plastic={need=4,tag=""},minecraft_jj_ice={need=1,tag=""},minecraft_jj_snowball={need=2,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=1,tag=""}}},
 industrialforegoing_jj_hydrator={hasPattern=true,label="Hydrator",recipe={industrialforegoing_jj_fertilizer={need=2,tag=""},industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_piston={need=1,tag=""},minecraft_jj_water_bucket={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=2,tag=""}}},
 industrialforegoing_jj_infinity_drill={hasPattern=true,label="Infinity Drill",recipe={industrialforegoing_jj_black_hole_tank={need=1,tag=""},industrialforegoing_jj_laser_drill={need=1,tag=""},industrialforegoing_jj_pink_slime_ingot={need=2,tag=""},minecraft_jj_diamond_block={need=1,tag=""},minecraft_jj_iron_block={need=2,tag=""}}},
 industrialforegoing_jj_item_splitter={hasPattern=true,label="Item Splitter",recipe={industrialforegoing_jj_plastic={need=4,tag=""},minecraft_jj_chest={need=1,tag=""},minecraft_jj_hopper={need=2,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=1,tag=""}}},
 industrialforegoing_jj_itemstack_transfer_addon_pull={hasPattern=true,label="Itemstack Transfer Addon (Pull/Down)",recipe={industrialforegoing_jj_plastic={need=4,tag=""},minecraft_jj_chest={need=2,tag=""},minecraft_jj_dye_jj_13={need=2,tag=""},minecraft_jj_sticky_piston={need=1,tag=""}}},
 industrialforegoing_jj_itemstack_transfer_addon_push={hasPattern=true,label="Itemstack Transfer Addon (Push/Down)",recipe={industrialforegoing_jj_plastic={need=4,tag=""},minecraft_jj_chest={need=2,tag=""},minecraft_jj_dye_jj_13={need=2,tag=""},minecraft_jj_piston={need=1,tag=""}}},
 industrialforegoing_jj_laser_base={hasPattern=true,label="Laser Base",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_glowstone={need=2,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=2,tag=""},thermalfoundation_jj_material_jj_26={need=2,tag=""}}},
 industrialforegoing_jj_laser_drill={hasPattern=true,label="Laser Drill",recipe={industrialforegoing_jj_laser_lens={need=1,tag=""},industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_glass={need=2,tag=""},minecraft_jj_glowstone={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_26={need=2,tag=""}}},
 industrialforegoing_jj_laser_lens={hasPattern=true,label="Weiß§r Laser Lens",recipe={industrialforegoing_jj_pink_slime={need=4,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_inverted={hasPattern=true,label="Weiß§r Laser Lens (Inverted)",recipe={minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_stained_glass_pane={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_inverted_jj_1={hasPattern=true,label="Orange§r Laser Lens (Inverted)",recipe={minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_1={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_inverted_jj_10={hasPattern=true,label="Violett§r Laser Lens (Inverted)",recipe={minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_10={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_inverted_jj_11={hasPattern=true,label="Blau§r Laser Lens (Inverted)",recipe={minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_11={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_inverted_jj_12={hasPattern=true,label="Braun§r Laser Lens (Inverted)",recipe={minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_12={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_inverted_jj_13={hasPattern=true,label="Grün§r Laser Lens (Inverted)",recipe={minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_13={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_inverted_jj_14={hasPattern=true,label="Rot§r Laser Lens (Inverted)",recipe={minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_14={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_inverted_jj_15={hasPattern=true,label="Schwarz§r Laser Lens (Inverted)",recipe={minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_15={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_inverted_jj_2={hasPattern=true,label="Magenta§r Laser Lens (Inverted)",recipe={minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_2={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_inverted_jj_3={hasPattern=true,label="Hellblau§r Laser Lens (Inverted)",recipe={minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_3={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_inverted_jj_4={hasPattern=true,label="Gelb§r Laser Lens (Inverted)",recipe={minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_4={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_inverted_jj_5={hasPattern=true,label="Hellgrün§r Laser Lens (Inverted)",recipe={minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_5={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_inverted_jj_6={hasPattern=true,label="Rosa§r Laser Lens (Inverted)",recipe={minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_6={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_inverted_jj_7={hasPattern=true,label="Grau§r Laser Lens (Inverted)",recipe={minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_7={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_inverted_jj_8={hasPattern=true,label="Hellgrau§r Laser Lens (Inverted)",recipe={minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_8={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_inverted_jj_9={hasPattern=true,label="Türkis§r Laser Lens (Inverted)",recipe={minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_9={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_jj_1={hasPattern=true,label="Orange§r Laser Lens",recipe={industrialforegoing_jj_pink_slime={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_1={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_jj_10={hasPattern=true,label="Violett§r Laser Lens",recipe={industrialforegoing_jj_pink_slime={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_10={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_jj_11={hasPattern=true,label="Blau§r Laser Lens",recipe={industrialforegoing_jj_pink_slime={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_11={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_jj_12={hasPattern=true,label="Braun§r Laser Lens",recipe={industrialforegoing_jj_pink_slime={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_12={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_jj_13={hasPattern=true,label="Grün§r Laser Lens",recipe={industrialforegoing_jj_pink_slime={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_13={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_jj_14={hasPattern=true,label="Rot§r Laser Lens",recipe={industrialforegoing_jj_pink_slime={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_14={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_jj_15={hasPattern=true,label="Schwarz§r Laser Lens",recipe={industrialforegoing_jj_pink_slime={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_15={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_jj_2={hasPattern=true,label="Magenta§r Laser Lens",recipe={industrialforegoing_jj_pink_slime={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_2={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_jj_3={hasPattern=true,label="Hellblau§r Laser Lens",recipe={industrialforegoing_jj_pink_slime={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_3={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_jj_4={hasPattern=true,label="Gelb§r Laser Lens",recipe={industrialforegoing_jj_pink_slime={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_4={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_jj_5={hasPattern=true,label="Hellgrün§r Laser Lens",recipe={industrialforegoing_jj_pink_slime={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_5={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_jj_6={hasPattern=true,label="Rosa§r Laser Lens",recipe={industrialforegoing_jj_pink_slime={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_6={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_jj_7={hasPattern=true,label="Grau§r Laser Lens",recipe={industrialforegoing_jj_pink_slime={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_7={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_jj_8={hasPattern=true,label="Hellgrau§r Laser Lens",recipe={industrialforegoing_jj_pink_slime={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_8={need=1,tag=""}}},
 industrialforegoing_jj_laser_lens_jj_9={hasPattern=true,label="Türkis§r Laser Lens",recipe={industrialforegoing_jj_pink_slime={need=4,tag=""},minecraft_jj_stained_glass_pane_jj_9={need=1,tag=""}}},
 industrialforegoing_jj_latex_processing_unit={hasPattern=true,label="Latex Processing Unit",recipe={minecraft_jj_furnace={need=2,tag=""},minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_redstone={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=1,tag=""}}},
 industrialforegoing_jj_lava_fabricator={hasPattern=true,label="Lava Fabricator",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_blaze_rod={need=2,tag=""},minecraft_jj_magma_cream={need=2,tag=""},minecraft_jj_obsidian={need=1,tag=""},minecraft_jj_redstone_block={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""}}},
 industrialforegoing_jj_leaf_shearing={hasPattern=true,label="Leaf Shearing Addon",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_gold_nugget={need=6,tag=""},minecraft_jj_shears={need=1,tag=""}}},
 industrialforegoing_jj_material_stonework_factory={hasPattern=true,label="Material StoneWork Factory",recipe={industrialforegoing_jj_pink_slime={need=1,tag=""},industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_crafting_table={need=1,tag=""},minecraft_jj_furnace={need=1,tag=""},minecraft_jj_iron_pickaxe={need=1,tag=""},minecraft_jj_lava_bucket={need=1,tag=""},minecraft_jj_water_bucket={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""}}},
 industrialforegoing_jj_meat_feeder={hasPattern=true,label="Meat Feeder",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_glass_bottle={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 industrialforegoing_jj_mob_detector={hasPattern=true,label="Mob Detector",recipe={industrialforegoing_jj_plastic={need=3,tag=""},minecraft_jj_comparator={need=1,tag=""},minecraft_jj_observer={need=2,tag=""},minecraft_jj_repeater={need=2,tag=""},thermalexpansion_jj_frame={need=1,tag=""}}},
 industrialforegoing_jj_mob_duplicator={hasPattern=true,label="Mob Duplicator",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_emerald={need=2,tag=""},minecraft_jj_magma_cream={need=2,tag=""},minecraft_jj_nether_wart={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""}}},
 industrialforegoing_jj_mob_imprisonment_tool={hasPattern=true,label="Mob Imprisonment Tool",recipe={industrialforegoing_jj_plastic={need=4,tag=""},minecraft_jj_ghast_tear={need=1,tag=""}}},
 industrialforegoing_jj_mob_relocator={hasPattern=true,label="Mob Crusher",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_book={need=2,tag=""},minecraft_jj_iron_sword={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=2,tag=""}}},
 industrialforegoing_jj_mob_slaughter_factory={hasPattern=true,label="Mob Slaughter Factory",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_iron_axe={need=2,tag=""},minecraft_jj_iron_sword={need=2,tag=""},minecraft_jj_redstone={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=1,tag=""}}},
 industrialforegoing_jj_ore_fermenter={hasPattern=true,label="Fermentation Station",recipe={minecraft_jj_iron_bars={need=4,tag=""},minecraft_jj_log={need=3,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=1,tag=""}}},
 industrialforegoing_jj_ore_processor={hasPattern=true,label="Ore Processor",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_book={need=2,tag=""},minecraft_jj_iron_pickaxe={need=2,tag=""},minecraft_jj_piston={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""}}},
 industrialforegoing_jj_ore_sieve={hasPattern=true,label="Fluid Sieving Machine",recipe={industrialforegoing_jj_pink_slime={need=1,tag=""},industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_iron_bars={need=3,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=2,tag=""}}},
 industrialforegoing_jj_ore_washer={hasPattern=true,label="Washing Factory",recipe={industrialforegoing_jj_conveyor={need=2,tag=""},industrialforegoing_jj_meat_feeder={need=1,tag=""},industrialforegoing_jj_pink_slime_ingot={need=2,tag=""},industrialforegoing_jj_plastic={need=2,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_26={need=1,tag=""}}},
 industrialforegoing_jj_oredictionary_converter={hasPattern=true,label="Ore Dictionary Converter",recipe={industrialforegoing_jj_plastic={need=5,tag=""},minecraft_jj_iron_block={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_iron_nugget={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""}}},
 industrialforegoing_jj_petrified_fuel_generator={hasPattern=true,label="Petrified Fuel Generator",recipe={industrialforegoing_jj_plastic={need=4,tag=""},minecraft_jj_diamond={need=1,tag=""},minecraft_jj_furnace={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=2,tag=""}}},
 industrialforegoing_jj_pink_slime={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_pink_slime_ingot={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_pitiful_fuel_generator={hasPattern=true,label="Pitiful Fuel Generator",recipe={minecraft_jj_cobblestone={need=4,tag=""},minecraft_jj_furnace={need=1,tag=""},minecraft_jj_gold_ingot={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=2,tag=""}}},
 industrialforegoing_jj_plant_interactor={hasPattern=true,label="Plant Interactor",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_iron_hoe={need=3,tag=""},minecraft_jj_redstone={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=2,tag=""}}},
 industrialforegoing_jj_plastic={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_potion_enervator={hasPattern=true,label="Potion Brewer",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_brewing_stand={need=1,tag=""},minecraft_jj_repeater={need=2,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=3,tag=""}}},
 industrialforegoing_jj_protein_generator={hasPattern=true,label="Protein Generator",recipe={industrialforegoing_jj_biofuel_generator={need=1,tag=""},industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_furnace={need=1,tag=""},minecraft_jj_piston={need=3,tag=""},minecraft_jj_spider_eye={need=2,tag=""}}},
 industrialforegoing_jj_protein_reactor={hasPattern=true,label="Protein Reactor",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_brick={need=2,tag=""},minecraft_jj_egg={need=2,tag=""},minecraft_jj_porkchop={need=1,tag=""},minecraft_jj_rabbit_foot={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""}}},
 industrialforegoing_jj_range_addon={hasPattern=true,label="Range Addon",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_cobblestone={need=6,tag=""},minecraft_jj_glass_pane={need=1,tag=""}}},
 industrialforegoing_jj_range_addon_jj_1={hasPattern=true,label="Range Addon",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_dye_jj_4={need=6,tag=""},minecraft_jj_glass_pane={need=1,tag=""}}},
 industrialforegoing_jj_range_addon_jj_10={hasPattern=true,label="Range Addon",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_glass_pane={need=1,tag=""},thermalfoundation_jj_material_jj_134={need=6,tag=""}}},
 industrialforegoing_jj_range_addon_jj_11={hasPattern=true,label="Range Addon",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_emerald={need=6,tag=""},minecraft_jj_glass_pane={need=1,tag=""}}},
 industrialforegoing_jj_range_addon_jj_2={hasPattern=true,label="Range Addon",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_iron_ingot={need=6,tag=""}}},
 industrialforegoing_jj_range_addon_jj_3={hasPattern=true,label="Range Addon",recipe={ic2_jj_ingot_jj_6={need=6,tag=""},industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_glass_pane={need=1,tag=""}}},
 industrialforegoing_jj_range_addon_jj_4={hasPattern=true,label="Range Addon",recipe={industrialforegoing_jj_plastic={need=2,tag=""},mekanism_jj_ingot_jj_5={need=6,tag=""},minecraft_jj_glass_pane={need=1,tag=""}}},
 industrialforegoing_jj_range_addon_jj_5={hasPattern=true,label="Range Addon",recipe={ic2_jj_ingot_jj_1={need=6,tag=""},industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_glass_pane={need=1,tag=""}}},
 industrialforegoing_jj_range_addon_jj_6={hasPattern=true,label="Range Addon",recipe={ic2_jj_ingot_jj_4={need=6,tag=""},industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_glass_pane={need=1,tag=""}}},
 industrialforegoing_jj_range_addon_jj_7={hasPattern=true,label="Range Addon",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_gold_ingot={need=6,tag=""}}},
 industrialforegoing_jj_range_addon_jj_8={hasPattern=true,label="Range Addon",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_quartz={need=6,tag=""}}},
 industrialforegoing_jj_range_addon_jj_9={hasPattern=true,label="Range Addon",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_diamond={need=6,tag=""},minecraft_jj_glass_pane={need=1,tag=""}}},
 industrialforegoing_jj_resourceful_furnace={hasPattern=true,label="Resourceful Furnace",recipe={industrialforegoing_jj_plastic={need=4,tag=""},minecraft_jj_bucket={need=1,tag=""},minecraft_jj_furnace={need=2,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=1,tag=""}}},
 industrialforegoing_jj_sewage_composter_solidifier={hasPattern=true,label="Sewage Composter",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_brick={need=2,tag=""},minecraft_jj_furnace={need=1,tag=""},minecraft_jj_piston={need=2,tag=""},minecraft_jj_redstone={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""}}},
 industrialforegoing_jj_sludge_refiner={hasPattern=true,label="Sludge Refiner",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_bucket={need=1,tag=""},minecraft_jj_furnace={need=2,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=2,tag=""},thermalfoundation_jj_material_jj_25={need=1,tag=""}}},
 industrialforegoing_jj_spores_recreator={hasPattern=true,label="Spores Recreator",recipe={industrialforegoing_jj_plastic={need=5,tag=""},minecraft_jj_red_mushroom={need=2,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=1,tag=""}}},
 industrialforegoing_jj_straw={hasPattern=true,label="Straw",recipe={industrialforegoing_jj_plastic={need=4,tag=""}}},
 industrialforegoing_jj_tinydryrubber={hasPattern=false,label="",recipe={}},
 industrialforegoing_jj_tree_fluid_extractor={hasPattern=true,label="Tree Fluid Extractor",recipe={minecraft_jj_furnace={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""},minecraft_jj_stone={need=6,tag=""},thermalfoundation_jj_material_jj_24={need=1,tag=""}}},
 industrialforegoing_jj_villager_trade_exchanger={hasPattern=true,label="Villager Trade Exchanger",recipe={industrialforegoing_jj_plastic={need=4,tag=""},minecraft_jj_emerald={need=2,tag=""},minecraft_jj_gold_ingot={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=1,tag=""}}},
 industrialforegoing_jj_water_condensator={hasPattern=true,label="Water Condensator",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_piston={need=2,tag=""},minecraft_jj_redstone={need=1,tag=""},minecraft_jj_water_bucket={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=2,tag=""}}},
 industrialforegoing_jj_water_resources_collector={hasPattern=true,label="Resources Fisher",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_bucket={need=2,tag=""},minecraft_jj_fishing_rod={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""},thermalexpansion_jj_frame={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=2,tag=""}}},
 industrialforegoing_jj_wither_builder={hasPattern=true,label="Wither Builder",recipe={industrialforegoing_jj_plastic={need=2,tag=""},minecraft_jj_nether_star={need=1,tag=""},minecraft_jj_skull_jj_1={need=2,tag=""},minecraft_jj_soul_sand={need=3,tag=""},thermalexpansion_jj_frame={need=1,tag=""}}},
 infinitycraft_jj_aluminum_bar={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_aluminum_block={hasPattern=true,label="Aluminum Block",recipe={infinitycraft_jj_aluminum_bar={need=9,tag=""}}},
 infinitycraft_jj_aluminum_brick={hasPattern=true,label="Aluminum Brick",recipe={infinitycraft_jj_aluminum_bar={need=8,tag=""},minecraft_jj_stone={need=1,tag=""}}},
 infinitycraft_jj_aluminum_can={hasPattern=true,label="Aluminum Can",recipe={infinitycraft_jj_aluminum_bar={need=7,tag=""}}},
 infinitycraft_jj_aluminum_light={hasPattern=true,label="Aluminum Light",recipe={infinitycraft_jj_aluminum_bar={need=8,tag=""},minecraft_jj_glowstone={need=1,tag=""}}},
 infinitycraft_jj_aluminum_ore={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_amethyst={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_amethyst_axe={hasPattern=true,label="Amethyst Axe",recipe={infinitycraft_jj_amethyst={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_amethyst_block={hasPattern=true,label="Amethyst Block",recipe={infinitycraft_jj_amethyst={need=9,tag=""}}},
 infinitycraft_jj_amethyst_brick={hasPattern=true,label="Amethyst Brick",recipe={infinitycraft_jj_amethyst={need=8,tag=""},minecraft_jj_stone={need=1,tag=""}}},
 infinitycraft_jj_amethyst_hoe={hasPattern=true,label="Amethyst Hoe",recipe={infinitycraft_jj_amethyst={need=2,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_amethyst_light={hasPattern=true,label="Amethyst Light",recipe={infinitycraft_jj_amethyst={need=8,tag=""},minecraft_jj_glowstone={need=1,tag=""}}},
 infinitycraft_jj_amethyst_ore={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_amethyst_pickaxe={hasPattern=true,label="Amethyst Pickaxe",recipe={infinitycraft_jj_amethyst={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_amethyst_shovel={hasPattern=true,label="Amethyst Shovel",recipe={infinitycraft_jj_amethyst={need=1,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_amethyst_sword={hasPattern=true,label="Amethyst Sword",recipe={infinitycraft_jj_amethyst={need=2,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 infinitycraft_jj_apple_juice={hasPattern=true,label="Apple juice",recipe={infinitycraft_jj_aluminum_can={need=1,tag=""},minecraft_jj_apple={need=1,tag=""}}},
 infinitycraft_jj_block_compressor={hasPattern=true,label="Compressor",recipe={infinitycraft_jj_onyx_block={need=6,tag=""},minecraft_jj_piston={need=2,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 infinitycraft_jj_bronze_axe={hasPattern=true,label="Bronze Axe",recipe={infinitycraft_jj_bronze_bar={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_bronze_bar={hasPattern=true,label="Bronze Bar",recipe={infinitycraft_jj_copper_bar={need=1,tag=""},infinitycraft_jj_tin_bar={need=1,tag=""}}},
 infinitycraft_jj_bronze_hoe={hasPattern=true,label="Bronze Hoe",recipe={infinitycraft_jj_bronze_bar={need=2,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_bronze_pickaxe={hasPattern=true,label="Bronze Pickaxe",recipe={infinitycraft_jj_bronze_bar={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_bronze_shovel={hasPattern=true,label="Bronze Shovel",recipe={infinitycraft_jj_bronze_bar={need=1,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_bronze_sword={hasPattern=true,label="Bronze Sword",recipe={infinitycraft_jj_bronze_bar={need=2,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 infinitycraft_jj_canned_beef={hasPattern=true,label="Canned Beef",recipe={infinitycraft_jj_aluminum_can={need=1,tag=""},minecraft_jj_beef={need=1,tag=""}}},
 infinitycraft_jj_canned_fish={hasPattern=true,label="Canned Fish",recipe={infinitycraft_jj_aluminum_can={need=1,tag=""},minecraft_jj_fish={need=1,tag=""}}},
 infinitycraft_jj_canned_pork={hasPattern=true,label="Canned Pork",recipe={infinitycraft_jj_aluminum_can={need=1,tag=""},minecraft_jj_porkchop={need=1,tag=""}}},
 infinitycraft_jj_chainsaw={hasPattern=true,label="Chainsaw",recipe={infinitycraft_jj_motor={need=1,tag=""},infinitycraft_jj_onyx_bar={need=5,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 infinitycraft_jj_chocolate_apple={hasPattern=true,label="Chocolate Apple",recipe={minecraft_jj_apple={need=1,tag=""},minecraft_jj_dye_jj_4={need=1,tag=""}}},
 infinitycraft_jj_copper_bar={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_copper_coil={hasPattern=true,label="Copper Coil",recipe={infinitycraft_jj_copper_bar={need=8,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 infinitycraft_jj_copper_ore={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_dia_drill={hasPattern=true,label="Diamond Drill",recipe={infinitycraft_jj_drill={need=1,tag=""},infinitycraft_jj_onyx_bar={need=3,tag=""},minecraft_jj_diamond={need=3,tag=""}}},
 infinitycraft_jj_diamond_chainsaw={hasPattern=true,label="Diamond Chainsaw",recipe={infinitycraft_jj_chainsaw={need=1,tag=""},infinitycraft_jj_onyx_bar={need=3,tag=""},minecraft_jj_diamond={need=3,tag=""}}},
 infinitycraft_jj_donut={hasPattern=true,label="Donut",recipe={minecraft_jj_sugar={need=8,tag=""},minecraft_jj_wheat={need=1,tag=""}}},
 infinitycraft_jj_drill={hasPattern=true,label="Drill",recipe={infinitycraft_jj_motor={need=1,tag=""},infinitycraft_jj_onyx_bar={need=6,tag=""}}},
 infinitycraft_jj_energy_crystal={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_energy_crystal_mesh={hasPattern=true,label="Energy Crystal Mesh",recipe={infinitycraft_jj_nether_dust={need=1,tag=""},minecraft_jj_emerald={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 infinitycraft_jj_exp_ore={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_khalzit_axe={hasPattern=true,label="Khalzit Axe",recipe={infinitycraft_jj_khalzit_bar={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_khalzit_bar={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_khalzit_block={hasPattern=true,label="Khalzit Block",recipe={infinitycraft_jj_khalzit_bar={need=9,tag=""}}},
 infinitycraft_jj_khalzit_brick={hasPattern=true,label="Khalzit Brick",recipe={infinitycraft_jj_khalzit_bar={need=8,tag=""},minecraft_jj_stone={need=1,tag=""}}},
 infinitycraft_jj_khalzit_dust={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_khalzit_hoe={hasPattern=true,label="Khalzit Hoe",recipe={infinitycraft_jj_khalzit_bar={need=2,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_khalzit_light={hasPattern=true,label="Khalzit Light",recipe={infinitycraft_jj_khalzit_bar={need=8,tag=""},minecraft_jj_glowstone={need=1,tag=""}}},
 infinitycraft_jj_khalzit_ore={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_khalzit_pickaxe={hasPattern=true,label="Khalzit Pickaxe",recipe={infinitycraft_jj_khalzit_bar={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_khalzit_shovel={hasPattern=true,label="Khalzit Shovel",recipe={infinitycraft_jj_khalzit_bar={need=1,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_khalzit_sword={hasPattern=true,label="Khalzit Sword",recipe={infinitycraft_jj_khalzit_bar={need=2,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 infinitycraft_jj_motor={hasPattern=true,label="Motor",recipe={infinitycraft_jj_aluminum_bar={need=1,tag=""},infinitycraft_jj_copper_coil={need=2,tag=""},infinitycraft_jj_energy_crystal={need=1,tag=""},infinitycraft_jj_onyx_bar={need=5,tag=""}}},
 infinitycraft_jj_nether_axe={hasPattern=true,label="Nether Axe",recipe={infinitycraft_jj_nether_diamond={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_nether_boots={hasPattern=true,label="Nether Boots",recipe={infinitycraft_jj_nether_diamond={need=4,tag=""}}},
 infinitycraft_jj_nether_chestplate={hasPattern=true,label="Nether Chestplate",recipe={infinitycraft_jj_nether_diamond={need=8,tag=""}}},
 infinitycraft_jj_nether_diamond={hasPattern=true,label="Nether Diamond",recipe={infinitycraft_jj_energy_crystal_mesh={need=1,tag=""}}},
 infinitycraft_jj_nether_dust={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_nether_dust_ore={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_nether_helmet={hasPattern=true,label="Nether Helmet",recipe={infinitycraft_jj_nether_diamond={need=5,tag=""}}},
 infinitycraft_jj_nether_hoe={hasPattern=true,label="Nether Hoe",recipe={infinitycraft_jj_nether_diamond={need=2,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_nether_leggings={hasPattern=true,label="Nether Leggings",recipe={infinitycraft_jj_nether_diamond={need=7,tag=""}}},
 infinitycraft_jj_nether_pickaxe={hasPattern=true,label="Nether Pickaxe",recipe={infinitycraft_jj_nether_diamond={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_nether_shovel={hasPattern=true,label="Nether Shovel",recipe={infinitycraft_jj_nether_diamond={need=1,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_nether_sword={hasPattern=true,label="Nether Sword",recipe={infinitycraft_jj_nether_diamond={need=2,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 infinitycraft_jj_ocean_boots={hasPattern=true,label="Ocean Boots",recipe={infinitycraft_jj_ocean_diamond={need=4,tag=""}}},
 infinitycraft_jj_ocean_chestplate={hasPattern=true,label="Ocean Chestplate",recipe={infinitycraft_jj_ocean_diamond={need=8,tag=""}}},
 infinitycraft_jj_ocean_chunk={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_ocean_diamond={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_ocean_helmet={hasPattern=true,label="Ocean Helmet",recipe={infinitycraft_jj_ocean_diamond={need=5,tag=""}}},
 infinitycraft_jj_ocean_leggings={hasPattern=true,label="Ocean Leggings",recipe={infinitycraft_jj_ocean_diamond={need=7,tag=""}}},
 infinitycraft_jj_ocean_ore={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_oily_stone={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_onyx_axe={hasPattern=true,label="Onyx Axe",recipe={infinitycraft_jj_onyx_bar={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_onyx_bar={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_onyx_block={hasPattern=true,label="Onyx Block",recipe={infinitycraft_jj_onyx_bar={need=9,tag=""}}},
 infinitycraft_jj_onyx_boots={hasPattern=true,label="Onyx Boots",recipe={infinitycraft_jj_onyx_bar={need=4,tag=""}}},
 infinitycraft_jj_onyx_brick={hasPattern=true,label="Onyx Brick",recipe={infinitycraft_jj_onyx_bar={need=8,tag=""},minecraft_jj_stone={need=1,tag=""}}},
 infinitycraft_jj_onyx_chestplate={hasPattern=true,label="Onyx Chestplate",recipe={infinitycraft_jj_onyx_bar={need=8,tag=""}}},
 infinitycraft_jj_onyx_helmet={hasPattern=true,label="Onyx Helmet",recipe={infinitycraft_jj_onyx_bar={need=5,tag=""}}},
 infinitycraft_jj_onyx_hoe={hasPattern=true,label="Onyx Hoe",recipe={infinitycraft_jj_onyx_bar={need=2,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_onyx_leggings={hasPattern=true,label="Onyx Leggings",recipe={infinitycraft_jj_onyx_bar={need=7,tag=""}}},
 infinitycraft_jj_onyx_light={hasPattern=true,label="Onyx Light",recipe={infinitycraft_jj_onyx_bar={need=8,tag=""},minecraft_jj_glowstone={need=1,tag=""}}},
 infinitycraft_jj_onyx_ore={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_onyx_pickaxe={hasPattern=true,label="Onyx Pickaxe",recipe={infinitycraft_jj_onyx_bar={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_onyx_shovel={hasPattern=true,label="Onyx Shovel",recipe={infinitycraft_jj_onyx_bar={need=1,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_onyx_sword={hasPattern=true,label="Onyx Sword",recipe={infinitycraft_jj_onyx_bar={need=2,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 infinitycraft_jj_pancake={hasPattern=true,label="Pancake",recipe={infinitycraft_jj_pancake_batter={need=1,tag=""}}},
 infinitycraft_jj_pancake_batter={hasPattern=true,label="Pancake Batter",recipe={minecraft_jj_bowl={need=1,tag=""},minecraft_jj_egg={need=1,tag=""},minecraft_jj_milk_bucket={need=1,tag=""},minecraft_jj_wheat={need=1,tag=""}}},
 infinitycraft_jj_pudding_bread={hasPattern=true,label="Pudding Bread",recipe={minecraft_jj_milk_bucket={need=1,tag=""},minecraft_jj_sugar={need=3,tag=""},minecraft_jj_wheat={need=3,tag=""}}},
 infinitycraft_jj_rubber_boots={hasPattern=true,label="Rubber Boots",recipe={infinitycraft_jj_rubbery_ball={need=2,tag=""},minecraft_jj_wool={need=2,tag=""}}},
 infinitycraft_jj_rubber_chestplate={hasPattern=true,label="Rubber Chestplate",recipe={infinitycraft_jj_rubbery_ball={need=7,tag=""},minecraft_jj_wool={need=1,tag=""}}},
 infinitycraft_jj_rubber_helmet={hasPattern=true,label="Rubber Helmet",recipe={infinitycraft_jj_rubbery_ball={need=5,tag=""},minecraft_jj_wool={need=1,tag=""}}},
 infinitycraft_jj_rubber_leggings={hasPattern=true,label="Rubber Leggings",recipe={infinitycraft_jj_rubbery_ball={need=6,tag=""},minecraft_jj_wool={need=1,tag=""}}},
 infinitycraft_jj_rubbery_ball={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_sphalzite_axe={hasPattern=true,label="Sphalzite Axe",recipe={infinitycraft_jj_sphalzite_bar={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_sphalzite_bar={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_sphalzite_block={hasPattern=true,label="Sphalzite Block",recipe={infinitycraft_jj_sphalzite_bar={need=9,tag=""}}},
 infinitycraft_jj_sphalzite_brick={hasPattern=true,label="Sphalzite Brick",recipe={infinitycraft_jj_sphalzite_bar={need=8,tag=""},minecraft_jj_stone={need=1,tag=""}}},
 infinitycraft_jj_sphalzite_chunk={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_sphalzite_hoe={hasPattern=true,label="Sphalzite Hoe",recipe={infinitycraft_jj_sphalzite_bar={need=2,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_sphalzite_light={hasPattern=true,label="Sphalzite Light",recipe={infinitycraft_jj_sphalzite_bar={need=8,tag=""},minecraft_jj_glowstone={need=1,tag=""}}},
 infinitycraft_jj_sphalzite_ore={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_sphalzite_pickaxe={hasPattern=true,label="Sphalzite Pickaxe",recipe={infinitycraft_jj_sphalzite_bar={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_sphalzite_shovel={hasPattern=true,label="Sphalzite Shovel",recipe={infinitycraft_jj_sphalzite_bar={need=1,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_sphalzite_sword={hasPattern=true,label="Sphalzite Sword",recipe={infinitycraft_jj_sphalzite_bar={need=2,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 infinitycraft_jj_sugar_bread={hasPattern=true,label="Sugar Bread",recipe={minecraft_jj_sugar={need=3,tag=""},minecraft_jj_wheat={need=3,tag=""}}},
 infinitycraft_jj_tin_bar={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_tin_ore={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_uranium={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_uranium_ore={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_zeux_axe={hasPattern=true,label="Zeux Axe",recipe={infinitycraft_jj_zeux_bar={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_zeux_bar={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_zeux_block={hasPattern=true,label="Zeux Block",recipe={infinitycraft_jj_zeux_bar={need=9,tag=""}}},
 infinitycraft_jj_zeux_brick={hasPattern=true,label="Zeux Brick",recipe={infinitycraft_jj_zeux_bar={need=8,tag=""},minecraft_jj_stone={need=1,tag=""}}},
 infinitycraft_jj_zeux_dust={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_zeux_hoe={hasPattern=true,label="Zeux Hoe",recipe={infinitycraft_jj_zeux_bar={need=2,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_zeux_light={hasPattern=true,label="Zeux Light",recipe={infinitycraft_jj_zeux_bar={need=8,tag=""},minecraft_jj_glowstone={need=1,tag=""}}},
 infinitycraft_jj_zeux_ore={hasPattern=false,label="",recipe={}},
 infinitycraft_jj_zeux_pickaxe={hasPattern=true,label="Zeux Pickaxe",recipe={infinitycraft_jj_zeux_bar={need=3,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_zeux_shovel={hasPattern=true,label="Zeux Shovel",recipe={infinitycraft_jj_zeux_bar={need=1,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 infinitycraft_jj_zeux_sword={hasPattern=true,label="Zeux Sword",recipe={infinitycraft_jj_zeux_bar={need=2,tag=""},minecraft_jj_stick={need=1,tag=""}}}
 }