return {
 plants2_jj_aakore={hasPattern=false,label="",recipe={}},
 plants2_jj_actaea_p={hasPattern=false,label="",recipe={}},
 plants2_jj_adlumia_f={hasPattern=false,label="",recipe={}},
 plants2_jj_afgekia_m={hasPattern=false,label="",recipe={}},
 plants2_jj_akebia_q={hasPattern=false,label="",recipe={}},
 plants2_jj_akebia_q_vine={hasPattern=false,label="",recipe={}},
 plants2_jj_alternanthera_f={hasPattern=false,label="",recipe={}},
 plants2_jj_alyxia_b={hasPattern=false,label="",recipe={}},
 plants2_jj_amaranthus_h={hasPattern=false,label="",recipe={}},
 plants2_jj_amaranthus_h_seeds={hasPattern=false,label="",recipe={}},
 plants2_jj_ambrosia_a={hasPattern=false,label="",recipe={}},
 plants2_jj_ampelopsis_a={hasPattern=false,label="",recipe={}},
 plants2_jj_ampelopsis_a_vine={hasPattern=false,label="",recipe={}},
 plants2_jj_androsace_a={hasPattern=false,label="",recipe={}},
 plants2_jj_aphrireroot={hasPattern=false,label="",recipe={}},
 plants2_jj_apocynum_c={hasPattern=false,label="",recipe={}},
 plants2_jj_ash_slab={hasPattern=false,label="",recipe={}},
 plants2_jj_ash_stairs={hasPattern=false,label="",recipe={}},
 plants2_jj_black_kauri_slab={hasPattern=false,label="",recipe={}},
 plants2_jj_black_kauri_stairs={hasPattern=false,label="",recipe={}},
 plants2_jj_blackberry={hasPattern=false,label="",recipe={}},
 plants2_jj_blaze_slab={hasPattern=false,label="",recipe={}},
 plants2_jj_blaze_stairs={hasPattern=false,label="",recipe={}},
 plants2_jj_blueberry={hasPattern=false,label="",recipe={}},
 plants2_jj_brazillian_pine_slab={hasPattern=false,label="",recipe={}},
 plants2_jj_brazillian_pine_stairs={hasPattern=false,label="",recipe={}},
 plants2_jj_brewing_cauldron={hasPattern=true,label="Magical Brewing Cauldron",recipe={conquest_jj_sapling_3_jj_6={need=3,tag={}},minecraft_jj_blaze_powder={need=2,tag={}},minecraft_jj_cauldron={need=1,tag={}},minecraft_jj_stone_slab={need=3,tag={}},minecraft_jj_yellow_flower={need=3,tag={}}}},
 plants2_jj_briblebum={hasPattern=false,label="",recipe={}},
 plants2_jj_bush={hasPattern=false,label="",recipe={}},
 plants2_jj_bush_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_bush_jj_2={hasPattern=false,label="",recipe={}},
 plants2_jj_bush_jj_3={hasPattern=false,label="",recipe={}},
 plants2_jj_bush_jj_4={hasPattern=false,label="",recipe={}},
 plants2_jj_bush_jj_5={hasPattern=false,label="",recipe={}},
 plants2_jj_bushling={hasPattern=false,label="",recipe={}},
 plants2_jj_bushling_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_bushling_jj_2={hasPattern=false,label="",recipe={}},
 plants2_jj_bushling_jj_3={hasPattern=false,label="",recipe={}},
 plants2_jj_bushling_jj_4={hasPattern=false,label="",recipe={}},
 plants2_jj_bushling_jj_5={hasPattern=false,label="",recipe={}},
 plants2_jj_cataplant={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_0={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_0_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_0_jj_10={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_0_jj_11={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_0_jj_12={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_0_jj_13={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_0_jj_14={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_0_jj_15={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_0_jj_2={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_0_jj_3={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_0_jj_4={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_0_jj_5={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_0_jj_6={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_0_jj_7={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_0_jj_8={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_0_jj_9={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_1={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_1_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_1_jj_10={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_1_jj_11={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_1_jj_12={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_1_jj_13={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_1_jj_14={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_1_jj_15={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_1_jj_2={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_1_jj_3={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_1_jj_4={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_1_jj_5={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_1_jj_6={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_1_jj_7={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_1_jj_8={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_1_jj_9={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_2={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_2_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_2_jj_10={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_2_jj_11={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_2_jj_12={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_2_jj_13={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_2_jj_14={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_2_jj_15={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_2_jj_2={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_2_jj_3={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_2_jj_4={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_2_jj_5={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_2_jj_6={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_2_jj_7={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_2_jj_8={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_2_jj_9={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_3={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_3_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_3_jj_10={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_3_jj_11={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_3_jj_12={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_3_jj_13={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_3_jj_14={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_3_jj_15={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_3_jj_2={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_3_jj_3={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_3_jj_4={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_3_jj_5={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_3_jj_6={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_3_jj_7={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_3_jj_8={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_3_jj_9={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_4={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_4_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_4_jj_10={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_4_jj_11={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_4_jj_12={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_4_jj_13={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_4_jj_14={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_4_jj_15={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_4_jj_2={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_4_jj_3={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_4_jj_4={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_4_jj_5={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_4_jj_6={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_4_jj_7={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_4_jj_8={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_4_jj_9={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_5={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_5_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_5_jj_10={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_5_jj_11={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_5_jj_12={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_5_jj_13={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_5_jj_14={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_5_jj_15={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_5_jj_2={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_5_jj_3={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_5_jj_4={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_5_jj_5={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_5_jj_6={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_5_jj_7={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_5_jj_8={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_5_jj_9={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_6={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_6_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_6_jj_2={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_6_jj_3={hasPattern=false,label="",recipe={}},
 plants2_jj_cosmetic_6_jj_4={hasPattern=false,label="",recipe={}},
 plants2_jj_crystal={hasPattern=true,label="Crystal Formation",recipe={appliedenergistics2_jj_material_jj_10={need=1,tag={}}}},
 plants2_jj_crystal_axe={hasPattern=false,label="",recipe={}},
 plants2_jj_crystal_hoe={hasPattern=false,label="",recipe={}},
 plants2_jj_crystal_jj_1={hasPattern=true,label="Crystal Block",recipe={plants2_jj_generic_jj_6={need=4,tag={}}}},
 plants2_jj_crystal_jj_2={hasPattern=true,label="Crystal Bricks",recipe={plants2_jj_crystal_jj_1={need=4,tag={}}}},
 plants2_jj_crystal_jj_3={hasPattern=true,label="Dark Crystal Formation",recipe={appliedenergistics2_jj_material_jj_12={need=1,tag={}}}},
 plants2_jj_crystal_jj_4={hasPattern=true,label="Dark Crystal Block",recipe={plants2_jj_generic_jj_8={need=4,tag={}}}},
 plants2_jj_crystal_jj_5={hasPattern=true,label="Dark Crystal Bricks",recipe={plants2_jj_crystal_jj_4={need=4,tag={}}}},
 plants2_jj_crystal_jj_6={hasPattern=true,label="Titan Stone",recipe={plants2_jj_crystal_jj_1={need=2,tag={}},plants2_jj_crystal_jj_4={need=2,tag={}}}},
 plants2_jj_crystal_leaves={hasPattern=false,label="",recipe={}},
 plants2_jj_crystal_leaves_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_crystal_log={hasPattern=false,label="",recipe={}},
 plants2_jj_crystal_log_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_crystal_pickaxe={hasPattern=false,label="",recipe={}},
 plants2_jj_crystal_planks={hasPattern=false,label="",recipe={}},
 plants2_jj_crystal_planks_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_crystal_sapling={hasPattern=false,label="",recipe={}},
 plants2_jj_crystal_shovel={hasPattern=false,label="",recipe={}},
 plants2_jj_crystal_slab={hasPattern=false,label="",recipe={}},
 plants2_jj_crystal_stairs={hasPattern=false,label="",recipe={}},
 plants2_jj_crystal_sword={hasPattern=false,label="",recipe={}},
 plants2_jj_crystal_torch={hasPattern=false,label="",recipe={}},
 plants2_jj_dark_crystal_axe={hasPattern=false,label="",recipe={}},
 plants2_jj_dark_crystal_hoe={hasPattern=false,label="",recipe={}},
 plants2_jj_dark_crystal_pickaxe={hasPattern=false,label="",recipe={}},
 plants2_jj_dark_crystal_shovel={hasPattern=false,label="",recipe={}},
 plants2_jj_dark_crystal_slab={hasPattern=false,label="",recipe={}},
 plants2_jj_dark_crystal_stairs={hasPattern=false,label="",recipe={}},
 plants2_jj_dark_crystal_sword={hasPattern=false,label="",recipe={}},
 plants2_jj_daucus_c={hasPattern=false,label="",recipe={}},
 plants2_jj_desert_0={hasPattern=false,label="",recipe={}},
 plants2_jj_desert_0_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_desert_0_jj_10={hasPattern=false,label="",recipe={}},
 plants2_jj_desert_0_jj_11={hasPattern=false,label="",recipe={}},
 plants2_jj_desert_0_jj_12={hasPattern=false,label="",recipe={}},
 plants2_jj_desert_0_jj_13={hasPattern=false,label="",recipe={}},
 plants2_jj_desert_0_jj_14={hasPattern=false,label="",recipe={}},
 plants2_jj_desert_0_jj_15={hasPattern=false,label="",recipe={}},
 plants2_jj_desert_0_jj_2={hasPattern=false,label="",recipe={}},
 plants2_jj_desert_0_jj_3={hasPattern=false,label="",recipe={}},
 plants2_jj_desert_0_jj_4={hasPattern=false,label="",recipe={}},
 plants2_jj_desert_0_jj_5={hasPattern=false,label="",recipe={}},
 plants2_jj_desert_0_jj_6={hasPattern=false,label="",recipe={}},
 plants2_jj_desert_0_jj_7={hasPattern=false,label="",recipe={}},
 plants2_jj_desert_0_jj_8={hasPattern=false,label="",recipe={}},
 plants2_jj_desert_0_jj_9={hasPattern=false,label="",recipe={}},
 plants2_jj_desert_1={hasPattern=false,label="",recipe={}},
 plants2_jj_desert_1_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_desert_1_jj_2={hasPattern=false,label="",recipe={}},
 plants2_jj_desert_1_jj_3={hasPattern=false,label="",recipe={}},
 plants2_jj_double_0={hasPattern=false,label="",recipe={}},
 plants2_jj_double_0_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_double_0_jj_2={hasPattern=false,label="",recipe={}},
 plants2_jj_double_0_jj_3={hasPattern=false,label="",recipe={}},
 plants2_jj_double_0_jj_4={hasPattern=false,label="",recipe={}},
 plants2_jj_double_0_jj_5={hasPattern=false,label="",recipe={}},
 plants2_jj_double_0_jj_6={hasPattern=false,label="",recipe={}},
 plants2_jj_double_harvest_0={hasPattern=false,label="",recipe={}},
 plants2_jj_excalibur={hasPattern=true,label="Holy Sword Excalibur",recipe={botania_jj_kingkey={need=1,tag={}}}},
 plants2_jj_fire_fruit={hasPattern=false,label="",recipe={}},
 plants2_jj_generic={hasPattern=false,label="",recipe={}},
 plants2_jj_generic_jj_1={hasPattern=false,label="",recipe={plants2_jj_blackberry={need=1,tag={}}}},
 plants2_jj_generic_jj_10={hasPattern=false,label="",recipe={}},
 plants2_jj_generic_jj_11={hasPattern=false,label="",recipe={}},
 plants2_jj_generic_jj_12={hasPattern=false,label="",recipe={}},
 plants2_jj_generic_jj_13={hasPattern=false,label="",recipe={}},
 plants2_jj_generic_jj_2={hasPattern=false,label="",recipe={plants2_jj_cosmetic_4_jj_4={need=1,tag={}}}},
 plants2_jj_generic_jj_3={hasPattern=false,label="",recipe={plants2_jj_cosmetic_4_jj_10={need=1,tag={}}}},
 plants2_jj_generic_jj_4={hasPattern=false,label="",recipe={plants2_jj_cosmetic_0_jj_2={need=1,tag={}}}},
 plants2_jj_generic_jj_5={hasPattern=false,label="",recipe={plants2_jj_generic_jj_6={need=1,tag={}}}},
 plants2_jj_generic_jj_6={hasPattern=true,label="Crystal Chunk",recipe={plants2_jj_generic_jj_5={need=4,tag={}}}},
 plants2_jj_generic_jj_7={hasPattern=false,label="",recipe={plants2_jj_generic_jj_8={need=1,tag={}}}},
 plants2_jj_generic_jj_8={hasPattern=true,label="Dark Crystal Chunk",recipe={plants2_jj_generic_jj_7={need=4,tag={}}}},
 plants2_jj_generic_jj_9={hasPattern=false,label="",recipe={plants2_jj_generic_jj_6={need=2,tag={}}}},
 plants2_jj_groundcover={hasPattern=true,label="Crystal Groundcover",recipe={minecraft_jj_gravel={need=1,tag={}},tconstruct_jj_soil={need=1,tag={}}}},
 plants2_jj_harvest_0={hasPattern=false,label="",recipe={}},
 plants2_jj_harvest_0_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_harvest_0_jj_2={hasPattern=false,label="",recipe={}},
 plants2_jj_harvest_0_jj_3={hasPattern=false,label="",recipe={}},
 plants2_jj_harvest_0_jj_4={hasPattern=false,label="",recipe={}},
 plants2_jj_harvest_0_jj_5={hasPattern=false,label="",recipe={}},
 plants2_jj_harvest_0_jj_6={hasPattern=false,label="",recipe={}},
 plants2_jj_harvest_0_jj_7={hasPattern=false,label="",recipe={}},
 plants2_jj_harvest_1={hasPattern=false,label="",recipe={}},
 plants2_jj_harvest_1_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_harvest_1_jj_2={hasPattern=false,label="",recipe={}},
 plants2_jj_harvest_1_jj_3={hasPattern=false,label="",recipe={}},
 plants2_jj_harvest_1_jj_4={hasPattern=false,label="",recipe={}},
 plants2_jj_harvest_1_jj_5={hasPattern=false,label="",recipe={}},
 plants2_jj_huckleberry={hasPattern=false,label="",recipe={}},
 plants2_jj_incense_cedar_slab={hasPattern=false,label="",recipe={}},
 plants2_jj_incense_cedar_stairs={hasPattern=false,label="",recipe={}},
 plants2_jj_jar={hasPattern=false,label="",recipe={}},
 plants2_jj_leaves_0={hasPattern=false,label="",recipe={}},
 plants2_jj_leaves_0_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_leaves_0_jj_2={hasPattern=false,label="",recipe={}},
 plants2_jj_leaves_0_jj_3={hasPattern=false,label="",recipe={}},
 plants2_jj_log_0={hasPattern=false,label="",recipe={}},
 plants2_jj_log_0_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_log_0_jj_2={hasPattern=false,label="",recipe={}},
 plants2_jj_log_0_jj_3={hasPattern=false,label="",recipe={}},
 plants2_jj_murray_pine_slab={hasPattern=false,label="",recipe={}},
 plants2_jj_murray_pine_stairs={hasPattern=false,label="",recipe={}},
 plants2_jj_nether_harvest={hasPattern=false,label="",recipe={}},
 plants2_jj_nether_harvest_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_nether_harvest_jj_2={hasPattern=false,label="",recipe={}},
 plants2_jj_nether_harvest_jj_3={hasPattern=false,label="",recipe={}},
 plants2_jj_nether_harvest_jj_4={hasPattern=false,label="",recipe={}},
 plants2_jj_nether_harvest_jj_5={hasPattern=false,label="",recipe={}},
 plants2_jj_nether_leaves={hasPattern=false,label="",recipe={}},
 plants2_jj_nether_leaves_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_nether_log={hasPattern=false,label="",recipe={}},
 plants2_jj_nether_log_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_nether_sapling={hasPattern=false,label="",recipe={}},
 plants2_jj_nether_sapling_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_okra={hasPattern=false,label="",recipe={}},
 plants2_jj_okra_seeds={hasPattern=false,label="",recipe={}},
 plants2_jj_phytolacca_a={hasPattern=false,label="",recipe={}},
 plants2_jj_pineapple={hasPattern=false,label="",recipe={}},
 plants2_jj_pineapple_seeds={hasPattern=false,label="",recipe={}},
 plants2_jj_planks={hasPattern=false,label="",recipe={plants2_jj_nether_log={need=1,tag={}}}},
 plants2_jj_planks_jj_1={hasPattern=false,label="",recipe={plants2_jj_nether_log_jj_1={need=1,tag={}}}},
 plants2_jj_planks_jj_2={hasPattern=false,label="",recipe={plants2_jj_log_0={need=1,tag={}}}},
 plants2_jj_planks_jj_3={hasPattern=false,label="",recipe={plants2_jj_log_0_jj_1={need=1,tag={}}}},
 plants2_jj_planks_jj_4={hasPattern=false,label="",recipe={plants2_jj_log_0_jj_2={need=1,tag={}}}},
 plants2_jj_planks_jj_5={hasPattern=false,label="",recipe={plants2_jj_log_0_jj_3={need=1,tag={}}}},
 plants2_jj_plantago_m={hasPattern=false,label="",recipe={}},
 plants2_jj_plantball={hasPattern=true,label="Coagulated Plant Ball",recipe={conquest_jj_sapling_3_jj_6={need=9,tag={}},minecraft_jj_sapling={need=9,tag={}}}},
 plants2_jj_raspberry={hasPattern=false,label="",recipe={}},
 plants2_jj_rubus_o={hasPattern=false,label="",recipe={}},
 plants2_jj_rubus_p={hasPattern=false,label="",recipe={}},
 plants2_jj_saffron={hasPattern=false,label="",recipe={}},
 plants2_jj_saimbaire={hasPattern=false,label="",recipe={}},
 plants2_jj_sapling_0={hasPattern=false,label="",recipe={}},
 plants2_jj_sapling_0_jj_1={hasPattern=false,label="",recipe={}},
 plants2_jj_sapling_0_jj_2={hasPattern=false,label="",recipe={}},
 plants2_jj_sapling_0_jj_3={hasPattern=false,label="",recipe={}},
 plants2_jj_small_flower_aithotus={hasPattern=false,label="",recipe={}},
 plants2_jj_solanum_c={hasPattern=false,label="",recipe={}},
 plants2_jj_solanum_d={hasPattern=false,label="",recipe={}},
 plants2_jj_solanum_n={hasPattern=false,label="",recipe={}},
 plants2_jj_tahitian_spinach={hasPattern=false,label="",recipe={}},
 rustic_jj_ale_wort={hasPattern=false,label="",recipe={}},
 rustic_jj_aloe_vera={hasPattern=false,label="",recipe={}},
 rustic_jj_andesite_pillar={hasPattern=true,label="Andesitsäule",recipe={minecraft_jj_stone_jj_5={need=6,tag={}}}},
 rustic_jj_apiary={hasPattern=true,label="Bienenhaus",recipe={minecraft_jj_log={need=6,tag={}},minecraft_jj_planks={need=2,tag={}}}},
 rustic_jj_apple_juice={hasPattern=false,label="",recipe={}},
 rustic_jj_apple_seeds={hasPattern=false,label="",recipe={}},
 rustic_jj_barrel={hasPattern=true,label="Fass",recipe={minecraft_jj_iron_ingot={need=2,tag={}},minecraft_jj_planks={need=4,tag={}},minecraft_jj_wooden_slab={need=2,tag={}}}},
 rustic_jj_bee={hasPattern=false,label="",recipe={}},
 rustic_jj_beehive={hasPattern=false,label="",recipe={}},
 rustic_jj_beeswax={hasPattern=false,label="",recipe={}},
 rustic_jj_blood_orchid={hasPattern=false,label="",recipe={}},
 rustic_jj_book={hasPattern=true,label="Almanac",recipe={minecraft_jj_book={need=1,tag={}},minecraft_jj_iron_nugget={need=3,tag={}},rustic_jj_olives={need=1,tag={}}}},
 rustic_jj_brewing_barrel={hasPattern=true,label="Braufass",recipe={minecraft_jj_iron_ingot={need=2,tag={}},minecraft_jj_planks={need=4,tag={}},minecraft_jj_wooden_slab={need=2,tag={}}}},
 rustic_jj_cabinet={hasPattern=false,label="",recipe={minecraft_jj_planks={need=7,tag={}},minecraft_jj_trapdoor={need=1,tag={}}}},
 rustic_jj_candle={hasPattern=true,label="Kerze",recipe={minecraft_jj_iron_ingot={need=1,tag={}},minecraft_jj_string={need=1,tag={}},rustic_jj_beeswax={need=1,tag={}}}},
 rustic_jj_candle_gold={hasPattern=false,label="",recipe={}},
 rustic_jj_chain={hasPattern=true,label="Eisenkette",recipe={minecraft_jj_iron_ingot={need=3,tag={}}}},
 rustic_jj_chain_gold={hasPattern=false,label="",recipe={}},
 rustic_jj_chair_acacia={hasPattern=true,label="Akazienstuhl",recipe={minecraft_jj_planks_jj_4={need=4,tag={}},minecraft_jj_stick={need=2,tag={}}}},
 rustic_jj_chair_big_oak={hasPattern=true,label="Schwarzeichenstuhl",recipe={minecraft_jj_planks_jj_5={need=4,tag={}},minecraft_jj_stick={need=2,tag={}}}},
 rustic_jj_chair_birch={hasPattern=true,label="Birkenstuhl",recipe={minecraft_jj_planks_jj_2={need=4,tag={}},minecraft_jj_stick={need=2,tag={}}}},
 rustic_jj_chair_ironwood={hasPattern=true,label="Eisenholzstuhl",recipe={minecraft_jj_stick={need=2,tag={}},rustic_jj_planks_jj_1={need=4,tag={}}}},
 rustic_jj_chair_jungle={hasPattern=true,label="Tropenstuhl",recipe={minecraft_jj_planks_jj_3={need=4,tag={}},minecraft_jj_stick={need=2,tag={}}}},
 rustic_jj_chair_oak={hasPattern=true,label="Eichenstuhl",recipe={minecraft_jj_planks={need=4,tag={}},minecraft_jj_stick={need=2,tag={}}}},
 rustic_jj_chair_olive={hasPattern=true,label="Olivenholzstuhl",recipe={minecraft_jj_stick={need=2,tag={}},rustic_jj_planks={need=4,tag={}}}},
 rustic_jj_chair_spruce={hasPattern=true,label="Fichtenstuhl",recipe={minecraft_jj_planks_jj_1={need=4,tag={}},minecraft_jj_stick={need=2,tag={}}}},
 rustic_jj_chamomile={hasPattern=false,label="",recipe={}},
 rustic_jj_chandelier={hasPattern=true,label="Kronleuchterring",recipe={minecraft_jj_iron_ingot={need=4,tag={}},rustic_jj_chain={need=2,tag={}}}},
 rustic_jj_chandelier_gold={hasPattern=false,label="",recipe={}},
 rustic_jj_chili_pepper={hasPattern=false,label="",recipe={}},
 rustic_jj_chili_pepper_seeds={hasPattern=false,label="",recipe={}},
 rustic_jj_clay_wall={hasPattern=true,label="Tonmauer",recipe={minecraft_jj_clay={need=1,tag={}},minecraft_jj_planks={need=4,tag={}}}},
 rustic_jj_clay_wall_cross={hasPattern=true,label="Gekreuzte Tonmauer",recipe={minecraft_jj_planks={need=4,tag={}},rustic_jj_clay_wall={need=1,tag={}}}},
 rustic_jj_clay_wall_diag={hasPattern=true,label="Diagonale Tonmauer",recipe={minecraft_jj_planks={need=2,tag={}},rustic_jj_clay_wall={need=1,tag={}}}},
 rustic_jj_cloudsbluff={hasPattern=false,label="",recipe={}},
 rustic_jj_cohosh={hasPattern=false,label="",recipe={}},
 rustic_jj_condenser={hasPattern=true,label="Alchemischer Kondensator",recipe={minecraft_jj_brick={need=5,tag={}},minecraft_jj_bucket={need=1,tag={}},minecraft_jj_stained_hardened_clay={need=1,tag={}}}},
 rustic_jj_condenser_advanced={hasPattern=true,label="Erweiterter Alchemischer Kondensator",recipe={minecraft_jj_bucket={need=1,tag={}},minecraft_jj_iron_block={need=1,tag={}},minecraft_jj_netherbrick={need=5,tag={}}}},
 rustic_jj_core_root={hasPattern=false,label="",recipe={}},
 rustic_jj_crop_stake={hasPattern=true,label="Holzpflock",recipe={minecraft_jj_planks={need=3,tag={}}}},
 rustic_jj_crushing_tub={hasPattern=true,label="Zerkleinerungswanne",recipe={minecraft_jj_iron_ingot={need=2,tag={}},minecraft_jj_planks={need=2,tag={}},minecraft_jj_wooden_slab={need=3,tag={}}}},
 rustic_jj_deathstalk_mushroom={hasPattern=false,label="",recipe={}},
 rustic_jj_diorite_pillar={hasPattern=true,label="Dioritsäule",recipe={minecraft_jj_stone_jj_3={need=6,tag={}}}},
 rustic_jj_dust_tiny_iron={hasPattern=false,label="",recipe={}},
 rustic_jj_elixir={hasPattern=false,label="",recipe={}},
 rustic_jj_evaporating_basin={hasPattern=true,label="Trockenbecken",recipe={minecraft_jj_hardened_clay={need=3,tag={}}}},
 rustic_jj_fence_gate_ironwood={hasPattern=true,label="Eisenholzzauntor",recipe={minecraft_jj_stick={need=4,tag={}},rustic_jj_planks_jj_1={need=2,tag={}}}},
 rustic_jj_fence_gate_olive={hasPattern=true,label="Olivenholzzauntor",recipe={minecraft_jj_stick={need=4,tag={}},rustic_jj_planks={need=2,tag={}}}},
 rustic_jj_fence_ironwood={hasPattern=true,label="Eisenholzzaun",recipe={minecraft_jj_stick={need=2,tag={}},rustic_jj_planks_jj_1={need=4,tag={}}}},
 rustic_jj_fence_olive={hasPattern=true,label="Olivenholzzaun",recipe={minecraft_jj_stick={need=2,tag={}},rustic_jj_planks={need=4,tag={}}}},
 rustic_jj_fertile_soil={hasPattern=true,label="Fruchtbarer Boden",recipe={minecraft_jj_dirt={need=1,tag={}},minecraft_jj_dye_jj_15={need=1,tag={}}}},
 rustic_jj_fluid_bottle={hasPattern=false,label="",recipe={}},
 rustic_jj_gargoyle={hasPattern=true,label="Wasserspeier",recipe={minecraft_jj_stone={need=1,tag={}},minecraft_jj_stone_pressure_plate={need=2,tag={}},minecraft_jj_stone_slab={need=3,tag={}}}},
 rustic_jj_ginseng={hasPattern=false,label="",recipe={}},
 rustic_jj_golden_lantern={hasPattern=false,label="",recipe={}},
 rustic_jj_granite_pillar={hasPattern=true,label="Granitsäule",recipe={minecraft_jj_stone_jj_1={need=6,tag={}}}},
 rustic_jj_grape_juice={hasPattern=false,label="",recipe={}},
 rustic_jj_grape_stem={hasPattern=true,label="Traubensamen",recipe={rustic_jj_grapes={need=1,tag={}}}},
 rustic_jj_grapes={hasPattern=false,label="",recipe={}},
 rustic_jj_honey={hasPattern=false,label="",recipe={}},
 rustic_jj_honeycomb={hasPattern=true,label="Bienenwabe",recipe={harvestcraft_jj_honeycombitem={need=1,tag={}}}},
 rustic_jj_horsetail={hasPattern=false,label="",recipe={}},
 rustic_jj_iron_lantern={hasPattern=true,label="Eisenlaterne",recipe={minecraft_jj_coal={need=1,tag={}},minecraft_jj_coal_jj_1={need=1,tag={}},minecraft_jj_iron_ingot={need=2,tag={}}}},
 rustic_jj_iron_lattice={hasPattern=true,label="Eisengitterwerk",recipe={minecraft_jj_iron_ingot={need=4,tag={}},minecraft_jj_iron_nugget={need=1,tag={}}}},
 rustic_jj_ironberries={hasPattern=true,label="Eisenbeeren",recipe={mekanism_jj_dust={need=1,tag={}},rustic_jj_wildberries={need=8,tag={}}}},
 rustic_jj_ironberry_juice={hasPattern=false,label="",recipe={}},
 rustic_jj_ironwood_door={hasPattern=true,label="Ironwood Door",recipe={rustic_jj_planks_jj_1={need=6,tag={}}}},
 rustic_jj_ironwood_slab_item={hasPattern=true,label="Eisenholzstufe",recipe={rustic_jj_planks_jj_1={need=3,tag={}}}},
 rustic_jj_leaves={hasPattern=false,label="",recipe={}},
 rustic_jj_leaves_apple={hasPattern=false,label="",recipe={}},
 rustic_jj_leaves_jj_1={hasPattern=false,label="",recipe={}},
 rustic_jj_liquid_barrel={hasPattern=true,label="Flüssigkeitsfass",recipe={minecraft_jj_iron_ingot={need=2,tag={}},minecraft_jj_planks={need=4,tag={}},minecraft_jj_wooden_slab={need=1,tag={}}}},
 rustic_jj_log={hasPattern=false,label="",recipe={}},
 rustic_jj_log_jj_1={hasPattern=false,label="",recipe={}},
 rustic_jj_marsh_mallow={hasPattern=false,label="",recipe={}},
 rustic_jj_mooncap_mushroom={hasPattern=false,label="",recipe={}},
 rustic_jj_olive_door={hasPattern=true,label="Olive Door",recipe={rustic_jj_planks={need=6,tag={}}}},
 rustic_jj_olive_oil={hasPattern=false,label="",recipe={}},
 rustic_jj_olive_slab_item={hasPattern=true,label="Olivenholzstufe",recipe={rustic_jj_planks={need=3,tag={}}}},
 rustic_jj_olives={hasPattern=true,label="Oliven",recipe={harvestcraft_jj_oliveitem={need=1,tag={}}}},
 rustic_jj_painted_wood_black={hasPattern=true,label="Schwarz gefärbtes Holz",recipe={minecraft_jj_dye={need=1,tag={}},minecraft_jj_planks={need=8,tag={}}}},
 rustic_jj_painted_wood_blue={hasPattern=false,label="",recipe={minecraft_jj_dye_jj_4={need=1,tag={}},minecraft_jj_planks={need=8,tag={}}}},
 rustic_jj_painted_wood_brown={hasPattern=true,label="Braun gefärbtes Holz",recipe={minecraft_jj_dye_jj_3={need=1,tag={}},minecraft_jj_planks={need=8,tag={}}}},
 rustic_jj_painted_wood_cyan={hasPattern=true,label="Türkis gefärbtes Holz",recipe={minecraft_jj_dye_jj_6={need=1,tag={}},minecraft_jj_planks={need=8,tag={}}}},
 rustic_jj_painted_wood_gray={hasPattern=true,label="Grau gefärbtes Holz",recipe={minecraft_jj_dye_jj_8={need=1,tag={}},minecraft_jj_planks={need=8,tag={}}}},
 rustic_jj_painted_wood_green={hasPattern=true,label="Grün gefärbtes Holz",recipe={minecraft_jj_dye_jj_2={need=1,tag={}},minecraft_jj_planks={need=8,tag={}}}},
 rustic_jj_painted_wood_light_blue={hasPattern=true,label="Hellblau gefärbtes Holz",recipe={minecraft_jj_dye_jj_12={need=1,tag={}},minecraft_jj_planks={need=8,tag={}}}},
 rustic_jj_painted_wood_lime={hasPattern=true,label="Hellgrün gefärbtes Holz",recipe={minecraft_jj_dye_jj_10={need=1,tag={}},minecraft_jj_planks={need=8,tag={}}}},
 rustic_jj_painted_wood_magenta={hasPattern=true,label="Magenta gefärbtes Holz",recipe={minecraft_jj_dye_jj_13={need=1,tag={}},minecraft_jj_planks={need=8,tag={}}}},
 rustic_jj_painted_wood_orange={hasPattern=true,label="Orange gefärbtes Holz",recipe={minecraft_jj_dye_jj_14={need=1,tag={}},minecraft_jj_planks={need=8,tag={}}}},
 rustic_jj_painted_wood_pink={hasPattern=true,label="Rosa gefärbtes Holz",recipe={minecraft_jj_dye_jj_9={need=1,tag={}},minecraft_jj_planks={need=8,tag={}}}},
 rustic_jj_painted_wood_purple={hasPattern=true,label="Violett gefärbtes Holz",recipe={minecraft_jj_dye_jj_5={need=1,tag={}},minecraft_jj_planks={need=8,tag={}}}},
 rustic_jj_painted_wood_red={hasPattern=true,label="Rot gefärbtes Holz",recipe={minecraft_jj_dye_jj_1={need=1,tag={}},minecraft_jj_planks={need=8,tag={}}}},
 rustic_jj_painted_wood_silver={hasPattern=true,label="Hellgrau gefärbtes Holz",recipe={minecraft_jj_dye_jj_7={need=1,tag={}},minecraft_jj_planks={need=8,tag={}}}},
 rustic_jj_painted_wood_white={hasPattern=true,label="Weiß gefärbtes Holz",recipe={minecraft_jj_dye_jj_15={need=1,tag={}},minecraft_jj_planks={need=8,tag={}}}},
 rustic_jj_painted_wood_yellow={hasPattern=true,label="Gelb gefärbtes Holz",recipe={minecraft_jj_dye_jj_11={need=1,tag={}},minecraft_jj_planks={need=8,tag={}}}},
 rustic_jj_planks={hasPattern=false,label="",recipe={rustic_jj_log={need=1,tag={}}}},
 rustic_jj_planks_jj_1={hasPattern=false,label="",recipe={rustic_jj_log_jj_1={need=1,tag={}}}},
 rustic_jj_retort={hasPattern=true,label="Alchemische Retorte",recipe={minecraft_jj_brick={need=2,tag={}},minecraft_jj_bucket={need=1,tag={}},minecraft_jj_iron_ingot={need=1,tag={}}}},
 rustic_jj_retort_advanced={hasPattern=true,label="Erweiterte Alchemische Retorte",recipe={minecraft_jj_bucket={need=1,tag={}},minecraft_jj_iron_ingot={need=1,tag={}},minecraft_jj_netherbrick={need=2,tag={}}}},
 rustic_jj_rope={hasPattern=false,label="",recipe={minecraft_jj_string={need=3,tag={}}}},
 rustic_jj_sapling={hasPattern=false,label="",recipe={}},
 rustic_jj_sapling_apple={hasPattern=false,label="",recipe={}},
 rustic_jj_sapling_jj_1={hasPattern=false,label="",recipe={}},
 rustic_jj_slate={hasPattern=false,label="",recipe={mysticalagriculture_jj_slate_essence={need=8,tag={}}}},
 rustic_jj_slate_brick={hasPattern=true,label="Schieferziegel",recipe={rustic_jj_slate_tile={need=4,tag={}}}},
 rustic_jj_slate_brick_slab_item={hasPattern=true,label="Schieferziegelstufe",recipe={rustic_jj_slate_brick={need=3,tag={}}}},
 rustic_jj_slate_chiseled={hasPattern=true,label="Gemeißelter Schiefer",recipe={rustic_jj_slate_brick={need=4,tag={}}}},
 rustic_jj_slate_pillar={hasPattern=false,label="",recipe={rustic_jj_slate_tile={need=6,tag={}}}},
 rustic_jj_slate_roof={hasPattern=true,label="Schieferdach",recipe={rustic_jj_slate={need=4,tag={}}}},
 rustic_jj_slate_roof_slab_item={hasPattern=true,label="Schieferdachstufe",recipe={rustic_jj_slate_roof={need=3,tag={}}}},
 rustic_jj_slate_tile={hasPattern=true,label="Schieferfliesen",recipe={rustic_jj_slate={need=1,tag={}}}},
 rustic_jj_stairs_ironwood={hasPattern=true,label="Eisenholztreppe",recipe={rustic_jj_planks_jj_1={need=6,tag={}}}},
 rustic_jj_stairs_olive={hasPattern=true,label="Olivenholztreppe",recipe={rustic_jj_planks={need=6,tag={}}}},
 rustic_jj_stairs_slate_brick={hasPattern=true,label="Schieferziegeltreppe",recipe={rustic_jj_slate_brick={need=6,tag={}}}},
 rustic_jj_stairs_slate_roof={hasPattern=true,label="Schieferdachtreppe",recipe={rustic_jj_slate_roof={need=6,tag={}}}},
 rustic_jj_stone_pillar={hasPattern=true,label="Steinsäule",recipe={minecraft_jj_stone={need=6,tag={}}}},
 rustic_jj_table_acacia={hasPattern=true,label="Akazientisch",recipe={minecraft_jj_planks_jj_4={need=3,tag={}},minecraft_jj_stick={need=2,tag={}}}},
 rustic_jj_table_big_oak={hasPattern=true,label="Schwarzeichentisch",recipe={minecraft_jj_planks_jj_5={need=3,tag={}},minecraft_jj_stick={need=2,tag={}}}},
 rustic_jj_table_birch={hasPattern=true,label="Birkentisch",recipe={minecraft_jj_planks_jj_2={need=3,tag={}},minecraft_jj_stick={need=2,tag={}}}},
 rustic_jj_table_ironwood={hasPattern=true,label="Eisenholztisch",recipe={minecraft_jj_stick={need=2,tag={}},rustic_jj_planks_jj_1={need=3,tag={}}}},
 rustic_jj_table_jungle={hasPattern=true,label="Tropentisch",recipe={minecraft_jj_planks_jj_3={need=3,tag={}},minecraft_jj_stick={need=2,tag={}}}},
 rustic_jj_table_oak={hasPattern=true,label="Eichentisch",recipe={minecraft_jj_planks={need=3,tag={}},minecraft_jj_stick={need=2,tag={}}}},
 rustic_jj_table_olive={hasPattern=true,label="Olivenholztisch",recipe={minecraft_jj_stick={need=2,tag={}},rustic_jj_planks={need=3,tag={}}}},
 rustic_jj_table_spruce={hasPattern=true,label="Fichtentisch",recipe={minecraft_jj_planks_jj_1={need=3,tag={}},minecraft_jj_stick={need=2,tag={}}}},
 rustic_jj_tallow={hasPattern=false,label="",recipe={}},
 rustic_jj_tomato={hasPattern=false,label="",recipe={}},
 rustic_jj_tomato_seeds={hasPattern=false,label="",recipe={}},
 rustic_jj_vase={hasPattern=true,label="Topf",recipe={minecraft_jj_hardened_clay={need=6,tag={}}}},
 rustic_jj_wildberries={hasPattern=true,label="Wildbeeren",recipe={plants2_jj_alyxia_b={need=1,tag={}}}},
 rustic_jj_wildberry_bush={hasPattern=true,label="Wildbeerenbusch",recipe={minecraft_jj_fence={need=2,tag={}},minecraft_jj_leaves={need=1,tag={}},rustic_jj_wildberries={need=4,tag={}}}},
 rustic_jj_wildberry_juice={hasPattern=false,label="",recipe={}},
 rustic_jj_wind_thistle={hasPattern=false,label="",recipe={}},
 twilightforest_jj_alpha_fur={hasPattern=false,label="",recipe={}},
 twilightforest_jj_arctic_boots={hasPattern=true,label="Arktistiefel",recipe={twilightforest_jj_arctic_fur={need=4,tag={}}}},
 twilightforest_jj_arctic_chestplate={hasPattern=true,label="Arktisjacke",recipe={twilightforest_jj_arctic_fur={need=8,tag={}}}},
 twilightforest_jj_arctic_fur={hasPattern=false,label="",recipe={twilightforest_jj_block_storage_jj_3={need=1,tag={}}}},
 twilightforest_jj_arctic_helmet={hasPattern=true,label="Arktiskapuze",recipe={twilightforest_jj_arctic_fur={need=5,tag={}}}},
 twilightforest_jj_arctic_leggings={hasPattern=true,label="Arktishose",recipe={twilightforest_jj_arctic_fur={need=7,tag={}}}},
 twilightforest_jj_armor_shard={hasPattern=false,label="",recipe={}},
 twilightforest_jj_armor_shard_cluster={hasPattern=true,label="Rüstungsscherbencluster",recipe={twilightforest_jj_armor_shard={need=9,tag={}}}},
 twilightforest_jj_aurora_block={hasPattern=false,label="",recipe={}},
 twilightforest_jj_aurora_pillar={hasPattern=true,label="Aurorasäule",recipe={twilightforest_jj_aurora_block={need=2,tag={}}}},
 twilightforest_jj_aurora_slab={hasPattern=true,label="Aurorastufe",recipe={twilightforest_jj_aurora_block={need=3,tag={}}}},
 twilightforest_jj_auroralized_glass={hasPattern=false,label="",recipe={}},
 twilightforest_jj_block_and_chain={hasPattern=true,label="Morgenstern",recipe={twilightforest_jj_knightmetal_block={need=1,tag={}},twilightforest_jj_knightmetal_ingot={need=3,tag={}},twilightforest_jj_knightmetal_ring={need=1,tag={}}}},
 twilightforest_jj_block_storage={hasPattern=true,label="Block of Ironwood",recipe={twilightforest_jj_ironwood_ingot={need=9,tag={}}}},
 twilightforest_jj_block_storage_jj_1={hasPattern=true,label="Block of Fiery Metal",recipe={twilightforest_jj_fiery_ingot={need=9,tag={}}}},
 twilightforest_jj_block_storage_jj_2={hasPattern=true,label="Block of Steeleaf",recipe={twilightforest_jj_steeleaf_ingot={need=9,tag={}}}},
 twilightforest_jj_block_storage_jj_3={hasPattern=true,label="Block of Arctic Fur",recipe={twilightforest_jj_arctic_fur={need=9,tag={}}}},
 twilightforest_jj_block_storage_jj_4={hasPattern=true,label="Block of Carminite",recipe={twilightforest_jj_carminite={need=9,tag={}}}},
 twilightforest_jj_borer_essence={hasPattern=false,label="",recipe={}},
 twilightforest_jj_boss_spawner={hasPattern=false,label="",recipe={}},
 twilightforest_jj_boss_spawner_jj_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_boss_spawner_jj_2={hasPattern=false,label="",recipe={}},
 twilightforest_jj_boss_spawner_jj_3={hasPattern=false,label="",recipe={}},
 twilightforest_jj_boss_spawner_jj_4={hasPattern=false,label="",recipe={}},
 twilightforest_jj_boss_spawner_jj_5={hasPattern=false,label="",recipe={}},
 twilightforest_jj_boss_spawner_jj_6={hasPattern=false,label="",recipe={}},
 twilightforest_jj_boss_spawner_jj_7={hasPattern=false,label="",recipe={}},
 twilightforest_jj_boss_spawner_jj_9={hasPattern=false,label="",recipe={}},
 twilightforest_jj_burnt_thorns={hasPattern=false,label="",recipe={}},
 twilightforest_jj_canopy_button={hasPattern=false,label="",recipe={}},
 twilightforest_jj_canopy_door={hasPattern=false,label="",recipe={}},
 twilightforest_jj_canopy_fence={hasPattern=false,label="",recipe={}},
 twilightforest_jj_canopy_gate={hasPattern=false,label="",recipe={}},
 twilightforest_jj_canopy_planks={hasPattern=false,label="",recipe={}},
 twilightforest_jj_canopy_plate={hasPattern=false,label="",recipe={}},
 twilightforest_jj_canopy_slab={hasPattern=false,label="",recipe={}},
 twilightforest_jj_canopy_stairs={hasPattern=false,label="",recipe={}},
 twilightforest_jj_canopy_trapdoor={hasPattern=false,label="",recipe={}},
 twilightforest_jj_carminite={hasPattern=true,label="Karminit",recipe={minecraft_jj_ghast_tear={need=1,tag={}},minecraft_jj_redstone={need=4,tag={}},twilightforest_jj_borer_essence={need=4,tag={}}}},
 twilightforest_jj_castle_brick={hasPattern=false,label="",recipe={}},
 twilightforest_jj_castle_brick_jj_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_castle_brick_jj_2={hasPattern=false,label="",recipe={}},
 twilightforest_jj_castle_brick_jj_3={hasPattern=false,label="",recipe={}},
 twilightforest_jj_castle_brick_jj_4={hasPattern=false,label="",recipe={}},
 twilightforest_jj_castle_brick_jj_5={hasPattern=true,label="Thick Castle Brick",recipe={twilightforest_jj_castle_brick={need=4,tag={}},twilightforest_jj_castle_brick_jj_1={need=4,tag={}},twilightforest_jj_castle_brick_jj_2={need=4,tag={}},twilightforest_jj_castle_brick_jj_4={need=4,tag={}}}},
 twilightforest_jj_castle_door={hasPattern=false,label="",recipe={}},
 twilightforest_jj_castle_door_jj_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_castle_door_jj_2={hasPattern=false,label="",recipe={}},
 twilightforest_jj_castle_door_jj_3={hasPattern=false,label="",recipe={}},
 twilightforest_jj_castle_pillar={hasPattern=true,label="Encased Castle Brick Pillar",recipe={twilightforest_jj_castle_brick={need=4,tag={}},twilightforest_jj_castle_brick_jj_1={need=4,tag={}},twilightforest_jj_castle_brick_jj_2={need=4,tag={}},twilightforest_jj_castle_brick_jj_3={need=2,tag={}},twilightforest_jj_castle_brick_jj_4={need=4,tag={}},twilightforest_jj_castle_brick_jj_5={need=4,tag={}},twilightforest_jj_castle_pillar={need=2,tag={}},twilightforest_jj_castle_pillar_jj_1={need=2,tag={}}}},
 twilightforest_jj_castle_pillar_jj_1={hasPattern=true,label="Encased Castle Brick Tile",recipe={twilightforest_jj_castle_pillar={need=4,tag={}},twilightforest_jj_castle_pillar_jj_1={need=4,tag={}}}},
 twilightforest_jj_castle_pillar_jj_2={hasPattern=true,label="Bold Castle Brick Pillar",recipe={twilightforest_jj_castle_brick_jj_5={need=4,tag={}}}},
 twilightforest_jj_castle_pillar_jj_3={hasPattern=true,label="Bold Castle Brick Tiles",recipe={twilightforest_jj_castle_pillar_jj_2={need=4,tag={}},twilightforest_jj_castle_pillar_jj_3={need=4,tag={}}}},
 twilightforest_jj_castle_rune_brick={hasPattern=false,label="",recipe={}},
 twilightforest_jj_castle_rune_brick_jj_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_castle_rune_brick_jj_2={hasPattern=false,label="",recipe={}},
 twilightforest_jj_castle_rune_brick_jj_3={hasPattern=false,label="",recipe={}},
 twilightforest_jj_castle_stairs={hasPattern=true,label="Encased Castle Brick Stairs",recipe={twilightforest_jj_castle_pillar={need=6,tag={}},twilightforest_jj_castle_pillar_jj_1={need=6,tag={}}}},
 twilightforest_jj_castle_stairs_brick={hasPattern=false,label="",recipe={}},
 twilightforest_jj_castle_stairs_cracked={hasPattern=false,label="",recipe={}},
 twilightforest_jj_castle_stairs_jj_8={hasPattern=true,label="Bold Castle Brick Stairs",recipe={twilightforest_jj_castle_pillar_jj_2={need=6,tag={}},twilightforest_jj_castle_pillar_jj_3={need=6,tag={}}}},
 twilightforest_jj_castle_stairs_mossy={hasPattern=false,label="",recipe={}},
 twilightforest_jj_castle_stairs_worn={hasPattern=false,label="",recipe={}},
 twilightforest_jj_charm_of_keeping_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_charm_of_keeping_2={hasPattern=true,label="Totem der Bewahrung II",recipe={twilightforest_jj_charm_of_keeping_1={need=4,tag={}}}},
 twilightforest_jj_charm_of_keeping_3={hasPattern=true,label="Totem der Bewahrung III",recipe={twilightforest_jj_charm_of_keeping_2={need=4,tag={}}}},
 twilightforest_jj_charm_of_life_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_charm_of_life_2={hasPattern=true,label="Totem des Lebens II",recipe={twilightforest_jj_charm_of_life_1={need=4,tag={}}}},
 twilightforest_jj_cicada={hasPattern=false,label="",recipe={}},
 twilightforest_jj_cinder_furnace={hasPattern=false,label="",recipe={}},
 twilightforest_jj_cinder_log={hasPattern=false,label="",recipe={}},
 twilightforest_jj_cooked_meef={hasPattern=false,label="",recipe={}},
 twilightforest_jj_cooked_venison={hasPattern=false,label="",recipe={}},
 twilightforest_jj_crumble_horn={hasPattern=false,label="",recipe={}},
 twilightforest_jj_cube_of_annihilation={hasPattern=false,label="",recipe={}},
 twilightforest_jj_cube_talisman={hasPattern=false,label="",recipe={}},
 twilightforest_jj_dark_button={hasPattern=false,label="",recipe={}},
 twilightforest_jj_dark_door={hasPattern=false,label="",recipe={}},
 twilightforest_jj_dark_fence={hasPattern=false,label="",recipe={}},
 twilightforest_jj_dark_gate={hasPattern=false,label="",recipe={}},
 twilightforest_jj_dark_leaves={hasPattern=false,label="",recipe={}},
 twilightforest_jj_dark_planks={hasPattern=false,label="",recipe={}},
 twilightforest_jj_dark_plate={hasPattern=false,label="",recipe={}},
 twilightforest_jj_dark_slab={hasPattern=false,label="",recipe={}},
 twilightforest_jj_dark_stairs={hasPattern=false,label="",recipe={}},
 twilightforest_jj_dark_trapdoor={hasPattern=false,label="",recipe={}},
 twilightforest_jj_deadrock={hasPattern=false,label="",recipe={}},
 twilightforest_jj_deadrock_jj_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_deadrock_jj_2={hasPattern=false,label="",recipe={}},
 twilightforest_jj_ender_bow={hasPattern=false,label="",recipe={}},
 twilightforest_jj_etched_nagastone={hasPattern=false,label="",recipe={}},
 twilightforest_jj_etched_nagastone_mossy={hasPattern=false,label="",recipe={}},
 twilightforest_jj_etched_nagastone_weathered={hasPattern=false,label="",recipe={}},
 twilightforest_jj_experiment_115={hasPattern=false,label="",recipe={}},
 twilightforest_jj_fiery_blood={hasPattern=false,label="",recipe={}},
 twilightforest_jj_fiery_boots={hasPattern=true,label="Feuerstiefel",recipe={twilightforest_jj_fiery_ingot={need=4,tag={}}}},
 twilightforest_jj_fiery_chestplate={hasPattern=true,label="Feuerharnisch",recipe={twilightforest_jj_fiery_ingot={need=8,tag={}}}},
 twilightforest_jj_fiery_helmet={hasPattern=true,label="Feuerhelm",recipe={twilightforest_jj_fiery_ingot={need=5,tag={}}}},
 twilightforest_jj_fiery_ingot={hasPattern=true,label="Feuerbarren",recipe={minecraft_jj_iron_ingot={need=1,tag={}},twilightforest_jj_fiery_blood={need=1,tag={}},twilightforest_jj_fiery_tears={need=1,tag={}}}},
 twilightforest_jj_fiery_leggings={hasPattern=true,label="Feuerbeinschutz",recipe={twilightforest_jj_fiery_ingot={need=7,tag={}}}},
 twilightforest_jj_fiery_pickaxe={hasPattern=true,label="Feuerspitzhacke",recipe={minecraft_jj_blaze_rod={need=2,tag={}},twilightforest_jj_fiery_ingot={need=3,tag={}}}},
 twilightforest_jj_fiery_sword={hasPattern=false,label="",recipe={}},
 twilightforest_jj_fiery_tears={hasPattern=false,label="",recipe={}},
 twilightforest_jj_fire_jet={hasPattern=false,label="",recipe={}},
 twilightforest_jj_fire_jet_jj_1={hasPattern=false,label="",recipe={minecraft_jj_redstone={need=4,tag={}},twilightforest_jj_fire_jet={need=1,tag={}},twilightforest_jj_tower_wood_jj_1={need=4,tag={}}}},
 twilightforest_jj_fire_jet_jj_3={hasPattern=false,label="",recipe={}},
 twilightforest_jj_fire_jet_jj_6={hasPattern=true,label="Eingehüllter Feuerdüse",recipe={minecraft_jj_lava_bucket={need=3,tag={}},minecraft_jj_redstone={need=3,tag={}},twilightforest_jj_fire_jet_jj_3={need=1,tag={}},twilightforest_jj_tower_wood_jj_1={need=2,tag={}}}},
 twilightforest_jj_firefly={hasPattern=false,label="",recipe={}},
 twilightforest_jj_firefly_jar={hasPattern=true,label="Leuchtkäferflasche",recipe={minecraft_jj_glass_bottle={need=1,tag={}},twilightforest_jj_firefly={need=1,tag={}}}},
 twilightforest_jj_fluffy_cloud={hasPattern=false,label="",recipe={}},
 twilightforest_jj_force_field={hasPattern=false,label="",recipe={}},
 twilightforest_jj_force_field_jj_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_force_field_jj_2={hasPattern=false,label="",recipe={}},
 twilightforest_jj_force_field_jj_3={hasPattern=false,label="",recipe={}},
 twilightforest_jj_force_field_jj_4={hasPattern=false,label="",recipe={}},
 twilightforest_jj_giant_cobblestone={hasPattern=false,label="",recipe={}},
 twilightforest_jj_giant_leaves={hasPattern=false,label="",recipe={}},
 twilightforest_jj_giant_log={hasPattern=false,label="",recipe={}},
 twilightforest_jj_giant_obsidian={hasPattern=false,label="",recipe={}},
 twilightforest_jj_giant_pickaxe={hasPattern=true,label="Spitzhacke des Riesen",recipe={twilightforest_jj_giant_cobblestone={need=3,tag={}},twilightforest_jj_giant_log={need=2,tag={}}}},
 twilightforest_jj_giant_sword={hasPattern=true,label="Schwert der Riesen",recipe={twilightforest_jj_giant_cobblestone={need=2,tag={}},twilightforest_jj_giant_log={need=1,tag={}}}},
 twilightforest_jj_glass_sword={hasPattern=false,label="",recipe={}},
 twilightforest_jj_hedge={hasPattern=false,label="",recipe={}},
 twilightforest_jj_huge_lilypad={hasPattern=false,label="",recipe={}},
 twilightforest_jj_huge_mushgloom={hasPattern=false,label="",recipe={}},
 twilightforest_jj_huge_stalk={hasPattern=false,label="",recipe={}},
 twilightforest_jj_huge_waterlily={hasPattern=false,label="",recipe={}},
 twilightforest_jj_hydra_chop={hasPattern=false,label="",recipe={}},
 twilightforest_jj_ice_bomb={hasPattern=false,label="",recipe={}},
 twilightforest_jj_ice_bow={hasPattern=false,label="",recipe={}},
 twilightforest_jj_ice_sword={hasPattern=false,label="",recipe={}},
 twilightforest_jj_iron_ladder={hasPattern=false,label="",recipe={}},
 twilightforest_jj_ironwood_axe={hasPattern=false,label="",recipe={}},
 twilightforest_jj_ironwood_boots={hasPattern=false,label="",recipe={}},
 twilightforest_jj_ironwood_chestplate={hasPattern=false,label="",recipe={}},
 twilightforest_jj_ironwood_helmet={hasPattern=false,label="",recipe={}},
 twilightforest_jj_ironwood_hoe={hasPattern=true,label="Eisenholzhacke",recipe={minecraft_jj_stick={need=2,tag={}},twilightforest_jj_ironwood_ingot={need=2,tag={}}}},
 twilightforest_jj_ironwood_ingot={hasPattern=false,label="",recipe={twilightforest_jj_block_storage={need=1,tag={}}}},
 twilightforest_jj_ironwood_leggings={hasPattern=false,label="",recipe={}},
 twilightforest_jj_ironwood_pickaxe={hasPattern=false,label="",recipe={}},
 twilightforest_jj_ironwood_raw={hasPattern=true,label="Eisenholzmaterialien",recipe={minecraft_jj_gold_nugget={need=1,tag={}},minecraft_jj_iron_ingot={need=1,tag={}},twilightforest_jj_liveroot={need=1,tag={}}}},
 twilightforest_jj_ironwood_shovel={hasPattern=false,label="",recipe={}},
 twilightforest_jj_ironwood_sword={hasPattern=false,label="",recipe={}},
 twilightforest_jj_knightmetal_axe={hasPattern=true,label="Ritterliche Axt",recipe={minecraft_jj_stick={need=2,tag={}},twilightforest_jj_knightmetal_ingot={need=3,tag={}}}},
 twilightforest_jj_knightmetal_block={hasPattern=true,label="Rittermetallblock",recipe={twilightforest_jj_knightmetal_ingot={need=9,tag={}}}},
 twilightforest_jj_knightmetal_boots={hasPattern=true,label="Ritterliche Stiefel",recipe={twilightforest_jj_knightmetal_ingot={need=4,tag={}}}},
 twilightforest_jj_knightmetal_chestplate={hasPattern=true,label="Ritterlicher Harnisch",recipe={twilightforest_jj_knightmetal_ingot={need=8,tag={}}}},
 twilightforest_jj_knightmetal_helmet={hasPattern=true,label="Ritterlicher Helm",recipe={twilightforest_jj_knightmetal_ingot={need=5,tag={}}}},
 twilightforest_jj_knightmetal_ingot={hasPattern=false,label="",recipe={twilightforest_jj_knightmetal_block={need=1,tag={}}}},
 twilightforest_jj_knightmetal_leggings={hasPattern=true,label="Ritterlicher Beinschutz",recipe={twilightforest_jj_knightmetal_ingot={need=7,tag={}}}},
 twilightforest_jj_knightmetal_pickaxe={hasPattern=true,label="Ritterliche Spitzhacke",recipe={minecraft_jj_stick={need=2,tag={}},twilightforest_jj_knightmetal_ingot={need=3,tag={}}}},
 twilightforest_jj_knightmetal_ring={hasPattern=true,label="Ritermetallkettenglied",recipe={twilightforest_jj_knightmetal_ingot={need=4,tag={}}}},
 twilightforest_jj_knightmetal_shield={hasPattern=false,label="",recipe={}},
 twilightforest_jj_knightmetal_sword={hasPattern=true,label="Ritterliches Schwert",recipe={minecraft_jj_stick={need=1,tag={}},twilightforest_jj_knightmetal_ingot={need=2,tag={}}}},
 twilightforest_jj_lamp_of_cinders={hasPattern=false,label="",recipe={}},
 twilightforest_jj_lifedrain_scepter={hasPattern=false,label="",recipe={minecraft_jj_fermented_spider_eye={need=1,tag={}},twilightforest_jj_lifedrain_scepter={need=1,tag={}}}},
 twilightforest_jj_liveroot={hasPattern=false,label="",recipe={}},
 twilightforest_jj_magic_beans={hasPattern=false,label="",recipe={}},
 twilightforest_jj_magic_leaves={hasPattern=false,label="",recipe={}},
 twilightforest_jj_magic_leaves_jj_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_magic_leaves_jj_2={hasPattern=false,label="",recipe={}},
 twilightforest_jj_magic_leaves_jj_3={hasPattern=false,label="",recipe={}},
 twilightforest_jj_magic_log={hasPattern=false,label="",recipe={}},
 twilightforest_jj_magic_log_core={hasPattern=false,label="",recipe={}},
 twilightforest_jj_magic_log_core_jj_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_magic_log_core_jj_2={hasPattern=false,label="",recipe={}},
 twilightforest_jj_magic_log_core_jj_3={hasPattern=false,label="",recipe={}},
 twilightforest_jj_magic_log_jj_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_magic_log_jj_2={hasPattern=false,label="",recipe={}},
 twilightforest_jj_magic_log_jj_3={hasPattern=false,label="",recipe={}},
 twilightforest_jj_magic_map={hasPattern=false,label="",recipe={}},
 twilightforest_jj_magic_map_empty={hasPattern=true,label="Leere magische Karte",recipe={minecraft_jj_paper={need=8,tag={}},twilightforest_jj_magic_map_focus={need=1,tag={}}}},
 twilightforest_jj_magic_map_focus={hasPattern=true,label="Magischer Kartenfokus",recipe={minecraft_jj_glowstone_dust={need=1,tag={}},twilightforest_jj_raven_feather={need=1,tag={}},twilightforest_jj_torchberries={need=1,tag={}}}},
 twilightforest_jj_mangrove_button={hasPattern=false,label="",recipe={}},
 twilightforest_jj_mangrove_door={hasPattern=false,label="",recipe={}},
 twilightforest_jj_mangrove_fence={hasPattern=false,label="",recipe={}},
 twilightforest_jj_mangrove_gate={hasPattern=false,label="",recipe={}},
 twilightforest_jj_mangrove_planks={hasPattern=false,label="",recipe={}},
 twilightforest_jj_mangrove_plate={hasPattern=false,label="",recipe={}},
 twilightforest_jj_mangrove_slab={hasPattern=false,label="",recipe={}},
 twilightforest_jj_mangrove_stairs={hasPattern=false,label="",recipe={}},
 twilightforest_jj_mangrove_trapdoor={hasPattern=false,label="",recipe={}},
 twilightforest_jj_maze_map={hasPattern=false,label="",recipe={}},
 twilightforest_jj_maze_map_empty={hasPattern=true,label="Leere Labyrinthkarte",recipe={minecraft_jj_paper={need=8,tag={}},twilightforest_jj_maze_map_focus={need=1,tag={}}}},
 twilightforest_jj_maze_map_focus={hasPattern=false,label="",recipe={}},
 twilightforest_jj_maze_stone={hasPattern=false,label="",recipe={}},
 twilightforest_jj_maze_stone_jj_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_maze_stone_jj_2={hasPattern=false,label="",recipe={}},
 twilightforest_jj_maze_stone_jj_3={hasPattern=false,label="",recipe={}},
 twilightforest_jj_maze_stone_jj_4={hasPattern=false,label="",recipe={}},
 twilightforest_jj_maze_stone_jj_5={hasPattern=false,label="",recipe={}},
 twilightforest_jj_maze_stone_jj_6={hasPattern=false,label="",recipe={}},
 twilightforest_jj_maze_stone_jj_7={hasPattern=false,label="",recipe={}},
 twilightforest_jj_maze_wafer={hasPattern=false,label="",recipe={}},
 twilightforest_jj_mazebreaker_pickaxe={hasPattern=false,label="",recipe={}},
 twilightforest_jj_meef_stroganoff={hasPattern=false,label="",recipe={}},
 twilightforest_jj_mine_button={hasPattern=false,label="",recipe={}},
 twilightforest_jj_mine_door={hasPattern=false,label="",recipe={}},
 twilightforest_jj_mine_fence={hasPattern=false,label="",recipe={}},
 twilightforest_jj_mine_gate={hasPattern=false,label="",recipe={}},
 twilightforest_jj_mine_planks={hasPattern=false,label="",recipe={}},
 twilightforest_jj_mine_plate={hasPattern=false,label="",recipe={}},
 twilightforest_jj_mine_slab={hasPattern=false,label="",recipe={}},
 twilightforest_jj_mine_stairs={hasPattern=false,label="",recipe={}},
 twilightforest_jj_mine_trapdoor={hasPattern=false,label="",recipe={}},
 twilightforest_jj_miniature_structure={hasPattern=false,label="",recipe={}},
 twilightforest_jj_miniature_structure_jj_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_miniature_structure_jj_10={hasPattern=false,label="",recipe={}},
 twilightforest_jj_miniature_structure_jj_11={hasPattern=false,label="",recipe={}},
 twilightforest_jj_miniature_structure_jj_12={hasPattern=false,label="",recipe={}},
 twilightforest_jj_miniature_structure_jj_13={hasPattern=false,label="",recipe={}},
 twilightforest_jj_miniature_structure_jj_14={hasPattern=false,label="",recipe={}},
 twilightforest_jj_miniature_structure_jj_2={hasPattern=false,label="",recipe={}},
 twilightforest_jj_miniature_structure_jj_3={hasPattern=false,label="",recipe={}},
 twilightforest_jj_miniature_structure_jj_4={hasPattern=false,label="",recipe={}},
 twilightforest_jj_miniature_structure_jj_5={hasPattern=false,label="",recipe={}},
 twilightforest_jj_miniature_structure_jj_6={hasPattern=false,label="",recipe={}},
 twilightforest_jj_miniature_structure_jj_7={hasPattern=false,label="",recipe={}},
 twilightforest_jj_miniature_structure_jj_8={hasPattern=false,label="",recipe={}},
 twilightforest_jj_miniature_structure_jj_9={hasPattern=false,label="",recipe={}},
 twilightforest_jj_minotaur_axe={hasPattern=false,label="",recipe={}},
 twilightforest_jj_minotaur_axe_gold={hasPattern=false,label="",recipe={}},
 twilightforest_jj_moon_dial={hasPattern=false,label="",recipe={}},
 twilightforest_jj_moonworm={hasPattern=false,label="",recipe={}},
 twilightforest_jj_moonworm_queen={hasPattern=false,label="",recipe={twilightforest_jj_moonworm_queen={need=1,tag={}},twilightforest_jj_torchberries={need=3,tag={}}}},
 twilightforest_jj_naga_chestplate={hasPattern=false,label="",recipe={}},
 twilightforest_jj_naga_leggings={hasPattern=false,label="",recipe={}},
 twilightforest_jj_naga_scale={hasPattern=false,label="",recipe={}},
 twilightforest_jj_naga_stone={hasPattern=false,label="",recipe={}},
 twilightforest_jj_naga_stone_jj_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_nagastone_pillar={hasPattern=false,label="",recipe={}},
 twilightforest_jj_nagastone_pillar_mossy={hasPattern=false,label="",recipe={}},
 twilightforest_jj_nagastone_pillar_weathered={hasPattern=false,label="",recipe={}},
 twilightforest_jj_nagastone_stairs={hasPattern=false,label="",recipe={}},
 twilightforest_jj_nagastone_stairs_jj_8={hasPattern=false,label="",recipe={}},
 twilightforest_jj_nagastone_stairs_mossy={hasPattern=false,label="",recipe={}},
 twilightforest_jj_nagastone_stairs_mossy_jj_8={hasPattern=false,label="",recipe={}},
 twilightforest_jj_nagastone_stairs_weathered={hasPattern=false,label="",recipe={}},
 twilightforest_jj_nagastone_stairs_weathered_jj_8={hasPattern=false,label="",recipe={}},
 twilightforest_jj_ore_magnet={hasPattern=false,label="",recipe={}},
 twilightforest_jj_ore_map={hasPattern=false,label="",recipe={}},
 twilightforest_jj_ore_map_empty={hasPattern=true,label="Leere Labyrinth-Erzkarte",recipe={minecraft_jj_diamond_block={need=1,tag={}},minecraft_jj_gold_block={need=1,tag={}},minecraft_jj_iron_block={need=1,tag={}},twilightforest_jj_maze_map_empty={need=1,tag={}}}},
 twilightforest_jj_ore_meter={hasPattern=false,label="",recipe={}},
 twilightforest_jj_peacock_fan={hasPattern=false,label="",recipe={}},
 twilightforest_jj_phantom_chestplate={hasPattern=false,label="",recipe={}},
 twilightforest_jj_phantom_helmet={hasPattern=false,label="",recipe={}},
 twilightforest_jj_raven_feather={hasPattern=false,label="",recipe={}},
 twilightforest_jj_raw_meef={hasPattern=false,label="",recipe={}},
 twilightforest_jj_raw_venison={hasPattern=false,label="",recipe={}},
 twilightforest_jj_root={hasPattern=false,label="",recipe={}},
 twilightforest_jj_root_jj_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_seeker_bow={hasPattern=false,label="",recipe={}},
 twilightforest_jj_shader={hasPattern=false,label="",recipe={}},
 twilightforest_jj_shader_bag={hasPattern=false,label="",recipe={}},
 twilightforest_jj_shield_scepter={hasPattern=false,label="",recipe={}},
 twilightforest_jj_slider={hasPattern=false,label="",recipe={}},
 twilightforest_jj_slider_jj_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_slider_jj_2={hasPattern=false,label="",recipe={}},
 twilightforest_jj_slider_jj_3={hasPattern=false,label="",recipe={}},
 twilightforest_jj_sort_button={hasPattern=false,label="",recipe={}},
 twilightforest_jj_sort_door={hasPattern=false,label="",recipe={}},
 twilightforest_jj_sort_fence={hasPattern=false,label="",recipe={}},
 twilightforest_jj_sort_gate={hasPattern=false,label="",recipe={}},
 twilightforest_jj_sort_planks={hasPattern=false,label="",recipe={}},
 twilightforest_jj_sort_plate={hasPattern=false,label="",recipe={}},
 twilightforest_jj_sort_slab={hasPattern=false,label="",recipe={}},
 twilightforest_jj_sort_stairs={hasPattern=false,label="",recipe={}},
 twilightforest_jj_sort_trapdoor={hasPattern=false,label="",recipe={}},
 twilightforest_jj_spiral_bricks={hasPattern=false,label="",recipe={}},
 twilightforest_jj_steeleaf_axe={hasPattern=false,label="",recipe={}},
 twilightforest_jj_steeleaf_boots={hasPattern=false,label="",recipe={}},
 twilightforest_jj_steeleaf_chestplate={hasPattern=false,label="",recipe={}},
 twilightforest_jj_steeleaf_helmet={hasPattern=false,label="",recipe={}},
 twilightforest_jj_steeleaf_hoe={hasPattern=true,label="Stahlblatthacke",recipe={minecraft_jj_stick={need=2,tag={}},twilightforest_jj_steeleaf_ingot={need=2,tag={}}}},
 twilightforest_jj_steeleaf_ingot={hasPattern=false,label="",recipe={mysticalagriculture_jj_steeleaf_essence={need=8,tag={}}}},
 twilightforest_jj_steeleaf_leggings={hasPattern=false,label="",recipe={}},
 twilightforest_jj_steeleaf_pickaxe={hasPattern=false,label="",recipe={}},
 twilightforest_jj_steeleaf_shovel={hasPattern=false,label="",recipe={}},
 twilightforest_jj_steeleaf_sword={hasPattern=false,label="",recipe={}},
 twilightforest_jj_stone_twist={hasPattern=false,label="",recipe={}},
 twilightforest_jj_stone_twist_thin={hasPattern=false,label="",recipe={}},
 twilightforest_jj_stronghold_shield={hasPattern=false,label="",recipe={}},
 twilightforest_jj_terrorcotta_circle={hasPattern=false,label="",recipe={}},
 twilightforest_jj_terrorcotta_diagonal={hasPattern=false,label="",recipe={}},
 twilightforest_jj_thorn_rose={hasPattern=false,label="",recipe={}},
 twilightforest_jj_thorns={hasPattern=false,label="",recipe={}},
 twilightforest_jj_thorns_jj_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_time_button={hasPattern=false,label="",recipe={}},
 twilightforest_jj_time_door={hasPattern=false,label="",recipe={}},
 twilightforest_jj_time_fence={hasPattern=false,label="",recipe={}},
 twilightforest_jj_time_gate={hasPattern=false,label="",recipe={}},
 twilightforest_jj_time_planks={hasPattern=false,label="",recipe={}},
 twilightforest_jj_time_plate={hasPattern=false,label="",recipe={}},
 twilightforest_jj_time_slab={hasPattern=false,label="",recipe={}},
 twilightforest_jj_time_stairs={hasPattern=false,label="",recipe={}},
 twilightforest_jj_time_trapdoor={hasPattern=false,label="",recipe={}},
 twilightforest_jj_torchberries={hasPattern=false,label="",recipe={}},
 twilightforest_jj_tower_device={hasPattern=true,label="Wiedererscheinender Block",recipe={minecraft_jj_redstone={need=4,tag={}},twilightforest_jj_carminite={need=1,tag={}},twilightforest_jj_tower_wood_jj_1={need=4,tag={}}}},
 twilightforest_jj_tower_device_jj_10={hasPattern=false,label="",recipe={}},
 twilightforest_jj_tower_device_jj_12={hasPattern=true,label="Karminit-Reaktor",recipe={minecraft_jj_redstone_ore={need=1,tag={}},twilightforest_jj_carminite={need=4,tag={}},twilightforest_jj_tower_wood_jj_1={need=4,tag={}}}},
 twilightforest_jj_tower_device_jj_2={hasPattern=true,label="Verschwindender Block",recipe={twilightforest_jj_carminite={need=1,tag={}},twilightforest_jj_tower_wood={need=4,tag={}},twilightforest_jj_tower_wood_jj_1={need=4,tag={}}}},
 twilightforest_jj_tower_device_jj_4={hasPattern=false,label="",recipe={}},
 twilightforest_jj_tower_device_jj_5={hasPattern=false,label="",recipe={}},
 twilightforest_jj_tower_device_jj_6={hasPattern=true,label="Turmbauer",recipe={minecraft_jj_dispenser={need=1,tag={}},twilightforest_jj_carminite={need=4,tag={}},twilightforest_jj_tower_wood_jj_1={need=4,tag={}}}},
 twilightforest_jj_tower_device_jj_9={hasPattern=false,label="",recipe={}},
 twilightforest_jj_tower_key={hasPattern=false,label="",recipe={}},
 twilightforest_jj_tower_translucent={hasPattern=false,label="",recipe={}},
 twilightforest_jj_tower_wood={hasPattern=true,label="Turmholzbretter",recipe={twilightforest_jj_twilight_log_jj_3={need=4,tag={}}}},
 twilightforest_jj_tower_wood_jj_1={hasPattern=true,label="Eingehülltes Turmholz",recipe={twilightforest_jj_tower_wood={need=3,tag={}}}},
 twilightforest_jj_tower_wood_jj_2={hasPattern=false,label="",recipe={}},
 twilightforest_jj_tower_wood_jj_3={hasPattern=false,label="",recipe={}},
 twilightforest_jj_tower_wood_jj_4={hasPattern=false,label="",recipe={}},
 twilightforest_jj_trans_button={hasPattern=false,label="",recipe={}},
 twilightforest_jj_trans_door={hasPattern=false,label="",recipe={}},
 twilightforest_jj_trans_fence={hasPattern=false,label="",recipe={}},
 twilightforest_jj_trans_gate={hasPattern=false,label="",recipe={}},
 twilightforest_jj_trans_planks={hasPattern=false,label="",recipe={}},
 twilightforest_jj_trans_plate={hasPattern=false,label="",recipe={}},
 twilightforest_jj_trans_slab={hasPattern=false,label="",recipe={}},
 twilightforest_jj_trans_stairs={hasPattern=false,label="",recipe={}},
 twilightforest_jj_trans_trapdoor={hasPattern=false,label="",recipe={}},
 twilightforest_jj_transformation_powder={hasPattern=false,label="",recipe={}},
 twilightforest_jj_triple_bow={hasPattern=false,label="",recipe={}},
 twilightforest_jj_trollber={hasPattern=false,label="",recipe={}},
 twilightforest_jj_trollsteinn={hasPattern=false,label="",recipe={}},
 twilightforest_jj_trollvidr={hasPattern=false,label="",recipe={}},
 twilightforest_jj_trophy={hasPattern=false,label="",recipe={}},
 twilightforest_jj_trophy_jj_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_trophy_jj_2={hasPattern=false,label="",recipe={}},
 twilightforest_jj_trophy_jj_3={hasPattern=false,label="",recipe={}},
 twilightforest_jj_trophy_jj_4={hasPattern=false,label="",recipe={}},
 twilightforest_jj_trophy_jj_5={hasPattern=false,label="",recipe={}},
 twilightforest_jj_trophy_jj_6={hasPattern=false,label="",recipe={}},
 twilightforest_jj_trophy_jj_8={hasPattern=false,label="",recipe={}},
 twilightforest_jj_trophy_pedestal={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_leaves={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_leaves_3={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_leaves_3_jj_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_leaves_jj_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_leaves_jj_2={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_leaves_jj_3={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_log={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_log_jj_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_log_jj_2={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_log_jj_3={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_oak_button={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_oak_door={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_oak_fence={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_oak_gate={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_oak_planks={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_oak_plate={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_oak_slab={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_oak_stairs={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_oak_trapdoor={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_plant={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_plant_jj_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_plant_jj_2={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_plant_jj_3={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_plant_jj_4={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_plant_jj_5={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_plant_jj_6={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_plant_jj_7={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_plant_jj_8={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_plant_jj_9={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_sapling={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_sapling_jj_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_sapling_jj_2={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_sapling_jj_3={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_sapling_jj_4={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_sapling_jj_5={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_sapling_jj_6={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_sapling_jj_7={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_sapling_jj_8={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_sapling_jj_9={hasPattern=false,label="",recipe={}},
 twilightforest_jj_twilight_scepter={hasPattern=false,label="",recipe={minecraft_jj_ender_pearl={need=1,tag={}},twilightforest_jj_twilight_scepter={need=1,tag={}}}},
 twilightforest_jj_uberous_soil={hasPattern=false,label="",recipe={}},
 twilightforest_jj_uncrafting_table={hasPattern=true,label="Zerlegbank",recipe={minecraft_jj_crafting_table={need=8,tag={}},twilightforest_jj_maze_map_focus={need=1,tag={}}}},
 twilightforest_jj_underbrick={hasPattern=false,label="",recipe={}},
 twilightforest_jj_underbrick_jj_1={hasPattern=false,label="",recipe={}},
 twilightforest_jj_underbrick_jj_2={hasPattern=false,label="",recipe={}},
 twilightforest_jj_underbrick_jj_3={hasPattern=false,label="",recipe={}},
 twilightforest_jj_unripe_trollber={hasPattern=false,label="",recipe={}},
 twilightforest_jj_wispy_cloud={hasPattern=false,label="",recipe={}},
 twilightforest_jj_yeti_boots={hasPattern=false,label="",recipe={}},
 twilightforest_jj_yeti_chestplate={hasPattern=false,label="",recipe={}},
 twilightforest_jj_yeti_helmet={hasPattern=false,label="",recipe={}},
 twilightforest_jj_yeti_leggings={hasPattern=false,label="",recipe={}},
 twilightforest_jj_zombie_scepter={hasPattern=true,label="Zombiezepter",recipe={minecraft_jj_potion={need=1,tag={}},minecraft_jj_rotten_flesh={need=1,tag={}},twilightforest_jj_zombie_scepter={need=1,tag={}}}},
 uniquecrops_jj_3dglasses={hasPattern=true,label="3D Glasses",recipe={minecraft_jj_iron_ingot={need=4,tag={}},minecraft_jj_stained_glass_pane_jj_11={need=1,tag={}},minecraft_jj_stained_glass_pane_jj_14={need=1,tag={}},minecraft_jj_wool={need=1,tag={}}}},
 uniquecrops_jj_abstractbarrel={hasPattern=true,label="Abstract Barrel",recipe={minecraft_jj_chest={need=1,tag={}},uniquecrops_jj_generic_jj_22={need=8,tag={}}}},
 uniquecrops_jj_ankh={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_batstaff={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_beanpower={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_boiled_milk={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_bookmultiblock={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_bootsleague={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_brassknuckles={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_bucketrope={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_cactusboots={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_cactushelm={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_cactuslegs={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_cactusplate={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_cocito={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_darkblock={hasPattern=true,label="Dark Block",recipe={minecraft_jj_dye={need=4,tag={}},minecraft_jj_stone={need=1,tag={}}}},
 uniquecrops_jj_democord={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_diamonds={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_driedthatch={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_ediblemetal_vv_diamond={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_ediblemetal_vv_emerald={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_ediblemetal_vv_goldingot={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_ediblemetal_vv_goldnugget={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_ediblemetal_vv_ironingot={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_ediblemetal_vv_lapis={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_eggbasket={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_emblem_vv_blacksmith={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_emblem_vv_bookworm={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_emblem_vv_defense={hasPattern=true,label="Emblem of the Cobalt Shield",recipe={minecraft_jj_arrow={need=4,tag={}},minecraft_jj_bow={need=2,tag={}},minecraft_jj_shield={need=2,tag={}},uniquecrops_jj_darkblock={need=1,tag={}}}},
 uniquecrops_jj_emblem_vv_food={hasPattern=false,label="",recipe={minecraft_jj_potato={need=8,tag={}},uniquecrops_jj_darkblock={need=1,tag={}}}},
 uniquecrops_jj_emblem_vv_ironstomach={hasPattern=true,label="Cast-Iron Stomach Emblem",recipe={minecraft_jj_cooked_beef={need=1,tag={}},minecraft_jj_cooked_chicken={need=1,tag={}},minecraft_jj_cooked_porkchop={need=1,tag={}},minecraft_jj_cooked_rabbit={need=1,tag={}},minecraft_jj_diamond={need=1,tag={}},minecraft_jj_emerald={need=1,tag={}},minecraft_jj_gold_ingot={need=1,tag={}},minecraft_jj_iron_ingot={need=1,tag={}},uniquecrops_jj_darkblock={need=1,tag={}}}},
 uniquecrops_jj_emblem_vv_leaf={hasPattern=true,label="Leaf Badge",recipe={minecraft_jj_leaves={need=4,tag={}},minecraft_jj_log={need=4,tag={}},uniquecrops_jj_darkblock={need=1,tag={}}}},
 uniquecrops_jj_emblem_vv_melee={hasPattern=true,label="Melee Emblem",recipe={minecraft_jj_diamond_sword={need=1,tag={}},minecraft_jj_golden_sword={need=1,tag={}},minecraft_jj_iron_sword={need=1,tag={}},minecraft_jj_wooden_sword={need=1,tag={}},uniquecrops_jj_darkblock={need=1,tag={}}}},
 uniquecrops_jj_emblem_vv_pacifism={hasPattern=false,label="",recipe={uniquecrops_jj_emblem_vv_defense={need=1,tag={}},uniquecrops_jj_emblem_vv_food={need=1,tag={}},uniquecrops_jj_emblem_vv_ironstomach={need=1,tag={}},uniquecrops_jj_emblem_vv_leaf={need=1,tag={}},uniquecrops_jj_emblem_vv_melee={need=1,tag={}},uniquecrops_jj_emblem_vv_powerfist={need=1,tag={}},uniquecrops_jj_emblem_vv_rainbow={need=1,tag={}},uniquecrops_jj_emblem_vv_scarab={need=1,tag={}},uniquecrops_jj_emblem_vv_transformation={need=1,tag={}}}},
 uniquecrops_jj_emblem_vv_powerfist={hasPattern=true,label="Mighty Miner Emblem",recipe={minecraft_jj_blaze_powder={need=1,tag={}},minecraft_jj_blaze_rod={need=2,tag={}},minecraft_jj_diamond_pickaxe={need=1,tag={}},uniquecrops_jj_darkblock={need=1,tag={}}}},
 uniquecrops_jj_emblem_vv_rainbow={hasPattern=false,label="",recipe={minecraft_jj_wool={need=1,tag={}},minecraft_jj_wool_jj_10={need=1,tag={}},minecraft_jj_wool_jj_11={need=1,tag={}},minecraft_jj_wool_jj_12={need=1,tag={}},minecraft_jj_wool_jj_13={need=1,tag={}},minecraft_jj_wool_jj_14={need=1,tag={}},minecraft_jj_wool_jj_15={need=1,tag={}},minecraft_jj_wool_jj_4={need=1,tag={}},uniquecrops_jj_darkblock={need=1,tag={}}}},
 uniquecrops_jj_emblem_vv_scarab={hasPattern=true,label="Emblem of the Golden Scarab",recipe={minecraft_jj_gold_block={need=4,tag={}},minecraft_jj_gold_ingot={need=4,tag={}},uniquecrops_jj_darkblock={need=1,tag={}}}},
 uniquecrops_jj_emblem_vv_transformation={hasPattern=true,label="Emblem of Transformation",recipe={minecraft_jj_feather={need=3,tag={}},uniquecrops_jj_darkblock={need=1,tag={}},uniquecrops_jj_generic_jj_13={need=1,tag={}}}},
 uniquecrops_jj_emblem_vv_weight={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_emeradic_diamond={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_enderlily={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_endersnooker={hasPattern=true,label="Ender Snooker",recipe={minecraft_jj_ender_pearl={need=4,tag={}},minecraft_jj_stick={need=1,tag={}},uniquecrops_jj_generic_jj_5={need=4,tag={}}}},
 uniquecrops_jj_flywood_leaves={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_flywood_log={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_flywood_plank={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_flywood_sapling={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_generic={hasPattern=true,label="Guide to Unique Crops",recipe={minecraft_jj_book={need=1,tag={}},minecraft_jj_melon_seeds={need=1,tag={}},minecraft_jj_pumpkin_seeds={need=1,tag={}},minecraft_jj_wheat_seeds={need=1,tag={}},uniquecrops_jj_seednormal={need=1,tag={}}}},
 uniquecrops_jj_generic_jj_1={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_generic_jj_10={hasPattern=true,label="Time Meal",recipe={minecraft_jj_clock={need=1,tag={}},minecraft_jj_dye_jj_15={need=4,tag={}}}},
 uniquecrops_jj_generic_jj_11={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_generic_jj_12={hasPattern=true,label="Invisibilia Feather",recipe={minecraft_jj_feather={need=1,tag={}},uniquecrops_jj_generic_jj_11={need=8,tag={}}}},
 uniquecrops_jj_generic_jj_13={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_generic_jj_14={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_generic_jj_15={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_generic_jj_16={hasPattern=true,label="Weeping Eye",recipe={minecraft_jj_ender_eye={need=1,tag={}},uniquecrops_jj_generic_jj_15={need=8,tag={}}}},
 uniquecrops_jj_generic_jj_17={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_generic_jj_18={hasPattern=true,label="Upgrade Book",recipe={uniquecrops_jj_generic_jj_1={need=1,tag={}},uniquecrops_jj_generic_jj_12={need=4,tag={}}}},
 uniquecrops_jj_generic_jj_19={hasPattern=true,label="Egg Upgrade",recipe={minecraft_jj_egg={need=4,tag={}},minecraft_jj_iron_ingot={need=4,tag={}},uniquecrops_jj_generic_jj_17={need=1,tag={}}}},
 uniquecrops_jj_generic_jj_2={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_generic_jj_20={hasPattern=true,label="Easy Badge",recipe={minecraft_jj_gold_ingot={need=4,tag={}},minecraft_jj_quartz_block={need=1,tag={}},uniquecrops_jj_generic_jj_17={need=4,tag={}}}},
 uniquecrops_jj_generic_jj_21={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_generic_jj_22={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_generic_jj_23={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_generic_jj_24={hasPattern=false,label="",recipe={minecraft_jj_book={need=1,tag={}},uniquecrops_jj_generic_jj_23={need=4,tag={}}}},
 uniquecrops_jj_generic_jj_26={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_generic_jj_27={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_generic_jj_28={hasPattern=true,label="Escape Rope",recipe={uniquecrops_jj_generic_jj_11={need=3,tag={}},uniquecrops_jj_generic_jj_5={need=3,tag={}}}},
 uniquecrops_jj_generic_jj_29={hasPattern=true,label="Sundial",recipe={minecraft_jj_cobblestone={need=4,tag={}},minecraft_jj_redstone={need=2,tag={}}}},
 uniquecrops_jj_generic_jj_3={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_generic_jj_30={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_generic_jj_31={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_generic_jj_32={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_generic_jj_4={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_generic_jj_5={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_generic_jj_6={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_generic_jj_7={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_generic_jj_8={hasPattern=true,label="Precision Gem",recipe={minecraft_jj_diamond={need=1,tag={}},uniquecrops_jj_generic_jj_7={need=4,tag={}}}},
 uniquecrops_jj_generic_jj_9={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_genericfood_vv_dietpills={hasPattern=true,label="Diet Pills",recipe={minecraft_jj_glass_bottle={need=1,tag={}},uniquecrops_jj_generic_jj_22={need=2,tag={}}}},
 uniquecrops_jj_genericfood_vv_eggnog={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_genericfood_vv_ennuipotion={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_genericfood_vv_goldenbread={hasPattern=true,label="Golden Bread",recipe={uniquecrops_jj_generic_jj_6={need=3,tag={}}}},
 uniquecrops_jj_genericfood_vv_heart={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_genericfood_vv_largeplum={hasPattern=true,label="Large Dirible Plum",recipe={uniquecrops_jj_generic_jj_2={need=9,tag={}}}},
 uniquecrops_jj_genericfood_vv_reversepotion={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_genericfood_vv_teriyaki={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_genericfood_vv_waffle={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_genericfood_vv_yogurt={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_goblet={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_goodiebag={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_handmirror={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_harvesttrap={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_hourglass={hasPattern=true,label="Hourglass of Nostalgia",recipe={minecraft_jj_glass_pane={need=2,tag={}},minecraft_jj_gold_block={need=2,tag={}},uniquecrops_jj_generic_jj_4={need=5,tag={}}}},
 uniquecrops_jj_icelily={hasPattern=true,label="Ice Lily",recipe={minecraft_jj_packed_ice={need=4,tag={}},minecraft_jj_waterlily={need=1,tag={}}}},
 uniquecrops_jj_impactshield={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_impregnated_leather={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_impregnated_leather_jj_1={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_invisiglass={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_item_magnet={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_junglelily={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_lavalily={hasPattern=true,label="Lava Lily",recipe={minecraft_jj_waterlily={need=1,tag={}},uniquecrops_jj_generic_jj_3={need=4,tag={}}}},
 uniquecrops_jj_mirror={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_normiecrate={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_oldbrick={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_oldcobble={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_oldcobblemoss={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_oldgrass={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_oldgravel={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_pixelbrush={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_pixelbrush_jj_131={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_pixelglasses={hasPattern=true,label="Pixel Glasses",recipe={uniquecrops_jj_3dglasses={need=1,tag={}},uniquecrops_jj_generic_jj_26={need=8,tag={}}}},
 uniquecrops_jj_poncho={hasPattern=true,label="Comfy Poncho",recipe={uniquecrops_jj_generic_jj_12={need=8,tag={}}}},
 uniquecrops_jj_precision_vv_axe={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_precision_vv_hammer={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_precision_vv_pick={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_precision_vv_shovel={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_precision_vv_sword={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_record_vv_faraway={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_record_vv_neonsigns={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_record_vv_simply={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_record_vv_taxi={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_rubikscube={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_ruinedbricks={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_ruinedbrickscarved={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_ruinedbricksghost={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_ruinedbricksred={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedabstract={hasPattern=false,label="",recipe={uniquecrops_jj_generic_jj_22={need=1,tag={}}}},
 uniquecrops_jj_seedadventus={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedartisia={hasPattern=true,label="Artisia Seeds",recipe={minecraft_jj_crafting_table={need=1,tag={}},uniquecrops_jj_seednormal={need=4,tag={}}}},
 uniquecrops_jj_seedblessed={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedcinderbella={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedcobblonia={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedcollis={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seeddevilsnare={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seeddirigible={hasPattern=true,label="Dirigible Plum Seeds",recipe={uniquecrops_jj_genericfood_vv_largeplum={need=1,tag={}}}},
 uniquecrops_jj_seeddonutsteel={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seeddyeius={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedenderlily={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedeula={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedferoxia={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedhexis={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedimperia={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedindustria={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedinstabilis={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedinvisibilia={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedknowledge={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedlacusia={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedmagnes={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedmalleatoris={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedmaryjane={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedmerlinia={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedmillennium={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedmusica={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seednormal={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedpetramia={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedpixelsius={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedprecision={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedquarry={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedsucco={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedwafflonia={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_seedweepingbells={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_slippers={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_steel_donut={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_sunblock={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_thunderpantz={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_totemhead={hasPattern=true,label="Totem of Sneaky Mobs",recipe={minecraft_jj_lapis_block={need=5,tag={}},minecraft_jj_stick={need=1,tag={}},uniquecrops_jj_generic_jj_17={need=1,tag={}}}},
 uniquecrops_jj_useless_lump={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_vampiric_ointment={hasPattern=false,label="",recipe={}},
 uniquecrops_jj_wildwood_staff={hasPattern=false,label="",recipe={}}
 }