return {
 animus_jj_altardiviner={hasPattern=false,label="",recipe={}},
 animus_jj_blockantimatter={hasPattern=false,label="",recipe={}},
 animus_jj_blockbloodcore={hasPattern=false,label="",recipe={}},
 animus_jj_blockbloodsapling={hasPattern=false,label="",recipe={}},
 animus_jj_blockbloodwood={hasPattern=false,label="",recipe={}},
 animus_jj_bloodapple={hasPattern=false,label="",recipe={}},
 animus_jj_component={hasPattern=false,label="",recipe={}},
 animus_jj_component_jj_1={hasPattern=false,label="",recipe={}},
 animus_jj_component_jj_2={hasPattern=false,label="",recipe={}},
 animus_jj_component_jj_3={hasPattern=false,label="",recipe={}},
 animus_jj_component_jj_4={hasPattern=false,label="",recipe={}},
 animus_jj_component_jj_5={hasPattern=false,label="",recipe={}},
 animus_jj_fragmenthealing={hasPattern=false,label="",recipe={}},
 animus_jj_kama_bound={hasPattern=false,label="",recipe={}},
 animus_jj_kama_diamond={hasPattern=false,label="",recipe={}},
 animus_jj_kama_gold={hasPattern=false,label="",recipe={}},
 animus_jj_kama_iron={hasPattern=false,label="",recipe={}},
 animus_jj_kama_stone={hasPattern=false,label="",recipe={}},
 animus_jj_kama_wood={hasPattern=false,label="",recipe={}},
 animus_jj_keybinding={hasPattern=false,label="",recipe={}},
 animus_jj_mobsoul={hasPattern=false,label="",recipe={}},
 animus_jj_sigil_builder={hasPattern=false,label="",recipe={}},
 animus_jj_sigil_chains={hasPattern=false,label="",recipe={}},
 animus_jj_sigil_consumption={hasPattern=false,label="",recipe={}},
 animus_jj_sigil_leech={hasPattern=false,label="",recipe={}},
 animus_jj_sigil_storm={hasPattern=false,label="",recipe={}},
 animus_jj_sigil_transposition={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockaltar={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockaltar_jj_1={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockaltar_jj_2={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockaltar_jj_3={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockattunementaltar={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockattunementrelay={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockblackmarble={hasPattern=true,label="Sooty Marble",recipe={astralsorcery_jj_blockmarble={need=8,tag={}},minecraft_jj_coal={need=1,tag={}}}},
 astralsorcery_jj_blockblackmarble_jj_1={hasPattern=true,label="Sooty Marble Bricks",recipe={astralsorcery_jj_blockblackmarble={need=4,tag={}}}},
 astralsorcery_jj_blockblackmarble_jj_2={hasPattern=true,label="Sooty Marble Pillar",recipe={astralsorcery_jj_blockblackmarble={need=2,tag={}}}},
 astralsorcery_jj_blockblackmarble_jj_3={hasPattern=true,label="Sooty Marble Arch",recipe={astralsorcery_jj_blockblackmarble={need=3,tag={}}}},
 astralsorcery_jj_blockblackmarble_jj_4={hasPattern=true,label="Chiseled Sooty Marble",recipe={astralsorcery_jj_blockblackmarble={need=4,tag={}}}},
 astralsorcery_jj_blockblackmarble_jj_5={hasPattern=true,label="Engraved Sooty Marble",recipe={astralsorcery_jj_blockblackmarble={need=4,tag={}},astralsorcery_jj_blockblackmarble_jj_4={need=1,tag={}}}},
 astralsorcery_jj_blockblackmarble_jj_6={hasPattern=true,label="Runed Sooty Marble",recipe={astralsorcery_jj_blockblackmarble={need=2,tag={}},astralsorcery_jj_blockblackmarble_jj_4={need=1,tag={}}}},
 astralsorcery_jj_blockbore={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockborehead={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockborehead_jj_1={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockcelestialcollectorcrystal={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockcelestialcrystals={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockcelestialcrystals_jj_1={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockcelestialcrystals_jj_2={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockcelestialcrystals_jj_3={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockcelestialcrystals_jj_4={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockcelestialgateway={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockchalice={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockcollectorcrystal={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockcustomflower={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockcustomore={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockcustomore_jj_1={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockcustomsandore={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockfaketree={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockflarelight={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockgemcrystals={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockgemcrystals_jj_1={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockgemcrystals_jj_2={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockgemcrystals_jj_3={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockgemcrystals_jj_4={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockinfusedwood={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockinfusedwood_jj_1={hasPattern=true,label="Infused Wood Planks",recipe={astralsorcery_jj_blockinfusedwood={need=1,tag={}}}},
 astralsorcery_jj_blockinfusedwood_jj_2={hasPattern=true,label="Infused Wood Column",recipe={astralsorcery_jj_blockinfusedwood_jj_1={need=3,tag={}}}},
 astralsorcery_jj_blockinfusedwood_jj_3={hasPattern=true,label="Infused Wood Arch",recipe={astralsorcery_jj_blockinfusedwood_jj_1={need=3,tag={}}}},
 astralsorcery_jj_blockinfusedwood_jj_4={hasPattern=true,label="Engraved Infused Wood",recipe={astralsorcery_jj_blockinfusedwood_jj_1={need=4,tag={}}}},
 astralsorcery_jj_blockinfusedwood_jj_5={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockinfusedwood_jj_6={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blocklens={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockmachine={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockmachine_jj_1={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockmapdrawingtable={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockmarble={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockmarble_jj_1={hasPattern=true,label="Marble Bricks",recipe={chisel_jj_marble={need=4,tag={}}}},
 astralsorcery_jj_blockmarble_jj_2={hasPattern=true,label="Marble Pillar",recipe={astralsorcery_jj_blockmarble={need=2,tag={}}}},
 astralsorcery_jj_blockmarble_jj_3={hasPattern=true,label="Marble Arch",recipe={astralsorcery_jj_blockmarble={need=3,tag={}}}},
 astralsorcery_jj_blockmarble_jj_4={hasPattern=true,label="Chiseled Marble",recipe={astralsorcery_jj_blockmarble={need=4,tag={}}}},
 astralsorcery_jj_blockmarble_jj_5={hasPattern=true,label="Engraved Marble",recipe={astralsorcery_jj_blockmarble={need=4,tag={}},astralsorcery_jj_blockmarble_jj_4={need=1,tag={}}}},
 astralsorcery_jj_blockmarble_jj_6={hasPattern=true,label="Runed Marble",recipe={astralsorcery_jj_blockmarble={need=2,tag={}},astralsorcery_jj_blockmarble_jj_4={need=1,tag={}}}},
 astralsorcery_jj_blockmarbleslab={hasPattern=true,label="Marble Slab",recipe={astralsorcery_jj_blockmarble_jj_1={need=3,tag={}}}},
 astralsorcery_jj_blockmarblestairs={hasPattern=true,label="Marble Stairs",recipe={astralsorcery_jj_blockmarble={need=6,tag={}}}},
 astralsorcery_jj_blockobservatory={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockportalnode={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockprism={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockrituallink={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockritualpedestal={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockstarlightinfuser={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockstructural={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blocktranslucentblock={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blocktreebeacon={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockvanishing={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockwell={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_blockworldilluminator={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemarchitectwand={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemcape={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemcelestialcrystal={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemchargedcrystalaxe={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemchargedcrystalpickaxe={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemchargedcrystalshovel={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemchargedcrystalsword={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemcoloredlens={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemcoloredlens_jj_1={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemcoloredlens_jj_2={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemcoloredlens_jj_3={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemcoloredlens_jj_4={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemcoloredlens_jj_5={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemcoloredlens_jj_6={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemconstellationpaper={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemcraftingcomponent={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemcraftingcomponent_jj_1={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemcraftingcomponent_jj_2={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemcraftingcomponent_jj_3={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemcraftingcomponent_jj_4={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemcraftingcomponent_jj_5={hasPattern=true,label="Parchment",recipe={astralsorcery_jj_itemcraftingcomponent={need=1,tag={}},minecraft_jj_paper={need=4,tag={}}}},
 astralsorcery_jj_itemcrystalaxe={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemcrystalpickaxe={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemcrystalshovel={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemcrystalsword={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemenchantmentamulet={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemexchangewand={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemfragmentcapsule={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemgrapplewand={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemhandtelescope={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemilluminationwand={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_iteminfusedglass={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemjournal={hasPattern=true,label="Astral Tome",recipe={astralsorcery_jj_itemcraftingcomponent={need=3,tag={}},astralsorcery_jj_itemcraftingcomponent_jj_5={need=1,tag={}},minecraft_jj_book={need=1,tag={}}}},
 astralsorcery_jj_itemknowledgefragment={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemknowledgeshare={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemlinkingtool={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemperkgem={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemperkgem_jj_1={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemperkgem_jj_2={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemperkseal={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemrockcrystalsimple={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemsextant={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemshiftingstar={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemskyresonator={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemtunedcelestialcrystal={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemtunedrockcrystal={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemusabledust={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemusabledust_jj_1={hasPattern=false,label="",recipe={}},
 astralsorcery_jj_itemwand={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_altare_aenigmatica={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_base_item={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_base_item_jj_1={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_base_item_jj_2={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_base_item_jj_3={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_base_item_jj_4={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_base_item_jj_5={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_base_item_jj_6={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_base_item_jj_7={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_base_item_jj_8={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_base_item_jj_9={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_block_blood_burned_string={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_burned_string={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_capacitor={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_diamond={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_diamond_jj_1={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_diamond_jj_2={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_diamond_jj_3={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_infused_glowstone={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_infused_iron_axe={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_infused_iron_block={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_infused_iron_pickaxe={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_infused_iron_shovel={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_infused_iron_sickle={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_infused_iron_sword={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_infused_wooden_axe={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_infused_wooden_fence={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_infused_wooden_fence_gate={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_infused_wooden_log={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_infused_wooden_pickaxe={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_infused_wooden_planks={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_infused_wooden_shovel={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_infused_wooden_sickle={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_infused_wooden_stairs={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_infused_wooden_sword={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_orange={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_stained_glass={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_stained_glass_pane={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_blood_torch={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_bound_igniter={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_bound_shears={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_bound_sickle={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_bound_stick={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_gem={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_gem_jj_1={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_gem_jj_2={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_glass_dagger_of_sacrifice={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_glass_sacrificial_dagger={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_glass_shards={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_modifier_tome={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_sacrifice_amulet={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_self_sacrifice_amulet={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_sigil_augmented_holding={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_sigil_divinity={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_sigil_ender={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_sigil_lightning={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_sigil_sentience={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_sigil_swimming={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_slate={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_slate_jj_1={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_slate_jj_2={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_slate_jj_3={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_slate_jj_4={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_soul_pendant={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_soul_pendant_jj_1={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_soul_pendant_jj_2={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_soul_pendant_jj_3={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_soul_pendant_jj_4={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_stasis_axe={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_stasis_pickaxe={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_stasis_plate={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_stasis_shovel={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_stasis_sword={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_vampire_ring={hasPattern=false,label="",recipe={}},
 bloodarsenal_jj_warp_blade={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_activation_crystal={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_activation_crystal_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_activation_crystal_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_alchemic_vial={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_alchemy_table={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_altar={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_altar_maker={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_arcane_ashes={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_base_fluid_filter={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_base_item_filter={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_base_item_filter_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_base_item_filter_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_base_item_filter_jj_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_orb={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_rune={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_rune_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_rune_jj_10={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_rune_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_rune_jj_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_rune_jj_4={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_rune_jj_5={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_rune_jj_6={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_rune_jj_7={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_rune_jj_8={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_rune_jj_9={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_shard={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_shard_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_tank={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_tank_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_tank_jj_10={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_tank_jj_11={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_tank_jj_12={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_tank_jj_13={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_tank_jj_14={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_tank_jj_15={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_tank_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_tank_jj_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_tank_jj_4={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_tank_jj_5={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_tank_jj_6={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_tank_jj_7={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_tank_jj_8={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_blood_tank_jj_9={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_bound_axe={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_bound_pickaxe={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_bound_shovel={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_bound_sword={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_10={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_11={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_12={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_13={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_14={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_15={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_16={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_17={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_18={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_19={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_20={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_21={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_22={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_23={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_24={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_25={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_26={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_27={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_28={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_29={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_30={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_31={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_32={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_4={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_5={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_6={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_7={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_8={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_component_jj_9={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_cutting_fluid={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_cutting_fluid_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_dagger_of_sacrifice={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_decorative_brick={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_decorative_brick_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_brick_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_brick_1_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_brick_1_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_brick_1_jj_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_brick_1_jj_4={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_brick_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_brick_2_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_brick_2_jj_10={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_brick_2_jj_11={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_brick_2_jj_12={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_brick_2_jj_13={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_brick_2_jj_14={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_brick_2_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_brick_2_jj_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_brick_2_jj_4={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_brick_2_jj_5={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_brick_2_jj_6={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_brick_2_jj_7={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_brick_2_jj_8={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_brick_2_jj_9={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_crucible={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_crystal={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_crystal_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_crystal_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_crystal_jj_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_crystal_jj_4={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_crystallizer={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_extras={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_extras_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_extras_jj_10={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_extras_jj_11={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_extras_jj_12={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_extras_jj_13={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_extras_jj_14={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_extras_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_extras_jj_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_extras_jj_4={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_extras_jj_5={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_extras_jj_6={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_extras_jj_7={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_extras_jj_8={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_extras_jj_9={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_light={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_light_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_light_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_light_jj_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_light_jj_4={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_pillar_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_pillar_1_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_pillar_1_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_pillar_1_jj_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_pillar_1_jj_4={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_pillar_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_pillar_2_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_pillar_2_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_pillar_2_jj_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_pillar_2_jj_4={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_pillar_cap_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_pillar_cap_1_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_pillar_cap_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_pillar_cap_2_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_pillar_cap_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_pylon={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_stairs_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_stairs_1_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_stairs_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_stairs_2_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_stairs_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_wall_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_wall_1_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_wall_1_jj_10={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_wall_1_jj_11={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_wall_1_jj_12={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_wall_1_jj_13={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_wall_1_jj_14={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_wall_1_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_wall_1_jj_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_wall_1_jj_4={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_wall_1_jj_5={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_wall_1_jj_6={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_wall_1_jj_7={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_wall_1_jj_8={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_wall_1_jj_9={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_demon_will_gauge={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_experience_tome={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_icarus_scroll={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_incense_altar={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_input_routing_node={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_inscription_tool_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_inscription_tool_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_inscription_tool_jj_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_inscription_tool_jj_4={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_inscription_tool_jj_5={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_inversion_pillar={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_inversion_pillar_end={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_inversion_pillar_end_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_inversion_pillar_end_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_inversion_pillar_end_jj_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_inversion_pillar_end_jj_4={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_inversion_pillar_end_jj_5={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_inversion_pillar_end_jj_6={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_inversion_pillar_end_jj_7={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_inversion_pillar_end_jj_8={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_inversion_pillar_end_jj_9={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_inversion_pillar_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_inversion_pillar_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_inversion_pillar_jj_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_inversion_pillar_jj_4={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_item_demon_crystal={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_item_demon_crystal_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_item_demon_crystal_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_item_demon_crystal_jj_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_item_demon_crystal_jj_4={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_item_routing_node={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_lava_crystal={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_living_armour_boots={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_living_armour_chest={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_living_armour_helmet={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_living_armour_leggings={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_master_routing_node={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_mimic={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_mimic_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_mimic_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_mimic_jj_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_mimic_jj_4={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_monster_soul={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_monster_soul_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_monster_soul_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_monster_soul_jj_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_monster_soul_jj_4={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_node_router={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_output_routing_node={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_pack_sacrifice={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_pack_self_sacrifice={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_path={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_path_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_path_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_path_jj_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_path_jj_4={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_path_jj_5={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_path_jj_6={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_path_jj_7={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_points_upgrade={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_potion_flask={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_ritual_controller={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_ritual_controller_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_ritual_controller_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_ritual_dismantler={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_ritual_diviner={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_ritual_diviner_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_ritual_diviner_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_ritual_reader={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_ritual_stone={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_ritual_stone_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_ritual_stone_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_ritual_stone_jj_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_ritual_stone_jj_4={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_ritual_stone_jj_5={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_ritual_stone_jj_6={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sacrificial_dagger={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sacrificial_dagger_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sanguine_book={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sentient_armour_boots={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sentient_armour_chest={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sentient_armour_gem={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sentient_armour_helmet={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sentient_armour_leggings={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sentient_axe={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sentient_bow={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sentient_pickaxe={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sentient_shovel={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sentient_sword={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sigil_air={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sigil_blood_light={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sigil_bounce={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sigil_claw={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sigil_compression={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sigil_divination={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sigil_elemental_affinity={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sigil_ender_severance={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sigil_fast_miner={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sigil_frost={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sigil_green_grove={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sigil_haste={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sigil_holding={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sigil_lava={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sigil_magnetism={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sigil_phantom_bridge={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sigil_seer={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sigil_suppression={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sigil_teleposition={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sigil_transposition={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sigil_void={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sigil_water={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_sigil_whirlwind={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_slate={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_slate_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_slate_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_slate_jj_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_slate_jj_4={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_soul_forge={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_soul_gem={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_soul_gem_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_soul_gem_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_soul_gem_jj_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_soul_gem_jj_4={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_soul_snare={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_teleposer={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_teleposition_focus={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_teleposition_focus_jj_1={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_teleposition_focus_jj_2={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_teleposition_focus_jj_3={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_upgrade_tome={hasPattern=false,label="",recipe={}},
 bloodmagic_jj_upgrade_trainer={hasPattern=false,label="",recipe={}},
 bloodtinker_jj_blood_bronze_block={hasPattern=false,label="",recipe={}},
 bloodtinker_jj_blood_bronze_ingot={hasPattern=false,label="",recipe={}},
 bloodtinker_jj_bloody_thorn_ring={hasPattern=false,label="",recipe={}},
 woot_jj_anvil={hasPattern=false,label="",recipe={}},
 woot_jj_builder={hasPattern=false,label="",recipe={}},
 woot_jj_cell={hasPattern=false,label="",recipe={}},
 woot_jj_cell_jj_1={hasPattern=false,label="",recipe={}},
 woot_jj_cell_jj_2={hasPattern=false,label="",recipe={}},
 woot_jj_controller={hasPattern=false,label="",recipe={}},
 woot_jj_die={hasPattern=false,label="",recipe={}},
 woot_jj_die_jj_1={hasPattern=false,label="",recipe={}},
 woot_jj_die_jj_2={hasPattern=false,label="",recipe={}},
 woot_jj_die_jj_3={hasPattern=false,label="",recipe={}},
 woot_jj_endershard={hasPattern=false,label="",recipe={}},
 woot_jj_exporter={hasPattern=false,label="",recipe={}},
 woot_jj_factory={hasPattern=false,label="",recipe={}},
 woot_jj_factorybase={hasPattern=false,label="",recipe={}},
 woot_jj_factorycore={hasPattern=false,label="",recipe={}},
 woot_jj_factorycore_jj_1={hasPattern=false,label="",recipe={}},
 woot_jj_factorycore_jj_2={hasPattern=false,label="",recipe={}},
 woot_jj_factorycore_jj_3={hasPattern=false,label="",recipe={}},
 woot_jj_factorycore_jj_4={hasPattern=false,label="",recipe={}},
 woot_jj_factorycore_jj_5={hasPattern=false,label="",recipe={}},
 woot_jj_factorycore_jj_6={hasPattern=false,label="",recipe={}},
 woot_jj_fakemanual={hasPattern=false,label="",recipe={}},
 woot_jj_importer={hasPattern=false,label="",recipe={}},
 woot_jj_layout={hasPattern=false,label="",recipe={}},
 woot_jj_prism={hasPattern=false,label="",recipe={}},
 woot_jj_shard={hasPattern=false,label="",recipe={}},
 woot_jj_shard_jj_1={hasPattern=false,label="",recipe={}},
 woot_jj_shard_jj_2={hasPattern=false,label="",recipe={}},
 woot_jj_shard_jj_3={hasPattern=false,label="",recipe={}},
 woot_jj_shard_jj_4={hasPattern=false,label="",recipe={}},
 woot_jj_shard_jj_5={hasPattern=false,label="",recipe={}},
 woot_jj_shard_jj_6={hasPattern=false,label="",recipe={}},
 woot_jj_soulsanddust={hasPattern=false,label="",recipe={}},
 woot_jj_soulstone={hasPattern=false,label="",recipe={}},
 woot_jj_structure={hasPattern=false,label="",recipe={}},
 woot_jj_structure_jj_1={hasPattern=false,label="",recipe={}},
 woot_jj_structure_jj_2={hasPattern=false,label="",recipe={}},
 woot_jj_structure_jj_3={hasPattern=false,label="",recipe={}},
 woot_jj_structure_jj_4={hasPattern=false,label="",recipe={}},
 woot_jj_structure_jj_5={hasPattern=false,label="",recipe={}},
 woot_jj_structure_jj_6={hasPattern=false,label="",recipe={}},
 woot_jj_structure_jj_7={hasPattern=false,label="",recipe={}},
 woot_jj_structure_jj_8={hasPattern=false,label="",recipe={}},
 woot_jj_structure_jj_9={hasPattern=false,label="",recipe={}},
 woot_jj_stygianiron={hasPattern=false,label="",recipe={}},
 woot_jj_stygianirondust={hasPattern=false,label="",recipe={}},
 woot_jj_stygianironingot={hasPattern=false,label="",recipe={}},
 woot_jj_stygianironore={hasPattern=false,label="",recipe={}},
 woot_jj_stygianironplate={hasPattern=false,label="",recipe={}},
 woot_jj_upgrade={hasPattern=false,label="",recipe={}},
 woot_jj_upgrade_jj_1={hasPattern=false,label="",recipe={}},
 woot_jj_upgrade_jj_10={hasPattern=false,label="",recipe={}},
 woot_jj_upgrade_jj_11={hasPattern=false,label="",recipe={}},
 woot_jj_upgrade_jj_12={hasPattern=false,label="",recipe={}},
 woot_jj_upgrade_jj_13={hasPattern=false,label="",recipe={}},
 woot_jj_upgrade_jj_14={hasPattern=false,label="",recipe={}},
 woot_jj_upgrade_jj_2={hasPattern=false,label="",recipe={}},
 woot_jj_upgrade_jj_3={hasPattern=false,label="",recipe={}},
 woot_jj_upgrade_jj_4={hasPattern=false,label="",recipe={}},
 woot_jj_upgrade_jj_5={hasPattern=false,label="",recipe={}},
 woot_jj_upgrade_jj_6={hasPattern=false,label="",recipe={}},
 woot_jj_upgrade_jj_7={hasPattern=false,label="",recipe={}},
 woot_jj_upgrade_jj_8={hasPattern=false,label="",recipe={}},
 woot_jj_upgrade_jj_9={hasPattern=false,label="",recipe={}},
 woot_jj_upgradeb={hasPattern=false,label="",recipe={}},
 woot_jj_upgradeb_jj_1={hasPattern=false,label="",recipe={}},
 woot_jj_upgradeb_jj_10={hasPattern=false,label="",recipe={}},
 woot_jj_upgradeb_jj_11={hasPattern=false,label="",recipe={}},
 woot_jj_upgradeb_jj_12={hasPattern=false,label="",recipe={}},
 woot_jj_upgradeb_jj_13={hasPattern=false,label="",recipe={}},
 woot_jj_upgradeb_jj_14={hasPattern=false,label="",recipe={}},
 woot_jj_upgradeb_jj_2={hasPattern=false,label="",recipe={}},
 woot_jj_upgradeb_jj_3={hasPattern=false,label="",recipe={}},
 woot_jj_upgradeb_jj_4={hasPattern=false,label="",recipe={}},
 woot_jj_upgradeb_jj_5={hasPattern=false,label="",recipe={}},
 woot_jj_upgradeb_jj_6={hasPattern=false,label="",recipe={}},
 woot_jj_upgradeb_jj_7={hasPattern=false,label="",recipe={}},
 woot_jj_upgradeb_jj_8={hasPattern=false,label="",recipe={}},
 woot_jj_upgradeb_jj_9={hasPattern=false,label="",recipe={}},
 woot_jj_xpshard={hasPattern=false,label="",recipe={}},
 woot_jj_yahhammer={hasPattern=false,label="",recipe={}},
 xreliquary_jj_alkahestry_tome_jj_1001={hasPattern=false,label="",recipe={}},
 xreliquary_jj_altar={hasPattern=true,label="Altar of Light",recipe={minecraft_jj_obsidian={need=1,tag={}},minecraft_jj_redstone_lamp={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_11={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_3={need=1,tag={}}}},
 xreliquary_jj_angelheart_vial={hasPattern=true,label="Angelheart Vial",recipe={minecraft_jj_glass_pane={need=5,tag={}},minecraft_jj_milk_bucket={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_13={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_9={need=2,tag={}}}},
 xreliquary_jj_angelic_feather={hasPattern=true,label="Angelic Feather",recipe={minecraft_jj_feather={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_11={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_5={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_9={need=1,tag={}}}},
 xreliquary_jj_apothecary_cauldron={hasPattern=true,label="Apothecary Cauldron",recipe={minecraft_jj_cauldron={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_11={need=3,tag={}},xreliquary_jj_mob_ingredient_jj_13={need=2,tag={}},xreliquary_jj_mob_ingredient_jj_3={need=2,tag={}},xreliquary_jj_mob_ingredient_jj_7={need=1,tag={}}}},
 xreliquary_jj_apothecary_mortar={hasPattern=true,label="Apothecary Mortar",recipe={minecraft_jj_quartz_block={need=6,tag={}},minecraft_jj_quartz_block_jj_1={need=6,tag={}},minecraft_jj_quartz_block_jj_2={need=6,tag={}},xreliquary_jj_mob_ingredient_jj_3={need=3,tag={}}}},
 xreliquary_jj_attraction_potion={hasPattern=true,label="Aphrodite's Serum",recipe={minecraft_jj_dye_jj_1={need=1,tag={}},minecraft_jj_dye_jj_3={need=1,tag={}},minecraft_jj_glass_pane={need=5,tag={}},minecraft_jj_water_bucket={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_9={need=1,tag={}}}},
 xreliquary_jj_bullet={hasPattern=false,label="",recipe={xreliquary_jj_bullet={need=8,tag={}},xreliquary_jj_potion={need=1,tag={}}}},
 xreliquary_jj_bullet_jj_1={hasPattern=false,label="",recipe={}},
 xreliquary_jj_bullet_jj_2={hasPattern=true,label="Exorcism Shot",recipe={xreliquary_jj_bullet_jj_1={need=8,tag={}},xreliquary_jj_mob_ingredient_jj_6={need=1,tag={}}}},
 xreliquary_jj_bullet_jj_3={hasPattern=true,label="Blaze Shot",recipe={minecraft_jj_blaze_powder={need=1,tag={}},minecraft_jj_blaze_rod={need=1,tag={}},minecraft_jj_gold_nugget={need=2,tag={}}}},
 xreliquary_jj_bullet_jj_4={hasPattern=true,label="Ender Shot",recipe={xreliquary_jj_bullet_jj_7={need=8,tag={}},xreliquary_jj_mob_ingredient_jj_11={need=1,tag={}}}},
 xreliquary_jj_bullet_jj_5={hasPattern=true,label="Concussive Shot",recipe={minecraft_jj_gold_nugget={need=2,tag={}},minecraft_jj_gunpowder={need=1,tag={}},minecraft_jj_slime_ball={need=1,tag={}}}},
 xreliquary_jj_bullet_jj_6={hasPattern=true,label="Buster Shot",recipe={xreliquary_jj_bullet_jj_5={need=8,tag={}},xreliquary_jj_mob_ingredient_jj_3={need=1,tag={}}}},
 xreliquary_jj_bullet_jj_7={hasPattern=true,label="Seeker Shot",recipe={minecraft_jj_dye_jj_4={need=1,tag={}},minecraft_jj_gold_nugget={need=2,tag={}},minecraft_jj_gunpowder={need=1,tag={}}}},
 xreliquary_jj_bullet_jj_8={hasPattern=true,label="Sand Shot",recipe={minecraft_jj_gold_nugget={need=1,tag={}},minecraft_jj_gunpowder={need=1,tag={}},minecraft_jj_sandstone={need=1,tag={}},minecraft_jj_slime_ball={need=1,tag={}}}},
 xreliquary_jj_bullet_jj_9={hasPattern=true,label="Storm Shot",recipe={minecraft_jj_gold_nugget={need=2,tag={}},minecraft_jj_gunpowder={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_3={need=2,tag={}}}},
 xreliquary_jj_destruction_catalyst={hasPattern=true,label="Destruction Catalyst",recipe={minecraft_jj_flint_and_steel={need=1,tag={}},xreliquary_jj_infernal_tear={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_3={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_7={need=1,tag={}}}},
 xreliquary_jj_emperor_chalice={hasPattern=true,label="Emperor's Chalice",recipe={minecraft_jj_bucket={need=1,tag={}},minecraft_jj_emerald={need=1,tag={}},minecraft_jj_gold_ingot={need=1,tag={}},xreliquary_jj_void_tear={need=1,tag={}}}},
 xreliquary_jj_ender_staff={hasPattern=true,label="Ender Staff",recipe={minecraft_jj_ender_eye={need=1,tag={}},minecraft_jj_stick={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_11={need=2,tag={}},xreliquary_jj_mob_ingredient_jj_5={need=2,tag={}},xreliquary_jj_void_tear={need=1,tag={}}}},
 xreliquary_jj_fertile_lilypad={hasPattern=true,label="Lilypad of Fertility",recipe={minecraft_jj_waterlily={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_9={need=3,tag={}}}},
 xreliquary_jj_fertile_potion={hasPattern=true,label="Fertile Potion",recipe={minecraft_jj_dye_jj_11={need=1,tag={}},minecraft_jj_dye_jj_2={need=1,tag={}},minecraft_jj_glass_pane={need=5,tag={}},minecraft_jj_water_bucket={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_9={need=1,tag={}}}},
 xreliquary_jj_fortune_coin={hasPattern=true,label="Coin of Fortune",recipe={minecraft_jj_gold_nugget={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_11={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_4={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_5={need=1,tag={}}}},
 xreliquary_jj_glacial_staff={hasPattern=true,label="Glacial Staff",recipe={xreliquary_jj_ice_magus_rod={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_10={need=1,tag={}},xreliquary_jj_shears_of_winter={need=1,tag={}},xreliquary_jj_void_tear={need=1,tag={}}}},
 xreliquary_jj_glowing_bread={hasPattern=true,label="Glowing Bread",recipe={minecraft_jj_bread={need=3,tag={}},xreliquary_jj_glowing_water={need=1,tag={}}}},
 xreliquary_jj_glowing_water={hasPattern=true,label="Glowing Water",recipe={minecraft_jj_glass_pane={need=5,tag={}},minecraft_jj_glowstone_dust={need=1,tag={}},minecraft_jj_gunpowder={need=1,tag={}},minecraft_jj_nether_wart={need=1,tag={}},minecraft_jj_water_bucket={need=1,tag={}}}},
 xreliquary_jj_gun_part={hasPattern=true,label="Grip Assembly",recipe={minecraft_jj_iron_ingot={need=7,tag={}},minecraft_jj_magma_cream={need=1,tag={}},xreliquary_jj_magazine={need=1,tag={}}}},
 xreliquary_jj_gun_part_jj_1={hasPattern=true,label="Barrel Assembly",recipe={minecraft_jj_iron_ingot={need=6,tag={}},minecraft_jj_magma_cream={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_11={need=2,tag={}}}},
 xreliquary_jj_gun_part_jj_2={hasPattern=true,label="Hammer Assembly",recipe={minecraft_jj_blaze_rod={need=1,tag={}},minecraft_jj_iron_ingot={need=6,tag={}},minecraft_jj_stone_button={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_7={need=1,tag={}}}},
 xreliquary_jj_handgun={hasPattern=true,label="Hunter's Handgun",recipe={minecraft_jj_iron_ingot={need=5,tag={}},xreliquary_jj_gun_part={need=1,tag={}},xreliquary_jj_gun_part_jj_1={need=1,tag={}},xreliquary_jj_gun_part_jj_2={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_4={need=1,tag={}}}},
 xreliquary_jj_harvest_rod={hasPattern=true,label="§2Harvest Rod",recipe={minecraft_jj_double_plant_jj_4={need=2,tag={}},minecraft_jj_stick={need=1,tag={}},minecraft_jj_vine={need=2,tag={}},xreliquary_jj_mob_ingredient_jj_9={need=1,tag={}},xreliquary_jj_void_tear={need=1,tag={}}}},
 xreliquary_jj_hero_medallion={hasPattern=true,label="Hero's Medallion",recipe={xreliquary_jj_fortune_coin={need=1,tag={}},xreliquary_jj_infernal_tear={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_11={need=1,tag={}},xreliquary_jj_witch_hat={need=1,tag={}}}},
 xreliquary_jj_holy_hand_grenade={hasPattern=true,label="Holy Hand Grenade",recipe={minecraft_jj_gold_nugget={need=1,tag={}},minecraft_jj_tnt={need=1,tag={}},xreliquary_jj_glowing_water={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_3={need=1,tag={}}}},
 xreliquary_jj_ice_magus_rod={hasPattern=true,label="Ice Magus Rod",recipe={minecraft_jj_diamond={need=2,tag={}},minecraft_jj_iron_ingot={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_10={need=1,tag={}},xreliquary_jj_void_tear={need=1,tag={}}}},
 xreliquary_jj_infernal_chalice={hasPattern=true,label="Infernal Chalice",recipe={xreliquary_jj_emperor_chalice={need=1,tag={}},xreliquary_jj_infernal_claws={need=1,tag={}},xreliquary_jj_infernal_tear={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_7={need=1,tag={}}}},
 xreliquary_jj_infernal_claws={hasPattern=true,label="§4Infernal Claws",recipe={xreliquary_jj_mob_ingredient_jj_13={need=3,tag={}},xreliquary_jj_mob_ingredient_jj_4={need=1,tag={}}}},
 xreliquary_jj_infernal_tear={hasPattern=true,label="§4Infernal Tear",recipe={xreliquary_jj_mob_ingredient_jj_13={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_7={need=1,tag={}},xreliquary_jj_void_tear={need=1,tag={}},xreliquary_jj_witch_hat={need=1,tag={}}}},
 xreliquary_jj_interdiction_torch={hasPattern=true,label="§eInterdiction Torch",recipe={minecraft_jj_blaze_rod={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_11={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_5={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_7={need=1,tag={}}}},
 xreliquary_jj_kraken_shell={hasPattern=true,label="Kraken Shell",recipe={xreliquary_jj_mob_ingredient_jj_11={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_14={need=3,tag={}}}},
 xreliquary_jj_lantern_of_paranoia={hasPattern=true,label="§eLantern Of Paranoia",recipe={minecraft_jj_glass={need=2,tag={}},minecraft_jj_iron_ingot={need=3,tag={}},xreliquary_jj_mob_ingredient_jj_4={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_7={need=1,tag={}}}},
 xreliquary_jj_magazine={hasPattern=true,label="Empty Magazine",recipe={minecraft_jj_glass={need=1,tag={}},minecraft_jj_iron_ingot={need=5,tag={}},minecraft_jj_stone={need=2,tag={}},xreliquary_jj_bullet={need=8,tag={}},xreliquary_jj_magazine={need=1,tag={}}}},
 xreliquary_jj_magazine_jj_1={hasPattern=false,label="",recipe={}},
 xreliquary_jj_magazine_jj_2={hasPattern=true,label="Exorcism Magazine",recipe={xreliquary_jj_bullet={need=8,tag={}},xreliquary_jj_magazine={need=1,tag={}}}},
 xreliquary_jj_magazine_jj_3={hasPattern=true,label="Blaze Magazine",recipe={xreliquary_jj_bullet={need=8,tag={}},xreliquary_jj_magazine={need=1,tag={}}}},
 xreliquary_jj_magazine_jj_4={hasPattern=true,label="Ender Magazine",recipe={xreliquary_jj_bullet={need=8,tag={}},xreliquary_jj_magazine={need=1,tag={}}}},
 xreliquary_jj_magazine_jj_5={hasPattern=true,label="Concussive Magazine",recipe={xreliquary_jj_bullet={need=8,tag={}},xreliquary_jj_magazine={need=1,tag={}}}},
 xreliquary_jj_magazine_jj_6={hasPattern=true,label="Buster Magazine",recipe={xreliquary_jj_bullet={need=8,tag={}},xreliquary_jj_magazine={need=1,tag={}}}},
 xreliquary_jj_magazine_jj_7={hasPattern=true,label="Seeker Magazine",recipe={xreliquary_jj_bullet={need=8,tag={}},xreliquary_jj_magazine={need=1,tag={}}}},
 xreliquary_jj_magazine_jj_8={hasPattern=true,label="Sand Magazine",recipe={xreliquary_jj_bullet={need=8,tag={}},xreliquary_jj_magazine={need=1,tag={}}}},
 xreliquary_jj_magazine_jj_9={hasPattern=true,label="Storm Magazine",recipe={xreliquary_jj_bullet={need=8,tag={}},xreliquary_jj_magazine={need=1,tag={}}}},
 xreliquary_jj_magicbane={hasPattern=true,label="Magicbane",recipe={minecraft_jj_gold_ingot={need=1,tag={}},minecraft_jj_iron_ingot={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_11={need=2,tag={}}}},
 xreliquary_jj_mercy_cross={hasPattern=true,label="Cross of Mercy",recipe={minecraft_jj_gold_ingot={need=4,tag={}},minecraft_jj_leather={need=1,tag={}},minecraft_jj_skull_jj_1={need=1,tag={}},xreliquary_jj_mob_ingredient={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_1={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_6={need=1,tag={}}}},
 xreliquary_jj_midas_touchstone={hasPattern=true,label="Touchstone of Midas",recipe={minecraft_jj_anvil={need=1,tag={}},minecraft_jj_gold_block={need=2,tag={}},xreliquary_jj_mob_ingredient_jj_3={need=2,tag={}},xreliquary_jj_mob_ingredient_jj_7={need=3,tag={}},xreliquary_jj_void_tear={need=1,tag={}}}},
 xreliquary_jj_mob_charm={hasPattern=false,label="",recipe={}},
 xreliquary_jj_mob_charm_belt={hasPattern=true,label="Charm Belt",recipe={minecraft_jj_leather={need=3,tag={}},xreliquary_jj_mob_charm_fragment={need=5,tag={}}}},
 xreliquary_jj_mob_charm_fragment={hasPattern=true,label="§aZombie Charm Fragment",recipe={minecraft_jj_bone={need=1,tag={}},minecraft_jj_rotten_flesh={need=2,tag={}},xreliquary_jj_mob_ingredient_jj_6={need=6,tag={}}}},
 xreliquary_jj_mob_charm_fragment_jj_1={hasPattern=true,label="§aSkeleton Charm Fragment",recipe={minecraft_jj_bone={need=2,tag={}},minecraft_jj_flint={need=1,tag={}},xreliquary_jj_mob_ingredient={need=6,tag={}}}},
 xreliquary_jj_mob_charm_fragment_jj_10={hasPattern=true,label="§aSlime Charm Fragment",recipe={minecraft_jj_slime_ball={need=3,tag={}},xreliquary_jj_mob_ingredient_jj_4={need=6,tag={}}}},
 xreliquary_jj_mob_charm_fragment_jj_11={hasPattern=true,label="§aMagma Cube Charm Fragment",recipe={minecraft_jj_magma_cream={need=3,tag={}},xreliquary_jj_mob_ingredient_jj_7={need=6,tag={}}}},
 xreliquary_jj_mob_charm_fragment_jj_12={hasPattern=true,label="§aBlaze Charm Fragment",recipe={minecraft_jj_blaze_powder={need=1,tag={}},minecraft_jj_blaze_rod={need=2,tag={}},xreliquary_jj_mob_ingredient_jj_7={need=6,tag={}}}},
 xreliquary_jj_mob_charm_fragment_jj_13={hasPattern=true,label="§aGuardian Charm Fragment",recipe={minecraft_jj_fish={need=1,tag={}},minecraft_jj_prismarine_shard={need=2,tag={}},xreliquary_jj_mob_ingredient_jj_16={need=6,tag={}}}},
 xreliquary_jj_mob_charm_fragment_jj_2={hasPattern=true,label="§aWither Skeleton Charm Fragment",recipe={minecraft_jj_bone={need=2,tag={}},minecraft_jj_skull_jj_1={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_1={need=6,tag={}}}},
 xreliquary_jj_mob_charm_fragment_jj_3={hasPattern=true,label="§aCreeper Charm Fragment",recipe={minecraft_jj_bone={need=1,tag={}},minecraft_jj_gunpowder={need=2,tag={}},xreliquary_jj_mob_ingredient_jj_3={need=6,tag={}}}},
 xreliquary_jj_mob_charm_fragment_jj_4={hasPattern=true,label="§aWitch Charm Fragment",recipe={minecraft_jj_glass_bottle={need=2,tag={}},minecraft_jj_spider_eye={need=1,tag={}},xreliquary_jj_witch_hat={need=6,tag={}}}},
 xreliquary_jj_mob_charm_fragment_jj_5={hasPattern=true,label="§aZombie Pigman Charm Fragment",recipe={minecraft_jj_golden_sword={need=1,tag={}},minecraft_jj_rotten_flesh={need=2,tag={}},xreliquary_jj_mob_ingredient_jj_6={need=6,tag={}}}},
 xreliquary_jj_mob_charm_fragment_jj_6={hasPattern=true,label="§aCave Spider Charm Fragment",recipe={minecraft_jj_potion={need=1,tag={}},minecraft_jj_string={need=2,tag={}},xreliquary_jj_mob_ingredient_jj_2={need=6,tag={}}}},
 xreliquary_jj_mob_charm_fragment_jj_7={hasPattern=true,label="§aSpider Charm Fragment",recipe={minecraft_jj_spider_eye={need=1,tag={}},minecraft_jj_string={need=2,tag={}},xreliquary_jj_mob_ingredient_jj_2={need=6,tag={}}}},
 xreliquary_jj_mob_charm_fragment_jj_8={hasPattern=true,label="§aEnderman Charm Fragment",recipe={minecraft_jj_ender_pearl={need=2,tag={}},xreliquary_jj_mob_ingredient_jj_11={need=7,tag={}}}},
 xreliquary_jj_mob_charm_fragment_jj_9={hasPattern=true,label="§aGhast Charm Fragment",recipe={minecraft_jj_ghast_tear={need=6,tag={}},minecraft_jj_gunpowder={need=2,tag={}},xreliquary_jj_mob_ingredient_jj_3={need=1,tag={}}}},
 xreliquary_jj_mob_ingredient={hasPattern=false,label="",recipe={}},
 xreliquary_jj_mob_ingredient_jj_1={hasPattern=false,label="",recipe={}},
 xreliquary_jj_mob_ingredient_jj_10={hasPattern=false,label="",recipe={}},
 xreliquary_jj_mob_ingredient_jj_11={hasPattern=false,label="",recipe={}},
 xreliquary_jj_mob_ingredient_jj_12={hasPattern=false,label="",recipe={}},
 xreliquary_jj_mob_ingredient_jj_13={hasPattern=true,label="Infernal Claw",recipe={minecraft_jj_leather={need=1,tag={}},xreliquary_jj_mob_ingredient={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_4={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_7={need=1,tag={}}}},
 xreliquary_jj_mob_ingredient_jj_14={hasPattern=true,label="Kraken Shell Fragment",recipe={xreliquary_jj_mob_ingredient_jj_12={need=3,tag={}},xreliquary_jj_mob_ingredient_jj_4={need=1,tag={}}}},
 xreliquary_jj_mob_ingredient_jj_15={hasPattern=true,label="Crimson Cloth",recipe={minecraft_jj_wool_jj_14={need=1,tag={}},minecraft_jj_wool_jj_15={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_11={need=2,tag={}}}},
 xreliquary_jj_mob_ingredient_jj_16={hasPattern=false,label="",recipe={}},
 xreliquary_jj_mob_ingredient_jj_2={hasPattern=false,label="",recipe={}},
 xreliquary_jj_mob_ingredient_jj_3={hasPattern=false,label="",recipe={}},
 xreliquary_jj_mob_ingredient_jj_4={hasPattern=false,label="",recipe={}},
 xreliquary_jj_mob_ingredient_jj_5={hasPattern=false,label="",recipe={}},
 xreliquary_jj_mob_ingredient_jj_6={hasPattern=false,label="",recipe={}},
 xreliquary_jj_mob_ingredient_jj_7={hasPattern=false,label="",recipe={}},
 xreliquary_jj_mob_ingredient_jj_8={hasPattern=false,label="",recipe={}},
 xreliquary_jj_mob_ingredient_jj_9={hasPattern=true,label="Fertile Essence",recipe={minecraft_jj_dye_jj_2={need=1,tag={}},xreliquary_jj_mob_ingredient={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_3={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_4={need=1,tag={}}}},
 xreliquary_jj_pedestal={hasPattern=true,label="Pedestal",recipe={minecraft_jj_diamond={need=4,tag={}},xreliquary_jj_pedestal_passive={need=1,tag={}}}},
 xreliquary_jj_pedestal_jj_1={hasPattern=true,label="Pedestal",recipe={minecraft_jj_diamond={need=4,tag={}},xreliquary_jj_pedestal_passive_jj_1={need=1,tag={}}}},
 xreliquary_jj_pedestal_jj_10={hasPattern=true,label="Pedestal",recipe={minecraft_jj_diamond={need=4,tag={}},xreliquary_jj_pedestal_passive_jj_10={need=1,tag={}}}},
 xreliquary_jj_pedestal_jj_11={hasPattern=true,label="Pedestal",recipe={minecraft_jj_diamond={need=4,tag={}},xreliquary_jj_pedestal_passive_jj_11={need=1,tag={}}}},
 xreliquary_jj_pedestal_jj_12={hasPattern=true,label="Pedestal",recipe={minecraft_jj_diamond={need=4,tag={}},xreliquary_jj_pedestal_passive_jj_12={need=1,tag={}}}},
 xreliquary_jj_pedestal_jj_13={hasPattern=true,label="Pedestal",recipe={minecraft_jj_diamond={need=4,tag={}},xreliquary_jj_pedestal_passive_jj_13={need=1,tag={}}}},
 xreliquary_jj_pedestal_jj_14={hasPattern=true,label="Pedestal",recipe={minecraft_jj_diamond={need=4,tag={}},xreliquary_jj_pedestal_passive_jj_14={need=1,tag={}}}},
 xreliquary_jj_pedestal_jj_15={hasPattern=true,label="Pedestal",recipe={minecraft_jj_diamond={need=4,tag={}},xreliquary_jj_pedestal_passive_jj_15={need=1,tag={}}}},
 xreliquary_jj_pedestal_jj_2={hasPattern=true,label="Pedestal",recipe={minecraft_jj_diamond={need=4,tag={}},xreliquary_jj_pedestal_passive_jj_2={need=1,tag={}}}},
 xreliquary_jj_pedestal_jj_3={hasPattern=true,label="Pedestal",recipe={minecraft_jj_diamond={need=4,tag={}},xreliquary_jj_pedestal_passive_jj_3={need=1,tag={}}}},
 xreliquary_jj_pedestal_jj_4={hasPattern=true,label="Pedestal",recipe={minecraft_jj_diamond={need=4,tag={}},xreliquary_jj_pedestal_passive_jj_4={need=1,tag={}}}},
 xreliquary_jj_pedestal_jj_5={hasPattern=true,label="Pedestal",recipe={minecraft_jj_diamond={need=4,tag={}},xreliquary_jj_pedestal_passive_jj_5={need=1,tag={}}}},
 xreliquary_jj_pedestal_jj_6={hasPattern=true,label="Pedestal",recipe={minecraft_jj_diamond={need=4,tag={}},xreliquary_jj_pedestal_passive_jj_6={need=1,tag={}}}},
 xreliquary_jj_pedestal_jj_7={hasPattern=true,label="Pedestal",recipe={minecraft_jj_diamond={need=4,tag={}},xreliquary_jj_pedestal_passive_jj_7={need=1,tag={}}}},
 xreliquary_jj_pedestal_jj_8={hasPattern=true,label="Pedestal",recipe={minecraft_jj_diamond={need=4,tag={}},xreliquary_jj_pedestal_passive_jj_8={need=1,tag={}}}},
 xreliquary_jj_pedestal_jj_9={hasPattern=true,label="Pedestal",recipe={minecraft_jj_diamond={need=4,tag={}},xreliquary_jj_pedestal_passive_jj_9={need=1,tag={}}}},
 xreliquary_jj_pedestal_passive={hasPattern=true,label="Pedestal (Display only)",recipe={minecraft_jj_carpet={need=1,tag={}},minecraft_jj_gold_nugget={need=2,tag={}},minecraft_jj_quartz_block={need=1,tag={}},minecraft_jj_quartz_block_jj_1={need=1,tag={}},minecraft_jj_quartz_block_jj_2={need=1,tag={}},minecraft_jj_stone_slab_jj_7={need=3,tag={}}}},
 xreliquary_jj_pedestal_passive_jj_1={hasPattern=true,label="Pedestal (Display only)",recipe={minecraft_jj_carpet_jj_1={need=1,tag={}},minecraft_jj_gold_nugget={need=2,tag={}},minecraft_jj_quartz_block={need=1,tag={}},minecraft_jj_quartz_block_jj_1={need=1,tag={}},minecraft_jj_quartz_block_jj_2={need=1,tag={}},minecraft_jj_stone_slab_jj_7={need=3,tag={}}}},
 xreliquary_jj_pedestal_passive_jj_10={hasPattern=true,label="Pedestal (Display only)",recipe={minecraft_jj_carpet_jj_10={need=1,tag={}},minecraft_jj_gold_nugget={need=2,tag={}},minecraft_jj_quartz_block={need=1,tag={}},minecraft_jj_quartz_block_jj_1={need=1,tag={}},minecraft_jj_quartz_block_jj_2={need=1,tag={}},minecraft_jj_stone_slab_jj_7={need=3,tag={}}}},
 xreliquary_jj_pedestal_passive_jj_11={hasPattern=true,label="Pedestal (Display only)",recipe={minecraft_jj_carpet_jj_11={need=1,tag={}},minecraft_jj_gold_nugget={need=2,tag={}},minecraft_jj_quartz_block={need=1,tag={}},minecraft_jj_quartz_block_jj_1={need=1,tag={}},minecraft_jj_quartz_block_jj_2={need=1,tag={}},minecraft_jj_stone_slab_jj_7={need=3,tag={}}}},
 xreliquary_jj_pedestal_passive_jj_12={hasPattern=true,label="Pedestal (Display only)",recipe={minecraft_jj_carpet_jj_12={need=1,tag={}},minecraft_jj_gold_nugget={need=2,tag={}},minecraft_jj_quartz_block={need=1,tag={}},minecraft_jj_quartz_block_jj_1={need=1,tag={}},minecraft_jj_quartz_block_jj_2={need=1,tag={}},minecraft_jj_stone_slab_jj_7={need=3,tag={}}}},
 xreliquary_jj_pedestal_passive_jj_13={hasPattern=true,label="Pedestal (Display only)",recipe={minecraft_jj_carpet_jj_13={need=1,tag={}},minecraft_jj_gold_nugget={need=2,tag={}},minecraft_jj_quartz_block={need=1,tag={}},minecraft_jj_quartz_block_jj_1={need=1,tag={}},minecraft_jj_quartz_block_jj_2={need=1,tag={}},minecraft_jj_stone_slab_jj_7={need=3,tag={}}}},
 xreliquary_jj_pedestal_passive_jj_14={hasPattern=true,label="Pedestal (Display only)",recipe={minecraft_jj_carpet_jj_14={need=1,tag={}},minecraft_jj_gold_nugget={need=2,tag={}},minecraft_jj_quartz_block={need=1,tag={}},minecraft_jj_quartz_block_jj_1={need=1,tag={}},minecraft_jj_quartz_block_jj_2={need=1,tag={}},minecraft_jj_stone_slab_jj_7={need=3,tag={}}}},
 xreliquary_jj_pedestal_passive_jj_15={hasPattern=true,label="Pedestal (Display only)",recipe={minecraft_jj_carpet_jj_15={need=1,tag={}},minecraft_jj_gold_nugget={need=2,tag={}},minecraft_jj_quartz_block={need=1,tag={}},minecraft_jj_quartz_block_jj_1={need=1,tag={}},minecraft_jj_quartz_block_jj_2={need=1,tag={}},minecraft_jj_stone_slab_jj_7={need=3,tag={}}}},
 xreliquary_jj_pedestal_passive_jj_2={hasPattern=true,label="Pedestal (Display only)",recipe={minecraft_jj_carpet_jj_2={need=1,tag={}},minecraft_jj_gold_nugget={need=2,tag={}},minecraft_jj_quartz_block={need=1,tag={}},minecraft_jj_quartz_block_jj_1={need=1,tag={}},minecraft_jj_quartz_block_jj_2={need=1,tag={}},minecraft_jj_stone_slab_jj_7={need=3,tag={}}}},
 xreliquary_jj_pedestal_passive_jj_3={hasPattern=true,label="Pedestal (Display only)",recipe={minecraft_jj_carpet_jj_3={need=1,tag={}},minecraft_jj_gold_nugget={need=2,tag={}},minecraft_jj_quartz_block={need=1,tag={}},minecraft_jj_quartz_block_jj_1={need=1,tag={}},minecraft_jj_quartz_block_jj_2={need=1,tag={}},minecraft_jj_stone_slab_jj_7={need=3,tag={}}}},
 xreliquary_jj_pedestal_passive_jj_4={hasPattern=true,label="Pedestal (Display only)",recipe={minecraft_jj_carpet_jj_4={need=1,tag={}},minecraft_jj_gold_nugget={need=2,tag={}},minecraft_jj_quartz_block={need=1,tag={}},minecraft_jj_quartz_block_jj_1={need=1,tag={}},minecraft_jj_quartz_block_jj_2={need=1,tag={}},minecraft_jj_stone_slab_jj_7={need=3,tag={}}}},
 xreliquary_jj_pedestal_passive_jj_5={hasPattern=true,label="Pedestal (Display only)",recipe={minecraft_jj_carpet_jj_5={need=1,tag={}},minecraft_jj_gold_nugget={need=2,tag={}},minecraft_jj_quartz_block={need=1,tag={}},minecraft_jj_quartz_block_jj_1={need=1,tag={}},minecraft_jj_quartz_block_jj_2={need=1,tag={}},minecraft_jj_stone_slab_jj_7={need=3,tag={}}}},
 xreliquary_jj_pedestal_passive_jj_6={hasPattern=true,label="Pedestal (Display only)",recipe={minecraft_jj_carpet_jj_6={need=1,tag={}},minecraft_jj_gold_nugget={need=2,tag={}},minecraft_jj_quartz_block={need=1,tag={}},minecraft_jj_quartz_block_jj_1={need=1,tag={}},minecraft_jj_quartz_block_jj_2={need=1,tag={}},minecraft_jj_stone_slab_jj_7={need=3,tag={}}}},
 xreliquary_jj_pedestal_passive_jj_7={hasPattern=true,label="Pedestal (Display only)",recipe={minecraft_jj_carpet_jj_7={need=1,tag={}},minecraft_jj_gold_nugget={need=2,tag={}},minecraft_jj_quartz_block={need=1,tag={}},minecraft_jj_quartz_block_jj_1={need=1,tag={}},minecraft_jj_quartz_block_jj_2={need=1,tag={}},minecraft_jj_stone_slab_jj_7={need=3,tag={}}}},
 xreliquary_jj_pedestal_passive_jj_8={hasPattern=true,label="Pedestal (Display only)",recipe={minecraft_jj_carpet_jj_8={need=1,tag={}},minecraft_jj_gold_nugget={need=2,tag={}},minecraft_jj_quartz_block={need=1,tag={}},minecraft_jj_quartz_block_jj_1={need=1,tag={}},minecraft_jj_quartz_block_jj_2={need=1,tag={}},minecraft_jj_stone_slab_jj_7={need=3,tag={}}}},
 xreliquary_jj_pedestal_passive_jj_9={hasPattern=true,label="Pedestal (Display only)",recipe={minecraft_jj_carpet_jj_9={need=1,tag={}},minecraft_jj_gold_nugget={need=2,tag={}},minecraft_jj_quartz_block={need=1,tag={}},minecraft_jj_quartz_block_jj_1={need=1,tag={}},minecraft_jj_quartz_block_jj_2={need=1,tag={}},minecraft_jj_stone_slab_jj_7={need=3,tag={}}}},
 xreliquary_jj_phoenix_down={hasPattern=true,label="Phoenix Down",recipe={xreliquary_jj_angelheart_vial={need=3,tag={}},xreliquary_jj_angelic_feather={need=1,tag={}}}},
 xreliquary_jj_potion={hasPattern=false,label="",recipe={}},
 xreliquary_jj_potion_essence={hasPattern=false,label="",recipe={}},
 xreliquary_jj_pyromancer_staff={hasPattern=true,label="§4Pyromancer's Staff",recipe={minecraft_jj_blaze_rod={need=1,tag={}},xreliquary_jj_infernal_claws={need=1,tag={}},xreliquary_jj_infernal_tear={need=1,tag={}},xreliquary_jj_salamander_eye={need=1,tag={}}}},
 xreliquary_jj_rending_gale={hasPattern=true,label="§eRending Gale",recipe={minecraft_jj_gold_ingot={need=2,tag={}},minecraft_jj_stick={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_5={need=2,tag={}},xreliquary_jj_mob_ingredient_jj_8={need=1,tag={}},xreliquary_jj_void_tear={need=1,tag={}}}},
 xreliquary_jj_rod_of_lyssa={hasPattern=true,label="Rod of Lyssa",recipe={minecraft_jj_fishing_rod={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_11={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_13={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_5={need=1,tag={}}}},
 xreliquary_jj_salamander_eye={hasPattern=true,label="Salamander's Eye",recipe={minecraft_jj_ender_eye={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_10={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_11={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_7={need=1,tag={}}}},
 xreliquary_jj_serpent_staff={hasPattern=true,label="§2Serpent Staff",recipe={minecraft_jj_ender_eye={need=1,tag={}},minecraft_jj_stick={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_14={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_2={need=2,tag={}}}},
 xreliquary_jj_shears_of_winter={hasPattern=true,label="Shears of Winter",recipe={minecraft_jj_diamond={need=2,tag={}},minecraft_jj_shears={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_10={need=1,tag={}}}},
 xreliquary_jj_sojourner_staff={hasPattern=true,label="Sojourner's Staff",recipe={minecraft_jj_blaze_rod={need=1,tag={}},minecraft_jj_gold_ingot={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_7={need=1,tag={}},xreliquary_jj_void_tear={need=1,tag={}}}},
 xreliquary_jj_tipped_arrow={hasPattern=false,label="",recipe={}},
 xreliquary_jj_twilight_cloak={hasPattern=true,label="Twilight Cloak",recipe={minecraft_jj_iron_ingot={need=2,tag={}},minecraft_jj_wool_jj_15={need=4,tag={}},xreliquary_jj_mob_ingredient_jj_15={need=3,tag={}}}},
 xreliquary_jj_void_tear={hasPattern=true,label="Void Tear",recipe={minecraft_jj_dye_jj_4={need=1,tag={}},minecraft_jj_ghast_tear={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_11={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_4={need=1,tag={}}}},
 xreliquary_jj_witch_hat={hasPattern=false,label="",recipe={}},
 xreliquary_jj_witherless_rose={hasPattern=true,label="Witherless Rose",recipe={minecraft_jj_double_plant_jj_4={need=1,tag={}},minecraft_jj_nether_star={need=4,tag={}},xreliquary_jj_mob_ingredient_jj_9={need=4,tag={}}}},
 xreliquary_jj_wraith_node={hasPattern=true,label="Wraith Node",recipe={minecraft_jj_emerald={need=1,tag={}},xreliquary_jj_mob_ingredient_jj_11={need=1,tag={}}}}
 }