return {
 rftools_jj_advanced_charged_porter={hasPattern=true,label="Advanced Charged Porter",recipe={minecraft_jj_diamond={need=4,tag=""},minecraft_jj_redstone_block={need=4,tag=""},rftools_jj_charged_porter={need=1,tag=""}}},
 rftools_jj_analog_block={hasPattern=true,label="Analog",recipe={minecraft_jj_comparator={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""},rftools_jj_machine_base={need=1,tag=""}}},
 rftools_jj_blindness_module={hasPattern=true,label="Blindness Environmental Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_dye_jj_4={need=2,tag=""},minecraft_jj_obsidian={need=1,tag=""},rftools_jj_syringe={need=1,tag=""}}},
 rftools_jj_block_protector={hasPattern=true,label="Block Protector",recipe={minecraft_jj_obsidian={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""},rftools_jj_shield_template_block={need=4,tag=""}}},
 rftools_jj_booster={hasPattern=true,label="Booster",recipe={minecraft_jj_diamond={need=1,tag=""},minecraft_jj_glass_bottle={need=4,tag=""},minecraft_jj_gold_ingot={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_builder={hasPattern=true,label="Builder",recipe={minecraft_jj_brick_block={need=4,tag=""},minecraft_jj_ender_pearl={need=1,tag=""},minecraft_jj_redstone={need=3,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_button_module={hasPattern=true,label="Button Screen Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""},minecraft_jj_stone_button={need=1,tag=""}}},
 rftools_jj_camo_shield_block={hasPattern=false,label="",recipe={}},
 rftools_jj_camo_shield_block_opaque={hasPattern=false,label="",recipe={}},
 rftools_jj_charged_porter={hasPattern=true,label="Charged Porter",recipe={minecraft_jj_ender_pearl={need=4,tag=""},minecraft_jj_iron_ingot={need=2,tag=""},minecraft_jj_redstone_block={need=1,tag=""}}},
 rftools_jj_clock_module={hasPattern=true,label="Clock Screen Module",recipe={minecraft_jj_clock={need=1,tag=""},minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""}}},
 rftools_jj_coalgenerator={hasPattern=true,label="Coal Generator",recipe={minecraft_jj_coal={need=6,tag=""},minecraft_jj_redstone_torch={need=2,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_composer={hasPattern=true,label="Composer",recipe={minecraft_jj_brick={need=4,tag=""},minecraft_jj_paper={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_computer_module={hasPattern=true,label="Computermodul",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_quartz={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""}}},
 rftools_jj_counter_block={hasPattern=true,label="Counter",recipe={minecraft_jj_clock={need=1,tag=""},minecraft_jj_gold_nugget={need=2,tag=""},minecraft_jj_redstone={need=2,tag=""},minecraft_jj_redstone_torch={need=3,tag=""},rftools_jj_machine_base={need=1,tag=""}}},
 rftools_jj_counter_module={hasPattern=true,label="Counter Screen Module",recipe={minecraft_jj_comparator={need=1,tag=""},minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""}}},
 rftools_jj_counterplus_module={hasPattern=true,label="Counter Plus Screen Module",recipe={minecraft_jj_ender_pearl={need=2,tag=""},minecraft_jj_gold_ingot={need=2,tag=""},rftools_jj_counter_module={need=1,tag=""}}},
 rftools_jj_crafter1={hasPattern=true,label="Crafter Tier 1",recipe={minecraft_jj_crafting_table={need=2,tag=""},minecraft_jj_redstone_torch={need=2,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_crafter2={hasPattern=true,label="Crafter Tier 2",recipe={minecraft_jj_crafting_table={need=2,tag=""},minecraft_jj_redstone_torch={need=2,tag=""},rftools_jj_crafter1={need=1,tag=""}}},
 rftools_jj_crafter3={hasPattern=true,label="Crafter Tier 3",recipe={minecraft_jj_crafting_table={need=2,tag=""},minecraft_jj_redstone_torch={need=2,tag=""},rftools_jj_crafter2={need=1,tag=""}}},
 rftools_jj_creative_screen={hasPattern=false,label="",recipe={}},
 rftools_jj_destination_analyzer={hasPattern=true,label="Destination Analyzer",recipe={minecraft_jj_ender_pearl={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_developers_delight={hasPattern=false,label="",recipe={}},
 rftools_jj_dialing_device={hasPattern=true,label="Dialing Device",recipe={minecraft_jj_redstone={need=6,tag=""},minecraft_jj_redstone_torch={need=2,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_digit_block={hasPattern=true,label="Digit",recipe={minecraft_jj_glass_pane={need=6,tag=""},minecraft_jj_redstone={need=2,tag=""},rftools_jj_machine_base={need=1,tag=""}}},
 rftools_jj_dimensional_shard={hasPattern=false,label="",recipe={}},
 rftools_jj_dimensional_shard_ore={hasPattern=false,label="",recipe={}},
 rftools_jj_dimensional_shard_ore_jj_1={hasPattern=false,label="",recipe={}},
 rftools_jj_dimensional_shard_ore_jj_2={hasPattern=false,label="",recipe={}},
 rftools_jj_dump_module={hasPattern=true,label="Dump Screen Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""},minecraft_jj_wooden_button={need=1,tag=""}}},
 rftools_jj_elevator={hasPattern=true,label="Elevator",recipe={minecraft_jj_ender_pearl={need=1,tag=""},minecraft_jj_redstone={need=6,tag=""},minecraft_jj_redstone_torch={need=1,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_elevator_button_module={hasPattern=true,label="Elevator Button Screen Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""},minecraft_jj_stone_button={need=3,tag=""}}},
 rftools_jj_ender_monitor={hasPattern=true,label="Ender Monitor",recipe={minecraft_jj_ender_pearl={need=1,tag=""},minecraft_jj_redstone={need=4,tag=""},minecraft_jj_redstone_torch={need=3,tag=""},rftools_jj_machine_base={need=1,tag=""}}},
 rftools_jj_endergenic={hasPattern=true,label="Endergenic Generator",recipe={minecraft_jj_diamond={need=4,tag=""},minecraft_jj_ender_pearl={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_energy_module={hasPattern=true,label="Energy Screen Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_redstone={need=3,tag=""}}},
 rftools_jj_energyplus_module={hasPattern=true,label="Energy Plus Screen Module",recipe={minecraft_jj_ender_pearl={need=2,tag=""},minecraft_jj_gold_ingot={need=2,tag=""},rftools_jj_energy_module={need=1,tag=""}}},
 rftools_jj_environmental_controller={hasPattern=true,label="Environmental Controller",recipe={minecraft_jj_diamond_block={need=1,tag=""},minecraft_jj_emerald_block={need=1,tag=""},minecraft_jj_ender_pearl={need=4,tag=""},minecraft_jj_gold_block={need=1,tag=""},minecraft_jj_iron_block={need=1,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_featherfalling_module={hasPattern=true,label="Feather Falling Environmental Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_gold_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""},rftools_jj_syringe={need=1,tag=""}}},
 rftools_jj_featherfallingplus_module={hasPattern=true,label="Feather Falling Plus Environmental Module",recipe={rftools_jj_featherfalling_module={need=1,tag=""},rftools_jj_syringe={need=2,tag=""}}},
 rftools_jj_filter_module={hasPattern=true,label="Filter Module",recipe={minecraft_jj_hopper={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_paper={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""}}},
 rftools_jj_flight_module={hasPattern=true,label="Flight Environmental Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_gold_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""},rftools_jj_syringe={need=1,tag=""}}},
 rftools_jj_fluid_module={hasPattern=true,label="Fluid Screen Module",recipe={minecraft_jj_bucket={need=1,tag=""},minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""}}},
 rftools_jj_fluidplus_module={hasPattern=true,label="Fluid Plus Screen Module",recipe={minecraft_jj_ender_pearl={need=2,tag=""},minecraft_jj_gold_ingot={need=2,tag=""},rftools_jj_fluid_module={need=1,tag=""}}},
 rftools_jj_generic_module={hasPattern=true,label="Generic Type Module",recipe={minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_paper={need=2,tag=""},minecraft_jj_redstone={need=2,tag=""}}},
 rftools_jj_glowing_module={hasPattern=true,label="Glowing Environmental Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_gold_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""},rftools_jj_syringe={need=1,tag=""}}},
 rftools_jj_haste_module={hasPattern=true,label="Haste Environmental Module",recipe={minecraft_jj_diamond_pickaxe={need=1,tag=""},minecraft_jj_dye={need=1,tag=""},minecraft_jj_gold_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""}}},
 rftools_jj_hasteplus_module={hasPattern=true,label="Haste Plus Environmental Module",recipe={minecraft_jj_diamond_pickaxe={need=1,tag=""},rftools_jj_haste_module={need=1,tag=""}}},
 rftools_jj_infused_diamond={hasPattern=true,label="Infused Diamond",recipe={minecraft_jj_diamond={need=1,tag=""},rftools_jj_dimensional_shard={need=8,tag=""}}},
 rftools_jj_infused_enderpearl={hasPattern=true,label="Infused Enderpearl",recipe={minecraft_jj_ender_pearl={need=1,tag=""},rftools_jj_dimensional_shard={need=8,tag=""}}},
 rftools_jj_invchecker_block={hasPattern=true,label="Inventory Checker",recipe={minecraft_jj_chest={need=1,tag=""},minecraft_jj_comparator={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""},rftools_jj_machine_base={need=1,tag=""}}},
 rftools_jj_inventory_module={hasPattern=true,label="Inventory Screen Module",recipe={minecraft_jj_chest={need=1,tag=""},minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""}}},
 rftools_jj_inventoryplus_module={hasPattern=true,label="Inventory Plus Screen Module",recipe={minecraft_jj_ender_pearl={need=2,tag=""},minecraft_jj_gold_ingot={need=2,tag=""},rftools_jj_inventory_module={need=1,tag=""}}},
 rftools_jj_invisible_shield_block={hasPattern=false,label="",recipe={}},
 rftools_jj_invisible_shield_block_opaque={hasPattern=false,label="",recipe={}},
 rftools_jj_item_filter={hasPattern=true,label="Item Filter",recipe={minecraft_jj_chest={need=1,tag=""},minecraft_jj_paper={need=4,tag=""},minecraft_jj_redstone={need=2,tag=""},minecraft_jj_redstone_torch={need=1,tag=""},rftools_jj_machine_base={need=1,tag=""}}},
 rftools_jj_level_emitter={hasPattern=true,label="Level Emitter",recipe={minecraft_jj_comparator={need=1,tag=""},minecraft_jj_ender_pearl={need=2,tag=""},minecraft_jj_glass={need=3,tag=""},minecraft_jj_paper={need=2,tag=""},rftools_jj_machine_base={need=1,tag=""}}},
 rftools_jj_liquid_monitor={hasPattern=true,label="Liquid Monitor",recipe={minecraft_jj_bucket={need=2,tag=""},minecraft_jj_redstone_torch={need=2,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_locator={hasPattern=true,label="Locator",recipe={minecraft_jj_comparator={need=2,tag=""},minecraft_jj_ender_pearl={need=1,tag=""},minecraft_jj_quartz={need=2,tag=""},minecraft_jj_redstone={need=1,tag=""},rftools_jj_infused_diamond={need=2,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_logic_block={hasPattern=true,label="Logic Gate",recipe={minecraft_jj_comparator={need=4,tag=""},minecraft_jj_dye_jj_4={need=4,tag=""},rftools_jj_machine_base={need=1,tag=""}}},
 rftools_jj_luck_module={hasPattern=true,label="Luck Environmental Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_gold_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""},rftools_jj_syringe={need=1,tag=""}}},
 rftools_jj_machine_base={hasPattern=true,label="Machine Base",recipe={minecraft_jj_gold_nugget={need=3,tag=""},minecraft_jj_stone={need=3,tag=""}}},
 rftools_jj_machine_frame={hasPattern=true,label="Machine Frame",recipe={minecraft_jj_dye_jj_4={need=2,tag=""},minecraft_jj_gold_nugget={need=2,tag=""},minecraft_jj_iron_ingot={need=4,tag=""}}},
 rftools_jj_machine_infuser={hasPattern=true,label="Machine Infuser",recipe={minecraft_jj_diamond={need=2,tag=""},minecraft_jj_redstone={need=2,tag=""},rftools_jj_dimensional_shard={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_machineinformation_module={hasPattern=true,label="Machine Information Screen Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_furnace={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""}}},
 rftools_jj_matter_beamer={hasPattern=true,label="Matter Beamer",recipe={minecraft_jj_glowstone={need=4,tag=""},minecraft_jj_redstone_block={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_matter_booster={hasPattern=true,label="Matter Booster",recipe={minecraft_jj_redstone_block={need=4,tag=""},rftools_jj_destination_analyzer={need=1,tag=""}}},
 rftools_jj_matter_receiver={hasPattern=true,label="Matter Receiver",recipe={minecraft_jj_ender_pearl={need=3,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_redstone={need=2,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_matter_transmitter={hasPattern=true,label="Matter Transmitter",recipe={minecraft_jj_ender_pearl={need=3,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_redstone={need=2,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_modifier_module={hasPattern=true,label="Modifier",recipe={minecraft_jj_brick={need=2,tag=""},minecraft_jj_paper={need=3,tag=""},minecraft_jj_redstone={need=4,tag=""}}},
 rftools_jj_modular_storage={hasPattern=true,label="Modular Storage",recipe={minecraft_jj_chest={need=1,tag=""},minecraft_jj_quartz={need=3,tag=""},minecraft_jj_redstone={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_network_monitor={hasPattern=true,label="RF Network Monitor",recipe={minecraft_jj_dye={need=2,tag=""},minecraft_jj_iron_ingot={need=2,tag=""},minecraft_jj_redstone={need=5,tag=""}}},
 rftools_jj_nightvision_module={hasPattern=true,label="Night Vision Environmental Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_gold_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""},rftools_jj_syringe={need=1,tag=""}}},
 rftools_jj_noteleport_module={hasPattern=true,label="No Teleport Environmental Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_dye_jj_4={need=2,tag=""},minecraft_jj_obsidian={need=1,tag=""},rftools_jj_syringe={need=1,tag=""}}},
 rftools_jj_notick_camo_shield_block={hasPattern=false,label="",recipe={}},
 rftools_jj_notick_camo_shield_block_opaque={hasPattern=false,label="",recipe={}},
 rftools_jj_notick_invisible_shield_block={hasPattern=false,label="",recipe={}},
 rftools_jj_notick_invisible_shield_block_opaque={hasPattern=false,label="",recipe={}},
 rftools_jj_notick_solid_shield_block={hasPattern=false,label="",recipe={}},
 rftools_jj_notick_solid_shield_block_opaque={hasPattern=false,label="",recipe={}},
 rftools_jj_oredict_module={hasPattern=true,label="Ore Dictionary Type Module",recipe={minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_iron_ore={need=1,tag=""},minecraft_jj_paper={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""}}},
 rftools_jj_orphaning_card={hasPattern=true,label="Orphaning Card",recipe={minecraft_jj_book={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_paper={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""}}},
 rftools_jj_peace_essence={hasPattern=true,label="Peace Essence",recipe={rftools_jj_syringe={need=9,tag=""}}},
 rftools_jj_peaceful_module={hasPattern=true,label="Peaceful Environmental Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_gold_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""},rftools_jj_peace_essence={need=1,tag=""}}},
 rftools_jj_pearl_injector={hasPattern=true,label="Pearl Injector",recipe={minecraft_jj_chest={need=1,tag=""},minecraft_jj_hopper={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_poison_module={hasPattern=true,label="Poison Environmental Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_dye_jj_4={need=2,tag=""},minecraft_jj_obsidian={need=1,tag=""},rftools_jj_syringe={need=1,tag=""}}},
 rftools_jj_powercell={hasPattern=true,label="Powercell",recipe={minecraft_jj_diamond={need=1,tag=""},minecraft_jj_emerald={need=1,tag=""},minecraft_jj_prismarine_shard={need=2,tag=""},minecraft_jj_redstone={need=4,tag=""},rftools_jj_powercell_simple={need=1,tag=""}}},
 rftools_jj_powercell_advanced={hasPattern=true,label="Advanced Powercell",recipe={minecraft_jj_redstone_block={need=4,tag=""},rftools_jj_infused_diamond={need=4,tag=""},rftools_jj_powercell={need=1,tag=""}}},
 rftools_jj_powercell_card={hasPattern=true,label="Powercell Card",recipe={minecraft_jj_gold_nugget={need=4,tag=""},minecraft_jj_paper={need=1,tag=""},minecraft_jj_redstone={need=4,tag=""}}},
 rftools_jj_powercell_creative={hasPattern=false,label="",recipe={}},
 rftools_jj_powercell_simple={hasPattern=true,label="Simple Powercell",recipe={minecraft_jj_diamond={need=2,tag=""},minecraft_jj_quartz={need=2,tag=""},minecraft_jj_redstone_block={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_projector={hasPattern=true,label="Projector",recipe={minecraft_jj_ender_pearl={need=1,tag=""},minecraft_jj_glowstone_dust={need=2,tag=""},minecraft_jj_redstone={need=1,tag=""},rftools_jj_infused_diamond={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_redstone_module={hasPattern=true,label="Redstone Screen Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""},minecraft_jj_repeater={need=1,tag=""}}},
 rftools_jj_redstone_receiver_block={hasPattern=true,label="Redstone Receiver",recipe={minecraft_jj_comparator={need=2,tag=""},minecraft_jj_ender_pearl={need=1,tag=""},minecraft_jj_redstone={need=4,tag=""},minecraft_jj_redstone_block={need=1,tag=""},rftools_jj_machine_base={need=1,tag=""}}},
 rftools_jj_redstone_transmitter_block={hasPattern=true,label="Redstone Transmitter",recipe={minecraft_jj_ender_pearl={need=1,tag=""},minecraft_jj_redstone={need=4,tag=""},minecraft_jj_redstone_block={need=1,tag=""},minecraft_jj_redstone_torch={need=2,tag=""},rftools_jj_machine_base={need=1,tag=""}}},
 rftools_jj_regeneration_module={hasPattern=true,label="Regeneration Environmental Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_gold_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""},rftools_jj_syringe={need=1,tag=""}}},
 rftools_jj_regenerationplus_module={hasPattern=true,label="Regeneration Plus Environmental Module",recipe={rftools_jj_regeneration_module={need=1,tag=""},rftools_jj_syringe={need=2,tag=""}}},
 rftools_jj_relay={hasPattern=true,label="Power Relay",recipe={minecraft_jj_gold_ingot={need=6,tag=""},minecraft_jj_redstone_torch={need=2,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_remote_scanner={hasPattern=true,label="Remote Scanner",recipe={rftools_jj_infused_enderpearl={need=8,tag=""},rftools_jj_scanner={need=1,tag=""}}},
 rftools_jj_remote_storage={hasPattern=true,label="Remote Storage",recipe={minecraft_jj_chest={need=1,tag=""},minecraft_jj_ender_pearl={need=4,tag=""},minecraft_jj_quartz={need=3,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_rf_monitor={hasPattern=true,label="RF Monitor",recipe={minecraft_jj_redstone={need=2,tag=""},minecraft_jj_redstone_torch={need=2,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_rftools_manual={hasPattern=true,label="RFTools Manual",recipe={minecraft_jj_book={need=1,tag=""},minecraft_jj_redstone={need=4,tag=""}}},
 rftools_jj_rftools_shape_manual={hasPattern=true,label="RFTools Shape Manual",recipe={minecraft_jj_book={need=1,tag=""},minecraft_jj_brick={need=1,tag=""},minecraft_jj_redstone={need=3,tag=""}}},
 rftools_jj_saturation_module={hasPattern=true,label="Saturation Environmental Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_gold_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""},rftools_jj_syringe={need=1,tag=""}}},
 rftools_jj_saturationplus_module={hasPattern=true,label="Saturation Plus Environmental Module",recipe={rftools_jj_saturation_module={need=1,tag=""},rftools_jj_syringe={need=2,tag=""}}},
 rftools_jj_scanner={hasPattern=true,label="Scanner",recipe={minecraft_jj_ender_pearl={need=1,tag=""},minecraft_jj_quartz={need=2,tag=""},minecraft_jj_redstone={need=1,tag=""},rftools_jj_infused_diamond={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_screen={hasPattern=true,label="Screen",recipe={minecraft_jj_glass={need=5,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},rftools_jj_machine_base={need=1,tag=""}}},
 rftools_jj_screen_controller={hasPattern=true,label="Screen Controller",recipe={minecraft_jj_ender_pearl={need=1,tag=""},minecraft_jj_glass={need=3,tag=""},minecraft_jj_redstone={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_security_card={hasPattern=true,label="Security Card",recipe={minecraft_jj_flint={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_paper={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""}}},
 rftools_jj_security_manager={hasPattern=true,label="Security Manager",recipe={minecraft_jj_chest={need=1,tag=""},minecraft_jj_flint={need=3,tag=""},minecraft_jj_redstone={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_sensor_block={hasPattern=true,label="Sensor",recipe={minecraft_jj_comparator={need=2,tag=""},minecraft_jj_quartz={need=4,tag=""},minecraft_jj_redstone={need=2,tag=""},rftools_jj_machine_base={need=1,tag=""}}},
 rftools_jj_sequencer_block={hasPattern=true,label="Sequencer",recipe={minecraft_jj_redstone={need=4,tag=""},minecraft_jj_redstone_torch={need=4,tag=""},rftools_jj_machine_base={need=1,tag=""}}},
 rftools_jj_shape_card={hasPattern=true,label="Shape Card",recipe={minecraft_jj_brick={need=2,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_paper={need=4,tag=""},minecraft_jj_redstone={need=2,tag=""}}},
 rftools_jj_shape_card_jj_1={hasPattern=true,label="Shape Card (Void)",recipe={minecraft_jj_dye={need=4,tag=""},minecraft_jj_obsidian={need=4,tag=""},rftools_jj_shape_card={need=1,tag=""}}},
 rftools_jj_shape_card_jj_10={hasPattern=true,label="Shape Card (Placing Liquids)",recipe={minecraft_jj_iron_ingot={need=2,tag=""},minecraft_jj_lava_bucket={need=1,tag=""},minecraft_jj_redstone={need=4,tag=""},minecraft_jj_water_bucket={need=1,tag=""},rftools_jj_shape_card={need=1,tag=""}}},
 rftools_jj_shape_card_jj_2={hasPattern=true,label="Shape Card (Quarry)",recipe={minecraft_jj_diamond_pickaxe={need=1,tag=""},minecraft_jj_diamond_shovel={need=1,tag=""},minecraft_jj_iron_ingot={need=2,tag=""},minecraft_jj_redstone={need=4,tag=""},rftools_jj_shape_card={need=1,tag=""}}},
 rftools_jj_shape_card_jj_3={hasPattern=true,label="Shape Card (Silk Quarry)",recipe={minecraft_jj_diamond={need=3,tag=""},minecraft_jj_nether_star={need=1,tag=""},rftools_jj_dimensional_shard={need=4,tag=""},rftools_jj_shape_card_jj_2={need=1,tag=""}}},
 rftools_jj_shape_card_jj_4={hasPattern=true,label="Shape Card (Fortune Quarry)",recipe={minecraft_jj_diamond={need=1,tag=""},minecraft_jj_emerald={need=1,tag=""},minecraft_jj_ghast_tear={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""},rftools_jj_dimensional_shard={need=4,tag=""},rftools_jj_shape_card_jj_2={need=1,tag=""}}},
 rftools_jj_shape_card_jj_5={hasPattern=true,label="Shape Card (Clearing Quarry)",recipe={minecraft_jj_glass={need=8,tag=""},rftools_jj_shape_card_jj_2={need=1,tag=""}}},
 rftools_jj_shape_card_jj_6={hasPattern=true,label="Shape Card (Clearing Silk Quarry)",recipe={minecraft_jj_glass={need=8,tag=""},rftools_jj_shape_card_jj_3={need=1,tag=""}}},
 rftools_jj_shape_card_jj_7={hasPattern=true,label="Shape Card (Clearing Fortune Quarry)",recipe={minecraft_jj_glass={need=8,tag=""},rftools_jj_shape_card_jj_4={need=1,tag=""}}},
 rftools_jj_shape_card_jj_8={hasPattern=true,label="Shape Card (Pump)",recipe={minecraft_jj_bucket={need=2,tag=""},minecraft_jj_lava_bucket={need=1,tag=""},minecraft_jj_redstone={need=4,tag=""},minecraft_jj_water_bucket={need=1,tag=""},rftools_jj_shape_card={need=1,tag=""}}},
 rftools_jj_shape_card_jj_9={hasPattern=true,label="Shape Card (Clearing Pump)",recipe={minecraft_jj_glass={need=8,tag=""},rftools_jj_shape_card_jj_8={need=1,tag=""}}},
 rftools_jj_shard_wand={hasPattern=false,label="",recipe={}},
 rftools_jj_shield_block1={hasPattern=true,label="Shield Projector Tier 1",recipe={minecraft_jj_gold_ingot={need=2,tag=""},minecraft_jj_obsidian={need=3,tag=""},minecraft_jj_redstone={need=2,tag=""},minecraft_jj_redstone_torch={need=1,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_shield_block2={hasPattern=true,label="Shield Projector Tier 2",recipe={minecraft_jj_obsidian={need=4,tag=""},minecraft_jj_redstone_block={need=4,tag=""},rftools_jj_shield_block1={need=1,tag=""}}},
 rftools_jj_shield_block3={hasPattern=true,label="Shield Projector Tier 3",recipe={minecraft_jj_obsidian={need=4,tag=""},rftools_jj_dimensional_shard={need=4,tag=""},rftools_jj_shield_block2={need=1,tag=""}}},
 rftools_jj_shield_block4={hasPattern=true,label="Shield Projector Tier 4",recipe={minecraft_jj_nether_star={need=2,tag=""},minecraft_jj_obsidian={need=4,tag=""},rftools_jj_dimensional_shard={need=2,tag=""},rftools_jj_shield_block3={need=1,tag=""}}},
 rftools_jj_shield_template_block={hasPattern=true,label="Shield Template",recipe={minecraft_jj_dye_jj_4={need=2,tag=""},minecraft_jj_glass={need=1,tag=""},minecraft_jj_wool={need=6,tag=""}}},
 rftools_jj_shield_template_block_jj_1={hasPattern=true,label="Shield Template",recipe={rftools_jj_shield_template_block={need=1,tag=""}}},
 rftools_jj_shield_template_block_jj_2={hasPattern=true,label="Shield Template",recipe={rftools_jj_shield_template_block_jj_1={need=1,tag=""}}},
 rftools_jj_shield_template_block_jj_3={hasPattern=true,label="Shield Template",recipe={rftools_jj_shield_template_block_jj_2={need=1,tag=""}}},
 rftools_jj_simple_dialer={hasPattern=true,label="Simple Dialer",recipe={minecraft_jj_redstone={need=4,tag=""},minecraft_jj_redstone_block={need=2,tag=""},minecraft_jj_redstone_torch={need=2,tag=""},rftools_jj_machine_base={need=1,tag=""}}},
 rftools_jj_slowness_module={hasPattern=true,label="Slowness Environmental Module",recipe={minecraft_jj_clock={need=1,tag=""},minecraft_jj_dye={need=1,tag=""},minecraft_jj_dye_jj_4={need=2,tag=""},minecraft_jj_obsidian={need=1,tag=""}}},
 rftools_jj_smartwrench={hasPattern=true,label="Smart Wrench",recipe={minecraft_jj_dye_jj_4={need=2,tag=""},minecraft_jj_iron_ingot={need=1,tag=""}}},
 rftools_jj_solid_shield_block={hasPattern=false,label="",recipe={}},
 rftools_jj_solid_shield_block_opaque={hasPattern=false,label="",recipe={}},
 rftools_jj_space_chamber={hasPattern=true,label="Space Chamber Corner Block",recipe={minecraft_jj_dye_jj_4={need=4,tag=""},minecraft_jj_glass={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_space_chamber_card={hasPattern=true,label="Space Chamber Card",recipe={minecraft_jj_brick={need=2,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""}}},
 rftools_jj_space_chamber_controller={hasPattern=true,label="Space Chamber Controller Block",recipe={minecraft_jj_ender_pearl={need=2,tag=""},minecraft_jj_redstone_torch={need=2,tag=""},rftools_jj_space_chamber={need=1,tag=""}}},
 rftools_jj_spawner={hasPattern=true,label="Spawner",recipe={minecraft_jj_blaze_rod={need=1,tag=""},minecraft_jj_bone={need=1,tag=""},minecraft_jj_ender_pearl={need=1,tag=""},minecraft_jj_redstone={need=4,tag=""},minecraft_jj_rotten_flesh={need=1,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_speed_module={hasPattern=true,label="Speed Environmental Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_gold_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""},rftools_jj_syringe={need=1,tag=""}}},
 rftools_jj_speedplus_module={hasPattern=true,label="Speed Plus Environmental Module",recipe={rftools_jj_speed_module={need=1,tag=""},rftools_jj_syringe={need=2,tag=""}}},
 rftools_jj_storage_control_module={hasPattern=true,label="Storage Control Screen Module",recipe={minecraft_jj_crafting_table={need=1,tag=""},minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""}}},
 rftools_jj_storage_module={hasPattern=true,label="Tier 1 Storage Module",recipe={minecraft_jj_chest={need=1,tag=""},minecraft_jj_gold_nugget={need=2,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_quartz={need=2,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 rftools_jj_storage_module_jj_1={hasPattern=true,label="Tier 2 Storage Module",recipe={minecraft_jj_chest={need=1,tag=""},minecraft_jj_gold_ingot={need=2,tag=""},minecraft_jj_quartz={need=2,tag=""},minecraft_jj_redstone={need=1,tag=""},rftools_jj_storage_module={need=1,tag=""}}},
 rftools_jj_storage_module_jj_2={hasPattern=true,label="Tier 3 Storage Module",recipe={minecraft_jj_chest={need=1,tag=""},minecraft_jj_gold_block={need=2,tag=""},minecraft_jj_quartz_block={need=2,tag=""},minecraft_jj_redstone_block={need=1,tag=""},rftools_jj_storage_module_jj_1={need=1,tag=""}}},
 rftools_jj_storage_module_jj_6={hasPattern=true,label="Remote Storage Module",recipe={minecraft_jj_chest={need=1,tag=""},minecraft_jj_ender_pearl={need=2,tag=""},minecraft_jj_gold_nugget={need=2,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_quartz={need=2,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 rftools_jj_storage_module_tablet={hasPattern=true,label="Storage Tablet",recipe={minecraft_jj_emerald={need=1,tag=""},minecraft_jj_gold_nugget={need=4,tag=""},minecraft_jj_quartz_block={need=1,tag=""},minecraft_jj_redstone_block={need=3,tag=""}}},
 rftools_jj_storage_scanner={hasPattern=true,label="Storage Scanner",recipe={minecraft_jj_ender_pearl={need=2,tag=""},minecraft_jj_gold_ingot={need=2,tag=""},minecraft_jj_redstone_torch={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftools_jj_storage_terminal={hasPattern=true,label="Storage Terminal",recipe={minecraft_jj_ender_pearl={need=2,tag=""},minecraft_jj_glass={need=4,tag=""},minecraft_jj_paper={need=2,tag=""},rftools_jj_machine_base={need=1,tag=""}}},
 rftools_jj_support_block={hasPattern=false,label="",recipe={}},
 rftools_jj_syringe={hasPattern=true,label="Syringe",recipe={minecraft_jj_glass_bottle={need=1,tag=""},minecraft_jj_iron_ingot={need=2,tag=""}}},
 rftools_jj_teleport_probe={hasPattern=false,label="",recipe={}},
 rftools_jj_text_module={hasPattern=true,label="Text Screen Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_paper={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""}}},
 rftools_jj_timer_block={hasPattern=true,label="Timer",recipe={minecraft_jj_clock={need=1,tag=""},minecraft_jj_redstone={need=4,tag=""},minecraft_jj_redstone_torch={need=3,tag=""},rftools_jj_machine_base={need=1,tag=""}}},
 rftools_jj_waterbreathing_module={hasPattern=true,label="Water Breathing Environmental Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_gold_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""},rftools_jj_syringe={need=1,tag=""}}},
 rftools_jj_weakness_module={hasPattern=true,label="Weakness Environmental Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_dye_jj_4={need=2,tag=""},minecraft_jj_obsidian={need=1,tag=""},rftools_jj_syringe={need=1,tag=""}}},
 rftools_jj_wire_block={hasPattern=true,label="Wire",recipe={minecraft_jj_redstone={need=2,tag=""},rftools_jj_machine_base={need=1,tag=""}}},
 rftoolscontrol_jj_advanced_network_card={hasPattern=true,label="Advanced Network Card",recipe={minecraft_jj_emerald={need=2,tag=""},minecraft_jj_ender_pearl={need=2,tag=""},minecraft_jj_redstone={need=4,tag=""},rftoolscontrol_jj_network_card={need=1,tag=""}}},
 rftoolscontrol_jj_card_base={hasPattern=true,label="Card Base",recipe={minecraft_jj_dye_jj_2={need=3,tag=""},minecraft_jj_gold_nugget={need=3,tag=""},minecraft_jj_redstone={need=3,tag=""}}},
 rftoolscontrol_jj_console_module={hasPattern=true,label="Console Screen Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_glass_pane={need=4,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""},rftoolscontrol_jj_card_base={need=1,tag=""}}},
 rftoolscontrol_jj_cpu_core_1000={hasPattern=true,label="CPU Core S1000",recipe={minecraft_jj_diamond={need=2,tag=""},minecraft_jj_emerald={need=2,tag=""},minecraft_jj_redstone={need=4,tag=""},rftoolscontrol_jj_cpu_core_500={need=1,tag=""}}},
 rftoolscontrol_jj_cpu_core_2000={hasPattern=true,label="CPU Core EX2000",recipe={minecraft_jj_redstone={need=4,tag=""},rftools_jj_dimensional_shard={need=4,tag=""},rftoolscontrol_jj_cpu_core_1000={need=1,tag=""}}},
 rftoolscontrol_jj_cpu_core_500={hasPattern=true,label="CPU Core B500",recipe={minecraft_jj_gold_nugget={need=2,tag=""},minecraft_jj_paper={need=2,tag=""},minecraft_jj_redstone={need=4,tag=""},rftoolscontrol_jj_card_base={need=1,tag=""}}},
 rftoolscontrol_jj_crafting_card={hasPattern=true,label="Crafting Card",recipe={minecraft_jj_crafting_table={need=1,tag=""},minecraft_jj_paper={need=2,tag=""},rftoolscontrol_jj_card_base={need=1,tag=""}}},
 rftoolscontrol_jj_craftingstation={hasPattern=true,label="Crafting Station",recipe={minecraft_jj_crafting_table={need=2,tag=""},minecraft_jj_redstone={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""},rftoolscontrol_jj_card_base={need=2,tag=""}}},
 rftoolscontrol_jj_graphics_card={hasPattern=true,label="Graphics Card",recipe={minecraft_jj_glass={need=1,tag=""},minecraft_jj_glowstone={need=1,tag=""},minecraft_jj_quartz={need=4,tag=""},minecraft_jj_redstone={need=2,tag=""},rftoolscontrol_jj_card_base={need=1,tag=""}}},
 rftoolscontrol_jj_interaction_module={hasPattern=true,label="Interaction Screen Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""},minecraft_jj_stone_pressure_plate={need=2,tag=""},rftoolscontrol_jj_card_base={need=1,tag=""}}},
 rftoolscontrol_jj_network_card={hasPattern=true,label="Network Card",recipe={minecraft_jj_ender_pearl={need=1,tag=""},minecraft_jj_gold_nugget={need=2,tag=""},minecraft_jj_redstone={need=5,tag=""},rftoolscontrol_jj_card_base={need=1,tag=""}}},
 rftoolscontrol_jj_network_identifier={hasPattern=true,label="Network Identifier",recipe={minecraft_jj_comparator={need=1,tag=""},minecraft_jj_repeater={need=1,tag=""},rftoolscontrol_jj_card_base={need=1,tag=""}}},
 rftoolscontrol_jj_node={hasPattern=true,label="Node",recipe={minecraft_jj_ender_pearl={need=1,tag=""},minecraft_jj_redstone={need=6,tag=""},rftools_jj_machine_frame={need=1,tag=""},rftoolscontrol_jj_card_base={need=1,tag=""}}},
 rftoolscontrol_jj_processor={hasPattern=true,label="Processor",recipe={minecraft_jj_quartz={need=2,tag=""},minecraft_jj_redstone={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""},rftoolscontrol_jj_card_base={need=2,tag=""}}},
 rftoolscontrol_jj_program_card={hasPattern=true,label="Program Card",recipe={minecraft_jj_paper={need=3,tag=""},rftoolscontrol_jj_card_base={need=1,tag=""}}},
 rftoolscontrol_jj_programmer={hasPattern=true,label="Programmer",recipe={minecraft_jj_paper={need=2,tag=""},minecraft_jj_quartz={need=2,tag=""},minecraft_jj_redstone={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftoolscontrol_jj_ram_chip={hasPattern=true,label="RAM Chip 8E",recipe={minecraft_jj_paper={need=2,tag=""},minecraft_jj_redstone={need=6,tag=""},rftoolscontrol_jj_card_base={need=1,tag=""}}},
 rftoolscontrol_jj_rftoolscontrol_manual={hasPattern=true,label="RFTools Control Manual",recipe={minecraft_jj_book={need=1,tag=""},minecraft_jj_redstone={need=3,tag=""}}},
 rftoolscontrol_jj_tank={hasPattern=true,label="Multi Tank",recipe={minecraft_jj_glass={need=4,tag=""},minecraft_jj_iron_ingot={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftoolscontrol_jj_token={hasPattern=true,label="Token",recipe={minecraft_jj_paper={need=8,tag=""},rftoolscontrol_jj_card_base={need=1,tag=""}}},
 rftoolscontrol_jj_variable_module={hasPattern=true,label="Variable Screen Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""},rftoolscontrol_jj_card_base={need=1,tag=""}}},
 rftoolscontrol_jj_vectorart_module={hasPattern=true,label="Vector Art Screen Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_glass_pane={need=4,tag=""},minecraft_jj_glowstone_dust={need=2,tag=""},minecraft_jj_gold_ingot={need=1,tag=""},rftoolscontrol_jj_card_base={need=1,tag=""}}},
 rftoolscontrol_jj_workbench={hasPattern=true,label="Workbench",recipe={minecraft_jj_chest={need=1,tag=""},minecraft_jj_crafting_table={need=1,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftoolsdim_jj_activity_probe={hasPattern=true,label="Activity Probe",recipe={minecraft_jj_ender_pearl={need=2,tag=""},rftools_jj_dimensional_shard={need=6,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftoolsdim_jj_biome_absorber={hasPattern=true,label="Biome Absorber",recipe={minecraft_jj_dirt={need=2,tag=""},minecraft_jj_sapling={need=2,tag=""},minecraft_jj_wool={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftoolsdim_jj_dimension_builder={hasPattern=true,label="Dimension Builder",recipe={minecraft_jj_diamond={need=2,tag=""},minecraft_jj_emerald={need=1,tag=""},minecraft_jj_ender_pearl={need=2,tag=""},minecraft_jj_gold_ingot={need=3,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftoolsdim_jj_dimension_editor={hasPattern=true,label="Dimension Editor",recipe={minecraft_jj_diamond={need=2,tag=""},minecraft_jj_emerald={need=1,tag=""},minecraft_jj_gold_ingot={need=3,tag=""},minecraft_jj_redstone={need=2,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftoolsdim_jj_dimension_enscriber={hasPattern=true,label="Dimension Enscriber",recipe={minecraft_jj_dye={need=2,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_paper={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftoolsdim_jj_dimension_module={hasPattern=true,label="Dimension Screen Module",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_ender_pearl={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""}}},
 rftoolsdim_jj_dimension_monitor={hasPattern=true,label="Dimension Monitor",recipe={minecraft_jj_comparator={need=1,tag=""},minecraft_jj_redstone={need=3,tag=""},rftools_jj_dimensional_shard={need=1,tag=""}}},
 rftoolsdim_jj_dimensional_blank_block={hasPattern=true,label="Dimensional Blank Block",recipe={minecraft_jj_stone={need=8,tag=""},rftools_jj_dimensional_shard={need=1,tag=""}}},
 rftoolsdim_jj_dimensional_block={hasPattern=true,label="Dimensional Block",recipe={rftoolsdim_jj_dimensional_blank_block={need=1,tag=""}}},
 rftoolsdim_jj_dimensional_cross2_block={hasPattern=true,label="Dimensional Cross 2 Block",recipe={rftoolsdim_jj_dimensional_blank_block={need=5,tag=""}}},
 rftoolsdim_jj_dimensional_cross_block={hasPattern=true,label="Dimensional Cross Block",recipe={rftoolsdim_jj_dimensional_blank_block={need=5,tag=""}}},
 rftoolsdim_jj_dimensional_pattern1_block={hasPattern=true,label="Dimensional Pattern 1 Block",recipe={minecraft_jj_dye={need=2,tag=""},rftoolsdim_jj_dimensional_blank_block={need=7,tag=""}}},
 rftoolsdim_jj_dimensional_pattern2_block={hasPattern=true,label="Dimensional Pattern 2 Block",recipe={minecraft_jj_dye_jj_15={need=2,tag=""},rftoolsdim_jj_dimensional_blank_block={need=7,tag=""}}},
 rftoolsdim_jj_dimensional_small_blocks={hasPattern=true,label="Dimensional Small Blocks",recipe={rftoolsdim_jj_dimensional_blank_block={need=4,tag=""}}},
 rftoolsdim_jj_dimlet_base={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_control_circuit={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_control_circuit_jj_1={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_control_circuit_jj_2={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_control_circuit_jj_3={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_control_circuit_jj_4={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_control_circuit_jj_5={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_control_circuit_jj_6={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_energy_module={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_energy_module_jj_1={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_energy_module_jj_2={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_memory_unit={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_memory_unit_jj_1={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_memory_unit_jj_2={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_parcel={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_template={hasPattern=true,label="Dimlet Template",recipe={minecraft_jj_paper={need=1,tag=""},rftools_jj_dimensional_shard={need=8,tag=""}}},
 rftoolsdim_jj_dimlet_type_controller={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_type_controller_jj_1={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_type_controller_jj_10={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_type_controller_jj_11={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_type_controller_jj_12={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_type_controller_jj_13={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_type_controller_jj_14={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_type_controller_jj_2={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_type_controller_jj_3={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_type_controller_jj_4={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_type_controller_jj_5={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_type_controller_jj_6={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_type_controller_jj_7={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_type_controller_jj_8={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_type_controller_jj_9={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_dimlet_workbench={hasPattern=true,label="Dimlet Workbench",recipe={minecraft_jj_crafting_table={need=2,tag=""},minecraft_jj_gold_nugget={need=4,tag=""},minecraft_jj_redstone={need=1,tag=""},rftools_jj_machine_frame={need=1,tag=""},rftoolsdim_jj_dimlet_base={need=1,tag=""}}},
 rftoolsdim_jj_efficiency_essence={hasPattern=true,label="Efficiency Essence",recipe={minecraft_jj_diamond_pickaxe={need=1,tag=""},minecraft_jj_ender_eye={need=3,tag=""},minecraft_jj_nether_star={need=1,tag=""}}},
 rftoolsdim_jj_empty_dimension_tab={hasPattern=true,label="Empty Dimension Tab",recipe={minecraft_jj_paper={need=5,tag=""},minecraft_jj_redstone={need=4,tag=""}}},
 rftoolsdim_jj_energy_extractor={hasPattern=true,label="Energy Extractor",recipe={minecraft_jj_ender_pearl={need=1,tag=""},minecraft_jj_redstone_block={need=4,tag=""},rftools_jj_dimensional_shard={need=3,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftoolsdim_jj_fake_gravel={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_fake_sand={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_fake_water={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_feature_absorber={hasPattern=true,label="Feature Absorber",recipe={minecraft_jj_diamond={need=2,tag=""},minecraft_jj_emerald={need=2,tag=""},minecraft_jj_wool={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftoolsdim_jj_known_dimlet_jj_1={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_known_dimlet_jj_10={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_known_dimlet_jj_12={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_known_dimlet_jj_13={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_known_dimlet_jj_2={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_known_dimlet_jj_3={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_known_dimlet_jj_4={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_known_dimlet_jj_5={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_known_dimlet_jj_6={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_known_dimlet_jj_7={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_known_dimlet_jj_8={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_known_dimlet_jj_9={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_liquid_absorber={hasPattern=true,label="Liquid Absorber",recipe={minecraft_jj_bucket={need=4,tag=""},minecraft_jj_wool={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftoolsdim_jj_material_absorber={hasPattern=true,label="Material Absorber",recipe={minecraft_jj_cobblestone={need=1,tag=""},minecraft_jj_dirt={need=1,tag=""},minecraft_jj_gravel={need=1,tag=""},minecraft_jj_sand={need=1,tag=""},minecraft_jj_wool={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftoolsdim_jj_mediocre_efficiency_essence={hasPattern=true,label="Mediocre Efficiency Essence",recipe={minecraft_jj_ender_eye={need=3,tag=""},minecraft_jj_ghast_tear={need=1,tag=""},minecraft_jj_iron_pickaxe={need=1,tag=""}}},
 rftoolsdim_jj_phased_field_generator={hasPattern=true,label="Phased Field Generator",recipe={minecraft_jj_ender_eye={need=1,tag=""},minecraft_jj_redstone={need=4,tag=""},rftools_jj_dimensional_shard={need=4,tag=""}}},
 rftoolsdim_jj_realized_dimension_tab={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_rftoolsdim_manual={hasPattern=true,label="RFTools Dimension Manual",recipe={minecraft_jj_book={need=1,tag=""},minecraft_jj_redstone={need=4,tag=""}}},
 rftoolsdim_jj_structure_essence={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_structure_essence_jj_1={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_structure_essence_jj_10={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_structure_essence_jj_11={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_structure_essence_jj_2={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_structure_essence_jj_3={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_structure_essence_jj_4={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_structure_essence_jj_5={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_structure_essence_jj_6={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_structure_essence_jj_7={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_structure_essence_jj_8={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_structure_essence_jj_9={hasPattern=false,label="",recipe={}},
 rftoolsdim_jj_terrain_absorber={hasPattern=true,label="Terrain Absorber",recipe={minecraft_jj_dirt={need=2,tag=""},minecraft_jj_stone={need=2,tag=""},minecraft_jj_wool={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""}}},
 rftoolsdim_jj_time_absorber={hasPattern=true,label="Time Absorber",recipe={minecraft_jj_clock={need=4,tag=""},minecraft_jj_wool={need=4,tag=""},rftools_jj_machine_frame={need=1,tag=""}}}
 }