return {
 advancedrocketry_jj_advrocketmotor={hasPattern=true,label="Verbesserter Flüßigtreibstoff",recipe={advancedrocketry_jj_productingot={need=3,tag=""},advancedrocketry_jj_productplate_jj_1={need=3,tag=""}}},
 advancedrocketry_jj_airlock_door={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_alienleaves={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_aliensapling={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_alienwood={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_altitudecontroller={hasPattern=true,label="Flughöhensteuerung",recipe={advancedrocketry_jj_ic={need=1,tag=""},advancedrocketry_jj_misc={need=1,tag=""},libvulpes_jj_structuremachine={need=1,tag=""}}},
 advancedrocketry_jj_arcfurnace={hasPattern=true,label="Elektrischer Hochofen",recipe={advancedrocketry_jj_blastbrick={need=1,tag=""},advancedrocketry_jj_ic_jj_3={need=1,tag=""},advancedrocketry_jj_ic_jj_4={need=1,tag=""},advancedrocketry_jj_misc={need=1,tag=""},ic2_jj_ingot_jj_2={need=1,tag=""},mekanism_jj_ingot_jj_5={need=1,tag=""},minecraft_jj_netherbrick={need=4,tag=""}}},
 advancedrocketry_jj_asteroidchip={hasPattern=true,label="Asteroiden Chip",recipe={advancedrocketry_jj_dataunit={need=1,tag=""},advancedrocketry_jj_ic_jj_1={need=1,tag=""}}},
 advancedrocketry_jj_astrobed={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_atmanalyser={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_basiclasergun={hasPattern=true,label="Einfache Laserpistole",recipe={minecraft_jj_emerald={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_redstone={need=1,tag=""},refinedstorage_jj_silicon={need=1,tag=""}}},
 advancedrocketry_jj_beacon={hasPattern=true,label="Leuchtfeuer",recipe={advancedrocketry_jj_ic_jj_1={need=1,tag=""},advancedrocketry_jj_ic_jj_3={need=1,tag=""},libvulpes_jj_coil0_jj_4={need=2,tag=""},libvulpes_jj_productsheet_jj_1={need=2,tag=""},libvulpes_jj_structuremachine={need=1,tag=""}}},
 advancedrocketry_jj_beaconfinder={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_biomechanger={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_biomescanner={hasPattern=true,label="Biomenscanner",recipe={advancedrocketry_jj_satelliteprimaryfunction_jj_5={need=1,tag=""},ic2_jj_plate_jj_8={need=5,tag=""},libvulpes_jj_battery={need=2,tag=""},libvulpes_jj_productplate_jj_5={need=5,tag=""},libvulpes_jj_structuremachine={need=1,tag=""}}},
 advancedrocketry_jj_blackholegenerator={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_blastbrick={hasPattern=false,label="",recipe={minecraft_jj_brick_block={need=4,tag=""},minecraft_jj_magma_cream={need=2,tag=""}}},
 advancedrocketry_jj_blocklens={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_buckethydrogen={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_bucketnitrogen={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_bucketoxygen={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_bucketrocketfuel={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_carbonscrubbercartridge={hasPattern=true,label="Carbonsammlungskassete",recipe={libvulpes_jj_productsheet_jj_1={need=6,tag=""},minecraft_jj_iron_bars={need=3,tag=""}}},
 advancedrocketry_jj_charcoallog={hasPattern=true,label="Holzkohlenholzscheit",recipe={minecraft_jj_coal_jj_1={need=8,tag=""},minecraft_jj_log={need=1,tag=""}}},
 advancedrocketry_jj_chemicalreactor={hasPattern=true,label="Chemischer Reaktor",recipe={advancedrocketry_jj_ic={need=2,tag=""},advancedrocketry_jj_ic_jj_3={need=1,tag=""},advancedrocketry_jj_ic_jj_4={need=1,tag=""},advancedrocketry_jj_ic_jj_5={need=1,tag=""},advancedrocketry_jj_misc={need=1,tag=""},ic2_jj_plate_jj_2={need=2,tag=""},libvulpes_jj_productplate_jj_2={need=2,tag=""},libvulpes_jj_structuremachine={need=1,tag=""}}},
 advancedrocketry_jj_circlelight={hasPattern=true,label="Raumstationsbeleuchtung",recipe={libvulpes_jj_productsheet_jj_1={need=1,tag=""},minecraft_jj_glowstone={need=1,tag=""}}},
 advancedrocketry_jj_concrete={hasPattern=true,label="Asphalttile.lathe.name=Drechselbank",recipe={minecraft_jj_gravel={need=1,tag=""},minecraft_jj_sand={need=1,tag=""},minecraft_jj_water_bucket={need=1,tag=""}}},
 advancedrocketry_jj_crystal={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_crystal_jj_1={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_crystal_jj_2={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_crystal_jj_3={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_crystal_jj_4={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_crystal_jj_5={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_crystallizer={hasPattern=true,label="Kristallisierer",recipe={advancedrocketry_jj_ic_jj_3={need=1,tag=""},advancedrocketry_jj_ic_jj_4={need=1,tag=""},advancedrocketry_jj_misc={need=1,tag=""},ic2_jj_plate_jj_7={need=1,tag=""},libvulpes_jj_productplate_jj_6={need=1,tag=""},libvulpes_jj_structuremachine={need=1,tag=""},minecraft_jj_quartz={need=2,tag=""},minecraft_jj_repeater={need=2,tag=""}}},
 advancedrocketry_jj_cuttingmachine={hasPattern=true,label="Schneidemaschine",recipe={advancedrocketry_jj_ic_jj_3={need=1,tag=""},advancedrocketry_jj_ic_jj_4={need=1,tag=""},advancedrocketry_jj_misc={need=1,tag=""},ic2_jj_plate_jj_7={need=1,tag=""},libvulpes_jj_productgear_jj_6={need=2,tag=""},libvulpes_jj_productplate_jj_6={need=1,tag=""},libvulpes_jj_structuremachine={need=1,tag=""},minecraft_jj_obsidian={need=2,tag=""},thermalfoundation_jj_material_jj_288={need=2,tag=""}}},
 advancedrocketry_jj_datapipe={hasPattern=true,label="Datenkabel",recipe={advancedrocketry_jj_productplate_jj_1={need=4,tag=""},refinedstorage_jj_cable={need=1,tag=""}}},
 advancedrocketry_jj_dataunit={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_deployablerocketbuilder={hasPattern=true,label="Unbemannte Raketen Monteur",recipe={advancedrocketry_jj_productgear={need=2,tag=""},advancedrocketry_jj_productrod={need=2,tag=""},advancedrocketry_jj_rocketbuilder={need=1,tag=""},libvulpes_jj_productdust={need=4,tag=""},taiga_jj_dilithium_dust={need=4,tag=""}}},
 advancedrocketry_jj_drill={hasPattern=true,label="Bohrer",recipe={libvulpes_jj_structuremachine={need=1,tag=""},minecraft_jj_iron_pickaxe={need=1,tag=""}}},
 advancedrocketry_jj_electricmushroom={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_electrolyser={hasPattern=true,label="Elektrolyseur",recipe={advancedrocketry_jj_ic={need=2,tag=""},advancedrocketry_jj_ic_jj_3={need=1,tag=""},advancedrocketry_jj_ic_jj_5={need=1,tag=""},advancedrocketry_jj_misc={need=1,tag=""},ic2_jj_plate_jj_7={need=2,tag=""},libvulpes_jj_productplate_jj_6={need=2,tag=""},libvulpes_jj_structuremachine={need=1,tag=""},minecraft_jj_redstone_torch={need=1,tag=""}}},
 advancedrocketry_jj_elevatorchip={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_energypipe={hasPattern=true,label="Energiekabel",recipe={advancedrocketry_jj_productplate_jj_1={need=4,tag=""},mekanism_jj_transmitter={need=1,tag=""}}},
 advancedrocketry_jj_forcefield={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_forcefieldprojector={hasPattern=true,label="Kraftfeldgenerator",recipe={libvulpes_jj_coil0_jj_4={need=1,tag=""},libvulpes_jj_productcrystal={need=1,tag=""},libvulpes_jj_productplate_jj_9={need=4,tag=""},libvulpes_jj_structuremachine={need=1,tag=""},taiga_jj_dilithium_crystal={need=1,tag=""},thermalfoundation_jj_material_jj_324={need=4,tag=""}}},
 advancedrocketry_jj_fuelingstation={hasPattern=true,label="Befüllungstation",recipe={advancedrocketry_jj_ic_jj_5={need=1,tag=""},advancedrocketry_jj_misc={need=1,tag=""},ic2_jj_plate_jj_8={need=3,tag=""},libvulpes_jj_productfan_jj_6={need=1,tag=""},libvulpes_jj_productplate_jj_5={need=3,tag=""},libvulpes_jj_structuremachine={need=3,tag=""}}},
 advancedrocketry_jj_fueltank={hasPattern=true,label="Treibstofftank",recipe={ic2_jj_plate_jj_7={need=2,tag=""},libvulpes_jj_productplate_jj_6={need=2,tag=""},libvulpes_jj_productrod_jj_6={need=4,tag=""}}},
 advancedrocketry_jj_geode={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_gravitycontroller={hasPattern=true,label="Gravitationssteuerung",recipe={libvulpes_jj_structuremachine={need=1,tag=""},minecraft_jj_piston={need=1,tag=""},minecraft_jj_redstone_block={need=1,tag=""}}},
 advancedrocketry_jj_gravitymachine={hasPattern=true,label="Gravitationsveränderer",recipe={advancedrocketry_jj_satelliteprimaryfunction_jj_2={need=1,tag=""},advancedrocketry_jj_warpcore={need=1,tag=""},libvulpes_jj_productsheet_jj_7={need=4,tag=""}}},
 advancedrocketry_jj_guidancecomputer={hasPattern=true,label="Raketenflugcomputer",recipe={advancedrocketry_jj_ic_jj_1={need=4,tag=""},libvulpes_jj_productplate_jj_7={need=1,tag=""},libvulpes_jj_structuremachine={need=1,tag=""},minecraft_jj_redstone={need=3,tag=""},techreborn_jj_plates_jj_30={need=1,tag=""}}},
 advancedrocketry_jj_hotturf={hasPattern=true,label="Oxidierter Eisensand",recipe={mekanism_jj_dust={need=8,tag=""},minecraft_jj_lava_bucket={need=1,tag=""}}},
 advancedrocketry_jj_hydrogenfluid={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_ic={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_ic_jj_1={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_ic_jj_2={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_ic_jj_3={hasPattern=false,label="",recipe={libvulpes_jj_productdust_jj_4={need=4,tag=""},libvulpes_jj_productplate_jj_1={need=1,tag=""},minecraft_jj_diamond={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""},minecraft_jj_wooden_slab={need=1,tag=""}}},
 advancedrocketry_jj_ic_jj_4={hasPattern=false,label="",recipe={libvulpes_jj_productdust_jj_2={need=4,tag=""},libvulpes_jj_productplate_jj_1={need=1,tag=""},minecraft_jj_diamond={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""},minecraft_jj_wooden_slab={need=1,tag=""}}},
 advancedrocketry_jj_ic_jj_5={hasPattern=false,label="",recipe={libvulpes_jj_productplate_jj_1={need=1,tag=""},minecraft_jj_diamond={need=1,tag=""},minecraft_jj_dye_jj_4={need=4,tag=""},minecraft_jj_redstone={need=2,tag=""},minecraft_jj_wooden_slab={need=1,tag=""}}},
 advancedrocketry_jj_intake={hasPattern=true,label="Gas Einlass",recipe={libvulpes_jj_productrod_jj_7={need=4,tag=""},libvulpes_jj_structuremachine={need=1,tag=""},minecraft_jj_hopper={need=4,tag=""}}},
 advancedrocketry_jj_itemcircuitplate={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_itemcircuitplate_jj_1={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_itemupgrade={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_itemupgrade_jj_1={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_itemupgrade_jj_2={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_itemupgrade_jj_3={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_itemupgrade_jj_4={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_jackhammer={hasPattern=true,label="Jackhammer",recipe={libvulpes_jj_motor={need=1,tag=""},libvulpes_jj_productplate_jj_9={need=2,tag=""},libvulpes_jj_productrod_jj_1={need=2,tag=""},libvulpes_jj_productrod_jj_7={need=1,tag=""},minecraft_jj_diamond={need=1,tag=""},thermalfoundation_jj_material_jj_324={need=2,tag=""}}},
 advancedrocketry_jj_jetpack={hasPattern=true,label="Raketenrucksack",recipe={advancedrocketry_jj_pressuretank={need=2,tag=""},ic2_jj_plate_jj_7={need=1,tag=""},libvulpes_jj_productplate_jj_6={need=1,tag=""},minecraft_jj_fire_charge={need=2,tag=""},minecraft_jj_lever={need=2,tag=""},minecraft_jj_string={need=1,tag=""}}},
 advancedrocketry_jj_landingpad={hasPattern=true,label="Landerampe",recipe={advancedrocketry_jj_concrete={need=1,tag=""},advancedrocketry_jj_ic_jj_1={need=1,tag=""}}},
 advancedrocketry_jj_lathe={hasPattern=true,label="Lathe",recipe={advancedrocketry_jj_ic_jj_3={need=1,tag=""},advancedrocketry_jj_ic_jj_4={need=1,tag=""},advancedrocketry_jj_misc={need=1,tag=""},ic2_jj_plate_jj_7={need=2,tag=""},libvulpes_jj_productgear_jj_6={need=1,tag=""},libvulpes_jj_productplate_jj_6={need=2,tag=""},libvulpes_jj_productrod_jj_1={need=2,tag=""},libvulpes_jj_structuremachine={need=1,tag=""},thermalfoundation_jj_material_jj_288={need=1,tag=""}}},
 advancedrocketry_jj_launchpad={hasPattern=false,label="",recipe={advancedrocketry_jj_concrete={need=1,tag=""},minecraft_jj_dye={need=1,tag=""},minecraft_jj_dye_jj_11={need=1,tag=""}}},
 advancedrocketry_jj_lens={hasPattern=true,label="Einfache Linse",recipe={minecraft_jj_glass_pane={need=3,tag=""}}},
 advancedrocketry_jj_lightsource={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_liquidpipe={hasPattern=true,label="Flüßigkeitenrohr",recipe={advancedrocketry_jj_productplate_jj_1={need=4,tag=""},mekanism_jj_transmitter_jj_1={need=1,tag=""}}},
 advancedrocketry_jj_liquidtank={hasPattern=true,label="Drucktank",recipe={advancedrocketry_jj_pressuretank_jj_3={need=6,tag=""},minecraft_jj_glass_pane={need=3,tag=""}}},
 advancedrocketry_jj_loader={hasPattern=true,label="Datenübertragungskabel",recipe={advancedrocketry_jj_dataunit={need=1,tag=""},libvulpes_jj_structuremachine={need=1,tag=""}}},
 advancedrocketry_jj_loader_jj_1={hasPattern=true,label="Satellitenkapsel",recipe={libvulpes_jj_productrod_jj_7={need=4,tag=""},libvulpes_jj_structuremachine={need=1,tag=""}}},
 advancedrocketry_jj_loader_jj_2={hasPattern=true,label="Raketen Entlader",recipe={advancedrocketry_jj_ic_jj_1={need=1,tag=""},libvulpes_jj_hatch_jj_1={need=1,tag=""}}},
 advancedrocketry_jj_loader_jj_3={hasPattern=true,label="Raketen Belader",recipe={advancedrocketry_jj_ic_jj_1={need=1,tag=""},libvulpes_jj_hatch={need=1,tag=""}}},
 advancedrocketry_jj_loader_jj_4={hasPattern=true,label="Flüßigkeits Entlader",recipe={advancedrocketry_jj_ic_jj_1={need=1,tag=""},libvulpes_jj_hatch_jj_3={need=1,tag=""}}},
 advancedrocketry_jj_loader_jj_5={hasPattern=true,label="Flüßigkeits Belader",recipe={advancedrocketry_jj_ic_jj_1={need=1,tag=""},libvulpes_jj_hatch_jj_2={need=1,tag=""}}},
 advancedrocketry_jj_loader_jj_6={hasPattern=true,label="Guidance Computer Access Hatch",recipe={advancedrocketry_jj_ic_jj_3={need=2,tag=""},libvulpes_jj_productrod_jj_4={need=2,tag=""},libvulpes_jj_structuremachine={need=1,tag=""}}},
 advancedrocketry_jj_metal0={hasPattern=true,label="Titanaluminide Block",recipe={advancedrocketry_jj_productingot={need=9,tag=""}}},
 advancedrocketry_jj_metal0_jj_1={hasPattern=true,label="Titanium Iridium Legierung Block",recipe={advancedrocketry_jj_productingot_jj_1={need=9,tag=""}}},
 advancedrocketry_jj_microwavereciever={hasPattern=true,label="Mikrowellenstrahlungs Fänger",recipe={advancedrocketry_jj_ic_jj_1={need=1,tag=""},advancedrocketry_jj_ic_jj_2={need=2,tag=""},advancedrocketry_jj_ic_jj_3={need=1,tag=""},advancedrocketry_jj_satelliteprimaryfunction={need=1,tag=""},ic2_jj_plate_jj_2={need=3,tag=""},libvulpes_jj_productplate_jj_2={need=3,tag=""},libvulpes_jj_structuremachine={need=1,tag=""}}},
 advancedrocketry_jj_misc={hasPattern=true,label="Nutzer Interface",recipe={minecraft_jj_dye_jj_10={need=2,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_glowstone_dust={need=2,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 advancedrocketry_jj_misc_jj_1={hasPattern=true,label="Carbonziegel",recipe={minecraft_jj_coal_jj_1={need=6,tag=""}}},
 advancedrocketry_jj_monitoringstation={hasPattern=true,label="Raketenbeobachtungsmonitor",recipe={advancedrocketry_jj_satelliteprimaryfunction={need=1,tag=""},libvulpes_jj_battery={need=1,tag=""},libvulpes_jj_productrod_jj_4={need=6,tag=""},libvulpes_jj_structuremachine={need=1,tag=""}}},
 advancedrocketry_jj_moonturf={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_moonturf_dark={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_nitrogenfluid={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_observatory={hasPattern=true,label="Observatorium",recipe={advancedrocketry_jj_misc={need=1,tag=""},libvulpes_jj_productrod_jj_1={need=3,tag=""},libvulpes_jj_structuremachine={need=1,tag=""},minecraft_jj_glass_pane={need=2,tag=""}}},
 advancedrocketry_jj_orescanner={hasPattern=true,label="Erzscanner",recipe={advancedrocketry_jj_ic_jj_2={need=1,tag=""},advancedrocketry_jj_misc={need=1,tag=""},libvulpes_jj_battery={need=2,tag=""},minecraft_jj_lever={need=2,tag=""}}},
 advancedrocketry_jj_orientationcontroller={hasPattern=true,label="Richtungssteuerung",recipe={advancedrocketry_jj_misc={need=1,tag=""},libvulpes_jj_structuremachine={need=1,tag=""},minecraft_jj_compass={need=1,tag=""}}},
 advancedrocketry_jj_oxygencharger={hasPattern=true,label="Gasaufladeplatte",recipe={advancedrocketry_jj_fueltank={need=2,tag=""},advancedrocketry_jj_misc={need=1,tag=""},ic2_jj_plate_jj_7={need=2,tag=""},libvulpes_jj_productfan_jj_6={need=2,tag=""},libvulpes_jj_productplate_jj_6={need=2,tag=""},libvulpes_jj_structuremachine={need=1,tag=""},minecraft_jj_heavy_weighted_pressure_plate={need=1,tag=""}}},
 advancedrocketry_jj_oxygendetection={hasPattern=true,label="Atmospherendetektor",recipe={advancedrocketry_jj_ic={need=1,tag=""},advancedrocketry_jj_misc={need=1,tag=""},ic2_jj_plate_jj_7={need=4,tag=""},libvulpes_jj_productfan_jj_6={need=1,tag=""},libvulpes_jj_productplate_jj_6={need=4,tag=""},libvulpes_jj_structuremachine={need=1,tag=""},minecraft_jj_iron_bars={need=1,tag=""}}},
 advancedrocketry_jj_oxygenfluid={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_oxygenscrubber={hasPattern=true,label="CO2 Reiniger",recipe={advancedrocketry_jj_misc_jj_1={need=1,tag=""},libvulpes_jj_motor={need=1,tag=""},libvulpes_jj_productfan_jj_6={need=1,tag=""},minecraft_jj_iron_bars={need=6,tag=""}}},
 advancedrocketry_jj_oxygenvent={hasPattern=true,label="Sauerstofflüftung",recipe={advancedrocketry_jj_fueltank={need=1,tag=""},libvulpes_jj_motor={need=1,tag=""},libvulpes_jj_productfan_jj_6={need=1,tag=""},minecraft_jj_iron_bars={need=6,tag=""}}},
 advancedrocketry_jj_pipesealer={hasPattern=true,label="Rohrdichtung",recipe={libvulpes_jj_productrod_jj_1={need=1,tag=""},minecraft_jj_clay_ball={need=4,tag=""}}},
 advancedrocketry_jj_planetanalyser={hasPattern=true,label="Planetenbeobachter",recipe={advancedrocketry_jj_ic_jj_1={need=2,tag=""},advancedrocketry_jj_misc={need=1,tag=""},advancedrocketry_jj_planetidchip={need=2,tag=""},ic2_jj_plate_jj_8={need=3,tag=""},libvulpes_jj_productplate_jj_5={need=3,tag=""},libvulpes_jj_structuremachine={need=1,tag=""}}},
 advancedrocketry_jj_planetholoselector={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_planetidchip={hasPattern=true,label="Planeten Id Chip",recipe={advancedrocketry_jj_ic={need=2,tag=""},advancedrocketry_jj_satelliteidchip={need=1,tag=""}}},
 advancedrocketry_jj_planetselector={hasPattern=false,label="",recipe={advancedrocketry_jj_guidancecomputer={need=1,tag=""},advancedrocketry_jj_ic_jj_1={need=4,tag=""},advancedrocketry_jj_satelliteprimaryfunction={need=1,tag=""},minecraft_jj_lever={need=2,tag=""},minecraft_jj_stone_button={need=1,tag=""}}},
 advancedrocketry_jj_planks={hasPattern=false,label="",recipe={advancedrocketry_jj_alienwood={need=1,tag=""}}},
 advancedrocketry_jj_platepress={hasPattern=true,label="Kleine Plattenpresse",recipe={minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_piston={need=1,tag=""}}},
 advancedrocketry_jj_precisionassemblingmachine={hasPattern=true,label="Prezisionsmonteur",recipe={advancedrocketry_jj_ic_jj_3={need=1,tag=""},advancedrocketry_jj_ic_jj_4={need=1,tag=""},advancedrocketry_jj_misc={need=1,tag=""},libvulpes_jj_productgear_jj_6={need=1,tag=""},libvulpes_jj_structuremachine={need=1,tag=""},minecraft_jj_diamond={need=1,tag=""},minecraft_jj_dropper={need=1,tag=""},minecraft_jj_furnace={need=1,tag=""},minecraft_jj_repeater={need=1,tag=""},thermalfoundation_jj_material_jj_288={need=1,tag=""}}},
 advancedrocketry_jj_pressuretank={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_pressuretank_jj_1={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_pressuretank_jj_2={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_pressuretank_jj_3={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_productboule={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_productcrystal={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_productdust={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_productdust_jj_1={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_productfan={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_productgear={hasPattern=true,label="Titanaluminide Gear",recipe={advancedrocketry_jj_productingot={need=1,tag=""},advancedrocketry_jj_productplate={need=2,tag=""},advancedrocketry_jj_productrod={need=4,tag=""}}},
 advancedrocketry_jj_productgear_jj_1={hasPattern=true,label="Titanium Iridium Legierung Gear",recipe={advancedrocketry_jj_productingot_jj_1={need=1,tag=""},advancedrocketry_jj_productplate_jj_1={need=2,tag=""},advancedrocketry_jj_productrod_jj_1={need=4,tag=""}}},
 advancedrocketry_jj_productingot={hasPattern=true,label="Titanaluminide Ingot",recipe={advancedrocketry_jj_metal0={need=1,tag=""}}},
 advancedrocketry_jj_productingot_jj_1={hasPattern=true,label="Titanium Iridium Legierung Ingot",recipe={advancedrocketry_jj_metal0_jj_1={need=1,tag=""}}},
 advancedrocketry_jj_productnugget={hasPattern=true,label="Titanaluminide Nugget",recipe={advancedrocketry_jj_productingot={need=1,tag=""}}},
 advancedrocketry_jj_productnugget_jj_1={hasPattern=true,label="Titanium Iridium Legierung Nugget",recipe={advancedrocketry_jj_productingot_jj_1={need=1,tag=""}}},
 advancedrocketry_jj_productplate={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_productplate_jj_1={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_productrod={hasPattern=true,label="Titanaluminide Rod",recipe={advancedrocketry_jj_productingot={need=3,tag=""}}},
 advancedrocketry_jj_productrod_jj_1={hasPattern=true,label="Titanium Iridium Legierung Rod",recipe={advancedrocketry_jj_productingot_jj_1={need=3,tag=""}}},
 advancedrocketry_jj_productsheet={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_productsheet_jj_1={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_quartzcrucible={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_railgun={hasPattern=false,label="",recipe={advancedrocketry_jj_ic_jj_1={need=1,tag=""},advancedrocketry_jj_ic_jj_3={need=1,tag=""},advancedrocketry_jj_ic_jj_4={need=1,tag=""},libvulpes_jj_advstructuremachine={need=1,tag=""},libvulpes_jj_coil0_jj_4={need=1,tag=""},libvulpes_jj_productfan_jj_6={need=2,tag=""}}},
 advancedrocketry_jj_rocketbuilder={hasPattern=true,label="Raketenmonteur",recipe={advancedrocketry_jj_concrete={need=1,tag=""},advancedrocketry_jj_ic_jj_3={need=2,tag=""},advancedrocketry_jj_misc={need=1,tag=""},libvulpes_jj_productgear_jj_7={need=2,tag=""},libvulpes_jj_productrod_jj_7={need=2,tag=""},libvulpes_jj_structuremachine={need=1,tag=""}}},
 advancedrocketry_jj_rocketfuel={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_rocketmotor={hasPattern=true,label="Flüßigtreibstoff Triebwerk",recipe={ic2_jj_ingot_jj_5={need=3,tag=""},libvulpes_jj_productingot_jj_6={need=3,tag=""},libvulpes_jj_productplate_jj_7={need=3,tag=""},techreborn_jj_plates_jj_30={need=3,tag=""}}},
 advancedrocketry_jj_rollingmachine={hasPattern=true,label="Walzenmaschine",recipe={advancedrocketry_jj_ic_jj_3={need=1,tag=""},advancedrocketry_jj_ic_jj_4={need=1,tag=""},advancedrocketry_jj_ic_jj_5={need=1,tag=""},advancedrocketry_jj_misc={need=1,tag=""},libvulpes_jj_productgear_jj_6={need=2,tag=""},libvulpes_jj_structuremachine={need=1,tag=""},minecraft_jj_iron_block={need=2,tag=""},thermalfoundation_jj_material_jj_288={need=2,tag=""}}},
 advancedrocketry_jj_satellite={hasPattern=true,label="Satellit",recipe={advancedrocketry_jj_ic_jj_3={need=1,tag=""},libvulpes_jj_productrod_jj_7={need=2,tag=""},libvulpes_jj_productsheet_jj_9={need=6,tag=""}}},
 advancedrocketry_jj_satellitebuilder={hasPattern=true,label="Satellitenkonstrukteur",recipe={advancedrocketry_jj_dataunit={need=1,tag=""},advancedrocketry_jj_ic={need=2,tag=""},advancedrocketry_jj_sawblade={need=1,tag=""},libvulpes_jj_motor={need=1,tag=""},libvulpes_jj_productplate_jj_7={need=1,tag=""},libvulpes_jj_structuremachine={need=1,tag=""},minecraft_jj_anvil={need=1,tag=""},minecraft_jj_hopper={need=1,tag=""},techreborn_jj_plates_jj_30={need=1,tag=""}}},
 advancedrocketry_jj_satellitecontrolcenter={hasPattern=true,label="Satellitenterminal",recipe={advancedrocketry_jj_misc={need=1,tag=""},advancedrocketry_jj_satelliteprimaryfunction={need=2,tag=""},libvulpes_jj_battery={need=1,tag=""},libvulpes_jj_productrod_jj_4={need=2,tag=""},libvulpes_jj_structuremachine={need=1,tag=""},minecraft_jj_repeater={need=2,tag=""}}},
 advancedrocketry_jj_satelliteidchip={hasPattern=true,label="Satelliten ID Chip",recipe={advancedrocketry_jj_ic={need=1,tag=""}}},
 advancedrocketry_jj_satellitepowersource={hasPattern=true,label="Einfache Solarpanelen",recipe={ic2_jj_plate_jj_2={need=3,tag=""},libvulpes_jj_productplate_jj_2={need=3,tag=""},minecraft_jj_glowstone_dust={need=3,tag=""},minecraft_jj_redstone={need=3,tag=""}}},
 advancedrocketry_jj_satellitepowersource_jj_1={hasPattern=true,label="Große Solarpanelen",recipe={advancedrocketry_jj_satellitepowersource={need=6,tag=""}}},
 advancedrocketry_jj_satelliteprimaryfunction={hasPattern=true,label="Optischer Sensor",recipe={ic2_jj_plate_jj_2={need=1,tag=""},libvulpes_jj_productplate_jj_2={need=1,tag=""},minecraft_jj_glass_pane={need=3,tag=""},minecraft_jj_glowstone_dust={need=1,tag=""}}},
 advancedrocketry_jj_satelliteprimaryfunction_jj_1={hasPattern=true,label="Zusamensetzungs Sensor",recipe={advancedrocketry_jj_ic={need=1,tag=""},advancedrocketry_jj_ic_jj_1={need=1,tag=""},advancedrocketry_jj_satelliteprimaryfunction={need=2,tag=""},advancedrocketry_jj_wafer={need=2,tag=""}}},
 advancedrocketry_jj_satelliteprimaryfunction_jj_2={hasPattern=true,label="Massendetektor",recipe={advancedrocketry_jj_ic={need=1,tag=""},advancedrocketry_jj_satelliteprimaryfunction={need=2,tag=""},advancedrocketry_jj_wafer={need=2,tag=""},libvulpes_jj_productcrystal={need=1,tag=""},taiga_jj_dilithium_crystal={need=1,tag=""}}},
 advancedrocketry_jj_satelliteprimaryfunction_jj_3={hasPattern=true,label="Mikrowellenstrahlungs Sender",recipe={advancedrocketry_jj_ic={need=1,tag=""},advancedrocketry_jj_ic_jj_1={need=1,tag=""},advancedrocketry_jj_lens={need=2,tag=""},advancedrocketry_jj_wafer={need=2,tag=""}}},
 advancedrocketry_jj_satelliteprimaryfunction_jj_4={hasPattern=true,label="Erzkarograph",recipe={advancedrocketry_jj_ic_jj_1={need=2,tag=""},advancedrocketry_jj_orescanner={need=1,tag=""},libvulpes_jj_productrod_jj_4={need=1,tag=""},libvulpes_jj_productsheet_jj_1={need=3,tag=""}}},
 advancedrocketry_jj_satelliteprimaryfunction_jj_5={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_sawblade={hasPattern=true,label="Sägeblatt",recipe={advancedrocketry_jj_sawbladeiron={need=1,tag=""},ic2_jj_plate_jj_3={need=4,tag=""},libvulpes_jj_productplate_jj_1={need=4,tag=""},libvulpes_jj_productrod_jj_1={need=2,tag=""}}},
 advancedrocketry_jj_sawbladeiron={hasPattern=false,label="",recipe={libvulpes_jj_productplate_jj_1={need=4,tag=""},libvulpes_jj_productrod_jj_1={need=1,tag=""}}},
 advancedrocketry_jj_sealdetector={hasPattern=true,label="Dichtungsdetektor",recipe={advancedrocketry_jj_ic_jj_2={need=2,tag=""},advancedrocketry_jj_misc={need=1,tag=""},advancedrocketry_jj_productgear_jj_1={need=2,tag=""},minecraft_jj_iron_ingot={need=4,tag=""}}},
 advancedrocketry_jj_seat={hasPattern=true,label="Seat",recipe={advancedrocketry_jj_productsheet_jj_1={need=3,tag=""},minecraft_jj_wool={need=3,tag=""}}},
 advancedrocketry_jj_smallairlockdoor={hasPattern=true,label="Kleine Luftschleuse",recipe={ic2_jj_plate_jj_7={need=6,tag=""},libvulpes_jj_productplate_jj_6={need=6,tag=""}}},
 advancedrocketry_jj_solargenerator={hasPattern=true,label="Solar Generator",recipe={advancedrocketry_jj_solarpanel={need=1,tag=""},libvulpes_jj_battery={need=1,tag=""},libvulpes_jj_forgepoweroutput={need=1,tag=""}}},
 advancedrocketry_jj_solarpanel={hasPattern=true,label="Solarpanele",recipe={ic2_jj_plate_jj_2={need=3,tag=""},libvulpes_jj_productplate_jj_2={need=3,tag=""},libvulpes_jj_structuremachine={need=1,tag=""},minecraft_jj_glowstone_dust={need=2,tag=""},minecraft_jj_redstone={need=3,tag=""}}},
 advancedrocketry_jj_spaceboots={hasPattern=true,label="Raumanzugsschuhe",recipe={ic2_jj_plate_jj_3={need=2,tag=""},libvulpes_jj_productplate_jj_1={need=2,tag=""},libvulpes_jj_productrod_jj_1={need=1,tag=""},minecraft_jj_wool={need=2,tag=""}}},
 advancedrocketry_jj_spacechestplate={hasPattern=false,label="",recipe={advancedrocketry_jj_fueltank={need=1,tag=""},libvulpes_jj_productfan_jj_6={need=1,tag=""},libvulpes_jj_productrod_jj_1={need=1,tag=""},minecraft_jj_wool={need=6,tag=""}}},
 advancedrocketry_jj_spaceelevatorcontroller={hasPattern=false,label="",recipe={advancedrocketry_jj_ic_jj_2={need=2,tag=""},advancedrocketry_jj_ic_jj_3={need=1,tag=""},libvulpes_jj_advstructuremachine={need=1,tag=""},libvulpes_jj_coil0_jj_9={need=3,tag=""}}},
 advancedrocketry_jj_spacehelmet={hasPattern=true,label="Raumanzugshelm",recipe={ic2_jj_plate_jj_3={need=2,tag=""},libvulpes_jj_productplate_jj_1={need=2,tag=""},libvulpes_jj_productrod_jj_1={need=3,tag=""},minecraft_jj_glass_pane={need=1,tag=""},minecraft_jj_wool={need=3,tag=""}}},
 advancedrocketry_jj_spacelaser={hasPattern=true,label="Weltraum Laserbohrer",recipe={advancedrocketry_jj_ic_jj_1={need=1,tag=""},advancedrocketry_jj_ic_jj_2={need=2,tag=""},advancedrocketry_jj_ic_jj_3={need=1,tag=""},libvulpes_jj_battery={need=1,tag=""},libvulpes_jj_productgear_jj_7={need=2,tag=""},libvulpes_jj_structuremachine={need=1,tag=""},minecraft_jj_emerald={need=1,tag=""}}},
 advancedrocketry_jj_spaceleggings={hasPattern=true,label="Raumanzugshose",recipe={libvulpes_jj_productrod_jj_1={need=1,tag=""},minecraft_jj_wool={need=6,tag=""}}},
 advancedrocketry_jj_spacestation={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_spacestationchip={hasPattern=true,label="Raumstations ID Chip",recipe={advancedrocketry_jj_ic={need=1,tag=""},libvulpes_jj_linker={need=1,tag=""}}},
 advancedrocketry_jj_stationbuilder={hasPattern=true,label="Raumstationsmonteur",recipe={advancedrocketry_jj_ic_jj_2={need=2,tag=""},advancedrocketry_jj_rocketbuilder={need=1,tag=""},libvulpes_jj_productdust={need=4,tag=""},libvulpes_jj_productgear_jj_7={need=2,tag=""},taiga_jj_dilithium_dust={need=4,tag=""}}},
 advancedrocketry_jj_stationmarker={hasPattern=false,label="",recipe={advancedrocketry_jj_ic_jj_1={need=1,tag=""},advancedrocketry_jj_loader_jj_1={need=1,tag=""}}},
 advancedrocketry_jj_structuretower={hasPattern=true,label="Structure Tower",recipe={libvulpes_jj_productrod_jj_6={need=7,tag=""}}},
 advancedrocketry_jj_suitworkstation={hasPattern=true,label="Raumanzugs Werkbank",recipe={libvulpes_jj_structuremachine={need=1,tag=""},minecraft_jj_crafting_table={need=1,tag=""}}},
 advancedrocketry_jj_terraformer={hasPattern=false,label="",recipe={advancedrocketry_jj_ic_jj_3={need=1,tag=""},advancedrocketry_jj_ic_jj_5={need=1,tag=""},advancedrocketry_jj_productgear={need=4,tag=""},libvulpes_jj_advstructuremachine={need=1,tag=""},libvulpes_jj_battery_jj_1={need=1,tag=""},libvulpes_jj_productcrystal={need=1,tag=""}}},
 advancedrocketry_jj_thermite={hasPattern=true,label="Thermit",recipe={ic2_jj_dust_jj_8={need=2,tag=""},libvulpes_jj_productdust_jj_1={need=2,tag=""},libvulpes_jj_productdust_jj_9={need=1,tag=""},thermalfoundation_jj_material_jj_68={need=1,tag=""}}},
 advancedrocketry_jj_thermitetorch={hasPattern=true,label="Thermitfackel",recipe={advancedrocketry_jj_thermite={need=1,tag=""},minecraft_jj_stick={need=1,tag=""}}},
 advancedrocketry_jj_unlittorch={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_vitrifiedsand={hasPattern=true,label="Verglaster Sand",recipe={minecraft_jj_glass={need=4,tag=""},minecraft_jj_lava_bucket={need=1,tag=""},minecraft_jj_sand={need=4,tag=""}}},
 advancedrocketry_jj_wafer={hasPattern=false,label="",recipe={}},
 advancedrocketry_jj_warpcore={hasPattern=true,label="Warpkern",recipe={advancedrocketry_jj_ic_jj_2={need=2,tag=""},ic2_jj_plate_jj_7={need=2,tag=""},libvulpes_jj_coil0_jj_4={need=1,tag=""},libvulpes_jj_productplate_jj_6={need=2,tag=""},libvulpes_jj_productplate_jj_7={need=4,tag=""},techreborn_jj_plates_jj_30={need=4,tag=""}}},
 advancedrocketry_jj_warpmonitor={hasPattern=true,label="Warpsteuerung",recipe={advancedrocketry_jj_ic_jj_2={need=1,tag=""},advancedrocketry_jj_ic_jj_3={need=2,tag=""},advancedrocketry_jj_misc={need=1,tag=""},ic2_jj_plate_jj_7={need=4,tag=""},libvulpes_jj_productplate_jj_6={need=4,tag=""},libvulpes_jj_structuremachine={need=1,tag=""}}},
 advancedrocketry_jj_wirelesstransciever={hasPattern=true,label="Wireless Transciever",recipe={advancedrocketry_jj_dataunit={need=1,tag=""},minecraft_jj_glass_pane={need=6,tag=""}}},
 buildcraftbuilders_jj_architect={hasPattern=false,label="",recipe={buildcraftbuilders_jj_snapshot_jj_2={need=1,tag=""},buildcraftcore_jj_gear_diamond={need=2,tag=""},buildcraftcore_jj_marker_volume={need=1,tag=""},minecraft_jj_crafting_table={need=1,tag=""},minecraft_jj_dye={need=2,tag=""},minecraft_jj_dye_jj_11={need=2,tag=""}}},
 buildcraftbuilders_jj_builder={hasPattern=false,label="",recipe={buildcraftcore_jj_gear_diamond={need=2,tag=""},buildcraftcore_jj_marker_volume={need=1,tag=""},minecraft_jj_chest={need=1,tag=""},minecraft_jj_crafting_table={need=1,tag=""},minecraft_jj_dye={need=2,tag=""},minecraft_jj_dye_jj_4={need=2,tag=""}}},
 buildcraftbuilders_jj_filler={hasPattern=false,label="",recipe={}},
 buildcraftbuilders_jj_filler_planner={hasPattern=false,label="",recipe={}},
 buildcraftbuilders_jj_frame={hasPattern=false,label="",recipe={}},
 buildcraftbuilders_jj_library={hasPattern=false,label="",recipe={}},
 buildcraftbuilders_jj_quarry={hasPattern=false,label="",recipe={buildcraftcore_jj_gear_diamond={need=2,tag=""},buildcraftcore_jj_gear_gold={need=2,tag=""},buildcraftcore_jj_gear_iron={need=3,tag=""},mekanism_jj_controlcircuit_jj_1={need=1,tag=""},techreborn_jj_diamonddrill={need=1,tag=""}}},
 buildcraftbuilders_jj_replacer={hasPattern=false,label="",recipe={}},
 buildcraftbuilders_jj_schematic_single={hasPattern=false,label="",recipe={}},
 buildcraftbuilders_jj_snapshot={hasPattern=true,label="Schablone",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_paper={need=8,tag=""}}},
 buildcraftbuilders_jj_snapshot_jj_2={hasPattern=true,label="Erweiterter Bauplan",recipe={minecraft_jj_dye_jj_4={need=1,tag=""},minecraft_jj_paper={need=8,tag=""}}},
 buildcraftcompat_jj_pipe_item_propolis={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_decorated={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_decorated_jj_1={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_decorated_jj_2={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_decorated_jj_3={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_decorated_jj_4={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_decorated_jj_5={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_engine={hasPattern=false,label="",recipe={buildcraftcore_jj_gear_wood={need=2,tag=""},minecraft_jj_glass={need=1,tag=""},minecraft_jj_piston={need=1,tag=""},minecraft_jj_planks={need=3,tag=""}}},
 buildcraftcore_jj_engine_jj_1={hasPattern=false,label="",recipe={buildcraftcore_jj_gear_stone={need=2,tag=""},minecraft_jj_cobblestone={need=3,tag=""},minecraft_jj_glass={need=1,tag=""},minecraft_jj_piston={need=1,tag=""}}},
 buildcraftcore_jj_engine_jj_2={hasPattern=true,label="Verbrennungsmotor",recipe={buildcraftcore_jj_gear_iron={need=2,tag=""},minecraft_jj_glass={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_piston={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=2,tag=""}}},
 buildcraftcore_jj_engine_jj_3={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_fragile_fluid_shard={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_gear_diamond={hasPattern=true,label="Diamantzahnrad",recipe={buildcraftcore_jj_gear_gold={need=1,tag=""},minecraft_jj_diamond={need=4,tag=""},thermalfoundation_jj_material_jj_25={need=1,tag=""}}},
 buildcraftcore_jj_gear_gold={hasPattern=true,label="Goldzahnrad",recipe={buildcraftcore_jj_gear_iron={need=1,tag=""},minecraft_jj_gold_ingot={need=4,tag=""},thermalfoundation_jj_material_jj_24={need=1,tag=""}}},
 buildcraftcore_jj_gear_iron={hasPattern=false,label="",recipe={buildcraftcore_jj_gear_stone={need=1,tag=""},minecraft_jj_iron_ingot={need=4,tag=""}}},
 buildcraftcore_jj_gear_stone={hasPattern=false,label="",recipe={buildcraftcore_jj_gear_wood={need=1,tag=""},minecraft_jj_cobblestone={need=4,tag=""}}},
 buildcraftcore_jj_gear_wood={hasPattern=false,label="",recipe={minecraft_jj_stick={need=4,tag=""}}},
 buildcraftcore_jj_list={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_map_location={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_marker_connector={hasPattern=true,label="Marker Connector",recipe={buildcraftcore_jj_gear_wood={need=1,tag=""},buildcraftcore_jj_wrench={need=1,tag=""},minecraft_jj_redstone_torch={need=1,tag=""},thermalfoundation_jj_material_jj_22={need=1,tag=""}}},
 buildcraftcore_jj_marker_path={hasPattern=true,label="Wegmarkierung",recipe={minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_redstone_torch={need=1,tag=""}}},
 buildcraftcore_jj_marker_volume={hasPattern=true,label="Platzmarker",recipe={minecraft_jj_dye_jj_4={need=1,tag=""},minecraft_jj_redstone_torch={need=1,tag=""}}},
 buildcraftcore_jj_paintbrush={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_paintbrush_jj_1={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_paintbrush_jj_10={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_paintbrush_jj_11={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_paintbrush_jj_12={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_paintbrush_jj_13={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_paintbrush_jj_14={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_paintbrush_jj_15={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_paintbrush_jj_16={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_paintbrush_jj_2={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_paintbrush_jj_3={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_paintbrush_jj_4={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_paintbrush_jj_5={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_paintbrush_jj_6={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_paintbrush_jj_7={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_paintbrush_jj_8={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_paintbrush_jj_9={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_spring={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_spring_jj_1={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_volume_box={hasPattern=false,label="",recipe={}},
 buildcraftcore_jj_wrench={hasPattern=false,label="",recipe={buildcraftcore_jj_gear_stone={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""}}},
 buildcraftenergy_jj_glob_of_oil={hasPattern=false,label="",recipe={}},
 buildcraftfactory_jj_autoworkbench_item={hasPattern=false,label="",recipe={buildcraftcore_jj_gear_stone={need=2,tag=""},minecraft_jj_crafting_table={need=1,tag=""}}},
 buildcraftfactory_jj_chute={hasPattern=false,label="",recipe={buildcraftcore_jj_gear_stone={need=1,tag=""},minecraft_jj_chest={need=1,tag=""},minecraft_jj_iron_ingot={need=5,tag=""}}},
 buildcraftfactory_jj_distiller={hasPattern=false,label="",recipe={buildcraftcore_jj_gear_diamond={need=1,tag=""},buildcraftfactory_jj_tank={need=3,tag=""},minecraft_jj_redstone_torch={need=2,tag=""}}},
 buildcraftfactory_jj_flood_gate={hasPattern=true,label="Auslass",recipe={buildcraftcore_jj_gear_iron={need=1,tag=""},buildcraftfactory_jj_tank={need=1,tag=""},minecraft_jj_iron_bars={need=3,tag=""},minecraft_jj_iron_ingot={need=4,tag=""},thermalfoundation_jj_material_jj_24={need=1,tag=""}}},
 buildcraftfactory_jj_gel={hasPattern=false,label="",recipe={}},
 buildcraftfactory_jj_heat_exchange={hasPattern=true,label="Heat Exchanger",recipe={buildcraftcore_jj_gear_iron={need=2,tag=""},minecraft_jj_glass={need=3,tag=""},minecraft_jj_iron_ingot={need=4,tag=""},thermalfoundation_jj_material_jj_24={need=2,tag=""}}},
 buildcraftfactory_jj_mining_well={hasPattern=true,label="Minenbohrer",recipe={buildcraftcore_jj_gear_iron={need=1,tag=""},minecraft_jj_iron_ingot={need=6,tag=""},minecraft_jj_iron_pickaxe={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=1,tag=""}}},
 buildcraftfactory_jj_pump={hasPattern=true,label="Pumpe",recipe={buildcraftcore_jj_gear_iron={need=1,tag=""},buildcraftfactory_jj_tank={need=2,tag=""},minecraft_jj_bucket={need=1,tag=""},minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_redstone={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=1,tag=""}}},
 buildcraftfactory_jj_tank={hasPattern=true,label="Tank",recipe={minecraft_jj_glass={need=8,tag=""}}},
 buildcraftfactory_jj_water_gel_spawn={hasPattern=false,label="",recipe={}},
 buildcraftlib_jj_debugger={hasPattern=false,label="",recipe={}},
 buildcraftlib_jj_guide={hasPattern=false,label="",recipe={buildcraftcore_jj_gear_wood={need=1,tag=""},minecraft_jj_paper={need=3,tag=""}}},
 buildcraftlib_jj_guide_note={hasPattern=false,label="",recipe={}},
 buildcraftrobotics_jj_zone_planner={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_advanced_crafting_table={hasPattern=true,label="Montagewerkbank",recipe={buildcraftsilicon_jj_redstone_chipset={need=1,tag=""},minecraft_jj_chest={need=1,tag=""},minecraft_jj_crafting_table={need=1,tag=""},minecraft_jj_obsidian={need=6,tag=""}}},
 buildcraftsilicon_jj_assembly_table={hasPattern=false,label="",recipe={buildcraftcore_jj_gear_diamond={need=1,tag=""},minecraft_jj_diamond={need=1,tag=""},minecraft_jj_obsidian={need=6,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 buildcraftsilicon_jj_integration_table={hasPattern=false,label="",recipe={buildcraftcore_jj_gear_diamond={need=1,tag=""},buildcraftsilicon_jj_redstone_chipset_jj_1={need=1,tag=""},minecraft_jj_gold_ingot={need=1,tag=""},minecraft_jj_obsidian={need=6,tag=""}}},
 buildcraftsilicon_jj_laser={hasPattern=true,label="Laser",recipe={minecraft_jj_diamond={need=2,tag=""},minecraft_jj_obsidian={need=2,tag=""},minecraft_jj_redstone={need=5,tag=""}}},
 buildcraftsilicon_jj_plug_gate={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_1={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_10={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_11={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_12={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_13={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_14={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_15={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_16={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_17={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_18={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_19={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_2={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_20={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_21={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_22={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_23={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_24={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_25={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_26={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_27={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_28={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_29={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_3={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_30={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_31={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_32={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_33={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_4={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_5={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_6={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_7={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_8={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_lens_jj_9={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_light_sensor={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_plug_pulsar={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_redstone_chipset={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_redstone_chipset_jj_1={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_redstone_chipset_jj_2={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_redstone_chipset_jj_3={hasPattern=false,label="",recipe={}},
 buildcraftsilicon_jj_redstone_chipset_jj_4={hasPattern=false,label="",recipe={}},
 buildcrafttransport_jj_filtered_buffer={hasPattern=true,label="Gefilterter Puffer",recipe={buildcrafttransport_jj_pipe_diamond_item={need=1,tag=""},minecraft_jj_chest={need=1,tag=""},minecraft_jj_piston={need=1,tag=""},minecraft_jj_planks={need=6,tag=""}}},
 buildcrafttransport_jj_pipe_clay_fluid={hasPattern=true,label="Lehmiges Flüssigkeitsrohr",recipe={buildcrafttransport_jj_pipe_clay_item={need=1,tag=""},buildcrafttransport_jj_waterproof={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_clay_item={hasPattern=true,label="Lehmiges Transportrohr",recipe={minecraft_jj_clay={need=2,tag=""},minecraft_jj_glass={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_cobble_fluid={hasPattern=true,label="Pflastersteinernes Flüssigkeitsrohr",recipe={buildcrafttransport_jj_pipe_cobble_item={need=1,tag=""},buildcrafttransport_jj_waterproof={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_cobble_item={hasPattern=true,label="Pflasterstein-Transportrohr",recipe={minecraft_jj_cobblestone={need=2,tag=""},minecraft_jj_glass={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_cobble_power={hasPattern=true,label="Pflasterstein-Energieleitung",recipe={buildcrafttransport_jj_pipe_cobble_item={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_daizuli_item={hasPattern=true,label="Daizuli-Transportrohr",recipe={minecraft_jj_diamond={need=1,tag=""},minecraft_jj_glass={need=1,tag=""},minecraft_jj_lapis_block={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_diamond_fluid={hasPattern=true,label="Diamantenes Flüssigkeitsrohr",recipe={buildcrafttransport_jj_pipe_diamond_item={need=1,tag=""},buildcrafttransport_jj_waterproof={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_diamond_item={hasPattern=true,label="Diamantenes Transportrohr",recipe={buildcrafttransport_jj_pipe_diamond_fluid={need=1,tag=""},minecraft_jj_diamond={need=2,tag=""},minecraft_jj_glass={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_diamond_wood_fluid={hasPattern=true,label="Wooden Diamond Fluid Pipe",recipe={buildcrafttransport_jj_pipe_diamond_wood_item={need=1,tag=""},buildcrafttransport_jj_waterproof={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_diamond_wood_item={hasPattern=true,label="Wooden Diamond Transport Pipe",recipe={buildcrafttransport_jj_pipe_diamond_wood_fluid={need=1,tag=""},minecraft_jj_diamond={need=1,tag=""},minecraft_jj_glass={need=1,tag=""},minecraft_jj_planks={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_emzuli_item={hasPattern=true,label="Emzuli-Transportrohr",recipe={buildcrafttransport_jj_pipe_diamond_wood_item={need=1,tag=""},minecraft_jj_lapis_block={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_gold_fluid={hasPattern=true,label="Goldenes Flüssigkeitsrohr",recipe={buildcrafttransport_jj_pipe_gold_item={need=1,tag=""},buildcrafttransport_jj_waterproof={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_gold_item={hasPattern=true,label="Goldenes Transportrohr",recipe={buildcrafttransport_jj_pipe_gold_power={need=1,tag=""},minecraft_jj_glass={need=1,tag=""},minecraft_jj_gold_ingot={need=2,tag=""}}},
 buildcrafttransport_jj_pipe_gold_power={hasPattern=true,label="Goldene Energieleitung",recipe={buildcrafttransport_jj_pipe_gold_item={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_iron_fluid={hasPattern=true,label="Eisernes Flüssigkeitsrohr",recipe={buildcrafttransport_jj_pipe_iron_item={need=1,tag=""},buildcrafttransport_jj_waterproof={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_iron_item={hasPattern=true,label="Eisernes Transportrohr",recipe={buildcrafttransport_jj_pipe_iron_fluid={need=1,tag=""},minecraft_jj_glass={need=1,tag=""},minecraft_jj_iron_ingot={need=2,tag=""}}},
 buildcrafttransport_jj_pipe_lapis_item={hasPattern=true,label="Lazuli-Transportrohr",recipe={minecraft_jj_glass={need=1,tag=""},minecraft_jj_lapis_block={need=2,tag=""}}},
 buildcrafttransport_jj_pipe_obsidian_item={hasPattern=true,label="Obsidian-Transportrohr",recipe={minecraft_jj_glass={need=1,tag=""},minecraft_jj_obsidian={need=2,tag=""}}},
 buildcrafttransport_jj_pipe_quartz_fluid={hasPattern=true,label="Quarz-Flüssigkeitsrohr",recipe={buildcrafttransport_jj_pipe_quartz_item={need=1,tag=""},buildcrafttransport_jj_waterproof={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_quartz_item={hasPattern=true,label="Quarz-Transportrohr",recipe={minecraft_jj_glass={need=1,tag=""},minecraft_jj_quartz_block={need=2,tag=""}}},
 buildcrafttransport_jj_pipe_quartz_power={hasPattern=true,label="Quarz-Energieleitung",recipe={buildcrafttransport_jj_pipe_quartz_item={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_sandstone_fluid={hasPattern=true,label="Sandstein-Flüssigkeitsrohr",recipe={buildcrafttransport_jj_pipe_sandstone_item={need=1,tag=""},buildcrafttransport_jj_waterproof={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_sandstone_item={hasPattern=true,label="Sandstein-Transportrohr",recipe={buildcrafttransport_jj_pipe_sandstone_power={need=1,tag=""},minecraft_jj_glass={need=1,tag=""},minecraft_jj_sandstone={need=2,tag=""}}},
 buildcrafttransport_jj_pipe_sandstone_power={hasPattern=true,label="Sandstein-Energieleitung",recipe={buildcrafttransport_jj_pipe_sandstone_item={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_stone_fluid={hasPattern=true,label="Steineres Flüssigkeitsrohr",recipe={buildcrafttransport_jj_pipe_stone_item={need=1,tag=""},buildcrafttransport_jj_waterproof={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_stone_item={hasPattern=true,label="Steineres Transportrohr",recipe={minecraft_jj_glass={need=1,tag=""},minecraft_jj_stone={need=2,tag=""}}},
 buildcrafttransport_jj_pipe_stone_power={hasPattern=true,label="Steinerne Energieleitung",recipe={buildcrafttransport_jj_pipe_stone_item={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_stripes_item={hasPattern=true,label="Gestreiftes Transportrohr",recipe={buildcraftcore_jj_gear_gold={need=2,tag=""},minecraft_jj_glass={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=2,tag=""}}},
 buildcrafttransport_jj_pipe_structure={hasPattern=true,label="Strukturrohr",recipe={minecraft_jj_cobblestone={need=2,tag=""},minecraft_jj_gravel={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_void_fluid={hasPattern=true,label="Löschendes Flüssigkeitsrohr",recipe={buildcrafttransport_jj_pipe_void_item={need=1,tag=""},buildcrafttransport_jj_waterproof={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_void_item={hasPattern=true,label="Löschendes Transportrohr",recipe={buildcrafttransport_jj_pipe_void_fluid={need=1,tag=""},minecraft_jj_dye={need=1,tag=""},minecraft_jj_glass={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_wood_fluid={hasPattern=true,label="Hölzernes Flüssigkeitsrohr",recipe={buildcrafttransport_jj_pipe_wood_item={need=1,tag=""},buildcrafttransport_jj_waterproof={need=1,tag=""}}},
 buildcrafttransport_jj_pipe_wood_item={hasPattern=true,label="Hölzernes Transportrohr",recipe={buildcrafttransport_jj_pipe_wood_power={need=1,tag=""},minecraft_jj_glass={need=1,tag=""},minecraft_jj_planks={need=2,tag=""}}},
 buildcrafttransport_jj_pipe_wood_power={hasPattern=true,label="Hölzerne Energieleitung",recipe={buildcrafttransport_jj_pipe_wood_item={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 buildcrafttransport_jj_plug_blocker={hasPattern=true,label="Rohrstöpsel",recipe={buildcrafttransport_jj_pipe_structure={need=1,tag=""}}},
 buildcrafttransport_jj_plug_power_adaptor={hasPattern=false,label="",recipe={}},
 buildcrafttransport_jj_waterproof={hasPattern=true,label="Dichtung",recipe={minecraft_jj_dye_jj_2={need=1,tag=""},minecraft_jj_slime_ball={need=1,tag=""}}},
 buildcrafttransport_jj_wire={hasPattern=false,label="",recipe={}},
 buildcrafttransport_jj_wire_jj_1={hasPattern=false,label="",recipe={}},
 buildcrafttransport_jj_wire_jj_10={hasPattern=false,label="",recipe={}},
 buildcrafttransport_jj_wire_jj_11={hasPattern=false,label="",recipe={}},
 buildcrafttransport_jj_wire_jj_12={hasPattern=false,label="",recipe={}},
 buildcrafttransport_jj_wire_jj_13={hasPattern=false,label="",recipe={}},
 buildcrafttransport_jj_wire_jj_14={hasPattern=false,label="",recipe={}},
 buildcrafttransport_jj_wire_jj_15={hasPattern=false,label="",recipe={}},
 buildcrafttransport_jj_wire_jj_2={hasPattern=false,label="",recipe={}},
 buildcrafttransport_jj_wire_jj_3={hasPattern=false,label="",recipe={}},
 buildcrafttransport_jj_wire_jj_4={hasPattern=false,label="",recipe={}},
 buildcrafttransport_jj_wire_jj_5={hasPattern=false,label="",recipe={}},
 buildcrafttransport_jj_wire_jj_6={hasPattern=false,label="",recipe={}},
 buildcrafttransport_jj_wire_jj_7={hasPattern=false,label="",recipe={}},
 buildcrafttransport_jj_wire_jj_8={hasPattern=false,label="",recipe={}},
 buildcrafttransport_jj_wire_jj_9={hasPattern=false,label="",recipe={}},
 libvulpes_jj_advancedmotor={hasPattern=true,label="Advanced Motor",recipe={ic2_jj_plate_jj_7={need=3,tag=""},libvulpes_jj_coil0_jj_2={need=2,tag=""},libvulpes_jj_productplate_jj_6={need=3,tag=""},libvulpes_jj_productrod_jj_6={need=2,tag=""}}},
 libvulpes_jj_advstructuremachine={hasPattern=false,label="",recipe={libvulpes_jj_productplate_jj_7={need=4,tag=""},libvulpes_jj_productrod_jj_7={need=5,tag=""}}},
 libvulpes_jj_battery={hasPattern=true,label="Kleine Batterie",recipe={ic2_jj_plate_jj_8={need=4,tag=""},libvulpes_jj_productplate_jj_5={need=4,tag=""},libvulpes_jj_productrod_jj_1={need=1,tag=""},minecraft_jj_redstone={need=2,tag=""}}},
 libvulpes_jj_battery_jj_1={hasPattern=true,label="2x Kleine Batterie",recipe={ic2_jj_plate_jj_1={need=2,tag=""},libvulpes_jj_battery={need=4,tag=""},libvulpes_jj_productplate_jj_4={need=2,tag=""}}},
 libvulpes_jj_blockphantom={hasPattern=false,label="",recipe={}},
 libvulpes_jj_coalgenerator={hasPattern=true,label="Coal Generator",recipe={libvulpes_jj_battery={need=1,tag=""},minecraft_jj_furnace={need=1,tag=""}}},
 libvulpes_jj_coil0_jj_10={hasPattern=true,label="Iridium Coil",recipe={libvulpes_jj_productingot_jj_10={need=8,tag=""},thermalfoundation_jj_material_jj_135={need=8,tag=""}}},
 libvulpes_jj_coil0_jj_2={hasPattern=true,label="Gold Coil",recipe={minecraft_jj_gold_ingot={need=8,tag=""}}},
 libvulpes_jj_coil0_jj_4={hasPattern=true,label="Copper Coil",recipe={ic2_jj_ingot_jj_2={need=8,tag=""},libvulpes_jj_productingot_jj_4={need=8,tag=""}}},
 libvulpes_jj_coil0_jj_7={hasPattern=true,label="Titanium Coil",recipe={libvulpes_jj_productingot_jj_7={need=8,tag=""},techreborn_jj_ingot_jj_14={need=8,tag=""}}},
 libvulpes_jj_coil0_jj_9={hasPattern=true,label="Aluminum Coil",recipe={libvulpes_jj_productingot_jj_9={need=8,tag=""},thermalfoundation_jj_material_jj_132={need=8,tag=""}}},
 libvulpes_jj_creativepowerbattery={hasPattern=false,label="",recipe={}},
 libvulpes_jj_elitemotor={hasPattern=true,label="Elite Motor",recipe={libvulpes_jj_coil0_jj_7={need=2,tag=""},libvulpes_jj_productplate_jj_10={need=3,tag=""},libvulpes_jj_productrod_jj_10={need=2,tag=""},thermalfoundation_jj_material_jj_327={need=3,tag=""}}},
 libvulpes_jj_enhancedmotor={hasPattern=true,label="Enhanced Motor",recipe={libvulpes_jj_coil0_jj_9={need=2,tag=""},libvulpes_jj_productplate_jj_7={need=3,tag=""},libvulpes_jj_productrod_jj_7={need=2,tag=""},techreborn_jj_plates_jj_30={need=3,tag=""}}},
 libvulpes_jj_forgepowerinput={hasPattern=true,label="Power Input Plug",recipe={libvulpes_jj_battery={need=4,tag=""},libvulpes_jj_forgepoweroutput={need=1,tag=""},libvulpes_jj_structuremachine={need=1,tag=""}}},
 libvulpes_jj_forgepoweroutput={hasPattern=true,label="Power Output Plug",recipe={libvulpes_jj_forgepowerinput={need=1,tag=""}}},
 libvulpes_jj_hatch={hasPattern=true,label="Input Hatch",recipe={libvulpes_jj_structuremachine={need=1,tag=""},minecraft_jj_chest={need=1,tag=""}}},
 libvulpes_jj_hatch_jj_1={hasPattern=true,label="Output Hatch",recipe={libvulpes_jj_structuremachine={need=1,tag=""},minecraft_jj_chest={need=1,tag=""}}},
 libvulpes_jj_hatch_jj_2={hasPattern=true,label="Fluid Input Hatch",recipe={libvulpes_jj_structuremachine={need=1,tag=""},minecraft_jj_bucket={need=1,tag=""}}},
 libvulpes_jj_hatch_jj_3={hasPattern=true,label="Fluid Output Hatch",recipe={libvulpes_jj_structuremachine={need=1,tag=""},minecraft_jj_bucket={need=1,tag=""}}},
 libvulpes_jj_holoprojector={hasPattern=true,label="Holo-Projector",recipe={advancedrocketry_jj_satelliteprimaryfunction={need=2,tag=""},ic2_jj_plate_jj_3={need=1,tag=""},libvulpes_jj_productplate_jj_1={need=1,tag=""},minecraft_jj_redstone={need=3,tag=""}}},
 libvulpes_jj_ic2plug={hasPattern=false,label="",recipe={}},
 libvulpes_jj_linker={hasPattern=true,label="Linker",recipe={minecraft_jj_gold_ingot={need=1,tag=""},minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 libvulpes_jj_metal0_jj_10={hasPattern=true,label="Iridium Block",recipe={libvulpes_jj_productingot_jj_10={need=9,tag=""}}},
 libvulpes_jj_metal0_jj_4={hasPattern=true,label="Copper Block",recipe={libvulpes_jj_productingot_jj_4={need=9,tag=""}}},
 libvulpes_jj_metal0_jj_5={hasPattern=true,label="Tin Block",recipe={libvulpes_jj_productingot_jj_5={need=9,tag=""}}},
 libvulpes_jj_metal0_jj_6={hasPattern=true,label="Steel Block",recipe={libvulpes_jj_productingot_jj_6={need=9,tag=""}}},
 libvulpes_jj_metal0_jj_7={hasPattern=true,label="Titanium Block",recipe={libvulpes_jj_productingot_jj_7={need=9,tag=""}}},
 libvulpes_jj_metal0_jj_9={hasPattern=true,label="Aluminum Block",recipe={libvulpes_jj_productingot_jj_9={need=9,tag=""}}},
 libvulpes_jj_motor={hasPattern=true,label="Motor",recipe={ic2_jj_plate_jj_7={need=3,tag=""},libvulpes_jj_coil0_jj_4={need=2,tag=""},libvulpes_jj_productplate_jj_6={need=3,tag=""},libvulpes_jj_productrod_jj_6={need=2,tag=""}}},
 libvulpes_jj_ore0={hasPattern=false,label="",recipe={}},
 libvulpes_jj_ore0_jj_10={hasPattern=false,label="",recipe={}},
 libvulpes_jj_ore0_jj_4={hasPattern=false,label="",recipe={}},
 libvulpes_jj_ore0_jj_5={hasPattern=false,label="",recipe={}},
 libvulpes_jj_ore0_jj_8={hasPattern=false,label="",recipe={}},
 libvulpes_jj_ore0_jj_9={hasPattern=false,label="",recipe={}},
 libvulpes_jj_placeholder={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productboule_jj_3={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productcrystal={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productdust={hasPattern=false,label="",recipe={libvulpes_jj_ore0={need=1,tag=""},thermalfoundation_jj_material_jj_1027={need=1,tag=""}}},
 libvulpes_jj_productdust_jj_1={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productdust_jj_10={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productdust_jj_2={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productdust_jj_3={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productdust_jj_4={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productdust_jj_5={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productdust_jj_6={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productdust_jj_7={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productdust_jj_9={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productfan_jj_6={hasPattern=true,label="Steel Fan",recipe={ic2_jj_plate_jj_7={need=4,tag=""},libvulpes_jj_productplate_jj_6={need=4,tag=""},libvulpes_jj_productrod_jj_6={need=1,tag=""}}},
 libvulpes_jj_productgear_jj_6={hasPattern=true,label="Steel Gear",recipe={ic2_jj_ingot_jj_5={need=1,tag=""},ic2_jj_plate_jj_7={need=2,tag=""},libvulpes_jj_productingot_jj_6={need=1,tag=""},libvulpes_jj_productplate_jj_6={need=2,tag=""},libvulpes_jj_productrod_jj_6={need=4,tag=""}}},
 libvulpes_jj_productgear_jj_7={hasPattern=true,label="Titanium Gear",recipe={libvulpes_jj_productingot_jj_7={need=1,tag=""},libvulpes_jj_productplate_jj_7={need=2,tag=""},libvulpes_jj_productrod_jj_7={need=4,tag=""},techreborn_jj_ingot_jj_14={need=1,tag=""},techreborn_jj_plates_jj_30={need=2,tag=""}}},
 libvulpes_jj_productingot_jj_10={hasPattern=false,label="",recipe={libvulpes_jj_metal0_jj_10={need=1,tag=""}}},
 libvulpes_jj_productingot_jj_3={hasPattern=true,label="Silicon Ingot",recipe={libvulpes_jj_productnugget_jj_3={need=9,tag=""}}},
 libvulpes_jj_productingot_jj_4={hasPattern=false,label="",recipe={libvulpes_jj_productnugget_jj_4={need=9,tag=""}}},
 libvulpes_jj_productingot_jj_5={hasPattern=false,label="",recipe={libvulpes_jj_productnugget_jj_5={need=9,tag=""}}},
 libvulpes_jj_productingot_jj_6={hasPattern=false,label="",recipe={libvulpes_jj_metal0_jj_6={need=1,tag=""}}},
 libvulpes_jj_productingot_jj_7={hasPattern=false,label="",recipe={libvulpes_jj_metal0_jj_7={need=1,tag=""}}},
 libvulpes_jj_productingot_jj_9={hasPattern=false,label="",recipe={libvulpes_jj_metal0_jj_9={need=1,tag=""}}},
 libvulpes_jj_productnugget_jj_10={hasPattern=false,label="",recipe={libvulpes_jj_productingot_jj_10={need=1,tag=""}}},
 libvulpes_jj_productnugget_jj_3={hasPattern=true,label="Silicon Nugget",recipe={libvulpes_jj_productingot_jj_3={need=1,tag=""}}},
 libvulpes_jj_productnugget_jj_4={hasPattern=false,label="",recipe={libvulpes_jj_productingot_jj_4={need=1,tag=""}}},
 libvulpes_jj_productnugget_jj_5={hasPattern=false,label="",recipe={libvulpes_jj_productingot_jj_5={need=1,tag=""}}},
 libvulpes_jj_productnugget_jj_6={hasPattern=false,label="",recipe={libvulpes_jj_productingot_jj_6={need=1,tag=""}}},
 libvulpes_jj_productnugget_jj_7={hasPattern=false,label="",recipe={libvulpes_jj_productingot_jj_7={need=1,tag=""}}},
 libvulpes_jj_productnugget_jj_9={hasPattern=false,label="",recipe={libvulpes_jj_productingot_jj_9={need=1,tag=""}}},
 libvulpes_jj_productplate_jj_1={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productplate_jj_10={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productplate_jj_2={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productplate_jj_3={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productplate_jj_4={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productplate_jj_5={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productplate_jj_6={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productplate_jj_7={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productplate_jj_9={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productrod_jj_1={hasPattern=true,label="Iron Rod",recipe={minecraft_jj_iron_ingot={need=3,tag=""}}},
 libvulpes_jj_productrod_jj_10={hasPattern=true,label="Iridium Rod",recipe={libvulpes_jj_productingot_jj_10={need=3,tag=""}}},
 libvulpes_jj_productrod_jj_4={hasPattern=true,label="Copper Rod",recipe={libvulpes_jj_productingot_jj_4={need=3,tag=""}}},
 libvulpes_jj_productrod_jj_6={hasPattern=true,label="Steel Rod",recipe={libvulpes_jj_productingot_jj_6={need=3,tag=""}}},
 libvulpes_jj_productrod_jj_7={hasPattern=true,label="Titanium Rod",recipe={libvulpes_jj_productingot_jj_7={need=3,tag=""}}},
 libvulpes_jj_productsheet_jj_1={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productsheet_jj_4={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productsheet_jj_6={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productsheet_jj_7={hasPattern=false,label="",recipe={}},
 libvulpes_jj_productsheet_jj_9={hasPattern=false,label="",recipe={}},
 libvulpes_jj_structuremachine={hasPattern=true,label="Machine Structure",recipe={ic2_jj_plate_jj_3={need=4,tag=""},libvulpes_jj_productplate_jj_1={need=4,tag=""},libvulpes_jj_productrod_jj_1={need=4,tag=""}}}
 }