return {
 terraqueous_jj_border={hasPattern=false,label="",recipe={}},
 terraqueous_jj_border_jj_1={hasPattern=true,label="Border",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_iron_nugget={need=3,tag=""}}},
 terraqueous_jj_border_jj_2={hasPattern=true,label="Border",recipe={minecraft_jj_iron_ingot={need=1,tag=""},minecraft_jj_iron_nugget={need=3,tag=""},terraqueous_jj_flowers_single_jj_4={need=1,tag=""}}},
 terraqueous_jj_border_jj_3={hasPattern=true,label="Border",recipe={minecraft_jj_iron_nugget={need=3,tag=""},minecraft_jj_rotten_flesh={need=1,tag=""},terraqueous_jj_flowers_single_jj_4={need=1,tag=""}}},
 terraqueous_jj_border_jj_4={hasPattern=true,label="Border",recipe={minecraft_jj_gold_ingot={need=1,tag=""},minecraft_jj_gold_nugget={need=3,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 terraqueous_jj_burnium_belt={hasPattern=false,label="",recipe={}},
 terraqueous_jj_cloud_staff={hasPattern=false,label="",recipe={}},
 terraqueous_jj_cloud_talisman={hasPattern=false,label="",recipe={}},
 terraqueous_jj_cloudfancy_jj_1={hasPattern=true,label="Cloud Column",recipe={terraqueous_jj_clouds={need=3,tag=""}}},
 terraqueous_jj_cloudfancy_jj_3={hasPattern=true,label="Cloud Column Capital",recipe={terraqueous_jj_clouds={need=4,tag=""}}},
 terraqueous_jj_cloudfancy_jj_4={hasPattern=true,label="Cloud Arch",recipe={terraqueous_jj_clouds={need=6,tag=""}}},
 terraqueous_jj_cloudfancy_jj_5={hasPattern=true,label="Cloud Edge",recipe={terraqueous_jj_clouds={need=2,tag=""},terraqueous_jj_clouds_jj_1={need=2,tag=""}}},
 terraqueous_jj_clouds={hasPattern=true,label="Light Cloud",recipe={terraqueous_jj_type_cloud_jj_110={need=4,tag=""},terraqueous_jj_type_cloud_jj_51={need=1,tag=""}}},
 terraqueous_jj_clouds_jj_1={hasPattern=true,label="Dense Cloud",recipe={terraqueous_jj_clouds={need=4,tag=""},terraqueous_jj_clouds_jj_2={need=1,tag=""}}},
 terraqueous_jj_clouds_jj_10={hasPattern=false,label="",recipe={}},
 terraqueous_jj_clouds_jj_2={hasPattern=true,label="Storm Cloud",recipe={terraqueous_jj_clouds_jj_1={need=4,tag=""},terraqueous_jj_crafting_jj_3={need=1,tag=""}}},
 terraqueous_jj_clouds_jj_8={hasPattern=false,label="",recipe={}},
 terraqueous_jj_clouds_jj_9={hasPattern=false,label="",recipe={}},
 terraqueous_jj_colorizer={hasPattern=false,label="",recipe={}},
 terraqueous_jj_colorizer_jj_512={hasPattern=false,label="",recipe={}},
 terraqueous_jj_crafting={hasPattern=true,label="Cloud Workbench",recipe={terraqueous_jj_clouds_jj_2={need=4,tag=""}}},
 terraqueous_jj_crafting_jj_1={hasPattern=true,label="Cloud Furnace",recipe={terraqueous_jj_clouds_jj_2={need=8,tag=""}}},
 terraqueous_jj_crafting_jj_2={hasPattern=true,label="Cloud CraftBench",recipe={terraqueous_jj_clouds_jj_2={need=8,tag=""},terraqueous_jj_crafting={need=1,tag=""}}},
 terraqueous_jj_crafting_jj_3={hasPattern=true,label="Cloud CraftFurnace",recipe={terraqueous_jj_clouds_jj_2={need=8,tag=""},terraqueous_jj_crafting_jj_1={need=1,tag=""}}},
 terraqueous_jj_crafting_jj_5={hasPattern=true,label="CraftBench",recipe={minecraft_jj_crafting_table={need=1,tag=""},minecraft_jj_stone={need=8,tag=""}}},
 terraqueous_jj_crafting_jj_6={hasPattern=true,label="CraftFurnace",recipe={minecraft_jj_furnace={need=1,tag=""},minecraft_jj_stone={need=8,tag=""}}},
 terraqueous_jj_doodads={hasPattern=false,label="",recipe={}},
 terraqueous_jj_doodads_jj_1={hasPattern=false,label="",recipe={}},
 terraqueous_jj_doodads_jj_2={hasPattern=false,label="",recipe={}},
 terraqueous_jj_doodads_jj_3={hasPattern=false,label="",recipe={}},
 terraqueous_jj_doodads_jj_4={hasPattern=false,label="",recipe={}},
 terraqueous_jj_doodads_jj_5={hasPattern=false,label="",recipe={}},
 terraqueous_jj_doodads_jj_6={hasPattern=true,label="Glass Shards",recipe={terraqueous_jj_item_main_jj_108={need=4,tag=""}}},
 terraqueous_jj_doodads_jj_7={hasPattern=false,label="",recipe={}},
 terraqueous_jj_earth_ore={hasPattern=false,label="",recipe={}},
 terraqueous_jj_earth_ore_jj_1={hasPattern=false,label="",recipe={}},
 terraqueous_jj_earth_ore_jj_10={hasPattern=true,label="Burnium Block - Groove",recipe={terraqueous_jj_earth_ore_jj_7={need=1,tag=""}}},
 terraqueous_jj_earth_ore_jj_12={hasPattern=true,label="Endimium Block - Rings",recipe={terraqueous_jj_earth_ore_jj_9={need=1,tag=""}}},
 terraqueous_jj_earth_ore_jj_13={hasPattern=true,label="Burnium Block - Rings",recipe={terraqueous_jj_earth_ore_jj_10={need=1,tag=""}}},
 terraqueous_jj_earth_ore_jj_3={hasPattern=true,label="Endimium Block",recipe={terraqueous_jj_item_main_jj_51={need=9,tag=""}}},
 terraqueous_jj_earth_ore_jj_4={hasPattern=true,label="Burnium Block",recipe={terraqueous_jj_item_main_jj_50={need=9,tag=""}}},
 terraqueous_jj_earth_ore_jj_6={hasPattern=true,label="Smooth Endimium Block",recipe={terraqueous_jj_earth_ore_jj_3={need=1,tag=""},terraqueous_jj_hammer={need=1,tag=""}}},
 terraqueous_jj_earth_ore_jj_7={hasPattern=true,label="Smooth Burnium Block",recipe={terraqueous_jj_earth_ore_jj_4={need=1,tag=""},terraqueous_jj_hammer={need=1,tag=""}}},
 terraqueous_jj_earth_ore_jj_9={hasPattern=true,label="Endimium Block - Groove",recipe={terraqueous_jj_earth_ore_jj_6={need=1,tag=""}}},
 terraqueous_jj_ender_monocle={hasPattern=false,label="",recipe={}},
 terraqueous_jj_ender_table={hasPattern=true,label="EnderTable",recipe={minecraft_jj_diamond={need=2,tag=""},minecraft_jj_obsidian={need=4,tag=""},terraqueous_jj_item_main_jj_109={need=1,tag=""}}},
 terraqueous_jj_flowerpot={hasPattern=true,label="Flowerpot",recipe={minecraft_jj_brick={need=2,tag=""},minecraft_jj_netherbrick={need=1,tag=""}}},
 terraqueous_jj_flowerpot_jj_1={hasPattern=false,label="",recipe={}},
 terraqueous_jj_flowers_cluster={hasPattern=true,label="Black Rose Cluster",recipe={terraqueous_jj_flowers_single={need=3,tag=""}}},
 terraqueous_jj_flowers_cluster_jj_1={hasPattern=true,label="Carnation Cluster",recipe={terraqueous_jj_flowers_single_jj_1={need=3,tag=""}}},
 terraqueous_jj_flowers_cluster_jj_10={hasPattern=true,label="Deirdre Cluster",recipe={terraqueous_jj_flowers_single_jj_10={need=3,tag=""}}},
 terraqueous_jj_flowers_cluster_jj_11={hasPattern=true,label="Daffodil Cluster",recipe={terraqueous_jj_flowers_single_jj_11={need=3,tag=""}}},
 terraqueous_jj_flowers_cluster_jj_12={hasPattern=true,label="Blue Bell Cluster",recipe={terraqueous_jj_flowers_single_jj_12={need=3,tag=""}}},
 terraqueous_jj_flowers_cluster_jj_13={hasPattern=true,label="Primrose Cluster",recipe={terraqueous_jj_flowers_single_jj_13={need=3,tag=""}}},
 terraqueous_jj_flowers_cluster_jj_14={hasPattern=true,label="Marigold Cluster",recipe={terraqueous_jj_flowers_single_jj_14={need=3,tag=""}}},
 terraqueous_jj_flowers_cluster_jj_15={hasPattern=true,label="Tulip Cluster",recipe={terraqueous_jj_flowers_single_jj_15={need=3,tag=""}}},
 terraqueous_jj_flowers_cluster_jj_2={hasPattern=true,label="Fern Cluster",recipe={terraqueous_jj_flowers_single_jj_2={need=3,tag=""}}},
 terraqueous_jj_flowers_cluster_jj_3={hasPattern=true,label="Burdock Cluster",recipe={terraqueous_jj_flowers_single_jj_3={need=3,tag=""}}},
 terraqueous_jj_flowers_cluster_jj_4={hasPattern=true,label="Trickster Bloom Cluster",recipe={terraqueous_jj_flowers_single_jj_4={need=3,tag=""}}},
 terraqueous_jj_flowers_cluster_jj_5={hasPattern=true,label="Lavender Cluster",recipe={terraqueous_jj_flowers_single_jj_5={need=3,tag=""}}},
 terraqueous_jj_flowers_cluster_jj_6={hasPattern=true,label="Leichtlinii Cluster",recipe={terraqueous_jj_flowers_single_jj_6={need=3,tag=""}}},
 terraqueous_jj_flowers_cluster_jj_7={hasPattern=true,label="Ghost Plant Cluster",recipe={terraqueous_jj_flowers_single_jj_7={need=3,tag=""}}},
 terraqueous_jj_flowers_cluster_jj_8={hasPattern=true,label="Gray Ghost Plant Cluster",recipe={terraqueous_jj_flowers_single_jj_8={need=3,tag=""}}},
 terraqueous_jj_flowers_cluster_jj_9={hasPattern=true,label="Rose Cluster",recipe={terraqueous_jj_flowers_single_jj_9={need=3,tag=""}}},
 terraqueous_jj_flowers_single={hasPattern=true,label="Black Rose",recipe={terraqueous_jj_flowers_cluster={need=1,tag=""}}},
 terraqueous_jj_flowers_single_jj_1={hasPattern=true,label="Carnation",recipe={terraqueous_jj_flowers_cluster_jj_1={need=1,tag=""}}},
 terraqueous_jj_flowers_single_jj_10={hasPattern=true,label="Deirdre",recipe={terraqueous_jj_flowers_cluster_jj_10={need=1,tag=""}}},
 terraqueous_jj_flowers_single_jj_11={hasPattern=true,label="Daffodil",recipe={terraqueous_jj_flowers_cluster_jj_11={need=1,tag=""}}},
 terraqueous_jj_flowers_single_jj_12={hasPattern=true,label="Blue Bell",recipe={terraqueous_jj_flowers_cluster_jj_12={need=1,tag=""}}},
 terraqueous_jj_flowers_single_jj_13={hasPattern=true,label="Primrose",recipe={terraqueous_jj_flowers_cluster_jj_13={need=1,tag=""}}},
 terraqueous_jj_flowers_single_jj_14={hasPattern=true,label="Marigold",recipe={terraqueous_jj_flowers_cluster_jj_14={need=1,tag=""}}},
 terraqueous_jj_flowers_single_jj_15={hasPattern=true,label="Tulip",recipe={terraqueous_jj_flowers_cluster_jj_15={need=1,tag=""}}},
 terraqueous_jj_flowers_single_jj_2={hasPattern=true,label="Fern",recipe={terraqueous_jj_flowers_cluster_jj_2={need=1,tag=""}}},
 terraqueous_jj_flowers_single_jj_3={hasPattern=true,label="Burdock",recipe={terraqueous_jj_flowers_cluster_jj_3={need=1,tag=""}}},
 terraqueous_jj_flowers_single_jj_4={hasPattern=true,label="Trickster Bloom",recipe={terraqueous_jj_flowers_cluster_jj_4={need=1,tag=""}}},
 terraqueous_jj_flowers_single_jj_5={hasPattern=true,label="Lavender",recipe={terraqueous_jj_flowers_cluster_jj_5={need=1,tag=""}}},
 terraqueous_jj_flowers_single_jj_6={hasPattern=true,label="Leichtlinii",recipe={terraqueous_jj_flowers_cluster_jj_6={need=1,tag=""}}},
 terraqueous_jj_flowers_single_jj_7={hasPattern=true,label="Ghost Plant",recipe={terraqueous_jj_flowers_cluster_jj_7={need=1,tag=""}}},
 terraqueous_jj_flowers_single_jj_8={hasPattern=true,label="Gray Ghost Plant",recipe={terraqueous_jj_flowers_cluster_jj_8={need=1,tag=""}}},
 terraqueous_jj_flowers_single_jj_9={hasPattern=true,label="Rose",recipe={terraqueous_jj_flowers_cluster_jj_9={need=1,tag=""}}},
 terraqueous_jj_foliage1={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage1_jj_1={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage1_jj_2={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage1_jj_4={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage1_jj_5={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage1_jj_6={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage2={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage2_jj_1={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage2_jj_2={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage2_jj_4={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage2_jj_5={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage2_jj_6={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage3={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage3_jj_1={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage3_jj_2={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage3_jj_4={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage3_jj_5={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage3_jj_6={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage4={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage4_jj_1={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage4_jj_2={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage4_jj_4={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage4_jj_5={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage4_jj_6={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage5={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage5_jj_1={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage5_jj_10={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage5_jj_11={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage5_jj_8={hasPattern=false,label="",recipe={}},
 terraqueous_jj_foliage5_jj_9={hasPattern=false,label="",recipe={}},
 terraqueous_jj_hammer={hasPattern=true,label="Hammer",recipe={minecraft_jj_iron_block={need=1,tag=""},minecraft_jj_log={need=1,tag=""}}},
 terraqueous_jj_hay={hasPattern=true,label="Hay Block",recipe={terraqueous_jj_hay_jj_3={need=4,tag=""}}},
 terraqueous_jj_hay_jj_1={hasPattern=true,label="Large Hay Pile",recipe={terraqueous_jj_hay_jj_2={need=1,tag=""},terraqueous_jj_hay_jj_3={need=3,tag=""}}},
 terraqueous_jj_hay_jj_10={hasPattern=false,label="",recipe={}},
 terraqueous_jj_hay_jj_11={hasPattern=false,label="",recipe={}},
 terraqueous_jj_hay_jj_12={hasPattern=false,label="",recipe={}},
 terraqueous_jj_hay_jj_13={hasPattern=false,label="",recipe={}},
 terraqueous_jj_hay_jj_14={hasPattern=false,label="",recipe={}},
 terraqueous_jj_hay_jj_15={hasPattern=false,label="",recipe={}},
 terraqueous_jj_hay_jj_2={hasPattern=true,label="Hay Pile",recipe={terraqueous_jj_hay_jj_3={need=2,tag=""}}},
 terraqueous_jj_hay_jj_3={hasPattern=true,label="Small Hay Pile",recipe={terraqueous_jj_hay={need=1,tag=""},terraqueous_jj_hay_jj_4={need=2,tag=""}}},
 terraqueous_jj_hay_jj_4={hasPattern=true,label="Thresh",recipe={terraqueous_jj_hay_jj_5={need=2,tag=""}}},
 terraqueous_jj_hay_jj_5={hasPattern=false,label="",recipe={terraqueous_jj_hay_jj_4={need=1,tag=""}}},
 terraqueous_jj_hay_jj_6={hasPattern=false,label="",recipe={}},
 terraqueous_jj_hay_jj_7={hasPattern=false,label="",recipe={}},
 terraqueous_jj_hay_jj_8={hasPattern=false,label="",recipe={}},
 terraqueous_jj_hay_jj_9={hasPattern=false,label="",recipe={}},
 terraqueous_jj_item_main={hasPattern=true,label="Paint Brush",recipe={minecraft_jj_dye={need=1,tag=""},minecraft_jj_dye_jj_1={need=1,tag=""},minecraft_jj_dye_jj_11={need=1,tag=""},minecraft_jj_dye_jj_15={need=1,tag=""},minecraft_jj_dye_jj_4={need=1,tag=""},minecraft_jj_stick={need=2,tag=""},minecraft_jj_string={need=1,tag=""}}},
 terraqueous_jj_item_main_jj_1={hasPattern=true,label="Cloud Painting",recipe={terraqueous_jj_clouds={need=1,tag=""},terraqueous_jj_clouds_jj_1={need=8,tag=""}}},
 terraqueous_jj_item_main_jj_100={hasPattern=false,label="",recipe={terraqueous_jj_item_main_jj_102={need=1,tag=""}}},
 terraqueous_jj_item_main_jj_1002={hasPattern=false,label="",recipe={}},
 terraqueous_jj_item_main_jj_101={hasPattern=false,label="",recipe={}},
 terraqueous_jj_item_main_jj_102={hasPattern=false,label="",recipe={}},
 terraqueous_jj_item_main_jj_103={hasPattern=false,label="",recipe={}},
 terraqueous_jj_item_main_jj_104={hasPattern=true,label="Black Dye",recipe={terraqueous_jj_flowers_single={need=2,tag=""}}},
 terraqueous_jj_item_main_jj_105={hasPattern=true,label="Brown Dye",recipe={terraqueous_jj_flowers_single_jj_3={need=2,tag=""}}},
 terraqueous_jj_item_main_jj_106={hasPattern=true,label="Blue Dye",recipe={terraqueous_jj_flowers_single_jj_4={need=2,tag=""}}},
 terraqueous_jj_item_main_jj_107={hasPattern=true,label="White Dye",recipe={terraqueous_jj_flowers_single_jj_15={need=2,tag=""}}},
 terraqueous_jj_item_main_jj_108={hasPattern=false,label="",recipe={}},
 terraqueous_jj_item_main_jj_109={hasPattern=true,label="Ender Book",recipe={minecraft_jj_book={need=1,tag=""},minecraft_jj_ender_eye={need=1,tag=""},terraqueous_jj_item_main_jj_251={need=1,tag=""}}},
 terraqueous_jj_item_main_jj_2={hasPattern=true,label="Earth Painting",recipe={minecraft_jj_paper={need=1,tag=""},minecraft_jj_stick={need=8,tag=""}}},
 terraqueous_jj_item_main_jj_200={hasPattern=false,label="",recipe={}},
 terraqueous_jj_item_main_jj_201={hasPattern=true,label="Ender Dust",recipe={minecraft_jj_ender_pearl={need=1,tag=""},terraqueous_jj_hammer={need=1,tag=""}}},
 terraqueous_jj_item_main_jj_202={hasPattern=false,label="",recipe={}},
 terraqueous_jj_item_main_jj_203={hasPattern=true,label="Iron Dust",recipe={terraqueous_jj_item_main_jj_202={need=4,tag=""}}},
 terraqueous_jj_item_main_jj_204={hasPattern=false,label="",recipe={}},
 terraqueous_jj_item_main_jj_205={hasPattern=true,label="Gold Dust",recipe={terraqueous_jj_item_main_jj_204={need=4,tag=""}}},
 terraqueous_jj_item_main_jj_206={hasPattern=false,label="",recipe={}},
 terraqueous_jj_item_main_jj_207={hasPattern=true,label="Coal Dust",recipe={minecraft_jj_coal={need=1,tag=""},terraqueous_jj_hammer={need=1,tag=""},terraqueous_jj_item_main_jj_206={need=4,tag=""}}},
 terraqueous_jj_item_main_jj_208={hasPattern=false,label="",recipe={}},
 terraqueous_jj_item_main_jj_209={hasPattern=true,label="Diamond Dust",recipe={minecraft_jj_diamond={need=1,tag=""},terraqueous_jj_hammer={need=1,tag=""}}},
 terraqueous_jj_item_main_jj_210={hasPattern=false,label="",recipe={}},
 terraqueous_jj_item_main_jj_211={hasPattern=true,label="Emerald Dust",recipe={terraqueous_jj_item_main_jj_210={need=4,tag=""}}},
 terraqueous_jj_item_main_jj_212={hasPattern=false,label="",recipe={}},
 terraqueous_jj_item_main_jj_213={hasPattern=false,label="",recipe={}},
 terraqueous_jj_item_main_jj_214={hasPattern=false,label="",recipe={}},
 terraqueous_jj_item_main_jj_215={hasPattern=false,label="",recipe={}},
 terraqueous_jj_item_main_jj_216={hasPattern=false,label="",recipe={}},
 terraqueous_jj_item_main_jj_250={hasPattern=false,label="",recipe={}},
 terraqueous_jj_item_main_jj_251={hasPattern=true,label="Burnium Dust",recipe={ic2_jj_dust_jj_2={need=1,tag=""},minecraft_jj_blaze_powder={need=1,tag=""},terraqueous_jj_item_main_jj_250={need=4,tag=""}}},
 terraqueous_jj_item_main_jj_252={hasPattern=false,label="",recipe={}},
 terraqueous_jj_item_main_jj_253={hasPattern=true,label="Endimium Dust",recipe={appliedenergistics2_jj_material_jj_46={need=1,tag=""},ic2_jj_dust_jj_5={need=1,tag=""},terraqueous_jj_item_main_jj_201={need=1,tag=""},terraqueous_jj_item_main_jj_209={need=1,tag=""}}},
 terraqueous_jj_item_main_jj_3={hasPattern=false,label="",recipe={minecraft_jj_clay={need=3,tag=""},minecraft_jj_feather={need=2,tag=""},terraqueous_jj_item_main_jj_51={need=1,tag=""}}},
 terraqueous_jj_item_main_jj_4={hasPattern=false,label="",recipe={}},
 terraqueous_jj_item_main_jj_5={hasPattern=true,label="Assembled Cloud Talisman",recipe={minecraft_jj_feather={need=2,tag=""},terraqueous_jj_item_main_jj_4={need=1,tag=""},terraqueous_jj_item_main_jj_51={need=1,tag=""}}},
 terraqueous_jj_item_main_jj_50={hasPattern=true,label="Burnium",recipe={terraqueous_jj_earth_ore_jj_4={need=1,tag=""}}},
 terraqueous_jj_item_main_jj_51={hasPattern=true,label="Endimium",recipe={terraqueous_jj_earth_ore_jj_3={need=1,tag=""}}},
 terraqueous_jj_multifood={hasPattern=false,label="",recipe={}},
 terraqueous_jj_multifood_jj_1={hasPattern=false,label="",recipe={}},
 terraqueous_jj_multifood_jj_10={hasPattern=false,label="",recipe={}},
 terraqueous_jj_multifood_jj_11={hasPattern=false,label="",recipe={}},
 terraqueous_jj_multifood_jj_12={hasPattern=false,label="",recipe={}},
 terraqueous_jj_multifood_jj_13={hasPattern=false,label="",recipe={}},
 terraqueous_jj_multifood_jj_2={hasPattern=false,label="",recipe={}},
 terraqueous_jj_multifood_jj_3={hasPattern=false,label="",recipe={}},
 terraqueous_jj_multifood_jj_4={hasPattern=false,label="",recipe={}},
 terraqueous_jj_multifood_jj_5={hasPattern=false,label="",recipe={}},
 terraqueous_jj_multifood_jj_6={hasPattern=false,label="",recipe={}},
 terraqueous_jj_multifood_jj_7={hasPattern=false,label="",recipe={}},
 terraqueous_jj_multifood_jj_8={hasPattern=false,label="",recipe={}},
 terraqueous_jj_multifood_jj_9={hasPattern=false,label="",recipe={}},
 terraqueous_jj_multitool={hasPattern=false,label="",recipe={}},
 terraqueous_jj_multitool_jj_1561={hasPattern=false,label="",recipe={}},
 terraqueous_jj_pergola={hasPattern=false,label="",recipe={}},
 terraqueous_jj_pergola_jj_1={hasPattern=false,label="",recipe={}},
 terraqueous_jj_pergola_jj_2={hasPattern=false,label="",recipe={}},
 terraqueous_jj_pergola_jj_3={hasPattern=false,label="",recipe={}},
 terraqueous_jj_pergola_jj_4={hasPattern=false,label="",recipe={}},
 terraqueous_jj_pergola_jj_5={hasPattern=false,label="",recipe={}},
 terraqueous_jj_pergola_jj_6={hasPattern=false,label="",recipe={}},
 terraqueous_jj_pergola_jj_7={hasPattern=false,label="",recipe={}},
 terraqueous_jj_pergola_jj_8={hasPattern=false,label="",recipe={}},
 terraqueous_jj_pitchfork={hasPattern=true,label="Pitchfork",recipe={minecraft_jj_iron_ingot={need=2,tag=""},minecraft_jj_stick={need=2,tag=""}}},
 terraqueous_jj_planks={hasPattern=false,label="",recipe={terraqueous_jj_trunk1={need=1,tag=""}}},
 terraqueous_jj_planks_jj_1={hasPattern=false,label="",recipe={terraqueous_jj_trunk1_jj_1={need=1,tag=""}}},
 terraqueous_jj_planks_jj_2={hasPattern=false,label="",recipe={terraqueous_jj_trunk1_jj_2={need=1,tag=""}}},
 terraqueous_jj_planks_jj_3={hasPattern=false,label="",recipe={terraqueous_jj_trunk1_jj_3={need=1,tag=""}}},
 terraqueous_jj_planks_jj_4={hasPattern=false,label="",recipe={terraqueous_jj_trunk1_jj_4={need=1,tag=""}}},
 terraqueous_jj_planks_jj_5={hasPattern=false,label="",recipe={terraqueous_jj_trunk2={need=1,tag=""}}},
 terraqueous_jj_planks_jj_6={hasPattern=false,label="",recipe={terraqueous_jj_trunk2_jj_1={need=1,tag=""}}},
 terraqueous_jj_planks_jj_7={hasPattern=false,label="",recipe={terraqueous_jj_trunk2_jj_2={need=1,tag=""}}},
 terraqueous_jj_planks_jj_8={hasPattern=false,label="",recipe={terraqueous_jj_trunk2_jj_3={need=1,tag=""}}},
 terraqueous_jj_planks_jj_9={hasPattern=false,label="",recipe={terraqueous_jj_trunk2_jj_4={need=1,tag=""}}},
 terraqueous_jj_plants={hasPattern=false,label="",recipe={}},
 terraqueous_jj_plants_jj_1={hasPattern=false,label="",recipe={}},
 terraqueous_jj_plants_jj_2={hasPattern=false,label="",recipe={}},
 terraqueous_jj_plants_jj_3={hasPattern=false,label="",recipe={}},
 terraqueous_jj_plants_jj_4={hasPattern=false,label="",recipe={terraqueous_jj_plants_jj_3={need=2,tag=""}}},
 terraqueous_jj_plants_jj_5={hasPattern=false,label="",recipe={terraqueous_jj_multifood_jj_10={need=2,tag=""},terraqueous_jj_plants_jj_4={need=1,tag=""}}},
 terraqueous_jj_sapling={hasPattern=false,label="",recipe={}},
 terraqueous_jj_sapling_jj_1={hasPattern=false,label="",recipe={}},
 terraqueous_jj_sapling_jj_2={hasPattern=false,label="",recipe={}},
 terraqueous_jj_sapling_jj_3={hasPattern=false,label="",recipe={}},
 terraqueous_jj_sapling_jj_4={hasPattern=false,label="",recipe={}},
 terraqueous_jj_sapling_jj_5={hasPattern=false,label="",recipe={}},
 terraqueous_jj_sapling_jj_6={hasPattern=false,label="",recipe={}},
 terraqueous_jj_sapling_jj_7={hasPattern=false,label="",recipe={}},
 terraqueous_jj_sapling_jj_8={hasPattern=false,label="",recipe={}},
 terraqueous_jj_sapling_jj_9={hasPattern=false,label="",recipe={}},
 terraqueous_jj_scythe={hasPattern=false,label="",recipe={}},
 terraqueous_jj_toon_trotters={hasPattern=false,label="",recipe={}},
 terraqueous_jj_trunk1={hasPattern=false,label="",recipe={}},
 terraqueous_jj_trunk1_jj_1={hasPattern=false,label="",recipe={}},
 terraqueous_jj_trunk1_jj_2={hasPattern=false,label="",recipe={}},
 terraqueous_jj_trunk1_jj_3={hasPattern=false,label="",recipe={}},
 terraqueous_jj_trunk1_jj_4={hasPattern=false,label="",recipe={}},
 terraqueous_jj_trunk2={hasPattern=false,label="",recipe={}},
 terraqueous_jj_trunk2_jj_1={hasPattern=false,label="",recipe={}},
 terraqueous_jj_trunk2_jj_2={hasPattern=false,label="",recipe={}},
 terraqueous_jj_trunk2_jj_3={hasPattern=false,label="",recipe={}},
 terraqueous_jj_trunk2_jj_4={hasPattern=false,label="",recipe={}},
 terraqueous_jj_type_cloud={hasPattern=true,label="Light Cloud Door",recipe={terraqueous_jj_clouds={need=6,tag=""}}},
 terraqueous_jj_type_cloud_jj_1={hasPattern=true,label="Dense Cloud Door",recipe={terraqueous_jj_clouds_jj_1={need=6,tag=""}}},
 terraqueous_jj_type_cloud_jj_10={hasPattern=true,label="Light Cloud Trapdoor",recipe={terraqueous_jj_clouds={need=6,tag=""}}},
 terraqueous_jj_type_cloud_jj_11={hasPattern=true,label="Dense Cloud Trapdoor",recipe={terraqueous_jj_clouds_jj_1={need=6,tag=""}}},
 terraqueous_jj_type_cloud_jj_110={hasPattern=false,label="",recipe={}},
 terraqueous_jj_type_cloud_jj_12={hasPattern=true,label="Storm Cloud Trapdoor",recipe={terraqueous_jj_clouds_jj_2={need=6,tag=""}}},
 terraqueous_jj_type_cloud_jj_120={hasPattern=false,label="",recipe={}},
 terraqueous_jj_type_cloud_jj_2={hasPattern=true,label="Storm Cloud Door",recipe={terraqueous_jj_clouds_jj_2={need=6,tag=""}}},
 terraqueous_jj_type_cloud_jj_20={hasPattern=true,label="Light Cloud Gate",recipe={terraqueous_jj_clouds={need=2,tag=""},terraqueous_jj_type_cloud_jj_110={need=4,tag=""}}},
 terraqueous_jj_type_cloud_jj_21={hasPattern=true,label="Dense Cloud Gate",recipe={terraqueous_jj_clouds={need=4,tag=""},terraqueous_jj_clouds_jj_1={need=2,tag=""}}},
 terraqueous_jj_type_cloud_jj_22={hasPattern=true,label="Storm Cloud Gate",recipe={terraqueous_jj_clouds_jj_1={need=4,tag=""},terraqueous_jj_clouds_jj_2={need=2,tag=""}}},
 terraqueous_jj_type_cloud_jj_30={hasPattern=true,label="Light Cloud Wall",recipe={terraqueous_jj_clouds={need=4,tag=""},terraqueous_jj_type_cloud_jj_110={need=2,tag=""}}},
 terraqueous_jj_type_cloud_jj_31={hasPattern=true,label="Dense Cloud Wall",recipe={terraqueous_jj_clouds={need=2,tag=""},terraqueous_jj_clouds_jj_1={need=4,tag=""}}},
 terraqueous_jj_type_cloud_jj_32={hasPattern=true,label="Storm Cloud Wall",recipe={terraqueous_jj_clouds_jj_1={need=2,tag=""},terraqueous_jj_clouds_jj_2={need=4,tag=""}}},
 terraqueous_jj_type_cloud_jj_40={hasPattern=true,label="Light Cloud Stairs",recipe={terraqueous_jj_clouds={need=6,tag=""}}},
 terraqueous_jj_type_cloud_jj_41={hasPattern=true,label="Dense Cloud Stairs",recipe={terraqueous_jj_clouds_jj_1={need=6,tag=""}}},
 terraqueous_jj_type_cloud_jj_42={hasPattern=true,label="Storm Cloud Stairs",recipe={terraqueous_jj_clouds_jj_2={need=6,tag=""}}},
 terraqueous_jj_type_cloud_jj_50={hasPattern=true,label="Light Cloud Slab",recipe={terraqueous_jj_clouds={need=3,tag=""}}},
 terraqueous_jj_type_cloud_jj_51={hasPattern=true,label="Dense Cloud Slab",recipe={terraqueous_jj_clouds_jj_1={need=3,tag=""}}},
 terraqueous_jj_type_cloud_jj_52={hasPattern=true,label="Storm Cloud Slab",recipe={terraqueous_jj_clouds_jj_2={need=3,tag=""}}},
 terraqueous_jj_type_earth={hasPattern=true,label="Apple Wood Door",recipe={terraqueous_jj_planks={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_1={hasPattern=true,label="Cherry Wood Door",recipe={terraqueous_jj_planks_jj_1={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_10={hasPattern=true,label="Apple Wood Trapdoor",recipe={terraqueous_jj_planks={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_11={hasPattern=true,label="Cherry Wood Trapdoor",recipe={terraqueous_jj_planks_jj_1={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_110={hasPattern=false,label="",recipe={}},
 terraqueous_jj_type_earth_jj_12={hasPattern=true,label="Orange Wood Trapdoor",recipe={terraqueous_jj_planks_jj_2={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_120={hasPattern=false,label="",recipe={}},
 terraqueous_jj_type_earth_jj_13={hasPattern=true,label="Pear Wood Trapdoor",recipe={terraqueous_jj_planks_jj_3={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_14={hasPattern=true,label="Peach Wood Trapdoor",recipe={terraqueous_jj_planks_jj_4={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_15={hasPattern=true,label="Mango Wood Trapdoor",recipe={terraqueous_jj_planks_jj_5={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_16={hasPattern=true,label="Lemon Wood Trapdoor",recipe={terraqueous_jj_planks_jj_6={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_17={hasPattern=true,label="Plum Wood Trapdoor",recipe={terraqueous_jj_planks_jj_7={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_18={hasPattern=true,label="Coconut Wood Trapdoor",recipe={terraqueous_jj_planks_jj_8={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_19={hasPattern=true,label="Banana Wood Trapdoor",recipe={terraqueous_jj_planks_jj_9={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_2={hasPattern=true,label="Orange Wood Door",recipe={terraqueous_jj_planks_jj_2={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_20={hasPattern=true,label="Apple Wood Gate",recipe={minecraft_jj_stick={need=4,tag=""},terraqueous_jj_planks={need=2,tag=""}}},
 terraqueous_jj_type_earth_jj_21={hasPattern=true,label="Cherry Wood Gate",recipe={minecraft_jj_stick={need=4,tag=""},terraqueous_jj_planks_jj_1={need=2,tag=""}}},
 terraqueous_jj_type_earth_jj_22={hasPattern=true,label="Orange Wood Gate",recipe={minecraft_jj_stick={need=4,tag=""},terraqueous_jj_planks_jj_2={need=2,tag=""}}},
 terraqueous_jj_type_earth_jj_23={hasPattern=true,label="Pear Wood Gate",recipe={minecraft_jj_stick={need=4,tag=""},terraqueous_jj_planks_jj_3={need=2,tag=""}}},
 terraqueous_jj_type_earth_jj_24={hasPattern=true,label="Peach Wood Gate",recipe={minecraft_jj_stick={need=4,tag=""},terraqueous_jj_planks_jj_4={need=2,tag=""}}},
 terraqueous_jj_type_earth_jj_25={hasPattern=true,label="Mango Wood Gate",recipe={minecraft_jj_stick={need=4,tag=""},terraqueous_jj_planks_jj_5={need=2,tag=""}}},
 terraqueous_jj_type_earth_jj_26={hasPattern=true,label="Lemon Wood Gate",recipe={minecraft_jj_stick={need=4,tag=""},terraqueous_jj_planks_jj_6={need=2,tag=""}}},
 terraqueous_jj_type_earth_jj_27={hasPattern=true,label="Plum Wood Gate",recipe={minecraft_jj_stick={need=4,tag=""},terraqueous_jj_planks_jj_7={need=2,tag=""}}},
 terraqueous_jj_type_earth_jj_28={hasPattern=true,label="Coconut Wood Gate",recipe={minecraft_jj_stick={need=4,tag=""},terraqueous_jj_planks_jj_8={need=2,tag=""}}},
 terraqueous_jj_type_earth_jj_29={hasPattern=true,label="Banana Wood Gate",recipe={minecraft_jj_stick={need=4,tag=""},terraqueous_jj_planks_jj_9={need=2,tag=""}}},
 terraqueous_jj_type_earth_jj_3={hasPattern=true,label="Pear Wood Door",recipe={terraqueous_jj_planks_jj_3={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_30={hasPattern=true,label="Apple Wood Fence",recipe={minecraft_jj_stick={need=2,tag=""},terraqueous_jj_planks={need=4,tag=""}}},
 terraqueous_jj_type_earth_jj_31={hasPattern=true,label="Cherry Wood Fence",recipe={minecraft_jj_stick={need=2,tag=""},terraqueous_jj_planks_jj_1={need=4,tag=""}}},
 terraqueous_jj_type_earth_jj_32={hasPattern=true,label="Orange Wood Fence",recipe={minecraft_jj_stick={need=2,tag=""},terraqueous_jj_planks_jj_2={need=4,tag=""}}},
 terraqueous_jj_type_earth_jj_33={hasPattern=true,label="Pear Wood Fence",recipe={minecraft_jj_stick={need=2,tag=""},terraqueous_jj_planks_jj_3={need=4,tag=""}}},
 terraqueous_jj_type_earth_jj_34={hasPattern=true,label="Peach Wood Fence",recipe={minecraft_jj_stick={need=2,tag=""},terraqueous_jj_planks_jj_4={need=4,tag=""}}},
 terraqueous_jj_type_earth_jj_35={hasPattern=true,label="Mango Wood Fence",recipe={minecraft_jj_stick={need=2,tag=""},terraqueous_jj_planks_jj_5={need=4,tag=""}}},
 terraqueous_jj_type_earth_jj_36={hasPattern=true,label="Lemon Wood Fence",recipe={minecraft_jj_stick={need=2,tag=""},terraqueous_jj_planks_jj_6={need=4,tag=""}}},
 terraqueous_jj_type_earth_jj_37={hasPattern=true,label="Plum Wood Fence",recipe={minecraft_jj_stick={need=2,tag=""},terraqueous_jj_planks_jj_7={need=4,tag=""}}},
 terraqueous_jj_type_earth_jj_38={hasPattern=true,label="Coconut Wood Fence",recipe={minecraft_jj_stick={need=2,tag=""},terraqueous_jj_planks_jj_8={need=4,tag=""}}},
 terraqueous_jj_type_earth_jj_39={hasPattern=true,label="Banana Wood Fence",recipe={minecraft_jj_stick={need=2,tag=""},terraqueous_jj_planks_jj_9={need=4,tag=""}}},
 terraqueous_jj_type_earth_jj_4={hasPattern=true,label="Peach Wood Door",recipe={terraqueous_jj_planks_jj_4={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_40={hasPattern=true,label="Apple Wood Stairs",recipe={terraqueous_jj_planks={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_41={hasPattern=true,label="Cherry Wood Stairs",recipe={terraqueous_jj_planks_jj_1={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_42={hasPattern=true,label="Orange Wood Stairs",recipe={terraqueous_jj_planks_jj_2={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_43={hasPattern=true,label="Pear Wood Stairs",recipe={terraqueous_jj_planks_jj_3={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_44={hasPattern=true,label="Peach Wood Stairs",recipe={terraqueous_jj_planks_jj_4={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_45={hasPattern=true,label="Mango Wood Stairs",recipe={terraqueous_jj_planks_jj_5={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_46={hasPattern=true,label="Lemon Wood Stairs",recipe={terraqueous_jj_planks_jj_6={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_47={hasPattern=true,label="Plum Wood Stairs",recipe={terraqueous_jj_planks_jj_7={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_48={hasPattern=true,label="Coconut Wood Stairs",recipe={terraqueous_jj_planks_jj_8={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_49={hasPattern=true,label="Banana Wood Stairs",recipe={terraqueous_jj_planks_jj_9={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_5={hasPattern=true,label="Mango Wood Door",recipe={terraqueous_jj_planks_jj_5={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_50={hasPattern=true,label="Apple Wood Slab",recipe={terraqueous_jj_planks={need=3,tag=""}}},
 terraqueous_jj_type_earth_jj_51={hasPattern=true,label="Cherry Wood Slab",recipe={terraqueous_jj_planks_jj_1={need=3,tag=""}}},
 terraqueous_jj_type_earth_jj_52={hasPattern=true,label="Orange Wood Slab",recipe={terraqueous_jj_planks_jj_2={need=3,tag=""}}},
 terraqueous_jj_type_earth_jj_53={hasPattern=true,label="Pear Wood Slab",recipe={terraqueous_jj_planks_jj_3={need=3,tag=""}}},
 terraqueous_jj_type_earth_jj_54={hasPattern=true,label="Peach Wood Slab",recipe={terraqueous_jj_planks_jj_4={need=3,tag=""}}},
 terraqueous_jj_type_earth_jj_55={hasPattern=true,label="Mango Wood Slab",recipe={terraqueous_jj_planks_jj_5={need=3,tag=""}}},
 terraqueous_jj_type_earth_jj_56={hasPattern=true,label="Lemon Wood Slab",recipe={terraqueous_jj_planks_jj_6={need=3,tag=""}}},
 terraqueous_jj_type_earth_jj_57={hasPattern=true,label="Plum Wood Slab",recipe={terraqueous_jj_planks_jj_7={need=3,tag=""}}},
 terraqueous_jj_type_earth_jj_58={hasPattern=true,label="Coconut Wood Slab",recipe={terraqueous_jj_planks_jj_8={need=3,tag=""}}},
 terraqueous_jj_type_earth_jj_59={hasPattern=true,label="Banana Wood Slab",recipe={terraqueous_jj_planks_jj_9={need=3,tag=""}}},
 terraqueous_jj_type_earth_jj_6={hasPattern=true,label="Lemon Wood Door",recipe={terraqueous_jj_planks_jj_6={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_7={hasPattern=true,label="Plum Wood Door",recipe={terraqueous_jj_planks_jj_7={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_8={hasPattern=true,label="Coconut Wood Door",recipe={terraqueous_jj_planks_jj_8={need=6,tag=""}}},
 terraqueous_jj_type_earth_jj_9={hasPattern=true,label="Banana Wood Door",recipe={terraqueous_jj_planks_jj_9={need=6,tag=""}}},
 terraqueous_jj_water_pearl={hasPattern=false,label="",recipe={}},
 teslacorelib_jj_base_addon={hasPattern=true,label="Base Addon",recipe={minecraft_jj_paper={need=7,tag=""},minecraft_jj_redstone={need=2,tag=""}}},
 teslacorelib_jj_battery={hasPattern=true,label="Tesla Battery",recipe={minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_redstone={need=4,tag=""},minecraft_jj_redstone_block={need=1,tag=""}}},
 teslacorelib_jj_energy_tier1={hasPattern=true,label="Energy Upgrade I",recipe={basemetals_jj_gold_gear={need=1,tag=""},minecraft_jj_redstone={need=5,tag=""},teslacorelib_jj_base_addon={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=1,tag=""}}},
 teslacorelib_jj_energy_tier2={hasPattern=false,label="",recipe={minecraft_jj_diamond={need=4,tag=""},teslacorelib_jj_energy_tier1={need=1,tag=""}}},
 teslacorelib_jj_machine_case={hasPattern=true,label="Machine Case",recipe={minecraft_jj_iron_ingot={need=4,tag=""},minecraft_jj_planks={need=4,tag=""},minecraft_jj_redstone_block={need=1,tag=""}}},
 teslacorelib_jj_speed_tier1={hasPattern=true,label="Speed Upgrade I",recipe={basemetals_jj_gold_gear={need=2,tag=""},minecraft_jj_redstone={need=6,tag=""},teslacorelib_jj_base_addon={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=2,tag=""}}},
 teslacorelib_jj_speed_tier2={hasPattern=false,label="",recipe={minecraft_jj_diamond={need=4,tag=""},teslacorelib_jj_speed_tier1={need=1,tag=""}}},
 teslacorelib_jj_wrench={hasPattern=true,label="Tesla Wrench",recipe={minecraft_jj_dye_jj_4={need=1,tag=""},minecraft_jj_iron_ingot={need=3,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 teslathingies_jj_addon_range_tier1={hasPattern=true,label="Range Addon I",recipe={basemetals_jj_gold_gear={need=1,tag=""},minecraft_jj_redstone={need=3,tag=""},teslacorelib_jj_base_addon={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=1,tag=""}}},
 teslathingies_jj_addon_range_tier2={hasPattern=false,label="",recipe={minecraft_jj_redstone={need=3,tag=""},teslacorelib_jj_base_addon={need=1,tag=""},teslacorelib_jj_gear_diamond={need=1,tag=""}}},
 teslathingies_jj_animal_age_filter_adult={hasPattern=true,label="Animal Filter (adults)",recipe={minecraft_jj_redstone={need=3,tag=""},teslathingies_jj_animal_filter={need=1,tag=""}}},
 teslathingies_jj_animal_age_filter_baby={hasPattern=true,label="Animal Filter (baby)",recipe={minecraft_jj_redstone={need=3,tag=""},teslathingies_jj_animal_filter={need=1,tag=""}}},
 teslathingies_jj_animal_farm={hasPattern=false,label="",recipe={minecraft_jj_carrot={need=1,tag=""},minecraft_jj_planks={need=4,tag=""},minecraft_jj_wheat={need=2,tag=""},teslacorelib_jj_gear_stone={need=1,tag=""},teslacorelib_jj_machine_case={need=1,tag=""}}},
 teslathingies_jj_animal_filter={hasPattern=true,label="Animal Filter",recipe={minecraft_jj_wheat={need=4,tag=""},teslacorelib_jj_base_addon={need=1,tag=""}}},
 teslathingies_jj_animal_gym={hasPattern=true,label="Animal Gym",recipe={basemetals_jj_iron_gear={need=2,tag=""},minecraft_jj_iron_bars={need=2,tag=""},minecraft_jj_planks={need=4,tag=""},teslacorelib_jj_machine_case={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=2,tag=""}}},
 teslathingies_jj_animal_package={hasPattern=true,label="Animal Package",recipe={minecraft_jj_iron_bars={need=4,tag=""},minecraft_jj_planks={need=4,tag=""},minecraft_jj_redstone={need=1,tag=""}}},
 teslathingies_jj_animal_releaser={hasPattern=false,label="",recipe={minecraft_jj_dispenser={need=1,tag=""},minecraft_jj_planks={need=6,tag=""},teslacorelib_jj_gear_stone={need=1,tag=""},teslacorelib_jj_machine_case={need=1,tag=""}}},
 teslathingies_jj_ash={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_adamantine={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_aluminum={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_antimony={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_bismuth={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_cadmium={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_chromium={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_coal={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_coldiron={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_copper={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_diamond={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_emerald={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_gold={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_iridium={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_iron={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_lapis={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_lead={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_magnesium={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_manganese={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_mercury={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_mithril={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_nickel={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_osmium={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_platinum={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_plutonium={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_redstone={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_rutile={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_silver={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_starsteel={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_steel={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_tantalum={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_tin={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_titanium={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_tungsten={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_uranium={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_zinc={hasPattern=false,label="",recipe={}},
 teslathingies_jj_augmented_zirconium={hasPattern=false,label="",recipe={}},
 teslathingies_jj_bush_master_addon={hasPattern=true,label="Bush Master Addon",recipe={biomesoplenty_jj_berries={need=3,tag=""},extratrees_jj_food_jj_7={need=3,tag=""},minecraft_jj_hopper={need=1,tag=""},minecraft_jj_stick={need=2,tag=""},plants2_jj_blueberry={need=3,tag=""},plants2_jj_huckleberry={need=3,tag=""},rustic_jj_chili_pepper={need=3,tag=""},rustic_jj_grapes={need=3,tag=""},rustic_jj_ironberries={need=3,tag=""},rustic_jj_tomato={need=3,tag=""},rustic_jj_wildberries={need=3,tag=""},teslacorelib_jj_base_addon={need=1,tag=""}}},
 teslathingies_jj_compound_maker={hasPattern=true,label="Compound Maker",recipe={basemetals_jj_gold_gear={need=1,tag=""},basemetals_jj_iron_gear={need=2,tag=""},minecraft_jj_glass={need=2,tag=""},minecraft_jj_stone={need=3,tag=""},teslacorelib_jj_machine_case={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=2,tag=""},thermalfoundation_jj_material_jj_25={need=1,tag=""}}},
 teslathingies_jj_crop_cloner={hasPattern=true,label="Crop Cloner",recipe={basemetals_jj_iron_gear={need=1,tag=""},minecraft_jj_diamond_hoe={need=1,tag=""},minecraft_jj_dirt={need=2,tag=""},minecraft_jj_planks={need=2,tag=""},minecraft_jj_redstone_block={need=2,tag=""},teslacorelib_jj_machine_case={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=1,tag=""}}},
 teslathingies_jj_crop_farm={hasPattern=false,label="",recipe={minecraft_jj_diamond_hoe={need=1,tag=""},minecraft_jj_planks={need=2,tag=""},teslacorelib_jj_gear_stone={need=1,tag=""},teslacorelib_jj_machine_case={need=1,tag=""}}},
 teslathingies_jj_dung_block={hasPattern=true,label="Dung Block",recipe={forge_jj_bucketfilled={need=1,tag=""},minecraft_jj_clay={need=1,tag=""},minecraft_jj_hay_block={need=1,tag=""},minecraft_jj_water_bucket={need=1,tag=""}}},
 teslathingies_jj_dung_bricks={hasPattern=true,label="Dung Bricks",recipe={teslathingies_jj_dung_block={need=4,tag=""}}},
 teslathingies_jj_electric_butcher={hasPattern=true,label="Electric Butcher",recipe={basemetals_jj_iron_gear={need=1,tag=""},minecraft_jj_diamond_sword={need=1,tag=""},minecraft_jj_planks={need=6,tag=""},teslacorelib_jj_machine_case={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=1,tag=""}}},
 teslathingies_jj_fluid_burner={hasPattern=true,label="Fluid Burner",recipe={basemetals_jj_iron_gear={need=1,tag=""},minecraft_jj_bucket={need=2,tag=""},minecraft_jj_stone={need=5,tag=""},teslacorelib_jj_machine_case={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=1,tag=""}}},
 teslathingies_jj_fluid_compound_producer={hasPattern=true,label="Fluid Compound Producer",recipe={basemetals_jj_gold_gear={need=1,tag=""},minecraft_jj_glass={need=2,tag=""},minecraft_jj_stone={need=5,tag=""},teslacorelib_jj_machine_case={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=1,tag=""}}},
 teslathingies_jj_fluid_solidifier={hasPattern=true,label="Fluid Solidifier",recipe={basemetals_jj_iron_gear={need=1,tag=""},minecraft_jj_bucket={need=2,tag=""},minecraft_jj_obsidian={need=5,tag=""},teslacorelib_jj_machine_case={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=1,tag=""}}},
 teslathingies_jj_fruit_picker_addon={hasPattern=true,label="Fruit Picker Addon",recipe={minecraft_jj_hopper={need=1,tag=""},minecraft_jj_sapling={need=3,tag=""},minecraft_jj_stick={need=2,tag=""},teslacorelib_jj_base_addon={need=1,tag=""}}},
 teslathingies_jj_incinerator={hasPattern=true,label="Incinerator",recipe={minecraft_jj_flint_and_steel={need=1,tag=""},minecraft_jj_furnace={need=1,tag=""},minecraft_jj_stone={need=6,tag=""},teslacorelib_jj_machine_case={need=1,tag=""}}},
 teslathingies_jj_item_compound_producer={hasPattern=true,label="Item Compound Producer",recipe={basemetals_jj_gold_gear={need=1,tag=""},minecraft_jj_glass={need=2,tag=""},minecraft_jj_planks={need=2,tag=""},minecraft_jj_stone={need=3,tag=""},teslacorelib_jj_machine_case={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=1,tag=""}}},
 teslathingies_jj_item_liquefier={hasPattern=true,label="Item Liquefier",recipe={basemetals_jj_iron_gear={need=1,tag=""},minecraft_jj_lava_bucket={need=2,tag=""},minecraft_jj_obsidian={need=5,tag=""},teslacorelib_jj_machine_case={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=1,tag=""}}},
 teslathingies_jj_liquidxp_collector={hasPattern=true,label="XP Orb Collector Addon",recipe={basemetals_jj_iron_gear={need=2,tag=""},minecraft_jj_experience_bottle={need=1,tag=""},minecraft_jj_glass_bottle={need=3,tag=""},teslacorelib_jj_base_addon={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=2,tag=""}}},
 teslathingies_jj_liquidxp_storage={hasPattern=true,label="Liquid XP Storage",recipe={basemetals_jj_iron_gear={need=1,tag=""},minecraft_jj_experience_bottle={need=1,tag=""},minecraft_jj_planks={need=4,tag=""},teslacorelib_jj_machine_case={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=1,tag=""}}},
 teslathingies_jj_lump_adamantine={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_aluminum={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_antimony={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_bismuth={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_cadmium={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_chromium={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_coal={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_coldiron={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_copper={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_diamond={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_emerald={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_gold={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_iridium={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_iron={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_lapis={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_lead={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_magnesium={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_manganese={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_mercury={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_mithril={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_nickel={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_osmium={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_platinum={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_plutonium={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_redstone={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_rutile={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_silver={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_starsteel={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_steel={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_tantalum={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_tin={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_titanium={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_tungsten={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_uranium={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_zinc={hasPattern=false,label="",recipe={}},
 teslathingies_jj_lump_zirconium={hasPattern=false,label="",recipe={}},
 teslathingies_jj_misc_farmer={hasPattern=true,label="Farmer Machine",recipe={basemetals_jj_iron_gear={need=3,tag=""},minecraft_jj_diamond_hoe={need=1,tag=""},minecraft_jj_planks={need=2,tag=""},teslacorelib_jj_base_addon={need=2,tag=""},teslacorelib_jj_machine_case={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=3,tag=""}}},
 teslathingies_jj_multi_tank={hasPattern=true,label="Multi Tank (WIP)",recipe={minecraft_jj_bucket={need=4,tag=""},minecraft_jj_glass={need=4,tag=""},teslacorelib_jj_machine_case={need=1,tag=""}}},
 teslathingies_jj_powder_maker={hasPattern=true,label="Powder Maker",recipe={minecraft_jj_piston={need=2,tag=""},minecraft_jj_stone={need=6,tag=""},teslacorelib_jj_machine_case={need=1,tag=""}}},
 teslathingies_jj_powered_kiln={hasPattern=true,label="Powered Kiln",recipe={minecraft_jj_flint_and_steel={need=1,tag=""},minecraft_jj_furnace={need=3,tag=""},minecraft_jj_stone={need=4,tag=""},teslacorelib_jj_machine_case={need=1,tag=""}}},
 teslathingies_jj_pump={hasPattern=false,label="",recipe={basemetals_jj_gold_gear={need=1,tag=""},minecraft_jj_bucket={need=1,tag=""},minecraft_jj_glass={need=4,tag=""},minecraft_jj_piston={need=2,tag=""},teslacorelib_jj_machine_case={need=1,tag=""}}},
 teslathingies_jj_sewer={hasPattern=false,label="",recipe={minecraft_jj_iron_bars={need=3,tag=""},minecraft_jj_planks={need=4,tag=""},teslacorelib_jj_gear_stone={need=1,tag=""},teslacorelib_jj_machine_case={need=1,tag=""}}},
 teslathingies_jj_simple_tank={hasPattern=true,label="Simple Tank (WIP)",recipe={minecraft_jj_bucket={need=1,tag=""},minecraft_jj_glass={need=7,tag=""},teslacorelib_jj_machine_case={need=1,tag=""}}},
 teslathingies_jj_tesla_plant_seeds={hasPattern=false,label="",recipe={}},
 teslathingies_jj_teslified_obsidian={hasPattern=false,label="",recipe={}},
 teslathingies_jj_tf_qq_liquidxp_block={hasPattern=false,label="",recipe={}},
 teslathingies_jj_tf_qq_molten_tesla_block={hasPattern=false,label="",recipe={}},
 teslathingies_jj_tf_qq_sewage_block={hasPattern=false,label="",recipe={}},
 teslathingies_jj_tree_farm={hasPattern=false,label="",recipe={minecraft_jj_planks={need=4,tag=""},minecraft_jj_sapling={need=3,tag=""},teslacorelib_jj_gear_stone={need=1,tag=""},teslacorelib_jj_machine_case={need=1,tag=""}}},
 teslathingies_jj_void_storage_addon={hasPattern=true,label="Void Storage Addon",recipe={basemetals_jj_iron_gear={need=1,tag=""},minecraft_jj_lava_bucket={need=1,tag=""},minecraft_jj_obsidian={need=6,tag=""},teslacorelib_jj_base_addon={need=1,tag=""},thermalfoundation_jj_material_jj_24={need=1,tag=""}}},
 teslathingies_jj_xp_tank_addon={hasPattern=true,label="Player XP Addon",recipe={basemetals_jj_gold_gear={need=1,tag=""},minecraft_jj_ender_pearl={need=1,tag=""},minecraft_jj_experience_bottle={need=2,tag=""},teslacorelib_jj_base_addon={need=1,tag=""},thermalfoundation_jj_material_jj_25={need=1,tag=""}}}
 }